website/content/docs/discovery/dns.mdx

Document `.addr` DNS subdomain that can be returned in SRV response records.
[Preview link](https://consul-mnpojbwau-hashicorp.vercel.app/docs/discovery/dns#srv-response-for-hosts-in-the-addr-subdomain)

docs: Document .addr DNS domain in SRV responses

---

agent/txn_endpoint.go
api/health.go

Hi guys,
Add GRPC to HealthCheckDefinition because it missing, and it is required for consul-esm to handle GRPC health-checks.
I have no idea if there is anything else to add to this PR. If there is please tell me.

Add GRPC to HealthCheckDefinition

---

version/version.go

As @banks mentioned in Slack, when running a server by building from `main`, you'll see warnings like:
```
agent.server.connect: error enabling virtual IPs: error="can't allocate Virtual IPs for terminating gateways until all servers >= 1.11.2"
``` 
More generally, this version on `main` should reflect whatever is the "latest" version of Consul. We should do this as part of our release. I've made a note of it in our docs until we sort out automating it.

Update version to use 1.11.2 prefix

---

website/content/docs/connect/config-entries/service-resolver.mdx

Fix typo in documentation for service resolver's RingHashConfig. The correct child parameters are `MinimumRingSize` and `MaximumRingSize`.

docs: Fix typo in service resolver's RingHashConfig

---

website/content/commands/config/write.mdx

Remove statement about service-defaults and proxy-defaults being the
only supported configuration entry types. Update the sentence to point to the configuration entry documentation for a list of supported types.

docs: Link to supported config kinds in `config write`

---

website/pages/docs/discovery/dns.mdx

Manual backport of #12056 to 1.8.x.

[1.8.x] Backport docs for SRV .addr domain 

---

website/content/docs/connect/config-entries/service-resolver.mdx

Manual backport of #12122 to 1.10.x.

[1.10.x] Backport docs for RingHashConfig typo

---

website/content/docs/connect/config-entries/service-resolver.mdx

Manual backport of #12122 to 1.9.x.

[1.9.x] Backport docs for RingHashConfig typo

---

.golangci.yml

This is a neat hack forbigido provides: https://github.com/ashanbrown/forbidigo#usage https://github.com/ashanbrown/forbidigo/pull/11
Better UX to provide a short explanation why we forbid these

ci: Add explanation in forbidigo

---

.changelog/12126.txt
sdk/testutil/server.go

- Adding a 'Partition' and 'RetryJoin' command allows test cases where one would like to spin up a Consul Agent in a non-default partition to test use-cases that are common when enabling Admin Partition on Kubernetes.
Question: Is the ability for a client to run as a non-server Agent intentionally unsupported? If so, the `retry_join` flag does enable one to do so.
Closes #12118

Add support for 'Partition' and 'RetryJoin' to sdk/TestServerConfig

---

website/content/docs/nia/cli/index.mdx

Related: hashicorp/consul-terraform-sync#617

Deprecate port CLI option for CTS and updated example usage #12154

---

.changelog/12176.txt
.release/linux/package/usr/lib/systemd/system/consul.service

Folks should be able to start/stop the service for linux packages even when the [optional] EnvironmentFile does not exist. This PR makes that possible- big thanks to @blake for this one! 
[Relevant snippet](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=) from the docs:
> The argument passed should be an absolute filename or wildcard expression, optionally prefixed with "-", which indicates that if the file does not exist, it will not be read and no error or warning message is logged. This option may be specified more than once in which case all specified files are read. If the empty string is assigned to this option, the list of file to read is reset, all prior assignments have no effect.
Relates to https://github.com/hashicorp/consul/issues/11943

Make systemd EnvironmentFile optional

---

api/acl.go
api/agent.go
api/catalog.go
api/config_entry.go
api/coordinate.go
api/discovery_chain.go

When r.toHTTP is called, http.Request is built with the path already escaped. This removes all calls to url.PathEscape that would have led to double-escaped URLs.
```
c.doRequest(r)
// calls
req, err := r.toHTTP()
^^^
// calls
req, err := http.NewRequest(r.method, r.url.RequestURI(), r.body)
^^^
```
It turns out that `(*URL).RequestURI` actually [escapes the path](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/net/url/url.go;l=1139).
This means that we are double-escaping URLs in the `api` package, but have not caught any errors until now because 1) we never published new versions of `api`; 2) we haven't run tests in module `consul` which depended on our updated `api` until https://github.com/hashicorp/consul/pull/12103
```go
// api/kv_test.go
func TestAPI_Demo(t *testing.T) …
```

api: Remove incorrect usage of url.PathEscape

---

.changelog/12174.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/envoy_versioning.go
agent/xds/envoy_versioning_test.go
agent/xds/testing.go

Backport of https://github.com/hashicorp/consul/pull/12174 to `1.10.x`

[1.10.x] xds: fix for delta xDS reconnect bug in LDS/CDS

---

.github/workflows/build.yml

This adds the "netcgo" tag to darwin builds to resolve a longstanding issue with DNS on mac binaries.

RDX-205 add netcgo tag for darwin builds

---

website/content/docs/k8s/service-sync.mdx

Clarify to only enable service sync on non-mesh Service instances.

docs: Service Sync clarify requirements when using Service Mesh

---

.circleci/config.yml
.circleci/scripts/rerun-fails-report.sh

backport of https://github.com/hashicorp/consul/pull/11059 to `1.10.x`

[1.10.x] Rerun go-test and go-test-32bits tests up to 3 times before failing

---

website/content/docs/connect/config-entries/ingress-gateway.mdx

Document the new TLS cipher and version parameters that were added to ingress gateways in #11576.

docs: Add ingress TLS cipher and version documentation

---

website/content/docs/agent/telemetry.mdx

The raw metrics information was added previously. This PR adds a "Bolt DB Performance" section to the "Key Metrics" part of the page. It goes over why you should monitor bolt db performance, potential issues with syncing the freelist to disk and links out to the options docs for how to disable freelist syncing.

Update telemetry page with advice for monitoring boltdb performance

---

website/content/commands/join.mdx

Rephrase the comment about specifying multiple join addresses to clarify that it pertains to joining a single cluster by attempting to contact one or more nodes.

docs: Clarify docs for providing multiple join addresses

---

agent/consul/acl.go
agent/consul/acl_client.go
agent/consul/acl_server.go
agent/consul/acl_test.go
agent/consul/client.go
agent/consul/replication.go
agent/consul/server.go

Related to #11337 
This is a small step to isolate the functionality that is used for the `ACLResolver` from the large Client and Server structs. This follows the pattern and naming we use for all new RPC endpoints.

acl: extract a backend type for the ACLResolverBackend

---

website/pages/commands/join.mdx

Manual backport of #12199 to 1.8.x.

[1.8.x] Backport removal of multi-cluster comment in `consul join`

---

agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/txn_endpoint_test.go
agent/structs/structs.go
agent/txn_endpoint_test.go

This is being done to make space for fixing #9449.  Best viewed by individual commit. There is more detail in the commit messages.
The current implementation of `blockingQueries` is difficult to read, and difficult to modify, for a few reasons.
1. the `goto`. While it is safe to use `goto` in Go, most readers will not be used to following logic that uses goto. A for loop is not only much easier to reason about, it removes the need to pre-define a bunch of variables at the top of the function. Sometimes a `goto` is the right solution for complicated logic, but I believe this refactor shows it is not necessary here, and that a for loop reads better.
2. there were many long inline block comments. These comments are almost always better as godoc comments on functions (even if that function is …

rpc: make blockingQuery easier to read

---

ui/packages/consul-ui/app/helpers/class-map.js
ui/packages/consul-ui/app/helpers/class-map.mdx

`{{class-map}}` is used to easily add a list of classes, conditionally, and
have them all formatted nicely ready to be printed in a DOM `class` attribute.
For ease, as well as using entries, you can also just provide a simple string
without the boolean and that class will always be added.
@didoo this might help you folks out also. If you ever think it will, lemme know and we can extract and publish elsewhere.
[Rendered Docs](https://consul-ui-staging-em57io68m-hashicorp.vercel.app/ui/docs/helpers/class-map)

ui: class-map helper

---

ui/packages/consul-ui/app/modifiers/css-prop.js
ui/packages/consul-ui/app/modifiers/css-prop.mdx

Get the value for a single specific CSS Property from the modified element.
`returns` can be specified either as a second parameter or an option.
[Rendered Docs](https://consul-ui-staging-2nldyoc5c-hashicorp.vercel.app/ui/docs/modifiers/css-prop)

ui: css-prop modifier

---

website/content/docs/ecs/configuration-reference.mdx
website/content/docs/ecs/manual/install.mdx
website/data/docs-nav-data.json

This adds a Configuration Reference page for ECS. This is generated from our JSON Schema (see https://github.com/hashicorp/consul-ecs/pull/58)

docs: Config reference for ECS

---

agent/consul/leader_connect_ca.go
agent/structs/connect_ca.go
testrpc/wait.go

Branched from #11661, this change is related to #11598, and #11159.
See the previous PR and the linked issues for context. Full details about the change in the commit messages.
Short version: we should not be calling `Provider.ActiveRoot` in the secondary. Instead we should get the RootCert from the stored `primaryRoots`. This PR makes that change.

ca: remove second call to Provider.ActiveRoot

---

website/pages/commands/config/write.mdx

Manual backport of #12124 to 1.8.x.

[1.8.x] Backport update to supported config kinds in `config write`

---

agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

Branched from #11663
This is the next step to support #11598.  We will need to return a full chain from `GenerateRoot`, so this PR starts adding support by changing the interface to return a struct, and removing `ActiveRoot`, which is no only ever called immediately after `GenerateRoot`.
I tested the AWS provider locally because those tests to do run in CI.

ca: remove Provider.ActiveRoot, return the root from Provider.GenerateRoot

---

.changelog/11918.txt
agent/config/builder.go
agent/config/builder_test.go
agent/consul/autopilot_test.go
agent/consul/client.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/server.go
agent/consul/server_test.go
agent/consul/system_metadata_test.go
command/snapshot/save/snapshot_save.go
command/snapshot/save/snapshot_save_test.go

Backports #11796 and #11918 to 1.10.x
Conflicts were mostly in tests

[1.10.x] Backport testing cleanup and small bug fixes

---

.changelog/11918.txt
agent/config/builder.go
agent/config/builder_test.go
agent/consul/autopilot_test.go
agent/consul/client.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/server.go
agent/consul/server_test.go
agent/consul/system_metadata_test.go
command/snapshot/save/snapshot_save.go
command/snapshot/save/snapshot_save_test.go

Backports #11796 and #11918 to 1.9.x
Conflicts were mostly in tests

[1.9.x] Backport testing cleanup and small bug fixes

---

website/content/docs/enterprise/network-segments.mdx

This PR fixes a confusing to read sentence in the Enterprise network segments page.
🧵 [Slack thread](https://hashicorp.slack.com/archives/C011HP57U0Y/p1643320798042500)

fixing a confusing sentence in network segments page

---

agent/event_endpoint.go
agent/ui_endpoint.go

Hi, I noticed that #12103 and #11957 did not contain changes to consul/ui_endpoint.go, I changed that endpoint.

URL-encode/decode resource names for HTTP API part 4

---

agent/consul/acl.go
agent/consul/acl_client.go
agent/consul/acl_endpoint.go
agent/consul/acl_server.go
agent/consul/acl_test.go
agent/consul/acl_token_exp.go
agent/consul/client.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/leader.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/server.go
agent/consul/server_serf.go

This is the first step in #11690, best viewed by individual commit
* Embed `ACLResolver` in `Client` and `Server`
* remove the methods off of `Client` and `Server`, and move one to `ACLResolver`

acl: remove some of the duplicate resolve token methods

---

.changelog/12080.txt
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/state/store_integration_test.go
agent/consul/stream/event.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/event_test.go
agent/consul/stream/subscription.go
agent/consul/stream/subscription_test.go
agent/rpc/subscribe/subscribe.go
agent/rpc/subscribe/subscribe_test.go
proto/pbsubscribe/subscribe.pb.go
proto/pbsubscribe/subscribe.proto

Backports the streaming performance improvements from #12080 to 1.10.x. It more or less applied cleanly apart from the lack of the `Partition` field.

streaming: split event buffer by key (backport #12080 to 1.10.x)

---

agent/acl_test.go
agent/consul/acl.go
agent/consul/acl_server.go
agent/consul/acl_test.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go

Branched from #12166,  continues the work described in #11690
This change allows us to remove one of the last remaining duplicate resolve token methods (`Server.ResolveToken`).
With this change we are down to only 2, where the second one also handles setting the default EnterpriseMeta from the token.

acl: rename ResolveTokenToIdentityAndAuthorizer to ResolveToken

---

ui/packages/consul-ui/app/modifiers/on-outside.js
ui/packages/consul-ui/app/modifiers/on-outside.mdx

`{{on-outside 'click' (fn @callback}}` works similarly to `{{on }}` but allows
you to attach handlers that is specifically not the currently modified
element.
Note: I'm aware there is an `on-click-outside` addon, but it is not in the shape I wanted (the same shape as `on`), plus we already have all the code needed for this already in our `dom` service.
[Rendered Docs](https://consul-ui-staging-m1vvynuio-hashicorp.vercel.app/ui/docs/modifiers/on-outside)
~Just realised the docs page for this one depends on `style-map` so the docs don't render without [that PR](https://github.com/hashicorp/consul/pull/12203) going in first 🤦 , will rebase and post a rendered docs link once that goes down. Or quite happy to merge this as it, the code itself doesn't depend on anything not already in main, the …

ui: on-outside modifier

---

ui/packages/consul-ui/app/helpers/style-map.js
ui/packages/consul-ui/app/helpers/style-map.mdx

`{{style-map}}` is used to easily add a list of styles, conditionally, and
have them all formatted nicely to be printed in a DOM `style` attribute.
As well as an entry-like array you can also pass an additional `unit` property
as the 3rd item in the array. This is to make it easier to do mathematical
calculations for units without having to use `(concat)`.
If any property has a value of `null` or `undefined`, that style property will
not be included in the resulting string.
Additionally for times when `style=""` CSP headers are important, an additional transpiler can be included to turn this into a modifier in the background. It's used as a helper here to match [`class-map`](https://github.com/hashicorp/consul/pull/12202), and also we aren't yet in a position where we need to do a …

ui: style-map helper

---

ui/packages/consul-ui/app/components/buttons/skin.scss
ui/packages/consul-ui/app/components/consul/external-source/index.scss
ui/packages/consul-ui/app/components/consul/intention/components.scss
ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/skin.scss
ui/packages/consul-ui/app/components/pill/index.scss
ui/packages/consul-ui/app/components/pill/layout.scss
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/styles/base/icons/base-placeholders.scss
ui/packages/consul-ui/app/styles/icons.scss

Following on from https://github.com/hashicorp/consul/pull/12209 this PR fixes up 1 problem (the sort icon) we saw with one of our old icons, and then adds a few more "themeable semantic placeholders" for our icons.
You'll see now on this [Preview Site](https://consul-ui-staging-fsceu80fl-hashicorp.vercel.app/ui/) that the sort icon mentioned in the last PR is now in the correct place.
Importantly we moved our icon sizing from `ems` + `font-size` to `rems`, which I read somewhere we should be doing, although I'm not super convinced its the best approach. We only really needed to do this in one or two places, so if I need to revert back at some point then it's not a huge deal.
Hopefully folks can see what's happening with tree-shaken/shimmable/colorable/themeable/scalable/semantically-named …

ui: Flight Icon tweaks

---

.github/workflows/build.yml
.release/linux/postremove
.release/linux/preremove

Fixes several issues with the pre/postremove scripts for both rpm and deb packages. Specifically:
For postremove:
- the postremove script now functions correctly (i.e. restarts consul after a package upgrade) on rpm-based systems (where `$1` is numeric rather than `purge` or `upgrade`)
- `systemctl daemon-reload` is called on package removal (rather than only on upgrade)
- calls `systemctl try-restart` instead of `systemctl restart`, which will only (re)start consul if it was already running when the upgrade happened.
For preremove:
- if the package is being completely uninstalled (rather than upgraded), stop consul before removing the package
Tested on CentOS 7.9 and Ubuntu 20.04, but should be applicable to all rpm and deb based distributions.

packaging: fix issues in pre/postremove scripts

---

agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

Backport of #11706
Conflicts were exclusively in tests, since `require.New(t)` was removed on main.

[1.11.x] Backport CA changes for external trusted CA

---

agent/acl_test.go
agent/consul/acl.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go

This is safer than embedding two interface because there are a number of places where we check the concrete type. If we check the concrete type on the top-level interface it will fail. So instead expose the ACLIdentity from a method.
The top-level type (`ACLResultResult`) is a struct, but in other packages we may consume it as an interface, which introduces the problem.

acl: un-embed ACLIdentity

---

.github/CONTRIBUTING.md
docs/contributing/add-a-changelog-entry.md
docs/contributing/fork-the-project.md

Adds guidance on:
- submitting a pull request
- adding a changelog entry
Reorganizes the content in ways that I think improve clarity.
You can preview the file here: 
https://github.com/hashicorp/consul/blob/45acc91c26f9fe1b9cddb489a93bf5551c8637e0/.github/CONTRIBUTING.md

Add changelog creation to contributor docs

---

agent/connect/ca/provider_vault.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

Related to #11598
This test found a bug in the secondary. We were appending the root cert to the PEM, but that cert was already appended. This was failing validation in Vault here:
https://github.com/hashicorp/vault/blob/sdk/v0.3.0/sdk/helper/certutil/types.go#L329
Previously this worked because self signed certs have the same SubjectKeyID and AuthorityKeyID. So having the same self-signed cert repeated doesn't fail that check.
However with an intermediate that is not self-signed, those values are different, and so we fail the check. A test I added in a previous commit (a4ba1f348ddbba770a876d32469fdbc981f24bfe) should show that this continues to work with self-signed root certs as well.
I traced this line back to the original PR that added support for secondaries (#4672), and I don't see …

ca: add a test that uses an intermediate CA as the primary CA

---

website/content/docs/connect/proxies/built-in.mdx
website/content/docs/connect/registration/sidecar-service.mdx

Remove incorrect sidecar port range on docs for built-in proxy.
Updates the bind_port/port fields on the built-in proxy and sidecar service registration pages to link to the `sidecar_min_port` and `sidecar_max_port` configuration options for the defined port range.
Fixes #12253

docs: Fix discrepancy with sidecar min/max port range

---

ui/packages/consul-ui/GNUmakefile
ui/packages/consul-ui/app/styles/app.scss
ui/packages/consul-ui/app/styles/debug.scss
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/lib/colocated-components/index.js
ui/packages/consul-ui/lib/startup/templates/head.html.js

We need a way to load certain CSS based on the environment you are viewing, i.e. we have debug CSS that we use for our Eng Documentation and various other DX utilities that shouldn't be compiled into our production or test builds.
Previously we would compile two entirely different CSS files (`app` and `debug`) and the load one or the other depending on which environment you were in.
This approach just empties out the debug.css file in certain environments (prod/test) which means we can just import that file from app. When in staging/development this imports the contents of debug.css (quite a bit of CSS) whereas when building for production/test this debug.css is emptied out during the build process.
There is a slight little hack in order to have this work, we import `_debug.scss` which …

ui: Change approach to loading debug.css

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/installation/configure.mdx
website/content/docs/nia/installation/requirements.mdx
website/content/docs/nia/release-notes/0-5-0.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

In 0.5 CTS deprecated:
- `task` block's `services` field configuration
- `service` block configuration
Doc changes for deprecated configs
- Add "deprecation" warning messages
- Remove / replace unnecessary references to deprecated configs
Other changes
- Aligned `services` field vs. list to field
- Fix typos where `service` block was pluralized
[link to config preview](https://consul-6ayxu6fry-hashicorp.vercel.app/docs/nia/configuration#service) (updated with latest)

docs/nia: deprecate "services" field and "service" block

---

website/content/docs/nia/api/status.mdx
website/content/docs/nia/configuration.mdx
website/content/docs/nia/installation/configure.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

Deprecate `source` and associate language. Update to `module`
Previous PR: Deprecate `source_includes_var` and `source_input`
link to [config preview](https://consul-b17c87e58-hashicorp.vercel.app/docs/nia/configuration#source) and [status api preview](https://consul-b17c87e58-hashicorp.vercel.app/docs/nia/api/status#event)

docs/nia: deprecate `source`

---

website/content/docs/k8s/connect/ingress-controllers.mdx
website/data/docs-nav-data.json

- Mention Consul API Gateway in Ingress Controllers K8s page
- Remove link to Ambassador API GW learn guide from docs

docs: mention Consul API gateway in Ingress Controllers page

---

.changelog/12267.txt
agent/connect/ca/provider_vault.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/leader_connect_ca.go

Fixes #12246
This commit makes two changes to the validation.
Previously we would call this validation in GenerateRoot, which happens
both on initialization (when a follower becomes leader), and when a
configuration is updated. We only want to do this validation during
config update so the logic was moved to the `UpdateConfiguration`
method.
Previously we would compare the config values against the actual cert.
This caused problems when the cert was created manually in Vault (not
created by Consul).  Now we compare the new config against the previous
config. Using an already created CA cert should never error now.
Adding the key bit and types to the config should only error when
the previous values were not the defaults.
This does mean that changing these values away from the defaults …

ca: change the PrivateKey type/bits validation

---

Dockerfile

This is required, as alpine:3.13 has a number of CVE's (which are all fixed in 3.15)!

Update docker image base to alpine:3.15

---

website/content/docs/enterprise/admin-partitions.mdx

This PR  updates the Admin Partitions page with the following changes.
🔍  [Preview](https://consul-8qk84206j-hashicorp.vercel.app/docs/enterprise/admin-partitions)
- Helm command now includes the helm version
- Add `$` to some code examples
- Updated Consul versions to `1.11.2`
- Added `global.name` to the client's `values.yaml` file. The client needs a unique name.
- Added comment in the client's `values.yaml` to help the reader know what steps correspond to the k8s auth method, and admin partition service IP. 
- Added link to the learn tutorial. The second one will be uncommented in a future PR.

docs: updated admin partitions instructions

---

.changelog/12236.txt
agent/xds/delta.go
agent/xds/delta_test.go

Fixes #11876
This enforces that multiple xDS mutations are not issued on the same ADS connection at once, so that we can 100% control the order that they are applied. The original code made assumptions about the way multiple in-flight mutations were applied on the Envoy side that was incorrect.

xds: allow only one outstanding delta request at a time

---

ui/packages/consul-ui/app/components/disclosure/README.mdx
ui/packages/consul-ui/app/components/disclosure/action/index.hbs
ui/packages/consul-ui/app/components/disclosure/index.hbs
ui/packages/consul-ui/app/components/state-chart/index.js
ui/packages/consul-ui/app/machines/boolean.xstate.js
ui/packages/consul-ui/app/services/state-with-charts.js

See [Rendered Docs](https://consul-ui-staging-l8deir0r3-hashicorp.vercel.app/ui/docs/components/disclosure)
I realised after building the docs that you might want to place the trigger underneath the panel (DOM-wise), so a contextual pattern would actually be better here. I'm happy to leave that to a future (soonish) PR to amend. The work that this is working towards only uses this in one place, so a quick refactor once the feature is complete won't be a huge issue. I'd rather keep going with the feature than slightly rethink things.

ui: Disclosure Component

---

ui/packages/consul-ui/app/components/menu/README.mdx
ui/packages/consul-ui/app/components/menu/action/index.hbs
ui/packages/consul-ui/app/components/menu/index.hbs
ui/packages/consul-ui/app/components/menu/item/index.hbs
ui/packages/consul-ui/app/components/menu/separator/index.hbs
ui/packages/consul-ui/app/modifiers/aria-menu.js
ui/packages/consul-ui/app/modifiers/aria-menu.mdx

New `{{aria-menu}}` modifier, slightly based on our old, and slightly crusty pre-octane [`<AriaMenu>` component](https://github.com/hashicorp/consul/blob/f020cedab29467ed630ac173a0accd3ea5747643/ui/packages/consul-ui/app/components/aria-menu/index.js), which is now deprecated and soon to be removed. The code here has not been completely re-thought, so at some point I'll probably come back and spruce it up a little more. For now its gets us as far as we need to go.
[Rendered Docs](https://consul-ui-staging-1x3l3u5ar-hashicorp.vercel.app/ui/docs/modifiers/aria-menu)

ui: aria-menu modifier

---

.changelog/12277.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

Fixes #12258
The test was able to reproduce the panic, and the second commit fixes the test. There are other ways we could fix this, but this one seemed like the most obvious. Open to other suggestions.
TODO:

catalog: initialize the refs map to prevent a nil panic

---

README.md
website/public/img/logo.svg

The README header introduced in #12230 doesn't look good in Github dark mode. The black text in the Consul logo is not readable.
This PR alters the README header to look good in light or dark mode. [README can be viewed here](https://github.com/hashicorp/consul/blob/readme-logo-dark-mode/README.md).
**Light mode rendered in Github**
**Dark mode rendered in Github**

Make README header look good in dark mode

---

.changelog/12195.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/xds_protocol_helpers_test.go

Previously the Delta xDS protocol could get into a tight loop where:
1. Consul sends xDS resources it believes are valid
2. Envoy rejects them with a NACK
3. Consul re-generates and sends the resources
4. Loop back to step 2
This tight loop leads to massive amounts of error logs in both Envoy and
Consul logs.
This commit updates the delta xDS loop to wait for new requests or
snapshots after a NACK is received from Envoy. By skipping to the top of
the for loop we avoid re-sending the resources that Envoy has already
rejected.

Prevent xDS tight loop on cfg errors

---

.changelog/12315.txt
ui/packages/consul-ui/app/services/repository.js

The majority of this PR is just `prettier` (sorry!), the important line is line 218.
https://github.com/hashicorp/consul/compare/ui/scratch/more-ember-data-fun#diff-e4c456fea821208520a230bc235b8e5c6692e338129127b7feabe472ed481b6fR218
- Consul UI uses blocking queries for its live updates this means that we are mostly kept completely up to date with the single source of truth on the backend.
- We use `ember-data` which additionally caches its own version of truth on the frontend, which is separate from the backend's source of truth (something I've never been onboard with). Therefore the source of truth is no longer 'single'.
- In order to keep ember-data's version of truth in sync with the actual truth on the backend we have to perform various cleanup and syncing tasks by either …

ui: Stop ember-data overwriting SyncTimes

---

.changelog/12317.txt
ui/packages/consul-ui/app/routes/dc/services/show/topology.js

See title.
Manually checking this involves clicking one of the [x] icons in the topology view. You'll see the `exact` HTTP request now includes the partition data. Please note the partition data will be sent whether in a partition supporting version of Consul or not, where partitions aren't supported `default` will be used, this is expected.
The preview site will not show you this information as yet as the preview site uses an in-browser HTTP server so Network traffic isn't 100% visible. When testing locally with `make start` our mock data is automatically served from a little node based HTTP server so you _will_ be able to see the Network requests there (you could also set this up via Consul for realz and just use `make start-consul`).

ui: Make sure saving intentions from topology includes the partition

---

ui/packages/consul-ui/app/components/disclosure-menu/README.mdx
ui/packages/consul-ui/app/components/disclosure-menu/action/index.hbs
ui/packages/consul-ui/app/components/disclosure-menu/index.hbs
ui/packages/consul-ui/app/components/disclosure-menu/index.scss
ui/packages/consul-ui/app/components/disclosure-menu/menu/index.hbs
ui/packages/consul-ui/app/components/disclosure/README.mdx
ui/packages/consul-ui/app/components/disclosure/action/index.hbs
ui/packages/consul-ui/app/components/disclosure/details/index.hbs
ui/packages/consul-ui/app/components/disclosure/index.hbs
ui/packages/consul-ui/app/components/disclosure/index.js
ui/packages/consul-ui/app/styles/components.scss

As I was [PRing our Disclosure Component](https://github.com/hashicorp/consul/pull/12263) I noticed that it wasn't quite ideal for what I wanted, I also realized that it would be better to fix up now rather than later:
> I realised after building the docs that you might want to place the trigger underneath the panel (DOM-wise), so a contextual pattern would actually be better here. I'm happy to leave that to a future (soonish) PR to amend.
[Rendered Docs](https://consul-ui-staging-ki6px026h-hashicorp.vercel.app/ui/docs/components/disclosure)
The changes here are mainly just moving from a slot based pattern to a contextual component based pattern, advantages to this/reasons for this are illustrated in the documentation above.
Additionally I've added the next piece of the puzzle here which …

ui: Disclosure Component amends plus DisclosureMenu Component

---

GNUmakefile

This restores the prior behavior of make dev and ensures that tests
using the sdk package (like the api package) will correctly locate the
consul binary under test.

ensure make dev target puts the newly constructed binary onto the PATH

---

.changelog/12308.txt
acl/errors.go
acl/errors_oss.go
acl/errors_test.go
agent/acl.go
agent/agent_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/structs/structs_oss.go

Port of the structured error work in consul-enterprise.
This is the OSS side of #12239

Refactor to make ACL errors more structured.

---

.changelog/12324.txt
agent/local/state.go
agent/local/state_test.go

The race detector noticed this initially in `TestAgentConfigWatcherSidecarProxy` but it is not restricted to just tests.
The two main changes here were:
- ensure that before we mutate the internal `agent/local` representation of a Service (for tags or VIPs) we clone those fields
- ensure that there's no function argument joint ownership between the caller of a function and the local state when calling `AddService`, `AddCheck`, and related using `copystructure` for now.
```
Failed
=== RUN   TestAgentConfigWatcherSidecarProxy
[INFO] freeport: detected ephemeral port range of [32768, 60999]
[INFO] freeport: reducing max blocks from 30 to 15 to avoid the ephemeral port range
==================
WARNING: DATA RACE
Write at 0x00c000d7e958 by goroutine 130: …
```

local: fixes a data race in anti-entropy sync

---

.changelog/12324.txt
agent/local/state.go
agent/local/state_test.go

[1.11.x] local: fixes a data race in anti-entropy sync

---

.changelog/12325.txt
api/go.sum
go.mod
go.sum
sdk/go.mod
sdk/go.sum

This includes closing some leadership transfer gaps and adding snapshot
restore progress logging.
Things relevant to consul:
* **v1.3.5**
* Snapshot restore progress in https://github.com/hashicorp/raft/pull/490
* **v1.3.4**
* fixed a race condition in leadership transfer that could result in reelection of the current leader https://github.com/hashicorp/raft/pull/487

raft: update to v1.3.5

---

.changelog/12321.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go

This will both save on unnecessary raft operations as well as
unnecessarily incrementing the raft modify index of config entries
subject to no-op updates.

server: conditionally avoid writing a config entry to raft if it was already the same

---

website/content/docs/nia/api/status.mdx
website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/configuration.mdx

We are deprecating some fields in Task Status API and replacing them with a new Get Task API
Changes (details in commit msg):
- new docs for Get Task API (also prepares for Create Task API)
- deprecate fields in Task Status API
- update APIs to align on `:task_name` in request parameter (open to feedback)
- misc fixes
[get status api preview link](https://consul-7qhowv9sm-hashicorp.vercel.app/docs/nia/api/tasks#get-task)

docs/nia - Get Task API docs & Task Status API deprecations

---

.changelog/12321.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go

[1.10.x] server: conditionally avoid writing a config entry to raft if it was already the same

---

.circleci/config.yml

Turns out `stash pop` [attempts a merge](https://app.circleci.com/pipelines/github/hashicorp/consul/26874/workflows/17c33cb9-4e41-43f8-8822-0c590a1c47c9/jobs/573010)!
Instead of:
1. Stash `bindata_assetfs.go`
2. Checkout `ci/main-assetfs-build`
3. Merge `main`
4. Stash pop `bindata_assetfs.go`
5. Conflict!
We instead:
1. Reset `ci/main-assetfs-build` to `main`
2. Commit `bindata_assetfs.go`
3. Force push

ci: Fix merge conflicts cleanly

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/task.mdx

CTS delete task command is now asynchronous, so updating docs to reflect
this new behavior.
https://consul-i5h6x6w1g-hashicorp.vercel.app/docs/nia/api/tasks#delete-task
https://consul-i5h6x6w1g-hashicorp.vercel.app/docs/nia/cli/task#task-delete

docs/nia: Update task delete with async behavior

---

.github/workflows/stale.yml

I noticed that our stale action is broken. Apparently, the `exempt-pr-labels` key for the stale action needs to be a string and not an array type.

ci: fix stalebot config

---

agent/consul/gateway_locator.go
agent/consul/gateway_locator_test.go
agent/consul/rpc.go

Clarify the rules for implementing a query function passed to `Server.blockingQuery`. Related to #12109 and #12110
The new interfaces here are to follow the Go convention of accepting a small interface that documents the methods used by the function.  They help document the function by being explicit about which methods are used.
In the future we can probably removes `structs.QueryOptionsCompat` and `structs.QueryMetaCompat` since those are now only used by a few parse functions in `http.go`. By following the pattern used here we could replace that usage as well.

rpc: improve docs for blockingQuery

---

build-support/functions/20-build.sh

I was trying to run `make proto` and discovered this little curfuffle. Apparently this snuck in with a recent change to our build plumbing.

Fix build script

---

.github/workflows/build.yml
.release/ci.hcl
.release/linux/preremove
.release/security-scan.hcl
Dockerfile

This is a backport of a number of either failed or unapplied changes relating to CRT and Docker. In particular, these are the PRs that contain the original changes that have already been merged to `main`:
- #12097 - The bulk of changes to fix the production Dockerfile and become compatible with CRT
- #12276 - Update Dockerfile to use `alpine:3.15`
- #11956 - Enable security scanner for Consul binaries and containers
- #12275 - Update security scanner config to work with not-yet-deprecated keys
- #12281 - Temporarily turn off `alpine_secdb` container scanning and secret scanning
- #12147 -  Fix issues in Linux `preremove`/`postremove` package scripts
See example runs of the build workflow [here](https://github.com/hashicorp/consul/actions/workflows/build.yml?query=branch%3Aeculver%2F1.9%2Fd …

[1.9.x] Backport CRT-related fixes

---

.github/workflows/build.yml
.release/ci.hcl
.release/linux/preremove
.release/security-scan.hcl
Dockerfile

This is a backport of a number of either failed or unapplied changes relating to CRT and Docker. In particular, these are the PRs that contain the original changes that have already been merged to `main`:
- #12097 - The bulk of changes to fix the production Dockerfile and become compatible with CRT
- #12276 - Update Dockerfile to use `alpine:3.15`
- #11956 - Enable security scanner for Consul binaries and containers
- #12275 - Update security scanner config to work with not-yet-deprecated keys
- #12281 - Temporarily turn off `alpine_secdb` container scanning and secret scanning
- #12147 -  Fix issues in Linux `preremove`/`postremove` package scripts
See example runs of the build workflow [here](https://github.com/hashicorp/consul/actions/workflows/build.yml?query=branch%3Aeculver%2F1.10%2F …

[1.10.x] Backport CRT-related fixes

---

.github/workflows/build.yml
.release/ci.hcl
.release/linux/preremove
.release/security-scan.hcl
Dockerfile

This is a backport of a number of either failed or unapplied changes relating to CRT and Docker. In particular, these are the PRs that contain the original changes that have already been merged to `main`:
- #12097 - The bulk of changes to fix the production Dockerfile and become compatible with CRT
- #12276 - Update Dockerfile to use `alpine:3.15`
- #11956 - Enable security scanner for Consul binaries and containers
- #12275 - Update security scanner config to work with not-yet-deprecated keys
- #12281 - Temporarily turn off `alpine_secdb` container scanning and secret scanning
- #12147 -  Fix issues in Linux `preremove`/`postremove` package scripts
See example runs of the build workflow [here](https://github.com/hashicorp/consul/actions/workflows/build.yml?query=branch%3Aeculver%2F1.11%2F …

[1.11.x] Backport CRT-related fixes

---

.changelog/12098.txt
agent/consul/state/catalog.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go
ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
ui/packages/consul-ui/app/models/topology.js

This is a draft implementation for #12096. Misses tests and probably cleanups of the JS code :)

Support for connect native services in topology view.

---

.changelog/12370.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go

Parse the value of the datacenter from the create/delete requests for AuthMethods and BindingRules so that they can be created in and deleted from the datacenters specified in the request.

Parse datacenter from request

---

.changelog/12376.txt
.changelog/changelog.tmpl

Prior to this change, we excluded entries with the `release-note:enhancement` heading despite it being a valid entry type. This adds it per the suggestion in [the template that ships with go-changelog](https://github.com/hashicorp/go-changelog/blob/main/cmd/changelog-build/changelog.tmpl#L30-L36).
We'll still need to go backport the 12 entries that have been excluded in their associated release. Future releases will do the right thing by including those that are part of the release.

ci: combine 'enhancement' entry type with 'improvement'

---

CHANGELOG.md

As it relates to #12376, this adds the missing `release-note:enhancement` entries to their appropriate place in the CHANGELOG.md.
Here's the list of entries and their respective releases where they should appear:
```
10504 - 1.11.0
10566 - 1.11.0
10598 - 1.11.0
11335 - 1.11.2
11376 - 1.10.8, 1.11.2
11569 - 1.11.0
11801 - 1.11.0
12080 - 1.11.3
12176 - 1.11.3
```

Add missing enhancement entries to appropriate spot in CHANGELOG

---

api/namespace.go

Namespaces method godoc has same sentence as Operator method.
Presumably a cut-n-paste error. Fix that.

fix godoc comment for Namespaces client method

---

.changelog/12316.txt
ui/packages/consul-ui/app/serializers/nspace.js

~Currently draft: Awaiting confirmation of how guaranteed it is that some properties here are always filled out~
Answer: There's no guarantee, I removed a commit off the end of this due to this.
Previous to this PR we were only adding a 'fake' template property when receiving a 'list type' response, but we also need to do this when receiving a 'single type' response also.
This PR adds it everywhere it needs to be.

ui: Fixup displaying a Nspace default policy when expanding the preview pane

---

.changelog/12358.txt
ui/packages/consul-ui/app/components/consul/instance-checks/index.hbs

Fixes https://github.com/hashicorp/consul/issues/12351
A new helper added for 1.12 work unfortunately ended up in our 1.11 branch. This removes the helper and replaces it with equivalent code.

ui: Remove class-map reference from 1.11

---

agent/consul/config_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/rpc.go

Otherwise when the query times out we might incorrectly send a value for the reply, when we should send an empty reply.
I went through all the changes in #12110. These were the only two places that seemed to be a problem. The rest appear to correctly set the reply value before returning `errNotFound`.
Thanks to @rboyer and @kisunji for finding this.

rpc: set response to nil when not found

---

.changelog/12385.txt
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-http-upstream.envoy-1-20-x.golden

This changes the logic in `getAndModifyUpstreamConfigForListener` to respect the discovery chain's protocol even in the `IsDefault() == true` case. As seen in #11570 we currently end up with a tcp listener in this case, which breaks some Envoy features such as outlier detection and retry policy.
Fixes #11570.

xds: respect chain protocol on default discovery chain

---

agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-http-upstream.envoy-1-18-x.golden
agent/xds/testdata/listeners/transparent-proxy-http-upstream.v2compat.envoy-1-16-x.golden

Backporting some test changes to fix the 1.10.x branch. Slight differences from #12395 because of partitions being added in 1.11.

Backport 1.10.x: tproxy http upstream fix

---

agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-http-upstream.envoy-1-20-x.golden

Backporting some test changes to fix the 1.11.x branch

Backport 1.11.x: tproxy http upstream fix

---

website/content/docs/connect/observability/ui-visualization.mdx

Manual backport of #11980 to 1.11.x. This change failed the initial cherry pick.

[1.11.x] docs: Backport add JSON examples to UI visualization

---

website/content/docs/dynamic-app-config/watches.mdx

* Adds HCL configuration examples to Consul watch configs.
* Updates example output for several watch types.

docs: Add HCL examples to watch configs

---

website/content/docs/k8s/installation/deployment-configurations/consul-enterprise.mdx
website/content/docs/k8s/installation/vault/enterprise-license.mdx
website/data/docs-nav-data.json

Documentation for configuring Enterprise License in Vault.  Related to https://github.com/hashicorp/consul-k8s/pull/1032
The process is effectively the same as configuring the gossip encryption.  I created a similar page and added it to the nav. At some point if these steps start to look the same for each page, we could think about how we combine them...but at the moment, I'm not sure the best way forward.

Adding documentation to store Enterprise License in Vault

---

.changelog/12307.txt
agent/consul/config_replication.go
agent/consul/config_replication_test.go

There are some cross-config-entry relationships that are enforced during
"graph validation" at persistence time that are required to be
maintained. This means that config entries may form a digraph at times.
Config entry replication proceeds in a particular sorted order by kind
and name.
Occasionally there are some fixups to these digraphs that end up
replicating in the wrong order and replicating the leaves
(ingress-gateway) before the roots (service-defaults) leading to
replication halting due to a graph validation error related to things
like mismatched service protocol requirements.
This PR changes replication to give each computed change (upsert/delete)
a fair shot at being applied before deciding to terminate that round of
replication in error. In the case where we've simply tried …

server: partly fix config entry replication issue that prevents replication in some circumstances

---

website/content/docs/k8s/connect/index.mdx

Add docs for the multiport workaround in K8s: https://github.com/hashicorp/consul-k8s/pull/1012
Is the position of the doc ok as is or should it be a standalone page?
Currently it's been added to /docs/k8s/connect

add multiport docs for K8s

---

.changelog/12321.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go

[1.9.x] server: conditionally avoid writing a config entry to raft if it was already the same

---

.changelog/12307.txt
agent/consul/config_replication.go
agent/consul/config_replication_test.go

[1.9.x] server: partly fix config entry replication issue that prevents replication in some circumstances

---

website/content/docs/connect/config-entries/service-router.mdx

This PRs adds an example configuration codeblock for retry logic with Consul. There is currently no example in the documentation. 
Discuss [example](https://discuss.hashicorp.com/t/how-to-setup-retry-policy-for-e-w-traffic-in-services-sidecars/36170/6)

docs: added example for service-router retry

---

.github/workflows/build.yml

This has been abstracted into the github action `actions-docker-build`: https://github.com/hashicorp/actions-docker-build/pull/8. 
Link to pipeline that ran for the second commit to this branch: https://github.com/hashicorp/consul/actions/runs/1862910790

Remove setup-qemu step from Docker build job

---

.changelog/12444.txt
agent/catalog_endpoint_test.go
agent/checks/alias.go
agent/checks/alias_test.go
agent/consul/catalog_endpoint.go
agent/consul/catalog_endpoint_test.go
agent/consul/leader.go
agent/consul/leader_test.go
agent/consul/merge.go
agent/consul/merge_test.go
agent/consul/prepared_query_endpoint.go
agent/consul/server_oss.go
agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_oss.go
agent/consul/state/catalog_test.go
agent/consul/util.go
agent/structs/structs.go
agent/structs/structs_test.go
command/rtt/rtt.go
command/rtt/rtt_test.go

Many places in consul already treated node names case insensitively.
The state store indexes already do it, but there are a few places that
did a direct byte comparison which have now been corrected.
One place of particular consideration is ensureCheckIfNodeMatches
which is executed during snapshot restore (among other places). If a
node check used a slightly different casing than the casing of the node
during register then the snapshot restore here would deterministically
fail. This has been fixed.
Primary approach:
git grep -i "node.*[!=]=.*node" -- ':!*_test.go' ':!docs'
git grep -i '\[[^]]*member[^]]*\]
git grep -i '\[[^]]*\(member\|name\|node\)[^]]*\]' -- ':!*_test.go' ':!website' ':!ui' ':!agent/proxycfg/testing.go:' ':!*.md'

catalog: compare node names case insensitively in more places

---

.changelog/12433.txt
.circleci/config.yml
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

This updates our Envoy integration test matrix to include 1.20.2. The only notable change that was needed was to match against the Envoy version string which is:
```
4aaf9593152c6996b9da384c8918e9ad4f0abd4d/1.20.2-dev/Clean/RELEASE/BoringSSL
```
Note the `-dev` suffix. 
This little version issue causes all the tests that use the `assert_envoy_version` helper to fail. To work around it, I just temporarily re-write the `ENVOY_VERSION` variable to include the suffix.
All other integration tests passed. 
FUN FACT: The latest releases for Envoy 1.19 and 1.18 also have this `-dev` suffix that we'll need to deal with as well.

[1.11.x] Add support for Envoy 1.20.2

---

agent/consul/leader_test.go

```
--- FAIL: TestLeader_FailedMember (0.63s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 20378 [running]:
testing.tRunner.func1.2({0x1ed1bc0, 0xc037bb4d08})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x1ed1bc0, 0xc037bb4d08})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/consul/sdk/testutil/retry.run.func2.1()
/home/circleci/project/sdk/testutil/retry/retry.go:145 +0x45
panic({0x1ed1bc0, 0xc037bb4d08})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/consul/agent/consul.TestLeader_FailedMember.func3( …
```

fix flaky test panic

---

.changelog/12316.txt
ui/packages/consul-ui/app/serializers/nspace.js

See https://github.com/hashicorp/consul/pull/12316, manually cherry picked onto 1.10.x,
no-changelog label added as our change log checker doesn't work if the base branch is not `main`, it does have a changelog

ui: [Backport 1.10.x] Fixup displaying a Nspace default policy when expanding the preview pane

---

ui/packages/consul-nspaces/app/components/consul/nspace/selector/index.hbs
ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs
ui/packages/consul-ui/app/components/disclosure-menu/README.mdx
ui/packages/consul-ui/app/components/disclosure-menu/index.hbs
ui/packages/consul-ui/app/components/disclosure-menu/index.scss
ui/packages/consul-ui/app/components/disclosure-menu/menu/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
ui/packages/consul-ui/app/components/menu/index.hbs

This PR is a follow on from https://github.com/hashicorp/consul/pull/12404 (note the base branch here)
[Preview Site](https://consul-ui-staging-p644eh34q-hashicorp.vercel.app/ui/dc1/services#CONSUL_DATACENTER_COUNT=1000;CONSUL_NSPACE_COUNT=1000;CONSUL_PARTITION_COUNT=1000;CONSUL_NSPACES_ENABLE=1;CONSUL_PARTITIONS_ENABLE=1): This link has 1000 each of Nspaces/Partitions/DCs. These are loaded when you first open the menu so there will be a little pause whilst the HTTP happens.
The PR integrates `PagedCollection` with our `DisclosureMenu` and then uses it in the 3 menus where we may get lots of items.
I also added more example documentation to our [DisclosureMenu documentation](https://consul-ui-staging-p644eh34q-hashicorp.vercel.app/ui/docs/components/disclosure-menu). You'll be able to see …

ui: Use PagedCollection

---

.changelog/12110.txt
agent/consul/acl_endpoint.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/coordinate_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/gateway_locator.go
agent/consul/gateway_locator_test.go
agent/consul/kvs_endpoint.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint_test.go
agent/structs/structs.go
agent/txn_endpoint_test.go

This is an omnibus PR including all blocking query fixes found in:
- https://github.com/hashicorp/consul/pull/12109
- https://github.com/hashicorp/consul/pull/12343
- https://github.com/hashicorp/consul/pull/12110
- https://github.com/hashicorp/consul/pull/12389

[1.11.x] backport of a series of blocking query readability and functionality improvements

---

.changelog/12442.txt
agent/keyring.go

There's no need to restrict keyring operations to server agents anymore. Clients can forward the RPC without issues.
To test this I built a modified binary, then spun up 2 agents, a server and a client, and performed all keyring operations hitting client HTTP interface.
Server was started with: 
```
consul agent -dev -encrypt='XzpEw/zF56iMIgk5nAAydBo+S9LuGmbye7m28K7tTeg=' -node=server
```
Client:
```
consul agent -http-port=8901 -serf-lan-port=8902 -serf-lan-bind=127.0.0.1 -bind=127.0.0.1 -data-dir=`pwd` -dns-port=8900  -node='client'  -log-level=trace -encrypt='XzpEw/zF56iMIgk5nAAydBo+S9LuGmbye7m28K7tTeg=' -join='127.0.0.1:8301'
```
Then set `CONSUL-HTTP-ADDR=http://localhost:8901`. 
```
consul keyring -list
==> Gathering installed encryption keys...
WAN: …
```

Allows keyring operations on client agents

---

.changelog/12362.txt
agent/configentry/config_entry.go
agent/configentry/service_config.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/discovery_chain_endpoint.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/state/config_entry.go
go.mod
go.sum

Starting from and extending the mechanism introduced in #12110 we can specially handle the 3 main special Consul RPC endpoints that react to many config entries in a single blocking query in Connect:
- `DiscoveryChain.Get`
- `ConfigEntry.ResolveServiceConfig`
- `Intentions.Match`
All of these will internally watch for many config entries, and at least one of those will likely be not found in any given query. Because these are blends of multiple reads the exact solution from #12110 isn't perfectly aligned, but we can tweak the approach slightly and regain the utility of that mechanism.
In this case, despite looking for many config entries none may be found at all. Unlike #12110 in this scenario we do not return an empty reply to the caller, but instead synthesize a struct from default …

server: suppress spurious blocking query returns where multiple config entries are involved

---

.changelog/12110.txt
agent/consul/acl_endpoint.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/coordinate_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/gateway_locator.go
agent/consul/gateway_locator_test.go
agent/consul/kvs_endpoint.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint.go
agent/consul/txn_endpoint_test.go
agent/structs/structs.go
agent/txn_endpoint_test.go

This is an omnibus PR including all blocking query fixes found in:
- https://github.com/hashicorp/consul/pull/12109
- https://github.com/hashicorp/consul/pull/12343
- https://github.com/hashicorp/consul/pull/12110
- https://github.com/hashicorp/consul/pull/12389
NOTE: the blocking query code was incidentally modified due to https://github.com/hashicorp/consul/pull/10299 but that change was not backported.

[1.10.x] backport of a series of blocking query readability and functionality improvements

---

.changelog/12362.txt
agent/configentry/config_entry.go
agent/configentry/service_config.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/discovery_chain_endpoint.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/state/config_entry.go
go.mod
go.sum

Backport of #12362 to 1.11.x
Conflicts:
- agent/consul/config_endpoint_test.go (imports)
- go.mod (adjacencies)

[1.11.x] server: suppress spurious blocking query returns where multiple config entries are involved

---

.changelog/12362.txt
agent/configentry/config_entry.go
agent/configentry/service_config.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/discovery_chain_endpoint.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/state/config_entry.go
go.mod
go.sum
vendor/github.com/mitchellh/hashstructure/v2/LICENSE
vendor/github.com/mitchellh/hashstructure/v2/README.md
vendor/github.com/mitchellh/hashstructure/v2/errors.go
vendor/github.com/mitchellh/hashstructure/v2/go.mod
vendor/github.com/mitchellh/hashstructure/v2/hashstructure.go
vendor/github.com/mitchellh/hashstructure/v2/include.go
vendor/modules.txt

Backport of #12362 to 1.10.x
Conflicts:
- agent/consul/config_endpoint.go
- agent/consul/discovery_chain_endpoint_test.go
- agent/consul/intention_endpoint_test.go
- agent/consul/internal_endpoint.go
- agent/consul/internal_endpoint_test.go
- agent/consul/rpc.go

[1.10.x] server: suppress spurious blocking query returns where multiple config entries are involved

---

.changelog/12316.txt
ui/packages/consul-ui/app/serializers/nspace.js

See https://github.com/hashicorp/consul/pull/12316, manually cherry picked onto 1.9.x,
no-changelog label added as our change log checker doesn't work if the base branch is not main, it does have a changelog

ui: [Backport 1.9.x] Fixup displaying a Nspace default policy when expanding the preview pane

---

GNUmakefile
agent/connect/ca/testing.go
agent/consul/leader_connect_test.go

Fixes #12466 with option 2 described in that issue.
Previously we were using two different criteria to decide where to run a
test.  The main `go-test` job would skip Vault tests based on the
presence of the `vault` binary, but the `test-connect-ca-providers` job
would run tests based on the name.
This led to a scenario where a test may never run in CI.
To fix this problem I added a name check to the function we use to skip
the test. This should ensure that any test that requires vault is named
correctly to be run as part of the `test-connect-ca-providers` job.
At the same time I relaxed the regex we use. I verified this runs the
same tests using `go test --list Vault`.  I made this change because a
bunch of tests in `agent/connect/ca` used `Vault` in the name, without
the underscores. …

ca: require that tests that use Vault are named correctly

---

website/content/docs/connect/proxies/built-in.mdx

Respective page being edited: https://www.consul.io/docs/connect/proxies/built-in

Remove deprecated built-in proxy tutorial reference

---

GNUmakefile

Fixes regression from #10833
Fixes `dev-docker` and `test-docker` make targets

build: ensure 'make linux' puts the binary in the expected location

---

.changelog/12496.txt
agent/consul/server.go
agent/consul/server_serf.go
go.mod
go.sum

Add additional protections on the Consul side to prevent NonVoters from bootstrapping raft.
This should un-flake `TestServer_Expect_NonVoters`
The main change being incorporated by the upgrade is https://github.com/hashicorp/raft/pull/492

raft: upgrade to v1.3.6

---

.changelog/12496.txt
agent/consul/server.go
agent/consul/server_serf.go
go.mod
go.sum

Backport of #12496 to 1.11.x
Conflicts:
- go.mod

[1.11.x] raft: upgrade to v1.3.6

---

.changelog/12496.txt
agent/consul/server.go
agent/consul/server_serf.go
go.mod
go.sum
vendor/github.com/hashicorp/raft/api.go
vendor/github.com/hashicorp/raft/raft.go
vendor/modules.txt

Backport of #12496 to 1.10.x
Conflicts:
- go.mod

[1.10.x] raft: upgrade to v1.3.6

---

ui/packages/consul-ui/app/components/action/README.mdx

[Rendered Docs](https://consul-ui-staging-h2zmb351p-hashicorp.vercel.app/ui/docs/components/action)
`Action` is probably one of our most commonly used components, and I realised we didn't have any docs for it. This adds those.

ui: Add docs for `<Action />` component

---

website/content/docs/k8s/connect/index.mdx

The `Verifying the Installation` section seemed out of place at the bottom. Moving it higher up.

docs: consul-k8s service mesh overview - move verification section

---

website/content/docs/connect/proxies/envoy.mdx

Typo on Envoy support matrix paragraph

docs: Envoy 'compatibility' typo

---

website/content/docs/agent/options.mdx

Recently there have been a handful of GitHub issues and Discuss posts [[1]] where users have expected the `consul` CLI to make use of config options defined in the agent configuration files, and are confused when it does not honor those config options.
This change clarifies that command-line and configuration file options documented on the /agent/options page only apply to the Consul agent, instead of the Consul CLI.
[1]: https://discuss.hashicorp.com/t/consul-members-fails-because-it-is-querying-the-wrong-port-how-to-tell-it-to-use-the-right-port/35602

docs: Clarify configuration options apply to agent

---

.changelog/12512.txt
agent/consul/discovery_chain_endpoint.go
agent/consul/state/config_entry.go

Minor fix for behavior in #12362
`IsDefault` sometimes returns `true` even if there was a `proxy-defaults` or `service-defaults` config entry that was consulted. This PR fixes that.

server: fix spurious blocking query suppression for discovery chains

---

website/content/docs/connect/observability/ui-visualization.mdx

* Update Kubernetes related YAML config examples to document supported
syntax in the latest version of the Helm chart.
* Fix syntax in JSON example configs.
Resolves #12403

docs: Update Kubernetes YAML examples in UI visualization

---

agent/consul/config_endpoint_test.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/status_endpoint_test.go

Improves tests from #12362 
These tests try to setup the following concurrent scenario:
1. (goroutine 1) execute read RPC with index=0
2. (goroutine 1) get response from (1) @ index=10
3. (goroutine 1) execute read RPC with index=10 **and block**
4. (goroutine 2) WHILE (3) is blocking, start slamming the system with stray writes that will cause the WatchSet to wakeup
5. (goroutine 2) after doing all writes, shut down the reader above
6. (goroutine 1) stops reading, double checks that it only ever woke up once (from 1)

reduce flakiness/raciness of errNotFound and errNotChanged blocking query tests

---

agent/consul/config_endpoint_test.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/rpc_test.go
agent/consul/status_endpoint_test.go

Backport of #12518 to 1.10.x
Conflicts:
- agent/consul/discovery_chain_endpoint_test.go (partitions)
- agent/consul/status_endpoint_test.go (net/rpc stuff)

[1.10.x] reduce flakiness/raciness of errNotFound and errNotChanged blocking query tests

---

ui/packages/consul-ui/app/components/custom-element/README.mdx
ui/packages/consul-ui/app/components/custom-element/index.hbs
ui/packages/consul-ui/app/components/custom-element/index.js
ui/packages/consul-ui/app/components/shadow-host/README.mdx
ui/packages/consul-ui/app/components/shadow-host/index.hbs
ui/packages/consul-ui/app/components/shadow-host/index.js
ui/packages/consul-ui/app/components/shadow-template/README.mdx
ui/packages/consul-ui/app/components/shadow-template/index.hbs
ui/packages/consul-ui/app/helpers/adopt-styles.js
ui/packages/consul-ui/app/helpers/adopt-styles.mdx
ui/packages/consul-ui/app/helpers/class-map.js
ui/packages/consul-ui/app/helpers/css-map.js

Builds on `attach-shadow`, `adopt-styles` and `ShadowTemplate`, this PR adds `ShadowHost` and finally (😅)`CustomElement`.
[Rendered Docs](https://consul-ui-staging-3tqpfqutu-hashicorp.vercel.app/ui/docs/components/custom-element)
(also [ShadowHost Docs](https://consul-ui-staging-3tqpfqutu-hashicorp.vercel.app/ui/docs/components/shadow-host))
CustomElement is a renderless component to help with the creation of native HTML Custom Elements along with runtime type checking and self-documentation for attributes, slots, cssprops and cssparts. As you will probably see there is a little more work to come here. But in the same breath, everything would be fine to go in as is.
I've left a bunch of utility functions in the top of the component for the moment, as I'm still unsure whether now is the …

ui: CustomElement component

---

.changelog/12478.txt
ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs

This PR orders the Datacenter selector/menu as:
1. Primary DC first
2. Local DC second
3. All the rest alphabetically
We figured Primary should go before Local (local is the one the UI is running on) but if anyone reads this and thinks otherwise please ping ty!

ui: List Primary and Local DCs first in the Datacenter selector

---

.changelog/12529.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/structs/config_entry.go

This ensures that terminating gateway proxycfg snapshots have `Meta` populated on `ServiceConfigs`. The `Meta` key on `ServiceConfigResponse` will end up being used to configure the serverless plugin.

Add `Meta` to `ServiceConfigResponse`

---

ui/packages/consul-ui/app/components/custom-element/README.mdx
ui/packages/consul-ui/app/components/custom-element/index.hbs
ui/packages/consul-ui/app/components/custom-element/index.js
ui/packages/consul-ui/app/components/distribution-meter/README.mdx
ui/packages/consul-ui/app/components/distribution-meter/index.css.js
ui/packages/consul-ui/app/components/distribution-meter/index.hbs
ui/packages/consul-ui/app/components/distribution-meter/meter/element.js
ui/packages/consul-ui/app/components/distribution-meter/meter/index.css.js
ui/packages/consul-ui/app/components/distribution-meter/meter/index.hbs
ui/packages/consul-ui/app/components/shadow-host/README.mdx
ui/packages/consul-ui/app/components/shadow-host/index.hbs
ui/packages/consul-ui/app/components/shadow-host/index.js
ui/packages/consul-ui/app/components/shadow-template/README.mdx
ui/packages/consul-ui/app/components/shadow-template/index.hbs
ui/packages/consul-ui/app/helpers/adopt-styles.js
ui/packages/consul-ui/app/helpers/adopt-styles.mdx
ui/packages/consul-ui/app/helpers/class-map.js
ui/packages/consul-ui/app/helpers/css-map.js
ui/packages/consul-ui/app/helpers/percentage-of.js
ui/packages/consul-ui/app/helpers/require.js
ui/packages/consul-ui/app/styles/base/decoration/base-variables.scss
ui/packages/consul-ui/app/styles/base/decoration/visually-hidden.css.js

[Rendered Docs](https://consul-ui-staging-paqi22d2o-hashicorp.vercel.app/ui/docs/components/distribution-meter#CONSUL_LATENCY=3000)
I turned up the BlockingQuery wakeup rate on that link ^ to 3 seconds so it's easy to see what it looks like when data is being updated. Note you'll randomly get a set of data with different states, sometimes those states will be 100% in critical for example, just wait for different data to come in if so)
Honestly pretty happy that all this is just 5-6 lines of JS.
Two PRs that will need to be added ontop of here that I'll PR after review are:
1. Compile out the documentation metadata from the Glimmer templates (mostly the descriptions)
2. Tool for extracting the metadata from the Glimmer templates and inserting it into the README.mdx files on git stage.
I'll …

ui: DistributionMeter Component

---

ui/packages/consul-ui/app/services/repository/dc.js
ui/packages/consul-ui/app/services/repository/dc.mdx
ui/packages/consul-ui/mock-api/v1/internal/ui/catalog-overview

This PR adds a new currently non-existing endpoint in Consul.
The endpoint shows the health of the catalog as a whole (as opposed to the health of the Cluster itself). Again this is _per datacenter_, so whilst we've called it `catalog/health` is lives in the Dc Repository for the moment. The backend will give us a grouping of 'totals' per partition/namespace to we do an additional aggregation on the frontend to give us totals over:
1. All partitions
2. All namespaces
3. The entire datacenter/catalog
I set the poll to 30 seconds again.
Small note: We are getting to the point that these dataSource methods could very well just be functions rather than a method on a class - i.e. Repositories are becoming less tied to EmberData models and/or Ember Services.
[Rendered …

ui: Catalog Health Overview DataSource

---

website/content/docs/agent/options.mdx
website/content/docs/connect/ca/vault.mdx

Update the connect CA documentation for vault provider to include updated vault auth method field.

[docs] update connect ca vault provider docs to include vault auth method field

---

website/content/docs/k8s/k8s-cli.mdx

This PR cleans up the `shell-session` blocks. Most of them were missing the prefix `$`. One of them also had multiple commands bundled into one. Additionally, I added a sentence to the intro that states the benefit of the CLI.

docs: cleaned up code blocks and added two sentences to the intro

---

ui/packages/consul-ui/app/abilities/license.js
ui/packages/consul-ui/app/abilities/zervice.js
ui/packages/consul-ui/app/helpers/can.js
ui/packages/consul-ui/app/helpers/is.js
ui/packages/consul-ui/app/helpers/test.js
ui/packages/consul-ui/app/services/abilities.js
ui/packages/consul-ui/app/services/repository/permission.js
ui/packages/consul-ui/app/templates/dc/show.hbs
ui/packages/consul-ui/package.json
ui/yarn.lock

Following on from https://github.com/hashicorp/consul/pull/12493
> I also spotted a very weird ember-can error right at the very end or the work, and whilst the code related to ember-can in the changeset here gets things working without a big read unfathomable console error - it doesn't read well: is license should be can license and use ember-can directly. I've briefly looked into this and converting the Helpers here to native classes helped, but I still get the error when using can. I quickly tried an upgrade but that unfortunately breaks things differently - all in all I wanted to keep this PR as clean as possible. I'll continue to look at this ontop in a separate PR as its already growing in size due to this ember-can problem.
This is the error that was presenting when you where on …

ui: Fix ember-can

---

ui/packages/consul-ui/lib/custom-element/index.js
ui/packages/consul-ui/lib/custom-element/package.json
ui/packages/consul-ui/package.json

https://github.com/hashicorp/consul/pull/12451 finished up the beginnings of an initial approach to using ShadowDOM and CustomElements in Ember.
ShadowDOM and CustomElements gives us almost complete isolation of application components, the clearest benefit of this right now is almost complete isolation of CSS. This has the huge benefit of having more control over the cascading nature of CSS. LightDOM CSS does not punch through the ShadowDOM boundary unless you want it to via the use of CSS parts and CSS custom properties.
The benefits here are huge, and longer term as we add more and more of these components the CSS is less likely to drift slightly as the project scales.
Here we are fixing/preventing the issue at source rather than curing after the fact.
This also means less …

ui: Add CustomElement Transform

---

agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json

This configuration option will be used from the xDS code to selectively enable the serverless plugin.
Checklist:
translate.
`agent/config/testdata/full-config.*`, which should cause the test to fail.
Then update the expected value in `TestLoad_FullConfig` in
`agent/config/runtime_test.go` to make the test pass again.
the expected value for `TestRuntimeConfig_Sanitize`. Look at `git diff` to
make sure the value changed as you expect.
some cases or with some values (often true). [Eric: Not required]
`agent/config/runtime_test.go`.
`agent/config/runtime_test.go`.
any state the feature needs changing. This needs to be added to one or
more of the following places:
- `ReloadConfig` in `agent/agent.go` if it needs to affect the local
client …

Add the `connect.enable_serverless_plugin` configuration option

---

website/content/docs/agent/telemetry.mdx

Noticed a broken link while working on a project that consumes these docs. This PR fixes the link.

docs: Fixing Prometheus link in docs/agent/telemetry

---

agent/consul/config_endpoint.go
agent/http.go
agent/structs/config_entry.go
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_exports.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_intentions.go
agent/structs/config_entry_mesh.go
agent/structs/config_entry_test.go

Currently the config_entry.go subsystem delegates authorization decisions via the ConfigEntry interface CanRead and CanWrite code. Unfortunately this returns a true/false value and loses the details of the source.
This is not helpful, especially since it the config subsystem can be more complex to understand, since it covers so many domains.
This refactors CanRead/CanWrite to return a structured error message (PermissionDenied or the like) with more details about the reason for denial.
Part of #12241

Refactor config checks oss

---

ui/packages/consul-ui/app/abilities/hcp.js
ui/packages/consul-ui/app/abilities/license.js
ui/packages/consul-ui/app/abilities/overview.js
ui/packages/consul-ui/app/abilities/raft.js
ui/packages/consul-ui/app/abilities/zervice.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/helpers/can.js
ui/packages/consul-ui/app/helpers/is.js
ui/packages/consul-ui/app/helpers/test.js
ui/packages/consul-ui/app/services/abilities.js
ui/packages/consul-ui/app/services/can.js
ui/packages/consul-ui/app/services/repository/permission.js
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/show.hbs
ui/packages/consul-ui/package.json
ui/packages/consul-ui/tests/acceptance/dc/error.feature
ui/packages/consul-ui/tests/acceptance/dc/forwarding.feature
ui/packages/consul-ui/tests/acceptance/index-forwarding.feature
ui/packages/consul-ui/tests/acceptance/page-navigation.feature
ui/packages/consul-ui/tests/acceptance/token-header.feature
ui/packages/consul-ui/translations/routes/en-us.yaml
ui/packages/consul-ui/vendor/consul-ui/routes.js
ui/yarn.lock

This PR adds routes and an initial landing page for the Cluster Overview page:
UI 'index page' now looks like that ^
You'll see the odd commented out bit in here, which is awaiting decisions on backend support etc. Other than that I've spotted some other opportunities for modernizing a little and making some of the code here consistent, so I wanted to do that in a separate PR, I'll probably do these on top of here.
I also spotted a very weird ember-can error right at the very end or the work, and whilst the code related to `ember-can` in the changeset here gets things working without a big read unfathomable console error - it doesn't read well: `is license` should be `can license` and use ember-can directly. I've briefly looked into this and converting the Helpers here to native classes …

ui: Overview UI Routing

---

.changelog/11821.txt
agent/http.go

Give the user a hint that they might be doing something wrong if their GET request has a non-empty body, which can easily happen using curl's `--data-urlencode` if specifying request type via `--request GET` rather than `--get`.
Partial solution to #11471. Before closing said issue, we should consider whether a small docs change is warranted, too.
For a GET request with a non-empty body, this PR initially returned an error. After internal discussions, we decided that ignoring the body of a GET request was conventional and were hesitant to return an error code other than `200 - OK`. As an alternative, we will log a WARN message instead.
- Do we have any `GET` requests for which having a non-empty body is valid?
- Seems unlikely
```
curl --verbose --request GET …
```

http: error if GET request has non-empty body

---

agent/consul/acl_replication_types.go
agent/consul/acl_token_exp.go
agent/consul/config_replication.go
agent/consul/federation_state_replication.go
agent/consul/leader.go
agent/consul/leader_federation_state_ae.go
agent/consul/leader_intentions.go
agent/consul/rpc.go
agent/consul/server.go
agent/consul/session_ttl.go
agent/consul/system_metadata.go
agent/metrics_test.go
agent/rpc/middleware/interceptors.go
go.mod
go.sum

This syncs ent changes to oss. 
Here's how I mechanically made this PR:
```
// ent
git show 866dcb0667 -- ':!*_ent.go' ':!*_ent_test.go' ':!go.*' > <path>/patch.diff
// oss
git apply --index <path>/patch.diff
go mod tidy
```

[sync oss] add net/rpc interceptor implementation

---

website/content/docs/connect/index.mdx

Renaming Connect to Consul Service Mesh in the title, and adding a link to the getting started for Consul Service Mesh on Kubernetes guide.

docs: Consul Service Mesh overview - rename of title and K8s getting started

---

.changelog/12567.txt
acl/authorizer.go
acl/errors.go
acl/testing.go
agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/catalog_endpoint.go
agent/consul/catalog_endpoint_test.go
agent/consul/kvs_endpoint.go
agent/consul/txn_endpoint.go
agent/consul/txn_endpoint_test.go
agent/structs/config_entry.go

This extends the acl.AllowAuthorizer with source of authority information.
The next step is to unify the AllowAuthorizer and ACLResolveResult structures; that will be done in a separate PR.
Part of https://github.com/hashicorp/consul/issues/12481
Signed-off-by: Mark Anderson [manderson@hashicorp.com](mailto:manderson@hashicorp.com)

Add source of authority annotations to the PermissionDeniedError output.

---

website/content/docs/k8s/index.mdx

Glad I caught this, we should just say Consul Service Mesh.

docs: consul-k8s Change "Consul Connect Service Mesh" to "Consul Service Mesh"

---

website/content/docs/k8s/operations/gossip-encryption-key-rotation.mdx

Gossip key rotation can happen in any DC, and does not need to happen in the primary.

docs: Correction on rotating gossip key order per DC

---

website/content/api-docs/agent/check.mdx
website/content/api-docs/agent/index.mdx
website/content/api-docs/agent/service.mdx
website/content/api-docs/catalog.mdx
website/content/api-docs/config.mdx
website/content/api-docs/connect/intentions.mdx
website/content/api-docs/event.mdx
website/content/api-docs/health.mdx
website/content/api-docs/kv.mdx
website/content/api-docs/namespaces.mdx
website/content/api-docs/query.mdx
website/content/api-docs/session.mdx

PR #12489 mentioned the filtered by ACLs header in the coordinate API. This PR applies the same approach across all affected HTTP API endpoints.
All endpoints except 2 just reference the partial created in #12489. Two endpoints are special cases that required different wording, so those endpoints have a copy of the text in the partial rather than referencing the partial directly. These are previews of the special cases:
- [Read Key](https://consul-8r1g2fpun-hashicorp.vercel.app/api-docs/kv#read-key)
- [Execute Prepared Query](https://consul-8r1g2fpun-hashicorp.vercel.app/api-docs/query#execute-prepared-query)

docs: mention filtered by ACLs in affected APIs

---

website/content/docs/nia/cli/index.mdx

A discrepancy exists between the CTS implementation and docs in regards to the environment variable used to set the CTS host address.
Currently in the docs the environment variable is listed as CTS_HTTP_ADDR, however in the CTS implementation the environment variable expected, and provided when using -help is CTS_ADDRESS.
This PR serves to make the CTS docs consistent with the implementation
[Table with change](https://consul-doi2bfafk-hashicorp.vercel.app/docs/nia/cli#general-options) (see description of `-http-addr`)

updated docs

---

agent/metrics_test.go
agent/rpc/middleware/interceptors.go
agent/setup.go

We want to pre register all prometheus metrics so we don't expire them by default. The first commit does that for our new rpc metric.
The second commit renames the metric bc there already exists a `rpc.request` and we want to avoid confusion with that.

pre register new rpc metric, rename metric

---

agent/consul/txn_endpoint_test.go

Looks like something got munged	at some point. Not sure how it slipped in, but my best guess is that because  TestTxn_Apply_ACLDeny is marked flaky we didn't block merge because it failed.

Fixup dropped SecretID usage

---

website/content/docs/security/security-models/core.mdx

As shown in the screenshot below, gossip should have its own section in "internal threats", not be included in the DNS section.

docs: make gossip threat model more visible

---

acl/acl_test.go
acl/authorizer.go
acl/authorizer_test.go
acl/chained_authorizer.go
acl/chained_authorizer_test.go
acl/policy_authorizer.go
acl/policy_authorizer_test.go
acl/static_authorizer.go

For many of the new RPCs that will be added in Consul servers for Agentless work,
the ACL token will need to be authorized for service:write on any service in any namespace in any partition.
The ACL package updates are to make ServiceWriteAny related helpers available on the different authorizers.

[oss] ACL pkg updates to support Agentless RPCs

---

agent/metrics_test.go
agent/rpc/middleware/interceptors.go
agent/setup.go

We made those changes to not expire prom metrics in here: https://github.com/hashicorp/consul/pull/12582.
There was a small mix up with this OSS sync: https://github.com/hashicorp/consul/pull/12586/files#diff-92974f7ecae0d7201c3bd5ad4a8e8b0e49a66e40ee72d1661644fbc3cee199c1L28-L268 that removed the prom gauge pre declaration.
Adding it back and actually using a gauge!

fix bad oss sync, use gauges not counters

---

website/content/docs/k8s/k8s-cli.mdx

This PR adds a note box that points the user to the installation page. This makes it easier for consumers to find the installation guidance.

docs: add link to k8s cli install page

---

.github/workflows/website-checker.yml

Workflow should run when no docs/cherry-pick label && no pr/docs-label

Fix logic for website checker

---

.changelog/12607.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

When the Vault CA Provider is reconfigured we do not stop the
LifetimeRenewers which can cause them to leak until the Consul processes
recycles. On Configure execute stopWatcher if it exists and is not nil
before starting a new renewal
Also add jitter before restarting the LifetimeWatcher to prevent overwhelming Vault
when it's configured with rate limiting.
If we fail to login to Vault or our token is no longer valid we can
overwhelm a Vault instance with many requests very quickly by restarting
the LifetimeWatcher. Before restarting the LifetimeWatcher provide a
backoff time of 1 second or less.

Fix leaked Vault LifetimeRenewers

---

.changelog/12607.txt
.circleci/config.yml
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

* Fix leaked Vault LifetimeRenewers
When the Vault CA Provider is reconfigured we do not stop the
LifetimeRenewers which can cause them to leak until the Consul processes
recycles. On Configure execute stopWatcher if it exists and is not nil
before starting a new renewal
* Add jitter before restarting the LifetimeWatcher
If we fail to login to Vault or our token is no longer valid we can
overwhelm a Vault instance with many requests very quickly by restarting
the LifetimeWatcher. Before restarting the LifetimeWatcher provide a
backoff time of 1 second or less.
* Use a retry.Waiter instead of RandomStagger
* changelog
* gofmt'd
* Swap out bool for atomic.Unit32 in test
* Provide some extra clarification in comment and changelog

Fix leaked Vault LifetimeRenewers (#12607) - 1.9.x backport

---

.circleci/config.yml
GNUmakefile

Backport of #12641 to 1.11.x
This should also work for 1.10.x and 1.9.x cleanly

[1.11.x] build: enforce protoc binary is the expected version

---

.release/release-metadata.hcl

Note: This is the same change as in https://github.com/hashicorp/consul/pull/12591. I forgot to add all of the right backporting labels. 
👋  This PR adds a `.release/release-metadata.hcl` file to the repo. This contains static metadata that will be processed and sent as part of the payload in RelAPI POST requests, which will be sent when staging and production releases are triggered.  
This can be merged now, but will not have any effect until after the RelAPI launch. Similar additions are being added across all projects that publish to releases.hashicorp.com.

RelAPI Onboarding for 1.10.x

---

.release/release-metadata.hcl

Note: This is the same change as in https://github.com/hashicorp/consul/pull/12591. I forgot to add all of the right backporting labels. 
👋  This PR adds a `.release/release-metadata.hcl` file to the repo. This contains static metadata that will be processed and sent as part of the payload in RelAPI POST requests, which will be sent when staging and production releases are triggered.  
This can be merged now, but will not have any effect until after the RelAPI launch. Similar additions are being added across all projects that publish to releases.hashicorp.com.

RelAPI Onboarding for 1.9.x

---

.release/release-metadata.hcl

Note: This is the same change as in https://github.com/hashicorp/consul/pull/12591. I forgot to add all of the right backporting labels. 
👋  This PR adds a `.release/release-metadata.hcl` file to the repo. This contains static metadata that will be processed and sent as part of the payload in RelAPI POST requests, which will be sent when staging and production releases are triggered.  
This can be merged now, but will not have any effect until after the RelAPI launch. Similar additions are being added across all projects that publish to releases.hashicorp.com.

RelAPI Onboarding 1.8.x

---

.changelog/12646.txt
go.mod
go.sum
website/content/docs/agent/telemetry.mdx

This PR pulls in the latest version of raft-boltdb. The only change to the library was to add a `writeCapacity` metric. This PR then also includes docs updates to reference the new metric.

Update raft-boltdb to pull in new writeCapacity metric

---

GNUmakefile
build-support/scripts/proto-gen.sh

Also ensure that we run mog serially on each package in dependency order.
Depends on https://github.com/hashicorp/mog/pull/9 landing first.

build: run mog separately after the protobufs are generated

---

.changelog/12670.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_oss.go
agent/consul/acl_endpoint_test.go
agent/structs/acl.go
agent/structs/acl_test.go
api/acl.go
command/acl/token/formatter.go
command/acl/token/formatter_oss_test.go
command/acl/token/formatter_test.go
command/acl/token/read/token_read.go
command/acl/token/testdata/FormatTokenExpanded/oss/basic.json.golden
command/acl/token/testdata/FormatTokenExpanded/oss/basic.pretty-meta.golden
command/acl/token/testdata/FormatTokenExpanded/oss/basic.pretty.golden
command/acl/token/testdata/FormatTokenExpanded/oss/complex.json.golden
command/acl/token/testdata/FormatTokenExpanded/oss/complex.pretty-meta.golden
command/acl/token/testdata/FormatTokenExpanded/oss/complex.pretty.golden

Closes #10831
This PR adds a new option, `-expanded`, to the token read command and endpoint that will also display detailed info about any policies/rules affecting the token.
```
$ consul acl token read -rules -expanded -id=fbd2447f-7479-4329-ad13-b021d74f86ba
AccessorID:       fbd2447f-7479-4329-ad13-b021d74f86ba
SecretID:         869c6e91-4de9-4dab-b56e-87548435f9c6
Namespace:        foo
Description:      test token
Local:            false
Auth Method:      bar (Namespace: baz)
Create Time:      2020-05-22 18:52:31 +0000 UTC
Expiration Time:  2020-05-22 19:52:31 +0000 UTC
Policies:
Policy Name: hobbiton
ID: beb04680-815b-4d7c-9e33-3d707c24672c
Description: user policy on token
Rules:
service_prefix "" {
policy = "read"
}
Policy Name: bywater
ID: 18788457-584c-4812-80d3-23d403148a90 …
```

oss: Add expanded token read flag and endpoint option

---

.changelog/12655.txt
agent/connect/ca/provider_vault.go

void doing list of /sys/mounts
From an internal ticket "Support standard "Vault namespace in the path" semantics for Connect Vault CA Provid\
er"
Vault allows the namespace to be specified as a prefix in the path of
a PKI definition, but this doesn't currently work for
```IntermediatePKIPath``` specifications, because we attempt to list
all of the paths to check if ours is already defined. This doesn't
really work in a namespaced world.
This changes the IntermediatePKIPath code to follow the same pattern
as the root key, where we directly get the key rather than listing.
This code is difficult to write automated tests for because it relies
on features of Vault Enterprise, which isn't currently part of our
test framework, so it was tested manually.
Signed-off-by: Mark Anderson …

Avoid using sys/mounts to enable namespaces

---

website/content/docs/k8s/dns.mdx

I verified this with:
```
~/dev/consul [fix-k8s-dns-service-name] -> kubectl get svc consul-consul-dns --output jsonpath='{.spec.clusterIP}'
Error from server (NotFound): services "consul-consul-dns" not found
~/dev/consul [fix-k8s-dns-service-name] -> kubectl get svc consul-dns --output jsonpath='{.spec.clusterIP}'       
172.20.102.6%
```

Fix the Kubernetes service name for DNS

---

.changelog/12681.txt
agent/xds/serverless_plugin_oss_test.go
agent/xds/serverlessplugin/lambda_patcher.go
agent/xds/serverlessplugin/patcher.go
agent/xds/serverlessplugin/serverlessplugin.go
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway.envoy-1-20-x.golden
agent/xds/testdata/serverless_plugin/routes/lambda-terminating-gateway.envoy-1-20-x.golden

- Move from `strip_matching_host_port` to `strip_any_host_port`
- Remove `auto_host_rewrite` since it conflicts with `strip_any_host_port`

Tweak the Lambda Envoy configuration generated by the serverless patcher

---

ui/packages/consul-ui/app/abilities/raft.js
ui/packages/consul-ui/app/abilities/zone.js
ui/packages/consul-ui/app/components/consul/server/card/layout.scss
ui/packages/consul-ui/app/components/consul/server/list/index.hbs
ui/packages/consul-ui/app/components/tile/index.scss
ui/packages/consul-ui/app/models/dc.js
ui/packages/consul-ui/app/services/repository/dc.js
ui/packages/consul-ui/app/styles/base/decoration/base-placeholders.scss
ui/packages/consul-ui/app/styles/base/decoration/base-variables.scss
ui/packages/consul-ui/app/styles/routes.scss
ui/packages/consul-ui/app/styles/routes/dc/overview/serverstatus.scss
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/show.hbs
ui/packages/consul-ui/app/templates/dc/show/index.hbs
ui/packages/consul-ui/app/templates/dc/show/serverstatus.hbs
ui/packages/consul-ui/mock-api/v1/operator/autopilot/state
ui/packages/consul-ui/tests/unit/abilities/-test.js
ui/packages/consul-ui/translations/common/en-us.yaml
ui/packages/consul-ui/translations/routes/en-us.yaml
ui/packages/consul-ui/vendor/consul-ui/routes.js

This PR begins to add a new Cluster Overview page to the UI.
The longer term plan is for this to have 3 individual tabs, and the visibility of these will all depend on whether certain features are enabled and what permissions you have to view content. For the moment you will see some `false` conditionals with some of this work, the false's are there as placeholders for upcoming work. In the meantime the content they wrap will not show.
There will be some tweaks added on top of this at a later date once all the tabs are in place to make things consistent and ensure that the ember-can abilities are all setup correctly.
We've decided for the moment not to write any additional tests against this until we can get more of the feature complete. We've also decided to put this entire piece of work …

ui: Initial Server Status Overview Page

---

website/content/docs/security/acl/index.mdx

This PR fixes a broken url in the ACL overview page.

docs: fixes broken url in acl overview page

---

website/content/docs/connect/transparent-proxy.mdx
website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/connect/ingress-controllers.mdx
website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

The list of supported annotations for Consul service mesh were moved from /docs/k8s/connect to /docs/k8s/annotations-and-labels in PR #12323.
This commit updates various across the site to point to the new URL for these annotations.

docs: Update links to K8s service mesh annotations

---

website/content/docs/k8s/connect/index.mdx

Slight re-wording as the title seems a bit off.

docs: rename Connect Service Mesh Kubernetes to Consul Service Mesh on Kubernetes

---

.changelog/12672.txt
agent/consul/config_endpoint.go
agent/proxycfg/testing_terminating_gateway.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/testdata/clusters/terminating-gateway-sni.envoy-1-20-x.golden
website/content/docs/connect/config-entries/terminating-gateway.mdx

This PR adds a note to the terminating gateway docs strongly recommended using SNI when TLS is configured. It also adds a warning log message when configuring a service on a terminating gateway with TLS without SNI set.

Respect SNI with terminating gateways and log a warning if it isn't set alongside TLS

---

agent/consul/connect_ca_endpoint.go
agent/consul/leader_connect_ca.go

OSS sync of enterprise changes at 8d6fd125

[OSS] ca: move `ConnectCA.Sign` authorization logic to `CAManager`

---

agent/consul/leader_routine_manager.go
agent/consul/leader_routine_manager_test.go

This backports PR #12565 to the release/1.9.x branch.
The conflicts in auto-backporting were due to the relevant code getting moved out of agent/consul to lib/ and having some types renamed.

Backport #12565 to v1.9.x

---

agent/rpc/middleware/interceptors.go

Early feedback points out that `debug` level for the RPC calls can be too noisy. 
```
$ consul agent -dev -log-level trace
...
2022-04-06T10:18:09.541-0700 [TRACE] agent.server: rpc_server_call: method=Health.NodeChecks errored=false request_type=read rpc_type=net/rpc elapsed=0
...
```

[middleware][rpc] lower log to trace

---

ui/packages/consul-ui/app/abilities/overview.js

Previously we were checking `service:read` and `node:read` here for permissions to view the new Overview Page.
Originally this was done for the Service Health overview, that isn't built yet, but also we currently hardcode the `service` and `node` permissions to allow due to the fact that the API we use to get those details doesn't work quite how we want it (see https://github.com/hashicorp/consul/issues/11098).
All in all this means that you can always access the Overview page currently even if you shouldn't have access (the page will show you a 403 error if you don't have access)
This PR removes the `service` and `node` permission checking, we don't need to do that until the Service Health Overview tab is built. This means that we may as well just fallback to checking for `operator` …

ui: Ignore Service/Node permissions for Overview just use operator

---

.circleci/config.yml

Backport of #12715 to 1.10.x
Conflicts:
-	.circleci/config.yml

[1.10.x] ci: run envoy integration tests on a real machine

---

.circleci/config.yml

Backport of #12715 to 1.9.x
Conflicts:
-	.circleci/config.yml

[1.9.x] ci: run envoy integration tests on a real machine

---

.changelog/12311.txt
.changelog/12573.txt

Adds a changelog for: https://github.com/hashicorp/consul/pull/12573 and https://github.com/hashicorp/consul/pull/12311. I went with the OSS sync since there's no actual enterprise only features. But open to more guidance.

add changelog for rpc metric improv project

---

agent/consul/connect_ca_endpoint.go
agent/consul/leader_connect_ca.go

Backport of #12609 to 1.12.x
Conflicts:
- agent/consul/connect_ca_endpoint.go

[1.12.x] ca: move ConnectCA.Sign authorization logic to CAManager

---

.changelog/12725.txt
agent/agent.go

If a service is automatically registered because it has a critical health check
for longer than deregister_critical_service_after, the error message will now
include:
- mention of the deregister_critical_service_after option
- the value of deregister_critical_service_after for that check
A user reported confusion as to why a service was being automatically deregistered "at random". They were unaware of `deregister_critical_service_after` which:
1. isn't mentioned as the cause of the deregistration in log messages, and
2. isn't returned when reading a health check
This PR addresses problem (1). Problem (2) can be addressed in a follow-up PR (TODO: create an issue for this).
I modified the `TestAgent_Service_Reap` automated test to output `INFO` level log messages with:
```
--- …
```

improve error msg for deregister critical service

---

.changelog/12354.txt
ui/packages/consul-lock-sessions/app/templates/dc/nodes/show/sessions.hbs
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/binding-rules.hbs
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/nspace-rules.hbs
ui/packages/consul-ui/app/templates/dc/acls/policies/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/roles/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/exposedpaths.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/app/templates/dc/services/show/instances.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show/services.hbs
ui/packages/consul-ui/app/templates/dc/services/show/tags.hbs
ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
ui/packages/consul-ui/translations/routes/en-us.yaml

Related: https://github.com/hashicorp/consul/issues/10426#issuecomment-868432159
This PR does two things:
1. From a human perspective it updates all our 'empty state' texts to include information on the [ACL policy dispositions](https://www.consul.io/docs/security/acl/acl-rules#policy-dispositions) required to view data on that specific view.
2. Moves all of this related text to our translation files.
Small note here:
I noticed whilst doing this that we seem to be very close to full i18n'ed text in all our Routes now. In fact we are probably at a stage where we should make a move to specifically go ahead and make sure all our Routes are 100% i18n'ed seeing as we must be about 95% there, we may aswell go ahead and get the last 5% done soon-ish.

ui: Add more explanatory texts for empty states

---

website/content/docs/k8s/upgrade/index.mdx

Somehow https://www.consul.io/docs/k8s/upgrade/compatibility is still showing up which is outdated. Removing the link from this page so it perhaps no longer is served up.

docs: Upgrade Consul K8s update link to combat matrix

---

.changelog/12672.txt
agent/consul/config_endpoint.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/testdata/clusters/terminating-gateway-sni.envoy-1-20-x.golden
website/content/docs/connect/config-entries/terminating-gateway.mdx

Backport the change from https://github.com/hashicorp/consul/pull/12672. The integration test failure looks like an unrelated flake.

backport/1.11.x: Use the GatewayService SNI field for upstream SAN validation

---

.changelog/12672.txt
agent/consul/config_endpoint.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/testdata/clusters/terminating-gateway-sni.envoy-1-20-x.golden
agent/xds/testdata/clusters/terminating-gateway-sni.v2compat.envoy-1-16-x.golden
website/content/docs/connect/config-entries/terminating-gateway.mdx

Backport the change from https://github.com/hashicorp/consul/pull/12672.

backport/1.10.x: Use the GatewayService SNI field for upstream SAN validation

---

.circleci/config.yml

Backport #12742 to 1.11.x
Conflicts:
- .circleci/config.yml

[1.11.x] ci: upsize many slow-running circleci builds

---

website/redirects.js

Somehow we are still re-directing to old compat matrix version which is cached somehow for Google search results.

website: redirect change consul k8s compatibility matrix link

---

.changelog/12672.txt
agent/consul/config_endpoint.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/testdata/clusters/terminating-gateway-sni.envoy-1-16-x.golden
website/content/docs/connect/config-entries/terminating-gateway.mdx

Backport the change from https://github.com/hashicorp/consul/pull/12672.

backport/1.9.x: Use the GatewayService SNI field for upstream SAN validation

---

website/redirects.js

Reverting previous change from https://github.com/hashicorp/consul/pull/12751 and adding new redirect to new Consul K8s compatibility matrix.

redirect.js: fixing redirect to new compatibility matrix for k8s

---

build-support/functions/20-build.sh
website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx

Fixing a search and replace mistake

docs: Correcting an uncapitalized word setup at the beginning of titles to be capitalized in vault section.

---

website/content/docs/agent/telemetry.mdx

Docs update for https://github.com/hashicorp/consul/pull/12727

add docs for new labels

---

ui/packages/consul-ui/app/services/repository/dc.js

There is a case where a read-replica could be configured to be in a redundancy zone. We originally decided to use the frontend to display this configuration with the read-replica as not being in the redundancy zone. Since then we've decided that we should show the users configuration rather than display that different to what it actually is rather than fix it up on the frontend.
This PR removes the little hack we made to fix up the config if this case happens.

ui: Don't automatically move rz read-replicas out of the rz

---

ui/packages/consul-ui/app/components/consul/server/card/index.hbs

Previously we omitted the health status for read-replicas. We've decided that these should be shown just like all other servers.

ui: Show read-replica health status

---

GNUmakefile

Without this, M1 laptop build will be annotated as an arm64 image.  Running the image in kubernetes will crash with this mismatch.

Setting DOCKER_DEFAULT_PLATFORM in make dev-docker so arm64 can build an amd64 container with an amd64 binary.

---

.changelog/12767.txt
.circleci/config.yml
.github/workflows/build.yml
build-support/docker/Build-Go.dockerfile
build-support/docker/Test-Flake.dockerfile

DO NOT MERGE until we've updated our CI mirror to include the Go 1.17.9 docker image

backport/1.9.x: Update CI and release Go versions to 1.17.9

---

.changelog/12766.txt
.circleci/config.yml
.github/workflows/build.yml
build-support/docker/Build-Go.dockerfile
build-support/docker/Test-Flake.dockerfile

DO NOT MERGE until we've updated our CI mirror to include the Go 1.17.9 docker image

backport/1.10.x: Update CI and release Go versions to 1.17.9

---

.circleci/config.yml

Vault hasn't been updated for a while, and we should be testing
against a newer version. I'd update to 1.10.0, but we would run afoul
of https://github.com/hashicorp/vault/issues/14863. We should update
to 1.10.1 as soon as it comes our, or better yet move to using latest.

Update vault to 1.9.4

---

agent/connect/ca/provider_vault.go

The namespace needs tobe set before trying to call the auth method.  Otherwise it will hit the general auth handler for most routes and look for a client token.  It returns this error:
```
2022-04-13T16:59:50.366Z [ERROR] connect.ca: Failed to initialize Connect CA: error="error configuring provider: Error making API request.
URL: PUT https://vault-cluster.private.vault.a718f64a-c2d8-4d80-a330-54bce161cf25.aws.hashicorp.cloud:8200/v1/auth/kubernetes/login
Code: 400. Errors:
* missing client token"
```

set vault namespaces on vault client prior to logging in with the vault auth method

---

.changelog/12774.txt
agent/consul/authmethod/awsauth/aws.go
agent/consul/authmethod/awsauth/aws_test.go
internal/iamauth/config.go
internal/iamauth/token.go
internal/iamauth/token_test.go
internal/iamauth/util.go

This improves region handling in the AWS IAM auth method:
1. Server-side, do not send `sts:GetCallerIdentity` requests to the global STS endpoint, by default. This causes login failures when the `sts:GetCallerIdentity` request is signed for a region-specific endpoint. Instead, validate the STS URL in the bearer token and send the request to that URL.
2. Remove the `STSRegion` field from the auth method config, which is unused (note that an internal field of the same name still exists for generating the bearer token client-side. This one is still used)
3. Client-side, use the AWS SDK's native regional endpoint selection for STS. This cleans up semi-custom endpoint selection code from Vault.
Closes #12661

acl: Adjust region handling in AWS IAM auth method

---

.changelog/12791.txt
api/api.go

This help find out if query was served using a streaming backend or a blocking query backend

add queryBackend to the api query meta.

---

.changelog/12797.txt
internal/iamauth/auth_test.go
internal/iamauth/iamauthtest/testing.go
internal/iamauth/responses/responses.go
internal/iamauth/responses/responses_test.go
internal/iamauth/responsestest/testing.go

This fixes parsing of IAM role and user tags in the IAM auth method (which I _thought_ I had tested, but here I am). Previously, parsing would ignore the tags.

acl: Fix tag parsing for IAM users and roles in IAM auth method

---

.changelog/12793.txt
agent/connect/ca/provider_vault.go

Set vault namespaces on vault client prior to logging in with the vault auth method
This is a potentially breaking change, but after discussion this seems
to have been a bug, blocking what is likely the most common usages;
where the auth and PKIPaths all live in the same namespace. As
implemented the auth can only be in the root namespace.
This was originally submitted as
https://github.com/hashicorp/consul/pull/12775
but was split out because we think it stands on it's own.

Set vault namespaces on vault client prior to logging in 

---

agent/config/builder.go
agent/config/runtime.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/uiserver/ui_template_data.go
agent/uiserver/uiserver_test.go

This PR adds an environment variable, `CONSUL_HCP_ENABLED`, to be used in HCP to enable specific features/views in the UI.

Add an internal env var for HCP to enable specific features/views in the ui

---

ui/packages/consul-ui/app/components/breadcrumbs/skin.scss
ui/packages/consul-ui/app/components/csv-list/index.scss
ui/packages/consul-ui/app/components/empty-state/skin.scss
ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
ui/packages/consul-ui/app/components/secret-button/layout.scss
ui/packages/consul-ui/app/components/tooltip-panel/skin.scss
ui/packages/consul-ui/app/components/tooltip/index.scss
ui/packages/consul-ui/app/styles/base/icons/base-keyframes.scss

Fixes https://github.com/hashicorp/consul/issues/12737
Icons that were using `currentColor` were not displaying their color in Safari (leading to invisible icons). This PR defaults all pseudo elements to use `currentColor`ing. This means that if a pseudo element is not an icon (pretty rare) then its needs to be set to use transparent coloring, which is what the majority of this PR does as well as the Safari fix itself.
Eventually as we move forwards, most icons will use our new `--icon-color` property anyway so whichever way we go with icons in the future this rule can eventually be removed.

ui: Fixup icons not displaying in Safari

---

website/content/docs/api-gateway/common-errors.mdx
website/content/docs/api-gateway/consul-api-gateway-install.mdx
website/data/docs-nav-data.json
website/redirects.js

Changing the file name, page name and title of the page containing installation instructions for Consul API Gateway. This should make it easier to find the install instructions when navigating the site and when doing web searches.

Docs: Rename and re-title docs page for installing Consul API Gateway

---

ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/tests/acceptance/dc/forwarding.feature
ui/packages/consul-ui/tests/acceptance/index-forwarding.feature
ui/packages/consul-ui/tests/acceptance/page-navigation.feature
ui/packages/consul-ui/vendor/consul-ui/routes.js

Reverting the default route for Consul UI to be the Services page for the initial 1.12 release

ui: Revert to Services route as default

---

ui/packages/consul-ui/app/styles/routes/dc/overview/serverstatus.scss
ui/packages/consul-ui/app/templates/dc/show/serverstatus.hbs
ui/packages/consul-ui/translations/routes/en-us.yaml

Adds a 'Learn more' link to the top of the Server Fault Tolerance panel:
I noticed some missing noreferrer etc on the links in the licensing page also, so I added those in whilst I was here.
cc @jherschman FYI on this one

ui: Add documentation link to the Server Fault Tolerance panel

---

ui/packages/consul-ui/translations/routes/en-us.yaml

The previous link was directing us to:
https://www.consul.io/docs/docs/enterprise/license/faq#q-how-can-i-renew-a-license
It needs to go to:
https://www.consul.io/docs/enterprise/license/faq#q-how-can-i-renew-a-license

ui: fix overview's renew license link

---

ui/packages/consul-ui/app/abilities/license.js
ui/packages/consul-ui/tests/unit/abilities/-test.js

Noticed bug where license tab was still showing for OSS users. Worked with @johncowen to update to check to ensure license tab only shows for enterprise users.

ui:fixed bug where license was showing in oss

---

.circleci/config.yml

We recently updated the version of Go we build with to 1.18 in #12808. I think we may have missed this one place in the builds for arm64. 
I won't be attaching a changelog as this is part of #12808.

Run arm64 builds on go1.18

---

.changelog/12820.txt
agent/agent_endpoint_test.go
agent/cache/cache.go

Fixes #12048
Fixes #12319
Regression introduced in #11693
Local reproduction steps:
1. `consul agent -dev`
2. `curl -sLiv 'localhost:8500/v1/agent/connect/ca/leaf/web'`
3. make note of the `X-Consul-Index` header returned 
4. `curl -sLi 'localhost:8500/v1/agent/connect/ca/leaf/web?index=<VALUE_FROM_STEP_3>'`
5. Kill the above curl when it hangs with Ctrl-C
6. Repeat (2) and it should not hang.

ca: fix a bug that caused a non blocking leaf cert query after a blocking leaf cert query to block

---

website/content/docs/connect/proxies/envoy.mdx

The docs describe only the n-2 supported releases. For older releases, versioned docs should be used to see previous compatibility matrix versions. 
Preview

docs: remove 1.9.x row in Envoy compatibility matrix table

---

.changelog/12807.txt
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go

Modify ACL error message for invalid node/service identities names to clearly state only lowercase alphanumeric characters are supported.

acl: Clarify node/service identities must be lowercase

---

website/content/docs/k8s/connect/connect-ca-provider.mdx
website/redirects.js

This PR fixes the broken url in the [Configuring a Connect CA Provider](https://www.consul.io/docs/k8s/connect/connect-ca-provider)

docs: fixed broken url

---

website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx

Updates documentation to include uuidgen as a means to generate the uuid for ACL tokens when using Vault as a secrets backend.

docs: update acl token generation with uuidgen

---

.changelog/12846.txt
.github/workflows/build.yml

The `generate-metadata` action needs to be pulling from tags for better release management. We run the risk of disruption if we pushed changes to the `main` branch of the generate-metadata action thus disrupting release workflows for Consul. 
Read more on [Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)
I added the backport labels for this PR, but I'm unsure which release branches Consul is using, so feel free to adjust!

change action to pull v1 instead of main

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/enterprise/audit-logging.mdx
website/content/docs/enterprise/federation.mdx
website/content/docs/enterprise/namespaces.mdx
website/content/docs/enterprise/network-segments.mdx
website/content/docs/enterprise/read-scale.mdx
website/content/docs/enterprise/redundancy.mdx
website/content/docs/enterprise/sentinel.mdx

Removed references to modules in callout box at the top of the page. 
Edit requested by Neena Pemmaraju via Slack on 4/21/22

Remove references to modules in consul/website/content/docs/enterprise

---

.changelog/12844.txt
agent/agent.go
agent/consul/config.go
agent/consul/server.go
agent/consul/server_test.go
go.mod
go.sum

This update raft to [v1.3.7](https://github.com/hashicorp/raft/releases/tag/v1.3.7)
In this raft release `HeartbeatTimeout` and `ElectionTimeout` became reloadable config, so Consul needed to be tweaked to only reload those configs only when the given values are within the acceptable range.
Note that this also introduce https://github.com/hashicorp/raft/pull/477

update raft to v1.3.8

---

.release/ci.hcl

Consul needs to have a workflow that notarizes the darwin arm64 binary. Currently there's no workflow to notarize it.

add notarize darwin arm64 workflow

---

website/redirects.js

Redirect [`/docs/agent/config`](https://www.consul.io/docs/agent/config) to [`/docs/agent/config/config-files`](https://www.consul.io/docs/agent/config/config-files) so that external links to anchors for specific config parameters continue to work.

docs: Redirect /agent/config to /agent/config/config-files

---

website/content/docs/connect/configuration.mdx
website/content/docs/connect/connect-internals.mdx
website/data/docs-nav-data.json

This PR is intended to re-deploy changes in the Enterprise docs (PR #12847 )
The Connect pages were also updated to help reduce confusion about service mesh vs connect. 

docs: updated connect docs and re-deploying missed changes

---

agent/structs/config_entry_exports.go
agent/structs/config_entry_test.go
api/config_entry_exports.go
command/config/write/config_write_test.go

Ensures that the newly added `PeerName` field in the `exported-services` configuration entry kind can be accessed both in `CamelCase` form as well as `snake_case` form (e.g. `peer_name`) like all other compound word fields in config entries.

structs: ensure exported-services PeerName field can be addressed as peer_name

---

.changelog/12640.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
agent/health_endpoint_test.go
agent/rpcclient/health/view.go
agent/structs/structs.go

The primary bug here is in the streaming subsystem that makes the overall v1/health/service/:service request behave incorrectly when servicing a blocking request with a filter provided.
There is a secondary non-streaming bug being fixed here that is much less obvious related to when to update the `reply` variable in a `blockingQuery` evaluation. It is unlikely that it is triggerable in practical environments and I could not actually get the bug to manifest, but I fixed it anyway while investigating the original issue.
Simple reproduction (streaming):
1. Register a service with a tag.
curl -sL --request PUT 'http://localhost:8500/v1/agent/service/register' \
--header 'Content-Type: application/json' \
--data-raw '{ "ID": "ID1", "Name": "test", "Tags":[ "a" ], "EnableTagOverride": true }' …

health: ensure /v1/health/service/:service endpoint returns the most recent results when a filter is used with streaming

---

.changelog/12640.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
agent/health_endpoint_test.go
agent/rpcclient/health/view.go
agent/structs/structs.go

[1.11.x] health: ensure /v1/health/service/:service endpoint returns the most recent results when a filter is used with streaming

---

.changelog/12865.txt
go.mod
go.sum
website/content/docs/agent/telemetry.mdx

Upgrades the Raft library to v1.3.9 for the thread saturation metrics introduced in https://github.com/hashicorp/raft/pull/489.

Upgrade Raft to v1.3.9 for saturation metrics

---

.changelog/12640.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
agent/health_endpoint_test.go
agent/rpcclient/health/view.go
agent/structs/structs.go

[1.10.x] health: ensure /v1/health/service/:service endpoint returns the most recent results when a filter is used with streaming

---

.github/workflows/build.yml

This is a backport of #11844. The cherry-picks failed at the time.
We should see a successful arm64 build once this is merged.

ci: Backport arm64 bulids

---

.github/workflows/backport-reminder.yml

Adds an automated comment on PRs labelled with `backport/*` to check that the backport automation has run. 
Users who are unauthorized to run the backport CircleCI workflows will never trigger the right workflows which posts success/failure messages. This GHA should raise more awareness of the gap in our CI while maintaining that it is the merger's responsibility to ensure backports have run.

Add a Github action to remind people about backport automation

---

.github/workflows/backport-assistant.yml

Teams at Hashicorp are adopting [backport-assistant](https://github.com/hashicorp/backport-assistant) for managing commit backports to release branches. 
Right now, this work is performed by bespoke shell scripts in Consul. Furthermore, there have been issues with backporting changes that tests would have been caught by testing if commits hadn't been merged directly.
The purpose of the PR is two-fold, to pay down tech debt with CircleCI and address deficiencies in the current process of testing backport changes.
I'm proposing activating this feature in parallel with the current cherry-pick.sh action. As advertised, this action will open PRs for backport changes. Even if the cherry-pick script merges directly to the target release branches, my assumption is that it will run tests against …

chore(ci): add initial support for backport assistant

---

.circleci/config.yml
test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/Dockerfile-test-sds-server
test/integration/connect/envoy/run-tests.sh

Bonus change: send less context when building the test-sds-server to
speed up the setup.
None of the `test-integration` envoy tests were functioning. Bats would either fail with an error implying that the `bats` binary had vanished, or that `/tmp` was somehow not writable.

ci: upgrade bats and the circle machine executors to get integration tests to function again

---

.circleci/config.yml
test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/run-tests.sh

[1.10.x] ci: upgrade bats and the circle machine executors to get integration tests to function again

---

.changelog/12885.txt
agent/consul/acl.go
agent/consul/acl_test.go
agent/structs/acl_cache.go
agent/structs/acl_cache_test.go

This PR adds an `Error` field to the `IdentityCacheEntry` to preserve the error returned when attempting to resolve a token. Currently we return `acl.ErrNotFound` in this case which bubbles up to the client agent that made the request and the down policy ends up not being respected if it's set to `allow`.

Store and return RPC error in ACL cache entries

---

.github/workflows/backport-assistant.yml

`backport-assistant` still [failing](https://github.com/hashicorp/consul/runs/6277835550?check_suite_focus=true), this time because of missing `target`, even though we want a literal. 
N/A

chore(ci): fix backport-assistant for stable website

---

website/content/docs/security/acl/index.mdx

https://www.consul.io/docs/security/acl was pointing to https://www.consul.io/docs/security/acl/policies (broken) and is now pointing to https://www.consul.io/docs/security/acl/acl-policies (working)

Updated the link to acl-policies

---

.changelog/12878.txt
agent/structs/config_entry_mesh.go
agent/structs/config_entry_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/http-listener-with-timeouts.latest.golden
agent/xds/testdata/listeners/http-public-listener-no-xfcc.latest.golden
agent/xds/testdata/listeners/terminating-gateway-service-subsets.latest.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway-with-service-resolvers.latest.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway.latest.golden
api/config_entry_mesh.go
api/config_entry_test.go
command/config/write/config_write_test.go
website/content/docs/connect/config-entries/mesh.mdx

Add x-fowarded-client-cert information where appropriate
Envoy provides support forwarding and annotating the x-forwarded-client-cert header via the forward_client_cert_details set_current_client_cert_details filter fields. It would be helpful for consul to support this directly in its config. The escape hatches are a bit cumbersome for this purpose.
Closes #12852
Asana [consul-x-forwarded-client-cert](https://go.hashi.co/consul-x-fowarded-client-cert)

Support x-forwarded-client-cert 

---

agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go

When initializing proxy configs, if an upstream has a DestinationPeer, skip the discovery chain compilation step and write a default one
Added test coverage for peered upstreams

Default discovery chain when upstream targets a DestinationPeer

---

ui/packages/consul-ui/app/components/breadcrumbs/skin.scss
ui/packages/consul-ui/app/components/csv-list/index.scss
ui/packages/consul-ui/app/components/empty-state/skin.scss
ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
ui/packages/consul-ui/app/components/secret-button/layout.scss
ui/packages/consul-ui/app/components/tooltip-panel/skin.scss
ui/packages/consul-ui/app/components/tooltip/index.scss
ui/packages/consul-ui/app/styles/base/icons/base-keyframes.scss

Backport of #12738
Icons that were using currentColor were not displaying their color in Safari (leading to invisible icons). See original PR for more details.
no changelog due to base not being `main`

ui: [Backport/1.12.x] Fixup icons not displaying in Safari (#12738)

---

ui/packages/consul-ui/app/components/consul/server/card/index.hbs

Backport of #12804
Previously we omitted the health status for read-replicas. We've decided that these should be shown just like all other servers.
no changelog due to base not being `main`

ui: [Backport/1.12.x] Show read-replica health status (#12758)

---

ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/tests/acceptance/dc/forwarding.feature
ui/packages/consul-ui/tests/acceptance/index-forwarding.feature
ui/packages/consul-ui/tests/acceptance/page-navigation.feature
ui/packages/consul-ui/vendor/consul-ui/routes.js

Backport of #12804
Reverts the default route back to Services list rather than Overview
no changelog due to base not being `main`

ui: [Backport/1.12.x] Revert to Services route as default (#12804)

---

.changelog/12904.txt
agent/config/builder.go
agent/connect/ca/provider.go
agent/connect/ca/provider_vault.go
agent/structs/connect_ca.go
website/content/docs/connect/ca/vault.mdx

Follow on to some missed items from #12655
From an internal ticket "Support standard "Vault namespace in the
path" semantics for Connect Vault CA Provider"
Vault allows the namespace to be specified as a prefix in the path of
a PKI definition, but our usage of the Vault API includes calls that
don't support a namespaced key. In particular the sys.* family of
calls simply appends the key, instead of prefixing the namespace in
front of the path.
Unfortunately it is difficult to reliably parse a path with a
namespace; only vault knows what namespaces are present, and the '/'
separator can be inside a key name, as well as separating path
elements. This is in use in the wild; for example
'dc1/intermediate-key' is a relatively common naming schema.
Instead we add two new fields: …

Support vault namespaces in connect CA

---

website/content/docs/agent/config/cli-flags.mdx
website/content/docs/agent/config/config-files.mdx
website/content/docs/agent/config/index.mdx

Re-add CLI flag and config option documentation that was accidentally removed in #12562. These changes were present in commit caf34daa3 from that branch, but accidentally removed in child commits f4c03d234 and c5220fd18.

docs: Restore agent config docs removed in PR #12562

---

.circleci/config.yml
.golangci.yml

Calling the `make lint` target with an empty `golangci-lint` cache takes about 1m. I noticed that in CI we had been upping the concurrency from the default to 2, so I doubled that, and made it the general default so it applied to the `make lint` target which now takes about 35s for me.

build: speed up linting by 1.5x

---

website/content/docs/security/acl/auth-methods/index.mdx

Fix broken links on `acl/auth-methods` page for roles and service identities
N/A
N/A

Fix broken links for roles and service identities

---

.github/workflows/nightly-release-ui-test.yaml

We had some problems with our backport process sending commits to branches that would break tests, but tests are not run if a commit can be merged directly. This PR adds nightly tests for all current release branches to verify that the UI is working correctly.
This is a short-term fix until we can move our backport process away from CircleCI to something in GHA that runs tests synchronously against a target release branch.
Honestly, I'm not sure how to test this one other than merging and triggering manually. I looked into [act](https://github.com/nektos/act), but it's not set up to deal with artifact caching. I'll own QA-ing the results.
The following is an [offending PR](https://github.com/hashicorp/consul/pull/12279) that got backported mistakenly. 
It had to be [reverted …

ci: add nightly action for UI testing release branches

---

.github/workflows/changelog-checker.yml

Without further changes to `backport-assistant`, backport PRs will never contain the original `pr/no-changelog` label. This will cause GitHub checks on the PR to fail ([example](https://github.com/hashicorp/consul/pull/12926)), which will eventually also block auto-merging pull requests. Adding the `pr/no-changelog` label should be something that is handled on the front-end of the originating PR before merging. This PR exempts the bot PRs from the check. We can decide if upstream changes to `backport-assistant` are needed at a later point.
N/A

chore(ci): exempt backport PRs from changelog-checker

---

.github/workflows/nightly-release-ui-test.yaml

Nightly UI tests [are broken](https://github.com/hashicorp/consul/actions/runs/2291933332) because [you can't substitute the `matrix` parameter with a variable](https://github.community/t/how-to-share-matrix-between-jobs/128595/5).
Refactoring the variable out.
N/A

chore(ci): fix nightly UI test syntaxx

---

test/integration/consul-container/upgrade/healthcheck_test.go
test/integration/consul-container/upgrade/version_oss.go

This PR add the ability to create clients with specific version for integration tests based on containers and put version flags in a separate file with oss build tags (to be used in enterprise)

Create clients with specific version for integration tests

---

ui/packages/consul-ui/app/styles/routes/dc/overview/serverstatus.scss
ui/packages/consul-ui/app/templates/dc/show/serverstatus.hbs
ui/packages/consul-ui/translations/routes/en-us.yaml

Backport of #12792
Adds a 'Learn more' link to the top of the Server Fault Tolerance panel. See original PR for more details.
no changelog due to base not being `main`

ui: [Backport/1.12.x] Add documentation link to the Server Fault Tolerance panel (#12792)

---

website/content/docs/k8s/installation/install.mdx

Provide an option in default install that describes how to install with a specific version of the Helm chart. 

docs: provide option for installing using a specific version via Helm

---

ui/packages/consul-ui/translations/routes/en-us.yaml

PR #12792 applied the correct link to the 1.12.x branch: https://github.com/hashicorp/consul/pull/12898/files#diff-6ddfe3e26515d476fa53a1ce3c3db3e9ea0800f8dafb17f829c4858e49fa7589R8-R9
This PR applies the same link to `main`. Therefore, **there is no need to backport this to 1.12.x**.

UI: update improve server fault tolerance link

---

go.mod

This was added in #7194 and is no longer a transitive dependency.

remove replace directive for istio.io/gogo-genproto

---

agent/agent_endpoint_test.go
agent/consul/acl_test.go
agent/consul/config_endpoint_test.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/discovery_chain_endpoint_test.go
agent/consul/health_endpoint_test.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/peering_backend_test.go
agent/consul/rpc_test.go
agent/consul/state/catalog_test.go
agent/consul/state/coordinate_test.go
agent/consul/state/peering_test.go
agent/consul/stream/event_publisher_test.go
agent/grpc/private/services/subscribe/subscribe_test.go
agent/health_endpoint_test.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/stream_tracker_test.go
agent/rpc/peering/subscription_manager_test.go
agent/rpc/peering/testing.go
agent/rpcclient/health/view_test.go
agent/submatview/store_test.go
agent/xds/delta_test.go
agent/xds/xds_protocol_helpers_test.go
api/config_entry_exports_test.go
api/config_entry_test.go
lib/ttlcache/eviction_test.go
sdk/testutil/assertions.go

We've been copying around the `runStep` test helper into too many packages. This PR moves it to `testutil.RunStep`.
The old methods are left as stubs for now to ease enterprise merging.

add general runstep test helper instead of copying it all over the place

---

website/content/docs/enterprise/admin-partitions.mdx

Adding some additional polish to Admin Partitions docs by updating the versions and making use of environment variables. Also use namespaces when running `kubectl` commands as well. 

docs: Update Admin Partitions with more explicit commands by using shell variables

---

agent/rpc/peering/service_test.go

I noticed that this package fails its tests with bind address errors if there is a consul agent running on the same machine. This means those tests are using hard coded ports rather than picking ports not known to collide
- `agent/rpc/peering`

test: ensure this package uses freeport for port allocation

---

website/content/docs/agent/config/config-files.mdx
website/content/docs/api-gateway/consul-api-gateway-install.mdx
website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/config-entries/proxy-defaults.mdx
website/content/docs/connect/registration/service-registration.mdx
website/content/docs/security/acl/acl-policies.mdx
website/content/docs/security/acl/acl-rules.mdx
website/content/docs/security/acl/acl-tokens.mdx

Remove empty CodeBlockConfig elements. These elements are not providing any benefit for the enclosed code blocks. Removing so that the source is easier to read.

docs: Remove unnecessary use of CodeBlockConfig

---

agent/structs/structs.go
agent/structs/structs_oss.go
agent/structs/structs_test.go

Being able to stable-sort `[]structs.ServiceName` will be convenient in future units of work.

structs: add convenience methods to sort slices of ServiceName values

---

website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx

Added missing "primary cluster" in the multi-cluster k8s install docs.

fix small typo in multi-cluster k8s install docs

---

website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx

@sofixa Added missing "primary cluster" in the multi-cluster k8s install docs.

Consul k8s docs typo

---

.changelog/13012.txt
agent/agent.go
agent/cache-types/config_entry.go
agent/cache-types/config_entry_test.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/state_test.go
agent/proxycfg/terminating_gateway.go
agent/proxycfg/testing_terminating_gateway.go

I noticed that we were using the listing version of the cache type here, relying on the RPC to filter to a singular config entry. The consuming side of the cache watch also was explicitly validating that exactly 1 entry was returned.
While functionally correct, this would incur extra overhead of iterating and filtering out all other service resolvers. This PR switches that watch to a singular config entry watch.
* If envoy integration tests pass then things are fine. This should not have any functional difference.

Watch the singular service resolver instead of the list + filtering to 1

---

acl/enterprisemeta_oss.go
agent/consul/fsm/snapshot_oss.go
agent/consul/leader_peering.go
agent/consul/peering_backend.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/subscription_view.go
agent/rpc/peering/testing.go
agent/structs/structs.go

Each response with an UPSERT op will contain snapshots of data for a
given ResourceID. For services, this will correspond to all instances
of a service name.
This commit adds handling for storing all of these instances to the
state store, following the snapshotting logic in persistNodes.
Note that this commit does not handle deleting previously imported data
that is not in the latest snapshot. A follow-up will add that handling.

[OSS] Add upsert handling for receiving CheckServiceNode

---

agent/rpc/peering/subscription_manager.go

By changing to use `WatchCtx` we will actually block for changes to the peering list. `WatchCh` creates a goroutine to collect errors from `WatchCtx` and returns immediately.
The existing behavior wouldn't result in a tight loop because of the rate limiting in the surrounding function, but it would still lead to more work than is necessary.

Actually block when syncing subscriptions

---

api/peering_test.go

I was futzing around with the API tests and noticed that when the happy path isn't so happy, the tests could panic. It's a one-line change to move a reference to after the assertions are made. 
If you build an older version that doesn't have support for peering and then run the `api` tests, this peering test case will panic.

peering: fix panic in test

---

.github/workflows/backport-assistant.yml

Fixes syntax error that's causing backport jobs to fail: https://github.com/hashicorp/consul/runs/6425383520?check_suite_focus=true

chore(ci): fix automerge spelling

---

.changelog/13071.txt
agent/ui_endpoint.go

Fix #10164
[The behaviour of `req.Header.Set` in the go `http` package ignore the Header when it's named Host](https://github.com/golang/go/issues/7682). To se the Host header this need to be set in `req.Host`. 
This PR add the ability to do so for the ui internal endpoint, so users can add an `add_header` directive in Consul config to overwrite the Host header so a proxy can be configured.
Note:
Header names are case insensitive as defined in [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

When a host header is defined override `req.Host` in the metrics ui

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/configuration.mdx

Also fixed a link that I noticed was going to the wrong `enabled` configuration.
https://consul-rdn4nuuem-hashicorp.vercel.app/docs/nia/configuration#id
https://consul-rdn4nuuem-hashicorp.vercel.app/docs/nia/configuration#consul

docs/nia: Add service registration configurations

---

.github/workflows/nightly-test-1.10.x.yaml
.github/workflows/nightly-test-1.11.x.yaml
.github/workflows/nightly-test-1.12.x.yaml
.github/workflows/nightly-test-main.yaml

Nightly UI tests are failing as-is due to various reasons, noted inline in the PR. Summary of changes:
* Release branches have different test processes but scheduled actions [can only run against main](https://github.community/t/scheduled-builds-of-non-default-branch/16306/14). I refactored into different files for each branch, which I think will be easier to maintain and reason about.
* Various Typos and Misspellings
* Removing caching step. Caches persist between runs, so warming is unnecessary.
* Delete todo for `test-reporter`. The test format `ember test` supports seem to be unsupported in [`test-reporter`](https://github.com/dorny/test-reporter) and there aren't a lot of other popular actions.
* [working 1.12 test](https://github.com/hashicorp/consul/actions/runs/2296720524)
* …

chore(ci): fixes and spilt nightly tests per release branch

---

website/content/docs/upgrading/upgrade-specific.mdx

Due to build changes in Consul 1.12.0 the `+ent` modifier is missing
from the version reported by `/v1/agent/self`.
Nomad looks for the `ent` modifier when determining whether to reconcile
services in non-default namespaces. Without the modifier Nomad will only
end up removing services from the default Consul namespace.
(cherry picked from commit 9acce31237fd9f23363711f4ef25fd1de10fe726)

Manual cherrypick to docs

---

.github/workflows/build.yml
.release/ci.hcl

This introduces build/publishing of dev dockerhub images to the hashicorppreview dockerhub org. This will be kicked off when a PR is merged to any of the release branches (or main) listed in the `release_branches` array in `.release/ci.hcl`. 
I tested out a publish from this test branch in commit: https://github.com/hashicorp/consul/commit/c29e03af47aaaa451e17be375b96aebffa54d2fa. You can see the images available here: https://hub.docker.com/repository/docker/hashicorppreview/consul/tags?page=1&ordering=last_updated (which I will delete after this PR is merged). 
Link to full documentation describing how dev images are created and published, their naming conventions, etc: https://go.hashi.co/dev-docker-images

[CI-only] Build and publish dev dockerhub images 

---

ui/packages/consul-ui/translations/routes/en-us.yaml

Corrected misspelling of "visualization"

Corrected "visualization" typo

---

.changelog/13118.txt
agent/config/builder.go
agent/config/config.go
agent/config/deprecated.go
agent/config/deprecated_test.go

Fixes #13088, a backwards-compatibility bug introduced in 1.12.

config: prevent top-level `verify_incoming` enabling mTLS on gRPC port

---

GNUmakefile
test/integration/consul-container/libs/node/consul-container.go
test/integration/consul-container/libs/node/consul-container_oss.go
test/integration/consul-container/libs/node/node.go
test/integration/consul-container/upgrade/healthcheck_test.go
test/integration/consul-container/upgrade/util_test.go

The compatibility tests seemed particularly flaky so I took a pass to attempt to unflake them. I also did some light cleanup and refactoring and added in some missing error handling.
I also added `make test-compat-integ` to aid in local debugging.

test: cleanup and unflake parts of the upgrade compat tests

---

.github/workflows/backport-assistant.yml
.github/workflows/oss-merge-trigger.yml

Backport assistant jobs and oss-merge were not matching on release branches because of a typo

fix 'releases/*.*.x' to 'release/*.*.x'

---

agent/dns/dns_test.go

I fixed `lint-consul-retry` in https://github.com/hashicorp/lint-consul-retry/pull/1 to also detect incorrect use of `retry.RunWith` which discovered this existing issue in `TestDNS_Recursor_StrategyRandom`

test: fix incorrect use of t instead of r in retry test

---

test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/upgrade/healthcheck_test.go
test/integration/consul-container/upgrade/util_test.go

I discovered a few more things that would reduce flakes (or the threat of flakes) in the compat tests.
- waited until the _client_ could detect a leader sometimes
- ensures each test cluster used a uniquely random serf encryption key to prevent stray old carryover containers from automatically joining new clusters by accident
- fixed some errant references to `t` instead of `r` in `retry.RunWith` (the actual bug most likely)

test: fix more flakes in the compatibility test

---

agent/consul/state/config_entry.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/rpc/peering/replication.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/rpc/peering/subscription_blocking.go
agent/rpc/peering/subscription_manager.go
agent/rpc/peering/subscription_manager_test.go
agent/rpc/peering/subscription_state.go
agent/rpc/peering/subscription_state_test.go
agent/rpc/peering/subscription_view.go
agent/rpc/peering/subscription_view_test.go
agent/structs/peering.go
lib/maps/maps.go
lib/maps/maps_test.go

Treat each exported service as a "discovery chain" and replicate one synthetic CheckServiceNode for each chain and remote mesh gateway.
The health will be a flattened generated check of the checks for that mesh gateway node.
The very first commit is special and I just lifted some functions out of `agent/rpc/peering/service.go` to make `agent/rpc/peering/replication.go` before I modified them. Subsequent commits are less helpful for reading.

peering: replicate discovery chains information to importing peers

---

agent/peering_endpoint.go
agent/rpc/peering/health_snapshot.go
agent/rpc/peering/health_snapshot_test.go
agent/rpc/peering/replication.go
agent/rpc/peering/service.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/testing.go
agent/rpc/peering/validate.go
agent/structs/structs_oss.go
go.mod
go.sum
proto/pbpeering/peering.go
proto/pbservice/convert.go

General cleanup of some of the import-side replication code and vetting that when used with #1834 the right data ends up being replicated to the peer.
out of scope: complete verification of peering sync data in all scenarios

peering: accept replication stream of discovery chain information at the importing side

---

lib/telemetry.go
lib/telemetry_test.go

It looks like we missed a lint issue in #13091 which only showed up in CI for its 1.12.x backport ([build log](https://app.circleci.com/pipelines/github/hashicorp/consul-enterprise/19330/workflows/a34a4902-ac10-45de-95bc-4bdd099c89b4/jobs/353135/parallel-runs/0/steps/0-105)).
I updated the test.
[Build log](https://app.circleci.com/pipelines/github/hashicorp/consul-enterprise/19330/workflows/a34a4902-ac10-45de-95bc-4bdd099c89b4/jobs/353135/parallel-runs/0/steps/0-105)

telemetry: remove unused arg

---

agent/agent.go
agent/cache/watch.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/glue.go
agent/proxycfg/ingress_gateway.go
agent/proxycfg/manager.go
agent/proxycfg/manager_test.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/mesh_gateway_oss.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/terminating_gateway.go
agent/proxycfg/testing.go
agent/proxycfg/testing_connect_proxy.go
agent/proxycfg/testing_ingress_gateway.go
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_terminating_gateway.go
agent/proxycfg/testing_tproxy.go
agent/proxycfg/testing_upstreams.go
agent/proxycfg/upstreams.go
agent/rpcclient/health/health.go
agent/rpcclient/health/health_test.go
agent/submatview/store.go
agent/submatview/store_integration_test.go
agent/xds/clusters_test.go
agent/xds/listeners_test.go

OSS portion of enterprise PR 1857.
This removes (most) references to the `cache.UpdateEvent` type in the `proxycfg` package.
As we're going to be direct usage of the agent cache with interfaces that can be satisfied by alternative server-local datasources, it doesn't make sense to depend on this type everywhere anymore (particularly on the `state.ch` channel).
We also plan to extract `proxycfg` out of Consul into a shared library in the future, which would require removing this dependency.
Aside from a fairly rote find-and-replace, the main change is that the `cache.Cache` and `health.Client` types now accept a callback function parameter, rather than a `chan<- cache.UpdateEvents`. This allows us to do the type conversion without running another goroutine.

[OSS] proxycfg: remove dependency on `cache.UpdateEvent`

---

website/content/docs/nia/configuration.mdx

Updates doc to change config `id` from format `cts-<uuid>` to `cts-<hostname>`
[preview link](https://consul-83kuqdzmu-hashicorp.vercel.app/docs/nia/configuration#id)

docs/nia - Update CTS service id format

---

agent/consul/state/catalog_events.go
agent/health_endpoint_test.go
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
proto/pbservice/ids.go
proto/pbservice/ids_test.go
proto/pbsubscribe/subscribe.pb.go
proto/pbsubscribe/subscribe.proto

Requesting service discovery data for peered services that have been imported should make use of streaming if enabled.
[Asana](https://app.asana.com/0/1201832349181086/1201834451438964/f)

agent: allow for service discovery queries involving peer name to use streaming

---

.github/workflows/backport-reminder.yml
.github/workflows/changelog-checker.yml
.github/workflows/load-test.yml
.github/workflows/website-checker.yml

This updates our GitHub Action workflows to all have `name` specified so that the filename isn't used instead, which is a little nicer on the eyes and easier to see which is which.
See the checks for this PR. This illustrates the state before this change:

ci: name unnamed GHA workflows

---

website/content/docs/nia/api/health.mdx

Documentation changes for CTS 0.6.0 release. The RequestID field in CTS was present on the health-check endpoint, but did not provide value to users, so it was removed from the response.
https://consul-gkooykne3-hashicorp.vercel.app/docs/nia/api/health

Remove RequestId field from cts health api docs.

---

agent/consul/stream/event_publisher_test.go

I changed the error type returned in a situation but didn’t update the tests to expect that error.
I am not sure how I missed this when merging a little while ago. I thought all checks had passed but that doesn't seem possible now.
* CI checks should all pass

Fix tests broken in #13173

---

agent/consul/stream/event_buffer_test.go

This test was flaky and would sometimes do this during `-race` tests:
```
Failed
=== RUN   TestEventBufferFuzz
event_buffer_test.go:30: Using seed 1653065273297638950
event_buffer_test.go:87: 
Error Trace:	event_buffer_test.go:87
Error:      	Received unexpected error:
subscriber 00178 got bad event want=0, got=1
Test:       	TestEventBufferFuzz
event_buffer_test.go:87: 
Error Trace:	event_buffer_test.go:87
Error:      	Received unexpected error:
subscriber 00176 got bad event want=0, got=1
Test:       	TestEventBufferFuzz
event_buffer_test.go:87: 
Error Trace:	event_buffer_test.go:87
Error:      	Received unexpected error:
subscriber 00007 got bad event want=0, got=1
Test:       	TestEventBufferFuzz
event_buffer_test.go:87: 
Error Trace:	event_buffer_test.go:87
Error:      	Received …
```

test: fix flaky test TestEventBufferFuzz

---

.circleci/config.yml
GNUmakefile
agent/consul/acl_test.go

- unparam is still missing in this golangci-lint release

Upgrade golangci-lint for go v1.18

---

build-support/functions/00-vars.sh
build-support/functions/10-util.sh

After #13184 was merged the GH actions were failing with:
tput: No value for $TERM and no -T specified
You could reproduce this locally with:
docker run -v $(pwd):/data --rm -i -w /data golang:1.18.1 make lint-tools

ci: github actions run with TERM=dumb and can't do tput commands

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/network-drivers/terraform-cloud.mdx

This change is mostly converting the bullet list formatted Consul configuration to the table format, but also includes additional documentation for ACL policies and for service registration.
The configuration descriptions were copied from the existing configs. If there were sub-bullets with additional details, I moved them to the start of the section.
~https://consul-nh1vpi4w9-hashicorp.vercel.app/docs/nia/configuration#consul~
https://consul-cc8z4ypnj-hashicorp.vercel.app/docs/nia/configuration#consul

docs/nia: Updating Consul config to table format

---

agent/consul/peering_backend.go
agent/rpc/peering/service.go
agent/rpc/peering/stream_test.go

This patch adds `IsLeader` to the peering backend to use when handling `StreamResource()` as a receiver. If the service runs on a consul that is not a leader, then we hang up on the dialer. Otherwise, calls to raft apply as a non leader would fail.
In the future (future PR), we may want to send a message to the dialer with the address of the leader but for now, we just hung up.
* `stream_test.go` updated
Asana tasks [1](https://app.asana.com/0/1201832349181086/1202294390627574) & [2](https://app.asana.com/0/1201832349181086/1202045399358213)

peering: expose IsLeader, hung up on dialer if follower

---

website/content/docs/nia/configuration.mdx

Documentation changes to add CTS `service_registration.address` configuration.
https://consul-2orj2ou3f-hashicorp.vercel.app/docs/nia/configuration#consul
https://consul-2orj2ou3f-hashicorp.vercel.app/docs/nia/configuration#service-registration

docs/nia: Add CTS service address config

---

agent/structs/config_entry.go
agent/structs/config_entry_test.go
api/config_entry.go
api/config_entry_test.go
command/config/write/config_write_test.go
test/integration/connect/envoy/Dockerfile-bats

First PR of many covering new terminating gateway functionality allowing external traffic w/o node registration and transparent proxying enabled.
This PR adds an `endpoint` field to `service-defaults` which represents a service external to Consul. It can be a hostname (w/ or w/o a wildcard), ipv4/ipv6 address or ipv4/ipv6 CIDR. Service defaults will represent the "virtual service", which will be consumed by the existing `Services` definition in `TerminatingGatewayConfigEntry`.
Unit tests added. Higher-level testing will happen when we start integrating the watch with the terminating gateway xDS generation.

feat: add endpoint struct to ServiceConfigEntry

---

ui/packages/consul-ui/app/components/horizontal-kv-list/layout.scss

Updating L7 permissions to be center aligned within the row.
```scss
%horizontal-kv-list {
display: inline-flex;
flex-wrap: nowrap;
/* New: */
align-items: center;
}
```
Manual/visual QA in Chrome, Safari, and FF

ui: Alignment of L7 permissions

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

###Description
- rpc call method appends extra error message, so change == to
"Strings.Contains"
Send http request to non-leader agent
fix #12578

fix: non-leader agents return 404 on Get Intention exact api

---

.github/workflows/build.yml

Small update to remove the hardcoded `-dev` suffix from dev_tags, which is causing tags to be in the format `1.12.0-dev-dev` instead of just `1.12.0-dev`. I'll clean up the old tags before making the dockerhub repo public, which will be available https://hub.docker.com/r/hashicorppreview/consul. 
dev_tags were first introduced in https://github.com/hashicorp/consul/pull/13084

[CI-only] Update tagging for dev_tags

---

agent/rpc/peering/replication.go
agent/rpc/peering/service.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/subscription_manager.go
agent/rpc/peering/subscription_state.go
agent/rpc/peering/subscription_view.go

The next milestone for peering should function for simple cases without mesh gateways being involved at all. This PR temporarily disables the newly added behavior so that other work can continue in parallel.
[Asana](https://app.asana.com/0/1201832349181086/1202323705986724/f)

peering: disable requirement for mesh gateways initially

---

CHANGELOG.md

For Consul 1.12.0, we had removed support for Envoy 1.17.4 and 1.18.6. Historically, we have considered these as "Improvements" but since we are removing support for some versions, it can also be seen as a "Breaking Change". 
Going forward, we want to call this out in our release notes as a "Breaking Change" so that users see the version compatibility change more prominently.

Update CHANGELOG to mention removal of Envoy 1.17.4 and 1.18.6

---

agent/connect/sni.go
agent/connect/sni_test.go
agent/connect/testing_ca.go
agent/consul/server.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/subscription_manager.go
agent/rpc/peering/subscription_manager_test.go
agent/rpc/peering/subscription_state.go
agent/rpc/peering/subscription_state_test.go
agent/structs/peering.go
agent/structs/structs.go
proto/pbservice/service.gen.go
proto/pbservice/service.pb.binary.go
proto/pbservice/service.pb.go
proto/pbservice/service.proto
proto/prototest/testing.go

The importing peer will need to know what SNI and SPIFFE name corresponds to each exported service. Additionally it will need to know at a high level the protocol in use (L4/L7) to generate the appropriate connection pool and local metrics.
For replicated connect synthetic entities we edit the `Connect{}` part of a `NodeService` to have a new section:
```
{
"PeerMeta": {
"SNI": [
"web.default.default.owt.external.183150d5-1033-3672-c426-c29205a576b8.consul"
],
"SpiffeID": [
"spiffe://183150d5-1033-3672-c426-c29205a576b8.consul/ns/default/dc/dc1/svc/web"
],
"Protocol": "tcp"
}
}
```
This data is then replicated and saved as-is at the importing side. Both SNI and SpiffeID are slices for now until I can be sure we don't need them for how mesh gateways will ultimately work. …

peering: replicate expected SNI, SPIFFE, and service protocol to peers

---

.github/workflows/build.yml
.release/ci.hcl
CHANGELOG.md
version/version.go

In preparing the 1.12.1 release, I noticed that the release branch was missing commits from `release/1.12.0` so this merges them in. There were conflicts in two files:
- `website/content/docs/api-gateway/consul-api-gateway-install.mdx` - had to refer to content in `release/1.12.x` and `main` to figure out what to take here, in some cases it was a 3-way merge :/
- `website/redirects.js` - this ends up being what is on `release/1.12.x` and `main` so I think it's correct.
CI

Merge changes from release/1.12.0

---

website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

Updating the documentation to emphasize the requirement that helm release names must be unique in each Kubernetes cluster when installing in a single-dc-multi-k8s environment.

update docs for single-dc-multi-k8s install

---

agent/agent_endpoint_test.go
agent/intentions_endpoint_test.go

This test was updating the `delegate` value after the test agent had started. Firstly this is racy, and there's no good way to create an Agent first, update the delegate, and then start it because starting it is what initially populates the delegate.
Secondly (and relevant to this PR) this delegate didn't populate it's embedded `delegate` field so sometimes the test agent during the test would call a method on it and nil panic.
For now since the original test didn't feel terribly important at what it was testing, I just removed it completely.

remove a source of test panics

---

CHANGELOG.md

Adds changelog entries from the 1.10.11 release today
- Notes should match https://github.com/hashicorp/consul/releases/tag/v1.10.11

Add changelog from 1.10.11

---

CHANGELOG.md

Adds changelog entries from the 1.11.6 release today
- Notes should match https://github.com/hashicorp/consul/releases/tag/v1.11.6

Add changelog from 1.11.6

---

.changelog/13127.txt
agent/proxycfg/testing_ingress_gateway.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/xds/listeners_test.go
agent/xds/routes_test.go
agent/xds/testdata/listeners/ingress-grpc-multiple-services.latest.golden
agent/xds/testdata/routes/ingress-grpc-multiple-services.latest.golden

https://github.com/hashicorp/consul/issues/12628 reported that there was a mismatch between the documentation and the consul CLI when it comes to using multiple grpc services per ingress listener. The error received is a validation on the config entry. Removing the validation for grpc/https allows traffic to be routed as expected, which is inline with the expectations in the docs.
* I set up two grpc services (fortio and moul/grpcbin) IAW with the [tutorial](https://learn.hashicorp.com/tutorials/consul/service-mesh-ingress-gateways), using `service-defaults` to set their protocols to `grpc`. Using the proposed code, I was able to route traffic to each of the services using the `authority` header.
`fortio-service.hcl`
```hcl
service {
name = "fortio"
id = "fortio-1"
port = 8079
connect { …
```

fix: multiple grpc/http2 services for ingress listeners

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_test.go
api/config_entry.go
api/config_entry_test.go
command/config/write/config_write_test.go

This based on the choice to go with "destination" as name for the new external endpoints managed in the terminating gateway

rename "endpoint" to "destination"

---

agent/uiserver/ui_template_data.go
agent/uiserver/uiserver_test.go

Exporting HCPEnabled as a top level variable into the go-template for the UI to pick up.
Amended tests included. Note: The tests here prove that the correct JSON is outputted into the index.html file, and no further, which is perfect. From there on in, the work is the UIs responsibility to pick the JSON up.
This PR was PRed separately from https://github.com/hashicorp/consul/pull/12771 ~(the base branch)~ for an easy way to ensure the extra tests info here gets run through CI before merge.
Edit: I decided it would be better to set the get this merged into `main` separate from https://github.com/hashicorp/consul/pull/12771 so we can get it merged into both OSS and Ent easier before bringing it all together on https://github.com/hashicorp/consul/pull/12771 so I rebased and changed the base …

Export top-level HCP Enabled go-template variable for UI

---

.github/workflows/build.yml
.release/docker/docker-entrypoint-ubi.sh
Dockerfile

This migrates the docker target and docker entrypoint used to build the UBI image from https://github.com/hashicorp/docker-consul/tree/master/ubi into consul. The UBI image will be built along with other artifact types in github actions on merges to `main`, and will be released alongside the other consul docker images via CRT.
* Tested a build on this branch by adding the branch name to the allow-list in `build.yml`. Link to green build: https://github.com/hashicorp/consul/actions/runs/2385840986
* Tested the UBI image locally with the following steps:
1. Download the ubi tarball `consul_ubi_linux_amd64_1.12.0-dev_b2683af13e34879895a59c54e43a0a5c30f88128.docker.redhat.tar` from github artifacts available here: https://github.com/hashicorp/consul/actions/runs/2385840986
2. Run `docker load …

[CI-only] Support UBI images

---

ui/packages/consul-ui/app/components/consul/intention/permission/form/skin.scss
ui/packages/consul-ui/app/styles/base/reset/base-variables.scss
ui/packages/consul-ui/app/styles/base/reset/minireset.scss

New:
```scss
.consul-intention-view {
h2 {
@extend %h200;
}
}
```
Before
After

ui: Typography update for view-only Intentions

---

agent/consul/peering_backend.go
agent/rpc/peering/replication.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/subscription_manager.go
agent/rpc/peering/subscription_manager_test.go
agent/rpc/peering/subscription_state.go
proto/pbpeering/types.go

Sender watches for changes to CA roots and sends them through the replication stream. 
Receiver saves CA roots to tablePeeringTrustBundle.

Add support for streaming CA roots to peers

---

agent/catalog_endpoint_test.go
agent/health_endpoint_test.go

Temporarily disabling the validation of merge central config response since it is breaking OSS to ENT merging.
A follow up PR will patch the fixes.

Termporarily disable validation of merge central config response

---

CHANGELOG.md

Adds changelog entries from the 1.12.1 release today
- Notes should match https://github.com/hashicorp/consul/releases/tag/v1.12.1

Add changelog from 1.12.1

---

CHANGELOG.md

These are collectively all the changelog entries from the releases yesterday (1.12.1, 1.11.6, and 1.10.11). It also includes entries for 1.10.10 too because they were missing for whatever reason.
These should match the entries for each of the releases:
- [1.12.1](https://github.com/hashicorp/consul/releases/tag/v1.12.1)
- [1.11.6](https://github.com/hashicorp/consul/releases/tag/v1.11.6)
- [1.10.11](https://github.com/hashicorp/consul/releases/tag/v1.10.11)
- [1.10.10](https://github.com/hashicorp/consul/releases/tag/v1.10.10)

Add latest changelog entries

---

agent/consul/peering_backend.go
agent/consul/server.go
agent/consul/server_test.go
agent/rpc/peering/service.go
agent/rpc/peering/stream_test.go

This diff adds a way for the peering service to monitor leadership changes on the consul server by looking at raft observations and recording the `leader address`. This will help us tell dialers what the address of the leader actually is.
* add server level testing in `server_test.go`
* [asana task](https://app.asana.com/0/1201832349181086/1202045399358214)
* poll approach: using [`monitorLeadership()`](https://github.com/hashicorp/consul/blob/f507f62f3cebd0ff9a4259d44487e75b2596492a/agent/consul/leader.go#L64) / adding a channel in peering service
-we would have to duplicate monitoring logic and have to add another go routine in the peering service, which can be more complex that we actually need

monitor leadership in peering service

---

command/registry_oss.go

I merged an oss PR https://github.com/hashicorp/consul/pull/12729 without the right build tag

Add build tag for oss

---

website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

Manual back port of https://github.com/hashicorp/consul/pull/13231/files 

docs: manual backport to 1.11.x for single dc multi k8s cluster

---

agent/proxycfg-sources/local/sync_test.go

This PR is just fixing a flaky test: agent/proxycfg-sources/local.TestSync
At the end of this test we were trying to ensure that updating a service in the local state causes it to re-register the service with the config manager.
The config manager in the same method will also call RegisteredProxies to determine if any need to be removed. This portion of the test is not attempting to verify that behavior.
Because the test is only blocked waiting for the Register event before it can end and assert all the mock expectations were met, we may not see the call to RegisteredProxies. This is especially apparent when tests are run with the race detector.
As we don’t actually care if that method is executed before the end of the test we can simply transition from expecting it to be called exactly …

Fix a flaky test

---

.circleci/config.yml
.circleci/terraform/load-test/main.tf
.circleci/terraform/load-test/variables.tf
test/load/terraform/variables.tf

The PR addresses the following 3 issues in the current load test
1.  The current circleCI load-test job always checkouts the main branch, although the CI passes the commit of a PR:
https://github.com/hashicorp/consul/blob/fd7a403e1190ef7f8cfc35a13bf388945d94e37e/.circleci/config.yml#L980-L987
This makes it difficult to run load test against any PR or any change made to the `./test/load/terraform`.
2. The tag key `consul-servers` is too general and applied to both client and server agent, so the PR change the key name to `consul-ci-load-test`:
3. `terraform destroy` may fail transiently; add a retry to make sure resources are always destroyed.

Add tag to resources provisioned during load test

---

.github/workflows/build.yml

Smoke test the linux built binaries: 386, amd64, arm, and arm64
Since qemu can't be installed in github action macOS runner, we can't smoke test the arm and arm64 binaries for darwin

CI: Verify built binaries in build job

---

connect/proxy/proxy.go

The race detector had picked up on this in another PR of mine.
The `Proxy` type within the `connect/proxy` package has a `service` field to track the connect service being served. The `Serve` method is what is responsible for changing the value of this field from nil to some service once its watches have given it data.
Closing or shutting down the `Proxy` and stopping the `Serve` method starts by closing a channel. The `Serve` method will pick up on this an exit. The `Close` method on the proxy itself was also checking if the `service` field was not nil and if so it was executing `Close` on that as well. From the point-of-view of ownership, the `Serve` method owns that data and it should not be accessed unsynchronized from outside of that method.
This PR does just that. I moved calling …

Fix race during proxy closing

---

website/content/api-docs/snapshot.mdx

Small Docs edit PR to remove ambiguity that may be confusing as to file extension names for snapshots.
When testing via CLI vs API, either the .snap or .tgz file types can be used. When Snapshot agent creates back-ups they are specifically saved as .snap files. In maintaining parity throughout our documentation, I submit this recommended change for approval.
N/A
Relevant Docs page where edit is proposed:
https://www.consul.io/api-docs/snapshot#restore-snapshot

Update to API Snapshot documentation

---

agent/catalog_endpoint_test.go
agent/health_endpoint_test.go

Setting the right enterprise meta to fix the merge central config tests.
Re-added the tests that were failing on the OSS to ENT merge.

[OSS] Fix merge central config tests

---

.circleci/config.yml

Right now branch protection rules for either UI or Go testing to pass cannot be applied Consul because CircleCI only selectively runs these checks depending on the branch name. This PR added `noop` jobs to each of the workflows so that each important check always appears in the PR, even if it does no meaningful work. The downside is that there will be a bit more noise in the CircleCi consul for each branch.
This PR and enabling the branch protections will make sure that tests pass on all of our automated PRs before they get merged in.
N/A

chore(ci): add no-op jobs for branch protection rules

---

GNUmakefile

There are a lot of useful and sometimes hidden `make` targets in our large makefile. This easily surfaces those targets with `make help`.

build: add 'make help' to simply list available make targets

---

agent/proxycfg/testing_ingress_gateway.go

The automated backport PR #13326 was merged in without tests passing, causing the release 1.12 branch to fail to build. This remediates the build issues.

fix: ingress multiple grpc test

---

.changelog/13127.txt
agent/proxycfg/testing.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/xds/listeners_test.go
agent/xds/routes_test.go
agent/xds/testdata/listeners/ingress-grpc-multiple-services.envoy-1-20-x.golden
agent/xds/testdata/routes/ingress-grpc-multiple-services.envoy-1-20-x.golden

This is a manual backport of https://github.com/hashicorp/consul/pull/13127. Due to the testing refactor, https://github.com/hashicorp/consul/pull/13248 failed.
At some point the testing code was refactored into a common function for 1.12. This PR breaks it out into it's own test case.

Backport of fix: multiple grpc/http2 services for ingress listeners into release/1.11.x

---

.changelog/13344.txt
agent/kvs_endpoint.go

Fixes https://github.com/hashicorp/consul/issues/13303
Originally reported by @wjordan [here](https://github.com/hashicorp/consul/pull/11500#issuecomment-990110027), I requested the bugfix be removed from https://github.com/hashicorp/consul/pull/11500 assuming it was a separate issue. Unfortunately it turns out that broke KVS.Get RPC operations in 1.12.1.
The KV.Get endpoint was being passed `**structs.KeyRequest`, which when handled by a client's RPC method, was not fulfilling this assertion: https://github.com/hashicorp/consul/blob/c48120d005539b687391b6861f24c13d553f5b05/agent/pool/pool.go#L632-L635
causing the ReadTimeout to be set to the default value of `rpc_hold_timeout` ([source](https://github.com/hashicorp/consul/blob/f507f62f3cebd0ff9a4259d44487e75b2596492a/agent/consul/client_t …

Fix KVSGet method to handle QueryOptions properly

---

website/content/docs/k8s/installation/multi-cluster/index.mdx
website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx

The docs are invalid for federation using k8s.

update multicluster docs for k8s to specify the correct k8sAuthMethodHost

---

agent/proxycfg/connect_proxy.go
agent/proxycfg/manager_test.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/testing_peering.go
agent/proxycfg/upstreams.go
agent/rpc/peering/subscription_manager.go
agent/structs/structs.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/testdata/clusters/connect-proxy-with-peered-upstreams.latest.golden
agent/xds/xdscommon/xdscommon.go

This removes unnecessary, vestigal remnants of discovery chains.
This is a necessary precursor to more work on making the mesh gateway peering code work end-to-end.

peering: update how cross-peer upstreams and represented in proxycfg and rendered in xds

---

agent/agent.go
agent/proxycfg/testing_connect_proxy.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/delta.go
agent/xds/endpoints_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/resources.go
agent/xds/routes_test.go
agent/xds/server.go
agent/xds/serverless_plugin_oss_test.go
agent/xds/xds_protocol_helpers_test.go

This is the OSS portion of enterprise PR 1994.
Rather than directly interrogating the agent-local state for HTTP checks using the `HTTPCheckFetcher` interface, we now rely on the config snapshot containing the checks.
This reduces the number of changes required to support server xDS sessions.
It's not clear why the fetching approach was chosen in https://github.com/hashicorp/consul/pull/6446 (https://github.com/hashicorp/consul/commit/931d167ebb2300839b218d08871f22323c60175d) when the same PR added the data to the config snapshot 🤷
Running `go test ./agent/xds` passes as before ✅
```hcl
service {
name = "web"
port = 8080
checks = [
{
http = "http://localhost:8081/"
interval = "10s"
}
]
connect {
sidecar_service {
proxy {
expose {
checks = true
}
}
}
}
}
```
```shell
$ consul agent -dev …
```

[OSS] xds: remove `HTTPCheckFetcher` dependency

---

command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
command/connect/envoy/testdata/access-log-path.golden
command/connect/envoy/testdata/custom-bootstrap.golden
command/connect/envoy/testdata/defaults-nodemeta.golden
command/connect/envoy/testdata/defaults.golden
command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
command/connect/envoy/testdata/existing-ca-file.golden
command/connect/envoy/testdata/existing-ca-path.golden
command/connect/envoy/testdata/extra_-multiple.golden
command/connect/envoy/testdata/extra_-single.golden
command/connect/envoy/testdata/grpc-addr-env.golden
command/connect/envoy/testdata/grpc-addr-flag.golden
command/connect/envoy/testdata/grpc-addr-unix.golden
command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
command/connect/envoy/testdata/stats-config-override.golden
command/connect/envoy/testdata/token-arg.golden
command/connect/envoy/testdata/token-env.golden
command/connect/envoy/testdata/token-file-arg.golden
command/connect/envoy/testdata/token-file-env.golden
command/connect/envoy/testdata/xds-addr-config.golden
command/connect/envoy/testdata/zipkin-tracing-config.golden

Changes the sourcing of the envoy bootstrap configuration to not use agent APIs and instead use the catalog(server) API.
This is done by passing a node-name flag to the command, (which can only be used with proxy-id).
Also fixes a bug where the golden envoy bootstrap config files used for tests did not use the expected destination service name in certain places for connect proxy kind.
Manual testing/demo: https://gist.github.com/riddhi89/b5823d922f6b76477b2e685325a6c8be

[OSS] consul connect envoy command changes for agentless

---

.circleci/config.yml

The upgrade compatibility tests need frequent retrying to pass because they are slightly flaky. To alleviate manual work borrow similar `gotestsum` logic from the main go tests CI job to rerun them automatically here.

test: retry the compat tests as often as other tests

---

agent/consul/client_test.go
agent/consul/leader_peering.go
proto/pbpeering/peering.go

When repeatedly standing up a peered pair of clusters locally I was pretty reliably encountering a peering race condition leading to one peer triggering a TERMINATION at the wrong time (which is terminal).
I made the race go away by moving some data access around.
If you read the current peerings from the state store, then read the current established streams you could lose the data race and have the sequence of events be:
1. list peerings [A,B,C]
2. persist new peering [D]
3. accept new stream for [D]
4. list streams [A,B,C,D]
5. terminate [D]
Which is wrong. If we instead ensure that (4) happens before (1), given that you can't get an established stream without first passing a "does this peering exist in the state store?" inquiry then this happens:
1. list streams [A,B,C]
2. list …

peering: avoid a race between peering establishment and termination

---

.changelog/13051.txt
go.mod
go.sum

Updates go-grpc/grpc to v1.37.1 to address memory leak issue in earlier versions.
I am including the test case I used to validate the behavior, I have removed it from the PR as it is testing internal library behavior and likely will not survive long-term. The test uses reflection to do some digging for connection leaks. The test when ported to 1.11.x at least demonstrates the issue cleanly.
<details><summary>Test code</summary>
In `agent/grpc/private/client_test.go`:
```
func TestClientConnPool_IntegrationWithGRPCResolver_Rebalance5000(t *testing.T) {
count := 5
res := resolver.NewServerResolverBuilder(newConfig(t))
registerWithGRPC(t, res)
pool := NewClientConnPool(ClientConnPoolConfig{
Servers:               res,
UseTLSForDC:           useTLSForDcAlwaysTrue,
DialingFromServer:     true, …
```

Update to go-grpc/grpc@v1.37.1 to resolve connection memory leak

---

agent/consul/state/config_entry_intention.go

This fix an issue introduced in https://github.com/hashicorp/consul/pull/13354 which fail to retrieve intentions when using enterprise namespace and partitions wildcard.

Fix intentions wildcard dest

---

.changelog/13394.txt
ui/packages/consul-lock-sessions/app/components/consul/lock-session/notifications/README.mdx
ui/packages/consul-nspaces/app/components/consul/nspace/search-bar/index.hbs
ui/packages/consul-partitions/app/components/consul/partition/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/auth-method/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/health-check/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/kv/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/node/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/policy/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/role/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/server/card/index.hbs
ui/packages/consul-ui/app/components/consul/service-instance/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/token/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/upstream/search-bar/index.hbs
ui/packages/consul-ui/app/components/disclosure-menu/menu/index.hbs
ui/packages/consul-ui/app/components/form-group/element/index.hbs
ui/packages/consul-ui/app/components/policy-form/index.hbs
ui/packages/consul-ui/app/styles/base/icons/README.mdx
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
ui/packages/consul-ui/package.json
ui/yarn.lock

Upgrade [ember-composable-helpers ](https://github.com/DockYard/ember-composable-helpers) to version 5.x. This version contains the `pick`-helper which makes composition in the template layer easier with Octane.
```hbs
{{!-- this is usually hard to do with Octane --}}
<input {{on "input" (pick "target.value" this.updateText)}} .../>
```
Version 5.x also fixes a regression with `sort-by` that according to @johncowen was the reason why the version was pinned to `4.0.0` at the moment.
Version 5 of `ember-composable-helpers` removes the `contains`-helper in favor of `includes` which I changed all occurences for.
Tests are passing locally.
[Fix for slow sort-by - PR](https://github.com/DockYard/ember-composable-helpers/pull/419)

ui: upgrade ember composable helper

---

agent/consul/peering_backend.go
agent/consul/peering_backend_oss.go
agent/consul/peering_backend_oss_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_oss_test.go
agent/rpc/peering/stream_test.go

Locally I was trying to run a peered service mesh using the OSS binary and was getting this:
```
2022-06-07T19:08:08.794Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=peer-trust-bundle error="rpc error: code = InvalidArgument desc = Partitions are a Consul Enterprise feature" index=0
```
This was because we were using `PartitionOrDefault()` to pass an argument to a protobuf request. The field-stripping logic isn't part of the protobuf stack, so in all cases `"default"` was being sent to the server which was rejecting the request.
This PR changes the logic to be cool with getting `""` or `"default"` for either Partition or Namespace fields on requests.

peering: allow protobuf requests to populate the default partition or namespace

---

website/content/docs/nia/cli/index.mdx
website/content/docs/nia/installation/run.mdx

Usage of consul-terraform-sync without a subcommand is deprecated. The `start` subcommand provides the same functionality and is intended for future use. Since the command is present in version 0.6.0, this documentation can be deployed without a new CTS release.
https://consul-61bn1zauw-hashicorp.vercel.app/docs/nia/cli
https://consul-61bn1zauw-hashicorp.vercel.app/docs/nia/installation/run

Change CTS docs to use the `start` subcommand.

---

website/content/docs/nia/configuration.mdx

Changes to doc :
Changed default service_name to consul-terraform-sync. Service name is used in service registration it was previously proper case, it is now lower case.
Preview Link :
https://consul-puh2px6pp-hashicorp.vercel.app/docs/nia/configuration#service-registration

Updated the default service name to lower case

---

.github/scripts/verify_artifact.sh
.github/scripts/verify_bin.sh
.github/scripts/verify_deb.sh
.github/scripts/verify_docker.sh
.github/scripts/verify_rpm.sh
.github/workflows/build.yml

This is a manually created backport for #13294. It also includes the resolved contents of #13200 that haven't been backported yet.
This is the last PR in the series to artifacts as part of the build workflow. The primary target for this last PR is for validating rpm and deb packages. There were TODOs for these last two jobs, which I'm adding. However, I'm also going back and making a few changes to the previous two PRs (#13200 and #13221):
- Verifications now all check the contents of the version string (as opposed to just running `consul version`)
- Renaming scripts to all match `verify_*.sh` pattern
- Moving zip/binary verification into its own job
The output can be seen in this run: 
- …

Backport of ci: Add package verifications to build workflow onto release/1.11.x

---

.github/workflows/build.yml

In #13376 I forgot to remove the trigger for its dev branch.

ci: Remove branch trigger for dev branch

---

.changelog/13051.txt
go.mod
go.sum

Backports #13051 to 1.12.x. Thanks, @dekimsey! ⭐

Backport gRPC upgrade to 1.12.x

---

.github/scripts/metrics_checker.sh

The metrics check is reporting sometimes reporting false change detections because it's looking at the raw diff of branches rather than the merge diff. [Stack overflow explanation.](https://stackoverflow.com/questions/37763836/how-to-make-git-diff-show-the-same-result-as-githubs-pull-request-diff)
N/A
N/A

chore(ci): fix false positive metrics check

---

.changelog/13421.txt
agent/dns.go
website/content/docs/discovery/dns.mdx

This PR has the OSS and docs updates for an enterprise change to support dns node lookups in specific partitions.

OSS: Add dns node lookup support in partitions

---

.changelog/13357.txt
.circleci/bash_env.sh
.github/workflows/build.yml
GNUmakefile
agent/agent_endpoint.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
build-support/functions/10-util.sh
build-support/scripts/build-date.sh
command/agent/agent.go
command/version/formatter.go
command/version/formatter_test.go
command/version/testdata/json.golden
command/version/testdata/pretty.golden
command/version/version.go
version/version.go

Capture build date (actually last github commit date) in consul. 
This adds support for build date in the makefile, circleci, and github workflows, and extends the self endpoint to return the date.

Add build date (oss)

---

agent/consul/peering_backend.go
agent/rpc/peering/replication.go
agent/rpc/peering/service.go
agent/rpc/peering/stream_test.go
proto/pbservice/convert.go

Previously, imported data would never be deleted. As
nodes/services/checks were registered and deregistered, resources
deleted from the exporting cluster would accumulate in the imported
cluster.
This commit makes updates to replication so that whenever an update is
received for a service name we reconcile what was present in the catalog
against what was received.
This handleUpdateService method can handle both updates and deletions.
* Added unit tests for various cases. Ran them in both OSS and ENT.

Clean up imported nodes/services/checks as needed

---

website/content/docs/k8s/connect/terminating-gateways.mdx

With Consul Helm chart `0.44.0` the default envoy proxy image is no longer based on the alpine base image, the trust store location is changed in this base image and needs to be updated in our docs when specifying the config-entry.
This should help users avoid situations like: https://github.com/hashicorp/consul-k8s/issues/1262
Include any links here that might be helpful for people reviewing your PR (Tickets, GH issues, API docs, external benchmarks, tools docs, etc). If there are none, feel …

[docs] update terminating gateway docs for trust store path

---

agent/intentions_endpoint_test.go

This diff adds a test to prove that the http api can list intentions for peered services. 
* [asana](https://app.asana.com/0/1201631904755166/1202439043013562/f)

peering: intentions list test

---

.changelog/13434.txt
.circleci/config.yml
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
test/integration/connect/envoy/run-tests.sh
website/content/docs/connect/proxies/envoy.mdx

Envoy [released some security-oriented patches recently for 1.22.1, 1.21.3, 1.20.4 and 1.19.5](https://groups.google.com/g/envoy-security-announce/c/LQkjLzgmFJA/m/8VMcT_BhAQAJ?utm_medium=email&utm_source=footer&pli=1). This upgrades our integration tests to run against these latest versions and adds them to the support matrix in our docs.
_Note:_ Since this is for 1.11, only the 1.20.4 and 1.19.5 versions were added. 
[CI run](https://app.circleci.com/pipelines/github/hashicorp/consul/33185/workflows/d28d4d0c-a42b-4d98-b0bc-f7586dd78c62).
[CTIA-31](https://hashicorp.atlassian.net/browse/CTIA-31).

[1.11] connect: Update supported Envoy versions to 1.20.4, 1.19.5, 1.18.6, 1.17.4

---

agent/consul/enterprise_server_oss.go
agent/consul/leader.go
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/server.go
agent/peering_endpoint_test.go
agent/rpc/peering/service_test.go
api/peering_test.go

Tech preview backport for: #13445
Once a peering is marked for deletion a new leader routine will now
clean up all imported resources and then the peering itself.
A lot of the logic was grabbed from the namespace/partitions deferred
deletions but with a handful of simplifications:
- The rate limiting is not configurable.
- Deleting imported nodes/services/checks is done by deleting nodes with
the Txn API. The services and checks are deleted as a side-effect.
- There is no "round rate limiter" like with namespaces and partitions.
This is because peerings are purely local, and deleting a peering in
the datacenter does not depend on deleting data from other DCs like
with WAN-federated namespaces. All rate limiting is handled by the
Raft rate limiter.

[OSS-Preview] Add leader routine to clean up peerings

---

docs/rpc/README.md
tools/private-grpc-proxy/main.go

Multiplexing several protocols over a single server port helps to reduce our network requirements, but also makes interacting with Consul using local development tools such as [grpcurl](https://github.com/fullstorydev/grpcurl) difficult.
This PR adds a tool that proxies connections to the private gRPC server (injecting the byte prefix) and some instructions for how to use it.

docs: instructions for interacting with the private gRPC server locally

---

agent/xds/clusters_test.go
agent/xds/endpoints_test.go
agent/xds/listeners_test.go
agent/xds/resources_oss_test.go
agent/xds/resources_test.go
agent/xds/routes_test.go
agent/xds/testdata/clusters/connect-proxy-exported-to-peers.latest.golden
agent/xds/testdata/clusters/mesh-gateway-with-exported-peered-services.latest.golden
agent/xds/testdata/endpoints/connect-proxy-exported-to-peers.latest.golden
agent/xds/testdata/endpoints/connect-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-with-exported-peered-services.latest.golden
agent/xds/testdata/listeners/connect-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/routes/connect-proxy-exported-to-peers.latest.golden
agent/xds/testdata/routes/connect-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/routes/mesh-gateway-with-exported-peered-services.latest.golden

This is one step in getting us to always test all 4 types of resources when we create these proxycfg ConfigSnapshot instances in the envoy golden tests. 
I was going to add more tests for the mesh gateway L7 stuff but found myself wanting to have already done this, so I figured now was a good time to get it out of the way and get started.

xds: begin refactor to always pass test snapshots through all xDS types

---

.changelog/13409.txt
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
ui/packages/consul-ui/app/utils/intl/missing-message.js
ui/packages/consul-ui/translations/routes/en-us.yaml

Some of our i18n intl keys were wrong for our empty states. As missing intl keys default to show the last part of the key capitalised (`dc.nodes.sessions.empty.header` => `Header`). This resulted in some empty states showing `Header` and `Body` instead of the actual text.
we initially added the "capitalise the last part of the missing key as a default/missing piece of text" thing to help machine > human word replacement for lots of small pieces of text that were always going to be the last part of the key but capitalized, which seemed like a good approach at the time 😬 . This unfortunately means we don't notice when we don't type the intl key correctly.
So additionally here, I've added a dev time only log message (using `runInDebug` so it doesn't compile in) so we can go through and …

ui: Fix intl keys in order to render correct messages for empty states

---

.github/workflows/build.yml

The `redhat_tag` used here contains the wrong OSPID which means the images can't be published.
Testing for this can only take place during a push to red hat. However, the new OSPID has been copy/pasted directly from the Consul project page on Red Hat Partner Connect, so it is correct.
Internal people can see [this slack thread](https://hashicorp.slack.com/archives/CR024M999/p1655349640576519) for links to failed pushes to red hat caused by this issue.

Correct redhat tags

---

agent/consul/intention_endpoint.go
agent/consul/state/config_entry_intention.go
agent/consul/state/intention_test.go
agent/structs/config_entry_intentions.go
agent/structs/config_entry_intentions_test.go
agent/structs/structs.go

We will be using the `IntentionsGetExact` endpoint/ query and we need it to handle `peer` service names for `peer` intentions.
* [asana](https://app.asana.com/0/1201631904755166/1202439043013558/f)

peering, state: account for peer intentions

---

agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go

I know `Intentions.*` is on its way out but today someone can still hit these endpoints with a SourcePeer like `Intention.Apply` hoping to create a peer service intention. This diff blocks that (and any other `.Apply` op) which is good api hygiene at least.

peering: block Intention.Apply ops

---

agent/consul/config_endpoint_test.go
agent/consul/merge_service_config.go
agent/proxycfg/snapshot.go
agent/proxycfg/terminating_gateway.go
agent/proxycfg/testing_terminating_gateway.go
agent/structs/config_entry.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/clusters/transparent-proxy-terminating-gateway-destinations-only.latest.golden
agent/xds/testdata/listeners/transparent-proxy-terminating-gateway-destinations-only.latest.golden

We are currently adding support for Destinations (nodeless egress services) in Consul Terminating Gateways. This PR adds the xDS generation at the Terminating gateway side of the connection, including listeners and clusters.
Since traffic may be encrypted from the client, all traffic appears as TCP. For hostname traffic, which may be part of a wildcard definition, we route traffic based on SNI to a dynamic forward proxy. For IP traffic, we use a placeholder SNI on the listener to identify the destination and route to a static envoy cluster.
The forward proxy configuration was tested with a local envoy instance based on [this setup](https://github.com/DanStough/envoy-examples/tree/main/tcp-dynamic-forward-proxy).

feat: xDS Generation for Terminating Gateway Destinations

---

website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
website/content/docs/k8s/installation/vault/wan-federation.mdx
website/data/docs-nav-data.json

* Docs - k8s - Webhook Certs on Vault
* Adding webhook certs to data-integration overview page
* marking items as code
* Apply suggestions from code review
Co-authored-by: trujillo-adam <47586768+trujillo-adam@users.noreply.github.com>
* Updating prerequisites intro
* Updating prerequisites intro
* Updating `Create a Vault auth roles that link the policy to each Consul on Kubernetes service account that requires access` to `Link the Vault policy to Consul workloads`
* changing `Configure the Vault Kubernetes auth role in the Consul on Kubernetes helm chart` to `Update the Consul on Kubernetes helm chart`.
* Changed `Create a Vault PKI role that establishes the domains that it is allowed to issue certificates for` to `Configure allowed domains for PKI certificates`
* Moved `Create a Vault …

Docs cherry pick (forgot label before merging to main) - k8s - Webhook Certs on Vault (#13441)

---

website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/registration/service-registration.mdx

This PR covers two sets of changes:
- Documenting the new `destination_peer` for proxy upstream definitions.
- Updating the exported-services config entry documentation.
Updates to the `exported-services` config entry include:
- As of 1.13.0 it is no longer only for Consul Enterprise
- A `PeerName` is now a possible consumer for an exported service.
- Added examples for OSS and Enterprise
- Linked to peering docs

Additional service mesh docs updates for peering

---

website/content/commands/monitor.mdx
website/content/commands/snapshot/agent.mdx
website/content/docs/agent/config/cli-flags.mdx

"err" was used for backwards compatibility, but we should use "error" as the standard for now per [log_levels.go](https://github.com/hashicorp/consul/blob/401221de5852432d742f2bdb1c4f17fb0d0e7362/logging/log_levels.go#L10) 
Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to …

docs: Use "error" to use standard log level value

---

website/content/commands/monitor.mdx
website/content/commands/snapshot/agent.mdx
website/content/docs/agent/options.mdx

Manual back port of https://github.com/hashicorp/consul/pull/13507 

docs: backport error value changes to 1.10.x 

---

test/integration/consul-container/go.mod
test/integration/consul-container/go.sum

This is to fix a dependabot alert related to tests https://github.com/hashicorp/consul/security/dependabot/65

update github.com/containerd/containerd to 1.5.13

---

CHANGELOG.md

Entries for `1.13.0-alpha{1,2}` which were released on June 15th and June 21st respectively. These will eventually be replaced by the entries for the `1.13.0` GA release when it is available.

Add changelog entries for 1.13.0-alpha1 and 1.13.0-alpha2

---

website/content/docs/discovery/dns.mdx

This brings some suggestions from a backport PR (https://github.com/hashicorp/consul/pull/13465) over to `main`.

docs: Clarify section on partitioned node DNS lookups

---

agent/consul/state/acl_oss.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/config_entry_schema.go
agent/consul/state/coordinate.go
agent/consul/state/indexer.go
agent/consul/state/kvs.go
agent/consul/state/kvs_oss.go
agent/consul/state/peering.go
agent/consul/state/peering_oss.go
agent/consul/state/query.go
agent/consul/state/query_oss.go
agent/consul/state/schema.go
agent/consul/state/session.go
agent/consul/state/session_oss.go

We have many indexer functions in Consul which take `interface{}` and type assert before building the index.
Example:
```go
p, ok := raw.(*structs.ACLToken)
if !ok {
return nil, fmt.Errorf("unexpected type %T for structs.ACLToken index", raw)
}
```
We can use generics to get rid of the initial plumbing and pass around functions with better defined signatures.
This has two benefits:
1. Less verbosity (see lines removed from this PR)
2. Developers can parse the argument types to memdb schemas without having to introspect the function for the type assertion
* This PR adds no new functionality; tests should pass as-is

Make memdb indexers generic

---

.changelog/12399.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_test.go
agent/consul/state/state_store.go

Fixes #12398 by adding fine-grained `node.[node]` entries to the `index` table, allowing blocking queries to return fine-grained indexes that prevent them from returning immediately when unrelated nodes/services are updated.

Fix fine-grained blocking queries for Catalog.NodeServices

---

website/content/docs/connect/cluster-peering/index.mdx

The existing statement about the limitation is quite confusing and can lead people to believe that only `http` cannot be used. Instead what the limitation is that no l7 protocols can be used: `http` `http2` or `grpc`. I think this clarifies what the limitations are better.

Clarify the wording of the peering limitations in the preview

---

.circleci/config.yml

We recently moved our OSS->Ent automation to a GitHub action. It is already set up to handle the release branches as well, so we need to remove these triggers to stop the CircleCI robots from doing it.
The effect is that jobs will no longer be triggered for merges to the release branch, so I'll be testing the absence of an event once this merges.

[1.12] Remove trigger-oss-merge CI job

---

.circleci/config.yml

We recently moved our OSS->Ent automation to a GitHub action. It is already set up to handle the release branches as well, so we need to remove these triggers to stop the CircleCI robots from doing it.
The effect is that jobs will no longer be triggered for merges to the release branch, so I'll be testing the absence of an event once this merges.

[1.11] Remove trigger-oss-merge CI job

---

.circleci/config.yml

We recently moved our OSS->Ent automation to a GitHub action. It is already set up to handle the release branches as well, so we need to remove these triggers to stop the CircleCI robots from doing it.
The effect is that jobs will no longer be triggered for merges to the release branch, so I'll be testing the absence of an event once this merges.

[1.10] Remove trigger-oss-merge CI job

---

.circleci/config.yml

We recently moved our OSS->Ent automation to a GitHub action. It is already set up to handle the release branches as well, so we need to remove these triggers to stop the CircleCI robots from doing it.
The effect is that jobs will no longer be triggered for merges to the release branch, so I'll be testing the absence of an event once this merges.

Remove trigger-oss-merge job

---

.github/workflows/build.yml
.release/ci.hcl
version/version.go

Pushing per-commit dev images to the `hashicorppreview` dockerhub org was introduced in https://github.com/hashicorp/consul/pull/13084, but the tag names have been unclear. 
This PR has been created to follow the guidance outlined in https://docs.google.com/document/d/1ovhf8DmlXbsuc45HkN7LdsrS2J3evfSvcy2LPiyUgZ8/edit for dev image naming, and for keeping the version string in `version.go` up to date. There are two parts to this:
1.  Keeping the version strings in `version.go` on each active release branch, and on `main`, updated after a release to point to the next minor or major version string. For example, after releasing consul `1.11.6` from branch `release/1.11.x`, the version string in `version.go` on `release/1.11.x` should be updated to `1.11.7`. 
2. `dev_tags`, the set of tags …

[CI-only] Dev tag update for main

---

.github/workflows/build.yml
.release/ci.hcl
version/version.go

Pushing per-commit dev images to the `hashicorppreview` dockerhub org was introduced in https://github.com/hashicorp/consul/pull/13084, but the tag names have been unclear. 
This PR has been created to follow the guidance outlined in https://docs.google.com/document/d/1ovhf8DmlXbsuc45HkN7LdsrS2J3evfSvcy2LPiyUgZ8/edit for dev image naming, and for keeping the version string in `version.go` up to date. There are two parts to this:
1.  Keeping the version strings in `version.go` on each active release branch, and on `main`, updated after a release to point to the next minor or major version string. For example, after releasing consul `1.11.6` from branch `release/1.11.x`, the version string in `version.go` on `release/1.11.x` should be updated to `1.11.7`. 
2. `dev_tags`, the set of tags …

[CI-only] Dev tag update for 1.12.x

---

.github/workflows/build.yml
.release/ci.hcl
version/version.go

Pushing per-commit dev images to the `hashicorppreview` dockerhub org was introduced in https://github.com/hashicorp/consul/pull/13084, but the tag names have been unclear. 
This PR has been created to follow the guidance outlined in https://docs.google.com/document/d/1ovhf8DmlXbsuc45HkN7LdsrS2J3evfSvcy2LPiyUgZ8/edit for dev image naming, and for keeping the version string in `version.go` up to date. There are two parts to this:
1.  Keeping the version strings in `version.go` on each active release branch, and on `main`, updated after a release to point to the next minor or major version string. For example, after releasing consul `1.11.6` from branch `release/1.11.x`, the version string in `version.go` on `release/1.11.x` should be updated to `1.11.7`. 
2. `dev_tags`, the set of tags …

[CI-only] Update dev image tagging on 1.11.x

---

agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/structs/structs.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

We need to add peering support for the following UI endpoints: `UIServices`, `UINodes`, `UINodeInfo` in order to add data about peered services and nodes thru the UI.
Out of the 3, `UINodeInfo` is the simplest because it either takes a `PeerName` or `""`. `""` is denoted to mean local fetch, aka, local look ups, aka services or nodes that are not peered.
> Note: If `UIServices` or `UINodes` RPC endpoints receive a request for a specific peer (i.e. `args.PeerName != ""), we error out since we don't support that case right now bc it's not needed.
* updated `_test` files
* https://app.asana.com/0/1202437710094276/1202439043013559
* https://app.asana.com/0/1202437710094276/1202454391493007

peering, internal: support UIServices, UINodes, UINodeInfo 

---

.changelog/13481.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden

This PR adds support for enabling TLS on the Envoy Prometheus endpoint (enabled when `envoy_prometheus_bind_addr` is set) via new CLI flags for the CA/cert/key. The intention is to provide these in kubernetes via a mounted volume and have Envoy watch the files to dynamically reload the certs when the volume is updated.

Add TLS support in Envoy Prometheus endpoint

---

website/content/docs/download-tools.mdx

This PR adds [HashiBox](https://github.com/nunchistudio/hashibox) to the community tools.
HashiBox is a local environment to simulate a highly-available cloud with [Consul](https://www.consul.io/), [Nomad](https://www.nomadproject.io/), and [Vault](https://www.vaultproject.io/). OSS and Enterprise versions of each product are supported.

Add HashiBox to community tools

---

website/content/commands/connect/envoy.mdx
website/content/docs/k8s/annotations-and-labels.mdx

Updates CLI/k8s annotation docs for the Envoy Prometheus TLS options added in https://github.com/hashicorp/consul/pull/13481.

Update docs for prometheus TLS options

---

agent/consul/state/config_entry.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/rpc/peering/stream_test.go
agent/rpc/peering/subscription_blocking.go
agent/rpc/peering/subscription_manager.go
agent/rpc/peering/subscription_manager_test.go
agent/rpc/peering/subscription_state.go
agent/structs/discovery_chain.go
agent/structs/peering.go
lib/maps/maps.go
lib/maps/maps_test.go

SAN validation is important for callers to verify that they are dialing the correct service mesh endpoint. They do this by verifying that the SpiffeID of the destination is expected (in a manner like "reverse intentions").
When traversing an exported peered service, the discovery chain evaluation at the other side may re-route the request to a variety of endpoints. Furthermore we intend to _terminate_ mTLS at the mesh gateway for arriving peered traffic that is http-like (L7), so the caller needs to know the mesh gateway's SpiffeID in that case as well.
The following new SpiffeID values will be shipped back in the peerstream replication:
- **tcp** : all possible SpiffeIDs resulting from the `service-resolver` component of the exported discovery chain
- **http-like**: the SpiffeID of the …

peering: replicate all SpiffeID values necessary for the importing side to do SAN validation

---

.github/scripts/verify_artifact.sh
.github/workflows/build.yml

The linux packaging action recently updated the way arm packages get named so our verifications broke. They were looking for packages with just `arm` in the name, but they are now `armhf` for debian and `armv7hl` for rpms.  
I temporarily added a branch target for this to see it get fixed. I'll remove the branch target before merging.
Upstream PR that changed the packaging action: https://github.com/hashicorp/actions-packaging-linux/pull/6.

Fix verifications by using updated arm package names

---

.release/security-scan.hcl

Temporarily disable security-scanner's binary secrets scanning, which is reporting a false negative here: https://github.com/hashicorp/crt-workflows-common/runs/7082460830?check_suite_focus=true. 
Related slack thread with ProdSec who recommended this approach as a temporary fix: https://hashicorp.slack.com/archives/CR024M999/p1656368792165579?thread_ts=1656004894.759009&cid=CR024M999

Turn off sec-scanner check

---

.circleci/config.yml
test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-none/primary/verify.bats
test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-none/secondary/join.hcl
test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-remote/primary/verify.bats
test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-remote/secondary/join.hcl
test/integration/connect/envoy/case-cross-peers/alpha/verify.bats
test/integration/connect/envoy/case-cross-peers/primary/verify.bats
test/integration/connect/envoy/case-gateways-local/primary/verify.bats
test/integration/connect/envoy/case-gateways-local/secondary/join.hcl
test/integration/connect/envoy/case-gateways-remote/secondary/join.hcl
test/integration/connect/envoy/case-ingress-mesh-gateways-resolver/primary/verify.bats
test/integration/connect/envoy/case-ingress-mesh-gateways-resolver/secondary/join.hcl
test/integration/connect/envoy/case-multidc-rsa-ca/secondary/join.hcl
test/integration/connect/envoy/case-wanfed-gw/primary/common.hcl
test/integration/connect/envoy/case-wanfed-gw/primary/verify.bats
test/integration/connect/envoy/case-wanfed-gw/secondary/common.hcl
test/integration/connect/envoy/case-wanfed-gw/secondary/server.hcl
test/integration/connect/envoy/case-wanfed-gw/secondary/verify.bats
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

This is the OSS portion of enterprise PR 2170.
With agentless, we source proxy configuration data differently on servers and clients, so it's necessary to run the integration tests against both to catch regressions.
This PR introduces a new environment variable `XDS_TARGET` that controls whether Envoy will be configured to a Consul server or client agent for its xDS sessions.
Setting `XDS_TARGET=server` maintains the existing behavior, where we run a single Consul process in `-dev` (and therefore server) mode. Whereas setting `XDS_TARGET=client` also runs a client agent and disables the server's gRPC port.
There's a fairly lengthy comment in `start_consul` that expands on some of the details of how all this works (e.g. hostnames, configuration).
* Run the integration tests (or watch the …

test: run Envoy integration tests against both servers and clients

---

agent/xds/listeners.go
agent/xds/testdata/listeners/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/listeners/mesh-gateway-with-exported-peered-services-http-with-splitter-crossing-partitions.latest.golden
agent/xds/testdata/listeners/mesh-gateway-with-exported-peered-services-http.latest.golden

When a service mesh connection is terminated at a peered mesh gateway (for http-like protocols), the ultimate destination that the mesh gateway sends the traffic to will lose the ability to introspect the TLS connection to see the origin's SpiffeID value.
This uses the X-Forwarded-Client-Cert header to send that data along by first clearing the XFCC header and ensuring the mesh-gateway added value goes first in the list.
Example header that makes it to the final destination:
```
By=spiffe://8c7db6d3-e4ee-aa8c-488c-dbedd3772b78.consul/gateway/mesh/dc/dc2;
Hash=2a2db78ac351a05854a0abd350631bf98cc0eb827d21f4ed5935ccd287779eb6;
Cert="-----BEGIN%20CERTIFICATE-----<SNIP>";
Chain="-----BEGIN%20CERTIFICATE-----<SNIP>";
Subject="";
URI=spiffe://5583c38e-c1c0-fd1e-2079-170bb2f396ad.consul/ns/default …
```

xds: have mesh gateways forward peered SpiffeIDs using the XFCC header

---

.github/scripts/verify_artifact.sh
.github/workflows/build.yml

This is a manual backport of #13601. The description of the original PR is below:
The linux packaging action recently updated the way arm packages get named so our verifications broke. They were looking for packages with just `arm` in the name, but they are now `armhf` for debian and `armv7hl` for rpms.  
I temporarily added a branch target for this to see it get fixed. I'll remove the branch target before merging.
Upstream PR that changed the packaging action: https://github.com/hashicorp/actions-packaging-linux/pull/6.

[1.10] Backport of "Fix verifications by using updated arm package names (#13601)"

---

.github/scripts/verify_artifact.sh
.github/workflows/build.yml

This is a manual backport of #13601. The description of the original PR is below:
The linux packaging action recently updated the way arm packages get named so our verifications broke. They were looking for packages with just `arm` in the name, but they are now `armhf` for debian and `armv7hl` for rpms.  
I temporarily added a branch target for this to see it get fixed. I'll remove the branch target before merging.
Upstream PR that changed the packaging action: https://github.com/hashicorp/actions-packaging-linux/pull/6.

[1.11] Backport of "Fix verifications by using updated arm package names (#13601)"

---

.github/scripts/verify_artifact.sh
.github/workflows/build.yml

This is a manual backport of #13601. The description of the original PR is below:
The linux packaging action recently updated the way arm packages get named so our verifications broke. They were looking for packages with just `arm` in the name, but they are now `armhf` for debian and `armv7hl` for rpms.  
I temporarily added a branch target for this to see it get fixed. I'll remove the branch target before merging.
Upstream PR that changed the packaging action: https://github.com/hashicorp/actions-packaging-linux/pull/6.

[1.12] Backport of "Fix verifications by using updated arm package names (#13601)"

---

website/content/docs/connect/cluster-peering/create-manage-peering.mdx
website/content/docs/connect/cluster-peering/index.mdx
website/content/docs/connect/cluster-peering/k8s.mdx

Fix typo in cluster peering docs. There's an extraneous "to"

Fix typo in cluster peering docs

---

ui/packages/consul-ui/app/adapters/node.js
ui/packages/consul-ui/app/adapters/service.js
ui/packages/consul-ui/app/locations/fsm-with-optional.js
ui/packages/consul-ui/tests/acceptance/dc/nodes/index.feature
ui/packages/consul-ui/tests/acceptance/dc/services/list.feature
ui/packages/consul-ui/tests/integration/adapters/node-test.js
ui/packages/consul-ui/tests/integration/adapters/service-test.js

When specifying extra "optional params" when generating href's unless you specify a value for every possible optional parameter, the ones you didn't specify would not 'inherit' the value already existing in the URL. Technically this was due to us _overwriting_ and optional object rather than _merging_ it with the optional object generated from the existing URL values i.e. we needed to splat the objects onto one another instead of just overwriting/replacing.
Additionally we added the conditional namespace 'test markers' in some places where they were needed, and also moved the order of the query parameter for `with-peers` to pragmatically satisfy existing test assertions.
Note: We've discussed creating a new, less brittle, API URL assertion step so we can specify specific parts of the URL …

ui: Fix up peer ENT tests

---

agent/agent.go
agent/cache-types/peered_upstreams.go
agent/cache-types/peered_upstreams_test.go
agent/consul/helper_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/query_oss.go
agent/proxycfg-glue/glue.go
agent/proxycfg/data_sources.go
agent/structs/structs.go

For initial cluster peering TProxy support we consider all imported services of a partition to be potential upstreams.
We leverage the VirtualIP table because it stores plain service names (e.g. "api", not "api-sidecar-proxy") and deduplicates them (one VIP per service name).
* Added new tests

Add internal endpoint to fetch peered upstream candidates from VirtualIP table

---

acl/authorizer.go
acl/authorizer_test.go

The UI uses the endpoint to determine if a user has permissions to do certain operations. This resource will be checked to see if a user has the ability to read/manage peerings.
Currently the permissions checked are just `operator:{read,write}`. Once we implement ACLs for peering this will need to be changed. In the mean time though, have this implemented like so will unblock frontend folks from working on integration.
* Unit tests
* Run a dev agent with ACLs enabled. Bootstrap ACLs and then `curl -X POST -H "X-Consul-Token: $CONSUL_HTTP_TOKEN" localhost:8500/v1/internal/acl/authorize -d '[{"resource": "peering", "access": "read"}, {"resource": "peering", "access": "write"}]'`

Allow the /v1/internal/acl/authorize endpoint to authorize the “peering" resource

---

agent/consul/helper_test.go
agent/consul/internal_endpoint_test.go

These files were edited in the enterprise-side PR but not the OSS; this PR is to sync them again.
Original: https://github.com/hashicorp/consul/pull/13642

Fix ENT drift in files

---

ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/filter/predicates/service.js
ui/packages/consul-ui/tests/unit/filter/predicates/service-test.js

Two small changes to move the peering UI forward:
* Update empty downstream topology message to take peers into account
* Add a filter on the service listing that allows for filtering services that don't have any ExternalSources set (this will include peered services)
cc @johncowen

ui: peering chores

---

ui/packages/consul-ui/app/search/predicates/service.js
ui/packages/consul-ui/tests/unit/search/predicates/service-test.js
ui/packages/consul-ui/translations/common/en-us.yaml
ui/packages/consul-ui/vendor/consul-ui/routes.js

Add `Admin Partitions` search property to services list
* ~~[ ] external facing docs updated~~
cc @johncowen

ui: allow searching services by admin-partition

---

ui/packages/consul-ui/app/components/state-chart/README.mdx
ui/packages/consul-ui/app/components/state-machine/README.mdx
ui/packages/consul-ui/app/components/state-machine/index.hbs
ui/packages/consul-ui/app/components/state-machine/index.js
ui/packages/consul-ui/app/components/state/README.mdx
ui/packages/consul-ui/app/components/state/index.hbs
ui/packages/consul-ui/app/components/state/index.js
ui/packages/consul-ui/app/helpers/require.js

TLDR
This is a a new `StateMachine` component inheriting from `StateChart` and has the exact same functionality for interface changing purposes, changes are:
1. exported `|State Guard Action dispatch state|` properties have changed to a object containing those properties instead instead > `|fsm|` (i.e. `fsm.State`, `fsm.dispatch` etc)
2. `Guard` and `Action` were removed, once we need them this will be managed via entry-like `@guards` and `@actions` args.
--- 
Our `<StateChart />` and related components could do with an upgrade, mainly due to the less than ergonomic interface which is proving difficult to work with. This is reasonably often, making it feel like a unicorn dies every time we use it 😅 . We are looking to use this quite a bit in our upcoming work.
We also use this component …

ui: Gradual deprecation of old StateChart interface

---

ui/packages/consul-ui/app/components/consul/peer/components.scss
ui/packages/consul-ui/app/components/consul/peer/index.scss
ui/packages/consul-ui/app/components/consul/peer/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/peer/search-bar/index.scss
ui/packages/consul-ui/app/filter/predicates/peer.js
ui/packages/consul-ui/app/helpers/require.js
ui/packages/consul-ui/app/routes/dc/peers/index.js
ui/packages/consul-ui/app/services/filter.js
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/templates/dc/peers/index.hbs
ui/packages/consul-ui/translations/components/consul/en-us.yaml

Adds filtering peer listing by State
Please note there are a few things that may be tweaked here moving forwards, i.e. specific icons etc. Right now we are just matching the previously used icons.

ui: Add filtering peer listing by State

---

.changelog/13687.txt
agent/agent.go
agent/consul/config.go
agent/consul/leader.go
agent/consul/server_serf.go
agent/consul/server_test.go
agent/metadata/server.go
agent/metadata/server_test.go

Currently servers exchange information about their WAN serf port and RPC port with serf tags, so that they all learn of each other's addressing information. We intend to make larger use of the new public-facing gRPC port exposed on all of the servers, so this PR addresses that by passing around the gRPC port via serf tags and then ensuring the generated `consul` service in the catalog has metadata about that new port as well for ease of non-serf-based lookup.

server: broadcast the public grpc port using lan serf and update the consul service in the catalog with the same data

---

website/content/docs/ecs/compatibility.mdx
website/content/docs/ecs/enterprise.mdx
website/content/docs/ecs/terraform/migrate-existing-tasks.mdx
website/content/docs/ecs/terraform/secure-configuration.mdx

The path to the `consul-ecs` Terraform modules were incorrect in some of the examples. This PR corrects those paths.

Fix path to consul-ecs Terraform modules

---

command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden

Follow-up to https://github.com/hashicorp/consul/pull/13481 - testing this uncovered a bug with the syntax for the validation context in the generated bootstrap config for the envoy prometheus TLS listener.

Fix syntax for envoy bootstrap prometheus secret config

---

agent/consul/peering_backend.go

Encountered an issue while tracking a regression in K8s acceptance tests where a dialer was passed a token with no ServerAddresses.

Return error if ServerAddresses is empty

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/consul/state/peering.go
agent/grpc/public/services/peerstream/subscription_manager_test.go
agent/proxycfg/testing_mesh_gateway.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/testdata/clusters/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/listeners/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/routes/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden

Because peerings are pairwise, between two tuples of `(datacenter, partition)` having any exported reference via a discovery chain that crosses out of the peered datacenter or partition will ultimately not be able to work for various reasons. The biggest one is that there is no way in the ultimate destination to configure an intention that can allow an external SpiffeID to access a service.
This PR ensures that a user simply cannot do this, so they won't run into weird situations like this.

state: prohibit exported discovery chains to have cross-datacenter or cross-partition references

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/grpc/public/services/peerstream/subscription_manager_test.go

For L4/tcp exported services the mesh gateways will not be terminating TLS. A caller in one peer will be directly establishing TLS connections to the ultimate exported service in the other peer.
The caller will be doing SAN validation using the replicated SpiffeID values shipped from the exporting side. There are a class of discovery chain edits that could be done on the exporting side that would cause the introduction of a **new** SpiffeID value. In between the time of the config entry update on the exporting side and the importing side getting updated peer stream data requests to the exported service would fail due to SAN validation errors.
This is unacceptable so instead prohibit the exporting peer from making changes that would break peering in this way.

state: prohibit changing an exported tcp discovery chain in a way that would break SAN validation 

---

agent/grpc/public/services/peerstream/stream_test.go
agent/grpc/public/services/peerstream/subscription_manager.go
agent/grpc/public/services/peerstream/subscription_manager_test.go

If someone were to switch a peer-exported service from L4 to L7 there would be a brief SAN validation hiccup as traffic shifted to the mesh gateway for termination.
This PR sends the mesh gateway SpiffeID down all the time so the clients always expect a switch.

peering: always send the mesh gateway SpiffeID even for tcp services

---

ui/packages/consul-ui/app/components/consul/peer/index.scss
ui/packages/consul-ui/app/components/consul/peer/list/index.scss
ui/packages/consul-ui/app/styles/routes.scss

In https://github.com/hashicorp/consul/pull/13685#pullrequestreview-1031744420 we noticed that a horizontal scroll had been added to the peering list rows in https://github.com/hashicorp/consul/pull/13425. This had the effect of pushing rendering/stacking out of place if you have scrollbars showing permanently.
This PR removes the CSS that was causing this.
Additionally, I noticed that I could move the rest of the CSS for the peer listing alongside the component that we now have for the listing so it's easier to find, so I moved the other related CSS other there.

ui: Remove horizontal scrollbar from peering list rows

---

agent/agent.go
agent/grpc-external/services/peerstream/subscription_manager.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/data_sources.go
agent/proxycfg/internal/watch/watchmap.go
agent/proxycfg/internal/watch/watchmap_test.go
agent/proxycfg/manager_test.go
agent/proxycfg/naming.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/testing.go
agent/proxycfg/upstreams.go
agent/xds/clusters.go
agent/xds/endpoints.go

Now that peered upstreams are valid candidates for TProxy upstreams, we need to set up the right watches.
Adds a new generic type which is a wrapper around a hashmap with added behavior:
- Key must be initialized with `InitWatch(key K, cancel func())` before `Set`
- `CancelWatch(key K)` can be called on a key to delete the entry and call `cancel()`
I hope this can be used for other "watch map"+"data map" combos to refactor parts of the code.
* Added tests

Watch imported services for transparent proxycfg snapshots

---

agent/proxycfg/snapshot.go
agent/proxycfg/upstreams.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/routes.go

Since we tracked implicit upstreams from peers in a separate map, this PR adds a helper method to check if an UpstreamID is implicit based on either the `IntentionUpstreams` or `PeeredUpstreams` map.

Check if an upstream is implicit from either intentions or peered services

---

CHANGELOG.md

Adds all the changelog entries from today's releases: [`1.12.3`](https://github.com/hashicorp/consul/releases/tag/v1.12.3), [`1.11.7`](https://github.com/hashicorp/consul/releases/tag/v1.11.7), [`1.10.12`](https://github.com/hashicorp/consul/releases/tag/v1.10.12).
The entries should match what is shown on the release pages.
* [`1.12.3`](https://github.com/hashicorp/consul/releases/tag/v1.12.3)
* [`1.11.7`](https://github.com/hashicorp/consul/releases/tag/v1.11.7)
* [`1.10.12`](https://github.com/hashicorp/consul/releases/tag/v1.10.12)

Add changelog entries from latest releases

---

CHANGELOG.md
version/version.go

Adds all the changelog entries from today's release: [`1.10.12`](https://github.com/hashicorp/consul/releases/tag/v1.10.12).
The entries should match what is shown on the release page.
* [`1.10.12`](https://github.com/hashicorp/consul/releases/tag/v1.10.12)

[1.10] Post-release updates

---

CHANGELOG.md
version/version.go

Adds all the changelog entries from today's release: [`1.11.7`](https://github.com/hashicorp/consul/releases/tag/v1.11.7).
The entries should match what is shown on the release page.
* [`1.11.7`](https://github.com/hashicorp/consul/releases/tag/v1.11.7)

[1.11] Post-release updates

---

CHANGELOG.md
version/version.go

Adds all the changelog entries from today's release: [`1.12.3`](https://github.com/hashicorp/consul/releases/tag/v1.12.3).
The entries should match what is shown on the release page.
* [`1.12.3`](https://github.com/hashicorp/consul/releases/tag/v1.12.3)

[1.12] Post-release updates

---

ui/packages/consul-ui/app/components/data-loader/README.mdx
ui/packages/consul-ui/app/components/data-loader/chart.xstate.js
ui/packages/consul-ui/app/components/data-loader/index.hbs
ui/packages/consul-ui/app/components/data-loader/index.js
ui/packages/consul-ui/app/components/data-source/README.mdx
ui/packages/consul-ui/app/components/data-source/index.hbs
ui/packages/consul-ui/app/components/data-source/index.js

This PR threads through an `invalidate` method from `DataSource` through to `DataLoader` and exposes it there.
The `invalidate` method always existed but we've never used it/needed it, and is used to notify the DataSource/Loader that the data associated with it is invalidated. The result of doing this means that the DataSource will immediately try to request a new set of data.
A little background here: As we usually use our blocking query support, we've never really needed to invalidate the data associated with DataSources as blocking queries always keep our data fresh.
As we are using more and more traditional polling for UI liveness, data could be out of date during the interval of the poll, by using `invalidate` you can force an immediate request for data, which will continue to poll …

ui: Thread through data-source invalidate method

---

website/content/docs/upgrading/index.mdx

Upgrading Envoy instance versions was not previously included in the upgrade docs.
Someone from engineering should review this in addition to a member of the docs team.

docs: add Envoy upgrade step to std upgrade docs

---

ui/packages/consul-ui/app/adapters/node.js
ui/packages/consul-ui/app/adapters/service.js
ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/tests/acceptance/dc/intentions/navigation.feature
ui/packages/consul-ui/tests/acceptance/dc/nodes/index.feature
ui/packages/consul-ui/tests/acceptance/dc/services/list.feature
ui/packages/consul-ui/tests/acceptance/page-navigation.feature
ui/packages/consul-ui/tests/acceptance/token-header.feature
ui/packages/consul-ui/tests/helpers/set-cookies.js
ui/packages/consul-ui/tests/integration/adapters/node-test.js
ui/packages/consul-ui/tests/integration/adapters/service-test.js

Removes the unneeded `with-peers`-query-param when requesting `service`s and `node`s for their respective listing pages.
cc @johncowen

ui: remove with-peers query param

---

agent/peering_endpoint.go
api/peering.go
proto/pbpeering/peering.gen.go

The functionality exists within Consul Enterprise but these changes are necessary in the common code to support peering partitions.

Enable API support for partitions during peering establishment

---

agent/grpc-external/services/peerstream/health_snapshot.go
agent/grpc-external/services/peerstream/health_snapshot_test.go
agent/grpc-external/services/peerstream/replication.go

Node IDs are not required in Consul's data model (this is unfortunate and has caused us many issues over the years). 
Therefore the peering code cannot require the node id. This PR transitions our healthSnapshot tracking of nodes to use the only unique identifying information a node has as the key for the map to track nodes - the nodes name.
* Unit tests were updated to include nodes without IDs to prove that the health snapshot gets built properly.
Manual Test:
1. Setup peering.
2. Export a service that doesn't exist.
3. Create that service through the API without specifying the node id. Before this would cause the peer importing the service to panic. Now it doesn't

Fix panic for replicating a node without a Node ID

---

internal/tools/proto-gen-rpc-glue/e2e/source.pb.go
internal/tools/proto-gen-rpc-glue/e2e/source.rpcglue.pb.go.golden
internal/tools/proto-gen-rpc-glue/main.go
proto/pbpeering/peering.pb.go
proto/pbpeering/peering.proto
proto/pbpeering/peering.rpcglue.pb.go

Freddy was mentioning that we need to add a warning about the constraint of having the leader field read request for peering calls.
This adds a TODO to add that context.

peering: add warning about AllowStaleRead

---

agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/replication.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/rpc/peering/service.go

For now, we are choosing to track the imported services count in the stream tracker shim. In the future, the tracking should make its way through raft.
* stream tracker tests updated
* NOTE: `leader_peering_test` contains a more e2e test approach to peering sync; let's keep this test in the leader for now since the `PeeringList` call needs to always get served by the leader

peering: track imported services

---

agent/agent.go
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/peering_backend.go
agent/consul/server_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/rpc/peering/service_test.go
test/integration/connect/envoy/case-wanfed-gw/primary/common.hcl
test/integration/connect/envoy/case-wanfed-gw/primary/server.hcl
test/integration/connect/envoy/case-wanfed-gw/secondary/common.hcl
tlsutil/config.go
website/content/docs/agent/config/config-files.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Ensure that the peer stream replication rpc can successfully be used with TLS activated.
Also:
- If key material is configured for the gRPC port but HTTPS is not enabled now TLS will still be activated for the gRPC port.
- peerstream replication stream opened by the establishing-side will now ignore `grpc.WithBlock` so that TLS errors will bubble up instead of being awkwardly delayed or suppressed

server: ensure peer replication can successfully use TLS over external gRPC

---

agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/stream_resources.go

If the stream is closed unexpectedly (i.e. when we haven't received
a terminated message), the dialer should attempt to re-establish the
stream.
Previously, the `HandleStream` would return `nil` when the stream
was closed. The caller then assumed the stream was terminated on purpose
and so didn't reconnect when instead it was stopped unexpectedly and
the dialer should have attempted to reconnect.
Start two servers, peer them, stop the accepting peer server and then restart it, see that the dialing server never reestablishes its connection.

peerstream: dialer should reconnect when stream closes 

---

agent/grpc-external/services/peerstream/stream_test.go

This ensures the test cases pass in both OSS and Enterprise. Example of how the assertion fails in enterprise:
```
Diff:
--- Expected
+++ Actual
@@ -36,3 +36,3 @@
ImportedServices: (map[string]struct {}) (len=1) {
-  (string) (len=3) "api": (struct {}) {
+  (string) (len=19) "default/default/api": (struct {}) {
}
```

peerstream: fix test assertions

---

ui/packages/consul-peerings/app/components/consul/peer/form/initiate/README.mdx
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/actions/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/fieldsets/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs
ui/packages/consul-ui/translations/common/en-us.yaml

[Minimal Rendered Docs](https://consul-ui-staging-5mojgk8oa-hashicorp.vercel.app/ui/docs/consul-peerings/consul/peer/form/initiate)
This adds a 'Peer Initiation Form' for initiating the peering connection between two peers using a peering token. 
Notes:
1. The form is split into `Fieldsets` and `Actions` contextual components, this means that the buttons/actions for the form don't necessarily need to be directly under the 'fieldsets'. In our upcoming case they need to be in a completely separate DOM area in our modals footer. This (along with the use of the HTML5 `form=""` attribute) means we can move the buttons/actons whereever we need them. Whilst this is perfect for this use case, all our forms should ideally use this approach meaning the buttons to control the form can be anywhere on …

ui: Adds Peer initiation form

---

ui/packages/consul-peerings/app/components/consul/peer/form/generate/README.mdx
ui/packages/consul-peerings/app/components/consul/peer/form/generate/actions/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/generate/chart.xstate.js
ui/packages/consul-peerings/app/components/consul/peer/form/generate/fieldsets/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs

[Minimal Rendered Docs](https://consul-ui-staging-eu2os86zq-hashicorp.vercel.app/ui/docs/consul-peerings/consul/peer/form/generate)
Similar to https://github.com/hashicorp/consul/pull/13754 this PR adds a Peer Token Generation form.
Notes (similar to #13754):
1. The form is split into Fieldsets and Actions contextual components, this means that the buttons/actions for the form don't necessarily need to be directly under the 'fieldsets'. In our upcoming case they need to be in a completely separate DOM area in our modals footer. This (along with the use of the HTML5 form="" attribute) means we can move the buttons/actons whereever we need them. Whilst this is perfect for this use case, all our forms should ideally use this approach meaning the buttons to control the form can be anywhere on …

ui: Add peer token generation form

---

website/content/docs/connect/cluster-peering/k8s.mdx
website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
website/content/docs/k8s/installation/vault/wan-federation.mdx
website/data/docs-nav-data.json

As part of the release process, updating the website requires merging changes from `origin/stable-website`. When I did this, there was one conflict to resolve which is included in this PR. The only difference was indentation for the items in the "Prerequisites" section and the addition of the `global.image` property in the helm values in the `website/content/docs/connect/cluster-peering/k8s.mdx` file. 
The rest of the changes are already present on the website, they just hadn't been merged back to `release/1.12.x` yet.
This should match what is currently deployed to the website.
See https://www.consul.io/docs/connect/cluster-peering/k8s.

docs: Resolve conflicts in docs

---

agent/grpc-external/server.go

The client is set to send keepalive pings every 30s. The server
keepalive enforcement must be set to a number less than that,
otherwise it will disconnect clients for sending pings too often.
MinTime governs the minimum amount of time between pings.
Need to set this to match the client policy set in https://github.com/hashicorp/consul/pull/13733/files. Otherwise it defaults to 5m which caused the server to disconnect in my testing. This setting matches the internal gRPC server (https://github.com/hashicorp/consul/blob/main/agent/grpc-internal/handler.go#L37-L39).
Without this I'm seeing connection resets in my testing:
```
INFO[0108] [transport] transport: Got too many pings from the client, closing the connection.  system=system
```
See also https://www.evanjones.ca/grpc-is-tricky.html.

peerstream: set keepalive enforcement to 15s

---

.changelog/13787.txt
command/acl/token/read/token_read.go

Fix panic on acl token read with -self and -expanded

---

ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/pageobject.js
ui/packages/consul-ui/tests/integration/components/hashicorp-consul-test.js

Fixes current failures in CI that were missed because people with non-contributor rights, like yours truly, won't have the CI test-suite executed for them.
Here's the link to the actual failure in the OSS test-suite: https://github.com/hashicorp/consul/runs/7402516620?check_suite_focus=true#step:6:1401
Link to one of the failures in ENT test-suite: https://github.com/hashicorp/consul/runs/7402525270?check_suite_focus=true#step:6:5038 ← you can see that all 4 test-failures are failing because of the same reason as OSS version is failing.
The fix here is to make the datacenter-item selector in the datacenter-selector-page-object be more specific. I introduced a new `data-test-`-attribute for that that only gets added to the actual datacenter items in the listing but not the …

ui: chore - fix CI test-suite

---

build-support/scripts/devtools.sh

I had protoc-gen-go installed through `google.golang.org/protobuf` instead of
`github.com/golang/protobuf` and `make proto` was failing silently.
This change will ensure you get an error:
```
protoc-gen-go is already installed by module "google.golang.org/protobuf" but
should be installed by module "github.com/golang/protobuf".
Delete it and re-run to re-install.
```

makefile: give better error for tool installed by wrong package

---

website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

Updated the Single DC Multi K8S doc to have the following details:
* Reference to supported network offerings of various hosted K8S providers
* Added a command to explicitly switch the kubectl context.

Update Single DC Multi K8S doc

---

agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/replication.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/rpc/peering/service.go
api/peering_test.go

This is a small refactor that addresses:
* refactoring the way we copy a peer on `PeeringRead` and `PeeringList`
* punted/ missed feedback from https://github.com/hashicorp/consul/pull/13619 & https://github.com/hashicorp/consul/pull/13784

peering: refactor reconcile, cleanup

---

agent/proxycfg/connect_proxy.go
agent/proxycfg/snapshot.go
agent/proxycfg/testing_peering.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/transparent-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/endpoints/transparent-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/endpoints/transparent-proxy.latest.golden
agent/xds/testdata/listeners/transparent-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/routes/transparent-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/routes/transparent-proxy.latest.golden

Peered upstreams has a separate loop in xds from discovery chain upstreams. This PR adds similar but slightly modified code to add filters for peered upstream listeners, clusters, and endpoints in the case of transparent proxy.
* Added golden test

Make envoy resources for inferred peered upstreams

---

ui/packages/consul-peerings/app/components/consul/peer/form/README.mdx
ui/packages/consul-peerings/app/components/consul/peer/form/chart.xstate.js
ui/packages/consul-peerings/app/components/consul/peer/form/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/index.scss
ui/packages/consul-peerings/app/components/consul/peer/index.scss

[Minimal Rendered Docs](https://consul-ui-staging-abzatq35a-hashicorp.vercel.app/ui/docs/consul-peerings/consul/peer/form)
Adds PeerForm. A wrapping 'form' that wraps all of the various states of the peer establishment forms into one easier to use component. Similarly to other related PRs this PR yields separate fieldsets and actions for the form depending on the selected tab.

ui: Add Peer Form

---

ui/packages/consul-ui/app/components/consul/bucket/list/README.mdx
ui/packages/consul-ui/app/components/consul/bucket/list/index.js
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/tests/integration/components/consul/bucket/list-test.js

This PR updates the bucket-list component to never display `partition` and `peer` at the same time. Whenever we have a peer the bucket-list component will only display a peer and the corresponding namespace.
When partitions and namespaces are not supported (OSS) we won't surface the namespace anymore.
This PR:
* Updates the bucket-list component as described above
* Adds tests for the bucket-list component
* Updates the intentions table to use the bucket-list to surface Source information
* this PR does not update the intentions table destination to use the bucket-list component as it won't surface peering information and we don't want to change this behavior
cc @johncowen

ui: no partition and peer in bucket-list at the same time

---

website/content/docs/agent/config/config-files.mdx

The current agent config options page suggests using the token query param in some places, even though that's not best practice. This PR links to the best practices.
Preview: https://consul-fohc2lxya-hashicorp.vercel.app/docs/agent/config/config-files#acl_tokens_default

docs: suggest using token header, not query param

---

agent/agent.go
agent/consul/state/catalog.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/peered_upstreams.go
agent/proxycfg-glue/peered_upstreams_test.go

This is the OSS portion of enterprise PR 2352.
It adds a server-local implementation of the `proxycfg.PeeredUpstreams` interface based on a blocking query against the server's state store.
It also fixes an omission in the Virtual IP freeing logic where we were never updating the max index (and therefore blocking queries against `VirtualIPsForAllImportedServices` would not return on service deletion).
- Run the Envoy integration tests ⚙️

[OSS] proxycfg-glue: server-local implementation of `PeeredUpstreams`

---

ui/packages/consul-peerings/app/templates/dc/peers/index.hbs

Updates the empty state copy of the peerings page to the latest copy. It will now also display differently based on the fact if the user is using OSS or not.
cc @johncowen

ui: Update peerings empty state copy

---

ui/packages/consul-ui/app/components/consul/peer/info/index.hbs
ui/packages/consul-ui/app/components/consul/peer/info/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/tests/pages/dc/services/show.js

Surfaces the peer name for a peered node in the `nodes.show`-view
cc @johncowen

ui: Surface peer info in nodes.show view

---

ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show-with-slashes.feature

Peered service-instances will now only surface the `Instances` and `Tags` Tab on the `services.show`-view.
This change made the `show-with-slashes`-feature test fail. That is because the first service that we load from the mock-api by default, when the peering feature is on, will be peered. To "fix" the failing test, I updated the URL that we are checking against in the test. A peered service will not show the `topology`-tab anymore and show the `instances`-tab instead. Because the URL isn't relevant for the test, this feels fine and was easier than to change the mocked service in the test.
cc @johncowen

ui: peered services only show instance- and tags-tabs 

---

ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
ui/packages/consul-peerings/vendor/consul-peerings/routes.js

This PR removes all the peering detail views, peer rows are now not clickable, but peers are still deletable.

ui: Remove peering detail page

---

agent/grpc-external/services/peerstream/server.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go

Add a heartbeating mechanism to peering streams.
Follows closely waypoint's approach: https://github.com/hashicorp/waypoint/pull/98
Senders and receivers each send heartbeats at a defined interval (15s). If a heartbeat isn't received for 2 minutes, the connection is closed.
To dos in future PRs:
* Track last receipt of any message (including heartbeats) in the peering status
* Add jitter to heartbeat sending

peering: Add heartbeating to peering streams

---

.circleci/config.yml

In #13783 I accidentally bumped the Golang version to 1.18. This resets it back to 1.17.12 which is the latest for the 1.17 release series.
CI should pass.
[go1.17 version history](https://go.dev/doc/devel/release#go1.17)

[1.12] Set Go version to latest 1.17 series

---

agent/consul/prepared_query/template_test.go
agent/consul/prepared_query/walk_test.go
agent/consul/prepared_query_endpoint.go
agent/consul/prepared_query_endpoint_test.go
agent/dns_test.go
agent/prepared_query_endpoint_test.go
agent/structs/prepared_query.go
api/prepared_query.go

Add cluster peering failover support to prepared queries.
* [Unit test validations](https://github.com/hashicorp/consul/compare/prepared-query-peering-failover?expand=1#diff-9865c52cf7cb8ef7edb4f8980519eef139049c970208a1581eb38bb42f708818R91-R105)
* [Unit test peering failover](https://github.com/hashicorp/consul/compare/prepared-query-peering-failover?expand=1#diff-9865c52cf7cb8ef7edb4f8980519eef139049c970208a1581eb38bb42f708818R3301)
* [Integration test peering failover](https://github.com/hashicorp/consul/compare/prepared-query-peering-failover?expand=1#diff-9865c52cf7cb8ef7edb4f8980519eef139049c970208a1581eb38bb42f708818R1468)

Add Cluster Peering Failover Support to Prepared Queries

---

agent/agent.go
agent/proxycfg-glue/exported_peered_services.go
agent/proxycfg-glue/exported_peered_services_test.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/helpers_test.go

This is the OSS portion of enterprise PR 2377.
Adds a server-local implementation of the `proxycfg.ExportedPeeredServices` interface that sources data from a blocking query against the server's state store.
* Run the Envoy integration tests 🍀

[OSS] proxycfg-glue: server-local implementation of `ExportedPeeredServices`

---

ui/packages/consul-ui/app/components/topology-metrics/index.js

Improves the empty downstreams message in service-topology to only mention "imported services" when the peering feature is enabled.

ui: Improve peered service empty downstreams message

---

agent/consul/leader.go
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/server.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/setup.go
logging/names.go

This patch adds a `consul_peering_exported_services` metric with labels for the `peer name` and `partition` (for ENT). This, in addition to more metrics, will help drive a better understanding about the overall state of a peering.
To be clear, we can probably add more metrics using this pattern but we are starting with just the one for now.
* `leader_peering_test` with mock sink and metrics instance.
* ~[ ] add external facing docs about the metric~ --> adding this as a separate PR

peering: emit exported services count metric

---

acl/acl_test.go
acl/authorizer.go
acl/authorizer_test.go
acl/chained_authorizer.go
acl/chained_authorizer_test.go
acl/policy.go
acl/policy_authorizer.go
acl/policy_authorizer_test.go
acl/policy_merger.go
acl/policy_test.go
acl/static_authorizer.go
agent/acl_endpoint_test.go
agent/structs/acl.go

OSS Backport of [ENT-2281](https://github.com/hashicorp/consul-enterprise/pull/2281)
This commit adds a new ACL rule named "peering" to authorize
actions taken against peering-related endpoints.
The "peering" rule has several key properties:
- It is scoped to a partition, and MUST be defined in the default
namespace.
- Its access level must be "read', "write", or "deny".
- Granting an access level will apply to all peerings. This ACL rule
cannot be used to selective grant access to some peerings but not
others.
- If the peering rule is not specified, we fall back to the "operator"
rule and then the default ACL rule.
* Tested with unit tests

[OSS] Add new peering ACL rule

---

.changelog/13847.txt
agent/proxycfg/ingress_gateway.go
agent/proxycfg/upstreams.go

This PR fixes 2 separate goroutine leaks happening in `agent/proxycfg` that occur when registering an ingress gateway:
- Whenever the list of gateway services was updated, a new goroutine was spawned via `cache.Notify()` for every service (even ones that were already being watched) because we were wrongly checking the `WatchedDiscoveryChains` in `snap.ConnectProxy` instead of `snap.IngressGateway`.
- When cleaning up services removed from the gateway services list, we were only canceling the watches for discovery chains and not their associated upstreams as well.

Fix goroutine leaks in proxycfg when using ingress gateway

---

agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/config.go
agent/consul/leader.go
agent/consul/leader_peering_test.go
agent/consul/server.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
docs/config/checklist-adding-config-fields.md
website/content/docs/agent/config/config-files.mdx

Add config:
```
peering {
enabled = true
}
```
Defaults to true. When disabled:
1. All peering RPC endpoints will return an error
2. Leader won't start its peering establishment goroutines
3. Leader won't start its peering deletion goroutines
translate.
`agent/config/testdata/full-config.*`, which should cause the `TestLoad_FullConfig` test to fail.
Then update the expected value in `TestLoad_FullConfig` in
`agent/config/runtime_test.go` to make the test pass again.
the expected value for `TestRuntimeConfig_Sanitize`. Look at `git diff` to
make sure the value changed as you expect.
some cases or with some values (often true).
`agent/config/runtime_test.go`.
`agent/config/runtime_test.go`.
any state the feature needs changing. This needs …

peering: add config to enable/disable peering

---

agent/uiserver/ui_template_data.go
agent/uiserver/uiserver_test.go

The UI has support for peering but only when told it is enabled. This PR tells the UI that peering is enabled or disabled based on the configuration flag to enable or disable it.

Enable/Disable Peering Support in the UI

---

website/content/docs/agent/config/config-files.mdx

Change wording because it does have effect on clients because it
disables peering in the UI served from that client.

Re-document peering disabled

---

.gitignore
agent/consul/config_endpoint_test.go
agent/consul/helper_test.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog_events_test.go
agent/proxycfg/snapshot.go
agent/proxycfg/testing_terminating_gateway.go
agent/proxycfg/testing_tproxy.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/routes.go
agent/xds/testdata/clusters/transparent-proxy-destination.latest.golden
agent/xds/testdata/clusters/transparent-proxy-terminating-gateway-destinations-only.latest.golden
agent/xds/testdata/endpoints/transparent-proxy-destination.latest.golden
agent/xds/testdata/listeners/transparent-proxy-destination.latest.golden
agent/xds/testdata/listeners/transparent-proxy-terminating-gateway-destinations-only.latest.golden
agent/xds/testdata/routes/transparent-proxy-terminating-gateway-destinations-only.latest.golden
api/config_entry.go
api/config_entry_test.go
command/helpers/helpers_test.go

Since we can't support IP CIDR blocks at the moment for Egress Destinations in t-proxy mode, this PR converts the `address` field of a `destination` into an array that can handle multiple entries. The PR also attempts to clean up references to IP CIDR blocks in the test cases since this won't be supported.
* See test cases in line with the PR.

[OSS] feat: dest addresses can be an array

---

ui/packages/consul-ui/app/controllers/_peered-resource.js
ui/packages/consul-ui/app/controllers/dc/nodes/index.js
ui/packages/consul-ui/app/controllers/dc/services/index.js
ui/packages/consul-ui/app/search/predicates/node.js
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/vendor/consul-ui/routes.js

Follow-up of https://github.com/hashicorp/consul/pull/13771 to make the tests execute on CI - couldn't find a way to do this in the old PR.
For discussion please follow the [old PR](https://github.com/hashicorp/consul/pull/13771). Nothing has changed - I'm just creating a new PR so that tests execute properly on CI.
__TLDR;__
This PR:
* makes nodes searchable by peer-name
* fixes peer-name showing up in services search although peers feature was turned off

ui: add peers to node search

---

agent/consul/state/peering.go
agent/peering_endpoint_test.go
agent/rpc/peering/service.go

Fixes a bug where if the generate token is called twice, the second call upserts the zero-value (undefined) of PeeringState.
* Added a test suite for calling generate token at various points in a peer's lifecycle

Preserve PeeringState on upsert

---

agent/proxycfg/ingress_gateway.go

This removes an unneeded debug log statement that got left in by https://github.com/hashicorp/consul/pull/13847

Remove extra logging from ingress upstream watch shutdown

---

agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/grpc-external/services/peerstream/stream_tracker_test.go
agent/rpc/peering/service.go

When the stream exits due to an error, e.g. the heartbeat failed or the connection quit, track this in the tracker. When the Read or List RPCs are called, use the tracker to set the status as failing.
Changes:
1. tracker: Differentiate a connection ending gracefully from a connection ending due to error by adding a field `DisconnectErrorMessage` that will be set to an error string if the connection ended due to an error.
2. tracker: rename `Disconnected()` => `DisconnectedGracefully()` and add `DisconnectedDueToErr()`
3. stream_resources: wrap `HandleStream()` to correctly set the tracker status based on why the connection was ended
4. add `TrackReceiveHeartbeat()`. This isn't used anywhere yet but can be used for better status info later.
5. rename `TrackReceiveSuccess() => …

peering: read endpoints can now return failing status

---

.github/workflows/build.yml

Add a build job to publish UBI images on DockerHub. This is to make it easier to test on OpenShift because you don't need a red hat account to be able to use those images

build: add a job to build and push UBI images to DockerHub

---

agent/rpc/peering/testing.go
agent/rpc/peering/validate.go
agent/rpc/peering/validate_test.go

When supplying an external address to put into the peering token, the external address could be a hostname of a load balancer, which for example is the default in EKS. We'd want to allow hostname based addresses in the peering token in this case. 
I was able to test a hostname based load balancer with this change and it worked as the dialer does not require an IP address.

Allow hostname based addresses in peering token

---

ui/packages/consul-ui/app/abilities/intention.js
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/models/intention.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/delete.feature
ui/packages/consul-ui/tests/acceptance/dc/intentions/navigation.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions/index.feature

Peered intentions are currently readonly. Clicking the rows will now take you to a readonly detail page based on the fact that intentions with SourcePeer set are not writable.
/cc @LevelbossMIke

ui: Make peered intentions read-only

---

website/content/commands/acl/auth-method/create.mdx

A number of our CLI docs pages show the command-specific options below the list of general options that apply across many commands. (Example screenshot below from [keyring command](https://www.consul.io/commands/keyring#usage))
I see several advantages to moving command-specific options above the general ones:
- The unique behavior and use of the command is easier to understand. The explanation of what the command does is adjacent to its flags, rather than being separated by general stuff.
- In many cases, the general flags will by familiar (from using other commands) are already handled (such as by setting environment variables for the Consul address and token).
[Preview](https://consul-6qvyke6un-hashicorp.vercel.app/commands/acl/auth-method/create)
This PR currently shows the proposed …

Docs: Show CLI command-specific options before general options

---

agent/consul/catalog_endpoint.go

Normally, registering a service, we use "name". However, when register service using catalog endpoint, the key of service
name actually should be "service". 
Adding this information to the error message will help user quickly fix in the request.

chore: clarify the error message: service.service must not be empty

---

agent/consul/helper_test.go
agent/consul/internal_endpoint_test.go
agent/consul/leader_connect_test.go
agent/consul/state/peering.go
agent/proxycfg-glue/exported_peered_services_test.go
connect/proxy/config_test.go

The watch is established in a background goroutine and the first assertion proves that the watcher is active so there is no reason for the update to happen in a racy goroutine.
Note that this does not completely remove the race condition as the first call to testGetConfigValTimeout could time out before a config is returned.
The ServiceName slice was being sourced from a non-deterministic `SliceOfKeys` function.
Updated code to sort the names deterministically so tests don't flake on the slice order.
Shortened the polling period for VIP metadata check and added retries (aligned with existing VIP tests)
This one is one of the top flaked tests but ONLY in arm64 environments. I haven't found the root cause but assuming the environment is low on resources, the 16 parallel tests spinning up …

Fix some flaky tests

---

.github/workflows/nightly-test-1.13.x.yaml

In preparation for creating a new release series for 1.13, this adds a new nightly job for testing against the new release branch. This needs to land on `main` vs the release branch, so I'll just plan to merge it around the time I create the release branch. It won't run until 4am UTC  which isn't for another 9 hours from the time I am creating this PR. Worst case is that it gets merged and ran before the release branch actually exists in which case, the job will just fail. We can still re-run it.
Signed-off-by: Evan Culver <eculver@hashicorp.com>

ci: Add nightly test workflow for 1.13, remove 1.10

---

agent/consul/state/state_store_test.go
agent/consul/state/usage.go
agent/consul/state/usage_test.go
agent/grpc-external/services/peerstream/health_snapshot.go

Services/nodes that are imported from other peers are stored in
state. We don't want to count those as part of our own cluster's usage.
A follow-up PR will be added to track these imported resources separately.

peering: don't track imported services/nodes in usage

---

command/kv/imp/kv_import.go
command/kv/imp/kv_import_test.go

- when importing an empty directory like foo/, the import
command will remove the trailing /, making it a
non-directory key.
- This change fixes the bug by adding back the / if
the imported key is an directory
Fix #13562

fix (cli): import empty directory to kv

---

.github/workflows/nightly-test-1.13.x.yaml

I got the `BRANCH_NAME` wrong in the original addition of this new workflow for 1.13. Apparently, it can't contain a '/' since it's used in the `upload-artifact` action. 
- I added a temporary branch trigger for my dev branch to ensure it runs as expected. I should have done this in the first place.
This only needs to land on `main` since it's triggered on a cron and the workflow itself knows to checkout the appropriate branch. This means I don't need to backport it to any release branches.

ci: Use correct branch name for 1.13 nightly test

---

agent/rpc/peering/service.go

This was introduced in `ef7edd79c4515789f767c28c36b443da737a0837` in ENT.
Essentially, `peering` objects from the state store come up with an empty string partition `""`. This overrides that to be called `default`. Maybe there's a better struct / way to do this so please comment if so!

[sync] fix empty partitions matching

---

agent/proxycfg/testing_terminating_gateway.go
agent/xds/clusters.go
agent/xds/testdata/clusters/transparent-proxy-terminating-gateway-destinations-only.latest.golden
agent/xds/testdata/listeners/transparent-proxy-terminating-gateway-destinations-only.latest.golden

This add injections of the gateway service addons (SNI, ca file and key file) when creating the cluster for a destination in the gateway side.
Added test to verify that the SNI and ca file are injected correctly

inject gateway addons to destination clusters

---

connect/proxy/listener.go

The previous ordering of defers meant the listener's connWG could fire and wake up other goroutines before the connection closed. Unsure if this caused any real bugs but this commit should make the code more correct.
* No behavioral change

Ensure connections are closed before WaitGroup marked as done

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go

When running with an LB in front of the Consul servers, dialers need to retry their requests until they land on a leader server. The default retry backoff was too long because it started at 2s and went exponentially from there: 4s, 8s, etc. This change adds new retry logic for specific errors to retry quickly.
I opted to treat all `FailedPrecondition` errors as quick-retry errors because they should all be resolved quickly.
Changes:
1. replace `retryLoopBackoff` with `retryLoopBackoffPeering` that implements the new retry mechanic
2. change logging everywhere we receive a `FailedPrecondition` error to not log as an error because they aren't indicative of an actual problem
3. refactor the main `HandleStream()` loop to add a new channel for errors. Previously, any error received from …

peering: retry establishing connection more quickly on certain errors

---

website/content/docs/k8s/annotations-and-labels.mdx

The existing link has no relevance to prepared queries and is misleading (can be interpreted as meaning that prepared query annotations are not supported).

docs: fix k8s prepared query upstream link

---

agent/proxycfg/testing_tproxy.go
agent/xds/listeners.go
agent/xds/resources_test.go
agent/xds/routes.go
agent/xds/testdata/clusters/transparent-proxy-destination-http.latest.golden
agent/xds/testdata/endpoints/transparent-proxy-destination-http.latest.golden
agent/xds/testdata/listeners/transparent-proxy-destination-http.latest.golden
agent/xds/testdata/routes/transparent-proxy-destination-http.latest.golden

This PR add the ability to perform http proxy to destination. 
Compared to TCP proxy where we use server_name to match on the destination and the port for non TLS traffic the server_name field is not populated by the http_inspector filter in envoy so we need a different way of matching traffic.
To do so we are matching on ports only at the TCP level and we are using the http_manager to match on the domain name for each destination and proxy traffic to the right cluster.
- FilterMatch will match on the common Port (for all destinations) 
- each port matching will have multiple virtual hosts which will match on the domain name and proxy to the right cluster.
- use RDS to generate the right routes in the virtual hosts.
This adds a limitation that the same port cannot be used for TCP and http …

Tgtwy egress HTTP support

---

agent/local/state.go

Although the metric is defined, there is no code which ever sets its
value - the code in question is genuinely asymmetric - there are 3 types
of object for which registration can be tracked, but only 2 for which
deregistration can be tracked.
This is already reflected in the documentation at:
https://www.consul.io/docs/agent/telemetry#metrics-reference
It's just this part of the code which is out of sync.

Delete definition of metric `consul.acl.blocked.node.deregistration`

---

.github/workflows/build.yml
.release/ci.hcl

This adds a `release/**` pattern to match all of our release branches.
It was [recently announced](https://hashicorp.atlassian.net/wiki/spaces/ENSV/pages/2383447278/July+15+2022+-+Pattern+matching+now+supported+for+branch+names+in+ci.hcl) that pattern matching is now supported in CRT configuration for branch names. What this means is that with a pattern for our release branches we will no longer have to update `.release/ci.hcl` whenever we need to trigger CRT for a new release branch. 
This is one of the patterns listed in their examples, so I would imagine it works. We will know once we push a change to the new `release/1.13.x` branch.
Also, I triggered the workflows for my dev branch (technically `eculver/**` to express the wildcard case) which can be seen here: …

ci: Use pattern for CRT release branch config

---

agent/xds/clusters.go
agent/xds/testdata/clusters/transparent-proxy-terminating-gateway-destinations-only.latest.golden

Currently, there are issues with Destination hostnames that resolve to IPV6 addresses.  The terminating gateway can resolve the names into addresses, but when dialing the IPV6 address, it reports the connection unreachable. 
We still need to consider if hardcoding this to IPV4 is a good long-term decision.
* try contacting `api.myip.com` using Destinations.

fix: ipv4 destination dns resolution

---

agent/consul/config_endpoint_test.go
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go

* Avoid logging StreamSecretID
* Wrap additional errors in stream handler
* Fix flakiness in leader test and rename servers for clarity. There was
a race condition where the peering was being deleted in the test
after the initial handling in `StreamResources` but before the stream was active. Now the test waits for the stream to be
connected on both sides before deleting the associated peering.
* Spotted the secret in peering leader unit test logs
`StreamSecretID` was introduced in #13977

Various peering fixes

---

agent/proxycfg-sources/catalog/config_source.go

Fixes a bug where a service getting deleted from the catalog would cause the `ConfigSource` to spin in a hot loop attempting to look up the service.
This is because we were returning a nil `WatchSet` which would always unblock the select.
Kudos to @freddygv for discovering this!
The easiest way to reproduce this is to run a dev server, register a service via the API, start a connect proxy for it, and then restart the agent (clearing out the in-memory state).

proxycfg-sources: fix hot loop when service not found in catalog

---

agent/proxycfg-glue/intentions.go

testing with 1.13.x branch we noticed this error in consul-k8s tests:
`2022-08-01T22:43:59.619Z [ERROR] agent.client: RPC failed to server: method=Intention.Match server=10.244.0.22:8300 error="rpc error making call: Permission denied: token with AccessorID '00000000-0000-0000-0000-000000000002' lacks permission 'intention:read' on "static-server" in partition "default" in namespace "ns1""`
This was happening because the service token was not propagated correctly in the Intention cache type which made the cache fallback to the agent token (anonymous token) which don't have the right permissions.
[This](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/6458/workflows/83324140-cf90-4b4c-a195-bf0bd6a4ba7b/jobs/54618/artifacts) is one reproduction, I was able to run the test …

add token to the request when creating a cacheIntentions query

---

agent/agent_endpoint.go
agent/sidecar_service_test.go
agent/structs/structs.go
agent/structs/structs_test.go

[PR #12881](https://github.com/hashicorp/consul/pull/12881) Introduced a requirement for either port or socket path to be provided in all requests. Due to [a race in automatic port assignment](https://github.com/hashicorp/consul/issues/8254) within the agent, automatic assignment needs [to be moved from the request-building stage to the locked registration stage post-validation](https://github.com/hashicorp/consul/pull/13928). One solution (this PR) is to exempt the port requirement from request validation when the request is coming from an agent that is trying to do auto-assignment.
* Manually registering a service from the agent still works with and without a port specified.
* Existing unit tests seem to cover many cases, and pass without need for changes.
[PR …

Separate port and socket path validation for local agent

---

ui/packages/consul-peerings/app/components/consul/peer/form/generate/chart.xstate.js
ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs

Erroneously removed here https://github.com/hashicorp/consul/pull/13792#discussion_r924496973
This PR makes the [Generate another token] button work (see below)

ui: Re-hook up regenerate button

---

ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
ui/packages/consul-ui/app/services/repository/peer.js

This PR fixes some things that broke the peering UI
* Api contract was changed - we can't send the `Datacenter` attribute anymore when creating a token / establishing a peer
* We were still surfacing a links to `peers.edit` which was breaking the list and surfacing an error whenever we established a peer.

ui: peering UI fixes - api contract change / wrong link in peerings list

---

command/services/deregister/deregister.go

When the deregister cli fails, the error message shows `Error registering service`, which should be `Error deregistering service`.
Run cli to deregister any non-existent service

fix(cli): error message in service deregister subcommand

---

ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs
ui/packages/consul-ui/app/components/data-writer/index.hbs
ui/packages/consul-ui/app/components/data-writer/index.js

We started out with our application using `ember-data`, but for many reasons we are slowly moving away from using that. As well as a few other benefits it also means our errors (API ones and any others) are all standard shaped errors - all errors are the same standard recognisable javascript errors.
This PR alters our `DataWriter` to work with standard shaped errors as well as `ember-data` shaped ones (as it did previously). This means we can keep deprecating our `ember-data` usage as we go. Eventually, if we get to the point we we aren't using `ember-data` shaped errors anymore, we can remove the majority of this code and just support standard javascript errors.
**Note**: We purposefully used an old style `action` here to keep consistent with the style/APIs already being used in the …

ui: Make DataWriter also deal with more standard shaped errors

---

ui/packages/consul-peerings/app/templates/dc/peers/index.hbs

Updates the links for peering docs to some actual peering related docs.
Follow-up from https://github.com/hashicorp/consul/pull/13757
- [Documentation on Peers](https://www.consul.io/docs/connect/cluster-peering)
- [Take the tutorial](https://www.consul.io/docs/connect/cluster-peering/create-manage-peering)

ui: Update peerings docs links

---

.release/ci.hcl

This PR introduces a new CRT workflow event in the ci.hcl file, post-publish-website and this event handles the dispatching of an API call (HTTP POST) to the mktg-dev endpoint. This is responsible for automating the triggering of marketing-dev's versioned docs pipeline to release versioned docs for product repos.
This only gets triggered as a post-publish event after you release your artifacts to production. The workflow should wait for the docs to be published and report passed/failed status.
This should not be merged into ENT repos as the versioned docs only live in OSS repos. (if you have an automated OSS-->ENT merge set up, please let me know to follow up with a PR to remove this event out of the ENT repo) 
I will merge this PR in next Monday (07/25)-- this is a new event set up so …

introduces the post publish website event

---

test/integration/connect/envoy/run-tests.sh

Our integration tests regularly fail on docker build steps due to network issues (io timeout, EOF, TLS timeout). I'm adding retries to our build steps to make the tests more consistent.
```
ERR: command exited with status 1
command:   docker build -t test-sds-server -f Dockerfile-test-sds-server test-sds-server
line:      575
function:  suite_setup
called at: ./run-tests.sh:896
main_test.go:21: command failed: exit status 1
--- FAIL: TestEnvoy (23.68s)
```
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.12": EOF
ERR: command exited with status 1
command:   docker build -t envoy-tcpdump -f Dockerfile-tcpdump .
line:      880
function:  common_run_container_tcpdump
called …
```

Retry docker build steps

---

sdk/freeport/freeport.go
sdk/testutil/server.go
sdk/testutil/types.go

Many of our flaky / failing tests seem to be caused by ports being held by parallel tests. @acpana tried to address this in https://github.com/hashicorp/consul/pull/13997.
```
[WARN] freeport: 1 out of 5 pending ports are still in use; something probably didn't wait around for the port to be closed!
[WARN] freeport: 1 out of 1 pending ports are still in use; something probably didn't wait around for the port to be closed!
[WARN] freeport: 1 out of 1 pending ports are still in use; something probably didn't wait around for the port to be closed!
```
This PR does not attempt a solution but adds debug lines to our tests to better trace which tests are still holding onto ports.

Add debugging logs to freeport

---

.changelog/13958.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/consul/state/state_store_test.go

This PR fixes an issue (https://github.com/hashicorp/consul/issues/13759) where a wildcard service definition in a gateway service config entry was causing the wrong type of services to be included for ingress and terminating gateways. Ingress gateways shouldn't pick up non-Connect services this way, and terminating gateways shouldn't pick up Connect services.
There's a couple changes to the service registration/gatewayServices table logic here:
- When a service is registered, it'll only be added to ingress wildcard mappings if it's the first connect instance, instead of any instance of the service. The reverse is true for terminating gateways - only non-connect instances will cause the mapping to get created.
- When a service is deregistered, it'll only remove ingress wildcard mappings …

Fix wildcard picking up services it shouldn't for ingress/terminating gateways

---

website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/config-entries/terminating-gateway.mdx
website/content/docs/connect/gateways/terminating-gateway.mdx

This adds documentation around destination feature.

add config parameters doc for destination in service-defaults

---

website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
website/content/docs/k8s/installation/vault/systems-integration.mdx
website/content/docs/k8s/installation/vault/wan-federation.mdx

* Made changes based on Adams suggestions
* updating list layout in systems integration guide.  updating wan federation docs.
* fixing env vars on systems integration page
* fixing h3 to h2 on enterprise license page
* Changed `The following steps will be performed` to `Complete the following steps`
* Replaced `These steps will be repeated for each datacenter` with `Repeat the following steps for each datacenter in the cluster`
* Emphasizing that kv2 secrets only need to be stored once.
* Move the sentence indicating where the vault path maps to the helm chart out of the -> Note callout
* remaining suggestions
* Removing store the secret in Vault from server-tls page
* Making the Bootstrapping the Server PKI Engine sections the same on server-tls and webhook-cert pages
* Apply suggestions …

Backport of Made changes based on Adams suggestions into release/1.12.x

---

ui/packages/consul-ui/app/services/repository/peer.js

Follow on from https://github.com/hashicorp/consul/pull/14018
As we don't pass a `:name` through when calling `generate`/`initiate` then we also need to check for `undefined` here. We could have also included `:name` in the DataSource URI, but _not including_ it is more intentional to what we are doing here. Therefore using an undefined check makes more sense.

ui: Add undefined check for peer model creation

---

agent/agent_endpoint_test.go
agent/config/config.go

There is a race between the CA being updated and the server responding to the leaf cert request. Added retries to make the test more consistent.
Similar retry loop exists in `TestAgentConnectCALeafCert_goodNotLocal`
https://github.com/hashicorp/consul/blob/61f86790115339972c4f6ad7328dd1ea3ccb73e8/agent/agent_endpoint_test.go#L6956-L6979

Add retry in TestAgentConnectCALeafCert_good

---

.changelog/14081.txt
agent/agent.go
agent/agent_test.go

If `startListeners` successfully created listeners for some of its input addresses but eventually failed, the function would return an error and existing listeners would not be cleaned up.
* Added testcase which fails without this PR

agent: Close existing active listeners when agent fails on an address

---

website/content/docs/connect/registration/service-registration.mdx
website/content/docs/connect/transparent-proxy.mdx
website/content/docs/discovery/dns.mdx

Did another pass through of docs re: tproxy.
One thing I noticed was that it's very hard to navigate from Transparent Proxy to any of the relevant information (service-registration and dns)

docs: Update references for transparent proxy with peers

---

website/content/docs/nia/configuration.mdx

The examples for NIA currently reference a configuration block with a url of `consul.example.com`  located [here](https://www.consul.io/docs/nia/configuration#consul)
Customers and partners that are utilizing HCP Consul are generally taking this configuration and replacing `consul.example.com` with the private HCP url. This allows for CTS to connect and register but the service checking requires the local agent to be used. 
Change the block to reflect `localhost:8500` to reduce the issues that users run into.  …

PR - Change configuration example for CTS documentation to reflect localhost instead of upstream cluster url 

---

command/agent/agent.go

We made it possible to configure TLS per-listener in Consul 1.12 but never updated the agent log output to reflect this.
Now, each listener/protocol's TLS settings are listed separately for clarity.
```
==> Starting Consul agent...
Version: '1.13.0-dev'
Revision: 'e4a579022b+CHANGES'
Build Date: '2022-08-09 10:08:07 +0000 UTC'
Node ID: 'f650ac70-0d0d-ee41-17a1-35a4d06dcb31'
Node name: 'daniel-macbook'
Datacenter: 'dc1' (Segment: '<all>')
Server: true (Bootstrap: false)
Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
Gossip Encryption: false
Auto-Encrypt-TLS: false
HTTPS TLS: Verify Incoming: false, Verify Outgoing: false, Min Version: TLSv1_2
gRPC TLS: Verify Incoming: false, Min Version: TLSv1_2
Internal RPC TLS: …
```

cli: update agent log preamble to reflect per-listener TLS config

---

agent/retry_join.go

- err value will be used later to surface the error message to stdout if r.join() returns any err.

fix: shadowed err in retryJoin()

---

ui/packages/consul-ui/app/templates/dc/intentions/edit.hbs

We weren't passing in the intention we load to the `can`-helper that checks the permission for the intention in question. This led to the permission check not being able to check an `intention`'s `SourcePeer` and subsequently not showing the `View Intention` headline but `Edit Intention` instead.

ui: fix - use actual intention for permission check intentions.edit

---

ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs

Removes the partitions-selection in the sources-dropdown in the services search. Users can search Partitions by name in the search-input. After this change, the sources-dropdown in the services-searchbar will look like in the following screenshot:
__This PR:__
* ~~changes the `Optgroup`-component to only surface the `@label` when we actually pass one - we can use that to not surface a label of an opt-group if we don't want to~~
* removes the partitions-selector in the sources-dropdown in the services search-bar

ui: don't surface partitions in services search source dropdown anymore

---

ui/packages/consul-ui/app/components/consul/bucket/list/index.js
ui/packages/consul-ui/app/components/consul/service/list/index.hbs
ui/packages/consul-ui/tests/integration/components/consul/bucket/list-test.js

This PR changes the following:
* Show namespace when peer info is surfaced - Whenever we display a peer and we are not on OSS we will surface the namespace as well. The rest of the ui logic of the bucket list has not changed.
* Display peer-info after instance-count

ui: Improve display peer info in service list

---

website/content/docs/connect/proxies/envoy.mdx

I forgot to update this in https://github.com/hashicorp/consul/pull/13807. With 1.13 out, the versions of supported Envoy move to 1.23-1.20.

docs: Update supported Envoy versions

---

CHANGELOG.md
version/version.go

A new major version was released today ([1.13.0](https://github.com/hashicorp/consul/releases/tag/v1.12.2)). This updates the CHANGELOG to include those entries and then removes the entries from the 1.13 pre-releases (they are all under the 1.13 heading now).
Since this is a new major, I also bumped the version in `/.version` to 1.14 so `make version` now reports:
```
Version:                    1.14.0
Version + release:          1.14.0-dev
Version + git:              1.14.0
Version + release + git:    1.14.0-dev (9ac184a769)
```
Run `make version` to see the new version.
The rendered CHANGELOG content can be found [here](https://github.com/hashicorp/consul/blob/eculver/release-updates/CHANGELOG.md).
- [v1.13.0](https://github.com/hashicorp/consul/releases/tag/v1.13.0)

Sync changes from 1.13.0 release

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/peering_backend_test.go
agent/consul/server.go

1. `isFailedPreconditionErr` did not properly handle wrapped status errors
2. PeerStreamService was not registered with the internal gRPC server, making gRPC forwarding to leaders throw `rpc error: code = Unimplemented desc = unknown service hashicorp.consul.internal.peerstream.PeerStreamService`
* Added testcase that will break if grpc library ever changes its implementation

Fix peering establishment bugs on followers

---

.github/workflows/build.yml

The `armv7hl` and `aarch64` RPM packages are currently being verified by invoking platform-specific Fedora 36 containers (ie `arm32v7/fedora:36` and `arm64v8/fedora:36`) which, after installing dependencies, are often OOM-killed which fails the entire build. This is not ideal. Until we have a reliable container to do these verifications, I'm commenting them out so they don't impede the release process or dev builds. We can do these verifications manually if we absolutely need to.
* build + verifications don't fail

ci: Disable Arm RPM verifications

---

website/content/docs/api-gateway/upgrades.mdx

Adding instructions for upgrading to Consul API Gateway v0.4.0
Wrote the instructions by taking notes as I upgraded Consul API Gateway to a newer binary, then upgraded resources, on a local [kind](https://kind.sigs.k8s.io/) cluster.
- [kube-storage-version-migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator)
Successfully updates the `GatewayClass`, `Gateway` and `HTTPRoute` resources in a cluster from v1alpha2 to v1beta1 when the new Gateway API CRDs are installed, but is fully automated and has a cluster-wide scope - it attempts to automatically update _every_ resource in the cluster, which would likely be an unexpected UX for an operator intending to update just a few specific resources.
- [kubectl-convert](https://kubernetes.io/docs/tasks/tools/install-kubectl-mac …

docs(consul-api-gateway): add v0.4.0 upgrade instructions

---

.changelog/14149.txt
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/structs/structs.go

fixes https://github.com/hashicorp/consul/issues/14107
Consul 1.13.0 changed ServiceVirtualIP to use PeeredServiceName instead of ServiceName which was a breaking change for those using service mesh and wanted to restore their snapshot after upgrading to 1.13.0.
This commit handles existing data with older ServiceName and converts it during restore so that there are no incompatibility issues when restoring from older snapshots.
* Manually tested in OSS and ENT by making a snapshot using Consul 1.12.3, then attempting to restore with the changes in this branch.
* Added unit tests restoring both versions of the struct

Handle breaking change for ServiceVirtualIP restore

---

.changelog/14119.txt

One of the fixes for [1.13.1](https://github.com/hashicorp/consul/tree/release/1.13.1) didn't get a changelog entry in its PR, so this adds it back for posterity.
I already ran the changelog tool with this present to generate the changelog for 1.13.1, so I think we're good.
Also, since the next release will base its changelog on `1.13.1` which has this in it already, there shouldn't be any duplication.
- [1.13.1 CHANGELOG](https://github.com/hashicorp/consul/blob/release/1.13.1/CHANGELOG.md#1131-august-10-2022)

Add changelog entry for peering fix

---

.changelog/14161.txt
agent/consul/client_serf.go
agent/consul/config.go
agent/consul/server_oss.go
agent/consul/server_serf.go
go.mod
go.sum
website/content/docs/agent/telemetry.mdx

To help user measure the gossip stability in the cluster, we need to separate the measurements between segment or partitions (for Enterprise). This PR adds the label to the serf metrics.
For OSS, we only label lan and wan network
- Example 1: server with 2 segments and wan gossip
```
consul_memberlist_gossip_count{job="server-1", network="lan", partition="default"} | 442
consul_memberlist_gossip_count{job="server-1", network="lan", partition="default", segment="alpha"} | 442
consul_memberlist_gossip_count{job="server-1", network="lan", partition="default", segment="beta"} | 442
consul_memberlist_gossip_count{job="server-1", network="wan", partition="default"} | 177
```
- Example 2: server with 2 partitions and one client in team 1 partition
consul_memberlist_gossip_count{job="client-1", …

feat(telemetry): add labels to serf and memberlist metrics

---

website/content/api-docs/query.mdx

Add documentation for https://github.com/hashicorp/consul/pull/13835. I'll wait to merge this until it is included in a 1.13 release.

Cluster Peering Prepared Query Failover Documentation

---

website/content/docs/k8s/compatibility.mdx

Update the compat matrix with the latest Consul K8s version and Consul Core version. Also remove 1.10.x associated notes since that is covered by versioned docs. 

docs: update consul-k8s compat matrix and remove 1.10.x version

---

website/content/docs/connect/cluster-peering/k8s.mdx
website/content/docs/k8s/helm.mdx

peering: update docs with exposing servers

---

agent/consul/client_serf.go
agent/consul/server_serf.go

This is the follow-up PR to https://github.com/hashicorp/consul/pull/14161 to fix the missing segment and partition in client and server's serf setup for ent

fix: missing segment and partition

---

website/redirects.js

After doing a google search, noticed the top result for install consul api gateway was broken. They must have gotten missed in the large docs refactor. Added the redirects in.

Add missing install redirrect to redirrect.js for api-gateway docs

---

.github/workflows/build.yml

This is a manual backport of #13808. The description of the original PR is below.
Add a build job to publish UBI images on DockerHub. This is to make it easier to test on OpenShift because you don't need a red hat account to be able to use those images

[1.12] Backport of add a build job to build and push UBI images to DockerHub 

---

.github/workflows/build.yml

This is a manual backport of #13808. The description of the original PR is below.
Add a build job to publish UBI images on DockerHub. This is to make it easier to test on OpenShift because you don't need a red hat account to be able to use those images

[1.11] Backport of add a build job to build and push UBI images to DockerHub

---

.circleci/config.yml

Currently, we have two distinct Nomad integration jobs in our CI config: one for 0.8.7 and one for `main`. How we came up with these two is not important. What is important, is that Nomad v0.8.7 was published on Jan. 11, 2019 which makes it two and a half years old. Similarly, `main` is brand new. So new, in fact, that when it updates to say, Go 1.19 ([like was done a few hours ago](https://github.com/hashicorp/nomad/commit/094a455c93450523223cf88ee42345c5446311c7)), our build breaks. 
This is not an optimal situation, so I'm updating our integration tests to use a fixed set of Nomad versions. I chose the most recent three because that is what I assume are still getting updates, just as the three newest versions of Consul are getting updates. Let me know if that's a silly assumption. …

ci: Replace Nomad integration tests with predictable compatibility matrix

---

.changelog/14233.txt
agent/consul/client_test.go
agent/structs/structs.go

This is a follow-up to #11500 and fixes #13695. @kisunji actually added back the `RandomStagger` in https://github.com/hashicorp/consul/pull/11500/commits/c8897b2912ddaa0007198c430bef553a18cc06a8
The timeout should include the maximum possible jitter since the server will randomly add to it's timeout a jitter. If the server's timeout is less than the client's timeout then the client will return an i/o deadline reached error.
Before:
```
time curl 'http://localhost:8500/v1/catalog/service/service?dc=other-dc&stale=&wait=600s&index=15820644'
rpc error making call: i/o deadline reached
real    10m11.469s
user    0m0.018s
sys     0m0.023s
```
After:
```
time curl 'http://localhost:8500/v1/catalog/service/service?dc=other-dc&stale=&wait=600s&index=15820644'
[...]
real    10m35.835s
user …
```

Use the maximum jitter when calculating the timeout

---

website/data/docs-nav-data.json

Replaces the `<sup>` tags in nav data JSON files with a `badge` property. This is a new feature in DevDot, introduced in https://github.com/hashicorp/dev-portal/pull/562. Each badge has type="outlined" and color="neutral".
Asana task: [[Consul] remove `<sup>` tags from nav data](https://app.asana.com/0/1202702246158644/1202707964020095/f)

Use badge for <sup> tags in nav data JSON file

---

.circleci/config.yml

This is a manual backport of https://github.com/hashicorp/consul/pull/14220 for which the backport assistant failed to backport due to a conflict. The description of the original PR is below. I should note, that there is a notable change from the original backport since I had to go back in time to establish what we expected the compatibility matrix to look like when Consul 1.12 was released. Based on the Consul 1.12 release date, I determined that the three active versions of Nomad at the time were 1.2, 1.1 and 1.0. I chose the latest versions of each of those here.
Currently, we have two distinct Nomad integration jobs in our CI config: one for 0.8.7 and one for `main`. How we came up with these two is not important. What is important, is that Nomad v0.8.7 was published on Jan. 11, 2019 …

[1.12] Backport of ci: Replace Nomad integration tests with predictable compatibility matrix

---

.circleci/config.yml

This is a manual backport of https://github.com/hashicorp/consul/pull/14220 for which the backport assistant failed to backport due to a conflict. The description of the original PR is below. I should note, that there is a notable change from the original backport since I had to go back in time to establish what we expected the compatibility matrix to look like when Consul 1.11 was released. Based on the Consul 1.11 release date, I determined that the three active versions of Nomad at the time were 1.2, 1.1 and 1.0. I chose the latest versions of each of those here.
Currently, we have two distinct Nomad integration jobs in our CI config: one for 0.8.7 and one for `main`. How we came up with these two is not important. What is important, is that Nomad v0.8.7 was published on Jan. 11, 2019 …

[1.11] Backport of ci: Replace Nomad integration tests with predictable compatibility matrix

---

website/content/docs/connect/cluster-peering/k8s.mdx

missed backport to stable-website from 1.13 release

stable-website: missed backport to stable-website from 1.13 release

---

Dockerfile

In `actions-docker-build` we [pass](https://github.com/hashicorp/actions-docker-build/blob/05c370a26e61b06be46c5095d6e914c9f0ea4f3d/scripts/docker_build#L49) `PRODUCT_VERSION` to the docker build command. Since this was not set, the label did not populate properly which is used in a comparison to determine the `minor-latest` and `latest` docker image tags. A change merged in today (https://github.com/hashicorp/actions-docker-build/pull/25) checks for this value being set in the docker build action, and errors out if it does not exist. This is causing docker build failures in this repo, for example: https://github.com/hashicorp/consul/actions/runs/2876677829
How I've tested this PR:
- build the image up to the point of label creation and pass in `--build-arg PRODUCT_VERSION=1.2.3`
- …

set PRODUCT_VERSION for docker build

---

website/content/docs/agent/config/config-files.mdx

A few sections of the agent config page aren't rendering properly. Example below:
[Preview link](https://consul-mjscn1a01-hashicorp.vercel.app/docs/agent/config/config-files#tls_internal_rpc_verify_server_hostname)

docs: fix broken markdown

---

website/content/docs/agent/config/config-files.mdx
website/content/docs/upgrading/instructions/index.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Adds guidance when upgrading a Consul service mesh deployment to 1.13 and:
- using auto-encrypt or auto-config; or
- the HTTPS port is not enabled on Consul agents
Needs review for:
- Technical accuracy
- Education team review for clarity
[Preview link](https://consul-59mdqqh25-hashicorp.vercel.app/docs/upgrading/upgrade-specific#service-mesh-compatibility) for the main change (1.13 upgrade notes section)

docs: add 1.13 upgrade considerations

---

.circleci/config.yml

The `test-integrations` CI workflow is consistently failing for fork PRs because forked repositories do not contain the necessary AWS credentials to perform an `aws assume-role` command. This PR ensures that `aws assume-role` is only attempted during CI workflows in the main Consul repository.
* Run the CI pipeline for this fork PR and ensure that it completes successfully.

Skip Lambda integration tests for fork PRs

---

CHANGELOG.md

https://github.com/hashicorp/consul/pull/14259 added 1.13 upgrade considerations to the docs site.
This PR references those considerations in the "breaking changes" section of the 1.13.0 changelog.
[Preview link](https://github.com/hashicorp/consul/blob/5ccbad4a286d6a4ea189e274929ca5d2297c25ba/CHANGELOG.md)

docs: add 1.13 upgrade considerations to changelog

---

agent/consul/merge_service_config_test.go

- This is to add the ent meta so that it can pass the ent test
- This fix the test issue caused by #14072  in ent

Fix: add missing ent meta for test

---

website/content/docs/api-gateway/configuration/gateway.mdx

We have an example for using `ReferenceGrants` to allow cross-namespace route `backendRefs` but not one for using `ReferenceGrants` to allow cross-namespace gateway `certificateRefs`. In addition, the [API Gateway Learn tutorial](https://learn.hashicorp.com/tutorials/consul/kubernetes-api-gateway) doesn't demonstrate this use case either. This use case requires slightly different values and is on a different page of the docs with its own context. Added this example to the appropriate page.
[Here](https://www.consul.io/docs/api-gateway/configuration/route …

Add example code for cross-namespace certificateRefs

---

website/content/api-docs/query.mdx

Minor improvement: link directly to the relevant DNS lookup section for prepared queries, rather than the long DNS overview page.

docs: link pq docs to relevant DNS lookup section

---

.changelog/14034.txt
command/connect/proxy/proxy.go
command/connect/proxy/proxy_test.go

Closes #13114
Closes #9144
Previously, when launching a sidecar proxy with one of the following commands:
- consul connect envoy -sidecar-for=...
- consul connect proxy -sidecar-for=...
... the -sidecar-for argument could only contain lowercase letters, even if
the service was registered with some uppercase letters.
Now, the -sidecar-for argument is treated as case-insensitive.
Tested with a new unit test case only.
Not tested by attempting to launch sidecar proxies manually.

Allow uppercase in proxy launch -sidecar-for arg

---

website/content/docs/discovery/dns.mdx

Previously, some variables were wrapped in < > while others were not,
creating ambiguity in whether some labels were a string literal or a
variable.
Now, all variables are wrapped in < >.

docs: improve consistency of DNS lookup variables

---

ui/packages/consul-ui/app/components/consul/external-source/index.scss
ui/packages/consul-ui/app/components/consul/kind/index.scss
ui/packages/consul-ui/app/components/pill/index.scss

Updates the badge and pill icon sizing. As far as I could tell, they're all using the [flight-icons](https://flight-hashicorp.vercel.app/). I've referenced a few of @johncowen's older PRs to try and get a grasp on where the transition is at for the icons, so if I've misunderstood how using flight-icons work, please let me know 😄. 
- [ticket](https://app.asana.com/0/701615483297399/1202765534781835/f)

ui: Update badge / pill icon sizing

---

agent/proxycfg-glue/glue.go
agent/proxycfg-glue/intention_upstreams.go
agent/proxycfg-glue/intentions.go
agent/proxycfg/data_sources.go
agent/proxycfg/manager.go
agent/proxycfg/state.go
agent/submatview/local_materializer.go
agent/submatview/store.go
agent/submatview/store_test.go
agent/xds/delta.go
agent/xds/server.go

This is the OSS portion of enterprise PR 2339.
It improves our handling of "irrecoverable" errors in `proxycfg` data sources.
The canonical example of this is what happens when the ACL token presented by Envoy is deleted/revoked. Previously, the stream would get "stuck" until the xDS server re-checked the token (after 5 minutes) and terminated the stream.
Materializers would also sit burning resources retrying something that could never succeed.
Now, it is possible for data sources to mark errors as "terminal" which causes the xDS stream to be closed immediately. Similarly, the `submatview.Store` will evict materializers when it observes they have encountered such an error.
Envoy integration tests provide general coverage 🔬 but it's useful to test manually by:
1. Starting a server with …

[OSS] proxycfg: terminate stream on irrecoverable errors

---

website/content/docs/api-gateway/configuration/gateway.mdx

Forgot to include the `type/docs-cherrypick` label on #14288. Manually cherrypicking the merge commit into `stable-website`.

Cherrypick merge of recent API Gateway docs addition

---

website/content/docs/connect/cluster-peering/k8s.mdx
website/content/docs/connect/transparent-proxy.mdx

Practitioner expressed confusion over known limitations for transparent proxy, specifically on explicit upstreams for federation versus cluster peering. Incorporated their feedback to change KubeDNS to Kubernetes DNS for consistency with Kubernetes documentation, as it may not be KubeDNS (the tool).
N/A

Clarify transparent proxy documentation

---

ui/.gitignore
ui/packages/consul-ui/app/components/composite-row/index.scss
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss

Policy lists were using the file-mask icon, where they should be using the file-text icon.
Manual Steps:
- Run in mock data mode
- Enable ACL 
- Visit the Tokens page or Roles page and observe the list of policies and the associated icon
- [Asana Ticket](https://app.asana.com/0/701615483297399/1202765534781840/f)
- I added `.tool-versions` to the `consul-ui/ui` gitignore as I used `asdf` for my node version management instead of nvm (performance reasons)

ui: Replace file-mask with file-text icon usage on policy list

---

agent/consul/usagemetrics/usagemetrics_oss_test.go

These tests copy a lot of repeated data, making it hard to discern what elements change between different cases, and any changes to the metrics themselves would require contributors to copy and paste them many times. This change makes the metrics tests more compliant with DRY principle, so it is easier to see what things change between test cases and add new metrics.
No-op, refactor

no-op: refactor usagemetrics tests for clarity and DRY cases

---

.circleci/config.yml
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
test/integration/connect/envoy/run-tests.sh
website/content/docs/connect/proxies/envoy.mdx

There are currently discrepancies between the docs in each release series, specifically for 1.10. This updates them all to agree. There will be an accompanying PR referenced below for 1.10.
- [Envoy integration docs (1.13)](https://www.consul.io/docs/v1.13.x/connect/proxies/envoy)
- [Envoy integration docs (1.12)](https://www.consul.io/docs/v1.12.x/connect/proxies/envoy) 
- [Envoy integration docs (1.11)](https://www.consul.io/docs/v1.11.x/connect/proxies/envoy)
- [Envoy integration docs (1.10)](https://www.consul.io/docs/v1.10.x/connect/proxies/envoy)
- https://github.com/hashicorp/consul/pull/14334

[1.11] docs: Update latest Envoy to 1.20.6, make docs consistent

---

.circleci/config.yml
agent/xds/proxysupport/proxysupport.go
website/content/docs/connect/proxies/envoy.mdx

There are currently discrepancies between the docs in each release series, specifically for 1.10. This updates them all to agree. There will be accompanying PRs referenced below for 1.11 and 1.10.
- [Envoy integration docs (1.13)](https://www.consul.io/docs/v1.13.x/connect/proxies/envoy)
- [Envoy integration docs (1.12)](https://www.consul.io/docs/v1.12.x/connect/proxies/envoy) 
- [Envoy integration docs (1.11)](https://www.consul.io/docs/v1.11.x/connect/proxies/envoy)
- [Envoy integration docs (1.10)](https://www.consul.io/docs/v1.10.x/connect/proxies/envoy)
- https://github.com/hashicorp/consul/pull/14335
- https://github.com/hashicorp/consul/pull/14334

[1.12] connect: Update Envoy support to latest patches for 1.20 and 1.21

---

website/content/docs/connect/proxies/envoy.mdx

There are currently discrepancies between the docs in each release series, specifically for 1.10. This updates them all to agree. There will be accompanying PRs referenced below for 1.12, 1.11 and 1.10.
- [Envoy integration docs (1.13)](https://www.consul.io/docs/v1.13.x/connect/proxies/envoy)
- [Envoy integration docs (1.12)](https://www.consul.io/docs/v1.12.x/connect/proxies/envoy) 
- [Envoy integration docs (1.11)](https://www.consul.io/docs/v1.11.x/connect/proxies/envoy)
- [Envoy integration docs (1.10)](https://www.consul.io/docs/v1.10.x/connect/proxies/envoy)
- https://github.com/hashicorp/consul/pull/14336
- https://github.com/hashicorp/consul/pull/14335
- https://github.com/hashicorp/consul/pull/14334

[1.13] docs: Update Envoy support matrix to match previous releases and code

---

website/content/docs/connect/proxies/envoy.mdx

Self-explanatory. The Envoy support docs do not match what is in the code. This also updates the docs to match what is in the versioned docs for 1.13, 1.12 and 1.11 once the associated PRs for them are merged. They will all be linked below.
Note: this does not need to be cherry-picked to `stable-website` -- it just needs to be kept up to date for future releases of Consul. The current docs published for "latest" Consul (e.g. `1.13.1` are correct).
- [Envoy integration docs (1.13/latest)](https://www.consul.io/docs/v1.13.x/connect/proxies/envoy)
- [Envoy integration docs (1.12)](https://www.consul.io/docs/v1.12.x/connect/proxies/envoy) 
- [Envoy integration docs (1.11)](https://www.consul.io/docs/v1.11.x/connect/proxies/envoy)
- [Envoy integration docs …

docs: Update Envoy support matrix to match the code

---

agent/consul/leader_peering.go

When a server is shutting down and the context passed to leader goroutines are cancelled, I noticed in a test that there was a tight loop that did not exit until the program exited.
```
2022-08-25T11:17:38.739-0400 [ERROR] acceptor.server.peering: Failed to remove trust bundle for peer: peer_id=7d228f34-28fe-0d20-eba9-21b6c09e390b peer_name=my-peer-dialer error="context canceled"
2022-08-25T11:17:38.740-0400 [ERROR] acceptor.server.peering: Failed to remove trust bundle for peer: peer_id=7d228f34-28fe-0d20-eba9-21b6c09e390b peer_name=my-peer-dialer error="context canceled"
2022-08-25T11:17:38.740-0400 [ERROR] acceptor.server.peering: Failed to remove trust bundle for peer: peer_id=7d228f34-28fe-0d20-eba9-21b6c09e390b peer_name=my-peer-dialer error="context canceled" …
```

Exit for loop when context is cancelled

---

website/content/api-docs/agent/check.mdx
website/content/api-docs/health.mdx
website/content/docs/discovery/checks.mdx

Includes:
- Improved scannability and organization of checks overview
- Checks overview includes more guidance on
- How to register a health check
- The options available for a health check definition
- Contextual cross-references to maintenance mode
Noting potential future improvements here so they aren't lost, but I'm considering them out-of-scope for this PR.
- Add subsection headers for examples
- Include a list of check type-specific options in the section for each type

docs: improve health check related docs

---

.changelog/13493.txt
command/kv/get/kv_get.go
command/kv/get/kv_get_test.go

…v get CLI
My attempt to fix the first [point](https://github.com/hashicorp/consul/issues/13412#issuecomment-1151603461) of @Amier3 in issue #13412 
* Added two extra test cases
```
❯ consul kv put foo/
Success! Data written to: foo/
❯ consul kv put foo1/a "Hello World 1"
Success! Data written to: foo1/a
❯ consul kv get -recurse -keys foo
foo/
foo1/
❯ consul kv get -recurse -keys -detailed foo
foo/
foo1/
❯ consul kv get -recurse -keys foo
foo/
foo1/a
❯ consul kv get -recurse -keys -detailed foo
CreateIndex      16
Flags            0
Key              foo/
LockIndex        0
ModifyIndex      16
Session          -
CreateIndex      17
Flags            0
Key              foo1/a
LockIndex        0
ModifyIndex      17
Session          -
```

Fix Consul KV CLI 'GET' flags 'keys' and 'recurse' to be set together

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/server.go
agent/grpc-external/services/peerstream/server.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/grpc-external/services/peerstream/stream_tracker_test.go

It'd be useful to be able to dashboard the "health" of a peering. We define a peering as unhealthy if any of the following is true:
```
// -  If heartbeat hasn't been received within the IncomingHeartbeatTimeout
// -  If the last sent error is newer than last sent success
// -  If the last received error is newer than last received success
```
Otherwise, we call the peering `healthy`.
* `stream_tracker` and metric level emission testing
- best viewed by commits

peering: add peer health metric

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/state/peering.go
agent/rpc/peering/service.go
proto/pbpeering/peering.go

Follow-up to https://github.com/hashicorp/consul/pull/14285
Currently we have a static list of server addresses from the peering token that may get stale over time. We need to watch for changes to peerings and update the server addresses which get served by the ring buffer.
* Added a testcase which updates an established peering with a bad server address, then confirms that we try to dial it at least once.
* Did not test end-to-end from a cluster generating raft autopilot events (mock events were tested in https://github.com/hashicorp/consul/pull/14285)

Replace ring buffer with async version

---

website/content/docs/k8s/connect/terminating-gateways.mdx

While working with terminating gateways, I noticed a few areas of improvement and spruced up the docs.

Update Kubernetes Terminating Gateway Docs

---

.changelog/14373.txt
agent/xds/clusters.go
agent/xds/testdata/clusters/connect-proxy-with-peered-upstreams.latest.golden
agent/xds/testdata/clusters/transparent-proxy-with-peered-upstreams.latest.golden

We can't trust health checks when service resolvers, splitters, and routers are used for peered clusters.

Update max_ejection_percent on outlier detection for peered clusters to 100%

---

.changelog/14378.txt
api/prepared_query.go

`QueryDatacenterOptions` was renamed to `QueryFailoverOptions` without creating an alias. This adds `QueryDatacenterOptions` back as an alias to `QueryFailoverOptions` and marks it as deprecated.

Fix a breaking change to the API package introduced in #13835

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/server.go
agent/grpc-external/services/peerstream/server.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/grpc-external/services/peerstream/stream_tracker_test.go

Follow-up to https://github.com/hashicorp/consul/pull/14004
https://github.com/hashicorp/consul/pull/14004 introduced a way of computing the health of a peering but I think the implementation could be simplified:
If heartbeats time out, the stream is disconnected:
https://github.com/hashicorp/consul/blob/64d6b46f75d6c37379a3cfd10b791d643c371f85/agent/grpc-external/services/peerstream/stream_resources.go#L457-L458
Then the error gets tracked:
https://github.com/hashicorp/consul/blob/64d6b46f75d6c37379a3cfd10b791d643c371f85/agent/grpc-external/services/peerstream/stream_resources.go#L277-L280
And eventually the leader retries the connection.
So the heartbeat health (among other classes of transient errors) can simply be inferred from the DisconnectTime. If the leader manages to connect to …

Adjust metrics reporting for peering tracker

---

.changelog/14364.txt
agent/consul/leader_peering_test.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go

Peerings are terminated when a peer decides to delete the peering from
their end. Deleting a peering sends a termination message to the peer
and triggers them to mark the peering as terminated but does NOT delete
the peering itself. This is to prevent peerings from disappearing from
both sides just because one side deleted them.
Previously the Delete endpoint was skipping the deletion if the peering
was not marked as active. However, terminated peerings are also
inactive.
This PR makes some updates so that peerings marked as terminated can be
deleted by users.
* Unit tests at state store and gRPC service layers

Allow terminated peerings to be deleted

---

.circleci/config.yml
GNUmakefile
test/integration/connect/envoy/Dockerfile-consul-envoy
test/integration/connect/envoy/case-wanfed-gw/global-setup.sh
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

Locally, always run integration tests using amd64, even if running
on an arm mac. This ensures the architecture locally always matches
the CI/CD environment.
In addition:
* Use consul:local for envoy integration and upgrade tests. Previously,
consul:local was used for upgrade tests and consul-dev for integration
tests. I didn't see a reason to use separate images as it's more
confusing.
* By default, disable the requirement that aws credentials are set.
These are only needed for the lambda tests and make it so you
can't run any tests locally, even if you're not running the
lambda tests. Now they'll only run if the LAMBDA_TESTS_ENABLED
env var is set.
* Split out the building of the Docker image for integration
tests into its own target from `dev-docker`. This allows us to always
use an …

Run integration tests locally using amd64

---

.changelog/14364.txt
agent/consul/leader_peering_test.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go

Backport of #14364
Peerings are terminated when a peer decides to delete the peering from
their end. Deleting a peering sends a termination message to the peer
and triggers them to mark the peering as terminated but does NOT delete
the peering itself. This is to prevent peerings from disappearing from
both sides just because one side deleted them.
Previously the Delete endpoint was skipping the deletion if the peering
was not marked as active. However, terminated peerings are also
inactive.
This PR makes some updates so that peerings marked as terminated can be
deleted by users.
* Unit tests at state store and gRPC service layers

[1.13.x] Allow terminated peerings to be deleted

---

.changelog/_2271.txt
website/content/commands/snapshot/agent.mdx

This is a feature branch to enable optionally configuring [path based addressing](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html) within S3 for the Consul Enterprise Snapshot Agent.  Disabled by default, this allows 3rd party object storage platforms(Minio/Dell ECS/Ceph/etc.) to work without requiring DNS records/TLS certs for each bucket name to support virtual addressing.
* Validated by creating snapshots against Dell ECS Object Storage.
https://github.com/hashicorp/consul/issues/11473
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

[OSS] Add support for S3 path based addressing

---

.github/workflows/backport-assistant.yml

Refs hashicorp/vault#15571, https://github.com/hashicorp/backport-assistant/issues/37, https://github.com/hashicorp/backport-assistant/pull/40, https://github.com/hashicorp/backport-assistant/issues/26
> Cherry-pick the merge commit instead of the individual commits in the PR. This will be less confusing, as it would eliminate the partial-success case, and may result in fewer failed cherry-picks in the first place.
This actually brings us back [closer to the implementation we had before switching](https://github.com/hashicorp/backport-assistant/issues/25#issuecomment-999895503) over to backport-assistant.

ci: update backport-assistant to pick merge commit

---

website/content/docs/discovery/dns.mdx
website/content/docs/enterprise/admin-partitions.mdx

Refactor enterprise node and service lookups into their respective sections, as opposed to having enterprise lookups in its own section. 

docs: re-organize service and node lookups for Consul Enterprise

---

.changelog/14290.txt
agent/consul/config_endpoint.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go

This PR fixes a bug where proxy defaults could be deleted by any name. Previously the code did not verify the name before proxy config deletion.
Fixes https://github.com/hashicorp/consul/issues/12684
* Replications steps are described [here](https://github.com/hashicorp/consul/issues/12684)

validate args before deleting proxy defaults

---

test/integration/connect/envoy/run-tests.sh

Without this change, you'd see this error:
```
./run-tests.sh: line 49: LAMBDA_TESTS_ENABLED: unbound variable
./run-tests.sh: line 49: LAMBDA_TESTS_ENABLED: unbound variable
```

Suppress "unbound variable" error.

---

.changelog/13998.txt
agent/xds/config.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/custom-trace-listener.latest.golden
website/content/docs/connect/proxies/envoy.mdx

The current tracing configuration provided to envoy is [deprecated](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-msg-config-bootstrap-v3-bootstrap). Should be replaced by the [HttpConnectionManager.Tracing](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing) configuration. That also allows more custom config as allowing us to add custom tags. This is an example of a valid config JSON.
```
{
"@type" : "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.Tracing",
"provider" : {
"name" : …
```

Add new envoy tracing configuration

---

agent/consul/internal_endpoint.go
agent/ui_endpoint.go

OSS port of a mainly Enterprise change. Should break no existing tests
The UIServices endpoint (`/v1/internal/ui/services`) needs to support querying imported services for a given peer. Initial support was added in https://github.com/hashicorp/consul/pull/13577 but that PR appended all imported services of a partition to the regular service dump response, whereas we want a narrower subset of ONLY imported services for a new UI view.
This PR updates the Internal.ServiceDump endpoint to behave differently when a PeerName is passed: it makes a single query to fetch only Peered services. If PeerName is empty, the endpoint behaves as usual. Non-empty PeerNames were not allowed prior to this PR.

Add Internal.ServiceDump support for querying by PeerName

---

.changelog/14238.txt
agent/consul/config_endpoint_test.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/structs/testing_connect_proxy_config.go
agent/xds/clusters_test.go
agent/xds/config.go
agent/xds/testdata/clusters/custom-passive-healthcheck.latest.golden
api/config_entry.go
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/proxies/envoy.mdx

This PR exposes an additional parameter (`EnforcingConsecutive5xx` in envoy `passive_health_check`) in Consul proxy configurations.
Resolves: https://github.com/hashicorp/consul/issues/11422

Add additional parameters to envoy passive health check config

---

website/content/docs/connect/cluster-peering/k8s.mdx

Typo for exposeServer.enabled and ensure the service and service account names are the same. 

docs: minor changes to cluster peering k8s docs and typos

---

.changelog/14343.txt
ui/packages/consul-ui/app/services/client/http.js
ui/packages/consul-ui/app/utils/http/xhr.js

Adds `withCredentials`/`credentials` to all HTTP API requests.
As discussed with @i0rek

ui: Use credentials for all HTTP API requests

---

ui/packages/consul-hcp/app/components/consul/hcp/home/index.hbs
ui/packages/consul-hcp/app/components/consul/hcp/home/index.scss
ui/packages/consul-hcp/vendor/consul-hcp/services.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/main-nav-vertical/index.scss
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/vendor/consul-ui/services.js

Adds a Back to HCP link only when HCP is enabled, the link uses a yet to exist `CONSUL_HCP_URL` "env var"

ui: Adds a HCP home link when in HCP

---

website/content/docs/k8s/connect/index.mdx

Updates Consul-k8s docs with information regarding supporting Kubernetes-1.24+

[docs] update docs for kube-1.24 support

---

agent/structs/config_entry_test.go

This PR fixes a test case in `TestProxyConfigEntry`. The test was failing in OSS->ENT PR.

fix TestProxyConfigEntry

---

.changelog/14423.txt
command/flags/http.go
command/peering/delete/delete.go
command/peering/delete/delete_test.go
command/peering/establish/establish.go
command/peering/establish/establish_test.go
command/peering/generate/generate.go
command/peering/generate/generate_test.go
command/peering/list/list.go
command/peering/list/list_test.go
command/peering/peering.go
command/peering/read/read.go
command/peering/read/read_test.go
command/registry.go
testrpc/wait.go
website/content/api-docs/peering.mdx
website/content/commands/index.mdx
website/content/commands/peering/delete.mdx
website/content/commands/peering/establish.mdx
website/content/commands/peering/generate-token.mdx
website/content/commands/peering/index.mdx
website/content/commands/peering/list.mdx
website/content/commands/peering/read.mdx
website/content/docs/connect/cluster-peering/create-manage-peering.mdx
website/data/commands-nav-data.json

Adding an initial cut of peering CLI commands for managing the connection workflow a little more intuitively from one place. RFC deviations where noted.
* Integration tests included
* `make dev` and run the commands as described in the docs.

[OSS] feat(cli): add initial peering cli commands

---

proto/prototest/testing.go

`AssertElementsMatch` should mirror the behavior of `testify`'s `ElementsMatch` ([src](https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch)).
However, given inputs `[A,B]` and `[A,B,C]`, `AssertElementsMatch` was returning too early based on the length of matched elements `{A,B}` because of a typo incorrectly comparing `len(outX) == len(listX)` when it should have been `len(listX) == len(listY)`
* This change should not cause tests to fail; otherwise they should be fixed

Fix early return in prototest.AssertElementsMatch

---

.golangci.yml

Using `net/rpc` and `consul-net-rpc` in the same repo can be dangerous. Let's add a linter setting for this then.
* Manual as per https://github.com/hashicorp/consul/pull/12816#discussion_r857675891

gomodguard net/rpc usage

---

agent/txn_endpoint.go
agent/txn_endpoint_test.go
api/agent.go
api/catalog.go
api/health.go

This PR adds missing fields to `HealthCheck`, `Node`, and `ConnectProxyConfig` in api to sync up with the definition in `agent/structs`
Please refer o the example in #14341
#14341

fix(txn api): missing proxy config in registering proxy service

---

.changelog/14429.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go

This PR adds some CA logic to prune old expired intermediate certs from the active root when a new intermediate is fetched. Since we renew the intermediate 1/3-1/2 of the way through its lifetime, this means there should never be more than a few old intermediates left around the root CA regardless of the configured root cert TTL.
Fixes #14159

Prune old expired intermediate certs when appending a new one

---

ui/packages/consul-ui/app/services/client/http.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/mock-api/prefixed-api/v1/catalog/.config
ui/packages/consul-ui/mock-api/prefixed-api/v1/catalog/datacenters
ui/packages/consul-ui/mock-api/prefixed-api/v1/internal/acl/authorize
ui/packages/consul-ui/mock-api/prefixed-api/v1/internal/ui/services
ui/packages/consul-ui/node-tests/config/environment.js
ui/packages/consul-ui/tests/acceptance/api-prefix.feature
ui/packages/consul-ui/tests/acceptance/steps/api-prefix-steps.js
ui/packages/consul-ui/tests/steps.js
ui/packages/consul-ui/tests/steps/doubles/http.js

Adds support for prefixing the path of API call made by the UI. Along with [`ui-config.content_path`](https://www.consul.io/docs/agent/config/config-files#ui_config_content_path), this will enable the UI to be usable at different paths behind reverse proxies etc, which is one of the UIs most requested features.
Please note: We have always spoken about the possibility of our `ui_config` being provided by an API requests rather than being supplied via our "env vars". This variable is slightly strange in that it can never be provided by an API call, as it provides us with the information as to where we need to make API calls, therefore this variable should always be thought of as an "env var"
The variable defaults to an empty string, and can be mocked out during development via either our …

ui: Add support for prefixing the API path

---

.changelog/14474.txt
agent/consul/kvs_endpoint.go
agent/consul/state/txn.go
agent/consul/state/txn_test.go
api/txn.go
website/content/api-docs/txn.mdx

Adds a `get-or-empty` operation to the kv txn api. There is currently no operation for fetching the value of a key that may not yet exist. The current `get` command will cause the entire transaction to roll-back if the key doesn't exist. The new op will return a `nil` value for a key if-not-found.
https://www.consul.io/api-docs/txn#kv-operations

Add kv txn get-not-exists operation.

---

agent/agent.go
agent/configentry/resolve.go
agent/configentry/resolve_test.go
agent/consul/config_endpoint.go
agent/consul/merge_service_config.go
agent/consul/merge_service_config_test.go
agent/proxycfg-glue/config_entry.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/intention_upstreams.go
agent/proxycfg-glue/internal_service_dump.go
agent/proxycfg-glue/internal_service_dump_test.go
agent/proxycfg-glue/resolved_service_config.go
agent/proxycfg-glue/resolved_service_config_test.go
agent/proxycfg/data_sources.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/state_test.go
agent/proxycfg/testing.go
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_upstreams.go
agent/proxycfg/upstreams.go

This PR contains the remaining server-local data sources.
It is the OSS portions of enterprise PRs 2460, 2489, and 2463. The changes have been reviewed properly in those PRs.
- As always, the Envoy integration tests are our friends 😉

proxycfg-glue: remaining server-local data sources

---

agent/agent.go
agent/agent_endpoint.go
agent/agent_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
agent/structs/structs.go

Closes #8254
This relocates automatic sidecar port assignment logic to a locked method immediately before registration, thereby preventing collisions when handling simultaneous requests.
Manual verification:
* Submit many simultaneous requests for registration with sidecar proxy and no port specified:
`for name in $(shuf -i 1-10000); do curl -d '{"name": "'$name'", "connect": {"sidecar_service": {}}}' -X PUT localhost:8500/v1/agent/service/register &; echo registered $name; done`
* See how many duplicate ports have been registered:
`curl localhost:8500/v1/agent/services | jq -r ' . | to_entries | map(select(.key | match("sidecar";"i"))) | map(.value) | .[] | .Port' | sort | uniq -d`
* Before this change: there should be several duplicate ports
* After this change: no duplicate ports
[GH …

Move sidecar port assignment logic to locked stage of add flow

---

website/content/commands/license.mdx
website/content/docs/agent/config/index.mdx
website/content/docs/enterprise/license/overview.mdx

- Adding a paragraph on updating a license in the _Enterprise License Overview_ page since practitioners have found it unclear that a `consul reload` can save them an agent restart.
- Adding the Consul License to the list of reloadable configuration
- Drawing the attention of the practitioner to the fact that `consul license [get|put]` has been deprecated
Tested that `consul reload` updates license information when the contents of the `license_path` file stanza have been updated.

docs: licensing improvements

---

ui/packages/consul-ui/package.json
ui/packages/consul-ui/tests/acceptance/dc/nodes/show.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show-routing.feature
ui/packages/consul-ui/tests/steps/assertions/page.js
ui/yarn.lock

This PR resolves an issue in the way we were working with ember-cli-page-object in our steps. The change introduced here makes sure we handle the fact that calling a page-object method is asynchronous. We need to return the promise instead of just `Promise.resolve`, so we properly await whatever happens based on the interaction with the page object.
This allows us to remove a (bad) sleep workaround introduced in this PR: https://github.com/hashicorp/consul/pull/14430
In addition to that, properly awaiting page-object promises in the `I see`-step creates the need to change the test order in another tab-nav related test. Because `see`ing a tab-item will actually click the item, we have to change the order of what things are being testing in that test.
This PR also updates …

ui: fix - proper await page object step

---

ui/packages/consul-hcp/app/components/consul/hcp/home/index.hbs
ui/packages/consul-hcp/app/components/consul/hcp/home/index.test.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/tests/integration/components/consul/hcp/home-test.js

Second part of https://github.com/hashicorp/consul/pull/14417, adds picking up the `.HCPURL` "env var"

ui: Use HCPURL / .HCPURL

---

ui/packages/consul-ui/app/components/tab-nav/pageobject.js
ui/packages/consul-ui/tests/acceptance/dc/nodes/show.feature
ui/packages/consul-ui/tests/acceptance/dc/services/instances/exposed-paths.feature
ui/packages/consul-ui/tests/acceptance/dc/services/instances/upstreams.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show-routing.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show-topology.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions/index.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/services.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/tags.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/routing-config.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/stats.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/upstreams.feature

Change tests that check visibility of tabs to not click, but only check for visibility via `isVisible`.
The tests changed in this PR accidentally clicked the tab because the page-object method being used was `clickable`, although we were only interested in checking for their visibility.
This should get rid of some recent occurred flakiness after upgrading ember-qunit et al.

ui: update tab nav steps to use `isVisible` vs `clickable`

---

agent/agent.go
agent/sidecar_service.go
agent/sidecar_service_test.go

Follow up to PR #14057
PR #14057 introduced a bug where a function to extract the serviceID from the sidecarServiceID did not precisely undo the append operation that was used to generate the sidecarServiceID. Submitting a sidecar registration for a service with a hyphen in the ID string creates an incorrect default alias check. This PR changes the serviceIDFromSidecarID function to exactly undo the function as intended.
* Register a service with a hyphenated name, accompanied by the unexpanded default sidecar syntax. The default sidecar alias check should correctly identify the service and pass (previously would fail).

PR #14057 follow up fix: service id parsing from sidecar id

---

.changelog/14475.txt
agent/cache/cache.go
agent/consul/intention_endpoint.go
agent/consul/leader_peering.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss.go
agent/consul/usagemetrics/usagemetrics_oss_test.go

We have dueling metrics patterns - sometimes we hard-code the "consul" prefix, but then we also automatically prepend it again to all metrics. See [Issue 13494](https://github.com/hashicorp/consul/issues/13494) for more info.
This PR takes the first step toward reconciling these patterns by establishing reliance on auto-prepending prefixes as the preferred pattern, and declaring existing metrics that hard-code prefixes as deprecated in help strings.
It applies the duplication tactic in examples such as https://github.com/hashicorp/consul/blob/c04515a844cf9348198fb16c637466604a94fc09/agent/consul/fsm/commands_oss.go#L351 to all legacy metrics.
* This does not eliminate double-prefixed metrics, but it adds a single-prefixed metric for every double-prefixed metrics, so that they can be …

Standardize on non-double-prefixed metrics

---

website/redirects.js

This commit fixes an oversight from PR #14009 where the K8s and VMs multi-cluster docs were moved, but not redirected to the proper location.

docs: Fix redirect to K8s and VM multi-cluster docs

---

website/content/docs/k8s/connect/connect-ca-provider.mdx
website/content/docs/k8s/connect/ingress-gateways.mdx
website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/deployment-configurations/consul-enterprise.mdx
website/content/docs/k8s/deployment-configurations/multi-cluster/kubernetes.mdx
website/content/docs/k8s/deployment-configurations/servers-outside-kubernetes.mdx
website/content/docs/k8s/deployment-configurations/single-dc-multi-k8s.mdx
website/content/docs/k8s/helm.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/upgrade/index.mdx

We have been using `values.yaml` and `config.yaml` interchangeably in our docs to describe the custom helm configurations.
This PR proposes that we use `values.yaml` to describe the helm chart configurations and use `config.yaml` in existing places where it is meant to describe other objects (like CRDs, etc).
This aligns our docs with whats in the consul-k8s repo and also what is described here: https://helm.sh/docs/chart_template_guide/values_files/

[docs] use values.yaml instead of config.yaml everywhere for helm configurations

---

.changelog/14577.txt
agent/consul/auto_config_endpoint.go
agent/consul/auto_config_endpoint_test.go

Added input validation for auto-config JWT authorization checks. Prior to this change, it was possible for malicious actors to construct requests which incorrectly pass custom JWT claim validation for the `AutoConfig.InitialConfiguration` endpoint. Now, only a subset of characters are allowed for the input before evaluating the bexpr.

Add input validation for auto-config JWT authorization checks.

---

.changelog/14579.txt
agent/consul/auto_config_endpoint.go
agent/consul/auto_config_endpoint_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

Added URI length checks to ConnectCA CSR requests. Prior to this change, it was possible for a malicious actor to designate multiple SAN URI values in a call to the `ConnectCA.Sign` endpoint. The endpoint now only allows for exactly one SAN URI to be specified.

Add CSR check for number of URIs.

---

.changelog/14516.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/structs/connect_ca.go
website/content/partials/http_api_connect_ca_common_options.mdx

This PR has a couple changes related to CA provider configuration:
- Update the docs to clarify that `IntermediateCertTTL` is only valid in the primary datacenter, as that's where the intermediates are signed. It isn't used at all in the secondary DCs.
- Update the Vault provider to update the intermediate PKI mount and role when `Configure()` is called. Previously these values were only set on creation of the mount/role and then any updates to the CA config were not reflected in Vault.

Fix inconsistent TTL behavior in CA providers

---

.changelog/14563.txt
agent/consul/server.go
agent/peering_endpoint_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
api/peering_test.go
command/peering/establish/establish_test.go

Adding some additional validation when establishing a peering connection as part of enhancements around mesh gateways for peering control plane traffic. The proposed changes look for a matching server name in the token, but an unknown PeerID, which indicates this token is from another cluster with the same datacenter name. This is unsupported.
* Unit tests + integration tests

[OSS] Validate Peering token Locality

---

ui/packages/consul-ui/ember-cli-build.js

In https://github.com/hashicorp/consul/pull/14518 we have upgrade ember to 3.24, this included switching from uglify to terser for JS minification etc, so we need to remove this config to prevent the following warning now that the config doesn't do anything:
I had a quick look to see if there is an equivalent config for terser and there doesn't seem to be.
Note the base branch for this is for https://github.com/hashicorp/consul/pull/14518, I know @LevelbossMike is AFK so I thought it would be best to branch off and make this tiny amend here.

ui: Remove ember-cli-uglify config

---

ui/packages/consul-ui/app/components/consul/external-source/index.scss
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/helpers/service/external-source.js
ui/packages/consul-ui/mock-api/v1/connect/_
ui/packages/consul-ui/mock-api/v1/health/service/_
ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
ui/packages/consul-ui/mock-api/v1/internal/ui/node/_
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/translations/common/en-us.yaml

See title. This is essentially adding to our list of icons and updating the mocks to add the potential new external-source metadata. Currently we are using our existing generic AWS icon. Expects the `external-source` value to be exactly `lambda`.

ui: Add AWS Lambda as potential external source

---

test/integration/connect/envoy/README.md
test/integration/connect/envoy/run-tests.sh

In #14391, @lkysow added developer docs for our integration tests. This adds a bit from my experience. Specifically, it calls out some of the bits that may cause issues if developers diverge from the prescribed processes. I also added a section with a little step-by-step for adding new test cases.
I was viewing the rendered content in a browser [here](https://github.com/hashicorp/consul/tree/eculver/integration-test-docs/test/integration/connect/envoy). 
- [Preview](https://github.com/hashicorp/consul/tree/eculver/integration-test-docs/test/integration/connect/envoy)

Add more content to integration test docs

---

ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/tests/unit/utils/get-environment-test.js

In the past we had always just turned on ACLs completely in the UI, and occasionally turned ACLs off in the HTTP API when we needed to do that (generally the UI is a thin client, so whatever the HTTP API says, that is what we do).
Back in https://github.com/hashicorp/consul/pull/11280#discussion_r742231738 we specifically wanted to turn off ACLs to test something in the topology view that didn't depend on the HTTP API, and we noticed that once we'd mocked ACLs out to be turned on (our testing default for ACLs only), we couldn't then turn them off again by setting the mock to something false. Note: All our feature flags are a one time setting only so we only generally 1. test without setting, 2. mock to on and test/retest, we generally never need to turn off again once set.
All the pieces …

ui: During testing ensure that when ui-only feature flags are mocked to true they can be re-mocked to false

---

website/content/api-docs/features/consistency.mdx
website/content/api-docs/index.mdx
website/content/api-docs/query.mdx
website/content/docs/api-gateway/configuration/gatewayclass.mdx
website/content/docs/api-gateway/configuration/routes.mdx
website/content/docs/api-gateway/upgrades.mdx
website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/config-entries/service-resolver.mdx
website/content/docs/connect/transparent-proxy.mdx
website/content/docs/ecs/manual/secure-configuration.mdx
website/content/docs/ecs/terraform/install.mdx
website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/k8s/annotations-and-labels.mdx
website/content/docs/lambda/index.mdx
website/content/docs/lambda/registration.mdx
website/content/docs/nia/configuration.mdx
website/content/docs/release-notes/consul/v1_13_x.mdx

This commit fixes spelling errors across various pages on the consul.io website.

docs: Fix spelling errors on website

---

.changelog/14619.txt
agent/agent.go
agent/agent_test.go

This PR fix a bug in health checks that sets check's interval value as its timeout.
Register a service with a timeout and interval set to different values. Retrieve the check information and see how interval value is returned for timeout field. 
The code diff is self explanatory

[BUGFIX] Do not use interval as timeout

---

website/content/docs/intro/index.mdx

fix merge conflict markings

---

.changelog/14598.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go

There are a couple cases in `primaryInitialize` in the `CAManager` that can cause the root to need updating when the leader is starting up. Currently when this happens, the old roots are discarded and only the new root is preserved, which could cause problems if the root was just rotated out and we still need to keep the old root around for interoperability during the switch to the new root. 
This PR changes that behavior to keep the old roots around in this case in `primaryInitialize` - they'll still be pruned through the normal leader routine once enough time has passed after they've been rotated out.

connect/ca: Don't discard old roots on primaryInitialize

---

.changelog/14429.txt

I was reviewing the OSS→Ent backlog for 1.12 and noticed the changelog entry for #14429 was missing a backtick.

changelog: fix missing backtick

---

website/content/docs/discovery/dns.mdx

Replaces https://github.com/hashicorp/consul/pull/14427
Automated backport failed due to some merge conflict. I tried to fix it, but the PR appears to be stuck due to a missing CLA agreement from user "temp" (probably something about our automation).
Manually submitting a PR to stable website to get this fixed.

Docs/fix node lookup by removing tag/stable website manual backport

---

.changelog/14679.txt
website/content/docs/agent/config/config-files.mdx
website/content/docs/discovery/dns.mdx

Documenting capabilities introduced by a Consul Enterprise PR (3072).
Preview: https://consul-cuhodfsls-hashicorp.vercel.app/docs/discovery/dns#service-lookups-for-consul-enterprise

docs: all enterprise locality labels now optional

---

.changelog/14233.txt
.changelog/14290.txt
CHANGELOG.md

Some changelog entries were missed from the 1.12.5 release because of wrong note types. This fixes the notes and adds the missing changelog items for what was already released.

Fix incorrect changelog labels.

---

.changelog/11500.txt
.changelog/14233.txt
CHANGELOG.md

Some changelog entries were missed from the 1.11.9 release because of wrong note types. This fixes the notes and adds the missing changelog items for what was already released.

fix missing changelog entries that were released

---

.changelog/14233.txt
.changelog/14269.txt
.changelog/14290.txt
.changelog/14364.txt
CHANGELOG.md

Some changelog entries were missed from the 1.13.2 release because of wrong note types. This fixes the notes and adds the missing changelog items for what was already released.

fix missing changelog entries that were previously released

---

.changelog/11500.txt
.changelog/11791.txt
.changelog/11804.txt
.changelog/11850.txt
.changelog/12279.txt
.changelog/14233.txt
.changelog/14269.txt
.changelog/14290.txt
.changelog/14364.txt
CHANGELOG.md

`bugfix` is an invalid category for our changelog generation tool. Unfortunately, the tool skipped over these entries and cause them to be missing from out changelog. This PR manually updates the changelog for the missing items originally labeled `bugfix`.

docs: fix missing bugfix changelog entries

---

website/content/docs/agent/telemetry.mdx

Labels' chart appears broken when rendered in the website:
This PR is adding some spacing to fix it.
* N/A
https://www.consul.io/docs/agent/telemetry#labels-2

docs: fix website/docs/agent/telemetry labels chart

---

agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/http_register.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

In Consul UI we want to display a condensed list of service names that are being exported to a peer. The state store functions already exist so this PR simply exposes a new endpoint.
* Added new testcases at UI and internal level

Add new internal endpoint to list exported services to a peer

---

.changelog/14616.txt
agent/configentry/resolve.go
agent/configentry/resolve_test.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/xds/config.go
agent/xds/config_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/listener-balance-inbound-connections.latest.golden
agent/xds/testdata/listeners/listener-balance-outbound-connections-bind-port.latest.golden
api/config_entry.go
api/config_entry_test.go
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/proxies/envoy.mdx

This PR adds support for the Envoy `exact_balance` configuration option.
https://cloudnative.to/envoy/api-v3/config/listener/v3/listener.proto.html#config-listener-v3-listener-connectionbalanceconfig-exactbalance
Without this configuration, connections are randomly allocated to Envoy worker threads. Because connections never change threads in Envoy after creation, this can result in uneven distribution of workload. For long-lived, high-traffic connections, it is best to specify this option to guarantee that connection counts are maintained evenly between Envoy workers.
Unit tests were added. Manual testing was performed by using the following configuration and toggling the various permutations of the new fields, then inspecting the Envoy admin `config_dump` endpoint.
```
Kind = …
```

Add envoy connection balancing.

---

website/content/docs/enterprise/admin-partitions.mdx

Admin partition CLI documentation was pointing at /commands/admin-partition.  Updated to point at /commands/partition
https://www.consul.io/commands/admin-partition returns not found.
Link to document to verify currently broken link: 
https://www.consul.io/docs/enterprise/admin-partitions#usage

Fix Link: Consul Enterprise Admin Partitions - Usage - CLI

---

website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx

- It looks like perhaps there was a typo in this section for Admin Partitions where the server acl init steps were copied for the Admin Partition Role and service account. 
- Update System Integrations page to use the latest Helm values format as externalVaultAddr is now in the global stanza: https://www.vaultproject.io/docs/platform/k8s/helm/configuration#externalvaultaddr
Include any links here that might be helpful for people reviewing your PR (Tickets, GH issues, API docs, external benchmarks, tools docs, etc). If there are none, feel free to delete …

docs: update to Vault secrets backend for partition init service account and Helm values for injector 

---

agent/proxycfg/connect_proxy.go
agent/proxycfg/manager_test.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/testing_peering.go
agent/proxycfg/upstreams.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/local-mesh-gateway-with-peered-upstreams.latest.golden
agent/xds/testdata/endpoints/local-mesh-gateway-with-peered-upstreams.latest.golden
agent/xds/testdata/listeners/local-mesh-gateway-with-peered-upstreams.latest.golden
agent/xds/testdata/routes/local-mesh-gateway-with-peered-upstreams.latest.golden

Some user networks may restrict which services have any external connectivity. In some circumstances, individual workloads may not be permitted to make direct connections out to the destination peers' mesh gateway. 
In those cases we want to be able to provide the "local" mesh gateway mode for cross-peer connectivity. In this mode workloads in the cluster will first make a connection to the mesh gateway running in their own cluster. It will then be the gateways responsibility to forward that connection along to the mesh gateway in the remote/destination peer which will then do all the final routing internal to that cluster.
* Added golden tests to verify endpoints of local mesh gateway

Enable outbound peered requests to go through local mesh gateway

---

README.md

- Remove Consul Connect from README and slight formatting changes.
- Add HCP Learn Guide link
- Change link from hashicorp.com Consul page to consul.io/docs/enterprise page for more information about Consul Enterprise.
Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to …

README: Consul Readme improvements 

---

website/content/docs/enterprise/license/faq.mdx

Manual backport because the auto-backport failed for some reason: https://github.com/hashicorp/consul/pull/14764

docs: clarify license behavior on restart
