- sdk/freeport/freeport.go
Follow-up to https://github.com/hashicorp/consul/pull/14055.
The added debug logs are helpful but we can narrow down on the handful of tests which consistently fail to release ports.
> freeport: Track tests which used ports

- website/content/docs/k8s/connect/terminating-gateways.mdx
Adding Kubernetes documentation for the new transparent proxy Destination feature.
N/A
Additional Doc PR #13950
> docs: destination docs for k8s

- website/content/docs/upgrading/upgrade-specific.mdx
(cherry picked from commit 807898a3c2bdac9890ffaac61fc52b4cc855086a)
original: https://github.com/hashicorp/consul/pull/14093
> [1.12.x] Updates upgrade docs to clarify Nomad bug is fixed

- website/content/docs/release-notes/consul-ecs/v0_4_x.mdx
- website/content/docs/release-notes/consul-ecs/v0_5_x.mdx
- website/data/docs-nav-data.json
Adding Consul ECS release notes for v0.5.x to docs
> Add Consul ECS v0.5 release notes

- website/content/docs/connect/cluster-peering/k8s.mdx
Update docs to specify how to recreate the peering token.
> Add docs to recreate peering token.

- CHANGELOG.md
Changelog Updates from today's release
> [OSS] docs: changelog 1.12.4 and 1.11.8

- CHANGELOG.md
- version/version.go
Syncing changes from the 1.12.4 release today.
> [OSS] Release 1.12.4 Updates

- CHANGELOG.md
- version/version.go
Syncing changes from the 1.11.8 release today.
> [OSS] Release 1.11.8 Updates

- CHANGELOG.md
- version/version.go
Sync changelog and version updates from the 1.13.1 release today.
> Sync changes from 1.13.1 release

- CHANGELOG.md
Sync changelog from 1.13.1 release today.
> docs: changelog for 1.13.1

- website/content/docs/upgrading/instructions/index.mdx
- website/content/docs/upgrading/upgrade-specific.mdx
Add upgrade instructions and considerations for upgrading Consul 1.13.0 to account for an issue with upgrades and snapshots.
> Add upgrade instructions and considerations for Consul 1.13.1

- website/content/docs/k8s/helm.mdx
> Update helm docs for cluster peering

- agent/connect/sni_test.go
- agent/consul/discovery_chain_endpoint_test.go
- agent/consul/discoverychain/compile.go
- agent/consul/discoverychain/compile_test.go
- agent/consul/state/peering_test.go
- agent/discovery_chain_endpoint_test.go
- agent/proxycfg/naming.go
- agent/proxycfg/naming_test.go
- agent/structs/config_entry_discoverychain.go
- agent/structs/discovery_chain.go
- agent/xds/failover_math_test.go
Update the discovery chain to support failover `Target`s.
* Unit tests
> Cluster Peering Failover Discovery Chain Changes

- website/content/docs/connect/config-entries/ingress-gateway.mdx
- website/content/docs/connect/config-entries/mesh.mdx
- website/content/docs/connect/config-entries/proxy-defaults.mdx
- website/content/docs/connect/config-entries/service-defaults.mdx
Updates docs for Mesh CRD to be up to date with latest spec
Asana task : https://app.asana.com/0/1159647457614001/1202475485785044
> Updates docs for CRDs

- website/content/docs/connect/config-entries/terminating-gateway.mdx
- website/content/docs/k8s/connect/terminating-gateways.mdx
This PR makes some small tweaks based on internal feedback on the new docs for Transparent Proxy Destinations.
> doc: tproxy destination fixes

- website/content/docs/integrate/partnerships.mdx
Hey Consul devs,
We have many users on our platform who are using Consul and would like to instrument it. We’d love to provide a smooth experience for Consul users who need to use commercial monitoring solutions, such as New Relic. Please see our documentation [here](https://newrelic.com/instant-observability/consul/b65825cc-faee-47b5-8d7c-6d60d6ab3c59).
Please consider adding a link for your direct users to provide an option for New Relic.  For your convenience, we have submitted this PR with our proposed content.
Please feel free to let us know if you have any questions or concerns.
Thank you for your consideration.
> Updated consul monitoring with Newrelic APM 

- website/content/docs/release-notes/consul/v1_12_x.mdx
- website/data/docs-nav-data.json
Manual backport of 1.12 release notes. 
> docs: manual backport Consul 1.12 release notes

- website/content/docs/release-notes/consul-k8s/v0_47_x.mdx
Explicitly call out 1.19 to 1.23 support
> docs: Update Consul K8s release notes with explicit versions

- website/content/docs/connect/cluster-peering/k8s.mdx
Numerous changes to document flow for using cluster peering with TProxy. This update now provides a working example for using Cluster Peering with Transparent Proxy. 
> docs: Cluster peering with Transparent Proxy updates 

- website/content/docs/enterprise/audit-logging.mdx
Very small correction to sentence structure on public facing documentation for Audit Logging.
n/a
n/a
> docs: audit logging restructure sentence

- website/content/api-docs/snapshot.mdx
- website/content/commands/snapshot/restore.mdx
This commit incorporates additional feedback received related to PR #12971.
> docs: Additional feedback from PR #12971

- website/content/docs/connect/config-entries/service-splitter.mdx
> Typo fix in service-splitter.mdx

- website/content/docs/connect/cluster-peering/create-manage-peering.mdx
Was following this guide and noticed some issues in the HCL
> docs: Fix code example in cluster peering

- website/data/docs-nav-data.json
Update get started section to include learn, rename overview -> install Consul
> Fix Get Started IA

- website/content/docs/discovery/dns.mdx
> docs: node lookups don't support filtering on tag

- website/content/docs/k8s/helm.mdx
Update automatically generated helm docs.
> update helm docs for release 0.48.0

- website/content/docs/k8s/deployment-configurations/single-dc-multi-k8s.mdx
Add in additional condition that will cause overwriting of ACL resources. Also call it out again in the requirements. 
> docs: Update single dc multiple k8s clusters doc

- ui/packages/consul-ui/app/components/data-writer/index.hbs
Follow on from https://github.com/hashicorp/consul/pull/14025, this change kinda got lost in the conversation so added as a separate PR.
> If so, I guess I can add a check for error.message here also
https://github.com/hashicorp/consul/pull/14025#discussion_r939967248
Please note, this is not necessary for any upcoming release and shouldn't be a blocker for anything.
> ui: Additionally use message for displaying errors in DataWriter

- website/content/docs/k8s/deployment-configurations/single-dc-multi-k8s.mdx
- website/content/docs/k8s/installation/install.mdx
Missing word and formatting for a single command. 
> docs: small typos in single dc k8s clusters

- .changelog/14495.txt
- ui/packages/consul-ui/app/routes/application.js
- ui/packages/consul-ui/app/utils/get-environment.js
Detects existence of a `TokenSecretID` cookie. When set, this gets passthrough to localStorage and therefore "automatically logs you in". Only happens when ACLs are enabled and you don't already have a token.
> ui: Detect token in a cookie and passthrough

- website/content/docs/api-gateway/tech-specs.mdx
Adding info to API Gateway Tech Specs page related to some product limitations.
N/A
* [N/A] updated test coverage
> Docs: add limitations to Tech Specs

- website/content/docs/k8s/installation/install.mdx
Clarifying documentation on how the Consul CNI plugin is installed and configured.
> [docs] update CNI docs to indicate how the CNI plugin is installed

- ui/packages/consul-peerings/app/components/consul/peer/list/test-support.js
- ui/packages/consul-ui/tests/acceptance/dc/peers/index.feature
- ui/packages/consul-ui/tests/acceptance/steps/dc/peers/index-steps.js
- ui/packages/consul-ui/tests/helpers/set-cookies.js
- ui/packages/consul-ui/tests/helpers/type-to-url.js
- ui/packages/consul-ui/tests/pages.js
- ui/packages/consul-ui/tests/pages/dc/peers/index.js
This PR adds initial test scaffolding and a simple acceptance test for the peer listing.
> ui: Add initial peering listing acceptance tests

- .changelog/14579.txt
- agent/consul/auto_config_endpoint.go
- agent/consul/auto_config_endpoint_test.go
- agent/consul/leader_connect_ca.go
- agent/consul/leader_connect_ca_test.go
This is a backport of: https://github.com/hashicorp/consul/pull/14579
It needed to be stripped down significantly due to version differences.
> Add CSR check for number of URIs.

- api/config_entry.go
- api/config_entry_test.go
update enforcing_consecutive_5xx type to pointer type
> update enforcing consecutive 5xx type to pointer type

- .changelog/14606.txt
- ui/packages/consul-hcp/vendor/consul-hcp/routes.js
- ui/packages/consul-ui/app/abilities/overview.js
- ui/packages/consul-ui/app/utils/get-environment.js
> ui: Completely remove the Overview routes when running the UI in HCP

- website/content/api-docs/index.mdx
Create a new Consul API overview page that serves as a landing page for all things Consul API.
> Create new Consul API overview page

- website/Makefile
- website/content/docs/concepts/service-discovery.mdx
- website/content/docs/concepts/service-mesh.mdx
- website/content/docs/install/index.mdx
Update `/install` links to point to `/downloads`
> docs: update /install -> /downloads

- website/content/docs/k8s/connect/ingress-controllers.mdx
Add NGINX Ingress controller example and make Consul API Gateway Notice more apparent. 
> docs: add nginx ingress controller example

- website/content/api-docs/catalog.mdx
- website/content/api-docs/health.mdx
Updates API docs to highlight merge-central-config support.
Related PRs that included the implementation:
https://github.com/hashicorp/consul/pull/13001
https://github.com/hashicorp/consul/pull/13450
> Update docs for merge-central-config support

- .changelog/14599.txt
- agent/acl_endpoint.go
- agent/txn_endpoint.go
- agent/txn_endpoint_test.go
increase the size of txn to support vault
> increase the size of txn to support vault

- website/content/docs/agent/telemetry.mdx
Fixing a table that doesn't render correctly
> docs: fix peering metrics labels table

- website/content/api-docs/index.mdx
This PR fixes typos on the API landing page
> fixed typos in API landing page

- website/content/docs/connect/gateways/ingress-gateway.mdx
> Fix md markup

- website/content/docs/api-gateway/usage.mdx
> fixed typos in CAPIgw usage docs

- website/content/docs/k8s/helm.mdx
Auto-generated helm docs update from consul-k8s.
> [docs] update helm docs for sync catalog and vault

- website/content/docs/agent/config/config-files.mdx
See https://github.com/hashicorp/consul/blob/84f8b87967e084406d36946472f8b00ba788983a/agent/config/builder.go#L685-L687
> Make defaulting behaviour of connect.enabled clear

- .changelog/14724.txt
- agent/cache-types/trust_bundle.go
- agent/cache-types/trust_bundles.go
- agent/consul/grpc_integration_test.go
- agent/consul/prepared_query_endpoint_test.go
- agent/grpc-external/options.go
- agent/grpc-external/options_test.go
- agent/grpc-external/services/connectca/sign.go
- agent/grpc-external/services/connectca/watch_roots.go
- agent/grpc-external/services/connectca/watch_roots_test.go
- agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
- agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
- agent/grpc-external/services/dataplane/get_supported_features.go
- agent/grpc-external/services/dataplane/get_supported_features_test.go
- agent/grpc-external/services/serverdiscovery/watch_servers.go
- agent/grpc-external/services/serverdiscovery/watch_servers_test.go
- agent/grpc-external/token.go
- agent/peering_endpoint.go
- agent/rpc/peering/service.go
- agent/rpc/peering/service_test.go
- agent/structs/structs.go
- agent/xds/delta.go
- agent/xds/server.go
Support Stale Queries for Trust Bundle Lookups
> Support Stale Queries for Trust Bundle Lookups

- ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
- ui/packages/consul-peerings/app/components/consul/peer/list/test-support.js
- ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
- ui/packages/consul-ui/tests/acceptance/dc/peers/create.feature
- ui/packages/consul-ui/tests/acceptance/dc/peers/delete.feature
- ui/packages/consul-ui/tests/acceptance/dc/peers/establish.feature
- ui/packages/consul-ui/tests/acceptance/dc/peers/regenerate.feature
- ui/packages/consul-ui/tests/acceptance/steps/dc/peers/create-steps.js
- ui/packages/consul-ui/tests/acceptance/steps/dc/peers/delete-steps.js
- ui/packages/consul-ui/tests/acceptance/steps/dc/peers/establish-steps.js
- ui/packages/consul-ui/tests/acceptance/steps/dc/peers/regenerate-steps.js
- ui/packages/consul-ui/tests/pages.js
Several more acceptance tests for generating/establishing/regenerating and deleting peerings
cc @LevelbossMike
> ui: Add more acceptance tests for cluster peering

- agent/proxycfg/upstreams.go
Port https://github.com/hashicorp/consul-enterprise/pull/3129 to Consul
> bug: watch local mesh gateways in non-default partitions with agentless

- website/content/docs/release-notes/consul-k8s/v0_49_x.mdx
- website/data/docs-nav-data.json
> docs: Consul K8s 0.49.x release notes

- website/content/docs/k8s/helm.mdx
Updated generated 0.49.x helm docs
> docs: updated 0.49.x generated helm docs

- website/content/docs/k8s/helm.mdx
Update helm docs for consul-k8s 1.0.0-beta1
> [docs] update helm docs for consul-k8s 1.0.0-beta1

- website/content/docs/connect/proxies/envoy.mdx
This updates the version compatibility matrix to include Consul Dataplane / Envoy versions for the upcoming beta.
> docs: Consul Dataplane Version Compatibility

- website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx
> Fix broken links on WAN Federation Vault docs page

- .changelog/14751.txt
- agent/proxycfg/connect_proxy.go
- agent/proxycfg/testing_tproxy.go
- agent/xds/listeners_test.go
- agent/xds/testdata/listeners/transparent-proxy-with-resolver-redirect-upstream.latest.golden
This is a backport of https://github.com/hashicorp/consul/pull/14751
> Backport of Fix tproxy listeners with discovery chains. into release/1.12.x

- website/content/docs/k8s/helm.mdx
autogenerated docs for helm, beta2
> [docs] update helm docs for beta2

- .release/ci.hcl
Enables Iron Bank updates after linux artifacts are published.
Matching backports to versions in https://repo1.dso.mil/dsop/hashicorp/consul with the exception of ``1.10``, which there is no label for.
> Enable ironbank integration

- website/content/docs/api-gateway/configuration/routes.mdx
- website/content/docs/k8s/deployment-configurations/multi-cluster/index.mdx
- website/content/docs/k8s/deployment-configurations/multi-cluster/kubernetes.mdx
- website/content/docs/k8s/deployment-configurations/multi-cluster/vms-and-kubernetes.mdx
Fixes some recently changed frontmatter that is malformed.
> docs: fix malformed yaml

- agent/grpc-external/services/peerstream/subscription_blocking.go
This change fixes a situation where every call to `syncViaBlockingQuery` gets exponentially slower, until reaching a cap. The change now modifies the logic to exponentially backoff and only sleep in the event of a failure. The wait time also is reset back to normal whenever a successful call is made.
> Fix incorrect backoff-wait logic.

- ui/packages/consul-ui/app/components/peerings/provider/index.js
- ui/packages/consul-ui/tests/acceptance/dc/peers/show.feature
- ui/packages/consul-ui/tests/pages/dc/peers/index.js
- ui/packages/consul-ui/translations/routes/en-us.yaml
Updating copy on peering detail page to match Figma designs.
> UI: Copy changes for peering detail page

- website/content/docs/connect/dataplane/index.mdx
> 1.14 dataplane docs beta: Bump to beta3

- website/content/docs/connect/cluster-peering/k8s.mdx
Previously there were mentions of adding annotations in a general sense, but the change explicitly defines what annotations are needed within steps to deploy a workload onto the mesh when using cluster peering. 
Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to obfuscate …
> docs: improvements on language from cluster peering steps

- command/flags/flag_map_value.go
- command/flags/flag_map_value_test.go
- lib/retry/retry.go
- lib/retry/retry_test.go
- website/content/commands/snapshot/agent.mdx
Port of hashicorp/consul-enterprise#3303
>  Allow snapshot agent to log in with an auth method

- internal/tools/proto-gen-rpc-glue/main.go
These methods were removed in https://github.com/hashicorp/consul/pull/14965
> Remove unused methods from template

- website/content/docs/enterprise/license/faq.mdx
- website/content/docs/enterprise/license/overview.mdx
- website/content/docs/nia/enterprise/license.mdx
Existing link is broken, this PR updates to the correct enterprise license link
> Update enterprise license link

- command/connect/envoy/bootstrap_tpl.go
This is a simple change to add some comments to the envoy bootstrap template. The file is copied over to consul-dataplane.
N/A
I updated the comments in [consul-dataplane](https://github.com/hashicorp/consul-dataplane/pull/36) but they should have been done here.
> update prometheus template args

- .golangci.yml
- GNUmakefile
- agent/consul/leader_peering.go
- agent/consul/leader_peering_test.go
- agent/consul/state/config_entry_test.go
- agent/consul/state/peering.go
- agent/grpc-external/services/peerstream/replication.go
- agent/grpc-external/services/peerstream/stream_resources.go
- agent/grpc-external/services/peerstream/subscription_manager.go
- agent/grpc-external/services/peerstream/subscription_manager_test.go
- agent/rpc/peering/service_test.go
- agent/xds/listeners.go
Update to golangci-lint v1.50.0
> chore: update to golangci-lint v1.50.0

- website/content/docs/upgrading/upgrade-specific.mdx
Docs in response to the change introduced by https://github.com/hashicorp/consul/pull/15035
> docs: update Vault CA provider policy guidance

- GNUmakefile
Fixes a minor regression from #14222
> build: ensure 'make dev-docker' updates consul-dev:latest too

- agent/grpc-external/services/peerstream/stream_resources.go
- agent/grpc-external/services/peerstream/stream_test.go
When peering two clusters, the acceptor will always display the following warning:
```
[WARN]  agent.grpc-api.peerstream.stream: client peer was unable to apply resource: dialed=false peer_id=57f283a6-7c25-5125-fe1b-bdb11150f2ce peer_name=cluster1 code=13 error="upsert error, ResourceURL: \"type.googleapis.com/hashicorp.consul.internal.peering.PeeringServerAddresses\", ResourceID: \"server-addrs\": Cannot switch peering dialing mode from false to true"
```
This occurs because the acceptor is attempting to save a new list of server addrs, which is not possible (a server addr list length greater than zero indicates that the peer is a dialer and not an acceptor).
> Prevent peering acceptor from subscribing to addr updates.

- website/content/commands/peering/generate-token.mdx
#15256 was merged, but it wasn't backported to stable-website
👀 
> Manual backport of #15256

- website/content/docs/connect/cluster-peering/k8s.mdx
Small changes in cluster peering docs when going through Cluster Peering with @nathancoleman 
> docs: cluster peering docs feedback

- .changelog/14679.txt
- .changelog/_3557.txt
- CHANGELOG.md
- api/go.mod
- go.mod
- test/integration/consul-container/go.mod
- test/integration/consul-container/go.sum
Update changelog and gomod with release 1.14.0 changes.
> Consul 1.14 post-release updates

- website/content/docs/k8s/helm.mdx
This change is only meant for consul 1.13.x branch.
> docs: helm docs for consul-k8s 0.49.1

- website/content/docs/connect/gateways/mesh-gateway/wan-federation-via-mesh-gateways.mdx
make the h1 title consistent with the page_title
> docs: make the h1 title consistent with the page_title

- website/content/docs/k8s/compatibility.mdx
Bump Compat matrix change and add K8s version in compat matrix 
> docs: Consul K8s 1.0/Consul 1.14 GA Compat Matrix change

- website/content/docs/enterprise/license/overview.mdx
Updating our licensing docs to describe how consul-dataplane and virtual agents impact pricing/licensing.
> Update licensing docs to account for virtual agents.

- website/content/docs/k8s/helm.mdx
> generate helm docs

- website/content/docs/connect/cluster-peering/create-manage-peering.mdx
- website/content/docs/connect/cluster-peering/index.mdx
- website/content/docs/connect/config-entries/exported-services.mdx
- website/content/docs/connect/gateways/mesh-gateway/peering-via-mesh-gateways.mdx
- website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-partitions.mdx
- website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-peers.mdx
- website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-wan-datacenters.mdx
- website/content/docs/connect/gateways/mesh-gateway/wan-federation-via-mesh-gateways.mdx
- website/content/docs/security/acl/acl-rules.mdx
Documentation updating ACL requirements for peering's GA release in Consul 1.14.
> docs(peering): peering GA ACL updates

- website/content/docs/release-notes/consul-k8s/v1_0_x.mdx
Small formatting issue on release notes, when moving around notice in the supported software section 
> docs: formatting release notes

- website/content/docs/upgrading/upgrade-specific.mdx
https://consul-mwh0hkh4q-hashicorp.vercel.app/consul/docs/upgrading/upgrade-specific#changes-to-grpc-tls-configuration
> Add -grpc-ca-file and -grpc-ca-path CLI info on upgrade notes.

- website/content/docs/agent/config/config-files.mdx
This agent config option is already supported (per @pglass), but not documented.
> docs: add retry_max agent config option

- website/content/docs/connect/cluster-peering/create-manage-peering.mdx
> Fix typo in cluster peering docs

- website/content/docs/connect/cluster-peering/k8s.mdx
add missing docs on mesh and proxydefaults config
> docs/peering/k8s: update docs with mesh and proxydefaults config

- website/content/docs/connect/cluster-peering/k8s.mdx
Small change in consistent style and adding explicit commands. Bump up versions, use minimal values config file. 
> docs: Clean up k8s cluster peering instructions

- website/content/docs/connect/cluster-peering/k8s.mdx
> docs: typo on cluster peering k8s 

- .changelog/_3783.txt
Added a changelog entry for adding partition update subcommand, an enterprise only feature
* [n/a] updated test coverage
* [n/a] external facing docs updated
> added changelog for enterprise only change

- website/content/docs/k8s/compatibility.mdx
- website/content/docs/k8s/installation/install.mdx
Small typos in Helm install for Consul K8s.
> docs: fix typos helm install

- CHANGELOG.md
Add missing changelog in 1.14.0 for https://github.com/hashicorp/consul/pull/14356 
> CHANGELOG: add alpn config for ingress and connect proxy

- CHANGELOG.md
- go.mod
- test/integration/consul-container/go.mod
- test/integration/consul-container/go.sum
Updates based on today's patch releases.
> chore: updates from 1.14.2 release

- CHANGELOG.md
- version/version.go
Updates based on today's patch releases.
> chore: updates from 1.13.4 release

- CHANGELOG.md
- version/version.go
Updates based on today's patch releases.
> docs: changelog update from 1.12.7

- .changelog/15253.txt
- CHANGELOG.md
Note: I added the backport labels at first, but realized that probably wasn't necessary.
> Clarify Vault CA changelog entry

- .changelog/15706.txt
- .circleci/bash_env.sh
- .circleci/config.yml
- .github/workflows/build.yml
> update go version to 1.18.9

- agent/dns_test.go
The go 1.20rc1 toolchain added an improved set of `vet` rules to detect loop variable capture in tests that use `t.Parallel`. Running this improved vet on the consul codebase unveiled one test that was actually _relying_ on the errant behavior.
> agent/dns_test.go:5395:70: loop variable qType captured by func literal
Fixing the shadowing with `qType := qType` broke most of the tests since the assertions for the `A` and `AAAA` record types were only ever being done against an `ANY` response so the test cases were all wrong.
While fixing this I also made the test "perfectly random" in the node ipv6/4 distribution so the test can't flake due to doing something like splitting "30" into approximately half of "16/14".
> test: remove variable shadowing in TestDNS_ServiceLookup_ARecordLimits

- website/content/docs/ecs/compatibility.mdx
This updates the Consul ECS compatibility table to indicate support for Consul 1.13 and 1.14.
> Update compatibility table for ECS

- Dockerfile
> Backport of chore(ci): update ubi base to ubi-9

- .changelog/_3846.txt
- CHANGELOG.md
- version/version.go
Update Changelog and bump version
> 1.12.8 updates

- .changelog/_3846.txt
- CHANGELOG.md
- version/version.go
Updates from the 1.13.5 release.
> 1.13.x updates from the 1.13.5 release

- .changelog/_3846.txt
- CHANGELOG.md
- version/version.go
Updates from the 1.14.3 release today.
> 1.14.x updates for 1.14.3 release

- .changelog/_3846.txt
- CHANGELOG.md
Updates from patch releases this week.
> docs: update changelog from 1.14.3, 1.13.5, 1.12.8

- website/content/docs/connect/ca/vault.mdx
- website/content/docs/k8s/connect/connect-ca-provider.mdx
- website/content/docs/k8s/deployment-configurations/vault/data-integration/connect-ca.mdx
> Update docs to reflect vault and consul compatibility

- agent/structs/config_entry_gateways.go
- agent/structs/config_entry_gateways_test.go
- agent/structs/config_entry_status.go
- api/config_entry_gateways.go
- api/config_entry_status.go
- proto/pbconfigentry/config_entry.gen.go
- proto/pbconfigentry/config_entry.go
- proto/pbconfigentry/config_entry.pb.binary.go
- proto/pbconfigentry/config_entry.pb.go
- proto/pbconfigentry/config_entry.proto
This adds the basic fields we need for an APIGateway along with its internal validation.
> Add APIGateway validation

- command/operator/raft/transferleader/transfer_leader.go
> fix cli string for id flag in transfer leadership cli

- .changelog/16015.txt
- command/connect/envoy/envoy.go
- command/connect/envoy/envoy_test.go
- command/connect/envoy/testdata/envoy-readiness-probe.golden
- website/content/commands/connect/envoy.mdx
> Add support for envoy readiness flags (#16015)

- test/integration/consul-container/libs/assert/envoy.go
- test/integration/consul-container/libs/service/helpers.go
- test/integration/consul-container/libs/topology/peering_topology.go
- test/integration/consul-container/test/basic/connect_service_test.go
- test/integration/consul-container/test/upgrade/peers_http_test.go
OSS split of ent [PR](https://github.com/hashicorp/consul-enterprise/pull/4169/commits)
> Post upgrade test validation: envoy endpoint and register service

- test/integration/consul-container/libs/assert/envoy.go
- test/integration/consul-container/libs/service/connect.go
- test/integration/consul-container/libs/service/examples.go
- test/integration/consul-container/libs/service/gateway.go
- test/integration/consul-container/libs/service/helpers.go
- test/integration/consul-container/libs/service/service.go
- test/integration/consul-container/libs/topology/peering_topology.go
- test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
- test/integration/consul-container/test/upgrade/peer_control_plane_mgw_test.go
OSS split of[ ent pr](https://github.com/hashicorp/consul-enterprise/pull/4182)
> Upgrade test: peering control plane traffic through mesh gateway

- agent/proxycfg/testing_tproxy.go
- agent/xds/builtin_extension_oss_test.go
- agent/xds/builtinextensions/validate/validate.go
- agent/xds/builtinextensions/validate/validate_test.go
- agent/xds/builtinextensiontemplate/template.go
- agent/xds/listeners.go
- agent/xds/listeners_test.go
- agent/xds/server.go
- agent/xds/testdata/builtin_extension/clusters/lambda-connect-proxy-tproxy.latest.golden
- agent/xds/testdata/builtin_extension/endpoints/lambda-connect-proxy-tproxy.latest.golden
- agent/xds/testdata/builtin_extension/listeners/lambda-connect-proxy-tproxy.latest.golden
- agent/xds/testdata/builtin_extension/routes/lambda-connect-proxy-tproxy.latest.golden
- agent/xds/testdata/validateupstream/clusters.json
- agent/xds/testdata/validateupstream/config.json
- agent/xds/validateupstream.go
- agent/xds/validateupstream_test.go
- agent/xds/xdscommon/xdscommon.go
* Add Tproxy support to Envoy Extensions (this is needed for service to service validation)
* Add service to service envoy configuration validation using /config_dump and /clusters
> troubleshoot: service to service validation

- CHANGELOG.md
- version/version.go
> Apply 1.12.9 chagnelog and prep for next release

- CHANGELOG.md
- version/version.go
> Apply 1.13.6 changelog and prep for next release

- CHANGELOG.md
Post-release step to apply changelog to main branch.
> Changelog for Consul 1.14.4, 1.13.6, and 1.12.9

- command/troubleshoot/proxy/troubleshoot_proxy.go
- troubleshoot/certs.go
- troubleshoot/stats.go
- troubleshoot/troubleshoot_proxy.go
- troubleshoot/utils.go
Enterprise PR: https://github.com/hashicorp/consul-enterprise/pull/4230
> validate certs and get stats

- website/content/docs/k8s/helm.mdx
Compare between 1.0.2 and 1.0.3 helm docs changes
> Update helm docs based on consul-k8s release/1.0.x branch

- website/content/docs/k8s/helm.mdx
Compare between 0.49.2 and 0.49.3 docs changes
> Update helm docs based on consul-k8s release/0.49.x branch to 1.13.x

- agent/consul/client.go
- agent/consul/rpc.go
- agent/consul/rpc_test.go
This change updates the the retry criteria to accommodate following use cases:
```
- Client RPC to Server -> Retry should be in the client, only the "ErrRetryElsewhere" error
- Client RPC to Follower Forwarded to Leader -> Retry should be implemented in the client, only the "ErrRetryElsewhere" error
- Server RPC executed locally -> Should NOT retry
- Server RPC forwarded to Leader -> Should retry, only "ErrRetryLater" error
```
> feat: update rpc retry criteria

- website/content/docs/release-notes/consul/v1_12_x.mdx
- website/content/docs/release-notes/consul/v1_13_x.mdx
- website/content/docs/release-notes/consul/v1_14_x.mdx
Add missing links for patch release notes.
> Add links in release-notes for the last five patch releases

- .changelog/14244.txt
- api/prepared_query.go
- api/prepared_query_test.go
> Remove empty tags 2

- agent/consul/rate/handler.go
- test/integration/consul-container/test/ratelimit/ratelimit_test.go
Change log level when rate limit exceeds given `enforcing` policy.
> change log level

- .circleci/config.yml
Rotate the SSH key used by Circle CI
> Rotate Circle CI SSH Key

- troubleshoot/proxy/troubleshoot_proxy.go
exclude inbound/outbound listeners from upstreams output
> exclude inbound/outbound listeners from upstreams output

- troubleshoot/proxy/certs.go
- troubleshoot/proxy/certs_test.go
- troubleshoot/proxy/troubleshoot_proxy.go
ENT PR: https://github.com/hashicorp/consul-enterprise/pull/4238
> add cert tests

- test/integration/consul-container/go.mod
- test/integration/consul-container/go.sum
- test/integration/consul-container/libs/assert/service.go
- test/integration/consul-container/libs/cluster/agent.go
- test/integration/consul-container/libs/cluster/builder.go
- test/integration/consul-container/libs/cluster/cluster.go
- test/integration/consul-container/libs/cluster/container.go
- test/integration/consul-container/libs/topology/peering_topology.go
- test/integration/consul-container/libs/utils/utils.go
- test/integration/consul-container/test/observability/access_logs_test.go
- test/integration/consul-container/test/upgrade/acl_node_test.go
- test/integration/consul-container/test/upgrade/traffic_management_default_subset_test.go
Oss split of ent [pr](https://github.com/hashicorp/consul-enterprise/pull/4244)
> Upgrade test: verify the agent token is working after upgrade

- command/troubleshoot/upstreams/troubleshoot_upstreams.go
- troubleshoot/proxy/testdata/listeners.json
- troubleshoot/proxy/troubleshoot_proxy.go
- troubleshoot/proxy/upstreams.go
- troubleshoot/proxy/upstreams_test.go
Get Upstream IPs and clusters for troubleshooting tool
> get upstream IPs

- command/troubleshoot/proxy/troubleshoot_proxy.go
- command/troubleshoot/upstreams/troubleshoot_upstreams.go
- troubleshoot/proxy/troubleshoot_proxy.go
Update troubleshoot CLI:
- flag names
- required flags 
- upstreams output
> update troubleshoot CLI, update flags and upstreams output

- troubleshoot/proxy/stats.go
- troubleshoot/proxy/troubleshoot_proxy.go
troubleshoot basic envoy stats for an upstream
> troubleshoot basic envoy stats for an upstream

- ui/packages/consul-ui/README.md
Add Vercel information to the UI readme.
[related investigation](https://hashicorp.slack.com/archives/C9X0VGJNL/p1676064064615999)
> UI: add Vercel info to the ui readme

- test/integration/connect/envoy/case-dogstatsd-udp/verify.bats
- test/integration/connect/envoy/case-statsd-udp/verify.bats
- test/integration/connect/envoy/case-zipkin/verify.bats
- test/integration/connect/envoy/helpers.bash
oss split of ent [pr](https://github.com/hashicorp/consul-enterprise/pull/4339)
> integ test: fix retry upstream test

- test/integration/consul-container/libs/assert/envoy.go
- test/integration/consul-container/libs/service/connect.go
- test/integration/consul-container/libs/service/examples.go
- test/integration/consul-container/libs/service/gateway.go
- test/integration/consul-container/libs/service/service.go
- test/integration/consul-container/libs/topology/peering_topology.go
- test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
- test/integration/consul-container/test/upgrade/peering_control_plane_mgw_test.go
- test/integration/consul-container/test/upgrade/peering_http_test.go
oss split of [PR](https://github.com/hashicorp/consul-enterprise/pull/4351)
> upgrade test: fix flaky peering through mesh gateway

- agent/proxycfg/ingress_gateway.go
- agent/proxycfg/manager.go
- agent/proxycfg/state.go
Manual backport of https://github.com/hashicorp/consul/pull/16277
> Backport of Fix nil-pointer panics from proxycfg package.

- .changelog/16292.txt
This adds the changelog entry for server side rate limiter.
> add server side rate-limiter changelog entry

- test/integration/consul-container/test/ratelimit/ratelimit_test.go
> fix rate limit tests flakiness

- .changelog/16369.txt
This adds a changelog entry announcing the availability of VM support for API gateway. This changelog entry reflects many PRs that have taken place over recent weeks.
> Add changelog entry for API Gateway (Beta)

- agent/consul/server_log_verification.go
- agent/metrics_test.go
- agent/setup.go
This PR splits out the code changes from #16270 since the docs need more work and can be merged later.
These were already reviewed in #16270.
> Correct WAL metrics registrations

- website/content/docs/agent/limits/init-rate-limits.mdx
Correct metrics name for rate limiting
Addresses comment on the previous PR: https://github.com/hashicorp/consul/pull/16345#discussion_r1116007418
> fix(docs): correct rate limit metrics

- .release/ci.hcl
> Fix promote staging

- .release/ci.hcl
> add back staging bits

- website/content/docs/agent/limits/set-global-traffic-rate-limits.mdx
> Add missing link

- website/content/docs/release-notes/consul/v1_15_x.mdx
Adding a known issue for running Consul with newer supported Envoy versions when using client agents.
> docs: Update release notes with Envoy compat issue

- agent/dns_test.go
`TestDNS_TCP_and_UDP_Truncate` is our longest running test averaging over 3m of runtime.
The biggest bottleneck when profiling was the registration of 5000-10000 services at the start which is meant to cause DNS responses to be truncated.
The catalog registration is able to be run concurrently, reducing the runtime by magnitudes (3m10s -> 7s on my machine)
> Speed up test by registering services concurrently

- website/content/docs/services/discovery/dns-static-lookups.mdx
This PR fixes an empty link in the main DNS usage page.
> fixes empty link in DNS usage page

- test/integration/consul-container/libs/assert/service.go
- test/integration/consul-container/libs/cluster/agent.go
- test/integration/consul-container/libs/cluster/builder.go
- test/integration/consul-container/libs/cluster/cluster.go
- test/integration/consul-container/libs/cluster/container.go
- test/integration/consul-container/test/upgrade/peering_http_test.go
oss split of ent [PR](https://github.com/hashicorp/consul-enterprise/pull/4566)
> upgrade test: discovery chain across partition

- CHANGELOG.md
- api/go.mod
- envoyextensions/go.mod
- envoyextensions/go.sum
- go.mod
- test/integration/consul-container/go.mod
- test/integration/consul-container/go.sum
- troubleshoot/go.mod
- troubleshoot/go.sum
> Bump submodules from latest 1.15.1 patch release

- .github/workflows/jira-pr.yaml
Filter out OSS/ENT merges and dependabot for JIRA PR syncs
> JIRA pr check: Filter out OSS/ENT merges

- agent/configentry/discoverychain.go
- agent/consul/discoverychain/compile.go
- agent/consul/discoverychain/compile_test.go
- agent/consul/state/config_entry.go
- agent/consul/state/config_entry_test.go
- agent/structs/config_entry_discoverychain.go
- agent/structs/discovery_chain.go
- agent/structs/structs.deepcopy.go
Add peer locality to discovery chains.
> Add Peer Locality to Discovery Chains

- agent/configentry/discoverychain.go
- agent/consul/discoverychain/compile.go
- agent/consul/state/config_entry.go
- agent/structs/config_entry_discoverychain.go
- agent/structs/config_entry_discoverychain_test.go
- agent/structs/config_entry_sameness_group.go
- agent/structs/discovery_chain.go
* Add service resolver failover and redirects to discovery chains.
> Add Sameness Groups to Discovery Chains

- .github/workflows/jira-issues.yaml
- .github/workflows/jira-pr.yaml
> Fix jira sync actions, remove custom fields

- .github/workflows/jira-issues.yaml
- .github/workflows/jira-pr.yaml
> Docs: Jira sync Update issuetype to bug

- api/health_test.go
Manual import of ent [pr](https://github.com/hashicorp/consul-enterprise/pull/4776)
> chore: replace hardcoded node name with a constant

- website/content/api-docs/connect/intentions.mdx
- website/content/commands/intention/check.mdx
- website/content/commands/intention/create.mdx
- website/content/commands/intention/delete.mdx
- website/content/commands/intention/get.mdx
- website/content/commands/intention/list.mdx
- website/content/commands/intention/match.mdx
> Fix broken links from api docs

- website/content/docs/k8s/helm.mdx
Generated by running `make gen-helm-docs`
> Regen helm docs

- .github/workflows/build.yml
Signed-off-by: Dan Bond <danbond@protonmail.com>
Fixes a bug introduced in https://github.com/hashicorp/consul/pull/16669
> fix build workflow

- .github/workflows/jira-issues.yaml
- .github/workflows/jira-pr.yaml
> Fix Edu Jira automation

- .changelog/_4821.txt
- agent/consul/prepared_query_endpoint.go
- agent/consul/prepared_query_endpoint_test.go
- agent/prepared_query_endpoint.go
- agent/structs/prepared_query.go
- api/prepared_query.go
- website/content/api-docs/query.mdx
This is a port of changes made upstream
> changes to support new PQ enterprise fields

- .github/workflows/verify-ci.yml
> Github Actions Migration - move verify-ci workflows to GHA

- .circleci/config.yml
- .github/scripts/get_runner_classes.sh
- .github/scripts/notify_slack.sh
- .github/scripts/rerun_fails_report.sh
- .github/scripts/set_test_package_matrix.sh
- .github/workflows/build-distros.yml
- .github/workflows/frontend.yml
- .github/workflows/go-tests.yml
- .github/workflows/reusable-check-go-mod.yml
- .github/workflows/reusable-dev-build.yml
- .github/workflows/reusable-lint.yml
- .github/workflows/reusable-unit-split.yml
- .github/workflows/reusable-unit.yml
- .github/workflows/verify-ci.yml
> Github Actions Migration - move go-tests workflows to GHA

- CHANGELOG.md
- website/content/docs/release-notes/consul/v1_15_x.mdx
- website/content/docs/upgrading/upgrade-specific.mdx
> docs: raise awareness of GH-16779

- .github/workflows/go-tests.yml
- .github/workflows/reusable-unit.yml
updating command to reflect the additional package exclusions in CircleCI for enterprise.
> ci: fixing go-test-race failure

- api/config_entry_discoverychain.go
- api/config_entry_discoverychain_test.go
Add the failover policy regions field to api package. 
* NA external facing docs updated
> add region field

- website/content/docs/agent/config/cli-flags.mdx
> Update cli-flags.mdx - typo

- .github/workflows/go-tests.yml
- agent/proxycfg/proxycfg.go
- docs/service-mesh/README.md
> ci: increase deep-copy and lint-enum jobs to use large runner as they hang in ENT

- .github/workflows/go-tests.yml
- .github/workflows/reusable-dev-build.yml
> ci: add arm64 testing

- .github/workflows/go-tests.yml
- .github/workflows/reusable-dev-build.yml
> Backport of ci: add arm64 testing into release/1.14.x

- .github/workflows/frontend.yml
This PR fixes the following issues when running this GitHub Actions workflow in ENT:
- Manually install yarn
- Manually install Chrome
- Run ENT tests dependent on repo.
> ci: fixes missing deps in frontend gha workflows

- .github/workflows/go-tests.yml
- .github/workflows/reusable-unit-split.yml
- .github/workflows/reusable-unit.yml
This has a passing CI run in enterprise: https://github.com/hashicorp/consul-enterprise/actions/runs/4568643952
> ci: always test oss and conditionally test enterprise

- .github/workflows/go-tests.yml
> temporarily disable macos-arm64 tests job in go-tests

- .github/workflows/build-artifacts.yml
- .github/workflows/build-distros.yml
- .github/workflows/frontend.yml
- .github/workflows/go-tests.yml
- .github/workflows/verify-ci.yml
> ci: Add success jobs. make go-test-enterprise conditional. build-distros and go-tests trigger on push to main and release branches

- website/content/docs/connect/config-entries/service-defaults.mdx
Fix typo in LocalRequestTimeoutMs
> [docs] fix typo in LocalRequestTimeoutMs

- .github/workflows/build-distros.yml
> ci: add GOTAGS to build-distros

- .circleci/config.yml
> ci: remove build-distros from CircleCI

- .github/pull_request_template.md
This change should help remind PR authors to include appropriate backport labels on their PR
> Added backport labels to PR template checklist

- agent/grpc-external/services/resource/delete.go
- agent/grpc-external/services/resource/delete_test.go
Fixes bug when caller opts to delete a resource by name (Id.Uid == "").
Extended `deleteTestCases` to cover all combinations of version and uid.
> Fix delete when uid not provided

- website/content/docs/troubleshoot/common-errors.mdx
Fixes a bad link introduced in [17005](https://github.com/hashicorp/consul/pull/17005)
> fixed bad link

- agent/consul/acl_server.go
- agent/consul/leader.go
- agent/consul/leader_connect.go
- agent/consul/leader_intentions.go
- agent/consul/leader_intentions_test.go
- agent/consul/leader_test.go
- agent/consul/reporting/reporting.go
- agent/consul/reporting/reporting_oss.go
- agent/consul/server.go
- agent/consul/server_oss.go
- agent/consul/system_metadata.go
- agent/consul/system_metadata_test.go
Adds reporting agent set up which is no-op at the moment
Confirmed no reporting logs are emitted when ran locally via `consul agent -dev`
> feat: set up reporting agent

- agent/consul/state/catalog.go
- agent/consul/state/intention.go
- agent/consul/state/intention_test.go
This PR causes 'virtual services' represented by service resolver/router/splitter config entries but without any existing service instances to be returned in intention topology lookups. This is to enable creating the config entry for the service ahead of time so that there will be a virtual IP for transparent proxies to use for these upstreams.
> Include virtual services from discovery chain in intention topology

- agent/consul/discoverychain/compile.go
- agent/consul/prepared_query/walk_test.go
- agent/consul/prepared_query_endpoint.go
- agent/consul/prepared_query_endpoint_oss.go
- agent/consul/prepared_query_endpoint_oss_test.go
- agent/consul/prepared_query_endpoint_test.go
- agent/consul/state/config_entry_sameness_group.go
- agent/structs/config_entry_sameness_group_oss.go
- agent/structs/prepared_query.go
- agent/structs/prepared_query_test.go
- api/prepared_query.go
- website/content/api-docs/query.mdx
This is a port of enterprise code already merged in
> Add sameness group field to prepared queries

- website/content/docs/k8s/deployment-configurations/single-dc-multi-k8s.mdx
Addresses the following issue: https://github.com/hashicorp/consul/issues/16849
> Update single-dc-multi-k8s to require flat network

- website/content/docs/k8s/deployment-configurations/single-dc-multi-k8s.mdx
Manual backport of https://github.com/hashicorp/consul/pull/17126
> Update single-dc-multi-k8s add flat network requirements 

- proto-public/pbresource/resource.pb.binary.go
- proto-public/pbresource/resource.pb.go
- proto-public/pbresource/resource.proto
- proto-public/pbresource/resource_grpc.pb.go
Adds protobuf documentation for the gRPC Resource Service 📝
> proto-public: document resource service

- website/content/docs/enterprise/admin-partitions.mdx
Fixup an inaccurate note about nodes being scoped to namespaces.
> docs: fixup note about node scope for admin partitions

- agent/structs/config_entry_intentions.go
- api/config_entry_discoverychain.go
Port of enterprise, already reviewed in there
> fixed aliases for sameness group (sameness_group)

- agent/grpc-external/services/resource/write.go
- agent/grpc-external/services/resource/write_test.go
As discussed in the sync today, this PR makes it so that we'll populate the owner `Uid` if it was not given (see comment inline for consistency-related caveats).
> resource: owner references must include a uid

- agent/consul/reporting/reporting.go
- agent/consul/reporting/reporting_oss.go
- agent/consul/server.go
Adding no-op background routine method to reporting manager
> feat: add no-op reporting background routine

- website/content/docs/integrate/partnerships.mdx
Fix broken link.
Found with automated broken link checker:
https://github.com/hashicorp/consul/issues/17199
> Fix broken lightstep link

- test/integration/consul-container/libs/agent/builder.go
- test/integration/consul-container/libs/agent/container.go
- test/integration/consul-container/libs/service/assets/Dockerfile-consul-envoy
- test/integration/consul-container/libs/service/connect.go
- test/integration/consul-container/libs/service/gateway.go
- test/integration/consul-container/libs/utils/version.go
- test/integration/consul-container/libs/utils/version_oss.go
- test/integration/consul-container/test/upgrade/healthcheck_test.go
Use correct docker images in integration tests
> fix: integration tests

- .github/workflows/test-integrations.yml
This is no longer needed after the ipv6 fix from GitHub.
> ci: remove test splitting for compatibility tests

- .github/workflows/test-integrations.yml
> manual backport of ci: remove test splitting for compatibility tests into release/1.14.x

- .github/workflows/test-integrations.yml
Reverts hashicorp/consul#17166
> Revert "ci: remove test splitting for compatibility tests"

- agent/consul/health_endpoint.go
All tests passed in OSS, but not ENT on #17241. This is a patch to resolve the problem for both.
> Fix ent bug caused by #17241.

- agent/consul/health_endpoint.go
Manual backport of: https://github.com/hashicorp/consul/pull/17278
> Backport of Fix ent bug caused by #17241. (#17278)

- website/content/docs/k8s/installation/install-cli.mdx
> Update consul-k8s install command so it is valid

- .github/workflows/go-tests.yml
- .github/workflows/reusable-unit-split.yml
- .github/workflows/reusable-unit.yml
- .github/workflows/test-integrations.yml
> Backport of ci:upload test results to datadog into release/1.13.x

- test/integration/consul-container/test/snapshot/snapshot_restore_test.go
Backport of https://github.com/hashicorp/consul/pull/17120
> Backport flaky-test fix to 1.15

- agent/grpc-external/services/peerstream/subscription_manager.go
- agent/sidecar_service.go
- agent/structs/config_entry_exports.go
- agent/structs/structs.go
This is the manual backport of https://github.com/hashicorp/consul/pull/17328
> 1.15 fix submat view bug

- agent/structs/config_entry_test.go
Fix broken test on release branch 
* [NA] updated test coverage
* [NA] external facing docs updated
* [NA] appropriate backport labels added
> fix test on 1.14.x branch

- agent/structs/config_entry_test.go
fix test on release branch
* [NA] updated test coverage
* [NA] external facing docs updated
* [NA] appropriate backport labels added
> fix test on 1.15.x branch

- agent/agent.go
Small fix for https://github.com/hashicorp/consul/pull/17171
> agent: don't write server metadata in dev mode

- test/integration/consul-container/libs/assert/envoy.go
- test/integration/consul-container/libs/assert/peering.go
- test/integration/consul-container/libs/assert/service.go
- test/integration/consul-container/libs/utils/tenancy.go
- test/integration/consul-container/libs/utils/version.go
- test/integration/consul-container/libs/utils/version_oss.go
Various refactors to the `test/integration/consul-container` library.
> test: slight refactoring ahead of peering testing improvements

- agent/grpc-external/services/peerstream/stream_test.go
- proto/prototest/testing.go
- proto/prototest/testing_test.go
manual backport of #17416 to 1.15.x
> [1.15.x] prototest: fix early return condition in AssertElementsMatch

- docs/persistence/README.md
- docs/resources/README.md
- docs/resources/guide.md
Took an initial pass at writing up a developer guide for resources and controllers.
> docs: first pass at a resource/controller developer guide

- command/version/formatter.go
- command/version/version.go
- version/fips.go
OSS hooks for FIPS version changes in ENT.
This does not affect anything in OSS.
> OSS version changes for FIPS work

- .changelog/4633.txt
This adds a changelog for ip rate limiting, an enterprise feature.
> add changelog for IP based rate limiting

- .changelog/5102.txt
Add changelog for enterprise-only reporting feature
> add changelog for reporting

- CHANGELOG.md
add changelog entries for 1.15.3
* [NA] updated test coverage
* [NA] appropriate backport labels added
> add changelog entries for 1.15.3

- agent/local/state.go
ENT PR: https://github.com/hashicorp/consul-enterprise/pull/5517
> continue anti-entropy sync when failures exist

- agent/consul/merge_test.go
- agent/grpc-external/services/dataplane/get_supported_features_test.go
- tlsutil/config_test.go
- version/version.go
A few small testing updates for FIPS tests in ENT.
> Update tests for fips

- agent/agent_endpoint_test.go
- agent/consul/acl_endpoint_test.go
- agent/consul/client_test.go
- agent/consul/multilimiter/multilimiter_test.go
- agent/consul/prepared_query_endpoint_test.go
- agent/dns_test.go
- agent/grpc-external/services/peerstream/stream_test.go
- agent/local/state_test.go
Backport of #17600 to release/1.15.x
> Backport of fix some testing.T retry.R mixups into release/1.15.x

- agent/agent_endpoint_test.go
- agent/consul/acl_endpoint_test.go
- agent/consul/client_test.go
- agent/consul/prepared_query_endpoint_test.go
- agent/dns_test.go
- agent/grpc-external/services/peerstream/stream_test.go
- agent/local/state_test.go
Backport of https://github.com/hashicorp/consul/pull/17600 to release/1.14.x
> Backport of fix some testing.T retry.R mixups into release/1.14.x

- .changelog/_5805.txt
- bringing repo to parity with enterprise repo
> enterprise changelog update for audit

- .changelog/17636.txt
- agent/cache-types/connect_ca_leaf.go
- agent/cache/cache.go
A code review for https://github.com/hashicorp/consul/pull/17075 surfaced a few minor goroutine leaks in refactored code. This patches the pre-refactored version suitable for backporting.
> cache: fix a few minor goroutine leaks in leaf certs and the agent cache

- agent/agent_endpoint.go
- agent/agent_endpoint_test.go
- agent/proxycfg/mesh_gateway.go
Sorting these imports in the oss/ent files so that they match and avoid having weird merge conflicts.
> sort some imports that are wonky between oss and ent

- command/agent/agent.go
Porting the counterpart of ENT PR: https://github.com/hashicorp/consul-enterprise/pull/5559
> fix: add agent info reporting log

- website/content/docs/api-gateway/upgrades.mdx
> additional feedback on API gateway upgrades

- website/content/docs/k8s/compatibility.mdx
Add 1.16.x compat matrix changes for consul-k8s.
> Update consul-k8s compat matrix

- .changelog/17719.txt
- Dockerfile
Bump Alpine to 3.18 to be consistent with Consul K8s
> Bump Alpine to 3.18

- website/content/docs/connect/proxies/envoy.mdx
Updating the compat matrix for 1.16.x. Also expanded the table to account for default bundled `consul-dataplane` version.
> docs - update Envoy and Dataplane compat matrix

- website/content/docs/connect/gateways/index.mdx
- website/content/docs/connect/gateways/mesh-gateway/index.mdx
- website/content/docs/connect/gateways/mesh-gateway/peering-via-mesh-gateways.mdx
- website/content/docs/enterprise/admin-partitions.mdx
- website/content/docs/lambda/invoke-from-lambda.mdx
- website/redirects.js
Replaces links to `service-to-service-traffic-peers` with links to `establish-cluster-peering` and adds a redirect.
> added redirects and updated links

- website/content/commands/license.mdx
This PR is to clarify what happens if the license get command is run on a follower if the leader hasn't been updated with a newer license.
> Update license get explanation

- website/content/docs/k8s/upgrade/index.mdx
Failed cherrypick for #17760  so re-doing here.
> docs - redo cherry pick from Consul K8s upgrade doc #17760

- website/content/docs/concepts/service-mesh.mdx
Deleted two commas which looks quite like some leftovers.
Not applicable here.
https://developer.hashicorp.com/consul/docs/concepts/service-mesh
> Tiny improvement in documentation: Update service-mesh.mdx

- website/content/docs/k8s/upgrade/index.mdx
> docs: update upgrade to consul-dataplane docs on k8s

- website/content/docs/api-gateway/usage/errors.mdx
Error is commonly reported as an issue among customers, adding an explanation to our common error docs. 
This doc update is needed for the 1.16 release today.
> api-gateway: add operation cannot be fulfilled error to common errors

- website/redirects.js
Updates temporary redirects set for 1.16-rc to permanent redirects for the GA release.
> updated redirects for 1.16.0

- website/content/docs/api-gateway/upgrades.mdx
- website/content/docs/api-gateway/usage/errors.mdx
This ports over some last-minute docs changes from #17874 and #17875 
- Validate that this is a low-risk docs-only change
- Compare with PRs linked above
> [release/1.16.0] api-gateway: update docs

- CHANGELOG.md
> Changelog - add 1.13.9, 1.14.8, and 1.15.4

- website/content/docs/release-notes/consul-k8s/v1_2_x.mdx
- website/content/docs/release-notes/consul/v1_16_x.mdx
- website/data/docs-nav-data.json
> Create and update release notes for 1.16 and 1.2

- CHANGELOG.md
- agent/xds/proxysupport/proxysupport.go
> Include changes from  v1.13.9 in 1.13.x

- website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Adds a dash to sameness group examples for partitions and peers.
> docs: Add dash (-) to sameness group examples

- website/content/api-docs/health.mdx
Fixes this issue https://github.com/hashicorp/consul/issues/17814#issuecomment-1612391487
> Fix streaming backend link

- website/content/docs/api-gateway/usage/usage.mdx
> Fix formatting codeblocks for APIgw docs (backports)

- CHANGELOG.md
Porting over the 1.16.0 changelog entry from the `release/1.16.0` branch
> Add changelog entry for 1.16.0

- .changelog/17894.txt
- agent/configentry/resolve.go
- agent/consul/config_endpoint_test.go
> Manual backport of #17894.

- website/content/docs/agent/limits/index.mdx
Added Enterprise Alert and fixed broken links in rate-limiting documentation.
> Fixes Traffic rate limitting docs

- website/content/docs/k8s/connect/index.mdx
Address feedback from https://github.com/hashicorp/consul/pull/18037
> docs - address feedback on service mesh overview for k8s

- test-integ/go.mod
- test-integ/peering_commontopo/ac5_1_test.go
- test-integ/peering_commontopo/ac5_2_test.go
This tests prepared queries failover in a peered mirror cluster.
> Refactor Prepared Query Failover tests

- test-integ/peering_commontopo/ac5_2_test.go
> delete failing health checks and test pq failover

- website/content/docs/k8s/helm.mdx
Update the helm docs on main(s) to make updating docs (I have a PR coming) easier.
It's probably a good idea to keep this update to date on main anyway.
> Update helm docs on main

- website/content/docs/k8s/upgrade/index.mdx
*note*: will merge once consul-k8s 0.49.8 is released
> Docs for dataplane upgrade on k8s

- website/content/docs/k8s/upgrade/index.mdx
Manual backport of https://github.com/hashicorp/consul/pull/18051
> docs - Docs for dataplane upgrade on k8s (#18051)

- website/content/docs/connect/nomad.mdx
Just a typo in the docs.
There is a small typo in the Markdown re the title of the page.
N/A
Live on Developer at https://developer.hashicorp.com/nomad/tools/autoscaling
> :ermahgerd "Sevice Mesh" -> "Service Mesh"

- agent/xds/clusters_test.go
- agent/xds/listeners_test.go
- agent/xds/testdata/clusters/connect-proxy-with-jwt-config-entry-with-local.latest.golden
- agent/xds/testdata/clusters/connect-proxy-with-jwt-config-entry-with-remote-jwks.latest.golden
- agent/xds/testdata/listeners/connect-proxy-with-jwt-config-entry-with-local.latest.golden
- adding some additional test coverage for jwt feature (in xds package)
> Improve XDS test coverage: JWT auth edition

- grafana/README.md
- grafana/consul-k8s-control-plane-monitoring.json
Add the grafana dashboard for monitoring consul-k8s's control plane.
1. Landing page
2. Raft
3. Leadership
4. Server agens
5. Client agents
6. rpc
7. Catalog and ACL
8. Client agents shown on landing page
> NET-4804: Add dashboard for monitoring consul-k8s

- website/content/docs/enterprise/license/utilization-reporting.mdx
Automated enterprise license utilization reporting does not run exactly every 24 hours. This PR caveats the timing and clarifies that reporting complies with GDPR. I'm submitting it on behalf of @aliciaclark1066.
* ~updated test coverage~
> Clarify license reporting timing and GDPR compliance

- website/data/docs-nav-data.json
Ensure that all release branches are aligned on content.
> Fix utilization reporting docs sync

- .github/workflows/reusable-dev-build-windows.yml
- .github/workflows/test-integrations-windows.yml
- .github/workflows/test-integrations.yml
- Updating actions versions before July 31st deadline
> Update actions for TSCCR

- website/redirects.js
User reported that link for mesh gateways on this [blog post](https://www.hashicorp.com/blog/achieving-multi-tenancy-with-consul-administrative-partitions) is broken. This PR adds redirects for the old page to the new page.
> Add redirects for mesh-gateway docs

- website/content/docs/connect/distributed-tracing.mdx
Fix ServiceDefaults example in distributed tracing
> [docs] Fix ServiceDefaults example in distributed tracing

- test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
- test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.sum
Locally I get this diff. Checking to see if it drifted as far as CI is concerned.
> chore: make go-mod-tidy

- website/content/docs/k8s/compatibility.mdx
Add OpenShift versions for clarity and also a link to the OpenShift deploy guide.
> k8s compat - Openshift versions

- website/content/docs/k8s/helm.mdx
Updates helm docs to include changes made in consul-k8s 1.1.4
> Updates helm docs to include changes from consul-k8s 1.1.4

- website/content/docs/k8s/helm.mdx
Updates helm values docs to be consistent with consul-k8s 1.2.1
> Update Helm docs for consul-k8s 1.2.1

- website/content/docs/agent/config/config-files.mdx
Manual backport of https://github.com/hashicorp/consul/pull/18477
> docs: specify manual server metadata intervention

- README.md
Placed BUSL badge first and fixed Docker Hub link to `hashicorp/consul`
> README - re-order badges and update hub link

- README.md
- website/content/docs/dynamic-app-config/kv.mdx
Manual backport of KV re-positioning.
> manual backport of #18301

- .github/workflows/nightly-test-1.13.x.yaml
- .github/workflows/nightly-test-1.14.x.yaml
- .github/workflows/nightly-test-1.15.x.yaml
- .github/workflows/nightly-test-1.16.x.yaml
- .github/workflows/nightly-test-integrations-1.15.x.yml
- .github/workflows/nightly-test-integrations-1.16.x.yml
- .github/workflows/nightly-test-main.yaml
- .github/workflows/test-integrations.yml
> Create nightly test-integration for consul release branch

- .changelog/18560.txt
- ui/packages/consul-peerings/app/components/consul/peer/form/token/fieldsets/index.hbs
Small verbiage update, no backport needed
> UI: community verbiage

- website/content/docs/connect/failover/index.mdx
> Fix broken link on sameness group page

- .github/scripts/get_runner_classes_windows.sh
Fix Consul Ent runner name as suggested by Rel Eng Team.
CI
> Fix windows Ent runner

- .changelog/18667.txt
- agent/acl_endpoint.go
- agent/acl_endpoint_test.go
- agent/consul/acl_endpoint.go
- agent/consul/acl_replication_test.go
- agent/consul/acl_replication_types.go
- agent/consul/state/acl.go
- agent/consul/state/acl_ce.go
- agent/consul/state/acl_schema.go
- agent/consul/state/acl_test.go
- agent/structs/acl.go
- api/acl.go
- api/acl_test.go
- website/content/api-docs/acl/tokens.mdx
This is a manual backport of: https://github.com/hashicorp/consul/pull/18667
> [NET-5399] Add support for querying tokens by service name.

- .github/scripts/get_runner_classes_windows.sh
Using m6a.4xlarge for Ent repo for windows integration tests
CI
> Using larger machine for Enterprise

- agent/consul/fsm/snapshot_test.go
- agent/consul/state/acl_test.go
- agent/structs/acl.go
This PR updates builtin policy descriptions to make them more consistent.
[Jira](https://hashicorp.atlassian.net/browse/CC-6039)
> [CC-6039] Update builtin policy descriptions

- .changelog/18724.txt
- agent/agent.go
- agent/consul/usagemetrics/usagemetrics.go
- agent/consul/usagemetrics/usagemetrics_ce_test.go
- agent/consul/usagemetrics/usagemetrics_test.go
CE version of approved ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6876
> fix: emit consul version metric on a regular interval

- .changelog/18719.txt
- agent/consul/acl_endpoint.go
- agent/consul/acl_endpoint_test.go
- agent/consul/auth/binder.go
- agent/consul/auth/binder_test.go
- agent/consul/auth/login.go
- agent/consul/state/acl.go
- agent/structs/acl.go
- api/acl.go
- command/acl/acl_helpers.go
- command/acl/bindingrule/create/bindingrule_create.go
- command/acl/bindingrule/create/bindingrule_create_test.go
- command/acl/bindingrule/formatter.go
- command/acl/bindingrule/update/bindingrule_update.go
- command/acl/bindingrule/update/bindingrule_update_test.go
- Supporting templated policies in binding rules
> [NET-5330] Support templated policies in Binding rules

- .changelog/18724.txt
- agent/agent.go
- agent/consul/usagemetrics/usagemetrics.go
- agent/consul/usagemetrics/usagemetrics_ce_test.go
- agent/consul/usagemetrics/usagemetrics_test.go
Manual backport (automated backport failed) for https://github.com/hashicorp/consul/pull/18724
> [manual backport]  1.14.x - emit consul version periodically

- .github/scripts/get_runner_classes_windows.sh
Fixes machine size for integration tests windows.
> Fix windows integrations tests machine size

- .github/workflows/test-integrations-windows.yml
- test/integration/connect/envoy/run-tests.windows.sh
> Added logs for debugging

- .changelog/18773.txt
- agent/connect/ca/provider_vault.go
- agent/connect/ca/provider_vault_test.go
(cherry picked from commit 4dfca64ded20512089c015f4913e969989934431)
> [1.14.x] Vault CA provider clean up previous default issuers (#18773)

- .changelog/18773.txt
- agent/connect/ca/provider_vault.go
- agent/connect/ca/provider_vault_test.go
(cherry picked from commit 4dfca64ded20512089c015f4913e969989934431)
> [1.15.x] Vault CA provider clean up previous default issuers (#18773)

- .changelog/18773.txt
- agent/connect/ca/provider_vault.go
- agent/connect/ca/provider_vault_test.go
(cherry picked from commit 4dfca64ded20512089c015f4913e969989934431)
> [1.16.x] Vault CA provider clean up previous default issuers (#18773)

- agent/hcp/telemetry/otel_sink_test.go
> Fix flaky test

- test/integration/consul-container/libs/service/common.go
- test/integration/consul-container/libs/service/examples.go
- test/integration/consul-container/test/gateways/gateway_endpoint_test.go
- test/integration/consul-container/test/gateways/http_route_test.go
- Added test to exersize new retry/timeout functionality 
CI Passes
* [ X ] updated test coverage
> Retry and timeout test acceptance test

- internal/catalog/internal/types/service.go
- internal/catalog/internal/types/service_test.go
> catalog: Default protocol to tcp in catalog.Service if unspecified

- agent/agent_endpoint_test.go
- agent/consul/leader_connect_test.go
- agent/health_endpoint_test.go
- command/acl/token/update/token_update_test.go
> Remove flaky test assertions

- go.mod
- go.sum
- test/integration/consul-container/go.mod
Updating Consul API Version for 1.14.x
> Updating Consul API Version for 1.14.x

- go.mod
- go.sum
Updating API Version for consul 1.15.x
> Update 1.15.x consul api version

- CHANGELOG.md
Adds changelog entries for patch releases
> Added changelog entries for 1.14.10, 1.15.6, 1.16.2

- .github/workflows/go-tests.yml
> Test skip ci

- internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder_test.go
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multi-destination.golden
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden
> NET-5131 - support multiple ported upstreams tests

- website/content/docs/k8s/helm.mdx
> [1.14.x] Update helm docs

- website/content/docs/k8s/helm.mdx
> [1.16.x] Update helm docs

- agent/hcp/telemetry_provider_test.go
> skip flaky test

- website/content/api-docs/catalog.mdx
- website/content/docs/architecture/coordinates.mdx
- website/content/docs/connect/config-entries/exported-services.mdx
- website/content/docs/connect/config-entries/ingress-gateway.mdx
- website/content/docs/connect/config-entries/terminating-gateway.mdx
- website/content/docs/connect/configuration.mdx
- website/content/docs/connect/proxies/built-in.mdx
- website/content/docs/connect/proxies/envoy-extensions/usage/otel-access-logging.mdx
- website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx
- website/content/docs/connect/proxies/envoy.mdx
- website/content/docs/connect/proxies/proxy-config-reference.mdx
- website/content/docs/dynamic-app-config/watches.mdx
- website/content/docs/ecs/manual/install.mdx
- website/content/docs/lambda/registration/automate.mdx
- website/content/docs/nia/api/status.mdx
- website/content/docs/security/acl/acl-federated-datacenters.mdx
- website/content/docs/security/acl/acl-rules.mdx
- website/content/docs/security/acl/tokens/index.mdx
- website/content/docs/services/configuration/services-configuration-reference.mdx
- website/content/docs/services/usage/checks.mdx
- website/content/docs/services/usage/define-services.mdx
This commit fixes invalid JSON in various code examples.
> docs: Fix invalid JSON in code examples

- agent/metrics_test.go
> Dump response body on fail

- website/content/api-docs/catalog.mdx
- website/content/docs/architecture/coordinates.mdx
- website/content/docs/connect/config-entries/exported-services.mdx
- website/content/docs/connect/config-entries/ingress-gateway.mdx
- website/content/docs/connect/config-entries/terminating-gateway.mdx
- website/content/docs/connect/configuration.mdx
- website/content/docs/connect/proxies/built-in.mdx
- website/content/docs/connect/proxies/envoy.mdx
- website/content/docs/connect/registration/service-registration.mdx
- website/content/docs/dynamic-app-config/watches.mdx
- website/content/docs/ecs/manual/install.mdx
- website/content/docs/lambda/registration/automate.mdx
- website/content/docs/nia/api/status.mdx
- website/content/docs/security/acl/acl-federated-datacenters.mdx
- website/content/docs/security/acl/acl-rules.mdx
- website/content/docs/security/acl/tokens/index.mdx
- website/content/docs/services/configuration/services-configuration-reference.mdx
- website/content/docs/services/usage/checks.mdx
- website/content/docs/services/usage/define-services.mdx
backport of commit cc40e084bbddcbf43e90c9fda5b3271d7392e59e
> Backport of docs: Fix invalid JSON into release/1.14.x

- website/content/api-docs/catalog.mdx
- website/content/docs/architecture/coordinates.mdx
- website/content/docs/connect/config-entries/exported-services.mdx
- website/content/docs/connect/config-entries/ingress-gateway.mdx
- website/content/docs/connect/config-entries/terminating-gateway.mdx
- website/content/docs/connect/configuration.mdx
- website/content/docs/connect/proxies/built-in.mdx
- website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx
- website/content/docs/connect/proxies/envoy.mdx
- website/content/docs/connect/proxies/proxy-config-reference.mdx
- website/content/docs/dynamic-app-config/watches.mdx
- website/content/docs/ecs/manual/install.mdx
- website/content/docs/lambda/registration/automate.mdx
- website/content/docs/nia/api/status.mdx
- website/content/docs/security/acl/acl-federated-datacenters.mdx
- website/content/docs/security/acl/acl-rules.mdx
- website/content/docs/security/acl/tokens/index.mdx
- website/content/docs/services/configuration/services-configuration-reference.mdx
- website/content/docs/services/usage/checks.mdx
- website/content/docs/services/usage/define-services.mdx
backport of commit cc40e084bbddcbf43e90c9fda5b3271d7392e59e
> Backport of docs: Fix invalid JSON into release/1.16.x

- website/content/docs/connect/distributed-tracing.mdx
backport of commmit 38c356c39bc60181dcdc56ec607e6dbc5ad7aa21
> Backport of docs: Fix ServiceDefaults example in distributed tracing into release/1.16.x

- website/content/docs/connect/distributed-tracing.mdx
backport of commit 38c356c39bc60181dcdc56ec607e6dbc5ad7aa21
> Backport of docs: Fix ServiceDefaults example in distributed tracing into release/1.15.x

- website/content/docs/connect/intentions/jwt-authorization.mdx
> [Docs] Add note to jwt docs to specify the need for ACLs

- proto-public/pbmesh/v2beta1/common.pb.go
- proto-public/pbmesh/v2beta1/common.proto
- proto-public/pbmesh/v2beta1/grpc_route.pb.go
- proto-public/pbmesh/v2beta1/grpc_route.proto
- proto-public/pbmesh/v2beta1/http_route.pb.go
- proto-public/pbmesh/v2beta1/http_route.proto
- proto-public/pbmesh/v2beta1/tcp_route.pb.go
- proto-public/pbmesh/v2beta1/tcp_route.proto
General cleanup of some comments.
NET-5527
> mesh: update various protobuf comments for mesh types

- .changelog/18994.txt
> docs: add changelog

- agent/consul/server.go
- test-integ/go.mod
Manual backport of #19000 to 1.17-rc1 branch
> auth: register auth controllers with the server (1.17-rc1)

- agent/xds/delta.go
backport of https://github.com/hashicorp/consul/pull/19029
> remove log backport

- agent/xds/delta.go
> remove log

- agent/xds/listeners_apigateway.go
To match changes made in consul enterprise in this PR https://github.com/hashicorp/consul-enterprise/pull/7209
- No behavior should change with this PR, all tests should continue to passing as expected
* [ X ] appropriate backport labels added
* [ X ] not a security concern
> [NET-5788] Fix needed for JWTAuth in Consul Enterprise

- .changelog/19031.txt
- agent/structs/config_entry_discoverychain.go
- agent/structs/config_entry_discoverychain_test.go
- api/config_entry_discoverychain.go
- api/config_entry_discoverychain_test.go
> Manual backport of #19031 to release/1.17.0-rc1

- website/content/docs/connect/config-entries/service-defaults.mdx
Sorry for the white-space changes; my IDE hates trailing spaces apparently
> Minor update to ratelimit wording

- website/content/docs/release-notes/consul/v1_17_x.mdx
- website/data/docs-nav-data.json
> Add 1.17 release notes

- test/integration/consul-container/libs/cluster/encryption.go
- test/integration/consul-container/test/ratelimit/ratelimit_test.go
This add some retries when exec in the container (to wait for the container to be ready) and fix a check that was using `t` instead of `r` in a retry loop.
> fix flaking container tests

- website/content/docs/connect/manage-traffic/index.mdx
Fix broken link on 'manage traffic' overview
> fix broken link

- .github/workflows/nightly-test-1.17.x.yaml
night-test for 1.17.x release branch
> nightly test workflow for 1.17.x

- sdk/testutil/server.go
This helper should work regardless of catalog version for use in things like `consul-k8s`.
Temporarily ensured this worked by modifying a KV test, both with and without the v2 catalog experiment and the test passed:
```
diff --git a/api/kv_test.go b/api/kv_test.go
index 1395446a3e..73560184bf 100644
--- a/api/kv_test.go
+++ b/api/kv_test.go
@@ -10,17 +10,21 @@
"testing"
"time"
+       "github.com/hashicorp/consul/sdk/testutil"
"github.com/stretchr/testify/require"
)
func TestAPI_ClientPutGetDelete(t *testing.T) {
t.Parallel()
-       c, s := makeClient(t)
+       c, s := makeClientWithConfig(t, nil, func(c *testutil.TestServerConfig) {
+               c.Experiments = []string{"resource-apis"}
+       })
defer s.Stop()
kv := c.KV()
-       s.WaitForSerfCheck(t)
+       s.WaitForLeader(t) …
```
> sdk: update testutil.WaitForLeader to not use the v1 catalog api

- .changelog/19095.txt
- agent/connect/ca/provider_vault.go
- agent/connect/ca/provider_vault_test.go
- agent/connect/ca/testing.go
This PR manually merges changes to release/1.15.x because of the divergence of that branch from main where the changes were introduced.
> release/1.15.x: Manual backport of #19095

- internal/mesh/internal/controllers/sidecarproxy/controller_test.go
> mesh: fix race in the sidecar-proxy controller test

- agent/grpc-external/services/resource/testing/testing.go
- internal/tenancy/internal/types/namespace.go
- internal/tenancy/internal/types/namespace_test.go
This PR add tests to verify that namespace Create Delete and Read work properly.
This is 100% test code
> Add namespace read write tests

- agent/xds/listeners_apigateway.go
- agent/xds/testdata/routes/api-gateway-with-multiple-hostnames.latest.golden
Backporting CE changes for multiple virtual hosts from ENT
> [NET-5810] CE changes for multiple virtual hosts

- agent/xds/endpoints.go
`overprovisioningFactor` should be overridden with the expected value (100,000) when there are multiple endpoint groups. Update code and tests to enforce this.
This is an Enterprise feature. This commit represents the CE portions of the change; tests are added in the corresponding `consul-enterprise` change.
This will need to be manually backported to `release/1.17.0` to be included for GA.
> [NET-6221] Ensure LB policy set for locality-aware routing (CE)

- .github/workflows/verify-envoy-version.yml
Enable Verify Envoy Version Check in CI
See [PR](https://github.com/hashicorp/consul/pull/19299/files) to disable check
> enable verify envoy script

- .github/scripts/verify_envoy_version.sh
- .github/workflows/verify-envoy-version.yml
Use environment variables in Github Settings so script never needs to be updated to turn it off
> skip envoy version check in ci

- .github/workflows/verify-envoy-version.yml
Left the branch name used for testing in this [PR](https://github.com/hashicorp/consul/pull/19315/files). Remove branch name.
> remove branch name causing conflicts

- website/content/docs/security/acl/acl-roles.mdx
- website/content/docs/security/acl/tokens/create/create-a-service-token.mdx
- website/content/docs/security/acl/tokens/index.mdx
- Updating docs and tutorials to include more templated policies stuff
> More templated policies docs

- .changelog/19285.txt
- agent/connect/ca/provider_vault.go
- agent/connect/ca/provider_vault_test.go
* Re-add retry logic to Vault token renewal
* Fix goroutine leak
* Add test for detecting goroutine leak
* Add changelog
* Rename tests
* Add comment
> [1.16.x] Vault CA bugfixes (#19285)

- agent/xdsv2/testdata/clusters/destination/l4-multi-destination.golden
- agent/xdsv2/testdata/clusters/destination/mixed-multi-destination.golden
- agent/xdsv2/testdata/endpoints/destination/l4-multi-destination.golden
- agent/xdsv2/testdata/endpoints/destination/mixed-multi-destination.golden
- agent/xdsv2/testdata/listeners/destination/l4-multi-destination.golden
- agent/xdsv2/testdata/listeners/destination/mixed-multi-destination.golden
- agent/xdsv2/testdata/routes/destination/mixed-multi-destination.golden
- internal/mesh/internal/controllers/sidecarproxy/builder/destinations_test.go
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multi-destination.golden
- internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
- internal/mesh/internal/controllers/xds/testdata/destination/l4-multi-destination.golden
- internal/mesh/internal/controllers/xds/testdata/destination/mixed-multi-destination.golden
> add http2 to GRPC tests

- website/content/docs/k8s/multiport/configure.mdx
> Update multi-port examples to remove spec.template.metadata.name

- command/resource/delete/delete.go
- command/resource/delete/delete_test.go
- command/resource/helper.go
- command/resource/read/read_test.go
Manually backport a merged PR: https://github.com/hashicorp/consul/pull/19058
> backport a merged PR: gvk partial inference (#19058)

- .changelog/18994.txt
> update v2 changelog

- .changelog/18994.txt
Manual backport of https://github.com/hashicorp/consul/pull/19446
> update changelog 1.17.0

- website/content/docs/k8s/helm.mdx
[Generating helm docs](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#generating-helm-reference-docs) for consul-k8s 1.2.3 after recent release
> changelog for consul-k8s 1.2.3

- website/content/docs/k8s/helm.mdx
[Generating helm docs](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#generating-helm-reference-docs for consul-k8s 1.1.7 after recent release
> helm docs for Consul k8s release 1.1.7

- CHANGELOG.md
- api/go.mod
- envoyextensions/go.mod
- go.mod
- test-integ/go.mod
- test-integ/go.sum
- test/integration/consul-container/go.mod
- testing/deployer/go.mod
- troubleshoot/go.mod
- troubleshoot/go.sum
backport to `main` of https://github.com/hashicorp/consul/pull/19445
`release/1.17.x` PR TBD
> build: dependency updates for 1.17.0

- website/redirects.js
Typos in API gateway redirects
> fixed typos in redirect for api gateways

- internal/catalog/internal/controllers/workloadhealth/controller_test.go
- internal/resource/resourcetest/tenancy.go
- Modified existing controller's tests to include tenancies.
> Added tenancy tests for WorkloadHealth controller

- test-integ/README.md
Initial developer facing docs on how to write deployer (topology) integration tests.
NET-5736
> docs: spike of info about how to use deployer topology tests

- test-integ/connect/snapshot_test.go
Reduce duplicate code by re-using `topoutil.Asserter` and its methods.
> Integ test - use asserter

- agent/consul/server.go
- agent/consul/testdata/v2-resource-dependencies.md
- internal/multicluster/exports.go
- internal/multicluster/internal/controllers/exportedservices/controller.go
- internal/multicluster/internal/controllers/exportedservices/controller_test.go
- internal/multicluster/internal/controllers/register.go
- internal/resource/decode.go
> added exported svc controller

- .github/workflows/go-tests.yml
- .github/workflows/reusable-lint.yml
CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7771
NET-6557
> unhack: remove consulprem build tag

- internal/catalog/internal/controllers/endpoints/controller_test.go
- internal/catalog/internal/controllers/endpoints/reconciliation_data.go
- internal/catalog/internal/controllers/endpoints/reconciliation_data_test.go
Added tenancy tests for endpoints controller
> Added tenancy tests for endpoints controller

- website/content/docs/connect/gateways/api-gateway/configuration/routetimeoutfilter.mdx
There was a mutation in how this value is parsed at some point between when I developed it and when it was released. The code isn't broken, but the docs are incorrect and will cause the user to receive an error if they follow the format listed here.
> Timeout Docs Update

- .github/workflows/nightly-test-integrations.yml
- .github/workflows/test-integrations.yml
- test-integ/README.md
- test-integ/connect/snapshot_test.go
- test-integ/peering_commontopo/ac6_failovers_test.go
- test-integ/upgrade/basic/common.go
- test-integ/upgrade/basic/upgrade_basic_test.go
- test/integration/consul-container/libs/utils/version.go
- testing/deployer/go.mod
- testing/deployer/go.sum
- testing/deployer/sprawl/boot.go
- testing/deployer/sprawl/internal/tfgen/agent.go
- testing/deployer/sprawl/sprawl.go
- testing/deployer/topology/topology.go
> Integ test (test/deployer): upgrade test with service mesh

- .github/workflows/nightly-test-integrations-1.17.x.yml
- .github/workflows/nightly-test-integrations.yml
Enable nightly upgrade test with test/deployer for 1.17.x branch
> Integ test: enable upgrade test deployer 1.17

- internal/auth/internal/controllers/trafficpermissions/controller_test.go
Made tests in traffic permissions controller tenancy aware
> Add tests for traffic permissions controller

- .github/workflows/nightly-test-integrations.yml
- test-integ/upgrade/basic/common.go
> integ-test: fix upgrade test for CE

- ui/packages/consul-ui/tests/acceptance/dc/acls/policies/as-many/add-existing.feature
[Tests are failing](https://github.com/hashicorp/consul-enterprise/actions/runs/6909027874/job/18800296412?pr=7833) on `consul-enterprise` with the test:  `Feature: dc / acls / policies / as many / add existing: Add existing policy > Scenario: Adding an existing policy as a child of token: Scenario: Adding an existing policy as a child of token with the empty namespace set`
We will address fix with the ticket: https://hashicorp.atlassian.net/browse/CC-6958
> fix: temporary remove token policy test

- website/content/docs/ecs/reference/compatibility.mdx
Update ECS compat matrix to reflect the recent releases made to ECS and Consul
> Update ECS compat matrix

- .github/workflows/nightly-test-integrations-1.15.x.yml
- .github/workflows/nightly-test-integrations-1.16.x.yml
- .github/workflows/nightly-test-integrations-1.17.x.yml
- .github/workflows/nightly-test-integrations.yml
- .github/workflows/test-integrations-windows.yml
- .github/workflows/test-integrations.yml
related to https://github.com/hashicorp/consul/pull/19667
[Kapture 2023-11-20 at 09.10.43.webm](https://github.com/hashicorp/consul/assets/30640057/1e39511e-df1d-4044-ac3d-aa28f25df266)
> Switch to github-actions format for integration tests

- internal/multicluster/internal/controllers/exportedservices/controller.go
- internal/multicluster/internal/controllers/exportedservices/controller_test.go
- internal/multicluster/internal/types/decoded.go
Optimize fetching services in exported services controller
> optimized fetching services in exported service controller

- ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
- ui/packages/consul-ui/app/components/hashicorp-consul/index.js
see details here: https://github.com/hashicorp/consul/pull/18559
> chore: add suffix to consul version in sidenav

- internal/mesh/internal/controllers/routes/controller_test.go
- internal/mesh/internal/controllers/routes/generate_test.go
- internal/mesh/internal/controllers/routes/ref_validation_test.go
- Add tenancy tests for routes controller
> Add tenancy tests for routes controller

- command/resource/read/read_test.go
Fixes https://hashicorp.slack.com/archives/C9KPKPKRN/p1700669963373219
> Fix failing test in command/resource/read

- website/content/docs/security/acl/acl-rules.mdx
> Add docs for identity acl rules

- agent/grpc-external/services/resource/delete.go
- agent/grpc-external/services/resource/delete_test.go
- agent/grpc-external/services/resource/list_by_owner.go
- agent/grpc-external/services/resource/list_by_owner_test.go
- internal/resource/reaper/controller.go
- internal/tenancy/internal/bridge/tenancy_bridge.go
- internal/tenancy/internal/types/namespace.go
CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7891
NET-6684
> resource: ListByOwner returns empty list on non-existent tenancy

- LICENSE
Per legal team request, this makes the LICENSE file ASCII compliant and updates product version/language.
> license file updates

- LICENSE
Manual backport of https://github.com/hashicorp/consul/pull/19750
> LICENSE: manual backport of #19750

- test/integration/consul-container/test/upgrade/catalog/catalog_test.go
skipped TestCatalogUpgrade for all consul versions < 1.18.0
> skip TestCatalogUpgrade for consul versions < 1.18.0

- test-integ/catalogv2/explicit_destinations_l7_test.go
Updated TestSplitterFeaturesL7ExplicitDestinations to enable testing for connectivity between client and server services present in different combinations of tenancies
> update l7expplicit dest test to test cross tenancy

- CHANGELOG.md
Add changelogs for:
* 1.16.3
* 1.15.7
* 1.14.11
> chore: update changelog for patch releases

- website/content/docs/connect/proxies/envoy.mdx
- website/content/docs/k8s/annotations-and-labels.mdx
Add documentation for the `consul.hashicorp.com/proxy-config-map` annotation and the `xds_fetch_timeout_ms` proxy config option.
> Add documentation for proxy-config-map and xds_fetch_timeout_ms.

- agent/http.go
- website/content/api-docs/api-structure.mdx
- website/content/docs/upgrading/upgrade-specific.mdx
- Comment is misleading so removing it
> Remove warning for consul 1.17 deprecation

- ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
The test will be get back with CC-7062 ticket
> fix: remove test to unblock CI

- .changelog/19912.txt
- ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
…… (#19912)
Backport of #19912
> Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.15.x

- .changelog/19912.txt
- ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
> Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.17.x

- .changelog/19912.txt
- ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
> Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.16.x

- testing/deployer/sprawl/acl.go
- testing/deployer/sprawl/boot.go
- testing/deployer/sprawl/internal/tfgen/agent.go
- testing/deployer/sprawl/network_area_ce.go
- testing/deployer/topology/compile.go
- testing/deployer/topology/topology.go
> Upgrade test(LTS): use network area to federate cluster

- website/content/docs/k8s/installation/install-cli.mdx
Forgot close code segment on `consul-k8s` CLI docs.
> docs: typo formatting consul-k8s docs

- website/content/docs/enterprise/index.mdx
Update network segments docs based on additional testing on K8s and VMs.
> docs: Update network segments in compat matrix for Enterprise features

- website/content/docs/k8s/helm.mdx
> Update Helm Documenation with changes from release 1.1.8

- website/content/docs/k8s/helm.mdx
Updates the Helm chart docs with changes from the 1.2.4 release.
> Update Helm Documenation with changes from release 1.2.4

- .changelog/20014.txt
- Dockerfile
Dockerfile: backport of #20014 for 1.17.x
---
<details>
- 54c38e55e03460f7f105b7feb4526554e870625b  - 7a446d30e803b871631d027c73c908c4de8b501e  - 0f79688848b29854b8e36e3b5df09520ea39035c  - ac3cfc3ed3e3160e49d69fca5c6af81fee23b91a  - 15c3227d8b177192d5fa59e35fdb37e167f8ca6e  - 80ce9c0f50d8d39182622f2a600dc60b09e0369d 
</details>
> Dockerfile: backport of #20014 for 1.17.x

- .changelog/20014.txt
- Dockerfile
Dockerfile: backport of #20014
---
<details>
- 54c38e55e03460f7f105b7feb4526554e870625b  - 7a446d30e803b871631d027c73c908c4de8b501e  - 0f79688848b29854b8e36e3b5df09520ea39035c  - ac3cfc3ed3e3160e49d69fca5c6af81fee23b91a  - 15c3227d8b177192d5fa59e35fdb37e167f8ca6e  - 80ce9c0f50d8d39182622f2a600dc60b09e0369d 
</details>
> Dockerfile: backport of #20014 for 1.15.x

- command/connect/envoy/bootstrap_config.go
- command/connect/envoy/bootstrap_config_test.go
- test/integration/connect/envoy/main_test.go
fixing formatting issues introduced in this pr: https://github.com/hashicorp/consul/pull/20010
> fix formatting issue in envoy bootstrapping.

- .github/workflows/nightly-test-integrations.yml
- .github/workflows/test-integrations.yml
- Makefile
These are envoy versions that should be set to main when updating supported envoy versions.  It should have come in this PR: https://github.com/hashicorp/consul/pull/19879
> update makefile, compatibility tests, and nightlies to use latest envoy.

- .changelog/19940.txt
- .changelog/20010.txt
- .changelog/20011.txt
- .changelog/20012.txt
- .changelog/20013.txt
The various PRs had inconsistent changelog entries.
> Clean up and make the changelog entries consistent for the replacement of Envoy deprecated fields.

- website/content/docs/api-gateway/configuration/gateway.mdx
Manual backport of https://github.com/hashicorp/consul/pull/20113
> Update gateway.mdx (#20113) - backport 1.16.x

- test-integ/topoutil/asserter.go
- test/integration/consul-container/libs/assert/envoy.go
Import missing changes from ent
> integ test: import missing changes from ent

- .github/scripts/set_test_package_matrix.sh
> always run agent tests alone on their own runner

- test-integ/go.mod
- test-integ/topoutil/asserter.go
- test-integ/topoutil/http_consul.go
- test-integ/upgrade/l7_traffic_management/common.go
- testing/deployer/sprawl/sprawl.go
- testing/deployer/topology/topology.go
> upgrade test (LTS): utility functions to support ent users

- test-integ/upgrade/basic/upgrade_basic_test.go
- test-integ/upgrade/l7_traffic_management/resolver_test.go
- testing/deployer/sprawl/sprawl.go
> upgrade test: call validation func during upgrade

- internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
This isn't needed since we just populate RequiredEndpoints, which is already done for the base case
> [NET-6431] Remove explicit endpoints function from PST builder

- internal/catalog/catalogtest/test_integration_v2beta1.go
Fixing integ test flake
With this change the compatibility-integration-test CI job should run more reliably and hopefully quicker.
> Deflake the catalog v2beta1 integration tests

- go.mod
Changes to the troubleshoot module were backported to 1.15 and 1.16 but not 1.17, this wasn't caught before releasing the new version of the troubleshoot module but has been rectified with v0.5.2 of the troubleshoot package. This PR updates 1.17 to the newest version that fixes the previous issues
> Update troubleshoot module in main go.mod for new version

- test-integ/topoutil/asserter.go
- test-integ/upgrade/l7_traffic_management/common.go
- testing/deployer/sprawl/consul.go
> upgrade test: run validation func at every node during upgrade

- .github/workflows/broken-link-check.yml
Check for broken links in docs once a month
> GHA: Update broken-link-check.yml to check once a month

- internal/controller/cache/index/convenience.go
Fixing a panic I encountered during development
> Fix panic on error

- .github/scripts/verify_envoy_version.sh
Follow-up fix for https://github.com/hashicorp/consul/pull/20384
> Fix CICD script that checks envoy versions.

- ui/packages/consul-ui/tests/integration/components/link-to-hcp-banner-test.js
Whoopsie! In https://github.com/hashicorp/consul/pull/20344, we accidentally broke the tests, by switching to a different env service stub!
This fixes those tests
Tests are 💚 
- [Failing test](https://pipelinesghubeus2.actions.githubusercontent.com/UDbxBJypzDlMC30YpWP9tCXovvipW6bmy9DJcJWSzjoR6Hfgah/_apis/pipelines/1/runs/282495/signedlogcontent/55?urlExpires=2024-01-29T18%3A23%3A45.0070494Z&urlSigningMethod=HMACV1&urlSignature=D44qfxT1zcwZD7HOy%2F0N0Wxn9tXwd61uqJXFW5I74dg%3D)
> Fixing UI tests

- internal/multicluster/internal/controllers/v1compat/controller.go
- Typo fix: tests will come in follow up PR
> [NET-7074] Exported Services typo fix

- agent/consul/testdata/v2-resource-dependencies.md
- internal/auth/internal/controllers/trafficpermissions/controller.go
- internal/auth/internal/controllers/trafficpermissions/controller_test.go
- internal/auth/internal/types/partition_traffic_permissions.go
- internal/auth/internal/types/partition_traffic_permissions_test.go
- internal/auth/internal/types/types.go
- follow up to https://github.com/hashicorp/consul/pull/20407/files
> [NET-6231] Handle Partition traffic permissions when reconciling traffic permissions

- docs/v2-architecture/controller-architecture/guide.md
- docs/v2-architecture/controller-architecture/testing.md
Add developer docs regarding controller testing.
N/A - just updating developer docs
> Controller testing docs

- sdk/iptables/iptables.go
- sdk/iptables/iptables_test.go
Backport of https://github.com/hashicorp/consul/pull/20451
> Fix SDK iptables.Config marshalling

- .changelog/20406.txt
- agent/xds/delta_envoy_extender_ce_test.go
- agent/xds/testdata/builtin_extension/clusters/tproxy-and-permissive-mtls-and-envoy-extension.latest.golden
- agent/xds/testdata/builtin_extension/endpoints/tproxy-and-permissive-mtls-and-envoy-extension.latest.golden
- agent/xds/testdata/builtin_extension/listeners/tproxy-and-permissive-mtls-and-envoy-extension.latest.golden
- agent/xds/testdata/builtin_extension/routes/tproxy-and-permissive-mtls-and-envoy-extension.latest.golden
- envoyextensions/extensioncommon/basic_envoy_extender.go
- website/content/docs/k8s/connect/onboarding-tproxy-mode.mdx
(cherry picked from commit b6f10bc58f04cd8ebcf264bc69a30225155554fd)
<details>
- b6f10bc58f04cd8ebcf264bc69a30225155554fd
</details>
> [1.17.x] Skip filter chain created by permissive mtls

- internal/hcp/internal/controllers/telemetrystate/controller.go
- internal/hcp/internal/controllers/telemetrystate/controller_test.go
Backport of #20435 to release branch
> Backport/cdp hcp telemetry/1.18.0 rc1

- internal/mesh/internal/controllers/gatewayproxy/controller.go
- internal/mesh/internal/controllers/register.go
- fixes typo in gateway proxy controller
- re-enables apigw v2 controller
-
> Fix Gatewayproxy Controller and Re-Enable APIGW v2 Controller

- test/integration/consul-container/test/resource/grpc_forwarding_test.go
We continue to add more integration tests for resource management in CLI. Specifically, we add TLS integration test in this ticket.
> add more integration tests

- internal/mesh/internal/controllers/gatewayproxy/builder/builder_test.go
- internal/mesh/internal/controllers/gatewayproxy/controller.go
- internal/mesh/internal/controllers/gatewayproxy/controller_test.go
- internal/resource/resourcetest/tenancy.go
- adds some basic tests for gateway proxy controller, we should still add some more when we do further apigw work
> Add tests for gw proxy controller

- website/content/commands/snapshot/agent.mdx
> fix typos in docs for `consul snapshot agent`

- internal/mesh/internal/controllers/gatewayproxy/controller_test.go
use the correct tenancy info for persisting the mesh gateway workload for gatewayproxy test
> Fixes gatewayproxy controller tests for ent

- .changelog/20474.txt
- ui/packages/consul-ui/app/components/hcp-nav-item/index.js
- ui/packages/consul-ui/app/components/link-to-hcp-banner/index.js
- ui/packages/consul-ui/app/components/link-to-hcp-modal/index.hbs
- ui/packages/consul-ui/app/components/link-to-hcp-modal/index.js
- ui/packages/consul-ui/app/components/link-to-hcp-modal/index.scss
- ui/packages/consul-ui/app/controllers/application.js
- ui/packages/consul-ui/app/helpers/hcp-authentication-link.js
- ui/packages/consul-ui/app/services/hcp-link-modal.js
- ui/packages/consul-ui/app/styles/components.scss
- ui/packages/consul-ui/app/templates/application.hbs
- ui/packages/consul-ui/app/templates/dc/services/index.hbs
- ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
- ui/packages/consul-ui/tests/integration/components/link-to-hcp-modal-test.js
- ui/packages/consul-ui/tests/integration/helpers/hcp-authentication-link-test.js
manual backport for https://github.com/hashicorp/consul/pull/20568
> Backport/cc 7147 link to hcp modal/kindly verified snipe manually

- agent/consul/controller/controller.go
- agent/consul/controller/queue/defer.go
- agent/consul/controller/queue/queue.go
- agent/consul/controller/queue_test.go
- agent/consul/controller/reconciler_test.go
- internal/controller/controller.go
- internal/controller/controller_test.go
- internal/controller/runner.go
https://hashicorp.atlassian.net/browse/NET-6520
CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/8536
> resource: reconcile managed types every ~8hrs

- internal/auth/internal/types/computed_traffic_permissions.go
- internal/auth/internal/types/computed_traffic_permissions_test.go
- internal/auth/internal/types/workload_identity_test.go
Computed resources should not be written by users. For debugging purposes, we can fallback on the read to operator:read
> Update ComputedTrafficPermissions ACL hooks

- ui/packages/consul-ui/app/components/link-to-hcp-modal/index.hbs
- ui/packages/consul-ui/app/components/link-to-hcp-modal/index.scss
- ui/packages/consul-ui/tests/integration/components/link-to-hcp-modal-test.js
backport for https://github.com/hashicorp/consul/pull/20600
> Backport/link to hcp modal error when acls disabled/severely cool sparrow manual

- CHANGELOG.md
add missing changelog for 1.15.10
> add missing changelog for 1.15.10

- CHANGELOG.md
> update releasing changelog

- CHANGELOG.md
In this PR we update the sequence of changelog entries in the main branch.
> update entry sequence

- proto-public/pbauth/v2beta1/traffic_permissions.pb.go
- proto-public/pbauth/v2beta1/traffic_permissions.proto
- website/content/docs/k8s/multiport/reference/trafficpermissions.mdx
> Add enterprise docs for deny action

- website/content/docs/k8s/helm.mdx
> Update helm docs for consul-k8s 1.1.10 release

- website/content/docs/k8s/helm.mdx
> Update helm docs for consul-k8s 1.2.6 release

- website/content/docs/k8s/helm.mdx
> Update helm docs for consul-k8s 1.3.3 release

- CHANGELOG.md
> Update main changelog for 1.18.0

- website/content/docs/release-notes/consul/v1_18_x.mdx
Changing v2 changes to only end user facing changes within the release notes.
> docs: Update release notes for 1.18.x

- website/content/docs/architecture/v2/catalog.mdx
- website/content/docs/architecture/v2/groups.mdx
- website/content/docs/architecture/v2/index.mdx
- website/content/docs/k8s/multiport/configure.mdx
- website/content/docs/k8s/multiport/index.mdx
- website/content/docs/k8s/multiport/traffic-split.mdx
- website/content/docs/release-notes/consul/v1_18_x.mdx
- Add beta note to v2 API update
- Reformat release notes
- Add in downgrade capability from Consul Enterprise to Consul Community Edition
- Additional Beta banners
> docs: Update v2 Catalog API note to re-iterate beta and add downgrade from enterprise note 

- api/go.mod
> Retract api@v1.28.0

- ui/packages/consul-ui/app/components/hcp-nav-item/index.js
- ui/packages/consul-ui/app/services/hcp-link-status.js
- ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
- ui/packages/consul-ui/tests/integration/components/hcp-nav-item-test.js
Let's disable links to CCM on the 1.18.X branch as well:
https://github.com/hashicorp/consul/pull/20730
https://github.com/hashicorp/consul/pull/20732
> Hardcode links to CCM to be false - due to CCM deprecation

- website/content/docs/connect/gateways/api-gateway/configuration/routetimeoutfilter.mdx
[Page containing typos](https://developer.hashicorp.com/consul/docs/connect/gateways/api-gateway/configuration/routeretryfilter)
> Fix typos in route retry filter docs for APIGW

- website/content/docs/release-notes/consul-k8s/v1_2_x.mdx
- website/content/docs/release-notes/consul-k8s/v1_3_x.mdx
> docs: manual backport of relnotes

- website/content/docs/lambda/registration/automate.mdx
fixes lambda registrator module doc link to point to 0.1.0-beta5
> fix lambda registrator module doc link

- website/content/docs/k8s/helm.mdx
Follow-up to https://github.com/hashicorp/consul/pull/20770, syncing changes from https://github.com/hashicorp/consul-k8s/pull/3714.
> docs: update 1.4.0 Helm docs with Docs team feedback

- website/content/docs/k8s/installation/install.mdx
Correcting indentation of CNI Plugin stanza and a few more modifications to correctly pass Autopilot Warden checks.
> docs: Update GKE Autopliot docs

- website/content/docs/connect/gateways/api-gateway/install-k8s.mdx
- website/content/docs/k8s/installation/install.mdx
Fix API Gateway install for GKE Autopilot
> docs: K8s docs cleanup

- website/content/docs/agent/config/config-files.mdx
- website/content/docs/connect/security.mdx
Adds missing documentation for default_intention_policy
> Add docs for default_intention_policy

- ui/packages/consul-ui/blueprints/route-test/index.js
- ui/packages/consul-ui/lib/commands/bin/list.js
Fix lint error causing frontend tests to fail on 1.15
> Fix UI lint error

- website/content/docs/connect/config-entries/sameness-group.mdx
> fix broken link on sameness groups page

- CHANGELOG.md
> update changelog for 1.18.1

- Dockerfile
Follow up to https://github.com/hashicorp/consul/pull/20897/files forgot to bump alpine in one other place.
> Update Dockerfile: Base image for dev bump

- Dockerfile
Manual backport of https://github.com/hashicorp/consul/pull/20919, replaces https://github.com/hashicorp/consul/pull/20920
> Update Dockerfile: alpine 3.19 for 1.15.x

- agent/grpc-external/services/resource/testing/builder.go
- internal/controller/controller.go
- website/content/docs/connect/config-entries/service-intentions.mdx
> chore: remove repetitive words

- website/content/docs/security/acl/tokens/create/create-a-dns-token.mdx
> docs: fix apply DNS ACL token via CLI

- website/content/commands/snapshot/decode.mdx
- website/data/commands-nav-data.json
Updating documentation for newly added `consul snapshot decode` command.
> Update snapshot CLI command addition of Decode subcommand from PR#20824

- website/content/docs/security/acl/index.mdx
Fix a typo in the docs
N/A
N/A
N/A
> docs: fix typo in security/acl

- .github/workflows/backport-assistant.yml
> Roll bpa version and cleanup

- website/content/docs/connect/proxies/envoy-extensions/index.mdx
Add fault injection to Envoy extensions list.
> docs: Add fault injection to Envoy extensions list

- .github/workflows/build.yml
> revert to previous working version

- .github/workflows/build.yml
> try with release engineering optional clean flag

- .github/workflows/build.yml
> Release use releng branch

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
Fixing the format of the PR Labeler config file since we bumped the action to V5.
> chore: fix PR Labeler config 

- website/content/docs/k8s/helm.mdx
Generate the helm docs from 1.3.5 release of consul-k8s
> Adds helm docs update from 1.3.5 consul k8s release

- website/content/docs/k8s/helm.mdx
Generate the helm docs from 1.2.8 release of consul-k8s
> Generate helm docs from 1.2.8 of consul-k8s release

- website/content/docs/k8s/helm.mdx
Generate the helm docs from 1.1.12 release of consul-k8s
> Add helm docs update from 1.1.12 consul k8s release

- api/go.mod
- envoyextensions/go.mod
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
- testing/deployer/go.mod
- troubleshoot/go.mod
- troubleshoot/go.sum
Update submodule version that were released.
CI continues to pass
> chore: update submodule versions on release/1.19.x

- website/content/docs/agent/wal-logstore/index.mdx
> Fix broken link in wal-logstore/index.mdx

- website/content/docs/release-notes/consul/v1_19_x.mdx
Manual backport of https://github.com/hashicorp/consul/pull/21279
> docs: Consul v1.19 Release Notes (#21279)

- CHANGELOG.md
Refreshing `main` and `release/1.19.x` with the new changelog.
> docs: update changelog.md for 1.19.0

- website/content/docs/k8s/compatibility.mdx
- website/content/docs/k8s/helm.mdx
Docs updates for the k8s 1.5.0 release.
> docs: k8s updates for the 1.5.0 release

- website/content/docs/release-notes/consul-k8s/v1_5_x.mdx
- website/content/docs/release-notes/consul/v1_19_x.mdx
Adding Argo Rollouts docs for discoverability.
> docs: Add argo rollouts to 1.19.x release notes

- CHANGELOG.md
Update `CHANGELOG.md` for this week's patch releases
> Add changelog entries for 1.15.13, 1.17.6, 1.18.3 and 1.19.1

- .github/workflows/backport-assistant.yml
Update to latest version to incorporate recent fixes.
> ci: Update backport-assistant to 0.4.4

- .changelog/21588.txt
- ui/packages/consul-ui/package.json
- ui/yarn.lock
Update D3 packages to resolve DoS issue
- CI Passes and UI deployment looks as expected
> ui: Upgrade d3 packages to update color dependency

- agent/xds/resources_test.go
Fixes a bug in how xds tests are run
> [NET-10733] fix generation of xds resources

- agent/xds/clusters.go
> fix where jwt clusters are generated

- agent/dns_service_lookup_test.go
This takes a similar approach as https://github.com/hashicorp/consul/pull/21608 and reduces 36 created test agents down to 12.  This reduces local runtime from 61 seconds to 20 secs.
> Fix TestDNS_ServiceLookup_AnswerLimits  so that it only creates test agents the minimal amount of time.

- .github/scripts/goldenfile_checker.sh
- .github/workflows/goldenfile-checker.yml
Updates goldenfile checker for running in the enterprise fork
> update goldenfile checker for running in ent repo

- agent/xds/proxystateconverter/endpoints.go
- agent/xds/proxystateconverter/listeners.go
- agent/xds/response/response.go
- agent/xds/testing.go
- api/api.go
Backport previously has failed: https://github.com/hashicorp/consul/pull/21251
> Manual backport of PR 21251 to 1.17.x

- agent/xds/response.go
- agent/xds/testing.go
- api/api.go
Backport previously has failed: https://github.com/hashicorp/consul/pull/21251
> Manual backport of PR 21251 to 1.15.x

- website/content/docs/connect/gateways/api-gateway/configuration/gatewaypolicy.mdx
- website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-k8s.mdx
Manual Backport of https://github.com/hashicorp/consul/pull/21625
---
<details>
- d899808cc2f2afded3872834ded8a04060d29278  - 8c55f41f9d0a66e2759fc6dcd739a37077c82aae 
</details>
> backport of commit d899808cc2f2afded3872834ded8a04060d29278

- CHANGELOG.md
> 1.19.x - add missing changelog for 1.19.1

- website/content/docs/k8s/helm.mdx
> [release/1.15.x] autogenerate helm docs

- website/content/docs/k8s/helm.mdx
> [release/1.17.x] autogenerate helm docs

- website/content/docs/k8s/helm.mdx
> [release/1.18.x] autogenerate helm docs

- .changelog/21710.txt
- ui/package.json
- ui/yarn.lock
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/1007
> [ui] Pin a newer version of Braces

- scan.hcl
> security: triage vendor alerts

- .changelog/21711.txt
- ui/packages/consul-ui/app/utils/get-environment.js
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/22
> [ui] Simple url sanitization for get-env and document.cookie

- .changelog/21717.txt
- ui/package.json
- ui/yarn.lock
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/606
> [ui] Markdown-it pinned

- ui/package.json
- ui/yarn.lock
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/608 https://github.com/hashicorp/consul-enterprise/security/code-scanning/610 https://github.com/hashicorp/consul-enterprise/security/code-scanning/615 https://github.com/hashicorp/consul-enterprise/security/code-scanning/609 https://github.com/hashicorp/consul-enterprise/security/code-scanning/924 https://github.com/hashicorp/consul-enterprise/security/code-scanning/745 and possibly others
> [ui] Regenerate yarn lockfile for 1.18 and lower versions

- .changelog/21715.txt
- ui/package.json
- ui/yarn.lock
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/603
> [ui] Codemirror resolution pinned in package.json

- .changelog/21735.txt
- ui/package.json
- ui/yarn.lock
Resolves https://github.com/hashicorp/consul-enterprise/security/code-scanning/1036 (https://github.com/advisories/GHSA-whgm-jr23-g3j9)
> [ui] Pin ansi-html to 0.0.8

- .release/security-scan.hcl
Suppress CVE-2024-8096 because it doesn't have a solution yet.
> Suppress CVE-2024-8096

- .release/security-scan.hcl
Suppression statement was under binary and not container
> Fix supression

- build-support/scripts/gen-changelog.sh
Fixed spacing of variable declarations, fixed shellcheck violations
> fix spacing of bash scripts

- .changelog/21750.txt
- CHANGELOG.md
- Dockerfile
Rebasing change to pull in last minute changes to the branch
> Rebase 1.20.0 rc

- CHANGELOG.md
> Fix changelog for 1.20-rc1

- .github/workflows/test-integrations.yml
> ci: ensure int test docker pull goes through proxy

- website/content/docs/k8s/compatibility.mdx
> Update compatibility matrix to include 1.20.x

- api/go.mod
Ensure future tags include this retraction.
> chore: retain retracted api submodule version

- .github/scripts/verify_artifact.sh
> fix verify_artifact call to verify_rpm

- .github/scripts/verify_artifact.sh
> pass docker version in verify_artifact for verify_rpm

- website/content/docs/dynamic-app-config/sessions/index.mdx
Fix broken link of `Chubby lock service`.
> docs: fix broken link

- envoyextensions/xdscommon/ENVOY_VERSIONS
Update envoy versions to most recent available versions. 
- CI passes
https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history
> [Security] Bump envoy versions

- .release/security-scan.hcl
- Dockerfile
- New alpine version that has some security issues resolved. 
- CI passes 
https://security.alpinelinux.org/branch/3.21-main
> Bump alpine image

- .changelog/22011.txt
- Dockerfile
- Number of vulnerabilities being reported in the redhat UBI image that are resolved in the 9.5 release
- CI passes
[current image vulnerabilities 
](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?image=66eb4713df6256d9be473d28)
[new image vulnerabilities 
](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?image=67573ccbf9a39cfdc66dbd4c)
> Update UBI Image 

- envoyextensions/xdscommon/ENVOY_VERSIONS
Update envoy versions to most recent available versions.
CI passes
https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history
> sec: bump envoy patch versions

- envoyextensions/go.mod
- envoyextensions/go.sum
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
- troubleshoot/go.mod
Reverts hashicorp/consul#22032
> Revert "Update api submodule versions to v1.31.0 for envoyextensions"

- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
Updated the submodules api v1.31.0, envoyextensions v0.7.7 and troubleshoot v0.7.4
> Update the submodules for 1.20.x

- .changelog/22055.txt
- go.mod
> Update api to 1.21.4

- .changelog/22056.txt
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
> Update api to 1.28.5

- .changelog/22058.txt
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
> Update api to 1.29.6

- CHANGELOG.md
Updated the changelogs for the latest releases
> chore: Updated the changelogs for 1.20.2, 1.19.4, 1.18.6, 1.15.16

- CHANGELOG.md
Updated the changelog for 1.15.16
> chore: Update changelog 1.15.16

- CHANGELOG.md
> chore: Updated changelog for 1.18.6

- .changelog/22109.txt
- go.mod
- go.sum
Consume latest version of consul-awsauth containing the fix in https://github.com/hashicorp/consul-awsauth/pull/10
Testing was done as part of merging https://github.com/hashicorp/consul-awsauth/pull/10
> Consume latest version of consul-awsauth dependency

- CHANGELOG.md
> chore: Update changelog 1.18.7

- .changelog/22138.txt
- envoyextensions/xdscommon/ENVOY_VERSIONS
> chore: Update supported Envoy versions in ENVOY_VERSIONS file

- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
Updated the submodules as below
```
- api/v1.31.1
- envoyextensions/v0.7.8
- proto-public/v0.6.4
- sdk/0.16.2
- troubleshoot/v0.7.5
```
> Update all the submodules 

- .github/CODEOWNERS
- agent/consul/state/txn.go
- agent/consul/txn_endpoint.go
Fixes the CI failure due to lint-enums and updates the CODEOWNERS
```
Run go install github.com/reillywatson/enumcover/cmd/enumcover@master && enumcover ./...
go: downloading github.com/reillywatson/enumcover v0.0.0-2025020[7](https://github.com/hashicorp/consul/actions/runs/13308237451/job/37164125289?pr=22156#step:5:8)113834-d3fe218c4b80
go: downloading golang.org/x/tools v0.20.0
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
Error: /home/runner/work/consul/consul/agent/consul/state/txn.go:31:2: Malformed enumcover comment (should be of the form "enumcover:sometypename"): // enumcover: api.KVOp
Error: /home/runner/work/consul/consul/agent/consul/state/txn.go:140:2: Malformed enumcover comment (should be of the form "enumcover:sometypename"): // …
```
> Fix lint-enums errors and update codeowners

- .changelog/22174.txt
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
upgraded consul/api submodule to 1.31.2
> upgraded consul/api submodule to v1.31.2

- .changelog/22174.txt
- go.mod
- test-integ/go.mod
- test/integration/consul-container/go.mod
Backport of PR https://github.com/hashicorp/consul/pull/22174
> upgraded consul/api submodule to v1.31.2 (#22174)

- .changelog/22184.txt
- logging/logfile_darwinandfreebsd.go
- logging/logfile_openbsd.go
compilation error fix for NetBSD OS
> logging fix for netbsd os

- .github/scripts/filter_changed_files_go_test.sh
- .github/workflows/build-distros.yml
- CHANGELOG.md
Adding changelog for 1.18.10
Ignoreing workflow checks for only changelog commit as this branch is not maintained in CE
> Changelog 1.18.10+ent

- CHANGELOG.md
> changelog from ENT to CE sync

- .github/CODEOWNERS
- .github/workflows/reusable-conditional-skip.yml
changed CODEOWNERS and skipping CODEOWNERS in PR merge check
> changed CODEOWNERS and skipping CODEOWNERS in PR merge check

- .changelog/22220.txt
- agent/txn_endpoint.go
- agent/txn_endpoint_test.go
- api/txn.go
- api/txn_test.go
- go.mod
- go.sum
fix: update go-discover dependency to v0.0.1
> fix: update go-discover dependency to v0.0.1

- .release/versions.hcl
Update release versions in release/versions.hcl
- remove v1.15
- remove ce tag in v1.20
> update: remove 1.15 as LTS, remove1.20 as CE

- .github/workflows/reusable-conditional-skip.yml
- .release/security-scan.hcl
- CHANGELOG.md
- Dockerfile
Preparation for release v1.21.1
> Prep v2 release/1.21.1

- envoyextensions/xdscommon/ENVOY_VERSIONS
Updated the list with newer patch versions for supported Envoy releases while removing outdated entries. This ensures compatibility and aligns with the latest supported versions documented by Consul's Envoy proxy guidelines.
> Update supported Envoy versions in ENVOY_VERSIONS file

- .release/security-scan.hcl
revert CVE suppression, to be merged in point release branch
N/A
N/A
> revert suppression - to be added in point release

- ui/packages/consul-ui/app/helpers/node-identity-template.js
- ui/packages/consul-ui/app/helpers/service-identity-template.js
- ui/packages/consul-ui/tests/integration/helpers/node-identity-template-test.js
- ui/packages/consul-ui/tests/integration/helpers/service-identity-template-test.js
Adds missing license file headers
> ui: Add generated license headers

- ui/packages/consul-ui/app/components/consul/node/list/index.hbs
https://hashicorp.atlassian.net/browse/CSL-11289
Fixes IP address formatting in Node Lists view
> ui: Fix missing format for ip address in node list view

- CHANGELOG.md
- update: post release changelog
> update: post release changelog

- .changelog/22598.txt
- agent/checks/check_test.go
- agent/consul/authmethod/kubeauth/testing.go
- agent/hcp/testing.go
- agent/http_test.go
- agent/kvs_endpoint.go
- agent/kvs_endpoint_test.go
- agent/txn_endpoint.go
- api/api.go
- api/api_test.go
- api/content_type.go
- command/resource/client/client.go
- internal/go-sso/oidcauth/oidcauthtest/testing.go
Add explicit charset encoding to prevent attacker from interpreting the output in a different encoding than intended.
> add charset

- ui/packages/consul-ui/app/components/consul/token/list/index.hbs
Fixes token list page accessibility error
> ui: add empty dt element under the header

- .changelog/22598.txt
- agent/checks/check_test.go
- agent/consul/authmethod/kubeauth/testing.go
- agent/hcp/testing.go
- agent/http_test.go
- agent/kvs_endpoint.go
- agent/kvs_endpoint_test.go
- agent/txn_endpoint.go
- api/api.go
- api/api_test.go
- api/content_type.go
- command/resource/client/client.go
- internal/go-sso/oidcauth/oidcauthtest/testing.go
Backport of #22598 
* add charset
* fix tests
* fix tests
> Manual Backport of add charset (#22598)

- website/content/commands/debug.mdx
Updated documentation of debug command to include details about validation of ports connectivity.
> updated debug command doc

- .github/workflows/ce-merge-trigger.yml
Fixed the logic to check active version
> chore: fixed the release version checking logic

- .github/workflows/ce-merge-trigger.yml
> chore: fixed the release version checking logic and approvers logic

- .github/workflows/ce-merge-trigger.yml
passing PR number in the ce-merge trigger workflow to ENT
> fixed the ce-merge trigger worlfow to pass PR number

- .github/workflows/ce-merge-trigger.yml
corrected the command to invoke repository dispatch
> fixed the ce-merge trigger workflow to pass PR number

- .github/workflows/ce-merge-trigger.yml
fixed the REPO empty issue while invoking repo dispatch
> fixed the REPO empty issue while invoking repo dispatch

- .github/workflows/ce-merge-trigger.yml
fixed the payload variable in repository dispatch call
> fixed the payload variable

- ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
- ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/skin.scss
- ui/packages/consul-ui/app/modifiers/fix-power-select-with-create-aria.js
Power Select With Create component from Ember has several Accessibility issues. This PR fixes those issues.
Visit the Intentions -> Create Page.
Open the Source OR Destination Dropdown
Run the Axe Dev Tools in Chrome.
Accessibility issues show up.
> fix accessibility isues of powerselectwithcreate component

- ui/packages/consul-ui/app/components/peerings/badge/index.scss
- ui/packages/consul-ui/app/styles/app.scss
- ui/packages/consul-ui/app/styles/tailwind-like.scss
Changes for accessibility issues in peer page.
Adds missing tailwind css classes
> [UI] peer page accessibility

- .changelog/22735.txt
- envoyextensions/xdscommon/ENVOY_VERSIONS
- testing/deployer/topology/default_versions.go
Updated the latest envoy version supported
> Latest Envoy version update - default v1.34.7

- .changelog/22735.txt
- envoyextensions/xdscommon/ENVOY_VERSIONS
- testing/deployer/topology/default_versions.go
- Updated the latest envoy version supported
> Latest Envoy version update - default v1.34.7 (#22735)

- ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
- ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
- ui/packages/consul-ui/app/modifiers/fix-super-select-aria.js
Fix A11y Issues on Intentions page and other Minor A11y fixes on some other places.
> add column headers on intention page and other minor a11y fixes

- testing/deployer/topology/default_versions.go
- Updated the latest consul ENT version supported
> Consul ENT default version change

- .release/security-scan.hcl
- Dockerfile
CVE-2025-6395 is suppresssed for containers
> Suppress CVE-2025-6395

- website/content/docs/reference/k8s/helm.mdx
Deploy preview: https://consul-git-fork-nitin-sachdev-29-main-hashicorp.vercel.app/consul/docs/reference/k8s/helm
> Synced helm docs with consul-k8s

- CHANGELOG.md
> updating change log

- .release/security-scan.hcl
> removing fixed cve from security scan file

- website/content/docs/reference/k8s/annotation-label.mdx
> Fix indentation for K8s annotation labels documentation.

- ui/packages/consul-ui/.husky/pre-commit
- ui/packages/consul-ui/package.json
- ui/pnpm-lock.yaml
Upgrading development utility libraries husky and lint-staged
> ui: upgrade lint-staged and husky

- .github/workflows/nightly-test-1.20.x.yaml
- .github/workflows/nightly-test-1.21.x.yaml
Fixes breaking workflow of nightly tests
> ci: Run pnpm install before node setup

- agent/netutil/network.go
- api/api.go
- command/connect/envoy/envoy.go
- command/connect/envoy/envoy_test.go
> fixes the config merge from client config to dualstack check internal client initialization config
