hashicorp/consul

.changelog/14527.txt
ui/packages/consul-ui/translations/routes/en-us.yaml

We've decided to make some text and logic amends to the topology notices/banners. This PR addresses the text changes only, partly because the logic changes are likely to affect line styling (dotted vs non-dotted) and other things in the topology visualisation itself.
Unchanged Texts:
- No Dependencies
- Limited Access
Additional texts ready for usage with to come logic.
- No intentions
All other texts apart from the above have been changed, please let me know if the unchanged texts do need changing.

ui: Amends to existing topology notice/banner texts

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/server-tls.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/webhook-certs.mdx

- Bump Consul and Consul K8s versions
- Add explicit requirement for global.name to be unique across K8s clusters
- Add -f values.yaml to each helm template command in the Vault Secrets backend integration pages
Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to obfuscate …

docs: admin partition docs improvements

---

ui/packages/consul-ui/lib/startup/templates/body.html.js

Make sure to use the "sub-app"-approach of injecting the hcp/back-link properly so that it actually gets bundled in production environments.
This issue probably occurred because testing against a real backend is hard at the moment. We most likely want to create an easy-to-use setup in the near future that allows us to run the UI against a proper consul-agent.
* run `make ui-docker` and `make docker-dev` after that
* setup a `docker-compose`-file that starts an agent and pass the following flag: `CONSUL_HCP_ENABLED=true`, alternatively you can run proper HCP and boot consul inside of it.

ui: fix link back to hcp not showing up

---

website/content/docs/k8s/installation/install.mdx

When consul-k8s is released with 0.49.0, around Sept 29th, there will now be support for using the consul-cni plugin on OpenShift.
This change adds that information to the consul-k8s install doc.
Ran the container locally and validated the changes.
[CNI: Add support for OpenShift and Multus](https://github.com/hashicorp/consul-k8s/pull/1527)

Docs: Add OpenShift CNI to list of install options for kubernetes

---

agent/consul/peering_backend.go
agent/consul/peering_backend_test.go
agent/consul/servercert/manager.go
agent/grpc-external/services/peerstream/server.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/subscription_blocking.go
agent/grpc-external/services/peerstream/subscription_manager.go
agent/grpc-external/services/peerstream/subscription_manager_test.go
agent/rpc/peering/service.go
lib/retry/retry.go

Exposing servers through mesh gateways will involve sharing mesh gateway addresses with peers instead of true server addresses.
There are two flows where these addresses are shared:
* When generating a peering token.
* When pushing server address updates in the peering stream.
Each flow was addressed in a separate commit.
* Unit tests
* NET-644
* PR with config entry changes: #14475

Return mesh gateway addrs if peering through mgw

---

agent/proxycfg/mesh_gateway.go
agent/proxycfg/snapshot.go
agent/proxycfg/state_test.go
agent/proxycfg/testing_mesh_gateway.go
agent/structs/config_entry_mesh.go
agent/structs/config_entry_mesh_test.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/mesh-gateway-peering-control-plane.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-peering-control-plane.latest.golden
agent/xds/testdata/listeners/mesh-gateway-peering-control-plane.latest.golden
agent/xds/testdata/routes/mesh-gateway-peering-control-plane.latest.golden

Routing peering control plane traffic through mesh gateways can be
enabled or disabled at runtime with the mesh config entry.
This PR updates proxycfg  and xDS to add configuration for local servers
depending on this central config.
Best reviewed by commit.
* Unit tests
Will do more manual/integration testing when more of these pieces are in place.
* NET-643

Update mesh gateway Envoy config for INBOUND peering control-plane traffic

---

test/integration/connect/envoy/case-ingress-gateway-multiple-services/verify.bats
test/integration/connect/envoy/case-ingress-gateway-simple/config_entries.hcl
test/integration/connect/envoy/case-ingress-gateway-simple/verify.bats

Fix flaky test because when a service is configured in two listeners in an ingress-gateway config entry; it randomly pick the service config from one of the listeners.
This PR moves test for setting non-default connection threshold to `integration/connect/envoy/case-ingress-gateway-simple` to avoid the non-deterministic results.

fix flaky integration test

---

.github/workflows/changelog-checker.yml

I was recently working on some manual backports for 1.11 in #14828 and others and the `changelog-checker` workflow was failing despite having added a proper changelog entry. When I looked into it, it seems that there is some broken shell code in the action that is making it fail for the case where the base is not the default branch. In my case, the base branch was `release/1.11.x`.
Some history: it looks like back in #10844, there was a bit of a refactor/update to the checker logic that added this default branch case. I guess we just missed the bug in the code review.
In any case, this should fix it!
I tested this by pulling the body of the checker out into a shell script and manually running it with the arguments for my pull request. The contents of the script are here in case you want …

ci: Fix changelog-checker GHA workflow

---

.changelog/14830.txt
.circleci/config.yml
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
website/content/docs/connect/proxies/envoy.mdx

Self-explanatory. Bumps versions in the test matrix, test code and our docs.
We should see our integration tests pass with this new patch.

connect: Bump Envoy 1.20 to 1.20.7

---

website/content/docs/ecs/index.mdx

Fixes a broken link to Learn. (same as #14871, just renaming the branch)

[docs] Fix broken Learn link

---

website/content/docs/consul-vs-other/api-gateway-compare.mdx

- The doc currently reads as if "Consul API Gateway documentation is an implementation..." which doesn't make sense.
- We should be using consistent casing when referring to the Consul API Gateway product vs. any API gateway
:eyes:
[Existing doc](https://developer.hashicorp.com/consul/docs/consul-vs-other/api-gateway-compare)

Update CAPIGW comparison docs

---

ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs

Allow the `managed-runtime`-badge to display dynamic values. Before this change, we hard-coded the text to always display `Self-managed`. This change will make the badge dynamic by using the value that is set as the `HCPEnabledRuntime`-option as the text for the badge.
I did not add a test for this behavior, as it is nearly impossible to add a test for configuration options in only one test with the current setup of environment-variables.
* add `HCPManagedRuntime` to the `operatorConfig` in `/config/environment.js` and set its value to the text you want the badge to display. In production, this will be taken care of by the server, for development this is the easiest way to change this option.

ui: Allow managed-runtime badge to be dynamic

---

api/api.go
api/api_test.go

When using API to query a service imported by a peering, we need to set the `peer` in query option, which is missing in the current implementation. This PR fixes this issue.
```go
cli.Health().Service("foo", "", false, &api.QueryOptions{
Peer: "dc-abc",
})
```

fix(api): missing peer name in query option

---

ui/packages/consul-ui/app/components/app-view/index.hbs
ui/packages/consul-ui/app/components/app-view/index.scss
ui/packages/consul-ui/app/components/app-view/layout.scss
ui/packages/consul-ui/app/components/app-view/skin.scss
ui/packages/consul-ui/app/components/breadcrumbs/layout.scss
ui/packages/consul-ui/app/styles/routes/dc/services/index.scss
ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/services/instance.hbs

Moves labels/kinds/sources to the bottom row of the title, and allows wrapping of the title text. Actions (ip, create, edit, etc.) are in their own column on the right and bottom aligned to match with either the labels, if they are present, or the title. 
Makes it so the breadcrumb overflow is hidden with an ellipsis, and a tooltip is show with the value. I think we could rethink breadcrumbs/tooltips so that:
- you don't have to manually add the breadcrumbs for routes in the templates
- you don't have to manually add tooltips to specific breadcrumbs
However, I felt that I didn't need to add more scope to this ticket.
**Before:**
**After:**
ant to apply this everywhere. (thinking auth methods, etc.).
- [NET-964](https://hashicorp.atlassian.net/browse/NET-964)
- …

ui: Wrap service names on show and instance routes

---

.changelog/14751.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/testing_tproxy.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-with-resolver-redirect-upstream.latest.golden

Transparent proxy does not spawn outbound listeners for explicit upstreams to service-resolvers. When upstreams are explicitly defined, a corresponding listener should be spawned.
Create a service with the following fields configured:
```
consul.hashicorp.com/connect-inject: "true"
consul.hashicorp.com/connect-service-upstreams: "upstream:9001"
consul.hashicorp.com/transparent-proxy: "true"
```
Create a service resolver that will be used as the upstream.
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
name: upstream
spec:
redirect:
service: other-svc
```
Check the Envoy admin config dump and observe that no listeners are spawned.

Fix tproxy listeners with discovery chains.

---

.changelog/14817.txt
agent/proxycfg/mesh_gateway.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/testing.go
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_upstreams.go
agent/structs/testing_catalog.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/connect-proxy-with-chain-and-failover-to-cluster-peer.latest.golden
agent/xds/testdata/clusters/connect-proxy-with-chain-and-redirect-to-cluster-peer.latest.golden
agent/xds/testdata/clusters/ingress-with-chain-and-failover-to-cluster-peer.latest.golden
agent/xds/testdata/clusters/ingress-with-defaults-service-max-connections.latest.golden
agent/xds/testdata/clusters/ingress-with-overwrite-defaults-service-max-connections.latest.golden
agent/xds/testdata/clusters/ingress-with-service-max-connections.latest.golden
agent/xds/testdata/clusters/mesh-gateway-with-imported-peered-services.latest.golden
agent/xds/testdata/endpoints/connect-proxy-with-chain-and-failover-to-cluster-peer.latest.golden
agent/xds/testdata/endpoints/connect-proxy-with-chain-and-redirect-to-cluster-peer.latest.golden
agent/xds/testdata/endpoints/ingress-with-chain-and-failover-to-cluster-peer.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-with-imported-peered-services.latest.golden
agent/xds/testdata/listeners/listener-balance-inbound-connections.latest.golden
agent/xds/testdata/listeners/listener-balance-outbound-connections-bind-port.latest.golden
agent/xds/testdata/listeners/mesh-gateway-with-imported-peered-services.latest.golden
agent/xds/testdata/routes/mesh-gateway-with-imported-peered-services.latest.golden
test/integration/connect/envoy/case-cross-peers/primary/service_s1.hcl
test/integration/connect/envoy/case-cross-peers/primary/verify.bats

This PR creates Envoy clusters and envoys on mesh gateways that forward requests to a mesh gateway in another admin partition. These Envoy resources are used to enable mesh gateway local mode with cluster peering.
* Manually set up cluster peering and verified that this works
* Unit tests
* Integration tests

Make the mesh gateway changes to allow `local` mode for cluster peering data plane traffic

---

ui/packages/consul-lock-sessions/app/templates/dc/nodes/show/sessions.hbs
ui/packages/consul-nspaces/app/templates/dc/nspaces/index.hbs
ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs
ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/index.feature
ui/packages/consul-ui/tests/acceptance/dc/nodes/index.feature
ui/packages/consul-ui/tests/acceptance/dc/nodes/sessions/list.feature
ui/packages/consul-ui/tests/acceptance/dc/peers/index.feature
ui/packages/consul-ui/tests/acceptance/dc/services/index.feature
ui/packages/consul-ui/translations/routes/en-us.yaml

Update empty-states throughout the app to only include mentions of ACLs if the user has ACLs enabled.
> When ACLs are disabled, we need to conditionally not show the second part of the empty state messaging that references ACL permissions or the "log in with a different token" button. They should still display when ACLs are enabled.
I didn't update any empty states that were under the Access Controls nav section, since I think you need ACLs enabled to access those. Please feel free to correct me here.
- JIRA: [NET-761](https://hashicorp.atlassian.net/browse/NET-761)
- [Design](https://www.figma.com/file/nJfkXEJ1rZ8KviqVmUTV9X/Empty-states?node-id=4206%3A2726)

ui: Update empty-state copy throughout app

---

CHANGELOG.md
website/content/docs/connect/ca/vault.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Status: looking for
Follow on work:
- Add a separate PR to note this is needed when upgrading to 1.14 (if not already handled)

docs: vault ca provider patch upgrade guidance

---

website/content/docs/connect/dataplane/index.mdx

The URLs were pointing to the wrong paths.
* Manual testing: I opened the URLs https://www.consul.io/docs/connect/dataplane/consul-dataplane and https://www.consul.io/docs/k8s/helm
* [n/a] updated test coverage

Fixes broken URLs in Dataplane docs

---

.changelog/14903.txt
ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/mock-api/v1/health/service/_
ui/packages/consul-ui/tests/acceptance/dc/services/instances/show.feature

Removes the reference to node name in the service instance header if it has the `synthetic-node: true` meta. I've set the mock-api to set `synthetic-node: true` on all service instances that have kubernetes as an external source.
- [Design](https://www.figma.com/file/S20gHKN9SoKfkabNjWKVuE/Agentless?node-id=101%3A11447)
- [NET-949](https://hashicorp.atlassian.net/browse/NET-949)

ui: Remove node name from agentless service instance

---

website/content/docs/enterprise/license/faq.mdx

The software delivery support email address is no longer valid. This replaces it with a link to the official support website.
The email address `support-softwaredelivery@hashicorp.com` is no longer valid. This removes it.
* Visit https://www.consul.io/docs/enterprise/license/faq#q-how-can-i-renew-a-license
* It should link to the HashiCorp support website instead of the software delivery email address.
Relevant [FAQ page](https://www.consul.io/docs/enterprise/license/faq#q-how-can-i-renew-a-license).

Fix outdated support email address

---

.github/scripts/metrics_checker.sh

It's possible that the output of the diff contains surrounding lines that were not modified. This change filters further to lines that were added or removed.
I'm not great with grep, so if there's a nicer way to handle this let me know!
* Tested manually

Ensure lines were modified

---

.changelog/14869.txt
agent/configentry/merge_service_config.go
agent/configentry/merge_service_config_test.go
agent/consul/catalog_endpoint.go
agent/consul/health_endpoint.go
agent/consul/server.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
agent/grpc-external/services/dataplane/server.go
agent/service_manager.go

This fixes GetEnvoyBootstrapParams to merge in proxy-defaults and service-defaults.
* Steps to reproduce: [Gist link](https://gist.github.com/pglass/d768358a85390abf90b98c6b33c10d54)
* A script to test: Run `consul agent -dev` and then run [`check.sh` here](https://gist.github.com/pglass/e68ecbcadfaa8b08d4d2da7c65b3c436#file-check-sh) and you should see [this output](https://gist.github.com/pglass/e68ecbcadfaa8b08d4d2da7c65b3c436#file-output-txt)
* Added unit tests

Merge central config for GetEnvoyBootstrapParams

---

website/content/api-docs/catalog.mdx

Some APIs supporting simple agent caching misses description in the API doc. This PR fixes
* [List datacenters](https://github.com/hashicorp/consul/blob/58c8a10b98d125531f9ca3b677eeb95f816382b9/agent/catalog_endpoint.go#L191-L200)
* [List catalog services](https://github.com/hashicorp/consul/blob/58c8a10b98d125531f9ca3b677eeb95f816382b9/agent/catalog_endpoint.go#L268-L284)

docs: fix missing agent caching method

---

test/integration/consul-container/upgrade/healthcheck_test.go

In #13658 (1.13+), we accidentally introduced a backwards incompatibility in our subscription/streaming API. Specifically, we 
[removed a field from the `SubscribeRequest` ](https://github.com/hashicorp/consul/pull/13658/commits/c7f491d174bb18c469f9fce4ee8cfad31bd78de5#diff-b23e1b89cf62b2990d0dcfcb707064c0e50fb8d1ba3e8d996807f0d05630276bL28) that gets sent for health requests. This is fine when all clients and servers are on the same version, but in the rare case where clients are on newer versions than the servers, it means that the requests they generate won't be compatible with the servers they are talking to. 
Ideally, we would remediate this issue in 1.13 and restore the compatibility, but that doesn't help us right now for the 1.12 tests which are really flaky. What makes them so …

tests: Fix flaky upgrade/compatibility test

---

ui/packages/consul-ui/app/models/peer.js
ui/packages/consul-ui/app/services/repository/peer.js
ui/packages/consul-ui/mock-api/v1/peerings

Update to latest peer-API changes. This makes the `StreamStatus`-data available to the peer-model. I'm normalizing the data in the repository layer because the peering repository works around the serializer layer.
* build docker image from latest `main`
* start a consul cluster setup that you can create peerings in. you can use [docker-compose](https://github.com/LevelbossMike/consul-setup)
* use `yarn start:consul` to run against this cluster and see that the UI behaves as it did before.

ui: Update peer repository to latest API changes

---

ui/packages/consul-ui/app/abilities/peer.js

Make terminated peers deletable. The only reason this wasn't possible before was because we had an ability prohibiting deleting a peer with the `TERMINATED`-state. Now that the API supports this, we can remove that check.
This PR depends on https://github.com/hashicorp/consul/pull/14937
* same as https://github.com/hashicorp/consul/pull/14937
* go to the dialer side of a peering, delete it, and then look at the receiver side and see that the peering can be deleted.

ui: make terminated peers removable

---

.changelog/14897.txt
go.mod
go.sum

This PR bump raft version to v1.3.11 to include some recent raft fixes in Consul
- https://github.com/hashicorp/raft/pull/519
- https://github.com/hashicorp/raft/pull/526
- https://github.com/hashicorp/raft/pull/516
- https://github.com/hashicorp/raft/pull/494

bump raft version to v1.3.11

---

agent/grpc-external/services/peerstream/replication.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go

This commit adds a monotonically increasing nonce to include in peering replication response messages. Every ack/nack from the peer handling a response will include this nonce, allowing to correlate the ack/nack with a specific resource.
At the moment nothing is done with the nonce when it is received. In the future we may want to add functionality such as retries on NACKs, depending on the class of error.
* Various unit tests from both the request/response sides

Add basic nonce management

---

.changelog/14924.txt
agent/agent.go
agent/cache-types/service_checks.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/service_http_checks.go
agent/proxycfg-glue/service_http_checks_test.go
agent/proxycfg/connect_proxy.go
agent/service_checks_test.go

Adds another datasource for `proxycfg.HTTPChecks`, for use on server agents. Typically these checks are performed by local client agents and there is no equivalent of this in agentless (where servers configure consul-dataplane proxies).
Hence, the data source is mostly a no-op on servers but in the case where the service is present within the local state, it delegates to the cache data source.
Using the cache data source for configuring agentless proxies when the service is not in the server local state causes an increase in the http checks fetch error rate which in turn causes a spike in memory usage (eventually leading to server OOM kill). 
Although this issue was only the symptom and the current PR solves this symptom ; the root cause fix of the memory leak is being handled here: …

Service http checks data source for agentless proxies

---

.changelog/14933.txt
command/connect/redirecttraffic/redirect_traffic.go
command/connect/redirecttraffic/redirect_traffic_test.go
website/content/commands/connect/redirect-traffic.mdx

Add -node-name flag to redirect-traffic command to support running it in environments without client agents.

Add -node-name flag to redirect-traffic command

---

.changelog/14936.txt
agent/config/builder.go
agent/config/config.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/hcp/config/config.go

When adding the `cloud` configuration stanza in https://github.com/hashicorp/consul/pull/14723, we forget to add `scada_address`. This is required when targeting other scada scada servers than the hcp sdk default ones. 
This addition doesn't have documentation because the other cloud configuration don't have that either.
I tested this by building consul and using the configuration option.
translate.
`agent/config/testdata/full-config.*`, which should cause the test to fail.
Then update the expected value in `TestLoad_FullConfig` in
`agent/config/runtime_test.go` to make the test pass again.
the expected value for `TestRuntimeConfig_Sanitize`. Look at `git diff` to
make sure the value changed as you expect.
some cases or with some values …

adding configuration option cloud.scada_address

---

.changelog/14916.txt
agent/consul/xdscapacity/capacity.go
agent/proxycfg-sources/catalog/config_source.go

[memdb's `WatchCh` method](https://pkg.go.dev/github.com/hashicorp/go-memdb#WatchSet.WatchCh) creates a goroutine that will publish to the returned channel when the watchset is triggered or the given context is canceled. Although this is called out in its godoc comment, it's not obvious that this method creates a goroutine who's lifecycle you need to manage.
In the xDS capacity controller, we were calling `WatchCh` on each iteration of the control loop, meaning the number of goroutines would grow on each autopilot event until there was catalog churn.
In the catalog config source, we were calling `WatchCh` with the background context, meaning that the goroutine would keep running after the sync loop had terminated.

bug: fix goroutine leaks caused by incorrect usage of `WatchCh`

---

.changelog/14962.txt
agent/proxycfg-sources/catalog/config_source.go
agent/proxycfg-sources/catalog/config_source_test.go

Fixes an omission in the 1.14 beta, where central service configuration (i.e. the `proxy-defaults` and `service-defaults` config entries) was not applied to the generated xDS resources.
1. Start a dev server
1. Register a node, service, and sidecar proxy via the catalog API
1. Run `consul-dataplane` with the proxy service's ID
1. Create a `proxy-defaults` config entry which sets the default protocol to HTTP
1. Observe in the Envoy admin server's `config_dump` page that the public listener has an `HttpConnectionManager` filter
1. Create a `service-defaults` entry which overrides the protcol to TCP
1. Observe that the `HttpConnectionManager` filter is gone

xds: properly merge central config for "agentless" services

---

ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/service/search-bar/index.js

Make sure the `Consul API Gateway`-source filter is always displayed at the bottom of the services sources filter when present. This PR also moves the `Consul`-source to the top of the list.
* `make start`
* go to the services overview and wait until a service has the `Consul API gateway` assigned.
* See that this source is always displayed at the bottom of the source dropdown now.
[NET-745](https://hashicorp.atlassian.net/browse/NET-745)

ui: Always sort consul-gateway to bottom sources list

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/grpc-external/server.go
agent/grpc-external/services/peerstream/stream_resources.go
website/content/docs/connect/cluster-peering/index.mdx

Backport of ENT-3239
increase grpc message size limit to 50MB, handle grpc ResouceExhausted error messages when it's related to a resource.
context:
Protobufs received by grpc-go are [limited to 4MB](https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize). Assuming large 5KB CheckServiceNode definitions, this allows to send ~800 instances in a single message.
That should be OK for most use-cases, particularly if we are merging health checks down into a single check. However, there could still be cases where a larger service is being replicated.
* validated the size limit by lowering `MaxCallSendMsgSize` and `MaxRecvMsgSize` to 50KB.
* updated tests to catch the new error code

[OSS] increase protobuf size limit for cluster peering

---

.changelog/14935.txt
agent/agent.go
agent/agent_test.go

Preivously when alias check was removed it would not be stopped nor cleaned up from the associated aliasChecks map.
This means that any time an alias check was deregistered we would leak a goroutine for CheckAlias.run() because the stopCh would never be closed.
This issue comes up then the `sidecar_service` stanza is used, as documented [here](https://www.consul.io/docs/connect/registration/sidecar-service#register-a-service-mesh-proxy-in-a-service-registration). When services are registered this way without custom health checks it leads to adding an alias check, which makes the sidecar service reflect the health of the underlying service.
The issue can lead to large goroutine counts in service mesh deployments on platforms where the client agent is mostly static but proxy services come …

Fix alias check leak

---

ui/packages/consul-peerings/app/components/consul/peer/bento-box/index.hbs

Only show scrollbars on the peering bento-box when necessary.
Before (on Windows and with scrollbars set to `always` on macOS):
After:

ui: Bento-Box show scrollbars only when necessary

---

.changelog/14960.txt
agent/agent.go
agent/agent_test.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/proxycfg/manager.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
website/content/docs/agent/config/config-files.mdx

Adds a user-configurable rate limiter to `proxycfg` snapshot delivery, with a default limit of 250 updates per second.
This addresses a problem observed in our load testing of Consul Dataplane where updating a "global" resource such as a wildcard intention or the `proxy-defaults` config entry could starve the Raft or memberlist goroutines of CPU time, causing general cluster instability.
Tested using the Consul Dataplane load test harness. Observed that creating a wildcard intention with 5k connected streams no longer triggers missed memberlist pings (and suspicions from other peers).

proxycfg: rate-limit delivery of config snapshots

---

.changelog/14986.txt
ui/packages/consul-ui/app/components/consul/health-check/list/pageobject.js
ui/packages/consul-ui/app/controllers/dc/services/instance/healthchecks.js
ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/instances/health-checks.feature
ui/packages/consul-ui/tests/acceptance/dc/services/instances/show.feature
ui/packages/consul-ui/tests/steps/assertions/model.js

Removes the "Node" type in "Search Across" dropdown on the service/instance/healthchecks page if the instance is using agentless. Also filters any healthchecks to not show any node checks, in case there were any.
- Kubernetes instances will be agentless on the vercel app so you can go to one of those and check it out.
- [NET-1126](https://hashicorp.atlassian.net/browse/NET-1126)

UI: filter node healthchecks on agentless service instances

---

agent/agent_test.go

Fixup of #14983
An auto-backport kept a reference to testutil.RunStep, which doesn't exist in 1.12.x.

[1.12.x] Fix runStep usage

---

.changelog/14981.txt
acl/acl_oss.go
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go
agent/consul/peering_backend.go
agent/consul/peering_backend_test.go
agent/grpc-external/services/peerstream/stream_resources.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/state_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/base.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/config_entries.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/service_gateway.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/service_s1.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/service_s2.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/setup.sh
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/verify.bats
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/bind.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/capture.sh
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/base.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/config_entries.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/service_gateway.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/service_s1.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/service_s2.hcl
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/setup.sh
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/verify.bats
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/vars.sh

OSS Backport of ENT-3244
When peering through mesh gateways we expect outbound dials to peer
servers to flow through the local mesh gateway addresses.
Now when establishing a peering we get a list of dial addresses as a
ring buffer that includes local mesh gateway addresses if the local DC
is configured to peer through mesh gateways. The ring buffer includes
the mesh gateway addresses first, but also includes the remote server
addresses as a fallback.
This fallback is present because it's possible that direct egress from
the servers may be allowed. If not allowed then the leader will cycle
back to a mesh gateway address through the ring.
When attempting to dial the remote servers we retry up to a fixed
timeout. If using mesh gateways we also have an initial wait in
order to allow for the …

Update peering establishment to maybe use gateways

---

.changelog/14800.txt
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/config.go
agent/xds/testdata/clusters/mesh-gateway-tcp-keepalives.latest.golden
agent/xds/testdata/clusters/terminating-gateway-tcp-keepalives.latest.golden
website/content/docs/connect/proxies/envoy.mdx

This PR adds TCP keepalive settings to the proxy config to be applied to connections between remote mesh gateways. This makes it easier to handle the case of a proxy in between with its own idle timeout settings (like an AWS NLB, which has a non-configurable 350s idle connection timeout).
TODO:

Add TCP keepalive settings to proxy config for mesh gateways

---

agent/proxycfg/state.go

Fixes a bug where we'd leak a goroutine in `state.run` when the given context was canceled while there was a pending update.

proxycfg: fix goroutine leak when service is re-registered

---

website/content/docs/connect/cluster-peering/k8s.mdx

- Highlighting on `backend` application was off and not highlighting annotation and config for Consul DNS name
- Add more details for removing Peering CRDs

docs: formatting on backend application and delete peering CRDs

---

.changelog/15005.txt
agent/cache-types/connect_ca_leaf.go

In practice this was masked by #14956 and was only uncovered fixing the other bug.
go test ./agent -run TestAgentConnectCALeafCert_goodNotLocal
would fail when only #14956 was fixed.

ca: fix a masked bug in leaf cert generation that would not be notified of root cert rotation after the first one

---

.changelog/14908.txt
agent/cache/cache.go
agent/cache/cache_test.go

There is a bug in the error handling code for the Agent cache subsystem discovered by @boxofrad :
1. `NotifyCallback` calls `notifyBlockingQuery` which calls `getWithIndex` in a loop (which backs off on-error up to 1 minute)
2. `getWithIndex` calls `fetch` if there’s no valid entry in the cache
3. `fetch` starts a goroutine which calls `Fetch` on the cache-type, waits for a while (again with backoff up to 1 minute for errors) and then calls `fetch` to trigger a refresh
The end result being that every 1 minute `notifyBlockingQuery` spawns an ancestry of goroutines that essentially lives forever.
This PR ensures that the goroutine started by `fetch` cancels any prior goroutine spawned by the same line for the same key.
In isolated testing where a cache type was tweaked to indefinitely …

cache: prevent goroutine leak in agent cache

---

agent/intentions_endpoint_test.go

Restructure test setup to be similar to `TestAgent_ServerCertificate` and see if that's enough to avoid flaking after join.

test: possibly fix flake in TestIntentionGetExact

---

test/integration/connect/envoy/case-ingress-gateway-multiple-services/verify.bats

The integration test `TestEnvoy/case-ingress-gateway-multiple-services` is flaky and this possibly reduces the flakiness by explicitly waiting for services to show up in the catalog as healthy before waiting for them to show up in envoy as healthy which gives it just a bit more time to sync.

test: possibly fix flaky TestEnvoy/case-ingress-gateway-multiple-services test

---

agent/consul/leader_peering_test.go
agent/grpc-external/services/peerstream/replication.go

When some resource such as a check is imported we currently always apply the newly received resource. This happens even if the resource was not modified.
For each imported resource we should compute a diff relative to the data stored locally. This will cost some CPU time but can save trips through Raft when data has not changed.
- Node: skip CatalogRegister duplicate node
- Service: skip CatalogRegister duplicate service instance
- Check: skip CatalogRegister duplicate check
1. Register a service in the acceptor cluster with some check
2. Export the service
3. Change the meta or tag of the service, which changes the service. Then register the service again.
4. Issue a request to `/v1/health/service/` of the peering cluster.  As a result, the Index of the service will be changed, but that …

peering: skip registering duplicate node and check from the peer

---

ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/docs/bookmarklets.mdx
ui/packages/consul-ui/mock-api/v1/health/service/_
ui/packages/consul-ui/mock-api/v1/internal/ui/nodes

Enable synthetic nodes in mock data by setting a cookie. I had to step through the `get-environment` utility to figure out what was going on, so I added a few comments. Michael and I already discussed some ways we could improve this, but that won't be included in this PR.

ui: enable synthetic nodes in mock data

---

.changelog/15035.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

This PR changes the behavior added in https://github.com/hashicorp/consul/pull/14516 - specifically, the fix required using the tune endpoint to update the `MaxLeaseTTL` in the intermediate PKI mount, which was a new permission in Vault we weren't explicitly documenting. This changes the failure case to emitting a warning log message instead of an error, which would've caused attempts to update the CA configuration to fail if this permission was missing.

Warn instead of returning error when missing intermediate mount tune permissions

---

test/integration/consul-container/go.mod
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/node/consul-container.go
test/integration/consul-container/metrics/leader_test.go
test/integration/consul-container/upgrade/healthcheck_test.go

The module path in the changed go.mod is `github.com/hashicorp/consul/integration/consul-container`, which appears to miss `test` in the path. This PR uses the full path.

chore: fix the module path to align with the code structure

---

.changelog/15065.txt
agent/consul/peering_backend.go
agent/consul/peering_backend_test.go

Use wan address in the peering token.
With the following agent config,
```
{
bind_addr =  “172.16.1.10”
advertise_addr_wan = “192.168.1.10"
}
ports {
grpc_tls = 8502
serf_wan = 8302
},
```
the generated token always has the private bind address in "ServerAddresses":["172.16.1.10:8502"]," , which prevents the peering cluster from reaching the acceptor cluster.
fix #15051

fix: wan address isn't used by peering token

---

ui/packages/consul-ui/app/routes/application.js
ui/packages/consul-ui/app/services/env.js
ui/packages/consul-ui/app/services/hcp.js
ui/packages/consul-ui/tests/acceptance/hcp-login-test.js

Fixes the logic that was added in https://github.com/hashicorp/consul/pull/14495 to always fetch a token based on `TokenSecretID` when that is different from what we persisted to settings before.
This makes sure we can override the `TokenSecretID` and not only set it up once.
In addition to fixing the login logic when the application boots up, I added tests and created a mechanism that we can use from now on when we want to stub out configuration on the `env`-service.
* setup `TokenSecretID` in a cookie and see that it will call the token endpoint with the provided value when the application boots up.

ui: Fix token in cookie passthrough

---

website/content/docs/connect/registration/service-registration.mdx

This PR fixes a typo in the Service mesh > Register a Service page.

fixed broken link/typo in service mesh reg page

---

test/integration/consul-container/libs/node/consul-container.go
test/integration/consul-container/libs/node/consul-container_oss.go
test/integration/consul-container/libs/node/node.go
test/integration/consul-container/libs/utils/version_oss.go
test/integration/consul-container/metrics/leader_test.go
test/integration/consul-container/upgrade/README.md
test/integration/consul-container/upgrade/healthcheck_test.go

Sometimes we need to run integration for a dev image such as `hashicorppreview/consul:1.14-dev`. The current implementation hardcoded the image name to be `consul`.
This PR adds options to specify the image name to be tested.
- Some note is added to `README`
NA

integration test: specify image name for testing dev container

---

agent/http.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go

This commit updates the establish endpoint to bubble up a 403 status code to callers when the establishment secret from the token is invalid. This is an additional signal that a new peering token must be generated.
* Updated the gRPC handler's test
* Manually tested re-using a token via the CLI and got the following output:
> Error establishing peering for cluster-02: Unexpected response code: 403 (rpc error: code = PermissionDenied desc = a new peering token must be generated: invalid peering establishment secret)

Return forbidden on permission denied

---

GNUmakefile

Previously, I would sometimes get Killed errors when executing the binary created by `make dev`. This is because we were using `cp` and OSX has a bug where it caches the old signature and so doesn't allow the new binary to run (see https://apple.stackexchange.com/a/428388)

builds: fix "Killed" error with make dev

---

.github/workflows/nightly-test-1.14.x.yaml
version/version.go

Branch `release/1.14.x` was just created, which moves `main` to build the dev version of Consul 1.15. This also adds a Nightly UI test job for the 1.14 branch. Despite git thinking this was renamed from `1.11`, I actually copied it from `main` to get the most current CI flow.

[OSS] chore: update main for release/1.14.x branch

---

website/content/docs/connect/gateways/mesh-gateway/wan-federation-via-mesh-gateways.mdx

Care must be taken when replacing mesh gateways in the primary datacenter. If the old gateway addresses become unreachable before the secondary datacenters receive the new addresses, then the primary datacenter overall will become unreachable.
This commit adds docs related to this class of upgrades.

Add docs about upgrading primary mesh gateways

---

website/content/docs/release-notes/consul-k8s/v0_49_x.mdx

Add .x next to supported k8s versions to make it explicit that all patch versions of k8s minor versions are supported 

docs: update versions to include .x in release notes

---

agent/consul/fsm/fsm.go
agent/consul/fsm/snapshot_oss_test.go

Closes #15055
The new error message will indicate that the log entry is a Consul Enterprise one and will not be recognized or loaded by Consul OSS.
Repro:
* Create a snapshot using a Consul Enterprise build.
* Change the binary to Consul OSS and try to restore the snapshot taken from the above step.
* You will notice the message - `'Unrecognized msg type %d'` and the startup would end.
Testing the changes:
* Repeating the above steps with the new binary will lead to the message - `'msg type <%d> is a Consul Enterprise log entry. Consul OSS does not recognize or load it'`
* Unit test case has been added to - `agent/consul/fsm/snapshot_oss_test.go`
* You could also test the entire `fsm` piece using - `go test github.com/hashicorp/consul/agent/consul/fsm`
This is for -> …

Committing for - 15055

---

agent/health_endpoint_test.go
agent/rpcclient/health/health.go

`TestHealthServiceNodes_NodeMetaFilter` is flaky when executing the streaming variant and in at least one investigation it flaked because the gRPC subsystem hadn't actually gotten a valid stream open to a server by the time the streaming parts tried to use it.
This updates the test (and also `TestHealthIngressServiceNodes`) to wait until that initial priming is complete before running the body of the test.

test: fix flaky TestHealthServiceNodes_NodeMetaFilter by waiting until the streaming subsystem has a valid grpc connection

---

.changelog/15108.txt
agent/grpc-external/services/peerstream/subscription_manager.go
agent/grpc-external/services/peerstream/subscription_manager_test.go

When sending server address to the dialing peer cluster, wan address should be used if there is any.
This PR is consistent to the fix for generating peering token (#15065).
fix #15087

fix(peering): replicating wan address

---

website/content/docs/upgrading/upgrade-specific.mdx

Manual backport of https://github.com/hashicorp/consul/pull/15028
Only difference is that it excludes the 1.14 specific content

[1.13 backport] auto cert 1.13.2 upgrade docs

---

agent/acl_test.go
agent/setup.go
agent/testagent.go
command/agent/agent.go

Some of the inner dependencies of a test agent were creating a different default logger than the one created specifically for the test (which ensures that the logs are tied to the testcase itself).
This rearranges it so that the test logger is used for the whole dependency construction pass.

test: ensure that all dependencies in a test agent use the test logger

---

ui/packages/consul-ui/ember-cli-build.js

When building the application for production, the auto-generated URLs for webpack asset chunks that ember-auto-import v2 adds to `index.html` pointed to the wrong URL. Instead of containing the `{{.ContentPath}}`-placeholder they were pointing to `/ui/assets`. This is correct in the default use-case for bundling the UI in the consul-binary, but would break when trying to serve the UI from a different place than `/ui`.
The `lib/startup`-add-on is used to create a custom index.html page to boot up the app. Because of this being a custom approach, ember-auto-import isn't doing the right thing by default, as we aren't relying on setting `rootURL` to a different value when running the app in `production`. We need to set `publicAssetURL` explicitly in the configuration we pass to …

ui: fix - customize ember-auto-import publicAssetURL in production

---

.changelog/14832.txt
agent/consul/auto_encrypt_endpoint.go
agent/consul/auto_encrypt_endpoint_test.go
agent/pool/pool.go

If clients have set a different datacenter than the servers they're connecting with for autoencrypt, give a helpful error message. Fixes https://github.com/hashicorp/consul/issues/10205
The change is to check when we're about to call `ForwardRPC` if the datacenter matches our current DC. There's no use-case for forwarding to a remote DC so we can short-circuit right there.
```
server = true
bootstrap_expect = 1
data_dir = "/tmp/consul-server"
auto_encrypt {
allow_tls = true
}
tls {
defaults {
ca_file = "certs/consul-agent-ca.pem"
cert_file = "certs/dc1-server-consul-0.pem"
key_file = "certs/dc1-server-consul-0-key.pem"
}
}
```
```
datacenter = "different"
retry_join = ["127.0.0.1:8301"]
ports {
http = 9501
dns = 9600
serf_lan = 9301
}
data_dir = "/tmp/consul-client"
auto_encrypt {
tls = …
```

autoencrypt: helpful error for clients with wrong dc

---

.changelog/14833.txt
api/config_entry.go
command/config/write/config_write_test.go

proxy-defaults can only have the name global. Because of this, we support not even setting the name in the config file:
```
kind = "proxy-defaults"
```
Previously, writing this would result in the output:
```
Config entry written: proxy-defaults/
```
Now it will output:
```
Config entry written: proxy-defaults/global
```
This change follows what was done for the new Mesh config entry.
Fixes https://github.com/hashicorp/consul/issues/10809

config entry: hardcode proxy-defaults name as global

---

agent/xds/clusters.go
agent/xds/testdata/clusters/mesh-gateway-with-imported-peered-services.latest.golden

On `main` I ran into this error:
```
2022-10-24T20:41:20.205Z+00:00 [warning] envoy.config(13) delta config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Error adding/updating cluster(s) product-api.default.default.us-west-1.external.7c74b5a2-3341-399e-1355-8c767c764b30.consul: eds_cluster_config set in a non-EDS cluster
```
It's caused by `makeGatewayCluster` configuring EDS when it doesn't receive `hostnameEndpoints`.

Fix bug that resulted in generating Envoy configs that use CDS with an EDS Configuration

---

ui/packages/consul-peerings/app/components/consul/peer/bento-box/index.hbs
ui/packages/consul-peerings/app/templates/dc/peers/show/exported.hbs
ui/packages/consul-ui/app/styles/tailwind.scss
ui/packages/consul-ui/docs/hds.mdx
ui/packages/consul-ui/tailwind.config.js

This PR updates our usage of [HashiCorp Design System](https://github.com/hashicorp/design-system) to match the best practices that the HDS team was telling us about in a recent call.
The changes update the code according to the following best-practices:
1. Don't generate custom tailwind utility classes for colors
2. Use HDS color utilities instead of creating our own variants for colors when displaying text base on tailwind color utilities
3. Update flight icons usage to make use of `@color` instead of setting a text-color via Tailwind and using `fill-current`
This PR also updates the section of our engineering docs about HDS to better reflect the HDS best practices discussed.
* Visit peer-detail page and see that everything looks the same as it did before
* Look at engineering docs to …

UI: update hds usage to hds best practices

---

ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs
ui/packages/consul-peerings/app/controllers/dc/peers/index.js
ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
ui/packages/consul-ui/tests/acceptance/dc/peers/establish.feature

After we establish a peering from the UI, we want to take users to the peer detail page.
* start a peerable cluster setup
* create a peering token in cluster-a
* establish a peering via created token in cluster-b
* see that the user will end up in the `dc.peers.show`-route after they successfully established the peering

ui: peer create redirect to show

---

.changelog/15160.txt
agent/grpc-external/services/peerstream/replication.go

handleUpdateService is called either from handleService or `handleUpsertExportedServiceList`. `handleUpsertExportedServiceList` passes nil to the export parameter, which will potentially cause panic due to the nil pointer.
https://github.com/hashicorp/consul/blob/41e50a0f8d5f38c0ffd394c0cd99c8dd4ddb35d9/agent/grpc-external/services/peerstream/replication.go#L291-L295

fix(peering): nil pointer in calling handleUpdateService

---

.changelog/15155.txt
agent/http.go
agent/http_test.go
api/api.go
api/debug.go
command/debug/debug.go
command/debug/debug_test.go

https://github.com/hashicorp/consul/pull/10273 had an unintended side-effect of crashing `consul debug` CLI command if ACLs were disabled and `debug_enabled` was false.
The correct behavior would be to disable the HTTP endpoints for profiling information but still allowing other debug profile targets like `logs` and `metrics` to run without issues.
* Modified tests to assert for previous behavior

Allow consul debug on non-ACL consul servers

---

ui/packages/consul-peerings/app/components/consul/peer/address/list/index.hbs

Improves the layout of the address list on the peer-detail page. This PR centers the IP address text and moves the copy button to the end of the row. The copy button will still only show up when hovering the row.
__Screenshot after change:__

ui: Improve layout address list peer detail

---

ui/packages/consul-ui/app/models/service.js
ui/packages/consul-ui/app/utils/create-fingerprinter.js

We need to make a `PeerName` part of the service ID when present.
This makes sure that peers can export services named the same as other peers, but have the UI still treat them as separate services.
This also resolves an issue where services in the host cluster would display weirdly when named the same as a service imported via a peer.
* set up a cluster setup that allows to create peerings
* create a service on cluster-a named the same as a service that will be exported from cluster-b
* see that both services are displayed as separate services in the service list and only the imported one displays peer information

ui: Fix PeerName is part of service uniqueness

---

.changelog/15178.txt
agent/consul/leader_peering.go
agent/consul/leader_peering_test.go

This bug was caused by the peering health metric being set to `NaN` when a peering has never been connected. This fixes the bug by setting the metric's value to `0` rather than `NaN`.

Fix Peering Metrics Bug

---

website/content/docs/api-gateway/configuration/gatewayclassconfig.mdx

Remove extraneous `[` causing broken link in Consul API Gateway docs
Verify that the `account` link [here](https://consul-ggzxbf4bz-hashicorp.vercel.app/consul/docs/api-gateway/configuration/gatewayclassconfig#configuration-model) works with this change in place
https://consul-ggzxbf4bz-hashicorp.vercel.app/consul/docs/api-gateway/configuration/gatewayclassconfig#configuration-model

Fix broken link in Consul API Gateway docs

---

GNUmakefile

In many local setups you may run `make dev-docker` with the intent to run that consul image on a local docker install. But frequently you will also want to interact with that running install using the CLI running on your host machine.
This ensures that `make dev-docker` will also produce a dev binary (`make dev`) at the same time so that they can match.

build: ensure 'make dev-docker' also produces a matching CLI binary at the same time

---

agent/configentry/merge_service_config.go
agent/configentry/merge_service_config_test.go
test/integration/connect/envoy/case-cross-peers-http/primary/config_entries.hcl

This change prevents `service-defaults` and `proxy-defaults` from overwriting the protocol on services imported through peering. Without this change, the protocol could mismatch what was expected on the remote mesh gateway.

Fix peered service protocols using proxy-defaults.

---

.changelog/15093.txt
.circleci/config.yml
agent/xds/envoy_versioning.go
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
website/content/docs/connect/proxies/envoy.mdx

Envoy 1.24.0 was recently released. This adds it to our integration test matrix. Because we are introducing a new minor series of Envoy, this means we drop the oldest minor which is 1.20. 
If the integration test suite fails, we will need to make changes, otherwise we are good.
- [Envoy 1.24.0](https://github.com/envoyproxy/envoy/releases/tag/v1.24.0)

connect: Add Envoy 1.24 to integration tests, remove Envoy 1.20

---

agent/consul/leader_peering.go
agent/consul/leader_peering_test.go

Decrease the max wait time to 64 seconds for failed peering connections.

Decrease retry time for failed peering connections.

---

website/content/docs/api-gateway/tech-specs.mdx

The [README](https://github.com/hashicorp/consul-api-gateway/blob/main/README.md) and [Release Notes](https://developer.hashicorp.com/consul/docs/release-notes/consul-api-gateway/v0_4_x#supported-software) for Consul API Gateway v0.4 indicate that v0.47.1+ of the Consul Helm chart is required; however, it seems we missed updating the Tech Specs page.
See README and Release Notes links above

Update required Helm chart version to match APIGW release notes

---

.changelog/15233.txt
test/integration/connect/envoy/case-basic/verify.bats
test/integration/connect/envoy/case-centralconf/verify.bats
test/integration/connect/envoy/case-cfg-resolver-cluster-peering-failover/primary/verify.bats
test/integration/connect/envoy/case-cfg-resolver-svc-redirect-http/verify.bats
test/integration/connect/envoy/case-cfg-resolver-svc-redirect-tcp/verify.bats
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-http-router/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-http/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-resolver-redirect-tcp/primary/verify.bats
test/integration/connect/envoy/case-cross-peers/primary/verify.bats
test/integration/connect/envoy/case-expose-checks/verify.bats
test/integration/connect/envoy/case-gateways-local/primary/verify.bats
test/integration/connect/envoy/case-gateways-remote/primary/verify.bats
test/integration/connect/envoy/case-http/verify.bats
test/integration/connect/envoy/case-ingress-gateway-simple/verify.bats
test/integration/connect/envoy/case-ingress-gateway-tls/verify.bats
test/integration/connect/envoy/case-ingress-mesh-gateways-resolver/primary/verify.bats
test/integration/connect/envoy/case-multidc-rsa-ca/primary/verify.bats
test/integration/connect/envoy/case-prometheus/verify.bats
test/integration/connect/envoy/case-stats-proxy/verify.bats
test/integration/connect/envoy/case-terminating-gateway-hostnames/verify.bats
test/integration/connect/envoy/case-terminating-gateway-simple/verify.bats
test/integration/connect/envoy/helpers.bash

The output of retry in bats test contains the failed message (see below example), a condition that will cause the step to fail because the `status=0` while output contains extraneous content.
```
not ok 14 s1 upstream should be able to connect to s2
```
This PR fixes the flakiness by using `string contain` test condition.
```
- [ "$output" = "hello" ]
+ [[ "$output" == *"hello"* ]]
```
- auto-format done by the editor

integ test: reduce flakiness due to compound output from retry

---

agent/grpc-middleware/auth_interceptor.go
agent/grpc-middleware/auth_interceptor_test.go

restrictPeeringEndpoints introduced some failures in consul-api-gateway. This check will prevent the middleware from erroring when no peeringsni is set
- consul-api-gateway tests pass when using an image built from this branch
* https://github.com/hashicorp/consul-api-gateway/actions/workflows/conformance.yml Pipeline failures in consul-api-gateway

Added check for empty peeringsni in restrictPeeringEndpoints

---

agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go
agent/grpc-external/services/peerstream/stream_tracker_test.go
agent/rpc/peering/service.go
api/peering.go
proto/pbpeering/peering.go

Convert stream status time fields to pointers to avoid zero-value time fields in front-end. 
ENT-PR: https://github.com/hashicorp/consul-enterprise/pull/3489

convert stream status time fields to pointers

---

website/content/commands/peering/generate-token.mdx

The [live docs](https://developer.hashicorp.com/consul/commands/peering/generate-token#meta) on the website have a stray line from a merge conflict that made it in
> **Note** This line is no longer present in the Consul 1.14.x [docs](https://raw.githubusercontent.com/hashicorp/consul/release/1.14.x/website/content/commands/peering/generate-token.mdx); however, those are not live on the docs site yet.
Verify line is no longer present
[Live docs containing this stray line](https://developer.hashicorp.com/consul/commands/peering/generate-token#meta)

Remove stray line from merge conflict

---

agent/consul/fsm/snapshot_test.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/proxycfg-glue/trust_bundle_test.go
test/integration/consul-container/libs/service/common.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go

During peering stream updates, accepting clusters send updates to dialers about TrustBundle changes, but these changes are not filtered back into the peering object. If the connection is interrupted after a CA rotation, the dialer will not have the correct CA info to dial the acceptor. 
This PR also updates the Peering records when a trust bundle is written to the state store.
* Unit Tests
* Run the integration test `rotate_server_and_ca_then_fail_test.go`

fix: persist peering CA updates to dialing clusters

---

agent/proxycfg/mesh_gateway.go
agent/proxycfg/state_test.go

* This adds a lot of tests that ensure ACL tokens are being passed in proxycfg

Fix a bug in mesh gateway proxycfg where ACL tokens aren't passed

---

.changelog/15083.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/endpoints.go
test/integration/consul-container/libs/service/common.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/helpers.go

When providing updates to Envoy it is safest to follow the update order of: Clusters, Endpoints, Listeners, Routes. This order is encoded in our delta xDS response generation code.
Another noteworthy attribute of these resources is that there are parent->child relationships between: Cluster->Endpoints and Listener->Routes. Envoy couples the storage of a parent and a child type such that whenever a control plane sends an update for a parent type, it MUST also send fresh data for the child type, even if Envoy previously had the latest data for the child type.
A wrinkle that isn't accounted for currently is that Envoy does not actually ACK parent types until after attempting to receive data for the child types. This behavior also actually differs between Clusters and Listeners:
- When a …

Avoid blocking child type updates on parent ack

---

api/config_entry_exports.go

Now that we don't support peering between local partitions, this comment is no longer true.

Update api package exported services comment.

---

agent/configentry/merge_service_config.go
agent/consul/catalog_endpoint.go
agent/consul/health_endpoint.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
agent/proxycfg-sources/catalog/config_source.go

Previously, the `MergeNodeServiceWithCentralConfig` method accepted a `ServiceSpecificRequest` argument, of which only the `Datacenter` and `QueryOptions` fields were used.
Digging a little deeper, it turns out these fields were only passed down to the `ComputeResolvedServiceConfig` method (through the `ServiceConfigRequest` struct) which didn't actually use them.
As such, not all call-sites passed a valid `ServiceSpecificRequest` so it's safer to remove the argument altogether to prevent future changes from depending on it.

chore: remove unused argument from `MergeNodeServiceWithCentralConfig`

---

website/content/docs/enterprise/license/faq.mdx

Two of the links pointing to sections of the same page need to be fixed
The following two sections contain links that point to `https://consul.io/faq#LINK-HERE`.
- [Q: Does this affect client agents?](https://developer.hashicorp.com/consul/docs/enterprise/license/faq#q-does-this-affect-client-agents)
- [Q: Does this affect snapshot agents?
](https://developer.hashicorp.com/consul/docs/enterprise/license/faq#q-does-this-affect-snapshot-agents)

docs: fix links in ent-license faq

---

.changelog/15317.txt
acl/acl.go
agent/consul/prepared_query_endpoint_test.go
agent/structs/aclfilter/filter.go
agent/structs/aclfilter/filter_test.go
agent/structs/structs.go
agent/structs/structs_test.go

Update ACLs for cluster peering, allow imported services to be read with readAll or writeAny tokens. 
Context: [Enterprise PR](https://github.com/hashicorp/consul-enterprise/pull/3431)

update ACLs for cluster peering

---

agent/consul/leader_peering_test.go
agent/consul/peering_backend.go
agent/consul/peering_backend_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go

When trying to establish a peering using mesh gateways, there is a high probability that because of the fallback behavior, you will end up bypassing the local mesh gateway and going directly to the remote cluster.
This PR attempts to solve the problem in two ways:
Increase the sleep time that allows the mesh gateway to update xDS from 350ms (~p50) to 1s (~p96)
Enter a retry loop of only gateway addresses for a few seconds, then fallback to all addresses.

[OSS] fix: wait and try longer to peer through mesh gw

---

.changelog/15339.txt
agent/agent.go
agent/config/builder.go
agent/config/builder_test.go
website/content/docs/agent/config/config-files.mdx
website/content/docs/upgrading/upgrade-specific.mdx

This PR builds upon https://github.com/hashicorp/consul/pull/14294 where the new `grpc_tls` port was originally added.
We remove the ability to run the `ports.grpc` in TLS mode to avoid confusion and to simplify configuration. This breaking change ensures that any user currently using `ports.grpc` in an encrypted mode will receive an error message indicating that `ports.grpc_tls` must be explicitly used.
The suggested action for these users is to simply swap their `ports.grpc` to `ports.grpc_tls` in the configuration file. If both ports are defined, or if the user has not configured TLS for grpc, then the error message will not be printed.

Prevent serving TLS via ports.grpc

---

.changelog/15320.txt
agent/connect/csr.go
agent/connect/csr_test.go
agent/proxycfg/ingress_gateway.go

Closes https://github.com/hashicorp/consul/issues/11092 - currently we're passing along whatever's in the `Hosts` field verbatim to construct the list of SANs. This PR changes that to strip the `:` and everything after it from each `Host` string so that it's in the format Vault expects when signing the leaf cert.

connect: strip port from DNS SANs for ingress gateway leaf cert

---

acl/authorizer_oss.go
acl/policy_authorizer.go
acl/policy_authorizer_test.go
agent/consul/acl.go
agent/consul/catalog_endpoint.go
agent/consul/filter.go
agent/consul/health_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/state/catalog_events.go
agent/proxycfg-glue/exported_peered_services.go
agent/proxycfg-glue/internal_service_dump.go
agent/structs/aclfilter/filter_test.go
agent/structs/structs.go
agent/structs/structs_oss.go
agent/structs/structs_test.go

OSS Backport of ENT-3560
Follow-up to: #15317
There are a few changes that needed to be made to to handle authorizing
reads for imported data:
- If the data was imported from a peer we should not attempt to read the
data using the traditional authz rules. This is because the name of
services/nodes in a peer cluster are not equivalent to those of the
importing cluster.
- If the data was imported from a peer we need to check whether the
token corresponds to a service, meaning that it has service:write
permissions, or to a local read only token that can read all
nodes/services in a namespace.
* Unit testing in acl package and for ACL filter

Fixup authz for data imported from peers

---

.changelog/15356.txt
agent/structs/aclfilter/filter.go
agent/structs/aclfilter/filter_test.go
agent/structs/structs_oss.go

OSS Backport of ENT-3561
Previously the ACL filter was not operating on NodeDump.ImportedDump,
which means that the UI Nodes views will always return data imported
from a peer without filtering.
Because of this, imported nodes/services/checks could be viewed by
users lacking the appropriate ACL permissions.
This commit updates the ACL filtering logic on IndexedImportedNode so
that we also filter the contents of the ImportedDump field.
* Unit tests

Ensure that NodeDump imported nodes are filtered

---

.changelog/15370.txt
agent/config/builder.go
agent/consul/auto_config_endpoint.go
website/content/docs/agent/config/cli-flags.mdx

This changes the JWT authorization logic to allow all non-whitespace, non-quote characters when validating node names. Consul had previously allowed these characters in node names, until this validation was added to fix a security vulnerability with whitespace/quotes being passed to the `bexpr` library. This unintentionally broke node names with characters like `.` which aren't related to this vulnerability. This PR also adds a warning on agent startup if an invalid character is present in the node name (at some point we can consider changing this to a hard error).

auto-config: relax node name validation for JWT authorization

---

test/integration/connect/envoy/case-cross-peer-control-plane-mgw/alpha/verify.bats

In the integ test case `case-cross-peer-control-plane-mgw`, remove unnecessary step since connection is already via mgw

integ-test: remove unnecessary step since connection is already via mgw

---

website/content/docs/k8s/compatibility.mdx

Update consul-k8s compatibility matrix to match stable release branches. Since after 1.0.0, consul <1.14 will only be compatible with up through consul-k8s 0.49.x
This change should go to the 1.13 branch of docs as well, so backporting them to 1.13. Not 100% sure if this is the right label.

docs: update compatibility matrix

---

website/content/docs/upgrading/upgrade-specific.mdx

The upgrade notes were not displaying correctly on the website due to a stray newline character. This fixes it.
Old: https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#changes-to-grpc-tls-configuration
New: https://consul-d80jhn4li-hashicorp.vercel.app/consul/docs/upgrading/upgrade-specific#changes-to-grpc-tls-configuration

Fix issue with formatting in upgrade notes.

---

website/content/docs/agent/config/config-files.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Fix missing documentation on upgrade process and new grpc_tls addresses config.

Include addresses.grpc_tls in upgrade docs.

---

agent/session_endpoint.go
website/content/commands/lock.mdx

When user uses `consul lock` to acquire a lock in a remote dc, if the command is run at a client agent, the returned error message is 
`Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: rpc error making call: apply failed: Missing node registration)`
which is unclear about the actual root cause. This PR updates the error message to 
`Lock acquisition failed: failed to create session: Unexpected response code: 500 (cross datacenter lock must be created at server agent)`
Please refer to the issue https://github.com/hashicorp/consul/issues/14212#issuecomment-1316215464
fix https://github.com/hashicorp/consul/issues/14212

fix: clarifying error message when acquiring a lock in remote dc

---

website/content/docs/upgrading/upgrade-specific.mdx

See https://github.com/hashicorp/nomad/issues/15266 for details.
I plan to submit a followup PR to update these docs once Nomad releases a fix. At that point Nomad users will still need to be informed that they must upgrade Nomad to a compatible version *before* upgrading Consul to 1.14.
Feel free to edit the wording or formatting or whatever. I just want to get any warning up for Nomad users ASAP so they don't discover this *after* having upgraded their Consul cluster and end up in a really bad state.

docs: add nomad incompatibility to 1.14 docs

---

website/content/docs/connect/ca/vault.mdx
website/content/docs/k8s/connect/connect-ca-provider.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/connect-ca.mdx

Update guidance for vault PKI CA provider

---

website/content/docs/connect/dataplane/consul-dataplane.mdx
website/content/docs/connect/dataplane/index.mdx
website/content/docs/connect/proxies/envoy.mdx

* Update the documentation for consul-dataplane config options to include newly-supported environment variables.
* Correct the bundled Envoy version to 1.24 for consul-dataplane GA release
* Remove "beta" text around Consul Dataplane
* https://github.com/hashicorp/consul-dataplane/#configuration-reference

docs: Include env vars in consul-dataplane reference

---

.changelog/15253.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

Consul used to rely on implicit issuer selection when calling Vault endpoints to issue new CSRs. Vault 1.11+ changed that behavior, which caused Consul to check the wrong (previous) issuer when renewing its Intermediate CA. This patch allows Consul to explicitly set a default issuer when it detects that the response from Vault is 1.11+.
Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>
Co-authored-by: Chris S. Kim <ckim@hashicorp.com>

Detect Vault 1.11+ import, update default issuer (#15253)

---

website/content/docs/enterprise/admin-partitions.mdx

Update admin partitions with new Consul 1.14/Consul K8s 1.0 release. Remove references to clients in the doc, and re-name client cluster to non-default partition cluster running your workloads. 

docs: Update admin-partitions.mdx

---

.changelog/15423.txt
api/go.mod
api/go.sum
sdk/go.mod
sdk/go.sum
sdk/testutil/server.go

This change was necessary, because the configuration was always generated with a gRPC TLS port, which did not exist in Consul 1.13, and would result in the server failing to launch with an error.
This code checks the version of Consul and conditionally adds the gRPC TLS port, only if the version number is greater than or equal to 1.14.

Fix SDK to support older versions of Consul.

---

.changelog/15423.txt
api/go.sum
sdk/go.mod
sdk/go.sum
sdk/testutil/server.go

Manual backport of https://github.com/hashicorp/consul/pull/15423 due to gomod conflicts.

Fix SDK to support older versions of Consul. (#15423)

---

CHANGELOG.md
website/content/docs/upgrading/upgrade-specific.mdx

Add known-issue message to changelog.
When `consul connect envoy` is configured to utilize TLS for the HTTP API, it will also attempt to incorrectly utilize TLS for the outgoing gRPC connection.

Add Consul 1.14.0 known issue.

---

.changelog/_3556.txt

This PR adds a changelog entry for the snapshot agent updates that add support for using IAM roles to get AWS credentials to manage snapshots in S3.

Add changelog for snapshot agent updates

---

.changelog/15541.txt
agent/consul/client_test.go
agent/pool/pool.go
agent/setup.go

Fixes https://github.com/hashicorp/consul/issues/15246
Reverts a bug I introduced while refactoring:
https://github.com/hashicorp/consul/pull/14965/files#diff-8f12aa7f72e8647fddfac936ab541982aae517babd3064a581bbcdcc2595c2dcL347-R360
Note that Timeout included `rpcHoldTimeout` but I extracted it out of `Timeout` into `HasTimedOut`. But we still need to consider it when calculating `BlockingTimeout`.
It's hard to write a test for this due to timeouts being very timing + random jitter dependent. It should not break any existing tests and at most it adds 7s to existing timeouts.
The problem I'm trying to solve is:
```
/v1/catalog/services?wait=2s&index=16165
client uses BlockingTimeout to calculate read timeout
2s + 2s/16 = 2.125s
server adds max possible jitter
2s + 2s/16 = 2.125s
```
if …

Use rpcHoldTimeout to calculate blocking timeout

---

.github/workflows/backport-assistant.yml

This change upgrades `backport-assistant` to use the new GitHub Automerge feature. Instead of merging directly into release branches without running tests, this will leverage the GitHub feature to make sure all of the required tests pass before merging. This will hopefully stabilize failures we've been seeing when changes get backported with failures.
N/A

[OSS] chore(ci): update backport-assistant to use gh automerge

---

.changelog/15503.txt
agent/consul/leader_peering.go
agent/grpc-internal/client.go
website/content/docs/connect/cluster-peering/index.mdx

Increase the gRPC limit to 50MB in both peering grpc client and health rpc client
The rpcclient limit is also updated since the health streaming client needs to pull the service from the catalog.
```
2022-11-21T11:08:33.477-0500 [DEBUG] agent.http: Request finished: method=GET url="/v1/internal/ui/services?dc=dc3&index=26" from=127.0.0.1:51829 latency=5.240129042s
2022-11-21T11:08:33.502-0500 [DEBUG] agent.server.peering-syncer: stream disconnected due to 'resource exhausted' error; reconnecting: peer_id=f7e2b2a5-2453-de22-823f-69d898971567 peer_name=acceptor error="unexpected error receiving from the stream: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5245223 vs. 4194304)"
2022-11-21T11:32:45.270-0500 [ERROR] agent.rpcclient.health: subscribe call …
```

fix(peering): increase the gRPC limit to 8MB

---

website/content/docs/connect/dataplane/index.mdx
website/content/docs/k8s/architecture.mdx

docs: Fix language to describe clients previously ran on each node

---

website/content/docs/connect/proxies/envoy.mdx

The current description doesn't give the Kind of config entry to set default configuration options for the envoy proxy of a service, which should be `service-defaults`. Also it misses `max_inbound_connections` as the available fields of service-defaults.
This PR adds the following:
- Specify using the service config entry to configure service's envoy proxy
- add missing fields in proxy.config

docs: clarify envoy proxy configuration

---

.changelog/15610.txt
agent/consul/acl_server.go

Currently the server management token is only being bootstrapped in the primary datacenter. That means that servers on the secondary datacenter will never have this token available, and would log this line any time a token is resolved.
Bootstrapping the token in secondary datacenters will be done in a follow-up.

Remove log line about server mgmt token init

---

.changelog/15615.txt
agent/grpc-external/services/peerstream/subscription_manager.go
agent/grpc-external/services/peerstream/subscription_manager_test.go

During peer stream replication we flatten checks from the source cluster and build one thin overall check to hide the irrelevant details from the consuming cluster. This flattening logic did correctly flip to non-passing if there were any non-passing checks, but WHICH status it got during that was random (warn/error).
Also it didn't represent "maintenance" operations. There is an `api` package call [`AggregatedStatus`](https://github.com/hashicorp/consul/blob/api/v1.17.0/api/health.go#L183) which more correctly flattened check statuses.
This PR replicated the more complete logic into the peer stream package.

peering: better represent non-passing states during peer check flattening

---

.changelog/15555.txt
ui/packages/consul-peerings/app/components/consul/peer/form/generate/fieldsets/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/generate/fieldsets/index.js
ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/index.hbs
ui/packages/consul-ui/app/models/peer.js
ui/packages/consul-ui/app/services/repository/peer.js
ui/packages/consul-ui/tests/acceptance/dc/peers/create.feature
ui/packages/consul-ui/translations/common/en-us.yaml
ui/packages/consul-ui/translations/components/consul/en-us.yaml

To support HCP Cluster Peering, an additional text input needs to be added to the Create Peering modal for fallback server addresses.
To test against a real API you can do the following:
- Checkout this branch
- Run `make ui-docker`. This will take an eternity.
- Run `make dev-docker`
- Clone https://github.com/WenInCode/consul-setup
- go to `consul-setup/setups/peering`
- `yarn`
- `docker-compose up`
- once the docker container is up and running, run `yarn setup:peerings`
- Go to `https://localhost:8501/ui`
- Go to the peers page and create a new peering token to test out adding fallback addresses. 
- You can observe the parameter being sent over in the network tab.
- [CC-3848](https://hashicorp.atlassian.net/browse/CC-3848)
- [Design](https://www.figma.com/file/nEhxeDU1hm5eqEPcU4Y1QT/Clu …

ui: Add ServerExternalAddresses to peer token create form

---

agent/config/config.go
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
test/integration/consul-container/libs/agent/agent.go
test/integration/consul-container/libs/agent/builder.go
test/integration/consul-container/libs/agent/container.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/upgrade/fullstopupgrade_test.go
test/integration/consul-container/test/upgrade/healthcheck_test.go

This PR adds an upgrade test case to the integration test suite. This particular test case verifies consul can be upgraded from the snapshot of an supported version, i.e., _n-1_ and _n-2_.
- The snapshot includes service mesh
- The test case is `func TestStandardUpgradeToTarget_fromLatest(t *testing.T)`
This upgrade test can catch the data incompatibility type of upgrade bug, such as  https://github.com/hashicorp/consul/pull/14149
- [Link](https://github.com/hashicorp/consul/pull/15595/files#diff-fe79f36c4f2afab65044e1713c85af4d00f8d8d9bc6b18d85b5ec8187e72a142R28-R32) to the test case in `TestStandardUpgradeToTarget_fromLatest`

integ-test: test consul upgrade from the snapshot of a running cluster

---

go.mod

Removes unused `replace` directive, groups the consul sub-modules into one block, and adds an `exclude` directive for msgpack

clean up go.mod

---

.changelog/15274.txt
api/agent_test.go
api/api.go

Closing  #14466 
* I used the script below ( similar to the script in the Github Issue with minor  bash syntax changes )
* I did some local testings and found out the main reason was this block of code and the way `config` class is merged and loaded twice
https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/api/api.go#L740-L755
* The value of `config.Token` in this [function](https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/api/api.go#L653) can contain either the CLI provided or the Environment Variable due to the [merge](https://github.com/hashicorp/consul/blob/25d272a67ab560d495575defaa311fbde9d7ab81/command/flags/http.go#L150) function. Similarly, the same issue happens with `config.TokenFile` value. Hence, we need to check …

Fixing CLI ACL token processing unexpected precedence

---

website/content/api-docs/catalog.mdx

The docs for [/catalog/services](https://developer.hashicorp.com/consul/api-docs/catalog#list-services) lists the agent caching type as `simple` but I think should actually be `background refresh`.
- [cachetype.CatalogListServices](https://github.com/hashicorp/consul/blob/58c8a10b98d125531f9ca3b677eeb95f816382b9/agent/cache-types/catalog_list_services.go#LL15) …

docs: fix agent catalog-services caching method

---

website/content/api-docs/connect/ca.mdx
website/content/commands/connect/ca.mdx
website/content/docs/connect/ca/vault.mdx

After this PR is merged, the associated tutorials that include Vault policies for use with the Vault as a Connect CA provider must be updated as well.
[Preview link to the Vault policies changes](https://consul-n4pht8hnd-hashicorp.vercel.app/consul/docs/connect/ca/vault#vault-acl-policies)

docs: clarify Vault CA provider permissions needed

---

website/content/docs/k8s/architecture.mdx

The `/index` appears to result in a 404.
Removing the `/index` in the URL results in the correct path loading.
- [Consul on Kubernetes: Architecture](https://developer.hashicorp.com/consul/docs/k8s/architecture)

Fix broken link to Consul Dataplane index

---

agent/consul/acl.go

UX improvement for operators to help identify when they use a token meant for another datacenter.

Add warn log when all ACL policies are filtered out

---

website/content/docs/connect/dataplane/index.mdx

Per [discussion on Slack](https://hashicorp.slack.com/archives/C02GG0RFPQC/p1669851806650559), this PR updates the section on performance for Consul Dataplane.
In particular, these edits add specificity around the internal testing results and explicitly state that dataplanes use fewer resources in small deployments.

docs: Agentless performance clarifications

---

website/content/docs/k8s/helm.mdx

Updating the helm docs to capture some cleanups of wording for helm and to add the `cni.namespace` helm stanza to the docs.
The CNI Namespace PR https://github.com/hashicorp/consul-k8s/pull/1756

Update consul-k8s docs based on the consul-k8s release/1.0.x branch

---

.changelog/15661.txt
.circleci/config.yml
agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

The fix outlined and merged in https://github.com/hashicorp/consul/pull/15253 fixed the issue as it occurs in the primary DC. There is a similar issue that arises when vault is used as the Connect CA in a secondary datacenter that is fixed by this PR.
Additionally: this PR adds support to run the existing suite of vault related integration tests against the last 4 versions of vualt (1.9, 1.10, 1.11, 1.12)

Detect Vault 1.11+ import in secondary datacenters and update default issuer

---

agent/connect/ca/testing.go

It turns out that by default the dev mode vault server will attempt to interact with the filesystem to store the provided root token. If multiple vault instances are running they'll all awkwardly share the filesystem and if timing results in one server stopping while another one is starting then the starting one will error with:
Error initializing Dev mode: rename /home/circleci/.vault-token.tmp /home/circleci/.vault-token: no such file or directory
This change uses `-dev-no-store-token` to bypass that source of flakes. Also the stdout/stderr from the vault process is included if the test fails.
The introduction of more `t.Parallel` use in https://github.com/hashicorp/consul/pull/15669 increased the likelihood of this failure, but any of the tests with multiple vaults in use (or running …

connect: use -dev-no-store-token for test vaults to reduce source of flakes

---

agent/consul/multilimiter/multilimiter.go
agent/consul/multilimiter/multilimiter_test.go

This is an alternative to #15642 
Use a go buffered go routine to accumulate Limiters in a transaction and write them to the immutable-radix-tree every 10Ms.
``` bash
❯ go test -bench=BenchmarkTestRateLimiterAllowC -count 5 -benchtime=1s  -timeout 6000s -run=XXX ./agent/consul/multilimiter
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/consul/agent/consul/multilimiter
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
AC/no_prefill-16         	  556688	      2060 ns/op
AC/no_prefill-16         	  672924	      1964 ns/op
AC/no_prefill-16         	  627190	      1932 ns/op
AC/no_prefill-16         	  615247	      1952 ns/op
AC/no_prefill-16         	  661696	      1907 ns/op
AC/prefill_with_1K_keys-16         	  727677	      1894 ns/op
AC/prefill_with_1K_keys-16         	  611496 …
```

use a separate go routine to write limiters

---

website/content/docs/connect/config-entries/index.mdx
website/content/docs/k8s/installation/install.mdx

- Remove enterprise from exportedServices config entry list entry
- Alter CNI namespace config to say for installed namespace. 

docs: Small docs updates, peering and K8s CNI

---

.changelog/15690.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go
agent/xds/endpoints.go

Prior to this patch, discovery chains with peer-targets would not properly honor the mesh gateway mode for two reasons.
1. An incorrect target upstream ID was used to lookup the mesh gateway mode. To fix this, the parent upstream uid is now used instead of the discovery-chain-target-uid to find the intended mesh gateway mode.
2. The watch for local mesh gateways was never initialized for discovery chains. To fix this, the discovery chains are now scanned, and a local GW watch is spawned if: the mesh gateway mode is local and the target is a peering connection.

Fix local mesh gateway with peering discovery chains.

---

.changelog/15705.txt
.circleci/config.yml
.github/workflows/build.yml

This upgrade go version to `go1.19.4`

update go version to 1.19.4

---

website/data/docs-nav-data.json

This PR adds a link to the admin partitions documentation in the Kubernetes > Service Mesh chapter. The purpose is to make navigation to the AP docs easier for users who are already aware that AP is primarily a feature for K8s.

added link to admin partitions under K8s SM

---

agent/xds/routes.go
test/integration/connect/envoy/case-cfg-resolver-cluster-peering-failover/primary/verify.bats
test/integration/connect/envoy/case-cfg-splitter-cluster-peering/primary/verify.bats
test/integration/connect/envoy/case-cfg-splitter-peering-ingress-gateways/primary/verify.bats
test/integration/connect/envoy/case-cross-peer-control-plane-mgw/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-http-router/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-http/primary/verify.bats
test/integration/connect/envoy/case-cross-peers-resolver-redirect-tcp/primary/verify.bats
test/integration/connect/envoy/case-cross-peers/primary/verify.bats
test/integration/connect/envoy/case-ingress-gateway-peering-failover/primary/verify.bats
test/integration/connect/envoy/helpers.bash

This PR adds additional steps to the flaky test case (_case-cfg-splitter-peering-ingress-gateways_) to help troubleshoot an failed run.
The two added assertions:
1. Verify the peering state is _ACTIVE_ and retry peering
2. Read the peering to make sure service is imported
**Analysis**
This flaky test failed at 
```
not ok 7 s1 alpha proxies should be healthy in primary
not ok 8 s2 alpha proxies should be healthy in primary
```
This PR reveals that the peering state is _PENDING_, even after retry:
```
not ok 6 peer the two clusters together
not ok 7 s1, s2 alpha proxies should be imported to primary
```
Log from alpha the dialing cluster:
```
2022-12-07T06:02:18.353Z [TRACE] agent: [core][Channel #1009] Resolver state updated: {
"Addresses": [
{
"Addr": "172.28.0.2:8503",
"ServerName": "", …
```

Flakiness test: case-cfg-splitter-peering-ingress-gateways

---

.changelog/15710.txt
agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/server.go
agent/xds/xds_protocol_helpers_test.go
test/integration/connect/envoy/case-mesh-to-lambda/serverless.hcl
website/content/docs/agent/config/config-files.mdx
website/content/docs/lambda/registration/index.mdx
website/content/docs/upgrading/upgrade-specific.mdx

We are moving Lambda support to an Envoy extension so this flag is no longer needed.

Remove the `connect.enable_serverless_plugin` agent configuration option

---

website/content/docs/enterprise/index.mdx
website/content/docs/enterprise/license/faq.mdx

The license form is no longer available so this recommends contacting a support representative instead.

Remove mention of enterprise license form

---

.changelog/15769.txt
agent/agent.go

For both the key and cert file watcher code, a call to `a.configFileWatcher.Replace()` is made but the error returned from this called is not used...but a check is right below it like this:
```
a.configFileWatcher.Replace(f.oldCfg.KeyFile, f.newCfg.KeyFile)
if err != nil {
return err
}
```
This seems to be an omission rather than strategic.  In its current case, this will either check on a previous error, or will never get triggered because a previous check would have exited.

agent: Fix assignment of error when auto-reloading cert and key file changes.

---

.github/workflows/changelog-checker.yml

Currently the changelog checker workflow doesn't account for enterprise-only changelog entries where we prefix the filename with an underscore, because there's no public PR to link to.
This PR updates how we check for the existence of a changelog entry by considering a `_` prefix as valid in enterprise. 
Note that this only helps the check pass in enterprise. The changelog checker workflow will still fail in OSS when it encounters a changelog entry for an enterprise-only PR because the number of the file won't match the OSS PR number. 
* Tested manually with and without an underscore in enterprise

Update changelog checker to handle ent-only entry

---

.changelog/15760.txt
agent/consul/discoverychain/compile.go
agent/consul/discoverychain/compile_test.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go
agent/structs/discovery_chain.go

The `DialedDirectly` configuration on upstreams is ignored by Consul Dataplane, because it selects data through the streaming backend which does not support the `MergeCentralConfig` flag. This means that any service-defaults or proxy-defaults configurations on upstreams were ignored.
This PR adds the `DialedDirectly` config into the compiled discovery chain targets, so that the "merged" version is available to the proxy config.
This PR also fixes an existing issue where passthrough clusters were not properly cleaned up whenever the `DialedDirectly` field is toggled on and off during runtime.

Fix DialedDirectly configuration for Consul dataplane.

---

agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/structs/connect_proxy_config.go
api/config_entry.go
api/config_entry_test.go

This PR is for Consul API changes to enable access logging.
Eventually, the `AcessLogsConfig` struct will make it into [`ConnectProxyConfig`](https://github.com/hashicorp/consul/blob/a0dd8335c069b95d69d6845855552a84a240b1ae/agent/structs/connect_proxy_config.go#L199-L248) in a follow-on story that plumb this configuration into the listener generation.
* Unit tests included

feat: add access logging API to proxy defaults

---

Dockerfile

ubi9 already has curl-minimal installed. Attempting to install curl results in a microdnf conflict and errors out.
Fixes https://github.com/hashicorp/consul-enterprise/actions/runs/3705700950/jobs/6280228266

Fix curl vs curl-minimal install conflict in ubi9 image

---

Dockerfile

Removing curl inadvertently dropped the transitive dependency on shadow-utils which is required for teh groupadd executable. Since curl-minimal does not have this dependency, make it explicit as part of the `microdnf install`.
Fixes issue introduced in [PR #15808](https://github.com/hashicorp/consul/pull/15808)

Force installation of shadow-utils for access to groupadd exe

---

.github/workflows/jira-pr.yaml

Fix for following error, should be `GH Issue`
```
2022/12/15 18:55:33 API call GET /rest/api/3/search failed (400): {"errorMessages":["The value 'Github Issue' does not exist for the field 'issuetype'."],"warningMessages":[]}
```
Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL …

JIRA: Small fix to search plugin for JIRA issues

---

api/config_entry.go
api/config_entry_test.go

This is another alternative to fix the upgrade test by changing the AccessLog to pointer in `ProxyConfigEntry` so that empty struct will be parsed as nil by json. Since this is a new field, any old version of Consul can't parse the field.
Please refer to #15830, #15827

tests: change AccessLogsConfig field to pointer so it will be parsed as nil

---

.changelog/15701.txt
agent/grpc-internal/balancer/balancer.go
agent/grpc-internal/balancer/custombalancer.go
agent/grpc-internal/balancer/pickfirst.go
agent/grpc-internal/client.go
agent/grpc-internal/resolver/resolver.go

Fixes https://github.com/hashicorp/consul/issues/10603
Remove the need to call `UpdateState` twice by changing the `pick_first` balancer's behavior to close existing connections (almost) every time.
No net-new behavior; existing test `TestClientConnPool_IntegrationWithGRPCResolver_Rebalance` is still passing.
Manually tested with frequent rebalancing

Add custom balancer to always remove subConns

---

agent/grpc-internal/balancer/custombalancer.go

Small followup to https://github.com/hashicorp/consul/pull/15701

grpc custom balancer - UpdateClientConnState Break - instead of returning early

---

.github/workflows/jira-pr.yaml

Currently an error when community PRs are filed pop up due to the default Workstream custom field not being populated. 

JIRA: Add Service Mesh work stream to JIRA API call

---

.changelog/15833.txt
agent/consul/discoverychain/compile.go
agent/consul/discoverychain/compile_test.go

The following message is incorrectly printed out whenever saving a service-resolver with a peer failover target.
`discovery chain "my-chain" uses inconsistent protocols; service "my-service" has "tcp" which is not "http"`
This PR excludes peer targets from the protocol validation logic when building discovery chains, which should prevent the error from occurring.
Steps to reproduce:
1. Set up a service-defaults with “http” protocol on a service “mylocal”
2. Set up a peering connection and import a remote service “myremote” (this remote's protocol shouldn't matter to reproduce the issue)
3. Attempt to save a resolver for “mylocal” that has a failover to “myremote” configured.
Be careful to ensure that no "myremote" service-default exists in the local cluster, as it will actually be looked …

Fix incorrect protocol check on discovery chains with peer targets.

---

.changelog/15818.txt
agent/xds/envoy_versioning.go
agent/xds/envoy_versioning_test.go
agent/xds/proxysupport/proxysupport.go
agent/xds/proxysupport/proxysupport_test.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/exec.go
command/connect/envoy/exec_test.go
website/content/commands/connect/envoy.mdx

Note: **docs team see last commit for docs change**
This PR introduces an enhancement to enable users to detect incompatible versions of Envoy early. This PR was motivated by issue [#13131](https://github.com/hashicorp/consul/issues/13131).
With the addition of these code changes, when using the `consul connect envoy` command the version of envoy being connected to is compared against the supported versions coded into the Consul binary. If the version of Envoy is deemed to be incompatible, then an error will be logged and the service will exit. 
Since this is a potentially breaking change, and there may be reasons that a user is using a version of Consul that we don't recognize as compatible (such as custom builds of Envoy), a flag has also been added to disable the check: …

Enhancement: Consul Compatibility Checking

---

GNUmakefile

You can't do multi-platform builds with the default docker driver now. This seems like new behavior, but regardless, this upserts a new build context for consul builds to make the multi-platform image.

chore: fix remote docker make target

---

.changelog/15866.txt
agent/cache/watch.go
agent/cache/watch_test.go

This change fixes a situation where the protobuf private fields would be read by reflect.DeepEqual() and indicate data was modified. This resulted in change notifications being fired every time, which could cause performance problems in proxycfg.

Fix agent cache incorrectly notifying unchanged protobufs.

---

.changelog/15865.txt
agent/proxycfg/snapshot.go
agent/proxycfg/upstreams.go
agent/xds/clusters.go
agent/xds/listeners.go

Sometimes when envoy was configured to do failovers to peered clusters, the SNI / SAN information was missing from the xDS configuration, which means that it was impossible to connect to the mesh gateway correctly.
This issue occurs because the incorrect partition / datacenter was used when creating watches from upstream targets. The datacenter / partition from discovery-chain peer-targets should NOT be used to perform lookups, since the fields are intentionally cleared during compilation (disco chain target fields indicate the destination's data, not the source's data).
Instead, the local datacenter / partition should be provided to the query so that it can properly lookup services.

Fix issue with incorrect proxycfg watch on upstream peer-targets.

---

.changelog/15346.txt
agent/grpc-external/services/connectca/sign_test.go
agent/grpc-external/services/connectca/watch_roots.go
agent/grpc-external/services/connectca/watch_roots_test.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
agent/grpc-external/services/dataplane/get_supported_features.go
agent/grpc-external/services/dataplane/get_supported_features_test.go
agent/grpc-external/services/serverdiscovery/watch_servers.go
agent/grpc-external/services/serverdiscovery/watch_servers_test.go
agent/grpc-external/testutils/acl.go
agent/grpc-external/utils.go

Previously, these endpoints required `service:write` permission on _any_ service as a sort of proxy for "is the caller allowed to participate in the mesh?".
Now, they're called as part of the process of establishing a server connection by any consumer of the [consul-server-connection-manager library](https://github.com/hashicorp/consul-server-connection-manager), which will include non-mesh workloads (e.g. Consul KV as a storage backend for Vault) as well as ancillary components such as consul-k8s' acl-init process, which likely won't have `service:write` permission.
So this commit relaxes those requirements to accept *any* valid ACL token on the following gRPC endpoints:
- `hashicorp.consul.dataplane.DataplaneService/GetSupportedDataplaneFeatures`
- …

grpc/acl: relax permissions required for "core" endpoints

---

.changelog/15107.txt
agent/config/builder.go
agent/config/builder_test.go

This should clear up a little confusion over error messages:
```bash
$ consul -version
Consul v1.13.3
Build Date 1970-01-01T00:00:01Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
$ cat > config.js # generate basic config
{"data_dir": "/tmp"}
```
```bash
$ consul validate config.js # confusing error message: "I thought I set that?"
Config validation failed: data_dir cannot be empty
```
```bash
$ go run . validate config.js # after this PR: "ah, I need to set config format"
Config validation failed: file config.js has unknown extension; must be .hcl or .json, or config format must be set
exit status 1
$ go run . validate -config-format=json config.js
Configuration is valid!
```
Unlike in the config directory …

fix: return error when config file with unknown extension is passed

---

internal/tools/protoc-gen-consul-rate-limit/postprocess/main.go

Fixes bug in #15564 where gofmt would strip out the generated code warning comment because it was on the same line as the build tag.

Fix missing comment in generated enterprise rate-limit file

---

agent/grpc-external/services/connectca/sign_test.go
agent/grpc-external/services/dataplane/get_supported_features_test.go
agent/grpc-external/testutils/acl.go
agent/grpc-external/utils.go

Fixes a bug introduced by #15346 where we'd always require an ACL token even if ACLs were disabled because we were erroneously treating `nil` identity as anonymous.

grpc/acl: fix bug where ACL token was required even if disabled

---

agent/checks/check_test.go

On macOS, we get a different error message for an untrusted TLS certificate which causes a couple of check tests cases to fail. This fixes the assertion so that these tests pass on macOS.
```
go test ./agent/checks -run TLS_BadVerify
```

Fix TLS_BadVerify test assertions on macOS

---

website/content/docs/k8s/connect/ingress-controllers.mdx

Update example link for Consul K8s NGINX ingress controller. New link is: https://github.com/hashicorp-education/consul-k8s-nginx-ingress-controller

Update example link for Consul K8s NGINX ingress controller

---

website/content/api-docs/acl/tokens.mdx

Make consistent with other heading levels on the page. (Also makes the sidebar nav better by removing content that's at the wrong level.)

docs: fix markdown heading levels

---

GNUmakefile
build-support/scripts/protobuf.sh

Manual backport of #15920. Instead of using the newer version of protoc-gen-go-binary I just pinned this to the version we happened to be using.

Pin to specific version of protoc-gen-go-binary

---

.changelog/15913.txt
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden

When using `consul connect envoy`, TLS configuration was not applied to local unix sockets, even when flags were specified that provided certificates.
Notably, this affects Nomad deployments, which rely on unix sockets + encryption for certain configurations.
https://github.com/hashicorp/nomad/issues/15360
Before this change, the only way TLS was enabled was if `https://` was a prefix for the `-grpc-addr` flag. This allowed users to configure the certificates via environment variables / flags on clients and slowly adopt grpc+tls over time (the `-grpc-addr` value is also discoverable via an API call to `/v1/agent/self`, but the certificate is not).
After this change, TLS will be enabled only if either of the following are true:
* `-grpc-addr` starts with `https://`
* `-grpc-addr` starts …

Fix issue where TLS configuration was ignored for unix sockets in consul connect envoy.

---

command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/access-logs-enabled-custom.golden
command/connect/envoy/testdata/access-logs-enabled.golden

This adopts the new access logging format from `proxy-defaults` for the Envoy admin interface. It also deprecates the command line argument for this setting, which is [deprecated in Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-msg-config-bootstrap-v3-admin).
* Golden files are included. There are also more golden files in the xds package tests.

[OSS] feat: add access log config to consul envoy connect

---

.changelog/15828.txt
agent/acl_test.go
agent/agent.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/config/builder.go
agent/config/config.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/local/state.go
agent/local/state_internal_test.go
agent/local/state_test.go
agent/proxycfg-glue/service_http_checks_test.go
agent/proxycfg-sources/catalog/config_source_test.go
agent/proxycfg-sources/local/sync_test.go
agent/token/persistence.go
agent/token/persistence_test.go
agent/token/store.go
agent/token/store_test.go
agent/user_event_test.go
api/agent.go
api/agent_test.go
command/acl/agenttokens/agent_tokens.go
website/content/api-docs/agent/index.mdx
website/content/commands/acl/set-agent-token.mdx
website/content/docs/agent/config/config-files.mdx

This adds a new agent token: `config_file_service_registration`. This token is used to register services and checks that are defined in local config files (including when defined in flags, such as with `-hcl`).
This adds:
* The config field `acl.tokens.config_file_service_registration`
* The `PUT /agent/token/config_file_service_registration` HTTP API request
* The `consul acl set-agent-token config_file_service_registration <token>` command
The precedence of tokens when registering a service from a service definition or a check from a check definition is:
1. **Inline service token**:  The token from the `token` field in the service/check definition is used, if set
2. **Config File Service Registration token**: otherwise, the config file registration token is used, if set
3. **Default …

Add new config_file_service_registration token

---

.changelog/15864.txt
website/content/commands/connect/envoy.mdx
website/content/docs/connect/config-entries/proxy-defaults.mdx
website/content/docs/connect/observability/access-logs.mdx
website/data/docs-nav-data.json

Docs supporting the new Access Logging feature for consul service mesh.
N/A
N/A

[OSS] docs(access logs): new docs for access logging

---

website/content/docs/connect/config-entries/terminating-gateway.mdx

When using SNI in Terminating Gateway, Consul configures envoy to have strict SAN matching. This requires all external services to have SANs in their certificates, and not having it will throw `CERTIFICATE_VERIFY_FAILED` error.
eg:
```
$ cat tg.hcl
Kind = "terminating-gateway"
Name = "terminating-gateway"
Services = [
{
Name = "counting"
CAfile = "/consul/consul-ca.pem"
SNI = "abc.example.com"
}
]
$ curl -s localhost:19000/config_dump | grep match_subject -A4
"match_subject_alt_names": [
{
"exact": "abc.example.com"
}
]
```
* https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-certificatevalidationcontext-match-typed-subject-alt-names

Update TG Docs with SAN match option when using SNI

---

website/content/docs/connect/config-entries/service-defaults.mdx

Prepends pre-devdot links with `/consul` on the service default configuration entry reference page to fix broken links.

fixes pre-devdot links in service defaults ref docs

---

test/integration/consul-container/libs/service/assets/Dockerfile-consul-envoy
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/gateway.go

Should fix issues with missing `consul:local` image used as the base for sidecars/gateways. This image is not available in ENT pipelines. Use the same image that was used to create the cluster.

[OSS] chore(ci): fix compat ent compat tests for sidecars and gateways

---

website/content/api-docs/operator/segment.mdx
website/content/docs/connect/connectivity-tasks.mdx
website/content/docs/connect/gateways/index.mdx
website/content/docs/connect/gateways/terminating-gateway.mdx
website/content/docs/discovery/services.mdx
website/content/docs/enterprise/network-segments/network-segments-overview.mdx
website/content/docs/integrate/partnerships.mdx
website/content/docs/lambda/registration/index.mdx

- Fixes a 4 `learn.hashicorp.com` links that had typos in them
- Updates some `learn.hashicorp.com` links that redirect to go to devdot paths
- Fixes a docs link that had an extra space in the `href` portion of the MDX syntax

[docs] Adjusting links for rewrite project

---

.changelog/16000.txt
agent/configentry/resolve.go
agent/configentry/resolve_test.go
agent/consul/config_endpoint_test.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/naming.go
agent/proxycfg/snapshot.go
agent/service_manager_test.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go

This PR fixes an issue where tproxy would not correctly use service-defaults and proxy-defaults for implicit upstreams. Normally, we handle this by taking configuration from an auto-generated wildcard `*` upstream, but that was not done in all cases -- notably peer upstreams.
The changes here are essentially:
1. Change the merging logic so that the wildcard upstream has correct proxy-defaults and service-defaults values combined into it. It did not previously merge all fields, and the wildcard upstream did not exist unless service-defaults existed (it ignored proxy-defaults, essentially).
2. Change the way we fetch upstream configuration in the xDS layer so that it falls back to the wildcard when no matching upstream is found. This is what allows implicit peer upstreams to have the …

Fix configuration merging for implicit tproxy upstreams.

---

agent/proxycfg-glue/config_entry.go

Adds switch statements for mapping config entry types to the pbsubscribe topics for each of the config entries added as part of Consul Native API Gateways.
* ~[ ] updated test coverage~
* ~[ ] not a security concern~

Add plumbing for Native API GW Subscriptions

---

test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/service/service.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go

This PR adds support to validate Envoy Listeners in Golang. This functionality already exists in bash, it has been refactored and the Envoy listener assertion has been added to the existing `BasicConnectService` test.

 Add envoy assertion in Golang

---

agent/consul/rate/handler.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/test/ratelimit/ratelimit_test.go

Adding in an integration test to assert that the following effects occur:
- error messages returned to clients
- trace logs when limits exceed
- warning logs when limits blocked
- metrics when limits exceeded
This is currently only for HTTP/ net-RPC.

Integration test for server rate limiting

---

.changelog/16000.txt
agent/configentry/resolve.go
agent/configentry/resolve_test.go
agent/consul/config_endpoint_test.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/naming.go
agent/proxycfg/snapshot.go
agent/service_manager_test.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go

Manual 1.14 backport of https://github.com/hashicorp/consul/pull/16000

Backport of Fix configuration merging for implicit tproxy upstreams

---

.changelog/16015.txt
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/envoy-readiness-probe.golden
website/content/commands/connect/envoy.mdx

- add flags `envoy-ready-bind-port` and `envoy-ready-bind-addr` on consul connect envoy to create a ready listener on that address.

Add support for envoy readiness flags

---

agent/configentry/resolve.go
agent/configentry/resolve_test.go
agent/consul/config_endpoint_test.go
agent/service_manager_test.go

This PR modifies behavior that was introduced in: https://github.com/hashicorp/consul/pull/16000
Only the mesh-gateway-mode and protocol should be inherited from proxy-defaults into upstreams. This PR modifies the merging logic to reflect that specific behavior.

Fix proxy-defaults incorrectly merging config on upstreams.

---

.changelog/16024.txt
agent/agent.go
agent/agent_endpoint.go
agent/agent_endpoint_oss.go

OSS split of ent [PR](https://github.com/hashicorp/consul-enterprise/pull/4100)
- load service in OSS -> ent (manually tested)
1. Register a service in oss client agent, e.g., C-1
1. Stop C-1
1. Replace C-1's binary with an ent binary 
1. Add non-partition to C-1's config file and join the cluster
1. The service should be loaded from C-1's on-disk service config 
- Agent endpoint
1. Start a client agent in non-default partition
1. register a service at the client agent without partition field in service definition
https://github.com/hashicorp/consul/issues/15881
https://github.com/hashicorp/consul/issues/15963

Apply agent partition to load services and agent api

---

.circleci/config.yml
GNUmakefile

The consul container tests orchestrate running containers from various versions of consul to test things like upgrades. Having the test framework itself depend on the consul codebase inherently links it to a specific version of consul which may make some test approaches in the future difficult.
This change prohibits any such relationship via a custom linting rule. Unfortunately because the `api`, `sdk`, and `test/integration/consul-container` packages are submodules of `github.com/hashicorp/consul` the `gomodguard` linter is incapable of handling those separately hence the need for some custom bash instead.

test: prevent the container tests from depending on consul

---

test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/service/service.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/observability/access_logs_test.go
test/integration/consul-container/test/observability/metrics_leader_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go

Adding an integration test for access logs. It does not comprehensively execute the API, but it does demonstrate a possible workflow.
* Use go test to run the integration test.

test(integration): add access logging test

---

website/content/docs/agent/config/index.mdx

Improvements:
- Alter wording to make it more obvious when reading quickly that this is a list of reloadable options, not a list of non-reloadable option
- Mention that auto-reload is possible and how to configure it

docs: clarify reloadable config option usage

---

website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/proxy-defaults.mdx
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/config-entries/service-resolver.mdx
website/content/docs/connect/config-entries/service-router.mdx
website/content/docs/connect/config-entries/service-splitter.mdx
website/content/docs/connect/config-entries/terminating-gateway.mdx

Where links in Markdown syntax are passed into `ConfigEntryReference` components, prefixes links to docs content with `/consul`.
In preparation for https://github.com/hashicorp/consul/pull/15976, because the link rewrite plugin cannot reach these links to update them automatically.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203750517664196

[docs] Updating MD links in ConfigEntryReference components

---

test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/cluster/network.go

If multiple container tests are run in parallel it is highly likely that one will randomly fail due to an inability to get a docker network for the test case. This change detects that scenario and sleep retries until it succeeds. Hopefully this means it will be safe to mark some tests as safe to run in parallel without flaking them out.

test: container tests wait for available networks

---

website/content/docs/connect/config-entries/service-defaults.mdx

The docs as-is imply that traffic goes from counting -> dashboard, when it actually goes from dashboard -> counting in all HashiCups examples.

docs: clarify service defaults example

---

.changelog/16009.txt
agent/acl_endpoint_test.go
agent/agent_endpoint_test.go
agent/coordinate_endpoint_test.go
agent/event_endpoint_test.go
agent/http.go
agent/prepared_query_endpoint_test.go
agent/snapshot_endpoint_test.go
website/content/api-docs/api-structure.mdx
website/content/docs/security/acl/acl-legacy.mdx
website/content/docs/security/acl/acl-policies.mdx
website/content/docs/upgrading/upgrade-specific.mdx

- Emit a warning log message every time the token query param is used 
- Update docs to reflect the deprecation of the token query param 
Makes progress on #11917. Remaining work: fully remove in a future release.
* Ran consul locally (make dev...)
* Tried a request with header
```
curl \
--header "X-Consul-Token: <my token>" \
"http://127.0.0.1:8500/v1/agent/members"
```
* Tried a request with token without the header
```
curl \
"http://127.0.0.1:8500/v1/agent/members?token=<my token>"
2023-01-18T15:37:36.989-0500 [WARN]  agent.http: This request is using a token query parameter; This is deprecated and will be removed in future Consul versions.: logUrl=/v1/agent/members?token=<hidden>
```
* Tried a request with token and the header present
```
curl \
--header "X-Consul-Token: <my token>" …
```

Warn when the token query param is used for auth

---

.circleci/config.yml
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/observability/metrics_leader_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
test/integration/consul-container/test/ratelimit/ratelimit_test.go
test/integration/consul-container/test/upgrade/fullstopupgrade_test.go
test/integration/consul-container/test/upgrade/healthcheck_test.go
test/integration/consul-container/test/upgrade/peers_http_test.go

Integration tests are taking ~12mins to complete, which is about double the other steps in the pipeline. Setting an arbitrary level of parallelism to p=4 cuts the time down to ~5min.
Builds off of #16045

test: run integration tests in parallel

---

agent/consul/server.go
agent/rpc/middleware/interceptors.go
agent/rpc/middleware/interceptors_test.go
agent/rpc/middleware/recovery.go

Add a panic handler that logs the error which is passed into the RPC rate limit interceptor (similar gRPC codepath)

feat: panic handler in rpc rate limit interceptor

---

test/integration/connect/envoy/case-badauthz/verify.bats
test/integration/connect/envoy/helpers.bash

The TestEnvoy/case-http-badauthz failed due to following error. Not sure what causes the error, so try increasing the retry times.
`agent.http: Request error: method=PUT url="/v1/connect/intentions/exact?source=s1&destination=s2" from=127.0.0.1:39148 error="Intentions are read only while being upgraded to config entries"
`
Failed test instance:
https://app.circleci.com/pipelines/github/hashicorp/consul/49943/workflows/a3c2a39d-f863-439d-849e-e8a74465685a/jobs/1145045/tests

flaky test: use retry long to wait for config entry upgrade

---

agent/proxycfg/testing_terminating_gateway.go
agent/xds/builtin_extension_oss_test.go
agent/xds/builtinextensions/lambda/lambda.go
agent/xds/builtinextensions/lambda/lambda_test.go
agent/xds/testdata/builtin_extension/listeners/lambda-connect-proxy-opposite-meta.latest.golden
agent/xds/testdata/builtin_extension/listeners/lambda-connect-proxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lambda-terminating-gateway-with-service-resolvers.latest.golden
agent/xds/testdata/builtin_extension/listeners/lambda-terminating-gateway.latest.golden
agent/xds/xdscommon/xdscommon_oss_test.go

This is a backport of Enterprise changes
* updated builtin extension to parse region directly from ARN
- added a unit test
- added some comments/light refactoring
* updated golden files with proper ARNs
- ARNs need to be right format now that they are being processed
* updated tests and integration tests
- removed 'region' from all EnvoyExtension arguments
- added properly formatted ARN which includes the same region found in the removed "Region" field: 'us-east-1'
* [n/a] external facing docs updated

Mw/lambda envoy extension parse region (#4107)

---

test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/test/upgrade/peers_http_test.go

oss split of ent [PR](https://github.com/hashicorp/consul-enterprise/pull/4195)

Upgrade test: retain sidecar containers during upgrade.

---

command/tls/ca/create/tls_ca_create.go
command/tls/ca/tls_ca.go
command/tls/cert/tls_cert.go
website/content/commands/tls/ca.mdx

Small PR to clarify some documentation around `consul tls` commands.

Update docs for tls commands

---

agent/envoyextensions/extensioncommon/basic_envoy_extender.go
test/integration/connect/envoy/case-lua/setup.sh
test/integration/connect/envoy/case-lua/verify.bats

This is to prevent any potential bug from any extension 
(1) may add filter twice, e.g., the Patch method of an extension both return some error and `ok = false`. In this case, filter will be added twice.
(2) doesn't change the filter and will result in err == nil and ok == false. In this case, original filter should be added back to the filter chain

improvement: prevent filter being added twice from any enovy extension

---

agent/xds/delta.go
agent/xds/delta_test.go

This PR adds metrics for Envoy extensions to track how long it takes for each of three steps to execute:
- validate_arguments (constructing the extension)
- validate (performing runtime validation)
- extend (executing the extension)
Each one of these metrics also includes some metadata as labels to better identify the service affected.

Add Envoy extension metrics.

---

.changelog/15988.txt
command/connect/envoy/envoy.go
website/content/commands/connect/envoy.mdx
website/content/docs/connect/proxies/envoy.mdx

This PR adds a flag, `-enable-config-gen-logging`, to the `connect envoy` command to display some log messages when generating the bootstrap config. It can be hard to troubleshoot slowness that happens during the multiple api requests during this command due to the current lack of logs, so this flag enables outputting some messages (on stderr) to help with that.

Add a flag for enabling debug logs to the `connect envoy` command

---

agent/consul/discoverychain/gateway.go
agent/consul/discoverychain/gateway_httproute.go
agent/consul/discoverychain/gateway_tcproute.go
agent/proxycfg/proxycfg.deepcopy.go
agent/proxycfg/snapshot.go
agent/proxycfg/snapshot_test.go
agent/structs/config_entry_routes.go
agent/structs/structs.deepcopy.go

Moves most of the route translation to the discoverychain package and adds the logic for merging in other discovery chains to the one we synthesize for a listener's routes.

Discovery Chain Merging/Synthesizing for HTTP/TCPRoutes

---

.changelog/16097.txt
agent/local/state.go
agent/local/state_test.go

The changes agent anti-entropy syncs to only use agent token for deregistration of services and checks.
The previous behavior had the agent attempt to use the "service" token (i.e. from the `token` field in a service definition file) and if that was not set, then it would use the agent token.
The previous behavior was problematic because, if the service token had been deleted, the deregistration request would fail. The agent would retry the deregistration during each anti-entropy sync, and the situation would never resolve.
The new behavior is to only/always use the agent token to service/check deregistration during anti-entropy. This is:
* Simpler: No fallback logic to try different tokens
* Faster (slightly): No time spent attempting the service token
* Correct: The agent token is able …

Use agent token for service/check deregistration during anti-entropy

---

test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/libs/utils/version.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/observability/access_logs_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/traffic_management_test.go

Create upgrade tests that validates traffic management in Consul. Several traffic management tests exists in `.bats`. This initial PR implements the basic health, certs and instance tests before validating traffic after a cluster upgrade.

NET-2087: Create basic upgrade test skeleton for traffic management

---

website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Docs for ##15956. Upstream overrides will require the `peer` field to work for peered services in 1.16.

docs(service-defaults): upstream overrides for peered services

---

agent/connect/ca/provider_vault_test.go

Test overwrote the stopWatcher() function variable for the test without keeping and calling the original value. The original value is the function that stops the goroutine... so it needs to be called.

fix goroutine leak in renew testing

---

command/connect/envoy/envoy.go

Follow up to (https://github.com/hashicorp/consul/pull/15988). Caught this when backporting - the logger is getting set up in the wrong place (before flags are parsed) so it won't get set to debug properly when the flag is passed in.

command: Fix logger not initializing properly in envoy command

---

GNUmakefile

I just ran into this when running `deep-copy` for the first time. While it didn't take me too long to figure out, I did spend a minute figuring out what what wrong when the error I got was originally a bit esoteric (raised from the `./agent/structs/deep-copy.sh` script).
I thought I would save future devs the moments of confusion with a helpful error.
Have `deep-copy` not installed (`rm $(which deep-copy)` works) then run `make deep-copy`.
You will get the error `deep-copy not found. Please run 'make codegen-tools' to install it.`
* ~[ ] updated test coverage~
* ~[ ] not a security concern~

Set `codegen-tools` to be a dependency of `deep-copy`

---

website/content/docs/connect/config-entries/service-router.mdx

Fixes https://github.com/hashicorp/consul/issues/11816 and fixes https://github.com/hashicorp/consul/issues/8516. See those issues for more details but tl;dr: envoy defaults num_retries to 1 and so if any other retry configs are set, then you'll get 1 retry. If you try setting our NumRetries to 0 we treat it as the zero value (because our struct doesn't have a pointer for that field) and so we leave it unset in the Envoy config which then results in it defaulting to 1.

Document how numRetries can't be set to 0

---

website/content/docs/k8s/deployment-configurations/vault/data-integration/server-tls.mdx

The generate_lease=true configuration is unnecessary and generates a note about performance implications in Vault logs. Remove this configuration so that the default value of generate_lease=false is used instead.
Follow-up to https://github.com/hashicorp/consul-k8s/pull/1877

docs: refine server TLS Vault PKI role config

---

test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/test/upgrade/peer_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peers_http_test.go
test/integration/consul-container/test/upgrade/traffic_management_default_subset_test.go

Updated the `Reset()` method to restart connect-proxy sidecar during upgrade. 
Added the Reset() method to all upgrade tests

NET-2087: Restart proxy sidecar during cluster upgrade

---

website/content/docs/connect/config-entries/service-resolver.mdx

When timeunit is not provided in `service-resolver.ConnectTimeout`, the default to be used in nanosecond.
* Use a config entry without time unit
```
{
"Kind":"service-resolver",
"Name":"REDACTED",
"ConnectTimeout":10, 
"Failover":{
"*":{
"Datacenters":["us-east-1","us-west-2"]
}
}
}
```
```bash
consul config write resolver.json
consul config read -kind service-resolver -name REDACTED  
{
"ConnectTimeout": "10ns",
"Kind": "service-resolver",
"Name": "REDACTED",
"Failover": {
"*": {
"Datacenters": [
"us-east-1",
"us-west-2"
]
}
},
"CreateIndex": 23,
"ModifyIndex": 137
}
```
https://github.com/hashicorp/consul/issues/16147

docs(service-resolver): clarify the default time unit in service-resolver.ConnectTimeout

---

agent/consul/client.go
agent/consul/rpc.go
agent/consul/rpc_test.go
lib/cluster.go
lib/cluster_test.go

This is a remake of #16146 
> The retries were too aggressive which compounded rate limiting errors. Hence, implementing an exponential back-off strategy which gives enough time for the server to recover.

Net 2229/rpc reduce max retries 2

---

ui/packages/consul-ui/app/abilities/token.js
ui/packages/consul-ui/app/models/token.js
ui/packages/consul-ui/tests/integration/helpers/token/is-legacy-test.js
ui/packages/consul-ui/tests/unit/helpers/token/is-legacy-test.js

Revert ui changes from https://github.com/hashicorp/consul/pull/15922
I had the idea that it might be helpful to remove some no-longer functional legacy acl code from the ui in https://github.com/hashicorp/consul/pull/15922
But this was unwise, and I should not have touched it without fully understanding their tests.

revert UI acl changes from #15922

---

agent/acl_test.go
agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/acl_test.go
agent/consul/connect_ca_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/snapshot_endpoint.go
agent/consul/txn_endpoint.go
agent/xds/server.go

https://github.com/hashicorp/consul/pull/16044 renamed a field in the xds server protocol struct (https://github.com/hashicorp/consul/pull/16044/files#diff-83eb78d94a07420323d5e88be3bc61881c2f6d5724b74a291e9a77a4c5e07995L108) that could cause version compatibility issues during an upgrade. Revert this rename.

revert method name change in xds server protocol for version compatibility

---

agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

We upgraded Vault API module version to a version that has built-in retry logic. So this code is no longer necessary.
Fixes #12613

remove redundant vault api retry logic

---

agent/envoyextensions/builtin/http/localratelimit/copied.go
agent/envoyextensions/builtin/http/localratelimit/ratelimit.go
agent/envoyextensions/builtin/http/localratelimit/ratelimit_test.go
agent/envoyextensions/registered_extensions.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/testdata/builtin_extension/clusters/http-local-ratelimit-applyto-filter.latest.golden
agent/xds/testdata/builtin_extension/endpoints/http-local-ratelimit-applyto-filter.latest.golden
agent/xds/testdata/builtin_extension/listeners/http-local-ratelimit-applyto-filter.latest.golden
agent/xds/testdata/builtin_extension/routes/http-local-ratelimit-applyto-filter.latest.golden
api/config_entry.go
go.mod
test/integration/connect/envoy/case-envoyext-ratelimit/capture.sh
test/integration/connect/envoy/case-envoyext-ratelimit/service_s1.hcl
test/integration/connect/envoy/case-envoyext-ratelimit/service_s2.hcl
test/integration/connect/envoy/case-envoyext-ratelimit/setup.sh
test/integration/connect/envoy/case-envoyext-ratelimit/vars.sh
test/integration/connect/envoy/case-envoyext-ratelimit/verify.bats

OSS split of ent [PR](https://github.com/hashicorp/consul-enterprise/pull/4206)

feat: envoy extension - http local rate limit

---

.changelog/16205.txt
agent/catalog_endpoint.go
agent/consul/operator_usage_endpoint.go
agent/consul/state/usage.go
agent/consul/state/usage_oss.go
agent/consul/state/usage_test.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/consul/xdscapacity/capacity.go
agent/http_register.go
agent/operator_endpoint.go
agent/operator_endpoint_oss_test.go
agent/structs/structs.go
agent/structs/structs_oss.go
api/api.go
api/operator_usage.go
api/operator_usage_test.go
command/operator/usage/instances/usage_instances.go
command/operator/usage/instances/usage_instances_oss.go
command/operator/usage/instances/usage_instances_oss_test.go
command/operator/usage/instances/usage_instances_test.go
command/operator/usage/usage.go
command/registry.go

This endpoint shows total services, connect service instances and billable service instances in the local datacenter or globally. Billable instances = total service instances - connect services - consul server instances.

oss: Add the `operator usage instances` command and api endpoint

---

agent/xds/validateupstream-test/validateupstream_test.go
command/troubleshoot/proxy/troubleshoot_proxy.go
troubleshoot/go.mod
troubleshoot/go.sum
troubleshoot/proxy/certs.go
troubleshoot/proxy/certs_test.go
troubleshoot/proxy/troubleshoot_proxy.go
troubleshoot/proxy/utils.go
troubleshoot/proxy/validateupstream.go
troubleshoot/proxy/validateupstream_test.go
troubleshoot/validate/validate.go
troubleshoot/validate/validate_test.go

Aggregate and log error messages. 
When you compile and run the CLI, you should now see output from all the validations. For example in a success case, here's what the command output looks like:
```
certificates are valid
listener for upstream "backend" found
route for upstream "backend" found
cluster "backend.default.dc1.internal.7838b4bd-58b3-8117-3df1-60584910541b.consul" for upstream "backend" found
healthy endpoints for cluster "backend.default.dc1.internal.7838b4bd-58b3-8117-3df1-60584910541b.consul" for upstream "backend"
cluster "backend2.default.dc1.internal.7838b4bd-58b3-8117-3df1-60584910541b.consul" for upstream "backend" found
healthy endpoints for cluster "backend2.default.dc1.internal.7838b4bd-58b3-8117-3df1-60584910541b.consul" for upstream "backend"
upstream resources are …
```

troubleshoot: output messages for the troubleshoot proxy command

---

ui/packages/consul-ui/app/styles/layouts/index.scss

Updates the content wrapper padding from 25px to 48px. 
**Before:**
**After:**
- [CC-4033](https://hashicorp.atlassian.net/browse/CC-4033)
[CC-4033]: https://hashicorp.atlassian.net/browse/CC-4033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI: CC-4033 - Update padding for the content wrapper

---

troubleshoot/validate/validate.go
troubleshoot/validate/validate_test.go

The troubleshoot proxy command validates Envoy config by checking for listeners, routes, clusters, and endpoints. However, if using Tproxy with DialedDirectly, there would be a passthrough cluster for that upstream without any endpoints. We shouldn't error in that case, and should log that it's a passthrough cluster.

troubleshoot: handle tproxy dialed directly case

---

.changelog/16105.txt
acl/errors.go
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_replication_test.go
agent/consul/acl_server.go
agent/consul/state/acl.go
api/acl_test.go
api/api_test.go
command/acl/acl_helpers.go
command/acl/authmethod/delete/authmethod_delete_test.go
command/acl/bindingrule/delete/bindingrule_delete_test.go
command/acl/policy/delete/policy_delete_test.go
command/acl/token/delete/token_delete_test.go
command/logout/logout_test.go

These errors provide helpful information in the case where the ACL system has not been bootstrapped, when a token does not exist, or when it does not exist in a particular namespace.
Functionality changes
Useful errors are now returned when:
- trying to get a specific resource (specified by ID) and failing because it does not exist
- trying to delete a resource that does not exist
Table of new API error messages:
| Message | Appears when | Previously |
|----|----|----|
| Requested * not found in namespace *: ACL not found |  ACL * Read / Get (namespace) | No error, return nothing |
| Requested * does not exist: ACL not found | ACL * Read / Get | No error, return nothing |
| Cannot find * to delete | ACL * Delete | Policy / Token: “ACL Not Found”, Role / Rule / AuthMethod: No error, return …

ACL error improvements: incomplete bootstrapping and non-existent token

---

envoyextensions/go.mod
go.mod
troubleshoot/go.mod
troubleshoot/go.sum

point to real sha's for api and envoyextensions so K8s doesn't need replace directives (api will use an actual tag later when it's tagged for the release)

update the api in envoyextensions and troubleshoot modules

---

.changelog/16230.txt
agent/consul/leader.go
agent/consul/leader_test.go
test/integration/consul-container/test/wanfed/wanfed_peering_test.go

Prior to this commit, secondary datacenters could not be initialized as peering acceptors if ACLs were enabled. This is due to the fact that internal server-to-server API calls would fail because the management token was not generated. This PR makes it so that both primary and secondary datacenters generate their own management token whenever a leader is elected in their respective clusters.

Fix peering acceptors in secondary datacenters.

---

agent/proxycfg/snapshot.go
agent/structs/config_entry_gateways.go
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/capture.sh
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/service_gateway.hcl
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/setup.sh
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/vars.sh
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/verify.bats
test/integration/connect/envoy/case-api-gateway-tcp-simple/verify.bats
test/integration/connect/envoy/helpers.bash

This adds a test to make sure we don't end up creating a listener that's in a conflicted state, previously without the changes here TCP-based listeners were still routing to upstream routes even when the listener was in a conflicted state.

[API Gateway] Add integration test for conflicted TCP listeners

---

agent/proxycfg/api_gateway.go

Leaving out enterprise metadata here causes our later route lookups to fail due to having enterprise metadata in one place and not another.
Verified the fix on an enterprise build.

[API Gateway] Fix missing references to enterprise metadata

---

.changelog/16204.txt
ui/packages/consul-ui/app/components/app/index.scss
ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
ui/packages/consul-ui/app/styles/variables/layout.scss
ui/packages/consul-ui/app/templates/application.hbs

Updating sidebar width to 280px to be consistent with Cloud UI.
- Run the app and check the sidebar width
**Before**
**After**
- [CC-4032](https://hashicorp.atlassian.net/browse/CC-4032)
[CC-4032]: https://hashicorp.atlassian.net/browse/CC-4032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI: CC-4032 - Update sidebar width

---

.changelog/16274.txt
.circleci/config.yml
envoyextensions/xdscommon/envoy_versioning_test.go
envoyextensions/xdscommon/proxysupport.go
website/content/docs/connect/proxies/envoy.mdx

Bump envoy to the latest versions.
1.22.5 -> 1.22.7
1.23.2 -> 1.23.4
1.24.0 -> 1.24.2
Add 1.25.1
Remove 1.21.5

[OSS] connect: Bump Envoy 1.22.5 to 1.22.7, 1.23.2 to 1.23.4, 1.24.0 to 1.24.2, add 1.25.1, remove 1.21.5

---

agent/proxycfg/api_gateway.go
agent/proxycfg/ingress_gateway.go
agent/proxycfg/manager.go
agent/proxycfg/state.go

Prior to this PR, servers / agents would panic and crash if an ingress or api gateway were configured to use a discovery chain that both:
1. Referenced a peered service
2. Had a mesh gateway mode of local
This could occur, because code for handling upstream watches was shared between both connect-proxy and the gateways. As a short-term fix, this PR ensures that the maps are always initialized for these gateway services.
To help prevent this, the PR also wraps the proxycfg execution and service registration calls with recover statements to ensure that future issues like this do not put the server into an unrecoverable state.
Closes #16238

Fix nil-pointer panics from proxycfg package.

---

agent/structs/config_entry_inline_certificate.go
api/config_entry_inline_certificate.go
api/config_entry_inline_certificate_test.go

Co-Authored-By: Andrew Stucki <3577250+andrewstucki@users.noreply.github.com>
`GetNamespace()` + `GetMeta()` were calling themselves. This PR also formats similar functions to match our config entries.

Fix infinite recursion in inline-certificate config entry

---

.changelog/16257.txt
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_upstreams.go
agent/structs/testing_catalog.go
agent/xds/endpoints.go

This fixes an issue where local mesh gateways use an incorrect address when attempting to forward traffic to a peered datacenter. Prior to this change it would use the lan address instead of the wan if the locality matched. This should never be done for peering, since we must route all traffic through the remote mesh gateway.

Fix mesh gateways incorrectly matching peer locality.

---

test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/libs/service/service.go
test/integration/consul-container/test/gateways/gateway_endpoint_test.go

This adds some optional ports you can pass in to the consul container used for initializing tests so that the ports get forwarded correctly to an upstream gateway so you can check the routing properly. It shouldn't break any existing tests, but adding this functionality to the testing libraries allows us to specify which ports to forward from our testing code.

Fix up API Gateway go tests

---

agent/xds/validateupstream-test/validateupstream_test.go
command/troubleshoot/proxy/troubleshoot_proxy.go
command/troubleshoot/upstreams/troubleshoot_upstreams.go
test/integration/consul-container/test/troubleshoot/troubleshoot_test.go
troubleshoot/proxy/certs.go
troubleshoot/proxy/certs_test.go
troubleshoot/proxy/stats.go
troubleshoot/proxy/troubleshoot_proxy.go
troubleshoot/proxy/upstreams.go
troubleshoot/proxy/upstreams_test.go
troubleshoot/validate/validate.go
troubleshoot/validate/validate_test.go

This PR makes a couple fixes, and updates all the output to be consistent across what's been discussed in the RFC. Note that this needs to be backported into 1.15.
Previously, it always printed `route ___ found`, even when there isn't a route. Now it only says that if it actually is a case where a route should be found.
In the below case, there are no routes and backendbloo does not have any instances. You can see there are no routes found in the below case (which is correct behavior) and the actions are displayed.
This also capitalizes the output, and makes the error messages more consistent and adds possible actions to most error cases.
Error case (deleted deployment for a peered upstream):
Success case (healthy upstream):
Output for `upstreams command`:

troubleshoot: fixes and updated messages

---

.github/ISSUE_TEMPLATE/bug_report.md

Update issue template to ask for agent HCL Config files for better diagnosis of bugs. 

ISSUE_TEMPLATE: Update issue template to include ask for HCL config files for bugs

---

agent/xds/validateupstream-test/validateupstream_test.go
command/troubleshoot/proxy/troubleshoot_proxy.go
command/troubleshoot/upstreams/troubleshoot_upstreams.go
test/integration/consul-container/test/troubleshoot/troubleshoot_upstream_test.go
troubleshoot/proxy/certs.go
troubleshoot/proxy/certs_test.go
troubleshoot/proxy/stats.go
troubleshoot/proxy/troubleshoot_proxy.go
troubleshoot/proxy/upstreams.go
troubleshoot/proxy/upstreams_test.go
troubleshoot/validate/validate.go
troubleshoot/validate/validate_test.go

Manual backport of https://github.com/hashicorp/consul/pull/16294

Backport: troubleshoot: fixes and updated messages

---

agent/xds/delta.go
agent/xds/testing.go

I'm seeing a bunch of panics in some flaky testing code in our xDS package. The relevant stack traces that come up time and again seem to mostly be on ARM (I'm assuming that this is due to some sort of slowness in the test runs that are accentuating race conditions due to additional qemu translation? 🤷):
```
goroutine 353 [running]:
github.com/hashicorp/consul/agent/xds.(*TestADSDeltaStream).Context(0x400009ff48?)
<autogenerated>:1
github.com/hashicorp/consul/agent/xds.(*Server).DeltaAggregatedResources(0x4001581620, {0x2998370, 0x0})
/home/circleci/project/agent/xds/delta.go:50 +0x4c
github.com/hashicorp/consul/agent/xds.newTestServerDeltaScenario.func3()
/home/circleci/project/agent/xds/xds_protocol_helpers_test.go:197 +0x38
created by …
```

Fix panicky xDS test flakes

---

agent/consul/discoverychain/gateway.go
agent/consul/discoverychain/gateway_test.go
agent/consul/gateways/controller_gateways.go
agent/proxycfg/snapshot.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_routes.go
test/integration/connect/envoy/case-api-gateway-http-hostnames/capture.sh
test/integration/connect/envoy/case-api-gateway-http-hostnames/service_gateway.hcl
test/integration/connect/envoy/case-api-gateway-http-hostnames/setup.sh
test/integration/connect/envoy/case-api-gateway-http-hostnames/vars.sh
test/integration/connect/envoy/case-api-gateway-http-hostnames/verify.bats

This PR is a manual backport from #16300
---
This adds a missing hostname check between listeners and HTTPRoutes. Without it we do no verification of the alignment between route and Listener hostnames and the listener hostnames are essentially unused. In the upstream spec, only http routes that have hostnames matching the listener hostname (or no hostnames specified) can be bound to a listener. We accomplish this by filtering out routes (both in the xDS code and in our controller) based on the listener hostname and then checking to see if there are any valid hosts to bind to.
It's a stacked PR on top of the inline certs PR (#16295), so that should get merged first.

Backport of Fix hostname alignment checks for HTTPRoutes into release/1.15.x

---

.changelog/16284.txt
command/troubleshoot/upstreams/troubleshoot_upstreams.go
website/content/commands/index.mdx
website/content/commands/troubleshoot/index.mdx
website/content/commands/troubleshoot/proxy.mdx
website/content/commands/troubleshoot/upstreams.mdx
website/content/docs/k8s/k8s-cli.mdx
website/data/commands-nav-data.json

Documentation for the new consul and consul-k8s troubleshoot command

new docs for consul and consul-k8s troubleshoot command

---

agent/structs/config_entry_gateways.go
agent/structs/config_entry_routes.go

This makes sure we normalize all enterprise metadata on write across our config entries. Enterprise tests were failing with the new TLS tests due to having a mismatch between what was in a `ResourceReference` and what was on the ConfigEntry itself as returned from the gRPC stream, as it got normalized elsewhere.
Tested and validated on enterprise.

Normalize all API Gateway references

---

agent/structs/config_entry_routes_test.go

Our unit tests were failing in enterprise due to the new normalization code

Fix HTTPRoute and TCPRoute expectation for enterprise metadata

---

api/go.mod
envoyextensions/go.mod
sdk/freeport/freeport.go
sdk/go.mod
troubleshoot/go.mod

This reverts changes from #16263 so that consumers of API/SDK modules can still use older, supported versions of Go with those modules.

fix: revert go mod compat for sdk,api to 1.19

---

.changelog/16301.txt
agent/agent.go
agent/http_test.go

Add tls config to unix socket when https is used
Manually tested with the following agent config
```
"addresses": {
"grpc_tls" : "unix://consul/consul_grpc.sock",
"http" : "unix://consul/consul_http.sock",
"https" : "unix://consul/consul_https.sock"
},
```
```
export CONSUL_HTTP_ADDR=unix://consul/consul_https.sock
CONSUL_HTTP_SSL=true consul connect 
```
fix #16252

fix: add tls config to unix socket when https is used

---

sdk/testutil/retry/retry.go
sdk/testutil/retry/retry_test.go

I was working with this test library in https://github.com/hashicorp/consul-enterprise/pull/4115 and the behavior is quite surprising, undocumented, and lacking unit tests showing the intended behavior. So I did some guessing at intent and documented it.
Note: Do not take this as my endorsement of this library being good. It is weird.
Bonus: there's a small bug that I've fixed. In [`ac2ac79` (#16049)](https://github.com/hashicorp/consul/pull/16049/commits/ac2ac7912143b77fb30c4cf18cc1a85779d9b30d) I add a test to show the bug (see [test run](https://app.circleci.com/pipelines/github/hashicorp/consul/49803/workflows/3a6a03d2-388b-471d-b84a-65a66b01422b/jobs/1141808)). In [`7e9af2c` (#16049)](https://github.com/hashicorp/consul/pull/16049/commits/7e9af2cf4c7afab648809528f40f83b00b62996d) I …

chore: document and unit test sdk/testutil/retry

---

agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
api/config_entry_gateways.go
test/integration/connect/envoy/case-api-gateway-tcp-conflicted/setup.sh

This adds the same validation rules that the API Gateway spec has for listener names. Previously we were allowing for an empty listener name which made it impossible to distinguish between wanting to bind to all listeners on a gateway or just the listener without a name.

[API Gateway] Validate listener name is not empty

---

.changelog/16339.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/peering.go
agent/consul/state/peering_test.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/subscription_manager.go
agent/grpc-external/services/peerstream/subscription_manager_test.go
agent/proxycfg-glue/exported_peered_services_test.go
agent/structs/peering.go
agent/structs/structs.go

Prior to this PR, all peer services were transmitted as connect-enabled as long as a one or more mesh-gateways were healthy. With this change, there is now a difference between typical services and connect services transmitted via peering.
A service will be reported as "connect-enabled" as long as any of these conditions are met:
1. a connect-proxy sidecar is registered for the service name.
2. a connect-native instance of the service is registered.
3. a service resolver / splitter / router is registered for the service name.
4. a terminating gateway has registered the service.

Fix issue with peer services incorrectly appearing as connect-enabled.

---

agent/consul/gateways/controller_gateways.go

This turns down all of our controller debug logs to trace logs to avoid too much spam. Additionally, all controller `Error` logs are moved to `Warn` level since:
1. previously `Error` would be logged for things like a failed reconciliation due to a CAS mismatch, which could just occur with high volumes of writes to a corresponding ConfigEntry
2. we wind up rescheduling the reconciliation when an error is encountered anyway, so this may or may not be a trivial error that gets resolved next reconciliation run.
Accordingly, it's probably more of a "warning" level than something we'd want to alert the user on at the "error" level.

[API Gateway] Turn down controller log levels

---

agent/consul/discoverychain/gateway.go
agent/consul/discoverychain/gateway_test.go
agent/structs/config_entry_routes.go
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/capture.sh
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/service_gateway.hcl
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/service_s3.hcl
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/setup.sh
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/vars.sh
test/integration/connect/envoy/case-api-gateway-http-splitter-targets/verify.bats

Previously when synthesizing an ingress discovery chain from API Gateway primitives, we weren't properly fixing up the discovery chain to allow for targeting service splitters, which we support today in our Kubernetes solution. This fixes this, allowing the use of virtual splitters in a service target inside of an HTTPRoute.

[API Gateway] Fix targeting service splitters in HTTPRoutes

---

test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/service/service.go
test/integration/consul-container/test/upgrade/peering_http_test.go

oss split of ent [pr](https://github.com/hashicorp/consul-enterprise/pull/4376)

upgrade test: splitter and resolver config entry in peered cluster

---

website/content/docs/api-gateway/index.mdx
website/content/docs/api-gateway/install.mdx
website/content/docs/api-gateway/tech-specs.mdx
website/content/docs/api-gateway/upgrades.mdx
website/content/docs/api-gateway/usage/usage.mdx
website/data/docs-nav-data.json

As we begin adding in documentation for API Gateway on VMs, the existing documentation will remain for API Gateway on Kubernetes. To avoid confusion, we want to rename the existing docs to reflect the environment that it's intended for.

Update existing docs from Consul API Gateway -> API Gateway for Kubernetes

---

test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_subset_onlypassing_test.go
test/integration/consul-container/test/upgrade/peering_http_test.go

Add tests for service resolver with onlypassing set to true. This test validates that Envoy and Consul can get an instance status. OnlyPassing field is used by both features to determine when an endpoint should be considered healthy
Convert .[bats](https://github.com/hashicorp/consul/blob/main/test/integration/connect/envoy/case-cfg-resolver-subset-onlypassing/verify.bats) test to golang

NET-2286: Add tests for service resolver with onlypassing set to true

---

agent/consul/gateways/controller_gateways.go
agent/consul/gateways/controller_gateways_test.go
agent/structs/config_entry_status.go

We were allowing gateways to bind routes that were in a "non-accepted" state in our gateway reconciliation path and not allowing them in the route reconciliation path. Because of the fact that a TCP route being added to a gateway and forcing the gateway into a "conflicted" state causes a status update to the gateway and a status update to the route, we could trigger an infinite loop where the route status was being written as "bound" and the gateway status as "conflicted" when the gateway was reconciled, and then it would trigger a route reconciliation marking the route as "unbound" and the gateway no longer as "conflicted". The mutual status setting would cause reconciliation to be triggered indefinitely.
The fix is to add a check inside of our binding logic that makes sure a route and …

[API Gateway] Fix infinite loop in controller and binding non-accepted routes and gateways

---

agent/consul/multilimiter/multilimiter.go
agent/consul/multilimiter/multilimiter_test.go

This change add the ability in multilimiter to associate a limiter with a config in the longest prefix tree. That way if we have a config under `127.0.0` the limiter for ip range `127.0.0.0/24` will use that config. 
Added a test to cover the use case above and another where we have 2 different prefixes (`127.0`(c1) and `127.0.0`(c2)) and we expect `127.0.0.1` to use c2 while `127.0.1.1` to use c2.

Rate limiter/add ip prefix

---

website/content/docs/k8s/deployment-configurations/servers-outside-kubernetes.mdx

The documentation on adding K8S clusters to external Consul servers needed to include a few details around installation with Consul Dataplane.

Documentation update: Adding K8S clusters to external Consul servers

---

website/content/api-docs/operator/usage.mdx
website/content/commands/operator/index.mdx
website/content/commands/operator/usage.mdx
website/data/api-docs-nav-data.json
website/data/commands-nav-data.json

Adds API and CLI docs for the new `operator usage instances` command (added [here](https://github.com/hashicorp/consul/pull/16205)).

Add docs for usage endpoint and command

---

test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go

Update Traffic Management integration test to include verification of passing instances by Consul after a server and client have been registered.

NET-2285: Assert total number of expected instances by Consul

---

.github/workflows/nightly-test-1.15.x.yaml

We had a bug in the github action that is causing frontend-oss-build to fail.
Builds should pass

[OSS] set BRANCH_NAME to release-1.15.x

---

website/content/api-docs/operator/usage.mdx

#16258 introduced a rendering error impacting Vercel runs on `main` and `release/1.15.x`:
Example failing Vercel run: https://vercel.com/hashicorp/consul/8vFm4QCA2PWxK87fiV9M1qiEW848

Fix rendering error on new operator usage docs

---

api/operator_license.go

This struct was missing a new field for licenses. This brings OSS up to parity with ENT.

add missing field to oss struct

---

agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/testing.go
agent/xds/delta_test.go
agent/xds/xds_protocol_helpers_test.go
command/debug/debug.go

Fixes tests that have high rates of failure in our CI pipeline:
* `TestStreamResources_Server_DisconnectsOnHeartbeatTimeout/stream_is_disconnected_due_to_heartbeat_timeout`
* `TestDebugCommand_DebugDisabled`
* `TestServer_DeltaAggregatedResources_v3_ACLEnforcement` (added retries but not 100% confident in fix)

Fix various flaky tests

---

website/content/docs/api-gateway/index.mdx
website/content/docs/connect/gateways/api-gateway/configuration/api-gateway.mdx
website/content/docs/connect/gateways/api-gateway/configuration/http-route.mdx
website/content/docs/connect/gateways/api-gateway/configuration/inline-certificate.mdx
website/content/docs/connect/gateways/api-gateway/configuration/tcp-route.mdx
website/content/docs/connect/gateways/api-gateway/index.mdx
website/content/docs/connect/gateways/api-gateway/usage.mdx
website/data/docs-nav-data.json

This is a manual backport of #16365 due to the failure of the automated backport, #16407 
Note that the diff here is slightly smaller than the original PR due to the fix for `website/content/api-docs/operator/usage.mdx` that has already been backported into this branch via #16399

Backport of Native API Gateway Docs (#16365)

---

test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_subset_redirect_test.go

This test sets up 2 servers and 2 subsets for server 2. Client should be able to redirect traffic from server n to server y based on the config set by the service resolver. 
Refactor of test written in [.bats](https://github.com/hashicorp/consul/tree/main/test/integration/connect/envoy/case-cfg-resolver-subset-redirect)

NET-2286: Add tests to verify traffic redirects between services

---

test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_subset_redirect_test.go

Refactor the `assertionFn` in `TestTrafficManagement_ServiceResolverSubsetRedirect` integration tests as it has some redundant code and fixes a bug where ports are being over written.

NO_JIRA: refactor validate function in traffic mgt tests

---

.changelog/16412.txt
ui/packages/consul-lock-sessions/app/components/consul/lock-session/notifications/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs
ui/packages/consul-ui/app/components/auth-form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/notice/custom-resource/index.hbs
ui/packages/consul-ui/app/components/consul/intention/notice/permissions/index.hbs
ui/packages/consul-ui/app/components/consul/node/agentless-notice/index.hbs
ui/packages/consul-ui/app/components/consul/node/agentless-notice/index.scss
ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/tokens/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
ui/packages/consul-ui/app/templates/settings.hbs
ui/packages/consul-ui/translations/routes/en-us.yaml

The Consul core UI is currently utilizing alert components (AKA [notifications](https://www.figma.com/file/B7yd8loYS7nA2TiQcJ8UtV/Structure-1.9?node-id=11920%3A0&t=93OyZpFy44QYFcWW-11)) from our old design system (structure). In efforts to upgrade from Structure → HDS and align Consul’s UIs for product consistency, we need to update our notification component to utilize the HDS alert components.
K/v issue with routing is fixed ([CC-4334](https://hashicorp.atlassian.net/browse/CC-4334))
https://hashicorp.atlassian.net/browse/CC-4035
https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/HDS-Product---Components?node-id=1377%3A11987&t=S7hrH9peTwLb3gZR-0
[CC-4334]: https://hashicorp.atlassian.net/browse/CC-4334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

feat: update alerts to Hds::Alert component

---

website/content/docs/connect/config-entries/service-splitter.mdx

Removes a trailing space that is causing frontmatter parsing to break.

docs: remove extra whitespace in frontmatter

---

.changelog/16444.txt
ui/packages/consul-ui/package.json
ui/yarn.lock

Fixes the issue that was [reported here](https://github.com/hashicorp/consul/issues/16429).
Search filters were throwing errors and showing up empty. This also resulted in lists not showing full results until being interacted with. Weirdly enough I haven't been able to reproduce this against mock data despite the helper still being called on strings.
**Before:**
Running locally I tried logging the properties being passed into the "search across" filter and then logging them with the `lowercase` helper. They show up locally
When running it on the built version the lowercase is never logged as it errors out (I had the errors filtered here)
**After**
List and filter shows up properly and the lowercase is logged (I didn't commit the logs)
1. Checkout `1.15.0` branch
2. run `make ui-docker` to …

UI: Fix rendering issue in search and lists

---

website/content/docs/connect/proxies/envoy.mdx
website/content/docs/k8s/compatibility.mdx
website/content/docs/k8s/helm.mdx

Updating docs website docs for Consul-k8s 1.1.0.
- Removed Consul 1.12 from Compatibility matrix
- Removed unneeded CVE entry
- Update Envoy versions for consul-dataplane
- Update with latest generated helm values.

Update docs for consul-k8s 1.1.0

---

.changelog/16445.txt
command/acl/token/read/token_read.go
command/acl/token/read/token_read_test.go

Fixes a regression in #16044
The `consul acl token read -self` cli command should not require an `-accessor-id` because typically the persona invoking this would not already know the accessor id of their own token.

cli: ensure acl token read -self works

---

website/content/docs/agent/limits/index.mdx
website/content/docs/agent/limits/init-rate-limits.mdx
website/content/docs/agent/limits/set-global-traffic-rate-limits.mdx

udpate docs so they're sentence case, style guide

---

website/content/docs/connect/proxies/envoy.mdx

Clarified our support policy around consul-dataplane versions and added consul-datapalane 1.1.0 to the 1.14.0 Envoy matrix.

docs: Add backwards compatibility for Consul 1.14.x and consul-dataplane in the Envoy compat matrix

---

test/integration/consul-container/test/gateways/gateway_endpoint_test.go
test/integration/consul-container/test/gateways/http_route_test.go

Adds an e2e test for switching the `ParentRef` of an `HTTPRoute` from one API Gateway to another.

gateways: add e2e test for API Gateway HTTPRoute ParentRef change

---

test/integration/consul-container/test/gateways/gateway_endpoint_test.go
test/integration/consul-container/test/gateways/http_route_test.go

Depends on the work done here https://github.com/hashicorp/consul/pull/16278, ports the additional test HTTPPathRewrite, plus adds some helper functions to run the test cases. 
go test ./...
[Original gateway e2e test
](https://github.com/hashicorp/consul-api-gateway/blob/f78ec587946fe18eae7d4fbb297e2527cdea2299/internal/commands/server/k8s_e2e_test.go#L674)
* [X ] updated test coverage
* [X ] not a security concern

Gateway Test HTTPPathRewrite

---

version/version.go

Fixes a regression from #15631 in the output of `consul version` from:
Consul v1.16.0-dev
+ent
Revision 56b86acbe5+CHANGES
to
Consul v1.16.0-dev+ent
Revision 56b86acbe5+CHANGES

cli: remove stray whitespace when loading the consul version from the VERSION file

---

.changelog/16298.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_auth.go
agent/connect/ca/provider_vault_auth_aws.go
agent/connect/ca/provider_vault_auth_azure.go
agent/connect/ca/provider_vault_auth_gcp.go
agent/connect/ca/provider_vault_auth_test.go
agent/connect/ca/provider_vault_test.go

Does the required dance with the local HTTP endpoint to get the required data for the jwt based auth setup in Azure. Keeps support for 'legacy' mode where all login data is passed on via the auth methods parameters.

add provider ca auth-method support for azure

---

website/content/docs/services/configuration/checks-configuration-reference.mdx
website/content/docs/services/configuration/services-configuration-overview.mdx
website/content/docs/services/configuration/services-configuration-reference.mdx
website/content/docs/services/discovery/dns-configuration.mdx
website/content/docs/services/discovery/dns-dynamic-lookups.mdx
website/content/docs/services/discovery/dns-overview.mdx
website/content/docs/services/discovery/dns-static-lookups.mdx
website/content/docs/services/services.mdx
website/content/docs/services/usage/checks.mdx
website/content/docs/services/usage/define-services.mdx
website/content/docs/services/usage/register-services-checks.mdx

This PR updates page titles for the Services section to the sentence -style capitalization per the recent style guide uipdate.

Changed titles for services pages to sentence style cap

---

.changelog/16485.txt
command/acl/policy/read/policy_read.go
command/acl/policy/read/policy_read_test.go

Return error message on acl policy not found, instead of panic
fix #16483

fix (cli): return error msg if acl policy not found

---

website/data/docs-nav-data.json

This PR updates the sidebar nav titles for the Services topics. Sidebar titles should start conform to the style guidance about using sentence-style capitalization for all content titles. Additionally, we should use a short form for nav titles, for example, "Services overview" => "Overview", to keep the nav concise.

update services nav titles

---

.changelog/16288.txt
command/acl/token/update/token_update.go
command/acl/token/update/token_update_test.go
website/content/commands/acl/token/update.mdx

- Marking `mergePolicies` for deprecation and encouraging the use of `-append-policy-id` and `-append-policy-name` to reduce the ambiguity when overwriting fields on update 
- Updating docs to clarify that using: `-policy-id` and `-policy-name` will overwrite existing policies
- Marking `mergeRoles` for deprecation and encouraging the use of `-append-role-id` and `-append-role-name` to reduce the ambiguity when overwriting fields on update 
- Updating docs to clarify that using: `-append-role-id` and `-append-role-name` will overwrite existing policies …

Improve ux to help users avoid overwriting fields of ACL tokens, roles and policies

---

test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/observability/access_logs_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
test/integration/consul-container/test/troubleshoot/troubleshoot_test.go
test/integration/consul-container/test/upgrade/acl_node_test.go
test/integration/consul-container/test/upgrade/ingress_gateway_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
test/integration/consul-container/test/upgrade/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering_http_test.go

Port from consul-enterprise: https://github.com/hashicorp/consul-enterprise/pull/4500:
Port the BATS test suite from`test/integration/connect/case-ingress-gateway-http` to Go, and make it an upgrade test.
- `AssertFortioName` can hack the `Host` header + `Host` field to make a mapped port on `localhost` behave a little more like a real one
- add a second static client in `NewPeeringCluster`

NET-2292: port ingress-gateway test case "http" from BATS addendum

---

.changelog/16274.txt
.circleci/config.yml
envoyextensions/xdscommon/envoy_versioning_test.go
envoyextensions/xdscommon/proxysupport.go
website/content/docs/connect/proxies/envoy.mdx

#16274 updated the Envoy compatibility list but wasn't backported into `release/1.15.x`. This is causing Consul 1.15.0 to report invalid Envoy version for newer Envoy releases - 1.25.1, for example - that are valid according to the compatibility chart in our docs.
This backport makes it so that our next patch release will accept the newer version of Envoy without warning the user.

Backport #16274

---

lib/telemetry.go

There is a new set of tests that have high rates of failure [(example)](https://app.circleci.com/pipelines/github/hashicorp/consul/52978/workflows/c3f09d66-2e45-4fb8-a56d-efca6223b88c/jobs/1235632).
They are labelled "flaky" but in reality are failing deterministically whenever there is a test retry which causes TestAgents to initialize the prometheus collectors more than once in a single runtime.
This PR suppresses [`prometheus.AlreadyRegisteredError`](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#AlreadyRegisteredError) so retries can run properly. This should have no impact on production usage as the metrics initialization happens only once on consul agent startup.
* Run a test which configures prometheus metrics from `metrics_test.go` like …

Suppress AlreadyRegisteredError to fix test retries

---

.changelog/16266.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_auth_jwt.go
agent/connect/ca/provider_vault_auth_test.go
agent/connect/ca/provider_vault_test.go

Adds support for a jwt token in a file. Simply reads the file and sends the read in jwt token along to the vault login.

add provider ca support for jwt file base auth

---

.changelog/16262.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_auth_k8s.go
agent/connect/ca/provider_vault_auth_test.go
agent/connect/ca/provider_vault_test.go

Adds support for Kubernetes jwt/token file based auth. Only needs to read the file and save the contents as the jwt/token.

add provider ca auth support for kubernetes

---

command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go

- When an envoy version is out of a supported range, we now return the envoy version being used as `major.minor.x` to indicate that it is the minor version at most that is incompatible
- When an envoy version is in the list of unsupported envoy versions we return back the envoy version in the error message as `major.minor.patch` as now the exact version matters.
Note: Currently we do not have any envoy versions in the list of `unsupported` versions but we can support this in the future should the need arise to invalidate a particular major, minor or patch version
Verified error message with envoy out of bounds:
```shell
dc1svc2    | Envoy version 1.18.x is not supported. If there is a reason you need to use this version of envoy use the ignore-envoy-compatibility flag. Using an …
```

modified unsupported envoy version error

---

internal/tools/proto-gen-rpc-glue/e2e/source.pb.go

In a previous PR I added a "private" directory within Consuls proto directory to prevent proto registry name conflicts. This apparently broke the proto-gen-rpc-glue e2e tests and even go mod tidy within the e2e dir would fail.
This fixes it.
This dir is especially weird because we are importing consul but consul is redefined to the embedded directory within the e2e tests. So global search/replace for imports happens to pick up changes in these files too.
To reproduce/test run `make go-mod-tidy`

Remove private prefix from proto-gen-rpc-glue e2e test

---

.changelog/16499.txt
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
test/integration/connect/envoy/case-terminating-gateway-subsets/capture.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/service_s3.hcl
test/integration/connect/envoy/case-terminating-gateway-subsets/setup.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/vars.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/verify.bats
test/integration/connect/envoy/helpers.bash

While fixing https://github.com/hashicorp/consul/pull/16498 I noticed that applying a `ServiceResolver` with subsets wasn't functional when referencing an external service proxied through a `TerminatingGateway` as an upstream. I'm not too familiar with the way we return service health for external services, but the problem appears to be that in our health check materializer we:
1. Grab the `CheckServiceNode` values from our subscription, and then
2. Apply any filters that were in our initial subscription request
Since we return the gateway associated with the service when we're using external services in conjuction with a `TerminatingGateway`:
https://github.com/hashicorp/consul/blob/21c30958cc89ba4a14a099d758002bc0a0ecc454/agent/consul/state/catalog.go#L2770-L2782
The filter never passes …

Fix resolution of service resolvers with subsets for external upstreams

---

.changelog/16259.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_auth_approle.go
agent/connect/ca/provider_vault_auth_test.go
agent/connect/ca/provider_vault_test.go

Adds support for the approle auth-method. Only handles using the approle role/secret to auth and it doesn't support the agent's extra management configuration options (wrap and delete after read) as they are not required as part of the auth (ie. they are vault agent things).

add provider ca support for approle auth-method

---

.changelog/16497.txt
agent/agent.go
agent/config/builder.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/proxycfg-sources/local/sync.go
agent/proxycfg/manager.go
agent/proxycfg/state.go
agent/proxycfg_test.go
agent/testagent.go

Receiving an "acl not found" error from an RPC in the agent cache and the streaming/event components will cause any request loops to cease under the assumption that they will never work again if the token was destroyed. This prevents log spam (https://github.com/hashicorp/consul/pull/14144, https://github.com/hashicorp/consul/pull/9738).
Unfortunately due to things like:
- authz requests going to stale servers that may not have witnessed the token creation yet
- authz requests in a secondary datacenter happening before the tokens get replicated to that datacenter
- authz requests from a primary TO a secondary datacenter happening before the tokens get replicated to that datacenter
The caller will get an "acl not found" *before* the token exists, rather than just after. The machinery added …

proxycfg: ensure that an irrecoverable error in proxycfg closes the xds session and triggers a replacement proxycfg watcher

---

.changelog/16506.txt
command/acl/token/update/token_update.go
command/acl/token/update/token_update_test.go
website/content/commands/acl/policy/update.mdx
website/content/commands/acl/token/update.mdx

Follow up to https://github.com/hashicorp/consul/pull/16288 
TLDR: `node-identity` and `service-identity` flags when specified without the `merge-*` flags overwrites service identities and node identities of a token. This is ambiguous to the user because we have a `no-merge` flag which seems to imply that on update we are merging. So we have been doing work to improve the ux by renaming/adding/sunsetting flags and adding more docs to help reduce the ambiguity
- Marking `merge-node-identities` and `merge-service-identities` for deprecation and encouraging the use of their replacement `append-node-policy` and `append-service-identity`
- Updating docs to clarify that using `-rules` overwrites existing rules 
- Adding docs for the new flags: `append-node-policy` and `append-service-identity`

Improve ux around ACL token to help users avoid overwriting node/service identities

---

command/acl/token/update/token_update_test.go

The idea is to make sure each test can independently run so this PR reduce the dependency of tests on each other which causes a degree of flakiness. 
- Each tests depended on the same token to run which sometimes meant one test will overwrite changes from the other. So fixing this by allowing each test to create its own individual token that it could update and read to without any interference from other tests.

Fix flakey tests related to ACL token updates

---

website/content/api-docs/config.mdx

This updates the api docs to include the permissions needed for each kind of config entry.

docs: Document config entry permissions

---

.changelog/16499.txt
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
test/integration/connect/envoy/case-terminating-gateway-subsets/capture.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/service_s3.hcl
test/integration/connect/envoy/case-terminating-gateway-subsets/setup.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/vars.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/verify.bats
test/integration/connect/envoy/helpers.bash

Manual backport from #16499 to release/1.13.x.
---
While fixing https://github.com/hashicorp/consul/pull/16498 I noticed that applying a `ServiceResolver` with subsets wasn't functional when referencing an external service proxied through a `TerminatingGateway` as an upstream. I'm not too familiar with the way we return service health for external services, but the problem appears to be that in our health check materializer we:
1. Grab the `CheckServiceNode` values from our subscription, and then
2. Apply any filters that were in our initial subscription request
Since we return the gateway associated with the service when we're using external services in conjuction with a `TerminatingGateway`: …

Manual Backport of Fix resolution of service resolvers with subsets for external upstreams into release/1.13.x

---

.changelog/16499.txt
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
test/integration/connect/envoy/case-terminating-gateway-subsets/capture.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/service_s3.hcl
test/integration/connect/envoy/case-terminating-gateway-subsets/setup.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/vars.sh
test/integration/connect/envoy/case-terminating-gateway-subsets/verify.bats
test/integration/connect/envoy/helpers.bash

Manual backport from #16499 to release/1.14.x.
---
While fixing https://github.com/hashicorp/consul/pull/16498 I noticed that applying a `ServiceResolver` with subsets wasn't functional when referencing an external service proxied through a `TerminatingGateway` as an upstream. I'm not too familiar with the way we return service health for external services, but the problem appears to be that in our health check materializer we:
1. Grab the `CheckServiceNode` values from our subscription, and then
2. Apply any filters that were in our initial subscription request
Since we return the gateway associated with the service when we're using external services in conjuction with a `TerminatingGateway`: …

Manual Backport of Fix resolution of service resolvers with subsets for external upstreams into release/1.14.x

---

website/content/docs/concepts/service-discovery.mdx
website/content/docs/intro/index.mdx
website/content/docs/nia/usage/requirements.mdx

Broken link fixes

---

.changelog/16570.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/usage.go
agent/structs/structs.go

This fixes a bug where `cleanupKindServiceName` was called for a peered service. If a local service with the same name exists, the local service's entry in `tableKindServiceNames` is unexpectedly deleted.

Fix Peering Service Cleanup Bug

---

CHANGELOG.md

Update changelog with patch releases 1.13.7, 1.14.5, and 1.15.1

Update changelog with patch releases

---

.github/workflows/backport-checker.yml

- Add a pipeline check for backport labels. This will ensure that developers must either add a backport label or deliberately specify that this pr does not require backporting with the `pr/no-backport` label.
- This check simply checks for the presence of a label matching `backport/*`. It is up to the developer to add the right backport labels as appropriate for a given PR.
How I've tested this PR:
No Backport label and no `pr/no-backport`
With backport label
With `pr/no-backport` label
* [n/a] updated test coverage
* [n/a] external facing docs updated

added a backport-checker GitHub action

---

.changelog/16574.txt
ui/packages/consul-ui/package.json
ui/yarn.lock

Traced `isHTMLSafe` errors back to `ember-intl` package. There was [minor release that addressed these issues](https://github.com/ember-intl/ember-intl/releases/tag/v5.7.0). Unfortunately, this missed the patch Consul release.
**Before**
**After:**
1. Checkout `1.15.1` branch
2. run `make ui-docker` to build the ui image
3. run `make dev-docker`
4. clone https://github.com/WenInCode/consul-setup
5. in the consul-setup repo go to the `setups/peering` directory
6. run `docker-compose up`
7. run `yarn setup:peerings`
8. Go to the overview page or any page with an empty state
- #16444 
- [CC-4450](https://hashicorp.atlassian.net/browse/CC-4450)
- https://github.com/hashicorp/consul/issues/16429
[CC-4450]: https://hashicorp.atlassian.net/browse/CC-4450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

UI: Fix htmlsafe errors throughout the app

---

website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/services/usage/define-services.mdx

We incorrectly documented that the `metadata.partitions` field is supported for some K8s CRDs. This PR removes the field and, in the appropriate context, explains that the pod inherits the partition configuration.

fixes for unsupported partitions field in CRD metadata block

---

.github/workflows/broken-link-check.yml

To address practitioner concerns over broken links, we would like to implement a 404 checker for Consul docs.
The GitHub action utilizes [lychee](https://github.com/lycheeverse/lychee), a popular, open source link-checking utility.
This implementation of the GitHub action would run lychee on a weekly cadence (Mondays) and output the report to a GitHub issue.
The same implementation has been put in place for the tutorials repository:
https://github.com/hashicorp/tutorials/pull/1204
Feel free to:
1. Download [lychee](https://github.com/lycheeverse/lychee).
2. Clone this repository and `cd` into the directory.
3. Run this command `lychee ./docs --base https://developer.hashicorp.com/ --exclude-all-private --exclude .png --exclude .svg --max-concurrency=24 --no-progress --verbose`
Some output …

Create a weekly 404 checker for all Consul docs content

---

.changelog/16585.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/proxycfg/testing_connect_proxy.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/hcp-metrics.latest.golden
agent/xds/testdata/endpoints/hcp-metrics.latest.golden
agent/xds/testdata/listeners/hcp-metrics.latest.golden
agent/xds/testdata/routes/hcp-metrics.latest.golden
agent/xds/testdata/secrets/hcp-metrics.latest.golden
api/connect.go

#16511 adds bootstrap configuration so that Envoy is configured to send its telemetry to a statically defined local socket. 
This PR builds on top of the previous one by configuring a dynamic listener at that statically configured socket. The changes below inject the HCP metrics collector as an upstream for connect proxies since it is intended to be a mesh service deployed onto the user's cluster. 
Why is there dynamic configuration when the cluster is statically defined at bootstrap time?
- We want to secure the metrics stream using TLS, but the stats sink can only be defined in bootstrap config. With dynamic listeners/clusters we can use certificates issued by the connect CA, which aren't available at bootstrap time.
- We want to intelligently route to the HCP collector. Configuring its …

[CC-4365] HCP Metrics xDS Config for Envoy

---

.changelog/16585.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/proxycfg/testing_connect_proxy.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/hcp-metrics.latest.golden
agent/xds/testdata/endpoints/hcp-metrics.latest.golden
agent/xds/testdata/listeners/hcp-metrics.latest.golden
agent/xds/testdata/routes/hcp-metrics.latest.golden
agent/xds/testdata/secrets/hcp-metrics.latest.golden
api/connect.go
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/hcp-metrics.golden
website/content/commands/connect/envoy.mdx

Add a new envoy flag: `envoy_hcp_metrics_bind_socket_dir`, a directory where a unix socket will be created with the name `<namespace>_<proxy_id>.sock` to forward Envoy metrics.
If set, this will configure a local `stats_sink` and `STATIC` cluster to forward Envoy metrics to an HCP collector.
The HCP Cloud team is working on enabling observability metrics in HCP. 
There will be a follow-up PR to generate a listener and cluster dynamically that will be listening on this unix socket. 
That listener and cluster will be configured to route to collector instances through the service mesh.
Caveat: we needed to add this local listener indirection as a workaround due to this [issue](https://github.com/envoyproxy/envoy/issues/25700)
- Added unit tests
- Tested locally by running consul, registering …

Allow HCP metrics collection for Envoy proxies

---

.changelog/16585.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/proxycfg/testing_connect_proxy.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/hcp-metrics.latest.golden
agent/xds/testdata/endpoints/hcp-metrics.latest.golden
agent/xds/testdata/listeners/hcp-metrics.latest.golden
agent/xds/testdata/routes/hcp-metrics.latest.golden
agent/xds/testdata/secrets/hcp-metrics.latest.golden
api/connect.go
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/hcp-metrics.golden
website/content/commands/connect/envoy.mdx

Replaces #16609 since it did not pull the entire change set from #16511

Backport of Allow HCP metrics collection for Envoy proxies into release/1.15.x

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_sameness_group_oss.go
agent/consul/state/config_entry_sameness_group_oss_test.go
agent/consul/state/config_entry_schema.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/structs/config_entry.go
agent/structs/config_entry_sameness_group.go
agent/structs/config_entry_sameness_group_oss.go
api/config_entry.go
api/config_entry_samness_group.go

This PR introduces a new sameness-group configuration entry. Sameness-groups will allow for multiple partitions / peers to be grouped together for failover, service-export, and intention configuration.
Note that while the data structure exists in the open-source version of the software, all functionality is currently planned to be enterprise-only.

Add sameness-group configuration entry.

---

.changelog/16592.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

If a CA config update did not cause a root change, the codepath would return early and skip some steps which preserve its intermediate certificates and signing key ID. This commit re-orders some code and prevents updates from unnecessarily generating new intermediate certificates if one exists.
* Added new testcase which should fail without this PR
* Existing integration tests are passing
Fixes https://github.com/hashicorp/consul/issues/16580
Fixes https://github.com/hashicorp/consul/issues/14564

Preserve CARoots when updating Vault CA configuration

---

.changelog/_4696.txt
agent/proxycfg-glue/trust_bundle.go
agent/rpc/peering/service.go

This commit fixes an issue where trust bundles could not be read by services in a non-default namespace, unless they had excessive ACL permissions given to them.
Prior to this change, `service:write` was required in the default namespace in order to read the trust bundle. Now, `service:write` to a service in any namespace is sufficient.

Fix issue with trust bundle read ACL check.

---

internal/resource/registry.go
internal/resource/registry_test.go

See NET-2686
`gotestsum --format=testname ./internal/resource`

Basic resource type registry

---

agent/structs/config_entry_routes.go
agent/structs/config_entry_status.go
test/integration/consul-container/test/gateways/http_route_test.go

Made some changes in ENT-4704 while trying to make tests pass. 
This PR has the changes made to OSS files, to being them back in sync.

Backport ENT-4704

---

test/integration/consul-container/test/gateways/gateway_endpoint_test.go

This got dropped in between rebases to keep branch up to date for previous PR https://github.com/hashicorp/consul/pull/16627
In enterprise change the `getNamespace` function to return a non-empty string, without this change gateway tests will fail.
https://github.com/hashicorp/consul/pull/16627

Add in query options for catalog service existing in a specific namespace when creating service for tests

---

.changelog/16660.txt
ui/packages/consul-ui/app/adapters/token.js

Triggering saving of token responds with 'Token Accessor ID in URL and payload do not match' error. 
The reason is the AccessorID property has not been included to requestBody. there might be some changes on backend side, which updated requestBody structure to include AccessorID for token PUT endpoint. 
https://user-images.githubusercontent.com/10027860/225770124-7b02a50d-6264-4134-a943-8233a9721526.mov
Testing & Reproduction steps
- run `make ui-docker` to build the ui image
- run `make dev-docker`
- clone `https://github.com/WenInCode/consul-setup`
- in the `consul-setup` repo go to the `setups/peering directory`
- run `docker-compose up`
- run `yarn setup:peerings`
- Go to the token details page and press 'Save' button
https://hashicorp.atlassian.net/browse/CC-4515

fix: add AccessorID property to PUT token request

---

.changelog/16661.txt
agent/consul/discoverychain/gateway.go
agent/consul/discoverychain/gateway_test.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/api-gateway-with-http-route-and-inline-certificate.latest.golden
agent/xds/testdata/endpoints/api-gateway-with-http-route-and-inline-certificate.latest.golden
agent/xds/testdata/listeners/api-gateway-with-http-route-and-inline-certificate.latest.golden
agent/xds/testdata/routes/api-gateway-with-http-route-and-inline-certificate.latest.golden
agent/xds/testdata/secrets/api-gateway-with-http-route-and-inline-certificate.latest.golden
test/integration/consul-container/test/gateways/gateway_endpoint_test.go
test/integration/consul-container/test/gateways/http_route_test.go

We were seeing that HTTP listeners on API Gateways were taking ~15 seconds or more to get programmed onto the envoy instances (this also happens on our Kubernetes offering). I finally tracked down what was the root cause. Because we are currently masquerading as ingress gateways for the purposes of xDS generation, the main entrypoint for each HTTP listener is a "virtual" service router, basically one that doesn't correspond to an actual service, but that contains our routing logic based on the rules in an HTTPRoute. What was happening is that when we use such a router, the discovery chain compilation process adds a "fallback target" for when no rules match that targets a service resolver with the same name as the router.
Thus, if our router was named `gateway-listener-12345` -- we were …

[API Gateway] Fix invalid cluster causing gateway programming delay

---

.changelog/16647.txt
go.mod
go.sum
test/integration/consul-container/libs/cluster/builder.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/test/snapshot/snapshot_restore_test.go

This adds an integration test to cover the use case of taking and restoring a snapshot on a consul cluster, it also run this test case using both raft log store backends (`boltdb` and `wal`).

Snapshot restore tests

---

.changelog/16675.txt
agent/proxycfg/upstreams.go
agent/xds/clusters.go

1.15 and 1.14 backport of https://github.com/hashicorp/consul/pull/16673

[release/1.15.x] peering: peering partition failover fixes

---

.changelog/16693.txt
agent/proxycfg/upstreams.go
agent/xds/clusters.go

manual release/1.14.x backport due to backport from 1.15 not working

[release/1.14.x] peering: peering partition failover fixes

---

website/content/docs/k8s/helm.mdx

This was causing linter errors, e.g. https://github.com/hashicorp/consul/actions/runs/4481350101/jobs/7877923133

Helm docs without developer.hashicorp.com prefix

---

test/integration/consul-container/test/snapshot/snapshot_restore_test.go

This add a check before reading the KV entries from the new cluster (restored from a snapshot) in the snapshot restore test. The extra check would verify that the follower is caught up with the leader before reading logs as we would like to read those KV entry performing a stale read from the follower to ensure that the logs were replicated to the follower correctly.
This is to avoid some flakes observed in CI as [this](https://app.circleci.com/pipelines/github/hashicorp/consul/54329/workflows/b15eff84-ef76-48db-ace3-5cbf5ab14c79/jobs/1284077/tests#failed-test-1).

add extra resiliency to snapshot restore test

---

agent/config/builder.go

Fail gracefully if the server port provided is 0.
Consul allows some ports, like gRPC, https, to be -1, meaning the ports are disabled. However, if the server port (8300) or 
serf port is disabled, consul seems not working properly. So this PR disallows disabling these 2 ports.
https://github.com/hashicorp/consul/issues/16715

fix: gracefully fail on invalid port number

---

.changelog/16729.txt
agent/consul/prepared_query_endpoint.go
agent/consul/prepared_query_endpoint_test.go

* This fixes a bug that caused the PQ query state to get overridden when failing over to a cluster peer.

Fix Prepared Query Peering Failover Bug

---

agent/consul/rate/handler.go

@dhiaayachi  noticed `Tenancy` category is not referred anywhere which prompted me to look into this. 
The only place I found tenancy referred is in gRPC `ResourceService`. Resource category is already added to the relevant proto file and is included in the `OperationCategory` struct hence we don't need Tenancy.
Resource proto file: https://github.com/hashicorp/consul-enterprise/blob/main/proto-public/pbresource/resource.proto

fix: remove unused tenancy category from rate limit spec

---

.release/ci.hcl

This part of the workflow bumps the version to reflect the next patch release ([example](https://github.com/hashicorp/consul/commit/b42941fd5b40da72d121482047bdb0ebcbd1ad91)); however, we use a specific branch for each patch release and so never wind up cutting a release directly from the `release/1.15.x` (for example) where this is intended to work.
The end result is that our `release/1.15.1` branch gets bumped to have a version of `1.15.2` which is non-sensical.
> Emily Neil
hey Chris and Nathan! yeah the CRT automation for version bumping was designed specifically for a singular release branch system, so it can't really support listening for a release and updating 1.15.x  at the moment unfortunately. I think the best work around for the moment would be to remove the bump-version block …

Remove version bump from CRT workflow

---

.github/workflows/build-distros.yml

Signed-off-by: Dan Bond <danbond@protonmail.com>
Fixes an incorrect commit merged in https://github.com/hashicorp/consul/pull/16718

ci: use correct build-distros workflow

---

agent/consul/client_test.go

noticed via their port still in use messages.

tests instantiating clients w/o shutting down

---

api/config_entry.go
api/config_entry_test.go
website/content/docs/connect/config-entries/proxy-defaults.mdx

add failover policy to ProxyConfigEntry in api to be able to use it in consul-k8s

add failover policy to ProxyConfigEntry in api

---

.github/scripts/changelog_checker.sh
.github/workflows/changelog-checker.yml

Manual backport of https://github.com/hashicorp/consul/pull/16681
N/A
N/A

Manual Backport: Fix bug in changelog checker where bash variable is not quoted (#16681)

---

agent/consul/fsm/snapshot_test.go
agent/consul/state/catalog.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go

Allocate virtual ips for resolver/router/splitter config entries if there isn't already one for the service. This is part of upcoming enhancements for transparent proxy. A virtual IP also now won't be deallocated unless there are no instances left and no resolver/router/splitter config entry for a service.

state-store: allocate / deallocate VIP on config-entry writes

---

ui/packages/consul-ui/.gitignore
ui/packages/consul-ui/README.md
ui/packages/consul-ui/package.json

We’ll be using [Yalc](https://github.com/wclr/yalc) to work with in development versions of the toolkit in the different consul apps. To do this we should add scripts for linking the yalc builds and subsequently removing the yalc builds to restore the package json.
**AC**
Setup script for linking `yalc` builds in cloud-ui consul engine and in consul-ui
Setup script for removing `yalc` builds from both repos
https://user-images.githubusercontent.com/10027860/228075494-5128671d-977c-4adb-8c45-900334ec4300.mov
- run `npm i yalc -g` or `yarn global add yalc`
- clone `https://github.com/hashicorp/consul-ui-toolkit`
- run `yalc publish` from the `consul-ui-toolkit/toolkit` folder
- from `consul root` `cd ui/packages/consul-ui`
- run `yarn toolkit:link` - it will add `yalc.lock` file to the …

add scripts for testing locally consul-ui-toolkit

---

api/config_entry_rate_limit_ip.go

Exporting `ReadWriteRatesConfig` from the API package that can be referenced in K8s.

fix: export ReadWriteRatesConfig struct as it needs to referenced from consul-k8s

---

test/integration/consul-container/test/upgrade/README.md
test/integration/consul-container/test/upgrade/acl_node_test.go
test/integration/consul-container/test/upgrade/basic_test.go
test/integration/consul-container/test/upgrade/healthcheck_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
test/integration/consul-container/test/upgrade/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering_http_test.go

Synchronize upgrade tests from ENT, namely for these two PRs:
https://github.com/hashicorp/consul-enterprise/pull/4886
https://github.com/hashicorp/consul-enterprise/pull/4768
I simply copied over the whole `upgrade` folder, minus an ENT-specific test file.

port ENT upgrade tests flattening

---

agent/grpc-external/services/resource/watch.go
internal/storage/conformance/conformance.go
internal/storage/inmem/watch.go
internal/storage/storage.go

While reviewing the existing controller code, I realized that when implementing watches, I'd forgotten that we need to call `Unsubscribe` on the event publisher subscription to free its resources when we're done.

storage: fix resource leak in `Watch`

---

agent/consul/state/usage.go
agent/consul/state/usage_oss.go
agent/consul/state/usage_test.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/consul/xdscapacity/capacity.go
agent/structs/structs.go
agent/structs/structs_oss.go

The service instances table was added to 1.15.0 which keeps a record of the number of service instances per cluster. 
For Census reporting the service instances metrics depends on this table which needs to be backported to 1.14.x and 1.13.x versions.
None
Related 1.15.0 PR: https://github.com/hashicorp/consul/pull/16205

feat: backport service instances table

---

.changelog/16776.txt
agent/consul/leader_peering_test.go
agent/consul/peering_backend.go
agent/consul/peering_backend_test.go

Currently, if an acceptor peer deletes a peering the dialer's peering will eventually get to a "terminated" state. If the two clusters need to be re-peered the acceptor will re-generate the token but the dialer will encounter this error on the call to establish:
>failed to get addresses to dial peer: failed to refresh peer server addresses, will continue to use initial addresses: there is no active peering for "<<<ID>>>"
This is because in `exchangeSecret().GetDialAddresses()` we will get an error if fetching addresses for an inactive peering. The peering shows up as inactive at this point because of the existing terminated state.
Rather than checking whether a peering is active we can instead check whether it was deleted. This way users do not need to delete terminated peerings in the …

Allow dialer to re-establish terminated peering

---

agent/consul/state/usage.go
agent/consul/state/usage_oss.go
agent/consul/state/usage_test.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/structs/structs.go
agent/structs/structs_oss.go

The backport label on `1.14` PR did not generate a backport PR here so I have to create this manually.
Also, some of the changes were not easily back portable:
- The `ServiceUsage` method in `state->usage.go` function does not take `memdb.WatchSet` parameter
- The `firstUsageEntry` function also does not take`memdb.WatchSet` param
- The `xdscapacity` directory does not exist in `1.13.x`
Cherry-picked commit from release 1.14.x: https://github.com/hashicorp/consul/pull/16819

[Manual backport] Net 3478/backport service instances table

---

website/content/docs/agent/telemetry.mdx

This is part of an effort to raise awareness that you need to monitor your mesh CA if coming from an external source as you'll need to manage the rotation.

CA mesh CA expiration to it's own section

---

.changelog/16776.txt
agent/consul/leader_peering_test.go
agent/consul/peering_backend.go
agent/consul/peering_backend_test.go

Backport to 1.14 of #16776 so that peerings can be more easily repaired across HCP-supported versions.
Currently, if an acceptor peer deletes a peering the dialer's peering will eventually get to a "terminated" state. If the two clusters need to be re-peered the acceptor will re-generate the token but the dialer will encounter this error on the call to establish:
"failed to get addresses to dial peer: failed to refresh peer server addresses, will continue to use initial addresses: there is no active peering for "<<<ID>>>""
This is because in `exchangeSecret().GetDialAddresses()` we will get an error if fetching addresses for an inactive peering. The peering shows up as inactive at this point because of the existing terminated state.
Rather than checking whether a peering is active we can …

[1.14.x] Allow dialer to re-establish terminated peering

---

agent/consul/usagemetrics/usagemetrics.go

I noticed that all metric labels in 1.13.x are prefixed with consul so matching the pattern

fix: metrics labels are prefixed by consul in 1.13.x

---

.github/workflows/go-tests.yml

Backport of ci: increase deep-copy and lint-enum jobs to use large runner as they hang in ENT into release/1.15.x

---

.github/workflows/broken-link-check.yml
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/intentions/create-manage-intentions.mdx

Omit false positives (403 errors) from the 404 checker.
1. download lychee
2. cd to consul repo's root folder
3. run the following
`lychee ./website/content/docs/ --base https://developer.hashicorp.com/ --exclude-all-private --exclude '\.(svg|gif|jpg|png)' --exclude 'manage\.auth0\.com' --accept 403 --max-concurrency=24 --no-progress --verbose`
Notes:
https://github.com/lycheeverse/lychee/blob/master/docs/TROUBLESHOOTING.md#unexpected-status-codes

Omit false positives from 404 checker

---

.github/workflows/go-tests.yml
.github/workflows/reusable-dev-build.yml

ci: add arm64 testing into release/1.15.x

---

.github/scripts/get_runner_classes.sh
.github/workflows/build-artifacts.yml
.github/workflows/build-distros.yml

ci: increase ENT runner size for xl to match OSS.  have build-distros use  xl to match CircleCI

---

agent/consul/leader_metrics.go
agent/consul/leader_metrics_test.go
agent/metrics.go

The old setting of 24 hours was not enough time to deal with an expiring CA. Changing it to 30 days to give a reasonable amount of time to do the rotation.

log warning about CA expiring sooner

---

website/content/docs/agent/telemetry.mdx

Related to #16747, this adds the agent.tls certificate to the section on important cert's that need monitoring.

highlight the agent.tls cert metric with CA ones

---

website/content/docs/upgrading/instructions/index.mdx
website/content/docs/upgrading/upgrade-specific.mdx

The current upgrade instructions have the following weaknesses:
- They imply more upgrades are needed than necessary (too restrictive with possible paths)
- 1.15 isn't accounted for
[Revised version jump instructions page
](https://consul-dazu1a7ur-hashicorp.vercel.app/consul/docs/upgrading/instructions)

docs: improve upgrade path guidance

---

sdk/testutil/server.go

`noCleanup` exists in the test code to preserve the data after unit test run.
https://github.com/hashicorp/consul/blob/430df05e61a017627f4e5eb5e38513840f6172d1/sdk/testutil/io.go#L12
`noCleanup` has been used in someplace like 
https://github.com/hashicorp/consul/blob/430df05e61a017627f4e5eb5e38513840f6172d1/sdk/testutil/io.go#L18

Test: add noCleanup to TestServer stop

---

agent/structs/config_entry_routes.go
agent/structs/config_entry_routes_test.go

We currently don't validate that routes cannot have duplicate parents. This change introduces validations to ensure parents are unique according to the k8s gateway spec https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.CommonRouteSpec
Of note: we reached out to the k8's sig for clarification on some potential edge cases: https://github.com/kubernetes-sigs/gateway-api/issues/1925
depending on the result of that this code may change in the future.
Run the `./start.sh` script from here https://github.com/jm96441n/consul-experiments/tree/main/vm/basic-api-gateway (this assumes you have run the `convoy-build` script at the root of the repo and have built a consul image locally). You will see the route be successfully added, rebuild the images with the changes …

APIGW: Routes with duplicate parents should be invalid

---

.circleci/config.yml

This is blocked by the following remaining issues with go-tests on GHA:
- configuring the GHA version as the required github check

ci: remove verify-ci from circleci

---

.github/workflows/test-integrations.yml

Based off https://github.com/hashicorp/consul/tree/jm/test-integrations branch (the GHA port of our CI). Bumping the vault version numbers in it.

update vault integration testing versions

---

.changelog/16957.txt
agent/configentry/merge_service_config.go
agent/configentry/resolve.go
agent/consul/config_endpoint_test.go
agent/proxycfg-glue/resolved_service_config.go
agent/service_manager_test.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/structs/structs.deepcopy.go
website/content/docs/upgrading/upgrade-specific.mdx

In 1.14 the service-defaults config entry lacked the `peer` field on upstream overrides and applied the override config purely based on the `name` field matching. For 1.15, we introduced the new `peer` field and also maintained the existing behavior. If `peer` was not specified anywhere in the config entry, we assume it was not peering aware and fell back to the compatibility mode. https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#service-defaults-overrides-for-upstream-peered-services
This commit removes that deprecated backwards-compatibility behavior. Now in 1.16, it is necessary to specify the `peer` field in order for upstream overrides to apply to a peer upstream.

Remove deprecated service-defaults upstream behavior.

---

website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Docs update for: https://github.com/hashicorp/consul/pull/16957

Update docs for service-defaults overrides.

---

website/content/docs/enterprise/admin-partitions.mdx

This is not a requirement when using APs because each AP has its own auth method so it's okay if the names overlap.

Remove global.name requirement for APs

---

test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/builder.go
test/integration/consul-container/libs/cluster/container.go

This PR allows configuring Node name, node Id, and external consul data to copy from for the consul container.
With this change, we can do upgrade test if a newer version of consul can use the data generated from an older version of consul.

upgrade test: config nodeName, nodeid, and inherited persistent data for consul container

---

agent/agent.go
agent/agent_oss_test.go
agent/config/builder_oss.go
agent/config/builder_oss_test.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_oss_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/config.go
agent/consul/server.go
agent/consul/server_oss.go
agent/consul/server_oss_test.go

Manually backporting: https://github.com/hashicorp/consul/pull/16890

Backport of feat: add reporting config with reload

---

website/content/docs/troubleshoot/common-errors.mdx

This PR adds error messages associated with rate limiting to the troubleshooting page. The content was missing and resulted in bad links on the source page. I also made a few minor changes to the troubleshooting page for style consistency.

added missing error message content to troubleshooting

---

website/content/docs/connect/config-entries/service-intentions.mdx

This PR adds an introductory statement to the configuration model section on the service intentions configuration reference page. This is for consistency.

added an intro statement for the SI conf entry confiration model

---

CHANGELOG.md
website/content/docs/release-notes/consul/v1_15_x.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Follow-up PR to https://github.com/hashicorp/consul/pull/16823, given the recent release of a fix in v1.15.2.

docs: update docs related to GH-16779

---

acl/resolver/danger.go
agent/consul/server.go
agent/grpc-external/services/peerstream/subscription_view.go
agent/grpc-internal/pipe.go
agent/grpc-internal/pipe_test.go

This PR adds an instance of the Resource Service that can be interacted with in-process, without going over the network, and without authentication/authorization. It will be used for purely internal operations (e.g. by controllers).
Manually tested by adding an RPC to the server setup code, and logging the response.
I think this is the kind of thing that's best exercised by a full-stack integration test, once the rest of the controller runtime pieces are in-place.

server: wire up in-process Resource Service

---

.changelog/15987.txt
api/agent.go
api/agent_test.go

This PR adds support for setting QueryOptions on the force-leave endpoints.
We are using Consul <> Vault ACL tokens and in-need of providing token for this purpose.
If it not provided a response similar to the below is given: 
```< date: Mon, 16 Jan 2023 22:23:57 GMT
< content-type: text/plain; charset=utf-8
< content-length: 113
< vary: Accept-Encoding
< x-consul-default-acl-policy: deny
<
* Connection #0 to host consul.server.net left intact
Permission denied: token with AccessorID 'dacd6887-313d-cb3f-1820-0994797e4375' lacks permission 'operator:write'
```
https://github.com/hashicorp/consul/issues/16805

api: enable query options on agent force-leave endpoint

---

agent/hcp/manager_test.go

Fix test race condition causing test flake.
```
=== RUN   TestManager_SendUpdate
panic: Fail in goroutine after TestManager_Run has completed
exec: go version
goroutine 35 [running]:
testing.(*common).Fail(0xc000484680)
/home/runner/actions-runner/_work/_tool/go/1.20.3/x64/src/testing/testing.go:933 +0xe5
testing.(*common).Errorf(0xc000484680, {0xc59347?, 0x40fd08?}, {0xc00049cac0?, 0x18?, 0x18?})
/home/runner/actions-runner/_work/_tool/go/1.20.3/x64/src/testing/testing.go:1050 +0x65
github.com/stretchr/testify/mock.(*Mock).fail(0xc0004ae140, {0xc59347?, 0x4?}, {0xc00049cac0?, 0x2?, 0x2?})
/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.2/mock/mock.go:330 +0xeb
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0004ae140, {0xe1cbd3, 0x10}, {0xc00061a000, 0x2, 0x2}) …
```

Don't send updates twice

---

.circleci/config.yml
.github/workflows/test-integrations.yml

This configuration currently works in ENT but fails in OSS.  GitHub is helping us look at it.  The docker based tests in `compatability-tests` and `upgrade-test` fail with intermittent communication failures when docker containers need to talk to each other as is the case for 3 servers joining in a cluster.
As part of troubleshooting that issue, most iteration has been done on [this](https://github.com/hashicorp/consul/tree/jm/hack-int) which comments out all of the envoy, nomad, and vault stuff so that it only runs the two jobs with docker based tests.

ci: add test-integrations

---

.circleci/config.yml
.github/workflows/test-integrations.yml

Manual Backport of test-intergrations into release/1.15.x branch

---

.changelog/17048.txt
lib/map_walker.go
lib/map_walker_test.go

This PR fixes a bug with the mapwalk decoding logic used on the client agents for things like config entries and resolved service configs. Currently, if there is a struct stored within a `map[string]interface{}`  with at least one field set and one pointer field unset/`nil` (such as `EnforcingConsecutive5xx` in the `PassiveHealthCheck` struct), the mapwalk logic here would attempt to call `reflect.Value.Type()` which is invalid for a nil pointer and we'd get `reflect: call of reflect.Value.Type on zero Value`.
Replication steps:
1. Set up a server and client agent
2. Register the following service config:
```json
{
"Kind": "service-defaults",
"Name": "frontend",
"Protocol": "http",
"UpstreamConfig": {
"Defaults": {
"ConnectTimeoutMs": 15000,
"PassiveHealthCheck": {
"MaxFailures": 1000000 …
```

Avoid decoding nil pointer in map walker

---

.github/workflows/test-integrations.yml

Currently the test-integrations workflow throws several warnings about not having any logs to upload.  Removing this for now as this directory is empty.  We can add back in and configure if needed and given the proper directory to upload.  CircleCI would not issue warnings if this directory was empty, so it is possible this was not in use in any way.

ci: remove worklogs upload toget rid of warning

---

test/integration/consul-container/test/consul_envoy_version/consul_envoy_version.go

This fixes an unnecessary string conversion linter failure introduced in https://github.com/hashicorp/consul/pull/17060
```
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/rboyer/src/consul/test/integration/consul-container /home/rboyer/src/consul/test/integration /home/rboyer/src/consul/test /home/rboyer/src/consul /home/rboyer/src /home/rboyer /home /]
INFO [config_reader] Used config file ../../../.golangci.yml
INFO [lintersdb] Active 9 linters: [depguard forbidigo gofmt gomodguard govet ineffassign staticcheck unconvert unparam]
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|name|exports_file|files|imports|types_sizes) took 166.718028ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 2.455952ms
INFO …
```

fix the linter

---

agent/consul/state/config_entry.go
agent/structs/config_entry_sameness_group.go
api/config_entry_sameness_group.go

Before this change, we were not fetching service resolvers (and therefore service defaults) configuration entries for services on members of sameness groups.

Fix a bug with sameness group disco chain config entry fetching

---

.github/workflows/test-integrations.yml

In 1.13, there are only two compatibility test packages.  So when a generate matrix job has a TOTAL_RUNNERS of 5 but there are only 2 packages, the process hangs.  This PR changes the runner count to 2 in this case.  
Another issue that occurs that is fixed in this PR is that when you specify TOTAL_RUNNERS = 4, you will actually split across 5 runners.  (The same occurs with any number you set TOTAL_RUNNERS to.  You will actually get 1 greater.)

ci: fix test splits that have less test packages than runner count from hanging

---

agent/consul/fsm/commands_oss.go
agent/consul/state/catalog.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go
agent/structs/structs.go

Follow-up to #16760 - add a manual virtual IPs field that can be used to manually assign multiple virtual IPs to a service, which will be returned through discovery chain lookups by transparent proxies.

Add manual virtual IP support to state store

---

.changelog/17081.md
.changelog/17081.txt
go.mod
go.sum

This pulls in https://github.com/hashicorp/raft/pull/541 which fixes a performance issue in our Raft implementation. See that PR for a very in-depth analysis of the issue and the change impacts. 
The fix was tested extensively in Consul locally as part of the wal testing for 1.15. Results of that are given in the PR linked.
I'm going to backport to 1.15 since it should be easy to and will allow people testing WAL in 1.15 to reproduce our results without this performance anomaly without a major upgrade.
* https://github.com/hashicorp/raft/pull/541 - the Raft fix PR we're pulling in
* ~[ ] updated test coverage~ (not applicable)

Bump raft to 1.5.0

---

agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_test.go

Partition and namespace must be "default"
Peername must be "local"

De-scope tenenacy requirements to OSS only for now.

---

agent/consul/state/intention.go

Recent changes for tproxy enhancements made a change to the intention topology lookup so that virtual services (discovery chains) were included in results. This was done to handle failover scenarios where all services instances may disappear, but a discovery-chain may still exist that should be referenced.
While not a direct issue, the intention lookups for downstream services were including virtual services in the results, which resulted in a broken unit test. Since downstream lookups will not necessarily need to be concerned with virtual services ever, this commit ensures that virtual services are only included in upstream lookups, rather than modifying the test itself.

Fix virtual services being included in intention topology as downstreams

---

.github/workflows/test-integrations.yml

This PR removes 2 unnecessary workflow steps from the `envoy-integration-test` job in the `test-integrations` workflow. This is no longer needed due to the removal of the legacy load test workflows and was accidentally migrated over.

CI: remove uneeded AWS creds from test-integrations

---

website/content/docs/k8s/k8s-cli.mdx

Envoy endpoint is not a flag in k8s but was added in documentation. 
Enterprise PR: https://github.com/hashicorp/consul-enterprise/pull/5228
* NA updated test coverage

remove envoy endpoint flag from k8s docs

---

website/content/docs/connect/distributed-tracing.mdx

Request for clarification of tracing documentation for Consul around OpenTelemetry. You can use the libraries, the proxies do not emit OTLP spans until Envoy fully supports it.

Clarify OpenTelemetry support for tracing

---

internal/storage/inmem/watch.go

See the comment in the code for more information.
It's hard to create a test-case for this bug because it's so timing/scheduler dependent, but it was intermittently causing the tests on my WIP controller branch to flake.

storage: fix bug where `WatchList` would (rarely) return duplicate events

---

agent/consul/server.go
agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/list_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/watch_test.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go
internal/controller/api.go
internal/controller/controller.go
internal/controller/lease.go
internal/controller/manager.go
internal/controller/supervisor.go
internal/controller/supervisor_test.go
internal/resource/demo/controller.go
internal/resource/demo/demo.go
lib/retry/retry.go
logging/names.go

This is the first piece of the new resource-based controller runtime. It introduces a `Manager` type that will execute controllers on the cluster leader, and restart them (with exponential backoff) if they crash. 🤹🏻
The actual controller implementation and the rest of the builder API will be done in subsequent PRs.
There are unit tests for the `supervisor` type which handles the bulk of the logic. Also manually tested by observing the logs in `consul agent -dev`.

Controller Supervision

---

test/integration/consul-container/test/snapshot/snapshot_restore_test.go

I found the snapshot container test was failing a lot with a nil pointer panic in the test runner itslelf.
It seems like there is some non-determinism in exactly when the follower has the snapshot installed - if we try to read from it before the snapshot install completes we get a nil key and panic.
This fixes that flake with a retry on the first Get from the follower so we will "wait" for a few seconds for the snapshot install to happen before running through and asserting all the keys are present.

De-flake snapshot test

---

.github/workflows/build-artifacts.yml
.github/workflows/build-distros.yml
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

The current `success` jobs are sometimes being skipped when there are failures in dependent jobs.  In these cases, the branch protection rules that use the required checks are treating this as a non-failure and allowing PRs to be merged even though there are failures.  an example is here: https://github.com/hashicorp/consul/actions/runs/4797440861

ci: adding in fix for success jobs getting skipped.

---

.github/workflows/build-distros.yml
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

Manual backport of this commit: https://github.com/hashicorp/consul/pull/17130/commits/e5ef91603be1e4c03f7658d0c5a1fa44dd5609f3

ci:backport of success job being skipped - 1.13

---

.github/workflows/build-artifacts.yml
.github/workflows/build-distros.yml
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

Manual backport of this commit: https://github.com/hashicorp/consul/pull/17130/commits/e5ef91603be1e4c03f7658d0c5a1fa44dd5609f3

ci:backport of success job being skipped - 1.15

---

agent/grpc-external/services/resource/testing/testing.go

This PR adds a helper method for running a Resource Service for the duration of a test. I'm using it in my WIP controller branch, and I think it'll be what most controller tests will end up using.

testing: `RunResourceService` helper

---

agent/structs/aclfilter/filter.go

These logs let operators know which service and node is resulting in the entity being dropped.

Add ACL Filter Logs

---

.changelog/17137.txt
api/catalog.go
api/peering.go

When the current `api` client is used for two endpoints (catalog register, peering) it sends a stray `{... "Locality": "", ...}` to a Consul server because the field is not marked `omitempty`.
If this lands on an older Consul server or client it will reject the request completely because of the unknown field.
Regressed in : https://github.com/hashicorp/consul/pull/16581

api: ensure empty locality field is not transmitted to Consul

---

.github/workflows/test-integrations.yml
test/integration/consul-container/libs/cluster/app.go
test/integration/consul-container/libs/service/assets/Dockerfile-consul-envoy
test/integration/consul-container/libs/service/assets/tproxy-startup.sh
test/integration/consul-container/libs/service/common.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/libs/topology/service_topology.go
test/integration/consul-container/test/basic/connect_service_test.go
test/integration/consul-container/test/tproxy/tproxy_test.go
test/integration/consul-container/test/upgrade/ingress_gateway_grpc_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
test/integration/consul-container/test/upgrade/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering_http_test.go
test/integration/consul-container/test/wanfed/wanfed_peering_test.go

This is a basic integration test for TProxy:
* Create 2 "client" pods for the static-client / static-server. Separate pods are needed because iptables rules apply for the network namespace
* Configure the test container with necessary permission for the iptables command:
* NET_ADMIN container capability. Required to run iptables in a container.
* sudo, so that the envoy user can run iptables commands
* A tproxy-startup.sh script that runs the `consul connect redirect-traffic` command to apply iptables rules
This took some fiddling to setup, so there are some workarounds for the moment:
* DNS queries don't automatically redirect to Consul DNS (on my machine)
* Because the Consul client and envoy share a network namespace, the Consul inbound ports and the Consul user id are excluded from …

TProxy integration test

---

.golangci.yml
agent/grpc-external/services/resource/delete.go

Syncs `.golangci.yml` file missed in the original protobuf modernization from [ENT](https://github.com/hashicorp/consul-enterprise/pull/4033/files#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9)

Sync .golangci.yml from ENT

---

.changelog/17179.txt
agent/configentry/merge_service_config.go
agent/configentry/merge_service_config_test.go

Partitioned downstreams with peered upstreams could not properly merge central config info (i.e. `proxy-defaults` and `service-defaults` things like mesh gateway modes) if the upstream had an empty `DestinationPartition` field in Enterprise.
Due to data flow, if this setup is done using Consul client agents the field is never empty and thus does not experience the bug.
When a service is registered directly to the catalog as is the case for `consul-dataplane` use this field may be empty and and the internal machinery of the merging function doesn't handle this well.
This PR ensure the internal machinery of that function is referentially self-consistent.
The easy way to observe the breakage is arrange for:
* peering with at least the calling side being in a non-default partition
* one …

peering: ensure that merged central configs of peered upstreams for partitioned downstreams work

---

.changelog/17185.txt
agent/xds/clusters.go

We frequently call `injectSANMatcher` [like this](https://github.com/hashicorp/consul/blob/main/agent/xds/clusters.go#L317-L322). The code panics when `commonTLSContext` is `nil` inside `injectSANMatcher` [here](https://github.com/hashicorp/consul/blob/main/agent/xds/clusters.go#L1430). `makeCommonTLSContext` returns `nil` [when it isn't passed root pems](https://github.com/hashicorp/consul/blob/main/agent/xds/listeners.go#L2629-L2631).

fix panic in `injectSANMatcher` when `tlsContext` is `nil`

---

.changelog/17179.txt
agent/configentry/merge_service_config.go
agent/configentry/merge_service_config_test.go

Backport of #17179 into release/1.15.x

[1.15.x] peering: ensure that merged central configs of peered upstreams for partitioned downstreams work

---

agent/proxycfg-glue/resolved_service_config.go

Since the auth context is not used when evaluating permissions, service resolution is failing whenever it should be evaluated in a non-default partition.

Use auth context when evaluating permissions for service config resolution

---

.changelog/17138.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go

When using vault as a CA and generating the local signing cert, try to enable the pki endpoint's auto-tidy feature with it set to tidy expired issuers.

enable auto-tidy expired issuers in vault (as CA)

---

agent/consul/controller/controller.go
agent/consul/controller/controller_test.go
agent/consul/controller/queue/defer.go
agent/consul/controller/queue/queue.go
agent/consul/controller/queue/rate.go
agent/consul/controller/queue/rate_test.go
agent/consul/controller/queue_test.go
agent/consul/gateways/controller_gateways_test.go

Makes the `WorkQueue` generic (and moves into a `queue` sub-package) so that it can be reused in the new resource-based controller implementation.

controller: make the `WorkQueue` generic

---

.github/workflows/test-integrations.yml

Use docker image from `docker.mirror.hashicorp.services` to avoid docker login in GHA
Also add image name as parameter to `cluster.StandardUpgrade(utils.GetTargetImageName(), tc.targetVersion)`, because the image we upgrade to is `consul:locally`, which is different than the latest image `docker.mirror.hashicorp.services/docker:1.15` for example.

upgrade test: use docker.mirror.hashicorp.services to avoid docker login

---

agent/consul/server.go
internal/catalog/exports.go
internal/catalog/internal/types/dns_policy.go
internal/catalog/internal/types/health_checks.go
internal/catalog/internal/types/health_status.go
internal/catalog/internal/types/node.go
internal/catalog/internal/types/service.go
internal/catalog/internal/types/service_endpoints.go
internal/catalog/internal/types/types.go
internal/catalog/internal/types/types_test.go
internal/catalog/internal/types/virtual_ips.go
internal/catalog/internal/types/workload.go
internal/mesh/exports.go
internal/mesh/internal/types/proxy_configuration.go
internal/mesh/internal/types/types.go
internal/mesh/internal/types/types_test.go
internal/mesh/internal/types/upstreams.go

This PR takes the protobuf type definitions for catalog and mesh resources from #17123 and causes them to be registered with the resource services type registry. In particular the following new resource types are being added:
* `catalog.v1alpha1.workload`
* `catalog.v1alpha1.service`
* `catalog.v1alpha1.serviceendpoints`
* `catalog.v1alpha1.virtualips`
* `catalog.v1alpha1.node`
* `catalog.v1alpha1.healthstatus`
* `catalog.v1alpha1.healthchecks`
* `catalog.v1alpha1.dnspolicy`
* `mesh.v1alpha1.proxyconfiguration`
* `mesh.v1alpha1.upstreams`
* Code to perform validation at admission time of the new resources.
* Code to authorize the use of the new resources
* Integration tests to ensure that the new types are properly registered with a real Consul server.
Some additional unit tests were …

Register new catalog & mesh protobuf types with the resource registry

---

.github/workflows/backport-assistant.yml

A new patch for `backport-assistant` was released to deal with a race in creating the new branch and pushing the PR. For a single PR, this may appear as an error pushing a reference that doesn't exist. For multiple backports, I suspect that it manifests itself as applying the cherry-picked commits on top of the previously checked-out branch.

chore(ci): fix backport assistant branch creation race

---

.github/workflows/test-integrations.yml

* remove test splitting from compatibility-integration-tests
* enable on push
* remove ipv6 loopback fix
* re-add ipv6 loopback fix
* remove test splitting from upgrade-integration-tests
* remove test splitting from upgrade-integration-tests
* put test splitting back in for upgrade tests
* upgrade-integration tests-o ne runner no retries

manual backport of ci: remove test splitting for compatibility tests into release/1.15.x

---

agent/consul/server.go
internal/controller/api.go
internal/controller/api_test.go
internal/controller/controller.go
internal/controller/doc.go
internal/controller/lease.go
internal/controller/manager.go
internal/resource/demo/controller.go
internal/resource/demo/controller_test.go
internal/resource/demo/demo.go

Introduces the new controller runtime for resources 🎉 
The API is pretty heavily inspired by [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder), and it leans on the awesome work the API GW folks did to support config entry-based controllers (hat tip @andrewstucki @mikemorris @nathancoleman @t-eckert @sarahalsmiller), including reusing the queue implementation.
There are unit tests! There's also a controller for our dummy `demo.v2.artist` resource type that you can see in-action if you spin up a server in dev mode and poke it with `grpcurl`.
```shell
$ grpcurl -d @ \
-plaintext \
-import-path proto-public \
-import-path proto/private \
-proto proto/private/pbdemo/v2/demo.proto \
-proto proto-public/pbresource/resource.proto \
127.0.0.1:8502 \ …
```

Controller Implementation 🏗

---

agent/consul/controller/queue/defer.go
agent/consul/controller/queue/queue.go
agent/consul/controller/queue/rate.go
agent/consul/controller/queue/rate_test.go
agent/consul/controller/queue_test.go
agent/consul/controller/reconciler.go
internal/controller/api.go
internal/controller/controller.go

This is an efficiency improvement for #17069.
The `WorkQueue` data structure has support for de-duplicating items, such that attempting to `Add` an item that is already in the queue (and hasn't yet been picked up for processing) is a no-op. Unfortunately, this relied on using the item itself as a map key, which didn't really work for the new `Request` type as it contains a pointer to a resource ID, so equivalent `Request`s might not hash to the same value.
This PR extends the `ItemType` interface with a `Key` method that is called to get a deterministic map key instead.
Run `consul agent -dev -log-level=TRACE` and write a demo artist resource.
Reconciler is called many times (in response to the artist controller creating album resources).
```
2023-04-27T14:24:21.663+0100 [TRACE] …
```

controller: deduplicate items in the queue 👯‍♀️

---

.changelog/17241.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go

1. The datacenter was not being provided to a proxycfg query, which resulted in bypassing agentless query optimizations and using the normal API instead.
2. The health rpc endpoint would return a zero index when insufficient ACLs were detected. This would result in the agent cache performing an infinite loop of queries in rapid succession without backoff.

Fix multiple issues related to proxycfg health queries.

---

agent/proxycfg/connect_proxy.go
agent/proxycfg/state_test.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
agent/structs/structs.go
agent/structs/structs_test.go
agent/xds/testdata/listeners/hcp-metrics.latest.golden
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/hcp-metrics.golden

UNIX domain socket paths are limited to 104-108 characters depending on the OS. This limit was quite easy to exceed when testing the feature on Kubernetes, due to how proxy IDs encode the Pod ID eg:
`metrics-collector-59467bcb9b-fkkzl-hcp-metrics-collector-sidecar-proxy`
To ensure we stay under the lower 104 character limit this commit makes a couple changes:
- Use a b64 encoded SHA1 hash of the namespace + proxy ID to create a short and deterministic socket file name.
- Add validation to proxy registrations and proxy-defaults to enforce a limit on the socket directory length.
* Added unit tests
* Manual testing with long socket path at and above limit

Hash namespace+proxy ID when creating socket path

---

.changelog/17241.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
agent/proxycfg/upstreams.go

Fix multiple issues related to proxycfg health queries. (#17241)

---

.changelog/17236.txt
agent/consul/server.go
snapshot/snapshot.go
website/content/commands/snapshot/save.mdx

snapshot: some improvments to the snapshot process
- Add `raft` to the snapshot logger because the log messages are from raft package, making it consistent with other snapshot logs like `starting snapshot up to`, which are from the raft package as well. Also it allows users know where to search for the logger message
```
// before
2023-05-08T10:10:19.954-0400 [INFO]  agent.server.raft: starting snapshot up to: index=30
2023-05-08T10:10:19.954-0400 [INFO]  agent.server.snapshot: creating new snapshot: path=/tmp/dc-2-consul-server-1/raft/snapshots/3-30-1683555019954.tmp
2023-05-08T10:10:19.967-0400 [INFO]  agent.server.raft: snapshot complete up to: index=30
// after
2023-05-08T10:04:20.361-0400 [INFO]  agent.server.raft: starting snapshot up to: index=25
2023-05-08T10:04:20.361-0400 [INFO] …
```

snapshot: some improvments to the snapshot process

---

internal/resource/demo/controller.go
internal/resource/equality.go
internal/resource/equality_test.go

Most of the time, controllers *won't* want to consider status timestamps when doing dirty-checking. But in the `Write` endpoint, we want to ensure they're exactly the same object.

resource: optionally compare timestamps in `EqualStatus`

---

agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_test.go
agent/grpc-external/services/resource/watch.go
agent/grpc-external/services/resource/watch_test.go

Prevents panics when clients don't send the `Type` and `Tenancy` parameters.

resource: add missing validation to the `List` and `WatchList` endpoints

---

.github/workflows/go-tests.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations.yml

Currently our workflow and job information is uploaded to datadog.  Test information is not.  This PR uploads the junit results file to DataDog.
1. go to the`upload coverage` step of any test job. 
2. It will give you the below output and you can verify there.  Example job is: https://github.com/hashicorp/consul/actions/runs/4916931172/jobs/8781403486?pr=17206
```
Run datadog-ci junit upload --service "$GITHUB_REPOSITORY" $TEST_RESULTS_DIR/results.xml
Starting upload with concurrency 20. 
Will upload jUnit XML file /tmp/test-results/results.xml
service: hashicorp/consul
Uploading jUnit XML test report file in /tmp/test-results/results.xml
✅ Uploaded [1](https://github.com/hashicorp/consul/actions/runs/4916931172/jobs/8781403486?pr=17206#step:12:1) files in 0.199 seconds.
Syncing git …
```

ci:upload test results to datadog

---

build-support/scripts/protobuf.sh

This will ensure that we don't use stale `.ratelimit.tmp` files from prior runs or branches.

proto: clear out old ratelimit.tmp files before making new ones

---

.changelog/17270.txt
agent/consul/client_test.go
agent/consul/server_serf.go
agent/consul/subscribe_backend_test.go
agent/grpc-internal/client_test.go
agent/grpc-internal/handler_test.go
agent/grpc-internal/resolver/resolver.go
agent/grpc-internal/resolver/resolver_test.go
agent/peering_endpoint_test.go
agent/rpc/peering/service_test.go
agent/setup.go

manual backport of https://github.com/hashicorp/consul/pull/17270 to 1.15.x

[1.15.x] grpc: ensure grpc resolver correctly uses lan/wan addresses on servers

---

.changelog/17270.txt
agent/consul/client_test.go
agent/consul/server_serf.go
agent/consul/subscribe_backend_test.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/testing.go
agent/grpc-internal/client_test.go
agent/grpc-internal/handler_test.go
agent/grpc-internal/resolver/resolver.go
agent/grpc-internal/resolver/resolver_test.go
agent/peering_endpoint_test.go
agent/rpc/peering/service_test.go
agent/setup.go

manual backport of https://github.com/hashicorp/consul/pull/17270 to 1.13.x

[1.13.x] grpc: ensure grpc resolver correctly uses lan/wan addresses on servers

---

agent/consul/discovery_chain_endpoint_test.go
agent/consul/discoverychain/compile.go
agent/consul/state/catalog.go
agent/consul/state/catalog_schema.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/discovery_chain_endpoint_test.go
agent/structs/discovery_chain.go
agent/structs/structs.deepcopy.go

This PR adds logic to return virtual IP information for a service in the compiled discovery chain response (both the auto-assigned IP and any manually set VIPs from the endpoint in https://github.com/hashicorp/consul/pull/17294).

Attach service virtual IP info to compiled discovery chain

---

agent/xds/extensionruntime/runtime_config.go
envoyextensions/extensioncommon/list_envoy_extender.go
envoyextensions/extensioncommon/runtime_config.go

This PR introduces the following updates to the Envoy extensions framework:
- Add the service `Protocol` to the `RuntimeConfig` so that extensions have access to this information when they need to make protocol-specific decisions.
- Add a new `interface` type and `Extender` implementation for extensions that need to mutate lists of Envoy resources. This is required specifically for extensions that insert/modify Envoy network (TCP) filters. It is also required for extensions that need to add xDS resources to the Envoy config (instead of patching existing resources).
These updates are needed to support TCP filters for the Wasm and External Authorization extensions.

Add Network Filter Support for Envoy Extensions

---

test/integration/consul-container/libs/utils/version.go
test/integration/consul-container/test/upgrade/basic/basic_test.go
test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
test/integration/consul-container/test/upgrade/basic/healthcheck_test.go
test/integration/consul-container/test/upgrade/common.go
test/integration/consul-container/test/upgrade/peering/peering_http_test.go

Manually import the change from ent to oss to mitigate the drift after resolving some conflict in oss->ent pr

consul-container: mitigate the drift from ent repo

---

.changelog/17171.txt
agent/agent.go
agent/agent_test.go
agent/config/builder.go
agent/config/builder_test.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/config.go
agent/consul/server_metadata.go
agent/consul/server_metadata_test.go
website/content/docs/agent/config/config-files.mdx

Manual backport of https://github.com/hashicorp/consul/pull/17171/

[1.15.x] agent: prevent very old servers re-joining a cluster with stale data

---

.github/workflows/test-integrations.yml
test/integration/consul-container/test/upgrade/ingress_gateway_sds_test.go

Fix another on-the-fly image build in integ test and downsize the runner.
Since we change the image in integ test, the change is needed for the GHA config.

upgrade test: fix on-the-fly-image build and downsize runner

---

agent/consul/server.go
internal/catalog/exports.go
internal/catalog/internal/controllers/nodehealth/controller.go
internal/catalog/internal/controllers/nodehealth/controller_test.go
internal/catalog/internal/controllers/nodehealth/status.go
internal/catalog/internal/controllers/register.go
internal/controller/api.go
internal/controller/api_test.go
internal/resource/resourcetest/builder.go

This controller will monitor HealthStatus objects owned by Nodes and report aggregate health information in the Status of a Node. 
This builds on PR #17211. I did have to also squash merge the boxofrad/controller-implementation branch. Eventually that should be removed from this PR once it is merged. For now you can just look at the second non-squashed commit.
Unit tests are complete with 93.5% coverage. The uncovered lines shouldn't really be possible.
Multi-controller lifecycle integration test will come in a future PR.

Add Node health controller

---

agent/consul/rate/handler.go
agent/consul/rate/handler_oss.go
agent/consul/rate/handler_test.go

counterpart of the ent in oss

---

.github/workflows/test-integrations.yml

Integ test could be flaky because CI may fail to install the package in build image steps. This PR adds a retry to mitigate the flakiness.

integ-test CI: retry if fail to install packages

---

.changelog/17086.txt
command/agent/agent.go

When starting the consul agent, we output a status message which shows various parts of the configuration including `Gossip Encryption` and `Auto-Encrypt-TLS` configurations. 
This adds another field to the status showing whether or not ACLs are enabled.
```
make dev
./bin/consul agent -dev
```

Add ACLs Enabled field to consul agent startup status message

---

agent/proxycfg/testing_tproxy.go
agent/xds/listeners.go
agent/xds/testdata/listeners/transparent-proxy-with-resolver-redirect-upstream.latest.golden

This PR is a follow-up to previous work that adds logic in `xds` to pull virtual IPs from discovery chains - including both auto-assigned and manually set (such as cluster IPs via kubernetes).

Pull virtual IPs for filter chains from discovery chains

---

.github/workflows/test-integrations.yml
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/test/gateways/http_route_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
test/integration/consul-container/test/snapshot/snapshot_restore_test.go
test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering/peering_http_test.go

Manually import from ent [pr](https://github.com/hashicorp/consul-enterprise/pull/5494)

consul-container test: no splitting and on single runner

---

CHANGELOG.md

This ports the changelog entries for yesterday's releases - Consul 1.13.8 and 1.14.7 - into `main`.

Add changelog entries for Consul 1.13.8 + 1.14.7

---

website/content/docs/services/services.mdx

Small tweaks to the description block on the _Services overview_ page. The description now points to additional overview information about how services work in SM and SM on K8s.

updates to links in services overview description paragraph

---

agent/proxycfg/api_gateway.go
agent/proxycfg/snapshot.go
agent/xds/endpoints.go

Each listener would previously have all upstreams from any route that bound to the listener. This is problematic when a route bound to one listener also binds to other listeners and so includes upstreams for multiple listeners. The list for a given listener would then wind up including upstreams for other listeners.

Modify getReadyUpstreams to filter upstreams by listener

---

agent/consul/server.go
internal/catalog/exports.go
internal/catalog/internal/controllers/register.go
internal/catalog/internal/controllers/workloadhealth/controller.go
internal/catalog/internal/controllers/workloadhealth/controller_test.go
internal/catalog/internal/controllers/workloadhealth/status.go
internal/catalog/internal/mappers/nodemapper/node_mapper.go
internal/catalog/internal/mappers/nodemapper/node_mapper_test.go

This PR builds on #17214. It implements a workload health controller similar to the node health controller that PR introduced.
This one is a little more complex though as workload health depends on health statuses with workload owners but also with the associated nodes. The workload health controller therefore needs an extra dependency that is capable of tracking the node <-> workload associations and to map node watch events into the corresponding workloads that require reconciliation.
* The unit tests for the controller amount to ~96% code coverage. A future PR will introduce a multi-catalog-controller integration test.

Add the workload health controller

---

agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_test.go

This change enables workflows where you are reapplying a resource that should have an owner ref to publish modifications to the resources data without performing a read to figure out the current owner resource incarnations UID.
Basically we want workflows similar to `kubectl apply` or `consul config write` to be able to work seamlessly even for owned resources.
In these cases the users intention is to have the resource owned by the “current” incarnation of the owner resource.

Allow resource updates to omit an owner refs UID

---

agent/grpc-external/services/peerstream/stream_test.go
proto/prototest/testing.go
proto/prototest/testing_test.go

manual backport of #17416 to 1.14.x

[1.14.x] prototest: fix early return condition in AssertElementsMatch

---

proto/prototest/testing.go
proto/prototest/testing_test.go

manual backport of #17416 to 1.13.x

[1.13.x] prototest: fix early return condition in AssertElementsMatch

---

.changelog/17231.txt
agent/consul/acl_server.go
test/integration/consul-container/test/wanfed/acl_bootstrap_replication_test.go
test/integration/consul-container/test/wanfed/wanfed_peering_test.go

Prior to https://github.com/hashicorp/consul/pull/16200, the anonymous token was only inserted in the primary datacenter. This is a potential fix for WAN fed issues seen in: https://github.com/hashicorp/consul/issues/16620.

Only synthesize anonymous token in primary DC

---

agent/configentry/compare.go
agent/configentry/compare_test.go
agent/consul/config_replication.go
agent/consul/config_replication_test.go

Directly lift a few generic config entry helper functions out of `agent/consul` into `agent/configentry` to be used elsewhere later.

extract some config entry helpers into package

---

.github/workflows/test-integrations.yml
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/libs/utils/version.go
test/integration/consul-container/test/gateways/http_route_test.go
test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
test/integration/consul-container/test/upgrade/common.go
test/integration/consul-container/test/upgrade/fullstopupgrade_test.go
test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering/peering_http_test.go

Manually backport https://github.com/hashicorp/consul/pull/17394 to remove test splitting for container integ tests
- no test splitting
- integ tests on a single runner

[Release/1.15.x] net 3914 gha consul container test no splitting

---

.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations.yml

Tested that these changes work on PR from fork: https://github.com/hashicorp/consul/pull/17445
- create a PR from fork with only docs changes (or anything that does not cause test failures on its own)
- validate checks run successfully
expected results: `go-tests` and `test-integrations` pass.
actual results: both workflows fail when trying to upload test coverage data to DataDog because the DD API key is not present (since the fork does not contain it).

CI: do not upload test metrics to datadog on forks

---

.changelog/17456.txt
agent/grpc-external/services/peerstream/replication.go
agent/grpc-external/services/peerstream/stream_test.go

This change fixes a function call so that namespaced services are correctly queried when handling updates / deletes. Prior to this change, some peered services would not correctly be un-exported when the exported-services configuration entry was modified.

Fix namespaced peer service updates / deletes.

---

.changelog/17424.txt
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go
website/content/docs/upgrading/upgrade-specific.mdx

Prior to this change, the service health API would not explicitly return an error whenever a token with invalid permissions was given, and it would instead return empty results. 
With this change, a "Permission denied" error is returned whenever data is queried. This is done to better support the agent cache, which performs a fetch backoff sleep whenever ACL errors are encountered.  
Affected endpoints are: `/v1/health/connect/` and `/v1/health/ingress/`.

Fix ACL check on health endpoint

---

.github/workflows/reusable-lint.yml

It would seem that GitHub runners are picking up on previous `golanglint-ci` caches on the host, causing false positives.  This turns off caching for the reusable lint action.
Different engineers made several attempts to reproduce the failing results locally.
Examples are available in the Enterprise version of this PR.

chore(ci): skip cache for lint workflow

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/xds/endpoints.go

This fixes an issue where TCP services that are exported cannot be configured to failover. This happened because there was a validation that exported services cannot add additional discovery chain targets. Relaxing this constraint is harmless for failover because xds/endpoints excludes cross partition and peer endpoints.
This also adds a bunch of missing tests for existing validations.
This PR has more background on why some disco chain changes are restricted https://github.com/hashicorp/consul/pull/13727.

This fixes an issue where TCP services that are exported cannot be configured to failover

---

.github/workflows/reusable-lint.yml
.github/workflows/test-integrations.yml
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/examples.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/test/upgrade/healthcheck_test.go

Manual backport  https://github.com/hashicorp/consul/pull/17394
Backport removing test splitting to 1.14.x. Note that in 1.14.x, we don't have actual upgrade test yet (upgrade test for service mesh was added since 1.15.x). The upgrade tests in 1.14.x tests the combination between consul:local and the latest patched version of 1.14.x.
This PR also fixes some issue of passing image name and version arguments in creating consul containers. The problem was not exposed because some of the tests were not triggered.

[Release/1.14.x] net 3914 gha consul container test no splitting

---

agent/hcp/client/client.go

> In Cortex we make sure we only ingest from one of T1.a and T1.b, and only from one of T2.a and T2.b. We do this by electing a leader replica for each cluster of Prometheus. For example, in the case of T1, let it be T1.a. As long as T1.a is the leader, we drop the samples sent by T1.b. And if Cortex sees no new samples from T1.a for a short period (30s by default), it’ll switch the leader to be T1.b.
docs: https://cortexmetrics.io/docs/guides/ha-pair-handling/
Having __replica__ will prevent ingestion of metrics from multiple proxies because one will be elected leader. It's not deduplication of metrics from a single replica, it's deduplication of samples across all replicas
Deploy `feature/hcp-telemetry` and push to a Cortex or Cortex-like Prometheus database that has HA-availability …

Remove replica tag

---

.github/workflows/backport-assistant.yml

Updating backport assistant to 0.3.4 so that backports will be assigned to the merge-by user.

ci: update backport assistant to 0.3.4

---

agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/testdata/builtin_extension/clusters/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/clusters/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/clusters/propertyoverride-listener-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/clusters/propertyoverride-listener-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/endpoints/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/endpoints/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/endpoints/propertyoverride-listener-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/endpoints/propertyoverride-listener-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/listeners/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/listeners/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/listeners/propertyoverride-listener-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/listeners/propertyoverride-listener-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/routes/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/routes/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
agent/xds/testdata/builtin_extension/routes/propertyoverride-listener-inbound-add.latest.golden
agent/xds/testdata/builtin_extension/routes/propertyoverride-listener-outbound-add.latest.golden
envoyextensions/extensioncommon/basic_envoy_extender.go
envoyextensions/extensioncommon/basic_extension_adapter.go
envoyextensions/extensioncommon/resources.go

Add support for patching `Listener` and `ClusterLoadAssignment` resources via the builtin `property-override` extension.
Changes for each resource split across two commits for easier review.
I skipped a separate changelog entry since this is an enhancement to a feature already introduced in the next release.
Note that several golden files used by new tests were previously committed with the bulk of `property-override` extension work; they're now in use with this change.
* Add support for patching resources
* Refactor existing listener patch code in `BasicEnvoyExtender` to simplify addition of resource support
* Add golden tests

Support `Listener` and `ClusterLoadAssignment` in `property-override`

---

agent/hcp/client/metrics_client.go

Turn off retries by setting `defaultRetryMax` to 0 in MetricsClient
Why?
- Avoid retry storm if CTGW is down for lack of capacity in the OTLP service
- For GA, we can add this back in as we'll be able to dynamically update the retry with configuration changes.
I tested this change end to end with a mock endpoint that returns `status.ServiceUnavailable`, and the retry does not kick off unlike on the feature/hcp-telemetry branch.

[HCP Observability] Turn off retries for now until dynamically configurable

---

.changelog/17505.txt
agent/envoyextensions/builtin/wasm/wasm.go
agent/envoyextensions/builtin/wasm/wasm_test.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/delta_envoy_extender_test.go
agent/xds/testdata/builtin_extension/clusters/wasm-tcp-local-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/clusters/wasm-tcp-local-file.latest.golden
agent/xds/testdata/builtin_extension/clusters/wasm-tcp-remote-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/clusters/wasm-tcp-remote-file.latest.golden
agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-local-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-local-file.latest.golden
agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-remote-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-remote-file.latest.golden
agent/xds/testdata/builtin_extension/listeners/wasm-tcp-local-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/wasm-tcp-local-file.latest.golden
agent/xds/testdata/builtin_extension/listeners/wasm-tcp-remote-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/wasm-tcp-remote-file.latest.golden
agent/xds/testdata/builtin_extension/routes/wasm-tcp-local-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/routes/wasm-tcp-local-file.latest.golden
agent/xds/testdata/builtin_extension/routes/wasm-tcp-remote-file-outbound.latest.golden
agent/xds/testdata/builtin_extension/routes/wasm-tcp-remote-file.latest.golden

This PR enables the `builtin/wasm` Envoy extension to apply Wasm network filters for TCP services.
- The extension unit tests have been updated to verify patching Wasm network filters.
- Envoy golden tests have been added for Wasm network filters
- [Envoy Wasm network filter docs](https://www.envoyproxy.io/docs/envoy/v1.25.6/api-v3/extensions/filters/network/wasm/v3/wasm.proto)

Enable Network filters for Wasm Envoy Extension

---

.github/workflows/build.yml

This addresses the deprecation of the "set-output" command by Github.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details on this deprecation

remove deprecated set-output calls in gha

---

agent/hcp/client/client.go
agent/hcp/client/client_test.go

This is a follow-up to #17460
This PR adds safety checks in the event that the Telemetry Gateway is down, or the client does not return an error, we should have the response validated.
- Add unit tests
- Run integration k8s test

[HCP Observability] Add safety checks for TelemetryConfig payload response

---

.changelog/17038.txt
agent/config/builder.go
agent/config/builder_test.go
agent/config/config.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/setup.go
lib/hoststats/collector.go
lib/hoststats/cpu.go
lib/hoststats/cpu_test.go
lib/hoststats/host.go
lib/hoststats/metrics.go
lib/telemetry.go
website/content/docs/agent/config/config-files.mdx
website/content/docs/agent/telemetry.mdx

This PR adds the ability for Consul to report host statistics through go-metrics. These metrics include cpu utilization by core and in aggregate, system memory usage and disk usage for the disk backing the configured data_dir. 
Tests were added to assert cpu utilization calculation is performed accurately. Manual testing was performed on linux and darwin to ensure reported host stats values were accurate.

hoststats: add package for collecting host statistics including cpu memory and disk usage

---

agent/consul/server.go

This change the isServer behaviour to only return true when other servers IP detected. This to account for the use case when a server is receiving requests from its local IP.

fix isServer to exclude local address

---

.changelog/17525.txt
agent/http.go
agent/http_test.go
api/api.go
command/connect/envoy/envoy_test.go

This commit only contains the OSS PR (datacenter query param support). A separate enterprise PR adds support for ap and namespace query params.
Resources in Consul can exists within scopes such as datacenters, cluster peers, admin partitions, and namespaces. You can refer to those resources from interfaces such as the CLI, HTTP API, DNS, and configuration files.
Some scope levels have consistent naming: cluster peers are always referred to as "peer".
Other scope levels use a short-hand in DNS lookups...
- "ns" for namespace
- "ap" for admin partition
- "dc" for datacenter
...But use long-hand in CLI commands:
- "namespace" for namespace
- "partition" for admin partition
- and "datacenter"
However, HTTP API query parameters do not follow a consistent pattern, supporting short-hand for some …

Accept ap, datacenter, and namespace query params

---

test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/container.go

Exposed Logs method on container interface to enable reading container logs for relevant test cases
Counterpart of https://github.com/hashicorp/consul-enterprise/pull/5615

feat: expose logs method on container interface

---

agent/consul/fsm/snapshot_test.go
agent/consul/state/catalog.go
agent/consul/state/config_entry.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go

Sameness groups with default-for-failover enabled did not function properly with tproxy whenever all instances of the service disappeared from the local cluster. This occured, because there were no corresponding resolvers (due to the implicit failover policy) which caused VIPs to be deallocated.
This ticket expands upon the VIP allocations so that both service-defaults and service-intentions (without destination wildcards) will ensure that the virtual IP exists.

Fix tproxy failover issue with sameness groups

---

.changelog/17055.txt
agent/consul/discoverychain/gateway.go
agent/consul/discoverychain/gateway_test.go

I realized that we were actually improperly munging http route references in synthesized discovery chains for API gateways. What this meant was that when using an service resolver to create a virtual service referenced by an HTTPRoute we wind up writing in the wrong target cluster for a routing rule. This results in the gateway returning "no healthy upstreams".
This change takes into account when the target is just a virtual service created by a service-resolver.
Unit tested and manually verified with the following configuration entries and a mesh-federated Consul setup:
1. TCP Routes
```hcl
Kind = "tcp-route"
Name = "api-gateway-route"
Services = [
{
Name = "tcp-dc-2"
}
]
Parents = [
{
Name = "api"
}
]
```
```hcl
Kind = "api-gateway"
Name = "api"
Listeners = [
{
Name     = "listener-one" …
```

[API Gateway] Fix use of virtual resolvers in HTTPRoutes

---

agent/proxycfg/testing_tproxy.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/resources_test.go
agent/xds/testdata/builtin_extension/clusters/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/endpoints/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/routes/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
envoyextensions/extensioncommon/basic_envoy_extender.go
envoyextensions/extensioncommon/upstream_envoy_extender.go

When `UpstreamEnvoyExtender` was introduced, some code was left duplicated between it and `BasicEnvoyExtender`. One path in that code panics when a TProxy listener patch is attempted due to no upstream data in `RuntimeConfig` matching the local service (which would only happen in rare cases).
Instead, we can remove the special handling of upstream VIPs from `BasicEnvoyExtender` entirely, greatly simplifying the listener filter patch code and avoiding the panic. `UpstreamEnvoyExtender`, which needs this code to function, is modified to ensure a panic does not occur.
This also fixes a second regression in which the Lua extension was not applied to TProxy outbound listeners.
This fixes two regressions caused by https://github.com/hashicorp/consul/pull/17415.
I've hand-tested this fix in …

Avoid panic applying TProxy Envoy extensions

---

agent/proxycfg/testing_tproxy.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/resources_test.go
agent/xds/testdata/builtin_extension/clusters/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/endpoints/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/routes/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
envoyextensions/extensioncommon/basic_envoy_extender.go
envoyextensions/extensioncommon/upstream_envoy_extender.go

backport of commit https://github.com/hashicorp/consul/commit/8c3045576143eaf258d1fdcac0fe2252398b3816
Manual backport of https://github.com/hashicorp/consul/pull/17537.
Resolves automated backport PR https://github.com/hashicorp/consul/pull/17542.

Manual backport 1.15.x of Avoid panic applying TProxy Envoy extensions

---

website/content/docs/upgrading/upgrade-specific.mdx

Document the impact of https://github.com/hashicorp/consul/issues/17503 for Nomad users.
This was a general description, but feel free to modify the text as you see fit.

docs: add note about Nomad support for Consul 1.13.8

---

agent/agent.go

Fix the error message format with `logger.Error`

chore: fix the error message format

---

.changelog/16845.txt
.release/linux/package/usr/lib/systemd/system/consul.service

* updates `consul.service` systemd service unit to use `Type=notify` to resolve issue #16844
To resolve issue #16844 and switch packaged systemd unit to use systemd's notify mechanism by default.
See #16844 where the steps to reproduce the current and updated behavior are documented
https://github.com/hashicorp/consul/issues/2121
https://github.com/hashicorp/consul/commit/31a310f551c36243d2aae9ed80054c200e079b81
https://developer.hashicorp.com/consul/docs/agent#understanding-the-agent-startup-output
https://developer.hashicorp.com/consul/tutorials/production-deploy/deployment-guide#configure-the-consul-process

Resolves issue-16844 - systemd notify by default

---

.changelog/17566.txt
agent/proxycfg-glue/glue.go

Due to swallowing and only logging xDS errors here:
https://github.com/hashicorp/consul/blob/88951bfafaa969f52235dc5b443cb64ba329660c/agent/proxycfg/state.go#L375-L386
We were getting into a state where if ACLs were modified while connected to xDS, the stream wasn't properly being re-established and instead the Consul logs were filling up with error logs such as:
> Failed to handle update from watch: kind=api-gateway proxy=default/default/gateway-d6b4d69c-krz5b service_id=default/default/gateway-d6b4d69c-krz5b id=gateway-config error="error filling agent cache: subscription closed by server, client must reset state and resubscribe"
Basically we were missing some casing for marking certain errors as `TerminalError`s in proxycfg-glue, this fixes that.
Get a proxy and/or gateway to connect …

Fix up case where subscription is terminated due to ACLs changing or a snapshot restore occurring

---

test/integration/connect/envoy/case-property-override/capture.sh
test/integration/connect/envoy/case-property-override/service_s1.hcl
test/integration/connect/envoy/case-property-override/service_s2.hcl
test/integration/connect/envoy/case-property-override/setup.sh
test/integration/connect/envoy/case-property-override/vars.sh
test/integration/connect/envoy/case-property-override/verify.bats
test/integration/connect/envoy/helpers.bash

Add integration test for Property Override extension that patches two different proxies.
Follow-up changes will ensure that we parse single- and multi-value array config fields appropriately; initial testing shows we may still have a bug there, so committing this simple test for now.

Add Prop Override Envoy extension integration test

---

agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go
test/integration/connect/envoy/case-property-override/capture.sh
test/integration/connect/envoy/case-property-override/service_s1.hcl
test/integration/connect/envoy/case-property-override/service_s3.hcl
test/integration/connect/envoy/case-property-override/setup.sh
test/integration/connect/envoy/case-property-override/vars.sh
test/integration/connect/envoy/case-property-override/verify.bats

Ensure that the embedded `api` struct is properly parsed when deserializing config containing a set `ResourceFilter.Services` field.
Also enhance existing integration test to guard against bugs and exercise this field.
Follow-up to https://github.com/hashicorp/consul/pull/17569.

Fix Property Override Services parsing

---

agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go

More validation is needed to ensure this behaves as expected; in the meantime, align with docs and disable this proxy type.
Disable configuring `terminating-gateway` in the `property-override` builtin Envoy extension.

Disable terminating-gateway for property-override

---

agent/agent_endpoint_test.go
agent/consul/acl_endpoint_test.go
agent/consul/client_test.go
agent/dns_test.go
agent/grpc-external/services/peerstream/stream_test.go
agent/local/state_test.go

Backport of https://github.com/hashicorp/consul/pull/17600 to release/1.13.x

Backport of fix some testing.T retry.R mixups into release/1.13.x

---

.changelog/17609.txt
agent/proxycfg/snapshot.go

This bug was found in writing this test on k8s: https://github.com/hashicorp/consul-k8s/pull/2306
I would like to circle around and write an acceptance-level test in core, but think that might likely have to wait a few weeks given some time constraints, and any behavior that this breaks (v. fixing) should already be covered by tests.
Ran k8s acceptance test and would not pass until these changes were introduced.

[API Gateway] Fix trust domain for external peered services in synthesis code

---

.changelog/_5669.txt
api/api_test.go
sdk/testutil/server.go

- Fixing disparities between ent repo and oss repos 
- Drift will be caught in the future by this work: 🤞🏾 https://github.com/hashicorp/consul-enterprise/pull/5781

backport ent changes to oss

---

go.mod
go.sum
test/integration/consul-container/go.mod

Updating submodules, solely on the running release branch, as this is the only branch that should consume the RC submodule tags.

Update submodules for 1.16.0-rc1 release

---

.changelog/17636.txt
agent/cache-types/connect_ca_leaf.go
agent/cache/cache.go

[1.14.x] cache: fix a few minor goroutine leaks in leaf certs and the agent cache

---

agent/xds/resources_test.go
agent/xds/routes.go
agent/xds/testdata/routes/api-gateway-with-http-route-and-inline-certificate.latest.golden

Header filters on http-route rules are being added to the virtual host _and_ the route when generating xDS.
This is demonstrated by stepping through the commits in this PR:
1. The first commit demonstrates the xDS that _was_ being generated, which includes the header modifications on both the virtual host and the routes
2. The second commit includes the fix to stop adding all header filters to the virtual host
3. The third commit updates the golden file containing the generated xDS, so this is what we're generating after the fix
- This PR adds a test verifying that this bug existed and is now fixed
- The kubernetes-sigs/gateway-api conformance tests exercise this functionality, which is how I identified this bug

api-gateway: stop adding all header filters to virtual host when generating xDS

---

website/content/docs/agent/config/config-files.mdx
website/content/docs/agent/config/index.mdx
website/content/docs/agent/limits/index.mdx
website/content/docs/agent/limits/usage/init-rate-limits.mdx
website/content/docs/agent/limits/usage/limit-request-rates-from-ips.mdx
website/content/docs/agent/limits/usage/monitor-rate-limits.mdx
website/content/docs/agent/limits/usage/set-global-traffic-rate-limits.mdx
website/content/docs/connect/config-entries/control-plane-request-limit.mdx
website/content/docs/connect/proxies/envoy-extensions/configuration/ext-authz.mdx
website/content/docs/connect/proxies/envoy-extensions/configuration/property-override.mdx
website/content/docs/connect/proxies/envoy-extensions/configuration/wasm.mdx
website/content/docs/connect/proxies/envoy-extensions/index.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/ext-authz.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/wasm.mdx
website/content/docs/enterprise/license/utilization-reporting.mdx
website/content/partials/envoy_ext_rule_matcher.mdx
website/data/docs-nav-data.json

Add new Consul 1.16 docs

---

agent/envoyextensions/builtin/http/localratelimit/ratelimit.go
agent/envoyextensions/builtin/http/localratelimit/ratelimit_test.go
agent/envoyextensions/builtin/lua/lua.go
agent/envoyextensions/builtin/lua/lua_test.go
agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go

This PR updates the local rate limt, Lua and property override extensions to default the `ProxyType` input to `connect-proxy` since this is [currently] the only supported proxy type for these extensions. This aligns the default behavior across all builtin extensions that take a `ProxyType` and only support `connect-proxy`.
This is a non-breaking change since the config still allows setting the `ProxyType` expressly.
Note that the docs have not been updated. I will update the docs in a separate PR once https://github.com/hashicorp/consul/pull/17651 is merged.
- Updated unit tests to cover both the default and explicit cases.
- Ran the xds golden tests and they pass unmodified.
N/A

Default `ProxyType` for builtin extensions

---

website/data/docs-nav-data.json

With Consul 1.16, the Native API Gateway Config Entries are no longer "BETA" so I have removed the pill that marks them as such.
If you run the website locally, you should see that the sidebar no longer includes the "BETA" tags.

Remove "BETA" marker from config entries

---

website/content/docs/k8s/l7-traffic/failover-tproxy.mdx

Updated title for page about configuring failovers on K8s when tproxy is enabled to more accurately reflect the content. The topic appears in the VM and K8s nav section, so it might be unclear which runtime we mean.

updated failover for k8s w-tproxy page title

---

.changelog/17483.txt
.changelog/_5614.txt
agent/consul/leader.go

This complements an enterprise PR that resolves an issue with namespaces but also affects the leader routine. When we lose leadership, we clean up the peering deferred deletion routine.

fix: stop peering delete routine on leader loss

---

agent/consul/discoverychain/compile.go
agent/consul/discoverychain/compile_test.go
agent/structs/discovery_chain.go
agent/structs/structs.deepcopy.go

This includes prioritize by localities on disco chain targets rather than resolvers, allowing different targets within the same partition to have different policies.

Refactor disco chain prioritize by locality structs

---

.github/workflows/bot-auto-approve.yaml
.github/workflows/broken-link-check.yml
.github/workflows/build-artifacts.yml
.github/workflows/build-distros.yml
.github/workflows/build.yml
.github/workflows/changelog-checker.yml
.github/workflows/embedded-asset-checker.yml
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/issue-comment-created.yml
.github/workflows/jira-issues.yaml
.github/workflows/jira-pr.yaml
.github/workflows/nightly-test-1.13.x.yaml
.github/workflows/nightly-test-1.14.x.yaml
.github/workflows/nightly-test-1.15.x.yaml
.github/workflows/nightly-test-1.16.x.yaml
.github/workflows/nightly-test-main.yaml
.github/workflows/pr-labeler.yml
.github/workflows/pr-metrics-test-checker.yml
.github/workflows/reusable-check-go-mod.yml
.github/workflows/reusable-dev-build.yml
.github/workflows/reusable-lint.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/stale.yml
.github/workflows/test-integrations.yml
.github/workflows/verify-envoy-version.yml

Ran the tsccr tool to update all the actions. Actions are run from main so no need to backport.

[chore]: Pin github action workflows

---

website/content/docs/agent/limits/index.mdx
website/content/docs/agent/limits/usage/limit-request-rates-from-ips.mdx
website/content/docs/connect/config-entries/control-plane-request-limit.mdx
website/content/docs/enterprise/index.mdx
website/content/docs/release-notes/consul/v1_16_x.mdx

This PR flags the IP-based request rate limiting functionality as Consul Enterprise. The usage docs, configuration entry, and CE matrix have been updated.

add enterprise notes for IP-based rate limits

---

website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/terminating-gateway.mdx

Now that 1.14-1.16 will be the versions that will actively maintained, we should remove these mentions of old versions from our config entries. Users can still see this in previous versions of our docs due to versioned docs support.

Remove extraneous version info for Config entries

---

website/content/docs/k8s/upgrade/index.mdx

fix a typo in documentation of a link to a section

docs: fix typo in link to section

---

.changelog/17731.txt
agent/agent.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/manager.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/testing.go
agent/proxycfg/testing_connect_proxy.go
agent/proxycfg/testing_ingress_gateway.go
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_peering.go
agent/proxycfg/testing_terminating_gateway.go
agent/proxycfg/testing_tproxy.go
agent/proxycfg/upstreams.go
agent/xds/clusters_test.go
agent/xds/listeners_test.go
agent/xds/resources_test.go

This PR disables peering functionality in proxycfg by default, unless `peering.enabled = true` is explicitly set in the agent config.
This change was necessary to prevent expensive polling watch queries (that were introduced for peer upstreams) from impacting users that do not wish to leverage peering features. While this is technically a breaking change, the 1.13 implementation of peering is considered to be experimental and not production ready. After this PR is merged, any users that wish to use peering in conjunction with mesh will need to enable peering on each agent and server.

Disable peering queries by default in proxycfg

---

agent/xds/delta.go

This PR updates the logging and error handling logic for when extensions succeed or fail to apply. The existing behavior was always logging a failure message even when the extension was successfully applied. In some of the failure cases, the log message did not include the error returned from the extension.
- `agent/xds` unit tests.

OSS merge: Update error handling login when applying extensions

---

agent/hcp/client/metrics_client.go
agent/hcp/client/metrics_client_test.go

There is a bug in the error logs where the entire body of the request is output. Instead of using the request body in the error we should be using the body of the response and truncating it to a reasonable size and add an ellipsis.
We see this in our error codes with a large payload of metrics (https://go.hashi.co/cc-5248) 
DD Link to example of issue: https://go.hashi.co/cc-5248
* [n/a] external facing docs updated

Add truncation to body

---

.changelog/17757.txt

This PR is intended to document some of the transparent proxy enhancements that were made for the 1.16 release.
Prior to these changes, transparent proxy deployments would not function properly for several failover scenarios. Most notably, when the number of service instances reached zero, the discovery chain watch would disappear for the corresponding service, causing the resolver to also disappear from proxycfg. This would result in the failover not applying.
With these changes, discovery chains will now continue to exist in the proxy configuration as long as one of the following config entry types also exists and shares a name with the targeted upstream service:
- service-resolver
- service-router
- service-splitter
- service-defaults
- service-intentions
For example, when the …

Improve Transparent Proxy Virtual Services and Failovers

---

website/content/docs/upgrading/instructions/general-process.mdx

_Note: this needs to be updated on all versions of docs, so backport labels for 1.13 - 1.16 are in place.  I will manually cherry pick this into PRS to the docs release branches prior to 1.13._
A customer ran into an issue where leadership elections occurred multiple times for each server that they were upgrading when the initial goal of the process is to ensure the leader is upgraded last.  This was caused by the use of `consul leave` during the upgrade process as they upgraded from consul to consul enterprise.
When upgrading it is important that the leader goes last, so that the leader is replicating raft logs on the lower consul version to servers that are either at the same level or at a higher level and are aware of all fields that are within the raft log.
When using consul leave …

docs - remove use of consul leave during upgrade instructions as it caused leadership changes

---

.changelog/17775.txt
agent/agent.go
agent/consul/watch/server_local.go
agent/proxycfg-glue/health_blocking.go
agent/proxycfg-glue/health_blocking_test.go

This commit fixes an issue where the health streams were unaware of service export changes. Whenever an exported-services config entry is modified, it is effectively an ACL change.
The bug would be triggered by the following situation:
- no services are exported
- an upstream watch to service X is spawned
- the streaming backend filters out data for service X (due to lack of exports)
- service X is finally exported
In the situation above, the streaming backend does not trigger a refresh of its data.  This means that any events that were supposed to have been received prior to the export are NOT backfilled, and the watches never see service X spawning.
We currently have decided to not trigger a stream refresh in this situation due to the potential for a thundering herd effect (touching …

Fix issue with streaming service health watches.

---

.changelog/17759.txt
agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go
agent/envoyextensions/builtin/property-override/structpatcher.go
agent/envoyextensions/builtin/property-override/structpatcher_test.go

Improve validation by `property-override` builtin Envoy Extension.
- Reject invalid `ResourceFilter` combination of `TrafficDirection`: `inbound` w/ non-empty `Services`
- Cover additional invalid field cases due to type mismatch or unsupported target
- Add specific error message for attempting to set `Any` fields

Property Override validation improvements

---

agent/envoyextensions/builtin/property-override/property_override.go
agent/envoyextensions/builtin/property-override/property_override_test.go

When a patch is found invalid, include its index for easier debugging when multiple patches are provided.
Changelog added in https://github.com/hashicorp/consul/pull/17759

Add Patch index to Prop Override validation errors

---

internal/catalog/catalogtest/run_test.go
internal/catalog/catalogtest/test_integration_v1alpha1.go
internal/catalog/catalogtest/test_lifecycle_v1alpha1.go
internal/catalog/exports.go
internal/resource/resourcetest/builder.go
internal/resource/resourcetest/client.go
proto/private/prototest/testing.go

This adds some lifecycle integration tests to the catalogtest package. These tests will publish resources modify/delete them and generally just exercise various behavior which should cause the various catalog controllers to do work. As these tests focus on modifying resources over time they wont be as suitable for use in upgrade tests.
Its just new tests being added.

Implement a Catalog Controllers Lifecycle Integration Test

---

test/integration/connect/envoy/case-property-override/setup.sh
test/integration/connect/envoy/case-property-override/verify.bats
website/content/docs/connect/proxies/envoy-extensions/configuration/property-override.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx

- Provide more realistics examples for setting properties not already
supported natively by Consul
- Remove superfluous commas from HCL, correct target service name, and
fix service defaults vs. proxy defaults in examples
- Align existing integration test to updated docs
Existing docs: https://developer.hashicorp.com/consul/docs/v1.16.x/connect/proxies/envoy-extensions/usage/property-override

Improve Prop Override docs examples

---

agent/xds/listeners_test.go
agent/xds/testdata/listeners/connect-proxy-without-tproxy-and-permissive-mtls.latest.golden

This adds a golden data test to validate the permissive mTLS listener modifications are not applied when transparent proxy is disabled and permissive mTLS is enabled.
```
go test -v -run TestListenersFromSnapshot/envoy-1.23.10/connect-proxy-without-tproxy-and-permissive-mtls/current 
```

Test permissive mTLS filter chain is not configured with tproxy disabled

---

website/content/docs/connect/proxies/envoy-extensions/configuration/property-override.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx

Explicitly document the limitations of the extension, particularly what kind of fields it is capable of modifying.
I wasn't sure exactly where this copy should live, so I took my best guess. Happy to shift if there's a better spot for it.
Existing docs: https://developer.hashicorp.com/consul/docs/v1.16.x/connect/proxies/envoy-extensions/usage/property-override
Related docs PR: https://github.com/hashicorp/consul/pull/17799

Clarify limitations of Prop Override extension

---

website/content/docs/connect/config-entries/jwt-provider.mdx

- Adding jwt authn docs to jwt provider page 
**NOTE**: we can't provide much more details about these metrics as envoy doesn't provide any details. I did log an issue for them to address this: https://github.com/envoyproxy/envoy/issues/28051

Add jwt-authn metrics to jwt-provider docs

---

website/redirects.js

This PR updates the redirects implemented for the 1.16-RC version of the docs so that they use the _latest_ paths.

Change URLs for redirects from RC to default latest

---

website/content/docs/connect/config-entries/jwt-provider.mdx

For some reason the auto merge process didn't pick up the latest changes from: https://github.com/hashicorp/consul/pull/17816  in the backport: https://github.com/hashicorp/consul/pull/17824
so this fixes the disparity

fix docs weirdness

---

.changelog/17582.txt
agent/consul/operator_raft_endpoint.go
agent/consul/operator_raft_endpoint_test.go
agent/structs/operator.go
api/operator_raft.go
command/operator/raft/listpeers/operator_raft_list.go
command/operator/raft/listpeers/operator_raft_list_test.go
website/content/commands/operator/raft.mdx

As per requirement of [NET - 3865](https://hashicorp.atlassian.net/browse/NET-3865), We want to have the 'commit_index' to be included in the output of 'consul operator raft list-peers -detailed'. This feature specifically useful in the cases where Consul is being upgraded to determine the replication rate and intervene as needed.
I have implemented it by calling a API `/v1/operator/autopilot/health`, storing the response in a map -> [server id, OperatorHealthReply]. Then this data is used to print the Commit Index by matching the id of server from this to server id in RaftGetConfiguration.
Create a consul cluster by following this [tutorial](https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-windows-nodes).
`kubectl exec -it consul-server-0 -n consul -- /bin/sh` in …

Backport of [NET-3865] [Supportability] Additional Information in the output - in 1.14.x

---

.github/workflows/build-artifacts.yml
.github/workflows/build-distros.yml
.github/workflows/build.yml
.github/workflows/go-tests.yml
.github/workflows/nightly-test-1.13.x.yaml
.github/workflows/nightly-test-1.14.x.yaml
.github/workflows/nightly-test-1.15.x.yaml
.github/workflows/nightly-test-1.16.x.yaml
.github/workflows/nightly-test-main.yaml
.github/workflows/reusable-lint.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations.yml

Consistently set `GOPRIVATE` to include all `hashicorp` repos, s.t. private modules are successfully pulled in enterprise CI.
This prevents issues resulting from private indirect dependencies appearing in `go.mod` preventing successful builds.
We [already set `GOPRIVATE` in build-artifacts.yml](https://github.com/hashicorp/consul/blob/e4c9793ee2015bcda2af790d318b1b3f5b48a5bf/.github/workflows/build-artifacts.yml#L16) but do not do it consistently in all places where code is built.
I'm skipping backporting this for now as the instigating change (https://github.com/hashicorp/consul/pull/17674) was not backported.

Set GOPRIVATE for all hashicorp repos in CI

---

agent/proxycfg/proxycfg.deepcopy.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/structs/structs.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/failover_policy.go
agent/xds/locality_policy.go
agent/xds/locality_policy_oss.go
test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/service/helpers.go

* Make xDS locality aware routing changes

Locality routing xDS

---

test/integration/connect/envoy/case-property-override/setup.sh
test/integration/connect/envoy/case-property-override/verify.bats
website/content/docs/connect/proxies/envoy-extensions/configuration/property-override.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/property-override.mdx

backport of commit 910a115cd3812cd66fab1cdfc47baeec65415d14 (#17813)
backport of commit 21263c8a004dffe7e8fcefc234d80abfa3ec66d5 (#17811)
These are manual backports of doc- and test-only changes made to improve user-facing documentation of the Property Override Envoy extension added in 1.16.

Manual backports of Prop Override doc updates

---

test/integration/consul-container/test/debugging.md

Add missing `-t` flag and fix minor typo. Follow-up to https://github.com/hashicorp/consul/pull/17800.

Fixup consul-container/test/debugging.md

---

.changelog/17739.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go

see #17732
https://developer.hashicorp.com/consul/api-docs/acl/tokens#update-a-token

fixes #17732 - AccessorID in request body should be optional when updating ACL token

---

.changelog/17831.txt
agent/config/builder.go
agent/connect/ca/provider_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
website/content/docs/connect/ca/index.mdx
website/content/docs/connect/ca/vault.mdx

Small code update to only validate for `RootPKIPath` if the server is in the primary datacenter.
Docs updates to clarify and correct outdated information around CA providers (specifically the Vault CA provider)

CA provider doc updates and Vault provider minor update

---

agent/envoyextensions/builtin/ext-authz/ext_authz_test.go
agent/envoyextensions/builtin/ext-authz/structs.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/delta_envoy_extender_test.go
agent/xds/testdata/builtin_extension/clusters/ext-authz-http-local-http-service.latest.golden
website/content/docs/connect/proxies/envoy-extensions/configuration/ext-authz.mdx
website/content/docs/connect/proxies/envoy-extensions/usage/ext-authz.mdx

This PR fixes a bug in the `builtin/ext-authz` extension when using `localhost` as the target URI. When using an upstream on the localhost network we configure a `STATIC` cluster type that requires using an IP address. The extension was configuring the cluster with the `localhost` hostname, which caused Envoy to reject the xDS configuration update with an error similar to:
```log
2023-06-20T16:27:39.907Z [ERROR] agent.envoy.xds: got error response from envoy proxy: service_id=default/default/api-5f54fbf97-vkpgr-api-sidecar-proxy typeUrl=type.googleapis.com/envoy.config.cluster.v3.Cluster xdsVersion=v3 nonce=00000006 error="rpc error: code = Internal desc = Error adding/updating cluster(s) local_ext_authz: malformed IP address: localhost. Consider setting resolver_name or setting cluster …
```

ext-authz Envoy extension: support `localhost` as a valid target URI.

---

.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

This PR contains 2 updates to CI
1. The test-integrations for compatibility and upgrade tests now use the elevated github token secret when necessary (like many other jobs)
2. The check-generated-protobuf job now uses a medium sized runner instead of a small. This change was prompted by seeing this job fail a number of times when the runner became disconnected from GitHub and presuming that it was a resource contention issue. Things are working again with the medium runner.
* CI still runs?

CI Updates

---

.github/workflows/go-tests.yml

The check-generated-protobuf job now uses a medium sized runner instead of a small. This change was prompted by seeing this job fail a number of times when the runner became disconnected from GitHub and presuming that it was a resource contention issue. Things are working again with the medium runner.
CI passes.
[Change from original PR](https://github.com/hashicorp/consul/pull/17834/files#diff-5a1bcf51eaa62614197dde8c00207b1c6a3c91d08241b0953e600baa7b66f6d7)

Bump check-generated-protobuf runner size to medium

---

.github/workflows/oss-merge-trigger.yml

Previously, this only triggered for `release/*.*.x` branches; however, our release process involves cutting a `release/1.16.0` branch, for example, at time of code freeze these days. Any PRs to that branch after code freeze today do not make their way to consul-enterprise. This will make behavior for a .0 branch consistent with current behavior for a .x branch.

Trigger OSS => ENT merge for all release branches

---

website/content/docs/connect/gateways/api-gateway/configuration/http-route.mdx

The Gateway API spec says the following about path prefix route matches ([source](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.PathMatchType)):
> Matches based on a URL path prefix split by /. Matching is case sensitive and done on a path element by element basis. A path element refers to the list of labels in the path split by the / separator. When specified, a trailing / is ignored.
> 
> For example, the paths `/abc`, `/abc/`, and `/abc/def` would all match the prefix `/abc`, but the path `/abcd` would not.
Consul API Gateway does simple string prefix comparison today, which is the same thing that the rest of Consul does. The result is that, contrary to the specification above, we do match `/abcd`. This is because Consul uses `RouteMatch_Prefix` …

docs: add note about path prefix matching behavior for HTTPRoute config

---

internal/resource/authz_oss.go

While writing up a developer guide for resources/controllers, I realised that it'd be helpful to have an easy way to construct an `AuthorizerContext` for use in ACL hooks - particularly as this struct is different in the OSS and Enterprise repositories.

resource: add `AuthorizerContext` helper method

---

agent/grpc-external/services/resource/list_by_owner_test.go
agent/grpc-external/services/resource/list_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/watch_test.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go
internal/controller/api_test.go
internal/resource/demo/demo.go
internal/resource/registry.go
internal/resource/registry_test.go
internal/resource/tombstone.go

For consistency, resource type names must follow these rules:
- `Group` must be snake case, and in most cases a single word.
- `GroupVersion` must be lowercase, start with a "v" and end with a number.
- `Kind` must be pascal case.
These were chosen because they map to our protobuf type naming conventions.

resource: enforce consistent naming of resource types

---

build-support/scripts/protobuf.sh

Extends the `proto` make target to generate a protoset file for use with [grpcurl](https://github.com/fullstorydev/grpcurl) etc.

tooling: generate protoset file

---

website/content/docs/api-gateway/upgrades.mdx

The upgrade docs for migrating to the new native api-gateway solution should include a step for creating intentions that allow the gateway to communicate with the backend services that it’s routing to. This is important if a user does not have allow-all in place since the Gateway would be unable to communicate with the service backends post-upgrade.
In the legacy api-gateway solution, we created these intentions automatically; however, we intentionally stopped doing this with our new implementation.
Follow upgrade instructions.
https://consul-asgedpqp3-hashicorp.vercel.app/consul/docs/api-gateway/upgrades#upgrade-to-native-consul-api-gateway

api-gateway: add step to upgrade instructions for creating intentions

---

website/content/docs/connect/ca/vault.mdx

Follow-up to https://github.com/hashicorp/consul/pull/17831

Update wording on WAN fed and intermediate_pki_path

---

agent/structs/config_entry_jwt_provider.go
agent/structs/config_entry_jwt_provider_test.go

- This PR allows service identity tokens the ability to read jwt providers. This is necessary because before writing an intention that referenced a jwt-provider, there is a validation to ensure that jwt-provider exist. 
- Prior to this PR, if the token didn't have `mesh:read` permission, it will not be able to access the provider hence failing to write any intentions referencing jwt providers due to the validation mentioned above

Allow service identity tokens the ability to read jwt-providers

---

.changelog/17888.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/telemetry-collector.golden

This flips an Envoy flag on so metrics sent to the [Consul Telemetry Collector](https://github.com/hashicorp/consul-telemetry-collector) get all the tags that we create via regexes: https://github.com/hashicorp/consul/blob/94584cf5402c11e5a3c93467d43a8ad97af8d6b3/command/connect/envoy/bootstrap_config.go#L352
I made this [change directly to `consul-dataplane`](https://github.com/hashicorp/consul-dataplane/blob/main/internal/bootstrap/bootstrap_config.go#L848), deployed it to a personal Docker Hub repo, and ran `consul-k8s install` with it:
```bash
consul-k8s install -preset cloud -hcp-resource-id "$HCP_RESOURCE_ID" -demo \
--set="global.enterpriseLicense.secretKey=key" \
--set="global.enterpriseLicense.secretName=consul-license" \
--set="global.logLevel=debug" \ …
```

Add emit_tags_as_labels to envoy bootstrap config when using Consul Telemetry Collector

---

GNUmakefile
build-support/docker/Consul-Dev-Multiarch.dockerfile
build-support/docker/Consul-Dev.dockerfile
website/content/docs/k8s/installation/install.mdx

`consul:latest` no longer exists. We should instead reference `hashicorp/consul:latest` (or whichever other tag we're using).
Prior to this PR, our integration tests are broken due to the above ([example](https://github.com/hashicorp/consul/actions/runs/5395205237/jobs/9797421738)).
Our own integration tests exercise the modified Dockerfiles. They should pass on this PR.

Reference hashicorp/consul instead of consul for Docker image

---

website/content/docs/k8s/upgrade/index.mdx

Updating upgrade procedures to encompass expected CrashLoopBackOff  during upgrade process from v1.13.x to v1.14.x.
Spun up single consul-k8s on KinD cluster at:
hashicorp/consul-enterprise:1.13.8-ent
hashicorp/consul-k8s-control-plane:0.49.5
envoyproxy/envoy:v1.23.2
Upgraded cluster to:
hashicorp/consul-enterprise:1.14.7-ent
hashicorp/consul-k8s-control-plane:1.0.7
envoyproxy/envoy:v1.24.7
hashicorp/consul-dataplane:1.0.2
Followed: https://developer.hashicorp.com/consul/docs/k8s/upgrade
-->

Update Consul K8s Upgrade Doc Updates

---

website/content/docs/connect/config-entries/sameness-group.mdx

Dashes were missing for sameness groups causing errors like so 
```
Error from server (BadRequest): error when creating "./kube/configs/dc3/sameness-groups/sameness-group-unicorn.yaml": SamenessGroup in version "v1alpha1" cannot be handled as a SamenessGroup: strict decoding error: unknown field "spec.members.partition", unknown field "spec.members.peer"
```

Add dashes (-) for sameness group

---

website/content/docs/connect/native/go.mdx
website/content/docs/connect/native/index.mdx
website/content/docs/connect/proxies/integrate.mdx
website/content/docs/release-notes/consul/v1_16_x.mdx

Deprecation of connect native SDK and specific connect native APIs to discourage new users from adopting connect native until a longer term solution exists (i.e. proxyless GRPC for XDS [GH-10339](https://github.com/hashicorp/consul/issues/10339)) for native app integration into Consul Service Mesh.

docs: Deprecations for connect-native SDK and specific connect native APIs

---

.changelog/17846.txt
agent/consul/leader_connect_ca.go

Fixes https://github.com/hashicorp/consul/issues/11363
This fixes a bug that was identified, which resulted in subsequent ConnectCA configuration updates in secondary DC's not persisting in the cluster.
Details in NET-4540

Fixes Secondary ConnectCA update

---

website/content/docs/connect/intentions/jwt-authorization.mdx

fixing typo in link to jwt-validations-with-intentions doc

---

agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/jwt_authn.go
agent/xds/jwt_authn_test.go
agent/xds/testdata/jwt_authn/intention-with-path.golden
agent/xds/testdata/jwt_authn/multiple-providers-and-one-permission.golden
agent/xds/testdata/jwt_authn/remote-provider.golden
agent/xds/testdata/jwt_authn/top-level-provider-with-permission.golden
agent/xds/testdata/jwt_authn_clusters/http-provider-with-hostname-and-port.golden
agent/xds/testdata/jwt_authn_clusters/http-provider-with-hostname-no-port.golden
agent/xds/testdata/jwt_authn_clusters/http-provider-with-ip-and-port.golden
agent/xds/testdata/jwt_authn_clusters/http-provider-with-ip-no-port.golden
agent/xds/testdata/jwt_authn_clusters/https-provider-with-hostname-and-port.golden
agent/xds/testdata/jwt_authn_clusters/https-provider-with-hostname-no-port.golden
agent/xds/testdata/jwt_authn_clusters/https-provider-with-ip-and-port.golden
agent/xds/testdata/jwt_authn_clusters/https-provider-with-ip-no-port.golden

- 1/n PRs to improve jwks clusters for jwt providers authentication with intention
- This PR allows us to create a cluster per jwt-config entry. Prior to this, the envoy config would fail with the following message: `failed: [cluster = jwks_cluster] is not configured`
- The cluster has more configuration like certs and other entries that we can expose. We will be exposing them as part of a follow up PR. 
- create a jwt provider that has a remote JWKS 
- write an intention referencing that jwt provider 
- make a request without a jwt (this request should fail with `Jwt is missing%` )
- make a request with a correct jwt (this should be successful)

Dynamically create jwks clusters for jwt providers 

---

website/content/docs/api-gateway/usage/usage.mdx

Fix formatting codeblocks on APIgw docs

---

agent/structs/config_entry.go
command/config/write/config_write.go

This is a small housekeeping PR that removes the duplicate and unused `newDecodeConfigEntry` func from the `command/config/write` package. This func has been moved to the `command/helpers` package.
- Unit tests all passing
- CI passing

Remove duplicate and unused `newDecodeConfigEntry` func

---

.changelog/17894.txt
agent/configentry/resolve.go
agent/consul/config_endpoint_test.go

This PR fixes a bug that was introduced in: https://github.com/hashicorp/consul/pull/16021
A user setting a protocol in proxy-defaults would cause tproxy implicit upstreams to not honor the upstream service's protocol set in its `ServiceDefaults.Protocol` field, and would instead always use the proxy-defaults value.
Due to the fact that upstreams configured with "tcp" can successfully contact upstream "http" services, this issue was not recognized until recently (a proxy-defaults with "tcp" and a listening service with "http" would make successful requests, but not the opposite).
As a temporary work-around, users experiencing this issue can explicitly set the protocol on the `ServiceDefaults.UpstreamConfig.Overrides`, which should take precedence.
The fix in this PR removes the …

Fix incorrect protocol for transparent proxy upstreams.

---

.changelog/17939.txt
agent/consul/state/usage.go
agent/operator_endpoint_oss_test.go
agent/structs/structs.go
api/operator_usage.go
command/operator/usage/instances/usage_instances.go
command/operator/usage/instances/usage_instances_oss_test.go
website/content/api-docs/operator/usage.mdx
website/content/commands/operator/usage.mdx

Enhances the `operator/usage` API endpoint and the corresponding CLI command to include node count in the output.
Tested in dev mode
API
CLI
API doc: https://developer.hashicorp.com/consul/api-docs/operator/usage

feat: include nodes count in operator usage endpoint and cli command

---

website/content/docs/connect/proxies/envoy-extensions/usage/ext-authz.mdx

This PR fixes a typo in the ext-authz usage docs.

updated typo in tab heading

---

agent/xds/listeners.go
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
test/integration/consul-container/libs/utils/helpers.go
test/integration/consul-container/test/jwtauth/jwt_auth_test.go

- Introduces an integration test for JWT auth with intentions. The test spins up a static-server and client, write a jwt-provider and intention, verifies that this blocks/allows request as expected.
- Inverting rbac filters and jwt-auth filters because the jwt-auth filters are supposed to forward data to the rbac filters. So when rbac get evaluated first, it will be doing so without the potential jwt-auth filter data
```
$ make test-compat-integ-setup
$ cd ./test/integration/consul-container
test/integration/consul-container$ go test -v ./test/jwtauth -timeout 2m
```

Add first integration test for jwt auth with intentions

---

website/content/docs/connect/config-entries/control-plane-request-limit.mdx

This PR changes the stand-in text for the `name` field in the complete configuration section.

fix stand-in text for name field

---

website/data/docs-nav-data.json

This PR removes the alias for sameness groups configuration entry from the Failover > Configuration. We will reconsider this area of the docs for 1.17

removed sameness conf entry from failover nav

---

website/content/docs/k8s/annotations-and-labels.mdx
website/content/docs/k8s/service-sync.mdx

Docs for https://github.com/hashicorp/consul-k8s/pull/2293 and also adding new section for Service Sync in the annotations page.

docs - add service sync annotations and k8s service weight annotation

---

website/content/docs/k8s/connect/index.mdx

Add jobs use case for service mesh on k8s and provides better organization for workload types on the mesh.

docs - add jobs use case for service mesh k8s

---

website/content/docs/k8s/helm.mdx

Changes from 1.1.x. Reviewing to see if these are correct.

docs - helm consul k8s 1.1.x helm chart reference

---

agent/structs/config_entry_inline_certificate_test.go

This error message is different when running the test against FIPS build as noted in the comments.

test: fix FIPS inline cert test message

---

website/content/docs/k8s/connect/cluster-peering/tech-specs.mdx
website/content/docs/k8s/connect/cluster-peering/usage/establish-peering.mdx
website/content/docs/k8s/l7-traffic/failover-tproxy.mdx
website/content/docs/k8s/l7-traffic/route-to-virtual-services.mdx

Mention peering over mesh gateways `Mesh` config that is required. Also update to consul k8s 1.2.0 on Virtual services

docs updates - cluster peering and virtual services

---

.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations.yml

Specifically to for this fix: https://github.com/gotestyourself/gotestsum/pull/338
@freddygv reported (internally) that a subtest `TestDecodeConfigEntry/service-defaults*` was passing on retry when it should have failed repeatably. 
You can see in the raw logs for e.g. https://github.com/hashicorp/consul/actions/runs/4930752511/jobs/8813642599?pr=17208 that the test was retried, failed, but that the job succeeded.
```
2023-05-09T22:12:05.3648472Z exec: [go test -json -test.run=^TestDecodeConfigEntry$/^service-defaults_(camel_case)$ -tags= -p 2 -cover -coverprofile=coverage.txt github.com/hashicorp/consul/agent/structs]
2023-05-09T22:12:05.3649057Z go test pid: 35074
2023-05-09T22:12:06.3734309Z [32mPASS[0m agent/structs.TestDecodeConfigEntry (re-run 1) (0.00s) …
```

ci: use gotestsum v1.10.1 [NET-4042]

---

website/content/docs/connect/dataplane/consul-dataplane.mdx
website/content/docs/k8s/annotations-and-labels.mdx

Docs part of the proxy lifecycle work. Add new consul-k8s pod annotations and consul-dataplane flags.
Followed the links created in Vercel and verified that they worked.

Docs: Update proxy lifecycle annotations and consul-dataplane flags

---

.changelog/17885.txt
agent/connect/ca/provider_vault_auth_aws.go
agent/connect/ca/provider_vault_auth_test.go

Fixes https://github.com/hashicorp/consul/issues/17887.
When using Connect, with Vault CA, with AWS auth - this change ensures that the `role` name (if configured) is passed as part of the login request. Prior to this change, Consul did not respect this parameter and therefore always falls back to the default Vault behaviour of using the instance AWS IAM role name, even if `role` was specified in `params`.
- Added additional coverage to the existing `TestVaultCAProvider_AWSLoginDataGenerator`  tests.
1. Create a file with CA configuration, e.g.
```
{
"Provider": "vault",
"Config": {
"Address": "https://my.vault.server:8200",
"IntermediatePKIPath": "pki_int",
"RootPKIPath": "pki",
"AuthMethod": {
"Type": "aws",
"MountPath": "aws",
"Params": {
"role": "configured-role-name"
}
}
}
}
```
2. …

Passes configured role name to Vault for AWS auth in Connect CA

---

website/content/docs/upgrading/index.mdx

consul leave is bad during upgrades because the leaving server will disconnect and think there is no leader and initiate a series of new elections, but cannot communicate with others.  When it comes up, its term is much higher than the leader and the leader will detect this and step down.  Having the leader change is bad when you are trying to guarantee that the leader is upgraded last.
We've already changed this on the general upgrade process page.  This is another instance we just found

[NET-4876] docs - update upgrade index page to not recommend consul leave.

---

website/content/docs/k8s/helm.mdx

- Updating helm docs as part of the consul-k8s 0.49.8 release process
- There are so many changes here because the helm docs were not updated when 0.49.7 was released.
👀

Add updated helm docs for consul-k8s 0.49.8

---

.github/workflows/build-distros.yml
.github/workflows/build.yml
.github/workflows/go-tests.yml
.github/workflows/reusable-dev-build.yml

This PR adds build and unit test support for the s390x architecture in Consul Enterprise automated workflows.
The following changes have been made:
- Build the Consul binary for s390x.
- Run tests using a dev build of the above binary.
Tested in ENT: https://github.com/hashicorp/consul-enterprise/pull/6265

[NET-4103] ci: build s390x

---

website/content/docs/concepts/service-mesh.mdx
website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/gateways/index.mdx
website/content/docs/connect/gateways/ingress-gateway/index.mdx
website/content/docs/k8s/connect/ingress-gateways.mdx

This adds notices, that ingress gateway is deprecated, to several places in the product docs where ingress gateway is the topic.
Tested with a local copy of the website.
Deprecation of ingress gateway was announced in the Release Notes for Consul 1.16 and Consul-K8s 1.2. See:
[https://developer.hashicorp.com/consul/docs/release-notes/consul/v1_16_x#what-s-deprecated](https://developer.hashicorp.com/consul/docs/release-notes/consul/v1_16_x#what-s-deprecated
)
[https://developer.hashicorp.com/consul/docs/release-notes/consul-k8s/v1_2_x#what-s-deprecated](https://developer.hashicorp.com/consul/docs/release-notes/consul-k8s/v1_2_x#what-s-deprecated)
* [N/A] updated test coverage

Add ingress gateway deprecation notices to docs

---

website/content/docs/connect/config-entries/jwt-provider.mdx

- Add jwt-provider docs for jwks cluster configuration. The configuration was added here: https://github.com/hashicorp/consul/pull/17978

Add docs for jwt cluster configuration

---

website/content/docs/services/usage/checks.mdx

- Fix unmatched bracket in the [doc](https://developer.hashicorp.com/consul/docs/services/usage/checks#ttl-check-configuration) (see the following screenshot of the page)

Docs: fix unmatched bracket for health checks page

---

agent/acl_test.go
agent/agent.go
agent/consul/client.go
agent/consul/server.go

Dan had already started on this [task](https://github.com/hashicorp/consul/pull/17849) which is needed to start building the HTTP APIs. This just needed some cleanup to get it ready for review.
Overview:
- Rename `internalResourceServiceClient` to `insecureResourceServiceClient` for name consistency
- Configure a `secureResourceServiceClient` with auth enabled

NET-4657/add resource service client

---

.changelog/18112.txt
agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/structs/connect_ca.go

Vault can be used as a CA for Consul service mesh ([docs](https://developer.hashicorp.com/consul/docs/connect/ca/vault)). Typically an organization's root trust CA is stored as a root mount (configured by `RootPKIPath`) in Vault. Consul uses an intermediate CA (stored in `IntermediatePKIPath`) signed by the root to issue leaf certificates to agents and services in the mesh.
Updating [RootPKIPath](https://developer.hashicorp.com/consul/docs/connect/ca/vault#rootpkipath) but not [IntermediatePKIPath](https://developer.hashicorp.com/consul/docs/connect/ca/vault#intermediatepkipath) would not update leaf signing certs with the new root. Unsure if this happens in practice but manual testing showed it is a bug that would break mesh and agent connections once the old root is pruned.
Added a unit …

Fix bug with Vault CA provider

---

agent/ui_endpoint.go

This is to correct a code problem because this assumes all segments, but when you get to Enterprise, you can be in partition that is not the default partition, in which case specifying all segments does not validate and fails.  This is to correct the setting of this filter with `AllSegments` to `true` to only occur when in the the `default` partition.

add a conditional around setting LANFilter.AllSegments to make sure it is valid

---

.github/workflows/test-integrations.yml
test/integration/consul-container/libs/utils/version.go

1.15 and 1.16 are current. 1.14 is not
Sidequest: apparently we don't use the mirror any more

chore: bump upgrade integrations tests to 1.15, 116 [NET-4743]

---

agent/consul/client_test.go
agent/consul/options.go
agent/consul/server.go
agent/consul/type_registry.go
agent/rpc/peering/service_test.go
agent/setup.go
docs/resources/guide.md

In this PR, we lift the `registry` out of the server code so that client, server and cli can share the registry. It's stored in `BaseDeps.Deps` (not `setup.go` but `options.go`) because when we newServer, we are passing `baseDeps.Deps` instead of `baseDeps`.
This [PR](https://github.com/hashicorp/consul/pull/18052/files) shows how we use the registry when register the http endpoints.
Notice I changed the signature of functions: `setupExternalGRPC` and `setupInternalResourceService`. Please let me know if there are better options.

re org registry

---

agent/delegate_mock_test.go

The mock is used in `http_ent_test` file which caused lint failures. For OSS->ENT parity adding the same change here.
Identified in OSS->ENT [merge PR](https://github.com/hashicorp/consul-enterprise/pull/6328)

fix: update delegateMock used in ENT

---

website/content/docs/agent/config/config-files.mdx

Addresses https://github.com/hashicorp/consul/pull/17171#issuecomment-1636930705

Change docs to say 168h instead of 7d for server_rejoin_age_max

---

GNUmakefile
test/integration/consul-container/libs/assert/service.go

- with changes introduced in: https://github.com/hashicorp/consul/pull/18130/files, make dev-docker still builds `consul:local` image whilst the integration tests locally are looking for `hashicorp/consul:local`. This PR fixes that 
- Little bonus: whilst working on integration tests I realized `AssertContainerState` gives the container statuses in reverse orders 
- CI tests
- or locally: `make dev-docker` and run any integration test of your choice

Re-order expected/actual for assertContainerState in consul container tests

---

.changelog/17160.txt
agent/dns.go
agent/dns_test.go

This a backport of https://github.com/hashicorp/consul/pull/17160

Fix a bug that wrongly trims domains when there is an overlap with DC name 1.14.x

---

.changelog/17160.txt
agent/dns.go
agent/dns_test.go

This is a backport of https://github.com/hashicorp/consul/pull/17160

Fix a bug that wrongly trims domains when there is an overlap with DC name 1.15.x

---

.changelog/17160.txt
agent/dns.go
agent/dns_test.go

This is a backport of https://github.com/hashicorp/consul/pull/17160

Fix a bug that wrongly trims domains when there is an overlap with DC 1.16.x

---

test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/test/jwtauth/jwt_auth_test.go

- Add jwt-auth with intentions integration tests
- The test covers validation across service identities, claims verification/validation and multiple permissions referencing different providers
- Remove unnecessary old claims 
```
$ make test-compat-integ-setup
$ cd ./test/integration/consul-container
$ go test -v ./test/jwtauth -timeout 2m
```

[NET-4792] Add integrations tests for jwt-auth

---

api/prepared_query.go

Manual backport of c2bbe67714ee7c603447e18c25ad391b8de6226e.
This change is needed to address client errors for consumers of the `api` submodule. Backporting to the only release line the bug exists in (1.16).
No changelog was added for the original fix in `main`, so will add one in a separate change in `main` and backport it.
I expect automated tests to continue to pass.

[NET-3700] add `omitempty` to api prepared query targets

---

.changelog/18190.txt
.github/workflows/build.yml
build-support/docker/Build-Go.dockerfile

This resolves [CVE-2023-29406](https://nvd.nist.gov/vuln/detail/CVE-2023-29406) for uses of the `net/http` standard library.
Note that until the follow-up to #18124 is done, the version of Go used in those impacted tests will need to remain on 1.20.5.
See related PR for `golang.org/x/net` dependencies: https://github.com/hashicorp/consul/pull/18186
Resolves CVE and brings us up to the latest version of Go.
Tests should continue to pass.
https://nvd.nist.gov/vuln/detail/CVE-2023-29406
https://go-review.googlesource.com/c/go/+/506996
https://go-review.googlesource.com/c/net/+/506995

[NET-4865] security: Update Go version to 1.20.6

---

.github/workflows/build.yml

Our verification process requires running the binary. We have no hardware to do this for `s390x`, so we can't verify.

ci: don't verify s390x

---

website/content/docs/k8s/deployment-configurations/servers-outside-kubernetes.mdx
website/content/docs/k8s/helm.mdx

Add guidance for proper configuration when joining to a secondary cluster using WAN fed with external servers also enabled.
Also clarify federation requirements and fix formatting for an unrelated value.
Update both the Helm chart reference (synced from `consul-k8s`, see hashicorp/consul-k8s#2583) and the docs on using `externalServers`.
GH issue inspiring this clarification: https://github.com/hashicorp/consul-k8s/issues/2138

[NET-4122] Doc guidance for federation with externalServers

---

agent/proxycfg/testing.go
agent/proxycfg/testing_mesh_gateway.go
agent/structs/structs_test.go
agent/structs/testing_catalog.go
agent/xds/clusters_test.go
agent/xds/config.go
agent/xds/delta_test.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/rbac.go
agent/xds/testdata/clusters/custom-passive-healthcheck-zero-consecutive_5xx.latest.golden
agent/xds/testdata/clusters/ingress-with-overwrite-defaults-passive-health-check.latest.golden
agent/xds/testdata/clusters/mesh-gateway-using-federation-control-plane.latest.golden
agent/xds/testdata/clusters/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-using-federation-control-plane.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
agent/xds/testdata/listeners/ingress-with-tls-mixed-cipher-suites-listeners.latest.golden
agent/xds/testdata/listeners/ingress-with-tls-mixed-max-version-listeners.latest.golden
agent/xds/testdata/listeners/mesh-gateway-using-federation-control-plane.latest.golden

Improves test coverage in the xDS package for endpoints and other miscellaneous xDS files. 
* Routes TBD
* Listeners [OSS PR](https://github.com/hashicorp/consul/pull/18138)
* Clusters  [OSS PR](https://github.com/hashicorp/consul/pull/18165)
* Endpoints & Misc -OSS (this PR)

[OSS] Improve xDS Code Coverage - Endpoints and Misc

---

.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

NET-4996 - filter go-tests and test-integration workflows from running on docs only and ui only changes

---

.github/workflows/build.yml

Ensure that OSS remains in sync w/ Enterprise by aligning the format of arch matrix args for various build jobs.
This should help lower the chance of merge conflicts in the future.
Backporting to 1.16; prior to that branch, there was no divergence as it predates FIPS support in Enterprise.

Align build arch matrix with enterprise

---

grafana/consul-k8s-control-plane-monitoring.json

This is a follow-up PR to #18208 and adds the panel of the connect injector pod's  resource usage
Also reformat the file by `json prettify`.

grafana: add the panel resource usage of connect injector

---

website/content/docs/enterprise/license/utilization-reporting.mdx
website/data/docs-nav-data.json

Automated reporting for license consumptions was added to this release, but the docs were not back-ported. This PR adds the docs for this functionality.

add auto lic usage docs

---

api/api.go

A new [issue](https://github.com/golang/go/issues/61431) has been created on the Go project backlog that replaces the comment thread that was on the PR that introduced the breaking change.

NET-4897 - update comment to include the current issue url from the go team.

---

website/content/docs/enterprise/license/utilization-reporting.mdx

This PR fixes some issues in the documentation for the automated license consumption reporting functionality

fix typos, style, and improper links

---

.github/workflows/go-tests.yml

Disable `s390x` go tests due to resource contention and flakeyness.

go-tests: disable s390x

---

.changelog/18223.txt
agent/agent_endpoint.go
api/agent.go
api/agent_test.go
command/members/members.go
website/content/commands/members.mdx

Manual backport of #18223 
The autogenerated one #18275  contains many irrelevant commits.

Backport of member cli: add -filter expression to flags into release/1.15.x

---

website/content/docs/connect/proxies/envoy-extensions/usage/ext-authz.mdx

Update ext-authz documentation for kubernetes

docs: Update ext-authz documentation for kubernetes

---

website/content/docs/connect/proxies/envoy-extensions/index.mdx

Fix typo in Envoy extensions doc

---

.changelog/18140.txt
agent/hcp/bootstrap/bootstrap.go
agent/hcp/bootstrap/bootstrap_test.go

---
We are removing the requirement for HCP to provide Consul with a management token to support read-only tokens. This changes the validations to allow for a management token to be missing/ignored during bootstrapping with HCP.
[OSS PR](https://github.com/hashicorp/consul/pull/18140)
[Ticket](https://go.hashi.co/cc5718)
[RFC](https://go.hashi.co/rfc-read-only)

Backport of [CC-5718] Remove HCP token requirement during bootstrap

---

website/content/docs/k8s/deployment-configurations/multi-cluster/kubernetes.mdx
website/content/docs/k8s/deployment-configurations/multi-cluster/vms-and-kubernetes.mdx

This PR responds to a request to highlight the Kubernetes WAN Federation requirement that when ACLs are enabled, the Kube API of the secondary datacenters must be routable from the primary datacenter.
- [JIRA Ticket](https://hashicorp.atlassian.net/browse/CE-433)
- [Slack convo](https://hashicorp.slack.com/archives/CMTKDL287/p1660697937824169)

docs: K8s secondary DC requirements

---

.changelog/18291.txt
agent/proxycfg/api_gateway.go

This fixes a race condition due to our dependency on having the listener(s) from the api-gateway config entry in order to fully and properly process the resources on the bound-api-gateway config entry.
Existing tests should all pass

api-gateway: subscribe to bound-api-gateway only after receiving api-gateway

---

.changelog/13023.txt
agent/consul/state/catalog.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

If a service is registered twice, once with connect-native and once
without, the topology views would prune the existing intentions. This
change brings the code more in line with the transparent proxy behavior.

Fix topology view when displaying mixed connect-native/normal services.

---

.changelog/18325.txt
agent/structs/config_entry_jwt_provider.go
agent/structs/config_entry_jwt_provider_oss.go

JWT provider config entries are supposed to be globally available via default namespace. Adding missing validation

Stop JWT provider from being written in non default namespace

---

website/content/docs/enterprise/license/utilization-reporting.mdx

Ensure that all release branches are aligned on content.
@trujillo-adam I realized I missed this one when we paired - did we want backports of this doc to 1.13 since that line is no longer being released?
(The simplest thing at this point is to merge this either way; y'all can always remove if you want after)

Fix utilization reporting docs sync

---

.changelog/18068.txt
agent/xds/delta.go
agent/xds/delta_envoy_extender_oss_test.go
agent/xds/delta_test.go
envoyextensions/extensioncommon/basic_envoy_extender.go
envoyextensions/extensioncommon/envoy_extender.go
envoyextensions/extensioncommon/runtime_config.go
envoyextensions/extensioncommon/upstream_envoy_extender.go
envoyextensions/go.mod
envoyextensions/go.sum
envoyextensions/xdscommon/xdscommon.go
envoyextensions/xdscommon/xdscommon_test.go

Ensure that non-required extensions do not change xDS resources before exiting on failure by cloning proto messages prior to applying each extension.
Also avoid unnecessary cloning by moving `CanApply` checks up a layer and making them before application is attempted.
Today, it's theoretically possible that a non-required extension could fail partway through making updates. If that extension is not configured as `Required`, we will not short-circuit xDS updates; the error will be logged and swallowed, allowing any other extensions to continue applying before updating xDS resources.
By proactively cloning resources that are subject to extensions, s.t. we do not pass any data by reference that is intended to be modified atomically, we can prevent the unintentional partial application of …

[NET-4703] Prevent partial application of Envoy extensions

---

website/content/docs/connect/ca/consul.mdx
website/content/docs/ecs/manual/secure-configuration.mdx
website/content/docs/security/acl/auth-methods/oidc.mdx
website/content/docs/troubleshoot/common-errors.mdx

Simplify jq command examples by removing pipes to other commands.
Simply command examples with `jq` by no longer piping data to other commands. `jq` can internally handle all of the operations  that were being performed by the removed commands. This should also make the command examples more portable across non-Unix operating systems.
I've manually tested each of the modified commands to ensure that they return the same output that was generated with the previous command.

docs: Simplify example jq commands by removing pipes

---

website/content/docs/security/acl/tokens/create/create-a-mesh-gateway-token.mdx

fix typo in create a mesh token docs

---

internal/resource/decode.go
internal/resource/decode_test.go
internal/resource/equality.go
internal/resource/equality_test.go
internal/resource/errors.go
internal/resource/mappers/bimapper/bimapper.go
internal/resource/mappers/bimapper/bimapper_test.go
internal/resource/reference.go
internal/resource/refkey.go
internal/resource/refkey_test.go
internal/resource/resourcetest/builder.go
internal/resource/resourcetest/client.go
internal/resource/resourcetest/decode.go
internal/resource/resourcetest/validation.go
internal/resource/stringer.go

This is a bit of a grab bag of helpers that I found useful for working with them when authoring substantial Controllers. Subsequent PRs will make use  of them.

resource: adding various helpers for working with resources

---

internal/mesh/exports.go
internal/mesh/internal/types/proxy_state_template.go
internal/mesh/internal/types/types.go
proto-public/pbmesh/v1alpha1/proxy_state.pb.go
proto-public/pbmesh/v1alpha1/proxy_state.proto

* Register ProxyStateTemplate Resource
* also change the ProxyState.id to identity. This is because we already have the id of this proxy from the resource, and this id should be name-aligned with the workload it represents. It should also have the owner ref set to the workload ID if we need that. And so the id field seems unnecessary. We do, however, need a reference to workload identity so that we can authorize the proxy when it initially connects to the xDS server.
* N/A updated test coverage
* N/A external facing docs updated

Register ProxyStateTemplate Resource

---

internal/resource/mappers/bimapper/bimapper.go
internal/resource/mappers/bimapper/bimapper_test.go

Fixes a small bug introduced in https://github.com/hashicorp/consul/pull/18342

bimapper: fix a bug and add some more test coverage

---

.changelog/18367.txt
agent/http.go

Removed new line in response when running consul in dev mode. This fixes https://github.com/hashicorp/consul/issues/17730.
Keeping new line only when pretty is passed in the url not in dev mode.
Reproduction steps
```
1. make dev
2. ./bin/consul agent -data-dir=/tmp/consul  -node consul -bind 0.0.0.0 -server -bootstrap  -ui -dev
3. Open browser and network tab - save some k/v - observe new line in xhr response.
4. ./bin/consul agent -data-dir=/tmp/consul  -node consul -bind 0.0.0.0 -server -bootstrap  -ui
5. Open browser and network tab - save some k/v - observe no new line in xhr response
```
Tested the code with the above steps and issue is fixed. i.e. could not see any new line in dev mode now.

Fix #17730 - Dev mode has new line

---

internal/catalog/internal/types/service_endpoints.go
internal/catalog/internal/types/service_endpoints_test.go
internal/resource/errors.go
internal/resource/resourcetest/builder.go
internal/resource/resourcetest/require.go

Apparently when implementing the hooks previously I missed some tests for the Mutation hook specifically so this is adding them.
I also discovered that one error emitted by the Mutation hook wasn't filling in all the necessary fields and have fixed that.
This PR is mainly just adding tests.

Add ServiceEndpoints Mutation hook tests

---

internal/catalog/exports.go
internal/catalog/internal/controllers/failover/controller.go
internal/catalog/internal/controllers/failover/controller_test.go
internal/catalog/internal/controllers/failover/status.go
internal/catalog/internal/controllers/register.go
internal/catalog/internal/mappers/failovermapper/failover_mapper.go
internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
internal/resource/decode.go
internal/resource/decode_test.go
proto/private/prototest/testing.go

Add most of the semantic cross-resource validation for FailoverPolicy resources using a new controller.
NET-5051
NET-5056

catalog: adding a controller to reconcile FailoverPolicy resources

---

agent/agent_endpoint_test.go
agent/agent_test.go

The delegateMock missed some function mocking which breaks tests in ent repo. This is a fix for that.

fix the error in ent repo

---

CHANGELOG.md
api/go.mod
envoyextensions/go.mod
envoyextensions/go.sum
go.mod
test-integ/go.mod
test/integration/consul-container/go.mod
testing/deployer/go.mod
testing/deployer/go.sum
troubleshoot/go.mod

Updates following the release of 1.16.1, 1.15.5, 1.14.9, and the new set of submodules.

build: updates for 1.16.1 release

---

website/content/docs/ecs/index.mdx

Update Consul ECS link to newly created tutorial.
Deprecate links to legacy tutorials.

update ECS links

---

website/content/docs/connect/proxies/envoy-extensions/usage/lua.mdx

The current example `proxy-defaults` config is incorrect and will cause these errors. 
```
Failed to decode config entry input: Failed to decode config entry input: At 22:1: heredoc not terminated
Failed to decode config entry input: 1 error occurred:
* invalid config key "Protocol"
```
I updated the config with correct `protocol` setting, as well as changed heredoc delimiter to `EOF` to be consistent with other examples in `service-defaults`.
- Built the doc locally with `make`
- Copy and apply the config successfully in Consul Dev
```
consul config write correct.hcl
Config entry written: proxy-defaults/global
```
https://developer.hashicorp.com/consul/docs/connect/proxies/envoy-extensions/usage/lua

docs: fix incorrect proxy-defaults config in Lua Envoy extension

---

agent/consul/tenancy_bridge_oss.go
agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/mock_TenancyBridge.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/testing/testing.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_test.go
internal/mesh/internal/types/proxy_state_template.go
internal/resource/demo/demo.go
internal/resource/registry.go
internal/resource/registry_test.go
internal/resource/tenancy.go

OSS version of https://github.com/hashicorp/consul-enterprise/pull/6571.  See NET-4911.
Zero additional changes from the branch in ENT.

resource: Make resource write tenancy aware

---

.github/workflows/go-tests.yml

Once we figure out what to do with license headers for these files we should re-enable this check.

Disable deep-copy codegen verification for now.

---

website/content/commands/services/export.mdx
website/content/commands/services/index.mdx
website/data/commands-nav-data.json

Consul 1.16 introduced the `services export` command in the Consul CLI via #14547 / #15654 , and I intended to add docs at the time but forgot. These are the docs.
Verify docs match usage introduced in #15654.
[Vercel deploy](https://consul-git-export-docs-hashicorp.vercel.app/consul/commands/services/export)

NET-4952 Add docs for export command

---

website/content/docs/k8s/helm.mdx

Updates helm values docs to be consistent with consul-k8s 1.0.9

Updates helm values for consul-k8s 1.0.9

---

test/integration/consul-container/libs/service/connect.go

If `--follow-log=true` several upgrade tests timeout after passing. This was as a result of container failing to stop due to log producer not being stopped before container restart
**SOLUTION**
To restart a container - sidecar:
- Stop log producer
- Stop Container
- Start Container
- Start Log Producer
Then container can be stopped and terminated gracefully.

NET-5187: Upgrade test timeout due to log producer errors

---

website/content/docs/k8s/helm.mdx

Updates 1.15.x to match changes made for other versions of consul-k8s.
https://github.com/hashicorp/consul/pull/18447
The PR for the changes in consul-k8s can be found here: https://github.com/hashicorp/consul-k8s/pull/2775

Updates 1.15.x for changes to helm docs

---

agent/xds/clusters.go
agent/xds/config/config.go
agent/xds/config/config_test.go
agent/xds/configfetcher/config_fetcher.go
agent/xds/listeners.go
agent/xds/listeners_apigateway.go
agent/xds/listeners_ingress.go
agent/xds/listeners_test.go
agent/xds/naming/naming.go
agent/xds/platform/net_fallback.go
agent/xds/platform/net_linux.go
agent/xds/proxystateconverter/clusters.go
agent/xds/proxystateconverter/converter.go
agent/xds/proxystateconverter/listeners.go
agent/xds/resources.go
agent/xds/routes.go
agent/xds/server.go
agent/xdsv2/cluster_resources.go
agent/xdsv2/listener_resources.go
agent/xdsv2/resources.go
agent/xdsv2/route_resources.go
proto-public/pbmesh/v1alpha1/proxy_state.pb.go
proto-public/pbmesh/v1alpha1/proxy_state.proto
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/helpers.windows.bash

* This creates the proxystateconverter component for converting snapshots into proxystate and an xdsv2 package for turning proxystate into envoy resources.
*  The scope of this PR is supporting L4 listeners for connect proxies, and making all of those tests pass.
* The converter component should not import xds (it will eventually be moved out of xds into proxycfg, to convert v1 `proxycfg.ConfigSnapshot` into `pbmesh.ProxyState` when xdsv2 is complete and usable by v1.
* Any sorting should occur in the xdsv2 package, rather than in the converter.

[NET-4799] [OSS] xdsv2: listeners L4 support for connect proxies

---

agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_test.go
agent/grpc-external/services/resource/watch.go
internal/mesh/internal/types/proxy_state_template.go
internal/resource/demo/demo.go
internal/resource/registry.go
internal/resource/registry_test.go

CE version of already approved ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6600.
Clean merge, no changes.
See NET-4915 for details.

resource: Make resource list tenancy aware

---

website/content/docs/agent/config/config-files.mdx

Updates docs to specify what operator intervention is needed to restart a stale server.

docs: specify manual server metadata intervention

---

website/content/docs/k8s/compatibility.mdx

Remove restriction of default CNI plugin only supported with OpenShifSDN as this is now working with OVN Kubernetes as of OpenShift 4.12.

docs: Update OpenShift compatibility 

---

agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/server_test.go

CE version of already approved ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6640
Clean merge with no changes.
See NET-4919 for details.

resource: Make resource delete tenancy aware

---

.github/scripts/license_checker.sh
.github/workflows/license-checker.yml

We want to make sure that we aren't accidentally backporting the BUSL license header into versions of Consul that should remain under MPL through the end of the year.
Run script locally on `main` where it should fail, identifying files which have the BUSL header, and on release branches such as `release/1.16.x` where it should succeed since no files have the BUSL header.

Add license-checker action that fails when any backported file contains BUSL header

---

website/content/docs/k8s/connect/terminating-gateways.mdx

The `grep` command used to obtain the ID for the terminating gateway role is not reliable in all scenarios. For example, if there is a similarly named role, the command may return the wrong role ID for the active terminating gateway instance.
This commit updates the command to use jq to obtain the role ID. If multiple roles are found, jq will raise an error informing the user that it cannot reliably determine the role ID.

docs: Update K8s TGW tutorial to reliably obtain role ID

---

.github/scripts/license_checker.sh
.github/workflows/license-checker.yml

I created a test PR (#18486) after merging this action originally in https://github.com/hashicorp/consul/pull/18485 and realized that `grep` behaves differently in `ubuntu:latest` than it does in MacOS.
This updates to use a format that works in Ubuntu and runs the action whenever new commits are pushed to a backport PR instead of just when it's initially opened.
Ran script in an Ubuntu docker container
```bash
$ docker run -it ubuntu:latest /bin/sh
$ apt update && apt install git
$ git clone https://github.com/hashicorp/consul
$ cd consul
$ ./.github/scripts/license_checker.sh
$ git checkout release/1.15.x
$ git checkout license-checker-pt2 -- .github/scripts/license_checker.sh
$ ./.github/scripts/license_checker.sh
```

NET-5371 License checker pt2

---

README.md
website/content/docs/dynamic-app-config/kv.mdx

Renaming the KV use case to Dynamic APP Configuration. Re-positioning KV as our KV API is feature complete but is a relatively simple KV system and not meant for large scale KV use. Also adding a note around the KV being feature complete.

README - Update KV use case to Dynamic App Configuration 

---

sdk/testutil/retry/timer.go
test/integration/consul-container/libs/assert/service.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/helpers.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/libs/topology/service_topology.go
test/integration/consul-container/test/envoy_extensions/ext_authz_test.go
test/integration/consul-container/test/envoy_extensions/wasm_test.go
test/integration/consul-container/test/jwtauth/jwt_auth_test.go
test/integration/consul-container/test/tproxy/tproxy_test.go
test/integration/consul-container/test/upgrade/ingress_gateway_grpc_test.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
test/integration/consul-container/test/upgrade/peering/peering_http_test.go
test/integration/consul-container/test/wanfed/wanfed_peering_test.go

* Support including locality in client sidecar config.
* Refactor fortio test helpers to separate HTTP retries from waiting on fortio result changes due to e.g. service startup and failovers.
* Align test config structs with Ent to avoid future conflicts.
I was planning to backport the non-locality changes further back, but there's other divergence that complicates doing that, so just doing 1.16 for now.
_Note: these changes are primarily to support Ent testing in a separate change_

[NET-5163] Support locality testing in consul-container

---

.changelog/18439.txt
internal/controller/api.go
internal/controller/api_test.go
internal/controller/controller.go
internal/controller/dependency_mappers.go

This PR introduces custom watch support to the Consul Controller framework.

Support custom watches on controller

---

.github/workflows/nightly-test-integrations.yml
.github/workflows/test-integrations.yml

This PR splits our integration test into 2 sets: one keeps being triggered on every PR and the other to run nightly.
- Vault, nomad test
- compatibility test
- Peering test
- Envoy version 1.27
- Upgrade test
- Envoy versions ["1.24.10", "1.25.9", "1.26.4"]
The reason we split envoy versions is because the dozens of envoy tests run on xlarge runner and each takes 5mintes to complete (link to a recent [run](https://github.com/hashicorp/consul/actions/runs/5895542915/job/15991642741)).
Backport PR will be made manually due to the version conflict.

CI Split integration tests to run nightly and every PR

---

internal/catalog/exports.go
internal/catalog/internal/controllers/failover/controller.go
internal/catalog/internal/mappers/failovermapper/failover_mapper.go
internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
internal/catalog/internal/types/failover_policy_test.go
internal/resource/decode.go
internal/resource/decode_test.go
internal/resource/resourcetest/decode.go

The `DecodedResource` was requiring two type arguments in order to call `make` on the concrete type and get a pointer to one. 
This PR modifies the `Decode` function so that it uses the protobuf system for allocating a new struct and then decodes into that. This allows dropping one of the two Types.
Existing tests still work

Reduce required type arguments for DecodedResource

---

internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/failover_policy_test.go

Check for unknown enum values of FailoverMode during validation and block them.
This sort of thing is required for `proto3` open enums: https://protobuf.dev/programming-guides/enum/

catalog: add failover mode enum validation

---

internal/catalog/exports.go
internal/catalog/internal/controllers/failover/controller.go
internal/catalog/internal/mappers/failovermapper/failover_mapper.go
internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
internal/catalog/internal/types/failover_policy_test.go
internal/mesh/internal/types/computed_routes.go
internal/mesh/internal/types/computed_routes_test.go
internal/mesh/internal/types/destination_policy.go
internal/mesh/internal/types/destination_policy_test.go
internal/mesh/internal/types/grpc_route.go
internal/mesh/internal/types/grpc_route_test.go
internal/mesh/internal/types/http_route.go
internal/mesh/internal/types/http_route_test.go
internal/mesh/internal/types/proxy_configuration.go
internal/mesh/internal/types/tcp_route.go
internal/mesh/internal/types/tcp_route_test.go
internal/mesh/internal/types/util.go
internal/mesh/internal/types/xroute.go
internal/resource/decode.go
internal/resource/decode_test.go
internal/resource/resourcetest/decode.go
proto-public/pbmesh/v1alpha1/xroute_addons.go
proto-public/pbmesh/v1alpha1/xroute_addons_test.go

Adds validation for HTTPRoute, GRPCRoute, TCPRoute, DestinationPolicy, and ComputedRoutes.
NET-5054
NET-5055

mesh: add validation for the new pbmesh resources

---

internal/mesh/internal/types/decoded.go
internal/resource/decode.go

Introduces some simple type aliases for `DecodedResource[*X]` wrappers for each type which cut down on the verbosity in my own code so instead of having something like:
```
stuff map[resource.ReferenceKey]*resource.DecodedResource[*pbmesh.HTTPRoute]
```
you have
```
stuff map[resource.ReferenceKey]*types.DecodedHTTPRoute
```

mesh: adding type aliases for mesh resource usage

---

agent/consul/server.go
internal/mesh/exports.go
internal/mesh/internal/controllers/register.go
internal/mesh/internal/controllers/xds/controller.go
internal/mesh/internal/controllers/xds/controller_test.go
internal/mesh/internal/controllers/xds/mock_updater.go
internal/mesh/internal/controllers/xds/status/status.go

clone of https://github.com/hashicorp/consul-enterprise/pull/6684

Update trust bundle into proxy-state-template

---

internal/catalog/internal/types/service.go
internal/catalog/internal/types/service_endpoints.go
internal/catalog/internal/types/service_endpoints_test.go
internal/catalog/internal/types/service_test.go
internal/catalog/internal/types/validators.go
internal/catalog/internal/types/validators_test.go
internal/catalog/internal/types/workload.go
internal/catalog/internal/types/workload_test.go

Check for unknown enum values of `Protocol` and `Health` during validation and block them in the catalog.
This sort of thing is required for `proto3` open enums: https://protobuf.dev/programming-guides/enum/
Related: https://github.com/hashicorp/consul/pull/18545

catalog: validating Protocol and Health enums on Service, Workload, and ServiceEndpoints

---

.changelog/18464.txt
ui/packages/consul-ui/app/serializers/application.js
ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
ui/packages/consul-ui/tests/unit/serializers/application-test.js

Fixes #18406 
Hi @david-yu 
Fixed the ui for non-presence of consul-version in Node meta.

fix for , non presence of consul-version meta

---

sdk/testutil/server.go

To test gRPC connections in `consul-k8s`, the experiments config option must be configured.

feat: add experiments flag to testserver sdk
