.changelog/18558.txt
agent/local/state.go

Prevent go routine leakage due to existing DeferCheck
Please refer to https://github.com/hashicorp/consul/issues/18429 how to reproduce.

bug: prevent go routine leakage due to existing DeferCheck

---

.changelog/18464.txt
ui/packages/consul-ui/app/serializers/application.js
ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
ui/packages/consul-ui/tests/unit/serializers/application-test.js

Manual backport of https://github.com/hashicorp/consul/pull/18464

fix for , non presence of consul-version meta (#18464)

---

.github/scripts/filter_changed_files_go_test.sh
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

Stop running go-test and test-integrations workflow if the changes in PR only occurs in docs, ui, website, grafana 
- Add a script to check changeset in branch history
- If change includes docs + `*.go` files, trigger test workflows
- If changes ONLY include docs/, do not trigger test workflows
**Testcases**
1. Validate that the following jobs are skipped when changeset only occurs in `docs` file
See current CI result
2. Validate that the following jobs are are NOT skipped when changeset occurs in `docs` and `*.go` files

NET-5382 & PLAT-1159: Do not trigger workflow if only doc files are in commit history

---

agent/grpc-external/services/resource/write_status.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go

CE version of approved ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6732

resource: Make resource writestatus tenancy aware

---

.github/scripts/notify_slack.sh
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations.yml

Send slack message to channel when nightly integration tests fail

CI: send slack notification on failed nightly job

---

.github/workflows/build-distros.yml
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

- This adds concurrency to the bigger workflows that we run.
- These should only work on 'push' style actions (ie pushing a commit or creating a PR).
- Merges to main as pushes are ok as they are done as part of the merge process and not developers pushing commits over and over.
- I've skipped all the smaller workflows because those will need to be cleaned up/merged together soon(tm)
- It will limit 1 workflow run per branch at a time and will cancel current runs of other workflows.
- try doing 2 commits at the same time and the 1st set of workflows should be cancelled.
You can see in the `go-tests` below how they were cancelled because I pushed a 2nd commit.
https://github.com/hashicorp/consul/actions/runs/5954040559

Set concurrency for workflows

---

.changelog/18584.txt
agent/hcp/deps.go
agent/hcp/telemetry/otel_exporter.go
agent/hcp/telemetry/otel_exporter_test.go
agent/hcp/telemetry/otel_sink.go

This is a manually created backport of the change to reduce the frequency of OTEL metric exporting from Consul to HCP made in the other PR over in https://github.com/hashicorp/consul/pull/18596
> @jjti
This person should manually cherry-pick the original PR into a new backport PR,
and close this one when the manual backport PR is merged in.
failed auto backport: https://github.com/hashicorp/consul/pull/18596

Reduce the frequency of metric exports to minutely (#18584)

---

agent/consul/client_test.go
agent/consul/server.go
internal/catalog/internal/types/service.go

As we will continue to use current tenancy implementation with the new resources API, we need to make current tenancy implementation aware of the resources under it and manage it.
In this PR we add the deletion of the resources within a namespace when the namespace is deleted. As there is no way to list all the resources under the same namespace (of any type) we iterate over all the registered types with a namespace scope and delete them except for Type: TypeV1Tombstone as those need to be present after the resource deletion and will be deleted later on.
The code in this PR is only needed as an intermediate step until we design v2 tenancy and come up with a way of deleting resources under v2 tenancy.

delete all v2 resources type when deleting a namespace (CE)

---

agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/list_by_owner_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/write_status.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go

NET- 5468: CE version of approved ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6763

resource: Allow nil tenancy

---

.github/scripts/get_runner_classes.sh
.github/scripts/get_runner_classes_windows.sh
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations.yml
.github/workflows/test-integrations-windows.yml
.github/workflows/test-integrations.yml

- Reducing most test runs to use smaller VMs.
- Looking at the speed of things this doesn't add to much time to the tests (we are waiting on other tests to finish anyway)
- I left build-distros on xl machines as those should stay fast.
- Reduced the vm size for enterprise to a similarly spec'd machine that is much cheaper per minute.
- Removed peering topology test as it is flakey and is moving to nightly.
Ran the tests over and over.

PLAT-1192 - Run CI on smaller instances

---

website/content/docs/enterprise/admin-partitions.mdx

Current documentation is incorrect/misleading. Agents can return DNS responses with results from other partitions.

docs: admin partition and DNS clarification

---

internal/catalog/internal/types/validators.go
internal/catalog/internal/types/validators_test.go

We explicitly enumerate the allowed protocols in validation, so this change is necessary to use the new enum value.
Also add tests for enum validators to ensure they stay aligned to protos unless we explicitly want them to diverge.
Follow-up to https://github.com/hashicorp/consul/pull/18612
When I went to test integration on the k8s side, I found out the server was rejecting any request with the newly added value.
There's a few other protos that are validated as part of larger structs; I opted not to rework tests for them in this change.
~I looked into the possibility of making this validation more generic, but I'm not sure it'll be trivial if we also want to keep the rich error feedback that includes the string name of the rejected enum value.~ _edit, see …

fix: make UNSPECIFIED protocol pass validation

---

.changelog/18636.txt
agent/agent.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/health_blocking.go
agent/proxycfg-glue/health_blocking_test.go

Fixes an issue that was introduced in #17775. This issue happens because a long-lived pointer to the state store is held, which is unsafe to do. Snapshot restorations will swap out this state store, meaning that the server's proxycfg endpoint-health watches would break.
Any mesh services utilizing a consul-dataplane workflow would experience this problem, which is primarily consul-k8s deployments. This issue will typically result in Envoy proxies displaying zero upstream endpoints to contact.

[NET-4958] Fix issue where envoy endpoints would fail to populate after snapshot restore

---

agent/proxycfg-glue/health_blocking.go
agent/proxycfg/upstreams.go
agent/xds/endpoints.go

Add extra trace / debug logging statements to assist with future debugging efforts

Add extra logging for mesh health endpoints.

---

ui/packages/consul-ui/app/abilities/policy.js
ui/packages/consul-ui/app/components/consul/policy/list/index.hbs
ui/packages/consul-ui/app/helpers/policy/typeof.js
ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
ui/packages/consul-ui/mock-api/v1/acl/policies
ui/packages/consul-ui/mock-api/v1/acl/policy/_
ui/packages/consul-ui/tests/acceptance/dc/acls/policies/view-read-only.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/acls/policies/view-read-only-steps.js
ui/packages/consul-ui/tests/integration/helpers/policy/typeof-test.js

Update global-read-only to non editable
1. set up CONSUL_ACLS_ENABLE to 1 in session storage
2. set CONSUL_POLICY_COUNT = 10
3. go to Policies
4. log in with any securId
5. check list of items to see **global-read-only** policy
6. go to the policy details and check that form is non-editable
[JIRA](https://hashicorp.atlassian.net/browse/CC-5792)
[Figma](https://www.figma.com/file/oMJ1VqcRzb2EP1mqfaohDz/View-Builtin-Token?type=design&node-id=916-8806&mode=design&t=ZRNWWdS4Bb0fhced-0)

feat: Change global-read-only policy to non editable

---

ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs

[figma](https://www.figma.com/file/oMJ1VqcRzb2EP1mqfaohDz/View-Builtin-Token?type=design&node-id=916-10427&mode=design&t=pwg7CT5HbY6jAfBx-0)

feat: copy edits for built-in policy alert

---

command/snapshot/save/snapshot_save_test.go

Small fix for this test. This fails in ENT because the version has `1.17.0+ent`, but the test agent version does not have the `+ent` suffix.
The original PR is #18625

test: fix snapshot save w/ append test for ENT

---

command/snapshot/save/snapshot_save_test.go

Small fix for this test. This fails in ENT because the version has `1.17.0+ent`, but the test agent version does not have the `+ent` suffix.
The original PR is #18625

Backport fix test snapshot save - 1.14.x

---

command/snapshot/save/snapshot_save_test.go

Small fix for this test. This fails in ENT because the version has `1.17.0+ent`, but the test agent version does not have the `+ent` suffix.
The original PR is #18625

Backport 1.16 fix test snapshot save 

---

command/snapshot/save/snapshot_save_test.go

Small fix for this test. This fails in ENT because the version has `1.17.0+ent`, but the test agent version does not have the `+ent` suffix.
The original PR is #18625 and https://github.com/hashicorp/consul/pull/18656

Backport 1.15 fix test snapshot save

---

.github/scripts/get_runner_classes.sh
.github/workflows/frontend.yml
.github/workflows/go-tests.yml
.github/workflows/nightly-test-integrations.yml
.github/workflows/test-integrations.yml

I am seeing this very weird thing where backports are using the github workflows on the release branches themselves. I cannot explain it...

Release 1.16.x reduce runner sizes and concurrency

---

docs/resources/guide.md

This PR update the resource dev guide to reflect the changes introduced by supporting tenancy v1 when using v2 resource API
Doc change, not test needed

update guide to reflect tenancy and scope

---

.changelog/18667.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_replication_test.go
agent/consul/acl_replication_types.go
agent/consul/state/acl.go
agent/consul/state/acl_ce.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/structs/acl.go
api/acl.go
api/acl_test.go
website/content/api-docs/acl/tokens.mdx

The consul-k8s endpoints controller has a [workflow where it fetches all tokens](https://github.com/hashicorp/consul-k8s/blob/v1.2.1/control-plane/connect-inject/controllers/endpoints/endpoints_controller.go#L968-L970)
This is not performant for large clusters, where there may be a sizable number of tokens. This PR attempts to alleviate that problem and introduces a new way to query by the token's service name.
Added in extra unit tests.
Performed manual tests:
- Ensured that calling `/v1/acl/tokens?servicename=mysvc` does not throw an error on prior versions of Consul 1.16 and simply returns the full list of tokens. This means that updating consul-k8s to use the new query param will still be backwards compatible (because it can still loop and filter on the full list of tokens in-memory, …

Add support for querying tokens by service name.

---

.changelog/18667.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_replication_test.go
agent/consul/acl_replication_types.go
agent/consul/state/acl.go
agent/consul/state/acl_ce.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/structs/acl.go
api/acl.go
api/acl_test.go
website/content/api-docs/acl/tokens.mdx

This is a manual backport of: https://github.com/hashicorp/consul/pull/18667

[NET-5399] Add support for querying tokens by service name.

---

internal/mesh/internal/controllers/sidecarproxy/builder/builder_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-multiple-workload-addresses-with-specific-ports.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-multiple-workload-addresses-without-ports.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-single-destination-ip-port-bind-address.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-single-destination-unix-socket-bind-address.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/l4-single-workload-address-without-ports.golden

In various places (like sidecarproxy/builder) we use `protojson` to marshal golden data for comparison. Unfortunately [by design](https://github.com/golang/protobuf/issues/1269) this introduces random whitespace in generated output so using `git diff` to peek at proposed output changes in your tests after running the test with `-update` will show more lines changed than expected which is confusing.
This patch updates only *one* of these call sites to use deterministic output by a trick:
1. protojson marshal (nondeterminstic)
2. json unmarshal
3. json marshal (determinstic)
The whitespace will be reasonable and the fields will be sorted alphabetically rather than by protobuf field id.
If this seems helpful we should likely update the `agent/xds` package tests too, but that will need to be …

test: update sidecarproxy/builder golden tests to use determinstic golden data

---

.changelog/_6870.txt

Added changelog for jwt features

---

agent/consul/server.go

In a previous PR (https://github.com/hashicorp/consul/pull/18504), we moved resource client instantiation to be before setting up the external gRPC server. However, the secure client relies on the resource server not being nil which is done by the gRPC server setup. This PR moves the setup of the secure client to be after the gRPC server setup.

Instantiate secure resource service client after the grpc server

---

.changelog/18724.txt
agent/agent.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_ce_test.go
agent/consul/usagemetrics/usagemetrics_test.go

Manual backport (automated backport failed) for https://github.com/hashicorp/consul/pull/18724

[manual backport] 1.15.x - emit consul version periodically

---

api/resource.go
command/registry.go
command/resource/apply/apply.go
command/resource/helper.go
command/resource/list/list.go
command/resource/list/list_test.go
command/resource/resource.go
command/resource/testdata/invalid_type.hcl

- Add support for the `list` command to read all resources by type.
- Small refactor to apply command (second commit) since I added the `helpers` file for code reusability.
Note: I am pointing this to the apply command branch for easy review.
Usage:
- `consul resource list -f=<file-path>`
- `consul resource list demo.v2.artist -namespace=default -partition=namespace -peer=local`
- Add unit tests for validations and correctness
- Manually tested the command in both server and client mode

Net-4292/list command

---

internal/resource/http/http.go
internal/resource/http/http_test.go

This PR fixes the following problem:
When the request body does not comply with the resource schema we still end up calling the gRPC endpoint and in some cases incorrectly creating a resource in the backend with partial data while returning the `400` status code.
- Add unit tests that also asserts the error  message not just the status code
[Ticket](https://hashicorp.atlassian.net/browse/NET-5561)

fix: write endpoint errors out gracefully

---

.changelog/18742.txt
.github/workflows/build.yml
build-support/docker/Build-Go.dockerfile

This resolves several CVEs:
* CVE-2023-39320: cmd/go: go.mod toolchain directive allows arbitrary execution
* CVE-2023-39318: html/template: improper handling of HTML-like comments within script contexts
* CVE-2023-39319: html/template: improper handling of special tags within script contexts
* CVE-2023-39321 and CVE-2023-39322: crypto/tls: panic when processing post-handshake message on QUIC connections
Resolves CVEs and brings us up to the latest version of Go.
Tests should continue to pass.
* https://groups.google.com/g/golang-announce/c/Fm51GRLNRvM

[NET-5574] Update Go version to 1.20.8

---

agent/envoyextensions/builtin/otel-access-logging/structs.go
agent/xds/delta_envoy_extender_ce_test.go
agent/xds/testdata/builtin_extension/clusters/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/endpoints/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/listeners/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/routes/otel-access-logging-http.latest.golden

This PR add an Envoy golden test for the OpenTelemetry access logging Envoy extension (`builtin/otel-access-logging`)
```
go test ./agent/xds
```

Add Envoy golden test for OTEL access logging extension

---

.github/workflows/test-integrations.yml

Test Nomad's latest supported releases : v1.6.1, v1.5.8, v1.4.12

Test: NET-5592 - update Nomad integration testing

---

internal/resource/tenancy.go
internal/resource/tenancy_test.go

When one resource contains an inner field that is of type `*pbresource.Reference` we want the Tenancy to be reasonably defaulted by the following rules:
1. The final values will be limited by the scope of the referenced type.
2. Values will be inferred from the parent's tenancy, and if that is insufficient then using the default tenancy for the type's scope.
3. Namespace will only be used from a parent if the reference and the parent share a partition, otherwise the default namespace will be used.
Until we tackle peering, this hard codes an assumption of peer name being `local`. The logic for defaulting may need adjustment when that is addressed.
A followup PR will address adding this to the appropriate types that contain references.

resource: add helper to normalize inner Reference tenancy during mutate

---

.github/scripts/filter_changed_files_go_test.sh

There's currently a bug that causes CI to be skipped on all non-PR changes. Until that's fixed and we can be certain the check will fail CI or default to running tests in the case of errors, disabling this check.
Original PR: https://github.com/hashicorp/consul/pull/18528

Disable docs change CI skip detection

---

.changelog/18773.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

Fixes an issue where the [Vault CA provider](https://developer.hashicorp.com/consul/docs/connect/ca/vault) did not clean up previous CA certificate "[issuers](https://developer.hashicorp.com/vault/api-docs/secret/pki#notice-about-new-multi-issuer-functionality)" when generating new leaf-signing certs (previously referred to as intermediate certs).
This meant that every leadership change, 1) the leader would request a new leaf-signing cert from Vault; 2) Vault would generate a new issuer; 3) Consul would set the issuer as default for future operations
If leadership change occurs frequently, the number of issuers on the Vault mount may grow and degrade the PKI performance.
This PR adds a step 4) Consul deletes the previous default issuer

Vault CA provider clean up previous default issuers

---

agent/consul/fsm/snapshot.go
agent/consul/fsm/snapshot_ce.go

The renaming of files from oss -> ce caused incorrect snapshots to be created due to ce writes now happening prior to ent writes. When this happens various entities will attempt to be restored from the snapshot prior to a partition existing and will cause a panic to occur.

Fix snapshot creation issue.

---

internal/catalog/internal/controllers/endpoints/controller.go
internal/catalog/internal/controllers/endpoints/controller_test.go

On Kubernetes, we don't know the workload port protocol (only service ports can have `appProtocol` provided), and for that case we need to inherit the protocol from the service if workload doesn't have one.

catalog: service endpoints inherits protocol from service when workload doesn't have one

---

internal/protohcl/primitives.go
internal/resourcehcl/any.go
internal/resourcehcl/naming.go
internal/resourcehcl/testdata/fuzz/FuzzUnmarshall/0e4b8ec300611dbc
internal/resourcehcl/testdata/fuzz/FuzzUnmarshall/c800420b7494c6d1
internal/resourcehcl/testdata/fuzz/FuzzUnmarshall/eaba8205942c3f31
internal/resourcehcl/unmarshal_test.go

This PR add a simple fuzz test to `resourcehcl` package. Using that test 3 panic conditions were uncovered, the fix for those and the use cases of those are added to the corpus.
Fuzz test added and fixes are covered by that test that should run in CI from now on.

add fuzz tests to resourcehcl package and fix some panics 

---

agent/agent_test.go

TestAgent_HTTPMaxHeaderBytes always has ports hanging in CI. Trying to close resources on an at-best effort

Clean up resources in test

---

website/content/docs/api-gateway/configuration/gatewayclassconfig.mdx

https://github.com/hashicorp/consul/pull/18776 Accidentally introduced an error into the docs site. This fixes it. This is already updated in the backport PR.

Removes errant word in docs that was breaking the build

---

.changelog/18813.txt
agent/structs/acl.go
command/acl/token/testdata/FormatTokenExpanded/ce/complex.pretty-meta.golden
command/acl/token/testdata/FormatTokenExpanded/ce/complex.pretty.golden

- ACL templated policies accomplish the same thing as node/service identities when it comes to generating a synthetic policy. The long term is for ACL templated policies to be the source of generating synthetic policies to simplify getting the right acl token
- We also rely on existing tests to catch any issues (as a lot of tests rely on synthetic policies generated by node/service identities), ideally there shouldn't a test update as all tests relying on service/node identities synthetic policies should just seamlessly pass
- step 1: create token with a service identity  
```
consul acl token create -service-identity "web"
AccessorID:       916a549b-148d-9026-7e08-5375405ba51f
SecretID:         5669dbcb-9f1e-c354-25d0-435915cb4858
Partition:        default
Namespace:        default …
```

[NET-5329] use acl templated policy under the hood for node/service identities

---

.changelog/18816.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
api/acl.go
command/acl/templatedpolicy/formatter.go
command/acl/templatedpolicy/formatter_ce_test.go
command/acl/templatedpolicy/formatter_test.go
command/acl/templatedpolicy/list/templated_policy_list.go
command/acl/templatedpolicy/list/templated_policy_list_test.go
command/acl/templatedpolicy/preview/templated_policy_preview.go
command/acl/templatedpolicy/preview/templated_policy_preview_test.go
command/acl/templatedpolicy/read/templated_policy_read.go
command/acl/templatedpolicy/read/templated_policy_read_test.go
command/acl/templatedpolicy/templated_policy.go
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicyList/ce/list.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicyList/ce/list.pretty.golden
command/registry.go

- Added three commands here: list, preview and read templated-policies. 
- Moved `ACLTemplatedPolicyResponse` to api package to avoid duplicating it
- command
```
consul acl templated-policy 
Usage: consul acl templated-policy <subcommand> [options] [args]
This command has subcommands for managing Consul ACL templated policies.
Here are some simple examples, and more detailed examples are available
in the subcommands or the documentation.
List all templated policies:
$ consul acl templated-policy list
Preview the policy rendered by the ACL templated policy:
$ consul acl templated-policy preview -name "builtin/service" -var "name:api"
Read a templated policy with name:
$ consul acl templated-policy read -name "builtin/service"
For more examples, ask for subcommand help or view the …
```

[NET-5334] Added CLI commands for templated policies

---

command/acl/templatedpolicy/formatter.go
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty.golden

- The tab really ruins the output, fixed it by using spaces and it looks much better
```
consul acl templated-policy read -name "builtin/dns"
```

fix templated policy cli output

---

agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/write_status.go
agent/grpc-external/services/resource/write_test.go
internal/resource/tenancy.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/6981

resource: default peername to "local" for now

---

internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
internal/mesh/internal/mappers/sidecarproxymapper/service_mapper.go

Workload ports are allowed to have no protocol, and we need to default to tcp protocol in this case for now.
Note this PR has not test because we need to re-work how port protocols are handled properly for a case when they need to be inherited. This is just a quick fix for now as we don't fully support other protocols quite yet.

Default to tcp protocol when workload protocol is unspecified

---

agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
agent/structs/acltemplatedpolicy/schemas/node.json
agent/structs/acltemplatedpolicy/schemas/service.json
command/acl/templatedpolicy/formatter_test.go
command/acl/templatedpolicy/read/templated_policy_read_test.go
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicyList/ce/list.json.golden

- We will have a total of 12 templated policies, to make it easier we thought each template schema could reside in its own json file and use go embedded strings 
- Splitting the node and service schema so it doesn't get confusing in the future 
- The test cover all templated policy stuff to CI running fine should enough to know if we broke off anything. 
- Manually you can try reading an acl templated policy with meta: `consul acl templated-policy read -name "builtin/node" -meta`

Use embedded strings for templated policies

---

command/operator/usage/instances/usage_instances.go

Tests with dc1 and dc2 were expecting them to be printed in order. Maps are not iterated deterministically so we want to sort the datacenters before iterating.

Fix nondeterministic test

---

internal/mesh/internal/controllers/routes/generate.go
internal/mesh/internal/controllers/routes/generate_test.go

If a service exposes a "mesh" port it can **have** upstreams, but if it exposes no other ports it cannot **be** an upstream, so it should not have a `ComputedRoutes` written.
NET-5650

mesh: prevent writing a ComputedRoutes with no ported configs

---

agent/metrics_test.go

This test suite flakes VERY often and we cannot debug why because the handlers may be returning without go errors (instead choosing to write to ResponseWriter instead).
Call the handler differently (through Consul's middleware) and assert for status code. This won't fix the flakes but it will help debug why the tests are failing.

Adjust metrics test

---

.github/scripts/get_runner_classes_windows.sh
.github/workflows/test-integrations-windows.yml
build-support/windows/build-consul-dev-image.sh

Fixes for integration test for Consul Enterprise for windows. 
CI
https://github.com/hashicorp/consul-enterprise/actions/runs/6214229144/job/16866026452
https://github.com/hashicorp/consul/actions/runs/6214462815/job/16866420103

Fixes for integration tests windows for ENT

---

command/resource/apply/apply.go
command/resource/apply/apply_test.go
command/resource/delete/delete.go
command/resource/delete/delete_test.go
command/resource/list/list.go
command/resource/list/list_test.go
command/resource/read/read.go
command/resource/read/read_test.go

- Add missing test cases and patch for variations of resource type format
- Consistent language/messaging across CLI commands
- Rely on the `flag.args` to confirm that required arguments are passed correctly
Feedback that prompted this [PR](https://hashicorp.slack.com/archives/C0253EQ5B40/p1694462086447919)

fix: provide meaningful error messages and add test

---

agent/consul/server.go
agent/consul/tenancy_bridge.go
agent/consul/tenancy_bridge_v2_ce.go
agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/testing/testing.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_status.go
agent/grpc-external/services/resource/write_test.go
internal/resource/tenancy.go
internal/resource/tenancy_bridge_ce.go

This PR is the initial introduction of a second implementation of the tenancy bridge that would allow us to use a v2 resources backed tenancy.
This also rename `V1TenancyBridge` to `TenancyBridge` as we would be using the bridge for both implementations.
No tests are added as the introduced behaviour is just to return an `unimplemented` error for now.
All the tests using V1TenancyBridge should work as expected, notice that those tests are not yet part of the code and WIP.

add v2 tenancy bridge Flag and v2 Tenancy Bridge initial implementation

---

website/content/docs/agent/config/config-files.mdx

Change 'If not port' to 'If no port'.
Resolves #18553

docs: Fix typo in description for server_addresses

---

grafana/consul-k8s-control-plane-monitoring.json

**Update the consul-k8s control plan dashboard**:
Display the number of connected consul-dataplanes in the cluster such that users get some idea of the workloads running in the cluster.

grafana: display connected consul-dataplanes

---

internal/catalog/exports.go
internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/failover_policy_test.go
internal/catalog/internal/types/validators.go

`FailoverPolicy` resources contain inner `Reference` fields. We want to ensure that components of those reference `Tenancy` fields left unspecified are defaulted using the tenancy of the enclosing FailoverPolicy resource.
As the underlying helper being used to do the normalization calls the function modified in #18822, it also means that the `PeerName` field will be set to `"local"` for now automatically to avoid `"local" != ""` issues downstream.
NET-5641

catalog: normalize/default/validate tenancy components of FailoverPolicy internal References

---

.changelog/18831.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

While trying to debug a customer issue, I noticed that when:
1. A user specifies an ingress gateway with a target of `"*"`
3. They boot up the ingress gateway and a service in the target namespace
4. They've registered the target and its sidecar proxy individually
5. They then deregister the target _followed_ by the corresponding sidecar
6. The gateway still attempts to route to the service
This happens because of a bug in the store that was causing wildcard-targeted gateway services to be pruned from `tableGatewayServices` only when they don't have existing sidecar proxies. In the above case, when the sidecar is deregistered second, the cleanup routine never triggers for the main service (instead a routine runs that attempts to prune the sidecar service name from `tableGatewayServices` …

Fix gateway services cleanup where proxy deregistration happens after service deregistration

---

.changelog/18831.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

This PR is a backport of #18831 to release/1.15.x
---
While trying to debug a customer issue, I noticed that when:
1. A user specifies an ingress gateway with a target of `"*"`
3. They boot up the ingress gateway and a service in the target namespace
4. They've registered the target and its sidecar proxy individually
5. They then deregister the target _followed_ by the corresponding sidecar
6. The gateway still attempts to route to the service
This happens because of a bug in the store that was causing wildcard-targeted gateway services to be pruned from `tableGatewayServices` only when they don't have existing sidecar proxies. In the above case, when the sidecar is deregistered second, the cleanup routine never triggers for the …

Backport of Fix gateway services cleanup where proxy deregistration happens after service deregistration into release/1.15.x

---

.changelog/18831.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

This PR is a backport of #18831 to release/1.16.x
---
While trying to debug a customer issue, I noticed that when:
1. A user specifies an ingress gateway with a target of `"*"`
3. They boot up the ingress gateway and a service in the target namespace
4. They've registered the target and its sidecar proxy individually
5. They then deregister the target _followed_ by the corresponding sidecar
6. The gateway still attempts to route to the service
This happens because of a bug in the store that was causing wildcard-targeted gateway services to be pruned from `tableGatewayServices` only when they don't have existing sidecar proxies. In the above case, when the sidecar is deregistered second, the cleanup routine never triggers for the …

Backport of Fix gateway services cleanup where proxy deregistration happens after service deregistration into release/1.16.x

---

.changelog/18831.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

This PR is a backport of #18831 to release/1.14.x
---
While trying to debug a customer issue, I noticed that when:
1. A user specifies an ingress gateway with a target of `"*"`
3. They boot up the ingress gateway and a service in the target namespace
4. They've registered the target and its sidecar proxy individually
5. They then deregister the target _followed_ by the corresponding sidecar
6. The gateway still attempts to route to the service
This happens because of a bug in the store that was causing wildcard-targeted gateway services to be pruned from `tableGatewayServices` only when they don't have existing sidecar proxies. In the above case, when the sidecar is deregistered second, the cleanup routine never triggers for the …

Backport of Fix gateway services cleanup where proxy deregistration happens after service deregistration into release/1.14.x

---

.copywrite.hcl
agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
agent/structs/acl_templated_policy_ce.go
agent/structs/acltemplatedpolicy/policies/ce/dns.hcl
agent/structs/acltemplatedpolicy/policies/ce/node.hcl
agent/structs/acltemplatedpolicy/policies/ce/service.hcl
command/acl/templatedpolicy/formatter_test.go
command/acl/templatedpolicy/list/templated_policy_list_test.go

- keeping the templated policies in the `.go` was fine initially but we will be adding another 9 templates so removing them to a separate file for each template sounds like a good idea 
- The CI tests should catch any unintended changes.
- You can also manually test with:
```
consul acl templated-policy read -name "builtin/service" -meta
```

Move ACL templated policies to hcl files

---

internal/mesh/internal/controllers/xds/controller.go

mesh: update xds controller to synthesize empty endpoints when no endpoints ref is found

---

internal/mesh/internal/mappers/sidecarproxymapper/destinations_mapper_test.go
internal/mesh/internal/types/grpc_route.go
internal/mesh/internal/types/grpc_route_test.go
internal/mesh/internal/types/http_route.go
internal/mesh/internal/types/http_route_test.go
internal/mesh/internal/types/tcp_route.go
internal/mesh/internal/types/tcp_route_test.go
internal/mesh/internal/types/upstreams.go
internal/mesh/internal/types/upstreams_test.go
internal/mesh/internal/types/xroute.go

`HTTPRoute`, `GRPCRoute`, `TCPRoute`, and `Upstreams` resources contain inner `Reference` fields. We want to ensure that components of those reference `Tenancy` fields left unspecified are defaulted using the tenancy of the enclosing resource.
As the underlying helper being used to do the normalization calls the function modified in #18822, it also means that the `PeerName` field will be set to `"local"` for now automatically to avoid `"local" != ""` issues downstream.
NET-5641

mesh: normalize/default/validate tenancy components of mesh internal References

---

agent/agent.go
agent/consul/acl.go
agent/consul/server.go
internal/auth/internal/types/computed_traffic_permissions.go
internal/mesh/internal/controllers/register.go
internal/mesh/internal/controllers/sidecarproxy/builder/builder.go
internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder_multiport_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/local_app_multiport_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l4-multiple-workload-addresses-with-specific-ports.golden
internal/mesh/internal/controllers/sidecarproxy/controller.go
internal/mesh/internal/controllers/sidecarproxy/controller_test.go
internal/resource/resourcetest/decode.go

This PR wires up default traffic permissions in v2.
* Unit tests
* Manual testing

Honor Default Traffic Permissions in V2

---

website/content/docs/connect/config-entries/control-plane-request-limit.mdx
website/content/docs/connect/config-entries/jwt-provider.mdx
website/content/docs/connect/proxies/envoy-extensions/configuration/property-override.mdx
website/content/docs/k8s/connect/transparent-proxy/enable-transparent-proxy.mdx
website/content/docs/nia/cli/task.mdx
website/content/docs/nia/configuration.mdx

This commit fixes syntax errors in HCL, JSON, and YAML example configurations. In some cases, it replaces the code example with the proper format for the code block.

docs: Fix HCL, JSON, and YAML syntax errors

---

website/content/docs/services/discovery/dns-static-lookups.mdx

HCL and JSON configuration examples were being displayed in the same code block. This commit separates the configurations to properly display them as independent configuration examples.

Fix code block examples on dns-static-lookups.mdx

---

api/operator_audit.go

- Api feature parity for 1.16.x following [example of operator-area ](https://github.com/hashicorp/consul/blob/main/api/operator_area.go)

Add operator audit endpoint changes

---

website/content/docs/connect/gateways/mesh-gateway/index.mdx
website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-partitions.mdx
website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-wan-datacenters.mdx
website/content/docs/services/usage/define-services.mdx

Remove YAML service registration examples and replace them with JSON. This is because YAML is not a supported configuration format for the Consul's agent configuration, nor is it supported by the HTTP API.
This commit replaces the YAML examples with JSON and adds additional JSON examples where they were missing.

docs: Remove YAML service registration examples

---

test/integration/consul-container/test/envoy_extensions/otel_access_logging_test.go
test/integration/consul-container/test/envoy_extensions/testdata/otel/config.yaml

This PR adds an integration test for the OpenTelemetry access logging Envoy extension (`builtin/otel-access-logging`).
Use the following commands to run the new integration test locally.
```shell
cd consul
make test-compat-integ-setup
cd test/integration/consul-container/test/envoy_extensions
go test -v -run '^TestOTELAccessLogging$'
```

Add otel-access-logging Envoy extension integration test

---

website/content/docs/k8s/annotations-and-labels.mdx
website/content/docs/k8s/connect/index.mdx

Add note about service upstream env var dot broken

---

.changelog/18573.txt
agent/xds/clusters.go
agent/xds/testdata/clusters/expose-paths-grpc-new-cluster-http1.latest.golden
agent/xds/testdata/clusters/expose-paths-new-cluster-http2.latest.golden
agent/xdsv2/cluster_resources.go

Configure Envoy to use the same HTTP protocol version used by the downstream caller when forwarding requests to the local application.
This allows upstream applications that support both HTTP/1.1 and HTTP/2 to receive requests using either protocol.
For example, this is beneficial when the application primarily communicates using HTTP/2, but also needs to support HTTP/1.1 to correctly handle requests from Kubernetes readiness/liveness probes.

xds: Use downstream protocol when connecting to local app

---

website/content/api-docs/acl/binding-rules.mdx
website/content/docs/security/acl/auth-methods/aws-iam.mdx
website/content/docs/security/acl/auth-methods/jwt.mdx
website/content/docs/security/acl/auth-methods/kubernetes.mdx
website/content/docs/security/acl/auth-methods/oidc.mdx
website/content/partials/jwt_claim_mapping_details.mdx

This commit modifies the example payloads for various auth methods to remove 'other fields' and instead use complete example payloads.
This helps readers clearly understand how the payloads should be constructed for the `/v1/acl/auth-method` API endpoint.

docs: Add complete auth method payloads

---

agent/config/builder.go
agent/config/builder_test.go

Prevents configuration that enabled the resource-apis experiment and includes cloud credentials for linking with HCP Consul.

agent/config: prevent startup if resource-apis experiment and cloud are enabled

---

.github/scripts/filter_changed_files_go_test.sh
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

**PROBLEM**
We found a bug where on pull request merge, the following error was returned by the `filter_changed_files_go_test.sh ` 
```
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
See example [here](https://github.com/hashicorp/consul/actions/runs/6172863474/job/16753960303#step:3:8) 
**SOLUTION**
Update the `conditional-skip` job with a step to conditional check the github event, 
- if event is `pull_request merged`, set GitHub branch value to `github.ref_name`
- for `pull_request` event, set GitHub branch value to `github.head_ref`
Update the `filter_changed_files_go_test.sh` script to fail on script error and set the default behaviour to …

Update base ref property name

---

.github/scripts/filter_changed_files_go_test.sh

Fix bug in `.github/scripts/filter_changed_files_go_test.sh` script. Update the script with the correct code for for loop. It currently only checks first file, iterate step to check all changed files. See original [PR](https://github.com/hashicorp/consul/pull/18851)

Fix for loop in filter_changed_files_go_test script

---

internal/mesh/internal/controllers/xds/controller.go
internal/mesh/internal/controllers/xds/controller_test.go

This improves the performance of managing leaf cert watches for xds v2 by swapping it from an `N*M` operation to an `N+M` operation.

[NET-5589] Optimize leaf watch diff on xds controller.

---

website/content/docs/k8s/helm.mdx

[1.15.x] Update helm docs

---

.github/scripts/filter_changed_files_go_test.sh
.github/workflows/go-tests.yml
.github/workflows/test-integrations.yml

**PROBLEM**
Actions was not correctly reading the result of script to not run CI, it continuously ran CI when changes were only to docs file. See example [here](https://github.com/hashicorp/consul/actions/runs/6265236668/job/17013624352)
**SOLUTION**
Push the result of script to GITHUB_OUTPUT which can be read easily by Github Actions to execute workflows conditionally. 
[CI](https://github.com/hashicorp/consul/actions/runs/6265534204/job/17014579594) runs all workflows where non doc files are included in changeset
[CI](https://github.com/hashicorp/consul/actions/runs/6265490477/job/17014449286) skips test workflows when only doc files are  in changeset

when skip-ci is true do not trigger integration and go tests

---

website/content/api-docs/catalog.mdx
website/content/docs/architecture/coordinates.mdx
website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/config-entries/terminating-gateway.mdx
website/content/docs/connect/configuration.mdx
website/content/docs/connect/proxies/built-in.mdx
website/content/docs/connect/proxies/envoy.mdx
website/content/docs/connect/registration/service-registration.mdx
website/content/docs/dynamic-app-config/watches.mdx
website/content/docs/ecs/manual/install.mdx
website/content/docs/lambda/registration/automate.mdx
website/content/docs/nia/api/status.mdx
website/content/docs/security/acl/acl-federated-datacenters.mdx
website/content/docs/security/acl/acl-rules.mdx
website/content/docs/security/acl/tokens/index.mdx
website/content/docs/services/configuration/services-configuration-reference.mdx
website/content/docs/services/usage/checks.mdx
website/content/docs/services/usage/define-services.mdx

backport of commit cc40e084bbddcbf43e90c9fda5b3271d7392e59e

Backport of docs: Fix invalid JSON into release/1.15.x

---

website/content/docs/connect/gateways/ingress-gateway/tls-external-service.mdx
website/content/docs/connect/gateways/mesh-gateway/index.mdx
website/content/docs/connect/intentions/create-manage-intentions.mdx
website/content/docs/k8s/l7-traffic/failover-tproxy.mdx
website/content/docs/k8s/l7-traffic/route-to-virtual-services.mdx
website/content/docs/services/discovery/dns-dynamic-lookups.mdx
website/content/docs/services/usage/define-services.mdx

Change various CodeBlockConfig objects to use the `filename` attribute instead of `heading` when the code block references a named file.

docs: Change heading to filename in CodeBlockConfig

---

agent/xds/clusters_test.go
agent/xds/proxystateconverter/clusters.go
agent/xdsv2/cluster_resources.go
agent/xdsv2/testdata/output/clusters/l4-single-implicit-destination-tproxy.golden

The panic threshold logic was just slightly off, where we do want to disable panic threshold on discovery chain clusters, peered clusters, and passthrough clusters. I just made sure we do that in those cases. This fixed acceptance tests for k8s here: https://github.com/hashicorp/consul-k8s/pull/2994 
Ran acceptance tests on k8s with health status syncing and ensured endpoints are not routed to: https://github.com/hashicorp/consul-k8s/pull/2994

fix disabling panic threshold logic

---

internal/tenancy/internal/types/types.go
internal/tenancy/internal/types/types_ce.go

See NET-5516 for acceptance criteria.
This is the CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7090
Just splits up `types.go` into a CE version so the ENT version can register both partition and namespace.

tenancy: split up tenancy `types.go` into CE version

---

agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/watch.go
docs/resources/guide.md
internal/mesh/internal/types/proxy_state_template.go
internal/resource/demo/demo.go
internal/resource/registry.go
internal/resource/registry_test.go

The `ACLs.Read` hook for a resource only allows for the identity of a resource to be passed in for use in authz consideration. For some resources we wish to allow for the current stored value to dictate how to enforce the ACLs (such as reading a list of applicable services from the payload and allowing `service:read` on any of them to control reading the enclosing resource).
This change update the interface to _usually_ accept a `*pbresource.ID`, but if the hook decides it needs more data it returns a sentinel error and the resource service knows to defer the authz check until after fetching the data from storage.
NET-5680

resource: allow for the ACLs.Read hook to request the entire data payload to perform the authz check

---

internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/failover_policy_test.go

FailoverPolicy resources are name-aligned with the Service they control. They also contain a list of possible failover destinations that are References to other Services.
The ACLs should be:
- list: (default)
- read: `service:<resource_name>:read`
- write: `service:<resource_name>:write` + `service:<destination_name>:read` (for any destination)
NET-5058

catalog: add ACL checks for FailoverPolicy resources

---

internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/failover_policy_test.go

The intersection of 2 PRs merged cleanly and ultimately did not work together. The github actions did not detect this sadly.

catalog: fix for new method argument

---

agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/subscription_manager_test.go

Occasionally a peerstream/subscription test would flake because a handler was called one extra time. This was due to an overly restrictive mock being too sensitive to multiple requests for the same data.
These tests did not need to care about the number of calls, so I've swapped it out with a dummy object instead in all of the relevant tests. Hopefully that removes the flake completely.

peerstream: fix flaky test related to autopilot integration

---

internal/mesh/internal/types/destination_policy.go
internal/mesh/internal/types/destination_policy_test.go

DestinationPolicy resources are name-aligned with the Service they control. 
The ACLs should be:
- list: (default)
- read: `service:<resource_name>:read`
- write: `service:<resource_name>:write`
NET-5059

mesh: add ACL checks for DestinationPolicy resources

---

internal/mesh/internal/types/grpc_route.go
internal/mesh/internal/types/grpc_route_test.go
internal/mesh/internal/types/http_route.go
internal/mesh/internal/types/http_route_test.go
internal/mesh/internal/types/tcp_route.go
internal/mesh/internal/types/tcp_route_test.go
internal/mesh/internal/types/xroute.go
internal/mesh/internal/types/xroute_test.go

`xRoute` resources are **not** name-aligned with the Services they control. They have a list of "parent ref" services that they alter traffic flow for, and they contain a list of "backend ref" services that they direct that traffic to.
The ACLs should be:
- list: (default)
- read:
- ALL `service:<parent_ref_service>:read`
- write:
- ALL `service:<parent_ref_service>:write`
- ALL `service:<backend_ref_service>:read`
NET-5060

mesh: add ACL checks for xRoute resources

---

internal/auth/internal/types/computed_traffic_permissions.go
internal/auth/internal/types/computed_traffic_permissions_test.go
internal/auth/internal/types/errors.go
internal/auth/internal/types/traffic_permissions.go
internal/auth/internal/types/traffic_permissions_test.go
internal/resource/tenancy.go
internal/resource/tenancy_test.go
proto-public/pbauth/v2beta1/traffic_permissions_addon.go

* Add validation that traffic permission sources can't have a wildcard namespace and explicit name.
* Default tenancy on traffic permission sources.
* Validate computed traffic permissions resources.
Unit tests

Traffic Permissions Validations

---

.changelog/18983.txt
api/agent.go
api/agent_test.go

Ongoing work to support Nomad Workload Identity for authenticating with Consul will mean that Nomad's service registration sync with Consul will want to use Consul tokens scoped to individual workloads for registering services and checks. The `ServiceRegisterOpts` type in the API doesn't have an option to pass the token in, which prevent us from sharing the same Consul connection for all workloads. Add a `Token` field to match the behavior of `ServiceDeregisterOpts`.
Related: https://github.com/hashicorp/nomad/issues/15618
Related: https://github.com/hashicorp/consul/pull/18943

api: add Token field to ServiceRegisterOpts

---

.changelog/18943.txt
api/agent.go
api/agent_test.go

Ongoing work to support Nomad Workload Identity for authenticating with Consul will mean that Nomad's service registration sync with Consul will want to use Consul tokens scoped to individual workloads for registering services and checks. The `CheckRegister` method in the API doesn't have an option to pass the token in, which prevent us from sharing the same Consul connection for all workloads. Add a `CheckRegisterOpts` to match the behavior of `CheckDeregisterOpts`.
Related: https://github.com/hashicorp/nomad/issues/15618
Related: https://github.com/hashicorp/consul/pull/18983

api: add `CheckRegisterOpts` method to Agent API

---

grafana/consul-k8s-control-plane-monitoring.json

- Fix a query metrics for ent version: in ent the metric name of consul server member is `consul_members_server`, but in OSS it is `members_server`.
- Add consul version to the dashboard

grafana: fix a query metrics from ent and add consul version

---

acl/resolver/danger.go

When using the no-auth acl resolver (the case for most controllers and the get-envoy-boostrap-params endpoint), ResolveTokenAndDefaultMeta method only returns an acl resolver. However, the resource service relies on the ent meta to be filled in to do the tenancy defaulting and inheriting it from the token when one is present.
So this change makes sure that the ent meta defaulting always happens in the ACL resolver.
This is needed when using consul-ent binary with various resource service endpoints that use the no-auth resolver. Without this change, we're seeing errors like:
```
code = NotFound desc = partition resource not found: 
```

acl: default tenancy with the no-auth ACL resolver

---

test/integration/consul-container/test/upgrade/catalog/catalog_test.go

We intentionally broke api compatibility here as we are not yet maintaining backwards compat for the v2 apis

Skip the catalog v2 upgrade test

---

website/content/docs/connect/config-entries/service-resolver.mdx

Datacenter inside Redirect map is of type string. As mentioned [here also](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-resolver#redirect-datacenter)
Fixes the doc.
https://developer.hashicorp.com/consul/docs/connect/config-entries/service-resolver#redirect-datacenter

Fix type of datacenter in Service Resolvers Config Entry

---

.github/workflows/build.yml

See link in inline comment.
```
$ cat blah.sh                                                                                                                                                                                                                                    #!/bin/bash
version="1.17.0-rc1"
echo "dev_tag=${version%.-}-dev"
$ ./blah.sh
dev_tag=1.17.0-rc1-dev
```

rc: Workaround for docker dev tag

---

agent/xds/rbac_test.go
agent/xds/testdata/rbac/v2-ignore-empty-permissions.golden
agent/xdsv2/rbac_resources.go
internal/auth/internal/controllers/trafficpermissions/controller_test.go
internal/auth/internal/types/traffic_permissions.go
internal/auth/internal/types/traffic_permissions_test.go

Backport https://github.com/hashicorp/consul/pull/19024
* Validate that each permission on traffic permissions resources has at least one source.
* Don't construct RBAC policies when there aren't any principals. This resulted in Envoy rejecting xDS updates with a validation error.
```
error=
| rpc error: code = Internal desc = Error adding/updating listener(s) public_listener: Proto constraint validation failed (RBACValidationError.Rules: embedded message failed validation | caused by RBACValidationError.Policies[consul-intentions-layer4-1]: embedded message failed validation | caused by PolicyValidationError.Principals: value must contain at least 1 item(s)): rules {
```

Backport tp validation fix

---

acl/MockAuthorizer.go
acl/acl_test.go
acl/authorizer.go
acl/chained_authorizer.go
acl/chained_authorizer_test.go
acl/policy_authorizer.go
acl/static_authorizer.go
internal/auth/internal/types/computed_traffic_permissions.go
internal/auth/internal/types/computed_traffic_permissions_test.go
internal/auth/internal/types/traffic_permissions.go
internal/auth/internal/types/traffic_permissions_test.go

Add ACL hooks for TrafficPermissions. This PR allows the same ACL policy behavior for workload identities in v2 as services have in v1 - intentions access can be separately specified in a nested manner.
I have not changed the "intentions" syntax within the policy syntax, however behind the scenes I have added a separate radix tree to track workloadIdentity <-> traffic permissions mappings, so that they do not collide with service <-> intentions mappings.

TrafficPermissions: add ACL hooks

---

website/content/docs/k8s/connect/cluster-peering/usage/establish-peering.mdx

When `meshgateway.mode=local`, service dials local mesh gateway.

docs: fix the description of meshgateway.mode=local in peering doc

---

command/resource/client/client.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/test/resource/http_api/acl_enabled_test.go
test/integration/consul-container/test/resource/http_api/client/client.go
test/integration/consul-container/test/resource/http_api/helper.go

- Add container tests for resource HTTP API endpoints when ACL is enabled
- Add Client agent smoke test to make sure client agent also work with ACLs as expected
Created new HTTP API Client for testing only that interacts with HTTP endpoints of the resource API.
To create this new API client the Container node interface was updated so that the correct HTTP address could be used.
- Tests added for Write, Read, List, and Delete HTTP endpoints called on the server with ACL-enabled cluster.

NET-5600/container-test-acl-enabled

---

sdk/testutil/io.go
sdk/testutil/server.go
sdk/testutil/testlog.go
testing/deployer/go.mod
testing/deployer/go.sum
testing/deployer/sprawl/acl.go
testing/deployer/sprawl/acl_rules.go
testing/deployer/sprawl/boot.go
testing/deployer/sprawl/catalog.go
testing/deployer/sprawl/configentries.go
testing/deployer/sprawl/consul.go
testing/deployer/sprawl/details.go
testing/deployer/sprawl/ent.go
testing/deployer/sprawl/internal/build/docker.go
testing/deployer/sprawl/internal/tfgen/digest.go
testing/deployer/sprawl/internal/tfgen/gen.go
testing/deployer/sprawl/internal/tfgen/io.go
testing/deployer/sprawl/peering.go
testing/deployer/sprawl/sprawl.go
testing/deployer/sprawl/sprawltest/sprawltest.go
testing/deployer/topology/compile.go

This just lifts any delta from enterprise and restores it in CE.

chore: fix ce/ent drift in sdk and testing/deployer submodules

---

agent/testagent.go

After I increased test parallelism in https://github.com/hashicorp/consul/pull/18999, I noticed random tests would panic due to not enough ports being free:
```
2023-10-03T16:41:26.3801137Z === [31mFAIL[0m: command/monitor TestMonitorCommand_exitsOnSignalBeforeLinesArrive (0.00s)
2023-10-03T16:41:26.3801752Z     testagent.go:417: failed to take 8 ports: %!w(*errors.errorString=&{freeport: block size too small})
2023-10-03T16:41:26.3802154Z panic: freeport: cannot allocate port block [recovered]
2023-10-03T16:41:26.3802542Z 	panic: freeport: cannot allocate port block [recovered]
2023-10-03T16:41:26.3802949Z 	panic: freeport: cannot allocate port block
```
This PR attempts to reduce reserved ports by 1, hoping to reduce the frequency of these panics.

Reduce number of ports that consul test agents take

---

agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
agent/grpc-external/testutils/acl.go
internal/mesh/proxy-tracker/proxy_state_exports.go
internal/mesh/proxy-tracker/proxy_state_exports_test.go

PR Discussion: https://github.com/hashicorp/consul-enterprise/pull/6760#discussion_r1319233169
TODO in code: https://github.com/hashicorp/consul/blob/main/agent/consul/leader_connect_ca.go#L1459
AuthorizeAndSignCertificate is called from two places and both resolve the authorizer from the token.  So, we can utilize IdentityWriteAllowed which will pass in the authorizer based on the token to achieve Check for identity:write on the token when identity permissions are supported. 
- https://github.com/hashicorp/consul/blob/21ea527089ef81e6b2ec48042915e60c3d385b5a/agent/grpc-external/services/connectca/sign.go#L71-L76
- https://github.com/hashicorp/consul/blob/21ea527089ef81e6b2ec48042915e60c3d385b5a/agent/consul/connect_ca_endpoint.go#L155-L161
Acceptance Criteria:
- check that we have …

NET-5590 - authorization: check for identity:write in CA certs, xds server, and getting envoy bootstrap params

---

internal/auth/internal/types/workload_identity.go
internal/auth/internal/types/workload_identity_test.go

Will add tenanted tests in a followup PR

Add workload identity hooks

---

website/content/docs/upgrading/upgrade-specific.mdx

Add upgrade warnings

---

website/content/docs/upgrading/upgrade-specific.mdx

[1.15.x] Update upgrade-specific.mdx

---

website/content/docs/upgrading/upgrade-specific.mdx

[1.14.x] Update upgrade-specific.mdx

---

.github/workflows/test-integrations.yml

Bump up compatibility test runner 

---

.changelog/19077.txt
agent/acl_endpoint_test.go
agent/consul/acl_endpoint.go
agent/consul/auth/binder.go
agent/consul/auth/binder_test.go
agent/structs/acl_templated_policy.go
agent/structs/acl_templated_policy_ce.go
agent/structs/acl_templated_policy_ce_test.go
agent/structs/acltemplatedpolicy/policies/ce/workload-identity.hcl
agent/structs/acltemplatedpolicy/schemas/workload-identity.json
api/acl.go

[CE] Add workload bind type and templated policy

---

agent/health_endpoint_test.go
agent/http_test.go
agent/metrics_test.go
agent/testagent.go

These tests are flaky but tend to pass eventually

Retry flaky tests

---

.changelog/18959.txt
agent/proxycfg/proxycfg.deepcopy.go
agent/proxycfg/snapshot.go
agent/proxycfg/terminating_gateway.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/builtin_extension/clusters/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/endpoints/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/listeners/otel-access-logging-http.latest.golden
agent/xds/testdata/builtin_extension/routes/otel-access-logging-http.latest.golden
agent/xds/testdata/listeners/terminating-gateway-with-peer-trust-bundle.latest.golden
agent/xds/testdata/rbac/v2-default-deny.golden
agent/xds/testdata/rbac/v2-kitchen-sink.golden

This PR enables services in one datacenter to access resources through a terminating gateway in another datacenter over cluster peering.
In the diagram below, previously only `backend` could reach `Google`. Now `frontend` can also reach `Google`.
```text
__ dc1 ________________          __ dc2 ________________
|  ____________       |          |  ___________        |
|  |          |       |          |  |         |        |
|  | frontend |       |          |  | backend |        |
|  |__________|       |          |  |_________|        |
|        |            |          |         |           |
|        |    ___________     ___________  |  _______________    __________
|        |    |         |     |         |  -->|             |    |        |
|        ---->|  Mesh   |---->|  Mesh   |---->| …
```

Allow connections through Terminating Gateways from peered clusters NET-3463

---

internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden

The virtual port number should be present for implicit upstreams in both L4 and L7 so that the tproxy matching rules can correctly "catch" the traffic.

mesh: ensure we add the virtual port number for L7 implicit upstreams

---

.github/workflows/jira-pr.yaml

Change from `hub` to `gh` for checking member roles. https://mislav.net/2020/01/github-cli/

Replace `hub` with `gh` for member roles on JIRA sync checks

---

agent/config/builder.go
agent/config/default.go
agent/config/runtime_test.go
agent/consul/config.go
agent/consul/server.go
agent/setup.go

This change the raft backend configuration behaviour as follow:
- If no backend is specified, `experiments=["resource-apis"]` is set  and no boltdb raft file is on disk the backend will be WAL
- If WAL is set and no boltdb raft file is on disk WAL is used (this is haven't changed)
- If Boltdb is set boltDB will be used (this is haven't changed)
- If a db exist on disk using boltdb it will be used (this is haven't changed)
This is still missing the doc part that need to be added, I'm not sure if we add it right away or need to wait for the release.
Added config tests and manually tested that all the combinations above work as expected.

Make raft-wal default when `resource-apis` is active

---

.github/workflows/test-integrations.yml
Makefile
internal/resource/resourcetest/builder.go
internal/resource/resourcetest/client.go
test/integration/consul-container/assets/Dockerfile-consul-dataplane
test/integration/consul-container/libs/cluster/builder.go
test/integration/consul-container/libs/cluster/dataplane.go
test/integration/consul-container/libs/topology/peering_topology.go
test/integration/consul-container/test/multiport/explicit_destination_test.go
test/integration/consul-container/test/traffic_permissions/tcp_test.go
test/integration/consul-container/test/trafficpermissions/tcp_test.go

Add integration tests for TCP traffic permissions.

Add traffic permissions integration tests.

---

.changelog/_6074.txt
agent/configentry/merge_service_config.go
agent/service_manager.go
agent/structs/config_entry.go
agent/structs/config_entry_ce.go
agent/structs/config_entry_ce_test.go
agent/structs/structs_ce.go
website/content/docs/connect/proxies/proxy-config-reference.mdx

This PR fixes an issue where upstreams did not correctly inherit the proper namespace / partition from the parent service when attempting to fetch the upstream protocol due to inconsistent normalization.
Some of the merge-service-configuration logic would normalize to default, while some of the proxycfg logic would normalize to match the parent service. Due to this mismatch in logic, an incorrect service-defaults configuration entry would be fetched and have its protocol applied to the upstream.
It's worth noting that the documentation for upstreams has been wrong for quite some time, and so this PR changes it to match the actual underlying logic. https://github.com/hashicorp/consul/blame/v1.16.2/agent/proxycfg/state.go#L139-L161

Ensure that upstream configuration is properly normalized.

---

internal/protohcl/decoder.go
internal/protohcl/unmarshal_test.go

Fixes a bug where the protohcl decoder wouldn't decode maps in attribute syntax properly.
* protohcl unmarshalling tests ensure that we got things correct

protohcl: allow attribute syntax for all map fields

---

.github/workflows/test-integrations-windows.yml

Stops integration tests for windows.

Stop windows integration tests

---

agent/agent.go
agent/consul/options.go
agent/consul/server.go
agent/http.go
agent/testagent.go

centralize useV2Resources logic in deps and use that to configure server

---

agent/ae/ae.go
agent/agent.go
agent/agent_endpoint_test.go
agent/catalog_endpoint_test.go
agent/config_endpoint_test.go
agent/consul/options.go
agent/consul/server.go
agent/health_endpoint_test.go
agent/http.go
agent/rpc/middleware/interceptors.go
agent/structs/errors.go
agent/testagent.go
agent/ui_endpoint_test.go

When the v2 catalog experiment is enabled the old v1 catalog apis will be forcibly disabled at both the API (json) layer and the RPC (msgpack) layer. This will also disable anti-entropy as it uses the v1 api.
This includes all of `/v1/catalog/*`, `/v1/health/*`, most of `/v1/agent/*`, `/v1/config/*`, and most of `/v1/internal/*`.
NET-5581

server: when the v2 catalog experiment is enabled reject api and rpc requests that are for the v1 catalog

---

agent/xdsv2/testdata/input/l4-single-implicit-destination-tproxy.golden
agent/xdsv2/testdata/output/listeners/l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-implicit-and-explicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden

The tproxy destination builder code does not create this blurb: https://github.com/hashicorp/consul/blob/main/agent/xds/listeners.go#L551 to add the catch-all outbound filter chain to let you send traffic outside of the cluster (i.e. [google.com](http://google.com/)). In effect we’ve inlined MeshDestinationsOnly = true.
We should allow outbound traffic to work.
Manually verfied in consul-k8s by:
- configuring Tproxy
- using image from this branch
- deploying web and api services per the multiport docs
- execing into web and curling google.com and getting the below response:

NET-5822 - Add default outbound router in TProxy

---

command/resource/helper.go

We serially attempt to decode resources in the `consul resource apply` command using HCL and then falling back on JSON. This causes the HCL errors to be dropped completely in the case where the HCL decode failed due to a typo instead of it actually being JSON instead.
This PR proposes sniffing to see if the first non-whitespace character in the input is `{` and if so treat it as JSON, otherwise as HCL and not double-decode on error.
This turns the following masked error:
```
Failed to decode resource from input file: Failed to decode resource from input file: invalid character 'I' looking for beginning of value
```
into this proper un-masked error:
```
Failed to decode resource from input file: Failed to decode resource from input file: :13,3-8: Unsupported argument; An argument named …
```

cli: do not hide the resource HCL parsing error and replace it with a JSON error

---

api/go.mod
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/libs/service/connect.go
test/integration/consul-container/libs/service/gateway.go
test/integration/consul-container/libs/service/helpers.go

This ensures that the `test/integration/consul-container` tree matches between CE and Enterprise save for some divergences called out on the related enterprise PR.

test: fix container test enterprise drift

---

.changelog/19095.txt
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go

This PR manually merges changes to release/1.14.x because of the divergence of that branch from main where the changes were introduced. There are no changes to the `agent/connect/ca/provider_vault.go` file because the existing `setNamespace` func in this branch correctly handles setting the namespace from the configuration.

release/1.14.x: Manual backport of #19095

---

.github/scripts/license_checker.sh
.github/workflows/license-checker.yml

Just testing this out on the release branch and then will rubberstamp in all the places.
```
$ cat crap.sh                                                                                                                                                                                                                                     
#!/bin/bash
if [[ ${GITHUB_BASE_REF} == release/1.14.* ]] || [[ ${GITHUB_BASE_REF} == release/1.15.* ]] || [[ ${GITHUB_BASE_REF} == release/1.16.* ]]; then
echo "Matched!"
else
echo "skipped"
fi% …
```

Fix BUSL license checker to skip >= 1.17.x target branches

---

.github/scripts/license_checker.sh
.github/workflows/license-checker.yml

Rubber stamping https://github.com/hashicorp/consul/commit/76f5b71708bd5e7872e809732fd23f59b825cada from `release/1.17.x` and backporting to n-2.
See NET-5935 for tracking.

Fix BUSL license checker to skip >= 1.17.x target branches (#19152)

---

internal/catalog/internal/controllers/workloadhealth/controller.go
internal/catalog/internal/controllers/workloadhealth/controller_test.go
internal/catalog/internal/mappers/nodemapper/node_mapper.go

The initial version of node mapper just used a map based on workload name.  it did not respect tenancy.  this PR replaces the nodemapper internals to use bimapper.
I checked other mappers and did not see any that did not use bimapper.

NET-5799 - ensure catalog controllers and dependency mappers function correctly for tenancy fields

---

internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/failover_policy_test.go

FailoverPolicy does not support `mode`, `regions`, or `sameness_group` yet, so block them during validation.
NET-5698

catalog: block unsupported failover policy settings for now

---

agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go

Previously this endpoint was listing all proxy configs and combining them into one. Now we can re-use the computed resource so that we get the sorting and easy lookup.

get-envoy-bootstrap-params: when v2 is enabled, use computed proxy configuration

---

website/content/docs/upgrading/upgrade-specific.mdx

Add Enterprise upgrade-specific note for: https://github.com/hashicorp/consul/pull/19076

Add 1.17 upgrade-specific note for upstream normalization.

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/naming.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-implicit-and-explicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-destination-ip-port-bind-address.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-destination-unix-socket-bind-address.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden

NET-5951 - Unique route names for implicit routes

---

command/resource/apply/apply.go
command/resource/apply/apply_test.go
command/resource/helper.go

Similar to the config entry write command the resource apply command can take input from stdin directly without having to store the HCL file on the file system.
`echo {{resource-definition}} | consul resource apply -`
Added automated tests and manual testing locally

Net-5771/apply command stdin input

---

internal/catalog/exports.go
internal/catalog/internal/controllers/endpoints/reconciliation_data.go
internal/catalog/internal/controllers/endpoints/reconciliation_data_test.go
internal/catalog/internal/types/dns_policy.go
internal/catalog/internal/types/health_checks.go
internal/catalog/internal/types/service.go
internal/catalog/internal/types/validators.go
internal/catalog/internal/types/validators_test.go
internal/mesh/internal/controllers/explicitdestinations/controller.go
internal/mesh/internal/controllers/proxyconfiguration/controller.go
internal/mesh/internal/types/destinations.go
internal/mesh/internal/types/destinations_configuration.go
internal/mesh/internal/types/destinations_configuration_test.go
internal/mesh/internal/types/destinations_test.go
internal/mesh/internal/types/proxy_configuration.go
internal/mesh/internal/types/proxy_configuration_test.go
internal/resource/filter.go
internal/resource/filter_test.go

This implements the `Filter` field on `pbcatalog.WorkloadSelector` to be a post-fetch in-memory filter using the https://github.com/hashicorp/go-bexpr expression language to filter resources based on their envelope `metadata` fields.
All existing usages of WorkloadSelector should be able to make use of the filter.
NET-5696

catalog: add metadata filtering to refine workload selectors

---

agent/agent_endpoint_test.go
agent/http.go

Fixes a bug in https://github.com/hashicorp/consul/pull/19129 where `/v1/agent/self` was allowed but `/v1/agent/self?dc=dc1` was not.

server: run the api checks against the path without params

---

command/resource/testdata/nested_data.hcl
internal/catalog/exports.go
internal/catalog/internal/types/failover_policy.go
internal/catalog/internal/types/service.go
internal/catalog/internal/types/service_endpoints.go
internal/catalog/internal/types/validators.go
internal/catalog/internal/types/validators_test.go
internal/catalog/internal/types/workload.go
internal/mesh/internal/controllers/sidecarproxy/controller_test.go
internal/mesh/internal/types/destinations.go
internal/mesh/internal/types/destinations_test.go
internal/mesh/internal/types/errors.go
internal/resource/errors.go

Add more validations to supported fields and error out for fields that we don't yet support.

mesh: add more validations to Destinations resource

---

internal/mesh/internal/types/xroute_test.go
internal/resource/resourcetest/acls.go

Enhance the xRoute ACL hook tests to cover tenanted situations. These tests will only execute in enterprise.

mesh: add xRoute ACL hook tenancy tests

---

.changelog/19218.txt
agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/list_by_owner_test.go
agent/grpc-external/services/resource/list_test.go
agent/grpc-external/services/resource/read_test.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/watch.go
agent/grpc-external/services/resource/watch_test.go
agent/grpc-external/services/resource/write_status.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go
internal/mesh/internal/controllers/xds/controller_test.go
internal/resource/demo/controller.go
internal/resource/demo/demo.go
internal/resource/http/http_test.go
internal/resource/resource.go
internal/resource/tenancy.go
internal/tenancy/internal/types/namespace_test.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7344
JIRA: NET-5816

resource: enforce lowercase resource names

---

internal/mesh/internal/types/destination_policy_test.go
internal/resource/resourcetest/acls.go

Enhance the DestinationPolicy ACL hook tests to cover tenanted situations. These tests will only execute in enterprise.

mesh: add DestinationPolicy ACL hook tenancy tests

---

internal/catalog/internal/types/failover_policy_test.go

Enhance the FailoverPolicy ACL hook tests to cover tenanted situations. These tests will only execute in enterprise.

catalog: add FailoverPolicy ACL hook tenancy test

---

website/content/docs/services/discovery/dns-configuration.mdx

Add  reason in docs why port 53 is not used by default.

Add reason why port 53 is not used by default

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden

This fixes a small issue where the failover endpoint group had the first element for the original destination but it did not have a name.  It needs to carry the failover target naming convention and use the index of 0.  destinations specified in the FailoverPolicy then start with an index of 1 and higher.
See unit test.

NET-6097 - sidecar proxy controller - give name to first failover policy target

---

.github/workflows/frontend.yml

CI has been failing for V1.15.X, which isn't good!
We're planning on just downgrading the node version on CI until next quarter when v1.15.X is no longer supported!
We also only want this change on v1.15.X branch, since we don't want to downgrade node for main.
- Run CI
- Note that the [frontend tasks don't fail](https://github.com/hashicorp/consul/actions/runs/6152797280/job/16696147709?pr=18750)
- 
- [Jira](https://hashicorp.atlassian.net/browse/CC-6363)

Downgrading node on CI to support v1.15.X

---

website/content/docs/connect/config-entries/control-plane-request-limit.mdx

The control-plane-request-limit config entry does not support specifying parameter names in snake case format.
This commit updates the HCL and JSON examples to use the supported camel case key format.
1. Create `control-plane-request-limit-snake_case.hcl` with the following configuration.
```hcl
kind = "control-plane-request-limit"
name = "global-limits"
mode = "permissive"
read_rate =  100
write_rate = 100
kv = {
read_rate =  100
write_rate = 100
}
acl = {
read_rate =  100
write_rate = 100
}
catalog = {
read_rate =  100
write_rate = 100
}
```
1. Attempt to save the configuration using `consul config write`.
```shell-session
$ consul config write control-plane-request-limit-snake_case.hcl
Failed to decode config entry input: 8 errors occurred:
* invalid config key "ACL.read_rate"
* …
```

docs: Fix example control-plane-request-limit HCL and JSON

---

.github/workflows/nightly-test-integrations-1.17.x.yml

This step is missing from our release doc. We have new nightly integration tests that must be added when a new, long-lived release branch is cut.

test: add 1.17 nightly integrations test

---

internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l7-expose-paths.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden

* When testing adding http probes to apps, I ran into some issues which I fixed here:
* The listener should be listening on the exposed listener port, updated that.
* The listener and route names were pointing to the path of the exposed path. In my test, the path was "/" resulting in an empty string path. Also, the path may not be unique across exposed path listeners, so I decided to use the path+exposed port as the unique identifier.

fix expose paths

---

internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l7-expose-paths.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden

Backporting https://github.com/hashicorp/consul/pull/19257

[Backport 1.17] fix expose paths

---

website/content/docs/k8s/multiport/configure.mdx

- Fix install instructions for installing multi-port 1.17-rc1. 
- Add in env variables to make it easier to run commands. 
- Remove `--namespace=consul` from commands related to workloads since that namespaces is reserved just for Consul.

docs: Fix multi-port install

---

agent/consul/server.go
agent/consul/server_test.go
agent/consul/testdata/v2-resource-dependencies.md
internal/controller/dependencies.go
internal/controller/dependencies_test.go
internal/controller/testdata/dependencies.golden

* Validate that no circular dependencies exist between resources. If they do, the agent will fail to start up. At some point, it might be nice to use a custom client from controllers that only allows fetching watched resources.
* Store a mermaid diagram with all dependencies between resources in agent/consul/testdata/v2-resource-dependencies.md. This is slightly annoying because the golden test will need to be updated as new resources and controller watches are created, but the upside is always having an up-to-date diagram with these relationships.

Prevent circular dependencies between v2 resources and generate a mermaid diagram with their dependencies

---

website/content/docs/k8s/multiport/configure.mdx

backport: docs: Fix multi-port install (#19262)

---

.github/workflows/build.yml

Always publishing full and minor-only tag versions. This accomplishes two goals:
For long-running release branches, .x, always publish a minor-only tag so that tests use the latest version (e.g. 1.17-dev)
For point release branches, .0, always publish the full version so we can fix this for testing purposes (e.g. 1.17.0)
Similar to https://github.com/hashicorp/consul-dataplane/pull/306

build(docker): always publish full and minor version tags for dev images

---

.github/workflows/nightly-test-integrations-1.17.x.yml

Fix the envoy version in the nightly integration test, as well as the upgrade from version (we support upgrade from 1.15 and 1.16 to 1.17, so remove 1.14 from the list)

fix nightly integration test: envoy version and n-2 version

---

.changelog/_7406.txt
api/config_entry_rate_limit_ip.go

The counterpart of ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7406
See ENT PR.

fix: allow snake case keys for ip based rate limit config entry

---

website/content/docs/ecs/reference/consul-server-json.mdx

This formats the ECS Consul server configuration reference into our standard configuration reference format. This PR is an incremental improvement over the existing page. We apply another round of edits when we have a better idea about the content gaps.

reformatted the JSON schema server conf ref

---

acl/MockAuthorizer.go
acl/acl_test.go
acl/authorizer.go
acl/chained_authorizer.go
acl/chained_authorizer_test.go
acl/policy_authorizer.go
acl/policy_authorizer_test.go
acl/static_authorizer.go
internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
internal/catalog/internal/types/acl_hooks.go

To properly enforce writes on resources that have workload selectors with prefixes, we need another `service` authorization rule that allows us to check whether read is allowed within a given prefix. Specifically we need to only allow writes if the policy prefix allows for a wider set of names than the prefix selector on the resource. We should also not allow policies with exact names for prefix matches.
Part of [NET-3993]
Examples:
(when default is deny)
**Decision: deny**
selector:
```
Workloads: { Prefixes = ["api"] }
```
policy:
```
...
service "api" { policy = "read" }
```
**Decision: allow**
selector:
```
Workloads: { Prefixes = ["api"] }
```
policy:
```
...
service_prefix "api" { policy = "read" }
```
**Decision: deny**
selector:
```
Workloads: { Prefixes = ["api"] }
```
policy: …

acls,catalog,mesh: properly authorize workload selectors on writes

---

.github/scripts/verify_envoy_version.sh
.github/workflows/verify-envoy-version.yml

Temporarily  disable `Verify Envoy Version` script. 
Script is currently failing in CI because Envoy just released a new version (1.28.0) this AM. The process of updating Envoy versions across branches is currently in progress.
```
Latest released Envoy version is: v1.28.0
ERROR! Branch refs/heads/main; Envoy versions: 1.27.0 1.26.4 1.25.9 1.24.10 needs to be updated.
Error: Process completed with exit code 1.
```
[CI](https://github.com/hashicorp/consul/actions/runs/6579264966/job/17874749926) of failing Verify Envoy Version
[CI](https://github.com/hashicorp/consul/actions/runs/6579139141/job/17874364219#step:3:8) to skip Verify Envoy version

NET-6239: Temporarily disable verify envoy check

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden

* domain was missing, I think it's ok to just hardcode ["*"] for now
* in v1, we set custom named domains in api gateway or terminating gateway cases, but we don't have any gateway-backed or fronted upstreams in v2 yet.
* in v1 for discovery chain upstreams we always use ["*"] here: https://github.com/hashicorp/consul/blob/main/agent/xds/routes.go#L64

mesh: provide missing domain to route configurations in ProxyStateTemplate

---

acl/MockAuthorizer.go
acl/acl_test.go
acl/authorizer.go
acl/chained_authorizer.go
acl/chained_authorizer_test.go
acl/policy_authorizer.go
acl/policy_authorizer_test.go
acl/static_authorizer.go
internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
internal/catalog/internal/types/acl_hooks.go

[1.17.0 backport] acls,catalog,mesh: properly authorize workload selectors on writes

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden

This PR is manually generated from #19298 for backporting to the `1.17.0` GA release branch.
---
* domain was missing, I think it's ok to just hardcode ["*"] for now
* in v1, we set custom named domains in api gateway or terminating gateway cases, but we don't have any gateway-backed or fronted upstreams in v2 yet.
* in v1 for discovery chain upstreams we always use ["*"] here: https://github.com/hashicorp/consul/blob/main/agent/xds/routes.go#L64

Backport of mesh: provide missing domain to route configurations in ProxyStateTemplate into release/1.17.0

---

.changelog/19285.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

Fixing edge case bugs uncovered by https://github.com/hashicorp/consul/issues/19051
Added tests for goroutine leak detection.
The retry functionality is a revert of #16143 and was tested manually.

Vault CA bugfixes

---

agent/consul/server.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/testing/testing.go
agent/grpc-external/services/resource/testing/testing_ce.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_status.go
internal/resource/http/http_test.go
internal/resource/tenancy.go
internal/tenancy/exports.go
internal/tenancy/internal/bridge/tenancy_bridge.go
internal/tenancy/internal/bridge/tenancy_bridge_ce.go
internal/tenancy/internal/types/types_test.go
internal/tenancy/tenancytest/namespace_test.go

This change the namespace tests to use the real tenancy bridge and add all the bits to make the tests pass
Some tests were added but more real code is used in the tests now.

Tenancy Bridge v2 

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/naming.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden

Ensure that route configs are named uniquely per port so that we don't overwrite route configs for ports with the same protocol.

mesh: ensure route configs are named uniquely per port

---

website/content/api-docs/acl/auth-methods.mdx
website/content/api-docs/acl/binding-rules.mdx
website/content/api-docs/acl/index.mdx
website/content/api-docs/acl/policies.mdx
website/content/api-docs/acl/roles.mdx
website/content/api-docs/acl/templated-policies.mdx
website/content/api-docs/acl/tokens.mdx
website/content/api-docs/agent/check.mdx
website/content/api-docs/agent/connect.mdx
website/content/api-docs/agent/service.mdx
website/content/api-docs/catalog.mdx
website/content/api-docs/config.mdx
website/content/api-docs/connect/intentions.mdx
website/content/api-docs/discovery-chain.mdx
website/content/api-docs/health.mdx
website/content/api-docs/kv.mdx
website/content/api-docs/session.mdx
website/content/commands/acl/templated-policy/index.mdx
website/content/commands/acl/templated-policy/list.mdx
website/content/commands/acl/templated-policy/preview.mdx
website/content/commands/acl/templated-policy/read.mdx
website/content/docs/security/acl/index.mdx
website/content/docs/upgrading/upgrade-specific.mdx
website/data/api-docs-nav-data.json
website/data/commands-nav-data.json

- Adding API, CLI and more docs for templated policy feature

[NET-5327] Templated policies api/cli docs

---

.changelog/19285.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

* Re-add retry logic to Vault token renewal
* Fix goroutine leak
* Add test for detecting goroutine leak
* Add changelog
* Rename tests
* Add comment

[1.15.x] Vault CA bugfixes (#19285)

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/naming.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden

[1.17.0 manual backport]  mesh: ensure route configs are named uniquely per port 

---

website/content/docs/security/acl/index.mdx

Fixing docs to add more templated policies references

---

.changelog/19339.txt
agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/server_test.go
agent/grpc-external/server.go
agent/grpc-external/stats_test.go
agent/rpc/peering/service_test.go
website/content/docs/agent/config/config-files.mdx

Prior to the introduction of this configuration, grpc keepalive messages were sent after 2 hours of inactivity on the stream. This posed issues in various scenarios where the server-side xds connection balancing was unaware that envoy instances were uncleanly killed / force-closed, since the connections would only be cleaned up after ~5 minutes of TCP timeouts occurred. Setting this config to a 30 second interval with a 20 second timeout ensures that at most, it should take up to 50 seconds for a dead xds connection to be closed.

Add grpc keepalive configuration.

---

.changelog/19339.txt
agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/server_test.go
agent/grpc-external/server.go
agent/grpc-external/stats_test.go
agent/rpc/peering/service_test.go
website/content/docs/agent/config/config-files.mdx

Manual backport of https://github.com/hashicorp/consul/pull/19339

Backport of Add grpc keepalive configuration into release/1.16.x (#19339)

---

.changelog/19314.txt
go.mod
go.sum
test-integ/go.mod
test-integ/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum

This bump the version of raft-wal library to 0.4.1, which fixes 2 issues in raft-wal:
- https://github.com/hashicorp/raft-wal/pull/33
- https://github.com/hashicorp/raft-wal/pull/32
Notice that WAL is an experimental feature in Consul and only available when explicitly activated or when v2 resource-api experimental feature is on.
No specific testing for this, testing was done in raft-wal library.

bump raft-wal version to 0.4.1

---

internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/xds/controller_test.go
internal/mesh/internal/controllers/xds/testdata/destination/l4-implicit-and-explicit-destinations-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/l4-multi-destination.golden
internal/mesh/internal/controllers/xds/testdata/destination/l4-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/l4-single-destination-ip-port-bind-address.golden
internal/mesh/internal/controllers/xds/testdata/destination/l4-single-destination-unix-socket-bind-address.golden
internal/mesh/internal/controllers/xds/testdata/destination/l4-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
internal/testing/golden/golden.go

TestReconcile_SidecarProxyGoldenFileInputs tests the Reconcile() by using the golden test output/expected files from the sidecar proxy tests as inputs to the XDS controller reconciliation.   The golden files added here for the expected output really only need to be verified for the correctness of the following proxyState fields:
- endpoints
- trustBundles
- leafCertificates
Destination proxy tests cases are tested in this PR.  Sources are added in a follow up PR: https://github.com/hashicorp/consul/pull/19241

NET-5397 - wire up destination golden tests from sidecar-proxy controller for xds controller and xdsv2

---

.changelog/19268.txt
agent/xds/clusters.go
agent/xds/testdata/clusters/mesh-gateway-with-peer-through-mesh-gateway-enabled.latest.golden

This fixes https://github.com/hashicorp/consul/issues/17557. In an attempt to support mesh gateways fronted by AWS load balancers, a code path for peered mesh gateways was introduced in https://github.com/hashicorp/consul/pull/14917 that leverages envoy clusters backed by the `LOGICAL_DNS` cluster discovery type. Problematically, when replicas of mesh gateways exist in a peered connection, the dialing peer will hit this code path and attempt to add multiple endpoints for the targeted mesh gateways. Envoy, however, doesn't support multiple endpoints using `LOGICAL_DNS` and will start spitting out errors applying the xDS it receives from Consul.
In Kubernetes, when a mesh gateway restarts then, it will never finish initializing and get marked as healthy, so its pod will continually restart …

Use strict DNS for mesh gateways with hostnames

---

.changelog/19339.txt
agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/server_test.go
agent/grpc-external/server.go
agent/grpc-external/stats_test.go
agent/rpc/peering/service_test.go
website/content/docs/agent/config/config-files.mdx

[NET-6295] Backport of Add grpc keepalive configuration. (#19339)

---

.changelog/19314.txt
go.mod
go.sum
test-integ/go.mod
test-integ/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum

This is a manual backport of https://github.com/hashicorp/consul/pull/19314

1.17.x backport: bump raft-wal version to 0.4.1 (#19314) 

---

.changelog/19314.txt
go.mod
go.sum
test-integ/go.mod
test-integ/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum

This is a manual backport of https://github.com/hashicorp/consul/pull/19314

1.17.0 backport: bump raft-wal version to 0.4.1 (#19314)

---

agent/structs/config_entry.go
api/config_entry.go
website/content/docs/connect/config-entries/service-defaults.mdx

Add clarification for route match behavior

---

website/content/docs/release-notes/consul/v1_17_x.mdx

- Fix docs to formatting 
- Added docs for templated policies

Fix 1.17.x release notes and added templated policies

---

website/content/docs/release-notes/consul/v1_17_x.mdx

- Add Enterprise labels to features
- Add non-dns compatible example

docs - release notes (add enterprise label and example of non compatible service name)

---

internal/tenancy/tenancytest/namespace_test.go

- This PR just adds the missing tests for the namespace read use case.
~- Update error type to `InvalidArgument` on tenancy check which is now consistent with other endpoints~
- Tested manually
- Added tests
See the Acceptance Criteria in [NET-5521](https://hashicorp.atlassian.net/browse/NET-5521)
[NET-5521]: https://hashicorp.atlassian.net/browse/NET-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: read resource namespace

---

agent/grpc-external/services/resource/list_test.go

PR adds missing test for Name prefix matching
Ticket: [NET-5523](https://hashicorp.atlassian.net/browse/NET-5523)
[NET-5523]: https://hashicorp.atlassian.net/browse/NET-5523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add missing tests for list endpoint

---

website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/manage-traffic/limit-request-rates.mdx

Add enterprise label for rate limiting

---

testing/deployer/topology/compile.go
testing/deployer/topology/images.go

When testing a cluster with different consul versions, the per node `ConsulEnterprise` image should override the default image. Since `c.Images` has been mutated with `ChooseConsul(c.Enterprise)` (see below code), the per node overwrite won't happen
https://github.com/hashicorp/consul/blob/0fefaa649fc7b65c3975bff15f0fc635b33e26fa/testing/deployer/topology/compile.go#L114-L116
To fix this, we need to mutate the per node image as well and then use it to overwrite the default one.
Create a cluster with server nodes with different `ConsulEnterprise`, and the created cluster will have the same images.

test deployer: fix a bug when deploying cluster with various ent images

---

.changelog/19389.txt
command/acl/role/create/role_create.go
command/acl/role/create/role_create_test.go
command/acl/token/create/token_create.go
command/acl/token/create/token_create_test.go

- Prevent usage of `templated-policy` and `templated-policy-file` simultaneously to improve ux for templated policy use
```
consul acl token create -templated-policy "builtin/service" -templated-policy-file "templatedpolicy.hcl"
Cannot combine the use of templated-policy flag with templated-policy-file. To create a token with a single templated policy and simple use case, use -templated-policy. For multiple templated policies and more complicated use cases, use -templated-policy-file
```

Stop use of templated-policy and templated-policy-file simultaneously

---

website/content/docs/services/discovery/dns-configuration.mdx

Add reason in docs why port 53 is not used by default. Backport of https://github.com/hashicorp/consul/pull/19222

docs: Update dns-configuration.mdx

---

agent/consul/options.go
agent/consul/server.go
agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_ce.go
agent/grpc-external/services/resource/testing/testing.go
agent/grpc-external/services/resource/testing/testing_ce.go
agent/grpc-external/services/resource/watch.go
agent/grpc-external/services/resource/write.go
internal/tenancy/exports.go
internal/tenancy/internal/controllers/register_ce.go
internal/tenancy/internal/types/namespace.go
internal/tenancy/internal/types/types_test.go
internal/tenancy/tenancytest/namespace_test.go

CE version of merged ENT PR that adds checking for `v2tenancy` feature flag: https://github.com/hashicorp/consul-enterprise/pull/7479

resource: resource service now checks for `v2tenancy` feature flag

---

website/content/docs/connect/config-entries/exported-services.mdx

[This page](https://developer.hashicorp.com/consul/docs/connect/config-entries/exported-services) in the docs has example code that is copy-pastable; however, it has a casing error which prevents the copied code from working for Kubernetes:
```
error: error validating "cluster-2/exported-services.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
```
Copy-paste the modified examples and attempt to apply them to a Kubernetes cluster using `kubectl apply -f <filename>`. Verify the command completes successfully instead of returning the above error.
[Page containing broken example code](https://developer.hashicorp.com/consul/docs/connect/config-entries/exported-services)

Fix casing in example yaml config

---

.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml

CI is failing when a whole test run goes over the default of 10m.  This happens mostly with the agent package when the tests are split.  and this happens more in enterprise with self hosted runners.  
This change is to make it 30m which matches the integration tests setting.

increasing unit tests timeout from 10m to 30m

---

.github/workflows/test-integrations.yml
test-integ/connect/snapshot_test.go
testing/deployer/sprawl/boot.go
testing/deployer/sprawl/sprawl.go
testing/deployer/topology/default_consul.go
testing/deployer/topology/topology.go

integ test: snapshot mesh frozen bug test

---

website/content/docs/k8s/compatibility.mdx

Update k8s compat matrix. Remove TKGI note for 0.49.x and below.

docs - Update k8s compat matrix 

---

website/content/docs/connect/dataplane/index.mdx

As a compliment to https://github.com/hashicorp/consul-dataplane/pull/238 and https://github.com/hashicorp/consul-k8s/pull/2787, this PR updates the docs to list the `NET_BIND_SERVICE` capability as a requirement for consul-dataplane.
N/A
Related to:
- https://github.com/hashicorp/consul-dataplane/pull/238
- https://github.com/hashicorp/consul-k8s/pull/2787

NET-5186 Add NET_BIND_SERVICE capability to consul-dataplane requirements

---

website/redirects.js

Prior to v1.9.x, configuration entries appeared int he /agent dir instead the /connect dir. This PR redirects people who view a conf entry in the current /connect folder and switch to docs v1.8.x so that they land on the conf entry in the /agent folder.  Fixes per this [Slack thread](https://hashicorp.slack.com/archives/C011HP57U0Y/p1698853199142849).

added redirect for conf entries 1.8.x

---

website/content/docs/connect/manage-traffic/index.mdx

Update a typo in the L7 Traffic splitting example

Update docs for service splitter example typo

---

website/content/docs/connect/l7-traffic/index.mdx

Update a typo in the L7 Traffic splitting example

Update typo in l7-traffic service splitting example

---

build-support/docker/Consul-Dev-Multiarch.dockerfile
build-support/docker/Consul-Dev.dockerfile

This should remove the following reason integration tests can flake:
```
#3 [internal] load metadata for docker.io/hashicorp/consul:latest
#3 ERROR: pulling from host registry-1.docker.io failed with status code [manifests latest]: 429 Too Many Requests
------
> [internal] load metadata for docker.io/hashicorp/consul:latest:
------
Consul-Dev.dockerfile:5
--------------------
3 |     
4 |     ARG CONSUL_IMAGE_VERSION=latest
5 | >>> FROM hashicorp/consul:${CONSUL_IMAGE_VERSION}
6 |     RUN apk update && apk add iptables
7 |     COPY consul /bin/consul
--------------------
ERROR: failed to solve: hashicorp/consul:latest: pulling from host registry-1.docker.io failed with status code [manifests latest]: 4[29](https://github.com/hashicorp/consul/actions/runs/6735998317/job/18310522716?pr=19046 …
```

build: ensure we pull through the hashicorp proxy instead of going directly to the docker hub

---

internal/auth/internal/types/errors.go
internal/auth/internal/types/traffic_permissions.go
internal/auth/internal/types/traffic_permissions_test.go

Temporarily prohibit L7 rules in Traffic Permissions (hopefully can remove in a week or two when implementation is done)

temporarily disallow L7 traffic permissions

---

agent/agent.go
agent/agent_endpoint.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime_test.go
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/proxycfg-sources/local/sync.go
agent/proxycfg-sources/local/sync_test.go
command/services/register/register_test.go
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/helpers.windows.bash
test/integration/consul-container/libs/cluster/agent.go

This change fixes several issues with configuring and using the new locality-aware routing feature introduced in 1.17.
* Ensure that file-based configuration (agent config and service registration) accept `locality` in addition to HTTP endpoints
* Ensure inheritance of locality from `NodeService` (agent configuration) to service proxies occurs when not explicitly specified in service registration
* Update integration and unit tests to exercise these changes
A follow-up change will align docs with proper user flows as noted in the ticket.
* Added/updated tests to verify behavior
* Manually tested locally

[NET-5916] Fix locality-aware routing config and tests (CE)

---

test-integ/catalogv2/helpers_test.go
test-integ/catalogv2/implicit_destinations_test.go
test-integ/peering_commontopo/ac3_service_defaults_upstream_test.go
test-integ/peering_commontopo/ac4_proxy_defaults_test.go
test-integ/topoutil/asserter.go
test-integ/topoutil/fixtures.go
test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/libs/assert/service.go
testing/deployer/sprawl/catalog.go
testing/deployer/sprawl/details.go
testing/deployer/sprawl/internal/build/docker.go
testing/deployer/sprawl/internal/tfgen/dns.go
testing/deployer/sprawl/internal/tfgen/gen.go
testing/deployer/sprawl/internal/tfgen/nodes.go
testing/deployer/sprawl/internal/tfgen/templates/container-app-dataplane.tf.tmpl
testing/deployer/topology/compile.go
testing/deployer/topology/images.go
testing/deployer/topology/relationships.go
testing/deployer/topology/topology.go

This is dependent upon https://github.com/hashicorp/consul/pull/19046.
This updates the testing/deployer (aka "topology test") framework to allow for a v2-oriented topology to opt services into enabling TransparentProxy. The restrictions are similar to that of #19046 
The multiport `Ports` map that was added in #19046 was changed to allow for the protocol to be specified at this time, but for now the only supported protocol is TCP as only L4 functions currently on main.
As part of making transparent proxy work, the DNS server needed a new zonefile for responding to `virtual.consul` requests, since there is no Kubernetes DNS and the Consul DNS work for v2 has not happened yet. Once Consul DNS supports v2 we should switch over. For now the format of queries is:
``` …
```

testing/deployer: support tproxy in v2 for dataplane

---

agent/xdsv2/testdata/listeners/destination/mixed-multi-destination.golden
agent/xdsv2/testdata/listeners/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
agent/xdsv2/testdata/listeners/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
agent/xdsv2/testdata/listeners/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/mixed-multi-destination.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
internal/mesh/internal/controllers/xds/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden

Sidecar proxy's builder is setting L7 destinations to have `statPrefix` of "upstream."  if you search `"statePrefix": ` in V1 golden files, you will not find any set to "upstream.", they have the full path.  
This was from implementing this check form V1 code.  However, if you follow the code further, it will wind up [here](https://github.com/hashicorp/consul/blob/413e2a76002b27c3ab4b0670c5daa11e1d0ff65b/agent/xds/listeners.go#L2468), where further calculates the `statPrefix` that is actually used.

NET-6319 - L7 routes have statePrefix of upstream. and should have a full path

---

test-integ/peering_commontopo/ac1_basic_test.go
test-integ/peering_commontopo/ac3_service_defaults_upstream_test.go
test-integ/peering_commontopo/ac4_proxy_defaults_test.go
test-integ/peering_commontopo/ac5_2_pq_failover_test.go
test-integ/peering_commontopo/ac6_failovers_test.go
test-integ/peering_commontopo/ac7_1_rotate_gw_test.go
test-integ/peering_commontopo/ac7_2_rotate_leader_test.go
test-integ/peering_commontopo/commontopo.go
test-integ/topoutil/asserter.go
test-integ/topoutil/fixtures.go
test/integration/consul-container/libs/cluster/cluster.go
test/integration/consul-container/test/ratelimit/ratelimit_test.go
testing/deployer/sprawl/internal/build/docker.go
testing/deployer/sprawl/peering.go
testing/deployer/sprawl/sprawl.go

This should align between CE ef35525cf1446544e574fd0d02c78ce5f31900b8 and ENT 7f95226dbe40151c8f17dd4464784b60cf358dc1 in:
- testing/integration/consul-container
- test-integ
- testing/deployer

chore: apply enterprise changes that were missed to some testing files

---

agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/list.go
agent/grpc-external/services/resource/list_by_owner.go
agent/grpc-external/services/resource/read.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/watch.go
agent/grpc-external/services/resource/watch_test.go
agent/grpc-external/services/resource/write.go
internal/controller/api_test.go
internal/controller/controller.go

Problem:
Since we were defaulting to watching all tenancy units by passing `*` regardless of the scope of the resource this caused the watch call in the controller to fail the validation check on the watch endpoint.
Solution:
In this PR I moved the defaulting of tenancy wildcards to the watch endpoint where scope is available to make the decision on necessary defaulting. This change also keeps us open to the possibility of allowing the controllers to watch for specific values in the tenancy fields as opposed to watching all (*).
Added test that demonstrates watches could be added on the partition and cluster scope resources.
Ticket:  [NET-6291](https://hashicorp.atlassian.net/browse/NET-6291)
[NET-6291]: https://hashicorp.atlassian.net/browse/NET-6291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

Net-6291/fix/watch resources

---

agent/xds/clusters_test.go
agent/xds/endpoints_test.go
agent/xds/listeners_test.go
agent/xds/resources_test.go
agent/xds/routes.go
agent/xds/routes_test.go
agent/xds/testdata/builtin_extension/routes/propertyoverride-patch-specific-upstream-service-failover.latest.golden
agent/xds/testdata/listeners/connect-proxy-with-chain.latest.golden
agent/xds/testdata/routes/connect-proxy-with-chain-and-failover-to-cluster-peer.latest.golden
agent/xds/testdata/routes/connect-proxy-with-chain-and-redirect-to-cluster-peer.latest.golden
agent/xds/testdata/routes/connect-proxy-with-chain-external-sni.latest.golden
agent/xds/testdata/routes/connect-proxy-with-chain.latest.golden
agent/xds/testdata/secrets/connect-proxy-with-chain-external-sni.latest.golden
agent/xds/testdata/secrets/connect-proxy-with-chain.latest.golden

This was found while trying to fix a xds v2 issue.  This causes routes to be created when they are not needed.  Having them should not cause unexpected behavior or user facing problems, but having this causes discrepancies when trying to validate V2 XDS code is generating the correct output.

XDS V1 should not make runs for TCP Disco Chains.

---

testing/deployer/sprawl/catalog.go

In 1.17 the catalog.v2beta1.Node type is of the namespace scope, which is incorrect. It should be a partition scoped type, but it needed to have the same tenancy scoping as the shared health status type for different reasons.
Until we create a new node health status type, update the `deployer` tests to not try and create workload-to-node linkages as they will not work properly in 1.17.

testing: disable v2 linkage to nodes in integration tests

---

.changelog/19444.txt
ui/packages/consul-hcp/app/components/consul/hcp/home/index.hbs
ui/packages/consul-hcp/app/components/consul/hcp/home/index.test.js

Currently the back to hcp link will show whenever `CONSUL_HCP_ENABLE` is set. However, there are times when the `CONSUL_HCP_URL` is not present. My understanding is this could be if you visit the UI directly without accessing it via HCP UI? Either way, we should only show the link if the value is present.
This is handled will be handled in the new sidenav on `main` and `1.17.x` via the side nav updates PR (#19342 ). I am manually backporting this change to 1.16 and 1.15 because of that.
1. Run the UI
2. Run `Scenario('CONSUL_HCP_ENABLE', 1)` in the browser console to enable HCP mode
3. Run `Scenario('CONSUL_HCP_URL', 'url of your choice')` in the browser console to set the HCP url.

ui: 1.15.x back to hcp link conditions

---

.changelog/19443.txt
ui/packages/consul-hcp/app/components/consul/hcp/home/index.hbs
ui/packages/consul-hcp/app/components/consul/hcp/home/index.test.js

Currently the back to hcp link will show whenever `CONSUL_HCP_ENABLE` is set. However, there are times when the `CONSUL_HCP_URL` is not present. My understanding is this could be if you visit the UI directly without accessing it via HCP UI? Either way, we should only show the link if the value is present.
This is handled will be handled in the new sidenav on `main` and `1.17.x` via the side nav updates PR (#19342 ). I am manually backporting this change to 1.16 and 1.15 because of that.
1. Run the UI
2. Run `Scenario('CONSUL_HCP_ENABLE', 1)` in the browser console to enable HCP mode
3. Run `Scenario('CONSUL_HCP_URL', 'url of your choice')` in the browser console to set the HCP url.

ui: 1.16.x Back to HCP link conditions

---

.changelog/19503.txt
agent/pool/pool.go

Prior to this commit, the connection pools were unaware which datacenter the connection was associated with. This meant that any time servers with overlapping LAN IP addresses and node shortnames existed, they would be incorrectly co-located in the same pool. Whenever this occurred, the servers would get stuck in an infinite loop of forwarding RPCs to themselves (rather than the intended remote DC) until they eventually run out of memory.
Most notably, this issue can occur whenever wan federation through mesh gateways is enabled.
This fix adds extra metadata to specify which DC the connection is associated with in the pool.

[NET-6459] Fix issue with wanfed lan ip conflicts.

---

website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx

This section is not necessary as it is not unique to the feature. The instructions for starting proxies are available in other pages.
Follow-up to https://github.com/hashicorp/consul/pull/19529.

[NET-5916] docs: Remove locality proxy startup section

---

.github/workflows/nightly-test-integrations.yml
test/integration/consul-container/test/upgrade/catalog/catalog_test.go

- Bump upgrade test for 1.17
- In `TestCatalogUpgrade`,  disable V1 API request since this test is for V2

Ci upgrade test 1 17

---

agent/consul/server.go
internal/controller/manager.go
internal/resource/resourcetest/client.go
internal/tenancy/exports.go
internal/tenancy/internal/controllers/register.go
internal/tenancy/internal/controllers/register_ce.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7597
https://hashicorp.atlassian.net/browse/NET-6334
Since the namespace controller (when it is written in CE) will also need access to the registry, I went ahead and exposed the deps in CE.

v2tenancy: register tenancy controller deps

---

proto-public/pbcatalog/v2beta1/failover_policy.pb.go
proto-public/pbcatalog/v2beta1/failover_policy.proto
proto-public/pbcatalog/v2beta1/health.pb.go
proto-public/pbcatalog/v2beta1/health.proto

Add kubebuilder labels to the enum fields in proto-public for catalog v2beta1 types for proper processing for CRDs.

Add kubebuilder annotations to enums

---

test-integ/peering_commontopo/ac6_failovers_test.go
test-integ/peering_commontopo/commontopo.go
test-integ/topoutil/fixtures.go
testing/deployer/sprawl/peering.go
testing/deployer/topology/ids.go

https://github.com/hashicorp/consul/pull/19504 promoted some tests authored in enterprise to also run in CE. Since they were not running in both variations a few places were still passing non-empty tenancy fields which does not work in v1.
Additionally these test failures were missed before that PR was merged because these tests are only run nightly.

test: fix some of the peering topology tests to safely run without tenancy in CE

---

.github/workflows/test-integrations.yml
Makefile
test-integ/peering_commontopo/README.md
test-integ/topoutil/images.go

```
$ make help | grep deployer
test-deployer    Run deployer-based integration tests (skipping peering_commontopo).
test-deployer-peering  Run deployer-based integration tests (just peering_commontopo).
```
It also creates a `make test-deployer-setup` which is like `make test-compat-integ-setup` without the envoy/dataplane steps, which are handled elsewhere with deployer.

test: update makefile to include ways to trigger deployer integration tests

---

website/content/docs/connect/gateways/api-gateway/configuration/gatewayclassconfig.mdx

Fixes typo in docs for `GatewayClassConfig`
Visual inspection
Typo can be found [here](https://developer.hashicorp.com/consul/docs/connect/gateways/api-gateway/configuration/gatewayclassconfig#matchprivilegedcontainerports)

Fix typo in GatewayClassConfig docs

---

test-integ/connect/snapshot_test.go
testing/deployer/sprawl/boot.go
testing/deployer/sprawl/catalog.go

For certain test scenarios, we need to detect if server agent can update the service endpoint after some instances are removed during relaunch (e.g.,[ the snapshot restore scenario](https://github.com/hashicorp/consul/blob/e5948e8eb4181011639b7f017fc0687135b286fa/test-integ/connect/snapshot_test.go#L197-L202)). In this case, the service instance needs to be removed from the catalog.
This PR adds the method of deregistering the services when a node is disabled during relaunch.

test/deployer: add the method of deregistering services

---

agent/proxycfg/manager.go
internal/mesh/proxy-tracker/proxy_tracker.go
lib/channels/deliver_latest.go

add DeliverLatest as common function for use by Manager and ProxyTracker

add DeliverLatest as common function for use by Manager and ProxyTracker Open

---

internal/catalog/catalogtest/run_test.go
internal/catalog/catalogtest/test_integration_v2beta1.go
internal/catalog/catalogtest/test_lifecycle_v2beta1.go
internal/resource/resourcetest/builder.go
internal/resource/resourcetest/client.go
test/integration/consul-container/test/catalog/catalog_test.go

As the V2 architecture hinges on eventual consistency and controllers reconciling the existing state in response to writes, there are potential issues we could run into regarding ordering and timing of operations. We want to be able to guarantee that given a set of resources the system will always eventually get to the desired correct state. The order of resource writes and delays in performing those writes should not alter the final outcome of reaching the desired state.
To that end, this commit introduces arbitrary randomized delays before performing resources writes into the `resourcetest.Client`. Its `PublishResources` method was already randomizing the order of resource writes. By default, no delay is added to normal writes and deletes but tests can opt-in via either passing hard …

Introduce randomized timings and reproducible randomization into controller integration tests.

---

website/content/docs/k8s/helm.mdx

This PR is the regeneration of the Helm docs with updated values from consul-k8s 1.3.0, released today.
Visual inspection
Generated from the 1.3.0 `values.yaml` [here](https://github.com/hashicorp/consul-k8s/blob/release/1.3.0/charts/consul/values.yaml)

Update Helm docs for consul-k8s 1.3.0

---

test-integ/catalogv2/explicit_destinations_l7_test.go
test-integ/catalogv2/explicit_destinations_test.go
test-integ/catalogv2/helpers_test.go
test-integ/catalogv2/implicit_destinations_test.go
test-integ/go.mod
test-integ/go.sum
test-integ/topoutil/asserter.go
test-integ/topoutil/asserter_blankspace.go
test-integ/topoutil/blankspace.go
test-integ/topoutil/fixtures.go
test-integ/topoutil/http2.go
testing/deployer/sprawl/internal/build/docker.go
testing/deployer/sprawl/internal/tfgen/gen.go
testing/deployer/topology/images.go
testing/deployer/topology/topology.go

This adds a deployer-based integration test verifying that a 90/10 traffic split works for: `HTTPRoute`, `GRPCRoute`, and `TCPRoute`.
Ordinarily we would use `fortio` to verify the destinations reached during the test, but there wasn't a good way to exploit its gRPC ping service to unearth the original app identity, so for now I wrote a quick server to reply in a protocol-specific way with a user-defined name that works for `http`, `http2`, `grpc`, and plain `tcp`: https://github.com/rboyer/blankspace

test: add a v2 container integration test of xRoute splits

---

website/content/docs/connect/config-entries/http-route.mdx
website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-k8s.mdx
website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-vms.mdx

Fixes some jwt docs for a typo in the external filter kind name and links between docs

Update links and fix route kind for APIGW JWT Docs

---

agent/grpc-external/services/resource/testing/testing.go
internal/catalog/internal/controllers/failover/controller_test.go
internal/resource/resourcetest/tenancy.go

- Updated controller_test.go to account for tenancy
- Manual Run
- CI pipeline

[NET-6356] Add tenancy to Failover Tests

---

.changelog/19594.txt
ui/packages/consul-nspaces/app/components/consul/nspace/selector/index.hbs
ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs
ui/packages/consul-ui/app/components/nav-selector/generic.hbs
ui/packages/consul-ui/app/components/nav-selector/index.hbs

When I was testing the sameness group stuff I saw that the namespaces blocking query was firing right away and timing out after a while. I looked back at what we hhad before and the requests would only load when they were in the DOM, and they were placed inside the old dropdown menu. I've since yielded a slot in the `NavSelector` to place the data sources so that they only request once you open the dropdowns.

ui: move queries for selectors within the dropdowns

---

internal/catalog/internal/controllers/nodehealth/controller_test.go
internal/catalog/internal/controllers/workloadhealth/controller_test.go
internal/catalog/internal/types/failover_policy_test.go
internal/mesh/internal/types/destination_policy_test.go
internal/mesh/internal/types/xroute_test.go
internal/multicluster/internal/controllers/exportedservices/controller_test.go
internal/multicluster/internal/types/computed_exported_services_test.go
internal/multicluster/internal/types/exported_services_test.go
internal/multicluster/internal/types/namespace_exported_services_test.go
internal/multicluster/internal/types/partition_exported_services_test.go
internal/resource/resourcetest/tenancy.go
version/versiontest/versiontest.go

This can help conditionally change test behavior if the test is executing in enterprise without the need to split the test with build tags.

test: add test helper to detect if the current build is enterprise

---

logging/logfile_bsd.go

Fixes:
```
make lint                                                                                                                                                                                                                                                                              ✔  17s  
--> Running golangci-lint (.)
logging/logfile_bsd.go:17:24: unnecessary conversion (unconvert)
return time.Unix(int64(createTime.Sec), int64(createTime.Nsec))
^
make: *** [lint/.] Error 1
```

unhack: fix broken `make lint` on macbooks

---

website/content/docs/k8s/helm.mdx

Sync docs for several recent changes to the Helm chart from `consul-k8s`.
Original PR: https://github.com/hashicorp/consul-k8s/pull/3180
I figure the ideal thing rather than backporting will be to run a sync for the active branches as well, since there's some divergence between the diffs on those.

[NET-6232] docs: Update consul-k8s Helm chart docs

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/install/ports.mdx

This fixes some of the admin partitions guide. It still does not work for Kind for a couple reasons:
1. we need to use the internal IP of the K8s API (not the external LoadBalanced one):
```
kubectl config view --output "jsonpath={.clusters[?(@.name=='${CLIENT_CONTEXT}')].cluster.server}"
```
2. we get TLS issues on the K8s server certs:
```txt
2023-11-14T02:56:54.305Z [ERROR] consul-server-connection-manager: ACL auth method login failed: error="rpc error: code = Unauthenticated desc = Post \"https://10.96.0.1/apis/authentication.k8s.io/v1/tokenreviews\": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")"
2023-11-14T02:56:54.305Z …
```

Fix parts of admin-partitions guide

---

.github/scripts/set_test_package_matrix.sh

CI currently specifies 12 runners, but 13 actually gets spun up in the logic to split the runners using `_nwise()` function.  This PR corrects that behavior.
[Previous runs in CI ](https://github.com/hashicorp/consul/actions/runs/6852852764) shows 13 jobs
[Run for this PR](https://github.com/hashicorp/consul/actions/runs/6857604553?pr=19620) show 12 jobs

fix runner count logic in set_test_package_matrix.sh from adding an additional runner

---

website/content/docs/ecs/deploy/manual.mdx
website/content/docs/ecs/deploy/terraform.mdx

'
Add `service:write` permissions to ACL token passed to the ECS controller

Fix ACL permissions for ECS controller

---

ui/packages/consul-ui/app/abilities/policy.js
ui/packages/consul-ui/app/components/consul/policy/list/index.hbs
ui/packages/consul-ui/app/helpers/policy/typeof.js
ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
ui/packages/consul-ui/mock-api/v1/acl/policies
ui/packages/consul-ui/mock-api/v1/acl/policy/_
ui/packages/consul-ui/tests/acceptance/dc/acls/policies/view-read-only.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/acls/policies/view-read-only-steps.js
ui/packages/consul-ui/tests/integration/helpers/policy/typeof-test.js

PR is manually created to backport https://github.com/hashicorp/consul/pull/18602
1. set up CONSUL_ACLS_ENABLE to 1 in session storage
2. set CONSUL_POLICY_COUNT = 10
3. go to Policies
4. log in with any securId
5. check list of items to see global-read-only policy
6. go to the policy details and check that form is non-editable
[JIRA](https://hashicorp.atlassian.net/browse/CC-5792)
[Figma](https://www.figma.com/file/oMJ1VqcRzb2EP1mqfaohDz/View-Builtin-Token?type=design&node-id=916-8806&mode=design&t=ZRNWWdS4Bb0fhced-0)

Backport/UI/feature/make global read only policy non editable/instantly hardy chamois 2

---

internal/mesh/internal/controllers/proxyconfiguration/controller_test.go

Made proxy cfg controller tests aware of different tenancies

Add tenancy tests for proxy cfg controller

---

.pre-commit-config.yaml
Makefile

This was intended to add `golangci-lint` as a precommit hook, but it takes way too long to run (see https://hashicorp.atlassian.net/browse/NET-6562 for the details).  Instead, I figured it was a good opportunity to codify some of the guidelines for adding hooks so that it doesn't turn into a dumping ground for "all the things".

unhack: add pre-commit guidelines

---

agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_test.go
internal/tenancy/internal/bridge/tenancy_bridge.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7678
NET-6335

resource: freeze resources after marked for deletion (4 of 5)

---

.github/workflows/go-tests.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
agent/config/runtime_test.go
agent/connect/ca/provider_vault_test.go
command/connect/envoy/exec_test.go
internal/resource/sort_test.go
internal/storage/inmem/backend_test.go
internal/storage/raft/conformance_test.go

When looking at the slowest tests based on P95, most of them are marked as skip when the -short flag is passed to the test.  We have done this on platform specific test runs like 32bit, arm, etc., but never on the main unit test runs.  
This PR puts in the same logic that skips test that are "marked as too slow" in branches outside of main and release branches.  It also tags any test as too slow that exceeds 30 seconds for P95 for the last 3 months on main in consul CE and enterprise.  I propose a similar policy and evaluation at the end of releases (as well as ad hoc) to move long running tests to be run less frequent...namely on integration to main or the release branch
Some of these are curious why they take so long, but that investigation is for another day.
*there is a bug in the …

Skip tests with p95 greater than 30 seconds outside of main and release branches.

---

.changelog/19666.txt
agent/acl_endpoint_test.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/structs/acl_templated_policy.go

- In [consul-k8s](https://github.com/hashicorp/consul-k8s/blob/f4ccbaa9bc9152722fdb8ff032220f1bc95475e2/control-plane/connect-inject/controllers/endpoints/endpoints_controller.go#L990) we query tokens by service name. with templated policies eventually replacing NodeIdentity and ServiceIdentity fields on token, we need a way to support service name queries based on templated policy. This PR adds support for that, there will be a follow up

[NET-6103] Enable query tokens by service name using templated policy

---

website/content/docs/connect/gateways/api-gateway/configuration/routetimeoutfilter.mdx

Manual backport of docs fix in this PR into 1.17 https://github.com/hashicorp/consul/pull/19601
[Original PR
](https://github.com/hashicorp/consul/pull/19601)
* [ X ] external facing docs updated

Timeout Docs Update (#19601)

---

agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_test.go
internal/resource/resource.go
proto-public/pbresource/resource.pb.go
proto-public/pbresource/resource.proto

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7804
NET-6556

resource: preserve deferred deletion metadata on non-CAS writes

---

ui/packages/consul-ui/tests/acceptance/dc/nodes/show.feature
ui/packages/consul-ui/tests/integration/utils/dom/event-source/callable-test.js

Remove tests which fails on `consul-enterprise` repo to unblock merges
[Draft pr ](https://github.com/hashicorp/consul-enterprise/pull/7850) in consul-enterprise to make sure that without the tests
Tickets to add the tests back are added: 
https://hashicorp.atlassian.net/browse/CC-6960
https://hashicorp.atlassian.net/browse/CC-6961

fix: remove 2 tests to unblock consul-enterprise merges

---

.changelog/19679.txt
command/acl/acl_helpers.go
command/acl/acl_test.go

This fix a panic in the CLI when deleting a policy using its name and that name do not exist on the server.
```
consul acl policy delete -namespace david-test -datacenter us-east-infra -name namespace-management
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1012db5]
goroutine 1 [running]:
github.com/hashicorp/consul/command/acl.GetPolicyIDByName(...)
/Users/dayachi/git/consul-enterprise/command/acl/acl_helpers.go:102
github.com/hashicorp/consul/command/acl/policy/delete.(*cmd).Run(0xc000d62050, {0xc000072180?, 0xffffffffffffffff?, 0x0?})
/Users/dayachi/git/consul-enterprise/command/acl/policy/delete/policy_delete.go:62 +0x155
github.com/mitchellh/cli.(*CLI).Run(0xc000fa3400) …
```

fix a panic in the CLI when deleting an acl policy with an unknown name

---

.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml

`gotestsum@v1.11.0` adds a new test output format called `github-actions` which is like `testname` but adds collapsable logging/output which helps scroll-ability of our current test outputs.
Our current copy-pasted default is `short-verbose` which many dislike due to its... verbosity. We end up scrolling through thousands of verbose logging output to find the actual `fail: ` line. It should be fine in 99% of cases to only output testnames unless there is an error or stdout lines
[Kapture 2023-11-20 at 09.10.43.webm](https://github.com/hashicorp/consul/assets/30640057/b61bb3ac-2229-4310-b2d3-1e5d62fc76ba)

Switch to github-actions format

---

.changelog/19663.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/telemetry-collector.golden
website/content/docs/connect/proxies/envoy.mdx

**Context**
We want to reduce the number of metrics processed by the Consul Telemetry Collector. 
By default, Envoy has a `stats_flush_interval` of 5 seconds ([docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto))
**Changes**
- For users that setup the consul telemetry collector, we default the `stats_flush_interval ` to 1 minute (60 seconds). **However, we avoid doing this override in 2 cases**:
- 1. They have a custom `envoy_stats_flush_interval`, we don't want to override their use case.
- 2. They have a custom stats sink: we don't want to impact their custom metrics processing. 
- A custom stats sink can be set in multiple ways: via the `envoy_statsd_url`, `envoy_dogstatsd_url` or `envoy_extra_stats_sinks_json`. In order to address all these …

Default "stats_flush_interval" to 1 minute for Consul Telemetry Collector

---

internal/go-sso/oidcauth/config.go
internal/go-sso/oidcauth/oidc.go

Remove old TODO comments and update remaining comments for clarity.
Cleanup from security review.
From [docs](https://developer.hashicorp.com/consul/docs/security/acl/auth-methods/oidc#oidc-configuration-troubleshooting):
> [BoundAudiences](https://developer.hashicorp.com/consul/docs/security/acl/auth-methods/oidc#boundaudiences) is optional and typically not required. OIDC providers will use the client_id as the audience and OIDC validation expects this.

[SECVULN-1532] chore: Remove TODO comments for OIDC/JWT auth

---

sdk/iptables/iptables.go

Add docs clarifying constraints on use and return values.
Clarify docs in response to security assessment informational finding.
* The implementation of `iptablesExecutor.Rules()` returns both rules that have and have not yet been applied
* `iptablesExecutor.ApplyRules()` does not clear out its commands list before returning, leading to misconfiguration (duplicate entries) when called multiple times

[SECVULN-1533] chore: Clarify iptables Provider interface docs

---

command/resource/helper.go

Add a string method to GVK to avoid print out the struct directly
* Before
`Error reading resources for type &{catalog v2beta1 Service}:`
* After
`Error reading resources for type catalog.v2beta1.Service:`

cli: add a string method to gvk struct

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.js

Backport for https://github.com/hashicorp/consul/pull/19660

Backport/UI/net 438 add ent version suffix/privately inspired wolf self

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.js

Backport for https://github.com/hashicorp/consul/pull/19660

chore: add suffix to consul version in sidenav

---

internal/tenancy/internal/controllers/common/common.go
internal/tenancy/internal/controllers/namespace/controller.go
internal/tenancy/internal/controllers/register_ce.go
internal/tenancy/tenancytest/namespace_controller_test.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7842
NET-5529

v2tenancy: namespace deletion using finalizers

---

.changelog/19728.txt
agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
agent/structs/acl_templated_policy_ce.go
agent/structs/acl_templated_policy_ce_test.go
agent/structs/acltemplatedpolicy/policies/ce/api-gateway.hcl
agent/structs/acltemplatedpolicy/schemas/api-gateway.json
api/acl.go
command/acl/templatedpolicy/formatter.go

- Add api gateway templated policy
- Will replace that policy in consul-k8s https://github.com/hashicorp/consul-k8s/pull/3132 
- Template tested through consul-ecs https://github.com/hashicorp/consul-ecs/pull/198/files 
- create a token with api gateway templated policy
```
consul acl token create -templated-policy "builtin/api-gateway"
AccessorID:       e7d5f058-881d-c218-a5f7-2e2586df2456
SecretID:         3b3dd7b4-ab57-2019-7f33-f6402299b7dc
Partition:        default
Namespace:        default
Description:
Local:            false
Create Time:      2023-10-25 13:33:56.826587 -0400 EDT
Templated Policies:
builtin/api-gateway
Datacenters: all
```
- read the token with `-expanded` flag to ensure the 
```
consul acl token read -accessor-id "e7d5f058-881d-c218-a5f7-2e2586df2456" -expanded …
```

NET-6251 API gateway templated policy

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
test-integ/peering_commontopo/ac7_2_rotate_leader_test.go

I noticed 7.2 was flaking pretty often. I did some timing of this section, and with N=5, found the following timing:
```
30s
2m30s
8m30s
30s
2m30s
```
(I only had 30s resolution for unrelated reasons.)
I don't know why there would be this much variability; that's for another day.
Based on #19724 just so I could run it manually.
https://github.com/hashicorp/consul/actions/runs/6974518632/job/18980327887?pr=19727 ✅

unflake peering_commontopo AC 7.2

---

.changelog/19735.txt
agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
api/acl.go
command/acl/templatedpolicy/formatter.go
command/acl/templatedpolicy/formatter_test.go
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/dns-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/node-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-server-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-server-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-server-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/service-templated-policy.pretty.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicyList/ce/list.json.golden

- Though the templated policy names are self explanatory for the most part, we thought it'd be a good idea to have a description that allows to make it easier for someone not as familiar with Consul to use them.
- This PR adds description to the templated policies
```
consul acl templated-policy read -name "builtin/dns"
Name:            builtin/dns
Description:     Gives the token or role permissions for the Consul DNS to query services in the network.
Input variables: None
Example usage:
consul acl token create -templated-policy builtin/dns
```

[NET-6249] Add templated policies description

---

.changelog/19679.txt
command/acl/acl_helpers.go
command/acl/acl_test.go

This is a backport of the fix introduced in https://github.com/hashicorp/consul/pull/19679
<details>
- f027d610149d7dbb0d486e92a3a1a55f4b948cc3 
</details>

[1.15.x backport] Fix panic policy delete 

---

.github/workflows/reusable-check-go-mod.yml

Today, we do not enforce a clean `go mod tidy` on submodules. This allows for drift and can eventually lead to `golangci-lint` failures, along with the obvious disadvantage of not having an up-to-date `go.mod`.
Enforce clean `go mod tidy` on all `go.mod` by using our make target rather than the direct root-level command.

ci: Run `go mod tidy` check on submodules

---

website/content/docs/k8s/helm.mdx

Sync docs for recent changes to the Helm chart from `consul-k8s`.
Updates docs for backport of https://github.com/hashicorp/consul-k8s/pull/3180 following https://github.com/hashicorp/consul/pull/19577. This is the only change that needed syncing on this branch.

[NET-6232] docs: Update consul-k8s Helm chart docs (1.1.x)

---

website/content/docs/k8s/helm.mdx

This reverts commit c4b3ca81d591fd44216a7fd627a0a0bc2901d0ea.
Docs should not have been updated until the next patch release.
Reverts change made in https://github.com/hashicorp/consul/pull/19699.

Revert "[NET-6232] docs: Update consul-k8s Helm chart docs (1.1.x) (#19699)

---

website/content/docs/k8s/helm.mdx

Sync docs for recent changes to the Helm chart from `consul-k8s`.
Updates docs for backport of https://github.com/hashicorp/consul-k8s/pull/3180 following https://github.com/hashicorp/consul/pull/19577.
Also includes another minor previous change that wasn't synced.

[NET-6232] docs: Update consul-k8s Helm chart docs (1.2.x)

---

agent/consul/testdata/v2-resource-dependencies.md
internal/mesh/internal/controllers/meshconfiguration/controller.go
internal/mesh/internal/controllers/meshconfiguration/controller_test.go
internal/mesh/internal/controllers/register.go
internal/mesh/internal/types/mesh_configuration.go
internal/mesh/internal/types/mesh_gateway.go
internal/mesh/internal/types/types.go

This adds a stub for the `MeshConfiguration` Consul controller.
There are not any testable changes. This adds simply a stub of the controller for us to add work into.

[NET-6420] Add MeshConfiguration Controller stub

---

website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx

Add further examples and tips for locality-aware routing configuration, observability, and troubleshooting.
@trujillo-adam would appreciate a quick look at the formatting and prose in case I can align better w/ standards, if you have time.
Enhance docs with examples and testing/troubleshooting advice.
I've hand-tested a local `k3d` cluster with manually set localities and observed the expected changes in endpoints config.

[NET-5916] docs: Add locality examples and troubleshooting

---

internal/mesh/internal/controllers/sidecarproxy/controller_test.go

[1.17.x] Move test setup out of subtest

---

internal/mesh/internal/controllers/sidecarproxy/controller_test.go

We've observed an occasional flake ([example](https://github.com/hashicorp/consul/actions/runs/6983670981/job/19005259553#step:13:36428)) in this test where some state check fails. Adding in some wait wrappers to these state checks will hopefully address the issue, assuming it is a simple flake.
_Reviewer note: I'd appreciate 👀 on my approach here since I've not touched these tests much before this change._
Use existing helpers to wrap state checks in waits, rather than relying on any detected resource version change as a signal that the expected state is present.
Ran ~300x locally with no observed flakes (though TBF, I was unable to repro the flake locally and suspect it only occurs under heavy resource constraints, e.g. on taxed CI runners)

[NET-6725] test: Address occasional flakes in sidecarproxy/controller_test.go

---

website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx

Follow-up to #19605 review.
See https://github.com/hashicorp/consul/pull/19605#pullrequestreview-1753317957 for more context.
This is a minimal change suggested as a potential alternative to moving this doc into its own section. If preferred, we can move the doc instead; opening PR to prompt that decision. Also happy to merge this as-is and consider a later follow-up.

docs: Rename locality docs observe section to verification

---

internal/mesh/internal/controllers/sidecarproxy/controller_test.go

Manual backport of https://github.com/hashicorp/consul/pull/19760
Original backport PR (failed due to intervening test changes on `main`): https://github.com/hashicorp/consul/pull/19770
<details>
- 5be0c8f89b809b0723677a1ce4f412646315265a 
</details>

Backport of [NET-6725] test: Address occasional flakes in sidecarproxy/controller_test.go into release/1.17.x

---

website/content/docs/enterprise/fips.mdx

Updates FIPS documentation by adding a section about Cluster Peering on the page. 
N/A
None
* [N/A] updated test coverage

Docs: FIPS - add cluster peering info

---

internal/resource/resourcetest/client.go
test-integ/Makefile
test-integ/README.md
test-integ/connect/snapshot_test.go
test-integ/tenancy/client.go
testing/deployer/sprawl/internal/tfgen/agent.go
testing/deployer/sprawl/internal/tfgen/nodes.go
testing/deployer/sprawl/sprawl.go
testing/deployer/topology/default_versions.go
testing/deployer/topology/images.go
testing/deployer/topology/topology.go
testing/deployer/update-latest-versions.sh

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/7912
After removing the ENT bits, all that is left is support for the v2tenancy feature flag.
https://hashicorp.atlassian.net/browse/NET-6587

resource: add v2tenancy feature flag to deployer tests

---

.github/workflows/build.yml

This PR is intended to avoid a [production incident](https://github.com/hashicorp/releng-support/issues/123) where there are duplicate tags (auto-assigned) to UBI images. The entire issue is described [here](https://github.com/hashicorp/crt-workflows-common/pull/407#issue-1999804835), and can be avoided by building `UBI`s (intended for both `Dockerhub` and `Redhat`) in one step.

Remove Duplicate UBI Tags

---

.github/workflows/nightly-test-integ-peering_commontopo.yml

Currently, upload test results step is skipped if there is a failure in one of its preceding steps (this includes tests failure). We should ideally upload the test results for failed tests too.
If a step fails before the workflow reaches the tests execution step, then the upload test results will fail because of unavailability of results.xml file
https://github.com/hashicorp/consul/actions/runs/7042749371 workflow demonstrating the positive and negative scenario

NET-6692: Ensure 'upload test results' step is always run

---

.github/workflows/go-tests.yml

- Skip notifications for cancelled workflows. Cancellation can be manual or caused by branch concurrency limits.
- Fix multi-line JSON parsing error by only printing the summary line of the commit message. We do not need more than this in Slack.
- Update Slack webhook name to match purpose
- Previous: `slack github nightly integration test`
- Now: [`Tests - protected branches`](https://app.slack.com/workflow-builder/EF1GCKJNM/workflow/Wf068HTD43AP)
- I've added the new webhook secret to `consul` and `consul-enterprise`, so this should work immediately.
This only addresses the workflow for pushes to protected branches (the only one that runs outside a schedule today). A separate change would be needed to make this form of the job reusable and apply the same fix in nightly integration …

ci: fix test failure Slack notifications

---

website/content/docs/k8s/multiport/reference/trafficpermissions.mdx

The `portNames` refers to the exposed pods of Kubernetes pod since a service can point to multiple pods.

doc: clarify the portNames used in trafficpermission V2

---

.changelog/19827.txt
agent/acl_endpoint_test.go
agent/structs/acl_templated_policy.go
agent/structs/acl_templated_policy_ce.go
agent/structs/acltemplatedpolicy/policies/ce/nomad-client.hcl
api/acl.go
command/acl/templatedpolicy/formatter.go
command/acl/templatedpolicy/formatter_test.go
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.json.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.pretty-meta.golden
command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.pretty.golden

- Adding nomad client templated policy 
```
consul acl token create -templated-policy "builtin/nomad-client"
```
- [Testing repo (nomad + consul)](https://github.com/hashicorp/consul-gateway-on-nomad/blob/main/nomad-client-policy.hcl)

[NET-6251] Nomad client templated policy

---

.changelog/19721.txt
agent/consul/client.go

The client.rpc metric now excludes internal retries for consistency with client.rpc.exceeded and client.rpc.failed. All of these metrics now increment at most once per RPC method call, allowing for accurate calculation of failure / rate limit application occurrence.
Additionally, if an RPC fails because no servers are present, client.rpc.failed is now incremented.
Note: The client.rpc.failed metric used to increment on internal retries as well, but that was changed in [this commit](https://github.com/hashicorp/consul/commit/c48120d005539b687391b6861f24c13d553f5b05) (CC @kisunji).
Manual testing conducted by reviewer (@rboyer).
1. Set up Consul cluster.
2. Run `curl -sL -XPUT 172.17.0.3:8500/v1/catalog/register -d'{"Node":"foo", "Address":"4.4.4.4", "ID":"blah"}'`. Note: this should …

improve client RPC metrics consistency

---

.changelog/19840.txt
.github/workflows/build.yml
build-support/docker/Build-Go.dockerfile

- Bump go version to `1.20.12` to fix various cves
- CVE-2023-45283: path/filepath: recognize \??\ as a Root Local Device path prefix (Windows)
- CVE-2023-45284: recognize device names with trailing spaces and superscripts (Windows)
- CVE-2023-39326: net/http: limit chunked data overhead
- CVE-2023-45285: cmd/go: go get may unexpectedly fallback to insecure git

[NET-6650] Bump go version to 1.20.12

---

test-integ/upgrade/usage_profiles/sd_wan_segments_test.go
testing/deployer/go.mod
testing/deployer/sprawl/acl.go
testing/deployer/sprawl/boot.go
testing/deployer/sprawl/internal/tfgen/agent.go
testing/deployer/sprawl/sprawl.go
testing/deployer/topology/images.go

NET-6643: upgrade test from 1.10 to 1.15 (lts) of a single cluster

---

.changelog/19663.txt
.github/workflows/pr-labeler.yml
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/telemetry-collector.golden
website/content/docs/connect/proxies/envoy.mdx

Backport changes from https://github.com/hashicorp/consul/pull/19663
…ctor (#19663)
* Set default of 1m for StatsFlushInterval when the collector is setup
* Add documentation on the stats_flush_interval value
* Do not default in two conditions 1) preconfigured sinks exist 2) preconfigured flush interval exists
* Fix wording of docs
* Add changelog
* Fix docs
(cherry picked from commit bfb3a43648634e117c8405d6a6e3cc837fb8e3dc)

Backport stats flush interval 1.16.x

---

.changelog/19821.txt
command/peering/exportedservices/exported_services.go
command/peering/exportedservices/exported_services_test.go
command/peering/peering.go
command/registry.go
website/content/commands/peering/exported-services.mdx
website/content/commands/peering/index.mdx
website/data/commands-nav-data.json

This PR adds a new cli command to list exported services to a peer.
command: `consul peering exported-services -name cluster-02`
- Integration tests added
- make dev and run the commands as described in the docs.

NET-6784: Adding cli command to list exported services to a peer

---

internal/tenancy/internal/bridge/tenancy_bridge.go
internal/tenancy/internal/bridge/tenancy_bridge_ce.go

I was running into some flakey integration tests where I was getting partition or namespace not found errors. It turns out that the integration tests were attempting resource writes prior to the creation of the v2 partition/namespace resources. 
This PR fixes that so that the default namespace always exists so that writes into the default namespace are successful even before we create the resource.
Existing flakey tests pass.

Ensure that the default namespace always exists even prior to resource creation

---

.changelog/19829.txt
agent/consul/discoverychain/compile.go
agent/consul/discoverychain/compile_test.go
agent/consul/discoverychain/gateway_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/proxycfg/manager_test.go
agent/proxycfg/testing_mesh_gateway.go
agent/proxycfg/testing_tproxy.go
agent/proxycfg/testing_upstreams.go
agent/structs/config_entry.go
agent/structs/discovery_chain.go
agent/xds/resources_test.go

This remove deserializing the `map[string]string` inside ProxyConfig from the hot code path of compiling disco-chains and moving it to be done when `ProxyDefaults` are written.
The rational behind this is that `ProxyDefaults` should not be written as often as the disco-chain compilation happen (on every change on a proxy).
modified test to verify that on proxy-defaults write the right field get populated.

parse config protocol on write to optimize disco-chain compilation

---

test/integration/consul-container/test/gateways/terminating_gateway_test.go

TLDR `retry.Timer` types cannot be reused.
Fixed the flakes

Fix a test flake where a retry timer was being reused causing tests after the first to exit early

---

.github/workflows/go-tests.yml

Follow-up to https://github.com/hashicorp/consul/pull/19838
To ensure that shell code cannot be injected, capture the commit message in an env var, then format it as needed.
Also fix several other issues with formatting and JSON escaping by wrapping the entire message in a `toJSON` expression.
Another advantage of this change is it's easier to edit the message without accidentally breaking formatting.
Tested here: https://github.com/hashicorp/consul/actions/runs/7144725767

ci: sanitize commit message for Slack failure alerts

---

.github/workflows/build.yml

- Fixing CE to ent merge conflicts moving forward by separating go version to a separate line for smoother go version bumps

[NET-6842] splitting go version on different lines

---

internal/multicluster/exports.go
internal/multicluster/internal/controllers/exportedservices/controller_test.go
internal/multicluster/internal/types/types.go
internal/multicluster/internal/types/types_ce.go

1. Move registering enterprise types to the common register function so that tests could use them too.
2. Refactor some exported service controller tests to use the existing function.

Move enterprise multicluster types to Register function 

---

.changelog/19907.txt
ui/packages/consul-ui/app/services/repository.js

If you visited the services page, then a peers imported services list, then back to the services page it would only display the services imported by the peer. It seems like this issue had to do with manual reconciling that was happening when we queried all services for a peer. When you first visit the services list page we set up a Blocking query that is stored as a source in a service. The first visit queries the services and stores this source. When you visit a peers imported services it [queries all the services for that peer.](https://github.com/hashicorp/consul/blob/e13fbc743ea490135e1c182d5c4749e8d8fe673a/ui/packages/consul-ui/app/services/repository/service.js#L33) Part of that process involves [calling](https://github.com/hashicorp/consul/blob/e13fbc743ea490135e1c182d5c4749e8d8fe67 …

NET-6900: stop reconciling services when peering is enabled

---

.github/workflows/nightly-test-integrations.yml
.github/workflows/test-integrations-windows.yml
.github/workflows/test-integrations.yml

This changes were missing when porting envoy 1.28 update from ENT to CE.

fix actions to no longer use envoy 1.24.x to match supported versions.

---

website/content/api-docs/peering.mdx

This PR updates the API docs for peering read and list APIs.
The changes were added in [PR1](https://github.com/hashicorp/consul/pull/14747) and [PR2](https://github.com/hashicorp/consul/pull/14889)
NA

NET-6785: updating peering docs to include stream status and remote data

---

website/content/docs/agent/telemetry.mdx

Update Server Workload telemetry section to demonstrate explicitly enabling metric emission as they're [default disabled](https://github.com/hashicorp/consul/blob/f5bf256425e33c0da805eda6a2fc5ea05100d491/agent/config/builder.go#L2763C1-L2763C1).
Customers need to be aware that if investigating server workload via metrics this needs to be explicitly enabled.
* Run any support version of Consul or Consul Enterprise
* Enable telemetry in agent config via`prometheus_retention_time` 
* Observe default blocked prefixes showing `consul.rpc.server.call`:
```shell
$ consul agent -dev -node localhost -client 127.0.0.1 -hcl 'telemetry { prometheus_retention_time = "10m" }'
$ curl -s localhost:8500/v1/agent/self | jq -r '.DebugConfig.Telemetry.BlockedPrefixes' …
```

Update telemetry.mdx RPC Metrics

---

website/content/docs/connect/config-entries/service-defaults.mdx

Noticed a typo in the docs, fixing it
:eyes:
[Location of typo in docs](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-defaults#partition)

Fix typo in service-defaults documentation

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/nightly-test-integrations.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations-windows.yml
.github/workflows/test-integrations.yml

Due to the unintuitive behavior of GHA w.r.t. implicit status check `success()`, test results were only being uploaded on success (failures presumably came from retried tests that passed).
Example skip on `main`: https://github.com/hashicorp/consul/actions/runs/7214020207/job/19655377560#step:13:34655

ci: upload test results to DataDog on test failure

---

.changelog/_7773.txt
agent/consul/prepared_query_endpoint_test.go

Note that this is simply some CE test file changes needed for the corresponding ENT PR.
This commit fixes an issue where the partition was not properly set on the peering query failover target created from sameness-groups. Before this change, it was always empty, meaning that the data would be queried with respect to the default partition always. This resulted in a situation where a PQ that was attempting to use a sameness-group for failover would select peers from the default partition, rather than the partition of the sameness-group itself.

Fix bug with prepared queries using sameness-groups.

---

internal/mesh/internal/controllers/sidecarproxy/controller.go
internal/mesh/internal/controllers/sidecarproxy/controller_test.go

The `sidecarproxy.Controller` should skip `Workload` resources with a `gateway-kind` specified in the resource metadata. The forthcoming `gatewayproxy.Controller` will be responsible for managing these.
When combined with https://github.com/hashicorp/consul-k8s/pull/3365, the sidecar proxy controller should skip any Workloads created for a `MeshGateway` when `meshGateway.enabled=true` and `experiments: [resource-apis]` in values.yaml.

NET-6663 Modify sidecarproxy controller to skip xGateway resources

---

agent/consul/server_metadata.go
agent/consul/server_metadata_test.go

Remove `os.O_TRUNC` when agent opens `server_metadata.json`. This flag seems redundant since we will write the new timestamp to the file immediately. In case the agent crashes in-between `OpenServerMetadata` and `WriteServerMetadata`, the `server_metadata.json` becomes empty, leading to erroneous state where agent can't be started 
An alternative way is to continue the agent if  `server_metadata.json` is empty, but this may cause a situation where a very old agent joins a cluster.
Fix: https://github.com/hashicorp/consul/issues/19720
1. Start an agent
2. Stop agent
3. Remove the content in `server_metadata.json`
4. Agent can't be started again
```
==> Log data will now stream in as it occurs:
2023-12-13T16:11:42.763-0500 [WARN]  agent: BootstrapExpect is set to 1; this is the same as …
```

agent: prevent empty server_metadata.json

---

.changelog/19992.txt
agent/proxycfg/testing_upstreams.go
agent/xds/proxystateconverter/routes.go
agent/xds/routes.go
agent/xds/testdata/clusters/connect-proxy-with-chain-and-splitter.latest.golden
agent/xds/testdata/clusters/ingress-with-chain-and-splitter.latest.golden
agent/xds/testdata/endpoints/connect-proxy-with-chain-and-splitter.latest.golden
agent/xds/testdata/endpoints/ingress-with-chain-and-splitter.latest.golden
agent/xds/testdata/routes/connect-proxy-with-chain-and-splitter.latest.golden
agent/xds/testdata/routes/ingress-with-chain-and-splitter.latest.golden

Adds the ability to disable request and idle timeouts in a service router and service resolver.
*Previous Behavior*:
user sets 0s or doesn’t set anything -> results in envoy defaults of 15s (requestTimeout) or 1hr (idleTimeout)
user sets >0s -> results in setting that same value in envoy
*Behavior with this change*:
user sets -1s -> results in setting 0s in envoy (disabling the timeout)
user sets 0s or doesn’t set anything -> result in envoy defaults of 15s or 1hr
user sets >0s ->  results in setting that same value in envoy
* Made changes to xds/routes.go and proxystateconverter/routes.go to support this
* Adds to the chain-with-splitter test cases to test the timeout (picked an arbitrary case with disco chains to add coverage for the timeouts) …

[NET-5455] Allow disabling request and idle timeouts with -1 in service router and resolver

---

.github/workflows/security-scan.yml
.release/security-scan.hcl
scan.hcl

* Re-enable `binary` Go Modules + secrets security scans to block releases automatically in CRT on failure 
* Previously disabled in the following PRs; all prior issues appear to now be resolved:
* https://github.com/hashicorp/consul/pull/13614
* https://github.com/hashicorp/consul/pull/12281
* https://github.com/hashicorp/consul/pull/12275
* I also re-enabled secrets in the `container` scans because that seemed like an obvious opportunity
* Introduce PR and merge scans of the repository on `main` and `release/**` branches
* The goal here is to increase visibility of un-triaged scan results before they block a release; doing so requires scanning more than our [nightly run on `main`](https://github.com/hashicorp/security-scanning/blob/17ff72eb77354fc66cdaa2edcb7c050e3f09c756/.github/workflo …

[NET-6969] security: Re-enable Go Module + secrets security scans for release branches

---

internal/mesh/internal/controllers/meshgateways/controller.go

Create a name-aligned `Service` resource when reconciling a `MeshGateway` resource.
The `Service` has an owner reference added to it indicating that it belongs to a MeshGateway.

[NET-6899] Create name-aligned Service when reconciling MeshGateway resource

---

.changelog/20014.txt
Dockerfile

- Dockerfile: bump up to `ubi-minimal:9.3` to remediate vulnerabilities. The current `ubi-minimal:9.2` image is not actively maintained and CVEs fixes are not backported.

Dockerfile: bump up to `ubi-minimal:9.3`

---

.changelog/20010.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/testdata/envoy-readiness-probe.golden
command/connect/envoy/testdata/ingress-gateway-address-specified.golden
command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway.golden
command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
command/connect/envoy/testdata/prometheus-metrics.golden
test/integration/connect/envoy/main_test.go

NET-6942 - Replace usage of deprecated Envoy field envoy.config.cluster.v3.Cluster.http_protocol_options.

---

agent/consul/testdata/v2-resource-dependencies.md
internal/controller/dependencies.go
internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
internal/mesh/internal/controllers/gatewayproxy/controller.go
internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher.go
internal/mesh/internal/controllers/register.go
internal/mesh/internal/types/decoded.go

This PR creates the `gatewayproxy.Controller`, analogous to the `sidecarproxy.Controller` but designed to created `ProxyStateTemplate` (PST) resources for xGateways. It relies on `gateway-kind` being set in the metadata of the `Workload` that the PST is being created for.
#19902 introduced logic to have the sidecar proxy controller skip workloads with this piece of metadata so that the two controllers will not be fighting to write the same PST.

[NET-6426] Add gateway proxy controller that generates empty proxy state template

---

internal/resource/mappers/selectiontracker/selection_tracker.go

We are seeing the following panics in CI:
```
Error: sul-server-0-nckhszq0l ~~ 2023-12-21T21:08:23.587Z [ERROR] agent.controller-runtime: controller panic: controller=consul.io/sidecar-proxy-controller managed_type=mesh.v2beta1.ProxyStateTemplate panic="runtime error: invalid memory address or nil pointer dereference"
dc1-consul-server-0-nckhszq0l ~~ github.com/hashicorp/go-hclog.Stacktrace
dc1-consul-server-0-nckhszq0l ~~ 	/home/runner/go/pkg/mod/github.com/hashicorp/go-hclog@v1.5.0/stacktrace.go:51
dc1-consul-server-0-nckhszq0l ~~ github.com/hashicorp/consul/internal/controller.(*controllerRunner).handlePanic.func1
dc1-consul-server-0-nckhszq0l ~~ 	/home/runner/work/consul/consul/internal/controller/runner.go:254
dc1-consul-server-0-nckhszq0l ~~ runtime.gopanic …
```

NET-7025 - ci: test-integrations failures in compatibility tests. panics occuring in selectionTracker.TrackIDForSelection

---

.changelog/20012.txt
agent/envoyextensions/builtin/lua/lua.go
agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden

This approach has ben available [since Envoy v1.23.0](https://www.envoyproxy.io/docs/envoy/v1.23.0/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-lua).

NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code

---

.changelog/20012.txt
agent/envoyextensions/builtin/lua/lua.go
agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden

Manual backport of https://github.com/hashicorp/consul/pull/20012

Backport into 1.16 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code

---

.changelog/20012.txt
agent/envoyextensions/builtin/lua/lua.go
agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden

Manual backport of https://github.com/hashicorp/consul/pull/20012

Backport into 1.17 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code

---

.github/workflows/security-scan.yml

We've noticed runners appearing to become resource-starved during heavy CI traffic. While we should try to prevent this by limiting the scanner's CPU consumption, increasing the runner size should help in the interim.
Follow-up to https://github.com/hashicorp/consul/pull/19978

ci: increase runner size for security scans

---

ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature

Duplicate for the pr: https://github.com/hashicorp/consul/pull/19927

fix: add test which has been removed for metrics to unblock CI

---

.changelog/20012.txt
agent/envoyextensions/builtin/lua/lua.go
agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden

Manual backport of https://github.com/hashicorp/consul/pull/20012

Backport into 1.15 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code

---

.github/workflows/nightly-test-integrations.yml

The upgrade test failed due to the envoy config of the latest version of the consul. When doing upgrade test, we should use the envoy version that is supported by both versions.
This PR fixes the version in CI and adds some explanation to the version variable.
Please see the [passed run](https://github.com/hashicorp/consul/actions/runs/7392008723/job/20109849070).

Fix upgrade test envoy version

---

website/content/docs/services/configuration/services-configuration-reference.mdx

I'm looking into the DNS code, and I noticed a couple of issues with the docs on weights:
* AFAICT, there is no `critical` field for the DNS `weights`
* The phrasing is wrong about instances serving DNS requests. A DNS SRV query goes to a consul agent and lists a bunch of instances. Each instance in the list has a single weight. Consul's responsibility is only to pass along the correct weight in the DNS request based on the instance health. It's up to the DNS consumer to consider the weights for load-balancing purposes.

docs: remove unsupported critical flag from DNS weights

---

agent/agent.go
agent/consul/server_metadata.go

This is a follow-up PR to #19935. The previous PR doesn't solve the problem entirely since failure may occur if agent crashes mid-write then the file is partial.
This PR uses the [safeio](https://pkg.go.dev/github.com/rboyer/safeio)'s write, commit, and close to write the file atomicly.

Use safeio to write server metadata file

---

website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/index.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/replication-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx
website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx

There was feedback from our Support team about customers facing an issue following the documentation from the [Vault for Consul: System integration](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/systems-integration) into the [Vault for Consul: Data integration](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/data-integration). The former defines a `consul`-named Vault secret engine, but the latter runs commands and config against a `secrets`-named Vault secret engine - no doubt a leftover from times where the default secret engine from running Vault in `-dev` mode was used to showcase functionality in the docs.
Furthermore, because of the secret engine name `consul`, the customers were confused and expected the secret …

Backport of docs/consul: rename the Vault secret engine for Consul integration into release/1.17.x

---

website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/index.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/replication-token.mdx
website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx
website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx

There was feedback from our Support team about customers facing an issue following the documentation from the [Vault for Consul: System integration](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/systems-integration) into the [Vault for Consul: Data integration](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault/data-integration). The former defines a `consul`-named Vault secret engine, but the latter runs commands and config against a `secrets`-named Vault secret engine - no doubt a leftover from times where the default secret engine from running Vault in `-dev` mode was used to showcase functionality in the docs.
Furthermore, because of the secret engine name `consul`, the customers were confused and expected the secret …

Backport of docs/consul: rename the Vault secret engine for Consul integration into release/1.15.x

---

agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

This is an attempt to set up a testing strategy for the v2 dns work.  The majority of the v2 dns tests run a server agent and assert behavior without knowing the inner workings / implementation of the dns code.  This sets up the ability to take the same tests and just change the configuration of the test set up but still use the same actions and assertions.
This PR could be the first step of a testing and implementation strategy that looks like this:
1. **Configure the DNS test to be able to run a matrix based on DNS versions and catalog versions, but still only running DNS v1 tests.  (This PR)**  
- at this stage, we would have confidence that we have a path to best confirm that the v2 implementation of dns against both v1 and v2 catalog maintains the functionality of dns v1 against v …

Make DNS test run across a matrix of dns and catalog versions.

---

ui/packages/consul-ui/tests/acceptance/dc/nspaces/manage.feature
ui/packages/consul-ui/tests/acceptance/dc/services/dc-switch.feature

Fixes the dc-switch test. The dropdown didn't close and so when we went to reopen it it would then close. [This fix is also in an existing backport](https://github.com/hashicorp/consul/pull/20125) so no need to backport it. 
Fixes the same issue in the nspaces test.

fix: stop re-clicking dc dropdown in dc-switch test

---

agent/config_endpoint_test.go
agent/consul/intention_endpoint_test.go
agent/consul/leader_test.go

This fixes some tests that were broken, but not caught, due to the CICD pipeline only running a subset of the overall tests on PRs.

Fix broken tests.

---

proto-public/pbmulticluster/v2beta1/exported_services_consumer.pb.go
proto-public/pbmulticluster/v2beta1/exported_services_consumer.proto

Kubebuilder validation doesn't handle proto `oneof` fields which generate Go bindings with no `json` tag.
This set of `kubebuilder` annotations will override the inspections when generating CRD manifests so that everything works as expected in consul-k8s.
This is being tested as part of https://github.com/hashicorp/consul-k8s/pull/3458, where you'll find testing instructions.
N/A

[NET-7106] Add kubebuilder validation annotations to ExportedServicesConsumer proto

---

test-integ/topoutil/asserter.go
test-integ/upgrade/l7_traffic_management/common.go
test-integ/upgrade/l7_traffic_management/resolver_test.go
test/integration/consul-container/libs/assert/envoy.go
test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go

This ticket adds a new test TestTrafficManagement_ResolverDefaultSubset_Agentless in the series for l7 traffic management
Add service resolver subsets defaulting the subset to v2. Verify the traffic is routing to default v2 subset. The behaviour should remain intact after the upgrade too.
Ran the workflow https://github.com/hashicorp/consul/actions/runs/7299031468 against branch [NET-6813-add-resolver-test](https://github.com/hashicorp/consul/tree/NET-6813-add-resolver-test) which includes TestTrafficManagement_ResolverDefaultSubset_Agentless from the PR
upgrade/l7_traffic_management.TestTrafficManagement_ResolverDefaultSubset_Agentless from 1.16 to latest: [Link](https://github.com/hashicorp/consul/actions/runs/7299031468/job/19891094038#step:7:52) …

NET-6813: adding resolver default subset test in agentless upgrade test

---

proto-public/.copywrite.hcl
troubleshoot/ports/hostport.go
troubleshoot/ports/troubleshoot_ports.go
troubleshoot/ports/troubleshoot_ports_test.go
troubleshoot/ports/troubleshoot_protocol.go
troubleshoot/ports/troubleshoot_tcp.go

Description
Automated backport https://github.com/hashicorp/consul/pull/20145 failed, so this is the manual backport.
Original PR on main: https://github.com/hashicorp/consul/pull/20143

license: MPL'ify proto-public (manual backport for 1.16.x)

---

.github/workflows/go-tests.yml
agent/consul/operator_backend_test.go
lib/testhelpers/testhelpers.go

We are reverting the change where we skip slow in the main go-tests workflow for CE and Enterprise.  The motivations for reverting this change is that we have found an introduced CI failure that has existed in main and it was not detected.  
This failing test going unnoticed is an indication that we don't currently have the processes and responsibility in place to delay these tests to be run after they are already merged.  Consul is a complex product with many edge cases.  We also need to have confidence that our test coverage is being asserted properly and timely so that we do not have delayed detection of failures.
We are reverting this change based on the idea that the original motivations below were to try to address developer toil with flakes and timely feedback from our CI pipeline, …

remove the skipping of slow tests in go-tests-ce and go-test-enterprise

---

internal/multicluster/internal/controllers/exportedservices/expander/expander_ce/expander.go

Sorts the list of peers in exported services expander to make sure we always return back a deterministic result. This will avoid any flakiness in tests with the consumers that rely on this method.

Sort peer list in expander

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.17.x.yml

Even though these files aren't used, adding them prevents backport failures for common changes that are backported n-2 versions.
Follow-up to https://github.com/hashicorp/consul/pull/20160#pullrequestreview-1816200322

chore: improve CI backports by backporting new workflows (1.17)

---

.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/reusable-dev-build-windows.yml
.github/workflows/test-integrations-windows.yml

Even though these files aren't used, adding them prevents backport failures for common changes that are backported n-2 versions.
Follow-up to https://github.com/hashicorp/consul/pull/20160#pullrequestreview-1816200322

chore: improve CI backports by backporting new workflows (1.16)

---

agent/agent.go
agent/agent_endpoint.go

To fix an issue displaying the current reloaded config in the `v1/agent/self` endpoint #18681 caused the agent's internal `config` struct member to be deepcopied and replaced on reload.
This is not safe because the field is not protected by a lock, nor should it be due to how it is accessed by the rest of the system.
This PR does the same deepcopy, but into a new field solely for the point of capturing the current reloaded values for display purposes. If there has been no reload then the original config is used.

agent: remove data race in agent config

---

agent/dns.go

The DNS code is hard to follow and there are a few low hangind changes that can be made to make the various functions easier to remember.
- add docstrings where missing
- the DNS server has a processing flow from the dispatch function that has these responsibilities and the function have been renamed to reflect it:
- **handle** the query from dispatch based on the type (changes here also help with confusing word reversals in functions such as `nodeLookup()` vs `lookupNode()`.
- `lookupService()` becomes `handleServiceQuery()`
- `lookupNode()` becomes `handleNodeQuery()`
- `lookupPreparedQuery()` becomes `handlePreparedQuery()` 
- **lookup** the Consul catalog data
- no changes here 
- **make** dns RR and SOA records from consul data
- `nodeServiceRecords()` becomes …

v1 dns - add doc strings for functions and update function names to be consistent and more descriptive.

---

website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx

A simple fix for a typo. The yaml file is targeted at `dc2` and should point to the local `partition-1`; as well as the remote `partition-1` and `partition-2` from `dc1`.
None

docs: fix partition target in samenessgroups

---

agent/acl_endpoint_test.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/testing.go
agent/metrics_test.go
agent/rpc/peering/service.go
agent/rpc/peering/service_test.go
agent/testagent.go

This PR fixes various test flakes / failures. Notably, it introduces a new check to test agent initialization that will wait for the bootstrap process to complete successfully before unblocking (which I suspect was causing a large number of flakes in tests globally).
It appears that there may have been a race condition in some of the peering state store logic due to the object not being cloned before mutation, which was flagged in tests. It doesn't appear to be a code path that would be encountered outside of our tests (which inserts partial data).

Various race condition and test fixes.

---

command/resource/client/grpc-config.go
command/resource/client/grpc-config_test.go
command/resource/client/grpc-flags.go
command/resource/client/grpc-flags_test.go

In this PR, we add the ACL `token` and `tokenFile` fields into GRPC config.
Notice the field of `tokenFile` takes precedence over the `token` field.

add acl token

---

grafana/consul-k8s-control-plane-monitoring.json

To get disk-io and disk usage of consul server pods and visualise them in the grafana dashboard
disk usage metrics is the sum of all containers in the cluster. There is no way to get disk usage of a specific pod/container using cAdvisor
- Bring up infra either [locally](https://github.com/hashicorp-education/learn-consul-get-started-kubernetes/tree/main/self-managed/local) using kind or on AWS using [consul-test-infra](https://github.com/hashicorp/consul-test-infra/blob/main/docs/consul-load-test-steps.md) repo
- Import the grafana dashboard from this PR
- You should be able to see new panels related to disk-IO and disk usage under "Resource Utilization (consul-servers)" section in grafana dashboard

NET-6862: adding disk-io and disk usage metrics to k8s grafana dashboard

---

agent/consul/server.go
agent/hcp/client/http_client.go
agent/hcp/client/http_client_test.go
agent/hcp/client/metrics_client.go
agent/hcp/client/metrics_client_test.go
agent/hcp/config/config.go
agent/hcp/config/mock_CloudConfig.go
agent/hcp/deps.go
agent/hcp/manager.go
agent/hcp/manager_test.go
agent/hcp/telemetry/otel_exporter.go
agent/hcp/telemetry_provider.go
agent/hcp/telemetry_provider_test.go

This PR adds support to initialize the HCP metrics sink without an HCP configuration and to then later update the sink with the HCP config at runtime in the HCP manager. The purpose of this change is to eventually support initiating the linking process via an API request, where that API request will start the HCP manager.
This PR is best viewed commit-by-commit. The general strategy is to add update methods to the HCP telemetry config provider and then call those update methods from the HCP manager.
Changes so that the HCP Telemetry Provider can fetch the config from HCP:
1. Remove the requirement to set the HCP client on the HCP telemetry provider and handle the case when it’s unset.
2. Save the telemetry provider as a dependency and pass it to the HCP manager.
3. In the HCP manager, …

[CC-7042] Update and enable the HCP metrics sink in the HCP manager

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/reusable-dev-build-windows.yml
.github/workflows/test-integrations-windows.yml

Manual backport of https://github.com/hashicorp/consul/pull/20173 and https://github.com/hashicorp/consul/pull/20174
It seems backport assistant is currently [no-op'ing](https://github.com/hashicorp/consul/actions/runs/7543298716/job/20534006499) backports from release branches.
<details>
- 4ef2845fc41415b63cadad10dbeb9eff68bb5630
- 8ae1f38a118675abc02a492774de55253e2df4d9
</details>

Backport of chore: improve CI backports by backporting new workflows into release/1.15.x

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.17.x.yml

Manual backport of https://github.com/hashicorp/consul/pull/20173
It seems backport assistant is currently [no-op'ing](https://github.com/hashicorp/consul/actions/runs/7543298716/job/20534006499) backports from release branches.
<details>
- 4ef2845fc41415b63cadad10dbeb9eff68bb5630
</details>

Backport of chore: improve CI backports by backporting new workflows into release/1.16.x

---

.github/workflows/test-integrations.yml

Unlike the Nomad tests (where Nomad is compiled from source and provides the tests), Vault is installed as a binary, and local Consul tests are run.
Fixes incorrect version change introduced in #20058.

ci: Use Consul Go version for Vault int tests

---

website/content/docs/k8s/annotations-and-labels.mdx
website/content/docs/k8s/helm.mdx

Docs changes for: https://github.com/hashicorp/consul-k8s/pull/3450

Add docs for k8s liveness / startup probes.

---

agent/discovery/discovery.go
agent/dns.go
agent/dns/router.go
agent/dns/router_test.go
agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

This is part of the DNS re-write that includes Catalog V2 support.
This PR completes the round-trip for `addr.` queries. These queries simply decode addresses into A/AAAA records. They do not need to interact directly with the catalog.
This PR includes new unit tests for the router based on manually inspecting the responses for the existing DNS code. It also enables running the relevant, existing DNS tests against the old and new code to verify correctness.  In general I think the new unit tests hold stronger assertions.
All the new unit tests should run in CI. You can also do manual testing using this agent config:
```hcl
ports {
https = 8501
grpc = 8502
grpc_tls = 8503
}
bind_addr = "127.0.0.1"
bootstrap = true
server = true
data_dir = "/tmp/consul-dc1"
datacenter = "dc1"
node_name = …
```

feat(v2dns): addr. query support

---

sdk/iptables/iptables.go
sdk/iptables/iptables_test.go

In order to support TProxy for Consul on ECS we need to add the following IPtable rule apart from the ones that the SDK supports
```zsh
iptables -t nat --policy POSTROUTING ACCEPT
```
Without this, redirected traffic will timeout without a response. The issue is only specific to ECS and happens when containers run inside EC2 instances based out of ECS optimized AMIs.
The other way to fix this problem would be to directly add the rule in the iptables SDK along with the others, but I thought of providing a way to extend stuff because we could have similar restrictions in other platforms as we keep adding support for traffic redirection.

Add additional rules to iptables SDK

---

internal/mesh/internal/controllers/gatewayproxy/controller.go

The fetched gateway isn't currently used anywhere, so stop fetching it. In addition, the identity of the gateway is assumed, which won't be valid even if we do need to fetch the gateway for the workload in the future.
🤖  tests pass
N/A

Remove unnecessary fetching of gateway

---

internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
internal/mesh/internal/controllers/gatewayproxy/builder/builder_test.go
internal/mesh/internal/controllers/gatewayproxy/controller.go

PR from ent, this adds listeners and clusters for mesh-gateway v2

[NET6429] Add listeners for mesh-gateway v2

---

website/content/docs/k8s/upgrade/index.mdx

With https://github.com/hashicorp/consul-k8s/pull/3000 merged, users can
upgrade their k8s installs using a regular helm upgrade since the
upgrade is now stable.

docs: update k8s upgrade instructions

---

.release/security-scan.hcl

This was recently shown to have issues with false positives that blocked a preview release build, so disabling for now.

security: disable Vault secret scans due to false positives

---

.changelog/20281.txt
api/go.mod
api/go.sum
internal/tools/proto-gen-rpc-glue/go.mod
internal/tools/proto-gen-rpc-glue/go.sum
proto-public/go.mod
proto-public/go.sum
sdk/go.mod
sdk/go.sum

This addresses CVE-2022-28948 and CVE-2021-4235.
CI continues to pass.

[NET-7339] security: update gopkg.in/yaml

---

internal/catalog/internal/controllers/nodehealth/controller.go
internal/catalog/internal/controllers/nodehealth/controller_test.go

This migrates the node health controller to use the cache.
This should perform better but also this makes retrieval of specific resource types that are owned by a resource potentially much more efficient as no post processing needs to be done to filter all resources owned by something to all resources of the specific type owned by that something.
* Existing unit tests
**Note: Some edge case error testing had to be removed because it was no longer possible to force errors when going through the cache layer as opposed to the resource service itself.**

Migrate the node health controller to use the cache

---

agent/config/builder.go
agent/consul/server.go
agent/hcp/config/config.go
agent/hcp/deps.go
docs/v2-architecture/controller-architecture/controllers.md
docs/v2-architecture/controller-architecture/guide.md
internal/controller/controller.go
internal/controller/controller_test.go
internal/controller/runner.go
internal/hcp/internal/controllers/link/controller.go
internal/hcp/internal/controllers/link/controller_test.go
internal/hcp/internal/controllers/register.go
internal/hcp/internal/types/link.go

This PR adds support to specify initialization logic that is executed when a resource’s controller is first started. Controllers now have an `Initializer` interface with an `Initialize` method to implement this logic.
This PR also implements the initialization logic for the hcp.v2.Link resource, where a link is created if the [cloud configuration](https://developer.hashicorp.com/consul/docs/agent/config/config-files#self-managed-hcp-parameters) is set.
Added unit tests and manually E2E tested with the following steps:
1. Add a `cloud` stanza in the configuration file
2. Start Consul
3. Observe the logs for the controller initializer
4. Fetch the expected hcp.v2.Link, confirm that it exists and that it has the same values as the configuration stanza and that the metadata indicates the …

[CC-7031] Add initialization support to resource controllers

---

.release/security-scan.hcl

Backport of https://github.com/hashicorp/consul/pull/20264 and subsequent fix https://github.com/hashicorp/consul/pull/20279

Backport of security: disable Vault secret scans due to false positives into release/1.15.9

---

agent/consul/leader.go
agent/consul/server.go
agent/hcp/manager.go
agent/hcp/manager_test.go

Jira: https://hashicorp.atlassian.net/browse/CC-7043
Previously, the HCP management token was only created when Consul starts up and when there is a leadership change. This was sufficient because the HCP token could not change at runtime.
The Link API will allow users to link to HCP using an API call at runtime. This PR makes it so the HCP management token will also be upserted when the HCP manager runs, which is one part of making it possible to link the cluster to HCP at runtime.
As I mention in a comment below, depending on where I placed this code, I could trigger an error message like: `node is not the leader`. I believe this error is mitigated by running this code inside the main loop of the HCP manager— in the worst case, if this call fails, it will be retried the next time through …

Create HCP management token in HCP manager

---

.changelog/20299.txt
agent/config/builder.go
agent/config/builder_test.go
agent/consul/server.go

Ultimately we will have to rectify wan federation with v2 catalog adjacent experiments, but for now blanket prevent usage of the `resource-apis`, `v2dns`, and `v2tenancy` experiments in secondary datacenters.

v2: prevent use of the v2 experiments in secondary datacenters for now

---

internal/controller/controller_test.go

Fixes some intermittent test failures by removing the initializer error and retry in the controller API test and putting it in a new, separate test. The other controller API test cases were running into timing issues since the initializer retries added more time between when the controller is started and when the reconciler runs.

Add a separate test for initializer retries

---

command/registry.go
command/resource/apply-grpc/apply.go
command/resource/client/grpc-flags.go
command/resource/client/grpc-resource-flags.go
command/resource/delete/delete.go
command/resource/helper.go
command/resource/read-grpc/read.go
command/resource/read-grpc/read_test.go
command/resource/resource-grpc.go

[This](https://hashicorp.atlassian.net/browse/NET-5649) is the background for this ticket.
In this PR, we enable the read command for grpc cli. The read command needs four flags to pass the information to consul:
- namespace
- partion
- peer
- stale
The user could also choose to use the `hcl`  file to retrieve the target resource information.

grpc CLI client read command

---

agent/grpc-external/services/resource/delete.go
agent/grpc-external/services/resource/delete_test.go
agent/grpc-external/services/resource/server.go
agent/grpc-external/services/resource/server_test.go
agent/grpc-external/services/resource/write.go
agent/grpc-external/services/resource/write_status_test.go
agent/grpc-external/services/resource/write_test.go

CE version of merged ENT PR: https://github.com/hashicorp/consul-enterprise/pull/8366
NET-6719

resource: retry non-CAS deletes automatically

---

.changelog/20220.txt
agent/hcp/bootstrap/bootstrap.go
agent/hcp/bootstrap/bootstrap_test.go
command/agent/agent.go

This adds the following header to _all_ Consul HTTP responses:
```
Access-Control-Expose-Headers: x-consul-default-acl-policy
```
The reasoning for this is in [this RFC](https://docs.google.com/document/d/185Kj_pDcuOmmVOzIPZYsCLIIOFB_26bg9kWD7i8qgkQ/edit#heading=h.5gihsi8y54bu), but in summary, we need this header in order to support the HCP UI. Previously, we added this at startup conditionally if the cluster was being linked to HCP. With the changes in the RFC, we are allowing Consul to be linked to HCP at any time and adding this header unconditionally at startup is the simplest solution as it doesn't require us to reload configuration at runtime.
```
➜ http localhost:8500/v1/catalog/services
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json
Date: Tue, 16 Jan 2024 …
```

Unconditionally add Access-Control-Expose-Headers HTTP header

---

.changelog/19647.txt
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_discoverychain_test.go
agent/structs/config_entry_test.go
agent/xds/routes.go
api/config_entry_discoverychain.go
api/config_entry_discoverychain_test.go
test/integration/connect/envoy/case-cfg-router-features/setup.sh
test/integration/connect/envoy/case-cfg-router-features/verify.bats
website/content/docs/connect/config-entries/service-router.mdx

Sometimes we need route to be case insensitive when using `prefix` in order to apply some rules later.
Envoy is supporting this feature since a while and can be found [here](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routematch-case-sensitive) all the way down to version `1.22.x`

Case sensitive route match

---

internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
internal/mesh/internal/controllers/gatewayproxy/builder/builder_test.go
internal/mesh/internal/controllers/gatewayproxy/controller.go

Mesh gateways won't start up successfully today if there are no exported services. This seems to be due to the fact that the only router on the listener in this case points to a non-existent cluster named `""`.
When this default router points to a valid cluster, the mesh gateway starts up correctly even when no services are exported. I used the "null route cluster" concept from the sidecar proxy builder for this target cluster.
Install w/ v2 resource APIs and mesh gateways enabled. The mesh gateway pods should come up healthy before creating any `ExportedServices` resources in k8s.

Use null route cluster for default router when no matches on v2 mesh gateway

---

website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx

A small change to the export group name reflecting the local partition being exported from as defined in the [Exported Services Configuration docs](/consul/docs/connect/config-entries/exported-services#configuration).
None
https://developer.hashicorp.com/consul/docs/connect/config-entries/exported-services#configuration

docs: Update k8s/connect/create-sameness-groups

---

agent/consul/server.go
agent/hcp/bootstrap/bootstrap.go
agent/hcp/bootstrap/bootstrap_test.go
agent/hcp/bootstrap/config-loader/loader.go
agent/hcp/bootstrap/config-loader/loader_test.go
agent/hcp/client/client.go
agent/hcp/client/errors.go
agent/hcp/deps.go
agent/setup.go
command/agent/agent.go
internal/hcp/internal/controllers/link/controller.go
internal/hcp/internal/controllers/link/controller_test.go
internal/hcp/internal/controllers/link/status.go
internal/hcp/internal/controllers/register.go
internal/hcp/internal/types/link.go
internal/hcp/internal/types/link_test.go
internal/hcp/internal/types/testing.go

This PR updates the link reconciler to get the value of the management token from HCP by fetching the agent bootstrap configuration. This reuses a lot of the existing logic for fetching the agent bootstrap config, specifically the code that first checks if the relevant files already exist locally on disk.
This PR is best viewed commit-by-commit. The main changes are:
- Moves the config loader code into a separate package to avoid cyclical dependencies
- Adds support for loading just the management token rather than also checking for the server configuration, as the server config is not needed by the link resource.
- Passes the data directory as a dependency to the link controller so that it can check if the management token file exists in the data directory or not.
- Calls the load …

[CC-7063] Fetch HCP agent bootstrap config in Link reconciler

---

internal/auth/internal/controllers/trafficpermissions/controller_test.go
internal/auth/internal/types/errors.go
internal/auth/internal/types/traffic_permissions.go
internal/auth/internal/types/traffic_permissions_ce_test.go
internal/auth/internal/types/traffic_permissions_test.go
internal/auth/internal/types/traffic_permissions_validator_ce.go
test/integration/consul-container/test/trafficpermissions/tcp_test.go

Moves the `deny` action for traffic permissions to enterprise only.

move deny action to enterprise only for traffic permissions

---

agent/discovery/discovery.go
agent/dns/router.go
agent/dns/router_test.go
agent/dns_test.go

This PR adds partial support for SOA records. SOA records are return in these cases:
* When an SOA query type is used. Nameservers are also provided in this case.
* When there is a valid query name but no data to return.
The necessary code paths for this record type are implemented, but not the fetching of nameservers, which will come in a subsequent PR.
* Unit tests are added with mock QueryProcessors
* V1 DNS tests - there weren't any to enable here. They all involve hitting the catalog in one way or another.

feat(v2dns): add partial support for SOA records

---

internal/hcp/internal/controllers/link/controller.go
internal/hcp/internal/controllers/link/controller_test.go
internal/hcp/internal/controllers/link/finalizer.go

This adds a `Finalizer` to the Link controller. For now, this just handles deleting the `hcp-config` directory.
In addition to automated unit tests, I performed the following manual test.
1. Run consul like so:
```
go run . agent -dev --log-level trace --data-dir /tmp/consul-test
```
2. Verify that `hcp-config` directory is created
```
➜  consul git:(nickcellino/CC-7338/add-link-finalizer) ls /tmp/consul-test
checkpoint-signature hcp-config           node-id              serf
➜  consul git:(nickcellino/CC-7338/add-link-finalizer) ls /tmp/consul-test/hcp-config
hcp-management-token server-config.json   successful-bootstrap
➜  consul git:(nickcellino/CC-7338/add-link-finalizer)
```
3. Create a Link:
```shell-session
➜  consul git:(nickcellino/CC-7338/add-link-finalizer) http PUT …
```

Add finalizer to link resource

---

ui/packages/consul-ui/mock-api/v1/agent/services
website/content/docs/connect/proxies/built-in.mdx

Fix the sample service registration for the built-in proxy by adding the missing `sidecar_service` block.

docs: Fix example service registration for built-in proxy

---

.changelog/20352.txt
agent/http.go
internal/resource/http/http.go
internal/resource/http/http_test.go

Previous:
agent.http: Registered resource endpoint: endpoint=/demo/v1/executive
New:
agent.http: Registered resource endpoint: endpoint=/api/demo/v1/executive
This reduces confusion when attempting to call the APIs after looking at the logs.

Change logging of registered v2 resource endpoints to add /api prefix

---

test/integration/consul-container/libs/cluster/container.go
testing/deployer/sprawl/internal/tfgen/gen.go

The docker image used in CICD was referencing `registry.k8s.io/pause:3.3`, which appears to no longer function correctly (either due to rate limiting or not being available to pull). This commit swaps over to a Hashicorp mirrored image that shouldn't have rate limits or disappearing images.

Fix CICD docker image rate limits.

---

.changelog/20353.txt
agent/uiserver/ui_template_data.go
agent/uiserver/uiserver_test.go
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/lib/startup/templates/body.html.js
ui/packages/consul-ui/node-tests/config/environment.js

For [NET-5398](https://hashicorp.atlassian.net/browse/NET-5398) we need to not render the rest of the ui app if v2 catalog is enabled and show a message as to why it's disabled and link out to help resources. Right now this would require another network request on app boot and we would have to wait until that resolves before rendering the rest of the app. 
I saw that experiments is a part of the runtime config so I figured we could add a `V2CatalogEnabled` property to the config that we pass to the UI app. With this, we can immediately check if V2 is enabled and render the help page, or immediately proceed with normal app operations if it's not enabled.
Enabled:
Disabled:
I've tested this by building the ui and the consul and then running it with and without the resources-api experiment …

NET-5398: Update UI server to include if v2 is enabled

---

internal/mesh/internal/controllers/sidecarproxy/controller.go
internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher.go
internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher_test.go
internal/mesh/internal/types/proxy_configuration.go
internal/mesh/internal/types/proxy_configuration_test.go

When a destination resides in a different partition from the source and mesh gateway mode is set to local or remote, the mesh gateway's service endpoints should be used for the destination cluster instead of the destination's own endpoints.
The results in outgoing requests targeting the appropriate mesh gateway (either local or remote) but sending along the same SNI + ALPN that was previously used. The mesh gateway will then forward the request to the appropriate place based on the SNI+ALPN combination.

[NET-5075] Implement mesh gateway mode for explicit destinations

---

.github/scripts/verify_envoy_version.sh

CICD was failing due to more envoy versions being added to the 1.15 supported list.

Increase number of supported envoy versions in failing CICD script

---

.github/workflows/verify-envoy-version.yml

The current version of this script does not work well with the LTS release having a much longer list of supported Envoy versions than the other branches. Later on, we should tweak this to have the expected behavior, but for now, it is being disabled so that the CICD pipeline can complete successfully and publish images.

Disable CICD Envoy check

---

.github/workflows/nightly-test-integrations-1.15.x.yml

LTS releases will support a widening number of envoy versions and we need to run integration tests against them. To be specific, 1.15.x is going to be the next LTS release.
Ran CI against my branch and reverted it.

add support for more envoy versions for LTS

---

.changelog/20312.txt
agent/agent.go
agent/agent_test.go
agent/config/builder.go
agent/consul/server.go
agent/consul/server_test.go
agent/hcp/config/config.go
agent/hcp/config/config_test.go
agent/hcp/deps.go
agent/hcp/manager.go
agent/hcp/manager_test.go
agent/hcp/telemetry/otel_sink.go
agent/hcp/telemetry_provider.go
agent/hcp/telemetry_provider_test.go
agent/setup.go
api/agent_test.go
internal/hcp/internal/controllers/link/controller.go
internal/hcp/internal/controllers/link/controller_test.go
internal/hcp/internal/controllers/register.go
internal/hcp/internal/types/link.go
internal/hcp/internal/types/link_test.go
lib/telemetry.go

Depends on https://github.com/hashicorp/consul/pull/20306
This PR starts the HCP manger when an HCP link resource is created instead of when Consul is started. This allows the linking process to be initiated via the HCP link API.
These changes are best viewed commit-by-commit. A summary of the changes are:
- Check explicitly for ACL policies since the HCP manger will create a token, so `acl:write` is also now required in addition to `operator:write`
- Change the HCP manager’s Run method to a Start method, keep track of if its running, and only allow to start once
- Always initialize the required HCP components (i.e., SCADA provider, HCP metrics sink) when Consul starts
- Pass the HCP manager as a dependency to the link controller 
- When a link is created, update the HCP manager with the …

[CC-7044] Start HCP manager as part of link creation

---

.github/workflows/test-integrations.yml

Update Vault/Nomad versions to ensure we're testing all the latest versions .
Test Nomad's latest supported nomad-version: ['v1.7.3', 'v1.6.6', 'v1.5.13']
https://github.com/hashicorp/nomad/blob/v1.7.3/CHANGELOG.md
Test Vault's latest supported vault-version: ["1.15.4", "1.14.8", "1.13.12"]
Grabbed the latest from the changelog- (https://github.com/hashicorp/vault/commit/b5e9f3f32ca55a11b0722858f352a4e70d22be60)

Update Vault/Nomad versions.

---

website/content/docs/agent/config/config-files.mdx

In agent config doc, wal and boldb should be in the same level. Remove the extra `-`

docs: Fix indention of wal object in agent config

---

internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher_test.go
internal/mesh/internal/types/mesh_gateway.go
internal/mesh/internal/types/mesh_gateway_test.go

* Add validation of MeshGateway name + listeners
* Adds test for ValidateMeshGateway
* Fixes data fetcher test for gatewayproxy
---------
Merge from Enterprise into CE, Validate that MeshGateway has required name and single listener with required listener name.

[NET-6417] Add validation of MeshGateway name + listeners

---

website/.husky/pre-commit
website/package-lock.json
website/package.json

In [another PR](https://github.com/hashicorp/consul/pull/20387) the husky pre-commit hook was changed to match the v9 specs, but `website` being a sub-directory of the root directory containing `.git` was not accounted for. This PR changes the pre-commit hook and script to account for that, and ensures the pre-commit hook runs as expected. ([Husky doc here](https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory)).
1. cd into `website/`
2. Run `npm install`
3. Make changes to a file in `website/`
4. Run `git commit -m "<your commit message>"`
5. You should see something like this in your terminal:
```
➜ git commit -m "Update husky"   
✔ Preparing...
✔ Running tasks...
✔ Applying modifications...
✔ Cleaning up...
[<branch> bdb989ffe1] Update husky
2 files changed, 8 …
```

website: fix husky command

---

.changelog/20439.txt
website/content/docs/k8s/dns.mdx

This updates our Consul DNS forwarding documentation to include methods for updating the DNS Operator on OpenShift clusters to include Consul's DNS service.
Our documentation titled **Resolve Consul DNS Requests in Kubernetes** has long been missing steps to update Kubernetes on OpenShift's DNS Operator to include the Consul DNS Forwarder. This PR aims to close that gap.
* Deploy Consul on OpenShift, and ensure the following overrides are set to enable `consul-dns` service:
```yaml
dns:
enabled: true
enabledRedirection: true
type: ClusterIP
```
* Find `consul-dns` service clusterIP: `oc get svc consul-dns --namespace consul --output jsonpath='{.spec.clusterIP}'`
* Edit the DNS Operator Configuration (as outlined in the OpenShift [Documentation](https://docs.openshift.com/container-platform …

Resolve Consul DNS in OpenShift

---

sdk/iptables/iptables.go
sdk/iptables/iptables_test.go

This fixes behavior introduced by hashicorp/consul#20232 where a function was added to the iptables configuration struct. Since this struct is actually marshalled into json by consul-k8s, we should not be placing functions inside of it.

Fix SDK iptables.Config marshalling

---

agent/grpc-external/server.go
command/resource/client/client.go
command/resource/client/grpc-flags.go
test/integration/consul-container/libs/cluster/agent.go
test/integration/consul-container/libs/cluster/container.go
test/integration/consul-container/test/resource/grpc_forwarding_test.go
test/integration/consul-container/test/resource/resource_test.go

This PR fix the allow forward policy. We should only allow the client agent to forward services that starts with `/hashicorp.consul.` but we missed the prefix `/` in the code base.
We also fix some typos in the code base.
The integration tests ensure that the forwarding policy actually works.

missing prefix /

---

internal/hcp/internal/controllers/telemetrystate/controller.go
internal/hcp/internal/controllers/telemetrystate/controller_test.go

Fixes a bug causing the TelemetryState controller to reconcile indefinitely

internal/hcp: prevent write loop on telemetrystate resource updates

---

internal/catalog/exports.go
internal/catalog/internal/controllers/endpoints/bound.go
internal/catalog/internal/controllers/endpoints/bound_test.go
internal/catalog/internal/controllers/endpoints/status.go

The endpoints controller currently encodes the list of unique workload identities referenced by all workload matched by a Service into a special data-bearing status condition on that Service. This allows a downstream controller to avoid an expensive watch on the ServiceEndpoints type just to get this data.
The current encoding does not lend itself well to machine parsing, which is what the field is meant for, so this PR simplifies the encoding from:
```
"blah blah: " + strings.Join(ids, ",") + "."
```
to
```
strings.Join(ids, ",")
```
It also provides an exported utility function to easily extract this data.

catalog: improve the bound workload identity encoding on services

---

agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v2.go
agent/dns/router.go
agent/dns/router_query.go
agent/dns/router_query_test.go
agent/dns_service_lookup_test.go

This is part of the DNS re-write that includes Catalog V2 support.
This PR completes the round-trip for `query.` queries against catalog v1 from dns v2.   
Out of Scope:
- TTL for Prepared Queries.  This will be addressed in NET-7613 which is ready for dev.
- Tests enabled for v2 dns in `agent/dns_service_lookup_test.go`

NET-7488 - dns v2 add support for prepared queries in catalog v1 data model

---

agent/discovery/discovery.go
agent/discovery/discovery_test.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/discovery/query_fetcher_v2.go
agent/discovery/query_fetcher_v2_test.go
agent/dns/router.go
agent/dns/router_ce.go
agent/dns/router_ce_test.go
agent/dns/router_query.go
agent/dns/router_query_test.go
agent/dns/router_test.go
agent/dns_service_lookup_test.go

This changes the discovery result to pass back the name and address of both service and Node.  previously we had target and address as two string fields.  The dns logic needs access to more data in order to process the dns results from the discovery results.
- Tests enabled for v2 dns in `agent/dns_service_lookup_test.go`, `agent/dns_node_lookup_test.go`, and `agent/dns_test.go`

DNS V2 - Revise discovery result to have service and node name and address fields.

---

.github/workflows/ce-merge-trigger.yml

This replicates the pattern used in `main` and `release/1.17.x`.
https://github.com/hashicorp/consul/blob/main/.github/workflows/ce-merge-trigger.yml
@jm96441n LMK if you'd like me to backport this to the point-release branch as well.

ci: sync point release branches in addition to .x

---

agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

DNS tests fail regularly in CI and with the recent addition of running dns v2 and dns v1 versions of these tests, ports on the runner get exhausted and failures in these tests and other tests occur.
CI with verificiation that total runtime is reasonable comparative to these tests before this change.

Do not parallelize DNS tests because they consume too many ports

---

.changelog/20481.txt
agent/config_endpoint_test.go
agent/consul/state/config_entry.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go

This resolves an issue introduced in hashicorp/consul#19829 where the proxy-defaults configuration entry with an HTTP protocol cannot be updated after it has been persisted once and a router exists. This occurs because the protocol field is not properly pre-computed before being passed into validation functions and will result in a protocol mis-match error message (the new proxy-defaults will have an assumed protocol of `tcp` which will conflict with the router's need for `http`).
This PR hoists the protocol computing logic into the Normalize function of the config entry, which will ensure that it is properly populated prior to the validation function executing.

Fix issue with persisting proxy-defaults

---

.changelog/20331.txt
command/registry.go
command/services/exportedservices/exported_services.go
command/services/exportedservices/exported_services_test.go
website/content/api-docs/exported-services.mdx
website/content/commands/services/exported-services.mdx
website/data/api-docs-nav-data.json
website/data/commands-nav-data.json

<details>
- 53c499b32869c1a86d155463d72a6c1e127620e9  - 92c7e4e4245ac2b89a7d07ac344ccd7065f6bdb5  - 3aa961288b76c2655d04e828b551645a21f0c213  - 4e65f120077aaa2b3e0e42312f1c4154ec7d621f  - 2070d61d634c5bc08cf16df9c94c96f2c36227e4  - 292b2452ddc710d0d06f80c18f7dab6e6b940413  - 33154cde48155396bf74f38d6a935b547f42c568  - e9e81efb13a5186bda59a7c3b38e6e7711b35153 
</details>
---------
PR: https://github.com/hashicorp/consul/pull/20331

Manual Backport  of Exported services CLI and docs into release/1.18.x (#20331)

---

agent/consul/testdata/v2-resource-dependencies.md
internal/mesh/internal/controllers/routes/controller.go
internal/mesh/internal/controllers/routes/controller_test.go
internal/mesh/internal/controllers/routes/generate.go
internal/mesh/internal/controllers/routes/generate_test.go
internal/mesh/internal/controllers/routes/loader/loader.go
internal/mesh/internal/controllers/routes/loader/loader_test.go
internal/mesh/internal/controllers/routes/loader/memoized.go
internal/mesh/internal/controllers/routes/loader/related.go
internal/mesh/internal/controllers/routes/xroutemapper/xroutemapper.go
internal/mesh/internal/controllers/routes/xroutemapper/xroutemapper_test.go
internal/mesh/internal/controllers/sidecarproxy/builder/destinations_test.go
internal/mesh/internal/controllers/sidecarproxy/cache/cache_test.go
internal/mesh/internal/types/decoded.go
proto-public/pbcatalog/v2beta1/computed_failover_policy_extras.go
proto-public/pbcatalog/v2beta1/computed_failover_policy_extras_test.go
proto-public/pbcatalog/v2beta1/failover_policy_extras.go
proto-public/pbcatalog/v2beta1/failover_policy_extras_test.go

Update the routes controller to:
Watch computed failover policies instead of failover policies.
On reconcile, fetch and use computed failover policies rather than failover policies.

NET-6776 - Update Routes controller to use ComputedFailoverPolicy CE

---

agent/dns/router.go
agent/dns/router_query.go
agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

- TXT records were not working on node lookups.
- audited the failing tests in the service and node lookups file and created sub tasks for them related to the theme of what needed to be implemented.
CI

NET-7630 - Fix TXT record creation on node queries

---

internal/mesh/internal/controllers/apigateways/controller.go
internal/mesh/internal/controllers/apigateways/controller_test.go
internal/mesh/internal/controllers/apigateways/fetcher/data_fetcher.go
internal/mesh/internal/controllers/apigateways/fetcher/data_fetcher_test.go
internal/mesh/internal/controllers/gatewayproxy/controller.go
internal/mesh/internal/types/api_gateway.go
internal/mesh/internal/types/decoded.go
internal/mesh/internal/types/types.go

CE port of ENT PR
Adds APIGateway support to GatewayProxyController
Adds registration for APIGateway
Setup APIGatewayController to reconcile the Gateway

[NET-7280] Add APIGW support to the gatewayproxy controller

---

agent/discovery/discovery.go
agent/discovery/query_fetcher_v2.go
agent/discovery/query_fetcher_v2_test.go
agent/dns/router.go
agent/dns/router_ce_test.go
agent/dns/router_test.go

This PR adds support for SOA and NS records using the Catalog V2. There is still an open question if the DNS format should include tenancy for V2 but I think this is a good first cut.
* Unit tests contributed inline
* I did some manual testing and compared V1 DNS + Catalog responses against V2 DNS + Catalog and the results look pretty good:
```
; <<>> DiG 9.18.21 <<>> @127.0.0.1 -p 8600 consul. SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62853
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;consul.                                IN      SOA
;; ANSWER SECTION:
consul. …
```

feat(v2dns): catalog v2 SOA and NS support

---

agent/consul/client_test.go
agent/consul/server_test.go
agent/consul/testdata/v2-resource-dependencies.md
agent/rpc/peering/service_test.go
internal/controller/runner.go
internal/mesh/internal/controllers/register.go

If controllers get configured to watch invalid types or otherwise make invalid requests to the resource service, these can go unnoticed (especially for code that is not intended to be finished yet). This PR changes that. Now if a controller would make invalid requests it causes a panic of the whole server. This should cause these issues to surface in other tests which and therefore should block merging of invalid code due to CI failures.
The goal is to catch all of these before code gets merged so that we minimize the impact of any wip code going into main/release branches.
If you remove the second commit, you can see that the api-gw controller makes invalid requests to the resource service and will cause a server panic.

Panic for unregistered types

---

internal/catalog/catalogtest/run_test.go

In Consul Enterprise the failover controller depends on the multicluster types so they need to be registered here to prevent a panic.
N/A - the change doesn't affect Consul CE and already has been made in Consul Enterprise. This is just synchronizing the files.

Register the multicluster types for the catalogtest integration tests

---

agent/consul/server.go
internal/multicluster/exports.go
internal/multicluster/internal/controllers/register.go
internal/multicluster/internal/controllers/v1compat/controller.go

* Don't start the v2 exported services controller in v1 mode.
* Use the controller cache.

V1 Compat Exported Services Controller Optimizations

---

lib/hoststats/collector.go
lib/hoststats/collector_test.go

Fixes an issue where in dev mode, the data directory is not set, so this metrics collection would always fail and logs errors.
```
2024-02-07T14:15:06.466-0600 [ERROR] agent.host_stats: failed to collect dataDir disk stats: error="failed to collect disk usage stats: no such file or directory"
2024-02-07T14:15:16.468-0600 [ERROR] agent.host_stats: failed to collect dataDir disk stats: error="failed to collect disk usage stats: no such file or directory"
2024-02-07T14:15:26.468-0600 [ERROR] agent.host_stats: failed to collect dataDir disk stats: error="failed to collect disk usage stats: no such file or directory"
```
Checked that metrics were skipped in dev mode:
1. Started consul in dev mode (`consul agent -dev`)
2. Inspected the logs to ensure this error was no longer outputted
Checked …

[CC-7434] Skip collecting data directory metrics in dev mode

---

website/content/docs/agent/config/config-files.mdx

Providing more detail to the [cache section](https://developer.hashicorp.com/consul/docs/agent/config/config-files#cache) to address behavior of API calls using streaming backend. This will help users understand that when '?index' is used and '?cached' is not, caching to servers will be [bypassed](https://github.com/hashicorp/consul/blob/543c6a30af784a39fea5f7893b785ff1ba6d4d2e/agent/cache/cache.go#L406), causing [entry_fetch_max_burst](https://developer.hashicorp.com/consul/docs/agent/config/config-files#entry_fetch_max_burst) and [entry_fetch_rate](https://developer.hashicorp.com/consul/docs/agent/config/config-files#entry_fetch_rate) to not be used in this scenario.

Update cache section for certain API calls

---

agent/config/runtime.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_ce.go
agent/dns/router.go
agent/dns/router_ce.go
agent/dns/router_query.go
agent/dns/router_response.go
agent/dns/router_test.go
agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

- NET-7635 - Fix error dns: overflowing header size in the following tests:
- TestDNS_ServiceLookup_Randomize
- TestDNS_ServiceLookup_Truncate
- TestDNS_TCP_and_UDP_Truncate
- TestDNS_TCP_and_UDP_Truncate
- NET-7641 - Service and query lookups not properly de-duping SRV records.  Fixes test:
- TestDNS_ServiceLookup_Dedup_SRV
- NET-7643 - Implement EDNS0 records when queried.  Fixes tests:
- TestDNS_EDNS0
- TestDNS_EDNS0_ECS
- NET-7640 - NS or SOA Records not populate on some invalid service / prepared query lookups. Fixes tests:
- TestDNS_ServiceLookup
- TestDNS_SOA_Settings
- TestDNS_NSRecords
- TestDNS_NSRecords_IPV6
- TestDNS_AltDomain_NSRecords
- TestDNS_AltDomain_NSRecords_IPV6
- TestDNS_InvalidQueries
- TestDNS_AltDomains_SOA
* ~~[ ] external facing docs updated~~

DNS v2 Multiple fixes.

---

agent/auto-config/auto_config_test.go
agent/hcp/client/http_client.go
agent/hcp/client/http_client_test.go
agent/hcp/telemetry_provider.go

I'm seeing redundant log lines on failures to push metrics to HCP:
> 2024-02-07T14:22:37.358Z [ERROR] agent.hcp.hcp_telemetry_client: request failed: error="Post \"[https://consul-telemetry.hcp.dev/otlp/v1/metrics\\](https://consul-telemetry.hcp.dev/otlp/v1/metrics%5C%5C)": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error" method=POST url=https://consul-telemetry.hcp.dev/otlp/v1/metrics
> 2024/02/07 14:22:37 failed to export metrics: failed to post metrics: POST https://consul-telemetry.hcp.dev/otlp/v1/metrics giving up after 1 attempt(s): Post "https://consul-telemetry.hcp.dev/otlp/v1/metrics": http2: Transport: cannot retry err [http2: Transport received Server's …

Fix: avoid redundant logs on failures to export metrics

---

.changelog/20514.txt
agent/hcp/deps.go
agent/hcp/deps_test.go

Testing 1.18.x I noticed some stderr log lines w/o the normal hclog formatting:
```
2024-02-06T22:35:18.972Z [ERROR] agent.envoy: Error receiving new DeltaDiscoveryRequest; closing request channel: error="rpc error: code = Canceled desc = context canceled"
2024-02-06T22:35:19.072Z [ERROR] agent.envoy: Error receiving new DeltaDiscoveryRequest; closing request channel: error="rpc error: code = Canceled desc = context canceled"
2024/02/06 22:35:31 failed to export metrics: failed to export metrics: code 404: 404 page not found
2024/02/06 22:44:31 failed to export metrics: failed to export metrics: code 404: 404 page not found
```
Here in OTEL there's a `GlobalHandler` that defaults to logging to stderr: https://github.com/open-telemetry/opentelemetry-go/blob/main/internal/global/handler.go#L …

Fix logging when we fail to export metrics to hcp

---

.changelog/20544.txt
acl/authorizer.go
acl/chained_authorizer.go
agent/agent.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/consul/acl.go
agent/consul/client.go
agent/consul/config.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/server.go
agent/consul/state/catalog.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/consul/util.go
agent/proxycfg-glue/glue.go
agent/proxycfg-glue/intention_upstreams.go
agent/proxycfg-glue/intention_upstreams_test.go
agent/structs/intention.go

Recommended to review commit-by-commit
Adds a new agent configuration field `DefaultIntentionPolicy` (`default_intention_policy`) which controls how service-to-service traffic is authorized in the absence of specific intentions.
`DefaultIntentionPolicy` can be `"allow"`, `"deny"`, or `""`, where if left blank it will inherit the default ACL policy.
This field will de-couple the ACL subsystem from intentions, allowing users to incrementally adopt secure configurations one step at a time without dealing with implicit dependencies between the two subsystems.
* Added unit tests which inject default intention policy and observe that it overrides the default ACL policy

Add default intention policy

---

.changelog/20511.txt
agent/consul/xdscapacity/capacity.go

This prevents a potential bug where raft-autopilot could deadlock while attempting to execute `AutopilotDelegate.NotifyState()` on an xdscapacity controller that has stopped / delayed consuming messages.
The following line of logic appears that it could be a potential problem:
1. The call to `countProxies()` can wait for up to 1 minute before retrying to load info. It also never resets its counter, which means a significant wait is more likely. https://github.com/hashicorp/consul/blob/v1.17.2/agent/consul/xdscapacity/capacity.go#L194
2. `countProxies()` shares a loop with the consumption from the `serverCh` that has counts published to it. https://github.com/hashicorp/consul/blob/v1.17.2/agent/consul/xdscapacity/capacity.go#L93-L97
3. The `serverCh` channel is published to by the …

Decouple xds capacity controller and raft-autopilot

---

agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_ce.go
agent/dns/router.go
agent/dns/router_query.go
agent/dns/router_query_test.go
agent/dns/router_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go

NET-7637 - Implement Health filtering.  Fixes tests:
- TestDNS_ServiceLookup_FilterCritical
- TestDNS_ServiceLookup_OnlyFailing
- TestDNS_ServiceLookup_OnlyPassing
NET-7659 - Fix Ingress and Connect Service Lookups. Fixes tests:
- TestDNS_IngressServiceLookup
- TestDNS_ConnectServiceLookup
NET-7636 - Implement target having encoded IP address. fixes tests:
- TestDNS_ServiceLookup_ServiceAddressIPV6
- TestDNS_ServiceLookup_ServiceAddress_A
- TestDNS_AltDomain_ServiceLookup_ServiceAddressIPV6
- TestDNS_AltDomain_ServiceLookup_ServiceAddress_A
NET-7647 - supporting non-existent lookups and datacenters. fixes tests:
- TestDNS_NonExistentDC_Server
- TestDNS_NonExistentDC_RPC
- TestDNS_NonExistingLookup
- TestDNS_NonExistingLookupEmptyAorAAAA
NET-7648/NET-7646/NET-7649 - Prepared Query - inject …

NET-7637 / NET-7659/NET-7636/NET-7647/NET-7648/NET-7646/NET-7649/NET-7645 - Multiple DNS v2 fixes

---

agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/discovery/query_fetcher_v2.go
agent/discovery/query_fetcher_v2_test.go
agent/dns/router.go
agent/dns/router_test.go
agent/dns_service_lookup_test.go

This adds support for Prepared Query TTLs in the V2 DNS server in two ways:
* If returned as part of the prepared query result, that TTL will be threaded back to the router as an override
* If there is no override, prepared queries should look at service TTLs.
* I updated the existing V1 tests to prove this is the correct behavior, since there was no existing coverage.
* New router tests look at both cases. With both an override and service TTL, and with only a matching service TTL.

feat(v2dns): prepared query ttls

---

ui/packages/consul-ui/app/services/hcp-link-status.js
ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
ui/packages/consul-ui/tests/integration/components/link-to-hcp-banner-test.js

Remove temporary `CONSUL_HCP_LINK_ENABLED` env flag.
PR it was added: https://github.com/hashicorp/consul/pull/20392
1. go to consul 
2. go to Service list - link to HCP banner is visible
3. set CONSUL_HCP_LINK_ENABLED to true and then to false (from cookies or with running locally Scenario('CONSUL_HCP_LINK_ENABLED=true')) - banner is still there for any value

chor: remove temporary CONSUL_HCP_LINK_ENABLED env flag

---

internal/controller/cache/index/convenience_test.go
internal/controller/cache/index/index.go
internal/controller/cache/index/index_test.go
internal/controller/cache/index/txn.go
internal/controller/cache/index/txn_test.go
internal/controller/cache/indexers/decoded_indexer_test.go
internal/controller/cache/indexers/id_indexer_test.go
internal/controller/cache/indexers/ref_indexer_test.go
internal/controller/cache/kind.go

Previously calling `index.New` would return an object with the index information such as the `Indexer`, whether it was required, and the name of the index as well as a radix tree to store indexed data.
Now the main `Index` type doesn’t contain the radix tree for indexed data. Instead the `IndexedData` method can be used to combine the main Index with a radix tree in the `IndexedData` structure.
The cache still only allows configuring the `Index` type and will invoke the `IndexedData` method on the provided indexes to get the structure that the cache can use for actual data management.
All of this makes it now safe to reuse the `index.Index` types.
This is mainly important to remove a potential stumbling block for using the cache correctly by making it harder to use incorrectly.
* New unit …

Allow reuse of cache indexes

---

.changelog/20474.txt
ui/packages/consul-ui/app/components/hcp-nav-item/index.js
ui/packages/consul-ui/app/components/link-to-hcp-banner/index.js
ui/packages/consul-ui/app/components/link-to-hcp-modal/index.hbs
ui/packages/consul-ui/app/components/link-to-hcp-modal/index.js
ui/packages/consul-ui/app/components/link-to-hcp-modal/index.scss
ui/packages/consul-ui/app/controllers/application.js
ui/packages/consul-ui/app/helpers/hcp-authentication-link.js
ui/packages/consul-ui/app/services/hcp-link-modal.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
ui/packages/consul-ui/tests/integration/components/link-to-hcp-modal-test.js
ui/packages/consul-ui/tests/integration/helpers/hcp-authentication-link-test.js

https://hashicorp.atlassian.net/browse/CC-7147
Add Link to HCP modal and integrate to link to hcp banner and side-nav item
https://github.com/hashicorp/consul/assets/10027860/1ce346bb-26df-4ce1-b639-0fb1fef70047
1. go to Consul 
2. visit Services page
3. click purple banner 'Link the cluster' action
4. enjoy the modal, check how token is generated and try to link to hcp
5. open modal by clicking 'Link to HCP Consul Central' from side nav
6. repeat steps

Cc 7147 link to hcp modal

---

agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/discovery/query_fetcher_v2.go
agent/discovery/query_fetcher_v2_test.go
agent/dns/router.go
agent/dns/router_ce.go
agent/dns/router_test.go

This PR completes service queries against the V2 Catalog using the refactored DNS server. Multi-port services and A/AAAA/SRV queries with port names are now supported.
* unit tests updated as noted
* integration tests coming in a future PR
* manual testing
I used some of the workload, healthstatus, and service resources [in this scenario](https://github.com/DanStough/consul-scenarios/tree/main/local/v2-resource-api) to configure a test agent. Then I ran some of the following commands:
```bash
❯ dig @127.0.0.1 -p 8600 royco-waystar.service.consul
; <<>> DiG 9.18.21 <<>> @127.0.0.1 -p 8600 royco-waystar.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15083
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, …
```

feat(v2dns): catalog v2 service query support

---

agent/dns_ce_test.go

Found DNS tests that were not configured to run in v1 & v2 modes in router_ent.go and router_ce.go.
This adds that capability to run both versions and as well tags the following broken tests with a task comment to fix them:
- TestDNS_CE_PeeredServices
- TestDNS_Enterprise_LookupNodeInOtherPartition
- TestDNS_Enterprise_NamespacedServices_PreferNamespace
- TestDNS_Enterprise_PeeredServices
- TestDNS_SamenessFailover

set up ent and CE specific DNS tests to be able to run v1 and v2

---

internal/mesh/internal/controllers/apigateways/controller.go
internal/mesh/internal/controllers/apigateways/controller_test.go

Makes the listenerToProtocol function more forgiving of different cased input (in the case that input is `TCP` for example).

[NET-7450] Fix listenerToProtocol function for input

---

agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/discovery/query_fetcher_v2.go
agent/dns_ce_test.go

This completes peering and sameness group queries for v2 DNS. All of the tests in `dns_ce.go` and `dns_ent.go` are either enabled or deemed unsupported in v2 DNS 
* Running the agent tests `dns*.go`

feat(v2dns): enable peering queries

---

agent/agent.go
agent/catalog_endpoint.go
agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/dns.go
agent/dns/router.go
agent/dns/router_query.go
agent/dns/router_service_question_test.go
agent/dns/router_test.go
agent/dns/server.go
agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go
agent/health_endpoint.go
agent/prepared_query_endpoint.go
agent/translate_addr.go
internal/dnsutil/dns.go

Fixes tests:
- TestDNS_Lookup_TaggedIPAddresses (passing). part of NET-7644.
- TestDNS_ServiceLookup_WanTranslation (not passing). part of NET-7634.
- this logic requires addtional data from the database in the TaggedAddresses collection on nodes and services, as well as it also requires whether you are asking for IPV6, IPV4 or ANY,
- since it requires data from the database, there needs to be a change to DiscoveryResult.  
- Right now it is just  TaggedAddresses on the Discovery Result level. 
- Also, the Tagged Address on the service has address and PortNumber, so I hacked around with moving PortName and PortNumber to the Location struct and then making Tagged Addresses a `map[string]*Location` on the discovery result.
- This is still a WIP and it looks like both Node and Service will …

NET-7644/NET-7634 - Implement query lookup for tagged addresses on nodes and services including WAN translation.

---

website/content/docs/agent/config/config-files.mdx

At first it's not clear what verify_outgoing would do for the https listener as it seems like Consul agent's don't make https requests. Upon further investigation, it's clear that Consul agents do make https requests in the following scenarios:
- to implement watches
- to perform checks
In the first scenario, this setting is used here:
https://github.com/hashicorp/consul/blob/a1c8d4dd19caad13edf2d86441d1b7f9bbdc9c34/agent/config/runtime.go#L1725
In the second scenario, it's actually the internal_rpc setting that is used:
https://github.com/hashicorp/consul/blob/a1c8d4dd19caad13edf2d86441d1b7f9bbdc9c34/tlsutil/config.go#L903

docs: document behaviour of tls.https.verify_outgoing

---

agent/dns_catalogv2_test.go

Add a "kitchen sink" smoke test for DNS v2 + Catalog v2 in the style of existing Catalog v1 DNS integration tests.
Cases covered:
* A/AAAA query against a service with several matching workloads
* A/AAAA query directly against a workload
* SRV request against a multi-port service with at least one matching workload
* A/AAAA query against an invalid name
* A/AAAA query against a service with no matching workloads
* TCP and UDP clients

[NET-7015] DNS v2 + Catalog v2 int test

---

internal/auth/internal/controllers/trafficpermissions/controller_test.go

Fixes missed enterprise type registration in https://github.com/hashicorp/consul/pull/20593

Add samenessgroup registration for enterprise

---

agent/config/builder.go
agent/config/builder_test.go
agent/config/runtime_test.go
agent/hcp/config/config.go

This PR fixes an issue where the values in an API request were not taking precedence over the ones set by environment variables. The rules of precedence should be:
1. At startup, environment variables take precedence over configuration values (per [configuration docs](https://developer.hashicorp.com/consul/docs/agent/config/config-files#self-managed-hcp-parameters)).
2. At runtime, incoming values from API requests take precedence over environment variables and configuration values.
To accommodate both rules, I updated the config builder to be completely responsible for loading environment variables and using them over config values. Previously, this was taken care of on demand whenever `HCPConfig()` was called, which called [`FromEnv()`](https://github.com/hashicorp/hcp-sdk-go/blob/87afe7 …

[CC-7411] Fix environment variable precedence when linking to HCP

---

.changelog/20642.txt
agent/consul/controller/controller.go
agent/consul/fsm/fsm.go
agent/consul/gateways/controller_gateways.go
agent/consul/stream/event_publisher.go

This PR fixes two issues:
1. Not all streams were force closed whenever a snapshot restore happened. This means that anything consuming data from the stream (controllers, queries, etc) were unaware that the data they have is potentially stale / invalid. This first part ensures that all topics are purged.
2. The v1 controllers did not properly handle stream errors (which are likely to appear much more often due to 1 above) and so it introduces a supervisor thread to restart the watches when these errors occur.
---
Prior to this change, the config entry controllers (use for v1 API gateway) would terminate and restart whenever a snapshot restore happened, but it was only by chance that it would handle this event gracefully due to the [reassertLeaderCh firing and starting the entire watch …

Ensure all topics are refreshed on FSM restore and add supervisor loop to v1 controller subscriptions

---

.changelog/20643.txt
agent/discovery/discovery.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_test.go
agent/dns/parser_test.go
agent/dns/router.go
agent/dns/router_test.go
agent/dns/server_test.go
agent/dns_node_lookup_test.go
agent/dns_service_lookup_test.go
agent/dns_test.go
agent/grpc-external/services/dns/server_v2.go

This PR started out as comment cleanup but ended up including some functional changes, including eliminating some unused fields and adding the Node TTLs to Workloads (which was discussed previously with Keeler). 
The changelog for V2 DNS is also included here.
* CI

fix(v2dns): add node ttl to workloads, comment cleanup, and changelog

---

ui/packages/consul-ui/app/components/hcp-nav-item/index.js
ui/packages/consul-ui/app/components/link-to-hcp-banner/index.js
ui/packages/consul-ui/app/components/link-to-hcp-modal/index.hbs
ui/packages/consul-ui/app/components/link-to-hcp-modal/index.js
ui/packages/consul-ui/app/helpers/hcp-authentication-link.js
ui/packages/consul-ui/app/services/hcp-link-modal.js
ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
ui/packages/consul-ui/tests/integration/components/link-to-hcp-modal-test.js
ui/packages/consul-ui/tests/integration/helpers/hcp-authentication-link-test.js

rethink on default value for cluster name on linking. 
With the pr it is set to datacenter name
Attention to link ⬇️ 
1. fo to consul 
2. check the link to hcp modal and click/hover the Next button
3. see the cluster_name param in the link bellow/in a new tab when redirected

chor: change cluster name param to have datacenter.name as default value

---

docs/v2-architecture/controller-architecture/guide.md

Docs for finalizers. See https://hashicorp.atlassian.net/browse/NET-6959.
- tagging @mkam and @NickCellino as primaries since you folks are the only ones that have tried to use finalizers
- @loshz for core team coverage

docs: developer docs for resource finalizers

---

agent/agent.go
agent/config/builder_test.go
agent/consul/options.go
agent/consul/server.go
agent/dns/router.go
agent/dns_catalogv2_test.go

I noticed that we added code to invalidate certain experiments on secondary datacenters. We want to allow V2 DNS on secondary centers if we ever want to delete the old implementation.
* Unit tests updates

[CE] fix(v2dns): allow secondary datacenters

---

agent/agent.go
agent/config/builder_test.go
agent/consul/options.go
agent/consul/server.go
agent/dns/router.go
agent/dns_catalogv2_test.go

Release backport of #20657
I noticed that we added code to invalidate certain experiments on secondary datacenters. We want to allow V2 DNS on secondary centers if we ever want to delete the old implementation.
* Unit tests updates

[CE ]Backport of fix(v2dns): allow secondary datacenters

---

Makefile

To enable more consistent and error-proof dependency management, add a Make target that will set a dependency version across all submodules that require it.
Also runs `go mod tidy`. This first ensures the dependency addition is reverted if the module in question does not require it; it also ensures that any additional cleanup needed in `go.mod`/`go.sum` is applied.
At one point, it seemed we could avoid executing `go get` per each `go.mod` by instead moving to a versioned `go.work` and using workspace-based dependency management commands. Though there's still reasons to move to `go.work` beyond this change, it probably won't work for bumping dependencies conveniently: `go work sync` consolidates versions using MVS, so in practice, it seems we still need to use a visit-all approach to be …

[NET-6741] make: Add target for updating dependencies across all modules

---

website/content/docs/connect/gateways/api-gateway/install-k8s.mdx
website/content/docs/k8s/installation/install.mdx

GKE Autopilot section for reference when installing Consul K8s. Update API Gateway install guide on K8s to also show GKE Autopilot install.

docs: GKE Autopilot section

---

website/content/docs/connect/gateways/api-gateway/install-k8s.mdx

It looks like what was happening was due to the [lines 57 and 59](https://github.com/hashicorp/consul/blob/main/website/content/docs/connect/gateways/api-gateway/install-k8s.mdx#L57) not having the same spacing as it's parent tab that our MDX parser was treating them as a separate section.

Fix malformed MDX in install-k8s

---

.github/workflows/go-tests.yml
testing/deployer/sprawl/sprawltest/test_test.go
testing/deployer/topology/compile.go
testing/deployer/topology/compile_test.go
testing/deployer/topology/topology.go

This adds a bunch of coverage of the `topology.Compile` method. It is not complete, but it is a start.
- A few panics and miscellany were fixed.
- The `testing/deployer` tests are now also run in CI.

deployer: add a bunch of test coverage and fix a few panics

---

website/content/docs/connect/gateways/api-gateway/install-k8s.mdx

Format install guide for API GW.

docs: format API GW tab docs

---

website/content/docs/api-gateway/install.mdx
website/content/docs/k8s/installation/install.mdx
website/redirects.js

Manual backport of https://github.com/hashicorp/consul/pull/20697

docs: manual backport #20697

---

website/content/docs/k8s/multiport/reference/grpcroute.mdx
website/content/docs/k8s/multiport/reference/httproute.mdx
website/content/docs/k8s/multiport/reference/tcproute.mdx
website/content/docs/k8s/multiport/traffic-split.mdx

Now that service virtual port references are supported in xRoutes and config,
- Call out both formats accepted for service port references
- Update K8s examples to use virtual ports (most likely use case)
I will manually backport this to the 1.18.0 release branch once merged.

[NET-7713] docs: Update v2 K8s docs to use virtual port references

---

.changelog/20474.txt
ui/packages/consul-ui/app/components/hcp-nav-item/index.js
ui/packages/consul-ui/app/services/hcp-link-status.js
ui/packages/consul-ui/tests/acceptance/link-to-hcp-test.js
ui/packages/consul-ui/tests/integration/components/hcp-nav-item-test.js

This PR just hardcodes all of the CTAS to never display - so we can ensure the 1.18 release does not display them!
We will pull all this code out in a follow up PR
Load the UI - see that there's no CTAs to Consul Cental

Hardcode links to CCM to be false 

---

GNUmakefile

Backport of https://github.com/hashicorp/consul/pull/19785 which also includes updates to Go modules list / Make target from https://github.com/hashicorp/consul/pull/17462 (landed on `main` during 1.16).
Asking for a quick extra review bc @rboyer 's  original `go-mod-tidy` introduction [noted](https://github.com/hashicorp/consul/pull/7179/commits/ce3b557e8359221723373e6d8172334dafab463e) "the correct order" and I wanted to make sure this wasn't sneakily risky in 1.15.
Tested locally as in original PR, same results.
<details>
- 6f0e24cda79b6c395b7424a0389e97afbb36a712 
</details>

Manual backport of [NET-6741] make: Add target for updating dependencies across all modules into release/1.15.x

---

website/content/docs/k8s/helm.mdx

This PR is the regeneration of the Helm docs with updated values from `consul-k8s` 1.4.0, released today.
Visual inspection
Generated from the 1.4.0 `values.yaml` [here](https://github.com/hashicorp/consul-k8s/blob/release/1.4.0/charts/consul/values.yaml)

docs: update Helm docs for consul-k8s 1.4.0

---

website/content/docs/k8s/compatibility.mdx
website/content/docs/k8s/multiport/configure.mdx
website/content/docs/release-notes/consul/v1_18_x.mdx

- OpenShift bumps on k8s compat matrix
- Typos on v2 API pages

docs: 1.18.x cleanup

---

website/content/docs/k8s/compatibility.mdx

K8s 1.26.x is actually built-in to OpenShift 4.13.x so we need to change the version of OpenShift for Consul K8s 1.4.x we support.

docs: Update OpenShift compat matrix

---

.changelog/20674.txt
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_ce.go
agent/consul/usagemetrics/usagemetrics_ce_test.go
agent/consul/usagemetrics/usagemetrics_test.go
website/content/docs/upgrading/upgrade-specific.mdx

Usage metrics reporting is relatively expensive (especially for Consul Enterprise which emits these metrics per tenant). We have been emitting redundant and duplicate metrics for years. This PR stops emitting the redundant metrics and reduces CPU usage for this by 20% in CE and 42% in Enterprise.
* Existing tests
* Benchmarks

Remove redundant usage metrics

---

website/content/commands/snapshot/agent.mdx
website/content/docs/release-notes/consul/v1_19_x.mdx
website/data/docs-nav-data.json

Docs to accompany ENT PR: https://github.com/hashicorp/consul-enterprise/pull/9002

snapshot agent: docs to deprecate top-level snapshot destinations

---

website/content/docs/connect/config-entries/index.mdx

Adds the API gateway configuration entry -- introduced as beta in Consul 1.15 and GA in Consul 1.16 -- to the list of configuration entries.
I've only backported to 1.17 and 1.18 as the page linked to did not exist in its current location prior to that.
[Modified page including API gateway config entry](https://consul-9kub2rqr6-hashicorp.vercel.app/consul/docs/connect/config-entries)

Add API gateway to index of configuration entries

---

website/content/docs/release-notes/consul-k8s/v1_3_x.mdx
website/content/docs/release-notes/consul/v1_17_x.mdx

A removal for support for legacy API Gateway was missed, so adding in the removal notice.

docs: Update release notes for 1.17.x for legacy api gateway removal

---

website/content/docs/k8s/connect/index.mdx

Updating the indentations for the kubernetes service account secrets.  The type wasn't being appropriately set.
Docs only

K8s v1 Multiport documentation indentation updates

---

.changelog/20866.txt
agent/grpc-external/services/serverdiscovery/watch_servers.go
agent/grpc-external/services/serverdiscovery/watch_servers_test.go
agent/xds/delta.go

This PR is best reviewed commit-by-commit.
It contains two separate improvements:
- Randomized shuffling of the server list returned by the WatchServers gRPC endpoint.
- The fix of a potential goroutine leak in the xDS code.

Various bug-fixes and improvements

---

.changelog/20868.txt
agent/agent.go
agent/rpcclient/health/health.go
agent/structs/structs.go

This PR fixes an issue where cross-dc RPCs were unable to utilize the streaming backend due to having the node name set. The result of this was the agent-cache being utilized, which would cause high cpu utilization and memory consumption due to the fact that it keeps queries alive for 72 hours before purging inactive entries.
This resource consumption is compounded by the fact that each pod in consul-k8s gets a unique token. Since the agent-cache uses the token as a component of the key, the same query is duplicated for each pod that is deployed.

Fix streaming RPCs for agentless.

---

.changelog/20876.txt
agent/consul/state/store_integration_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/subscription.go
agent/grpc-external/services/connectca/watch_roots.go
agent/grpc-external/services/serverdiscovery/watch_servers.go
agent/grpc-internal/services/subscribe/subscribe.go
agent/grpc-internal/services/subscribe/subscribe_test.go

Please see #20790 for reproduction steps.
Currently, when a client starts a blocking query and an ACL token expires within that time, Consul will return an "ACL not found" error with a 403 status code. However, sometimes if an ACL token is invalidated at the same time as the query's deadline is reached, Consul will instead return an empty response with a 200 status code.
This is because of the events being executed:
1. Client issues a blocking query request with timeout `t`.
2. ACL is deleted.
3. Server detects a change in ACLs and force closes the gRPC stream.
4. Client resubscribes with the same token and resets its state (view).
5. Client sees "ACL not found" error.
If ACL is deleted before step 4, the client is unaware that the stream was closed due to an ACL error and will return an …

Handle ACL errors consistently when blocking query timeout is reached.

---

.changelog/20715.txt
agent/agent.go
agent/config/builder_test.go
agent/consul/options.go
agent/consul/server.go
agent/dns_catalogv2_test.go
agent/dns_test.go

This PR default enables the V2 DNS server implementation for Consul 1.19. The experiment flag is changed to `v1dns` to be able to revert to the old implementation until there is more feedback on V2. 
**Notes:**
1. I noticed that RB added a gate to prevent these flags on secondary servers, but we definitely should allow this.
2. This is only for 1.19. I will create a separate PR against 1.18 to re-enable secondary servers using V2 DNS
* Existing `agent` tests are updated to run against both implementations.
* Any integration tests should now run against the new implementation.

[CE] feat(v2dns): enable v2 dns as default

---

.release/security-scan.hcl
scan.hcl

Per https://osv.dev/vulnerability/GO-2024-2631 this vulnerability is not present in the version currently used (go-jose/v3@3.0.3).
I'm suspicious that the `Introduced               0` version in the [OSV](https://osv.dev/vulnerability/GO-2024-2631) entry is why we're flagging the fix version as invalid. Just a guess.
This unblocks the Consul patch release currently underway.
CI continues to pass including Security Scan check.

security: triage false positive for go-jose/v3

---

.release/security-scan.hcl
scan.hcl

This PR is a manual backport of #20901.
---
Per https://osv.dev/vulnerability/GO-2024-2631 this vulnerability is not present in the version currently used (go-jose/v3@3.0.3).
I'm suspicious that the `Introduced               0` version in the [OSV](https://osv.dev/vulnerability/GO-2024-2631) entry is why we're flagging the fix version as invalid. Just a guess.
This unblocks the Consul patch release currently underway.
CI continues to pass including Security Scan check.
---
<details>
- c8d6b2528cdf861bff796d6d8e5a93e7e4c660b7 
</details>

Backport of security: triage false positive for go-jose/v3 into release/1.18.1

---

CHANGELOG.md

This is a CE+Ent release, so there should not be an "Enterprise" designation in the changelog entry.

Remove Enterprise callout from 1.18.1 changelog

---

.changelog/20897.txt
Dockerfile

Manual backport of https://github.com/hashicorp/consul/pull/20897/files

Update Dockerfile: backport to 1.15.x

---

website/content/docs/enterprise/network-segments/network-segments-overview.mdx

This link appears on the segments overview page as a "Read more..." but it is a link to the page you are viewing.  Removing it.

remove self-referencing link on network segments page

---

website/content/api-docs/libraries-and-sdks.mdx

The original [python-consul](https://github.com/python-consul/python-consul) is unmaintained with no activity for 6 years. The [python-consul2](https://github.com/poppyred/python-consul2) fork has had no activity for 3 years, whether it's commits or responding to PRs and issues.
[py-consul](https://github.com/criteo/py-consul) is a (now detached) fork of python-consul, maintained. It's compatible with more recent Python and Consul versions.
Fixes #20853

Documentation: update python SDKs list

---

.changelog/19881.txt
agent/xds/listeners.go
agent/xds/resources_test.go
agent/xds/testdata/listeners/terminating-gateway-with-peer-trust-bundle.latest.golden

> [!NOTE]
> This is a followup to #18959 which fixed the same problem specifically when using `http` protocol.
The terminating gateways needs to be able to handle TCP connections from peers which are not TLS-terminated at the local mesh gateway. This amounts to including the target SNI that downstreams from peers would use when building the TLS context for the terminating gateway.
<details>
<summary>Filter chain match before this change</summary>
```yaml
filter_chain_match: {
server_names: [
"destination.default.dc2.internal.b81d6ee2-8454-768e-0a06-38a62620f76a.consul"
]
}
```
</details>
<details>
<summary>Filter chain match after this change</summary>
```yaml
filter_chain_match: {
server_names: [
"destination.default.dc2.internal.b81d6ee2-8454-768e-0a06-38a62620f76a.consul", …
```

[NET-5772] Make tcp external service registered on terminating gw reachable from peered cluster

---

internal/mesh/internal/controllers/register.go

Removing registration of API Gateway controller since it is not fully implemented and the work has been deprioritized. 
* [ X ] appropriate backport labels added
* [  X ] not a security concern

NET-8524 Remove registation of api gateway controller

---

.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/test-integrations.yml

Follow-up to #20956
Nightly files do not require backport bc these only run on `main`, but backporting to update the `test-integrations` compatibility test env var.

ci: fix Envoy int test versions

---

.changelog/20977.txt
agent/consul/fsm/fsm.go
agent/consul/fsm/snapshot_ce_test.go

This operation would previously fail due to unconsumed bytes in the decoder buffer when reading the Ent snapshot (the first byte of the record would be misinterpreted as a type indicator, and the remaining bytes would fail to be deserialized or read as invalid data).
Ensure restore succeeds by decoding the ignored record as an `interface{}`, which will consume the record bytes without requiring a concrete target struct, then moving on to the next record.
Opened in response to a bug report by @sayap (thank you)
- Added new test to verify Ent->CE restore works as intended

fix: consume ignored entries in CE downgrade via Ent snapshot

---

website/content/docs/connect/gateways/api-gateway/configuration/routes.mdx

…Ref example yaml file
wrong indentation of
```yaml
to:
- group: ""
kind: Service
name: echo
```
will cause error
```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```
wrong indentation of 
```yaml
to:
- group: ""
kind: Service
name: echo
```
will cause error
```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```
* [✓] external facing docs updated
* [✓ ] not a security concern

FIX: wrong indentation of  to block in Example yaml

---

website/content/docs/ecs/deploy/bind-addresses.mdx
website/content/docs/ecs/deploy/configure-routes.mdx

Fixing broken links in the ECS documentation

Fixed broken link in the ECS documentation

---

testing/deployer/sprawl/internal/tfgen/templates/container-coredns.tf.tmpl
testing/deployer/sprawl/internal/tfgen/templates/container-pause.tf.tmpl
testing/deployer/sprawl/internal/tfgen/templates/container-proxy.tf.tmpl

There must have been a change to the Docker API that caused the behavior of the `NetworkMode` field to default differently. Each terraform run would detect that this field differed and it needed to do a full destroy and recreate to update it, but it wouldn't "stick".
The forwardproxy and pause containers CANNOT churn like this. They are expected to launch once for the life of the test environment. Destroying and recreating them was causing the exposed ports to change, and then the test runner was trying to use ports that were closed forever.
Example:
```
2024-05-03T14:52:41.184-0500 [DEBUG] Test_Ratelimit.tfgen.terraform:
-/+ resource "docker_container" "cslc-dc1-41a09620a19d81b9-forwardproxy" {
+ bridge                                      = (known after apply)
~ command …
```

deployer: ensure the proxy/dns/pause containers do not continually get replaced due to a change in a docker default

---

agent/xds/listeners.go

This narrows the scope of changes made previously in https://github.com/hashicorp/consul/pull/19881 which have unintentionally impacted http config on terminating gateway filter chains
Run the consul-k8s peering acceptance test with transparent proxy and CNI flavors using a build of this consul-enterprise branch. The test that is currently broken should pass with this build.
Example:
```shell
$ cd consul-k8s
$ make kind-small
$ cd acceptance
$ go test ./tests/peering -v -p 1 -timeout 20m -count=1 -run ^TestPeering_Connect$ \
-enable-multi-cluster -kube-contexts="kind-dc1,kind-dc2" -use-kind \
-enable-transparent-proxy -consul-image '<image here>'
```
There are existing xDS golden tests that cover TCP services. Those updates can be seen in https://github.com/hashicorp/consul/pull/19881. …

[NET-9098] Narrow scope of peering config on terminating gw filter chain to TCP services

---

agent/acl_test.go
agent/agent.go
agent/agent_endpoint.go
agent/agent_test.go
agent/consul/catalog_endpoint_test.go
agent/consul/client.go
agent/consul/client_serf.go
agent/consul/config.go
agent/consul/coordinate_endpoint_test.go
agent/consul/health_endpoint_test.go
agent/consul/leader_ce_test.go
agent/consul/rtt.go
agent/consul/rtt_test.go
agent/consul/server.go
agent/consul/server_ce.go
agent/consul/server_serf.go
agent/consul/state/coordinate.go
agent/consul/state/coordinate_test.go
agent/delegate_mock_test.go
agent/dns_test.go
agent/router/router.go
agent/router/router_test.go
command/rtt/rtt.go
internal/gossip/librtt/rtt.go
internal/gossip/librtt/rtt_test.go
internal/gossip/libserf/serf.go

This refactors and relocates the following packages to live under `internal/gossip` instead of either in the toplevel `lib` or `agent/consul`:
- `librtt` : related to serf coordinates
- `libserf` : random serf stuff

gossip: refactor some gossip related libraries into a central place

---

.github/workflows/build.yml

Follow-up to https://github.com/hashicorp/consul/pull/21035 to skip copying license file for linux packages.
Exclusion of copy actions in uses of `hashicorp/actions-go-build` are already handled separately in Ent.

[NET-9141] ci: skip LICENSE copy for Ent linux packages

---

.github/workflows/backport-assistant.yml
.release/versions.hcl

Configuration changes to use backport assistant with LTS support. These include:
- adding a manifest file for active releases 
- adding configuration to send backport to ENT repo

Backport assistant onboarding with LTS support #9224

---

.release/versions.hcl

Make it obvious that this file is only consumed from the default branch.
I only thought to add this just after the first PR was merged.

doc: add clarifying note to versions.hcl

---

docs/README.md

Add a newline to docs/README.md to test a backport without functional changes.
Uses BPA 0.4.1: https://github.com/hashicorp/consul/blob/zalimeni/test-bpa-0.4.1/.github/workflows/backport-assistant.yml#L22
This is a no-op change.

ci: test BPA 0.4.1 with no-op doc change

---

.github/workflows/backport-assistant.yml

To ease migration during this week's patch releases, temporarily use the more permissive version of BPA to allow old + new backport labels to be used simultaneously.
Partially reverts https://github.com/hashicorp/consul/pull/21091

ci: temporarily re-enable retired CE backport labels

---

website/content/docs/agent/config/cli-flags.mdx

Fix the rendering of the documentation for the `-ui-content-path` CLI flag.
The bookmark and subsequent text are not correctly rendered due to a missing space between a sentence and a code span.
> [-ui-content-path](https://developer.hashicorp.com/consul/docs/v1.16.x/agent/config/cli-flags#ui-content-path) ((#_uicontent_path)) - This flag provides the option to change the path the Consul UI loads from and will be displayed in the browser. By default, the path is `/ui/`, for example `http://localhost:8500/ui/`. Only alphanumerics, `-`, and \`` are allowed in a custom path.`/v1/` is not allowed as it would overwrite the API endpoint.
This commit fixes that issue so that the block is correctly rendered.
> [-ui-content-path](http://localhost:3000/consul/docs/agent/config/cli-flags#_ui_content_ …

docs: Fix docs for `-ui-content-path` CLI flag

---

agent/dns.go
agent/dns/discovery_results_fetcher.go
agent/health_endpoint_test.go
agent/structs/errors.go

With the enhancement to add the sameness group parameter to the health endpoint, the code that validated that `DefaultForFailover` was `true` when querying DNS was moved/deleted and needed to be readded in a different way.

additional changes to ensure sameness groups without DefaultForFailover can be used for DNS

---

website/content/docs/intro/index.mdx

This PR fixes #21109. It addresses two small typos in the [What is Consul?](https://developer.hashicorp.com/consul/docs/intro) introductory documentation.
This is my first contribution to Consul, so please let me know if there's anything I need to change. Thanks!
Not applicable
- [What is Consul?](https://developer.hashicorp.com/consul/docs/intro) documentation

docs: Fix two small typos in "What is Consul?" introduction

---

go.mod

Set toolchain directive to 1.22.3 to avoid compilation errors as the generated code since go was updated to 1.22.3 will not be compatible with older versions of go.

set go toolchain to go1.22.3

---

website/content/docs/k8s/connect/terminating-gateways.mdx

The upstream annotation is not required for external services defined using the ServiceDefaults Destinations. Created a Tab that separates the static client spec for ServiceDefaults Destinations and directly registered into catalog scenarios.
Preview: https://consul-git-docs-k8s-terminating-gw-hashicorp.vercel.app/consul/docs/k8s/connect/terminating-gateways#define-the-external-services-as-upstreams-for-services-in-the-mesh

Fixes annotation and introduce tabs for static-client spec

---

.github/workflows/build.yml

Disable CRT (and by extension, security scans and preview builds) for disabled CE branches.
Tested here: https://github.com/hashicorp/consul/actions/runs/9198792600
The skip on the top jobs trickles down into all the actual build jobs.
I'm not 100% certain this will work due to release branch config in `.release/ci.hcl` but it's faster to just try. Will follow up as needed.

chore: disable CRT for inactive release (1.17)

---

.github/workflows/build.yml

Disable CRT (and by extension, security scans and preview builds) for disabled CE branches.
Verified working on 1.17: https://github.com/hashicorp/consul/pull/21206 (CRT build skipped on this [commit](https://github.com/hashicorp/consul/commit/679abd54dfbfdce583f6b5072b0a6e3fbb15b57e))
The skip on the top jobs trickles down into all the actual build jobs.

chore: disable CRT for inactive release (1.15)

---

.github/workflows/build.yml

Disable CRT (and by extension, security scans and preview builds) for disabled CE branches.
Verified working on 1.17: https://github.com/hashicorp/consul/pull/21206 (CRT build skipped on this [commit](https://github.com/hashicorp/consul/commit/679abd54dfbfdce583f6b5072b0a6e3fbb15b57e))
The skip on the top jobs trickles down into all the actual build jobs.

chore: disable CRT for inactive release (1.16)

---

.release/security-scan.hcl
scan.hcl

Adding configuration to support go standard librairies (`stdlibs`) in security-scanner at the `repository` and `binary` level.

security: enable go stdlib scans

---

.github/workflows/nightly-test-integrations-1.19.x.yml

We should be testing against n-2 + LTS, so we need to replace 1.16 with 1.18.
Follow-up to #21219.
cc @DanStough in case I messed this up due to bad assumptions

Fix Consul versions in nightly 1.19 int tests

---

website/content/docs/release-notes/consul-k8s/v1_2_x.mdx
website/content/docs/release-notes/consul-k8s/v1_3_x.mdx
website/content/docs/release-notes/consul-k8s/v1_4_x.mdx

https://github.com/hashicorp/consul-k8s/pull/3813 was recently reverted due to broken service→service networking when deployed on OpenShift. This change is to document the consul-k8s releases that should not be consumed on OpenShift as a result and point to the fix in the subsequent patch releases.
> [!NOTE]
> This will need to be backported to 1.18, 1.17 and 1.16 in order to cover the corresponding docs for each version of consul-k8s that was impacted.
N/A
[Docs deployed with change
](https://consul-gpbinz31c-hashicorp.vercel.app/consul/docs/release-notes/consul-k8s/v1_4_x#known-issues)

[NET-9510] Document known OpenShift issue for consul-k8s 1.2.x, 1.3.x and 1.4.x

---

website/content/docs/release-notes/consul-k8s/v1_2_x.mdx

This PR generated from #21224 to be assessed for backporting.
---
https://github.com/hashicorp/consul-k8s/pull/3813 was recently reverted due to broken service→service networking when deployed on OpenShift. This change is to document the consul-k8s releases that should not be consumed on OpenShift as a result and point to the fix in the subsequent patch releases.
> [!NOTE]
> This will need to be backported to 1.18, 1.17 and 1.16 in order to cover the corresponding docs for each version of consul-k8s that was impacted.
N/A
[Docs deployed with change
](https://consul-gpbinz31c-hashicorp.vercel.app/consul/docs/release-notes/consul-k8s/v1_4_x#known-issues)

Backport of [NET-9510] Document known OpenShift issue for consul-k8s 1.2.x, 1.3.x and 1.4.x into release/1.16.x

---

website/content/docs/release-notes/consul-k8s/v1_2_x.mdx
website/content/docs/release-notes/consul-k8s/v1_3_x.mdx

This PR generated from #21224 to be assessed for backporting.
---
https://github.com/hashicorp/consul-k8s/pull/3813 was recently reverted due to broken service→service networking when deployed on OpenShift. This change is to document the consul-k8s releases that should not be consumed on OpenShift as a result and point to the fix in the subsequent patch releases.
> [!NOTE]
> This will need to be backported to 1.18, 1.17 and 1.16 in order to cover the corresponding docs for each version of consul-k8s that was impacted.
N/A
[Docs deployed with change
](https://consul-gpbinz31c-hashicorp.vercel.app/consul/docs/release-notes/consul-k8s/v1_4_x#known-issues)

Backport of [NET-9510] Document known OpenShift issue for consul-k8s 1.2.x, 1.3.x and 1.4.x into release/1.17.x

---

.changelog/21230.txt
acl/acl_ce.go
agent/discovery/query_fetcher_v1.go
agent/discovery/query_fetcher_v1_ce.go
agent/discovery/query_fetcher_v1_ce_test.go

tenancy was being validated on DNS queries from consul-dataplane to only allow partition to be set to an empty string.  It was not allow `default` in either case.

dns v2 - both empty string and default should be allowed for namespace and partition in CE

---

agent/metrics_test.go

This is one of our flakiest tests.  When it fails, there are lots of logs related to:
- initial warnings of `A cluster with 2 servers will provide no failure tolerance.`
- leadership not being able to be established
- each of the two servers each trying to start their own election but not being able to get a quorom
- index mismatches when contacting the other server and then stepping down
Basically an endless loop when their indexes get out of sync.  Changing the test to do have 3 servers to align with our recommendations and prevent this 2 server index / election loop.
An example can be seen here: https://github.com/hashicorp/consul-enterprise/actions/runs/9103918643/job/25026885402
You will want to View Raw Logs and search for `TestHTTPHandlers_AgentMetrics_LeaderShipMetrics`

update TestHTTPHandlers_AgentMetrics_LeaderShipMetrics to use 3 servers instead of 2 to allow quorum when leadership flails.

---

.github/CONTRIBUTING.md
contributing/INTERNALS.md
contributing/README.md

Add detail about Consul's backport policy w.r.t. LTS/CE.
Also update label docs and remove defunct redirect .md files.
Also backporting these changes to active CE branches for more visibility.

[NET-8953] docs: add backport policy section to CONTRIBUTING

---

.changelog/21251.txt
agent/consul/leader_registrator_v2.go
agent/xds/proxystateconverter/endpoints.go
agent/xds/proxystateconverter/listeners.go
agent/xds/response/response.go
agent/xds/testing.go
api/api.go

Resolves `Incorrect conversion between integer types` alerts to catch potential overflows.

security: resolve incorrect type conversions

---

api/go.mod
envoyextensions/go.mod
go.mod
test-integ/go.mod
test/integration/consul-container/go.mod
testing/deployer/go.mod
troubleshoot/go.mod
troubleshoot/go.sum

- Update submodule versions that were released
- Add missing replace directive to troubleshoot submodule
Propagate 1.19.x submodule updates made in https://github.com/hashicorp/consul/pull/21237 to `main`.

[NET-9445] chore: update submodule versions

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/nightly-test-integrations-1.18.x.yml
.github/workflows/nightly-test-integrations-1.19.x.yml
.github/workflows/nightly-test-integrations.yml

Several of our nightly cron jobs are actually running repeatedly back-to-back during the designated hour. Change the cron to run them once as intended.

ci: fix nightly cron schedules to run once

---

.github/workflows/nightly-test-integrations-1.19.x.yml
.github/workflows/nightly-test-integrations.yml

Also update a missed Consul version shift for deployer upgrade tests to match non-deployer tests matrix, and update public docs on `main`.
Follow-up to https://github.com/hashicorp/consul/pull/21277.

ci: fix a few missed Envoy version changes in latest bump

---

agent/structs/acl_templated_policy.go

We've discovered significant performance penalties using `html/template` that are seemingly made worse by the upgrade to Go 1.22. This PR switches to `text/template` instead since we aren't rendering HTML.

Use text/template instead of html/template for ACL template policy generation

---

.golangci.yml

We should never use html/template due to the performance penalty and the fact that we are highly unlikely to ever be generating HTML templates. This PR enforces a ban using the linter.

Configure linter to forbid use of html/template

---

CHANGELOG.md

Refresh changelog prior to release. Expecting this to sync to ENT before promoting the release.

docs: stage changelog for release

---

.release/versions.hcl

Remove 1.18 as active for CE and totally remove support for 1.16.

chore: update versions.hcl for 1.19.0 release

---

website/content/docs/release-notes/consul/v1_19_x.mdx

Document known issues related to #21325

docs: known issue with v2dns SRV requests

---

.changelog/21339.txt
agent/checks/alias.go

Resolves the following
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10370a28c]
goroutine 344 [running]:
[github.com/hashicorp/consul/agent/checks.(*CheckAlias).checkServiceExistsOnRemoteServer(0x140009f37c0](http://github.com/hashicorp/consul/agent/checks.(*CheckAlias).checkServiceExistsOnRemoteServer(0x140009f37c0), 0x140009f37d0)
[github.com/hashicorp/consul/agent/checks/alias.go:164](http://github.com/hashicorp/consul/agent/checks/alias.go:164) +0x18c
[github.com/hashicorp/consul/agent/checks.(*CheckAlias).runQuery.func1(0x1](http://github.com/hashicorp/consul/agent/checks.(*CheckAlias).runQuery.func1(0x1)?)
[github.com/hashicorp/consul/agent/checks/alias.go:237](http://github.com/hashicorp/con …
```

security: fix AliasCheck panic

---

website/content/docs/connect/proxies/envoy.mdx

Manual backport of https://github.com/hashicorp/consul/pull/21295
Also adds a note to check latest docs for LTS details, as the extended version range here somewhat contradicts the statement above it:
> As a policy, Consul will add support for a new major versions of Envoy in a Consul major release. Support for newer versions of Envoy will not be added to existing releases.

Backport of docs: simplify Envoy version support docs into release/1.15.x

---

website/content/docs/connect/proxies/envoy.mdx

Manual backport of https://github.com/hashicorp/consul/pull/21295

Backport of docs: simplify Envoy version support docs into release/1.18.x

---

.changelog/21342.txt
agent/kvs_endpoint.go

Sanitizes the user input before returning it using %v instead of directly concatenating the string 
https://github.com/hashicorp/consul-enterprise/security/code-scanning/17

[Security] Close cross scripting vulnerability 

---

.github/workflows/nightly-test-1.18.x.yaml
.github/workflows/nightly-test-integrations-1.18.x.yml

This version is no longer active in CE.
c.f. https://github.com/hashicorp/consul/pull/21242/files

ci: skip 1.18 nightly int tests on CE

---

.github/scripts/check_skip_ci.sh
.github/workflows/go-tests.yml
.github/workflows/security-scan.yml
.github/workflows/test-integrations.yml

Ensure files are split rather than compared as a single list for accuracy and easier debugging. This was sneaky and it took me a while to notice even after testing some other changes!
Also adopt minor changes and file name from introduction of similar check `consul-dataplane` and `consul-k8s` for clarity.

ci: fix file parsing in conditional-skip script

---

website/content/docs/k8s/deployment-configurations/argo-rollouts-configuration.mdx
website/data/docs-nav-data.json

VERCEL LINK: https://consul-31z9s3g9y-hashicorp.vercel.app/consul/docs/k8s/deployment-configurations/argo-rollouts-configuration

Create documentation for Argo Rollouts Plugin.

---

.github/workflows/build.yml

For cost reasons, we can cross-compile macos binaries on linux. Historically we didn't do this because of a problem with Go that has since been resolved: https://github.com/hashicorp/consul/issues/3267.
This step removes the verification of Darwin binaries. I believe this is acceptable since the vast majority of users and on Linux and Windows. Developers will naturally test the Darwin build during the development cycle.

build: cross compile darwin builds

---

agent/checks/alias.go

Updated `checkServiceExistsOnRemoteServer` to ensure there are services returned from the specified node before proceeding with the service matcher.
Resolves the following
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10370a28c]
goroutine 344 [running]:
[github.com/hashicorp/consul/agent/checks.(*CheckAlias).checkServiceExistsOnRemoteServer(0x140009f37c0](http://github.com/hashicorp/consul/agent/checks.(*CheckAlias).checkServiceExistsOnRemoteServer(0x140009f37c0), 0x140009f37d0)
[github.com/hashicorp/consul/agent/checks/alias.go:164](http://github.com/hashicorp/consul/agent/checks/alias.go:164) +0x18c
[github.com/hashicorp/consul/agent/checks.(*CheckAlias).runQuery.func1(0x1](http://github.com/hash …
```

security: fix AliasCheck panic (update)

---

.changelog/21519.txt
agent/consul/kvs_endpoint.go
agent/consul/state/txn.go
agent/consul/state/txn_test.go
agent/consul/txn_endpoint.go
agent/consul/txn_endpoint_test.go

There are two entry points into the state store:
1. Through RPCs
2. Indirectly, through Raft FSM Applies
In the latter case, errors are not acknowledged because the log must be processed by Consul. It is possible in this case that if a future version of Consul is using syntax, such as Txn API Verbs, that the current version does not understand, it will fail to apply successfully, causing a divergence with other servers.
This PR makes two types of changes:
1. Panics are introduced for unknown verb types to prevent state store divergence
1. Validation at the endpoint layer to make sure there is feedback to user for invalid verbs and this cannot be used for a DOS attack.

fix(txn): validate verbs

---

.github/workflows/nightly-test-integ-peering_commontopo.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/nightly-test-integrations-1.18.x.yml
.github/workflows/nightly-test-integrations-1.19.x.yml
.github/workflows/nightly-test-integrations.yml
.github/workflows/reusable-get-envoy-versions.yml
.github/workflows/reusable-get-go-version.yml
.github/workflows/test-integrations.yml
Makefile
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
envoyextensions/xdscommon/ENVOY_VERSIONS
envoyextensions/xdscommon/envoy_versioning.go
envoyextensions/xdscommon/envoy_versioning_test.go
envoyextensions/xdscommon/proxysupport.go
envoyextensions/xdscommon/proxysupport_test.go
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

Consolidate Envoy versions into a single canonical file to enable simpler management and avoid missed updates in the future.
This effort is motivated by repeated experience struggling to ensure that we updated Envoy "everywhere" we needed to. Even moreso than managing our Go versions, there's a significant amount of sprawl when it comes to Envoy, and addressing that will enable us to more confidently update versions as well as automate the toil of doing so when new releases are available.
> Note that if it weren't for returning full x.y.z Envoy versions in `v1/agent/self` [output](https://github.com/hashicorp/consul/blob/c18c911ac8ec1ce9b7ba1e5a00cb38201910cf9a/agent/agent_endpoint.go#L99), I'm pretty sure we could just store the "major" x.y versions going forward and dynamically test …

[NET-5622] build: consolidate Envoy version management

---

.changelog/21524.txt
envoyextensions/xdscommon/ENVOY_VERSIONS

Upgrade envoy module dependencies to version 1.27.7, 1.28.5 and 1.29.7 or higher to resolve CVE-2024-39305
🤖 tests pass

[NET-10290] Update ENVOY_VERSIONS

---

.github/scripts/verify_artifact.sh

CentOS 7 has entered End of Life as of June 30, 2024. We aren't using CentOS 7 for builds but are using it for verifying artifacts for some architectures. In order for artifact verification to continue working, we must upgrade. I'm switching to `debian:12` which is supported through June 10, 2028.

Use debian:12 instead of centos:7 for artifact verification

---

.github/scripts/verify_artifact.sh
.github/scripts/verify_rpm.sh

The latter is no longer resolvable since CentOS 7 is EOL. Note that part of this PR is reverting #21527 
There's no way to fully test the script in the right environment without merging; however, since the verify step is already broken, merging is low risk as we're in no worse shape.

Use vault.centos.org instead of mirror.centos.org

---

.changelog/21382.txt
agent/consul/state/catalog.go

Previously we were incorrectly using the terminating gateway enterprise meta for linked services when we should be using the linked services ent meta

[NET-10246] use correct enterprise meta for service name for LinkedService

---

website/content/docs/connect/cluster-peering/index.mdx

[KV replication](https://developer.hashicorp.com/consul/tutorials/production-multi-cluster/multi-cluster-reference-architecture#replication) can happen only with third-party tool [consul-replicate](https://github.com/hashicorp/consul-replicate). Clarifying the documentation by removing the entry from the comparison table.
N/A
- https://developer.hashicorp.com/consul/tutorials/production-multi-cluster/multi-cluster-reference-architecture#replication
- https://github.com/hashicorp/consul-replicate

docs: Clarify cluster peering vs WAN federation comparison

---

.github/workflows/backport-assistant.yml

This is necessary to allow backporting changes to GHA workflows, and mirrors the [token use in the CE->Ent merge workflow](https://github.com/hashicorp/consul-enterprise/blob/bd059e81e88e1a7a2a3b5d81c2c1c238d24c5a40/.github/workflows/oss-merge.yml#L21).
Marking this PR for backport should verify the fix, since this PR is itself modifying GHA workflows.

ci: use workflow-scoped GH PAT for backports

---

agent/dns/router.go

In the DNS subsystem, the router should pass of errors to the response generator.  The response generator already has logic to log things at the right level and for No Data error, this is the debug level.  This PR removes logging that occurs just before the error is passed off to response generator which is logging everything as an error which creates large amount of noise in logs.
https://github.com/hashicorp/consul/issues/21508

NET-10610 - stop logging no data as errors in DNS lookups

---

.release/security-scan.hcl

CVE-2024-7264 is recently reported and is blocking our dev builds from successfully completing. As there is not currently a fix available I am suppressing the CVE until a fix is made available.

Suppress CVE-2024-7264

---

website/content/docs/k8s/compatibility.mdx

Remove note that OpenShift 4.16 is not yet available, now that it's been released.
It will be added to the matrix in a future update once we've tested compatibility across eligible `consul-k8s` versions.
1.18 PR: https://github.com/hashicorp/consul/pull/21601

docs: Update compatibility.mdx for OpenShift

---

.changelog/21604.txt
agent/xds/clusters.go
agent/xds/jwt_authn_ce.go

JWT clusters were previously not being created correctly, this adds the plumbing to handle this in the enterprise fork

[NET-10719] Fix cluster generation for jwt clusters for external jwt providers

---

website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-k8s.mdx
website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-vms.mdx

Manual backport of https://github.com/hashicorp/consul/pull/20800
---
<details>
- 498c0857fbc971161613b4893105ed0fc006129b  - 61e8343d2e63092ed6296ff6a35daba0a8b2a48a  - 489b8200eccc17a89fb8af9bbf5cb9faa15ffce8  - 7a1cf1ad99f59b2fb42f3074e5efbf34a3c3d83d  - ad5f52c52a44acf2a3c5b0a9cba12345c3dd3db3  - a13c7b648177c36f04946c915145559cd1c1c251  - 448ab6af1d10096747562fffb3e8f8abaf581459  - 361c10025c317ac610ce465b33957bf2050e1b53  - a643a24674c6651e4f6f55c810313bce4e485ed9  - 904112ce391d5ff231cf478804b4518b740b6f8d  - 5f19970c931ef5506d920c7f1abd7a99476a6e25  - 6fad695fa60fde145e648cb6f049c6eba9162467  - a19cf381be5e922b3be0ccf5f5722804271f7e6f  - 04a39d8d93982087fd1c23b18cf3a951b666638c  - 48ec67ebabe1e0031ca02bd4b028b517c96d7fe7  - …

manual backport of updating jwt docs

---

agent/dns_service_lookup_test.go

`TestDNS_ServiceLookup_ARecordLimits` is one of our longest running tests.  
It's average runtime in CI over the last 3 months is 1min 45 secs.
Locally on a mac M1, it performs in 1 min 11 seconds:
The reason why is that for every test case it spawns a new TestAgent.  This is **112 test agents** getting spawned, taking up ports, file descriptors, etc.  
Re-arranging this test so that test agents are only created when the agent config changes, reduces it to 7 Test Agents getting created.  (There was also a category of tests that could be removed as duplicates that removed 28 of the test agent).
This is the test results locally now that finish in 10 secs:

Fix TestDNS_ServiceLookup_ARecordLimits so that it only creates test agents the minimal amount of time

---

website/content/docs/k8s/compatibility.mdx

Remove note that OpenShift 4.16 is not yet available, now that it's been released.
It will be added to the matrix in a future update once we've tested compatibility across eligible `consul-k8s` versions.

docs: Update compatibility.mdx for OpenShift (1.18.x)

---

website/content/docs/connect/gateways/api-gateway/configuration/gatewaypolicy.mdx
website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-k8s.mdx

Gateway policy docs incorrectly specify the group for the target ref to be `gateway.networking.kubernetes.io` it should be `gateway.networking.k8s.io/v1beta1`

[NET-10774] Fix Group Reference in GatewayPolcy Docs

---

build-support/functions/10-util.sh
build-support/scripts/consul-module-versions-in-consul.sh

This PR is manual from #21635.
---
This is used during releases to know which bumps need to be made.  Will manually backport to 1.15, 1.17, and 1.18.
Usage: 
```
$ ./build-support/scripts/consul-module-versions-in-consul.sh
Module versions for directory: '.':
--------------
github.com/hashicorp/consul/api v1.29.1 => ./api
add build support script to print out the submodule versions required in other submodules
github.com/hashicorp/consul/envoyextensions v0.7.0 => ./envoyextensions
github.com/hashicorp/consul/proto-public v0.6.1 => ./proto-public
github.com/hashicorp/consul/sdk v0.16.1 => ./sdk
github.com/hashicorp/consul/troubleshoot v0.6.1 => ./troubleshoot
--------------
Module versions for directory: 'api':
-------------- …
```

Backport of add build support script to print out the submodule versions required in other submodules into release/1.17.x

---

build-support/functions/10-util.sh
build-support/scripts/consul-module-versions-in-consul.sh

This PR is manual from #21635.
---
This is used during releases to know which bumps need to be made.  Will manually backport to 1.15, 1.17, and 1.18.
Usage: 
```
$ ./build-support/scripts/consul-module-versions-in-consul.sh
Module versions for directory: '.':
--------------
github.com/hashicorp/consul/api v1.29.1 => ./api
add build support script to print out the submodule versions required in other submodules
github.com/hashicorp/consul/envoyextensions v0.7.0 => ./envoyextensions
github.com/hashicorp/consul/proto-public v0.6.1 => ./proto-public
github.com/hashicorp/consul/sdk v0.16.1 => ./sdk
github.com/hashicorp/consul/troubleshoot v0.6.1 => ./troubleshoot
--------------
Module versions for directory: 'api':
-------------- …
```

Backport of add build support script to print out the submodule versions required in other submodules into release/1.18.x

---

.github/workflows/nightly-test-integrations-1.18.x.yml

This branch is no longer active on CE, so its jobs should all be skipped via check-ent. One job was missed so it fails nightly right now.

ci: fix workflow graph for 1.18 Envoy int tests

---

website/content/docs/connect/config-entries/mesh.mdx

In backporting the ValidateClusters change to api and protos a docs change also inadvertently got pulled back.

revert change to website/content/docs/connect/config-entries/mesh.mdx

---

agent/config/builder.go
agent/config_endpoint_test.go
agent/consul/config_endpoint.go
agent/consul/config_replication_test.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
api/config_entry_test.go
command/config/write/config_write_test.go

- Add validation for the `protocol` field for `service-defaults`. With this change, the CLI and HTTP API only allows values listed in the [documentation](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-defaults#protocol).
- Tested locally in dev mode for both HTTP API (`v1/config`) and CLI `config write`
Ticket: https://hashicorp.atlassian.net/browse/NET-5912

NET-5912/service-defaults protocol validation

---

test/integration/connect/envoy/run-tests.sh

k8s.gcr.io has been migrated to registry.k8s.io for several years now, and the old registry is being shut down, causing image pull failures.
Update to target the new registry when pulling the pause image used in Envoy integration tests.

test: update pause Docker image in Envoy int tests

---

go.mod
test-integ/go.mod
test/integration/consul-container/go.mod
troubleshoot/go.mod

The following tags have been released and this PR updates 1.18.x with the recent versions:
- [api/v1.28.4](https://github.com/hashicorp/consul/releases/tag/api%2Fv1.28.4)
- [envoyextensions/v0.6.2](https://github.com/hashicorp/consul/releases/tag/envoyextensions%2Fv0.6.2)
- [troubleshoot/v0.6.5](https://github.com/hashicorp/consul/releases/tag/troubleshoot%2Fv0.6.5)

Update 1.18.x after re-publishing modules

---

api/go.mod
envoyextensions/go.mod
troubleshoot/go.mod

Adding the module retractions that were added this release period to main.

add module retractions

---

.github/workflows/test-integrations.yml

Our branch protection rules expect this...and we have no reason not to run these in release branches and on main.
Will manually backport to 1.15, 1.17, and 1.18.

run integration tests on push in main and release/*

---

.github/workflows/test-integrations.yml

This PR is manually generated from #21666.
---
Our branch protection rules expect this...and we have no reason not to run these in release branches and on main.
Will manually backport to 1.15, 1.17, and 1.18.
---
<details>
- cb63abf7a7f1597fdd00a55af0d49ecb04ff4d31  - 40a95ae7599fffb29dd64b05f80defbdaae0f6e7 
</details>

Backport of run integration tests on push in main and release/* into release/1.17.x

---

.github/workflows/test-integrations.yml

This PR is manually generated from #21666.
---
Our branch protection rules expect this...and we have no reason not to run these in release branches and on main.
Will manually backport to 1.15, 1.17, and 1.18.
---
<details>
- cb63abf7a7f1597fdd00a55af0d49ecb04ff4d31  - 40a95ae7599fffb29dd64b05f80defbdaae0f6e7 
</details>

Backport of run integration tests on push in main and release/* into release/1.18.x

---

.github/workflows/test-integrations.yml

This PR is manually generated from #21666.
---
Our branch protection rules expect this...and we have no reason not to run these in release branches and on main.
Will manually backport to 1.15, 1.17, and 1.18.
---
<details>
- cb63abf7a7f1597fdd00a55af0d49ecb04ff4d31  - 40a95ae7599fffb29dd64b05f80defbdaae0f6e7 
</details>

Backport of run integration tests on push in main and release/* into release/1.15.x

---

agent/consul/leader.go
agent/consul/replication.go

Fixes https://github.com/hashicorp/consul/issues/11377#issuecomment-966107284
When the leader changes the replication metrics on the old leader (now follower) keeps reporting 1. This PR fixes that issue.

Set replication metric to 0 when losing leadership

---

website/content/docs/security/acl/index.mdx

Remove links to tutorials that no longer exist. The tutorial links redirect back to the ACL overview page.
[Deploy preview](https://consul-git-ce709-hashicorp.vercel.app/consul/docs/security/acl)
Fixes Jira [CE-709](https://hashicorp.atlassian.net/browse/CE-709)
[CE-709]: https://hashicorp.atlassian.net/browse/CE-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Docs CE-709: Remove circular links

---

website/content/docs/security/acl/index.mdx

Manual backport of Docs CE-709: Remove circular links
Remove links to tutorials that no longer exist and redirect back to the ACL overview page.

Backport of Docs CE-709: Remove circular links (#21685) into release/1.18.x

---

website/content/docs/security/acl/index.mdx

Manual backport of Docs CE-70: Remove circular links
Remove links to tutorials that no longer exist and redirect back to the ACL overview page.

Backport of Docs CE-709: Remove circular links (#21685) into release/1.17.x

---

website/content/docs/security/acl/index.mdx

Manual backport of Docs CE-70: Remove circular links
Remove links to tutorials that no longer exist and redirect back to the ACL overview page.

Backport of Docs CE-709: Remove circular links (#21685) into release/1.15.x

---

.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/nightly-test-integrations-1.18.x.yml
.github/workflows/nightly-test-integrations-1.19.x.yml
.github/workflows/test-integrations.yml

Correctly set the the version of Consul built by the `dev-build` job, which is then copied into the Consul dev image used in integration tests.
This was causing failures starting sidecar proxies via `consul connect envoy` due to a mismatch between the (incorrect) Consul binary's supported Envoy versions and the (correct) Envoy version under test.
Also add debug log uploads to each int test so we can more easily diagnose this sort of failure in the future, as it was entirely hidden in test output.
What's most unintuitive about this, is that the Consul Docker image used as a base for the tests was correct - it was only the _replaced binary_ in that image that was wrong.
This change does not need to be backported since it's made within scheduled workflows run from `main`. Note that only 1.19 …

test: fix Envoy int tests and add container logs

---

.github/workflows/ce-merge-trigger.yml

Sync needs to be disabled for release branches that are not supported in CE.  This causes PRs with large merge conflicts for dependencies.  We can come up with a more elegant solution later that possibly reads `.releases/version.hcl` but for now this will stop the syncs.

exclude release branches for 1.15 thru 1.18

---

website/content/docs/k8s/helm.mdx

[release/1.19.x] autogenerate helm docs

---

.changelog/21704.txt
agent/http.go
agent/http_test.go

Added middleware to ensure that content-type header is always set to mitigate XSS vulnerability.
- Updated unit tests to add additional checks for content-type header
- Vercel should deploy UI with no errors

[Security] Fix XSS Vulnerability where content-type header wasn't explicitly set

---

.changelog/21703.txt
agent/xds/clusters.go
agent/xds/clusters_test.go

When creating an envoy cluster the default [DNS Lookup Family](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-dns-lookup-family) defaults to [AUTO](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#enum-config-cluster-v3-cluster-dnslookupfamily), for inter-cluster communication this is not an issue but when creating a cluster that access external sources (like we do for `JWTProviders`) this can cause an issue. The `AUTO` setting prefers using `ipv6`, so if a user has a cluster that is not setup to handle ipv6 they will get an ipv6 address back for the external source and will be unable to connect.
To handle this we will be using the `V4_PREFERRED` lookup family when …

[NET-10952] fix cluster dns lookup family to gracefully handle ipv6

---

.github/workflows/test-integrations.yml
Makefile
test-integ/connect/snapshot_test.go
testing/deployer/sprawl/sprawltest/test_test.go
testing/deployer/topology/default_versions.go

Found several isntances of dataplane 1.3 hardcoded. Updating all of them to 1.6 and adding todos to remove hardcoding.

Hard update all 1.3 dataplane to 1.6

---

.changelog/21729.txt
.release/security-scan.hcl
Dockerfile
test/integration/connect/envoy/Dockerfile-tcpdump
test/integration/connect/envoy/helpers.bash

Fixes several CVEs by upgrading dependencies via base image upgrade.
Tested locally from [one-off Docker CI build](https://github.com/hashicorp/consul/actions/runs/10854208959/job/30124439601):
```shell
❯ scan container ./consul_default_linux_arm64_1.19.3-dev_c5ca319b156ce0bbb67d79eaa1bbc80113ae3557.docker.tar
✓ Scanned file:{path:"/Users/michael.zalimeni/workspace/security-scanner/consul_default_linux_arm64_1.19.3-dev_c5ca319b156ce0bbb67d79eaa1bbc80113ae3557.docker.tar"} in 59.8s - no results found
```

security: update alpine base image to 3.20

---

.github/workflows/security-scan.yml

Removing the conditional-skip step and updating action versions.
If the CI runs the scan, we should be good.

ci: fix security-scanner conditional skip

---

.github/scripts/check_skip_ci.sh

In some environments, the script will not fail despite `SKIP_CHECK_BRANCH` being unset, leading to the script explicitly skipping CI when it should fail fast.
**Meta-comment: we should consider transitioning to [paths-ignore](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore). Even though it'd be a bit more copypasta, the upside is we can't silently skip and pass tests + security scans by accident if a future bug or misconfiguration occurs.**
Example script failure -> skipped CI: https://github.com/hashicorp/consul/actions/runs/10851790913/job/30116333377#step:3:5 (this workflow no longer uses the script, and relies on `paths-ignore` instead).
```shell
❯ .github/scripts/check_skip_ci.sh; echo $? …
```

ci: fix CI skip script hole

---

.release/versions.hcl

Commas are not expected after HCL blocks. This is causing parsing in BPA to fail and may interfere w/ other release-related workflows.

ci: fix versions.hcl parsing by removing extraneous comma

---

.github/workflows/test-integrations.yml

Update Vault/Nomad versions to ensure we're testing the latest versions .
Nomad's latest supported nomad-version: nomad-version: ['v1.8.3', 'v1.7.11', 'v1.6.15']
[Releases · hashicorp/nomad](https://github.com/hashicorp/nomad/releases) 
Vault's latest supported vault-version: [] Grabbed the latest from the changelog- [vault/CHANGELOG.md at main · hashicorp/vault](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md)

Update test-integrations.yml to capture latest versions of Nomad and Vault

---

CHANGELOG.md

Stage rc release

---

website/content/api-docs/catalog.mdx

We accept a Partition field for deregistering nodes and it is required if you're trying to deregister a node that only exists in a particular partition.

Add partition field for catalog deregister docs

---

website/content/docs/services/discovery/dns-forwarding/enable.mdx

The original commands fail when being directly pasted in a shell.

docs: Add missing `&&` in DNS forwading tutorial

---

.github/workflows/nightly-test-integrations-1.20.x.yml
test/integration/consul-container/test/upgrade/README.md
test/integration/consul-container/test/upgrade/peering/peering_http_test.go

Upgrade tests targeting Consul `1.20.0-rc1` are currently failing. This is due to the Envoy version not being pinned properly for this particular set of tests.
In addition, I updated the docs where I caught some typos and missing line breaks.
Run the nightly integration tests using this branch ([example](https://github.com/hashicorp/consul/actions/runs/11299034017))
See above for a run of the failing upgrade tests that pass when using this branch.

Upgrade test improvements for 1.20.x

---

.gitignore

Also prevent future re-commits of this submodule path by adding to .gitignore.
Removes submodule added in #21802.

chore: remove unintentionally committed consul-k8s submodule

---

website/content/docs/k8s/dns/enable.mdx
website/content/docs/k8s/dns/views/enable.mdx
website/content/docs/k8s/dns/views/index.mdx
website/content/docs/services/discovery/dns-cache.mdx
website/content/docs/services/discovery/dns-forwarding/index.mdx
website/content/docs/services/discovery/dns-overview.mdx
website/data/docs-nav-data.json
website/redirects.js

Follow-up since original backport #21828 failed. 
I've also removed unneeded changes to `version/VERSION` and addition of `consul-k8s` submodule since those weren't part of the intended changeset.

Manual backport of docs: Consul DNS views on Kubernetes (#21802) Beta into release/1.20.x

---

api/config_entry_intentions.go
api/config_entry_mesh.go
command/helpers/helpers_test.go

This feature is available in Consul CE 1.20.1 and Consul Enterprise 1.19.3, 1.18.4, and 1.15.15.
Adds fields for consumption in `consul-k8s` when used with a supported version of Consul. These will be available in new patch releases of `api` corresponding with the latest tag for each Consul release version.
Enterprise changelogs will be added with backports of original change.
Full feature PR: https://github.com/hashicorp/consul/pull/21816

[NET-1151 NET-11228] api: Add fields for HTTP request normalization and L7 intentions header additions (1.19)

---

api/config_entry_intentions.go
api/config_entry_mesh.go
command/helpers/helpers_test.go

This feature is available in Consul CE 1.20.1 and Consul Enterprise 1.19.3, 1.18.4, and 1.15.15.
Adds fields for consumption in `consul-k8s` when used with a supported version of Consul. These will be available in new patch releases of `api` corresponding with the latest tag for each Consul release version.
Enterprise changelogs will be added with backports of original change.
Full feature PR: https://github.com/hashicorp/consul/pull/21816

[NET-1151 NET-11228] api: Add fields for HTTP request normalization and L7 intentions header additions (1.18)

---

api/config_entry_intentions.go
api/config_entry_mesh.go
command/helpers/helpers_test.go

This feature is available in Consul CE 1.20.1 and Consul Enterprise 1.19.3, 1.18.4, and 1.15.15.
Adds fields for consumption in `consul-k8s` when used with a supported version of Consul. These will be available in new patch releases of `api` corresponding with the latest tag for each Consul release version.
Enterprise changelogs will be added with backports of original change.
Full feature PR: https://github.com/hashicorp/consul/pull/21816

[NET-1151 NET-11228] api: Add fields for HTTP request normalization and L7 intentions header additions (1.15)

---

.release/security-scan.hcl

Suppressing CVE-2024-9143 because the fix is listed as deferred and to unblock our builds.

Suppress CVE-2024-9143

---

website/content/docs/connect/proxies/envoy.mdx

Update matrices and clarify statements as to when Consul expands support to new major versions of Envoy and Consul dataplane in light of Consul LTS or Envoy EOL status.

docs: clarify Envoy and dataplane LTS support policy

---

website/content/docs/connect/proxies/envoy.mdx

Update Envoy matrices to include latest set of releases for consul + consul-dataplane

Update Envoy compatibility matrices to include consul 1.20.x and dataplane 1.6.x

---

.github/workflows/nightly-test-integrations.yml

Nightly integrations tests are currently failing presumably due to unsupported envoy version in the test. 
- CI passes

Upgrade envoy version in nightly integration tests

---

website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/security.mdx
website/content/docs/upgrading/upgrade-specific.mdx

- Add notes on feature availability tied to specific fix versions
- Add missing 1.20 upgrade entry
- Remove erroneous 1.17 upgrade entry (version DNE)
- Add missing HCL variant for service intentions config
Follow-up to https://github.com/hashicorp/consul/pull/21816 to clarify feature availability in CE and Enterprise.
These changes are incorporated into the version-aligned backports of the original docs changes (linked below). I'll incorporate any feedback into those before merging.

[NET-1151 NET-11046] docs: clarify request normalization and L7 headers feature availability

---

website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/intentions/index.mdx
website/content/docs/connect/security.mdx
website/content/docs/security/security-models/core.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Docs-only follow-up to https://github.com/hashicorp/consul/pull/21816, and backport of https://github.com/hashicorp/consul/pull/21855, combined into a single PR for clarity.

[NET-1151 NET-11046] docs: Add request normalization, L7 headers options, and security guidance to release/1.19.x

---

website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/intentions/index.mdx
website/content/docs/connect/security.mdx
website/content/docs/security/security-models/core.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Docs-only follow-up to https://github.com/hashicorp/consul/pull/21816, and backport of https://github.com/hashicorp/consul/pull/21855, combined into a single PR for clarity.

[NET-1151 NET-11046] docs: Add request normalization, L7 headers options, and security guidance to release/1.15.x

---

website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/intentions/index.mdx
website/content/docs/connect/security.mdx
website/content/docs/security/security-models/core.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Docs-only follow-up to https://github.com/hashicorp/consul/pull/21816, and backport of https://github.com/hashicorp/consul/pull/21855, combined into a single PR for clarity.

[NET-1151 NET-11046] docs: Add request normalization, L7 headers options, and security guidance to release/1.18.x

---

.changelog/21655.txt
agent/xds/clusters.go

Currently when Consul generates configuration for Envoy, it behaves the same for both `LOGICAL_DNS` and `STRICT_DNS` [discovery types](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery) and provides only a single endpoint to Envoy in both modes. This means that when multiple hostnames are configured in `STRICT_DNS` mode, requests are not load balanced over all available hosts.
This change configures Envoy with all available hostnames when the discovery type is set to `STRICT_DNS`. In `LOGICAL_DNS` mode, Envoy [supports only a single endpoint](https://github.com/envoyproxy/envoy/blob/93099c6e9ea24eeb22a41d477d821beab164777f/source/extensions/clusters/logical_dns/logical_dns_cluster.cc#L175) and so the current behaviour of Consul remains unchanged. …

Allow multiple endpoints in Envoy clusters configured with hostnames

---

website/content/docs/connect/proxies/envoy.mdx

Manual backport of https://github.com/hashicorp/consul/pull/21337.
Original PR description below:
---------------
Update matrices and clarify statements as to when Consul expands support to new major versions of Envoy and Consul dataplane in light of Consul LTS or Envoy EOL status.

Backport of docs: clarify Envoy and dataplane LTS support policy into release/1.18.x

---

website/content/docs/connect/proxies/envoy.mdx

Manual backport of https://github.com/hashicorp/consul/pull/21337.
Original PR description below:
---------------
Update matrices and clarify statements as to when Consul expands support to new major versions of Envoy and Consul dataplane in light of Consul LTS or Envoy EOL status.

Backport of docs: clarify Envoy and dataplane LTS support policy into release/1.19.x

---

.github/scripts/verify_rpm.sh

backport to 1.18.5 - centos logic to point to vault.centos.org for centos:7 since it is EOL

---

.github/scripts/verify_rpm.sh

backport to 1.18.x - centos logic to point to vault.centos.org for centos:7 since it is EOL

---

.release/security-scan.hcl
scan.hcl

Adding support for RedHat UBI images scans to cover more type of container images and fixing a typo.
Ref: [PSP-2287](https://hashicorp.atlassian.net/browse/PSP-2287)
https://github.com/hashicorp/security-scanner/pull/918
[PSP-2287]: https://hashicorp.atlassian.net/browse/PSP-2287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(security-scanner): add support for Red Hat UBI images and fix typo

---

.changelog/21951.txt
go.mod
go.sum

Update package to resolve CVE-2024-51744
- CI passes
https://pkg.go.dev/vuln/GO-2024-3250

Update JWT to resolve CVE-2024-51744

---

.changelog/21871.txt
agent/proxycfg/api_gateway.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/ingress_gateway.go
agent/proxycfg/state.go
agent/proxycfg/upstreams.go

This PR unify the way we cancel `PeerUpstreamEndpoints` and `UpstreamPeerTrustBundles` and add more safeguards to only cancel those watches when no other data needs them. 
This is important because those watches could be shared by different upstreams in the scenario where multiple upstreams have the same target for `PeerUpstreamEndpoints` and in the case where multiple targets belong to the same Peer for `UpstreamPeerTrustBundles`. To avoid canceling a watch for those data sources while another upstream need them, we loop through all the upstreams and determine which watch is still needed and only cancel those which are not.

Fix PeerUpstreamEndpoints and UpstreamPeerTrustBundles to only Cancel watch when needed, otherwise keep the watch active

---

.changelog/21909.txt
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
lib/stringslice/stringslice.go
lib/stringslice/stringslice_test.go

The `consul-k8s` endpoints controller issues catalog register and manual virtual ip updates without first checking to see if the updates would be effectively not changing anything. This is supposed to be reasonable because the state store functions do the check for a no-op update and should discard repeat updates so that downstream blocking queries watching one of the  resources don't fire pointlessly (and CPU wastefully).
While this is true for the check/service/node catalog updates, it is not true for the "manual virtual ip" updates triggered by the `PUT /v1/internal/service-virtual-ip`. Forcing the connect injector pod to recycle while watching some lightly modified FSM code can show that a lot of updates are of the `update list of ips from [A] to [A]`. Immediately following this stray …

state: ensure that identical manual virtual IP updates result in not bumping the modify indexes

---

.release/security-scan.hcl

Suppress alpine image CVEs that are currently unresolved. 
- CI Passes
https://hub.docker.com/layers/library/alpine/3.20/images/sha256-dea9f02e103e837849f984d5679305c758aba7fea1b95b7766218597f61a05ab?context=repo

Add alpine image cves to suppress list

---

.changelog/21930.txt
agent/http.go
agent/http_test.go
api/api.go
api/api_test.go
api/content_type.go

- Modified existing `ensureContentTypeHeader` middleware to set the response `Content-Type` to match the type of content that the server will process.
`ensureContentTypeHeader` middleware is used to determine if the content-type set in the API request is the expected content type. If it's not a match:
- A warning is logged in Consul 
- The appropriate contentType Header set before processing the request.
- The same action is carried out for API response. 
**NOTE**: The same function is used in `doRequest` function which is used in processing CLI requests to the Consul API.  
Updated unit tests to add additional checks for content-type header
Vercel should deploy UI with no errors
Before Changes
<details>
<summary>
</summary>
</details>
After Changes
<details>
<summary>
</summary> …

[Security] SECVULN-8621: Fix XSS Vulnerability where content-type header wasn't explicitly set in API requests

---

website/content/api-docs/health.mdx

Manual cherry-pick. The original PR was merged on Sept 18 into main and release/1.19.x. @nickwales noticed that his `sg` [commit](https://github.com/hashicorp/consul/commit/ac9e694b98c4ccef4f2e6fc8803dc598bfcf18c5) was not in release/1.20.x, so I manually cherry picked into release/1.20.x
Jira: [CE-767]
[Deploy preview](https://consul-a5149qm4i-hashicorp.vercel.app/consul/api-docs/health#query-parameters-2) `sg` is the last parameter in the Query parameters list.
[CE-767]: https://hashicorp.atlassian.net/browse/CE-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Backport of docs: Adds initial sg documentation for the health API into release 1.20.x

---

.changelog/22011.txt
.release/security-scan.hcl

Previous PR https://github.com/hashicorp/consul/pull/22011 attempted to resolve these CVEs by updating the redhat ubi image, however these CVEs are still being reported in the scanner. Suppressing for now as we do not use these packages.
- CI passes
[Original PR 
](https://github.com/hashicorp/consul/pull/22011)

Suppress redhat linux CVEs

---

.github/CODEOWNERS

The staff codeowners line items were added when the codeowners files were non-mandatory, to be used as a notification only. Now that the codeowners file requires mandatory review the spirit of the original change isn't correct anymore.

chore: remove staff codeowners now that it requires mandatory review

---

.changelog/22021.txt
go.mod
go.sum
test-integ/go.mod
test-integ/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum

- bumps net packages to resolve GO-2024-3333
- CI passes
https://pkg.go.dev/vuln/GO-2024-3333

[Security] Bump net packages to resolve GO-2024-3333

---

envoyextensions/go.mod
envoyextensions/go.sum
go.mod
test-integ/go.mod
test/integration/consul-container/go.mod
troubleshoot/go.mod

Updated the api versions to the new released tag `v1.31.0` for api submodule used by `envoyextensions` as per this [wiki](https://github.com/hashicorp/engineering-docs/blob/main/consul/releases/submodules.md#envoyextensions)

Update api submodule versions to v1.31.0 for envoyextensions

---

Dockerfile

The CRT workflow is failing when promoting the redhat images for consul 1.20.2 release. Redhat have enforced the validations which requires the following labels to be present. These changes cater to those.
Link to failed promote [workflow](https://github.com/hashicorp/crt-workflows-common/actions/runs/12579059539/job/35059070743#step:9:104)
```
Add the following labels to your Dockerfile or Containerfile: name, vendor, version, release, summary, description, maintainer and validate that they do not violate Red Hat trademark.
```
I can see there was an older [PR](https://github.com/hashicorp/consul/pull/22011) which was trying to backport the changes to other versions but that seemed to have caused issues except in 1.20 hence doing the same here

Added labels for redhat validation

---

Dockerfile

Manual Backport of https://github.com/hashicorp/consul/pull/22048 which Added labels for redhat validation into release/1.20.2

Manual backport of Added labels for redhat validation into release/1.20.2

---

.github/workflows/security-scan.yml

The security scan check is failing due to expired gh token. Using the org level GH token which rotates and is maintained 
Failed scan: https://github.com/hashicorp/consul/actions/runs/12657118157?pr=22055

fix: security scanner gh token 

---

.github/workflows/security-scan.yml

The security scan check is failing due to expired gh token. Using the org level GH token which rotates and is maintained
Failed scan: https://github.com/hashicorp/consul/actions/runs/12657463329/job/35272531206?pr=22056

fix: security scanner gh token

---

CHANGELOG.md

chore: Updated changelog for 1.20.2

---

.changelog/22113.txt
agent/metadata/build.go
agent/metadata/server.go

There will only be a small set of consul build versions that a single consul server will witness. Inside of `metadata.IsConsulServer` we use a very expensive function in the `hashicorp/go-version` library to parse these into read-only `*version.Version` structs all over Consul.
Memoize these in a package cache map. Likely the thing will only have like 2 keys in it ever over the life of the process.

metadata: memoize the parsed build versions

---

.github/CODEOWNERS
.github/workflows/build.yml
.github/workflows/nightly-test-integrations-1.15.x.yml
.github/workflows/nightly-test-integrations-1.16.x.yml
.github/workflows/nightly-test-integrations-1.17.x.yml
.github/workflows/nightly-test-integrations.yml
.github/workflows/reusable-dev-build-windows.yml
.github/workflows/reusable-dev-build.yml
.github/workflows/reusable-unit-split.yml
.github/workflows/reusable-unit.yml
.github/workflows/test-integrations-windows.yml
.github/workflows/test-integrations.yml

The current CI is failing due to the error `This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: 0b7f8abb1508181956e8e162db84b466c27e18ce`.`
Updated to v4 version now. 
[Deprecation Link](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
Failed CI [run](https://github.com/hashicorp/consul/actions/runs/13236305622/job/36941822483?pr=22125)

Fix CI: Updated upload-artifact and download-artifact to v4 

---

Makefile

Lint is failing after upgrade to go 1.22.12 and hence updating the golangci-lint to 1.56.1

Update golangci-lint to 1.56.1

---

.changelog/22172.txt
api/go.mod

retracting api submodule version 1.31.1

retracting api submodule version 1.31.1

---

.changelog/22220.txt
agent/txn_endpoint.go
agent/txn_endpoint_test.go

**Update**: looks like there is an issue with API package unable to unmarshall [TxnResult](https://github.com/hashicorp/consul/blob/v1.20.3/api/txn.go#L237) when the service has `TaggedAddresses` set. This issue should be resolved first before this PR. 
Consul Transaction API Service Operation does not register the `TaggedAddresses` field in the `AgentService` struct that is sent from the client. Same with the `Type` field in the `HealthCheck` struct.
1. Create a Transaction API input file `txn.json`
```
[
{
"Node": {
"Verb": "set",
"Node": {
"Node": "n1",
"Address": "192.168.0.10"
}
}
},
{
"Service": {
"Verb": "set",
"Node": "n1",
"Service": {
"ID": "s1",
"Service": "s1",
"Address": "192.168.0.10",
"TaggedAddresses": {
"lan": {
"Address": "192.168.0.10",
"Port": 8080
}
},
"Port": 8080
} …
```

Add the missing Service TaggedAddresses and Check Type fields to Txn API

---

website/content/commands/lock.mdx

**Title**  
Consul lock docs: Clarify node checks & TTL behavior, plus manual session workaround
This PR updates the `consul lock` command documentation to explain how an ephemeral session is automatically created with node checks (e.g. `serfHealth`), which can cause the lock’s TTL to be effectively auto-renewed as long as the node is healthy. It also outlines a recommended workaround (manually creating and managing a custom session) for users who need strict TTL enforcement without node checks.
- **No functional code changes** – this is a documentation-only update.
- **Relevant sections**:
- A new note/section titled “Node Health Checks and TTL Behavior.”
- Explains that the default session includes node checks, leading to indefinite lock behavior unless manually overridden.
- …

Update lock.mdx (Node Health Check and TTL)

---

.changelog/22268.txt
api/go.mod
api/go.sum
envoyextensions/go.sum
go.mod
go.sum
proto-public/go.mod
proto-public/go.sum
test-integ/go.mod
test-integ/go.sum
test/integration/connect/envoy/test-sds-server/go.mod
test/integration/connect/envoy/test-sds-server/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
testing/deployer/go.mod
testing/deployer/go.sum
troubleshoot/go.mod
troubleshoot/go.sum

Backport of CVE Fix into release/1.21.0-rc2

Backport of CVE Fix into release/1.21.0-rc2

---

.changelog/22268.txt
api/go.mod
api/go.sum
envoyextensions/go.mod
envoyextensions/go.sum
go.mod
go.sum
internal/tools/protoc-gen-consul-rate-limit/go.mod
proto-public/go.mod
proto-public/go.sum
sdk/go.mod
test-integ/go.mod
test-integ/go.sum
test/integration/connect/envoy/test-sds-server/go.mod
test/integration/connect/envoy/test-sds-server/go.sum
test/integration/consul-container/go.mod
test/integration/consul-container/go.sum
testing/deployer/go.mod
testing/deployer/go.sum
troubleshoot/go.mod
troubleshoot/go.sum

Backport of Upgraded go to 1.23.8 into release/1.21.x

Backport of Upgraded go to 1.23.8 into release/1.21.0-rc2

---

.release/security-scan.hcl

Suppressing  following alpine CVEs as there is no fix yet:
CVE-2024-53427 from Alpine Linux's Security Issue Tracker in jq@1.7.1-r0
CVE-2025-31498 from Alpine Linux's Security Issue Tracker in c-ares@1.34.3-r0
CVE-2025-30258 from Alpine Linux's Security Issue Tracker in gnupg@2.4.7-r0
CVE-2025-31498 from Alpine Linux's Security Issue Tracker in c-ares@1.34.3-r0
CVE-2025-30258 from Alpine Linux's Security Issue Tracker in gnupg@2.4.7-r0
CVE-2024-53427 from Alpine Linux's Security Issue Tracker in jq@1.7.1-r0

suppressing alpine CVEs as there is no fix yet

---

agent/grpc-internal/client.go

This PR enhances the gRPC retry configuration to reduce the total waiting time in case any error that occurs.
**Context**
When an invalid datacenter URL parameter is provided to the /v1/partitions endpoint, the server currently hangs for 30 seconds to one minute before responding with a "resolver error: resolver produced no addresses" error message. This was due to the internal gRPC retry configuration. This change ensures that clients encountering errors will retry with appropriate backoff rather than waiting for the full server timeout.
**Changes**
Update existing retry configuration:
- Initial backoff: 1 second
- Backoff multiplier: 1.1 (each retry waits 10% longer than previous)
- Maximum attempts: 3 (initial + 2 retries)
- Maximum backoff of 5 seconds per attempt
With these changes …

fix: updated grpc config for partition endpoint

---

.changelog/22226.txt
agent/consul/server.go

When `advertise_addr` is an IPv6 address, Consul WAN federation breaks and we get a constant stream of warnings:
```
[WARN]  agent.server.memberlist.wan: memberlist: Failed to resolve
i-02a3c94b46768b01f.aws-eu-west-1/2a05:d018:18a3:f202:64d9:1621:ab22:df45:8302:
lookup 2a05:d018:18a3:f202:64d9:1621:ab22:df45:8302: no such host
```
The LAN <-> WAN join flooder creates IPv6 addresses without square brackets with `fmt.Sprintf("%s:%d", addr, s.WanJoinPort)`, which confuses `net.SplitHostPort` in `memberlist.resolveAddr`.
Fixes hashicorp/consul#22225

Fix IPv6 address handling in LAN <-> WAN join flooder

---

.changelog/22286.txt
command/tls/ca/create/tls_ca_create.go
command/tls/cert/create/tls_cert_create.go

Consul CLI's tls create command was generating some sensitive files (e.g. consul tls ca create -server) that had excessive permissions at 0666 for public certs created and it should be 0644. Updated the code to use 0644 file perms when creating sensitive files with ca and certs.
NOTE: [disabled Compatibility Integration Tests until pipeline upgrade is in place](https://github.com/hashicorp/consul/pull/22286/commits/dcca5a9ae629b0bb33f65979f4054f85cadf475c)
1. Update default OS masking to view actual code behaviour: `umask 000`
2. Run `consul tls ca create -domain=example.test` and list the directory to view generated files with `ls -lah` with excessive perms.
3. Run `consul tls cert create -server` to see similar results
4. Revert OS level masking to default: `umask 022` …

(manual) Backport of cmd/tls: set explicit file permissions for generated certs into release/1.20.x

---

.changelog/22382.txt
agent/config/builder.go
agent/config/builder_test.go
website/content/commands/agent.mdx
website/content/docs/reference/agent/configuration-file/general.mdx

Non-compliant characters lead to invalid DNS names that are incompatible with externalized PKI Certificate generation.
- Start consul with invalid characters in `datacenter` property.
- Create tls certificates using [CLI Commands](https://developer.hashicorp.com/consul/commands/tls/cert). Consul does not warn/fail.
- When using other PKI engines to generate certificates with SAN as `<service-name>.service.<datacenter>.consul` PKI generation usually fails because of invalid characters in datacenter field.
- It is not possible to change datacenter name as it is an initial bootstrapping configuration of consul. One has to migrate entire data.

fix(config): Warn on invalid characters in `datacenter` property leading to incompatible DNS names

---

.changelog/22381.txt
agent/consul/catalog_endpoint.go
agent/consul/catalog_endpoint_test.go

Adds validation to the catalog register endpoint to ensure that a service name (`Service.Service`) is provided when registering a service. This prevents registrations with empty service names, which resulted in the Services page in the Consul UI being broken.
If both `Service.ID` and `Service.Service` are empty, the API now returns an error message.
* Added unit test `TestCatalog_Register_RejectsMissingServiceName` in `catalog_endpoint_test.go`
* Manually validated behavior using:
```bash
curl -X PUT http://localhost:8500/v1/catalog/register \
-H "Content-Type: application/json" \
--data-raw '{
"Datacenter": "dc1",
"Node": "my_node",
"Address": "123.456.78.9",
"Service": {
"ID": "",
"Service": "",
"Port": 9001
}
}'
service name (Service.Service) is required; both Service ID (Service.ID) …
```

enforce validation for missing service name in registration

---

website/content/docs/deploy/server/k8s/helm.mdx

When moving around on the docs page the _Install Consul on Kubernetes with the Consul K8s CLI_ links you to localhost:3000 no matter what
https://developer.hashicorp.com/consul/docs/deploy/server/k8s/helm#install-consul-on-kubernetes-with-helm

Fix Install Consul on Kubernetes button having localhost:3000 hard coded

---

website/content/docs/register/health-check/vm.mdx

Tiny fix for the warn link on the TTL section, it was not rendering properly due to a misplaced space.
Just confirming that the link renders properly on page load.
N/A
Just a visual update, nothing majorly impacting.

Update vm.mdx - syntax fix for warn link

---

.changelog/22409.txt
.release/security-scan.hcl
Dockerfile

Upgraded UBI base image from  `9.5` to `9.6-1749489516` to fix following CVEs:
[CVE-2025-4802](https://access.redhat.com/security/cve/cve-2025-4802)
[CVE-2024-40896](https://access.redhat.com/security/cve/cve-2024-40896)
[CVE-2024-12243](https://nvd.nist.gov/vuln/detail/CVE-2024-12243)
[CVE-2025-24528](https://access.redhat.com/security/cve/cve-2025-24528)
[CVE-2025-3277](https://access.redhat.com/security/cve/cve-2025-3277)
[CVE-2024-12133](https://access.redhat.com/security/cve/cve-2024-12133)
[CVE-2024-57970](https://access.redhat.com/security/cve/cve-2024-57970)
[CVE-2025-31115](https://access.redhat.com/security/cve/cve-2025-31115)
> NOTE: Suppressed binary CVEs as it require Go upgrade to 1.24 and internal tool mog is not generating the structs for proto properly and needs further …

upgrade ubi base image to fix CVEs

---

.changelog/22423.txt
ui/packages/consul-ui/app/components/consul/service-instance/list/index.hbs

Updated the rendering logic to handle IPv6 addresses properly. The changes ensure that IPv6 addresses are enclosed in square brackets to conform to standard formatting.
Tested this manually with the IPv6 setup for minion-chat-advance app.

fix(consul-ui): properly format ipv6 addresses

---

.github/workflows/test-integrations.yml

Dependabot PRs are failing at upload coverage stage as it is unable to access DATADOG secrets. Disabling that stage for dependabot PRs along with PRs from forks

fix: skipping the coverage step for dependabot PRs also

---

website/content/docs/secure/auto-config/docker.mdx

Backport link to original PR
https://github.com/hashicorp/consul/pull/22506
Converting the  “Automate Consul agent security with auto config” tutorial into a docs page. This issue is part of the Consul tutorials to documentation conversion project.
[Deployment preview](https://consul-git-krastin-ce-913-hashicorp.vercel.app/consul/docs/secure/auto-config/docker)
https://hashicorp.atlassian.net/jira/software/c/projects/CE/boards/919?selectedIssue=CE-913
---
<details>
- d5655380793e7d5a7c308f17afa46387ea05a447  - 49d2a5b7a5e357e494b2cfa94ababdb75712f964  - fee16c5678c31ce6435e02808df64f6c0aa380ad  - …

docs: CE-913 update docker autoconf page (#22495)

---

.github/workflows/build.yml

make-clean-flag-optional branch / tag in hashicorp/actions-go-build branch is deleted.
So updating it to v1.1.1

Updating hashicorp/actions-go-build action to v1.1.1

---

.changelog/22552.txt
command/debug/debug.go
command/debug/debug_test.go

* fix consul debug cmd not collecting pprof
* add changelog
* incorporate review changes
* Update 22538.txt
* Update 22538.txt
* refactor code
* add logs
* revert the code for http.go, and also reduce comments
* rename the changelog file
---------

Csl 9247 consul debug not collecting pprof (#22552)

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/list-collection/index.js
ui/packages/consul-ui/app/components/modal-dialog/index.hbs
ui/packages/consul-ui/app/components/modal-dialog/layout.scss
ui/packages/consul-ui/app/components/modal-dialog/skin.scss
ui/packages/consul-ui/app/components/providers/dimension/README.mdx
ui/packages/consul-ui/app/components/providers/dimension/index.js
ui/packages/consul-ui/app/components/tabular-collection/index.js

https://hashicorp.atlassian.net/browse/CSL-11371
Removes footer element from modal and navigation. 
Footer should be representing the footer of the whole page and should be unique. In Consul UI, there is no footer representation hence removing it.

UI - Remove footer landmark

---

ui/packages/consul-ui/app/components/anchors/index.scss
ui/packages/consul-ui/app/components/app-view/skin.scss
ui/packages/consul-ui/app/components/confirmation-dialog/skin.scss
ui/packages/consul-ui/app/components/consul/health-check/list/skin.scss
ui/packages/consul-ui/app/components/form-elements/skin.scss
ui/packages/consul-ui/app/components/freetext-filter/skin.scss
ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
ui/packages/consul-ui/app/styles/base/color/ui/frame-placeholders.scss
ui/packages/consul-ui/app/styles/debug.scss

foreground-disabled color was being used for help and sub texts. This color on top of white background doesn't maintain minimum required contrast. foreground-faint seems to be more suitable for such texts which meets accessibility standards. 
PR replaces references of foreground-disabled with foreground-faint on text color property.

ui: CSL-11417 replace foreground-disabled with foreground-faint

---

agent/rpc/peering/testing.go
agent/rpc/peering/validate_test.go

This PR adds test coverage for IPv6 address handling in the /peering/establish endpoint.
Unit Test: TestValidatePeeringToken in agent/rpc/peering — verifies /peering/establish correctly handles valid and invalid IPv6 addresses during peering setup.
````
go test -timeout 30s -run ^TestValidatePeeringToken$ github.com/hashicorp/consul/agent/rpc/peering
````
- [CSL-11318](https://hashicorp.atlassian.net/browse/CSL-11318) — [consul-peering-http-api]: Add IPv6 test case in /peering/establish
* [] external facing docs updated
* [] appropriate backport labels added
[CSL-11318]: https://hashicorp.atlassian.net/browse/CSL-11318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add: testcase for IPv6 scenarios in peering establish api

---

.changelog/22624.txt
command/debug/debug.go
command/debug/debug_test.go

This change is to add functionality to the debug command to include port verification results in the debug bundle. This checks if the required ports(8500, 8501, 8502, 8503, 8301, 8302, 8300, 8600) are open and listening on the node where debug command is executed. A file ports.json is created in the debug bundle which has two lists for ports open and closed. This helps during troubleshooting issues so that support engineers can diagnose network-related issues without requiring direct access to the environment.
Built consul binary on local and started a local single node consul server without enabling TLS so that ports 8501, 8502 are closed. Then validated the debug command that it creates a file ports.json and it has ports 8501, 8502 in closed ports list and remaining in the list of open …

Add troubleshoot ports info in debug bundle

---

.changelog/22604.txt
agent/proxycfg/proxycfg.deepcopy.go
agent/xds/config/config.go
agent/xds/config/config_test.go
agent/xds/listeners.go
agent/xds/listeners_apigateway.go
agent/xds/listeners_test.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/connect-proxy-with-http-max-request-headers.latest.golden
agent/xds/testdata/endpoints/connect-proxy-with-http-max-request-headers.latest.golden
agent/xds/testdata/listeners/connect-proxy-with-http-max-request-headers.latest.golden
agent/xds/testdata/routes/connect-proxy-with-http-max-request-headers.latest.golden
agent/xds/testdata/secrets/connect-proxy-with-http-max-request-headers.latest.golden
test/integration/connect/envoy/case-max-request-headers/capture.sh
test/integration/connect/envoy/case-max-request-headers/service_s1.hcl
test/integration/connect/envoy/case-max-request-headers/service_s2.hcl
test/integration/connect/envoy/case-max-request-headers/setup.sh
test/integration/connect/envoy/case-max-request-headers/verify.bats
test/integration/connect/envoy/helpers.bash

The Connect/ Sidecar Envoy proxy created is not allowing request from downstream to upstream with header > 60KB. To allow the request headers with increased header size envoy provides option in the bootstrap config by setting up a param called max_request_headers_kb and the max limit allowed is 96KB.
1. Run the local consul server.
2. Register 2 services - serviceA and serviceB
serviceB.json:
```
{
"service": {
"name": "ServiceB",
"port": 8080,
"connect": {
"sidecar_service": {
"proxy": {
"upstreams": [
{
"destination_name": "serviceA",
"local_bind_port": 9191
}
],
"Config": {
"protocol": "http",
"max_request_headers_kb": 96
}
}
}
}
}
}
```
4. Write proxy-defaults config with protocol as http, and max_request_headers as 96.
```
proxy-defaults.json:
{
"Kind": "proxy-defaults", 
"Name": …
```

max_request_headers_kb param handling in Proxy Defaults for Connect Proxy

---

.changelog/22626.txt
agent/auto-config/persist.go

This PR is manually generated from #22626 to be assessed for backporting. 
---
Currently the auto configuration file is being written to disk with 0660 permissions. If an attacker gains the ability to read an arbitrary file from the Consul agent’s filesystem using the group ID that the Consul agent runs as. The attacker can then read the agent’s TLS certificate and private key, giving them the ability to impersonate the Consul agent and further attack the cluster. To mitigate this in short term, in this PR the permissions of the persisted auto configuration file are updated to 0600 to prevent any user except the Consul agent’s user from reading this file.
In the long term, review the Consul agent’s data persistence mechanisms that …

Manual backport of update group permission to auto-config.json into release/1.21.x

---

ui/packages/consul-ui/app/components/child-selector/index.hbs
ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/permission/header/form/index.hbs
ui/packages/consul-ui/app/components/option-input/index.hbs
ui/packages/consul-ui/app/components/policy-form/index.hbs
ui/packages/consul-ui/app/modifiers/fix-super-select-aria.js

MIgrated from Power Select to Super Select from HDS:
Role Page -> Create New -> Policy Section
Intentions → Permissions → Add Permission Modal
Intentions → Permissions → Header
Component → Option Input
Component → Policy Form
Run Axe Developer Tools in Chrome on the page that has this component being rendered. It shows the accessibility issues to be fixed

migrate from ember power select to HDS super select

---

.github/workflows/backport-assistant.yml

The current backporting agent cherry-picks each commit in the PR. This is error prone and a lot of times there are merge conflicts and only some commits are picked. Cherry picking the squashed commit will avoid that. 
While there could be cases with empty commit, which needs to be addressed separately, this change will help in having all the changes instead of engineer cherry-picking the commits again.

chore: updated backport assistant to use squash merge commit for cherry picking

---

ui/packages/consul-ui/app/components/nav-selector/index.hbs
ui/packages/consul-ui/mock-api/prefixed-api/v1/namespaces

HDS dropdown component updates it's list element based on the number of items, or type of items under the list. If the items are dynamic, it fails to assign the required accessibility attributes. This PR fetches the data required for the dropdown in advance to avoid the above scenario.

[UI] trigger fetch-data before dropdown is rendered.

---

.changelog/22682.txt
agent/kvs_endpoint.go
agent/kvs_endpoint_test.go

Add input validation in KV stores to match https://developer.hashicorp.com/consul/docs/automate/kv#using-consul-kv

fix: kv input validation

---

agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go

We recently updated code editor to use hds code-editor instead of ivymirror code editor. The hds editor uses dynamic imports, which causes some js assets to include paths to these files. These paths are again dynamic since they depend on the variable `-ui-content-path`. Therefore, these paths in the files are to be transformed before getting served to the client. 
This PR adds a new method which replaces the variable {{.ContentPath}} in these files with the actual value. To limit the blast radius, i've included files which match `assets/chunk` prefix. 
This [issue](https://github.com/hashicorp/consul/issues/22574) has steps to reproduce.
https://github.com/hashicorp/consul/issues/22574
Examples of changes to security controls include using new access control methods, adding or removing …

update ui server to replace ContentPath variable in js assets as well

---

.changelog/22722.txt
agent/xds/listeners.go
agent/xds/listeners_ingress.go
agent/xds/listeners_test.go
agent/xds/resources_test.go
agent/xds/testdata/clusters/mesh-gateway-peering-service-max-request-headers.latest.golden
agent/xds/testdata/endpoints/mesh-gateway-peering-service-max-request-headers.latest.golden
agent/xds/testdata/listeners/mesh-gateway-peering-service-max-request-headers.latest.golden
agent/xds/testdata/routes/mesh-gateway-peering-service-max-request-headers.latest.golden
agent/xds/testdata/secrets/mesh-gateway-peering-service-max-request-headers.latest.golden

Backport of [#22722](https://github.com/hashicorp/consul/pull/22722)
The Connect/ Sidecar Envoy proxy created is not allowing request from downstream to upstream with header > 60KB. To allow the request headers with increased header size envoy provides option in the bootstrap config by setting up a param called max_request_headers_kb and the max limit allowed is 96KB.
1. Start Two Consul Datacenters
```
consul agent -dev -server -bootstrap-expect=1 -node=server-dc1 -datacenter=dc1 -client=127.0.0.1 -bind=127.0.0.1 -ui -ui-content-path=/ui/ -enable-script-checks
consul agent -server -bootstrap-expect=1 -node=server-dc2 -datacenter=dc2 -client=127.0.0.1 -bind=127.0.0.1 -serf-lan-port=19301 -serf-wan-port=19302 -http-port=19500 -dns-port=19600 -grpc-port=19502 -data-dir=/tmp/consul-dc2 …
```

Backport: max_request_headers_kb param handling in Service Defaults for Mesh Gateway

---

.changelog/22763.txt
agent/agent_endpoint_test.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/admin-bind-flag-with-dual-stack.golden
command/connect/envoy/testdata/defaults-with-dual-stack.golden
command/connect/envoy/testdata/grpc-addr-flag-with-dual-stack.golden

When no explicit flags are provided, Envoy should default to 127.0.0.1 in IPv4-only environments and ::1 in IPv6/Dual Stack environment determine based on the local agent bind_addr.
* [ x] updated test coverage
* [ x] appropriate backport labels added
* [ x] not a security concern

[CSL-11760] [Envoy Bootstrap] Defaults to IPv6 for admin-bind and grpc-addr in dual stack if its empty

---

.changelog/22537.txt
agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/auth/token_writer.go

Backport of [#22537](https://github.com/hashicorp/consul/pull/22537)
[SECVULN-25353](https://hashicorp.atlassian.net/browse/SECVULN-25353)
[SECVULN-25353]: https://hashicorp.atlassian.net/browse/SECVULN-25353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Backport: sec: perform constant time compare for sensitive values (#22537)

---

.changelog/22671.txt
agent/ui_endpoint.go
agent/ui_endpoint_test.go

This pull request addresses a security issue in the `UIMetricsProxy` handler by improving how proxied URL paths are cleaned and validated to prevent path traversal attacks. The main focus is on ensuring that user-supplied paths cannot escape the intended base URL, even in edge cases.
**Security improvements to URL path handling:**
* Paths are now cleaned using `path.Clean` with a leading slash to ensure that any `../` segments are properly removed, preventing path traversal attacks. (`agent/ui_endpoint.go`)
* The previous redundant cleaning of the parsed URL path after construction has been removed, as the cleaning is now handled earlier and more securely. (`agent/ui_endpoint.go`)
**Base URL validation enhancements:**
* The check for whether the target URL is within the base URL now …

fix path cleaning of proxied urls

---

agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
command/connect/redirecttraffic/redirect_traffic.go
command/flags/http.go

Removal of added dualstack flag to redirect-traffic command as it has a http interface available to connect to consul agent
Removing Ipv4 check for b in addIPv6Offset as b passed in code passes check for Ipv4 

Removing dualstack flag from consul redirect and check from consul API

---

website/content/docs/east-west/cluster-peering/establish/k8s.mdx

The current documentation had `Cluster peering between services cannot be established until all four steps are complete.` repeated in the peering steps.

docs: removed duplicate lines

---

agent/agent.go
agent/agent_endpoint_test.go
agent/config/config.go
agent/config/runtime_test.go
agent/structs/structs.go
agent/structs/structs_test.go
api/agent.go
api/agent_test.go

Initially, we thought that every port in a service definition has to be unique, but we found out that multiple services expose different protocols in the same port and would want to define them as different ports with different names in consul. This is also backed by the fact that K8s allows multiple ports with duplicate port values as long as the port names are unique.
This PR acknowledges this and modifies the multiport validation to allow duplicate ports.
1. Start consul agent with the branch
2. Register this service definition ( Note that the port value is same for both the ports )
```hcl
service {
name = "multiport-service"
ports = [
{
name = "http"
port = 8080
default = true
},
{
name = "metrics",
port = 8080
}
]
}
```
3. Ensure registration goes through. You can `curl …

Fixed Duplicate Port Validation issues in CLI registration
