command/agent/command.go, command/agent/dns.go
Fixes #609
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
=> Don't forget to Shutdown the DNS Server!

Makefile
**_I noticed that a similar PR (#593) has been rejected in the past, however,
this vet target disables checks that are considered to be "nosiy"._**
**_See also hashicorp/terraform#828._**
Add a vet target in order to catch suspicious constructs
reported by go vet.
Vet has successfully detected problems in the past,
for example, see
c9333b1b9b472feb5cad80e2c8276d41b64bde88
Some vet flags are noisy. In particular, the following flags
reports a large amount of generally unharmful constructs:
```
-assign: check for useless assignments
-composites: check that composite literals used field-keyed
elements
-shadow: check for shadowed variables
-shadowstrict: whether to be strict about shadowing
-unreachable: check for unreachable code
```
In order to skip running the flags mentioned above, vet is …
=> Makefile: add vet target

command/agent/remote_exec.go, command/agent/remote_exec_test.go
=> agent: pass locally configured token during remote exec

website/source/community.html.erb, website/source/downloads.html.erb
=> Load images over SSL

website/source/docs/agent/options.html.markdown
Didn't have the heart to tackle the entirety of docs/agent/options in one sitting. :-)
=> Website: cleanup for the docs/agent/options Command-line options section

website/source/docs/agent/http/session.html.markdown
I had a question I couldn't answer while editing this doc, so this PR is not ready to merge.  I'm just using the PR to ask the question because I'm lazy
The question is inline below.  Just search for the following block to find the context:
```
<QUESTION: I don't see anywhere in the code to substantiate this.  If this is true, how do we define small and large values? We need to give people some boundaries.  QUESTION>
```
Thanks!
=> Website: cleanup for docs/agent/http/session

website/source/intro/getting-started/agent.html.markdown, website/source/intro/index.html.markdown
I'll go ahead and merge this in a bit unless it doesn't look good, but I'm interested in feedback on this doc because it's so important to the new user experience.  Particularly, on line 82 I wanted to give a bit more definition on eventual consistency to make the distinction clear.  Any feedback would be appreciated.
And congrats on 0.5!
=> Website: cleanup for getting-started/agent

command/agent/command.go, consul/server.go, consul/util.go, ui/README.md, website/source/docs/agent/options.html.markdown, website/source/docs/guides/bootstrapping.html.markdown, website/source/docs/guides/manual-bootstrap.html.markdown
Might as well kill them all...
=> s/data center/datacenter/g

command/agent/command.go
Closes #602, This is replacement for #708.
=> Support multiple recursor flag

website/source/docs/guides/dns-cache.html.markdown
=> Add information about Negative Response Caching

ui/styles/_buttons.scss
=> make sure button text overflow is set to ellipsis

website/source/intro/getting-started/agent.html.markdown, website/source/intro/getting-started/join.html.markdown
Hi all, creating a PR for this one since this is an important doc for new users and these edits are substantial.  I added more prompts to make it clear exactly how to reproduce the steps in this walkthrough, and I provided accurate shell prompts (i.e. `vagrant@n1:~`) to make it more obvious the context in which each command should be run.
=> Website: substantial rewrite of intro/getting-started/join.html

website/source/docs/agent/basics.html.markdown
Hope you will find nice refrase
=> Small tip for gracefull kill

command/agent/http.go, command/agent/http_test.go
=> Hide tokens from logs and monitor

website/source/docs/agent/http/agent.html.markdown
Just an update to the docs with a small bit of missing information. Thanks for consul!
=> Updating the docs to include information about registering a check with a ServiceID.

website/source/docs/guides/servers.html.markdown
When i look how to start server, a read "simply start new server with the -server flag" and understand nothing. I think "agent" is a correct word here.
=> Fix ambiguity in server start

website/source/downloads_tools.html.erb
I should note that I'm not affiliated with `diplomat`, but it's a clever tool and would be nice to have it surfaced better.
=> Include diplomat

command/agent/agent.go, command/agent/agent_test.go
When updating services/checks from the API, they are persisted to disk. Instead of only persisting them during registration, this allows them to also be updated during subsequent PUT requests which update the definitons.
=> Update agent-persisted services/checks

acl/acl.go, acl/acl_test.go
Hi, 
I'm changed the way of consul checking service ACLs.
It's prefix based in this commit. No exact match like before.
What do you think about merging this to repo ?
=> Consul prefix services ACLs

terraform/aws/scripts/upstart.conf
This change should stop consul gracefully
=> Change upstart stop consul result

command/agent/agent.go, command/agent/agent_test.go
=> Deregister all associated checks on service deregistration

api/session.go
So we've come across an interesting condition operating our consul cluster.  Basically what we are seeing is that during a leader election all of our locks were being TTL'd out.  Digging in a bit further it appears that during a leader election, the renew call fails and RenewPeriodic returns.   After TTL time elapses the sessions are invalidated and the locks are lost.
I've made a modification to RenewPeriodic to keep trying if there is an error, up until the TTL passes.  This should allow our sessions locks to survive a leader election, so long as it takes less than TTL/2 for the election to finish.
Here is an example set of logs that show what is happening:
```
2015/05/02 19:22:52 [DEBUG] http: Request /v1/session/renew/db32a8ad-5e87-41b6-a217-f8f0e669948e (2.33141ms)
2015/05/02 …
```
=> modify RenewPeriodic to retry failed Renew until TTL elapses

website/Gemfile, website/Gemfile.lock, website/config.rb
This gives the new "bintray_enabled" option.
=> Use new middleman-hashicorp

website/source/downloads_tools.html.erb
=> Add Consul.NET to the tools page

command/agent/check.go
The current user agent for HTTP health checks are `Go 1.1 package http`. This PR change them to something slightly more informative: `Consul Health Check`.
=> Set the User Agent for HTTP health checks

terraform/aws/consul.tf, terraform/aws/variables.tf
Added the AWS Provisioner details and corresponding variables. Also added the optional Tag details which will have a nice thing to do when Launching servers
=> Fix terraform aws variables

Vagrantfile
No provider config was being set.
=> Vagrantfile: fix provider syntax

website/source/docs/commands/lock.html.markdown
=> Fix typo, probably

api/kv.go, api/kv_test.go
I think a proper error might be more fitting rather than a 301 status code.
=> Returns an error for a key with a '/'

testutil/server.go
=> Allow the user to control the output of the test server

api/lock.go
Fixes #1006 by adding an additional check for why a lock acquisition failed.
What changed is if a lock acquisition fails, it will now perform a `kv.Get` on the key that it is locking on **immediately** after failure to acquire to get the latest state, and if the session is not null, it deems the lock-delay to not be in effect and thus resets the loop to wait normally. If the session is null and the acquisition fails, it falls back to waiting and checking every `DefaultLockRetryTime` seconds.
The downside of this is that upon resetting the loop with `goto WAIT` it does _another_ `kv.Get` to update the latest state, but this one is a blocking request that actually does wait for the latest info since the WaitIndex is persisted from the "why did this fail to acquire" check result to the next …
=> Check to see why a lock acquisition failed

website/source/intro/getting-started/checks.html.markdown
=> Specified which user health checks get run as.

consul/util.go, consul/util_test.go
Fixes #1031 by adding 100.64.0.0/10 as a private IP range.
=> Add RFC 6598 private IP range

website/source/downloads_tools.html.erb
- add link to cfg4j.org
- fix broken indentation for other project
=> Add cfg4j to website (community projects section)

command/lock.go
Attempt to address https://github.com/hashicorp/consul/issues/800
Not sure how to pursue a negative test case for this.
=> Return every time lock acquisition fails

consul/catalog_endpoint_test.go, consul/health_endpoint.go, consul/health_endpoint_test.go
=> Filter services when using ChecksInState.

command/agent/dns.go
=> Recurse when PTR answer is empty

website/source/docs/internals/acl.html.markdown
=> website: fix broken link on acl page

website/source/docs/agent/basics.html.markdown, website/source/docs/faq.html.markdown
Ref: https://groups.google.com/forum/#!searchin/consul-tool/left/consul-tool/KVl0u91uCdw/bfzrUO4r-1QJ
=> Added detail about left/failed nodes and 72h reaping

website/Vagrantfile
- Added gpg key
- Updated to ruby 2.2.2
- bundle -> bundle update
=> website/Vagrantfile works again.

website/source/downloads_tools.html.erb
update: add consul-cli to downloads_tools.html.erb
=> update: add consul-cli to downloads_tools.html.erb

website/source/docs/agent/http/agent.html.markdown
This cleans up a loose end from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/4EaQofKm_Bc/T_Kvu3w_CAAJ.
=> Clarifies services docs a bit.

website/source/docs/guides/forwarding.html.markdown
The dnsmasq example here is bare bones, I can add more if that's desired.
=> add a dnsmasq example, explain the utility of 'recursors'

command/maint_test.go
=> Adds missing token to maint unit test.

api/session.go, api/session_test.go
Fixes part of #1040.  
Needs some sort of handling for how to deal with RenewPeriodic.
=> Fix Session.Renew to care about 404s properly

website/source/assets/stylesheets/_header.scss, website/source/assets/stylesheets/_jumbotron.scss
This reverts commit 809ed3634403a90dbc62d05e18351262fed10d4c.
I think this should fix #1334 which was introduced in pull #1300.
=> Revert "Fixed Header background"

ui/index.html
=> Show node status as failing if a service on the node is failing

command/agent/local.go
In #1265, the theory we have is that there is some O(N^2) stuff happening. This was at least one obvious case of that, might be a partial fix.
=> agent: remove an N^2 check. See #1265

website/source/assets/stylesheets/_home.scss, website/source/assets/stylesheets/_jumbotron.scss, website/source/assets/stylesheets/_variables.scss, website/source/index.html.erb
this fix was both a bit more involved and a bit hackier than I was hoping the
soultion would be, but that's how things go sometimes
to test:
- open up the website in a browser and resize your window
- make sure that the nav is always legible
=> fix for jumping header issues on the website

scripts/dist.sh
=> Use hc-releases to upload during dist

api/README.md
Updated the version that the library supports.
=> Fix version support

consul/pool.go
Shrink idle yamux streams in the connection pool to reduce memory overhead. Otherwise, each stream may allocate up to 512KB of buffers, and we may have up to 64 idle streams per remote peer.
/cc: @slackpad 
Depends on https://github.com/hashicorp/yamux/pull/21
=> consul: shrink yamux recv buffer on idle streams

consul/state/prepared_query.go, consul/state/prepared_query_test.go
While testing the example snippets in my blog post I realized you can register the same name multiple times.
/cc @ryanuber or @armon
=> Adds a check to make sure query names can't be registered twice.

website/source/community.html.erb
=> Add bios for @ryanuber, @slackpad, and @sethvargo

consul/rpc.go
This helps you figure out where bad messages are coming from.
=> Adds source address logging on RPC errors.

website/source/index.html.erb
=> Adds a base64 decode step to the example.

demo/vagrant-cluster/Vagrantfile
Please update Consul in demo if not depend v0.5.2.
=> Update Consul in demo

website/source/docs/agent/options.html.markdown
=> [doc] fix identation on statsd_addr

ui/javascripts/app/routes.js
The UI breaks if an acl master token is configured
=> Propagate token in UI

ui/javascripts/app/routes.js
Wanted to give @railsguru credit for a fix that I missed previously and was added later by someone else but it ended up duplicating the token variable. This fixes it.
=> Fixes a bad merge in the UI.

scripts/build.sh
This should close https://github.com/hashicorp/consul/issues/159.
=> Adds a solaris target.

website/source/docs/upgrade-specific.html.markdown
This is a note to help warn people so they have a heads up about issues like #1579.
=> Adds a cautionary note about data fitting into RAM.

command/agent/command.go
=> Add consul agent help for advertise-wan

demo/vagrant-cluster/Vagrantfile
=> Update consul version for vagrant demo

website/source/docs/agent/checks.html.markdown
I saw there were 5 checks listed - script, tcp, http, ttl, docker. Updating count to reflect that number.
=> Correcting count of checks

website/source/intro/hashicorp-ecosystem.html.markdown
As this is Consul, not Terraform, it makes sense to use Consul in this intro instead of Terraform.
=> Edit intro to present Consul instead of Terraform.

website/source/docs/guides/forwarding.html.markdown
Specifically:
* add Dnsmasq examples for reverse DNS for most of the RFC1918, 5735, and 6598 netblocks.
* Highlight some example options for dnsmasq that are probably of interest.
* Add a small section on reverse DNS testing
* Break out BINDs troubleshooting with Dnsmasq's troubleshooting
Not an exhaustive sweep, but should be helpful when introducing consul to new environments.
=> Iterate on the DNS forwarding docs

website/source/downloads_tools.html.erb
https://github.com/smoketurner/dropwizard-consul
=> Add dropwizard-consul to the Community Tools page

command/agent/agent_endpoint.go
Added some of the newer reasons this error could have occured.
=> Updated invalid check error message.

website/source/docs/guides/forwarding.html.markdown
It is not really clear that you only have to do one of the following and not all three.
Especially if you are new to DNS.
=> Updating dns forwarding

command/agent/http.go
=> Fixes redirect from / to /ui when internal UI is enabled.

command/agent/config.go, command/agent/config_test.go, command/configtest_test.go
Checks the size of the file, if it is 0 it skips the file.
=> fixes issue #1661 and adds supporting test

GNUmakefile
This adds a safety tweak to #1716.
=> Don't run `go vet` on vendor/

.travis.yml, Vagrantfile
We will leave the vendor experiment environment variables set for a little while.
=> Starts switch to Go 1.6.

website/source/docs/agent/options.html.markdown
This tweaks a few things on top of https://github.com/hashicorp/consul/pull/1728.
=> TLS example and correcting error

consul/state/schema.go
one line schema change to not allow missing for sessions Table node index, Fixes #1774
Are you looking for test cases with inserts to verify or just the simple change?
=> Session Table index require Node

website/source/assets/stylesheets/_announcement-bnr.scss, website/source/assets/stylesheets/_header.scss, website/source/layouts/_header.erb
@slackpad this is the display fix.
I also refactored so all style changes are in one file for clarity when announcement bnr is displayed.
=> Enerprise bnr caused header to display incorrectly on subpages

command/agent/dns.go, command/agent/dns_test.go, website/source/docs/agent/options.html.markdown
Took https://github.com/hashicorp/consul/pull/1734 by @idubinskiy and made a few minor tweaks.
=> Make sure UDP DNS responses aren't larger than allowed

website/source/docs/agent/options.html.markdown
=> Fix doc typo

website/source/intro/getting-started/services.html.markdown
=> Adds a reference to the health endpoint in the intro.

website/source/docs/internals/security.html.markdown
Update security.html.markdown add section on Network Port usage.
TODO: add Atlas port usage.
=> Update documentation - add Network Ports.

ui/index.html, ui/javascripts/app/controllers.js, ui/javascripts/app/routes.js
Included support to override the assumed location of the consul so you can run the UI on a normal web server potentially on a different host to your consul servers.
=> Configurable consul host address

command/agent/command.go
Added help text for the -dev option for 'consul agent' - https://github.com/hashicorp/consul/issues/1804
=> Added help text for -dev option #1804

consul/agent/server.go, consul/agent/server_internal_test.go, consul/agent/server_test.go, consul/client.go, consul/client_test.go, consul/leader.go, consul/merge.go, consul/pool.go, consul/serf.go, consul/server.go, consul/servers/manager.go, consul/servers/manager_internal_test.go, consul/servers/manager_test.go
Gratuitous bulk rename to provide future clarity.
=> F rename server manager

command/agent/dns_test.go, lib/math.go, lib/math_test.go
I'm not sure how I thought this passed last night, it was obviously wrong.
=> Fix DNS tests

command/agent/config.go
=> Set default bind address to 127.0.0.1 in development mode

command/agent/command.go, command/agent/command_test.go, command/agent/http_test.go, command/agent/rpc_client_test.go, consul/client_test.go
fixes #1541 
* Check for invalid data directory permissions
* Display appropriate permissions error message
* Add command test for bad data directory permissions
=> command: Data directory permission error message

testutil/server.go
Basically same changes in https://github.com/hashicorp/nomad/commit/0cb341adfb8d2fe083ec88b37e8b66597d6ea9b3
=> Make testutil.TestServer work correctly on Windows.

website/source/docs/agent/basics.html.markdown, website/source/docs/agent/options.html.markdown, website/source/docs/faq.html.markdown
Small doc change with suggestions to not change the reap timer.
=> Recommend against adjusting reap times

ISSUE_TEMPLATE.md
This format may have to be tweaked depending on how it shows up.
Borrowed from: Nomad Project
=> Add a Github issue template

website/source/assets/stylesheets/_announcement-bnr.scss
@slackpad This fixes https://github.com/hashicorp/consul/issues/2017
I verified the issue/fix by getting virtual box setup with Windows 10 and Internet Explorer.
=> add height to fix svg in announcement bnr

.travis.yml, GNUmakefile, scripts/build.sh, scripts/test.sh
=> Update testing output

command/agent/catalog_endpoint.go
=> Parse ACL tokens for the catalog register/deregister endpoints

website/source/docs/agent/http/agent.html.markdown
I found consul /v1/agent/service/register interface supprt TCP check as well.
=> add tcp in service/register

Godeps/Godeps.json, vendor/github.com/hashicorp/memberlist/README.md, vendor/github.com/hashicorp/memberlist/awareness.go, vendor/github.com/hashicorp/memberlist/config.go, vendor/github.com/hashicorp/memberlist/delegate.go, vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/suspicion.go, vendor/github.com/hashicorp/memberlist/util.go
=> Updates to latest Serf/memberlist to get lifeguard and TCP joins over DNS.

Godeps/Godeps.json, vendor/github.com/hashicorp/go-immutable-radix/iradix.go
See https://github.com/hashicorp/go-immutable-radix/pull/6.
=> Updates go-immutable-radix to pull in caching fix.

command/agent/agent.go, command/agent/rpc.go, consul/rpc.go, consul/server.go, consul/servers/manager.go, testutil/README.md
See individual commits for details.  No functional change in any of these improvements.
=> Misc micro optimizations

consul/prepared_query_endpoint.go, consul/prepared_query_endpoint_test.go
=> Sort source node first if at position <= 10 in PQ's

website/source/docs/agent/services.html.markdown
=> small typo

contrib/bash-completion/_consul
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>
=> contrib: added bash completion

consul/rpc_test.go
This adds some extra tests for #2175.
=> Adds some supplemental tests for RPC "no leader" retries.

command/agent/command.go
=> Add the version (from config) to the Starting Consul Agent printout

website/source/docs/agent/options.html.markdown
Change `circonus_broker_search_tag` to `circonus_broker_select_tag` to match same changes to `command/agent/{command,config}.go`.
=> Documentation update

website/source/docs/agent/http/agent.html.markdown
=> Adds api agent docs for EnableTagOverride.

command/leave.go, command/leave_test.go
=> add extra check for unexpected args to leave command

Godeps/Godeps.json, vendor/github.com/boltdb/bolt/README.md, vendor/github.com/boltdb/bolt/db.go, vendor/github.com/boltdb/bolt/errors.go, vendor/github.com/boltdb/bolt/page.go, vendor/github.com/boltdb/bolt/tx.go
This fixes #2203 which was a consistency problem on Windows.
=> Updates Bolt DB to v1.2.1.

website/source/docs/faq.html.markdown
- Added a table of protocols an ports used by Consul to FAQ
=> Network ports

command/agent/http.go
This generates useful telemetry for assessing the health of clients talking to Consul over HTTP. It rolls up telemetry about endpoints by using this basic structure:
`consul.consul.http.<verb>.<parts>`
`<verb>` is the HTTP verb, and `<parts>` is based on the path that is registered for each endpoint. It won't contain any specific parts of the path like service names or key names. For paths that have a variable part, a `_` placeholder will be added.
Here's some example telemetry with this patch active:
```
[2016-08-09 15:40:00 -0700 PDT][S] 'consul.consul.http.GET.v1.internal.ui.nodes': Count: 1 Sum: 0.562 LastUpdated: 2016-08-09 15:40:08.189480734 -0700 PDT
[2016-08-09 15:40:00 -0700 PDT][S] 'consul.consul.http.GET.v1.coordinate.nodes': Count: 1 Sum: 0.174 LastUpdated: 2016-08-09 …
```
=> Installs a wrapper around HTTP endpoints that generate metrics.

website/source/docs/guides/forwarding.html.markdown
Adding notes on using iptables to forward ports instead of a second service.
=> DNS forwarding with iptables

website/source/docs/agent/options.html.markdown
:link: Add an anchor for linking directly to the **Command-line Options** section of the docs
=> Add anchor

api/health.go, command/agent/dns_test.go, consul/structs/structs.go
Signed-off-by: Abhinav Dahiya <abhinavdtu2012@gmail.com>
=> Fixes #1775; Removes 'unknown' state

website/source/intro/getting-started/agent.html.markdown
- Updated starting agent example to show new output/timestamps
- Updated curl example to show TaggedAddresses
- Updated dig example to return 127.0.0.1
=> Command output updates.

website/source/docs/agent/checks.html.markdown
=> Clarify that hostname defaults to localhost for tcp

command/agent/local.go, command/agent/local_test.go
Fixes #2125. Should be covered by existing unit tests which I verified do a delete of a service and a check.
=> Cleans up state management for remote deletes from local state.

command/agent/gated_writer.go, command/agent/rpc.go
=> Makes Windows error check case-insensitive, runs go fmt.

website/source/docs/agent/options.html.markdown
Updated variable value details since ip+port are actually required (confirmed) and not vice versa.
=> Update variable value information, fixes #2210

website/source/intro/getting-started/join.html.markdown
This change, along with the updates merged in #2364 should resolve #2204.
=> Update getting started/join to address #2204

consul/server.go
=> Fixes port numbers in peers.info.

command/agent/agent.go
Not sure if the comment needs updating here too or can it be left alone?
=> Lower Service tag DNS warning to DEBUG for #2019

command/agent/agent_endpoint_test.go, command/agent/agent_test.go, command/agent/health_endpoint_test.go, command/rtt_test.go
=> WIP: Test fixes

api/kv_test.go, command/agent/local_test.go, consul/client_test.go
Fixes #2050 
Fixes #2052
Fixes #1974
=> Agent anti-entropy test fixes

command/agent/dns.go, command/agent/dns_test.go
=> Resolve Consul CNAME records on external services

consul/server.go, consul/snapshot_endpoint.go, consul/snapshot_endpoint_test.go, vendor/github.com/hashicorp/raft/inmem_snapshot.go, vendor/vendor.json, website/source/docs/agent/http/snapshot.html.markdown
=> Enable snapshots in dev mode

command/agent/agent.go, command/agent/agent_test.go, command/agent/command.go, command/agent/command_test.go, command/agent/config.go, command/agent/config_test.go, website/source/docs/agent/options.html.markdown
This tweaks a few things and closes #2380, and also fixes #2007.
=> Supports WAN and LAN Serf Bind Addresses.

command/agent/check_test.go
This replaces some hard sleeps with testutil.WaitForResult retry
logic in some recently added tests around TLSSkipVerify in checks.
=> Remove hard sleeps from some flaky tests

command/agent/command.go, command/agent/config.go
This sets the ACL Datacenter to lowercase, similar to the main DC config, and should resolve #2059 and #1778
=> Lowercase ACL Datacenter

command/agent/check.go, command/agent/check_test.go
=> Removes stale reference to reap lock which causes a panic.

vendor/github.com/hashicorp/raft/inmem_snapshot.go, vendor/vendor.json
=> Update raft deps to fix snapshot races in -dev mode

website/source/docs/agent/options.html.markdown
Added notes about `-ui-dir` and `ui_dir` for version 0.7.0 and later
=> Docs: Web UI config updates

command/operator.go, website/source/docs/agent/http/operator.html.markdown, website/source/docs/commands/operator.html.markdown
I've updated the docs slightly as it doesn't read correctly.
=> Update to operator docs/comments

website/source/docs/guides/datacenters.html.markdown
Updated the slightly confusing documentation on how to join the clusters over WAN. Also the inputs from #1656  is taken in account in this documentation update.
=> Multiple Datacenter Documentation

website/source/downloads_tools.html.erb
Would be good if this could be added to your page. Supplies higher level functionality wrapped up such as leader election and service with health registration etc.
=> [Website] Update community tools page to add condenserdotnet

website/source/downloads_tools.html.erb
[envoy](https://github.com/tolitius/envoy) to the [Download Consul Tools](https://www.consul.io/downloads_tools.html) list
=> [website]: adding a Clojure client

command/agent/http.go
This makes for a nice UX when trying things out.
=> Defaults to pretty JSON in dev mode.

website/source/docs/agent/http/catalog.html.markdown
Describe fields returned by /v1/catalog/service/<service>
=> Attempt to describe entire response (for #2393)

api/health.go
I forgot to actually update the types 😦 
/cc @slackpad
=> Return the correct type

ui/index.html, ui/javascripts/app/controllers.js
- Remove Deregister button
- Remove Deregister functionality
=> Remove Deregister from UI for #2541

command/agent/agent_endpoint_test.go
This has failed a few times in Travis - change it to be order agnostic and just check the first log.
=> Fix race issue in monitor endpoint test

consul/serf.go
=> Add retry with backoff to initial bootstrap checks

vendor/github.com/hashicorp/memberlist/config.go, vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/vendor.json
=> Update memberlist vendor deps

website/source/assets/stylesheets/_docs.scss, website/source/intro/getting-started/kv.html.markdown
=> Switch to KV CLI in getting started

command/agent/command.go
Fixes #2404 
Added code found in hashicorp nomad. 
https://github.com/hashicorp/nomad/pull/1802/commits/3a4bb56cf714f4b35eb1efb0fbb0cabb4afd0a3d#diff-9d1ee8f5adf90f07803d3f8bbc339694
=> Ignore sigpipe signals

command/agent/command.go
=> Check if data-dir is a directory

website/source/docs/agent/environment-variables.html.markdown, website/source/layouts/docs.erb
- Relocate Environment Variables page to Agent section
- Correct front matter newlines issue
=> DOCS: update Environment Variables page

demo/vagrant-cluster/README.md, demo/vagrant-cluster/Vagrantfile
- Add CONSUL_DEMO_VERSION env var for specifying Consul version
=> Demo: configurable Consul version

consul/fsm.go, consul/fsm_test.go, consul/rpc.go, consul/rpc_test.go
This is a follow on to https://github.com/hashicorp/consul/pull/2671. We added two new behaviors:
1. Blocking queries will bail out if a state restore occurs.
2. If a restore fails, the old contents of the state store will be retained.
=> Cleans up state store restore behavior.

testutil/server.go, testutil/wait.go
Individual commits contain more detail.
/cc @slackpad
=> testutil updates

website/source/layouts/_header.erb
Adds Google Tag Manager to the website per Hashicorp's request in (~redacted~).
@captainill
=> Add Google Tag Manager #GTM-NR2SD7C

consul/state/catalog.go
See individual commit messages for details.
=> E reduce len constraint

vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go, vendor/vendor.json
=> Revert "Updates go-cleanhttp to get better tuning for newer Go versions."

website/source/downloads_tools.html.erb
This is a clojure service discovery client for Consul HTTP API
=> New clojure discovery client for Consul HTTP API

consul/leader.go
=> Adds token to deregister request when reconciling.

.travis.yml, GNUmakefile, consul/flood.go, consul/fsm.go, consul/leader_test.go, consul/servers/router_test.go, consul/state/txn.go, consul/txn_endpoint.go, consul/txn_endpoint_test.go, logger/logger.go, scripts/test.sh
=> Updates testing harness.

website/source/assets/stylesheets/_variables.scss
Updated to the correct 'red'. Or 'raspberry' if you like.
=> correct consul brand colors

website/source/api/operator/area.html.md, website/source/docs/commands/operator/area.html.markdown.erb, website/source/docs/commands/snapshot/agent.html.markdown.erb, website/source/docs/guides/areas.html.markdown, website/source/docs/guides/autopilot.html.markdown, website/source/docs/guides/datacenters.html.markdown, website/source/layouts/_sidebar.erb, website/source/layouts/layout.erb
consul.html > products/consul/
=> update all links to enterprise to avoid redirect

website/source/docs/faq.html.markdown
- Add a FAQ for per-key value size limitation in the KV
- Update Atlas FAQ with post-deprecation recommendations
=> Docs: FAQ updates

website/source/assets/stylesheets/_home.scss, website/source/assets/stylesheets/_logos.scss, website/source/assets/stylesheets/_variables.scss
=> consuls color was reverted to incorrect

api/agent.go, api/catalog.go
- Add CreateIndex and ModifyIndex to AgentService
- Add CreateIndex and ModifyIndex to Node
=> API: Add struct fields, fixes #2882

consul/session_endpoint.go
=> Adds guard in session ACL check in case session is not found.

command/agent/acl_endpoint.go, command/agent/agent_endpoint.go, command/agent/catalog_endpoint.go, command/agent/coordinate_endpoint.go, command/agent/event_endpoint.go, command/agent/health_endpoint.go, command/agent/http.go, command/agent/kvs_endpoint.go, command/agent/operator_endpoint.go, command/agent/prepared_query_endpoint.go, command/agent/session_endpoint.go, command/agent/status_endpoint_test.go, command/agent/txn_endpoint.go, command/agent/ui_endpoint.go
Used the following rewrite rules:
gofmt -w -r 'resp.Write([]byte(fmt.Sprintf(a, b, c, d))) -> fmt.Fprintf(resp, a, b, c, d)' *.go
gofmt -w -r 'resp.Write([]byte(fmt.Sprintf(a, b, c))) -> fmt.Fprintf(resp, a, b, c)' *.go
gofmt -w -r 'resp.Write([]byte(fmt.Sprintf(a, b))) -> fmt.Fprintf(resp, a, b)'  *.go
gofmt -w -r 'resp.Write([]byte(fmt.Sprintf(a))) -> fmt.Fprint(resp, a)' *.go
gofmt -w -r 'resp.Write([]byte(a + "\n")) -> fmt.Fprintln(resp, a)' *.go
gofmt -w -r 'resp.Write([]byte(a)) -> fmt.Fprint(resp, a)' *.go
=> Use fmt.Fprint/Fprintf/Fprintln

ui/index.html
The page needed an update too!
=> ui: Update index to fix #2945

api/acl.go, api/acl_test.go
Adds ACL replication into API.
=> API: Add ACLReplication

ui/index.html
=> Revert "UI: remove ACL ID from the left list"

consul/leader.go, consul/server.go, consul/snapshot_endpoint.go
This adds on to the fix in #3004 for issue #2980.
=> Adds timeout and waits for feedback when asking the leader loop to reassert.

website/source/api/acl.html.md, website/source/docs/guides/acl.html.markdown
Was implementing ACLs and found two minor typos.
=> Fixup ACL docs

testutil/server.go
Currently, the test server is waiting up to 3 seconds to be started before returning a start error.
In our case, it would be great to changer this timeout because when our CI platform (which is not really a supercomputer) is working hard,  the start can be longer than 3 seconds.
=> test: Make testserver start timeout configurable.

command/agent/acl_endpoint_test.go, command/agent/acl_test.go, command/agent/agent_endpoint_test.go, command/agent/catalog_endpoint_test.go, command/agent/coordinate_endpoint_test.go, command/agent/event_endpoint_test.go, command/agent/health_endpoint_test.go, command/agent/http_test.go, command/agent/kvs_endpoint_test.go, command/agent/operator_endpoint_test.go, command/agent/prepared_query_endpoint_test.go, command/agent/session_endpoint_test.go, command/agent/snapshot_endpoint_test.go, command/agent/txn_endpoint_test.go, command/agent/ui_endpoint_test.go
* simplify http.NewRequest calls
* add helper for `permissionDenied` checking
=> test: Simplify tests

scripts/build.sh
=> build: make linux/arm64 package

command/agent/agent.go, command/agent/config.go
=> agent: allow "::" as IPv6 bind address

website/source/api/catalog.html.md
`Sample Respons` should be `Sample Response`.
=> Spelling Error

consul/coordinate_endpoint.go, consul/coordinate_endpoint_test.go, consul/state/coordinate.go, consul/state/coordinate_test.go, vendor/github.com/hashicorp/serf/coordinate/client.go, vendor/github.com/hashicorp/serf/coordinate/coordinate.go, vendor/github.com/hashicorp/serf/serf/ping_delegate.go, vendor/github.com/hashicorp/serf/serf/query.go, vendor/github.com/hashicorp/serf/serf/serf.go, vendor/github.com/hashicorp/serf/serf/snapshot.go, vendor/vendor.json
Fixes #3023 by preventing bad coordinates from getting in, and it drops any bad coordinates already in the state store.
=> Adds defensive checks for NaN and Inf values in network coordinates.

command/agent/dns.go, command/agent/dns_test.go
=> Do not recurse when the service address is a local cname

consul/server.go, consul/servers/router.go, consul/servers/router_test.go
=> Cleans up incorrect router shutdown.

api/api.go
=> Prevent Session.Destroy from leaving open TCP connections

command/agent/agent.go, command/agent/command.go, command/agent/config.go, command/agent/http.go, command/agent/retry_join.go
The changes in this branch consist of pre-work that needs to be done to move the `command/agent` package into the root and leave only `command/agent.go`.
=> First steps towards moving packages around

command/agent/agent_endpoint_test.go
This test was still referring to cmd.agent which has been removed.
=> test: Fix TestAgent_Reload

command/agent/config_test.go
While I was working on the change for the HTTP header and method for the checks I noticed that the `DecodeConfig` tests could use some ❤️ ❤️ ❤️
=> test: refactor decode config test

command/agent/command.go
Log the different code paths during shutdown.
=> agent: log differnt shutdown stages

agent/agent.go
When the agent is triggered to shutdown via an external 'consul leave'
command delivered via the HTTP API then the client expects to receive a
response when the agent is down. This creates a race on when to shutdown
the agent itself like the RPC server, the checks and the state and the
external endpoints like DNS and HTTP. Ideally, the external endpoints
should be shutdown before the internal state but if the goal is to
respond reliably that the agent is down then this is not possible.
This patch splits the agent shutdown into two parts implemented in a
single method to keep it simple and unambiguos for the caller. The first
stage shuts down the internal state, checks, RPC server, ...
synchronously and then triggers the shutdown of the external endpoints
asychronously. This way the caller …
=> agent: fix 'consul leave' shutdown race (#2880)

command/agent.go
=> Warn when attempting to bootstrap an even number of nodes

vendor/github.com/hashicorp/memberlist/net.go, vendor/vendor.json
=> vendor: update github.com/hashicorp/memberlist

agent/dns_test.go
The makeRecursor function was using an unreliable mechanism
to start a server with a random port. This patch changes this
so that the server starts on port 0 to let the kernel pick
a free port.
In addition, to similar functions for starting a test DNS
server were folded into one.
=> agent: fix DNS recursor tests

website/source/docs/agent/options.html.md
=> Documentation: Update # of ports

website/source/docs/agent/options.html.md
- Add note about port 8302 to address #3058
=> DOCS: Add note in Ports Used section

agent/config_azure.go
=> azure: tag map can return nil

agent/acl.go, agent/acl_test.go, website/source/docs/agent/options.html.md, website/source/docs/guides/acl.html.md
=> Adds node read privileges to the acl_agent_master_token.

vendor/github.com/hashicorp/memberlist/README.md, vendor/github.com/hashicorp/memberlist/config.go, vendor/vendor.json
See https://www.hashicorp.com/blog/making-gossip-more-robust-with-lifeguard/.
=> Updates memberlist to pick up Lifeguard research findings.

website/source/api/acl.html.md, website/source/docs/commands/exec.html.markdown.erb
=> Updates consul exec docs to mention ACLs.

agent/consul/prepared_query/template.go, agent/consul/prepared_query/template_test.go, agent/consul/structs/prepared_query.go, website/source/api/query.html.md
=> Adds option to prepared queries to remove empty tags.

agent/consul/fsm.go, agent/consul/state/autopilot_test.go
Just some small things I noticed while working nearby.
=> Adds missing autopilot snapshot test and avoids snapshotting nil.

website/source/docs/guides/consul-containers.html.md, website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
Addressed a bunch of review comments, pls take a final look.
=> Containers guide

vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/vendor.json
=> Propagates a better error message from memberlist.

api/agent.go
=> Adds a guard to make sure that empty log lines don't close consul monitor.

acl/acl_test.go
little fault in **TestStaticACL**
=> fix UnitTest in acl

agent/consul/filter.go, agent/consul/filter_test.go, agent/consul/kvs_endpoint_test.go
=> Revert "Ensure that we return a permission denied only if the list of keys/en…"

agent/consul/filter.go, agent/consul/filter_test.go, agent/consul/kvs_endpoint.go, agent/consul/kvs_endpoint_test.go, agent/consul/txn_endpoint.go
=> Revert "Return 403 rather than a 404 when acls cause all results to be filter…"

website/source/docs/agent/options.html.md
=> Document the new auto-join in the config and CLI

website/source/docs/agent/options.html.md
Since there's so much goodness higher up in the page we should just link people there.
/cc @sethvargo
=> Remove partial details in the retry_join config file section.

command/kv_import.go
=> fix command/kv_import.go help text

website/source/docs/commands/maint.html.markdown.erb
as discussed in #[3268](https://github.com/hashicorp/consul/issues/3268) maint mode does not have any affect on the node health.
=> Updating maint.html to remove node maint

website/source/docs/enterprise/index.html.md, website/source/docs/enterprise/network-segments/index.html.md, website/source/layouts/docs.erb
Gives a marketing description for the Network Segments feature and links to the technical guide
=> Add Network Segments overview page

test/porter/cmd/porter/main.go
I was getting conflicts with things like Dropbox, so putting this in place made things more reliable, and not too slow.
=> Makes porter more conservative by trying to connect to ports before handing them out.

agent/consul/snapshot_endpoint_test.go
These could cause the tests to hang.
=> Cleans up some edge cases in TestSnapshot_Forward_Leader.

vendor/github.com/boltdb/bolt/README.md, vendor/github.com/boltdb/bolt/bolt_386.go, vendor/github.com/boltdb/bolt/bolt_amd64.go, vendor/github.com/boltdb/bolt/bolt_arm.go, vendor/github.com/boltdb/bolt/bolt_arm64.go, vendor/github.com/boltdb/bolt/bolt_ppc64.go, vendor/github.com/boltdb/bolt/bolt_ppc64le.go, vendor/github.com/boltdb/bolt/bolt_s390x.go, vendor/github.com/boltdb/bolt/bolt_windows.go, vendor/github.com/boltdb/bolt/bucket.go, vendor/github.com/boltdb/bolt/db.go, vendor/github.com/boltdb/bolt/freelist.go, vendor/github.com/boltdb/bolt/node.go, vendor/github.com/boltdb/bolt/page.go, vendor/github.com/boltdb/bolt/tx.go, vendor/vendor.json
=> Updates BoltDB to 1.3.1.

test/porter/cmd/porter/main.go
I'll merge this for now to make CI happy so it doesn't get stuck if a porter process gets killed before it can delete the temp file. It's a bit of a hack, so I'd welcome your feedback @magiconair.
=> Makes porter clean up if a porter instance died.

agent/check.go
=> Adds a brief wait and poll period to update check status after a timeout.

agent/config/builder.go, agent/config/flags.go, agent/config/flags_test.go, agent/config/runtime_test.go, agent/config/segments_oss_test.go, command/agent/agent.go, command/agent/agent_test.go
=> Revert "config: return error on extra command line arguments (#3397)"

lib/freeport/freeport.go, vendor/github.com/mitchellh/go-testing-interface/LICENSE, vendor/github.com/mitchellh/go-testing-interface/README.md, vendor/github.com/mitchellh/go-testing-interface/testing.go, vendor/github.com/mitchellh/go-testing-interface/testing_go19.go, vendor/vendor.json
This PR allows the caller to decide if they would like to have the
calling test fail, have the caller panic on error, or handle the errors
themselves.
=> Make freeport testing friendly

command/agent/agent_test.go, watch/funcs_test.go, watch/plan_test.go, watch/watch_test.go
This PR addresses the skipped tests
=> Fix skipped tests

agent/consul/state/tombstone_gc_test.go
=> Adds a small sleep to make sure we are in the next GC bucket.

agent/consul/state/tombstone_gc_test.go
=> Revert "Adds a small sleep to make sure we are in the next GC bucket."

vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/suspicion.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/vendor.json
=> Updates memberlist to pick up https://github.com/hashicorp/memberlist/pull/69.

agent/config/builder.go, agent/config/runtime_test.go
=> Skips files with unknown extensions when not forcing a format.

agent/consul/state/tombstone_gc.go, agent/consul/state/tombstone_gc_test.go
=> Sheds monotonic time info so tombstone GC bins work properly.

agent/agent.go, agent/config/default.go, agent/consul/config.go
=> Copies the autopilot settings from the runtime config.

agent/session_endpoint.go, agent/session_endpoint_test.go, api/session_test.go
=> Works around mapstructure behavior to enable sessions with no checks.

command/kv/get/kv_get.go, command/kv/get/kv_get_test.go
=> Adds -base64 support to kv get command.

agent/consul/rpc.go
Signed-off-by: Wei Wei <weiwei.inf@gmail.com>
=> fix globalRPC goroutine leak

website/source/api/agent/service.html.md
=> add missing 'Port' description in register service doc

demo/vagrant-cluster/README.md, website/source/docs/commands/index.html.md, website/source/docs/internals/anti-entropy.html.md, website/source/docs/internals/architecture.html.md, website/source/docs/internals/consensus.html.md, website/source/docs/internals/sessions.html.md, website/source/intro/vs/custom.html.md, website/source/intro/vs/skydns.html.md
=> Fix some small doc errors

website/source/api/index.html.md
Also removed a couple of extraneous spaces.
=> Corrected word order sequence

CHANGELOG.md, agent/prepared_query_endpoint.go
=>  Fixes crash where body was optional for PQ endpoint (it is not).

agent/config/builder.go, agent/config/runtime_test.go
=> Enforce a valid port for the Serf WAN since it can't be disabled.

vendor/github.com/hashicorp/go-discover/provider/azure/azure_discover.go, vendor/vendor.json
=> Fix panic in azure go discover provider

.travis.yml, GNUmakefile
This is a WIP PR to experiment with more reliable test setup with travis. Won't merge until we are happen with the changes improve the situation.
=> [WIP] Attempt to find some low-hanging fruit for CI failures

website/Gemfile, website/Gemfile.lock, website/source/index.html.erb
At the request of Mitchell and Armon, a couple small text-based fixes. Comes with a free dependency upgrade ✨
=> Small Adjustments

website/source/docs/guides/dns-cache.html.md
I updated the content based on discussion with James Phillips on 2/8/2018.
=> Updated Stale Reads section of DNS Caching Guide

website/source/docs/guides/acl.html.md
Figured it would be worth documenting based on #3931.
=> website: add UI section to ACL guide

website/source/downloads_tools.html.erb
This PR organizes the community tools list to make it
- Easier to scan
- Easier for contributors to know where they should add their tool
=> Alphabetizing community tools list

vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go
#3986 attempted to add a new vendored dep but I git-failed and didn't actually add the new files.
Since nothing is using the new lib yet it didn't break CI or builds etc.
Note that the vendor.json is already correct but the actual files were never checked in so report as missing:
```
$ govendor list | grep testify
v  github.com/stretchr/testify/assert
m github.com/stretchr/testify/require
```
=> Actually add the `require` vendored files I missed in #3986

website/source/intro/getting-started/ui.html.md
Directions on how to use the new Consul web UI added to [this page](https://www.consul.io/intro/getting-started/ui.html).
=> Directions for using the new Consul UI

website/source/docs/guides/deployment.html.md, website/source/layouts/docs.erb
Recommended practices for deploying Consul to production with notes for read-heavy, write-heavy, and other scenarios.
=> Production deployment guide

website/source/layouts/docs.erb
Will be published when it has been reviewed.
=> Revert sidebar link to Production Deployment Guide

ui-v2/app/controllers/dc/nodes/show.js, ui-v2/app/styles/components/filter-bar.scss, ui-v2/app/templates/dc/nodes/-services.hbs
Partly addresses #4115 
As well as searching on service also search by port
=> Enable searching by port in the Node > [Service] listing

ui-v2/app/templates/dc/acls/index.hbs, ui-v2/tests/acceptance/dc/acls/list-order.feature, ui-v2/tests/acceptance/steps/dc/acls/list-order-steps.js, ui-v2/tests/steps.js
Adds sorting of ACLs by Name
Fixes #4210
=> UI - Sort ACL tokens by name

website/source/docs/guides/deployment.html.md
In **Node Removal** section, clarify that server nodes are being discussed.
=> Minor clarification of server nodes

ui-v2/app/routes/application.js, ui-v2/app/templates/error.hbs, ui-v2/tests/acceptance/dc/services/error.feature, ui-v2/tests/acceptance/steps/dc/services/error-steps.js, ui-v2/tests/steps.js, ui-v2/yarn.lock
Addresses: #4265 
1. Check the dc's model for both dcs list and the requested dc.
2. If the dc model doesn't exist use and empty array for dcs and a fake
dc with the Name 'Error' as we can't even trust what is in the
`paramsFor`
=> Make sure the dc menu is as useful as possible when things go wrong

website/source/assets/stylesheets/consul-connect/_animations.scss
This should make the progress bars in the configuration page animations work again 😁
=> Configuration page animation fix

website/source/intro/index.html.md, website/source/intro/vs/istio.html.md
This includes some recommendations from readers to improve both the description of Consul itself as well as the Istio comparison.
=> website: update vs. istio page and clarify control plane & pluggable data layer

website/source/docs/connect/native.html.md
I was going to the public feedback on Connect-Native app integration and came across [this](https://twitter.com/relistan/status/1012263110403555329) thread. Added a few statements in the Connect-Native app integration page.
=> website: make performance impact explicit for connect-native

ui-v2/tests/acceptance/dc/intentions/filtered-select.feature, ui-v2/tests/acceptance/dc/intentions/form-select.feature
The vocabulary for this step was slightly different between connect and consul, this PR makes sure everything is the same
=> Tweak vocabulary to match new step vocab

website/source/docs/agent/telemetry.html.md
This PR adds some more previously undocumented telemetry metrics for Consul.
=> Website: Added more telemetry metrics.

website/source/docs/connect/configuration.html.md
Signed-off-by: M S Vishwanath Bhat <msvbhat@gmail.com>
=> Trivial spell correction in connect configuration doc

agent/consul/state/catalog.go, agent/consul/state/catalog_test.go
=> Revert "Allow changing Node names since Node now have IDs"

vendor/golang.org/x/sys/windows/svc/event.go, vendor/golang.org/x/sys/windows/svc/go12.c, vendor/golang.org/x/sys/windows/svc/go12.go, vendor/golang.org/x/sys/windows/svc/go13.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/golang.org/x/sys/windows/svc/sys_386.s, vendor/golang.org/x/sys/windows/svc/sys_amd64.s, vendor/vendor.json
This was missing and wouldn't build for windows.
=> Vendor golang.org/x/sys/windows/svc

NOTICE.md
=> Add copyright notice file

CHANGELOG.md
Additions for UI changes in the Changelog.
Will try and get these added as I go moving forwards.
Matt I popped you on this aswell as I think you'll be driving next when we do it.
=> UI: Changelog additions

api/README.md
Includes Go source that runs without modification, as well as simple
instructions for compiling, running, and viewing the output in the
Consul UI.
=> Copy-and-paste Go client example

ui-v2/ember-cli-build.js
This PR adds CSS sourcemaps whilst developing or in staging
=> UI - Non-prod CSS sourcemaps

website/source/docs/agent/options.html.md
This supercedes #4078 with some additional language.
=> Clarification for serf_wan documentation

agent/connect/ca/provider_consul.go, agent/consul/leader_test.go
Reverts hashicorp/consul#4493. Introduces a lot of CA related failures in tests.
=> Revert "CA initialization while boostrapping and TestLeader_ChangeServerID fix."

website/source/docs/guides/deployment.html.md, website/source/layouts/docs.erb
This is a placeholder commit so HashiCorp engineering can review this guide.
https://github.com/hashicorp/consul/blob/master/website/source/docs/guides/deployment.html.md
=> Engineering review needed

agent/consul/fsm/snapshot_oss.go, agent/consul/fsm/snapshot_oss_test.go
=> - Added code to allow snapshot inclusion of NodeMeta

website/source/api/connect/intentions.html.md, website/source/docs/connect/intentions.html.md
Updates related to https://github.com/hashicorp/consul/issues/4536
Couldn't find an example of a non policy ACL in the API docs so I'm not sure if the format I used it the best way to signal that.
=> Update intentions documentation to clarify ACL behavior

website/source/api/connect/intentions.html.md
Follow up from #4546 to fix all the API docs to make them consistent.
=> Intention ACL API clarification

command/rtt/rtt_test.go
@freddygv Example: https://travis-ci.org/hashicorp/consul/jobs/420864010
=> Fixed unstable test TestRTTCommand_LAN in command/rtt/rtt_test.go

connect/proxy/proxy_test.go
@freddygv : yet another unstable one :-)
=> Fixed unstable test TestProxy_public

agent/ui_endpoint_test.go
@freddygv Example: https://travis-ci.org/hashicorp/consul/jobs/420864008
=> Fixed unstable test TestUiNodeInfo

command/catalog/list/services/catalog_list_services_test.go
@freddygv Example: https://travis-ci.org/hashicorp/consul/jobs/421173461
=> Fixed unit test TestCatalogListServicesCommand

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
Just cleaning these up a tiny bit based on seeing how they're being used.
=> github: some minor changes to issue templates

ui-v2/app/models/coordinate.js, ui-v2/app/models/dc.js, ui-v2/app/models/intention.js, ui-v2/app/models/kv.js, ui-v2/app/services/session.js, ui-v2/tests/helpers/api.js, ui-v2/tests/helpers/measure.js, ui-v2/tests/helpers/repo.js, ui-v2/tests/integration/services/acls-test.js, ui-v2/tests/integration/services/coordinates-test.js, ui-v2/tests/integration/services/dc-test.js, ui-v2/tests/integration/services/intentions-test.js, ui-v2/tests/integration/services/kvs-test.js, ui-v2/tests/integration/services/nodes-test.js, ui-v2/tests/integration/services/services-test.js, ui-v2/tests/integration/services/sessions-test.js, ui-v2/tests/lib/measure/getMeasure.js, ui-v2/yarn.lock
This PR is just re-merging https://github.com/hashicorp/consul/pull/4454 (see link for info) down onto master, there are no further additions additional to that PR.
Originally the idea was to go ahead and refactor the repo layer slightly following on from these tests. But I'm going to shelve this refactoring for the moment and come back in soon to do it. These tests can be used for my upcoming work also.
=> UI: Repo layer integration tests (#4454)

CHANGELOG.md
Changelog additions, needs approval to merge.
=> Updated CHANGELOG.md with the dns recursor fix.

website/source/docs/guides/deployment.html.md
- Mentions XL machine specs for 3 cloud vendors
- Links to gossip tuning configuration docs
- Links to non-voting server feature
- Links to performance tuning section of guide
=> Adds XL machine spec and notes on large deployments

agent/agent_test.go, command/connect/ca/set/connect_ca_set_test.go, command/operator/autopilot/get/operator_autopilot_get_test.go, command/operator/autopilot/set/operator_autopilot_set_test.go, connect/proxy/proxy_test.go, connect/service_test.go, connect/tls_test.go, watch/funcs_test.go
@freddygv Some other unstable tests in Travis
=> Fixed unstable tests

watch/funcs_test.go
=> Fixed unit test TestServicesWatch

agent/consul/catalog_endpoint_test.go, agent/consul/leader_test.go, agent/consul/rtt_test.go, agent/consul/session_endpoint_test.go, agent/consul/snapshot_endpoint_test.go
@freddygv See https://travis-ci.org/hashicorp/consul/jobs/422421749
=> Fixed unstable unit tests as seen in https://travis-ci.org/hashicorp/consul/jobs/422421749

agent/agent.go, agent/agent_endpoint.go
This fixes https://github.com/hashicorp/consul/issues/4648 and avoid having many many proxies accumulating over time
=> [Connect][Bugfix] Ensure that Proxies ARE always cleaned up, event with DeregisterCriticalServiceAfter

website/source/docs/platform/k8s/dns.html.md, website/source/docs/platform/k8s/helm.html.md, website/source/docs/platform/k8s/index.html.md, website/source/docs/platform/k8s/run.html.md, website/source/layouts/docs.erb
This adds the initial docs for the helm chart being released tomorrow, along with basic K8S overviews.
=> Initial Helm Chart/K8S Docs

command/catalog/list/dc/catalog_list_datacenters.go
Fixes #4582. Seemed like a simple enough change so I just did it :) I tested by building on Linux.
=> Exit with error code 1 when failing to list DCs

README.md
=> Update required golang version in Readme

ui-v2/tests/acceptance/dc/intentions/create.feature
Make sure we specifically set and test for deny on testing intention creation.
No change to UI code
=> ui: Test bugfix. Specifically set deny for intention creation

website/source/docs/connect/index.html.md
=> fix typo on connect/index

agent/agent_endpoint.go
=> Fix prometheus error message

agent/agent.go, agent/agent_endpoint.go, agent/config/builder.go, agent/config/config.go, agent/config/runtime.go, agent/config/runtime_test.go, agent/consul/config.go, agent/consul/connect_ca_endpoint.go, agent/consul/leader.go, agent/consul/leader_oss.go, agent/consul/server.go, agent/structs/connect_ca.go, agent/token/store.go, website/source/api/acl.html.md, website/source/docs/agent/options.html.md, website/source/docs/guides/acl.html.md, website/source/docs/guides/areas.html.markdown.erb
This re-adds the docs and OSS code changes to the 1.4.0 branch.
=> re-add Connect multi-dc config changes

website/source/docs/platform/k8s/helm.html.md
In response to consul-helm issue 16.
=> Add additional formatting detail to the Helm `join` command docs

agent/consul/acl_endpoint_test.go
=> ACL V2 RPC additional RPC tests

website/source/docs/commands/debug.html.markdown.erb, website/source/downloads.html.erb, website/source/index.html.erb
=> website: minor notes about 1.4.0

website/source/api/session.html.md
Updated the response json with the true response from Consul 1.2.2
=> docs: update the response json fields

agent/acl_endpoint.go, api/acl.go, api/acl_test.go
This is one of a few PRs to finish #4833 
This is a follow up to the original ACL PR. I implemented unit tests to exercise the new functions in the api package related to ACLs.
This also uncovered several other issues which have all been fixed.
=> New ACL API Tests

website/source/docs/guides/index.html.md
The sidebar was out of sync with the list of guides.
=> Sync guides list with guides sidebar.

website/source/docs/agent/options.html.md
I actually requested the content-type sniffing be removed from the feature PR here: https://github.com/hashicorp/consul/pull/4016#discussion_r183110645 however we missed removing it from the docs!
=> Correct prometheus docs

website/source/docs/agent/options.html.md
=> website: clarify log file filename format

command/debug/debug.go
Before this fix the debug snapshot archive may still be created in incomplete states, or not be persisted to disk.
=> command/debug: make better use of atomic operations to write out the debug snapshots to disk

api/api.go
There should be no space before a comma
=> Remove wrong space character

website/source/docs/guides/acl.html.md
Fixes a couple minor things I found looking over the ACL guide.
=> docs: fix some examples in the new ACL guide

agent/agent_endpoint.go, command/acl/token/token.go, website/source/docs/commands/debug.html.markdown.erb, website/source/docs/connect/index.html.md, website/source/docs/enterprise/connect-multi-datacenter/index.html.md, website/source/docs/guides/acl-legacy.html.md, website/source/docs/guides/acl.html.md, website/source/downloads.html.erb, website/source/index.html.erb, website/source/layouts/docs.erb
This is some minor docs prep for the 1.4 final that we'll need to merge prior.
=> Doc changes for 1.4 Final

website/source/docs/guides/acl-migrate-tokens.html.md, website/source/docs/upgrade-specific.html.md, website/source/layouts/docs.erb
A very WIP preview for early review. Will complete tomorrow.
=> Acl upgrade guide

website/source/docs/guides/consul-template.html.md, website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
I have created a new guide for Consul Template based on the repos README. Some of the language should look familiar.
=> Adding the new Consul Template Guide.

website/source/docs/guides/consul-aws.html.md, website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
This is the guide for [consul-aws](https://github.com/hashicorp/consul-aws) written by @i0rek.
=> website: add consul-aws guide from @i0rek

website/source/docs/guides/consul-template.html.md
Minor edits to consul-template guide.
=> Corrects you/your and camel-casing of "GitHub"

website/source/docs/guides/autopilot.html.md
=> Fixed typos in autopilot doc

ui-v2/app/components/modal-dialog.js, ui-v2/app/components/modal-layer.js, ui-v2/app/components/tabular-collection.js, ui-v2/app/utils/form/builder.js, ui-v2/ember-cli-build.js
This PR make some small changes resulting from a post merge review of https://github.com/hashicorp/consul/pull/4789
1. Change the imported name of Components to reflect that they are not the base Component (see https://github.com/hashicorp/consul/pull/4789#discussion_r229544671).
2. Alter a couple of comments (see https://github.com/hashicorp/consul/pull/4789#discussion_r229817203 and https://github.com/hashicorp/consul/pull/4789#discussion_r229818832)
(sorry about the wait for this @DingoEatingFuzz !)
=> UI: ACL review amends

ui-v2/app/styles/components/flash-message/skin.scss, ui-v2/app/templates/components/app-view.hbs
=> ui: Adds warning flash messages (yellow with warning icon)

website/source/api/session.html.md
Fixes https://github.com/hashicorp/consul/issues/3675.
=> website: clarify format of check IDs for sessions

website/source/api/catalog.html.md
=> website: clarify catalog registration ID behavior

agent/consul/operator_raft_endpoint_test.go, agent/consul/session_ttl_test.go, api/acl_test.go, api/catalog_test.go, api/operator_autopilot_test.go, api/status_test.go
As seen in https://travis-ci.org/hashicorp/consul/jobs/460824602
@freddygv This is a forever quest :-)
=> [Travis][UnstableTests] Fixed unstable tests in travis

website/source/downloads_tools.html.erb
A simple tool for benching performance of Consul with large workloads
=> Added consul-bench tool to list of community tools

command/commands_oss.go, command/tls/ca/create/tls_ca_create.go, command/tls/ca/create/tls_ca_create_test.go, command/tls/ca/tls_ca.go, command/tls/ca/tls_ca_test.go, command/tls/cert/create/tls_cert_create.go, command/tls/cert/create/tls_cert_create_test.go, command/tls/cert/tls_cert.go, command/tls/cert/tls_cert_test.go, command/tls/generate.go, command/tls/generate_test.go, command/tls/tls.go, command/tls/tls_test.go, website/source/docs/commands/tls.html.md, website/source/docs/commands/tls/ca.html.md.erb, website/source/docs/commands/tls/cert.html.md.erb, website/source/docs/guides/creating-certificates.html.md, website/source/layouts/docs.erb
This PR adds builtin helpers to setup agent CAs and certificates for Consul TLS!
=> Builtin tls helper

website/source/docs/guides/agent-encryption.html.md
removed an extra period that messed up formatting
=> Fixed bad formatting

website/source/docs/guides/acl-legacy.html.md, website/source/docs/guides/acl.html.md
=> website: fix stray sentinel references using the old syntax

website/source/docs/connect/index.html.md
Fixes https://github.com/hashicorp/consul/issues/5182.
=> website: fixed ca provider references

website/source/docs/guides/backup.html.md, website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
Updating the index and sidebar nav.
=> Update links for learn migration

agent/consul/intention_endpoint.go
One more thing to bring over from the enterprise fixes.
=> connect: Forward intention RPCs if this isn't the primary

website/source/docs/platform/k8s/helm.html.md
=> Fix repeating wording in sentence

agent/http_oss_test.go, testrpc/wait.go
`TestHTTPAPI_MethodNotAllowed_OSS` tests all HTTP API endpoints crossed with HTTP methods to verify that only allowed methods work.
This is slow (~11 seconds) but not because of the quantity of work done. It's slow because when it does correctly verify a method _does_ work, it does so by actually invoking the RPC. This is test overreach.
To speed it up this PR enabled default-deny ACLs. ACLs are checked AFTER the method allow list is checked, so you still can correctly detect a http `405` response code (as the test is supposed to do) but we don't end up invoking slow endpoints like the agent leave endpoint which takes about 11 seconds all on its own to execute for unrelated reasons.
=> speed up TestHTTPAPI_MethodNotAllowed_OSS from 11s -> 0.5s

website/source/api/agent/service.html.md
Just a broken link the link checker found.
=> Broken link on API service docs

website/source/docs/agent/checks.html.md
=> Corrects `defile` to `defined`

website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
- Fixing broken link to DNS Caching guide on Learn.
- Fixed ordering of Datacenter Backup guide.
=> Fixing broken link.

website/source/api/libraries-and-sdks.html.md
Update the section `Client Libraries & SDKs` for add a new librarie to convert KV-Store (JSON) to environment variables with Webpack in web apps.
=> Documentation - New plugin for frontend applications based in webpack

agent/consul/server.go, agent/consul/state/acl.go, agent/consul/state/state_store.go, command/acl/policy/create/policy_create.go, website/source/docs/commands/acl/acl-policy.html.md.erb
This is just a collection of a few small changes that I ran across while in the process of working on other things. They seemed almost too small for their own PRs and I didn't want to clutter any future PRs with unrelated commits.
=> various small fixes

agent/consul/acl_endpoint_test.go
Also in `acl_endpoint_test.go`:
* convert logical blocks in some token tests to subtests
* remove use of require.New
This removes a lot of noise in a later PR.
=> test: switch test file from assert -> require for consistency

logger/logfile.go, logger/logfile_test.go
=> Fix logfile open filemode

website/source/docs/commands/acl/acl-bootstrap.html.md.erb, website/source/docs/guides/acl.html.md
- Added instructions for resetting the ACL system to the bootstrapping guide.
- Added link to bootstrapping guide to the ACL command docs.
=> [docs] ACL reset procedure

website/source/docs/platform/k8s/helm.html.md
- Updated the Helm chart to include ACL parameter 
- Added examples of the Helm Chart.
- Updated the formatting for readability.
=> [Docs] Helm Chart

ui-v2/app/mixins/with-health-filtering.js, ui-v2/app/styles/components/app-view.scss, ui-v2/app/styles/core/typography.scss, ui-v2/app/templates/components/catalog-filter.hbs, ui-v2/app/templates/dc/acls/index.hbs, ui-v2/app/templates/dc/intentions/index.hbs, ui-v2/app/templates/dc/nodes/index.hbs, ui-v2/app/templates/dc/services/index.hbs, ui-v2/tests/integration/components/catalog-filter-test.js
This PR implements the work outlined here:
https://github.com/hashicorp/consul/issues/4158#issuecomment-461151993
=> UI: Service Numbers

agent/consul/acl_endpoint_test.go
Lifted from PR #5307 as it was an unrelated drive-by fix on that PR anyway.
s/token/policy/
=> fix incorrect body of TestACLEndpoint_PolicyBatchRead

website/source/downloads_tools.html.erb
Please add Consul K/V Support plugin to the list of community tools.
=> [docs] Add IntelliJ Consul to the list of community tools

ui-v2/app/routes/dc.js, ui-v2/app/routes/dc/acls/create.js, ui-v2/app/routes/dc/acls/edit.js, ui-v2/app/routes/dc/acls/index.js, ui-v2/app/routes/dc/acls/policies/edit.js, ui-v2/app/routes/dc/acls/policies/index.js, ui-v2/app/routes/dc/acls/tokens/edit.js, ui-v2/app/routes/dc/acls/tokens/index.js, ui-v2/app/routes/dc/intentions/create.js, ui-v2/app/routes/dc/intentions/edit.js, ui-v2/app/routes/dc/intentions/index.js, ui-v2/app/routes/dc/kv/create.js, ui-v2/app/routes/dc/kv/edit.js, ui-v2/app/routes/dc/kv/index.js, ui-v2/app/routes/dc/nodes/index.js, ui-v2/app/routes/dc/nodes/show.js, ui-v2/app/routes/dc/services/index.js, ui-v2/app/routes/dc/services/instance.js, ui-v2/app/routes/dc/services/show.js, ui-v2/app/routes/settings.js
See https://github.com/hashicorp/consul/pull/5326#discussion_r257354670
=> UI: Remove call to super in setupController

.circleci/config.yml
This PR changes the CircleCI configuration to version 2.0 compatibility. There should be no change in functionality.
=> refactor circleci config to 2.0

agent/agent.go, agent/agent_test.go
Fix my recently discovered issue described here: #5456
=> Fix checks removal when removing service

website/source/docs/agent/acl-rules.html.md, website/source/docs/agent/acl-system.html.md, website/source/docs/agent/checks.html.md, website/source/docs/agent/options.html.md, website/source/docs/guides/acl.html.md
Cleaup code snippets
Fix broken links
Remove unused example config option
Minor sentence tweeks
=> Docs Proofing

agent/agent.go
This will fix https://github.com/hashicorp/consul/issues/5351
=> Ensure we remove Connect proxy before deregistering the service itself

agent/agent_test.go, agent/testagent.go
I realized that my `NewUnstartedAgent` is doing things that are none of its business.
=> Use TestAgent when appropriate

website/source/docs/guides/index.html.md, website/source/docs/guides/network-segments.html.md, website/source/layouts/docs.erb
Updating network segments guide for migration. 
- converted file to markdown
- added sections and headers
- added summary
=> [docs] Network Segments

api/agent.go, api/agent_test.go
=> api: fix panic in 'consul acl set-agent-token'

.circleci/config.yml, build-support/functions/20-build.sh
This PR will build binaries for all the distros we usually release to make sure PRs and any new commits don't introduce anything that will break the binary build.
=> Add xc builds

website/source/docs/guides/production-acls.html.md
=> [docs] Production ACLs

website/source/docs/guides/forwarding.html.md
Updated for migration.
- added summary
- updated headings for clarity
- updated intro
=> [docs] DNS Forwarding

website/source/docs/acl/acl-legacy.html.md, website/source/docs/acl/acl-migrate-tokens.html.md, website/source/docs/acl/acl-rules.html.md, website/source/docs/acl/acl-system.html.md, website/source/docs/acl/index.html.md, website/source/docs/guides/index.html.md, website/source/layouts/docs.erb
With the guide migration to Learn in progress, it became clear that some ACL work didn't have a good place on either site. This PR includes:
- New "Access Control (ACLs) side nav under "Agent".
- ACL System and ACL Rules have been moved from "Agent" to "Access Control".
- The legacy and migration guides moved to "Access Control".
- The "What changed" section from the migration guided move to the legacy documentation. This was based on customer feedback and further reflection on the guides goal.
=> [docs] ACL Side Navigation Added

website/source/docs/guides/semaphore.html.md
Updates:
- Added section headers
- Renamed the first header
- added summary
- removed some information that seemed confusing
**Please let me know if the heading titles make sense.**
=> [docs] Semaphore

website/source/docs/guides/connect-envoy.md
=> Revert "[docs] Connect with Envoy Guide"

website/source/docs/guides/connect-envoy.md
- Reimplement changes from the reverted PR #5505 
- fix line lengths
=> [docs] reimplement changes from PR #5505

website/source/docs/guides/deployment-guide.html.md
Update EA front matter to indicate this content is valid for Consul 1.4.
=> EA has validated that this content works with Consul 1.4

website/source/docs/guides/deployment.html.md
Update EA front matter to indicate this content is valid for Consul 1.4.
=> EA has validated this content as working with Consul 1.4

website/source/docs/guides/datacenters.html.md
Updates:
- Added headers
- Added example output
- Rearranged content
- added summary
=> [docs] Basic Federation

website/source/docs/guides/connect-production.md
Updating guide to prepare for Learn migration. The updates are:
- remove roadmap/future feature language 
- added a summary
- added some code examples
- Moved subsections to callouts
=> [docs] Connect in Production

.circleci/config.yml
This PR adds uploading of the dev binary to our dev s3 bucket. This will only be built for non-PR branches (prefixed with `pull-*`).
=> add s3 upload to dev bucket

website/source/docs/platform/k8s/helm.html.md
Correct security warning about helm chart to caution about default Consul install.
=> [docs] security warning about Helm chart

go.mod, go.sum, vendor/github.com/hashicorp/raft/CHANGELOG.md, vendor/github.com/hashicorp/raft/Makefile, vendor/github.com/hashicorp/raft/README.md, vendor/github.com/hashicorp/raft/api.go, vendor/github.com/hashicorp/raft/commitment.go, vendor/github.com/hashicorp/raft/configuration.go, vendor/github.com/hashicorp/raft/inmem_store.go, vendor/github.com/hashicorp/raft/inmem_transport.go, vendor/github.com/hashicorp/raft/net_transport.go, vendor/github.com/hashicorp/raft/raft.go, vendor/github.com/hashicorp/raft/replication.go, vendor/modules.txt, website/source/docs/agent/telemetry.html.md
New metrics were added to raft in [raft-316](https://github.com/hashicorp/raft/pull/316).
This PR re-vendors raft and updates Consul documentation to include the new metrics.
=> Add additional raft metrics

.circleci/config.yml, GNUmakefile
This PR will checkout the code outside the GOPATH and use go modules properly.
=> CircleCI: Checkout code outside GOPATH

logger/logfile.go, logger/logfile_test.go, logger/logger.go
Fixes the issue where when logging to file, it does not respect the log level filters. This PR fixes it by filtering out logs not matching the log level criteria.
Addressed issue: https://github.com/hashicorp/consul/issues/4778
=> Fix logfile filter bug

website/source/docs/guides/windows-guide.html.md
Updates for the Learn migration.
- headers
- new summary
- fixed formatting
We can add more updates as needed later.
=> [docs] Windows Guide

agent/consul/config.go, website/source/docs/agent/options.html.md, website/source/docs/agent/telemetry.html.md, website/source/docs/faq.html.md, website/source/docs/guides/connect-production.md, website/source/docs/guides/deployment-guide.html.md, website/source/docs/guides/deployment.html.md, website/source/docs/guides/index.html.md, website/source/docs/install/performance.html.md, website/source/docs/upgrade-specific.html.md, website/source/layouts/docs.erb
Moving server performance guide to docs. No content updates were made.
=> [docs] Server Performance

website/source/docs/guides/geo-failover.html.md
Updated the headers, code snippets, and some language.
Language updates include:
- "Failover Policy _Types_"
- cumbersome -> challenging
- api app -> banking- app
- templates -> prepared query template
=> [docs] Geo Failover

website/source/docs/guides/deployment.html.md
Updating network connectivity section based on feedback from Pavani.
=> [docs] Reference Architecture Update

website/source/docs/agent/services.html.md
=> Add missing token field in the service definition in the docs

website/source/api/agent/connect.html.md
Fixes https://github.com/hashicorp/consul/issues/5447
=> 5447 - Fixing inconsitencies in agent/connect API documentation

agent/agent.go, agent/config/builder.go, agent/config/config.go, agent/config/runtime.go, agent/config/runtime_test.go, agent/consul/config.go, agent/consul/leader.go, agent/consul/leader_test.go, agent/consul/server.go, agent/consul/server_test.go, website/source/docs/agent/options.html.md
I still need to write up some docs for this but otherwise it should be good to go.
TODO:
=> Implement bootstrapping proxy defaults from the config file

ui-v2/app/components/phrase-editor.js, ui-v2/app/controllers/dc/services/index.js, ui-v2/app/routes/dc/services/index.js, ui-v2/app/search/filters/service.js, ui-v2/app/styles/base/icons/base-placeholders.scss, ui-v2/app/styles/base/icons/index.scss, ui-v2/app/styles/components/index.scss, ui-v2/app/styles/components/phrase-editor.scss, ui-v2/app/styles/components/phrase-editor/index.scss, ui-v2/app/styles/components/phrase-editor/layout.scss, ui-v2/app/styles/components/phrase-editor/skin.scss, ui-v2/app/styles/components/pill/layout.scss, ui-v2/app/styles/components/pill/skin.scss, ui-v2/app/templates/components/phrase-editor.hbs, ui-v2/app/templates/dc/services/index.hbs, ui-v2/app/utils/search/filterable.js, ui-v2/tests/acceptance/components/catalog-filter.feature, ui-v2/tests/integration/components/phrase-editor-test.js
This PR is a collection of PRs to improve the search experience in the UI
- initial `phrase-editor` component (#5507)
=> ui: Search improvements

website/source/api/agent/connect.html.md
Completes the fix for #5447 missed by #5715. Thanks to @andye2004.
=> fix agent in connect docs

agent/config/runtime_test.go
CI build is failing because this file doesn't conform to go fmt
=> go fmt runtime_test

website/source/docs/agent/telemetry.html.md
Updating docs/agent/telemetry reference to include serf member events. Fixes https://github.com/hashicorp/consul/issues/5400
=> Adding documentation for Serf telemetry metrics

website/source/docs/acl/index.html.md
Also word wrap all of the other paragraphs on the acl overview doc for future PRs.
=> docs: add an overview section for the auth method docs

website/source/docs/guides/index.html.md
Fix Kubernetes operations anchor link.
=> [docs] fix kubernetes operations anchor link

website/source/redirects.txt
Redirecting until the containers guide is complete.
=> [docs] Redirect for Containers Guide

website/source/index.html.erb
Just updates this little alert message.
=> website: update to 1.5 on homepage link

website/source/docs/platform/k8s/index.html.md
Missing dot in Consul Kubernetes landing page.
=> docs/Consul Kubernetes landing page

website/source/docs/agent/telemetry.html.md
Fixed spelling and wording: avaliable/available, upto/up to, an other/another, recieved/received, transfered/transferred (x2)
=> docs: spelling and wording

website/source/docs/platform/k8s/dns.html.md
=> docs: fixed spelling

website/source/docs/platform/k8s/connect.html.md, website/source/docs/platform/k8s/helm.html.md
Additionally defines a new annotation that is used with these new
features.
=> Add docs for Helm chart features introduced in v0.8.0

website/source/docs/acl/acl-rules.html.md
=> docs: fixed typo

website/source/docs/enterprise/connect-multi-datacenter/index.html.md
Fixed typo: authorative/authoritative.
=> docs: spelling

agent/coordinate_endpoint_test.go, website/source/docs/enterprise/connect-multi-datacenter/index.html.md
Logic updated to evaluate with a boolean after the type assertion.
This allows us to check if the type assertion succeeded and be
more clear with errors.
=> Update type assertion logic

agent/consul/stats_fetcher_test.go
This test has been fragile in CI, this PR adds retries to address timing issues where we don't get responses from all servers.
=> Add retries to StatsFetcherTest

agent/consul/session_ttl_test.go
This test has been flaky in CI at a few points:
1. The `Get` after the `time.Sleep(ttl)`. This block assumes that no more than 2*ttl will pass before the `Get`, but that's not always the case. We've had failures where more time passed than expected, the timer is gone, and the test fails.
2. The check for the timer to be gone by `2*ttl` in L202. There are times when more than `2*ttl` time passes after the continue below.
For issue 1 a retry was added. For issue 2 that check is removed and a retry was added to ensure early invalidation didn't happen. 
The check from issue 2 was removed because `TestResetSessionTimerLocked` already verifies that timers are removed after they expire.
=> Increase reliability of TestResetSessionTimerLocked_Renew

website/source/docs/commands/connect/envoy.html.md.erb
=> Update default grpc-addr value in connect envoy command

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/question.md
Small PR updating the issue template for questions to direct users to the new HashiCorp forum
=> Update questions issue template directing q's to the forum

website/source/docs/commands/operator.html.markdown.erb
=> Fix documentation consul operator

website/source/docs/commands/acl/token.html.md.erb
Fixed wording: "will be resolve to the" -> "will be resolved to the".
=> docs: wording

website/source/docs/internals/security.html.md
Fixed typos: alterative/alternative & communciation/communication
=> docs: fixed typos

ui-v2/app/utils/atob.js, ui-v2/app/utils/btoa.js, ui-v2/package.json, ui-v2/tests/helpers/yadda.js, ui-v2/yarn.lock
=> ui: Adds ember-auto-import and replaces the 3 places where we used `npm:`

website/source/docs/platform/k8s/connect.html.md
Adds documentation for services, multiple services, and prepared
query under connect-service-upstreams annotation.
=> [docs] update documentation for connect-service-upstreams

website/source/assets/javascripts/application.js, website/source/assets/javascripts/consul-connect/home-hero.js, website/source/assets/stylesheets/consul-connect/pages/_home.scss, website/source/index.html.erb
This PR accomplishes the following things:
- Home hero carousel js has been added to application.js
- The homepage video carousel was never set up properly to work with Turbolinks.  This change will properly load the video carousel js when the `turbolinks:load` event is triggered.  It will also properly reset the carousel when leaving the homepage and returning, whereas previously the carousel would end up in an unusable state.
- Progress bars no longer use css transitions based on video length to determine progress.  They now check the position of the video and adjust width accordingly, preventing progress bars and videos from becoming out of sync.
=> website - updates to home hero video carousel

agent/consul/catalog_endpoint_test.go, agent/consul/state/catalog.go
My previous PR for tagged service addresses missed this little bit.
=> Ensure that looking for services by addreses works with Tagged Addresses

website/source/docs/internals/architecture.html.md
Updating the term node to be more clear. Since we are not discussing external services in this doc, most instances of node can be updated to be agent.
=> [docs] Architecture Node vs Agent

ui-v2/app/templates/components/healthcheck-output.hbs, ui-v2/tests/acceptance/components/copy-button.feature, ui-v2/tests/acceptance/steps/components/copy-button-steps.js
=> Add feature test for copy button

agent/proxycfg/manager_test.go, agent/proxycfg/testing.go
#6013 added a field but did not update a test
=> fix test that was failing after #6013

command/agent/agent.go
check if key is present instead of printing the key itself.
=> check for gossip encrypt key

agent/xds/listeners.go
=> Don't use WatchedDatacenters in the xds code as those get nil'ed out prior to sending to xds

website/source/docs/agent/encryption.html.md
=> [docs] Link to TLS guide in Encryption doc

agent/config/config.go, agent/consul/discoverychain/compile.go, agent/proxycfg/state.go, agent/xds/clusters.go, agent/xds/clusters_test.go, agent/xds/config.go, agent/xds/endpoints.go, agent/xds/listeners.go, agent/xds/listeners_test.go, agent/xds/routes.go, agent/xds/server_test.go, agent/xds/sni.go, agent/xds/testdata/clusters/custom-local-app.golden, agent/xds/testdata/clusters/custom-timeouts.golden, agent/xds/testdata/clusters/custom-upstream.golden, agent/xds/testdata/clusters/defaults.golden, agent/xds/testdata/endpoints/defaults.golden, agent/xds/testdata/listeners/custom-public-listener.golden, agent/xds/testdata/listeners/custom-upstream.golden, agent/xds/testdata/listeners/defaults.golden, agent/xds/testdata/listeners/http-public-listener.golden, agent/xds/testdata/listeners/http-upstream.golden, agent/xds/testdata/listeners/listener-bind-address-port.golden, agent/xds/testdata/listeners/listener-bind-address.golden, agent/xds/testdata/listeners/listener-bind-port.golden, test/integration/connect/envoy/case-grpc/verify.bats
Just opening this for visibility on behalf of @mkeeler. This changes cluster naming to be based on SNI.
=> Make cluster names SNI always

website/source/docs/guides/connect-gateways.md
=> [docs] Guide - Connecting Services Across Datacenters

agent/consul/config.json
This was for local testing only.
=> Remove dummy agent config

api/health_test.go
Some tests in api pkg had retries that weren't retrying.
=> Fix some retries in api pkg

ui-v2/package.json, ui-v2/yarn.lock
All related to:
- https://github.com/lodash/lodash/pull/4336
=> ui: Force upgrades lodash and lodash submodules

agent/consul/catalog_endpoint_test.go, agent/coordinate_endpoint_test.go, agent/remote_exec_test.go, api/acl_test.go, api/catalog_test.go, api/lock_test.go, api/operator_autopilot_test.go, command/connect/proxy/register_test.go
Fixes:
https://circleci.com/gh/hashicorp/consul/52237
=> Update retries to use retry.R

.circleci/config.yml
This should _not_ be merged until the lint failures are fixed. Otherwise everyone will see red 😭
=> add lint-consul-retry tool

test/integration/connect/envoy/run-tests.sh
I have a suspicion that certain test cases were interacting with each other via containers that were restarted from a prior case, rather than recreated.
Also if a test run were interrupted via `ctrl-c` it would leave behind some containers that would be erroneously resumed upon the next run  by whichever case went first.
To avoid this before we start any container, attempt to stop and remove it first to force those containers to be recreated completely.
=> tests: when running envoy integration tests try to limit container bleedover between cases

website/source/docs/connect/mesh_gateway.html.md
Add more detail about the Consul configurations required to use mesh gateways
=> Detail required settings in Gateway doc

website/source/docs/agent/encryption.html.md
=> [docs] Encryption docs update

agent/checks/grpc.go, agent/consul/acl_replication_types.go, agent/xds/clusters.go
None of these changes should have any side-effects. They're merely
fixing tautological mistakes.
=> Fixed a few tautological condition mistakes

agent/consul/state/acl_test.go, agent/consul/state/catalog_test.go
Just a few nitpicky typo fixes.
=> Fixed typos in comments

website/source/docs/guides/kubernetes-production-deploy.md
This guide covers deploying Consul with some production recommendations and includes a complete helm chart example.
=> [docs] New K8s-Consul deployment guide

agent/config/runtime_test.go, agent/structs/config_entry_discoverychain.go, agent/structs/config_entry_discoverychain_test.go, agent/structs/config_entry_test.go, agent/xds/routes.go, agent/xds/routes_test.go, agent/xds/testdata/routes/connect-proxy-with-chain-and-router.golden, api/config_entry_discoverychain.go, command/config/write/config_write_test.go, website/source/docs/agent/config-entries/service-router.html.md
=> connect: allow L7 routers to match on http methods

agent/consul/fsm/commands_oss_test.go
This ensures that it's not just a single operation we restores
successfully, but many. It's the same foundation, just with multiple
going on at once.
=> Make the chunking test multidimensional

.circleci/config.yml
This PR checks the vendor folder to make sure it is in sync with what is in `go.mod`.
=> check vendor folder

agent/consul/discoverychain/compile.go, agent/consul/discoverychain/compile_test.go, agent/consul/discoverychain/string_stack.go, agent/consul/discoverychain/string_stack_test.go, agent/consul/state/config_entry.go, agent/consul/state/config_entry_test.go, agent/structs/discovery_chain.go
=> connect: detect and prevent circular discovery chain references

website/source/api/agent/service.html.md
Refs https://github.com/hashicorp/consul/pull/6220/files/7ece6fbad8ad26caf753aa38be0f8ba1c68efc18#r312614317, oops 😬
=> website: restore accidental JSON deletion

agent/agent_endpoint.go, agent/agent_endpoint_test.go, api/agent_test.go
=> Update the v1/agent/service/:service endpoint to output tagged addresses

website/source/intro/vs/proxies.html.md
=> docs: Fix typo layey > layer

website/source/mesh.html.erb
=> website: fix typo on mesh page

agent/proxycfg/testing.go, agent/xds/clusters.go, agent/xds/clusters_test.go, agent/xds/testdata/clusters/custom-local-app.golden, agent/xds/testdata/clusters/custom-timeouts.golden, agent/xds/testdata/clusters/custom-upstream-default-chain.golden, agent/xds/testdata/clusters/custom-upstream.golden, agent/xds/testdata/clusters/defaults.golden
=> Fix cluster escape hatch

ui-v2/GNUmakefile, ui-v2/_redirects
This PR adds a Makefile target and redirects for Netlify PR previews ready for PRs made to `ui-staging`
(thanks @backspace !)
=> ui: Netlify previews

ui-v2/tests/acceptance/dc/services/instances/show.feature
This PR includes a test fix that is included in https://github.com/hashicorp/consul/pull/6386/commits/d3fd0cf1eca999f3ef9bcf06351fe821eec2a370 that is yet to be merged.
=> ui: Fix metaData test as result of new consul-api-double

website/source/docs/partnerships/index.html.md
@hashicorp/consul-docs @pearkes Adding this new PR for revisions.
=> Consul Integration Program - Fixed broken links on consul program page

ui-v2/app/styles/components/dom-recycling-table/layout.scss, ui-v2/app/styles/components/tag-list/layout.scss
Hi,
We have services with a huge number of tags in our company and we are faced with the fact that in the current UI they are displayed incorrectly: when a line of tags reaching the edge of the screen, it is not wrapped to the next line.
These changes fix it.
=> bugfix: tags list layout

website/source/docs/guides/containers-guide.md
Adding the updated containers guide that will be deployed on Learn only. @tryan225 completed the updates and we tested the guide several times!
=> [docs]Updated Containers Guide

website/source/downloads_tools.html.erb
Signed-off-by: bjaroszewski <bjaroszewski@griddynamics.com>
=> website, add git2consul-go to the tools list

website/source/docs/platform/k8s/dns.html.md, website/source/docs/platform/k8s/helm.html.md, website/source/docs/platform/k8s/service-sync.html.md
If ACLs are added then slightly different commands are needed.
Note: needs #6180 merged first
=> Update consul-helm enterprise docs for ACLs

website/source/assets/stylesheets/_inner.scss
This will make them stand out more and matches the style of terraform.io
=> Give code blocks coloured background

website/source/index.html.erb
=> website: update alert bar on homepage

agent/consul/acl_token_exp.go, agent/consul/leader.go, agent/consul/leader_connect.go, agent/consul/leader_routine_manager.go, agent/consul/leader_routine_manager_test.go, agent/consul/replication.go, agent/consul/replication_test.go, agent/consul/server.go
Switch over the following to use it for go routine management:
• Config entry Replication
• ACL replication - tokens, policies, roles and legacy tokens
• ACL legacy token upgrade
• ACL token reaping
• Intention Replication
• Secondary CA Roots Watching
• CA Root Pruning
=> Implement Leader Routine Management

README.md
Add CircleCI and Discuss badge/link. Removed Gitter chat and Mailing List links. 
Closes #6598
=> add circleci and discuss badge

.circleci/config.yml
Looks like it doesn't make it significantly faster but maybe in the future it will be with more deps.
=> add go cache to distro builds

agent/config/builder.go, agent/config/runtime_test.go
=> ui_content_path config option fix

website/source/docs/acl/acl-system.html.md, website/source/docs/agent/basics.html.md, website/source/docs/agent/checks.html.md, website/source/docs/agent/dns.html.md, website/source/docs/agent/encryption.html.md, website/source/docs/agent/kv.html.md, website/source/docs/agent/options.html.md, website/source/docs/agent/services.html.md, website/source/docs/agent/telemetry.html.md, website/source/docs/connect/mesh_gateway.html.md, website/source/docs/connect/observability.html.md, website/source/docs/connect/proxies/built-in.md, website/source/docs/connect/registration/sidecar-service.md, website/source/docs/connect/security.html.md, website/source/docs/install/index.html.md, website/source/docs/internals/architecture.html.md, website/source/docs/platform/k8s/helm.html.md, website/source/docs/platform/k8s/index.html.md, website/source/docs/platform/k8s/run.html.md
Review the CPE project (COS-002) for details.
=> [docs] Adding Links to Learn

agent/consul/leader_connect_test.go
This fixes a test that failed for me locally virtually every attempt.
The test is not waiting for the secondary CA to actually initialize before asserting that the CA setup is complete. This retry is about the most direct way to correctly wait for the state update and fixes it locally for me reliably so far.
=> Allow time for secondary CA to initialize

agent/consul/leader_connect_test.go
Fixes something introduced in #6627
=> appease the retry linter

website/source/docs/commands/acl/bootstrap.html.md.erb
Updating broken link to reset procedure.
=> [docs] ACL Bootstrap CLI docs

agent/config/config.go, command/debug/debug.go
* json struct tag duplicate
* incorrect wait group usage ref. https://godoc.org/sync#WaitGroup.Add
=> fix: incorrect struct tag and WaitGroup usage

.circleci/config.yml
This fixes the nomad master integ test.
=> Nomad Integration Test Build

website/source/docs/guides/index.html.md, website/source/layouts/layout.erb
=> Top Navigation change

website/source/docs/acl/acl-system.html.md, website/source/docs/commands/acl/bootstrap.html.md.erb
=> [docs] ACL reset

website/source/docs/guides/index.html.md
=> [docs] Guide - UTM parameter 

website/source/docs/platform/k8s/connect.html.md
If ACLs are enabled, service account name must match the name of the
service in Consul.
Fixes https://github.com/hashicorp/consul-helm/issues/202
=> Document service account name requirements

website/source/docs/agent/options.html.md
=> Update -protocol doc

agent/structs/acl_test.go
These seem fine in enterprise but I finally noticed the CI failure in enterprise.
=> Fix the Synthetic Policy Tests

agent/consul/acl_endpoint.go, agent/consul/acl_endpoint_test.go
Apparently I missed the ACLRoleUpsertValidateEnterprise call in RoleSet. I have some ent tests I was working on where I discovered this.
The other fixes are to reduce flakiness of a couple of tests and prevent test panicing to get accurate results from CI more often.
=> Miscellaneous fixes

website/source/api/libraries-and-sdks.html.md
Adding crystal-consul to the libraries & sdk website docs
=> [docs] Adds crystal-consul to libraries & sdk docs

agent/config/config.go, command/debug/debug.go
=> Backport: #6649

website/source/index.html.erb
=> Website - JTBD buttons

website/source/docs/agent/config-entries/service-resolver.html.md
=> docs: add sentence linking to available service-resolver filters

website/source/index.html.erb
Its time to remove kubecon banner, but the data collect was positive.
=> Remove Website Banner

agent/agent.go, agent/agent_oss.go, agent/consul/fsm/fsm_test.go, agent/consul/prepared_query_endpoint_test.go, lib/serf.go
We are trying to reduce the differences between Consul Enterprise code base and OSS. This PR introduces some adjustments in order to be more similar.
=> Fewer file local differences between enterprise and oss

website/source/assets/javascripts/application.js, website/source/assets/javascripts/section-quicknav.js, website/source/assets/stylesheets/_inner.scss, website/source/docs/commands/index.html.md, website/source/docs/glossary.html.md
Copied from terraform.io:
Clicking results in:
=> Add "jump to section" dropdown

website/source/docs/platform/k8s/helm.html.md
Fixes https://github.com/hashicorp/consul-helm/issues/276
=> Fix documentation for namespaceSelector

agent/http_test.go
Fixes https://github.com/hashicorp/consul/issues/6858.
=> Increase TLSHandshakeTimeout to help slow tests

agent/config/builder.go, agent/config/runtime_test.go, tlsutil/config.go, website/source/docs/agent/options.html.md
* relax requirements for auto_encrypt on server
* better error message when auto_encrypt and verify_incoming on
* docs: explain verify_incoming on Consul clients.
=> tls: auto_encrypt and verify_incoming (#6811)

agent/structs/structs.go
https://circleci.com/gh/hashicorp/consul/101186?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
```
The following file(s) do not conform to go fmt:
agent/structs/structs.go
```
=> [ci] fix: go-fmt fails on master branch

CHANGELOG.md, version/version.go
Reset dev tree after `1.7.0-beta1` release
=> reset dev tree

website/source/docs/connect/ca/aws.html.md
The list formatting was off due to white space.
Also realised we didn't include version information here so added that.
@kaitlincarter-hc @judithpatudith do you think we should add something else to indicate Beta release? I don't want to forget it's there but not sure we have precedence for that? ISTR a sidebar label once?
=> Fix formatting and add version info

sdk/freeport/ephemeral_linux.go
=> change sysctl call to use absolute path

website/source/docs/guides/acl-replication.md
This guide was leftover work from the production ACLs guide. We can now link to this guide from the summary of production ACLs. 
TODO: Finish summary
=> [docs] New Replication Guide

website/source/docs/enterprise/backups/index.html.md
updating the ent docs to mention GCP
=> [docs] Ent Backup 

website/source/docs/agent/checks.html.md
* Changed the link to point to new guide
* Removed querystring from link
=> Update docs to point to new learn guide

website/source/docs/enterprise/network-segments/index.html.md
using work made at https://github.com/hashicorp/consul/pull/6558 by @thepomeranian
=> added disclaimer about network segments due to Serf limitations

ui-v2/config/environment.js
Updates the year manually. This will not be merged into the `master` branch, just the 1.6.x release.
=> ui: Updates the Consul copyright year to 2020

.gitignore
Tiny change, inspired by some of the lines I saw reverted in [raft#382](https://github.com/hashicorp/raft/pull/382/files#diff-a084b794bc0759e7a6b77810e01874f2L24)
=> .gitignore: add vscode and MacOS-specific files. add a little org

agent/connect/ca/provider_vault_test.go
Fixes a test failure introduced in https://github.com/hashicorp/consul/pull/6835
=> test: ensure we don't ask vault to sign a leaf that outlives its CA when acting as a secondary

agent/catalog_endpoint_test.go
- Explicitly wait to start the test until the initial AE sync of the node.
- Run the blocking query in the main goroutine to cut down on possible
poor goroutine scheduling issues being to blame for delays.
- If the blocking query is woken up with no index change, rerun the
query. This may happen if the CI server is loaded and time dilation is
happening.
Example failure: https://circleci.com/gh/hashicorp/consul/113075#tests/containers/6
=> make TestCatalogNodes_Blocking less flaky

ui-v2/app/templates/settings.hbs
Adds a conditional that checks env CONSUL_UI_DISABLE_REALTIME to show/hide the Blocking Queries toggle in the Settings page.
=> ui: Checks env CONSUL_UI_DISABLE_REALTIME to show/hide toggle

README.md
Adding Service Mesh reference for Consul
=> Adding Service Mesh reference

README.md
Adding links to Kubernetes deployment guide and minikube install for visibility
=> Adding links to Kubernetes install

website/source/docs/commands/index.html.md
=> fix Unix socket path in docs

ui-v2/tests/acceptance/dc/nspaces/index.feature, ui-v2/tests/acceptance/dc/nspaces/update.feature, ui-v2/tests/acceptance/deleting.feature, ui-v2/tests/acceptance/steps/dc/nspaces/delete-steps.js, ui-v2/tests/acceptance/steps/dc/nspaces/index-steps.js, ui-v2/tests/acceptance/steps/dc/nspaces/update-steps.js, ui-v2/tests/helpers/set-cookies.js, ui-v2/tests/helpers/type-to-url.js, ui-v2/tests/pages.js, ui-v2/tests/pages/dc/nspaces/edit.js, ui-v2/tests/pages/dc/nspaces/index.js, ui-v2/yarn.lock
This PR builds on https://github.com/hashicorp/consul/pull/6980 and https://github.com/hashicorp/consul/pull/7005 by adding acceptance tests specifically for testing namespace CRUD.
=> ui: Namespace CRUD acceptance tests

website/source/redirects.txt
=> Redirect /docs/guides/outage.html to Learn

ui-v2/config/environment.js
This PR corrects an erroneous switch statement in our environment file.
=> ui: Change environment switch statement to correct env vars

.hashibot.hcl
=> Hashibot, slow down!

.hashibot.hcl
* locked issues it shouldn't have locked: https://github.com/hashicorp/consul/issues/6346
* closed issue correctly, but still too early for my taste: https://github.com/hashicorp/consul/issues/3250
=> disable most of hashibot

agent/agent_endpoint_test.go, agent/cache-types/catalog_datacenters.go, agent/cache-types/health_services.go, agent/cache-types/node_services.go, agent/cache-types/prepared_query.go, agent/cache/entry.go, agent/checks/check.go, agent/config/runtime.go, agent/coordinate_endpoint_test.go, agent/http_oss.go, command/connect/proxy/register.go
Couple more on top of https://github.com/hashicorp/consul/pull/5736
=> fix spelling errors

agent/config_endpoint.go
This didn't make it into a previous PR but the goal here is to make it a little easier to follow.
=> Small refactoring to move meta parsing into the switch statement

website/source/docs/agent/options.html.md
Fixes [clarification issue](https://github.com/hashicorp/consul/issues/6672#issuecomment-571259675) requested in #6672.
=> [docs] Clarify retry-join

.github/ISSUE_TEMPLATE/question.md
=> Revert "Update question.md"

website/source/docs/agent/sentinel.html.markdown.erb
Updating the documentation for the available Sentinel standard imports.
=> Update available Sentinel imports

website/source/docs/commands/acl/token/update.html.md.erb
=> Adding upgrade-legacy doc

agent/acl_endpoint.go, agent/agent_endpoint.go, agent/catalog_endpoint.go, agent/consul/connect_ca_endpoint.go, agent/consul/coordinate_endpoint.go, agent/consul/internal_endpoint.go, agent/consul/prepared_query_endpoint.go, agent/consul/server_test.go, agent/consul/state/acl.go, agent/consul/state/catalog.go, agent/discovery_chain_endpoint_test.go, agent/health_endpoint.go, agent/structs/prepared_query.go, api/discovery_chain.go, api/prepared_query.go
This PR will include all the various fixes that come up when writing more namespace tests.
=> Catalog + Namespace OSS changes.

agent/connect/ca/provider_consul_config.go, agent/connect/ca/provider_consul_test.go, agent/connect/ca/provider_test.go, agent/connect/generate.go, agent/connect/testing_ca.go, agent/connect_ca_endpoint_test.go, agent/consul/leader_connect.go, agent/consul/leader_connect_test.go, agent/consul/server_test.go, agent/structs/connect_ca.go, agent/structs/connect_ca_test.go, command/connect/ca/set/connect_ca_set_test.go, command/connect/ca/set/test-fixtures/ca_config.json
Fixes #7201, by enforcing TTLs that workaround that problem. Comments in the code has more details about what happens.
=> add validations to ensure values are ok

website/source/docs/acl/acl-rules.html.md.erb
Adding a note to ACL rules page for intentions.
=> [docs] ACL Rules Update

website/source/docs/agent/options.html.md
=> Document format for TTL values in Consul config

website/source/docs/guides/consul-splitting.md
Add the splitting guide. 
- [PR to learn is here](https://github.com/hashicorp/learn/pull/727)
- [Preview build here](https://deploy-preview-727--hashicorp-learn.netlify.com/consul/developer-mesh/consul-splitting)
=> Add splitting guide

website/source/docs/enterprise/namespaces/index.html.md
Attaching learn guides associated with Namespaces release
=> 1.7.0 Namespaces Learn Guides

website/source/docs/internals/consensus.html.md
Current formula for quorum size does not match numbers in table below.
=> Adjust formula for quorum size

website/source/docs/upgrade-specific.html.md
Related to https://github.com/hashicorp/consul/issues/7284.
=> Put a note on the website

ui-v2/app/components/popover-menu.js, ui-v2/app/styles/base/components/menu-panel/layout.scss, ui-v2/app/styles/components/main-nav-horizontal/index.scss, ui-v2/app/styles/components/main-nav-horizontal/skin.scss, ui-v2/app/styles/components/product.scss, ui-v2/app/styles/components/product/index.scss, ui-v2/app/templates/components/hashicorp-consul.hbs, ui-v2/app/templates/components/popover-menu.hbs, ui-v2/config/environment.js
[Preview link](https://deploy-preview-7310--consul-ui-staging.netlify.com/ui/)
=> ui: Add new Help menu with links to docs, learn and GH

website/source/docs/guides/secure-namespaces.html.md
Adding new guide for namespaces and ACLs
=> [docs] Setup Secure Namespaces

website/source/docs/guides/discovery-namespaces.html.md
Adding new guide for namespaces and service discovery
=> [docs] Register and Discover Services within Namespaces Guide

agent/consul/session_endpoint.go, agent/consul/session_endpoint_test.go, agent/session_endpoint.go, agent/structs/structs.go
=> Fix session backwards incompatibility with 1.6.x and earlier. 

test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-remote/primary/verify.bats, test/integration/connect/envoy/helpers.bash
Putting this up as a PR so I can get CI to run the tests. I have tried even with simulated load on my local machine but am having a hard time causing the tests to fail.
=> Change where the envoy snapshots get put when a test fails

agent/consul/acl_server.go, agent/consul/acl_server_oss.go
This PR has the OSS side of a fix around ACLs and network segments.
=> Add stub methods for ACL/segment bug fix from enterprise

.circleci/scripts/cherry-picker.sh
This PR adds slack notifications when cherry-picking is done. This looks something like this:
Success:
Failure:
=> add slack notifications for cherry-pick

.circleci/scripts/cherry-picker.sh
I set the `pr_url` inside the if so it didn't render properly outside 😢
=> set pr_url outside if

website/source/docs/guides/consul-template.html.md
I was walking through the tutorial and this sentence didn't make any sense to me.  I've updated the wording to what I believe was originally intended.
=> Fix typo in consul-template tutorial

command/connect/envoy/envoy.go
We support 1.13.1 and should default to it!
=> default to 1.13.1

README.md
I added a link to the Learn repo at the top of the readme. I also moved the "Service Segmentation/Service Mesh information higher in the features list.
=> README - Add Link to Learn

.circleci/scripts/cherry-picker.sh
Also ran shellcheck against the script and fixed the other errors.
This was breaking the cherry-picking on master.
=> ci: Move shebang to first line of cherry pick script

agent/agent.go, command/connect/envoy/envoy.go, command/connect/envoy/envoy_test.go
A few very minor things I noticed while reading over the code. I wanted to open a PR separate from any substantial code changes, but grouped the 3 commits into one PR to reduce the noise of 3 tiny PRs.
=> envoy: small cleanup in cmd and server

website/source/docs/enterprise/backups/index.html.md, website/source/docs/enterprise/index.html.md, website/source/docs/enterprise/namespaces/index.html.md, website/source/docs/enterprise/network-segments/index.html.md, website/source/docs/enterprise/read-scale/index.html.md, website/source/docs/enterprise/redundancy/index.html.md, website/source/docs/enterprise/upgrades/index.html.md
Added additional content to the Enterprise sections for several features based on feedback. Also included additional learn guides were appropriate.
=> updating enterprise documentation with additional clarity

website/source/api/acl/policies.html.md
This endpoint was added in #6615.
=> Add docs for v1/acl/policy/name endpoint

api/agent_test.go
* Use r.Fatalf() insteadd of t.Fatal() to be sure to get the log if it fails
* register a service at the begining to be sure something happens within 10s
=> FIX flaky test: TestAPI_AgentMonitorJSON

website/source/docs/faq.html.md, website/source/docs/internals/security.html.md
Documentation update around the security model.
=> Updated Security Model and FAQ pages

agent/dns.go
I noticed while reading over `dns.go` there were a couple functions which had unused parameters. This PR removes them.
There are a couple linters that detect this problem, but enabling them would require a large diff. If we were to consider that it might make sense to create a few smaller PRs first that fix the errors, before turning it on.
=> dns: Remove a few unused function parameters

.circleci/config.yml, codecov.yml
Allows us to remove the merge coverage report step.
=> ci: Upload coverage from each job

api/agent_test.go
Similar fix as https://github.com/hashicorp/consul/pull/7541
=> Fixed unstable test TestAPI_AgentMonitor

website/source/api/agent/check.html.md
=> Revert "Fix documentation registering service checks"

website/source/docs/upgrade-specific.html.md
Fix a couple broken broken links
Fix some grammatical errors
Fix section header version number for 1.6.4
=> docs: fix some errors in upgrade-specific

agent/agent.go
I wasn't sure how deep I should document `ReloadConfig`, since that could change over time and be quite complicated. Let me know what I should add/remove!
=> Document exported functions in agent.go

website/source/docs/connect/proxies/built-in.md
Note that we don't recommending using built-in proxies in production
=> [docs] Built-in Proxies not meant for production

agent/cache/cache.go, agent/cache/watch.go
This change moves all the typeEntry lookups to the first step in the exported methods, and makes unexported internals accept the typeEntry struct.
This change is primarily intended to make it easier to extract the container of caches from the Cache type. It may incidentally reduce locking in fetch, and make the internals a little bit more obvious.
=> agent/cache: move typeEntry lookup to the edge

agent/agent.go, agent/cache/cache.go, agent/cache/entry.go, agent/cache/watch.go, agent/snapshot_endpoint.go
I spent some time today learning how `agent/cache` works. This PR is a few small changes that helped make things more clear to me. Hopefully they will help others.
Best viewed by commit. I tried to include context in each commit.
=> agent/cache: Small changes to hopefully improve readability

website/source/docs/platform/k8s/eks.html.md, website/source/docs/platform/k8s/index.html.md, website/source/layouts/docs.erb
Updating to include EKS and GKE guides.
=> Consul on Kubernetes Learn Guide Links

website/lib/anchor-link-analytics.js, website/pages/_app.js
This script will run as lowest priority in an idle callback, checking to see if we have a hit for a given url hash on each page.
=> anchor link analytics

agent/consul/state/catalog.go, agent/consul/state/catalog_test.go
On every service registration, we check to see if a service should be
assassociated to a wildcard gateway-service. This fixes an issue where
we did not correctly check to see if the service being registered was a
"typical" service or not.
We have a corresponding check when upserting a config entry with a wildcard specifier, but we missed this case.
=> Fix bug where non-typical services are associated with gateways

website/pages/docs/k8s/index.mdx, website/pages/docs/k8s/installation/aks.mdx, website/pages/docs/k8s/installation/eks.mdx, website/pages/docs/k8s/installation/gke.mdx
Update k8s guide titles and remove ableist language from the descriptions.
=> [Docs] Kuberentes Guides

agent/http.go
Quick follow up to review comment in #7656 because I forgot to commit this to the last pr 🤦
=> http: rename paresTokenResolveProxy to parseTokenWithDefault

agent/config/builder.go, agent/config/runtime_test.go
Fixes https://github.com/hashicorp/consul/issues/7407.
=> add validations for auto_encrypt.{tls,allow_tls}

website/pages/docs/connect/proxies/envoy.mdx
As reported by Alvin, thanks for catching!
=> Fix multiline note on docs website

website/source/downloads.html.erb
=> website: update link to HashiCorp security page

ui-v2/app/services/data-sink/protocols/http.js, ui-v2/app/services/data-sink/protocols/local-storage.js, ui-v2/app/services/data-sink/service.js
1. Fix conditional typo
2. Code style changes
3. Don't use URL for parsing, Safari only likes http like URLs, just split on `://` instead
=> ui: Amends to the data-sink service/component

ui-v2/app/templates/dc/services/instance/healthchecks.hbs
=> ui: Remove headers from the Healthchecks tab

website/pages/docs/commands/snapshot/agent.mdx
Also fix some website upgrade bugs.
=> docs: add docs for snapshot agent local_scratch_path option

ui-v2/app/styles/components/main-header-horizontal.scss
=> ui: Fix CSS typo

website/source/docs/platform/k8s/consul-enterprise.html.md, website/source/docs/platform/k8s/run.html.md
Duplicate of https://github.com/hashicorp/consul/pull/7724 into `stable-website`
=> Update for new helm repo

website/data/alert-banner.js, website/package-lock.json, website/package.json, website/pages/_app.js, website/pages/style.css
This can be controlled through `website/data/alert-banner.js`
=> Add alert banner to website

ui-v2/app/styles/components/app-view/layout.scss, ui-v2/app/templates/dc/services/instance.hbs, ui-v2/app/templates/dc/services/show.hbs
=> ui: Update Gateway headers to include Service Kind

ui-v2/app/styles/base/components/buttons/layout.scss
=> ui: Update copy button icon margin

agent/config/builder_oss.go, agent/config/config.go, agent/config/runtime_test.go
=> agent/config: Fix tests & include Audit struct as a pointer on Config

website/pages/downloads_tools/index.mdx
added files-to-consul-kv to tools
=> added files-to-consul-kv to tools

website/pages/docs/faq.mdx
Ref: https://discuss.hashicorp.com/t/consul-official-image-compliancy-to-oci/8009/7
Adding to the FAQ about our Docker/OCI compliance.
=> Update FAQ + formatting

website/pages/docs/faq.mdx, website/pages/docs/install/index.mdx
Update install to have a pointer to FAQ.
Update FAQ to outline our browser support for Consul UI.
=> Update FAQ with Compat Matrix information
