hashicorp/consul

website/data/docs-navigation.js
website/pages/api-docs/acl/auth-methods.mdx
website/pages/api-docs/acl/index.mdx
website/pages/docs/acl/acl-system.mdx
website/pages/docs/acl/auth-methods/index.mdx
website/pages/docs/acl/auth-methods/jwt.mdx
website/pages/docs/acl/auth-methods/kubernetes.mdx
website/pages/docs/acl/auth-methods/oidc.mdx
website/pages/docs/acl/index.mdx
website/pages/docs/agent/options.mdx
website/pages/docs/commands/acl/auth-method/create.mdx
website/pages/docs/commands/acl/auth-method/update.mdx
website/pages/docs/commands/login.mdx
website/pages/docs/enterprise/index.mdx
website/pages/docs/guides/managing-acl-policies.mdx
website/pages/docs/k8s/helm.mdx
website/pages/partials/jwt_claim_mapping_details.mdx
website/pages/partials/jwt_or_oidc.mdx

This is draft because there are very teeny tiny TODOs in a few places that need addressing.

docs: docs for jwt and oidc auth methods

---

website/data/docs-navigation.js
website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx
website/pages/docs/connect/wan_federation_via_mesh_gateways.mdx

Fixes #7416 
Diagrams will come in a future PR

Redo PR #7430 for new website (docs for WAN federation over mesh gateways)

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/agent/config-entries/terminating-gateway.mdx
website/pages/docs/connect/ingress_gateway.mdx
website/pages/docs/connect/terminating_gateway.mdx

Applying in a single PR so that they can be reverted before 1.8.0 GA.

Add beta tags to gateway docs

---

website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx

will be readded later when k8s specific docs page is available

temporarily remove link that 404s

---

agent/local/state_test.go

Example of failure: https://circleci.com/gh/hashicorp/consul/153932#tests/containers/2

Fix unstable test TestAgentAntiEntropy_Checks

---

website/components/learn-callout/style.css

[Preview](https://deploy-preview-7895--consul-docs-preview.netlify.app)
Quick fix for correctly displaying image on Safari

website: fix image size on learn callout

---

website/pages/docs/commands/tls/ca.mdx
website/pages/docs/commands/tls/cert.mdx

Fixes https://github.com/hashicorp/consul/issues/7872

docs: update the 'consul tls' command docs to match the current flags

---

ui-v2/app/components/consul-metadata-list/index.hbs
ui-v2/app/styles/components/table.scss

ui: Remove box-shadow and pointer cursor from metada list hover effect

---

website/pages/docs/agent/options.mdx

docs: remove todos

---

ui-v2/app/components/tooltip/index.hbs
ui-v2/app/components/tooltip/index.js
ui-v2/app/styles/base/components/tooltip/layout.scss
ui-v2/app/styles/base/components/tooltip/skin.scss
ui-v2/app/styles/core/typography.scss
ui-v2/app/templates/dc/services/instance/proxy.hbs
ui-v2/app/templates/dc/services/show/upstreams.hbs
ui-v2/package.json
ui-v2/tests/integration/components/tooltip-test.js
ui-v2/yarn.lock

- Adding EmberTooltips addon to codebase
- Creating a Tooltip component to wrap around EmberTooltip
- Implementing the new Tooltip component in Upstreams composite rows

ui: Implement EmberTooltips to Upstreams

---

agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go

Fixes https://github.com/hashicorp/consul/issues/7859

connect: ensure proxy-defaults protocol is used for upstreams

---

website/pages/docs/k8s/installation/multi-cluster/kubernetes.mdx
website/pages/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

Pending merge of https://github.com/docker-library/official-images/pull/8052

Update for consul:1.8.0-beta2

---

website/pages/downloads_tools/index.mdx

add gobetween to the Consul tools
@eveld

add gobetween to the Consul tools

---

website/layouts/use-cases/index.jsx
website/pages/docs/connect/terminating-gateway.mdx
website/pages/use-cases/multi-platform-service-mesh.jsx
website/pages/use-cases/network-middleware-automation.jsx
website/pages/use-cases/service-discovery-and-health-checking.jsx

- Added guideLink prop to UseCaseLayout component
- Updated all component references to pass contextually appropriate prop value
- Added a link to the Terminating Gateway Guide from the doc page

Added UseCaseLayout guideLink prop

---

ui-v2/app/services/repository/service.js
ui-v2/app/templates/dc/services/show/upstreams.hbs

ui: Customize link for an Upstream in a different namespace as the ingress gateway

---

website/pages/docs/agent/index.mdx

Fixes #6935 to clarify agent behavior.

Clarify Agent Leave Behavior

---

website/pages/docs/internals/acl.mdx

Add newline to fix rendering bug

---

ui-v2/app/components/consul-service-list/index.hbs
ui-v2/app/templates/dc/services/index.hbs
ui-v2/app/templates/dc/services/show.hbs

ui: Reorder the tabs for Ingress/Terminating Gateway Service Detail page

---

ui-v2/app/templates/dc/services/instance/proxy.hbs

ui: Reorder items in the Proxy Info tab

---

CHANGELOG.md

Added some missing entries to changelog for release candidate today

1.8.0 rc changelog

---

ui-v2/app/components/consul-service-instance-list/index.hbs
ui-v2/app/helpers/service/instance-checks.js
ui-v2/app/styles/components/composite-row/skin.scss

ui: Add detailed Health Checks to Service Detail page

---

agent/service_manager.go

Some additional context in commit messages.

service_manager: small changes

---

README.md

Re-ordered features and revised Consul description.

Small changes to Readme around Consul description

---

website/pages/home/index.jsx

Fixed a typo

---

website/pages/api-docs/session.mdx

Improve Clarity on TTL docs, fixes #8059

---

website/data/docs-navigation.js
website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/agent/config-entries/terminating-gateway.mdx
website/pages/docs/connect/ingress-gateway.mdx
website/pages/docs/connect/terminating-gateway.mdx
website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx

This PR also:
- Updates references to the latest learn guides
- Adds a note about certificate rotation for terminating gateways

Finalize gateway documentation for 1.8.0 GA

---

go.mod
go.sum
vendor/github.com/stretchr/testify/assert/assertion_format.go
vendor/github.com/stretchr/testify/assert/assertion_forward.go
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/github.com/stretchr/testify/assert/forward_assertions.go
vendor/github.com/stretchr/testify/mock/mock.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/requirements.go
vendor/modules.txt

Update testify in the release/1.8.x branch

---

ui-v2/app/components/consul-upstream-instance-list/index.hbs
ui-v2/app/components/consul-upstream-list/index.hbs
ui-v2/app/styles/components/composite-row/skin.scss
ui-v2/yarn.lock

ui: Support ingress gateways upstreams with multiple addresses

---

website/pages/docs/acl/auth-methods/jwt.mdx
website/pages/docs/acl/auth-methods/oidc.mdx
website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/agent/config-entries/terminating-gateway.mdx
website/pages/docs/connect/ingress-gateway.mdx
website/pages/docs/connect/registration/service-registration.mdx
website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx

This PR makes some miscellaneous docs updates:
- Removes stray beta tags
- Fixes up some stray/missing docs
- Adds tabs with JSON/HCL examples for gateway config entries.

Misc docs updates

---

website/pages/home/index.jsx

Updated landing page links to learn to specific guides.

Landing page update.

---

website/pages/docs/agent/options.mdx

- Added anchors to https://github.com/hashicorp/consul/pull/8223
- Fix Typos
- Fixes #8220

Fix typos on commandline flags

---

website/pages/docs/commands/index.mdx

A customer was asking about this and I couldn't find anything but it is in fact listed in the source code so just seems to be missing from the website.

Added undocumented CONSUL_NAMESPACE to website.

---

agent/token/store.go
agent/token/store_test.go

Currently this isn't used but I have another PR to put up shortly that will use it.

Add ability for notifications when one of the agent tokens is updated

---

website/data/docs-navigation.js
website/pages/docs/enterprise/audit-logging.mdx
website/pages/docs/enterprise/index.mdx

Updated the top portion of the Overview for Consul Enterprise.
Added a page for Audit Logging, linking it to the sidebar and on the Consul Enterprise page.

Consul Enterprise docs update

---

command/kv/del/kv_delete.go
command/kv/del/kv_delete_test.go
command/kv/put/kv_put.go
command/kv/put/kv_put_test.go

Resolves #8330 
On my machine:

command: fix cas put when index=0 and better errors in put and delete

---

agent/agent.go
agent/watch_handler.go
agent/watch_handler_test.go

Fixes #8284
First commit extracts a function to make it possible to test the fix. Second commit contains the fix.
Draft for now until I finish off the additional test cases.

watch: fix script watches with single arg

---

ui-v2/app/components/consul-service-instance-list/index.hbs

ui: fix swapped node & serivce checks by fixing filter-by & reject-by

---

go.mod
go.sum
vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
vendor/github.com/mitchellh/mapstructure/mapstructure.go
vendor/modules.txt

This was done in preparation for another PR where I was running into https://github.com/mitchellh/mapstructure/issues/202 and implemented a fix for the library.

Update mapstructure to v1.3.3

---

ui-v2/app/components/consul-token-list/index.hbs
ui-v2/app/components/consul-token-list/pageobject.js
ui-v2/app/components/list-collection/index.hbs
ui-v2/app/controllers/dc/acls/tokens/index.js
ui-v2/app/initializers/sort.js
ui-v2/app/routes/dc/acls/tokens/index.js
ui-v2/app/sort/comparators/token.js
ui-v2/app/styles/components/notice.scss
ui-v2/app/templates/dc/acls/tokens/index.hbs
ui-v2/tests/acceptance/dc/acls/tokens/navigation.feature
ui-v2/tests/acceptance/dc/acls/tokens/sorting.feature
ui-v2/tests/acceptance/page-navigation.feature
ui-v2/tests/acceptance/steps/dc/acls/tokens/navigation-steps.js
ui-v2/tests/acceptance/steps/dc/acls/tokens/sorting-steps.js
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/acls/tokens/index.js
ui-v2/yarn.lock

Sort Tokens list by CreationTime.

ui: Add sorting to ACLs tokens with tests

---

ui-v2/app/templates/dc/intentions/index.hbs

I had some issues rebasing the original branch. New clean branch with change made.

ui: Fix up on the onchange value to target for sorting intentions

---

ui-v2/app/components/consul-role-list/pageobject.js
ui-v2/app/controllers/dc/acls/roles/index.js
ui-v2/app/initializers/sort.js
ui-v2/app/routes/dc/acls/roles/index.js
ui-v2/app/sort/comparators/role.js
ui-v2/app/templates/dc/acls/roles/index.hbs
ui-v2/tests/acceptance/dc/acls/roles/navigation.feature
ui-v2/tests/acceptance/dc/acls/roles/sorting.feature
ui-v2/tests/acceptance/steps/dc/acls/roles/navigation-steps.js
ui-v2/tests/acceptance/steps/dc/acls/roles/sorting-steps.js
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/acls/roles/index.js

Sort by:
- Name
- Creation Time

ui: Add sorting to Roles

---

ui-v2/app/components/consul-policy-list/pageobject.js
ui-v2/app/controllers/dc/acls/policies/index.js
ui-v2/app/initializers/sort.js
ui-v2/app/routes/dc/acls/policies/index.js
ui-v2/app/sort/comparators/policy.js
ui-v2/app/templates/dc/acls/policies/index.hbs
ui-v2/tests/acceptance/dc/acls/policies/navigation.feature
ui-v2/tests/acceptance/dc/acls/policies/sorting.feature
ui-v2/tests/acceptance/page-navigation.feature
ui-v2/tests/acceptance/steps/dc/acls/policies/navigation-steps.js
ui-v2/tests/acceptance/steps/dc/acls/policies/sorting-steps.js
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/acls/policies/index.js

ui: Add sorting to Policies

---

agent/cache/cache_test.go

This adds a test for agent-cache throttling in agent/cache.
cc @pierresouchay

agent/cache test for cache throttling.

---

CHANGELOG.md

Fix trailing backslash at the end of line in CHANGELOG.md

Removed trailing backslash in CHANGELOG

---

website/_redirects

Redirect service mesh use case page to point to new URL.

Redirect /mesh to /use-cases/multi-platform-service-mesh

---

.golangci.yml
agent/cache-types/catalog_datacenters_test.go
agent/cache-types/service_checks.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_test.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/server_lookup_test.go
agent/consul/state/catalog_test.go
agent/consul/state/coordinate_test.go
agent/consul/state/kvs_test.go
agent/consul/state/session_test.go
agent/metadata/server_test.go
agent/proxycfg/state.go
agent/session_endpoint_test.go
agent/util_test.go
api/agent_test.go
api/config_entry_gateways_test.go
api/config_entry_test.go
api/lock.go
api/semaphore_test.go
api/session_test.go
internal/go-sso/oidcauth/jwt.go
lib/decode/decode_test.go
tlsutil/config_test.go

[1.8.x] Backport addition of  ineffassign linter and staticcheck 

---

ui-v2/app/components/consul-nspace-list/index.hbs
ui-v2/app/components/consul-nspace-list/pageobject.js
ui-v2/app/controllers/dc/nspaces/index.js
ui-v2/app/initializers/sort.js
ui-v2/app/routes/dc/nspaces/index.js
ui-v2/app/sort/comparators/nspace.js
ui-v2/app/templates/dc/nspaces/index.hbs
ui-v2/tests/acceptance/dc/nspaces/index.feature
ui-v2/tests/acceptance/dc/nspaces/sorting.feature
ui-v2/tests/acceptance/steps/dc/nspaces/sorting-steps.js
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/nspaces/index.js

ui: Add sorting to namespaces

---

ui-v2/app/styles/components/composite-row/layout.scss

ui: Increase spacing between detail items in composite row

---

.changelog/8537.txt

I forgot to add a changelog entry in #8537
Opening a PR for this to check that I am doing it right, and to use the automatic backport

Add missing changelog for PR 8537

---

CHANGELOG.md
agent/structs/structs.go
agent/structs/structs_test.go

[1.7.x] backport connect=null bug fix

---

website/pages/api-docs/connect/intentions.mdx
website/pages/docs/commands/intention/check.mdx
website/pages/docs/commands/intention/create.mdx
website/pages/docs/commands/intention/delete.mdx
website/pages/docs/commands/intention/get.mdx
website/pages/docs/commands/intention/index.mdx
website/pages/docs/commands/intention/match.mdx

This functionality was already released but missing documentation.

Add docs for using namespaces with intentions

---

.changelog/8596.txt
agent/config/runtime_test.go
agent/structs/config_entry.go
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_test.go
api/config_entry.go
api/config_entry_discoverychain.go
api/config_entry_gateways.go
api/config_entry_test.go
command/config/write/config_write_test.go
website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/agent/config-entries/proxy-defaults.mdx
website/pages/docs/agent/config-entries/service-defaults.mdx
website/pages/docs/agent/config-entries/service-resolver.mdx
website/pages/docs/agent/config-entries/service-router.mdx
website/pages/docs/agent/config-entries/service-splitter.mdx
website/pages/docs/agent/config-entries/terminating-gateway.mdx

connect: all config entries pick up a meta field

---

website/data/docs-navigation.js
website/pages/docs/k8s/helm.mdx
website/pages/docs/k8s/installation/helm.mdx

Also move helm reference out into top-level and rename

Update useSystemRoots docs for k8s

---

README.md
website/pages/home/index.jsx
website/pages/use-cases/multi-platform-service-mesh.jsx
website/pages/use-cases/service-discovery-and-health-checking.jsx

I updated several of the links to Learn to be more specific for the use cases. For the landing page, I updated the tutorials to newer content and moved the CTA banner higher on the page so that practitioners see more hands on content sooner.

Website Links to Learn

---

README.md
website/data/docs-navigation.js

Added docs link to Learn tutorial for Kind. Also, updated some links that I saw were pointing to legacy urls.

Added docs link to Learn tutorial for Kind.

---

website/_redirects
website/pages/community/index.jsx
website/pages/docs/install/index.mdx
website/pages/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx
website/pages/docs/k8s/upgrade/compatibility.mdx
website/pages/docs/upgrading/upgrade-specific.mdx
website/pages/use-cases/multi-platform-service-mesh.jsx

Let's get back to zero broken links - fresh slate!

Broken link fixes

---

website/pages/api-docs/operator/keyring.mdx

The response includes a new field: PrimaryKeys that lists the installed
primary keys.

Update API docs for GET /operator/keyring

---

ui-v2/app/components/consul-node-list/index.hbs

ui: Add services count to node listings

---

website/data/alert-banner.js

Updates the alert banner to promote the release of HCS Azure Production SKU

website: update alert bar for HCS prod sku

---

agent/consul/catalog_endpoint_test.go
agent/consul/health_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog_test.go
agent/dns_test.go
agent/user_event_test.go

backport[1.7.x]: test: update tags for database service registrations and queries

---

website/pages/docs/dynamic-app-config/kv.mdx

docs: clarify KV url-safe key names

---

website/components/case-study-carousel/style.css
website/components/mini-cta/index.jsx
website/components/mini-cta/style.css
website/pages/home/index.jsx
website/pages/style.css

Add in mini cta for in prod usage
[Preview](https://deploy-preview-8718--consul-docs-preview.netlify.app/)

Add Using in Production Question

---

agent/acl.go

This is improvement for #7640.

[ACL] added permission denied error message

---

website/pages/docs/architecture/index.mdx

In one of the line, `will` is misssing between `there` and `be` - I added it.

Fixed a gramatical mistake

---

.circleci/scripts/cherry-picker.sh

fix command in cherry-picker script

---

website/data/docs-navigation.js
website/pages/docs/upgrading/index.mdx
website/pages/docs/upgrading/instructions/general-process.mdx
website/pages/docs/upgrading/instructions/index.mdx
website/pages/docs/upgrading/instructions/upgrade-to-1-2-x.mdx
website/pages/docs/upgrading/instructions/upgrade-to-1-6-x.mdx
website/pages/docs/upgrading/instructions/upgrade-to-1-8-x.mdx

This adds some more detailed documentation around the general upgrade process along with providing some specific instructions around upgrading over large version jumps (including handling the ACL changes in 1.4). Below are some screenshots for reference:
* [Overview](https://user-images.githubusercontent.com/244/93118528-0ea58300-f686-11ea-8dd9-b6c438b3d48f.png)
* [General Upgrade Process](https://user-images.githubusercontent.com/244/93117961-2d574a00-f685-11ea-93fb-ba8234f32936.png)
* [Upgrading to 1.6.9](https://user-images.githubusercontent.com/244/93118564-1c5b0880-f686-11ea-8e4e-07d3d330242a.png)

docs: Add documentation for large version jump upgrades

---

website/_redirects

This page was down due to a circular redirect

Fix jepsen circular redirect

---

.circleci/config.yml

I also added a short SHA to the git commit message so we can trace back which commit triggered the auto commit.

add git config for static assets

---

.circleci/config.yml
codecov.yml

Also disable publish static assets for now, until we can fix it.

Disable codecov annotations in github PRs

---

website/data/docs-navigation.js
website/pages/docs/nia/architecture.mdx
website/pages/docs/nia/cli.mdx
website/pages/docs/nia/index.mdx
website/pages/docs/nia/installation/configuration.mdx
website/pages/docs/nia/installation/install.mdx
website/pages/docs/nia/installation/requirements.mdx
website/pages/docs/nia/installation/run.mdx
website/pages/docs/nia/network-drivers.mdx
website/pages/docs/nia/tasks.mdx

Outline for NIA/Consul-Terraform-Sync Tech Preview docs with some base content.

Docs: Add outline and basic content for Tech Preview docs

---

ui-v2/app/adapters/node.js
ui-v2/app/routes/dc/nodes/index.js
ui-v2/app/serializers/application.js
ui-v2/app/serializers/node.js
ui-v2/app/services/client/http.js
ui-v2/app/services/data-source/protocols/http.js
ui-v2/app/services/data-source/protocols/http/blocking.js
ui-v2/app/services/repository/node.js
ui-v2/app/services/store.js
ui-v2/app/templates/dc/nodes/index.hbs
ui-v2/app/utils/dom/event-source/blocking.js
ui-v2/tests/integration/adapters/node-test.js
ui-v2/tests/integration/serializers/node-test.js

Following https://github.com/hashicorp/consul/pull/8805, this PR adds a 30 second poll to the leader API request to make the data needed to mark the leader on the node listing page 'live-ish'.

ui: Leader API polling

---

website/pages/docs/nia/cli.mdx

Latest netlify of cli docs: https://deploy-preview-8840--consul-docs-preview.netlify.app/docs/nia/cli

CLI Docs for Consul Terraform Sync

---

website/pages/docs/nia/tasks.mdx

https://deploy-preview-8860--consul-docs-preview.netlify.app/docs/nia/tasks

Task Docs for Consul Terraform Sync

---

ui-v2/app/components/consul-intention-form/fieldsets/index.hbs
ui-v2/app/components/consul-intention-form/fieldsets/skin.scss
ui-v2/app/components/consul-intention-permission-form/index.hbs
ui-v2/app/components/consul-intention-permission-form/skin.scss
ui-v2/app/components/consul-intention-permission-header-form/index.hbs
ui-v2/app/components/consul-intention-permission-list/index.hbs
ui-v2/app/components/consul-intention-permission-list/index.scss
ui-v2/app/components/form-group/element/checkbox/index.hbs
ui-v2/app/components/form-group/element/error/index.hbs
ui-v2/app/components/form-group/element/index.hbs
ui-v2/app/components/form-group/element/index.js
ui-v2/app/components/form-group/element/label/index.hbs
ui-v2/app/components/form-group/element/radio/index.hbs
ui-v2/app/components/form-group/element/text/index.hbs
ui-v2/app/components/form-group/index.hbs
ui-v2/app/components/form-group/index.js
ui-v2/app/styles/base/color/frame-placeholders.scss
ui-v2/app/styles/components/list-row/layout.scss
ui-v2/app/styles/routes.scss
ui-v2/app/styles/routes/dc/intentions/index.scss
ui-v2/tests/acceptance/dc/intentions/filtered-select.feature
ui-v2/tests/acceptance/dc/intentions/form-select.feature

1. Disable ability to edit the source when editing an intention
2. Various small CSS amends
3. Make the validations errors only appear once you've interacted with an input

ui: L7 intentions improvements

---

ui-v2/app/components/topology-metrics/index.hbs

ui: Add namespaces to downstream cards

---

go.mod
go.sum
vendor/github.com/hashicorp/raft/CHANGELOG.md
vendor/github.com/hashicorp/raft/Makefile
vendor/github.com/hashicorp/raft/README.md
vendor/github.com/hashicorp/raft/api.go
vendor/github.com/hashicorp/raft/config.go
vendor/github.com/hashicorp/raft/file_snapshot.go
vendor/github.com/hashicorp/raft/future.go
vendor/github.com/hashicorp/raft/inmem_snapshot.go
vendor/github.com/hashicorp/raft/inmem_transport.go
vendor/github.com/hashicorp/raft/net_transport.go
vendor/github.com/hashicorp/raft/raft.go
vendor/github.com/hashicorp/raft/replication.go
vendor/github.com/hashicorp/raft/snapshot.go
vendor/github.com/hashicorp/raft/tcp_transport.go
vendor/github.com/hashicorp/raft/testing.go
vendor/github.com/hashicorp/raft/util.go
vendor/modules.txt

To pull in `raft` improvements from the past several months, notably:
- Prevent non-voters from becoming eligible for leader elections (but ultimately rejected) https://github.com/hashicorp/raft/pull/398, fixes https://github.com/hashicorp/consul/issues/7031
- Adding peer id as metric label to reduce cardinality in metric names https://github.com/hashicorp/raft/pull/409, fixes #4450
Full changelog at https://github.com/hashicorp/raft/blob/master/CHANGELOG.md#120-october-5th-2020

chore: update raft to v1.2.0

---

website/pages/docs/nia/installation/configuration.mdx
website/pages/docs/nia/installation/install.mdx
website/pages/docs/nia/tasks.mdx

- Remove Install Consul in install docs. Will move to requirements docs
- Add Connect your Consul Cluster in install docs
- Add Connect your Network Device & Multi-Provider in install docs
- Add additional multi provider details in config docs
- Fix a case typo for Consul catalog in tasks doc

Update Installation Docs for Consul Terraform Sync

---

website/pages/commands/snapshot/agent.mdx

This change never made it out of the ent copy of the docs.

website: re-add forgotten updates

---

agent/ui_endpoint.go
agent/ui_endpoint_test.go

Based on @mikemorris find and original PR https://github.com/hashicorp/consul/pull/8883.
This includes a test and is from master so we can keep the feature branch UI-only code.
Thanks @mikemorris all credit to you!

Actually proxy the query string too

---

.changelog/8822.txt

Thanks @s-christoff for catching that I forgot this in #8822!

changelog: update raft to v1.2.0

---

website/pages/docs/integrate/nia-integration.mdx

- Added a note to explain that Consul-Terraform-Sync is one solution within NIA.
- Changed the link to the PANW TF module
- Added Kim's suggestions to clarify concepts and fix typos and wording

Docs: NIA integration program small updates

---

website/pages/docs/integrate/nia-integration.mdx

* Renames Terraform module registry to its new name Terraform Registry

Minor updates to NIA partner docs

---

.circleci/config.yml

This PR will trigger an oss->ent merge on every commit into `master` or `release/#.#.x` (via cherry-pick) branches.

add per commit oss->ent merge on master and release branches

---

.circleci/config.yml

[skip ci] ci: fix trigger-oss-merge yaml spacing

---

.changelog/8784.txt
GNUmakefile
agent/connect/ca/provider.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go
agent/consul/leader_connect.go
agent/consul/leader_connect_test.go
agent/consul/server.go

backport/1.8.x: renew intermediates in primary

---

website/pages/docs/integrate/nia-integration.mdx

* Update PANOS link
* Update sentences

Docs: Update a link and reword some sentences

---

website/pages/docs/nia/installation/requirements.mdx

Update "Using Terraform Modules" with latest module links from partners

Update Requirements doc: Terraform module links

---

website/pages/docs/integrate/nia-integration.mdx

Docs: Remove email address

---

website/pages/docs/agent/options.mdx

Add ui metrics config docs

---

website/package-lock.json
website/package.json

Updates `<HashiStackMenu />` to include waypoint 🎉 
[🔍  Preview link](https://deploy-preview-8971--consul-docs-preview.netlify.app/)

[Website] Update HSM version w/ Waypoint

---

website/pages/docs/nia/installation/requirements.mdx

* Add A10 TF Registry and GH link
* Add Checkpoint TF Registry and GH link

Docs: Add A10 and Checkpoint TF modules

---

website/pages/docs/integrate/nia-integration.mdx

* Update links to make them accurate

Docs: Update links in NIA Integration Program

---

agent/dns.go

I noticed this while reading over the code which sets EnterpriseMeta.
This commit is one small step toward modernizing and making the DNSServer readable.

dns: remove goto INVALID and a naked return

---

website/pages/docs/nia/tasks.mdx

[preview](https://deploy-preview-8985--consul-docs-preview.netlify.app/docs/nia/tasks#task-automation)

NIA: document daemon exiting on task errors

---

website/pages/docs/nia/installation/requirements.mdx

[preview](https://deploy-preview-9023--consul-docs-preview.netlify.app/docs/nia/installation/requirements#network-integration-using-a-terraform-module)

NIA: add Terraform version compatibility

---

.changelog/8774.txt
.changelog/9024.txt

Updates changelog entries fixed up on 1.8.5 branch too.

changelog: update formatting from 1.8.5 release

---

website/data/alert-banner.js
website/package-lock.json
website/package.json
website/pages/style.css

- Bump `<AlertBanner />`
- Expose new prop in data file

Expose `expirationDate` prop in <AlertBanner/>

---

.circleci/config.yml
ui/packages/consul-ui/package.json
ui/yarn.lock

See https://github.com/hashicorp/consul-api-double/pull/49

ui: Upgrade consul-api-double to fix datacenter mocks

---

.github/workflows/issue-labeler.yml

This turns off the issue labeler for now, until regex can get tuned better.

Turn off issue labeler for now

---

website/pages/docs/nia/index.mdx

[Preview](https://deploy-preview-9060--consul-docs-preview.netlify.app/docs/nia)
Removed "Tech Preview" from the page title which does not render properly in the browser tab

docs: Add links in CTS docs for the community to get involved

---

website/pages/docs/nia/cli.mdx

[preview](https://deploy-preview-9065--consul-docs-preview.netlify.app/docs/nia/cli#inspect-mode)

nia docs: add inspect mode

---

ui/packages/consul-ui/app/components/topology-metrics/index.js

ui: make metrics work again

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/routes/dc/services/show/index.js
ui/packages/consul-ui/app/templates/dc/services/show.hbs

This PR updates conditionals to not return metrics if service is an ingress-gateway.

ui: Update to not return metrics for ingress gateways

---

agent/cache-types/streaming_health_services.go
agent/cache-types/streaming_health_services_test.go
agent/cache-types/streaming_test.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/subscription.go
agent/consul/stream/subscription_test.go
agent/consul/subscribe_backend.go
agent/rpc/subscribe/logger.go
agent/rpc/subscribe/subscribe.go
agent/rpc/subscribe/subscribe_test.go
agent/structs/structs.go
agent/structs/structs_test.go
proto/pbcommon/common_oss.go
proto/pbservice/convert_oss.go
proto/pbservice/convert_oss_test.go
proto/pbservice/convert_test.go

streaming: backport namespace changes

---

test/load/packer/loadtest-ami/loadtest.json

This commit updates the Packer properties `ami_name` and `ami_description` for the loadtest image to reflect the image intent.

Update loadtest AMI name, description

---

ui/packages/consul-ui/.eslintrc.js
ui/packages/consul-ui/.template-lintrc.js
ui/packages/consul-ui/app/components/consul/intention/list/index.js
ui/packages/consul-ui/app/components/consul/intention/list/pageobject.js
ui/packages/consul-ui/app/search/predicates/intention.js
ui/packages/consul-ui/app/services/repository/intention.js
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/package.json
ui/packages/consul-ui/testem.js
ui/packages/consul-ui/tests/pages/dc/intentions/index.js
ui/packages/consul-ui/tests/steps/assertions/model.js
ui/packages/consul-ui/tests/steps/doubles/model.js
ui/packages/consul-ui/tests/steps/interactions/click.js
ui/packages/consul-ui/tests/unit/helpers/selectable-key-values-test.js
ui/packages/consul-ui/vendor/metrics-providers/consul.js
ui/packages/consul-ui/vendor/metrics-providers/prometheus.js

There are a few files that aren't automatically linted via a githook - this PR lints them and adds the `vendor` directory to automated githook linting.
cc @freddygv

ui: Add vendor directory as a target for JS linting and lint

---

website/pages/docs/k8s/upgrade/compatibility.mdx

Co-authored-by: Ashwin Venkatesh <ashwin@hashicorp.com>

Update Helm compatibility matrix

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/app/routes/dc/services/show.js
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

Namespace is now being passed down and fix for mixup with the datacenter used.

ui: Pass down nspace and dc from Service model down to prometheus request

---

.circleci/config.yml
test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/Dockerfile-consul-envoy
test/integration/connect/envoy/Dockerfile-tcpdump
test/integration/connect/envoy/docker-compose.yml
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

chore(backport): use HashiCorp Docker mirror (#9167)

---

api/agent.go

It will be coming back soon. Also this code has never had an official release so there are no breaking changes here.

Remove this constant as it is soon to be changing and we want to prevent backwards compat issues

---

agent/consul/config_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/leader.go
agent/consul/leader_test.go

server: intentions CRUD requires connect to be enabled

---

website/data/docs-navigation.js
website/pages/docs/k8s/crds/index.mdx
website/pages/docs/k8s/crds/upgrade-to-crds.mdx
website/pages/docs/k8s/upgrade/index.mdx

Add docs for how to upgrade to use CRDs. Does not address mesh gateways as we haven't figured out our plan yet for that.

Docs for upgrading to CRDs

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss

- Updated conditional to show nspaces if nspaces are enabled and the nspace of upstream/downstream is **_not_** the same as the origin Service
- Update styling for the empty state in Stats component
CC @freddygv

ui: Card component nspace refactor

---

CHANGELOG.md
website/data/version.js

Adds changelog entries for: 1.6.10, 1.7.10, 1.8.6
Updates latest version to 1.8.6

Add latest changelog entries and update website version

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss

* Refactoring conditional for showing nspaces
* Styling empty state for Stats component

ui: Card component nspace refactor (#9228)

---

website/data/alert-banner.js

Consul 1.9 GA Banner and Blog post link

Consul 1.9 GA Banner

---

.changelog/9296.txt
ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/roles/edit.hbs

ui: Add copyable IDs to the Role and Policy views

---

.changelog/9009.txt

changelog: add entries for secondary datacenter CA fixes

---

.changelog/9009.txt
.changelog/9318.txt

Refs #9318, fixes link added in #9322

changelog: add entry for fixing active CA root unset

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
ui/packages/consul-ui/app/routes/dc/services/show/topology.js
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

- ♻️ Refactor Series & Stats
- ♻️ Metrics errors messaging for ingress-gateway services
- 🐛 Fix upstream service for a ingress-gateway showing no metrics
- 💄 Update the positioning of upLines icons

ui: Refactor topology components

---

website/data/alert-banner.js

Updates the alert banner for an upcoming webinar.

[Website] Update alert banner

---

website/pages/api-docs/features/filtering.mdx

From user feedback, I tried to update the filter api docs to be a more clear on how to create expressions.

Filter API Docs

---

website/pages/docs/nia/installation/configuration.mdx

[Preview link](https://deploy-preview-9389--consul-docs-preview.netlify.app/docs/nia/installation/configuration#provider-environment-variables)
New call out box

docs/nia: Add task_env block for Terraform providers

---

ui/packages/consul-ui/app/utils/get-environment.js

This changes in this file during https://github.com/hashicorp/consul/pull/9345 missed the initial 'more lint coverage' PR here https://github.com/hashicorp/consul/pull/9385 due to it being in review.
This fixes up the linting for the changes made to this file during https://github.com/hashicorp/consul/pull/9345

ui: Lint get-environment.js

---

website/pages/docs/nia/installation/run.mdx

- Fix list numbering which was restarting after the shell snippet
- Update config link
- Add step to check on cts running
[Run preview link](https://deploy-preview-9393--consul-docs-preview.netlify.app/docs/nia/installation/run)
List numbering issue prior to fix (for reference):

docs/nia: update run page

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/skin.scss
ui/packages/consul-ui/app/helpers/service/health-percentage.js

ui: Return empty state for no health check in Topology Cards

---

website/content/docs/k8s/helm.mdx

Use docs generated by new tool

Use generated helm docs

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/styles/base/components/menu-panel/layout.scss
ui/packages/consul-ui/app/styles/base/components/menu-panel/skin.scss
ui/packages/consul-ui/app/styles/components/main-nav-horizontal/layout.scss
ui/packages/consul-ui/app/styles/components/main-nav-horizontal/skin.scss

ui: Add Local flag to local dc in dropdown

---

website/content/docs/k8s/upgrade/compatibility.mdx

Update k8s compat matrix for 0.28 release

Update k8s compat matrix with 0.28

---

.changelog/9487.txt

I forgot to add this into the PR previously.

Add changelog for #9487

---

.github/pr-labeler.yml

Artifact from https://github.com/hashicorp/consul/pull/9352

Update pr-labeler to new NIA docs path

---

.changelog/9512.txt
agent/grpc/client.go
agent/grpc/client_test.go
agent/setup.go
agent/streaming_test.go

Tnis is an alternative to https://github.com/hashicorp/consul/pull/9494
We just patch the GRPC side, not everything as suggested by @dnephin

[Streaming][bugfix] handle TLS signalisation when TLS is disabled on client side (alternative to #9494)

---

test/integration/connect/envoy/docker-compose.yml

[1.8.x] Pin alpine/socat image to a version

---

.changelog/9485.txt

Adds changelog entry for #9485

chore: Adds changelog entry for ui accessibility improvements

---

website/data/alert-banner.js

Updates alert banner to promote upcoming webinar. Sets the expiration date properly to avoid stale content.

website: update alert banner to promote webinar

---

website/content/docs/nia/configuration.mdx

docs/nia: Update CTS default transport options

---

website/package-lock.json
website/package.json

A small version bump to the HashiStackMenu (formally known as the MegaNav) for 1/14 updates.

[Website] StackMenu updates for 1/14

---

go.mod
go.sum
vendor/github.com/mitchellh/mapstructure/.travis.yml
vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
vendor/github.com/mitchellh/mapstructure/decode_hooks.go
vendor/github.com/mitchellh/mapstructure/mapstructure.go
vendor/modules.txt

I did this upgrade to see if it would fix some strange behaviour I was seeing. It did not, but it seems like it would be good to update this anyway.

Update mapstructure dependency

---

.changelog/9524.txt

chore: Changelog entry for #9524

---

.changelog/9593.txt

ui: Changelog for #9593

---

website/components/cloud-offerings-list/index.jsx
website/components/learn-callout/style.css

This PR fixes some minor link color issues on the home page.

Fix link color on home page

---

build-support/functions/20-build.sh

Allow any supported goos/goarch combination to be built locally

---

.changelog/9366.txt
agent/consul/federation_state_replication.go
agent/consul/gateway_locator.go
agent/consul/gateway_locator_test.go
agent/consul/leader.go

server: when wan federating via mesh gateways only do heuristic primary DC bypass on the leader

---

website/content/docs/k8s/helm.mdx

https://github.com/hashicorp/consul-helm/pull/774

Update docs with fields for ingress support for consul UI

---

website/pages/home/index.jsx

currently still pointing at private beta link, need to fix for GA.

changing HCP Consul to reflect GA

---

website/content/docs/k8s/upgrade/compatibility.mdx

Adding 0.29 Consul Helm release

docs: Update Compat Matrix for Consul Helm 0.29

---

ui/packages/consul-ui/app/adapters/http.js

https://github.com/hashicorp/consul/pull/9147 didn't seem to cherry pick properly.

ui: Cherry pick of #9147

---

.changelog/9660.txt

See https://github.com/hashicorp/consul/pull/9660

chore: changelog for 9660

---

CHANGELOG.md
website/data/version.js

Pull the changelog and website changes back into master

Release 1.9.3

---

website/content/docs/nia/installation/requirements.mdx

[Docs preview](https://consul-fpwja13jy.vercel.app/docs/nia/installation/requirements#module-input-variables)

docs/nia: recommend sensitive variables for module authoring

---

website/components/config-entry-reference/index.jsx
website/package.json

Refactors to use the `Tabs` & `Tab` component from `@hashicorp/react-tabs` directly

chore: upgrade react tabs

---

website/components/config-entry-reference/index.jsx
website/package-lock.json
website/package.json

Upgrading next to v10 and nextjs-scripts to v15.
[_Created by Sourcegraph campaign `bkalow/upgrade-to-next-10`._](https://sourcegraph.hashi-mktg.com/users/bkalow/campaigns/upgrade-to-next-10)

website: update next and nextjs-scripts

---

.changelog/9651.txt
agent/proxycfg/snapshot.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/listeners_test.go

[1.7.x] xds: prevent LDS flaps in mesh gateways due to unstable datacenter lists

---

.changelog/9740.txt
.circleci/config.yml
agent/xds/proxysupport/proxysupport.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/access-log-path.golden
command/connect/envoy/testdata/defaults.golden
command/connect/envoy/testdata/existing-ca-file.golden
command/connect/envoy/testdata/extra_-multiple.golden
command/connect/envoy/testdata/extra_-single.golden
command/connect/envoy/testdata/grpc-addr-config.golden
command/connect/envoy/testdata/grpc-addr-env.golden
command/connect/envoy/testdata/grpc-addr-flag.golden
command/connect/envoy/testdata/grpc-addr-unix.golden
command/connect/envoy/testdata/stats-config-override.golden
command/connect/envoy/testdata/token-arg.golden
command/connect/envoy/testdata/token-env.golden
command/connect/envoy/testdata/token-file-arg.golden
command/connect/envoy/testdata/token-file-env.golden
command/connect/envoy/testdata/zipkin-tracing-config.golden
test/integration/connect/envoy/run-tests.sh
test/integration/connect/envoy/test-envoy-versions.sh

[1.7.x] connect: update supported envoy point releases to 1.13.7, 1.12.7, 1.11.2, 1.10.0

---

website/pages/home/index.jsx

Rotate homepage tutorials to feature the new HCP Consul Terraform provider and Microservices collection.

[website] Update Learn Tutorials

---

website/content/docs/intro/index.mdx

Fix typo and add link to Learn.

[docs] Consul intro

---

.changelog/9806.txt
agent/connect/ca/provider_vault.go

connect: if the token given to the vault provider returns no data avoid a panic

---

ui/packages/consul-ui/blueprints/adapter/files/__root__/__path__/__name__.js
ui/packages/consul-ui/blueprints/model/files/__root__/__path__/__name__.js
ui/packages/consul-ui/blueprints/repository/files/__root__/__path__/__name__.js
ui/packages/consul-ui/blueprints/serializer/files/__root__/__path__/__name__.js

This PR brings our application blueprints up to date with Octane and other additions/patterns in the application.
P.S. The base branch here is the `@dataSource` decorator work and hence includes these in the blueprints

ui: Blueprints update

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_oss_test.go
agent/consul/state/catalog_events_test.go

state: Add terminating gateway events for streaming

---

website/content/docs/k8s/observability/metrics.mdx

Gateway metrics docs

---

website/data/alert-banner.js

As requested by revenue marketing, updates the alert banner to promote HCP Consul

Update alert banner

---

website/content/docs/connect/config-entries/terminating-gateway.mdx

Builds were failing due to this small issue.

docs: fixup syntax issue

---

.changelog/8564.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
website/content/docs/connect/proxies/envoy.mdx

support env var expansion in envoy statsd urls

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go
agent/consul/state/indexer.go
agent/consul/state/state_store_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

Following the pattern from #9796 and #9797

state: convert services.ID to the new pattern of functional indexers 

---

website/content/docs/nia/architecture.mdx
website/content/docs/nia/configuration.mdx
website/content/docs/nia/index.mdx
website/content/docs/nia/installation/install.mdx
website/content/docs/nia/installation/run.mdx
website/content/docs/security/security-models/nia.mdx

Cherrypick from https://github.com/hashicorp/consul/pull/9893

Cherrypick NIA doc cross linking

---

website/content/docs/nia/installation/requirements.mdx

* Add Avi Network GH link
* Add AWS ALB TF Registry and GH link
* Add NS1 TF Registry and GH link

Add Avi Network, AWS ALB and NS1 TF Registries and GitHub links

---

website/content/docs/integrate/nia-integration.mdx

* Add link to TF tutorial
* Add links to print TF module and template for TF modules

Add link to TF module tutorial and example TF modules

---

website/content/docs/upgrading/index.mdx

easier to do this than rebase pull/8643

Docs: add enterprise upgrade link

---

website/pages/home/index.jsx

[:mag: Preview Link upcoming]()
---
This PR reorders items in the "Why Consul?" section, as well as adds CTA links to each item.

website(homepage changes): "Why Consul?" changes

---

.changelog/8564.txt

so these changelog entries will be parsed successfully

changelog: fixup release-note formatting

---

contributing/streaming/README.md
contributing/streaming/adding-a-topic.md

These docs are pretty high level, but hopefully better than nothing. Writing this down since we have been talking about adding new topics.
[Preview](https://github.com/hashicorp/consul/blob/dnephin/streaming-docs-adding-a-topic/contributing/streaming/adding-a-topic.md)

contributing: add a quick doc on adding new streaming topics.

---

agent/consul/state/catalog_oss_test.go
agent/consul/state/schema_test.go

And add a few additional cases.

state: support additional test cases in indexer tests

---

agent/structs/config_entry_cluster_oss.go

from https://github.com/hashicorp/consul/pull/9973

missed build tag on this file

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/autopilot.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/consul/state/connect_ca.go
agent/consul/state/coordinate.go
agent/consul/state/federation_state.go
agent/consul/state/graveyard.go
agent/consul/state/graveyard_oss.go
agent/consul/state/intention.go
agent/consul/state/prepared_query.go
agent/consul/state/session.go
agent/consul/state/session_oss.go
agent/consul/state/system_metadata.go

And use constant for the index table.
This change is extracted from a larger one that needs more work, and I don't want these changes to rot.

state: use Txn interface everywhere

---

website/pages/home/index.jsx

🔍  [Preview](https://consul-8woj94wd0-hashicorp.vercel.app/)
Update links under the Why HashiCorp section.

website: update why hashicorp links

---

.changelog/10025.txt
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go

[1.7.x] backport snapshot of ACL Auth Methods bug fix

---

.changelog/10025.txt
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go

[1.8.x] backport snapshot of ACL Auth Methods bug fix

---

.changelog/_795.txt

This PR adds a synthetic enterprise entry for CVE-2021-28156

Add synthetic enterprise entry for CVE-2021-28156

---

website/scripts/index_search_content.js

Fixes issue with searching indexing. This is resolved in a newer version of `@hashicorp/react-search`, but we're waiting on the branding rollout until we can upgrade.

website: fix search indexing issue

---

website/data/version.js

Missed including this in #10054

website: v1.9.5

---

website/content/docs/k8s/installation/install.mdx
website/pages/home/index.jsx
website/pages/use-cases/multi-platform-service-mesh.jsx

Point all our links to the standardized new entry point.

Refactor get started links to new tutorial

---

website/content/docs/connect/transparent-proxy.mdx

docs - Adding json formatting to TProxy HCL examples

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh
agent/consul/leader.go
agent/consul/replication.go
agent/consul/replication_test.go
agent/consul/server.go

In addition to cherry-picking the commit from #10073 this also cherry-picks the commit to fix up the CI SSH key fingerprint being used.

[Backport/1.10.x]: Backport #10073

---

.changelog/10002.txt

Updated changelog to use `feature` instead of `enhancement`.

ui: Fix up changelog for 10002

---

.circleci/config.yml

See https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 for context.

remove Codecov from CI runs

---

website/content/docs/discovery/services.mdx

fix https://github.com/hashicorp/consul/issues/9929

Improve doc: add note about address validation

---

GNUmakefile

dev: adding a make target to regenerate envoy golden files

---

ui/packages/consul-ui/app/components/app/index.scss
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
ui/packages/consul-ui/app/components/main-nav-vertical/README.mdx
ui/packages/consul-ui/app/components/main-nav-vertical/debug.scss
ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
ui/packages/consul-ui/app/styles/debug.scss
ui/packages/consul-ui/lib/startup/templates/head.html.js

The PR and merge of https://github.com/hashicorp/consul/pull/10034 straddled the 1.10.0-beta1 release, so I've manually cherry-picked this over.

[Backport/1.10.x] Backport #10034

---

.changelog/10062.txt
.circleci/config.yml
ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
ui/packages/consul-ui/app/helpers/duration-from.js
ui/packages/consul-ui/app/helpers/duration-from.mdx
ui/packages/consul-ui/app/services/temporal.js
ui/packages/consul-ui/package.json
ui/packages/consul-ui/tests/acceptance/dc/nodes/sessions/list.feature
ui/packages/consul-ui/tests/integration/helpers/duration-from-test.js
ui/packages/consul-ui/tests/unit/services/temporal-test.js
ui/yarn.lock

Manual backport of https://github.com/hashicorp/consul/pull/10062 due to lock file conflict

[Backport/1.9.x] Backport #10062

---

agent/consul/state/config_entry.go

Small cleanup around config-entry validation. Reduce the number of arguments to the functions.

state: reduce arguments to validateProposedConfigEntryInServiceGraph

---

api/config_entry_test.go
website/content/api-docs/config.mdx
website/content/commands/config/delete.mdx
website/content/commands/config/list.mdx
website/content/commands/config/read.mdx
website/content/docs/connect/config-entries/index.mdx
website/content/docs/connect/config-entries/mesh.mdx

docs: remove name field from Mesh config entry

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh

I'm hoping that once this merges the automation will handle 1.8.x

[1.9.x] Backport CI changes

---

.changelog/10188.txt
agent/local/state.go
agent/local/state_test.go

[1.9.x] agent/local: do not persist the agent or user token

---

website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

* also fix some formatting. Will be easier to review if you hide whitespace changes.

Update k8s fed docs to clarify role of acl token

---

website/data/alert-banner.js

[🔍 Preview](https://consul-dt4nhuy7f-hashicorp.vercel.app/)
Adding an AlertBanner component to promote HashiConf Europe.

Updates AlertBanner for HashiConf EU

---

.changelog/8812.txt
agent/config/default.go

Add raft default values to default config used by the agent endpoint.

GH-8728 add raft default values

---

command/connect/redirecttraffic/redirect_traffic_test.go

I noticed this test failure: https://app.circleci.com/pipelines/github/hashicorp/consul-enterprise/6408/workflows/e90b1140-daa2-458f-8197-d1821e3693e3/jobs/94694/tests#failed-test-0
Apparently the `ExcludeInboundPorts` slice can be in a different order sometimes, although I'm not sure how. Is it safe to ignore the order of these ports?
Also removes t.Parallel. We should only need to use t.Parallel in large packages with many slow tests. In this case there is only a single slow test so we don't get any benefit.
Also add struct field names to the testcases list, so that it is easier to see what each value is doing, and to make it easier to add new fields in the future. I learned GoLand has a "add keys to struct literal" helper in the context menu that made adding these easy.

redirecttraffic: fix a flaky test

---

website/content/api-docs/agent/check.mdx

this is to pull the changes from https://github.com/hashicorp/consul/pull/7364
fixes #6635
Update register check documentation clarify that Id returns as CheckId in the response
Co-Authored-By: Shaker Islam <shaqq@users.noreply.github.com>

docs: update register check docs (closes #6635)

---

website/content/commands/snapshot/agent.mdx

Add example least privilege ACL policy for Consul snapshot agent.

docs: Add example ACL policy for snapshot agent

---

.changelog/_917.txt
agent/consul/client_serf.go
agent/consul/enterprise_client_oss.go
agent/consul/enterprise_server_oss.go
agent/consul/replication.go
agent/consul/server_serf.go
agent/metadata/server.go
agent/metadata/server_test.go

Also add a changelog for the fix which motivated these changes

Backport some ent changes for serf tags

---

.changelog/_917.txt
agent/consul/client_serf.go
agent/consul/enterprise_client_oss.go
agent/consul/enterprise_server_oss.go
agent/consul/replication.go
agent/consul/server_serf.go
agent/metadata/server.go
agent/metadata/server_test.go

[1.8.x] Backport some ent changes for serf tags

---

.changelog/10225.txt
ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
ui/packages/consul-ui/app/models/session.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/components/composite-row.scss
ui/packages/consul-ui/mock-api/v1/session/info/_
ui/packages/consul-ui/mock-api/v1/session/node/_

[Backport/1.9.x] Backport #10225

---

agent/agent.go
agent/agent_oss.go
agent/agent_test.go
agent/consul/client.go
agent/consul/client_test.go
agent/consul/enterprise_client_oss.go
agent/consul/enterprise_server_oss.go
agent/consul/enterprise_server_oss_test.go
agent/consul/options.go
agent/consul/options_oss.go
agent/consul/server.go
agent/routine-leak-checker/leak_test.go
agent/setup.go
agent/setup_oss.go
sdk/testutil/context.go

Previously Consul Enterprise license management was performed at the Client/Server level and now thats being moved up one level to the Agent.
This PR includes all the necessary modifications to the OSS repo to support the move.

Preparation for changing where license management is done.

---

website/content/docs/install/glossary.mdx

This is an updated rebase of #9348.

Updating Consul Glossary with more industry standard terms

---

.circleci/config.yml
GNUmakefile
agent/dns.go

Upgrade linter (golangci-lint) to latest version. 
This detected a new problem that was fixed as part of the PR

upgrade golangci-lint to v1.40.1

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh

Backports #10196 to `release/1.8.x`

backport(1.8.x): CI release branch auto backport

---

.changelog/10304.txt
website/content/docs/ecs/get-started/install.mdx

Add note about new ECS ARN format to ECS docs

Add note about new ECS ARN format to ECS docs

---

.changelog/10273.txt
agent/http.go
api/debug.go
command/debug/debug.go
command/debug/debug_test.go

[1.9.x] debug: remove the CLI check for debug_enabled

---

website/pages/home/index.jsx

Fixes a small typo / broken link

[Website] Fix broken link

---

website/content/commands/license.mdx
website/content/docs/agent/options.mdx

There was some PR feedback that came in just after I merged that other PR. This addresses that feedback.

Follow on to PR #10336

---

.changelog/10338.txt
command/agent/agent.go
command/agent/agent_test.go
command/cli/cli.go
command/commands_oss.go
command/registry.go
main.go

[1.9.x] agent: remove leading whitespace from agent log lines

---

.changelog/10267.txt
.changelog/_938.txt
website/content/commands/license.mdx

Also reformatted another changelog entry to add a missing newline.

Add license inspect command documentation and changelog

---

website/data/alert-banner.js

Changes alert banner content to promote recorded HashiConf videos.

Adjust alert banner for the end of HashiConf

---

website/pages/home/index.jsx

Updated the descriptions to match the right tiles and added a new alert for ECS integration

Adding ECS copy and other edits

---

website/content/docs/connect/proxies/envoy.mdx
website/content/docs/upgrading/upgrade-specific.mdx

docs: update envoy docs for changes related to xDS v2->v3 and SoTW->Incremental

---

website/pages/home/index.jsx

redirecting users to learn instead of to the download page.

Updating button

---

agent/xds/delta_test.go
agent/xds/testing.go
agent/xds/xds_protocol_helpers_test.go

xds: adding more delta protocol tests

---

ui/package.json
ui/yarn.lock

ui: Upgrade dev tooling dependency

---

ui/package.json
ui/yarn.lock

ui: [Backport 1.9.x] Add resolution for xmlhttprequest-ssl at least 1.6.3 (#10370)

---

ui/packages/consul-ui/app/components/main-header-horizontal/layout.scss

Backport of https://github.com/hashicorp/consul/pull/10428

ui: Increase z-index of main menus to avoid layering issues (#10428)

---

website/content/docs/k8s/connect/observability/metrics.mdx

Reference Grafana Config in the learn guide

docs: Remove Grafana from Observability section

---

website/content/docs/k8s/upgrade/compatibility.mdx

Updating Consul K8s compat matrix for Consul 1.10

docs: Update Consul K8s Compat Matrix for Consul 1.10

---

website/components/subnav/index.jsx

Updates `utm_content` to align with how Revenue Marketing is tracking attribution for HCP.

Update utm_content param for improved attribution

---

api/api.go
command/agent/agent.go

{api,command/agent}: change io.Discard to ioutil.Discard

---

.changelog/10486.txt
connect/proxy/listener.go
connect/proxy/proxy.go
connect/proxy/proxy_test.go

connect/proxy: fixes logic bug preventing builtin/native proxy from starting upstream listeners

---

website/content/docs/enterprise/audit-logging.mdx

Resolves #8375, resolves #9055

docs: Add audit logging examples

---

website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx
website/data/docs-nav-data.json

Preview: [link](https://consul-61cdxpn44-hashicorp.vercel.app/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s)

docs: add docs for running a single Consul dc in multiple k8s clusters

---

ui/packages/consul-ui/app/components/topology-metrics/index.hbs

ui: [Backport 1.9.x] Send item name down to Stats to call endpoint (#9358)

---

website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/connect/ingress-controllers.mdx
website/data/docs-nav-data.json

Add a document describing common configurations required for using an ingress controller with consul-k8s
Note to reviewers : this is a bit WIP at the moment, I'm trying to provide enough context and information  to be helpful without being too prescriptive about specific settings/platforms.
Ideally we could have individual blog posts showing "how to use x, y, z ingress controllers" and link them on this page?

docs: Ingress controllers configurations 

---

website/content/docs/k8s/connect/ingress-controllers.mdx

Preview: [link](https://consul-28yblkzer-hashicorp.vercel.app/docs/k8s/connect/ingress-controllers)

docs: Formatting for Ingress Controllers example repos

---

website/content/api-docs/libraries-and-sdks.mdx
website/content/docs/k8s/helm.mdx
website/content/docs/release-notes/1-10-0.mdx
website/content/docs/release-notes/1-9-0.mdx
website/data/docs-nav-data.json

Somehow we ended up with the old master branch still existing in OSS. These changes are the few that were missing from `main` before I deleted `master.

Changes that were accidentally merged into the old master branch

---

.changelog/10330.txt
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/leader_connect_test.go

connect/ca: ensure edits to the key type/bits for the connect builtin CA will regenerate the roots

---

agent/catalog_endpoint.go
agent/http_oss.go
api/catalog.go
api/health.go

OSS component of a partition change for the http api

oss: add partition query param parsing

---

.changelog/10619.txt
agent/xds/rbac.go
agent/xds/rbac_test.go
agent/xds/testdata/rbac/default-allow-deny-all-and-path-allow--httpfilter.golden
agent/xds/testdata/rbac/default-allow-deny-all-and-path-allow.golden
agent/xds/testdata/rbac/default-allow-deny-all-and-path-deny--httpfilter.golden
agent/xds/testdata/rbac/default-allow-deny-all-and-path-deny.golden
agent/xds/testdata/rbac/default-allow-path-allow--httpfilter.golden
agent/xds/testdata/rbac/default-allow-path-allow.golden
agent/xds/testdata/rbac/default-allow-path-deny--httpfilter.golden
agent/xds/testdata/rbac/default-allow-path-deny.golden
agent/xds/testdata/rbac/default-deny-deny-all-and-path-allow--httpfilter.golden
agent/xds/testdata/rbac/default-deny-deny-all-and-path-allow.golden
agent/xds/testdata/rbac/default-deny-deny-all-and-path-deny--httpfilter.golden
agent/xds/testdata/rbac/default-deny-deny-all-and-path-deny.golden
agent/xds/testdata/rbac/default-deny-path-allow--httpfilter.golden
agent/xds/testdata/rbac/default-deny-path-allow.golden
agent/xds/testdata/rbac/default-deny-path-deny--httpfilter.golden
agent/xds/testdata/rbac/default-deny-path-deny.golden

(1.9.x) xds: ensure single L7 deny intention with default deny policy does not result in allow action (CVE-2021-36213)

---

.changelog/10009.txt
agent/dns.go
agent/dns_test.go

[1.9.x] dns: properly trim response when EDNS is used

---

ui/packages/consul-ui/app/components/topology-metrics/card/index.scss
ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/stats.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/topology/stats-steps.js
ui/packages/consul-ui/tests/steps/doubles/model.js

Add two tests for seeing and not seeing the metrics stats

ui: Add tests for topology metrics stats

---

.changelog/10657.txt
agent/consul/leader_connect_ca.go
agent/consul/state/connect_ca.go
agent/consul/state/connect_ca_test.go

config raft apply silent error

---

command/flags/http.go

add partition http flag to be used by namespace

add http flag for admin partition

---

agent/consul/catalog_endpoint.go
agent/consul/coordinate_endpoint.go
agent/consul/coordinate_endpoint_test.go
agent/consul/fsm/commands_oss.go
agent/consul/fsm/commands_oss_test.go
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/leader.go
agent/consul/leader_test.go
agent/consul/prepared_query_endpoint.go
agent/consul/rtt.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/coordinate.go
agent/consul/state/coordinate_test.go
agent/consul/state/session_test.go
agent/consul/state/txn_test.go
agent/consul/state/usage_test.go
agent/consul/txn_endpoint_test.go

Note the field is not used yet.

state: refactor some node/coordinate state store functions to take an EnterpriseMeta

---

.changelog/10688.txt
agent/agent_endpoint_test.go
agent/config/runtime_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
agent/structs/service_definition.go
agent/structs/testing_connect_proxy_config.go

agent: update proxy upstreams to inherit namespace from service

---

.changelog/10688.txt
agent/agent_endpoint_test.go
agent/config/runtime_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
agent/structs/service_definition.go
agent/structs/testing_connect_proxy_config.go

(cherry picked from commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad)

agent: update proxy upstreams to inherit namespace from service (#10688/backport-1.10.x)

---

.changelog/10688.txt
agent/agent_endpoint_test.go
agent/config/runtime_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
agent/structs/service_definition.go
agent/structs/testing_connect_proxy_config.go

(cherry picked from commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad)

agent: update proxy upstreams to inherit namespace from service (#10688/backport-1.9.x)

---

.changelog/10688.txt
agent/agent_endpoint_test.go
agent/config/runtime_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
agent/structs/service_definition.go
agent/structs/structs_oss.go
agent/structs/testing_connect_proxy_config.go

(cherry picked from commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad)

agent: update proxy upstreams to inherit namespace from service (#10688/backport-1.8.x)

---

agent/agent_endpoint_test.go
agent/structs/service_definition.go

Updates to test files and comments from enterprise PR feedback

sync enterprise files with oss

---

website/content/docs/nia/installation/requirements.mdx

Add Citrix Terraform Registry and GH links

NIA Docs: Add Citrix TF module links

---

agent/agent_endpoint_test.go
agent/structs/service_definition.go

(cherry picked from commit 9c3af1a4298add7161512bc2bc817eb6d67f6531)

sync enterprise files with oss (#10705/backport-1.10.x)

---

agent/agent_endpoint_test.go
agent/structs/service_definition.go

(cherry picked from commit 9c3af1a4298add7161512bc2bc817eb6d67f6531)

sync enterprise files with oss (#10705/backport-1.8.x)

---

agent/agent_endpoint_test.go
agent/structs/service_definition.go

(cherry picked from commit 9c3af1a4298add7161512bc2bc817eb6d67f6531)

sync enterprise files with oss (#10705/backport-1.9.x)

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/network-drivers/index.mdx

Add more features to TFE list

---

website/content/docs/nia/installation/requirements.mdx

Add Citrix TF module links to NIA docs

Add Citrix TF module links to NIA docs (#10710)

---

acl/policy_authorizer.go
agent/consul/acl.go
agent/consul/catalog_endpoint.go
agent/consul/txn_endpoint.go
agent/structs/intention.go

Follow up to https://github.com/hashicorp/consul/pull/10738#discussion_r680190210 and https://github.com/hashicorp/consul/pull/10737#discussion_r680134445.
More details in the commit messages. I think one of these is actually a bug fix as well.

acl: small cleanup of a couple Authorization flows

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx

- [Service condition configuration changes](https://consul-okp07abf1-hashicorp.vercel.app/docs/nia/configuration#services-condition)
- [Task Execution: Services Condition changes](https://consul-okp07abf1-hashicorp.vercel.app/docs/nia/tasks#services-condition)

docs/nia: Add regex option to services condition

---

.changelog/10838.txt
agent/agent_test.go
agent/consul/client_test.go
agent/consul/options.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/server.go
agent/consul/subscribe_backend_test.go
agent/consul/wanfed/wanfed.go
agent/grpc/client.go
agent/grpc/client_test.go
agent/grpc/resolver/resolver.go
agent/grpc/server_test.go
agent/pool/conn.go
agent/pool/peek_test.go
agent/pool/pool.go
agent/setup.go

[1.10.x] grpc: ensure that streaming gRPC requests work over mesh gateway based wan federation

---

website/content/docs/nia/enterprise/license.mdx

[link to new section](https://consul-ofofe5suf-hashicorp.vercel.app/docs/nia/enterprise/license#updating-the-license)

docs/nia: add section on how to update cts-ent license

---

agent/connect/sni.go
agent/connect/sni_test.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go
agent/structs/discovery_chain.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/routes.go

This add partition to SNI while preserving retro compatibility for default partition

add partition to SNI when partition is non default

---

agent/catalog_endpoint.go
agent/coordinate_endpoint.go
agent/http_oss.go
agent/ui_endpoint.go

Partition: try to infer command partition from node partition

try to infer command partition from node partition

---

website/content/api-docs/query.mdx

docs: Add supported consistency modes to prepared queries

---

agent/config_endpoint.go
agent/consul/enterprise_server_oss.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/consul/leader_intentions.go
agent/consul/state/config_entry_intention.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/http_oss.go
agent/intentions_endpoint.go
agent/intentions_endpoint_test.go
agent/structs/config_entry.go
agent/structs/config_entry_intentions.go
agent/structs/config_entry_intentions_test.go
agent/structs/config_entry_test.go
agent/structs/intention.go
agent/structs/intention_oss.go
agent/structs/intention_test.go
agent/structs/structs_filtering_test.go
agent/structs/testing_intention.go

This PR updates OSS with files for enterprise-specific admin partitions feature work

Sync enterprise changes to oss

---

website/content/docs/security/security-models/core.mdx

Inspired by a practitioner's experience in #10721

docs: give tutorials links for securing UI access

---

agent/consul/state/acl.go
agent/consul/state/acl_events.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go

Convert SecretID to use indexerSingle
rename all literals "acl-tokens" to const tableACLTokens

convert `SecretID` index to use `indexerSingle`

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go
agent/consul/state/schema_test.go

Convert `indexPolicies` to a `indexerMulti`

convert `Policies` index to use `indexerMulti`

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go

convert `Roles` index to use `indexerMulti`

convert `Roles` index to use `indexerMulti`

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_schema.go
agent/consul/state/indexer.go
agent/consul/state/query.go

add locality indexer partitioning

add locality indexer partitioning

---

agent/consul/state/acl.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/consul/state/indexer.go

convert expiration indexed in ACLToken table to use `indexerSingle`

convert expiration indexed in ACLToken table to use `indexerSingle`

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/consul/state/schema_test.go

Refactor `indexAuthMethod` in `tableACLBindingRules`

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go

ACL Binding Rules table partitioning

---

acl/policy_authorizer.go
agent/consul/acl_test.go
agent/consul/intention_endpoint_test.go
agent/structs/intention.go

This is a partial revert of #10793

acl: fix intention:*:write checks

---

ui/packages/consul-ui/app/routes/dc.js

See title ^
Preferably this one _would_ make the next release. @mikemorris

ui: Ensure we request permission with the correct partition

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

Changes:
https://consul-1gpbw1hd6-hashicorp.vercel.app/docs/nia/configuration#consul-kv-condition
https://consul-1gpbw1hd6-hashicorp.vercel.app/docs/nia/tasks#consul-kv-condition
https://consul-1gpbw1hd6-hashicorp.vercel.app/docs/nia/terraform-modules#consul-kv-variable

docs/nia: Add Consul KV condition

---

.changelog/11026.txt
api/acl.go
internal/go-sso/oidcauth/config.go
internal/go-sso/oidcauth/config_test.go
internal/go-sso/oidcauth/oidc.go
internal/go-sso/oidcauth/oidc_test.go

[1.8.x] Backport adding acr_values to OIDC requests

---

.changelog/11107.txt
agent/delegate_mock_test.go

Also adding a changelog entry for the enterprise additions where this mock would be used.

Add a mock Agent delegate to ease/improve some types of testing

---

agent/consul/state/schema.go
agent/consul/state/state_store.go

Refactor table index

---

ui/packages/consul-ui/tests/steps/assertions/dom.js

See https://github.com/hashicorp/consul/pull/11127

ui: Fixup backport of 11095: adding dont which exists in 1.10 but not 1.9

---

ui-v2/tests/acceptance/dc/intentions/create.feature

ui: [Backport 1.8.x] Use last-child for selecting the desired nspace instead of nth-child

---

website/data/alert-banner.js

[:mag: Preview link upcoming](https://consul-git-nqupdate-alert-banner-hcg2021-hashicorp.vercel.app/)
---
This PR updates the alert banner for HashiConf Global 2021.

Update alert banner for HashiConf Global 2021

---

website/content/docs/k8s/k8s-cli.mdx

Add `bin/` to path from which you move `consul-k8s` to `/usr/local/bin/consul-k8s`

docs: consul-k8s cli install, add `bin/` to source path

---

agent/consul/autopilot.go

Fixing a minuscule typo in logging

Fix a tiny typo in logging in autopilot.go

---

agent/consul/intention_endpoint_test.go
agent/consul/state/intention_test.go
agent/structs/intention_oss.go
agent/structs/testing_intention.go

Cleanup unnecessary partition normalizing method for intentions

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/network-drivers/index.mdx
website/content/docs/nia/network-drivers/terraform-cloud.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

TFC callouts:
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/network-drivers
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/network-drivers/terraform-cloud
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/configuration#terraform-cloud-driver
Consul KV callouts:
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/tasks#consul-kv-condition
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/configuration#consul-kv-condition
https://consul-rf5ihwjmn-hashicorp.vercel.app/docs/nia/terraform-modules#consul-kv-variable

nia/docs: Callouts for v0.4.0-beta

---

agent/checks/alias.go
agent/consul/config_endpoint.go
agent/consul/state/acl.go
agent/consul/state/catalog.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_intention.go
agent/consul/state/intention.go
agent/dns.go
agent/local/state.go
agent/proxycfg/connect_proxy.go
agent/proxycfg/mesh_gateway.go
agent/structs/structs.go
agent/structs/structs_oss.go
agent/ui_endpoint.go

structs: remove EnterpriseMeta helper methods

---

website/content/docs/agent/index.mdx

One of the issues I had as someone brand new to Consul was that I didn't have a level of guidance between the getting started tutorials and the documentation. This PR is intended to cover the gap and provide a starting point for users at a similar level. It answers many of the questions I had when I first started that I couldn't figure out from the tutorials or current docs.

providing additional information about the Consul agent

---

agent/consul/state/acl.go

fix enterprise meta when listing tokens per auth method

fix token list by auth method 

---

website/components/card-list/index.tsx
website/components/card-list/style.module.css
website/components/consul-on-kubernetes-hero/index.tsx
website/components/consul-on-kubernetes-hero/style.module.css
website/components/docs-list/index.tsx
website/components/features-list/style.module.css
website/pages/consul-on-kubernetes/index.tsx

🎟️ **Asana Tasks:** [New copy](https://app.asana.com/0/1200785913255669/1200992155224319/f)  |   [Copy Updates](https://app.asana.com/0/1200785913255669/1201099558945921/f)  |   [Style Update](https://app.asana.com/0/1200785913255669/1201099558945906/f)
🔍 [Preview Link](https://consul-git-pbconsul-on-kubernetes-content-hashicorp.vercel.app/consul-on-kubernetes)
💅 [Design Reference](https://www.figma.com/file/0DT6uKPK214eFZtMG0pQUA/Consul-on-Kubernetes?node-id=102%3A6583)
This PR adds and updates content in the Consul on Kubernetes page. It also includes some updated styles.
This is a feature PR targeting assembly branch: #11047

Consul on Kubernetes Content

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

agent: Support partitions in parseIntentionStringComponent

---

website/content/docs/nia/configuration.mdx

CTS: add TLS config for TFE connection

---

website/content/docs/k8s/k8s-cli.mdx

In this PR, I added the `version` subcommand. I also added `--help` flags to the `install`/`uninstall` commands

added version flag to consul-k8s cli docs

---

website/content/docs/nia/configuration.mdx

- Clarify file types and uses of the configurations
- Update some wording to match between Consul and TFE TLS configs
Changes:
https://consul-1jfn77f2c-hashicorp.vercel.app/docs/nia/configuration#tls
https://consul-1jfn77f2c-hashicorp.vercel.app/docs/nia/configuration#tls-1

docs/nia: Update TLS-related configurations for CTS

---

website/data/subnav.js

per request from HLT, updating use case tab to lead to K8s page instead of service mesh.

adding K8s page to subnav

---

website/content/docs/k8s/installation/platforms/self-hosted-kubernetes.mdx

Closes https://github.com/hashicorp/consul-k8s/issues/776

Document default storage class requirements

---

website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/k8s-cli.mdx
website/content/docs/k8s/operations/uninstall.mdx

Add brew install workflow to docs, and re-order Consul K8s CLI to come first.

docs: add `brew install hashicorp/tap/consul-k8s` and re-order install and uninstall workflows 

---

agent/consul/acl_endpoint_test.go
api/kv.go
api/txn_test.go
command/kv/get/kv_get.go
command/kv/impexp/kvimpexp.go

KV partitioning part 2

---

.changelog/11491.txt
agent/agent.go
agent/agent_test.go
agent/service_manager_test.go
agent/structs/structs.go
agent/util.go
agent/util_test.go

Backport https://github.com/hashicorp/consul/pull/11491

Ma/md5 fix backport 1.9

---

.changelog/11522.txt
agent/proxycfg/testing.go
agent/structs/testing_catalog.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/testdata/endpoints/mesh-gateway-newer-information-in-federation-states.envoy-1-14-x.golden
agent/xds/testdata/endpoints/mesh-gateway-older-information-in-federation-states.envoy-1-14-x.golden

Backport 1.8.x: xds: prefer fed state gateway definitions if they're fresher

---

.changelog/11520.txt
ui/packages/consul-ui/app/services/repository/permission.js

Fixes https://github.com/hashicorp/consul/issues/11511
Related: https://github.com/hashicorp/consul/issues/11098
cc @jkirschner-hashicorp @dnephin

ui: Temporarily force all UI capabilities

---

.changelog/11522.txt
agent/proxycfg/testing.go
agent/structs/testing_catalog.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/testdata/endpoints/mesh-gateway-newer-information-in-federation-states.envoy-1-18-x.golden
agent/xds/testdata/endpoints/mesh-gateway-newer-information-in-federation-states.v2compat.envoy-1-16-x.golden
agent/xds/testdata/endpoints/mesh-gateway-older-information-in-federation-states.envoy-1-18-x.golden
agent/xds/testdata/endpoints/mesh-gateway-older-information-in-federation-states.v2compat.envoy-1-16-x.golden

Backport 1.10.x: xds: prefer fed state gateway definitions if they're fresher

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/network-drivers/terraform-cloud.mdx

docs: Add workspace tags

---

.changelog/_1328.txt

Changelog for bug fix in Consul Enterprise.

changelog: entry for snapshot agent `license_path` bug

---

website/content/docs/ecs/get-started/install.mdx
website/content/docs/ecs/get-started/migrate-existing-tasks.mdx
website/content/docs/ecs/index.mdx
website/data/docs-nav-data.json

* Remove "beta" tag
* `retry_join` is a list
* Link to new learn guides

docs: ECS GA doc update

---

website/content/docs/security/acl/acl-rules.mdx

Fixing spelling under Matching and Prefix Values

---

Dockerfile

make sure entrypoint file is always executable

Make entrypoint script always executable

---

website/data/version.js

Update website version to 1.10.4

---

agent/consul/leader_connect_ca.go

Branched from #11338
The motivation is largely the same, make it easier to see the two distinct modes. Another barrier to creating types for these two modes is access to shared state. In this case I found that checking the state is unnecessary because the callers have already set the correct state.
I opened #11346 as potential next steps along these lines.

ca: reduce use of state in the secondary

---

agent/consul/leader_connect_ca.go

In #9991 (d2ab767fef21244e9fe3b9887ea70fc177912381) `raftApply` was changed to handle this check in a single place, instead of requiring every caller check it. It looks like these few places were missed when I did that clean up.
This commit removes the remaining `resp.(error)` checks, since they are all no-ops now.

ca: clean up unnecessary raft.Apply response checking

---

website/content/docs/connect/config-entries/partition-exports.mdx
website/content/docs/connect/proxies/integrate.mdx
website/content/docs/connect/registration/service-registration.mdx
website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/k8s/crds/index.mdx
website/data/docs-nav-data.json

This PR adds the updates from #11692 to stable website

docs: updated stable website docs

---

.changelog/11656.txt
ui/packages/consul-ui/app/components/policy-form/index.hbs

☝️ 
Chatted through with @freddygv and @rboyer offline also (fyi folks)

ui: Don't show policy datacenter selector for non-default partitions

---

.changelog/11654.txt
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
website/content/docs/agent/options.mdx
website/content/docs/connect/observability/ui-visualization.mdx

Plus consul.io docs amends. @trujillo-adam I think I got the only two places where we mention this, but lemme know if I missed one

ui: Add `Service.Partition` as available variable for dashboard urls

---

.changelog/11722.txt
agent/agent.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/consul/server.go
agent/consul/server_oss.go
api/agent.go
command/forceleave/forceleave.go

agent: add variation of force-leave that exclusively works on the WAN

---

website/content/api-docs/agent/connect.mdx

This adds some an update to the docs after https://github.com/hashicorp/consul/pull/11693.

update connect ca leaf endpoint docs

---

agent/consul/txn_endpoint.go
agent/consul/txn_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the txn `Read` endpoint.
Note: as the `Apply` endpoint's response type doesn't embed `QueryMeta` I didn't add support for the new header there.

txn: support `ResultsFilteredByACLs` flag in `Read` endpoint

---

website/content/commands/admin-partition.mdx

Renamed for consistency with the HTTP API and CLI flags.

Rename partition CLI command

---

.changelog/11696.txt
ui/packages/consul-ui/app/components/code-editor/README.mdx
ui/packages/consul-ui/app/components/code-editor/index.hbs
ui/packages/consul-ui/app/components/consul/node-identity/template/README.mdx
ui/packages/consul-ui/app/components/consul/node-identity/template/index.hbs
ui/packages/consul-ui/app/components/consul/service-identity/template/README.mdx
ui/packages/consul-ui/app/components/consul/service-identity/template/index.hbs
ui/packages/consul-ui/app/components/inline-code/README.mdx
ui/packages/consul-ui/app/components/inline-code/layout.scss
ui/packages/consul-ui/app/components/inline-code/skin.scss
ui/packages/consul-ui/app/components/policy-form/index.hbs
ui/packages/consul-ui/app/components/policy-selector/index.hbs
ui/packages/consul-ui/app/styles/debug.scss

Adds partition support for our Service and Node Identity templates

ui: Adds partition support to Service and Node Identity templates

---

.changelog/11681.txt
ui/packages/consul-ui/app/services/data-source/service.js
ui/packages/consul-ui/app/utils/dom/event-source/callable.js

See https://github.com/hashicorp/consul/pull/11681

ui: [Backport 1.10.x] Don't cache event sources following a 401

---

agent/consul/catalog_endpoint.go
agent/structs/structs.go

Resolves https://github.com/hashicorp/consul/issues/11707
Tried my best to add new docs and clarify existing ones. Any suggestions are welcome!

Godoc updates for catalog endpoints

---

website/content/docs/security/security-models/nia.mdx

This change adds a missing verb at the end of the sentence.

docs: add missing verb

---

agent/consul/server_test.go

Backport of patch in enterprise.

test: test server should auto cleanup

---

.changelog/11747.txt
ui/packages/consul-ui/app/components/consul/discovery-chain/resolver-card/index.hbs
ui/packages/consul-ui/app/components/consul/discovery-chain/utils.js
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-1
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-2
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-3
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-4
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-5
ui/packages/consul-ui/mock-api/v1/discovery-chain/virtual-admin-6
ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-resolvers-test.js
ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-splitters-test.js

There is one user facing fix here (something I missed in https://github.com/hashicorp/consul/pull/11679). Plus a bunch of DX/fixture amends for when we manually check the functionality of the discovery chain component.
I decided it would be best to just PR this altogether for ease, but will note the bugfix inline.
~P.S. Looking at the failing tests now 😅~
~Moving to Draft til I get more info here~
Turns out the reason why I thought it was a bug is because that bit wasn't quite finished up yet, that PR finishing that up is now in so all makes sense.

ui: Amends to Routing visualization for partitions

---

api/namespace.go
command/acl/authmethod/formatter.go
command/acl/bindingrule/formatter.go
command/acl/policy/formatter.go
command/acl/role/formatter.go
command/acl/token/clone/token_clone_test.go
command/acl/token/formatter.go

Admin Partitions is an Enterprise feature.
I regex searched for `"\s*Namespace:` and added Partitions wherever Namespace was being written to a buffer.

Add partitions to prettyformatters

---

ui/packages/consul-partitions/app/components/consul/partition/form/index.hbs
ui/packages/consul-partitions/app/components/consul/partition/notifications/index.hbs
ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
ui/packages/consul-partitions/app/templates/dc/partitions/edit.hbs
ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs
ui/packages/consul-ui/app/components/auth-form/index.hbs
ui/packages/consul-ui/app/components/oidc-select/index.hbs

See title.
There are no real functional changes here, just copy updates as we decided to use the 'full term' "Admin Partition" less.

ui: Prefer shorter partition word in certain places vs Admin Partition

---

.changelog/11850.txt
ui/packages/consul-ui/app/components/app/index.scss

Fixes https://github.com/hashicorp/consul/issues/11849 , also see https://github.com/hashicorp/consul/pull/11803#issuecomment-994288219

ui: Fixes an issue with the version footer when scrolling

---

website/content/docs/enterprise/admin-partitions.mdx

Bump consul-enterprise image to GA.

docs: Admin Partitions image bump to GA

---

website/data/docs-nav-data.json

Remove BETA from Admin Partitions Nav

docs: Remove BETA from Admin Partitions

---

website/content/docs/connect/config-entries/exported-services.mdx

docs: fix ExportedServices typo on example

---

website/content/commands/partition.mdx

Remove beta notice from CLI doc

---

website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/k8s/crds/index.mdx

Correcting ExportedServices reference and example

docs: ExportedServices YAML correction

---

website/content/docs/k8s/installation/vault/index.mdx
website/content/docs/k8s/k8s-cli.mdx

Clarification on limitations on Helm chart automation fro Vault Secrets backend

docs: clarification on Limitations for Vault Secrets backend

---

.changelog/11781.txt
command/tls/ca/create/tls_ca_create.go
command/tls/ca/create/tls_ca_create_test.go
command/tls/cert/create/tls_cert_create.go
command/tls/cert/create/tls_cert_create_test.go

This applies to
consul tls ca create
consul tls cert create -client
consul tls cert create -server
Closes: #11741

cli: consul tls: create private keys with mode 0600

---

.changelog/11820.txt
agent/http.go

Response now clearly indicates:
- the UI is disabled
- how to enable the UI

http: improve UI not enabled response message

---

.github/ISSUE_TEMPLATE/docs_day.md

This PR creates a GitHub issue for Consul docs days.

chore: created an issue template for Consul docs day

---

website/content/docs/k8s/installation/vault/connect-ca.mdx
website/content/docs/k8s/installation/vault/gossip.mdx
website/content/docs/k8s/installation/vault/index.mdx
website/content/docs/k8s/installation/vault/server-tls.mdx

Adding more details for requirements needed to run the Vault Secrets Backend integration successfully.

docs: Clarification of Vault Consul K8s requirements for Auth Method

---

website/content/docs/connect/nomad.mdx

[:mag: Preview Link](https://consul-git-nqwebupdate-copy-hashicorp.vercel.app/docs/connect/nomad)
---
This PR updates some text on the Consul docs related to Nomad.

website: Update Nomad-related text

---

ui/packages/consul-ui/app/components/code-editor/index.js
ui/packages/consul-ui/app/instance-initializers/ivy-codemirror.js
ui/packages/consul-ui/app/services/code-mirror/linter.js
ui/packages/consul-ui/app/styles/components/code-editor/skin.scss
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/lib/startup/templates/body.html.js

Backport of https://github.com/hashicorp/consul/pull/11785 for 1.9.x

ui: [Backport/1.9.x] Add XML syntax highlighting to key/value editor

---

.changelog/11918.txt
agent/config/builder.go
agent/config/builder_test.go
agent/consul/client.go
agent/consul/server.go
command/snapshot/save/snapshot_save.go
command/snapshot/save/snapshot_save_test.go

Best viewed by individual commit, details in the commit messages.

Fix a few small bugs

---

.changelog/11940.txt
agent/local/state.go
vendor/github.com/hashicorp/raft/configuration.go
vendor/github.com/hashicorp/raft/net_transport.go
vendor/github.com/hashicorp/raft/raft.go
vendor/modules.txt

create a struct and copy the pointer to mutate it to avoid a data race

---

.changelog/11968.txt
ui/packages/consul-ui/app/abilities/kv.js
ui/packages/consul-ui/app/services/repository/kv.js

See https://github.com/hashicorp/consul/pull/11968

ui: [Backport/1.10.x] Remove KV pre-flight auth check

---

website/content/docs/discovery/services.mdx

Added HCL examples to service discovery page - I updated the main service discovery example as well as the multiple services example in this PR.

Added HCL examples to service discovery page

---

website/content/docs/discovery/checks.mdx

Updated all the examples in [Health Checks Docs](https://www.consul.io/docs/discovery/checks) to have HCL equivalents

Updated health check docs page with HCL examples

---

website/content/docs/architecture/coordinates.mdx

This PR is specifically for the [`architecture` pages](https://www.consul.io/docs/architecture) of the docs.
- Added `<CodeBlockConfig>` tags for code snippets with headings where applicable

Update Web Components for Architecture pages

---

website/content/docs/download-tools.mdx

Add CTS and API Gateway to docs on tools page

---

website/content/docs/nia/index.mdx

https://consul-47n4k1n3f-hashicorp.vercel.app/docs/nia#glossary

Clarify CTS monitoring of service and instances

---

website/package-lock.json
website/package.json

👀 [Preview](https://consul-git-brkfeat-upgrade-downloads-page-hashicorp.vercel.app/downloads)
Upgrade the downloads page component. The new version includes a retry on the fetch for release metadata, which should hopefully alleviate failed deploys immediately after a product release.

website: upgrade downloads page

---

website/content/docs/k8s/operations/uninstall.mdx

Formatting issue on command, add $ prior to command. Also ensure bulleted numbers are in correct order.

docs: Formatting for Consul K8s uninstall commands

---

.github/workflows/build.yml
.release/ci.hcl
CHANGELOG.md
version/version.go

Updates needed to pin version and changelog entries.

Stage 1.9.14 release

---

.github/workflows/build.yml
.release/ci.hcl
CHANGELOG.md
version/version.go

Updates needed to pin version and changelog entries.

Stage 1.10.7 release

---

website/next.config.js
website/package-lock.json
website/package.json
website/pages/api-docs/[[...page]].jsx
website/pages/commands/[[...page]].jsx
website/pages/docs/[[...page]].jsx

This introduces versioned-docs to Consul!
https://consul-git-kevin-versioned-docs-hashicorp.vercel.app/

feat: versioned-docs

---

CHANGELOG.md

Merge in changelog from 1.11.2

---

CHANGELOG.md

Merge in changelog from 1.10.7

---

website/data/version.js

Update website for latest version

---

website/content/docs/nia/compatibility.mdx

https://consul-9m4l5xzyi-hashicorp.vercel.app/docs/nia/compatibility

docs/nia: CTS Terraform v1.1 compatibility

---

.github/workflows/build.yml

This updates the ECR tag to the correct naming convention.
Signed-off-by: Scott Macfarlane <smacfarlane@hashicorp.com>

Update ECR tag in CRT Builds

---

website/package-lock.json
website/package.json

Upgrades `@hashicorp/react-content`, which removes explicit left alignment on table headings, allowing markdown short-hand for table alignment,

website: chore: upgrades react-content

---

website/content/docs/k8s/upgrade/index.mdx

There is no longer the lifecycle sidecar

Update k8s upgrade docs

---

.changelog/11827.txt
agent/acl_endpoint_test.go
agent/agent.go
agent/agent_endpoint_test.go
agent/consul/acl.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_test.go
agent/consul/acl_token_exp_test.go
agent/consul/auto_config_backend_test.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/federation_state_endpoint_test.go
agent/consul/fsm/commands_oss_test.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/leader_connect_test.go
agent/consul/leader_test.go
agent/consul/prepared_query_endpoint_test.go
agent/consul/server_test.go
agent/consul/state/prepared_query_test.go
agent/local/state_test.go
agent/structs/acl.go
api/acl_test.go
api/api_test.go
api/catalog_test.go
api/prepared_query_test.go
sdk/testutil/README.md
sdk/testutil/server.go
ui/packages/consul-ui/mock-api/v1/acl/list

This is the OSS port of enterprise PR 1443 (see that one for a commit-by-commit review).

[OSS] Remove remaining references to master

---

.golangci.yml

lint: forbid require.New and assert.New

---

ui/packages/consul-ui/app/utils/btoa.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/app/utils/keyToArray.js
ui/packages/consul-ui/app/utils/maybe-call.js
ui/packages/consul-ui/app/utils/merge-checks.js
ui/packages/consul-ui/app/utils/routing/walk.js
ui/packages/consul-ui/app/utils/tomography.js

This PR _mostly_ tweaks some code related meta information.

ui: Tweak some code related meta information

---

website/content/docs/k8s/installation/install-cli.mdx
website/content/docs/k8s/installation/vault/connect-ca.mdx
website/content/docs/k8s/installation/vault/gossip.mdx
website/content/docs/k8s/installation/vault/index.mdx
website/content/docs/k8s/installation/vault/server-tls.mdx

- Vault docs formatting
- Fix broken link on Consul K8s CLI install docs

docs: Formatting Consul K8s Vault docs

---

website/content/docs/k8s/installation/vault/connect-ca.mdx
website/content/docs/k8s/installation/vault/gossip.mdx
website/content/docs/k8s/installation/vault/index.mdx
website/content/docs/k8s/installation/vault/server-tls.mdx

- Removal of extraneous code tabs
- Indentation of some steps

docs: Vault Secrets Backend K8s, remove code tabs

---

api/acl.go
api/catalog.go
api/config_entry.go
api/coordinate.go
api/discovery_chain.go

An attempt to fix the agent endpoint api. This MR complements #11957

Add api changes to agent endpoint for part 2

---

website/content/docs/connect/observability/ui-visualization.mdx

adding JSON examples in tabs the the UI Visualization documentation

adding JSON examples to /docs/connect/observability/ui-visualization

---

website/content/docs/enterprise/admin-partitions.mdx

Clarify deployment model for Clients and Servers on K8s.

docs: Admin Partitions K8s requirement update

---

api/agent.go

Backport of https://github.com/hashicorp/consul/pull/12184

[1.10.x] Remove incorrect usage of url.PathEscape

---

api/agent.go

Backport of https://github.com/hashicorp/consul/pull/12184

[1.9.x] Remove incorrect usage of url.PathEscape

---

website/content/docs/connect/transparent-proxy.mdx

docs: iptables for TProxy requirement

---

.circleci/config.yml

Fixes error encountered [here](https://app.circleci.com/pipelines/github/hashicorp/consul/26664/workflows/e42f22a8-d7fc-41a9-b9ae-91bbfe2d9229/jobs/568075)

ci: Update CI to stash changes before checkout

---

website/content/docs/k8s/connect/index.mdx

Add docs for https://github.com/hashicorp/consul-k8s/pull/956
Note: this will need to be merged together or after the next consul-k8s release

docs: Add annotations for consul-sidecar resource overrides

---

website/content/docs/k8s/helm.mdx

Update the documentation on the website for Helm values to reflect values added for Consul API Gateway in the 0.40.0 release of Consul on Kubernetes.

Update Helm docs to reflect 0.40.0 release

---

agent/catalog_endpoint.go
agent/config_endpoint.go
agent/coordinate_endpoint.go
agent/coordinate_endpoint_test.go
agent/discovery_chain_endpoint.go
agent/event_endpoint.go
agent/event_endpoint_test.go
agent/health_endpoint.go
agent/health_endpoint_test.go
agent/http.go
agent/intentions_endpoint.go
agent/kvs_endpoint.go
agent/prepared_query_endpoint.go
agent/prepared_query_endpoint_test.go
agent/session_endpoint.go
agent/txn_endpoint.go
agent/txn_endpoint_test.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go
agent/uiserver/bindata_assetfs.go

issue #11393 
This is a continuation of a previous PR (#11599). Transition all the remaining endpoints to returning an error as opposed to writing directly to the response body.

Change error-handling across handlers. 

---

website/content/docs/api-gateway.mdx

Provide link to Helm chart apigateway stanza and clarify a few requirements.

docs: Small changes to API Gateway docs

---

website/components/footer/index.jsx

pointing to the brand page instead of a zip file.

updating press kit link

---

website/content/docs/k8s/installation/install.mdx

Update install doc for Consul K8s CLI with example of service mesh enabled.

docs: slight formatting update and provide example with service mesh enabled 

---

website/content/docs/k8s/upgrade/index.mdx

Updating examples to Consul K8s 0.40.0 and adding formatting

docs: formatting and update to consul-k8s 0.40.0

---

website/content/docs/k8s/installation/install.mdx

Provide a more explicit example for enabling mesh by using a label.

docs: provide example for enabling mesh on a per namespace basis

---

website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/config-entries/service-router.mdx
website/content/docs/connect/config-entries/service-splitter.mdx

Add docs now that k8s supports these new config entry fields

docs: update for k8s support for igw and header manip

---

agent/acl_test.go
agent/ae/ae_test.go
agent/consul/client_test.go
agent/consul/leader_test.go
agent/consul/prepared_query_endpoint_test.go
agent/http_test.go
agent/router/manager_internal_test.go
agent/testagent.go
sdk/testutil/testlog.go

Closes #12143
And default log level to WARN.

sdk: add TestLogLevel for setting log level in tests

---

.circleci/config.yml

Added test jobs for arm64 in CircleCI.

Add test jobs for arm64 in CircleCI

---

.circleci/config.yml

'make dev' is not enough, we need to move it into PATH as well.

ci: fix arm64 build

---

.changelog/12236.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/envoy_versioning.go
agent/xds/envoy_versioning_test.go

[1.10.x] xds: allow only one outstanding delta request at a time

---

ui/packages/consul-ui/app/components/menu/README.mdx
ui/packages/consul-ui/app/components/menu/action/index.hbs
ui/packages/consul-ui/app/components/menu/index.hbs
ui/packages/consul-ui/app/components/menu/item/index.hbs
ui/packages/consul-ui/app/components/menu/separator/index.hbs

See [Rendered Docs](https://consul-ui-staging-rkj158d0b-hashicorp.vercel.app/ui/docs/components/menu)
(note the base branch here is the aria-menu modifier branch)

ui: Menu component

---

website/content/docs/enterprise/admin-partitions.mdx

This PR adds a link to another learn tutorial dedicated to admin partitions.

adding new tutorial

---

.changelog/12195.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/xds_protocol_helpers_test.go

Prevent xDS tight loop on cfg errors [1.10.x]

---

.changelog/12195.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/xds_protocol_helpers_test.go

Prevent xDS tight loop on cfg errors [1.11.x]

---

CHANGELOG.md

These are the changelog entries from the latest release.

Add release notes from 1.11.3, 1.10.8 and 1.9.15

---

.changelog/12325.txt
api/go.sum
go.mod
go.sum
sdk/go.mod
sdk/go.sum

[1.11.x] raft: update to v1.3.5

---

.changelog/12325.txt
go.mod
go.sum
vendor/github.com/hashicorp/raft/api.go
vendor/github.com/hashicorp/raft/config.go
vendor/github.com/hashicorp/raft/configuration.go
vendor/github.com/hashicorp/raft/fsm.go
vendor/github.com/hashicorp/raft/log.go
vendor/github.com/hashicorp/raft/progress.go
vendor/github.com/hashicorp/raft/raft.go
vendor/github.com/hashicorp/raft/util.go
vendor/modules.txt

[1.10.x] raft: update to v1.3.5

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/task.mdx

Some changes made by @lornasong are required for these documentation changes, ignore commits made by Lorna in this review, they are part of a [separate PR](https://github.com/hashicorp/consul/pull/12303).
[task create api preview link](https://consul-bzlloxvss-hashicorp.vercel.app/docs/nia/api/tasks#create-task)
[task create cli preview link](https://consul-bzlloxvss-hashicorp.vercel.app/docs/nia/cli/task#task-create)

Cts create api

---

website/content/docs/nia/cli/task.mdx

Updated docs with changes from CTS repo https://github.com/hashicorp/consul-terraform-sync/pull/691

update create task CLI with new changes from code

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/task.mdx

- update curl command to include the json header
- update example task names to use 'task_a' to conform with other examples
https://consul-3f6m5ndrm-hashicorp.vercel.app/docs/nia/api/tasks#create-task
https://consul-3f6m5ndrm-hashicorp.vercel.app/docs/nia/cli/task#task-create

update create task api and cli

---

website/content/docs/nia/cli/task.mdx

https://consul-pahqtavva-hashicorp.vercel.app/docs/nia/cli/task

docs/nia: Fix hyphens in CTS CLI output

---

website/content/docs/nia/cli/task.mdx

https://consul-n0e7hedny-hashicorp.vercel.app/docs/nia/cli/task

docs/nia: Add auto-approve option in CLI

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/task.mdx

https://consul-lnia88ak5-hashicorp.vercel.app/docs/nia/api/tasks#delete-task
https://consul-lnia88ak5-hashicorp.vercel.app/docs/nia/cli/task#task-delete

docs/nia: Clarify infrastructure is not destroyed on task deletion

---

agent/xds/listeners_test.go

fix reference merged in 67547c68aa778123d385aae193f00b359cd946ae

---

agent/xds/listeners_test.go

This will need to be backported slightly differently to 1.10.x
This forces the oss/ent generated xds to be identical for things in the default partition and default namespace wherever a proxycfg map key is addressed as a `ServiceName` flavored string instead of the upstream-id ones used elsewhere.
Properly fixing that would require backporting https://github.com/hashicorp/consul/pull/12125

[1.11.x] xds: fix some test assertions for enterprise

---

website/content/docs/k8s/installation/vault/index.mdx

This limitation was enabled last week with https://github.com/hashicorp/consul-k8s/pull/1020

Updating consul on k8s to remove known limitations of serverAdditionalDNSSans and serverAdditionalIPSans

---

website/content/docs/k8s/connect/index.mdx

add tproxy set to false annotation. 
`consul.hashicorp.com/transparent-proxy: false`

docs: set tproxy annotation to false for multi-port

---

.release/ci.hcl

https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing

Adding post-publish events to ci.hcl.

---

website/content/docs/enterprise/license/faq.mdx

Improvements include:
- Clarifying license expiration behavior
- Adding a license renewal Q+A
- Adding obtaining a copy of your license as an existing customer Q+A
- Clarify evaluation license changes
[Preview](https://consul-r4rx5u4zh-hashicorp.vercel.app/docs/enterprise/license/faq)
To-Do:

Enterprise license FAQ improvements

---

website/data/version.js

Update latest version on website to 1.11.4

---

CHANGELOG.md

Adds all the entries from 1.11.4, 1.10.9 and 1.9.16.

Add changelog entries from latest releases

---

CHANGELOG.md

Adds entries from 1.11.4 release.

Add changelog entries from latest release

---

website/content/docs/enterprise/admin-partitions.mdx

This PR adds verbiage pertaining to the maximum admin partitions supported.

docs: adding text for maximum number of admin partitions

---

.changelog/12400.txt
ui/packages/consul-ui/app/templates/dc/services/show.hbs

fixes: #11322 
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

ui: [Bugfix] Added Tags tab to gateways(just like exists for non-gateway services)

---

agent/rpc/middleware/interceptors.go
agent/rpc/middleware/interceptors_test.go

PR adds package level testing for the `RequestRecorder`.  Credit to @dhiaayachi for some of these ideas here!

factor out recording func, add unit tests

---

agent/consul/state/connect_ca.go
agent/consul/state/connect_ca_events.go
agent/consul/state/connect_ca_events_test.go
agent/consul/state/memdb.go
agent/consul/stream/event.go

OSS sync of enterprise changes at 614f786d

[OSS] streaming: emit events when Connect CA Roots change

---

ui/packages/consul-ui/app/components/consul/server/card/README.mdx
ui/packages/consul-ui/app/components/consul/server/card/index.hbs
ui/packages/consul-ui/app/components/consul/server/card/index.scss
ui/packages/consul-ui/app/components/consul/server/card/layout.scss
ui/packages/consul-ui/app/components/consul/server/card/skin.scss
ui/packages/consul-ui/app/components/consul/server/list/index.hbs
ui/packages/consul-ui/app/components/consul/server/list/index.scss
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/base/typography/base-keyframes.scss
ui/packages/consul-ui/app/styles/base/typography/base-variables.scss
ui/packages/consul-ui/app/styles/base/typography/index.scss
ui/packages/consul-ui/app/styles/components.scss

Please see [Rendered Docs](https://consul-ui-staging-pvhhy3usj-hashicorp.vercel.app/ui/docs/consul/server/card)
also note the base branch which this component makes use of.

ui: Consul Server Card component

---

ui/packages/consul-ui/app/components/consul/server/card/README.mdx
ui/packages/consul-ui/app/components/consul/server/card/index.hbs
ui/packages/consul-ui/app/components/consul/server/card/index.scss
ui/packages/consul-ui/app/components/consul/server/card/layout.scss
ui/packages/consul-ui/app/components/consul/server/card/skin.scss
ui/packages/consul-ui/app/components/consul/server/list/index.hbs
ui/packages/consul-ui/app/components/consul/server/list/index.scss
ui/packages/consul-ui/app/components/tile/README.mdx
ui/packages/consul-ui/app/components/tile/debug.scss
ui/packages/consul-ui/app/components/tile/index.scss
ui/packages/consul-ui/app/styles/base/component/index.scss
ui/packages/consul-ui/app/styles/base/decoration/base-variables.scss
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/base/index.scss
ui/packages/consul-ui/app/styles/base/typography/base-keyframes.scss
ui/packages/consul-ui/app/styles/base/typography/base-variables.scss
ui/packages/consul-ui/app/styles/base/typography/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/debug.scss

[Rendered Docs](https://consul-ui-staging-6g6tfo8v1-hashicorp.vercel.app/ui/docs/components/tile)
Not so much docs this time, more just "having thing in isolation" for helping review.

ui: Tile CSS component

---

.changelog/12046.txt
agent/consul/server.go
agent/consul/wanfed/wanfed.go
go.mod
go.sum
vendor/github.com/hashicorp/memberlist/config.go
vendor/github.com/hashicorp/memberlist/event_delegate.go
vendor/github.com/hashicorp/memberlist/label.go
vendor/github.com/hashicorp/memberlist/memberlist.go
vendor/github.com/hashicorp/memberlist/net.go
vendor/github.com/hashicorp/memberlist/peeked_conn.go
vendor/github.com/hashicorp/memberlist/security.go
vendor/github.com/hashicorp/memberlist/state.go
vendor/github.com/hashicorp/memberlist/transport.go
vendor/github.com/hashicorp/memberlist/util.go
vendor/modules.txt

Includes cherrypick of 6713afdff30c188542d7e2eb1f8984eefdc201a5 introduced in https://github.com/hashicorp/consul/pull/10161

[1.9.x] Update memberlist to v0.3.1

---

agent/metrics_test.go

PR adds a test that shows how to "turn off" the new rpc metrics by using prefix filtering.
You can read more about prefix filtering here: https://www.consul.io/docs/agent/options#telemetry-prefix_filter 

[metrics][rpc]: add basic prefix filter test for new rpc metric

---

.circleci/config.yml
GNUmakefile
build-support/scripts/proto-gen.sh

- also import replace isn't needed anymore

build: install mog and execute it during protobuf compilation

---

website/content/docs/api-gateway/api-gateway-usage.mdx

To mirror instructions at https://learn.hashicorp.com/tutorials/consul/kubernetes-api-gateway

website(api-gateway): add consul namespace to helm install

---

website/content/docs/k8s/helm.mdx

Update Helm docs to reflect the v0.42.0 release.

Update Helm docs to reflect 0.42.0 release

---

lib/routine/routine.go
lib/routine/routine_test.go

Fix the bug that caused acl replication to stop after a node lose-regain leadership.
The investigation is at https://github.com/hashicorp/consul/issues/12295#issuecomment-1055141588

routine: fix that acl stops replicating after regaining leadership (#12295)

---

.changelog/12565.txt

Adding a changelog entry for a community PR I just merged.

Creating a changelog entry for  #12565

---

acl/policy_merger.go
agent/delegate_mock_test.go
api/acl_test.go
command/acl/authmethod/create/authmethod_create_test.go
command/acl/authmethod/update/authmethod_update_test.go
command/connect/expose/expose_test.go
test/integration/connect/envoy/case-basic/capture.sh
test/integration/connect/envoy/case-http/capture.sh

syncing changes back from enterprise

---

.release/ci.hcl

Update branch list for 1.12, remove 1.8

---

agent/consul/client_test.go
agent/consul/options.go
agent/consul/server.go
agent/consul/server_test.go
agent/rpc/middleware/interceptors.go
agent/rpc/middleware/interceptors_test.go
agent/setup.go

This is a manual backport of https://github.com/hashicorp/consul/pull/12692

backports #12692

---

agent/discovery_chain_endpoint_test.go

fix broken test

---

agent/proxycfg/testing_terminating_gateway.go
agent/xds/serverless_plugin_oss_test.go
agent/xds/serverlessplugin/lambda_patcher.go
agent/xds/testdata/serverless_plugin/clusters/lambda-terminating-gateway-with-service-resolvers.envoy-1-20-x.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway-with-service-resolvers.envoy-1-20-x.golden
agent/xds/testdata/serverless_plugin/routes/lambda-terminating-gateway-with-service-resolvers.envoy-1-20-x.golden
agent/xds/xdscommon/xdscommon.go
agent/xds/xdscommon/xdscommon_oss_test.go

Backport of https://github.com/hashicorp/consul/pull/12773 to 1.12.x

[1.12.x] Implement routing and intentions for AWS Lambdas

---

CHANGELOG.md

Adds entries from 1.10.10 release.

add changelog from 1.10.10 release

---

CHANGELOG.md

Adds entries from 1.11.5 release.

add changelog from 1.11.5 release

---

website/data/version.js

Update latest version on website to 1.11.5

---

.changelog/12786.txt
ui/packages/consul-ui/app/components/consul/auth-method/index.scss
ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
ui/packages/consul-ui/app/components/pill/index.scss
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/auth-method.hbs
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/binding-rules.hbs
ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/nspace-rules.hbs
ui/packages/consul-ui/mock-api/v1/acl/auth-methods
ui/packages/consul-ui/package.json
ui/packages/consul-ui/translations/common/en-us.yaml
ui/yarn.lock

Adds basic support for AWS IAM Auth Methods

ui: Adds support for AWS-IAM Auth Methods

---

ui/packages/consul-ui/app/components/consul/server/list/index.scss
ui/packages/consul-ui/app/styles/routes/dc/overview/license.scss

Updated paragraph copy on overview license tab to a lighter color to align with designs. Added a hover style to the overview cards (updated box-shadow and border color).

ui:updated text color and added overview card hover states

---

website/redirects.js

This PR fixes an issue related to redirects that is breaking local builds.

docs: fixed redirect issue

---

website/content/docs/security/acl/auth-methods/aws-iam.mdx
website/content/docs/security/acl/auth-methods/index.mdx
website/data/docs-nav-data.json
website/redirects.js

This adds documentation for the new IAM auth method added to 1.12.0
Closes #12662

Docs: IAM auth method

---

ui/packages/consul-ui/app/abilities/license.js
ui/packages/consul-ui/tests/unit/abilities/-test.js

This is a backport of [#12795](https://github.com/hashicorp/consul/pull/12795).

ui: fix issue where license viewable - backport of #12795 

---

CHANGELOG.md

Update changelog for 1.12.0

---

website/content/docs/k8s/installation/compatibility.mdx
website/content/docs/k8s/installation/vault/systems-integration.mdx

Add 1.12.0 notes and also add VMware Tanzu compatibility notes.

docs: Update Consul K8s compatibility matrix

---

website/content/docs/k8s/installation/compatibility.mdx

docs: small spelling typo on consul k8s compat matrix

---

website/content/docs/k8s/annotations-and-labels.mdx

This adds documentation for:
https://github.com/hashicorp/consul-k8s/pull/1150

Add documentation for proposed kubernetes-service annotation

---

website/content/docs/k8s/annotations-and-labels.mdx

From this PR: https://github.com/hashicorp/consul-k8s/pull/1111 which was a rebase of https://github.com/hashicorp/consul-k8s/pull/763.
**NOTE:** merge after next k8s release

Document consul.hashicorp.com/connect-inject-mount-volume

---

.changelog/_12855.txt
.gitignore

Adding a changelog for an enterprise-only snapshot agent fix.
N/A

changelog: snapshot-agent acl token fix for CLI and ENV

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx
website/content/docs/api-gateway/index.mdx
website/content/docs/api-gateway/tech-specs.mdx
website/content/docs/api-gateway/upgrade-specific-versions.mdx
website/content/docs/release-notes/consul-api-gateway/v0_1_x.mdx
website/content/docs/release-notes/consul-api-gateway/v0_2_x.mdx
website/data/docs-nav-data.json

Updated product docs for the release of Consul API Gateway v0.2
Ran website locally, navigated to the new pages and to the existing pages, visually examined all pages that are being changed.

Update product docs for release of Consul API Gateway v0.2

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx

We're releasing consul-api-gateway v0.2.0 and missed updating this version in #12863 

Update version pin for consul-api-gateway install docs

---

website/content/docs/security/security-models/core.mdx

This PR fixes markdown leakage that occurred due to incorrect indentation. 

docs: fixes makdown leakage

---

website/content/docs/api-gateway/upgrade-specific-versions.mdx

Fixes the two following minor rendering issues:
https://www.consul.io/docs/api-gateway/upgrade-specific-versions

website(consul-api-gateway): fixup stray div tag and step 8 link

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx
website/content/docs/release-notes/consul-api-gateway/v0_2_x.mdx

Update some version numbers as part of the API Gateway v0.2.0 release and correcting minor Markdown issues
Ran website locally
* [] not a security concern

Docs: updated versions on install page and other minor fixes.

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx

Manual backport of #12871 since the automatic backport process didn't pick it up

Release 1.11.x #12871 backport

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx

Manual backport of https://github.com/hashicorp/consul/pull/12871 since the automatic backport process didn't pick it up

Release 1.12.x #12871 backport

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx

Manual backport of https://github.com/hashicorp/consul/pull/12871 since the automatic backport process didn't pick it up

Stable website #12871 backport

---

website/content/docs/api-gateway/consul-api-gateway-install.mdx
website/content/docs/api-gateway/upgrade-specific-versions.mdx
website/content/docs/release-notes/consul-api-gateway/v0_2_x.mdx

Updating docs for Consul API Gateway release v0.2.1
Ran the website on local machine.

Docs: update for API Gateway v0.2.1

---

agent/peering_endpoint.go

I forgot to rebase https://github.com/hashicorp/consul/pull/12594 before merging!

Cleanup peering files that used removed error types

---

website/content/docs/architecture/improving-consul-resilience.mdx
website/data/docs-nav-data.json

Discuss available strategies for improving server-level and infrastructure-level fault tolerance in Consul.

docs: add guidance on improving Consul resilience

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/enterprise/audit-logging.mdx
website/content/docs/enterprise/federation.mdx
website/content/docs/enterprise/namespaces.mdx
website/content/docs/enterprise/network-segments.mdx
website/content/docs/enterprise/read-scale.mdx
website/content/docs/enterprise/redundancy.mdx
website/content/docs/enterprise/sentinel.mdx

The docs PR #12847 was merged into `main`, but failed to merge into `stable-website` and `release/1.12.x`.
This PR cherry-picks the commits from #12847 onto `stable-website`.
```
git cherry-pick 84bf170ca3b8118f366682ae0782bf4d307dd9a2^..1bfaf7a7d9513380254df6168a9533d4da846f4f
```

Docs: Merge #12847 into stable-website

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/enterprise/audit-logging.mdx
website/content/docs/enterprise/federation.mdx
website/content/docs/enterprise/namespaces.mdx
website/content/docs/enterprise/network-segments.mdx
website/content/docs/enterprise/read-scale.mdx
website/content/docs/enterprise/redundancy.mdx
website/content/docs/enterprise/sentinel.mdx

The docs PR #12847 was merged into `main`, but failed to merge into `stable-website` and `release/1.12.x`.
This PR cherry-picks the commits from #12847 onto `release/1.12.x`.
Cherry-pick performed with command:
```
git cherry-pick 84bf170ca3b8118f366682ae0782bf4d307dd9a2^..1bfaf7a7d9513380254df6168a9533d4da846f4f
```

Docs: Merge #12847 into release/1.12.x

---

website/content/docs/connect/proxies/envoy.mdx

Add example escape hatch configurations for all supported override types.

docs: Add example Envoy escape hatch configs

---

.changelog/_1781.txt
agent/http_register.go
agent/peering_endpoint.go
agent/peering_endpoint_oss_test.go
agent/peering_endpoint_test.go
api/api_test.go
api/peering.go
api/peering_test.go

OSS sync with ENT over { be63e99c3 f1aca2618 1c549d814 }

[sync oss] api: add peering api module

---

.github/workflows/backport-assistant.yml

Fixing runs that [are failing](https://github.com/hashicorp/consul/actions/runs/2265034000) because of syntax.
N/A

chore(ci): fix backport assistant

---

website/content/docs/k8s/upgrade/compatibility.mdx

docs: 1.10.x k8s compat manual backport

---

website/content/docs/k8s/installation/compatibility.mdx

docs: 1.11.x k8s compat matrix manual backport

---

website/content/docs/k8s/upgrade/compatibility.mdx

docs: update k8s compat matrix for 1.9.x

---

website/content/docs/nia/api/health.mdx
website/content/docs/nia/api/status.mdx
website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/start.mdx
website/data/docs-nav-data.json

This PR adds documentation about the new health API endpoint being added to CTS
[Health Endpoint page](https://consul-54m4rvjgc-hashicorp.vercel.app/docs/nia/api/health)

Added CTS health endpoint docs

---

test/integration/consul-container/upgrade/healthcheck_test.go
test/integration/consul-container/upgrade/version_oss.go

Some changes are needed to sync with enterprise tests. Also fixed some inconsistent naming (Current vs Target)

sync changes to healthcheck tests

---

agent/peering_endpoint.go
agent/peering_endpoint_test.go

Came across this as a convenience when working with nitya; would be nice to have!
* updated tests

add err msg on PeeringRead not found

---

agent/consul/config_endpoint_test.go
agent/consul/state/catalog_test.go
agent/consul/stream/event_publisher_test.go
agent/grpc/private/services/subscribe/subscribe_test.go
agent/rpc/peering/testing.go
agent/rpcclient/health/view_test.go
agent/submatview/store_test.go
agent/xds/xds_protocol_helpers_test.go
api/config_entry_test.go
lib/ttlcache/eviction_test.go

Wraps up the refactor from #13013

remove remaining shim runStep functions

---

website/content/docs/upgrading/upgrade-specific.mdx

Whoops, didn't get a chance to add this before the release!

docs: add section to 1.12 upgrade notes about new TLS config style

---

website/content/docs/enterprise/admin-partitions.mdx

docs: fix versions for admin partitions 1.11.x docs

---

website/content/docs/enterprise/admin-partitions.mdx

docs: Address comments from admin partitions docs changes around networking requirements

---

website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx

docs: add enterprise image to vault license data integration example

---

website/content/docs/discovery/checks.mdx
website/content/docs/security/acl/acl-policies.mdx
website/content/docs/security/acl/acl-roles.mdx
website/content/docs/security/acl/acl-rules.mdx
website/content/docs/security/acl/acl-tokens.mdx
website/content/docs/security/acl/index.mdx
website/redirects.js

Backport of #12972 to the stable-website branch

[stable-website] docs: Backport fix JSON formatted example ACL policies

---

website/content/docs/discovery/checks.mdx
website/content/docs/security/acl/acl-policies.mdx
website/content/docs/security/acl/acl-roles.mdx
website/content/docs/security/acl/acl-rules.mdx
website/content/docs/security/acl/acl-tokens.mdx
website/content/docs/security/acl/index.mdx
website/redirects.js

Backport of #12972 to 1.12.x branch.

[1.12.x] docs: Backport fix JSON formatted example ACL policies

---

test/load/terraform/consul.tf
test/load/terraform/test-servers.tf

fix insecure cidr_blocks in load test

---

.github/workflows/oss-merge-trigger.yml

follow up to https://github.com/hashicorp/consul/pull/13072

fix yaml alignment for oss to ent merge job

---

lib/retry/retry.go

Remove unused constant in retry.go

---

website/content/docs/k8s/installation/compatibility.mdx

Updating the compatibility matrix to include consul-k8s release 0.44.0.

docs: Updating compatibility matrix for consul-k8s version 0.44.0

---

.github/workflows/oss-merge-trigger.yml

Port of https://github.com/hashicorp/consul/pull/13072 to 1.10.x

add oss merge PR creation workflow trigger

---

.github/workflows/oss-merge-trigger.yml

Port of https://github.com/hashicorp/consul/pull/13072 to 1.12.x

add oss->ent merge trigger job

---

agent/consul/server_test.go

TestServer_RPC_MetricsIntercept was intermittently panicking in CI due to concurrent access of this `storage` map.

test: TestServer_RPC_MetricsIntercept should use a concurrency-safe metrics store

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

Manual cherry pick: https://github.com/hashicorp/consul/pull/13179/files

CTIA-5 cherry pick fix endpoint returning 500

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

Manual cherry-pick https://github.com/hashicorp/consul/pull/13205

CTIA-5 cherry pick fix endpoint returning 500 (#13205)

---

.github/workflows/load-test.yml

Allow developers to manually trigger dispatch from Actions

Enable manual triggering of load test

---

command/registry.go
command/registry_oss.go
main.go

Followup to https://github.com/hashicorp/consul/pull/12729

Refactor some functions for better enterprise use

---

.circleci/config.yml

Follow up to https://github.com/hashicorp/consul/pull/10996

Fix broken CI step

---

build-support/scripts/devtools.sh

Some tools, such as `mog` are sensitive to the Go toolchain versions being used due to the use of some of the source code analysis packages it relies upon. This update ensures that we always use tools compiled with the same version of go that consul is being compiled with.
I temporarily updated my local toolchain to go 1.18.2 and got the following output:
```
$ make tools
installing tool (go toolchain upgrade): github.com/vektra/mockery/v2@v2.12.2
installing tool (go toolchain upgrade): github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
installing tool (go toolchain upgrade): github.com/bufbuild/buf/cmd/buf@v1.4.0
installing tool (go toolchain upgrade): github.com/golang/protobuf/protoc-gen-go@v1.5.0
installing tool (go toolchain upgrade): …
```

build: ensure tools match go toolchain version

---

.circleci/config.yml

chore(ci): add noop jobs for branch protections

---

CHANGELOG.md

This adds the latest changelog entries from the 1.12.2 release.

Add latest changelog entries

---

acl/enterprisemeta_oss.go
agent/structs/config_entry_intentions.go
agent/structs/intention.go
agent/structs/intention_test.go
agent/structs/structs.go
agent/structs/structs_filtering_test.go
api/config_entry_intentions.go
api/connect_intention.go

This is the first step to enabling intentions to be peer aware
* Updated existing tests
* Will raise separate PR for state store tests

Add SourcePeer fields to relevant Intentions types

---

website/content/docs/enterprise/index.mdx

As requested (and double-checked) by the HCP Consul PM
Preview: https://consul-c5e14x5il-hashicorp.vercel.app/docs/enterprise#consul-enterprise-feature-availability

docs: show HCP Consul supports CTS enterprise

---

website/content/api-docs/peering.mdx
website/data/api-docs-nav-data.json

Documentation for the endpoints to create, read, list, and delete peerings.

Add peering endpoint API docs

---

website/content/docs/lambda/invocation.mdx

Fix broken link in lambda docs

---

website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
website/content/docs/k8s/installation/vault/wan-federation.mdx
website/data/docs-nav-data.json

Consul-k8s has added the ability to have Vault act as the Certificate Provider for Controller and Connect Inject Webhooks in kubernetes.

Docs - k8s - Webhook Certs on Vault

---

website/content/docs/k8s/annotations-and-labels.mdx
website/content/docs/k8s/helm.mdx

Update the auto-genned docs and add a line for the new thread annotation for envoy.

[docs] update helm values docs and annotations

---

website/content/docs/lambda/index.mdx

docs: Lambda consul service mesh naming suggestions

---

website/content/docs/k8s/helm.mdx

Add helm value doc for peering

docs: add peering helm value

---

website/content/docs/connect/cluster-peering/create-manage-peering.mdx
website/content/docs/connect/cluster-peering/k8s.mdx
website/content/docs/connect/proxies/envoy.mdx

Backport lines from failed cherry-pick 

docs: Backport to stable-website cluster peering

---

website/content/docs/connect/cluster-peering/k8s.mdx

docs: add Core requirements to cluster peering k8s docs

---

agent/consul/watch/server_local.go
agent/consul/watch/server_local_test.go

#13438 introduced the new server local blocking query mechanism. One thing I missed porting was the index correction. When a query returns a 0 index we should translate that to a 1 instead to prevent callers from getting into hot loops where the query never blocks.
* Unit tests

Port over the index 0 -> 1 code that lived in the old rpc setQueryMeta function.

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

OSS sync at aa45b957c078665e5aa487eab839f23689c8bb9c 
---
Description
The UI will use IntentionsGetExact to GET a peer intention.

oss: peering, http: get peer service intentions (#2098)

---

website/content/docs/connect/cluster-peering/k8s.mdx

docs: cluster peering k8s - add indent to code block config tab to align with other branches

---

website/content/docs/k8s/operations/gossip-encryption-key-rotation.mdx

Backport of failed cherry pick

docs: 1.12.x backport formatting to stable-website for gossip key encryption

---

website/content/docs/k8s/operations/gossip-encryption-key-rotation.mdx

Missing formatting comparing with 1.12.x and stable-website branches

docs: add missing $ gossip key rotation exec command

---

test/integration/consul-container/libs/node/consul-container.go

For tests that stop and start or upgrade the consul container this ensures that the original networking information is preserved and likely improves the reliability of a quick serf convergence and cuts down on flakiness.
Use a synthetic pod construct to hold onto the IP address in the interim.

test: for upgrade compatibility tests retain assigned container ip addresses on upgrade

---

.changelog/13607.txt
agent/xds/serverless_plugin_oss_test.go
agent/xds/serverlessplugin/lambda_patcher.go
agent/xds/testdata/serverless_plugin/clusters/lambda-connect-proxy-opposite-meta.latest.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-connect-proxy-opposite-meta.latest.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway-with-service-resolvers.latest.golden
agent/xds/testdata/serverless_plugin/listeners/lambda-terminating-gateway.latest.golden
agent/xds/testdata/serverless_plugin/routes/lambda-connect-proxy-opposite-meta.latest.golden

Renamed the payload passthrough key from "passhthrough" to "passthrough".

Fix Payload Passthrough in the Serverless Plugin

---

ui/packages/consul-ui/mock-api/v1/peering/_
ui/packages/consul-ui/mock-api/v1/peerings

Slight update to some missing things in our peering mocks that exist in the actual API response found whilst I was checking things over.

ui: Slight update to peering mocks to more properly match actual

---

ui/packages/consul-ui/app/components/consul/peer/components.scss
ui/packages/consul-ui/app/components/consul/peer/index.scss
ui/packages/consul-ui/app/components/consul/peer/list/README.mdx
ui/packages/consul-ui/app/components/consul/peer/list/index.hbs
ui/packages/consul-ui/app/components/consul/peer/notifications/README.mdx
ui/packages/consul-ui/app/components/consul/peer/notifications/index.hbs
ui/packages/consul-ui/app/components/consul/peer/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/peer/search-bar/index.scss
ui/packages/consul-ui/app/filter/predicates/peer.js
ui/packages/consul-ui/app/helpers/require.js
ui/packages/consul-ui/app/models/peer.js
ui/packages/consul-ui/app/routes/dc/peers/index.js
ui/packages/consul-ui/app/services/data-sink/protocols/http.js
ui/packages/consul-ui/app/services/filter.js
ui/packages/consul-ui/app/services/repository/peer.js
ui/packages/consul-ui/app/sort/comparators/peer.js
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/templates/dc/peers/index.hbs
ui/packages/consul-ui/translations/components/consul/en-us.yaml

Enable deletion of peers from the 'actions menu' in each row.
Note: we are using our newer 'use less Ember Data' approach to CRUD here, and this is the first time we need to do write-like things with this approach.
This PR includes:
1. Inject our `client.request` into data-sink so we can then inject that into the methods themselves via an argument. This is exactly the same as how our data-sources work, we just hadn't had reason to do this corresponding data-sink plumbing as yet. Just a bit of FYI, this exact method signature is probably temporary until we get everything moved over, or we end up moving to something else entirely first.
2. Move the peer listing into a component. Although the peer list is currently "single use", moving it to a component means we can easily add a …

ui: Peer Deletion

---

agent/proxycfg/testing_terminating_gateway.go

Fix some breakages from auto-merged PR here: https://github.com/hashicorp/consul/pull/13740

1.12.x: Fix broken stuff from auto-merge

---

ui/packages/consul-ui/app/services/repository/peer.js

This PR adds additional API requests required for peer establishment

ui: Add additional API requests for peering establishment

---

website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
website/content/docs/k8s/installation/vault/data-integration/index.mdx
website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
website/content/docs/k8s/installation/vault/systems-integration.mdx
website/content/docs/k8s/installation/vault/wan-federation.mdx

Made changes based on Adams suggestions

---

api/catalog_test.go

This test has been flaking lately due to raft index mismatches, but given that the test doesn't need to be comparing them I'll just remove them. I suspect some invariant was updated when we added `index` table usage to the nodes data set recently.
```
=== CONT  TestAPI_CatalogNodes
catalog_test.go:39: assertions.go:261: 
Error Trace:	catalog_test.go:75
retry.go:148
retry.go:149
retry.go:103
catalog_test.go:39
Error:      	Not equal: 
expected: []*api.Node{(*api.Node)(0xc0009fa150)}
actual  : []*api.Node{(*api.Node)(0xc0009fa0e0)}
Diff:
--- Expected
+++ Actual
@@ -16,3 +16,3 @@
CreateIndex: (uint64) 0,
-  ModifyIndex: (uint64) 12,
+  ModifyIndex: (uint64) 7,
Partition: (string) ""
```

test: fix flaky test TestAPI_CatalogNodes

---

internal/tools/proto-gen-rpc-glue/main.go

Leftover feedback from https://github.com/hashicorp/consul/pull/13768 🤦🏼

fix leader annotation

---

ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/index.scss
ui/packages/consul-peerings/app/components/consul/peer/form/token/actions/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/token/fieldsets/index.hbs
ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
ui/packages/consul-ui/app/styles/components.scss

Add a 'token use' form, very similar to the last 2 PRs on peer establishment flow.

ui: Peer token use form

---

agent/grpc-external/services/peerstream/stream_resources.go

As part of the heartbeating work, I'm going to use a separate goroutine to send heartbeats. This simplifies the code vs adding the heartbeat sending to the main work loop and also follows how waypoint sends heartbeats, but it necessitates that  we add a mutex to sending because the `Send()` function isn't goroutine safe.

peering: Add send mutex to protect against concurrent sends

---

ui/packages/consul-peerings/vendor/consul-peerings/routes.js
ui/packages/consul-ui/app/models/peer.js
ui/packages/consul-ui/app/search/predicates/peer.js

Allows searching for peerings by ID

ui: Allow searching for peerings by ID

---

ui/packages/consul-peerings/app/components/consul/peer/form/index.hbs

Change initiate > establish for peering the modal tab

ui: Change initiate > establish for peering the modal tab

---

agent/consul/state/catalog_oss_test.go
agent/structs/structs.go

[SYNC] Rename peering internal to ~

---

website/content/docs/k8s/annotations-and-labels.mdx

Updates k8s annotation docs for the  options added in https://github.com/hashicorp/consul-k8s/pull/1315.

docs: Updates k8s annotation docs

---

website/content/docs/agent/index.mdx

Similar to https://cloud.hashicorp.com/docs/consul/specifications#maximum-latency we should provide latency requirements around Consul agents within a cluster. 

docs: add details around Consul latency requirements

---

website/content/docs/agent/telemetry.mdx

This is the docs PR for https://github.com/hashicorp/consul/pull/13811

docs: add peering metric doc

---

website/content/docs/agent/index.mdx

Typo and added more detail on descriptions for latency requirements. 

docs: typo for latency requirements

---

agent/grpc-external/services/peerstream/stream_resources.go
agent/grpc-external/services/peerstream/stream_test.go
agent/grpc-external/services/peerstream/stream_tracker.go

Rename receive to recv in tracker

---

website/content/docs/agent/telemetry.mdx

This PR fixes a typo I introduced during my last review.

fixed typo

---

ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
ui/packages/consul-ui/app/components/buttons/index.scss
ui/packages/consul-ui/app/styles/routes/dc/acls/index.scss

Adds first draft of Peering Establishment flow to the peer listing page

ui: Add peering establishment to the peer listing page

---

agent/acl_test.go
agent/agent_endpoint_test.go
agent/local/state.go
agent/local/state_test.go
agent/proxycfg-sources/catalog/config_source_test.go
agent/proxycfg-sources/local/sync_test.go
agent/user_event_test.go

- The AddService in the local state package is not used anywhere.
AddServiceWithChecks is place of AddService
- Test code is updated

chore: removed unused method AddService

---

website/content/docs/k8s/helm.mdx

These docs were auto-generated from the Consul-k8s Helm chart values.yaml file: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml

docs: update helm reference docs

---

website/content/docs/enterprise/license/overview.mdx

docs: update enterprise licensing description

---

.changelog/13613.txt

Adds a changelog for the collection of PRs encompassing the new Destination feature of transparent proxies.
N/A

chore: changelog for destinations

---

website/content/docs/ecs/enterprise.mdx
website/content/docs/ecs/manual/secure-configuration.mdx
website/content/docs/ecs/terraform/secure-configuration.mdx

Updating audit logging documentation to bring it inline with main.

Fix audit docs to bring inline with main

---

ui/packages/consul-ui/app/components/copyable-code/index.scss

Ensure CopyableCode copy icon/button is fully clickable

ui: Ensure CopyableCode copy icon/button is fully clickable

---

ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs

Adds backend error messaging to the peering establishment flows.

ui: Add error states/messages for peering establishment

---

.changelog/14021.txt
ui/packages/consul-ui/app/modifiers/validate.js

Ensure we dispatch validation extended state when we have it, instead of just appending to the extended state, otherwise validation errors aren't reported properly.

ui: Ensure we dispatch validation state

---

connect/proxy/config_test.go

`TestAgentConfigWatcherSidecarProxy` keeps flaking because the second config fired by the watch sometimes does not reflect the updated config. I can't reproduce this locally so I added some retries and additional assertions to see what field changes may have fired the watch.

Add retries and debugging to flaky test
