hashicorp/consul

agent/consul/auto_encrypt.go
agent/consul/client.go
agent/consul/client_test.go
agent/consul/rpc.go
agent/consul/server.go
agent/consul/server_serf.go
agent/consul/server_test.go
agent/consul/snapshot_endpoint.go
agent/consul/snapshot_endpoint_test.go
agent/consul/stats_fetcher.go
agent/consul/status_endpoint_test.go
agent/pool/pool.go
agent/router/manager.go
agent/router/manager_internal_test.go
agent/router/manager_test.go

Removes some of the cruft from agent connection pool. Best viewed by commit.

Agent connection pool cleanup

---

agent/agent_test.go
agent/checks/alias.go
agent/checks/alias_test.go
agent/checks/check.go
agent/local/state.go
agent/local/state_test.go
agent/mock/notify.go

In current implementation of Consul, check alias cannot determine if a service exists or not. Because a service without any check is semantically considered as passing, so when no healthchecks are found for an agent, the check was considered as passing.
But this make little sense as the current implementation does not make any difference between:
* a non-existing service (passing)
* a service without any check (passing as well)
In order to make it work, we have to ensure that when a check did not find any healthcheck, the service does indeed exists. If it does not, lets consider the check as failing.
It should fix https://github.com/hashicorp/consul/issues/7374

BUGFIX #7374 When a service does not exists in an alias, consider it failing

---

.github/CONTRIBUTING.md

The github labels were changed.
`label:bug` -> ` label:type/bug`
`label:enhancement` -> `label:type/enhancement`
Fixes #8019

[docs/contributing] Fixed github labels

---

agent/local/state.go

This fixes a unit test failure over in enterprise due to https://github.com/hashicorp/consul/pull/7384

Ensure that the ServiceExists helper function normalizes entmeta

---

ui-v2/app/routes/dc/intentions/create.js
ui-v2/app/services/repository/intention.js

When we filter by intention for a specific service, we get a partial response back, i.e. the result of the filter. This means that we shouldn't then reconcile the ember-data store by removing records that don't exist in the response as it's a partial response i.e. records that don't exist anymore may still exist.
We currently use a `shouldReconcile` method in order to set this, but we are likely to adopt a different approach in the future.

ui: Blocking with filtering intentions amends

---

.circleci/config.yml

This gets around some issues regarding too large plt offsets when compiling with CGO

Use linkmode=external for the arm builds

---

agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go

Make sure to mount vault backend for intermediate_pki_path on secondary
dc.

Setup intermediate_pki_path on secondary

---

website/pages/use-cases/network-middleware-automation.jsx

Recently changed Network Middleware Automation use case to Network Infrastructure Automation, adding changes to the site to reflect this.

Updating NMA use case to reflect new name

---

website/pages/docs/agent/options.mdx

The description for the `-disable-host-node-id` parameter has a misformatted link that does not appear after markdown rendering.

docs: fix a link in docs/agent/options

---

agent/catalog_endpoint.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/discovery_chain_endpoint.go
agent/health_endpoint.go
agent/prepared_query_endpoint.go
website/pages/docs/agent/options.mdx

Adds `http_config.use_cache` to disable agent caching for HTTP endpoints.

Option to disable agent cache for HTTP endpoints

---

agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_test.go
agent/consul/config_endpoint_test.go

Related to #7908 
There were a couple minor changes to account for going back this far.

Backport: 7908 to release/1.6.x

---

website/pages/docs/install/performance.mdx

Fixes #8049 issue with markdown not being rendered on /docs/install/performance.mdx.

docs: Fix rendering of markdown on performance page

---

agent/xds/routes.go
agent/xds/testdata/routes/ingress-http-multiple-services.golden
agent/xds/testdata/routes/ingress-splitter-with-resolver-redirect.golden
agent/xds/testdata/routes/ingress-with-chain-and-router.golden
agent/xds/testdata/routes/ingress-with-chain-and-splitter.golden
agent/xds/testdata/routes/ingress-with-grpc-router.golden
test/integration/connect/envoy/case-ingress-gateway-http/verify.bats
test/integration/connect/envoy/case-ingress-gateway-multiple-services/verify.bats

Previously, we did not require the 'service-name.*' host header value
when on a single http service was exposed. However, this allows a user
to get into a situation where, if they add another service to the
listener, suddenly the previous service's traffic might not be routed
correctly. Thus, we always require the Host header, even if there is
only 1 service.
In a similar vein, we keep the 'service-name.*' domain when there are
ingress hosts defined, in case a service still has traffic going over
that route.

Always require Host header values for http services

---

agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/acl.go
agent/consul/state/acl_test.go
agent/structs/acl_legacy.go
agent/structs/acl_legacy_test.go

This allows new style token replication to work for legacy tokens as well when they change.
Fixes #5606

Tokens converted from legacy ACLs get their Hash computed

---

agent/consul/fsm/snapshot_oss.go
agent/consul/state/acl.go
agent/consul/state/acl_test.go
agent/structs/acl_legacy.go
agent/structs/acl_legacy_test.go

* Fixes #5606: Tokens converted from legacy ACLs get their Hash computed
This allows new style token replication to work for legacy tokens as well when they change.

Tokens converted from legacy ACLs get their Hash computed (#8047)

---

ui-v2/app/components/consul-kind/index.hbs
ui-v2/app/components/hashicorp-consul/index.hbs
ui-v2/app/components/menu-panel/index.hbs
ui-v2/app/components/menu-panel/index.js
ui-v2/app/components/popover-menu/index.hbs
ui-v2/app/components/popover-menu/index.js
ui-v2/app/helpers/from-entries.js
ui-v2/app/styles/base/components/buttons/skin.scss
ui-v2/app/styles/base/components/menu-panel/layout.scss
ui-v2/app/styles/base/components/menu-panel/skin.scss
ui-v2/app/styles/base/components/pill/layout.scss
ui-v2/app/styles/base/components/popover-menu/index.scss
ui-v2/app/styles/base/components/popover-menu/layout.scss
ui-v2/app/styles/components/app-view/layout.scss
ui-v2/app/styles/components/index.scss
ui-v2/app/styles/components/main-header-horizontal.scss
ui-v2/app/styles/components/main-nav-horizontal.scss
ui-v2/app/styles/components/menu-panel.scss
ui-v2/app/styles/components/tooltip-panel.scss
ui-v2/app/styles/components/tooltip-panel/index.scss
ui-v2/app/styles/components/tooltip-panel/layout.scss
ui-v2/app/styles/components/tooltip-panel/skin.scss
ui-v2/app/templates/dc/services/instance.hbs
ui-v2/app/templates/dc/services/show.hbs

This PR adds 'tooltip panels' to the ConsulKind icon/pill showing explanatory text and links for documentation on each gateway.
Few things to explain here from a code perspective:
1. I went for keeping the text/copy inside the template.
2. I'm using a new `from-entries` helper here, but I would have rather used `ember-composable-helpers` version of this. Unfortunately performing an upgrade here gave dependency problems, which would have meant having to upgrade other packages, something I'd rather not do this close to a release. Post release I'd like to switch our `from-entries` out and use the one provided by ember-composable helpers, following a complete upgrade of all of our packages.
3. Ideally all of this could use popper.js now that we are using something based on that, something for …

ui: ConsulKind explanatory tooltip panels

---

agent/config_endpoint.go
command/commands_oss.go
command/connect/expose/expose.go
command/connect/expose/expose_test.go
command/intention/create/create.go
website/data/docs-navigation.js
website/pages/docs/commands/connect/expose.mdx
website/pages/docs/commands/connect/index.mdx

This PR adds a new CLI command: `consul connect expose`, which can be used to automatically configure an ingress gateway and intentions in order to expose a Connect-enabled service to consumers outside the mesh via the chosen gateway.
```shell
$ consul connect expose -service=foo -ingress-gateway=ingress -port 8888 -protocol=tcp
Successfully updated config entry for ingress service "ingress"
Successfully set up intention for "ingress" -> "foo"
```

Ingress expose CLI command

---

.golangci.yml
agent/cache-types/connect_ca_leaf_test.go
agent/catalog_endpoint_test.go
agent/consul/catalog_endpoint_test.go
agent/consul/kvs_endpoint_test.go
agent/event_endpoint_test.go
api/kv_test.go
api/lock_test.go
api/semaphore_test.go
api/watch/funcs_test.go

And handle errors in the main test goroutine.
Calling `Errorf` from a different goroutine is fine because it won't try to exit the goroutine and cause a panic. The test may continue to run for a bit, but will still result in a failure.
In one case changed the channels to pass errors, so the main goroutine can `Fatalf`. The line numbers wont be that useful, but each error should be unique.

ci: Enabled SA2002 staticcheck check

---

agent/consul/intention_endpoint.go
agent/http_decode_test.go
agent/structs/intention.go
agent/structs/intention_test.go
agent/structs/structs_filtering_test.go
api/connect_intention.go
ui-v2/app/models/intention.js
website/pages/api-docs/connect/intentions.mdx

Found using staticcheck.
`binary.Write` does not accept `int` types without a size. The error from `binary.Write` was ignored, so we never saw this error. Casting the data to uint64 produces a correct hash. 
Without this fix the new test would continue to pass if `DefaultPort` and `Precedence` changed value, because those two fields were never being added to the hash. After this change the test fails correctly if those values are changed.
I guess this would cause problems with replicating Intentions if only the port or precedence changed?

intentions: fix a bug in Intention.SetHash

---

agent/health_endpoint.go
agent/health_endpoint_test.go
agent/structs/structs.go
api/health.go
api/health_test.go

This PR adds the query parameter `?ingress` to the `/v1/health/connect/:service` endpoint. It also adds to the `api` module a new method `health.Ingress()`.
We only allow the option on the connect-enabled health endpoint, not the regular `/v1/health/service/:service` endpoint.

Add API query parameter ?ingress to allow users to find ingress gateways associated to a service

---

command/connect/expose/expose.go
command/connect/expose/expose_test.go

This PR fixes a couple test failures and a bug in enterprise around the expose command with namespaces.

Fix a CLI test failure with namespaces in enterprise

---

agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go

This allows easier demoing/testing of ingress gateways, while still
preserving the validation we have for DNSSANs
In https://github.com/hashicorp/consul/pull/7990, we defaulted to always requiring a host header, even if only 1 service is exposed, so that adding another service to the configuration would not accidentally break traffic flows. However, that then made it hard to test ingress gateways using a single service by requiring the correct `Host` header always.
With this PR, a config like so is valid:
```
Kind = "ingress-gateway"
Name = "ingress-gateway"
Listeners = [
{
Port = 80
Protocol = "http"
Services = [
{
Name = "web"
Hosts = ["*"]
}
]
}
]
```
and this allows a user to send traffic to the ingress gateway and see it reach the `web` service without having to specify a specific …

Allow users to set hosts to the wildcard specifier when TLS is disabled

---

ui-v2/package.json
ui-v2/yarn.lock

`DefaultAddr` and `DefaultPort` where removed from the intentions API both in the backend and frontend in https://github.com/hashicorp/consul/pull/7900.
This updates our API doubles to reflect this removal.

ui: Upgrade consul-api-double to use intention response w/o old fields

---

ui-v2/ember-cli-build.js
ui-v2/package.json
ui-v2/yarn.lock

This excludes any `/components/**/pageobject.js` files from our production
builds which means we can co-locate all of our component page objects
(and selectors) along with the components themselves.
Currently we don't do any of this co-location, but moving forwards we plan on moving all of our component page objects into the same folders as the components themselves.
cc @meirish as you gave me a clue on how to do this and would be good if you cast your eye over this incase as I think you've done something similar elsewhere?

ui: Exclude any component/pageobject.js files from being included

---

ui-v2/ember-cli-build.js

In https://github.com/hashicorp/consul/pull/6746 the `encoder.js` polyfill was removed. Meaning our code-editor ceased to work in browsers without TextDecoder support (old Edge versions).
This PR adds this polyfill back in again.

ui: Ensure encoder.js polyfill is available

---

ui-v2/app/components/consul-service-list/index.hbs
ui-v2/app/components/tooltip/index.hbs
ui-v2/app/styles/base/components/tooltip/layout.scss
ui-v2/app/styles/components/composite-row/index.scss
ui-v2/app/styles/components/composite-row/layout.scss
ui-v2/app/styles/components/composite-row/skin.scss
ui-v2/app/templates/dc/services/instance/proxy.hbs
ui-v2/app/templates/dc/services/show/upstreams.hbs

- Added health check icons with tooltips to the Ingress Gateway Upstreams
- Added tooltips to the health check icons in the Service List page
- Fixed up tooltips on Upstreams to only display on over of icon
- Added tooltips to  Exposed Paths
Upstreams with Health Checks:
Service List page health icon with tooltips: 
Tooltips over icons:
Exposed Paths tooltips:

Add health check icon to Ingress Upstreams and add Tooltips in additional areas

---

agent/proxycfg/state.go
agent/xds/clusters.go
agent/xds/testdata/clusters/mesh-gateway-ignore-extra-resolvers.golden
agent/xds/testdata/clusters/mesh-gateway-service-subsets.golden
agent/xds/testdata/clusters/mesh-gateway-service-timeouts.golden
agent/xds/testdata/clusters/mesh-gateway-using-federation-states.golden
agent/xds/testdata/clusters/mesh-gateway.golden
agent/xds/testdata/clusters/terminating-gateway-hostname-service-subsets.golden
agent/xds/testdata/clusters/terminating-gateway-ignore-extra-resolvers.golden
agent/xds/testdata/clusters/terminating-gateway-service-subsets.golden
agent/xds/testdata/clusters/terminating-gateway.golden

Currently when passing hostname clusters to Envoy, we set each service instance registered with Consul as an LbEndpoint for the cluster.
However, Envoy can only handle one per cluster:
`[2020-06-04 18:32:34.094][1][warning][config] [source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) dc2.internal.ddd90499-9b47-91c5-4616-c0cbf0fc358a.consul: LOGICAL_DNS clusters must have a single locality_lb_endpoint and a single lb_endpoint, server.dc2.consul: LOGICAL_DNS clusters must have a single locality_lb_endpoint and a single lb_endpoint`
Envoy is currently handling this gracefully by only picking one of the endpoints. However, we should avoid passing multiple to avoid these warning logs.
This PR:
- …

Only pass one hostname via EDS and prefer healthy ones

---

agent/agent_endpoint.go
agent/cache-types/connect_ca_leaf.go
agent/cache/cache.go
agent/cache/cache_test.go
agent/cache/testing.go
agent/cache/watch.go
agent/catalog_endpoint.go
agent/connect_auth.go
agent/discovery_chain_endpoint.go
agent/dns.go
agent/health_endpoint.go
agent/prepared_query_endpoint.go
agent/service_manager.go

Blocking queries issues will still be uncancellable (that cannot be helped until we get rid of net/rpc). However this makes it so that if calling getWithIndex (like during a cache Notify go routine) we can cancell the outer routine. Previously it would keep issuing more blocking queries until the result state actually changed.
This prevents leaking of go routines by the agents ServiceManager used for resolving a services full configuration with central config entries.
TODOS:

Make the Agent Cache more Context aware

---

lib/decode/decode.go
lib/decode/decode_test.go

Without this change only the top level []map[string]interface{} will be unpacked as a single item.
With this change any nested config will be unpacked.
Also handle []interface{} in HookWeakDecodeFromSlice.

decode: recursively unslice opaque config

---

agent/config/runtime_test.go
agent/xds/clusters.go
agent/xds/listeners.go
contributing/checklist-adding-config-fields.md

To reference decode.HookWeakDecodeFromSlice instead.
Also removes a step from the "adding config fields checklist" which is no longer necessary.

Update comments that reference PatchSliceOfMaps

---

lib/decode/decode.go
lib/decode/decode_test.go

This was causing a 'fatal error: concurrent map iteration and map write' with gateways.
CC @freddygv , @adilyse  I believe you two have more context
This was a problem with the old `lib.TranslateKeys` as well. I kept the old behaviour in #7963, but this approach (of copying the source before making modifications) seems safer, and is more consistent with mapstructure and other hooks.

decode: do not modify the source data in HookTranslateKeys

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx

In the consul documentation it says that services at ingress gateways are available at one of two locations
```
<service-name>.*
```
or
```
<service-name>.ingress.<namespace>.*
```
This doesn't seem to match wha the ingress gateway documentation says
>To enable easier service discovery, a new Consul DNS subdomain is provided, on \<service>.ingress.\<domain>.
```
<service-name>.ingress.<domain>
```
https://www.consul.io/docs/connect/ingress_gateway
Its very possible I'm misunderstanding something because I have yet to get ingress-gateways working. I am taking a guess that the documentation is wrong on the ingress-gateway.mdx page and the correct domain should be
```
<service-name>.ingress.*
```

Fix ingress dns entry

---

website/pages/docs/agent/config-entries/service-resolver.mdx
website/pages/docs/agent/config-entries/service-router.mdx
website/pages/docs/agent/config-entries/service-splitter.mdx

Switch examples from lower to CamelCase for consistency across all configuration entries. Config entries also are case insensitive, but we prefer to use camelcase for consistency.

Switching service-route, service-resolver, service-splitter examples to CamelCase

---

.circleci/scripts/cherry-picker.sh

This PR adds GitHub notifications directly to the PR when there is a cherry pick for that PR based on backport labels or docs cherry picking to stable website. Notifications will be sent in slack and posted as a comment to the for both 'success' and 'failure' but there are two modifications:
* I removed the build log from the success notification since it is redundant (and you probably wouldn't check if it succeeded anyway)
* I sorted the logic for backports such that it will process backports to newer versions first (ex: backport/1.8 before backport/1.7)
* I return 1 for failed cherry picks and 0 for successful cherry picks and add them all up to exit based on a non-zero status for failures. This will allow the loop to complete through all backports before exiting early like it used to.

Add GitHub Notifications for cherry picks

---

.circleci/config.yml

This PR splits the oss and ent ember builds to pass to the respective ember tests. I have also increased the parallelism of ember tests to 4.

split out oss and ent ember builds for testing

---

ui-v2/app/components/healthcheck-list/index.hbs
ui-v2/tests/acceptance/dc/services/instances/proxyinfo.feature

This PR adds `...attributes` to the healthcheck-info component in order for the `data-test-*` props to be passed through to the component.
The test here looks like a lot of change, but we only changed two things, then rest of the change is due to different carriage returns.
1. Change the name of the test:
```diff
-Feature: dc / services / instances / show: Proxy Info tab
+Feature: dc / services / instances / proxyinfo: Proxy Info tab
```
2. Remove `@notNamespaceable` from line 36 of the `.feature` file

ui: Add ...attributes to healthcheck-info

---

agent/consul/leader.go
agent/consul/leader_test.go

While upgrading servers to a new version, I saw that metadata of
existing servers are not upgraded, so the version and raft meta
is not up to date in catalog.
The only way to do it was to:
* update Consul server
* make it leave the cluster, then metadata is accurate
That's because the optimization to avoid updating catalog does
not take into account metadata, so no update on catalog is performed.

[BUGFIX] Ensure that metadata of Consul Service is updated

---

ui-v2/app/models/intention.js
ui-v2/package.json
ui-v2/yarn.lock

In https://github.com/hashicorp/consul/pull/7900 these fields where removed, yet the our mocks where not removed to reflect this change, therefore we also PRed https://github.com/hashicorp/consul/pull/8089 to remove these fields from our mocks.
The above changes are earmarked for a 1.9 release, although this complicates matters from a frontend perspective. Therefore we've decided to apply this change to our 1.8.x branch at which point the test will fail until we cherry-pick https://github.com/hashicorp/consul/pull/8089 onto this PR.
None of this has any effect on the app, and just makes things easier moving forwards.

ui: Remove now unused intention fields DefaultAddr and DefaultPort

---

ui-v2/app/helpers/uniq-by.js
ui-v2/app/templates/dc/intentions/edit.hbs
ui-v2/tests/acceptance/dc/intentions/filtered-select.feature

This PR adds a uniq-by helper (following `ember-composable-helpers`) and uses it to pass a unique list of services through to the intentions form to be used in the dropdowns for selecting a service.
Fixes https://github.com/hashicorp/consul/issues/8124

ui: Don't show duplicate services in the intentions form dropdown

---

ui-v2/tests/integration/components/code-editor-test.js

This is a duplicate PR of #8087 to bring it down from ui-staging to master, before removing the ui-staging branch.

ui: Change code-editor tested to use querySelectorAll (#8087)

---

.golangci.yml
agent/agent.go
agent/cache-types/catalog_datacenters_test.go
agent/cache-types/service_checks.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_test.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/server_lookup_test.go
agent/consul/state/catalog_test.go
agent/consul/state/coordinate_test.go
agent/consul/state/kvs_test.go
agent/consul/state/session_test.go
agent/metadata/server_test.go
agent/proxycfg/state.go
agent/session_endpoint_test.go
agent/util_test.go
api/agent_test.go
api/config_entry_gateways_test.go
api/config_entry_test.go
api/lock.go
api/semaphore_test.go
api/session_test.go
internal/go-sso/oidcauth/jwt.go
lib/decode/decode_test.go
tlsutil/config_test.go

And fix the 'value not used' issues.
Many of these are not bugs, but a few are tests not checking errors, and one appears to be a missed error in non-test code.
Also added the `ineffassign` linter in a second commit. `staticcheck` finds most of these errors, but `ineffassign` found one more case where a variable was being set to a value that was never used.

ci: enable SA4006 staticcheck check and add ineffassign

---

website/package-lock.json
website/package.json

This PR updates our internal `@hashicorp/nextjs-scripts` package which contains a lot of dependencies itself...mainly our markdown plugins which was causing #8128. By updating this dependency, our markdown plugins get a version boost and fix the issues outlined there.

Update @hashicorp/nextjs-scripts dep

---

agent/config/agent_limits_test.go
agent/config/builder.go
agent/config/builder_test.go
agent/config/config.go
agent/config/default.go
agent/config/flags.go
agent/config/flags_test.go
agent/config/runtime_test.go
agent/testagent.go
command/agent/agent.go
command/agent/agent_test.go
command/services/config.go
command/services/config_test.go
command/services/deregister/deregister.go
command/services/register/register.go
command/validate/validate.go

Fixes #7748 
Adds a warning when config building skips files due to their file extension.
I found that `validate` and the `services` commands were not printing any warnings. I've made them print warnings as part of this change.
I did some cleanup, in separate commits, before making the change. To reduce the scope of `Builder`, and so that the two pieces of code which can produce this warning are much closer together.
Best viewed by individual commit. There is a lot more context in each commit message.

config: warn if a config file is being skipped because of its file extension

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/connect/ingress-gateway.mdx

Clarify that a Host header is required for L7 protocols, and specify
that the default is to use the Consul DNS ingress subdomain
This comes from merging #7990 and #8083, as well as just better clarity.

Updates docs with ingress Host header changes

---

agent/consul/leader_test.go

The field had been deprecated for a while and was recently removed,
however a PR which added these tests prior to removal was merged.

Remove ACLEnforceVersion8 from tests

---

ui-v2/app/components/consul-exposed-path-list/index.hbs
ui-v2/app/components/consul-upstream-instance-list/index.hbs
ui-v2/app/components/consul-upstream-list/index.hbs
ui-v2/app/styles/components/composite-row/layout.scss
ui-v2/app/styles/components/composite-row/skin.scss

- Update Upstreams to have the copy-button to the left of the text
- Update Upstreams to use a definition List
- Update Exposed Paths to use a definition List

ui: Refactor Upstreams and Exposed Paths icons

---

.circleci/config.yml

An issue where the golang runtime would hang and loop forever

Bump golang to 1.14.4 to avoid known runtime issue

---

website/pages/api-docs/config.mdx
website/pages/api-docs/kv.mdx
website/pages/docs/agent/options.mdx
website/pages/docs/commands/operator/raft.mdx

Fixes #7385 - Document KV Delete DC
Fixes #7432 - Updates Cipher Suites
Fixes #7646 - Config Entry types
Fixes #7663 - ACL Token Reloadable Docs
Updated Reft peers documentation to remove note about future information.

Fixing multiple document updates

---

website/pages/docs/k8s/helm.mdx

Based on the new Helm support for gateways:
- Ingress gateways [consul-helm #456](https://github.com/hashicorp/consul-helm/pull/456)
- Terminating gateways [consul-helm #491](https://github.com/hashicorp/consul-helm/pull/491)

Add helm chart options for ingress and terminating gateways

---

agent/agent_test.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime_test.go

The configuration now looks like:
```hcl
auto_config {
authorization {
enabled = true
static {
// static authorizer settings
}
}
}
```
Where before it looked like:
```hcl
auto_config {
authorizer {
enabled = true
// static authorizer settings
}
}
```
In the future we could add extra settings to enable dynamically defined auth methods to be used instead of or in addition to the statically defined one in the configuration. For now this is just the necessary configuration changes to not box our selves into

Agent Auto Configuration: Change auto config authorizer to allow for future extension

---

CHANGELOG.md

Updates the CHANGELOG to be in sync with the `release/1.8.0` branch.

Update master CHANGELOG to release 1.8.0

---

agent/agent.go
agent/auto-config/auto_config.go
agent/config/builder.go
agent/config/runtime_test.go
agent/consul/auto_encrypt.go
agent/consul/auto_encrypt_test.go
agent/testagent.go
command/agent/agent.go

This PR also has a second commit to allow specifying the intro token via an environment variable.

Allow cancelling startup when performing auto-config

---

agent/auto-config/auto_config_test.go
agent/config/builder.go
agent/config/runtime_test.go

On the servers they must have a certificate.
On the clients they just have to set verify_outgoing to true to attempt TLS connections for RPCs.
Eventually we may relax these restrictions but right now all of the settings we push down (acl tokens, acl related settings, certificates, gossip key) are sensitive and shouldn’t be transmitted over an unencrypted connection. Our guides and docs should recoommend verify_server_hostname on the clients as well although it is not strictly necessary.
Another reason to do this is weird things happen when making an insecure RPC when TLS is not enabled. Basically it tries TLS anyways. We should probably fix that to make it clearer what is going on although for the time being and specifically for auto config we can just prevent enabling the feature.

Require enabling TLS to enable Auto Config

---

agent/dns.go
agent/dns_test.go

This will allow to increase cache value when DC is not valid (aka
return SOA to avoid too many consecutive requests) and will
distinguish DC being temporarily not available from DC not existing.
Implements https://github.com/hashicorp/consul/issues/8102

Returns DNS Error NSDOMAIN when DC does not exists

---

api/agent.go

Fixing issue brought up in [this Google Groups](https://groups.google.com/g/consul-tool/c/5brpAoNHuAI/m/AJ117ferBAAJ) forum - making it more clear to understand the Status integer in the AgentMember struct.

Add AgentMemberStatus const

---

ui-v2/app/adapters/role.js
ui-v2/app/adapters/token.js
ui-v2/app/components/consul-intention-form/index.hbs
ui-v2/app/components/consul-token-list/index.hbs
ui-v2/app/components/node-identity/index.hbs
ui-v2/app/components/node-identity/index.js
ui-v2/app/components/policy-form/index.hbs
ui-v2/app/components/policy-form/index.js
ui-v2/app/components/policy-form/pageobject.js
ui-v2/app/components/policy-selector/index.hbs
ui-v2/app/components/policy-selector/index.js
ui-v2/app/mixins/policy/as-many.js
ui-v2/app/models/role.js
ui-v2/app/models/token.js
ui-v2/app/styles/base/components/radio-group/layout.scss
ui-v2/app/styles/components/composite-row.scss
ui-v2/app/styles/components/form-elements.scss
ui-v2/app/templates/dc/nspaces/-form.hbs
ui-v2/tests/acceptance/dc/acls/policies/as-many/add-existing.feature
ui-v2/tests/acceptance/dc/acls/policies/as-many/add-new.feature
ui-v2/tests/acceptance/dc/acls/policies/as-many/list.feature
ui-v2/tests/acceptance/dc/acls/policies/as-many/remove.feature
ui-v2/tests/acceptance/dc/acls/tokens/clone.feature
ui-v2/tests/helpers/normalizers.js
ui-v2/yarn.lock

https://github.com/hashicorp/consul/pull/7970 adds backend support for Node Identities, which are a templated policy similar to Service Identities.
This PR adds Phase 1 frontend UI support for Node Identities:
1. Amend ember-data layer for policies to deal with NodeIdentities. This uses the same approach as with ServiceIdentities i.e. we merge and unmerge all identities with policies. All of these policies are actually 'Templated Policies', normal policies having an empty template, in other words the rules for the normal policy are 100% user defined, all other policies use a template.
2. Specifically highlight Node Identities and Service Identities in the ConsulTokenList component. 
This will be replicated in the role listing via a new ConsulRoleList component in a later PR ontop of this …

ui: Support for Node Identities

---

ui-v2/app/components/node-identity/index.hbs
ui-v2/app/components/policy-form/index.hbs
ui-v2/app/components/policy-selector/index.hbs
ui-v2/app/components/service-identity/index.hbs
ui-v2/app/templates/dc/acls/policies/-form.hbs

Policy templates for ServiceIdentities and NodeIdentities are slightly different for a namespace enabled Consul. Whilst our templates aren't actually used to save the identities (they are just for user visibility in the UI), we make sure we show the namespaced version here if you are using a namespace enabled Consul.

ui: Add namespaced versions of templated policies

---

agent/http_oss.go
agent/structs/config_entry.go
agent/structs/config_entry_test.go
api/acl.go
command/flags/http.go
website/pages/partials/http_api_namespace_options.mdx

Fixes: #8069
Previously, when users would load config entries via [agent config](https://www.consul.io/docs/agent/options.html#config_entries_bootstrap) we wouldn't accept a namespace if specified, but also would not provide an informative error.
This PR checks for namespaces in the config decode. Note that this doesn't have to be done in `TestParseConfigEntry` because enterprise users need to be able to specify a namespace when using the CLI.

Let users know namespaces are ent only in config entry decode

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx

This example shows a TLS enabled ingress config on a non-https port.
Currently, that means we require the port to be specified in one of the
host entries to route traffic.
Pulled from https://github.com/hashicorp/consul/pull/8062#issuecomment-647120323.

docs: Specify port in host for ingress example

---

.circleci/scripts/cherry-picker.sh

While `set -e` is usually encouraged for scripts, this script should try looping through all backports and collects all the errors (`return 1`s) before failing at the end if `backport_failures != 0`. Previously, it short circuited and failed on the first backport failure. Additionally I changed the C style arithmetic expansion with `+=` to the more traditional bash style. The `(( ))` didn't expand `$?` before calculating.

remove set -e for cherry-pick script since we collect errors

---

website/pages/docs/internals/consensus.mdx

[Add & Remove Servers](https://learn.hashicorp.com/consul/day-2-operations/servers) guide uses `(N/2)+1` quorum formula.  So does the [Raft implementation](https://github.com/hashicorp/raft/blob/5927dcda05104774d2e6bbcda1d0a93c34384f9a/raft.go#L909).
Consensus Protocol document uses `(n+1)/2` formula.  This formula is not only different, it also conflicts with the [Deployment Table](https://www.consul.io/docs/internals/consensus.html#deployment_table) presented in the same document; e.g., (6+1)/2 = 3, not 4.
Replace `(n+1)/2` with `(N/2)+1` in Consensus Protocol document.

Fix quorum formula in consensus.mdx

---

website/pages/docs/connect/dev.mdx

Remove ref to "virtual service" to avoid confusion with L7 routing virtual services, replace with "debug service".

Update "debug service" reference in dev.mdx

---

agent/http.go

Since err is already checked, it should return `nil`.

agent-http: cleanup: return nil instead of err

---

ui-v2/app/components/consul-service-instance-list/index.hbs
ui-v2/app/components/consul-service-list/index.hbs
ui-v2/app/components/tag-list/index.hbs
ui-v2/app/styles/base/components/pill/layout.scss
ui-v2/app/styles/components/composite-row/layout.scss
ui-v2/app/styles/components/composite-row/skin.scss
ui-v2/app/styles/components/pill.scss
ui-v2/app/styles/components/tag-list/layout.scss

- Refactored the composite rows in Service List page and added tooltips 
- Refactored the composite rows in Service Detail List page and added tooltips

ui: Refactor composite rows to use description lists and add Tooltips

---

agent/agent.go
command/agent/agent.go

We were unconditionally configuring the metrics sinks before, even for tests. Now this requires that an option be set for the system to be initialized (which starts some go routines)

Don’t leak metrics go routines in tests

---

ui-v2/app/styles/components/tooltip-panel/layout.scss

ui: Ensure the tooltip panel chevron isn't hidden by overflow

---

agent/dns.go
agent/dns_oss.go
agent/dns_test.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

**Note**: This will break the ingress gateway UI in `1.8.0-beta1`, will need to coordinate updates their as well. cc @kaxcode 
Previously, we were only returning a single ListenerPort for a single
service. However, we actually allow a single service to be serviced over
multiple ports, as well as allow users to define what hostnames they
expect their services to be contacted over.
To show this in the UI, we modify the gateway-services-nodes API to
return a `GatewayConfig.Addresses` field instead of a `GatewayConfig.ListenerPort` field, which is a list of addresses over which the specific service can be contacted.
```
curl -s -H"X-Consul-Token: $CONSUL_HTTP_TOKEN" $CONSUL_HTTP_ADDR/v1/internal/ui/gateway-services-nodes/ingress1 | jq .
[
{
"Name": "counting",
"Tags": null,
"Nodes": [ …
```

Update gateway-services-nodes API endpoint to allow multiple addresses

---

.golangci.yml
agent/acl_endpoint.go
agent/agent.go
agent/agent_endpoint.go
agent/agent_test.go
agent/connect/ca/provider_consul.go
agent/consul/authmethod/kubeauth/testing.go
agent/consul/intention_endpoint.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/dns.go
agent/dns_test.go
agent/http_decode_test.go
agent/pool/pool.go
agent/proxycfg/manager_test.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/endpoints.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/routes.go
agent/xds/server_test.go
lib/telemetry.go

There are a few linters that detect unused code (`deadcode`, `unused`, `unparam`, `structcheck`, `varcheck`). I noticed a few unused function parameters, so I thought I would start with `unparam`.
A lot of exclude rules were added to keep this diff small. We can address each independently.

lint: add unparam linter and fix some of the issues

---

agent/structs/config_entry.go
agent/structs/config_entry_oss.go
agent/structs/config_entry_oss_test.go
agent/structs/config_entry_test.go

The previous PR to validate unused keys in agent config entry bootstrapping did not have split OSS/ENT implementations.
This is needed because we don't want to return an error if namespaces are provided in enterprise.
This PR pulls that validation into files guarded by build tags.

Split up unused key validation for oss/ent

---

agent/auto-config/auto_config.go
agent/auto-config/config_translate.go
agent/auto-config/config_translate_test.go

This fixes some issues around spurious warnings about using enterprise configuration in OSS.
While I am incredibly unsatisfied with how this turned out, it would take **huge** changes to our config to do it better. If we were willing to do that then it would be better to unify the config structure of the protobuf encoded configuration sent for auto-config with the agent config.
See the doc comment for the `translateConfig` function for all the intricate details.

Overhaul the auto-config translation

---

api/agent.go
website/pages/api-docs/agent/check.mdx

api/agent: enable setting SuccessBeforePassing and FailuresBeforeCritical in API
Fixes #7764
Needed by https://github.com/hashicorp/nomad/issues/6913
Until now these two fields could only be set through on-disk agent configuration.
This change adds the fields to the agent API struct definition so that they can
be set using the agent HTTP API.

api/agent: enable setting check thresholds in agent API

---

ui-v2/app/components/healthcheck-list/index.hbs

We'd assumed that TTL check outputs shouldn't be shown as it seemed like
they never had outputs, but they can be submitted with notes, which are
then converted into the output.
This unhides the output for TTLs and treats them exactly the same as
other healthchecks.
This reverts a change originally made in #6575
Fixes https://github.com/hashicorp/consul/issues/8161

ui: Don't hide TTL check output

---

command/config/delete/config_delete.go
command/config/delete/config_delete_test.go
command/config/read/config_read.go
command/config/write/config_write.go
command/config/write/config_write_test.go

This helps users feel like an action occurred, rather than no output leading them to wonder if it worked or not.
This also converts the formatting output of config entries from `"proxy-defaults" / "global"` to `proxy-defaults/global` as a slightly more readable form.

cli: Output message on success writing config entry

---

ui-v2/app/services/repository/discovery-chain.js

Currently we can only tell if connect is disabled on a datacenter by detecting a 500 error from a connect related endpoint.
In https://github.com/hashicorp/consul/pull/8065 we attempted to reduce the amount of times that the UI requests the discovery chain endpoint when connect is disabled on a datacenter.
In the above PR (present in Consul 1.8.0) we mistakenly `return`ed from a catch instead of rethrowing the error, which meant that when a `500` error was caught, the discovery chain data would be removed. Whilst at first glance this doesn't seem like a big problem due to the endpoint erroring, but we also receive a `0` status errors when we abort endpoints during blocking queries. This means that in certain cases we can replace cached data for the discovery chain with `undefined` which …

ui: Ensure routing tab is always shown when connect enabled

---

agent/consul/prepared_query_endpoint.go
agent/consul/prepared_query_endpoint_test.go
agent/dns.go
agent/dns_test.go
agent/prepared_query_endpoint.go
agent/structs/errors.go

Recently we found an issue when a DNS query sent to Consul for a non-existent domain makes client agent to keep querying servers indefinitely for that domain, when DNS cache is enabled, i.e. `dns_config.use_cache` is set to `true`. We were able to reproduce the issue locally with the most recent versions (1.7.4, 1.8.0):
```
2020-07-01T02:00:49.159+0100 [WARN]  agent.server.rpc: RPC request for DC is currently failing as no path was found: datacenter=locxx method=Health.ServiceNodes
2020-07-01T02:00:49.159+0100 [ERROR] agent.client: RPC failed to server: method=Health.ServiceNodes server=127.0.0.103:8310 error="rpc error making call: No path to datacenter"
...
```
In addition to be an annoying bug, this is also a DDoS vector allowing to quickly exhaust memory on all Consul servers in the …

Consul not returning NXDOMAIN for DNS queries to a non-existent datacenter

---

agent/agent.go
agent/agent_test.go
agent/cache-types/connect_ca_leaf.go
agent/consul/auto_encrypt.go
agent/consul/auto_encrypt_test.go
agent/consul/connect_ca_endpoint.go
agent/consul/server.go
agent/consul/server_connect.go
tlsutil/config.go
tlsutil/config_test.go

* Ensure that the original auto encrypt CSR contains the DNS and IP SANs from the configuration
* Initialize State of the agent leaf cert cache fetch result to prevent always issuing a second certificate signing RPC to the servers
* Move the connect CA signing rate limiter to the Server so that it can be shared with auto-encrypt and the main certificate signing RPC endpoints.
* Overwrite the agent leaf certificate trust domain on the servers. This ensures that the first certificate sent back is "correct" and has the correct trust domain instead of the dummy one.
* Fixed a bug where Consul would segfault if no client TLS certificate was available when initiating a connection.

Fix a handful of auto encrypt issues

---

website/pages/docs/connect/proxies/built-in.mdx

Fix markdown formatting and display issues on built-in proxy page.

docs: Fix formatting issues on built-in proxy page

---

agent/agent.go
go.mod
go.sum
vendor/github.com/hashicorp/go-connlimit/README.md
vendor/github.com/hashicorp/go-connlimit/connlimit.go
vendor/modules.txt

This implementation is basic and returns HTTP 429 when too many connections are done as explained in #7527, and will:
* let SDKs or other applications to self regulate when Consul refuses connections
* operators to diagnose easily issues
In my experience, this is one of the biggest source of questions since the introduction of the feature in Consul 1.6.x
This implementation is simple as it uses the default implementation from https://github.com/hashicorp/go-connlimit/pull/6, I made a proof of concept to handle it differently to avoid closing the connection in the main thread as quickly demonstrated here: https://github.com/pierresouchay/consul/commit/8399df9
I am not sure it deserves such complexity, however, but if you want to another implementation, it is still possible.

Upgrade go-connlimit to v0.3.0 / return http 429 on too many connections

---

agent/consul/catalog_endpoint.go
agent/consul/catalog_endpoint_test.go
agent/structs/structs.go

Related to #7968 (#7974, #7995).
A query made with `AllowNotModifiedResponse` and a `MinIndex`, where the result has the same `Index` as `MinIndex`, will return an empty response with `QueryMeta.NotModified` set to true.
This PR adds support to only 2 RPC endpoints to focus the review and discussion on the naming and server side implementation. If this looks good next steps (in follow up PRs) would be: add the same support to other endpoints, set `AllowNotModifiedResponse` when RPC calls are made from the client cache, and finally figure out how to expose this parameter from the HTTP API.

agent/consul: Add support for NotModified to two endpoints

---

website/package-lock.json
website/package.json
website/scripts/index_search_content.js

This PR alters the Algolia script that runs on CI. Previously we were indexing the entirety of the `.mdx` file's contents which resulted in conditional errors <sup>[1](#one)</sup> <sup>[2](#two)</sup>. With this change, we are removing that search dimension and only indexing `page_title`, `description`, and any h1, and h2 headings
<a name="one">1</a>: https://app.circleci.com/pipelines/github/hashicorp/consul/10750/workflows/1af7ff3e-339f-4e7d-a20e-344d3bf9c7b8/jobs/200845
<a name="two">2</a>:
```
ApiError Record at the position 246 objectID=docs/internals/jepsen is too big size=145566 bytes. Contact us if you need an extended quota
```

Update Algolia CI script

---

website/_redirects

Consul 1.8.0 includes a few gateway URLs that need to be handled via redirects. This PR appends 3 new routes.
----
@jescalan do you something like:
```
/*.html       /:splat     301!
```
is a more appropriate catch-all redirect as it doesn't look like we support the `.html` extension anymore?

Append redirects

---

ui-v2/app/components/consul-kind/index.hbs
ui-v2/app/templates/dc/services/show/services.hbs
ui-v2/app/templates/dc/services/show/upstreams.hbs

PRs #7610 and #7962 changed the locations/URLs for the gateway docs which results in a HTTP 404 Not Found being returned when accessing the previous URLs.
Update URLs for gateway docs to point to new URLs.
PR #8243 adds corresponding redirects on consul.io.

Update URLs for gateway docs

---

website/pages/docs/connect/intentions.mdx

/docs/connect/intentions has a broken link presumably meant
to go to /api-docs/agent/connect#authorize
This PR fixes the link.

docs: fix link to connect authorize endpoint

---

agent/xds/routes.go
agent/xds/routes_test.go
agent/xds/testdata/routes/ingress-http-multiple-services.golden
agent/xds/testdata/routes/ingress-splitter-with-resolver-redirect.golden
agent/xds/testdata/routes/ingress-with-chain-and-router.golden
agent/xds/testdata/routes/ingress-with-chain-and-splitter.golden
agent/xds/testdata/routes/ingress-with-grpc-router.golden
test/integration/connect/envoy/case-ingress-gateway-tls/config_entries.hcl
test/integration/connect/envoy/case-ingress-gateway-tls/verify.bats
test/integration/connect/envoy/main_test.go

A port can be sent in the Host header as defined in the HTTP RFC, so we
take any hosts that we want to match traffic to and also add another
host with the listener port added.
Also fix an issue with envoy integration tests not running the
case-ingress-gateway-tls test.
This fixes issues seen in https://github.com/hashicorp/consul/issues/8045. Also, see envoy issue https://github.com/envoyproxy/envoy/issues/886 for more context.
This seems like a good improvement/fix to backport to `1.8.1` as well, any other thoughts on that welcome.

Append port number to ingress host domain

---

ui-v2/app/styles/components/discovery-chain/skin.scss
ui-v2/app/styles/components/pill.scss

ui: Re-adds gray backgrounds to old style %pills

---

sdk/testutil/server.go

This PR proposes to switch from `/v1/agent/self` to `/v1/status/leader` when checking if the test server has come up successfully in the `waitForAPI` function:
https://github.com/hashicorp/consul/blob/833211c14cfecd64e36ab238ca943ceb97acee37/sdk/testutil/server.go#L372-L401
Previously, the test server was relying (probably not intentionally) on the default value of the `acl_enforce_version_8` in the TestConfig, which was `false`. So if you create a test server and enabled ACLs, they would not be enforced and the server would be able to come up pretty quickly because `/v1/agent/self` would return a `200` status pretty much as soon as the agent is running and most likely before leader election is finished.
Now that we have removed `acl_enforce_version_8` property (equivalent to being true …

sdk: Use /v1/status/leader endpoint when starting a test server

---

website/pages/docs/agent/options.mdx

Closes #7073
This was confusing because we linked to the API docs for caching, where the HTTP header behaves differently.
The zero value meaning "no max age" seems correct. I suspect the only reason we handled this differently in the HTTP header was to comply with the spec for those headers.

docs: Document that dns_config.cache_max_age=0 means "no max age"

---

website/scripts/link-check.sh

Cherry-pick #7676 into the release/1.7.x branch

[1.7.x] netlify CLI outputs "Website Draft URL" now instead of "Live Draft URL"

---

ui-v2/app/styles/components/tag-list/layout.scss

ui: Fix up styling for the Tags tab

---

ui-v2/app/components/aria-menu/index.js
ui-v2/app/components/popover-select/index.hbs

We temporarily disabled keyboard access for the sort dropdown menus in order to move forwards with a feature, but never came back to investigate the problem and re-enable.
This re-enables keyboard access for the sorting menus.

ui: Enable keyboard access for the sorting dropdown menus

---

ui-v2/app/components/popover-menu/index.hbs
ui-v2/app/components/popover-select/pageobject.js
ui-v2/app/components/popover-sort/pageobject.js
ui-v2/app/styles/base/components/popover-menu/index.scss
ui-v2/app/styles/base/components/popover-menu/layout.scss
ui-v2/app/styles/base/components/popover-menu/skin.scss
ui-v2/app/styles/base/reset/system.scss
ui-v2/app/styles/components/empty-state/index.scss
ui-v2/app/styles/components/main-header-horizontal.scss
ui-v2/app/styles/components/main-nav-horizontal.scss
ui-v2/app/styles/components/main-nav-horizontal/index.scss
ui-v2/app/styles/components/main-nav-horizontal/layout.scss
ui-v2/app/styles/components/main-nav-horizontal/skin.scss
ui-v2/app/styles/components/more-popover-menu.scss
ui-v2/app/styles/components/popover-select.scss
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/services/index.js

Our popover-menu component grew out of a mix of the dropdown menus in the main navigation (datacenters, then nspaces, help and logout), and our 'action' dropdowns in out listing rows.
We've begun to use this component and the components it is composed of much much more, and is pretty much the only component we use in the UI that has any major user interaction (the rest being renderless or glorified partials).
Upcoming work will be building on this component more, so we've refactored the component slightly (by giving it a wrapping `div` so it no longer relies on its parent using `%with-popover-menu`) and removed any rules that were essential for it from the main navigation.
In doing this we've moved some code around in the main-navigation CSS just so its ordered nicer, named nicer …

ui: Extract and organize popover-menu and related from main-nav

---

agent/agentpb/auto_config.pb.go
agent/agentpb/auto_config.proto
agent/auto-config/auto_config.go
agent/auto-config/auto_config_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/auto_config_endpoint.go
agent/consul/auto_config_endpoint_test.go
agent/consul/auto_encrypt_endpoint.go
agent/consul/catalog_endpoint.go
agent/consul/config_endpoint.go
agent/consul/connect_ca_endpoint.go
agent/consul/coordinate_endpoint.go
agent/consul/discovery_chain_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/gateway_locator.go
agent/consul/health_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/kvs_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/rpc.go
agent/consul/server.go
agent/consul/server_test.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint.go
agent/pool/pool.go

This PR does a couple things.
The first commit does:
1. Renames `Cluster.AutoConfig` RPC to `AutoConfig.InitialConfiguration`. This change includes updating the client side code to use the correct name.
2. Updates the `AutoConfig` RPC endpoint struct to take in an interface object that has methods to provide all the data it needs. Some logic (creating ACL tokens & generating a list of join addresses) was moved out of the RPC endpoint and into methods on the `Server` type itself. This simplifies the RPC endpoint quite a bit but also allows testing with fewer full test servers and utilizing more mocks. Utilizing the mocks to inject certain data also allows the tests to be simpler as much of the previous non-determinism that was in auto generated IDs and times has moved to being a function …

Agent Auto Configuration: Refactor RPC endpoint to use interface delegate

---

agent/agentpb/auto_config.pb.go
agent/agentpb/auto_config.proto
agent/auto-config/auto_config.go
agent/auto-config/auto_config_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/auto_config_endpoint.go
agent/consul/auto_config_endpoint_test.go
agent/consul/auto_encrypt_endpoint.go
agent/consul/catalog_endpoint.go
agent/consul/config_endpoint.go
agent/consul/connect_ca_endpoint.go
agent/consul/coordinate_endpoint.go
agent/consul/discovery_chain_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/gateway_locator.go
agent/consul/health_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/kvs_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/rpc.go
agent/consul/server.go
agent/consul/server_test.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint.go
agent/pool/pool.go

There was one conflict in agent/pool/pool.go where we had removed the unused `nodeName` param to `rpcInsecure`. So I just put the param back for the backport. No other modifications were necessary.

Backport of #8253

---

.circleci/config.yml

This jsonfile can be downloaded from CircleCI artifacts and used to find slow tests, or produce metrics to find flaky tests.
It can also help debug test failures until the go toolchain fix for parallel tests lands in go1.14.5 and go1.15.

ci: Store a jsonfile for go-test and go-test-api

---

agent/acl.go
agent/acl_endpoint.go
agent/acl_test.go
agent/agent.go
agent/consul/acl.go
agent/consul/acl_client.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/acl_server.go
agent/consul/acl_test.go
agent/consul/acl_token_exp.go
agent/consul/client.go
agent/consul/leader.go
agent/consul/server.go
agent/http.go

In all cases (oss/ent, client/server) this method was returning a value from config. Since the value is consistent, it doesn't need to be part of the delegate interface.

Remove ACLsEnabled from delegate interface

---

agent/agent.go
agent/agent_endpoint_test.go
agent/http.go
agent/http_oss_test.go
agent/http_test.go
agent/testagent.go
agent/ui_endpoint_test.go

While working on #6677 I hit a number of problems with the structure of the `agent.Agent` that will require some refactoring. To keep these changes small and easy to review I am splitting out a few of them ahead of the fix for that issue.
The embedded `http.Server` struct is not used by the large `HTTPServer` struct. It is used by tests and the agent. This change is a small first step in the process of removing that field.
The eventual goal is to reduce the scope of HTTPServer making it easier to test, and split into separate packages.

agent/http: un-embed the http.Server

---

acl/acl.go

Just a small typo in acl package docstring :)

Small typo in docstring

---

ui-v2/package.json

Following on from https://github.com/hashicorp/consul/pull/8276

ui: Lint staged no longer requires git add to be specified

---

ui-v2/app/templates/dc/nodes/show/rtt.hbs

We changed our default definition list layout in https://github.com/hashicorp/consul/pull/8117.
We replaced the default with a definition-table class but missed one place where the old default was previously used.
This adds the definition-table class in RTT where it used to use the default.
Before:
After:

ui: Adds definition-table class to RTT values table

---

command/commands_oss.go
command/version/formatter.go
command/version/formatter_test.go
command/version/testdata/json.golden
command/version/testdata/pretty.golden
command/version/version.go
command/version/version_test.go
main.go
website/pages/docs/commands/version.mdx

The formatters style was taken from similar code for the ACL CLI.

Add Revision to version CLI output and add JSON support

---

command/commands_oss.go
command/version/formatter.go
command/version/formatter_test.go
command/version/testdata/json.golden
command/version/testdata/pretty.golden
command/version/version.go
command/version/version_test.go
main.go
website/pages/docs/commands/version.mdx

This backports the version cli command output changes from #8268 
There was one conflict in the website file for the version command. Otherwise everything applied cleanly.

Backport: #8268

---

ui-v2/package.json
ui-v2/yarn.lock

In https://github.com/hashicorp/consul/pull/8276 we upgraded `ember-composable-helpers` partly for routine upgrade/maintenance and party to make use of its `from-entries` helper instead of using our own.
We've since noticed that `sort-by` now seems to be a lot slower, and this seems to be due to a switch to a custom BubbleSort implementation from version 4.0.0 to version 4.1.0.
For the moment we are reverting our dependency to 4.0.0 which seems to function at the same speed as before whilst we look into this further incase its due to something in our codebase that we've not noticed/considered.

ui: Revert ember-composable-helpers to ~4.0.0 due to faster sort-by

---

website/pages/api-docs/catalog.mdx
website/pages/api-docs/health.mdx

Adds API documentation for `/health/ingress/:service`.

docs: add section for /health/ingress/:service API

---

agent/catalog_endpoint_test.go
api/catalog.go
api/catalog_test.go

Follow-up of: #8099
This endpoint was primarily exposed for 3rd party integrations, so it should be accessible via the API module.

Add api mod support for /catalog/gateway-services

---

ui-v2/app/components/hashicorp-consul/index.hbs
ui-v2/app/services/repository/dc.js
ui-v2/app/services/repository/node.js
ui-v2/tests/integration/services/repository/dc-test.js

Whenever we request a list of datacenters we sort them in the model layer, whereas the reason for sorting them is a design/visual thing. Therefore this moves the sorting to the view/template.
We also spotted some dead code in the node repository, so we removed that whilst we were here.

ui: Move dc sorting to the view/template

---

ui-v2/app/adapters/acl.js
ui-v2/app/adapters/application.js
ui-v2/app/adapters/node.js
ui-v2/app/adapters/nspace.js
ui-v2/app/adapters/oidc-provider.js
ui-v2/app/adapters/token.js

`rpc` is used to define how to make a HTTP request/response messages.
This used to be called 'request' but the term is overused  and sounded
like only one 'leg' of the HTTP message, so the naming was moved to `rpc` a
while ago, this cleans up the places where we still used the old term.

ui: Replaces old request method with rpc.

---

agent/consul/catalog_endpoint.go

The token can encode enterprise metadata information, and we must make
sure we set that on the reply so that we can correct filter ACLs.
This syncs up OSS with enterprise changes needed when merging https://github.com/hashicorp/consul/pull/8215 into enterprise.

Set enterprise metadata after resolving the token

---

ui-v2/app/routes/dc/nodes/show.js
ui-v2/app/templates/dc/nodes/show.hbs

There's no point trying to load the sessions and coordinate data for a node if it doesn't exist.
https://github.com/hashicorp/consul/pull/7953
> The only downside here is that you must remember to add an EventSource component in order to clean up properly (previously the mixin would automatically detect whether a property was an EventSource that needed cleaning up. Longer term everything should really have some sort of error catching anyway, plus the benefit of being able to remove the mixin and all of the other custom code here is worth the small inconvenience.
This PR also ensures that sessions and coordinate blocking queries are closed when we leave the page 😿

ui: Only try and load sessions and coordinates if the node exists

---

.circleci/bash_env.sh
GNUmakefile
build-support/functions/10-util.sh
build-support/functions/20-build.sh
version/version.go

#8268 introduced a `Revision` line in `consul version` that outputs the ref that is currently built. For production builds, this didn't have a huge impact besides adding the extra line. However, for dev builds, we previous had:
```
$ make dev 
$ ./pkg/bin/darwin_amd64/consul version
Consul v1.7.0-124-g5f9029c65-dev (5f9029c65+CHANGES)
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
This PR changes this to:
```
$ make dev
$./pkg/bin/darwin_amd64/consul version
Consul 1.8.0-dev
Revision 41dab50e8+CHANGES
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
Most notably, the revision is no longer in parentheses in the version line …

remove GIT_DESCRIBE variable since we have a revision line

---

version/version.go

Bumping the version in the `master` branch to 1.9.0 to track the next release version. This is important for Cloud nightly integration environments. 
I am skipping CI on this commit because I think it is trivial enough to not spend any cycles running tests.

[skip ci] bump master to 1.9.0 to track next release version

---

.circleci/bash_env.sh

I mistakenly removed the ending quote when I was removing the GITDESCRIBE.

add back missing quote in bashenv for CI

---

agent/config/runtime.go

In runtime.go it had "duration" but it is actually a boolean.

minor: fix docstring of DNSOnlyPassing

---

ui-v2/app/services/repository/discovery-chain.js

In https://github.com/hashicorp/consul/pull/8065 we added a feature to disable further attempts to use API endpoints that are only enabled when connect is enabled in order to reduce HTTP log spam from the UI.
This PR improves this by making sure this error string checking works cross datacenter:
Error messages:
Same datacenter: `Connect must be enabled in order to use this endpoint`
Cross datacenter: `rpc error making call: Connect must be enabled in order to use this endpoint`

ui: Better error message checking for cross dc connect check

---

agent/consul/state/acl.go
agent/consul/state/acl_events_test.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_oss.go
agent/consul/state/connect_ca.go
agent/consul/state/federation_state.go
agent/consul/state/intention.go
agent/consul/state/intention_oss.go
agent/consul/state/kvs.go
agent/consul/state/kvs_oss.go
agent/consul/state/prepared_query.go
agent/consul/state/session.go
agent/consul/state/session_oss.go
agent/consul/state/txn.go

Changing these methods into functions allows them to be used without introducing an artificial dependency on the struct. Many of these will be called from streaming event processors, which do not have a store.
This change is being made ahead of the streaming work to reduce the size of the streaming diff.
Related to https://github.com/hashicorp/consul/pull/8160#discussion_r451511780
The first commit was done manually. The second commit was mostly automated, details in the commit message.

state: convert methods that don't use their receiver to functions

---

website/pages/docs/agent/kv.mdx

The sizing recommendation link should point to the config option for tuning kv_max_value_size.

docs: Fix link to kv_max_value_size config option

---

ui-v2/app/components/more-popover-menu/action/index.hbs
ui-v2/app/components/more-popover-menu/index.hbs
ui-v2/app/templates/dc/kv/index.hbs
ui-v2/app/templates/dc/nspaces/index.hbs

During https://github.com/hashicorp/consul/pull/8219 we noticed we were completely destroying and re-inserting our top-level `AppView` component / `outlet` everytime the app went through its loading state. We switched this out for a CSS based hide/show approach. 
This means that ember can reuse more DOM nodes, but as a consequence we noticed the menus within our dom recycling scrollpane would 'hang around' as they are now being reused.
This PR specifically closes these menus when the 'action' is clicked, which also closes the menu back to its initial state ready for reuse.
We noticed that this problem doesn't occur in Intentions which use our new Intention components.
Before:
After:

ui: Fix sticky action popover menus

---

.circleci/config.yml

I tried `-race` on all the packages ([example](https://circleci.com/gh/hashicorp/consul/204265)) but there were many failures. I expect it to add a lot of time to CI, but it actually ran in pretty reasonable time.
Since there were over 100 failures, I'm hoping we can get this enabled on a smaller number of packages with a few fixes and opt more in over time.
`-race` also enables `-d=checkptr` ([ref](https://golang.org/doc/go1.14#compiler)), which fails in the boltdb package. It looks like this was still an issue with bbolt until very recently (https://github.com/etcd-io/bbolt/issues/187, https://github.com/etcd-io/bbolt/pull/201). So for now that check is disabled.
There are still a bunch of failures in the smaller list of packages. I need to look over those failures to see if we should …

ci: add 'go test -race'

---

.circleci/config.yml

Includes the security patches from go14.5 and https://github.com/golang/go/issues/39308 to fix our test logs.

ci: Use go1.14.6

---

agent/cache-types/catalog_list_services.go
agent/cache-types/catalog_list_services_test.go
agent/cache/cache.go
agent/cache/type.go

Related to #7968, follow up to #8215
If there is a previous result then we enable `AllowNotModifiedResponse` to avoid re-serializing the result if it has not changed. The blocking query will not response if there is no change, unless the `RefreshTimeout` is hit, so this will only skip serializing a `NotModified` result once every 10 minutes. This is probably only an improvement on very large clusters.

agent/cache: Use AllowNotModified in CatalogListServices

---

website/pages/docs/install/performance.mdx

`raft_multiplier` defaults to `5`, but when I was reading through the [Server Performance docs](https://www.consul.io/docs/install/performance.html) for the first time it seemed like the default setting for `raft_multiplier` was actually what would be `1` due to this bit:
After reading the [`raft_multiplier` docs](https://www.consul.io/docs/agent/options#raft_multiplier), it was clear that this was not the case and the chart was referring to the default values for those settings individually and not `raft_multiplier`. This PR updates some of the verbiage to clarify this a bit further.

docs: Add raft_multiplier default clarification

---

ui-v2/app/styles/base/components/table/layout.scss

Set overflow to hidden for both x and y axis. This prevents the overflow-y defaulting to auto, and creating scrollbars. Given the text overflow is set to ellipsis, this doesn't change the UI functionality.

Issue #8294 - Table element's have vertical scrollbars

---

agent/checks/alias.go
agent/checks/check.go

Fixes https://github.com/hashicorp/consul/issues/8329#issuecomment-661245463
CheckAlias already had a WaitGroup, but the Add() call was happening too late, which was causing a race in tests. The add must happen before the goroutine is started.
CheckHTTP did not have a WaitGroup, so I added it to match CheckAlias.
It looks like `CheckTCP`, `CheckMonitor`, `CheckDocker`, `CheckGRPC`, and `CheckTTL` all may have the same problem. I'm not sure why it seems that only alias and http are failing. I saw one failure for GRPC, so maybe alias and http happen to have more tests written for them?
If this fix looks good, I will look at refactoring so that all of these can share the "run" mechanism and remove the need to copy the fix 7 times.

checks: wait for goroutine to complete (fix go-test-race failures)

---

.circleci/config.yml
agent/consul/stream/event_snapshot_test.go

When the race detector is enabled we see this test fail occasionally. The reordering of execution seems to make it possible for the snapshot splice to happen before any events are published to the topicBuffers.
We can handle this case in the test the same way it is handled by a subscription, by proceeding to the next event.
Example failure:
```
Failed
=== RUN   TestEventSnapshot/empty_snapshot_with_concurrent_mutations
--- FAIL: TestEventSnapshot/empty_snapshot_with_concurrent_mutations (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1043 [running]:
testing.tRunner.func1.1(0x8aaea0, 0xc0000d64a0)
/usr/local/go/src/testing/testing.go:940 +0x421
testing.tRunner.func1(0xc0000d8a20) …
```

stream: handle empty event in TestEventSnapshot

---

agent/agent.go
agent/agent_endpoint_test.go
agent/cache-types/connect_ca_leaf.go
agent/cache-types/options.go
agent/cache/cache.go
agent/cache/cache_test.go
agent/cert-monitor/cert_monitor.go
agent/cert-monitor/cert_monitor_test.go
agent/cert-monitor/config.go
agent/connect/testing_ca.go
agent/connect/uri_agent.go
agent/connect/uri_service.go
agent/consul/auto_encrypt.go
agent/consul/auto_encrypt_test.go
agent/proxycfg/testing.go

The fallback method would still work but it would get into a state where it would let the certificate expire for 10s before getting a new one. And the new one used the less secure RPC endpoint.
This is also a pretty large refactoring of the auto encrypt code. I was going to write some tests around the certificate monitoring but it was going to be impossible to get a TestAgent configured in such a way that I could write a test that ran in less than an hour or two to exercise the functionality.
Moving the certificate monitoring into its own package will allow for dependency injection and in particular mocking the cache types to control how it hands back certificates and how long those certificates should live. This will allow for exercising the main loop more than would be possible with it …

Fix issue with changing the agent token causing failure to renew the auto-encrypt certificate

---

agent/agent.go
agent/agent_endpoint_test.go
agent/cache-types/connect_ca_leaf.go
agent/cache-types/options.go
agent/cache/cache.go
agent/cache/cache_test.go
agent/cert-monitor/cert_monitor.go
agent/cert-monitor/cert_monitor_test.go
agent/cert-monitor/config.go
agent/connect/testing_ca.go
agent/connect/uri_agent.go
agent/connect/uri_service.go
agent/consul/auto_encrypt.go
agent/consul/auto_encrypt_test.go
agent/proxycfg/testing.go

There were a few other commits on master not backported that caused conflicts in agent/agent.go and agent/cache/cache.go. Both were pretty trivial to fix.

Backport: #8311

---

agent/acl_test.go
agent/ae/ae_test.go
agent/checks/check.go
agent/consul/acl_test.go
agent/consul/client_test.go
agent/consul/leader_test.go
agent/consul/server_test.go
agent/testagent.go
api/api_test.go
sdk/testutil/README.md
sdk/testutil/server.go
sdk/testutil/testlog.go

Replaces  #7559
Fixes this data race (and likely many others): https://github.com/hashicorp/consul/issues/8329#issuecomment-661424730
Running tests in parallel, with background goroutines, results in test output not being associated with the correct test. `go test` does not make any guarantees about output from goroutines being attributed to the correct test case.
Attaching log output from background goroutines also cause data races.  If the goroutine outlives the test, it will race with the test being marked done. Previously this was noticed as a panic when logging, but with the race detector enabled it is shown as a data race.
This commit attempts a new approach. Instead of printing all the logs, only print when a test fails. All of the logs are printed from the test goroutine, so they …

testutil: NewLogBuffer - buffer logs until a test fails

---

website/data/subnav.js

🌏 [Consul.io Staging Preview](https://deploy-preview-8356--consul-docs-preview.netlify.app/)
The "Overview" link previously went to a summary of Consul features and a
comparison to other products. This commit restores that destination at the
request of Consul PMs.
This commit previously removed the link (it went to `/` instead of `/intro`).
https://github.com/hashicorp/consul/commit/ac612a9cdcf81c713b4a2fadb3201980197a26ca#diff-f98b55875118725d1373dd2da36d9ee5

Restore link to /intro docs in main menu

---

agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/subscription.go
agent/consul/stream/subscription_test.go

Also fix an over-allocation in Subscription filtering of events. Resolves two TODOs from #8160

stream: close subscriptions on shutdown

---

command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go

Previously, the envoy bootstrap config would blindly copy the self_admin
cluster into the list of static clusters when configuring either
ReadyBindAddr, PrometheusBindAddr, or StatsBindAddr.
Since ingress gateways always configure the ReadyBindAddr property,
users run into this case much more often than previously.

Fix envoy bootstrap logic to not append multiple self_admin clusters

---

agent/agent.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/consul/config.go
agent/structs/connect_ca.go

Previously this was done in the `Agent.consulConfig` function but we will need this in other places for Agent Auto Configuration so this functionality is being moved to a method on the `RuntimeConfig`

Move generation of CA Configuration into a method on the `RuntimeConfig`

---

GNUmakefile

This should make it easy for us to find modules that are very out of date, or which have newer versions available.
<details><summary>Example output:</summary>
```
cloud.google.com/go                                v0.38.0                                   2019-05-01   v0.61.0
github.com/Azure/azure-sdk-for-go                  v40.3.0+incompatible                      2020-03-10   v44.2.0+incompatible
github.com/Azure/go-autorest/autorest              v0.10.0                                   2020-02-24   v0.11.2
github.com/Azure/go-autorest/autorest/adal         v0.8.2                                    2020-02-07   v0.9.0
github.com/Azure/go-autorest/autorest/azure/auth   v0.4.2                                    2019-12-13   v0.5.0
github.com/Azure/go-autorest/autorest/azure/cli …
```

Add script to print available module updates

---

agent/consul/connect_ca_endpoint.go
agent/consul/server_connect.go

The code now lives on the Server type itself. This was done so that all of this could be shared with auto config certificate signing.

Move connect root retrieval and cert signing logic out of the RPC endpoints

---

website/_redirects

A few online search engines (DuckDuckGo, Google, Yahoo, etc) currently return a link to https://www.consul.io/docs/k8s/connect.html as the first result when searching for "consul connect kubernetes". This page was moved in PR #8140 to https://www.consul.io/docs/k8s/connect/overview. The previous URL no longer exists and results in a HTTP 404 being returned when accessed.
This change resolves the 404 error by redirecting /docs/k8s/connect.html to /docs/k8s/connect/overview.

docs: Add redirect for /docs/k8s/connect.html

---

website/pages/docs/enterprise/network-segments.mdx

Change the callout on the Network Segments page to specify the limitation applies to versions of Consul prior to version 1.7.3.

docs: Modify network segments limitation callout

---

website/_redirects

Modify the HTTP redirects for the gateway documentation to point to the updated URL locations. Missed in PR #8195.

docs: Modify website redirects for gateways

---

api/status.go
api/status_test.go

Added QueryOptions for status api, according to the documentation https://www.consul.io/api/status.html

Added QueryOptions for status api

---

website/pages/docs/agent/options.mdx

Fix typo in `-pid` file option description. This change restores text which was erroneously deleted in PR #736 with commit f41dce9.
Fixes #8388

docs: Fix typo in -pid file description

---

agent/agent_test.go
agent/cache-types/catalog_list_services_test.go
agent/cache-types/connect_ca_leaf_test.go
agent/cache/cache.go
agent/cache/cache_test.go
agent/cache/testing.go
agent/cache/watch_test.go
agent/cert-monitor/cert_monitor_test.go
agent/config/builder.go
agent/proxycfg/testing.go

There were several PRs that while all passed CI independently, when they all got merged into the same branch caused compilation errors in test code.
The main changes that caused issues where changing agent/cache.Cache.New to require a concrete options struct instead of a pointer. This broke the cert monitor tests and the catalog_list_services_test.go. Another change was made to unembed the http.Server from the agent.HTTPServer struct. That coupled with another change to add a test to ensure cache rate limiting coming from HTTP requests was working as expected caused compilation failures.

Fix some broken code in master

---

.circleci/config.yml

This PR adds a custom slack notification to the #feed-consul-gh Slack channel when there is a failure of any job on the default (master) branch. 
Since this has a [when condition](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute) to run `on_fail` it should always be the last step of jobs. 
A sample notification looks like this:
where the `job-name` links to the failed CircleCI job and the `commit short ref` links to the GitHub commit.

add circleci job failure notifications for any jobs on master

---

ui-v2/app/adapters/intention.js
ui-v2/app/adapters/service.js
ui-v2/app/serializers/application.js
ui-v2/app/services/client/http.js
ui-v2/app/services/data-source/protocols/http.js
ui-v2/app/services/repository.js
ui-v2/app/services/repository/intention.js
ui-v2/app/services/repository/service.js
ui-v2/app/services/repository/type/event-source.js

Previously we used a `shouldReconcile` method in order to decide whether a response should trigger a reconciliation of the frontend ember-data 'source of truth' or not.
It's a lot nicer/clearer if this 'flag' can be set alongside the HTTP request information, moreover we almost have the same functionality in `If-Range`/`Partial Content` HTTP functionality.
Here we partly follow these HTTP semantics but use a custom `X-Range` header instead.
Additional note here, we are using 'header to meta' approach more and more for various little details, it would be nice to formalise this approach a little more. In fact, the code surrounding it is from the very beginnings of the Consul UI previous to the adapter cleanup we did in https://github.com/hashicorp/consul/pull/5637 (which actually mentions a …

ui: Use X-Range header as a signal as to whether to reconcile the ember-data store

---

ui-v2/app/components/tab-nav/pageobject.js
ui-v2/app/helpers/href-to.js
ui-v2/tests/acceptance/dc/services/show/dc-switch.feature
ui-v2/tests/acceptance/steps/dc/services/show/dc-switch-steps.js
ui-v2/tests/pages.js
ui-v2/tests/pages/dc/services/show.js
ui-v2/tests/steps/assertions/page.js

DC switching whilst you are on 'item' view page will either:
1. Show you an error page if the same 'item' _doesn't_ exist in the other DC
2. Show you the equivalent item in the other DC if it _does_ exist in the other DC (which can generally be the case for cross DC services)
If point 2 occurs, then the URLs of the tabs in the sub navigation can potentially maintain the links to the previous DC due to the fact that we aren't passing the DC into the `href-to` helper as a dependency property in the call to the helper.
The straightforward fix here is to update any `href-to` hrefs on url change (which is the exact same functionality as `is-href`). This is in someway a shortcut, ideally all `href-to`/`is-href` calls would include all their dependants, but unfortunately this isn't the case in …

ui: Ensure URLs for tabs change when selecting a different DC

---

api/status.go
api/status_test.go

Refs https://github.com/hashicorp/consul/pull/7818
Restores `Leader()` and `Peers()` function signatures as wrappers to avoid a breaking change, moves new implementations with `QueryOptions` support to `LeaderWithQueryOptions(q *QueryOptions)` and `PeersWithQueryOptions(q *QueryOptions)`

api: restore Leader() and Peers() to avoid breaking function signatures

---

agent/cert-monitor/cert_monitor.go
agent/cert-monitor/cert_monitor_test.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/consul/auto_encrypt_endpoint_test.go
agent/consul/server.go
tlsutil/config.go
tlsutil/config_test.go

Previously we disallowed that configuration with a note saying that auto encrypt didn't affect incoming connections. However the other code in the TLS configurator would use the auto_encrypt or auto_config generated TLS certificate for the public HTTPs API if no other certificate was provided manually. Therefore the restriction on the configuration has been relaxed to allow setting the configuration if either a certificate was manually provided or one of the auto tls features is enabled.

Allow setting verify_incoming* when using auto_encrypt or auto_config

---

agent/agent.go
agent/agent_test.go
agent/auto-config/auto_config.go
agent/auto-config/config_translate.go
agent/cert-monitor/cert_monitor.go
agent/cert-monitor/cert_monitor_test.go
agent/cert-monitor/config.go

When implementing auto-config certificate generation without auto-encrypt I missed a crucial feature which is that certificates for auto-config must be persisted to allow for restarts to function properly after the agent has existed for 3 days. The initial certificates get persisted but I wasn't updating the persisted configuration once new certificates were retrieved.
This PR implements that persistence.
In the near future I am going to be doing more refactoring and merging. The auto-encrypt code will be consumed by the auto-config packages as well as the cert-monitor package. Basically, with this PR I don't love how the persistence has to happen through a series of callbacks. I think with that the conclusion I have come to is that the code in the cert-monitor package really needs to be …

Ensure certificates retrieved through the cache get persisted with auto-config

---

website/pages/docs/agent/options.mdx

We will probably want a tutorial about this in the future but for now at least we document it a little.

Add some auto-config docs

---

agent/consul/server.go

Currently Consul can panic when starting up if one of the setup functions in `NewServerWithOptions()` fails. 
This is because:
- There are multiple calls to `s.Shutdown()` in `NewServerWithOptions()`
- `s.Shutdown()` calls to pointers like `s.fsm.State().Abandon()`, which will panic if the error and call to Shutdown came before they were setup.
This PR adds more nil checks to `s.Shutdown()` so that the shutdown can finish and the error from the setup function that failed is surfaced.

Avoid panics during shutdown routine

---

command/tls/cert/create/tls_cert_create.go

Was creating a cert and happened to notice part of the command was missing in the help string.

docs: Simple tls cert create help text typo

---

.circleci/config.yml
GNUmakefile
build-support/scripts/proto-gen.sh
proto/pbacl/acl.pb.go
proto/pbautoconf/auto_config.pb.go
proto/pbcommon/common.pb.go
proto/pbcommon/common_oss.pb.go
proto/pbconfig/config.pb.go
proto/pbconnect/connect.pb.go

This PR adds a CI job which checks that the generated Go files match the `.proto` files. 
With this change we ensure that:
1. all code is generated with the same version of protobuf.
2. contributors can discover which version to use by looking at the CI config.
3. if the proto files were ever changed without generating the code, we would catch the mistake immediately in the PR which made the change.
4. nothing unintentional was hidden in the generated code files (because generated code is rarely reviewed in-depth).
The CI check is currently failing. I guess because `protobuf` `v3.12.3` is not the version that was used to generate these files? Do we have a specific version to use, or should I update these files using `v3.12.3`.

ci: Add check-generated-protobuf

---

agent/cache-types/service_checks.go

The main bug was fixed in cb050b280ceb4186de765118611a7a92d8158c3f, but the return value of 'result' is still misleading.
Change the return value to nil to make the code more clear.
Related to #7512

cache-type: Return nil value on error

---

agent/acl_test.go
agent/agent.go
agent/consul/client.go
agent/consul/client_test.go
agent/consul/config.go
agent/consul/leader_test.go
agent/consul/rpc.go
agent/consul/server.go
agent/consul/server_test.go
agent/pool/pool.go
api/watch/plan.go
api/watch/watch.go
command/connect/proxy/proxy.go
logging/logger.go
logging/logger_test.go

This PR resolves a FIXME about the duplicate `LogOutput` field. Through large parts of the code (agent, client, server, watches, rpc) we pass around both a `Logger` and a `LogOutput io.Writer`. The Writer was passed to dependencies that I guess previously did not accept a Logger in some form. It seems that now all of those dependencies accept a `Logger`, so we can remove `LogOutput` which cleans up a few things.
Instead of a `Writer` a `Logger` is passed to dependencies that require one. This change allows us to delete a few `LogOutput` fields. It also removes, or moves duplicate Client and Server constructors into the test packages where they are used.
This change is being made to facilitate adding a `grpcHandler` to the RPC Server for streaming. It is the first of a few PRs that will …

Use Logger consistently, instead of LogOutput

---

command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
command/connect/envoy/testdata/access-log-path.golden
command/connect/envoy/testdata/defaults.golden
command/connect/envoy/testdata/existing-ca-file.golden
command/connect/envoy/testdata/extra_-multiple.golden
command/connect/envoy/testdata/extra_-single.golden
command/connect/envoy/testdata/grpc-addr-config.golden
command/connect/envoy/testdata/grpc-addr-env.golden
command/connect/envoy/testdata/grpc-addr-flag.golden
command/connect/envoy/testdata/grpc-addr-unix.golden
command/connect/envoy/testdata/ingress-gateway-address-specified.golden
command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway.golden
command/connect/envoy/testdata/stats-config-override.golden
command/connect/envoy/testdata/token-arg.golden
command/connect/envoy/testdata/token-env.golden
command/connect/envoy/testdata/token-file-arg.golden
command/connect/envoy/testdata/token-file-env.golden
command/connect/envoy/testdata/zipkin-tracing-config.golden

When consul is restarted and an envoy that had already sent DiscoveryRequests to the previous consul process sends a request to the new process it doesn't respect the `set_node_on_first_message_only` setting and never populates DiscoveryRequest.Node for the life of the new consul process due to this bug: https://github.com/envoyproxy/envoy/issues/9682
Fixes #8430

xds: revert setting set_node_on_first_message_only to true when generating envoy bootstrap config

---

command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/testdata/access-log-path.golden
command/connect/envoy/testdata/defaults.golden
command/connect/envoy/testdata/existing-ca-file.golden
command/connect/envoy/testdata/extra_-multiple.golden
command/connect/envoy/testdata/extra_-single.golden
command/connect/envoy/testdata/grpc-addr-config.golden
command/connect/envoy/testdata/grpc-addr-env.golden
command/connect/envoy/testdata/grpc-addr-flag.golden
command/connect/envoy/testdata/grpc-addr-unix.golden
command/connect/envoy/testdata/stats-config-override.golden
command/connect/envoy/testdata/token-arg.golden
command/connect/envoy/testdata/token-env.golden
command/connect/envoy/testdata/token-file-arg.golden
command/connect/envoy/testdata/token-file-env.golden
command/connect/envoy/testdata/zipkin-tracing-config.golden

This is a backport of https://github.com/hashicorp/consul/pull/8440 to 1.7.x

[backport/1.7.x] xds: revert setting set_node_on_first_message_only to true when generating envoy bootstrap config

---

agent/router/manager.go
agent/router/manager_internal_test.go

This code started as an optimization to avoid doing an RPC Ping to
itself. But in a single server cluster the rebalancing was led to
believe that there were no healthy servers because `foundHealthyServer`
was not set. Now this is being set properly.
Fixes #8401.

Mark its own cluster as healthy when rebalancing.

---

agent/config/builder.go
agent/config/runtime_test.go
agent/consul/acl_server.go
website/pages/docs/agent/options.mdx

This PR turns on connect when using auto_config.

AutoConfig implies Connect

---

agent/config/builder.go
agent/config/runtime_test.go

AutoConfig will generate local tokens for clients and the ability to use local tokens is gated off of token replication being enabled and being configured with a replication token. Therefore we already have a hard requirement on having token replication enabled, this commit just makes sure to surface that to the operator instead of having to discern what the issue is from RPC errors.

Require token replication to be enabled in secondary dcs when ACLs are enabled with AutoConfig

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx

It seems like only `tls` and `http` are supported right now.
https://github.com/hashicorp/consul/blob/586ee2566f1b75e675adc66a68639ecf22c69ab3/agent/structs/config_entry_gateways.go#L37-L40
https://github.com/hashicorp/consul/blob/586ee2566f1b75e675adc66a68639ecf22c69ab3/agent/structs/config_entry_gateways.go#L123-L126
I found this confusing when I was going through it. I'm hoping this will make someone else's life easier.

Specify allowed ingress gateway protocols in docs

---

ui-v2/tests/acceptance/dc/nspaces/index.feature

Mock out namespaces to test to prevent things changing at all in future, but make sure the default namespace is second in order, then assert on the second row (the default namespace) in the listing.

ui: Fix up default namespace no delete test

---

ui-v2/app/components/aria-menu/index.js
ui-v2/app/styles/base/components/buttons/index.scss
ui-v2/app/styles/base/components/buttons/layout.scss
ui-v2/app/styles/base/components/buttons/skin.scss
ui-v2/app/styles/components/filter-bar.scss
ui-v2/app/styles/components/filter-bar/layout.scss
ui-v2/app/styles/components/filter-bar/skin.scss
ui-v2/app/styles/components/popover-select.scss

We are currently undergoing changes/improvements to our sort menu look and feel. This prepares the way to change the design slightly
Previously when selecting an item from the menu via your keyboard, the menu itself would lose focus. This amend keeps the focus on the menu so pressing enter again will reopen the menu so you can reselect. If the menu is a multiple select menu, the focus will remain on the item you have selected.
Menu keyboard access before:
Menu keyboard access after:
Lastly this is part of a larger, currently unfinished, piece of work - but it this PR seemed like a good improvement/point to PR separately at this stage.

ui: Dropdown/select improvements

---

ui-v2/app/models/proxy.js
ui-v2/app/utils/create-fingerprinter.js

Recently, we noticed not all instances had the label connected with proxy even when they did have a proxy. Looking into the issue we realized Ember Data was not able to differentiate between the instances because they don't have a unique ID. The solution to this was to create a unique slug key. We did this by concatenating Node, and Service ID (dc and nspace is already concatenated to generate a unique id). This is a temporary solution. Long term, we plan on implementing a better solution in the serializer.

ui: Add unique slug key id to proxy

---

ui-v2/app/controllers/application.js

In certain circumstances logging out can produce one of our top notification errors even though it has logged you out successfully, this can make for a confusing experience.
It seems that refreshing an error route will still throw/reject another error, which kind of makes sense. Therefore if the application refresh does cause an error we catch this, but still perform any redirects required to send the user to the correct destination after the refresh, which is the desired behaviour.

ui: Passthrough any error from a route:application refresh

---

ui-v2/app/components/popover-menu/menu-item/index.hbs
ui-v2/app/components/popover-select/index.hbs
ui-v2/app/components/popover-select/index.js
ui-v2/app/components/popover-select/optgroup/index.hbs
ui-v2/app/components/popover-select/optgroup/index.js
ui-v2/app/components/popover-select/option/index.hbs
ui-v2/app/components/popover-select/option/index.js
ui-v2/app/components/search-bar/index.hbs
ui-v2/app/controllers/dc/services/show/instances.js
ui-v2/app/controllers/dc/services/show/intentions/index.js
ui-v2/app/initializers/sort.js
ui-v2/app/services/dom.js
ui-v2/app/sort/comparators/kv.js
ui-v2/app/styles/components/app-view/skin.scss
ui-v2/app/styles/components/buttons.scss
ui-v2/app/templates/dc/acls/policies/index.hbs
ui-v2/app/templates/dc/acls/roles/index.hbs
ui-v2/app/templates/dc/acls/tokens/index.hbs
ui-v2/app/templates/dc/intentions/index.hbs
ui-v2/app/templates/dc/kv/index.hbs
ui-v2/app/templates/dc/nspaces/index.hbs
ui-v2/app/templates/dc/services/index.hbs
ui-v2/app/templates/dc/services/show/intentions/index.hbs
ui-v2/tests/acceptance/dc/acls/roles/sorting.feature
ui-v2/tests/acceptance/dc/services/show/intentions.feature
ui-v2/tests/acceptance/dc/services/sorting.feature

This PR moves our `PopoverSelect` component to follow normal HTML `<select>` more closely:
Options, and option grouping is now configured using `<Option>` and `<Optgroup>` contextual components.
Previously we we had grouping functionality in out normal popover menus, but not in the select ones. This makes it much easier to configure the menus with `<Optgroups>` which is particularly needed in the intentions listing page:
Before:
After:
Additionally changing this to essentially be configured with XML/HTML means instead of looping through javascript/handlebar arrays means we can be more flexible with the label for the selected item, which again is needed in the intentions listing page, especially when we need to distinguish whether the list is sorted alphabetically by SourceName or by …

ui: Add Optgroups and selectedItems to multiple select dropdown and use

---

ui-v2/app/services/client/connections.js
ui-v2/app/services/client/http.js
ui-v2/app/utils/dom/event-source/blocking.js
ui-v2/tests/unit/utils/dom/event-source/blocking-test.js

The UI will attempt to reconnect/retry a blocking query to Consul after
a disconnection in certain circumstances.
1. On receipt of a 5xx error (used for keeping blocking queries running
through reverse proxies that have lower timeouts than consul itself)
2. When a user switches to a different tab and back again
3. When the connection to Consul is dropped entirely (when Consul itself
has exited)
In the last case the retry attempts where not using a 3 second pause
between attempts like the first case is.
This commit changes the last case to use the same 3 second pause as the
last case.

ui: Reduce reconnection attempts on disconnection

---

agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/txn.go
agent/structs/structs.go

This PR fixes a bug where nodes, services, and checks would not be restored with the correct Create/ModifyIndex when restoring from a snapshot. The KV entries didn't have this issue because we do a raw tx.Insert of the entry that we read from the transaction (so it includes the Create/ModifyIndex), but when loading in catalog objects we have to do additional bookkeeping, so we weren't doing a raw insert there. This PR adds a `preserveIndex` argument to some of the internal state store functions to enable keeping the index we read from the snapshot, without allowing users to arbitrarily modify these fields during a normal update.
Fixes #8377.

fsm: Fix snapshot bug with restoring node/service/check indexes

---

sdk/testutil/server.go

Occasionally we are seeing the go-test-api job timeout at 10 minutes.
Looking at the stack trace I saw the following:
1. Lots of tests blocked on server.Stop in NewTestServerConfigT. This
suggests that SIGINT is being sent to the server, but the server is
not properly shutting down.
2. Over 20k goroutines that look like this:
```
goroutine 16355 [select, 8 minutes]:
net/http.(*persistConn).readLoop(0xc004270240)
/usr/local/go/src/net/http/transport.go:2099 +0x99e
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1647 +0xc56
```
Issue 1 seems to be the main problem, but debugging that directly is not
possible because our buffered logs do not get sent when the tests
timeout. To mitigate this problem I've added a timeout to the cmd.Wait()
to force kill the …

sdk: mitigate api test timeout

---

website/pages/docs/k8s/helm.mdx

No longer require servers to be running on k8s when
manageSystemACLs is true.

docs: update helm chart reference

---

agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/http_register.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

Currently intention match queries require knowledge of the services referenced by the intention.
This means that if someone needs all the intentions for services linked to a terminating gateway they would need to:
1. Query for the linked services
2. Issue a separate intention match queries
This PR adds an endpoint that collapses these two steps into a single blocking query for the UI, since it has limitations regarding the number of active blocking queries it can maintain.
The endpoint is: `/v1/internal/ui/gateway-intentions/:gateway`. Where `:gateway` would be the name of the gateway.
The response would be a list of intentions for all services associated with the gateway, as with the `/v1/connect/intentions` endpoint: https://www.consul.io/api-docs/connect/intentions#sample-response-2

Internal endpoint to query intentions associated with a gateway

---

agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/txn.go
agent/structs/structs.go

This pulls the changes from #8474 into the `release/1.7.x` branch.

Backport catalog snapshot index fix to 1.7.x

---

agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/txn.go
agent/structs/structs.go

This pulls the changes from #8474 into the `release/1.8.x` branch.

Backport catalog snapshot index fix to 1.8.x

---

agent/consul/internal_endpoint.go
agent/consul/rpc.go
agent/consul/server_test.go
agent/keyring.go
agent/keyring_test.go
agent/operator_endpoint.go
agent/operator_endpoint_test.go
agent/router/router.go

Before `local-only` wouldn't work properly, instead it would still query every pool. This PR fixes it, by properly threading the flag through the layers:
```
$ consul keyring -list -local-only
==> Gathering installed encryption keys...
dc1 (LAN):
aUlAW4ST3+vwseI61so24CoORkyjZofcmHk+j7QPSYQ= [1/1]
```
On top of that it contains a refactoring commit that 
* changes some functions to return data instead of modifying pointer arguments.
* renames `globalRPC()` to `keyringRPCs()` to make its purpose more clear
* restructures `KeyringOperation()` to make it more understandable

thread local-only through the layers

---

agent/agent.go
agent/agent_endpoint_test.go
agent/agent_test.go
agent/auto-config/auto_config.go
agent/auto-config/auto_config_test.go
agent/auto-config/builder.go
agent/auto-config/config_translate.go
agent/auto-config/config_translate_test.go
agent/config/agent_limits_test.go
agent/config/builder.go
agent/config/builder_test.go
agent/config/config.go
agent/config/default.go
agent/config/default_oss.go
agent/config/runtime_test.go
agent/testagent.go
agent/testagent_test.go

I was looking around the changes to config loading and I noticed that we are now marshaling a `map[string]interface{}` into JSON so that we can feed it into config loading. 
This PR changes `config.Source` into an interface, so that we can use different implementations. `FileSource` replaces the previous `Source`. A new `LiteralSource` is added so that we can return a struct directly and it can be merged into the final `RuntimeConfiguration`. The default sources can also be changed into `LiteralSource` would should make it much easier to find default values for a field, and remove some unnecessary parsing and `mapstructure.Decode`.
This change is still a WIP. I didn't change the `translateConfig` function yet. I wanted to make sure this approach would be viable before finishing that work.

config: make Source an interface to avoid the marshal/unmarshal cycle in auto-config

---

agent/local/state.go
agent/local/state_test.go

Currently when monitoring alias checks locally we have two mechanisms for updating the status of the alias check:
1. [Get a notification](https://github.com/hashicorp/consul/blob/586ee2566f1b75e675adc66a68639ecf22c69ab3/agent/checks/alias.go#L129) when a check for the service we are aliasing is updated
2. Catch updates that didn't trigger a notification by [checking every minute](https://github.com/hashicorp/consul/blob/586ee2566f1b75e675adc66a68639ecf22c69ab3/agent/checks/alias.go#L105-L108)
PR #7384 added a check so that alias health checks do not pass if the underlying service doesn't exist. However, we did not notify existing alias checks when services were added/removed. This means we could wait up to a minute to update the check status in these cases (per item 2 above).
This PR …

Notify alias checks when aliased service is [de]registered

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/xds/listeners.go
agent/xds/routes.go

Fixes #8466
Since Consul 1.8.0 there was a bug in how ingress gateway protocol
compatibility was enforced. At the point in time that an ingress-gateway
config entry was modified the discovery chain for each upstream was
checked to ensure the ingress gateway protocol matched. Unfortunately
future modifications of other config entries were not validated against
existing ingress-gateway definitions, such as:
1. create tcp ingress-gateway pointing to 'api' (ok)
2. create service-defaults for 'api' setting protocol=http (worked, but not ok)
3. create service-splitter or service-router for 'api' (worked, but caused an agent panic)
If you were to do these in a different order, it would fail without a
crash:
1. create service-defaults for 'api' setting protocol=http (ok)
2. create …

connect: use stronger validation that ingress gateways have compatible protocols defined for their upstreams

---

website/pages/docs/k8s/service-sync.mdx

- remove docs that said for nodeport service we register each instance
on a node with its same node name. We instead register each instance
onto the k8s-sync node (was updated in https://github.com/hashicorp/consul-k8s/commit/ca2f3848b13217148bf04f60ae0db32004530a9d)
- add docs describing which ports and ips are used

Update k8s sync docs

---

.changelog/note.tmpl

Issue and PR numbers do not overlap, they are based of the same counter.
A PR can be also linked to via issues, if it is a PR, Github will
redirect to it.
This change has the benefit that one can link to both - issues and PRs.

Link issue in note template

---

agent/consul/state/catalog_test.go
agent/consul/state/state_store.go

I saw `TestStateStore_ServicesByNodeMeta` flake a few times in the `go-test-race` job. When I went to try and reproduce the flake I noticed the test was taking 6s to run (even longer in CI)! Attempting to reproduce the flake was not working well because it individual test run was so long.
To find the slowdown I started by splitting the test into sub-tests. The sub-tests help identify all the independent cases.
I was able to speed up the test significantly by making `watchLimit` a `var` and patching it to a much lower value. This test was previously creating 16000+ nodes and services, which is where all the time was spent. After this change it only creates 12 of each. We could create fewer, but the test runs in 0.01s now, so that is probably fast enough.
Unfortunately I was not able to …

state: speed up tests that use watchLimit

---

agent/consul/autopilot_test.go
agent/consul/client_test.go
agent/consul/config.go
agent/consul/leader_test.go
agent/consul/server.go
agent/consul/server_test.go

NotifyShutdown was only used for testing. Now that `t.Cleanup` exists, we can use that instead of attaching cleanup to the Server shutdown. This is one small step in reducing or removing the `agent/consul.Config` struct.
The Autopilot test which used NotifyShutdown doesn't need this notification because Shutdown is synchronous. Waiting for the function to return is equivalent.
Also removes a bunch of `defer os.RemoveAll()`, the directory can be removed by the test helper that creates it.

agent/consul: Remove NotifyShutdown

---

agent/agent.go
agent/agent_test.go
agent/nodeid.go
agent/nodeid_test.go

This is a small step in reducing the scope of `Agent`, and cleaning up how an Agent is created. By converting methods to functions we can pull out dependency creation from `Agent.New()` and pass dependencies to the constructor.
The first comment moves the functions to a new location with no changes, the second refactors.

agent: convert NodeID methods to functions 

---

agent/agent.go
agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_test.go
agent/consul/state/autopilot.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_oss.go
agent/consul/state/memdb.go
agent/consul/state/state_store.go
agent/consul/state/txn.go

This is a follow up to #8282. I'll need this for adding Terminating Gateways to streaming as a follow up to #8357. 
This was the last of the methods that I could find that do not use their receiver.
Also changed some functions to use the `ReadTxn` interface where appropriate.

state: remove unused Store method receiver

---

agent/agent.go
agent/agent_oss.go
agent/keyring.go
agent/testagent.go

This PR converts `Agent.consulConfig()`  method into a function which builds a `consul.Config` from a `config.RuntimeConfig`.
This is another small step to shrink `Agent`, and also to invert the flow, so that dependencies can be passed to constructors, instead of constructors creating all the dependencies.
The change was fairly mechanical, mostly consisting of removing method receivers and adding the one or two required parameters as function arguments. A couple of functions moved into `keyring.go` closer to the functions they call.

agent: convert consulConfig method to a function

---

website/pages/docs/k8s/installation/deployment-configurations/servers-outside-kubernetes.mdx

Based on [feedback](https://discuss.hashicorp.com/t/remote-error-tls-bad-certificate-for-k8s-consul-clients/12422/5) from a user on Discuss.

docs: consul on k8s doesn't support external servers requiring mTLS

---

.changelog/8494.txt
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/xds/listeners.go
agent/xds/routes.go

Backport of #8470 to 1.8.x
Due to some refactors of state machine methods->functions this did not backport cleanly.

[backport/1.8.x] connect: use stronger validation that ingress gateways have compatible protocols defined for their upstreams

---

agent/acl_test.go
agent/agent_endpoint_test.go
agent/agent_test.go
agent/dns_test.go
agent/keyring_test.go
agent/service_manager_test.go
agent/testagent.go
sdk/testutil/io.go

While working on another change I had to make some changes to TestAgent, so I am splitting out some of these changes ahead of the other PR.
While testing these changes I hit a few flaky tests, so this PR includes fixes for them, in separate commits. Details of each change in the commit messages.

testing: Use t.cleanup in TestAgent , and fix two flaky tests

---

website/pages/docs/commands/acl/bootstrap.mdx
website/pages/docs/commands/acl/token/update.mdx
website/pages/docs/commands/force-leave.mdx
website/pages/docs/commands/license.mdx
website/pages/docs/commands/lock.mdx
website/pages/docs/commands/operator/area.mdx
website/pages/docs/commands/operator/autopilot.mdx
website/pages/docs/commands/operator/index.mdx
website/pages/docs/connect/configuration.mdx
website/pages/docs/connect/connect-internals.mdx
website/pages/docs/connect/connectivity-tasks.mdx
website/pages/docs/connect/gateways/index.mdx
website/pages/docs/connect/gateways/ingress-gateway.mdx

Third batch of changes for the link refactor that is following the switch to Collections in learn.hashicorp.com.
This PR contains all the changes for pages under `website/pages/docs/commands` and some of the `website/pages/docs/connect`.
First PR: https://github.com/hashicorp/consul/pull/8488
Second PR: https://github.com/hashicorp/consul/pull/8490
Third: PR: https://github.com/hashicorp/consul/pull/8491
Related PR: https://github.com/hashicorp/consul/pull/8487

Refactor docs links to learn 2

---

website/pages/api-docs/acl-legacy.mdx
website/pages/api-docs/acl/auth-methods.mdx
website/pages/api-docs/acl/binding-rules.mdx
website/pages/api-docs/acl/index.mdx
website/pages/api-docs/acl/legacy.mdx
website/pages/api-docs/acl/policies.mdx
website/pages/api-docs/acl/roles.mdx
website/pages/api-docs/acl/tokens.mdx
website/pages/api-docs/kv.mdx
website/pages/api-docs/operator/area.mdx
website/pages/api-docs/operator/autopilot.mdx
website/pages/api-docs/operator/index.mdx
website/pages/api-docs/operator/segment.mdx
website/pages/api-docs/query.mdx
website/pages/api-docs/session.mdx

First batch of changes for the link refactor that is following the switch to Collections in learn.hashicorp.com.
This PR contains all the changes for pages under `website/pages/api-docs`.
First PR: https://github.com/hashicorp/consul/pull/8488
Second PR: https://github.com/hashicorp/consul/pull/8490
Third: PR: https://github.com/hashicorp/consul/pull/8491
Related PR: https://github.com/hashicorp/consul/pull/8487

Refactor api-docs links to learn

---

agent/config/builder.go
agent/config/runtime_test.go

- unexport testing shims, and document their purpose
- resolve a TODO by moving validation to NewBuilder and storing the one field that is used instead of all of Options
- create a slice with the correct size to avoid extra allocations

config: unexport fields and resolve TODOs in config.Builder

---

.changelog/8522.txt
agent/consul/internal_endpoint.go
agent/structs/structs.go
api/operator_keyring.go
go.mod
go.sum
vendor/github.com/hashicorp/serf/serf/internal_query.go
vendor/github.com/hashicorp/serf/serf/keymanager.go
vendor/github.com/hashicorp/serf/serf/serf.go
vendor/modules.txt

During gossip encryption key rotation it would be nice to be able to see if all nodes are using the same key. This PR adds another field to the json response from `GET v1/operator/keyring` which lists the primary keys in use per dc. That way an operator can tell when a key was successfully setup as primary key.
Based on https://github.com/hashicorp/serf/pull/611 to add primary key to list keyring output:
```json
[
{
"WAN": true,
"Datacenter": "dc2",
"Segment": "",
"Keys": {
"0OuM4oC3Os18OblWiBbZUaHA7Hk+tNs/6nhNYtaNduM=": 6,
"SINm887hKTzmMWeBNKTJReaTLX3mBEJKriDyt88Ad+g=": 6
},
"PrimaryKeys": {
"SINm887hKTzmMWeBNKTJReaTLX3mBEJKriDyt88Ad+g=": 6
},
"NumNodes": 6
},
{
"WAN": false,
"Datacenter": "dc2",
"Segment": "",
"Keys": {
"0OuM4oC3Os18OblWiBbZUaHA7Hk+tNs/6nhNYtaNduM=": 8, …
```

add primary keys to list keyring

---

website/pages/docs/agent/options.mdx

From: https://github.com/hashicorp/learn/issues/1339
When federating existing Consul data centers all policies/roles, intentions (if connect is enabled) and global tokens (if token replication is enabled) will be lost. Data from the primary datacenter will be replicated to secondary datacenters.
This is an expected behaviour but it should be mentioned in the learn guide and documentation to make sure a customer doesn't accidentally purges all roles/policies, intentions and global tokens from secondary cluster. Which by the way happend to en existing cluster, lucky they catched it in their non-prod environment.

Adding warning for ACL replication data loss

---

agent/agent.go
agent/config/builder.go
agent/config/builder_test.go
agent/config/runtime_test.go
agent/dns.go
agent/dns/dns.go
agent/dns_test.go

This validation only needs the config, so we can do it much earlier and avoid creating an Agent or taking a lock.
This is another small step to allow `Agent` to accept its dependencies from the constructor.

config: Move some config validation from Agent.Start to config.Builder.Validate

---

agent/http_test.go
agent/session_endpoint_test.go
agent/ui_endpoint_test.go
sdk/testutil/retry/retry.go

While working on another change I caused a bunch of these tests to fail.
Unfortunately the failure messages were not super helpful at first.
One problem was that the request and response were created outside of
the retry. This meant that when the second attempt happened, the request
body was empty (because the buffer had been consumed), and so the
request was not actually being retried. This was fixed by moving more of
the request creation into the retry block.
Another problem was that these functions can return errors in two ways, and
are not consistent about which way they use. Some errors are returned to
the response writer, but the tests were not checking those errors, which
was causing a panic later on. This was fixed by adding a check for the
response code.
Also adds some missing …

testing: small improvements to TestSessionCreate and testutil.retry

---

agent/acl.go
agent/acl_test.go
agent/agent.go
agent/config/builder.go
agent/config/runtime_test.go
agent/setup.go
agent/testagent.go
command/agent/agent.go
lib/telemetry.go
logging/grpc.go
logging/grpc_test.go
logging/logger.go

With this change, `Agent.New()` accepts many of the dependencies instead of creating them in `New`. Accepting fully constructed dependencies from a constructor has many advantages:
* the type is easier to test, because fakes can be passed to the constructor.
* the type is easier to reason about, because its state is more static. This can be seen in methods like `Shutdown` which have to check if a bunch of dependencies are `nil`. If all the dependencies are passed in and not-nil, we no longer have to worry about that class of bugs.
* the type can shrink significantly. For example in this PR `initializeConnectionPool` and `initializeACL` are no longer methods on `Agent`, and really do not need to know anything about `Agent`. They can be constructed ahead of time. Anything that is being …

agent: extract dependency creation from New

---

agent/structs/structs.go
agent/structs/structs_test.go

Fixes #8529
Surprisingly the `json.Unmarshal` updates the `aux` pointer to a nil, even though it was passed in non-nil. 
Note that while this fixes the panic, that request would still fail with a `400` because `ProxyDestination` was removed in 65be58703cfb4a19d8fb7fc81228dabc8bd407de and a704ebe6392a645f64ce56e87aec30bf1ac3df29 made unknown fields fail validation.
If we backport this fix to 1.6.x, that request should work.

Fix panic when decoding 'Connect: null'

---

agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/acl_replication_types.go
agent/consul/config_replication.go
agent/consul/federation_state_replication.go
agent/consul/leader_federation_state_ae.go

I tried to run the tests but `govet`failed immediately:
```
➜  consul git:(master) make test
--> Checking for other consul instances
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
--> Running go golangci-lint
agent/consul/acl.go:2146:10: nilness: tautological condition: non-nil != nil (govet)
if rule != nil && rule.NodeWrite(op.Node.Node, &authzContext) != acl.Allow {
^
agent/consul/acl_endpoint.go:1228:12: nilness: tautological condition: non-nil != nil (govet)
if policy != nil {
^
agent/consul/acl_endpoint.go:1695:10: nilness: tautological condition: non-nil != nil (govet)
if role != nil {
^
agent/consul/acl_replication_types.go:232:44: nilness: impossible condition: nil != nil (govet)
if respErr, ok := resp.(error); ok …
```

testing: Fix govet errors

---

website/pages/community/index.jsx

🔗 Preview Link TK
Adds the following section...

website: add link to certification on /community

---

ui-v2/app/components/discovery-chain/index.hbs
ui-v2/app/components/discovery-chain/index.js
ui-v2/app/styles/base/components/tooltip/layout.scss
ui-v2/app/styles/components/discovery-chain/layout.scss

- Fix for the tooltip bug in Discovery Chain while using Firefox Browser
- Fix stack order of the ember-tooltip to be above the search/sort

ui: Tooltip Bugs

---

.changelog/8545.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/xds/proxysupport/proxysupport.go

The xDS api exposed on a Consul agent's gRPC port can only successfully emit xDS configuration for a supported range of envoy versions documented here: https://www.consul.io/docs/connect/proxies/envoy#supported-versions
For systems that may wish to automatically launch the latest supported envoy version (like Nomad) this support matrix currently has to be copied from markdown into code in that system.
This PR exposes consul's own internal knowledge of the last 4 supported envoy versions on the `/v1/agent/self` endpoint like this:
```
$ curl -sL 'localhost:8500/v1/agent/self' | jq .xDS
{
"SupportedProxies": {
"envoy": [
"1.15.0",
"1.14.4",
"1.13.4",
"1.12.6"
]
}
}
```

agent: expose the list of supported envoy versions on /v1/agent/self

---

.changelog/8575.txt
api/agent.go
api/agent_test.go

Lots of constants were added for various tags that would concern users and are not already parsed out.
Additionally two methods on the `AgentMember` type were added to ask a member what its ACL Mode is and whether its a server or not.

Add helpers to the API client to help with getting information from `AgentMember` tags

---

agent/agent.go
agent/agent_test.go
agent/consul/auto_encrypt.go
agent/consul/client.go
agent/consul/client_serf.go
agent/consul/client_test.go
agent/consul/coordinate_endpoint.go
agent/consul/options.go
agent/consul/server.go
agent/consul/util.go
agent/router/manager.go
agent/router/router.go
agent/router/router_test.go
agent/setup.go
types/area.go

This will allow it to be a shared component which is needed for AutoConfig

Move RPC router from Client/Server and into BaseDeps

---

.changelog/8547.txt
agent/config/builder.go
agent/config/runtime_test.go

In all other ways to commit config entries to the state store we `Normalize()` before invoking `Validate()` save for the bootstrap angle which this PR corrects.

agent: ensure that we normalize bootstrapped config entries

---

agent/agent.go
agent/agent_test.go
agent/cache/cache.go
agent/cache/cache_test.go

This will apply cache throttling parameters are properly applied:
* cache.EntryFetchMaxBurst
* cache.EntryFetchRate
When values are updated, a log is displayed in info.
This will help to mitigate #7863 when values need to be updated without any downtime of agents

Ensure that Cache options are reloaded when `consul reload` is performed

---

agent/cache/testing.go
agent/cache/watch_test.go
agent/consul/acl_test.go

This attempts to fix a flaky test, as can be seen [here](https://app.circleci.com/pipelines/github/hashicorp/consul/12054/workflows/ff92087e-5e40-4c5e-839b-33b1a441d446/jobs/226784).

Fix flaky TestACLResolver_Client/Concurrent-Token-Resolve

---

logging/logfile_test.go
logging/logger_test.go
logging/monitor/monitor_test.go

I was going through my local branches to remove some merged ones and I found this one sitting around from a while ago.
The tests in this package all run fast enough (including compile time, under 600ms) that there is no advantage to using Parallel.
The one test that was slow used a long sleep. Changing the sleep to a few milliseconds speeds up the test considerably.

logging: Remove t.Parallel from tests

---

CHANGELOG.md
agent/structs/structs.go
agent/structs/structs_test.go

[1.6.x] backport connect=null bug fix

---

website/pages/docs/agent/options.mdx

Docs for https://github.com/hashicorp/consul/pull/6640.

add docs for dual stack options

---

ui-v2/app/styles/components/healthcheck-output.scss
ui-v2/app/styles/components/healthcheck-output/skin.scss

Reinstates tooltip on the exposed path pill within healthchecks

ui: Reinstate tooltip for exposed paths pill

---

.changelog/8601.txt
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry.go

Whenever an upsert/deletion of a config entry happens, within the open
state store transaction we speculatively test compile all discovery
chains that may be affected by the pending modification to verify that
the write would not create an erroneous scenario (such as splitting
traffic to a subset that did not exist).
If a single discovery chain evaluation references two config entries
with the same kind and name in different namespaces then sometimes the
upsert/deletion would be falsely rejected. It does not appear as though
this bug would've let invalid writes through to the state store so the
correction does not require a cleanup phase.

connect: fix bug in preventing some namespaced config entry modifications

---

agent/agent.go
agent/agent_test.go
agent/apiserver.go
agent/apiserver_test.go
agent/http.go
agent/http_test.go
agent/testagent.go
agent/ui_endpoint_test.go
command/agent/agent.go

Fixes #6677 
[x/sync/errgroup](https://golang.org/x/sync/errgroup) is designed to handle exactly this problem. I have used it in the past and found that it handled the problem well.
Eventually we may be able to use a single `errgroup.Group` as the core of the agent. That would require that every goroutine shutdown on a cancelled context (instead of calling `Shutdown`). Until that is possible I've put it into a new `apiServers` struct and exposed the channel so that `command` can be notified when one of them exits, and proceed with the shutdown.
As a follow up to this PR I think we can move at least the `dnsServers` into `apiServers`, which should further shrink `agent.Agent`. Maybe it would be appropriate to move the `grpcServers` in as well?
The retryJoiner for Lan/Wan pools also works …

agent: shutdown if the http server goroutine exits

---

agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/state/memdb.go
agent/consul/state/state_store.go
agent/consul/state/store_integration_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/event_snapshot.go
agent/consul/stream/event_snapshot_test.go

This should be the last of the `agent/consul/state` changes from #7547.
Currently includes #8323, I will rebase once that PR is merged.
Adds a changes->event processor and snapshot func for the `ServiceHealth` and `ServiceHealthConnect` topics.
Also fixes a couple bugs.
Some TODOs with questions to resolve before merge.

streaming: add ServiceHealth events

---

.circleci/config.yml

We have moved AWS accounts and dev artifacts will be pushed to a new bucket. (All the old artifacts will be one-time synced to the new bucket too but since S3 bucket names are  global I would've had to delete the old bucket and wait ~1hr to see if I could get the old name back on the new account. Any dev build s3 pushes during this time would've fail). 
The new service account requires assume-role to have permissions to push to the S3 bucket. I moved to downloading the CLI via curl rather than using a python container so we can keep using the same golang container for all jobs. The assume-role has a minimum duration of 15 mins but once the `cp` fires off, the assume-role credentials shouldn't be needed anymore. 
**Before I merge this PR I will need to flip the AWS credentials in the …

switch to new aws account s3 bucket for dev artifacts

---

agent/consul/leader_connect.go
agent/consul/leader_connect_test.go

secondaryIntermediateCertRenewalWatch was using `retryLoopBackoff` to
renew the intermediate certificate. Once it entered the inner loop and
started `retryLoopBackoff` it would never leave that.
`retryLoopBackoffAbortOnSuccess` will return when renewing is
successful, like it was intended originally.

secondaryIntermediateCertRenewalWatch abort on success

---

.circleci/config.yml

Since the new `aws-assume-role` step writes creds to the BASH_ENV I forgot we needed to `checkout` the code in the `dev-upload-s3` job now to get the `.circleci/bash_env.sh` file, otherwise the job fails looking for it to write to.

add checkout to dev-upload-s3

---

api/lock.go

Currently the lock delay cannot be overridden when calling `Lock` via the api, so it sticks to the default of 15s when creating a session.

Make LockDelay configurable in api locks

---

.changelog/8602.txt
api/api.go

The HTTP client over unix socket needs a special transport object,
and in doing so we need to create a fresh HTTP client so that we
pickup the environment variable based configuration options.

api: create fresh http client for unix sockets

---

.changelog/8606.txt
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/existing-ca-path.golden
tlsutil/config.go
tlsutil/config_test.go

The `consul connect envoy` CLI currently only takes CA certs that are provided using the `-ca-file` option. In some situations more then one CA file need to be used and therefore the `-ca-path* option exists in the Consul agent. However this option is not implemented for envoy itself.
Starting an envoy instance using the `consul connect envoy` commands using the -ca-path options results in an error.
`consul connect envoy -ca-path="/path/to/some/cafiles/folder" -mesh-gateway -register -grpc-addr=https://127.0.0.1:8502`
```
[2020-09-03 15:25:56.210][4342552][critical][main] [external/envoy/source/server/server.cc:95] error initializing configuration '/var/folders/zb/xqhmc3mx62g7gcr_1kg_vmd00000gp/T/envoy-163148f4268ed019-bootstrap.json': Proto constraint validation failed …
```

Add support for -ca-path option in the connect envoy command

---

website/pages/api-docs/agent/service.mdx

HTML and markdown cannot be present in the same line. Change markdown link to HTML anchor element.

docs: Fix rendering of link under service config endpoint

---

ui-v2/app/components/consul-kv-form/index.hbs
ui-v2/app/routes/dc/kv/edit.js
ui-v2/tests/acceptance/dc/kvs/create.feature

In https://github.com/hashicorp/consul/pull/8307 moved the KV area to use KVForm and KVListing components.
This unfortunately broke the creation of KVs when within a folder.
This fixes the bug by prefilling an empty KV for the form if we are on a create page.
We also added some more acceptance tests here.

ui: [Bugfix] KV creation from within a 'folder'

---

ui-v2/.gitignore
ui-v2/lib/commands/bin/list.js
ui-v2/lib/commands/lib/list.js
ui-v2/tests/acceptance/steps/steps.js
ui-v2/tests/steps.js
ui-v2/tests/steps/assertions/page.js

We use a set of BDD testing steps for our acceptance testing and its often useful to know what steps are available whilst writing steps.
We did have an `ember steps:list` command to do list these steps, but at some point during development this has ceased to work.
This PR reinstates this:
The list is visible by running either of the following commands:
```
yarn run steps:list
make steps
ember steps:list
```

ui: Reinstate listing of available test steps via CLI

---

ui-v2/app/styles/components/definition-table/layout.scss

This moves our `%definition-table` CSS component to use CSS grid instead of an absolutely positioned workaround.

ui: Move %definition-table to use CSS grid

---

ui-v2/tests/helpers/yadda-annotations.js

During development a HTTP request will pause for 1 minute ONLY when an
`?index` is set. This gives a realistic emulation of blocking queries.
During testing we can change this latency when we are testing blocking
queries, which we do in numerous places.
A problem can arise during testing on a very slow machine.
If you are not testing blocking queries and therefore you haven't set a latency
to test with, if the machine you are testing on is slow enough, a normal
test case can assert, yet not tear down before a further
blocking query request is made. This blocking query then uses the default
latency which causes the page to hang for 1 minute, which in turn causes
the test to timeout.
This only seems to happen on a very slow system, but it does potentially
explain why we occasionally see the …

ui: Default test latency to 0

---

website/pages/commands/acl/translate-rules.mdx

Just fixes a typo in the command's usage info.

Fix usage typo for `consul acl translate-rules`

---

.changelog/8588.txt
CHANGELOG.md

Changelog entries produced by:
```
$ go install github.com/hashicorp/go-changelog
$ changelog-build -last-release v1.8.3 -entries-dir .changelog/ -changelog-template .changelog/changelog.tmpl -note-template .changelog/note.tmpl -this-release 2e59d304b0307743931a195047710cee5826a048
```
Other potential missing entries:

Go changelog updates from go-changelog

---

sdk/testutil/server.go
sdk/testutil/testlog.go
sdk/testutil/types.go

These changes were made as a result of a suggestion by @dnephin in https://github.com/hashicorp/consul/pull/7559.
This PR enables using a `testing.TB` like interface (e.g. [GinkgoT](https://godoc.org/github.com/onsi/ginkgo#GinkgoT)) in addition to the 'real' [`testing.TB`](https://golang.org/pkg/testing/#TB) interface.
See https://github.com/onsi/ginkgo/issues/582 for further details.
cc @dnephin

testutil: use TestingTB instead of testing.TB

---

.circleci/config.yml

Required by usage of `t.Cleanup` introduced by newer `consul/sdk` version in https://github.com/hashicorp/nomad/pull/8709

ci: pin Nomad integration test to Go 1.14 for Consul 1.7.x

---

.circleci/config.yml

Required by usage of `t.Cleanup` introduced by newer `consul/sdk` version in https://github.com/hashicorp/nomad/pull/8709

ci: pin Nomad integration test to Go 1.14 for Consul 1.6.x

---

website/pages/commands/acl/role/create.mdx
website/pages/commands/acl/role/update.mdx
website/pages/commands/acl/token/create.mdx
website/pages/commands/acl/token/update.mdx

Document `-node-identity` option which was added in #7970 for `acl token <create|update>` and `acl role <create|update>` commands.

docs: Add -node-identity option to token and role command

---

ui-v2/ember-cli-build.js
ui-v2/lib/colocated-components/index.js
ui-v2/lib/colocated-components/package.json
ui-v2/package.json

Our list of components has gradually been expanding and keeping the CSS completely separate from the index.hbs/js component will become harder to manage as we move forwards with more and more components.
This lets us co-locate SCSS files within our component folders:
Before:
```
/components/component-name/index.{hbs,js}
/styles/components/component-name/{index,layout,skin}.scss
```
After:
```
/components/component-name/{index.scss,layout.scss,skin.scss,index.js,index.hbs,README.mdx}
```
Primary usecase here is to make it easier to work on our `consul-*` components, this should let us open up a single folder and have everything we need to build a component in the same place.

ui: Add in-repo addon to configure inclusion of components/**/*.scss

---

ui-v2/app/services/logger.js
ui-v2/app/services/state.js

We've had a logger service that we've used for debug logging for a while, but we've never found a nice way to commit actual error logging into the production source, so we've edited in debug logging here when we've needed it.
Any calls to `runInDebug` are compiled out of production sourcecode, which make this ideal for what we need here.
Additionally we've commented out state transition logging for the moment for a less noisy console, ideally we'd be able to turn this on and off during development via cookies or similar, but this is best left for a future task/PR.

ui: Use runInDebug to add error logging to logger service

---

.changelog/8646.txt
agent/connect/ca/provider_consul_config.go
agent/connect/ca/provider_test.go
agent/connect/ca/provider_vault.go
agent/connect/generate_test.go
agent/structs/connect_ca.go
agent/structs/connect_ca_test.go

This PR moves the IntermediateCertTTL field into the common CA config so that it can be used in the Vault provider. The documentation sort of implied this was already the case, but it was actually a field specific to the Consul CA.

Move IntermediateCertTTL to common CA config

---

agent/http.go
agent/http_oss.go
ui-v2/config/environment.js
ui-v2/lib/startup/templates/head.html.js

This PR slightly modifies the way we pass through runtime configuration to the UI.
It's a precursor/cleanup before some larger changes to UI config.
The main motivation is to remove the inline script which should allow tighter CSP policies to be used with the UI.
Overall, this is both simpler and slightly more hacky than before however it removed the need for inline script and hopefulyl allows us to easily expand the number of config options we pass to the UI significantly without needing changes in multipele JS files and go files just to plumb template placeholders through.
There is a small Enterprise PR needed once this is merged to rename the method.

Update UI Config passing to not use an inline script

---

.changelog/8685.txt
agent/router/router.go

When calling `GetDatacentersByDistance()` or `GetDatacentersMap()`, an
incorrect condition was used to diplay log message, thus flooding
Consul's logs.
Example of message:
```
[WARN] agent.router: Non-server in server-only area: non_server=myClientNode area=lan
```
This message is only valid for WAN areas, filter to avoid creating
hundreds of logs/s on our custers, each time someone is calling this
method.
Our logs were flooded by such messages when migrating our Consul servers
from 1.7.7 to 1.8.4.
This will issue fix #8663

[BUGFIX] Avoid GetDatacenter* methods to flood Consul servers logs

---

website/pages/docs/agent/config-entries/ingress-gateway.mdx

Add configuration example for path-based HTTP routing with virtual services to Ingress gateway configuration entry documentation.
Resolves #8018

Add path-based routing example to Ingress docs

---

agent/consul/catalog_endpoint_test.go
agent/consul/health_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog_test.go
agent/dns_test.go
agent/user_event_test.go

There shouldn't be any functional changes in this diff, just updating tag names for database services in test files to be a bit friendlier.

test: update tag names for database services

---

agent/agent_test.go
agent/http_test.go
agent/testagent.go

In #8234 I changed a few tests to use TestAgent.HTTPAddr() to find the
addr used in the test. Due to the way HTTPAddr() was implemented these
tests were passing, but I think the pass was incidental. HTTPAddr() was
not matching any servers, and was instead returning the last server,
which happened to be the one these tests wanted.
This commit fixes the implementation of HTTPAddr to panic if no match
was found. The tests which require an HTTPS server are changed to use
a new `firstAddr()` function to look up the correct address.

http: fix tests incorrectly using HTTPAddr to get the address of the https server

---

agent/connect/ca/provider_consul.go
agent/consul/leader_connect.go
agent/consul/leader_connect_test.go
agent/structs/connect_ca.go

@freddygv and I investigated this infamous flaky test and we think we fixed it!

fix TestLeader_SecondaryCA_IntermediateRenew

---

website/pages/commands/connect/envoy.mdx

Document available CLI options for the `consul connect envoy` command.
Resolves #8041

docs: Add missing options for consul connect envoy

---

website/pages/docs/agent/options.mdx

Add examples of using a go-sockaddr template with `bind_addr` within HCL or JSON configuration.
Resolves #8633

docs: Add go-sockaddr examples for bind_addr

---

website/pages/commands/maint.mdx

Try to make it more clear to an operator that toggling off a node-level
maintenance is independent of toggling service level maintenance.
Recently, we had an outage and there was some confusion by the subtle distinction between node and service level maintenance. In particular, that invoking `consul maint -disable` _does not_ clear all current maintenance checks on the node and instead only affects the node-level check. This PR aims to make that more clear to our sleep deprived future selves.
Future idea, perhaps there is some argument to be had for having an `-all-services` flag.

[docs] Clarify consul maint enable/disable scope

---

.circleci/scripts/cherry-picker.sh

This PR will add the latest `backport/*` label to any PRs labeled with `type/docs-cherrypick` before looping through the labels and trying to cherry pick to each branch. This ensures that all docs are picked to the `stable-website` branch and to the latest release branch so we can force push the latest release branch over `stable-website` when we release.

[ci] cherrypick docs to latest release branch

---

.changelog/8704.txt
agent/ui_endpoint.go
agent/ui_endpoint_test.go

I am pretty sure this was an oversight, it should be the service datacenter here. I did not check for the other places, but will be.

use service datacenter for dns name

---

website/pages/docs/connect/ca/vault.mdx

Created example Vault ACLs for access needed by Consul Connect to use Vault as the CA for Connect.

Adding Vault ACL examples for Connect CA

---

ui-v2/node-tests/config/environment.js

We run some config/environment tests to test the correct configuration as been set for each of our different environments.
In https://github.com/hashicorp/consul/pull/8645 we changed how we pass through various production environment settings from the binary, so this updates the existing test as a result of that.
Extra things of note:
1. It doesn't look like we ever got around to adding these tests into CI, otherwise they would have failed as a result of https://github.com/hashicorp/consul/pull/8645.
2. e are currently discussing improved testing of production settings on the resulting UI artifact file itself. Until its clear how we are moving forwards with that, I've fixed up the code so that the tests pass, which whilst correct, it's questionable how useful these tests actually are now …

ui: Go back to expecting falsey values during config env tests

---

website/data/alert-banner.js
website/pages/docs/architecture/index.mdx

Just two commits that went through without the `docs-cherrypick` workflow enhancement wired up to pick them back to latest release too.
@alvin-huang It looks like merging PRs from external contributors (#8727) will always fail the `docs-cherrypick` workflow, is there any way around this or should we just manually backport?

1.8.x: manual backports from stable-website

---

website/pages/docs/discovery/checks.mdx

The page does not mention the existence of an `alias_node` option for alias check.
It is only mentioned briefly in the API documentation https://www.consul.io/api-docs/agent/check#aliasnode.

Add alias-node option info

---

agent/consul/state/catalog_test.go
agent/consul/state/state_store_test.go
agent/structs/structs_test.go

Thought I'd try go1.15 locally.
The only issue was go vet complaining about these conversions now which is caught by my pre-commit hook.
I've not officially updated the build version of Go in the build container or even the job that runs vet on PRs yet but I thought I'd fix these up for anyone using 1.15 locally.

Fix bad int -> string conversions caught by go vet changes in 1.15

---

agent/agent.go
agent/agent_endpoint.go
agent/agent_test.go
agent/consul/client.go
agent/consul/client_test.go
agent/consul/leader_test.go
agent/consul/options.go
agent/consul/server.go
agent/consul/server_test.go
agent/setup.go

The first commit is extracted from #8667. This change will be necessary once #8667 is merged and we start using the `ClientConnPool`.
In an upcoming change we will need to pass a grpc.ClientConnPool from
BaseDeps into Server. While looking at that change I noticed all of the
existing consulOption fields are already on BaseDeps.
Instead of duplicating the fields, we can create a struct used by
agent/consul, and use that struct in BaseDeps. This allows us to pass
along dependencies without translating them into different
representations.
I also looked at moving all of BaseDeps in agent/consul, however that
created a circular import. Resolving the cycles wouldn't be too
bad (it was only an error in agent/consul being imported from
cache-types), however this change seems a little better by …

agent: Repalce ConsulOptions with a new struct from agent.BaseDeps

---

command/maint/maint.go

Currently we call NodeName even when the information is not needed, this makes tokens for services to fail if they do not have permission to read the agent information. fix #8734

remove nodeName call when using -service

---

.changelog/8741.txt
agent/structs/connect_proxy_config.go
agent/structs/connect_proxy_config_test.go

agent: make the json/hcl decoding of ConnectProxyConfig fully work with CamelCase and snake_case

---

website/data/docs-navigation.js

Adds a link to Vault as Service Mesh Certificate Authority to the Integrations section of the docs.
@kaitlincarter-hc It looks like we don't really mention Vault as an RPC TLS Certificate Authority in https://www.consul.io/docs/security/encryption#rpc-encryption-with-tls, should we add a short section there? The Learn tutorial linked from there mentions Vault as an option but doesn't use it.

docs: Highlight Vault integration points

---

.changelog/8745.txt
agent/consul/server.go

This generic replicator code is used for 3 places: config entries, federation states, and enterprise stuff. This gets all 3 variants to  actually log all of their components with the appropriate prefixes:
```
server.replication.config_entry: finished fetching config entries: amount=0
server.replication.config_entry: Config Entry replication: local=0 remote=0
server.replication.config_entry: Config Entry replication: deletions=0 updates=0
server.replication.config_entry: replication completed through remote index: index=1
server.replication.federation_state: finished fetching remote objects: amount=1
server.replication.federation_state: diffing replication state: local_amount=0 remote_amount=1
server.replication.federation_state: diffed replication state: deletions=0 updates=1 …
```

server: make sure that the various replication loggers use consistent logging

---

.changelog/8747.txt
agent/agent.go
agent/agent_test.go
agent/service_manager.go

Likely introduced when #7345 landed.
The backport to 1.8.x is clean but the 1.7.x has conflicts in test code (https://github.com/hashicorp/consul/pull/8748).

agent: when enable_central_service_config is enabled ensure agent reload doesn't revert check state to critical

---

website/pages/docs/install/cloud-auto-join.mdx

Update the Azure cloud-auto-join documentation with more information on the configuration of the Azure resources that need to be applied to make the auto-join feature work. 
Linked to #8432.

Improve the Azure cloud auto join documentation

---

website/pages/docs/discovery/services.mdx

Just a small typo I noticed when ready the docs.

Fix typo in Service Discovery/Services documentation

---

.changelog/8747.txt
agent/agent.go
agent/agent_test.go
agent/service_manager.go

`release/1.7.x` backport of https://github.com/hashicorp/consul/pull/8747
There are conflicts just in the test code.

[backport/1.7.x] agent: when enable_central_service_config is enabled ensure agent reload doesn't revert check state to critical

---

.changelog/8704.txt
agent/ui_endpoint.go
agent/ui_endpoint_test.go

Manually backport these to 1.8.x:
- https://github.com/hashicorp/consul/pull/8704
- https://github.com/hashicorp/consul/pull/8750

[backport/1.8.x]: use service datacenter for dns name

---

.changelog/8726.txt
agent/checks/grpc.go

Hi there!
This PR adds serving status to gRPC health check errors, because sometimes it's not clear what causes a failure, `SERVICE_UNKNOWN` due to misconfiguration or `NOT_SERVING` when a service is shutting down.

Return grpc serving status in health check errors

---

.changelog/8764.txt
api/config_entry.go
api/config_entry_discoverychain.go
api/config_entry_discoverychain_test.go
api/config_entry_gateways.go
api/config_entry_gateways_test.go
api/config_entry_test.go

Fixes #8755
Since I was updating the interface, i also added the missing `GetNamespace()`.
Depending upon how you look at it, this is a breaking change since it adds methods to the exported interface `api.ConfigEntry`. Given that you cannot define your own config entry kinds, and all of the machinery of the `api.Client` acts like a factory to construct the canned ones from the rest of the module, this feels like it's not a problematic change as it would only break someone who had reimplemented the `ConfigEntry` interface themselves for no apparent utility?

api: support GetMeta() and GetNamespace() on all config entry kinds

---

.circleci/config.yml
GNUmakefile
ui-v2/app/components/hashicorp-consul/index.hbs
ui-v2/config/environment.js

This PR auto updates `agent/bindata_assetfs.go` if there is a diff of the file built from a new master commit.
This is blocked by generating correct fingerprints for the dist/ javascript files and I will talk to @johncowen about this. I have fixed the other source of diff errors which is setting a static modtime to epoch 1.

ci:add check for bindata_assetfs changes

---

.circleci/config.yml

The git diff logic was wrong. It should commit a new file if there _are_ changes rather than _aren't_.

commit a new bindata file if there are changes

---

.circleci/config.yml

Previously we hadn't saved the `dist/` folder to the CircleCI workspace since we weren't doing anything with it downstream. Now that we do save it (to auto-publish), the tarball will contain those files. This PR will only tar up the `consul` binary itself which is all we care about.

ci: only add consul binary to dev tarball

---

.changelog/8786.txt
agent/consul/server.go

This really only matters for unit tests, since typically if an agent shuts down its server, it follows that up by exiting the process, which would also clean up all of the networking anyway.

server: ensure that we also shutdown network segment serf instances on server shutdown

---

ui-v2/app/routes/dc/services/show.js

Following the latest ember upgrade to 3.20 (https://github.com/hashicorp/consul/pull/8761), we noticed that certain variable access within handlebars templates no longer seem to be safe in that accessing a property of something that is `undefined` now throws an error - similar to what you would expect in javascript.
We have some strange cases where we use Ember Proxy objects to pass data around, the contents of these proxy objects can be null/undefined but a property containing the object will obviously not be `undefined`, therefore we check a property of the object to see if it is undefined/falsey instead of the the root property itself (in this case we check `chain.Chain` instead of just `chain`).
There are some areas where a property can be actually `undefined` instead of one of these …

ui: Initialize chain variable to null

---

ui-v2/app/styles/base/components/tabs/layout.scss
ui-v2/app/styles/routes/dc/services/index.scss

Fix up tab separator CSS to only apply to instance tabs.
Note the double thickness line between sections:
Before:
After:

ui: Fix up tab separator CSS to not apply to all tabs

---

.circleci/config.yml
GNUmakefile
agent/agent.go
agent/agent_test.go
agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/flags.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/http.go
agent/http_oss.go
agent/http_test.go
agent/reload.go
agent/testagent.go
agent/ui_endpoint_test.go
agent/uiserver/buf_index_fs.go
agent/uiserver/buffered_file.go
agent/uiserver/redirect_fs.go
agent/uiserver/ui_template_data.go
agent/uiserver/ui_template_data_oss.go
agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go
build-support/functions/20-build.sh
build-support/functions/30-release.sh
build-support/functions/40-publish.sh
codecov.yml
logging/names.go
ui-v2/config/environment.js
ui-v2/lib/startup/templates/head.html.js

This PR adds new configuration for the UI to support up-coming work on integrating metrics. None of the new configurations do anything yet this is just the wiring for them. Building the features will come in subsequent PRs.
Following the checklist in `/contributing`:
translate.
`TestFullConfig` in `agent/config/runtime_test.go`, it should fail now, then
add the same random value to the expected struct in that test so it passes
again.
file. (Running the test first gives you a nice diff which can save working
out where etc.)
some cases or with some values (often true).
`agent/config/runtime_test.go`.
`agent/config/runtime_test.go`.
any state the feature needs changing. This needs to be added to one or
more of the following places:
- …

Add config changes for UI metrics

---

ui-v2/app/templates/dc/services/instance/healthchecks.hbs
ui-v2/tests/acceptance/dc/services/instances/show.feature
ui-v2/tests/pages/dc/services/instance.js

This PR moves the healthchecks listing to a true combined list sorted by health, critical first.

ui: Show service and node checks as a merged list sorted by health

---

agent/consul/fsm/fsm.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/state/memdb.go
agent/consul/state/state_store.go
agent/consul/state/store_integration_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go

These commits are extracted from #8766 
The changes are small refactors in the `state` and `stream` packages to export some things that will be needed for the subscribe service, and to use protobuf types for enums (Topic and CatalogOp). We could create our own local types and test that the mapping between them is correct and complete, but for now we already have a dependency on protobuf from the `state` package, so it is probably easier to use the protobuf types. In the future it should be relatively easy to change it if we want to remove the dependency.

state: use protobuf Topic and and export payload type

---

.circleci/config.yml
GNUmakefile
ui-v2/app/components/hashicorp-consul/index.hbs
ui-v2/config/environment.js

Unfortunately, the way of checking for bindata diff I had in #8712 doesn't work. While @johncowen helped me with removing the sha from the index.html file and we changed the modtime to be static, there is a [temp directory](https://github.com/broccolijs/broccoli-persistent-filter#warning) that broccoli creates and uses when processing files that cannot be static (the tempdir can be specified but not the actual temp directory that is created in the tempdir).  Each UI build will always generate a random suffix and this create a diff when comparing the bindata files. 
A sample diff is here:
```
< var t=Ember.HTMLBars.template({id:"XjHn8fr1",block:'{"symbols":[],"statements":[[8,"head-layout",[],[[],[]],null],[2,"\\n"],[1,[30,[36,9],["Consul"],[["separator","_deprecate"],[" - …
```

ci: fix bindata autoupdate

---

ui-v2/app/routes/dc/services/show.js
ui-v2/app/routes/dc/services/show/services.js
ui-v2/app/routes/dc/services/show/upstreams.js
ui-v2/app/templates/dc/services/show.hbs
ui-v2/app/templates/dc/services/show/services.hbs
ui-v2/app/templates/dc/services/show/upstreams.hbs

This PR defers loading data for required for ingress and terminating gateways until the tab used to display them is actually visible. The data for both the `dc.services.show.services` and `dc.services.show.upstreams` is exactly the same, we just call it different things and present it differently, so we chose to use one Route to inherit from the other.

ui: Defer requesting gateway related services until the tab is visible

---

ui-v2/app/styles/base/components/table/layout.scss
ui-v2/app/styles/components/app-view.scss
ui-v2/app/styles/components/app-view/index.scss
ui-v2/app/styles/components/app-view/layout.scss
ui-v2/app/styles/components/app-view/skin.scss
ui-v2/app/styles/components/definition-table/layout.scss
ui-v2/app/styles/components/filter-bar/layout.scss
ui-v2/app/styles/layout.scss
ui-v2/app/styles/typography.scss

This PR contains a variety of small tweaks to get the space and borders between the headers and the content or the tabs bar and the content closer to what is specified in the designs we have. 
[Preview Link](https://deploy-preview-8796--consul-ui-staging.netlify.app/ui/)
1. Lists of things are now generally flush up to the filter bar above it.
2. Filter bar and header borders are now 1px not 2px.
I wasn't entirely sure where these should live as they are all kind of related yet spread across components. For the moment at least layout.scss was what I went with.
We also spotted a small copy-button positioning bug in the ACLs area which we fixed up whilst we were here.

ui: CSS margin/border alterations

---

website/pages/docs/k8s/helm.mdx

I've compared Helm values against the latest release (`0.24.1`) rather than master. I'll create a separate PR for missing values from the consul-helm `master` branch.

docs: Add missing helm docs and make link anchors consistent

---

agent/auto-config/auto_config.go
agent/auto-config/auto_config_test.go
agent/auto-config/auto_encrypt.go
agent/auto-config/auto_encrypt_test.go
agent/auto-config/config.go
agent/consul/replication.go
lib/retry/retry.go
lib/retry/retry_test.go

This PR extracts a new package (`lib/retry`) from `lib`. Large packages like `lib` suffer from weak cohesion. They provide many unrelated things making them hard to use.
This PR also changes `Waiter` to reduce the number of exported methods, and make it easier to use.
Export fields so that the caller doesn't have to define constants that are only ever used once. For example:
```go
// it's not really clear what all of these numbers are doing
retry.NewWaiter(1, 0, 10*time.Minute, retry.NewJitter(25))
```
Some callers may choose to make these constants, but they are likely only ever used once. Instead we can have callers set fields on the struct. The field names document how the values will be used:
```go
w := &Waiter{
MinFailures: 1,
MinWait:     0,
MaxWait:     10*time.Minute,
Jitter: …
```

lib/retry - extract a new package from lib/retry.go

---

ui-v2/app/serializers/application.js
ui-v2/app/services/client/http.js
ui-v2/app/services/data-source/protocols/http/blocking.js
ui-v2/app/utils/dom/event-source/blocking.js

Our DataSource service/components allow us to visualize live data in the page using blocking queries - which depend on API endpoints which support blocking queries.
It would be nice to be able to use the same Datasources for endpoints that don't support blocking queries, so here we've added support for polling Datasources, that work the same way as the blocking ones.
Enabling polling on an endpoint requires setting a `Refresh: 30` (30 second poll) HTTP header in the adapter method for the endpoint you would like to poll.

ui: Allow configuring a Datasource to poll an API endpoint instead of using Blocking Queries

---

ui-v2/app/components/consul-service-instance-list/index.hbs
ui-v2/app/routes/dc/services/show.js

In https://github.com/hashicorp/consul/pull/8775 we replaced the icon and wording we use to show that a Service is available via a proxy. This makes a similar change to Service Instances, although here I don't think we can currently tell whether an instance is fronted with ingress/terminating gateways, so we just change the icon and wording for 'connected with proxy' to 'in service mesh with proxy'

ui: Replace proxy icon with mesh icon

---

ui-v2/node-tests/config/environment.js

In https://github.com/hashicorp/consul/pull/8710 we changed the node tests to reflect the changes made for https://github.com/hashicorp/consul/pull/8710.
This changes things back to use check for the strings that are replaced at runtime.

ui: Fixup node tests to account for new runtime env var passing

---

ui-v2/app/styles/routes/dc/services/index.scss

During https://github.com/hashicorp/consul/pull/8796 we altered top/margins borders across the app. One of the changes there caused a CSS slight issue on the Healthchecks tab:
Before:
After:

ui: Restrict header styling to specific tabs

---

ui-v2/app/adapters/proxy.js
ui-v2/app/adapters/service-instance.js

All our Service instance requests and Proxy (which are actually proxy instances) 'query' requests only return a subset or range of instances, therefore they should not reconcile the ember-data store on response. If they do the ember-data will think that all other instances have been removed from the backend.
In order to mark a request to expect a subset or range as a response, we add the `X-Range` header, this prevents the reconciliation from happening.

ui: Specify Service instance requests and proxy requests as ranges

---

proto/pbservice/convert_test.go

Using the default value for now, with a TODO to restore the random value once namespace support is added.

proto: fix RoundTrip test for enterprise

---

.changelog/8703.txt
agent/consul/fsm/commands_oss.go
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/system_metadata.go
agent/consul/state/system_metadata_test.go
agent/consul/system_metadata_test.go
agent/structs/structs.go
agent/structs/system_metadata.go

This adds a new very tiny memdb table and corresponding raft operation
for updating a very small effective map[string]string collection of
"system metadata". This can persistently record a fact about the Consul
state machine itself.
The first use of this feature will come in a later PR.

server: create new memdb table for storing system metadata

---

agent/agent.go
agent/dns.go
agent/health_endpoint.go
agent/rpcclient/health/health.go

This new package provides a client agent implementation of an interface
for fetching the health of services. Currently the HTTP API and DNSServer
use the concrete type, however in the future (ex: #8624) we should introduce
interfaces for these types to accept their dependencies, which will allow us
to pass a different implementation on the Server.
This approach has a number of benefits:
1. It provides a much more explicit interface. Instead of everything
dependency on `RPC()` and `Cache.Get()` for many unrelated things
they can depend on a type that are named according to the behaviour
it provides.
2. It gives us a single place to vary the behaviour and migrate to
a new form of RPC (gRPC). The current implementation has two options
(cache, or direct RPC), and in the future we will have …

rpcclient: Add health.Client and use it in http and dns

---

.github/workflows/issue-labeler.yml

Issue labeler runs on edit of the first post. This can happen due to formatting, or simply updating the body.
Turns this to running on labels on when opened.

Remove label trigger on edit

---

.circleci/config.yml

This PR adds a CircleCI job to run `make test-node` in the UI tests. This is separate from all the ember tests we run. An example run can be found [here](https://app.circleci.com/pipelines/github/hashicorp/consul/13107/workflows/be2da824-8a0c-4b4a-823c-4dd12bee85a1) and the failing tests should be fixed by #8817. 
The output right now is only in the CircleCI log output so if we want the errors to bubble up in the CircleCI UI then we will need a package that turns the tape output into XML that CircleCI can parse. I found two libraries that can do this: [tape-junit](https://github.com/bvalosek/tape-junit) and [tap-junit](https://github.com/dhershman1/tap-junit)

ui: add ui test-node

---

ui-v2/app/components/consul-service-search-bar/index.hbs
ui-v2/app/filter/predicates/service.js
ui-v2/app/models/service.js

In https://github.com/hashicorp/consul/pull/8775 we added support for new properties on our API endpoints (ConnectedWithGateway and ConnectedWithProxy). This uses those new properties for filtering instead of inferring it from the `Kind` of Service or inspecting the `Proxy` of the Service.

ui: Fix up Service filtering by whether a Service is in the mesh or not in the mesh

---

.github/workflows/pr-labeler.yml

This tunes the PR labeler to only run on create. The previous setting is shorthand for "all things related to pull request"

Turns PR labeler to only trigger on create

---

.circleci/config.yml
GNUmakefile

This should enable code coverage reporting for the Connect CA providers integration test job, we discovered this was missing when looking at coverage in #8862

test(vault): generate test coverage and upload to CodeCov

---

agent/consul/state/store_integration_test.go
agent/consul/stream/event.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/subscription.go
agent/consul/stream/subscription_test.go
agent/rpc/subscribe/logger.go
agent/rpc/subscribe/subscribe.go

Branched from #8768 
This changes the return value of `Subscription.Next()` to return an `Event` instead of `[]Event`. By batching up the events earlier we can simplify the caller a bit.
It also moves filtering to be a method on `Event` so that both ACL filtering and `SubscribeRequest.Key` filtering can use the same mechanism, and benefit from the same optimizations.

stream: handle batch events as a special case of Event

---

agent/cache-types/streaming_events_test.go
agent/cache-types/streaming_health_services.go
agent/cache-types/streaming_health_services_test.go
agent/cache-types/streaming_materialized_view.go
agent/cache-types/streaming_test.go
agent/cache/cache.go
agent/cache/cache_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go
agent/submatview/handler.go
agent/submatview/materializer.go

Builds on #8799 #8768 #8802
Adds a new cache-type which uses streaming to populate a materialized view. Values for the cache come from the materialized view.

Add StreamingHealthServices cache-type

---

ui-v2/app/components/consul-nspace-list/index.hbs
ui-v2/app/services/repository/nspace.js

Namespace deletion is more of a soft delete, therefore the namespace can still exist once we've requested a delete/removal, and depending on timing ember-data can sometimes throw an error due to the UI trying to update the 'DeletedAt` property on a object that ember-data is trying to delete (if the delete request responds after the blocking query unblocking due to the delete change).
This PR makes `repo.remove` use a custom request rather than the default ember-data delete, this means we can bypass all the things that ember-data does to mark things as deleting/deleted - essentially turning the delete request into an update.
We also hide the Actions button whilst a namespace is being deleted here, so you can't try editing/deleting the namespace or once its marked for deletion.

ui: Use a custom request for nspace deletion

---

agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

Chained off of: #8853
This PR updates the `service-topology` chain to account for Ingress Gateways. Now whenever the gateway-service mappings are updated, we also update the mesh topology table.
This is so that ingress gateways can show up in the mesh visualization either as downstreams or the target service.

Support ingress gateways in mesh viz endpoint

---

ui-v2/app/components/topology-metrics/down-lines/index.hbs
ui-v2/app/components/topology-metrics/down-lines/index.js
ui-v2/app/components/topology-metrics/icon.hbs
ui-v2/app/components/topology-metrics/index.hbs
ui-v2/app/components/topology-metrics/index.js
ui-v2/app/components/topology-metrics/skin.scss
ui-v2/app/components/topology-metrics/up-lines/index.hbs
ui-v2/app/components/topology-metrics/up-lines/index.js
ui-v2/app/helpers/service/intention-permissions.js
ui-v2/package.json
ui-v2/tests/integration/helpers/service/intention-permissions-test.js
ui-v2/yarn.lock

Use Cases:
1. If intention is set to deny between services, the SVG lines is red with an icon.
2. If intention is set with L7, the line remains gray but has a L7 icon.
New contextual components:
- TopologyMetrics::Icon
- TopologyMetrics::UpLines
- TopologyMetrics::DownLines

ui: Add deny SVG lines with icons

---

.github/pr-labeler.yml

This label should never be auto-applied to prevent accidentally publishing docs intended for a major release early.

chore(ci): remove docs-cherrypick autolabel

---

agent/uiserver/testdata/bar.js
agent/uiserver/testdata/compiled-metrics-providers-golden.js
agent/uiserver/testdata/foo.js
agent/uiserver/ui_template_data.go
agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go
ui-v2/lib/startup/templates/body.html.js

This PR builds on #8694 and implements the JS provider serving component for the UI.
- All documentation for the new config and features is deferred until they are implemented as things might change but I want to keep PRs small and incremental.

Add support for serving additional metrics provider JS in the UI

---

agent/http.go
agent/http_register.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go
agent/uiserver/testdata/bar.js
agent/uiserver/testdata/compiled-metrics-providers-golden.js
agent/uiserver/testdata/foo.js
agent/uiserver/ui_template_data.go
agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go
logging/names.go
ui-v2/lib/startup/templates/body.html.js

This PR builds on #8743 and adds a proxy endpoint to allow the UI to request metrics from a configured backend.
I spent a while trying to make sure this was safe against path traversals, before realising in the tests that path traversals that would be dangerous are impossible currently since they'd already have been handled by the API mux before they get to the new proxy handler anyway.
I left the code and tests in though both to be warned/prepared in case that behaviour ever changes and to document the risk.

Add UI metrics proxy

---

ui-v2/app/styles/components/app-view/layout.scss
ui-v2/app/styles/components/breadcrumbs.scss
ui-v2/app/styles/layout.scss

In https://github.com/hashicorp/consul/pull/8796/files#diff-c3972e12e254fd8bc979a2b524c085bbR3 we moved `%app-view` to be extended by `.app-view` itself rather than `main`, unfortunately this altered some positioning.
This PR puts things back as they were in regard to positioning.

ui: Fix up positioning of subpage loader animation

---

ui-v2/app/components/consul-intention-form/fieldsets/layout.scss
ui-v2/app/components/radio-card/index.hbs

It seems problematic to try to set an inputs value attribute to `value=""` (empty) in Firefox with Ember, this worksaround the problem.

ui: Workaround FF and/or ember problem, trying to set a value=""

---

.changelog/8875.txt
agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

This is the recommended proxy integration API for listing intentions
which should not require an active connection to the servers to resolve
after the initial cache filling.

agent: allow the /v1/connect/intentions/match endpoint to use the agent cache

---

ui-v2/config/environment.js
ui-v2/node-tests/config/environment.js

This file was actually different in ent vs oss, despite supposedly being an oss file. The ent copy was more correct so i've corrected it here.

ui: fix the namespace flag

---

agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go
agent/structs/structs.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

This PR adds the protocol for the queried service, and is resolved from config entries.
@banks does it make sense for an ingress gateway to have a single protocol when it can have listeners for TCP and HTTP?
Need to fix the chained PR dance, only this commit is relevant: [`d32fda6` (#8868)](https://github.com/hashicorp/consul/pull/8868/commits/d32fda6c7c6a831e69b2698af880378cf60fd141)

Add protocol to the topology endpoint response

---

.changelog/8774.txt
agent/connect_ca_endpoint.go
agent/connect_ca_endpoint_test.go
website/pages/api-docs/connect/ca.mdx

The `v1/connect/ca/roots` endpoint has picked up a `pem=true` argument. When set this causes the endpoint to output data with a `Content-Type` set to `application/pem-certificate-chain` and the response body to be a PEM encoded certificate chain of all root and intermediate certs that would normally be contained in the response.
This output format can be useful in situations where you need a certificate bundle for passing off to another application such as the Consul CLI when they will interact with an API presenting behind a Connect CA signed TLS cert (such as when `auto_encrypt` or `auto_config` are used for generating a Consul clients HTTPs certificate).

Add capability for the v1/connect/ca/roots endpoint to return a PEM encoded certificate chain

---

ui-v2/app/components/consul-service-list/index.hbs
ui-v2/app/models/service.js

Not returning instances count for ingress and terminating gateways. Also, I removed a model attribute we no longer use.

ui: Update instances count for ingress and terminating gateways

---

agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/consul/usagemetrics/usagemetrics_test.go

Previously, we would emit service usage metrics both with and without a
namespace label attached. This is problematic in the case when you want
to aggregate metrics together, i.e. "sum(consul.state.services)". This
would cause services to be counted twice in that aggregate, once via the
metric emitted with a namespace label, and once in the metric emited
without any namespace label.

Emit service usage metrics with correct labeling strategy

---

website/pages/docs/nia/installation/requirements.mdx

For partners that we don’t have Terraform modules from yet, we’ll remove their sections for now and add back as we have links to modules.

Remove empty partner module sections

---

.circleci/config.yml
agent/cache-types/connect_ca_leaf.go
agent/cache-types/connect_ca_leaf_test.go
agent/cache-types/norace_test.go
agent/cache-types/race_test.go
agent/cache-types/testing.go
agent/grpc/stats_test.go

Adds a bunch more packages to the list we test in `go-test-race`. Also fixed a couple race problems in the new grpc tests, and skipped a couple tests in `cache-types` so that we can run the race detector against the rest of them.

ci: go test -race more packages

---

agent/rpc/subscribe/subscribe.go
agent/rpc/subscribe/subscribe_test.go
agent/user_event.go

Follow up to #8768
Adds `runStep` to the longer integration tests of the the subscribe rpc endpoint, as suggested by @kyhavlov . This should make the tests easier to read. It should also make them easier to debug when they fail, as the context about what is happening will be part of the test name.
Also adds new test cases for `newEventFromStreamEvent` to resolve a TODO. The convert function for `CheckServiceNode` is already well tested, so these new tests only cover converting the Events.

subscribe: add steps to long test cases, and add new cases for converting Events

---

.changelog/note.tmpl

This note template won't render the link to the github issue if the filename is prefixed with an underscore `_`. This is useful for enterprise changelog entries. Uses new functionality from https://github.com/hashicorp/go-changelog/pull/4.

go-changelog template with ent support

---

website/pages/docs/agent/options.mdx

adds missing options.mdx entry for telemetry {disable_compat_1.9}

---

.changelog/8731.txt
agent/consul/leader.go
agent/consul/leader_test.go

In Serf Tags, entreprise members being non-voters use the tag
`nonvoter=1`, not `non_voter = false`, so non-voters in members
were wrongly displayed as voter.
Demonstration:
```
consul members -detailed|grep voter
consul20-hk5 10.200.100.110:8301   alive   acls=1,build=1.8.4+ent,dc=hk5,expect=3,ft_fs=1,ft_ns=1,id=xxxxxxxx-5629-08f2-3a79-10a1ab3849d5,nonvoter=1,port=8300,raft_vsn=3,role=consul,segment=<all>,use_tls=1,vsn=2,vsn_max=3,vsn_min=2,wan_join_port=8302
```

Consul Service meta wrongly computes and exposes non_voter meta

---

ui-v2/app/styles/components/app-view.scss
ui-v2/app/styles/components/buttons.scss
ui-v2/app/styles/components/list-collection.scss
ui-v2/app/styles/components/tabular-collection.scss
ui-v2/app/styles/layout.scss
ui-v2/app/styles/variables/custom-query.scss

This PR removes a bunch of CSS that is no longer used, and replaces our old style 'target this route' to the our new style (.template vs data-route)
I also spotted an issue with horizontal scrolling on our list views so I fixed that up here also.

ui: CSS amends

---

.changelog/note.tmpl
.circleci/config.yml
CHANGELOG.md
version/version.go

Had to make a minor change to the `note.tmpl` syntax to get go-changelog to run successfully.

chore: merge 1.9.0-beta1 release branch back in

---

website/pages/docs/k8s/helm.mdx

Openshift + remaining Helm value docs from community PRs, as well as `syncCatalog.consulNodeName`.

docs: add Helm docs for openshift; also add other missing Helm docs

---

.github/pr-labeler.yml

There's another docs page related to NIA `website/pages/docs/integrate/nia-integration.mdx`. This PR includes it to the bot labler. 
Related context: https://github.com/hashicorp/consul/pull/8925

Include integration docs for NIA with consul-terraform-sync label

---

website/pages/downloads/index.jsx

How to do this completely changed in the web replatforming, should verify intended functionality from the Netlify preview deployment.

website: add v1.9.0-beta1 download callout

---

website/pages/docs/agent/options.mdx
website/pages/docs/connect/ca/vault.mdx

Adds a note about the new auto-renew behavior for the Vault token used by the Connect CA to the docs.

docs: Add a note about auto-renewing the Vault token

---

.changelog/8221.txt
CHANGELOG.md

I think there's something subtly off with the automagic changelog formatter that causes this.

fix 1.9.0-beta1 changelog formatting

---

ui-v2/public/robots.txt

The path pattern specified in allow / deny lines should start with a forward slash to designate the root.
[1] https://tools.ietf.org/html/draft-koster-rep-00#section-2.2
[2] https://developers.google.com/search/reference/robots_txt#group-member-rules

Fix robots.txt to disallow indexing of all paths

---

test/integration/connect/envoy/run-tests.sh

In local testing this sped up the `stop_services` call from 11s to 1s per test.

speed up envoy integ tests by not politely stopping containers before destroying them

---

ui-v2/package.json
ui-v2/yarn.lock

This removes some {{-in-element}} deprecation errors.
`ember-basic-dropdown` is causing the errors, which is pulled in via `ember-power-select`, updating the later doens't fix the errors, so we've temporarily used resolutions to bump the former. Both upgrades are patch releases so should be fairly ok.

ui: Upgrade ember-power-select and ember-basic-dropdown

---

ui-v2/app/routes/dc/services/show/services.js

This fills in a missing parameter name when calling the `gateway-services-nodes` endpoint and prevents a 400 error when visiting an gateway detail page.

ui: [BUGFIX] Fixup gateway services API call

---

ui-v2/app/components/consul/intention/components.scss
ui-v2/app/components/consul/intention/form/fieldsets/index.hbs
ui-v2/app/components/consul/intention/index.scss
ui-v2/app/components/consul/intention/list/components.scss
ui-v2/app/components/consul/intention/list/layout.scss
ui-v2/app/components/consul/intention/list/table/index.hbs
ui-v2/app/components/consul/intention/permission/list/index.hbs
ui-v2/app/components/consul/intention/search-bar/index.hbs
ui-v2/app/components/consul/intention/search-bar/index.scss
ui-v2/app/styles/base/components/pill/layout.scss
ui-v2/app/styles/components.scss
ui-v2/app/styles/components/pill.scss
ui-v2/app/styles/components/popover-select.scss

This changes some of the copy we use to use the phrase `App aware` instead of L7.
As well as this we also took the opportunity to move the intention related CSS into the `consul/intention` component folder.

ui: Change text around L7 permissions to app aware

---

ui-v2/app/components/topology-metrics/series/index.js
ui-v2/package.json
ui-v2/yarn.lock

This PR removes `ember-d3` in favour of specifying d3 using standard JS dependencies instead (ember-d3 was probably previous to ember-auto-import usage)
We install d3 v2 and upwards here so we had to switch out `mouse` usage for `pointer` usage instead which seems to be the replacement. Other than that everything seems to work as before.
Lastly, we also moved `dayjs` into devDependencies as per ember conventions.

ui: Depend on less D3

---

ui-v2/app/components/outlet/index.js

Previously we removed the routeName and left the nspace value, where we should have been removing the nspace value and leaving the routeName

ui: Remove nspace value from routeName

---

.circleci/config.yml
ui-v2/config/environment.js
ui-v2/config/utils.js
ui-v2/node-tests/config/environment.js
ui-v2/node-tests/config/utils.js

Our environment JS file has gradually got a little messy over time. This PR cleans it up a little, externalizes and adds some tests (mainly for documentation purposes) to the couple of utilities we use in a way that is `prettier` resistant (some of our ternary conditions we were using were a little long), and adds a bunch more documentation/explanatory text as to how things work here.
The one and only path based variable is hoisted to the top of the file so its obvious to change when we need to.
Overall the environment file is now a little less horrible.
cc @alvin-huang just incase as I added an explicit variable into the CI config. I'm sure its fine but just incase.

ui: Clean up and document environment.js file

---

ui-v2/app/components/topology-metrics/index.js
ui-v2/app/components/topology-metrics/series/index.hbs
ui-v2/app/components/topology-metrics/series/index.js
ui-v2/app/components/topology-metrics/series/layout.scss
ui-v2/app/components/topology-metrics/series/skin.scss
ui-v2/app/services/repository/metrics.js
ui-v2/vendor/metrics-providers/prometheus.js

This PR has a few things in:
The main thing is a refactor of the metics provider interface to make it a but less clunky to meet the strict requirements of the actual stacked series graphs we show. This format makes it more explicit that we need stacked values with same timestamps on same scale etc to be able to show them meaningfully.
This refactor depends on https://github.com/hashicorp/consul-api-double/pull/44.
This also changes the format for labels and descriptions the provider returns which enabled both a cleaner tooltip with more detailed modal to allow full description of the metrics being shown for quick reference without cluttering up the tooltip.
The provider currently hard codes the proxy endpoint so should per our own provider docs inline throw if that isn't configured. I've …

Refactor metrics provider interface for time series.

---

website/pages/docs/connect/ca/index.mdx

Consul's Connect CA documentation mentions future releases will support a pluggable CA system. This sentence has existed in the docs for over two years, however there are currently no plans to develop this feature on the near-term roadmap.
This commit removes this sentence to avoid giving the impression that this feature will be available in an upcoming release.

docs: Remove sentence about pluggable CAs

---

.changelog/8771.txt
agent/http_decode_test.go
agent/structs/check_definition.go
agent/structs/check_type.go

Currently HTTP APi doesn't recognize snake-cased `grpc_use_tls` option whereas loading from a config file works as expected, this fixes the following: 
```
curl -X PUT -d '{
"name": "test",
"port": 6060,
"check": {
"grpc": "127.0.0.1:8080/test",
"grpc_use_tls": true,
"interval": "5s"
}
}' http://127.0.0.1:8500/v1/agent/service/register
Request decode failed: json: unknown field "grpc_use_tls"
```
I know there was a lot of copy-pasting just to make it work :cry: probably it can be improved later for all fields.
Can be worked around now: `"GRPCUseTLS": true`

Fix GRPCUseTLS flag HTTP API mapping

---

agent/router/manager_internal_test.go

I was reading over `refreshServerRebalanceTimer` attempting to understand the delay that it calculates based on some common cluster configurations. I found it very difficult to understand because the test was only making very weak assertions about the values.
It only checked a minimum value making it look like the value was always random (because of the jitter), but in some cases the value is not random at all, it can be known ahead of time. 
This PR improves the test by:
* assert an exact value when possible
* check the maximum bound when a random value is used
* make the two cases (exact, or random range) more explicit in the test cases by excluding the random range. There is only ever 1 random range (2min-3min), so we can omit it  in the test cases to make it more obvious when the …

agent/router: improve  the test for refreshServerRebalanceTimer

---

website/pages/docs/k8s/helm.mdx

Document `client.extraEnvironmentVars`, `server.extraEnvironmentVars`, and `client.affinity` Helm chart values.
Remove deprecated `connectInject.imageEnvoy` and `meshGateway.imageEnvoy` values.

Add extraEnvVars and client.affinity to Helm values

---

.changelog/8924.txt
agent/agent.go
agent/agent_test.go

When a service is deregistered, we check whever matching services were
registered as sidecar along with it and deregister them as well.
To determine if a service is indeed a sidecar we check the
structs.ServiceNode.LocallyRegisteredAsSidecar property. However, to
avoid interal API leakage, it is excluded from JSON serialization,
meaning it is not persisted to disk either.
When the agent is restarted, this property lost and sidecars are no
longer deregistered along with their parent service.
To fix this, we now specifically save this property in the persisted
service file.

Fix: service LocallyRegisteredAsSidecar property is not persisted

---

agent/router/manager.go
agent/router/manager_internal_test.go
agent/router/router.go

Branched from #8970
This change attempts to make the delay logic more obvious by:
* removing indirection, inline a bunch of function calls
* move all the code and constants next to each other
* replace the two constant values with a single value
* reword the comments
To anyone reviewing this change:
Do the new names and comments help you understand how this works?
Did I miss anything relevant from the old comments that should be included?

agent/router: refactor calculation of delay between rebalances.

---

test/integration/connect/envoy/case-badauthz/capture.sh
test/integration/connect/envoy/case-badauthz/verify.bats
test/integration/connect/envoy/case-http-badauthz/capture.sh
test/integration/connect/envoy/case-http-badauthz/verify.bats
test/integration/connect/envoy/helpers.bash

There is a delay between an intentions change being made, and it being
reflected in the Envoy runtime configuration. Now that the enforcement
happens inside of Envoy instead of over in the agent, our tests need to
explicitly wait until the xDS reconfiguration is complete before
attempting to assert intentions worked.

fix flaky envoy integration tests involving intentions

---

.circleci/config.yml

The UI was moved to a new workspace folder structure in https://github.com/hashicorp/consul/pull/8994 and therefore the  build is not in `pkg/dist/` but `pkg/packages/consul-ui/dist/` instead.

move static-assets dist to new path

---

ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/skin.scss
ui/packages/consul-ui/app/routes/dc/services/show.js
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
ui/packages/consul-ui/app/templates/settings.hbs
ui/packages/consul-ui/lib/startup/templates/head.html.js
ui/packages/consul-ui/tests/acceptance/dc/services/show.feature

- Created some development configurations for running the metrics locally. 
- Updated the links in Topology tab to link to prometheus links from the config_ui configurations. 
- Updated the link to configure metrics to redirect to our documentation. 
- Removed the Dashboard Links sections out of Setting page.

ui: Update Topology metrics dashboard and configuration links

---

ui/packages/consul-ui/app/models/topology.js
ui/packages/consul-ui/app/routes/dc/services/show/index.js
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show-topology.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show-topology-steps.js
ui/packages/consul-ui/tests/pages/dc/services/show.js

Two conditions apply to see Topology tab:
1. Connect must be enabled
2. Service must have at least 1 proxy
Previously we covered just the first condition. This PR covers the 2nd. 
cc @banks

ui: Prevent redirect to topology url and hide Topology tab if service has no services

---

ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/components/topology-metrics/layout.scss
ui/packages/consul-ui/app/components/topology-metrics/series/layout.scss

Bug: The use of `pointer-events: none;` prevents the Tooltips from showing up.
Fixes:
- Moving the the lines to point towards the header of the metrics container.
- Using z-index to avoid the issue of overlapping divs.

ui: Fix the pointer events to view the tooltips when hovering over the icons

---

ui/packages/consul-ui/app/styles/components/tabular-collection.scss
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/styles/routes/dc/acls/index.scss
ui/packages/consul-ui/app/styles/routes/dc/kv/index.scss

Since we changed our approach of globally targeting pages with CSS we missed a couple of places where we needed to refer to both create and edit pages (previously both create and edit pages where targeted using `edit`)
Before:
After:

ui: Fixup CSS for create pages

---

.circleci/config.yml

This PR modifies our envoy test invocation to split a list of subtests across parallel workers based on the directories present in `test/integration/connect/envoy/`. This should roughly cut the testing time in half. Applying this commit on top of #8972 gives us < 10 min runtimes for each envoy test job 🎉 .

ci: add parallelism to envoy tests

---

ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/permission/form/pageobject.js
ui/packages/consul-ui/app/components/consul/intention/permission/header/form/pageobject.js
ui/packages/consul-ui/app/components/consul/intention/permission/header/list/pageobject.js
ui/packages/consul-ui/app/components/consul/intention/permission/list/pageobject.js
ui/packages/consul-ui/app/components/power-select/pageobject.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/permissions/create.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/intentions/permissions/create-steps.js
ui/packages/consul-ui/tests/acceptance/steps/steps.js
ui/packages/consul-ui/tests/dictionary.js
ui/packages/consul-ui/tests/helpers/page.js
ui/packages/consul-ui/tests/helpers/yadda-annotations.js
ui/packages/consul-ui/tests/integration/components/consul/intention/permission/form-test.js
ui/packages/consul-ui/tests/integration/components/consul/intention/permission/header/form-test.js
ui/packages/consul-ui/tests/lib/page-object/index.js
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/intentions/edit.js
ui/packages/consul-ui/tests/steps.js
ui/packages/consul-ui/tests/steps/assertions/page.js
ui/packages/consul-ui/tests/steps/interactions/visit.js

Generally we are pretty light on component integration testing and very heavy on app-wide acceptance testing, which is something we'd like to change. So this PR does various things:
1. Starts constructing page objects using a `noun.verb` pattern, which means we can perform various verbs on the same selector which means we can use this in integration testing like:
```
{
form: {
PathType: {
scope: 'input[name="pathtype"]',
click: clickable()
present: isPresent()
}
}
}
assert.ok(PermissionsForm.PathType.present)
PermissionsForm.PathType.click();
```
2. We also started adding some acceptance test steps to be able to use a similarly formatted page objects
3. We add some very basic integration and acceptance tests to hopefully ensure that it's easy to use the same page object for both types of …

ui: Initial Intention Permission Integration and acceptance testing

---

agent/consul/internal_endpoint_test.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/structs/intention.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

This flag is being added so that the UI can know whether an exact intention exists between two services. 
If an exact intention exists users will be sent to an "edit" page to avoid overwriting an existing intention.
Now the Intention object attached to each upstream/downstream in the response will look like this:
```
"Intention": {
"Allowed": false,
"HasPermissions": true,
"HasExact: true
}
```

Add HasExact to topology endpoint

---

agent/consul/state/store_integration_test.go
agent/consul/stream/event_buffer.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/subscription.go
agent/consul/stream/subscription_test.go
agent/rpc/subscribe/subscribe.go

Before this change a caller could `Unsubscribe`, which would remove the subscription tracking, but would not actually close the subscription. Since the subscription was not tracked it would never be force closed by an ACL change, or a state restore. It also meant that any goroutine blocked on `subscribe.Next()` would not exit.
With this change a subscription is closed, exiting `subscribe.Next()` with an error and preventing it from sending new events.
This was not really a security concern, because `Unsubscribe` is not exposed by any API, but it is probably still good to fix this now in case it changes in the future.

stream: close the subscription on Unsubscribe

---

.changelog/9024.txt
agent/consul/config_replication.go
agent/consul/config_replication_test.go
agent/structs/config_entry.go
agent/structs/connect_proxy_config.go

An operator with `service:write` ACL permissions in a Consul Enterprise cluster can write a malicious config entry that causes infinite raft writes due to issues with the namespace replication logic. This can lead to an operator with access to one namespace to be able to temporarily delete a doppelgänger configuration in another namespace they should not have access to modify.
This is CVE-2020-25201
Previously config entries sharing a kind & name but in different
namespaces could occasionally cause "stuck states" in replication
because the namespace fields were ignored during the differential
comparison phase.
Example:
Two config entries written to the primary:
```
kind=A,name=web,namespace=bar
kind=A,name=web,namespace=foo
```
Under the covers these both get saved to memdb, so they are …

server: config entry replication now correctly uses namespaces in comparisons

---

.circleci/config.yml

So that we are using the same version as the enterprise build

ci: upgrade gotestsum

---

agent/uiserver/ui_template_data.go
agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go
ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/series/index.js
ui/packages/consul-ui/app/components/topology-metrics/series/layout.scss
ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
ui/packages/consul-ui/app/components/topology-metrics/status/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/status/index.scss
ui/packages/consul-ui/app/services/repository/metrics.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/package.json
ui/packages/consul-ui/vendor/metrics-providers/prometheus.js
ui/yarn.lock

This plumbs DC and namespace through to the provider.
It's not actually used yet since we don't yet label metrics with those things CC @freddygv.
This should be last change needed for now before we can document the provider interface.
@freddygv one thing I've proposed here is that in the future if we support cross-DC metrics fetching, we would encode that as an option in this API rather than have another field "metricsDC" which might be different to "serviceDC" (e.g. because downstream metrics come from the source proxies which might be in a different DC to the one you are viewing.

UI metrics provider dc

---

test/integration/connect/envoy/case-badauthz/setup.sh
test/integration/connect/envoy/case-badauthz/teardown.sh
test/integration/connect/envoy/case-badauthz/verify.bats
test/integration/connect/envoy/case-http-badauthz/setup.sh
test/integration/connect/envoy/case-http-badauthz/teardown.sh
test/integration/connect/envoy/case-l7-intentions/verify.bats
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh

The key thing here is to use `curl --no-keepalive` so that envoy
pre-1.15 tests will reliably use the latest listener every time.
Extra:
- Switched away from editing line-item intentions the legacy way.
- Removed some teardown scripts, as we don't share anything between cases anyway
- Removed unnecessary use of `run` in some places.

Fix even more test flakes in intentions related envoy integration tests

---

ui/packages/consul-ui/app/components/topology-metrics/banner.hbs
ui/packages/consul-ui/app/components/topology-metrics/notice/limited-access.hbs
ui/packages/consul-ui/app/models/topology.js
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

Creates a banner for limited access from ACLs.

ui: Topology limited access banner

---

.github/issue-labeler.yml
.github/pr-labeler.yml

Follows up on https://github.com/hashicorp/consul/pull/8994 to update the labeler.

Remove auto-docs-cherrypick and update UI label

---

ui/packages/consul-ui/app/utils/dom/event-source/blocking.js
ui/packages/consul-ui/tests/unit/utils/dom/event-source/blocking-test.js
ui/packages/consul-ui/vendor/metrics-providers/prometheus.js

Previously errors were being caught in the provider and replaced with empty data. This meant that the UI would happily keep retrying the provider thinking that it was returning valid empty data even though the proxy was erroring with 404s.
This PR instead passes any errors through to the UI where it will be handled like any other event source/blocking query errors. Anything 50x-like will retry, anything 40x-like will just stop trying.
~~(Guessing tests will fail here until I can submit a PR for an error in the mocks and rebase)~~

ui: Metrics - Don't swallow metrics errors

---

agent/cache-types/streaming_health_services.go

Instead of the whole map. This should save a lot of time performing reflecting on a large map. The filter does not change, so there is no reason to re-apply it to older entries.

streaming: apply filter to a single item

---

agent/grpc/client.go
agent/grpc/client_test.go
agent/grpc/handler.go
agent/grpc/resolver/resolver.go
agent/grpc/server_test.go
agent/grpc/stats.go
agent/grpc/stats_test.go
agent/setup.go
tlsutil/config.go

This PR does a bunch of cleanup in `agent/grpc`, primarily in the tests. Best viewed by individual commit.
Adds a test, and fixes most of the test flakes (see comment below).

agent/grpc: fix some test flakes and handle duplicate server IDs in the pool

---

agent/connect/ca/provider_vault.go

It's possible for a Vault token to not have access to the `/auth/token/lookup` endpoint, so use `/auth/token/lookup-self` instead to fetch info about renewal.

connect: Use the lookup-self endpoint for Vault token

---

agent/consul/state/acl.go
agent/consul/state/acl_oss.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry_intention.go
agent/consul/state/connect_ca.go
agent/consul/state/federation_state.go
agent/consul/state/graveyard.go
agent/consul/state/graveyard_oss.go
agent/consul/state/intention.go
agent/consul/state/intention_oss.go
agent/consul/state/kvs.go
agent/consul/state/kvs_oss.go
agent/consul/state/memdb.go
agent/consul/state/prepared_query.go
agent/consul/state/session.go
agent/consul/state/session_oss.go
agent/consul/state/state_store.go
agent/consul/state/txn.go

This PR finishes the migration from `*txn` to the `ReadTxn` interface for all read-only functions. It required migrating some of the write functions to `WriteTxn` as well, because `TxnRO` shares a helper with `TxnRW` and would no longer use the same type.
This allows us to return a regular unwrapped `*memdb.Txn` from `db.ReadTxn()` instead of a wrapped one.
Also includes a commit backported from enterprise to set the default EnterpriseMeta on some expected test values.

state: Use ReadTxn everywhere

---

agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/consul/state/memdb.go
agent/health_endpoint.go
agent/rpcclient/health/health.go
agent/setup.go
website/pages/docs/agent/options.mdx

Rename the config field, it is no longer under the `cache` section, and update the docs.
Also change the condition which enables streaming so that streaming can be used even without the `cache=1` query parameter.
Also disables streaming for connect events. The events generated for terminating gateways are not correct yet, so we should use the old blocking queries for now.

streaming: rename config and remove requirement for cache=1

---

.changelog/9006.txt
command/snapshot/inspect/formatter.go
command/snapshot/inspect/formatter_test.go
command/snapshot/inspect/snapshot_inspect.go
command/snapshot/inspect/snapshot_inspect_test.go
command/snapshot/inspect/testdata/TestSnapshotInspectCommand.golden
command/snapshot/inspect/testdata/TestSnapshotInspectEnhanceCommand.golden
command/snapshot/inspect/testdata/json.golden
command/snapshot/inspect/testdata/pretty.golden
website/pages/commands/snapshot/inspect.mdx

Previous functionality still available unchanged:
```
consul snapshot inspect backup.snap
ID           2-13-1603221729747
Size         5141
Index        13
Term         2
Version      1
Type                        Count      Size
----                        ----       ----
Register                    3          1.7KB
ConnectCA                   1          1.2KB
ConnectCAProviderState      1          1.1KB
Index                       12         344B
Autopilot                   1          199B
ConnectCAConfig             1          197B
FederationState             1          139B
SystemMetadata              1          68B
ChunkingState               1          12B
----                        ----       ----
Total                                  5KB
```
However the addition of JSON output …

cli: Add JSON and Pretty Print formatting for `consul snapshot inspect`

---

agent/connect/ca/provider_consul_test.go
agent/consul/fsm/fsm.go
agent/consul/gateway_locator_test.go
agent/consul/issue_test.go
agent/consul/server.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_test.go
agent/consul/state/kvs_test.go
agent/consul/state/memdb.go
agent/consul/state/state_store.go
agent/consul/state/state_store_test.go
agent/consul/stream/noop.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/consul/usagemetrics/usagemetrics_test.go
agent/rpc/subscribe/subscribe_test.go

Branched from #8618
If streaming is disable we can avoid doing any of the work of creating events from memdb changes. This is an additional safeguard to ensure that the new streaming feature does not inadvertently negatively impact any existing clusters.

streaming: Use a no-op event publisher if streaming is disabled

---

ui/packages/consul-ui/GNUmakefile

Updates `node_modules` path/makefile target to fix top-level `make ui` command.

ui: Update node_modules deps path in GNUMakefile

---

agent/consul/state/intention.go
agent/consul/state/intention_test.go

1. do a state store query to list intentions as the agent would do over in `agent/proxycfg` backing `agent/xds`
2. upgrade the database and do a fresh `service-intentions` config entry write
3. the blocking query inside of the agent cache in (1) doesn't notice (2)

state: ensure we unblock intentions queries upon the upgrade to config entries

---

agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go
test/integration/connect/envoy/helpers.bash

Added a new option `ui_config.metrics_proxy.path_allowlist`. This defaults to `["/api/v1/query", "/api/v1/query_range"]` when the metrics provider is set to `prometheus`.
Requests that do not use one of the allow-listed paths (via exact match) get a 403 Forbidden response instead.
translate.
`TestFullConfig` in `agent/config/runtime_test.go`, it should fail now, then
add the same random value to the expected struct in that test so it passes
again.
file. (Running the test first gives you a nice diff which can save working
out where etc.)
some cases or with some values (often true).
`agent/config/runtime_test.go`.
`agent/config/runtime_test.go`.
any state the feature needs changing. This needs to be added to one or
more of the following …

agent: introduce path allow list for requests going through the metrics proxy

---

ui/packages/consul-ui/app/components/list-collection/index.js
ui/packages/consul-ui/app/components/tabular-collection/index.hbs
ui/packages/consul-ui/app/components/tabular-collection/index.js

This PR fixes an issue that has appeared since our Ember upgrade from https://github.com/hashicorp/consul/pull/8761 where our dropdown action menus would not close when the user clicks outside them.
From my vague memory (I can't find any description in history for it) the code I've removed here was added a result of a previous upgrade, so I'm guessing a regression was fixed somewhere that affected us.
Before:
After:

ui: Remove string casting when passing index/checked for dropmenus

---

test/integration/connect/envoy/helpers.bash

This is used in `setup.sh` scripts in bats, which do _not_ run in the `verify` container, so need to get access to the appropriate consul instance.

fix envoy integ test wait_for_namespace to actually work on CI

---

test/integration/connect/envoy/helpers.bash

Missed this one in the initial sweep.

use hashicorp docker mirror in envoy helper

---

website/pages/docs/nia/installation/configuration.mdx

The TLS option wasn't clear that it's not used if the agent does not have either option enabled [`verify_incoming`](https://www.consul.io/docs/agent/options#verify_incoming) or [`verify_incoming_https`](https://www.consul.io/docs/agent/options#verify_incoming_https).

docs/nia: improve clarity on Consul TLS option

---

ui/packages/consul-ui/.storybook/main.js
ui/packages/consul-ui/.storybook/preview.js
ui/packages/consul-ui/app/components/notice/README.stories.mdx
ui/packages/consul-ui/package.json
ui/yarn.lock

We've held off on installing storybook into the main project for quite a while now, holding out for some approach which meant that storybook would be installed only if you wanted to work on components.
That approach hasn't materialised and we really could do with a nice way to catalog and work on our components in a more isolated manner, so this PR installs storybook straight into the main UI project.
I've added one basic story here for our simple `<Notice />` component, but we should aim to add more and more stories for existing and new components as we move forwards with it.

ui: Storybook Install

---

ui/packages/consul-ui/app/services/client/http.js
ui/packages/consul-ui/app/services/repository/metrics.js
ui/packages/consul-ui/vendor/metrics-providers/prometheus.js

This PR creates wraps up `window.fetch` with an additional piece of functionality to shim in:
1. Consul's metrics proxy path prefixed on
2. Any current ACL token in use in the UI will be added to fetch's headers.
And passes this through to the provider as `options.fetch`.
I figured that in using `fetch` we are sticking to a recognisable interface that is simpler to use than XHR and means that we have a documented interface to stick to aswell as anyone writing custom providers.
I moved any additional functionality (query param encoding) back into the provider so we keep as close to fetch as possible.

ui: Metrics - Provide a fetch-like http client that automatically adds the current ACL token

---

agent/config/runtime.go
agent/config/runtime_test.go

The documentation indicates that the "add_headers" config option for the UI metrics proxy can be used to add additional credentials for the metrics backend which implies the value portion of this may contain secrets.
This PR replaces all header values with `"hidden"` when accessed via the `/v1/agent/self` endpoint.

agent: sanitize ui metrics proxy header values on agent/self endpoint

---

test/load/terraform/README.md

This branch adds a missing link from `test/load/terraform/README.md` to `test/load/packer`.

Link to packer directory from terraform ReadMe

---

ui/packages/consul-ui/.ember-cli

This means any components created using the ember component generator will now use the glimmer component blueprint by default.

ui: Default to glimmer components

---

ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions.feature

Per service intentions should NOT take the user to the global intention edit form in order to edit the intention, instead they should be editable in place within the service itself.
The intention list has a `routeName` attribute to control where it links to which was left out in a previous PR.
This adds it back in again, plus a simple test to warn us if its left out again.

ui: Ensure per service intentions link to the correct place

---

.circleci/config.yml
test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/Dockerfile-consul-envoy
test/integration/connect/envoy/run-tests.sh
website/Dockerfile

Manual backport of #9070 and #9085 to `release/1.9.x` to avoid merge conflicts.

chore: use hashicorp docker mirror to prevent rate limit (#9070) (#9085)

---

ui/yarn.lock

Followup to #9084, just found it while running `yarn`

ui: remove consul-api-double from yarn.lock

---

.changelog/9113.txt
command/connect/envoy/flags.go
command/connect/envoy/flags_test.go
command/connect/envoy/testdata/ingress-gateway.golden

To avoid assumption of Envoy running as root.
Fixes #8948
/cc @shoenig

connect: Switch the default gateway port from 443 to 8443

---

ui/packages/consul-ui/app/components/notice/README.stories.mdx

In https://github.com/hashicorp/consul/pull/9095 we removed the storybook knobs addon and switched to the controls addon instead, this also moves the notice to use the controls addon.

ui: Move notice storybook to use controls addon

---

.circleci/scripts/cherry-picker.sh

If we forgot to add backport labels, or decide later that we want to backport a PR it requires finding the Circle CI job that ran as a result of the PR merge. 
This PR makes that process a bit easier by commenting on every PR after it is merged with the CircleCI job url. With this change we can start the backport job from the github PR page by adding labels and clicking the link.
I tested this on my fork, and you can see the message [here](https://github.com/dnephin/consul/pull/3#issuecomment-723338392). It shows up as coming from me on my fork because I used a token with my creds. Our CI uses a token for the hashicorp-ci bot, so it will show up the same way as other comments from the bot.
An alternative approach would be to run the cherry-pick job automatically any time a label is added …

ci: Make backporting post-merge a bit easier

---

.circleci/config.yml
build-support/docker/Build-Go.dockerfile
build-support/docker/Test-Flake.dockerfile

Alternative to #9036, we should backport this to 1.9.x and 1.8.x for the fix to https://github.com/golang/go/issues/42138

chore: update to Go 1.14.11

---

ui/packages/consul-ui/app/adapters/http.js

`AdapterError` is the default export from `@ember-data/adapter/error` not a named export.

ui: Correct AdapterError import

---

agent/pool/pool.go

Formatting the error with `%v` eats up the error type of `rpc.ServerError`.  Wrapping the error with `%w` allows checking the error type without string comparison.
This change pairs with my colleague's PR #8698, which uses the error type.  In the case I'm working on, the error is handled in agent/consul/client.go:RPC(), where `canRetry(args, rpcErr)` should be able to understand the type of error.

Wrap rpc error object

---

agent/pool/pool.go

Same as #8976, wrapping errors allows using `Errors.Is()` and `Errors.As()` elsewhere instead of string comparing error messages.

Use error wrapping to preserve error type info

---

website/pages/docs/upgrading/upgrade-specific.mdx

For users upgrading from very old versions, we mentioned adding `enable_script_checks` in the specific upgrade notes, but have no mention of `enable_local_script_checks` when that was added. Based on how this is worded for 0.9.0, it sounds like users _should turn this on_ – which was true at that time if they wanted to use script checks. As of 0.9.4, it's recommended that `enable_local_script_checks` is used instead. The message being displayed is based off of the message [here](https://github.com/hashicorp/consul/blob/master/agent/config/builder.go#L2338).
If all you check are the specific upgrade notes, you could mistakenly enable this feature without realizing the potential security impact. This note should help with that.

docs: add warning in 0.9.0 upgrade notes

---

ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
ui/packages/consul-ui/app/routes/dc/services/show.js
ui/packages/consul-ui/app/serializers/topology.js
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
ui/packages/consul-ui/package.json
ui/yarn.lock

Previously creating a new allowing Intention meant visiting the Intention edit form and manually creating a new intention. This adds an 'inline' action that creates a new allowing intention without leaving the topology page.

ui: Inline Topology Intention Actions 

---

.changelog/9156.txt
.changelog/_666.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_oss.go
agent/consul/state/kvs.go
agent/consul/state/kvs_oss.go
agent/consul/state/session.go
agent/consul/state/session_oss.go

This helps fix an issue in Consul Enterprise, where the rest of the fix is, where snapshots can fail to restore if a namespace deletion was in progress when the snapshot was taken.
The fix is to ignore namespace existence checks when we are restoring data and then let the deferred namespace deletion routines delete the data normally.

Add a paramter in state store methods to indicate whether a resource insertion is from a snapshot restoration

---

agent/operator_endpoint_oss.go
agent/operator_endpoint_test.go
api/operator_autopilot.go
command/commands_oss.go
command/operator/autopilot/state/formatter.go
command/operator/autopilot/state/operator_autopilot_state.go
command/operator/autopilot/state/operator_autopilot_state_test.go
command/operator/autopilot/state/testdata/enterprise/json.golden
command/operator/autopilot/state/testdata/enterprise/pretty.golden
command/operator/autopilot/state/testdata/enterprise/state.json
command/operator/autopilot/state/testdata/oss/json.golden
command/operator/autopilot/state/testdata/oss/pretty.golden
command/operator/autopilot/state/testdata/oss/state.json
website/pages/commands/operator/autopilot.mdx

This is a small shim around the new `/v1/operator/autopilot/state` endpoint. The new command supports both JSON and pretty output formats.

Add a CLI command for retrieving the autopilot configuration.

---

.circleci/config.yml

There might be a backporting issue here due to the generated file moving to `agent/uiserver/bindata_assetfs.go` recently.

ci: publish bindata_assetfs.go for all release/.x branches

---

.circleci/config.yml
test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/Dockerfile-consul-envoy
test/integration/connect/envoy/Dockerfile-tcpdump
test/integration/connect/envoy/docker-compose.yml
test/integration/connect/envoy/helpers.bash
test/integration/connect/envoy/run-tests.sh
website/Dockerfile

"Backport" of #9070, #9080 and #9085, significantly reworked because of an intermediate Envoy integration tests refactor, would appreciate 👀 in case I missed anything.

chore(backport): use HashiCorp Docker mirror

---

ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.js
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.scss
ui/packages/consul-ui/app/components/consul/upstream-instance/list/pageobject.js
ui/packages/consul-ui/app/components/consul/upstream-instance/search-bar/index.hbs
ui/packages/consul-ui/app/controllers/dc/services/instance/upstreams.js
ui/packages/consul-ui/app/routes/dc/services/instance/upstreams.js
ui/packages/consul-ui/app/search/predicates/upstream-instance.js
ui/packages/consul-ui/app/services/search.js
ui/packages/consul-ui/app/services/sort.js
ui/packages/consul-ui/app/sort/comparators/upstream-instance.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/components/composite-row.scss
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/services/instance.js

This PR adds textual searching and sorting to the service instance > upstreams tab.

ui: Upstream Instance Search and Sort

---

agent/grpc/client.go
agent/grpc/handler.go
agent/grpc/stats.go
agent/grpc/stats_test.go

defaultMetrics was being set at package import time, which meant that it received an instance of the original default. But `lib/telemetry.InitTelemetry` sets a new global when it is called.
This resulted in the metrics being sent nowhere.
This commit changes `defaultMetrics` to be a function, so it will return the global instance when called. Since it is called after InitTelemetry it will return the correct metrics instance.

grpc: fix metrics

---

.changelog/9007.txt
agent/consul/intention_endpoint.go
agent/structs/config_entry_intentions.go

The `Intention.Apply` RPC is quite large, so this PR attempts to break it down into smaller functions and dissolves the pre-config-entry approach to the breakdown as it only confused things.

server: break up Intention.Apply monolithic method

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/routes/dc/services/show/index.js
ui/packages/consul-ui/app/templates/dc/services/show.hbs

Backports #9081
I resolved two sets of conflicts in `ui/packages/consul-ui/app/components/topology-metrics/card.hbs` that were pretty straightforward, taking the `@` ref (Glimmer style if I understand correctly) for:
```
<<<<<<< HEAD
@item={{@item.Name}}
=======
@item={{item.Name}}
>>>>>>> 56c2ff56e (ui: Update to not return metrics for ingress gateways (#9081))
```
There's two conflicts left in `ui/packages/consul-ui/app/components/topology-metrics/index.hbs` that I'm very much not sure how to resolve properly though...

ui: Update to not return metrics for ingress gateways (#9081)

---

.changelog/9151.txt
agent/consul/config_endpoint.go
agent/consul/fsm/commands_oss.go
agent/consul/intention_endpoint.go
agent/consul/server_register.go
agent/consul/state/config_entry.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/structs/config_entry_intentions.go
agent/structs/config_entry_intentions_test.go
agent/structs/intention.go

Change so line-item intention edits via the API are handled via the state store instead of via CAS operations.
Fixes #9143

server: remove config entry CAS in legacy intention API bridge code

---

.changelog/9119.txt
CHANGELOG.md
website/pages/downloads/index.jsx

Cherry-picking #9155 upwards from release/1.9.x for changelog and website updates.

changelog: merge release/1.9.0-beta3

---

.circleci/scripts/cherry-picker.sh

It was a little confusing seeing "Starting backport cherry picking." on a PR that intentionally wasn't being backported, hopefully this will be a little more clear - open to suggestions on language here.
Refs #9130

ci: reword cherry-picker comment

---

ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/mock-api/v1/internal/ui/metrics-proxy/api/v1/query
ui/packages/consul-ui/mock-api/v1/internal/ui/metrics-proxy/api/v1/query_range
ui/packages/consul-ui/mock-api/v1/internal/ui/service-topology/_
ui/packages/consul-ui/vendor/metrics-providers/prometheus.js

This PR does four things:
1. Updates our mock API to be slightly more random during smoke testing, which means we can work with/see more eventualities .
2. We ensure any development cookie values are passed to `faker.seed` as numbers so we can check various numbers of things by changing cookies similar to the rest of the UI.
3. Makes mocks randomly output `NaN` and `undefined` strings.
4. Any non-numeric values are replaced with `-` in the provider to prevent any `NaN`/`undefined`s showing up in the stats display.

ui: Replace NaN and undefined metrics values with `-`

---

.changelog/9204.txt
agent/consul/operator_autopilot_endpoint.go

Running `go test -count 100 ./agent -run TestOperator_ServerHealth_Unhealthy` was a reliable way to test this locally.
As for unit tests its pretty much impossible to time things just right such that we make the request after raft has elected a leader and before leader establishment has finished (which will create the autopilot state)

Prevent panic if autopilot health is requested prior to leader establishment finishing.

---

contributing/INTERNALS.md
website/pages/api-docs/query.mdx
website/pages/docs/agent/config-entries/ingress-gateway.mdx
website/pages/docs/agent/options.mdx
website/pages/docs/connect/gateways/ingress-gateway.mdx
website/pages/docs/connect/native/index.mdx
website/pages/docs/connect/proxies/index.mdx
website/pages/docs/connect/proxies/managed-deprecated.mdx
website/pages/docs/discovery/services.mdx
website/pages/docs/k8s/dns.mdx
website/pages/docs/k8s/service-sync.mdx
website/pages/intro/getting-started/agent.mdx

The redirects were working in many situations but some such as in INTERNALS.md were getting 404ed. This just flips everything over to using the real link location.

[docs] Change links to the DNS information to the right place

---

.circleci/config.yml
acl/authorizer_test.go
acl/chained_authorizer_test.go
acl/policy_authorizer_test.go
acl/static_authorizer_test.go
agent/auto-config/auto_config_test.go
connect/proxy/config_test.go
connect/proxy/proxy_test.go
connect/service_test.go
connect/testing.go
connect/tls.go

Related to #8329
An exclude list will ensure that any new packages we create are tested with `-race`, and also gives us a checklist for the packages that have tests that need to be fixed.
Fixes a couple small races to get the `connect/` packages working. Details in the commit message.

ci: change go-test-race package list to exclude list

---

ui/packages/consul-ui/app/components/tab-nav/index.hbs

This removes a deprecation warning in console.
We also formatted things slightly to make things easier to read.

ui: Add triple curlies and reformat style attribute

---

ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/policies/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/roles/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/roles/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/tokens/edit.hbs
ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
ui/packages/consul-ui/app/templates/dc/intentions/edit.hbs
ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
ui/packages/consul-ui/app/templates/dc/nspaces/edit.hbs
ui/packages/consul-ui/app/templates/dc/nspaces/index.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/settings.hbs

Removes a deprecation warning for the upgraded ember addon. A small note here, I kinda wish we'd made this part of the `<AppView />` component so:
`<AppView title="Title in here">`
Maybe something we can talk about doing in the future.

ui: Change title helper to page-title

---

ui/packages/consul-ui/app/components/list-collection/index.hbs
ui/packages/consul-ui/app/components/list-collection/index.js
ui/packages/consul-ui/app/components/tabular-collection/index.hbs
ui/packages/consul-ui/app/components/tabular-collection/index.js
ui/packages/consul-ui/package.json
ui/yarn.lock

Somewhere within `ember-computed-style` an ember deprecation warning is emitted. This refactors the two components that used that addon slightly to not use it and then uninstalls the addon.
Worthwhile noting: we changed our ancient `TabularCollection` component to be a tagless ember component, but both that component and `ListCollection` inherit from an ember supported addon ember component so we couldn't go glimmer here - and it would probably be more than trivial to do so in the future due to the reliance on the ember component in the addon.
Previous deprecation warning:

ui: Remove ember-computed-style to avoid deprecation error

---

ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/series/index.js

Create a `empty` state to be used in the Series to show or hide the loader.

ui: Fix empty state conditional for Series Graph

---

agent/agent.go
agent/agent_test.go
agent/apiserver.go

Manual backport of #9224 into 1.9.0 branch
Previously the listener was being passed to a closure in a loop without capturing the loop variable. The result is only the last listener is used, so the http/https servers only listen on one address.
This problem is fixed by capturing the variable by passing it into a function.

[1.9.0] agent: fix bug with multiple listeners

---

agent/agent.go
agent/agent_test.go
agent/apiserver.go

Fixes #9214
Previously the listener was being passed to a closure in a loop without capturing the loop variable. The result is only the last listener is used, so the http/https servers only listen on one address.
This problem is fixed by capturing the variable by passing it into a function.
There was a fix for this in https://github.com/hashicorp/consul/pull/8623/files#diff-62b6ad581fe3a3059ae8c85ef0f31dde4092bfdecfa7d6857c470bcacaa8cc8bR765, but that PR has not merged yet.

agent: fix bug with multiple listeners

---

website/pages/docs/k8s/connect/index.mdx
website/pages/docs/k8s/helm.mdx

* Adds `envoyExtraArgs` to the helm doc
* Adds `consul.hashicorp.com/envoy-extra-arg` to the annotation doc

Add docs for envoyExtraArgs

---

website/pages/docs/upgrading/upgrade-specific.mdx

Found that the default setting for `http_max_conns_per_client` wasn't increased as stated in the upgrade guide for any of the v1.6.4+ releases, [as seen here](https://github.com/hashicorp/consul/blob/v1.6.9/agent/config/default.go#L104).  Correcting text to advise explicitly setting it if upgrading to v1.6.3-v1.7.0.

Correcting text on when default was changed in Consul

---

ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/instances/show.feature

In https://github.com/hashicorp/consul/pull/9141 we removed the separate ProxyInfo tab and it's healthcheck listing for proxies and instead merged the healthchecks for proxies in with the healthchecks for the service instance itself in one listing under the healthchecks tabs
Although if an instance didn't have a proxy, this meant appending an `undefined` value to the list of healthchecks resulting in a 'ghost empty healthcheck' at the end of the listing:
This PR checks for the existence of the Proxy.Checks and if it doesn't exist instead appends/concats an empty array, which therefore has no effect on the length of the healthchecks list.

ui: Remove ghost healthcheck from the service instance healthcheck list

---

ui/packages/consul-ui/app/components/topology-metrics/card.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs

This ensures that a nspace is used in the request for metrics, whether in OSS or Enterprise Consul. Without this the metrics provider will just return empty results.

ui: All metrics cards should default to the default nspace if not set

---

ui/packages/consul-ui/app/components/child-selector/index.hbs
ui/packages/consul-ui/app/components/child-selector/index.js
ui/packages/consul-ui/app/services/sort.js
ui/packages/consul-ui/app/sort/comparators/policy.js
ui/packages/consul-ui/app/sort/comparators/role.js
ui/packages/consul-ui/app/sort/comparators/upstream-instance.js
ui/packages/consul-ui/tests/acceptance/dc/acls/policies/as-many/add-existing.feature
ui/packages/consul-ui/tests/acceptance/dc/acls/roles/as-many/add-existing.feature

This PR began as a fix for https://github.com/hashicorp/consul/issues/9227 but whilst we were there we progressed our comparator functions to use common utility functions slightly. There's potentially a follow up PR to be made after this to progress this further (I felt there was already quite a bit of change here for what we set out to do)
The Role and Policy selectors are now sorted by Name and text searchable.
Worthwhile noting that search functionality used to exist here but we lost it in an ember-power-select upgrade 😬 . A couple of small tests here should prevent that from ever happening again.

ui: ACL Tokens > Roles and Policy search and sort

---

ui/packages/consul-ui/app/components/empty-state/index.hbs
ui/packages/consul-ui/app/components/error-state/index.hbs
ui/packages/consul-ui/app/routes/application.js
ui/packages/consul-ui/app/services/repository/dc.js

This PR surfaces the API error response (if there is one) in our error pages giving pages that look like the following:

ui: Surface 'detail' of API errors in the error page

---

.changelog/9240.txt
agent/consul/connect_ca_endpoint.go
agent/consul/connect_ca_endpoint_test.go
website/pages/api-docs/connect/ca.mdx

CVE-2020-28053
A vulnerability was identified in Consul and Consul Enterprise (“Consul”) such that operators with `operator:read` ACL permissions are able to read the Consul Connect CA configuration when explicitly configured with the `/v1/connect/ca/configuration` endpoint, including the private key. This allows the user to effectively privilege escalate by enabling the ability to mint certificates for any Consul Connect services. This would potentially allow them to masquerade (receive/send traffic) as any service in the mesh.
------
This PR increases the permissions required to read the Connect CA's private key when it was configured via the `/connect/ca/configuration` endpoint. They are now `operator:write`.

Require operator:write to get Connect CA config

---

.changelog/9229.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
api/agent.go
api/agent_test.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
website/pages/api-docs/agent/service.mdx

command: when generating envoy bootstrap configs use the datacenter returned from the agent services endpoint

---

.changelog/9229.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
api/agent.go
api/agent_test.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
website/pages/api-docs/agent/service.mdx

Manual backport of #9229 into 1.9.0 branch
Fixes #9215

[1.9.0] command: when generating envoy bootstrap configs use the datacenter returned from the agent services endpoint

---

logging/logfile.go
logging/logfile_test.go
logging/logger.go

The issue was reported here: https://discuss.hashicorp.com/t/log-rotate-max-files-not-working/14834
When Consul starts it creates a new log file, but it only prunes log files when `rotate` is called. This could result in more than `MaxFiles` number of log files.
By calling `pruneFiles` on startup we not only ensure the number of files is enforced, we also get the error from `pruneFiles` immediately. Normally if a log file fails to write, rotate, or prune we would not see the error anywhere, because where would it go? It can't go to logs because that would likely fail. So seeing any failures to prune on startup should help debug issues with file permissions.
Also does a bunch of cleanup in both `pruneFiles` and the tests for `LogFile`.

logging: prune logs on startup

---

website/pages/docs/agent/options.mdx

Adds `(experimental)` to the docs for the two config settings used to enable streaming. Also fixes some minor errors in those sections.

docs: mark streaming as experimental

---

.changelog/8685.txt
.changelog/8703.txt
.changelog/8822.txt
.changelog/8834.txt
.changelog/8877.txt
.changelog/9036.txt
.changelog/9198.txt
CHANGELOG.md

Merge all beta releases into a single `UNRELEASED` section.
- Only found two UI entries and the Go 1.14.11 upgrade (1.9.0 moved to 1.15), updated a few categories for better grouping though

changelog: 1.9.0

---

website/pages/docs/k8s/upgrade/compatibility.mdx

Adding 1.9.x and link to Envoy compat matrix

docs: adding Consul 1.9.x to compat matrix and link to Envoy compat matrix

---

.changelog/9247.txt
agent/cache-types/streaming_health_services.go
agent/cache-types/streaming_health_services_test.go

This ensures the result is consitent with/witout streaming
Will partially fix #9239

[Streaming] Predictable order for results of /health/service/:serviceName to mimic memdb

---

agent/config/runtime.go
website/pages/docs/agent/options.mdx

WAN config is different than LAN config, source of truth is
https://github.com/hashicorp/memberlist/blob/f72d2042a81632f45a86ad548580c1bd8890dbf9/config.go#L315-L326
and now the docs are correct.

fix serf_wan documentation

---

.changelog/9284.txt
agent/ae/ae.go
agent/local/state.go
agent/local/state_test.go

When the existing service is the same as the new service.
Fixes #9266

local: mark service as InSync when added to local agent state

---

ui/packages/consul-ui/app/components/data-source/README.mdx
ui/packages/consul-ui/app/components/data-source/index.hbs
ui/packages/consul-ui/app/components/data-source/index.js
ui/packages/consul-ui/app/services/data-source/service.js
ui/packages/consul-ui/tests/integration/components/data-source-test.js

There are a few things that we've thought of adding to our DataSources recently but held off on upgrading things until now, these are:
1. Add a property based approach. Previously you could only use DataSources with a callback/event handler approach meaning looping through component/DataSources could be problematic. Also, in order to use the `mut` or `set` helper a glimmer component requires a backing JS class. We'd decided that yielding the DataSources properties would help to avoid this and make it easier to load data outside of components that could otherwise be purely presentational.
```hbs
{{#each things as |thing|}}
<DataSource @src={{ concat '/somewhere/thing/' thing.ID }} as |source|>
<PresentationalThingComponent @item={{source.data}} />
</DataSource>
{{/each}}
```
2. We'd like …

ui: Nestable DataSources (plus glimmer upgrade)

---

website/pages/commands/connect/index.mdx

Change `Connect Connect` to `Consul Connect, which is consistent with the command output as shown on this page.

Fix typo in explanation of connect command

---

ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/routes/dc/services/index.js
ui/packages/consul-ui/app/routes/dc/services/instance.js
ui/packages/consul-ui/app/routes/dc/services/show.js
ui/packages/consul-ui/app/routes/dc/services/show/services.js

This PR starts to convert our model hooks to ES6 async/await style. I've started with our most complicated model hooks, which started off using simple ternary statements and got more and more complicated as this grew.
Converting things to async/await makes everything easier to read and we no longer need to use `hash`.
Would appreciate extra 🦅 👀 on this one to make sure the logic is the same as the original, tests are passing and I'm happy-ish that they are, but I'm conscious I could have missed something here.
Notes:
1. I added 2 computed properties here which attempt to describe `Kind`s of Service that can be grouped together. See comments for details. Typically now reading these back myself, I'm not 100% on the terms so I'd love any other suggestions of names for these groups...naming …

ui: Asyncify Service Model Hooks

---

agent/consul/connect_ca_endpoint_test.go
agent/consul/leader_connect_ca.go

Follow-on PR to #9009 to fix an issue I found when backporting to 1.8 - don't unset the active root in the secondary unless there's a new one replacing it.

connect: Fix issue with updating config in secondary

---

.changelog/8685.txt
.changelog/8703.txt
.changelog/8822.txt
.changelog/8834.txt
.changelog/8877.txt
.changelog/9036.txt
.changelog/9198.txt
.changelog/changelog.tmpl
api/go.mod
go.mod
website/data/version.js
website/pages/downloads/index.jsx

Updates changelog entries, versions and website banner from changes made directly on `release/1.9.0` branch. Companion to https://github.com/hashicorp/consul/pull/9270

merge: release/1.9.0

---

ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/tests/acceptance/dc/services/show.feature

In https://github.com/hashicorp/consul/pull/8591/files#diff-a1f4a97fe9f6d8df10052fd136117cc45447ad061541730926382df6198932f0R23 we added a convenience property to ServiceInstances called 'Name' that checked `Service.ID` but fellback to `Service.Name`.
This property is confusingly named as the `Name` should never be the `ID`.
This PR changes things to the following:
The `ServiceInstance.ID` should try `Service.ID` and fallback to `Service.Name`, not `ServiceInstance.Name`. `ServiceInstance.Name` is just an alias to `Service.Name` which is always set.
We barely use this property yet (luckily) but we did use it once, which caused the bug outlined in https://github.com/hashicorp/consul/issues/9304, so this change addresses that bug also.
Fixes https://github.com/hashicorp/consul/issues/9304 …

ui: ServiceInstance.Name should be the Service.Name, never the Service.ID

---

CHANGELOG.md

Just editing changelog directly as this is prior to introduction of changelog-gen.

changelog: update 1.8.0 goroutine leak to note increasing memory usage

---

ui/packages/consul-ui/app/components/consul/health-check/list/index.hbs
ui/packages/consul-ui/app/components/consul/health-check/list/layout.scss
ui/packages/consul-ui/app/components/consul/health-check/list/pageobject.js
ui/packages/consul-ui/app/components/consul/health-check/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/node/search-bar/index.hbs
ui/packages/consul-ui/app/components/data-collection/index.js
ui/packages/consul-ui/app/filter/predicates/health-check.js
ui/packages/consul-ui/app/models/health-check.js
ui/packages/consul-ui/app/models/node.js
ui/packages/consul-ui/app/models/proxy.js
ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/routes/dc/nodes/show/healthchecks.js
ui/packages/consul-ui/app/routes/dc/services/instance.js
ui/packages/consul-ui/app/routes/dc/services/instance/healthchecks.js
ui/packages/consul-ui/app/search/predicates/health-check.js
ui/packages/consul-ui/app/services/data-source/protocols/http.js
ui/packages/consul-ui/app/services/filter.js
ui/packages/consul-ui/app/services/repository/service-instance.js
ui/packages/consul-ui/app/services/search.js
ui/packages/consul-ui/app/services/sort.js
ui/packages/consul-ui/app/sort/comparators/health-check.js
ui/packages/consul-ui/app/sort/comparators/service.js
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/tests/integration/services/repository/node-test.js
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/nodes/show.js
ui/packages/consul-ui/tests/pages/dc/services/instance.js

This PR adds search, sort and filtering to the healthcheck tabs in both Node and ServiceInstance views.
In doing this, we added a new HealthCheck model fragment and stitched ServiceInstances and their ProxyServiceInstances together a little more - ProxyServiceInstances are now a JS instance of our `Proxy` model (soon to be renamed `ProxyInstance`) which inherits from a our `ServiceInstance` model, this means that `ProxyServiceInstance`s now take on the properties of the responses of both the API endpoint we use for proxy meta endpoint and the API endpoint we use for service instance endpoint.
We also added some further computed properties onto these models (`ServiceInstance.MeshChecks`, `.HealthCheck.Exposable` and `.HealthCheck.Exposed`)
Lastly a tiny addition here is that we noticed …

ui: HealthCheck Search/Sort/Filtering

---

ui/packages/consul-ui/app/components/consul/service/list/index.hbs

This PR prevents phrases like `1 linked services` in the Service Listing component (vs `1 linked service`).

ui: Don't pluralize words when there is only 1 of the item

---

ui/packages/consul-ui/app/components/consul/service/list/index.hbs

During https://github.com/hashicorp/consul/pull/9321 we noticed that most of our wording in listings was lowercased. This updates the word `Instance` to also be lowercased to be consistent.

ui: Lowercase the word 'instance' in Service listings

---

ui/packages/consul-ui/app/helpers/dom-position.js
ui/packages/consul-ui/app/helpers/env.js
ui/packages/consul-ui/app/helpers/filter-predicate.js
ui/packages/consul-ui/app/helpers/href-mut.js
ui/packages/consul-ui/app/helpers/href-to.js
ui/packages/consul-ui/app/helpers/is-href.js
ui/packages/consul-ui/app/helpers/refresh-route.js
ui/packages/consul-ui/app/helpers/state-matches.js
ui/packages/consul-ui/app/helpers/tween-to.js
ui/packages/consul-ui/app/helpers/uri.js
ui/packages/consul-ui/package.json
ui/yarn.lock

Converts all class based helpers to native class syntax plus:
1. Installs `@observes` which is the replacement for the observer computed property
2. Injects the `env` service to the `env` helper and uses that instead of importing.
3. Deletes `filter-predicate` which we no longer use.

ui: Native-ize class based helpers

---

website/pages/docs/k8s/helm.mdx

- Fix anchors for `client.extraEnvironmentVars` and `server.extraEnvironmentVars`.
- Change extraEnvironmentVars data type to `map`.
- Fix external link to kubernetes.io under `connectInject.namespaceSelector`.

docs: Fix broken URLs in Helm docs

---

ui/packages/consul-ui/app/components/app-view/index.hbs
ui/packages/consul-ui/app/helpers/document-attrs.js
ui/packages/consul-ui/app/instance-initializers/nspace.js
ui/packages/consul-ui/app/styles/components/app-view/layout.scss
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/tests/unit/helpers/document-attrs-test.js

This PR adds a `{{document-attrs}}` helper, specifically for adding attributes to the root documentElement, which in our case is always `<html>`.
There is a fair amount of internal book keeping happening to ensure that when using this helper in multiple locations attributes values are merged and only removed when not being added by any currently used helpers. This is definitely how we want the following to work:
```hbs
{{document-attrs class="a-className"}}
{{document-attrs class="b-className"}}
// class="a-className b-className"
```
..and probably how we want the majority of attributes to work, if not all.
We don't currently implement any other attribute names here, as we don't need them yet. These can be added when required (if you try and set other attributes currently - an error is …

ui: document-attrs helper

---

ui/packages/consul-ui/app/components/data-form/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
ui/packages/consul-ui/app/helpers/render-template.js
ui/packages/consul-ui/app/helpers/uri.js
ui/packages/consul-ui/app/services/encoder.js
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs

This moves our `uri` helper to use a the template renderer we already have for rendering URLs.
Reasons behind this:
1. We had a bug a while ago where we were trying to construct a URL with an undefined nspace, this was resulting in a URL like `//dc/something`. This approach has a strict mode that will warn you whilst in development with a clear error if any values are `undefined`. This should prevent any such bugs in the future (we re-use the functionality we already had for rendering URLs without a strict mode).
2. Our template based datasources now look pretty much exactly the same as our javascript based ones, which additionally means it's easy to find places where we are using a specific data sources by searching through the project. This approach generally just looks easier to see …

ui: Change URI helper to a template based approach

---

ui/packages/consul-ui/app/components/consul/intention/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/intention/search-bar/index.scss

ui: Use pill/badge components for intention filter options

---

.changelog/9351.txt
agent/consul/acl_endpoint_test.go
agent/consul/acl_replication_test.go
agent/consul/acl_replication_types.go
agent/consul/fsm/commands_oss.go
agent/consul/state/acl.go
agent/consul/state/acl_events_test.go
agent/consul/state/acl_test.go
agent/structs/acl.go

Previously the tokens would fail to insert into the secondary's state
store because the AuthMethod field of the ACLToken did not point to a
known auth method from the primary.

acl: global tokens created by auth methods now correctly replicate to secondary datacenters

---

.changelog/9351.txt
agent/consul/acl_endpoint_test.go
agent/consul/acl_replication_test.go
agent/consul/acl_replication_types.go
agent/consul/fsm/commands_oss.go
agent/consul/state/acl.go
agent/consul/state/acl_test.go
agent/structs/acl.go

Previously the tokens would fail to insert into the secondary's state
store because the AuthMethod field of the ACLToken did not point to a
known auth method from the primary.
Backport of #9351 to 1.8.x
Reason for manual backport:
```
both modified:   agent/consul/fsm/commands_oss.go
both modified:   agent/consul/state/acl.go
deleted by us:   agent/consul/state/acl_events_test.go
```

[1.8.x] acl: global tokens created by auth methods now correctly replicate to secondary datacenters

---

website/data/docs-navigation.js
website/pages/docs/nia/api.mdx
website/pages/docs/nia/installation/configuration.mdx
website/pages/docs/nia/tasks.mdx

- Configuration page: port config
- API page covering endpoints and parameters
- Tasks page: additional details on event, task status, overall status hierarchy
Links to changes:
- Port config: https://deploy-preview-9362--consul-docs-preview.netlify.app/docs/nia/installation/configuration#port
- New API page: https://deploy-preview-9362--consul-docs-preview.netlify.app/docs/nia/api
- Task page status content: https://deploy-preview-9362--consul-docs-preview.netlify.app/docs/nia/tasks#status-information

nia docs: add status api

---

website/pages/docs/nia/installation/configuration.mdx
website/pages/docs/nia/installation/install.mdx
website/pages/docs/nia/tasks.mdx

[Preview link](https://deploy-preview-9365--consul-docs-preview.netlify.app/docs/nia/installation/configuration#securely-configure-terraform-providers)
Added a section capturing how to configure providers using template syntax for each source supported: Env, Consul KV, Vault. Also updates all references of the deprecated `provider` block to `terraform_provider`

docs/nia: securely configure providers

---

website/pages/docs/nia/installation/configuration.mdx
website/pages/docs/nia/installation/requirements.mdx

[Preview link](https://deploy-preview-9371--consul-docs-preview.netlify.app/docs/nia/installation/requirements#run-an-agent)

docs/nia: configure agent http limits

---

ui/packages/consul-ui/app/routes/dc.js

An Ember codemod for translating old style Ember classes to JS native class syntax that we ran in https://github.com/hashicorp/consul/pull/9093 added a random `undefined` in the code, this PR removes it.

ui: Remove random undefined from codemod run

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/models/dc.js
ui/packages/consul-ui/app/serializers/dc.js
ui/packages/consul-ui/app/services/repository/dc.js
ui/packages/consul-ui/tests/integration/services/repository/dc-test.js

As we now know the name of the local datacenter that the UI is running on using the `CONSUL_DATACENTER_LOCAL` UI environment variable (added in https://github.com/hashicorp/consul/pull/9001) we can automatically redirect the user there on first visit of the UI.
This addresses https://github.com/hashicorp/consul/issues/4366 cc @pierresouchay 
I also added a CSS class to the local datacenter in the datacenter dropdown but didn't do anything visually to call it out as of yet (cc @hannahhearth @jnwright if you want to add anything there )
Lastly, this only redirects you to the local datacenter if you haven't visited the UI on this host before, otherwise you are redirected to the last visited.

ui: Show local datacenter by default on first visit

---

website/pages/docs/nia/installation/configuration.mdx

The config docs were inconsistently including "optional" or the default zero-value, like false or `[]` for empty list. The changes remove them completely and assumes default zero if `required` or a default value is not explicitly documented.

docs/nia: omit zero-value defaults

---

website/pages/docs/nia/api.mdx
website/pages/docs/nia/installation/configuration.mdx

Related change: https://github.com/hashicorp/consul-terraform-sync/pull/158
[Api page change](https://deploy-preview-9391--consul-docs-preview.netlify.app/docs/nia/api)
[Config page](https://deploy-preview-9391--consul-docs-preview.netlify.app/docs/nia/installation/configuration)

docs/nia: update api default port

---

ui/packages/consul-ui/app/services/repository/metrics.js
ui/packages/consul-ui/app/services/ui-config.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/lib/startup/templates/head.html.js
ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
ui/packages/consul-ui/tests/helpers/yadda-annotations.js
ui/packages/consul-ui/tests/steps/doubles/model.js
ui/packages/consul-ui/tests/unit/utils/get-environment-test.js

In order to test certain setups for our metrics visualizations we need to be able to setup several different `ui_config` settings during development/testing. Generally in the UI, we use the Web Inspector to set various cookie values to configure the UI how we need to see it whilst developing, so this PR:
1. Routes `ui_config` through a dev time only `CONSUL_UI_CONFIG` env variable so we can change it via cookies vars.
2. Adds `CONSUL_METRICS_PROXY_ENABLE`, `CONSUL_METRICS_PROVIDER` and `CONSUL_SERVICE_DASHBOARD_URL` so it's easy to set/unset these only values during development.
3. Adds an acceptance testing step so we can setup `ui_config` to whatever we want during testing.
4. Adds an async 'repository-like' method to the `UiConfig` Service so it feels like a repository - incase we ever …

ui: Dev/Test environment configurable metrics

---

website/pages/docs/connect/gateways/mesh-gateway/index.mdx

Added missing words to mesh gateway config instructions, and corrected punctuation a paragraph above. Please review for technical accuracy.

Fixed mesh gateway config instructions

---

website/pages/docs/install/cloud-auto-join.mdx

In the example for azure the "tag_name" field is wrong cause say "tag_key" and not "tag_name"

update example for tag_name

---

.changelog/9262.txt
website/pages/api-docs/catalog.mdx
website/pages/api-docs/health.mdx

There are a few HTTP API endpoints under Health and Catalog that have query parameters for filtering results on specific fields. This filtering can now be done with the `filter` query parameter, so we should deprecate the older parameters and remove them in a future version of Consul.
`/health/state/:state` has a `node-meta` query parameter, but that one can't be replaced by `filter` because the response doesn't include the NodeMeta. The current implementation queries additional tables to get the metadata required for filtering.

docs: deprecate some old filter parameters

---

website/pages/docs/nia/api.mdx
website/pages/docs/nia/tasks.mdx

- Renamed: 'undetermined' => 'unknown', 'healthy' => 'successful',
'degraded' => 'errored'
- Updated language for task status to determine status based on most recent
event
- Updated language on overall status to summarize count of statuses
[Task preview link](https://deploy-preview-9406--consul-docs-preview.netlify.app/docs/nia/tasks#status-information)
[Api preview link](https://deploy-preview-9406--consul-docs-preview.netlify.app/docs/nia/api#status)

docs/nia: update status api with new language and calculations

---

ui/packages/consul-ui/app/controllers/dc/services/show.js
ui/packages/consul-ui/app/routes/dc.js
ui/packages/consul-ui/app/routes/dc/services/show.js
ui/packages/consul-ui/app/routes/dc/services/show/index.js
ui/packages/consul-ui/app/routes/dc/services/show/instances.js
ui/packages/consul-ui/app/routes/dc/services/show/routing.js
ui/packages/consul-ui/app/routes/dc/services/show/topology.js
ui/packages/consul-ui/app/services/repository/dc.js
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/routing.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

This PR continues to split up the once slightly complicated Service > Show Route into separate routes.
We use the new `IsOrigin` and `IsMeshOrigin` properties of services, along with DC.MeshEnabled, to decide whether to show certain tabs, the data for those tabs is only loaded when you visit them, instead of loading it all upfront in Services > Show.
In order to figure out id a DC is `MeshEnabled` we still do one extra HTTP request in order to figure this out, but this is a request that we are likely to reuse if it comes back successful. If we ever end up with a `/v1/catalog/datacenter/:dc-name` to gather data for a specific DC, we can replace this fuether up the Route hierarchy. I added some comments to that effect in the code.
Lastly, one super important thing to point out here is that …

ui: Rearrange Service > Show to load Topology and Routing tabs separately

---

ui/packages/consul-ui/app/components/tab-nav/layout.scss

This ensures scroll bars are mainly hidden, yet visible on small screens
if the tabs are large enough for there to be an overflow

ui: Set overflow: auto on the tab nav

---

ui/packages/consul-ui/README.md

This add the new dev time environment variables we added in https://github.com/hashicorp/consul/pull/9345 which missed the original PR adding the vars to the README.

ui: Add new dev UI environment variables to the README

---

ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

Previously this checked for the existence of `topology` in order to decide whether to show a topology visualization or not. `topology` is always truthy so we change the conditional here to look for the existence of Downstreams and Upstreams. We also change the order of the conditional to make it slightly easier to read.
~(Awaiting a question offline on which link to use in the No Dependencies empty state)~

ui: Show the No Dependencies message when a Topology has no streams

---

website/content/api-docs/acl/index.mdx
website/content/api-docs/connect/intentions.mdx
website/content/docs/agent/config-entries/index.mdx
website/content/docs/agent/config-entries/service-intentions.mdx
website/content/docs/k8s/crds/index.mdx

Remove beta tag for 1.8 and 1.9 features which are now GA.

docs: Remove beta tag for 1.8 and 1.9 features

---

ui/packages/consul-ui/app/components/consul/kv/list/index.hbs

Similar to #9398:
During #9305 we added an InformedAction component 'underneath' our ConfirmationAlerts so we could easily use the design for things other than a 'confirmation'
Unfortunately we omitted reimplementing this in our KV listing which uses a table instead of a list like most of our other listings.
This PR uses the InformedAction for KVListings also and fixes the problem in 1.9.1
Fixes https://github.com/hashicorp/consul/issues/9423

ui: [BUGFIX] Use InformedAction for KV confirmation dialogs

---

ui/packages/consul-ui/app/components/data-collection/index.js
ui/packages/consul-ui/app/search/predicates/acl.js
ui/packages/consul-ui/app/search/predicates/health-check.js
ui/packages/consul-ui/app/search/predicates/intention.js
ui/packages/consul-ui/app/search/predicates/kv.js
ui/packages/consul-ui/app/search/predicates/node.js
ui/packages/consul-ui/app/search/predicates/nspace.js
ui/packages/consul-ui/app/search/predicates/policy.js
ui/packages/consul-ui/app/search/predicates/role.js
ui/packages/consul-ui/app/search/predicates/service-instance.js
ui/packages/consul-ui/app/search/predicates/service.js
ui/packages/consul-ui/app/search/predicates/token.js
ui/packages/consul-ui/app/services/search.js
ui/packages/consul-ui/app/utils/search/exact.js
ui/packages/consul-ui/app/utils/search/fuzzy.js
ui/packages/consul-ui/app/utils/search/predicate.js
ui/packages/consul-ui/app/utils/search/regexp.js
ui/packages/consul-ui/package.json
ui/packages/consul-ui/tests/unit/search/predicates/acl-test.js
ui/packages/consul-ui/tests/unit/search/predicates/intention-test.js
ui/packages/consul-ui/tests/unit/search/predicates/kv-test.js
ui/packages/consul-ui/tests/unit/search/predicates/node-test.js
ui/packages/consul-ui/tests/unit/search/predicates/policy-test.js
ui/packages/consul-ui/tests/unit/search/predicates/role-test.js
ui/packages/consul-ui/tests/unit/search/predicates/service-test.js
ui/packages/consul-ui/tests/unit/search/predicates/token-test.js
ui/yarn.lock

This PR unfortunately moves search things around yet again to match an interface that can be switched in and out of fuzzy searching using fuse.js. We add both fuzzy searching and regex based searching to the codebase here, but it is not yet compiled in.
Once we have some sort of UI widget designed to enable you to select the type of searching you want to use (and store it in local storage), we'll add these into the build.
Unfortunately, there is a little more movement to come in a future PR in order to add a visual status for the filters.

ui: Fuzzy and Regex searching

---

website/content/docs/k8s/helm.mdx

These docs are autogenerated from https://github.com/hashicorp/consul-helm/blob/master/values.yaml.

Update helm docs for external client agents

---

.changelog/9410.txt
ui/packages/consul-ui/app/adapters/node.js
ui/packages/consul-ui/app/components/consul/node/list/index.hbs
ui/packages/consul-ui/app/routes/dc/nodes/index.js
ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs
ui/packages/consul-ui/tests/acceptance/page-navigation.feature
ui/packages/consul-ui/tests/integration/adapters/node-test.js

Nodes themselves are not namespaced, so we'd originally assumed we did not need to pass through the `ns` query parameter when listing or viewing nodes.
As it turns out the API endpoints we use to list and view nodes (and related things) return things that are namespaced, therefore any API requests for nodes do require a the `ns` query parameter to be passed through to the request.
This PR adds the necessary `ns` query param to all things Node, apart from the querying for the leader which only returns node related information.
Additionally here we decided to show `0 Services` text in the node listing if there are nodes with no service instances within the namespace you are viewing, as this is clearer than showing nothing at all. We also cleaned up/standardized the text we use to in the …

ui [BUGFIX] Ensure namespace is used for node API requests

---

CHANGELOG.md
version/version.go

This adds the 1.9.1 changelog entries to the master changelog and bumps the dev version to the next version (1.10.0)

changelog: add 1.9.1 entries

---

.changelog/9432.txt
ui/packages/consul-ui/app/adapters/intention.js
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
ui/packages/consul-ui/app/routes/dc/intentions/edit.js
ui/packages/consul-ui/app/routes/dc/intentions/index.js
ui/packages/consul-ui/app/services/repository.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/create.feature
ui/packages/consul-ui/tests/integration/adapters/intention-test.js
ui/packages/consul-ui/tests/steps.js

This PR adds the `ns=*` query parameter when namespaces are enabled to keep backwards compatibility with how the UI used to work (Intentions page always lists all intention across all namespace you have access to)
See https://github.com/hashicorp/consul/pull/9386 for details.
cc @dcanadillas 🙇 
I found a tiny dev bug for printing out the current URL during acceptance testing and fixed that up while I was there.

ui: [BUGFIX] Request intention listing with ns parameter

---

.changelog/9278.txt
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go
agent/intentions_endpoint_test.go

Restoring a behavior inadvertently changed while fixing https://github.com/hashicorp/consul/pull/9254

server: deletions of intentions by name using the intention API is now idempotent

---

.circleci/config.yml

We actually released Consul v1.7.9 and v1.7.10 built with Go 1.14, and Go 1.13 is now EOL.

ci(1.7.x): update to Go 1.14.13

---

ui/packages/consul-ui/app/components/child-selector/index.hbs
ui/packages/consul-ui/tests/acceptance/dc/acls/policies/as-many/add-existing.feature
ui/packages/consul-ui/tests/acceptance/dc/acls/roles/as-many/add-existing.feature

`ember-power-select` seems to have a somewhat interesting search API in that makes for a strange search/sort implementation.
1. The `options=""` attribute that the select will use for its options **is only when you are not searching using ember-power-select, or the search field is blank**
2. The `search=""` attribute (along with the `searchEnabled={{true}}` attribute) which accepts a function to which the search term is passed that should return a set of options as a result of the search. **If the search field is empty the function is not called and the menu instead uses `options` again**
So when the search is blank the menu will use the `options=""` for its options, not the result of the `search=""` function even when `searchEnabled={{true}}`.
We revisited our power-select related search …

ui: [BUGFIX] Role/Policy selector default sort

---

agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/snapshot_endpoint.go
agent/structs/errors.go

This can happen when one other node in the cluster such as a client is unable to communicate with the leader server and sees it as failed. When that happens its failing status eventually gets propagated to the other servers in the cluster and eventually this can result in RPCs returning “No cluster leader” error.
That error is misleading and unhelpful for determing the root cause of the issue as its not raft stability but rather and client -> server networking issue. Therefore this commit will add a new error that will be returned in that case to differentiate between the two cases.

Special case the error returned when we have a Raft leader but are not tracking it in the ServerLookup

---

sdk/freeport/ephemeral_linux.go

This drops the dependency of sysctl command

sdk: read procfs instead of using sysctl command

---

ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs

This meant that when where were no upstreams, no message would show
telling you of that fact, you'd just get whitespace underneath the selected tab.

ui: Fix up erroneously placed conditional in Upstreams listing

---

.changelog/9488.txt
ui-v2/app/adapters/node.js
ui-v2/app/routes/dc/nodes/index.js
ui-v2/tests/acceptance/page-navigation.feature
ui-v2/tests/integration/adapters/node-test.js

Manual backport of https://github.com/hashicorp/consul/pull/9410 to 1.8.x

ui: Make sure we pass the nspace through to the API for nodes

---

ui/packages/consul-ui/app/components/action/index.hbs
ui/packages/consul-ui/app/components/consul/exposed-path/list/index.hbs
ui/packages/consul-ui/app/components/consul/exposed-path/list/index.js
ui/packages/consul-ui/app/templates/dc/services/instance/exposedpaths.hbs

1. Add the port to the combined address
2. Use the proxy address for the ip address used in the combined address.
3. Add an empty state for when you don't have any ExposedPaths with some info plus a docs link.
Note: We started using our `Action` component a bit more here (our 'you can click on this to do something' component), we had to add some ember related whitespace ignoring here hence the `~`s

ui: Add EmptyState for exposed paths, plus additional details

---

ui/packages/consul-ui/app/templates/application.hbs

This PR adds localStorage (synced across browser tabs) based theme settings that are mapped to the root class of the app. Theming options are currently based on:
1. `prefers-contrast`: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast
2. `prefers-color-scheme`: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
This allows us to move forwards to incrementally add support for 'dark-mode' and 'low/high' contrast themes little by little, but purposefully not giving a user facing knob for this just yet. 
Eventually we will probably want to add support for the user to choose/change these themes via an in app toggle/menu as well as via browser configured `@media` queries when they are more widely supported, hence the use of localStorage here …

ui: Adds localStorage to <html class=""> mapping for user controlled theming

---

agent/consul/cluster_test.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/snapshot_endpoint.go
agent/structs/errors.go

There were conflicts in:
* agent/structs/errors.go related to the ErrQueryNotFound not existing in 1.7.x
* agent/consul/rpc_test.go related to import differences between 1.7.x and 1.8.x
I also pulled in the cluster_test.go file from a later release so I wouldn't have to rewrite the test. ~I did have to modify how a test cluster gets torn down as 1.7.x isn't compiled with Go 1.14. Now the cluster has a shutdown method which will do all the necessary steps to undo what it created.~

Backport #9487 to release/1.7.x

---

.changelog/9505.txt
agent/consul/acl_server.go
agent/consul/leader_test.go

This way we only have to wait for the serf barrier to pass once before
we can upgrade to v2 acls. Without this patch every restart needs to
re-compute the change, and potentially if a stray older node joins after
a migration it might regress back to v1 mode which would be problematic.

acl: use the presence of a management policy in the state store as a sign that we already migrated to v2 acls

---

.changelog/9488.txt
ui-v2/app/adapters/node.js
ui-v2/tests/acceptance/page-navigation.feature
ui-v2/tests/integration/adapters/node-test.js

This is a backport of #9488 to 1.7.x
Nodes themselves are not namespaced, so we'd originally assumed we did not need to pass through the ns query parameter when listing or viewing nodes.
As it turns out the API endpoints we use to list and view nodes (and related things) return things that are namespaced, therefore any API requests for nodes do require a the ns query parameter to be passed through to the request.
This PR adds the necessary ns query param to all things Node, apart from the querying for the leader which only returns node related information.

ui: Backport of #9488: Make sure we pass the nspace through to the API for nodes

---

.circleci/config.yml
ui/GNUmakefile
ui/README.md
ui/package.json
ui/yarn.lock

This PR adds a `make test-workspace` which in turn calls `yarn run compliance` which runs a license check on all our dependencies, mainly borrowed from boundary-ui
Decided that this would be nice on a CI hook, so I added that here also. Moving forwards we can add any further workspace wide sanity checks/tests under this makefile target.
Notes:
1. We removed the `--focus` from the yarn install here. We'd originally added this in the hope that we could separate out dependencies not required for building the final UI artifact, but that didn't work out on first attempt. Additionally for `yarn run compliance` to work it needs the dependencies that are defined in the top level workspace `package.json` added to the yarn dependency cache. Using `--focus` wasn't helping anybody here so no biggie …

ui: Add license checker to the workspace plus CI

---

.circleci/config.yml

We don't use that branch anymore.
Also while I was futzing around a little, I realised why we depend on building the ui for the coverage, so I added a little comment in there.

ui: Remove ui-staging from CI

---

.changelog/9510.txt
go.mod
go.sum
vendor/github.com/armon/go-metrics/metrics.go
vendor/github.com/armon/go-metrics/prometheus/prometheus.go
vendor/modules.txt

go-metrics is updated to 0.3.6 to properly handle help in prometheus metrics
This fixes https://github.com/hashicorp/consul/issues/9303

[bugfix] Prometheus metrics without warnings

---

website/content/commands/snapshot/save.mdx

Taking a snapshot with `consul snapshot save $FILE` causes a Consul server to write the contents of the snapshot to disk before sending it to the CLI client. By default, this is done on `/tmp` on most systems. There are some situations where the `/tmp` partition isn't large enough for a snapshot though and some other location needs to be specified. To do that, you simply need to set the `TMPDIR` environment variable for the Consul server process. This adds a note to the documentation for `consul snapshot save` that discusses this.

docs: add note about TMPDIR for snapshots

---

test/integration/connect/envoy/run-tests.sh

To fix failing integration tests. The latest version (`1.7.4.0-r0`) appears to not be catting all the bytes, so the expected metrics are missing in the output.
Reported the issue here: https://github.com/alpine-docker/socat/issues/11
Test failures can be seen here: https://app.circleci.com/pipelines/github/hashicorp/consul/15747/workflows/1c42c50d-eaeb-49c8-8ee6-eddf18895b52

Pin alpine/socat image to a version

---

agent/acl.go
agent/acl_test.go
agent/agent.go
agent/consul/acl.go
agent/consul/acl_client.go
agent/consul/acl_test.go

I found it not immediately obvious how to use these methods when I first went to use them. I'm hoping that removing some of the unused parts, removing some extra wrapping, and adding some godoc will help make it a bit easier to use.
I think there are potentially a few more improvements that could be made in this area, but I'm making this change initially to keep the diff small.

acl: Remove some unused things and document delegate method

---

api/agent.go
api/agent_test.go

Fixes #8605
So that operations can timeout instead of hanging forever.

api: Add a context to ServiceRegisterOpts

---

ui/GNUmakefile

In https://github.com/hashicorp/consul/pull/9507 we added a new target to the top of our Makefile, which of course redefines the default Makefile target ... 🤦 
This uses `.DEFAULT_GOAL` to explicitly set the default target instead.

ci: Explicitly specify a default Makefile target, don't default to the first target

---

website/content/docs/agent/config-entries/ingress-gateway.mdx
website/content/docs/agent/config-entries/proxy-defaults.mdx
website/content/docs/agent/config-entries/service-defaults.mdx
website/content/docs/agent/config-entries/service-intentions.mdx
website/content/docs/agent/config-entries/service-resolver.mdx
website/content/docs/agent/config-entries/service-router.mdx
website/content/docs/agent/config-entries/service-splitter.mdx
website/content/docs/agent/config-entries/terminating-gateway.mdx

With the addition of Kube CRD docs alongside the HCL config entry docs, it makes sense for the sidebar to use the name for the config entry (e.g. `Ingress Gateway` instead of `ingress-gateway`) because the CRD name is `IngressGateway`.

Use full names for cfg entries in sidebar

---

.circleci/config.yml
agent/agent.go
agent/xds/clusters_test.go
agent/xds/endpoints_test.go
agent/xds/listeners_test.go
agent/xds/routes_test.go
agent/xds/server.go
agent/xds/server_test.go
agent/xds/testing.go

One commit related to #8329
Mostly some minor cosmetic cleanup as I was reading over this code again. Also fixed what seems to be the only data race in the `agent/xds` package, which allows us to run the tests with `go test -race`.

xds: enable race detector and some small cleanup

---

agent/agent_test.go
agent/checks/alias.go
agent/consul/discoverychain/compile.go
agent/consul/state/config_entry.go
agent/local/state.go
agent/structs/config_entry.go
agent/structs/config_entry_gateways.go
agent/structs/structs.go
agent/structs/structs_oss.go
agent/structs/structs_oss_test.go

Fixes #7581 (maybe, worth some discussion)
We often use the struct without a pointer. Formatting the struct will not call String() because it had a pointer receiver. Making String() a non-pointer receiver may fix the problem.
[ref](https://golang.org/doc/faq#different_method_sets)
> As the Go specification says, the method set of a type T consists of all methods with receiver type T, while that of the corresponding pointer type *T consists of all methods with receiver *T or T. That means the method set of *T includes that of T, but not the reverse.
https://golang.org/doc/faq#methods_on_values_or_pointers suggests
> Next is consistency. If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used. …

Fix printing of ID types

---

agent/config/builder.go
agent/config/builder_test.go
agent/config/config.go
agent/config/default.go
agent/config/default_oss.go
agent/config/flags.go
agent/config/runtime_test.go

This is a small cleanup of `config`.
* starts using `LiteralSource` for some of the default config sources
* unexports some functions that don't need to be exported
* stores a `BuilderOpts` on `Builder`, which removes the need to copy over the `DevMode` field, and allows us to move the testing shims onto BuilderOpts. Since these are effectively inputs to `Build` they seem more appropriate on `BuilderOpts`.

config: move testing shims and cleanup some defaults

---

website/content/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes.mdx

Documents https://github.com/hashicorp/consul-helm/pull/740.
Also resolves/helps with https://github.com/hashicorp/consul-helm/issues/743.

Document how clients not on K8s can join a DC in K8s

---

agent/config/agent_limits_test.go
agent/config/builder.go
agent/config/builder_oss.go
agent/config/builder_oss_test.go
agent/config/default.go
agent/config/runtime_oss_test.go
agent/config/runtime_test.go

Now that config can come from non-file sources it is not safe to assumes that the mapstructure `Metdata.Keys` will contain all the keys because some config can be specified with command line flags or literals.
This change allows us to remove the json marshal/unmarshal cycle for command line flags, which will allow us to remove all of the hcl/json struct tags on config fields. That is done in #9250 which is a follow up to this PR.
This PR also does a bit of cleanup in some of the config tests to remove unused things and make the failure messages easier to understand.

config: use fields to detect enterprise-only settings

---

agent/config/config.go

Branched from #9249
The `hcl` tags have been unnecessary since we started using mapstructure many years ago. The `json` tags were only being used for serializing config flags to json so that they can be parsed again as JSON. A previous commit (in #9249) removed that serialization round-trip, which removes the need for the `json` struct tag as well.
Using find/replace with regex
json:"[^"]+"
hcl:"[^"]+"

config: remove unnecessary json/hcl struct tags

---

.changelog/9320.txt
agent/consul/replication.go

Previously this conditional accidentally skipped over all replicators that did not configure `r. suppressErrorLog`.

Log replication warnings when no error suppression is defined

---

.changelog/9530.txt
agent/config/builder.go
agent/config/runtime_test.go

This option has no effect when running as an agent.

Display a warning when rpc.enable_streaming = true is set on a client

---

website/content/docs/nia/configuration.mdx

CTS running with default configuration will communicate over http unless the Consul client is configured with TLS. Having the example set the scheme to https is misleading and will result in an error since TLS is not configured by default:
```
http: server gave HTTP response to HTTPS client
```
PR replaces the example block with a default value for those who do copy the config.
Resolves https://github.com/hashicorp/consul-terraform-sync/issues/163

docs/nia: Fix example config block to execute properly

---

ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/instances/navigation.feature
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/services/show.js

aka the 'in/out/in' test, aka 'The Hokey Cokey Test ™️ '
This PR is additional to https://github.com/hashicorp/consul/pull/9524 and is the base branch for this PR.
Here we add a test for clicking forwards and backwards, and then forwards again between the Service Detail page and the Service Instance detail page, to prove that the fix in https://github.com/hashicorp/consul/pull/9524 works.
I undid the fix to verify that this was failing with a 404 before the fix, redoing the fix makes the tests pass.
Notes:
We cheated a little here as in the app we call the same endpoint in quick succession one after the other and we have no generic way of mocking this absolutely realistically from within our acceptance tests. We rely on the fact that the list of instances from consul are then filtered by …

ui: Service Instance forwards/backwards/forwards navigation test

---

ui/packages/consul-ui/app/models/proxy.js
ui/packages/consul-ui/app/routes/dc/services/instance.js
ui/packages/consul-ui/app/serializers/proxy.js
ui/packages/consul-ui/app/services/repository/service-instance.js
ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/instances/navigation.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/instances/navigation-steps.js
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/services/show.js

🐛 Clicking on a instance, then back, then clicking on the instance again would redirect users to a 404 error page. 
Solution: There is a relationship between service-instance and proxy-instance models and they both have attr called `Node`. In the service-instance model `Node` is an object and in the proxy-instance model it's a string. We expect a string at all times. To avoid overwriting we have renamed `Node` to be `NodeName` in the proxy-instance model. 
Test: Left a TODO note on the navigation tests. Unable to complete due to mock data.

ui: Rename a model attribute to not be overwritten by ember-data

---

.changelog/9468.txt
command/commands_oss.go
command/intention/intention.go
command/intention/list/intention_list.go
command/intention/list/intention_list_test.go
website/content/commands/intention/index.mdx
website/content/commands/intention/list.mdx

This PR is based on the previous work by @snuggie12 in PR #6825. It adds the command `consul intention list` to list all available intentions. The `list` functionality for intentions seems a bit overdue as it's just very handy. The web UI cannot list intentions outside of the `default` namespace, and using the API is sometimes not the friendliest option. ;)
I cherry picked snuggie12's commits who did most of the heavy lifting (thanks again @snuggie12 for your great work!). The changes in the original commit mostly still worked on the current `HEAD`. On top of that I added support for namespaces and fixed the docs as they are managed differently today. Also the requested changes related to the "Connect" references in the original PRs have been addressed.
Fixes #5652

cli: Add consul intention list command (based on PR #6825)

---

.changelog/9440.txt
agent/consul/state/usage.go
agent/consul/state/usage_oss.go
agent/consul/state/usage_test.go

A log line like so:
```
2020-12-18T20:39:41.784Z [WARN]  agent.fsm: DeleteNode failed: error="failed to insert usage entry for "service-names": delta will cause a negative count"
```
When multiple service instances are registered/deregistered at once, usage metrics of service names would be computed incorrectly, eventually leading to state store errors like the above. This could happen on `DeleteNode` RPCs, and also when Consul does a restore.
To fix, we collect all of the memdb changes and then do a pass through the updated memdb state to reconcile, instead of dealing with the memdb changes one at a time.
Unfortunately it might not error out immediately, if you have enough services that the count does not go negative. Instead, the usage metrics will be subtly wrong until another service …

Fix bug in usage metrics when multiple service instances are changed in a single transaction

---

grafana/README.md
grafana/consul-server-monitoring.json

Updates should be shared here in the future before being uploaded to the Grafana community dashboard page.

add the latest export-for-public revision of the consul-server-monitoring grafana dash

---

agent/structs/structs_oss_test.go
agent/structs/structs_test.go

Five types seems to have a CacheInfo() method. The cache Key for one of them (`DatacentersRequest`) is a constant. Therefore, I didn't add a test for that type. Please let me know what can be improved on this PR.

(WIP) Add a add completeness test for all types with CacheInfo method

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs

ui: Show a feedback icon instead of a learn icon in the help menu

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/installation/requirements.mdx

[preview](https://deploy-preview-9561--consul-docs-preview.netlify.app/docs/nia/configuration#cts_user_defined_meta)

docs: Add cts_user_defined_meta option

---

agent/consul/leader_connect_test.go
agent/consul/stats_fetcher_test.go

Related to #8329
Fixing these gets us closer to being able to enable the `-race` detector for all packages.

Fix a couple data races in tests

---

.changelog/9436.txt
agent/structs/structs.go
agent/structs/structs_test.go

The field was not being included in the cache info key. This would result in a DNS request for
`web.service.consul` returning the same result as `web.ingress.consul`, when those results should
not be the same. The same bug existed in the HTTP api when the cache is enabled.
Issue reported by @blake 
This PR fixes the problem by adding the field to the cache key.

structs: fix caching of ServiceSpecificRequest when ingress=true

---

.changelog/8696.txt
agent/acl_test.go
agent/agent.go
agent/agent_endpoint_test.go
agent/config/runtime.go
agent/consul/client.go
agent/consul/client_test.go
agent/consul/config.go
agent/consul/rpc_test.go
agent/consul/server.go
agent/consul/server_test.go

Previously it was not clear which fields were being reloaded. They were hidden in multiple function calls and large structs. With this change the list of reloadable fields is explicit.
I believe this commit also fixes a bug. Previously `RPCMaxConnsPerClient` was not being re-read from the RuntimeConfig, so passing it to Server.ReloadConfig was never changing the value.
Also improve the test runtime by not doing a lot of unnecessary work, and fixed the naming of one of the config fields so that it is consistent across structs.

agent/consul: make Client/Server config reloading more obvious

---

.circleci/config.yml
.circleci/terraform/load-test/.terraform.lock.hcl
.circleci/terraform/load-test/main.tf
.circleci/terraform/load-test/variables.tf
.github/workflows/load-test.yml
.gitignore

This PR adds automation to run load tests against PRs. Currently this only supports PRs made internally (on a branch and not a fork) since we only publish dev builds to s3 from non-forks. 
To trigger load tests, you apply the `pr/load-test` GitHub label to a specific PR. This will trigger a GitHub action that passes the commit SHA of the PR, and a boolean to signal load tests to run, to CircleCI which triggers a pipeline that just runs the `load-test` workflow. It will also post the URL of the CircleCI workflow to the PR since API triggered runs do not show up in GitHub checks. If you make subsequent commits to the PR and want to run load tests again, you would remove the label and readd it to retrigger the GitHub Action again. 
**Note:** I had to modify the AWS credential environment …

ci: add load test automation

---

ui/packages/consul-ui/app/helpers/href-to.js

This originally comes from the ember-href-to helper and is one of those
errors that when I see it I think ... hmmm
This gives a little bit more of a clue as to what is wrong by logging
the route name you asked for plus the params you passed to it so you:
1. Have more help finding the href-to that is problematic in the
template/component
2. Can see all the parameters you passed (including a potential null
parameter for the thing you are missing)
After:

ui: Improves the 'you must provide ... to `generate`' error from href-to

---

ui/packages/consul-ui/app/components/consul/intention/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/kv/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/node/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/search-bar/index.hbs
ui/packages/consul-ui/app/components/search-bar/index.js
ui/packages/consul-ui/app/filter/predicates/intention.js
ui/packages/consul-ui/app/filter/predicates/kv.js
ui/packages/consul-ui/app/filter/predicates/node.js
ui/packages/consul-ui/app/routes/dc/intentions/index.js
ui/packages/consul-ui/app/routes/dc/nodes/index.js
ui/packages/consul-ui/app/routes/dc/services/show/intentions/index.js
ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
ui/packages/consul-ui/app/templates/dc/kv/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
ui/packages/consul-ui/tests/unit/filter/predicates/intention-test.js
ui/packages/consul-ui/translations/en-us.yaml

This continues on from https://github.com/hashicorp/consul/pull/9442 (which is the base branch for this PR), by adding the 'Filtered by' functionality to Nodes, KVs and Intentions (the top level, non-restricted areas), plus per service Intentions.
Additional notes:
1. Moved a top level i18n key: `component` > `components` to mirror the ember `components` directory.
2. Exported the generic search and menu components from the SearchBar component and used those for if we need to switch this up slightly at some point.
3. Moved a few `model` hooks to `async` (only was is actually async)
Apart from that its mainly 'copy/pasta, tweak, tweak, tweak' three times.

ui: Add filtered by in Nodes, KV and Intentions

---

.changelog/9513.txt
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/notifications/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
ui/packages/consul-ui/app/routes/dc/services/show/topology.js
ui/packages/consul-ui/app/services/feedback.js
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/topology-steps.js
ui/packages/consul-ui/tests/helpers/type-to-url.js

This PR adds various things:
Previously (in 1.9.0) if an intention already existed for an upstream, we would link to the intention save form in order for you to save it. Once saved this would push you back to the intention listing page, rather than back to the topology page. The user flow is much nicer when an upstream doesn't have an existing intention, in which case we simply created/saved the intention in-place within the topology view.
In 1.9.1 we accidentally updated things to not distinguish different flows between an upstream with an existing intention and a non-existent intention. This meant that an intention description or metadata could potentially be overwritten if saved from the topology view page.
This PR adds the user flow we actually want, i.e. there is no difference …

ui: Topology intention saving improvements

---

.changelog/9498.txt
agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/consul/leader.go
agent/consul/leader_connect.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server.go
agent/consul/server_connect.go
command/intention/list/intention_list_test.go

Fixes #9498
After fixing that bug I uncovered a couple more:
1. Fix an issue where we might try to cross sign a cert when we never had a valid root.
2. Fix a potential issue where reconfiguring the CA could cause either the Vault or AWS PCA CA providers to delete resources that are still required by the new incarnation of the CA.
The main fix was to remove the call to `InitializeCA` from within `establishLeadership`. Beyond that I made the `CAManager` have a `Start` method whose responsibility is to attempt to init the CA and if it fails spawn some background routines to ensure that will happen. Once CA initialization is complete the other background routines for performing cert renewal and primary dc roots watches are started.

Ensure that CA initialization does not block leader election.

---

agent/consul/state/catalog.go

Deleting from memdb inside an interation can cause a panic from Iterator.Next. This
case is technically safe (for now) because the iterator is using the root radix tree
not a modified one.
However this could break at any time if someone adds an insert or delete to the coordinates table
before this place in the function.
It also sets a bad example, because generally deletes in an interator are not safe. So this
commit uses the pattern we have in other places to move the deletes out of the iteration.
There's no test for this because nothing has really changed. This is "future proofing".
This was found while investigating #9566. I don't think this one can cause a panic, but still good to fix.

state: do not delete from inside an iteration (coordinates)

---

agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

Fixes: #9566
There is a panic that can be triggered with go-memdb when within a write transaction:
1. An index is modified with an insert/delete.
2. An object referenced by that index is deleted from inside an iterator while there are remaining elements to iterate through.
Memdb would benefit from some changes to prevent this foot-gun scenario, but that's left as future work for now.
This PR avoids the panic by collecting objects from the iterator before doing any of the deletions.

Fix crash from deleting objects while stepping through iterator

---

.changelog/9589.txt
agent/consul/state/catalog.go
agent/consul/state/catalog_test.go

To keep track of upstream/downstream pairings for the mesh topology visualization we keep the mapping stored in memdb. This pairing mapping contains a map with a reference to every proxy ID that contains this pair in its service definition.
As proxy instances are deregistered, this map needs to be updated to remove that reference for the pairing.
Currently that map is not being updated on deletions when the proxy ID being registered **is not** the last instance for that proxy **name**.
This PR ensures we persist the new reference map when proxy IDs are deregistered, and fixes the broken assertion in the relevant test.
Fixes: #9566

Update topology mapping Refs on all proxy instance deletions

---

ui/packages/consul-ui/app/models/gateway-config.js
ui/packages/consul-ui/app/models/service.js
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/tests/integration/services/repository/service-test.js

In https://github.com/hashicorp/consul/pull/9399 we added the ember-intl addon, which has its own format-number helper.
We replaced our own similarly named helper with this one, but the
ember-intl one is far stricter and errors if the arguments passed are
undefined. Our previous one would cope with this.
In the case of this issue, the format-number helper fails on the service listing page where any gateways have an empty GatewayConfig (`{}`).
We'd rather continue to use the stricter ember-intl helper, so here we
convert the GatewayConfig property to a model fragment so that we can
give the GatewayConfig.AssociatedServices property a default zero value.
Therefore if we ever get `{}` it is automatically converted to `{AssociatedServices: 0}`
This is a bug on `master` currently, not 1.9.* …

ui: Convert Service.GatewayConfig to a model fragment

---

agent/auto-config/auto_config_test.go

These expectations are optional because in a slow CI environment the deadline to cancell the context might occur before the go routine reaches issuing the RPC. Either way we are successfully ensuring context cancellation is working.

Fix flaky test by marking mock expectations as optional

---

agent/ui_endpoint.go
agent/ui_endpoint_test.go

A continuation of https://github.com/hashicorp/consul/pull/9397 fixes https://github.com/hashicorp/consul/issues/9535
In some circumstances endpoints that use this function will have no
results in them (due to ACLs, Namespaces, filtering or incorrect/missing
central config registration).
This ensures that the response is at least an empty array (`[]`) rather
than `null`.

api: Ensure internal/ui/gateway-service-nodes responds with array

---

.changelog/9498.txt
agent/connect/ca/mock_Provider.go
agent/connect/ca/provider.go
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/consul/leader.go
agent/consul/leader_connect.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server.go
agent/consul/server_connect.go

Relates to #9498
See #9570 for more context. This is just a backport of that PR for v1.8.x.
Conflicts:
* agent/consul/leader_connect.go - The main conflicts were with changing starting/stopping of the intentions migration added in 1.9.x back to the intention replicator in 1.8.x

Backport #9570 to release/1.8.x: Ensure that CA initialization does not block leader election.

---

.circleci/config.yml

`git diff --exit-code` does not account for untracked files but using a simple `git status -s` and checking for non-zero output will include all varieties of file changes.

ci: change check-vendor to verify git status has no changes

---

.circleci/config.yml

The check should error for non-zero rather than zero output.

ci: fix logic for check-vendor

---

ui/packages/consul-ui/app/components/search-bar/index.hbs
ui/packages/consul-ui/app/components/search-bar/index.js
ui/packages/consul-ui/app/components/search-bar/utils.js
ui/packages/consul-ui/tests/unit/components/search-bar/filters-test.js

This PR is part of https://github.com/hashicorp/consul/pull/9442 and the base branch of this is that PR.
Previously when removing a special 'searchproperty' filter, it would
remove all the search property filters instead of only the one you had
clicked.
This fixes that up, adds unit tests and adds copious amounts of documentation
around the filter data reshaping function for future self/somebody.

ui: Fix 'filter by' removal and provide more tests/docs around it

---

ui/packages/consul-ui/app/components/consul/health-check/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/service-instance/search-bar/index.hbs
ui/packages/consul-ui/app/filter/predicates/health-check.js
ui/packages/consul-ui/app/filter/predicates/service-instance.js
ui/packages/consul-ui/app/routes/dc/services/instance/healthchecks.js
ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/services/show/instances.hbs
ui/packages/consul-ui/translations/en-us.yaml

This continues on from #9442 (which is the base branch for this PR), by adding the 'Filtered by' functionality to Healthchecks, and ServiceInstances (sub Node tabs).

ui: Add 'filtered by' to Healthchecks and ServiceInstance listings

---

ui/packages/consul-ui/app/components/consul/upstream-instance/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/upstream/search-bar/index.hbs
ui/packages/consul-ui/app/filter/predicates/service-instance.js
ui/packages/consul-ui/app/filter/predicates/service.js
ui/packages/consul-ui/app/models/service.js
ui/packages/consul-ui/app/routes/dc/services/show/services.js
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/styles/typography.scss
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/app/templates/dc/services/show/services.hbs
ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
ui/packages/consul-ui/translations/en-us.yaml

This continues on from #9442 (which is the base branch for this PR), by adding the 'Filtered by' functionality to Upstreams, Linked Services and Upstream Instances tabs (remaining sub Service/Service Instance tabs)
Additionally, I noticed our filter for Services with no healthchecks at all was not configured, so I added that on the end here.

ui: Add 'filtered by' to Upstreams and UpstreamInstance listings

---

.changelog/9519.txt
agent/consul/helper_test.go
agent/consul/leader.go
agent/consul/leader_federation_state_ae.go
agent/consul/leader_federation_state_ae_test.go

This way we only have to wait for the serf barrier to pass once before
we can make use of federation state APIs Without this patch every
restart needs to re-compute the change.

server: use the presense of stored federation state data as a sign that we already activated the federation state feature flag

---

agent/agent.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/agent_test.go
agent/service_checks_test.go
agent/service_manager.go
agent/service_manager_test.go
agent/sidecar_service.go
agent/sidecar_service_test.go
command/maint/maint_test.go

This PR removes one of two nearly identical `Agent.AddService` functions by accepting a struct as parameters. The other function is deprecated and moved into test files, since it is used by many tests. It is now a wrapper around the single `AddService` so we know the live code path is actually being tested.
The `AddService` flow can be seen in the diagram below. This PR removes the `AddServiceAndReplaceChecks` branch in the logic.

agent: reduce AddService

---

.changelog/9528.txt
agent/agent_test.go
agent/consul/gateway_locator.go
agent/consul/gateway_locator_test.go

server: initialize mgw-wanfed to use local gateways more on startup

---

website/content/api-docs/operator/autopilot.mdx

There was a minor error using a component on this page which caused the entire page not to render. This fixes that situation.

fix render error on autopilot docs page

---

agent/agent.go
agent/agent_test.go
agent/service_manager.go

Branched from #9300 and building on those changes, this PR removes another branch from the `AddService` flow.
Also splits out some fields from the `AddServiceRequest` struct into internal structs to make their use more explicit. Removes an intermediary `serviceRegistration` struct which was populated from `AddServiceRequest`, and then used exclusively to build a new `AddServiceRequest` struct.
A couple of the fields on the new internal `addServiceRequestLocked` struct are replaced with a single field. Also adds some godoc for those fields to explain how they are used.
With the two branches removed, the flow now looks like this:

agent: reduce AddService 2

---

ui/packages/consul-ui/app/components/consul/discovery-chain/skin.scss
ui/packages/consul-ui/app/components/consul/external-source/index.scss
ui/packages/consul-ui/app/components/consul/health-check/list/skin.scss
ui/packages/consul-ui/app/components/consul/intention/permission/form/skin.scss
ui/packages/consul-ui/app/components/consul/kind/index.scss
ui/packages/consul-ui/app/components/consul/lock-session/form/index.scss
ui/packages/consul-ui/app/components/informed-action/skin.scss
ui/packages/consul-ui/app/components/modal-dialog/skin.scss
ui/packages/consul-ui/app/components/notice/skin.scss
ui/packages/consul-ui/app/styles/base/components/form-elements/skin.scss
ui/packages/consul-ui/app/styles/base/typography/base-placeholders.scss
ui/packages/consul-ui/app/styles/base/typography/index.scss
ui/packages/consul-ui/app/styles/base/typography/semantic-variables.scss
ui/packages/consul-ui/app/styles/components/app-view/skin.scss
ui/packages/consul-ui/app/styles/components/empty-state/skin.scss
ui/packages/consul-ui/app/styles/routes/dc/services/index.scss
ui/packages/consul-ui/app/styles/typography.scss
ui/packages/consul-ui/app/templates/dc/services/instance/metadata.hbs

We've always had this idea of being able to markup information
semantically without thinking about what it should look like, then
applying our `%h*` placeholder styles to control what the information
should look like.
Back when we originally made our set of `%h*` placeholders, we tried to
follow Structure as much as possible, which defined the largest header
(which we thought would have been the h1 style) as a super large `3.5rem`.
Therefore we made our set of `%h*` placeholders the same as Structure
beginning at that large 3.5 size. We then re-overwrote those sizes only in
Consul specific CSS files thinking that this was due to us existing
before Structure did.
Lately we saw an extra clue in Structure - the extra large 3.5 header was
called 'h0'.
This commit moves all our headers to use …

ui: Re-organize our %h* placeholders

---

website/content/docs/connect/config-entries/proxy-defaults.mdx

This is a common configuration and some folks (https://discuss.hashicorp.com/t/proxydefaults-for-envoy-kubernetes-with-external-consul-server/20169) had trouble with it.

Document proxy-defaults config for prometheus

---

.changelog/9585.txt
agent/consul/server_test.go
agent/pool/peek_test.go
agent/routine-leak-checker/leak_test.go
agent/testagent.go
command/tls/ca/create/tls_ca_create.go
command/tls/ca/create/tls_ca_create_test.go
tlsutil/generate.go
tlsutil/generate_test.go

There is one caveat: you have to know your clusterID in order to be able to generate a proper Connect CA. There is at least one way to get that: extract it from an existing Consul Connect CA from the very same cluster.

Add flags to support CA generation for Connect

---

.changelog/9626.txt
agent/consul/leader.go
agent/consul/snapshot_endpoint_test.go
go.mod
go.sum
vendor/github.com/hashicorp/raft-autopilot/autopilot.go
vendor/github.com/hashicorp/raft-autopilot/go.mod
vendor/github.com/hashicorp/raft-autopilot/go.sum
vendor/github.com/hashicorp/raft-autopilot/mutex.go
vendor/github.com/hashicorp/raft-autopilot/run.go
vendor/github.com/hashicorp/raft-autopilot/state.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/modules.txt

Upgrade raft-autopilot and wait for autopilot it to stop when revoking leadership

---

.circleci/scripts/cherry-picker.sh

We have automated cherry-picks that happen on any PRs with `type/docs-cherrypick` to the `stable-website` branch and automatically to the latest `release/1.#.x` branch. However, if the cherry-pick is not clean onto `stable-website`, the working directory is not cleared before attempting to pick into the latest release branch. This PR resets the working directory to allow that cherry-pick to happen regardless of whether the pick to `stable-website` succeeds or fails.

ci: reset working directory between cherrypick labels

---

agent/config/builder.go

This change allows us to re-use these functions in other places without the Builder, and makes it more explicit about which functions can warn/error and which can not.

config: remove Builder receiver from funcs that dont use it

---

api/api.go
api/api_test.go

I've got Consul behind a proxy that requires setting headers to authentication. 
This allows you to configure the client with headers that will be passed on every request. Headers that are set here have a lower precedence than the more specific fields, such as token and basic auth.
💭 Perhaps there should be a way to set this via the CLI too, open to suggestions for what format that would be ... perhaps `CONSUL_HTTP_HEADERS=key:value,hello:world` ?

Allow setting arbitrary headers in API client

---

website/content/api-docs/libraries-and-sdks.mdx
website/content/docs/download-tools.mdx

Hi everyone,
I'm developing an open source CLI tool for easily editing Consul KV values from your favorite text editor. I've added to Client Libraries & SDKs page on website.
Repository: https://github.com/sadedil/kvit
Kind regards,
Mustafa

Add a CLI tool for "Client Libraries & SDKs" page

---

agent/agent.go
agent/service_manager.go
agent/service_manager_test.go
go.mod
go.sum
lib/mutex/mutex.go
lib/mutex/mutex_test.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/golang.org/x/sync/singleflight/singleflight.go
vendor/modules.txt

Building on #9301
The `ServiceManager.Start` goroutine was used to serialize calls to `agent.addServiceInternal`.
All the goroutines which sent events to the channel would block waiting for a response from that same goroutine, which is effectively the same as a synchronous call without any channels. This goroutine existed as a workaround for synx.Mutex not having any way to stop blocking when a context is cancelled.  
The problem occurred when a service was being replaced. `ServiceManager.AddService` would cancel the old watcher and wait for the goroutine to exit. Previously, since the stateLock was acquired in `ServiceManager.Start` goroutine, it would block until the call to `Agent.AddService` unlocked, at which time it would resume handling updates. 
This PR removes the goroutine and …

agent: remove ServiceManager.Start goroutine

---

ui/packages/consul-ui/app/services/repository/proxy.js
ui/packages/consul-ui/app/services/repository/service-instance.js

Fixes https://github.com/hashicorp/consul/issues/9648
This PR fixes essentially two issue related to the listing of healthchecks correctly.
In https://github.com/hashicorp/consul/pull/9314 we changed our separate Proxy/ServiceInstance models to use a single ServiceInstance model extending from the Proxy model. This meant we had a single model to represent a Service Instance that happened to be a connect sidecar proxy. Unfortunately we didn't realize a clash of property names when we did this, both the Proxy endpoint and the ServiceInstance endpoint contain a `Node` property that are two different shapes. One is a plain string that is the name of the node and one is a map/object containing all the properties of a node (including its name), `"name"` vs `{Name: "name"}`.
In …

ui: [BUGFIX] Fix missing or duplicate service instance health checks

---

ui/packages/consul-ui/app/components/data-collection/index.js

The `@items` attribute of our DataCollection component is not 100% guaranteed to be set, in this specific case `Service.Proxy.Upstreams` could be undefined if there are no Upstreams set for a proxied service. As a consequence of this the Service Instance > Upstreams tab will not error, although it will just show an empty page instead of our 'no upstreams' message.
This guards for an empty `@items` attribute/argument from within the `DataCollection` component.

ui: Upstreams - Check for a non-existent items argument/attribute

---

ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/utils/merge-checks.js
ui/packages/consul-ui/tests/unit/utils/merge-checks-test.js

We noticed that since we now merge both the healthchecks for the service instance and the healthchecks for the proxy for that service instance all together in one list, node checks associated with the service/proxy appear in the listing twice (for example the serf healthcheck)
This PR dedupes these based on CheckID and Node name of the check. We had a quick check in with backend folks to make sure CheckID is guaranteed to be set and it seems to be.
We extracted the re-shaping code here into a util for easier unit-like testing.

ui: Keep track of previous node checks and avoid adding them twice

---

.circleci/scripts/cherry-picker.sh

This PR addresses the super rare case in the cherry-picking script where the automation may checkout a branch, cherrypick cleanly, but there may have been a new commit in that branch (either pushed manually or via another CI automated cherry pick job) in that time and the subsequent git push fails since there are new commits. This fix ensures notifying a success/fail when both the `git cherry-pick` and `git push` are both successful rather than when only the cherrypick is successful.

ci: fail cherrypick if git push fails

---

ui/packages/consul-ui/README.md
ui/packages/consul-ui/app/router.js
ui/packages/consul-ui/app/utils/routing/walk.js

Back in https://github.com/hashicorp/consul/pull/5206 we fixed a URL encoding/decoding issues with URLs for wildcarded routes by extracting our routing configuration to a JSON-like JS pojo, before feeding this in Embers `Route.map`. This meant we could inspect the routing configuration from elsewhere to provide support for URL encoding/decoding. The one downside in doing this was that we were not using Embers Route DSL to code our Routing configuration.
At the time we wrote a little `dump` util in order to easily convert the JSON-like configuration back to Ember's Router DSL should we ever need to, but commented it out as we didn't want it ending up in the production source code.
We've since discovered `runInDebug`, which lets you specify inline code to be stripped from production builds. …

ui: Adds a `Routes()` router DSL dumping function only in dev mode

---

ui/packages/consul-ui/README.md
ui/packages/consul-ui/app/utils/get-environment.js

Following on from https://github.com/hashicorp/consul/pull/9666, this PR adds a `Scenario()` debug function to allow you to easily save off 'scenarios' for easy debugging or demoing purposes.
When called with no arguments (using WebInspector's `console`, or via a bookmarklet), the function will open a new tab with an easily copy/pastable URL (for sharing preview sites) and a draggable bookmarklet link containing the configuration for your current development/debug configuration settings (which we can set via the cookies panel in the WebInspector). Whilst this function only exists in non-production environments we also only emit cookies that begin with `CONSUL_` which we know are our own debug/dev cookies.
Scenarios are composable, so instead of having lots of multiple bookmarklets, you …

ui: Add 'Scenario' debug function for easy saving debug scenarios

---

.github/workflows/changelog-check.yml

https://github.com/hashicorp/consul/pull/8387 added go-changelog which generates changelog entries from the `.changelog` directory. This PR adds a small CI check to add a comment to any PR that does not have the `pr/no-changelog` label to remind the author to double check that the PR does not require a changelog entry.

ci: add script to check for .changelog file in PRs

---

ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.js
ui/packages/consul-ui/app/helpers/unique-id.js

This PR adds a `{{unique-id}}` helper (the same as the upcoming native version, see Ember RFC 659).
We've held off adding something like this for a while as we knew something was coming down the line from the ember core team. Now we've seen that there is a very straightforwards polyfill for this based on the RFC, we decided to implement a similar polyfill ourselves to avoid an additional dependency (plus we currently use an injectable service to provide the ember `guidFor` functionality).
Once this is in ember itself we can just remove our own helper, unless we want to keep the injectable service for some reason.
There are quite a few areas where we'd use this over providing a property on a component, but we can replace those instances as we go.
Usage follows the RFCs recommendation, …

ui: Adds unique-id helper

---

website/content/docs/nia/configuration.mdx

This reorganizes and flags where and when sensitive information may be written in plain-text
[Docs preview](https://consul-odji97e9c.vercel.app/docs/nia/configuration#terraform-provider)

docs/nia: Update verbiage around securely configuring providers

---

.github/workflows/changelog-check.yml

Previously when using `with ref`, this job would checkout that commit with a detached HEAD. Since there were no references to the base ref (usually `master`), the git diff failed. This PR will instead use the [default GITHUB_REF](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) of a pull_request event, and also checks out the base ref branch to allow the comparison.

ci: fix changelog check checkout

---

website/content/docs/nia/installation/requirements.mdx

The linked repository currently has restricted viewing permissions and will be changed as we approach release.

docs/nia: Add link to template repository for building CTS module

---

.github/workflows/pr-file-checker.yml

This fixes the trigger conditional using the wrong key (`label`->`labels`) and also sets the checks  to only run when PRs are opened. The case this doesn't cover is if you forget to add docs to your PR but then add docs in the `website/` directory afterward opening the PR, the check won't rerun to remind you to check if `type/docs-cherrypick` needs to be added. I think this is a good enough compromise for now and we can refactor in the future depending on how helpful this is.

ci: fix pr file checker

---

.circleci/config.yml

This PR triggers a nightly load test job on the `master` branch. It will spin up the load test cluster using the dev build from the latest commit. 
I had to modify the `load-test` job slightly to use a local variable that is set to `pipeline.parameters.commit` if set (when we apply the `pr/load-test` label and trigger the job through the API against a PR commit) and `git rev-parse HEAD` if not (in nightly tests).

ci: add nightly load testing on master

---

website/content/docs/k8s/operations/certificate-rotation.mdx

Broken link to k8s server upgrade from tls certs page

docs: Small change to fix broken link to k8s upgrade from k8s tls certs page

---

tlsutil/generate.go
tlsutil/generate_test.go

Attempt to add RSA support in the TLS utils for parsing certs used in generating certs from your own CA/RSA private key.  Per https://github.com/hashicorp/consul/issues/7622
Not sure if this is all it would take.

Add support for RSA private key to TLS utils.

---

agent/consul/config_endpoint_test.go
agent/consul/fsm/commands_oss.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/catalog_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go

In every case we would pass in the value from the proceeding arg. The extra arg is an opportunity for introducing a bug, so I think we should remove it to avoid that bug.

state: Remove extra entMeta arg to EnsureConfigEntry

---

.github/workflows/pr-file-checker.yml

Without escaping backticks, the GitHub comment doesn't POST properly.

ci: escape backticks in github comment for website/ change check

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_intention.go
agent/consul/state/config_entry_oss.go
agent/consul/state/config_entry_schema.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go

Branched from #9664
Move the indexes so they are shared with enterprise and use constants for table and index names.

state: move config-entries table definition to config_entries_schema.go

---

agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_schema.go
agent/consul/state/config_entry.go
agent/consul/state/connect_ca.go
agent/consul/state/connect_ca_test.go
agent/consul/state/federation_state.go
agent/consul/state/intention.go
agent/consul/state/intention_oss.go
agent/consul/state/intention_test.go
agent/consul/state/system_metadata.go
agent/consul/state/usage.go

Branched from #9665
Best viewed by commit.
Renames table name constants to the new prefix pattern.

state: convert all table name constants to the new prefix pattern

---

agent/consul/state/acl.go
agent/consul/state/autopilot.go
agent/consul/state/catalog_schema.go
agent/consul/state/config_entry.go
agent/consul/state/connect_ca.go
agent/consul/state/coordinate.go
agent/consul/state/federation_state.go
agent/consul/state/intention.go
agent/consul/state/kvs.go
agent/consul/state/prepared_query.go
agent/consul/state/schema.go
agent/consul/state/schema_test.go
agent/consul/state/session.go
agent/consul/state/state_store.go
agent/consul/state/system_metadata.go
agent/consul/state/usage.go

Branched from #9718
`registerSchema` creates some indirection which is not necessary in this case. `newDBSchema` can call each of the functions to create the table schemas. Enterprise tables can be added from the existing `withEnterpriseSchema` shim.
This change should make it easier to trace the creation of the db schema, and also removes an unnecessary use of `init()`.

state: remove registerSchema

---

.changelog/9650.txt
agent/xds/listeners.go
agent/xds/listeners_test.go

In a situation where the mesh gateway is configured to bind to multiple
network interfaces, we use a feature called 'tagged addresses'.
Sometimes an address is duplicated across multiple tags such as 'lan'
and 'lan_ipv4'.
There is code to deduplicate these things when creating envoy listeners,
but that code doesn't ensure that the same tag wins every time. If the
winning tag flaps between xDS discovery requests it will cause the
listener to be drained and replaced.

xds: deduplicate mesh gateway listeners in a stable way

---

tlsutil/generate_test.go

An old PR (#7623) was merged after #9585. The old code was incompatible with the new
changes, but none of the lines caused a git conflict so the merge was allowed.
The incompatible changes caused the tests to fail. This fixes the old code to
work with the new changes.

Fix main build failing

---

.changelog/9651.txt
agent/proxycfg/snapshot.go
agent/xds/listeners.go
agent/xds/listeners_test.go

Also fix a similar issue in Terminating Gateways that was masked by an
overzealous test.
(chained on #9650)
I suspect the 1.7.x backport will need to be manual.

xds: prevent LDS flaps in mesh gateways due to unstable datacenter lists

---

.changelog/9428.txt
GNUmakefile
agent/agent_endpoint_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go
agent/proxycfg/state.go

This fixes an issue where leaf certificates issued in primary
datacenters using Vault as a Connect CA would be reissued very
frequently (every ~20 seconds) because the logic meant to detect root
rotation was errantly triggering.
The hash of the rootCA was being compared against a hash of the
intermediateCA and always failing. This doesn't apply to the Consul
built-in CA provider because there is no intermediate in use in the
primary DC.
This is reminiscent of #6513.

connect: connect CA Roots in the primary datacenter should use a SigningKeyID derived from their local intermediate

---

.changelog/9689.txt
agent/proxycfg/state.go
agent/xds/server.go
logging/names.go

Deadlock scenario:
1. Due to scheduling, the state runner sends one snapshot into
snapCh and then attempts to send a second. The first send succeeds
because the channel is buffered, but the second blocks.
2. Separately, Manager.Watch is called by the xDS server after
getting a discovery request from Envoy. This function acquires the
manager lock and then blocks on receiving the CurrentSnapshot from
the state runner.
3. Separately, there is a Manager goroutine that reads the snapshots
from the channel in step 1. These reads are done to notify proxy
watchers, but they require holding the manager lock. This goroutine
goes to acquire that lock, but can't because it is held by step 2.
Now, the goroutine from step 3 is waiting on the one from step 2 to
release the lock. The goroutine from step …

Avoid potential proxycfg/xDS deadlock using non-blocking send

---

.changelog/9738.txt
agent/cache/cache.go
agent/cache/cache_test.go

This is a partial fix to #9588 but is limited in scope. When the cache encounters an ACL not found error it will stop any background refresh which may be happening for that request. The assumption here is that the token was deleted and is not coming back.
There is however one case where a token may have yet to be replicated in a secondary DC that will prevent the background refresh of the request from happening when it may succeed. This might make the next request take a little longer but is preferable to spamming the logs for days with ACL not found errors.
Also of note is that cache watches for the request will cause the request to continually be made anyways and keep it in an always fetching state (or in exponential retry backoff sleeps).

Stop background refresh of cached data for requests that result in ACL not found errors

---

.changelog/9738.txt
agent/cache/cache.go
agent/cache/cache_test.go
agent/xds/server.go

The first commit is the backport of #9738 which required resolving some conflicts with changes to how the cache is structured. In 1.9.x the expiry heap implementation was moved out of the cache package and into lib/expiry.
The second commit is completely unrelated but fixes up what appears to be a botched auto-merge that resulted in duplicate imports of the logging package in agent/xds/server.go. Regardless I wanted to make the linter happy so its fixed too.

Backport to release/1.8.x: #9738 - Stop background refresh of cached data for requests that result in ACL not found errors

---

.changelog/9650.txt
agent/xds/listeners.go

1.7.x backport of #9650
In a situation where the mesh gateway is configured to bind to multiple
network interfaces, we use a feature called 'tagged addresses'.
Sometimes an address is duplicated across multiple tags such as 'lan'
and 'lan_ipv4'.
There is code to deduplicate these things when creating envoy listeners,
but that code doesn't ensure that the same tag wins every time. If the
winning tag flaps between xDS discovery requests it will cause the
listener to be drained and replaced.

[1.7.x] xds: deduplicate mesh gateway listeners in a stable way

---

.changelog/9428.txt
GNUmakefile
agent/agent_endpoint_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go

[1.9.x] connect: connect CA Roots in the primary datacenter should use a SigningKeyID derived from their local intermediate

---

.changelog/9428.txt
GNUmakefile
agent/agent_endpoint_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go

[1.8.x] connect: connect CA Roots in the primary datacenter should use a SigningKeyID derived from their local intermediate

---

agent/cache-types/streaming_health_services.go
agent/health_endpoint.go
agent/submatview/materializer.go

Details in the commit messages

streaming: fix a couple bugs

---

.changelog/9428.txt
GNUmakefile
agent/agent_endpoint_test.go
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go
agent/consul/leader_connect.go
agent/consul/leader_connect_test.go

[1.7.x] connect: connect CA Roots in the primary datacenter should use a SigningKeyID derived from their local intermediate

---

.changelog/9715.txt
ui/packages/consul-ui/app/components/form-group/element/index.js
ui/packages/consul-ui/app/components/freetext-filter/index.hbs
ui/packages/consul-ui/app/components/freetext-filter/layout.scss
ui/packages/consul-ui/app/utils/intl/missing-message.js

`String.replaceAll` is only available in newer browsers (for example after Chrome 85), so here we revert to using `split(find).join(replace)` instead of `replaceAll`.
A related CSS problem here was support for defining flex-box on fieldsets in older browsers. As this PR is a bugfix for 'older browsers' we added the fix for that here too.
Previous:
Fixes https://github.com/hashicorp/consul/issues/9714
Thanks @r3knit !

ui: [BUGFIX] Replace all replaceAll with split.join for older browsers without replaceAll

---

.changelog/9729.txt
ui/packages/consul-ui/config/targets.js
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/package.json
ui/yarn.lock

Consul UI pre 1.9 used a mainly ES5 style of javascript, this meant that the majority of the code did not need any ES6 to ES5 babel transpilation or shim code, and our javascript payload was roughly:
Consul UI: 116KB gzipped
Dependencies: 374KB gzipped
As of 1.9 we started moving towards using Ember's new Octane edition, which felt much more ES6-y. So as well as beginning to update all of our components to use glimmer components, we also updated the style of how we write the UI to use ES6 javascript rather than ES5. This meant that (with our existing browser targets file), much of this was being transpiled using babel into ES5 javascript, giving a rough javascript payload of:
Consul UI: 229KB gzipped
Dependencies: 460KB gzipped
That's roughly **200KB gzipped** of payload difference …

ui: Update browser targets

---

.changelog/9749.txt
ui/packages/consul-ui/app/components/consul/instance-checks/index.hbs
ui/packages/consul-ui/app/components/consul/node/list/index.hbs
ui/packages/consul-ui/app/models/node.js
ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs

In our node listing page we show the a number for the amount of Service Instances on each node.
Before this PR, this count included any proxies on the Node, essentially doubling the service count. This was probably correct in a previous version of the UI when we used to show all the proxies across the catalog as well as the services, but since we merged proxies into the services themselves, essentially making the an implementation detail and therefore invisible in the UI, this count should not include proxies.
This PR adds a `MeshServiceInstances` property to the node model, 'mesh' here meaning 'services that have a proxy assigned to them, and therefore not a proxy itself'. We then use this property to show the instance count, meaning we omit proxy instances from the final count.
We also …

ui: [BUGFIX] Ensure we show the correct count of instances for each node

---

website/content/commands/tls/ca.mdx
website/content/docs/connect/ca/index.mdx

Adding additional docs to highlights ways to regenerate CA certs upon expiration
Fixes #9653

Add docs section on regenerating expired CA certificates

---

agent/health_endpoint.go
website/content/api-docs/health.mdx

Follow up to https://github.com/hashicorp/consul/pull/9745#pullrequestreview-587002996
Error instead of silently falling back to blocking queries, also document the limitation.

http: error if near is used with streaming

---

agent/consul/state/acl.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/kvs_oss.go
agent/consul/state/schema.go
agent/consul/state/state_store.go

Also use a `tableIndex` constant for the table name to make it easier to find all the places it is used.

state: document how index table is used

---

.changelog/9772.txt
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go

Previously a snapshot created as part of a resume-stream request could have incorrectly cached the `newSnapshotToFollow` event. When the next subscribe request was received with `Index=0` the returned snapshot would cause clients to error because they received an unexpected framing event.
Fixed the bug by saving a snapshot without the framing event, then creating a new snapshot to prepend the framing event.

streaming: fix snapshot cache bug

---

agent/cache-types/streaming_health_services_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/state/config_entry.go
agent/rpc/subscribe/subscribe.go
agent/structs/structs_oss.go
agent/txn_endpoint.go

structs: rename EnterpriseMeta constructor

---

agent/config/builder.go
agent/config/builder_test.go
agent/config/runtime_test.go
agent/config/segment_oss_test.go
contributing/checklist-adding-config-fields.md

Branched from #9448
Lots of context in the commits messages.
The main changes here are:
1. reduce the number of fields in the `testCase` struct, and rename others so their purpose is more obvious from the name
2. reduce the test logic to separate iteration from the actual test logic
3. replace the slice with individual calls to `run()` so that when a case fails, the failure output includes a line for both the test function and the testCase. Without this change only the line number of the test function is printed, which makes it extremely difficult to find the relevant testCase data, because there are thousands of lines with very similar names.
An alternative to 3 would be to split this one case into a few hundred test cases. That would likely be significantly more work for roughly the …

config: make TestBuilder_BuildAndValidate_ConfigFlagsAndEdgecases easier to work with

---

website/content/api-docs/agent/index.mdx

This was added in 1.7.2 last year but I realised we don't document it so it's kinda surprising Prometheus "just works" now.

Add docs for MIME sniffing on metrics endpoint.

---

.changelog/9741.txt
agent/acl_endpoint_test.go
agent/structs/acl.go
api/acl.go
api/acl_test.go

Add fields to the /acl/auth-methods endpoint.
A GET of the /acl/auth-methods/:name endpoint returns the fieldsMaxTokenTTL and TokenLocality, while a LIST (/acl/auth-methods) does
not.
The list command returns a filtered subset of the full set. This is
somewhat deliberate, so that secrets aren't shown, but the TTL and
Locality fields aren't (IMO) security critical, and it is useful for
the front end to be able to show them.
For consistency these changes mirror the 'omit empty' and string
representation choices made for the GET call.
This includes changes to the gRPC and API code in the client.
The new output looks similar to this
curl 'http://localhost:8500/v1/acl/auth-methods' | jq '.'
{
"MaxTokenTTL": "8m20s",
"Name": "minikube-ttl-local2",
"Type": "kubernetes",
"Description": "minikube …

Add fields to the /acl/auth-methods endpoint.

---

ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/index.js
ui/packages/consul-ui/app/components/topology-metrics/layout.scss
ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs

🐛 The icons in the Topology View were not positioning themselves in the right place with the sidebar close/open action.
🔧 Use ember-on-resize-modifier to recalculate the positioning of the icons.

ui: Use ember-on-resize-modifier to fix bug with sidebar

---

website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/crds/upgrade-to-crds.mdx
website/content/docs/k8s/helm.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx
website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

* Document how users can migrate to CRDs.
* Update documentation for federation with new `ProxyDefaults`
requirement.
* Ensure `controller.enabled: true` is set in our example configs.
* Remove `connect-service-protocol` annotation docs.
⚠️ must be merged **after** consul-helm release ⚠️

Docs describing migrating to CRDs

---

test/integration/connect/envoy/Dockerfile-bats
test/integration/connect/envoy/Dockerfile-consul-envoy

This removes all references to `hashicorp.jfrog.io` which has been replaced with a self-hosted registry, `docker.mirror.hashicorp.services`

Remove jfrog references

---

test/integration/connect/envoy/Dockerfile-bats

Followup to #9782, there was an old lingering `/docker` namespace that we don't need anymore.

remove reference to docker/ path for old docker mirror

---

ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology.feature
ui/packages/consul-ui/tests/steps/assertions/dom.js
ui/packages/consul-ui/tests/steps/doubles/model.js

This PR adds some initial acceptance testing around the topology series graph, just to verify that it appears/doesn't appear depending on your `ui_config` settings.

ui: Add some acceptance testing around the Metrics graph

---

ui/packages/consul-ui/app/decorators/data-source.js
ui/packages/consul-ui/app/instance-initializers/container.js
ui/packages/consul-ui/app/services/container.js
ui/packages/consul-ui/app/services/data-source/protocols/http.js
ui/packages/consul-ui/app/services/repository.js
ui/packages/consul-ui/app/services/repository/node.js
ui/packages/consul-ui/app/services/repository/nspace.js
ui/packages/consul-ui/app/services/repository/policy.js
ui/packages/consul-ui/app/services/repository/role.js
ui/packages/consul-ui/app/services/repository/service.js

In https://github.com/hashicorp/consul/pull/9746 we added a new `@dataSource` decorator in order to annotate our `EventSource` functions with a URL for access using our `<DataSource />` component, the data then automatically updates live from the backend using our blocking query support:
```javascript
@dataSource('/:ns/:dc/services')
async findAllByDatacenter({ns, dc}) {
return fetch(`/somewhere?ns=${ns}&dc=${dc}`)
}
```
```hbs
<DataSource @src="/default/dc1/services" @onchange="" />
```
A few potential improvements we thought we could make with that PR revolved around:
1. Ensuring decorators of 'ember resolved' (and therefore auto imported) classes are executed at app boot up.
2. Being able to lookup instances of a class using a DI container. Ember's default container supports string …

ui: Adds a service for Class based service lookup for dataSource decorator

---

website/content/api-docs/health.mdx

These filters can not be reproduced with bexpr just yet.
Meta is not available from node list, so that can't be used to filter.
`passing` requires all checks are passing, where `Checks.Status` requires only a single check to be passing.
We might be able to extend bexpr to make this work, but removing the deprecation until that is possible seems appropriate.

docs: remove a couple deprecations

---

.changelog/9765.txt
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/net_fallback.go
agent/xds/net_linux.go
agent/xds/testdata/listeners/expose-checks.envoy-1-13-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-14-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-15-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-16-x.golden
test/integration/connect/envoy/case-expose-checks/capture.sh
test/integration/connect/envoy/case-expose-checks/service_s1.hcl
test/integration/connect/envoy/case-expose-checks/service_s2.hcl
test/integration/connect/envoy/case-expose-checks/setup.sh
test/integration/connect/envoy/case-expose-checks/verify.bats
test/integration/connect/envoy/helpers.bash

Fixes #9311 
This only fails if the kernel has ipv6 hard-disabled. It is not sufficient to merely not provide an ipv6 address for a network interface. For local testing I [disabled it in grub](https://itsfoss.com/disable-ipv6-ubuntu-linux/) on an ubuntu linux VM first.
Then register a service with connect locally with a config file like:
```
...
connect {
sidecar_service {
proxy {
expose {
checks = true
}
}
}
}
...
```
Then try launching the sidecar and grep the envoy logs for the word `expose`
TODO

xds: only try to create an ipv6 expose checks listener if ipv6 is supported by the kernel

---

agent/cache/cache.go
agent/cache/watch.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/setup.go

Without these warnings, errors are silently ignored, which can make debugging problems more challenging.

cache: log a warning when Cache.Notify handles an error

---

.changelog/9683.txt
agent/local/state.go

Hopefully improves the issue from #9577 (#7669, #8078).
If an ACL token used to register a service is removed before the service then anti-entropy sync can fail to deregister the service. In those cases the local agent logs are filled with noise from these failures, and it never resolves itself.
Previously it would attempt to fall back to the "default" token, then to the anonymous token. With this change it will first fall back to the "agent" token, then "default", then finally the anonymous.
ref: https://www.consul.io/docs/agent/options#acl_tokens
The agent token seems more appropriate in this case, since this is an "internal operation", not something initiated by the user.

local: use agent token to deregister services

---

ui/packages/consul-ui/testem.js

Here we look for a TESTEM_AUTOLAUNCH environment variable, which can be
set to either Chrome, Firefox or Safari, which will control which
browser to automatically start when running testem tests.
If the variable is set to anything else, then it will not automatically
start a browser in order to run the tests and you will need to visit the
tests manually. e.g.:
TESTEM_AUTOLAUNCH=0 make test-oss-view
Previously we only ever tested in Chrome and therefore there are no
specific settings for Firefox or Safari. If specific settings are
required for these browsers they can be added at a later date.

ui: Add an optional environment variable to control how testem tests start

---

ui/packages/consul-ui/app/adapters/permission.js
ui/packages/consul-ui/app/routes/dc.js
ui/packages/consul-ui/app/routes/dc/acls/auth-methods/index.js
ui/packages/consul-ui/app/services/repository.js
ui/packages/consul-ui/app/services/repository/auth-method.js
ui/packages/consul-ui/app/services/repository/intention.js
ui/packages/consul-ui/app/services/repository/kv.js
ui/packages/consul-ui/app/services/repository/permission.js
ui/packages/consul-ui/app/services/repository/service-instance.js
ui/packages/consul-ui/tests/integration/services/repository/auth-method-test.js

In a parallel timescale to https://github.com/hashicorp/consul/pull/9746 we added auth-methods and a new set of methods for authorization within repositories. Now that work is merged we've added the changes required to bring that work up to date with https://github.com/hashicorp/consul/pull/9746 here in a separate PR for keeping things easy to see those specific changes.
Few notes:
1. This mainly moves everything from using multiple arguments to using a params object. Previously we'd preferred multiple arguments to avoid having to remember the names of params/object properties when using the repository methods. Now we have our `@dataSource` decorator, the names of the properties of the `params` object are defined right alongside where they are used, and DataSource usage now uses URIs to …

ui: Update authorization things to use new DataSource decorator/params interface

---

.changelog/9765.txt
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/net_fallback.go
agent/xds/net_linux.go
agent/xds/testdata/listeners/expose-checks.envoy-1-11-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-12-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-13-x.golden
agent/xds/testdata/listeners/expose-checks.envoy-1-14-x.golden
test/integration/connect/envoy/case-expose-checks/capture.sh
test/integration/connect/envoy/case-expose-checks/service_s1.hcl
test/integration/connect/envoy/case-expose-checks/service_s2.hcl
test/integration/connect/envoy/case-expose-checks/setup.sh
test/integration/connect/envoy/case-expose-checks/verify.bats
test/integration/connect/envoy/helpers.bash

1.8.x backport of #9765
Conflicts:
- `agent/xds/listeners_test.go`
- `test/integration/connect/envoy/helpers.bash`
- `agent/xds/testdata` (different envoy versions)

[1.8.x] xds: only try to create an ipv6 expose checks listener if ipv6 is supported by the kernel

---

website/content/api-docs/acl/binding-rules.mdx

Fix indentation of code blocks on ACL binding rules page so that code fence does not display in JSON output.

docs: Fix code tag displaying on ACL binding rules

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx

- Add 'enabled' field to task configuration section
- Update tasks page with language about enabled vs. disabled tasks
Preview:
- [Config change](https://consul-52kkx2nsy-hashicorp.vercel.app/docs/nia/configuration#task)
- [Tasks page](https://consul-52kkx2nsy-hashicorp.vercel.app/docs/nia/tasks)

docs/nia: add task 'enabled' configuration

---

website/content/docs/nia/configuration.mdx

Kept it simple and purposely left off 'enabled' to highlight option that it is auto-enabled if any other value is set.

example and default syslog CTS settings

---

website/content/docs/security/security-models/nia.mdx

This PR introduces some minor updates to the NIA security model for the beta.
- Change from Tech Preview to Beta in the sidebar
- Update the overview section to better reflect the other NIA docs.
- Changes to the "NIA Daemon" wording to also refer to `consul-terraform-sync`, using them interchangeably where I thought it made sense.

Update NIA Security Model for Beta

---

website/content/docs/nia/cli/cli-overview.mdx
website/content/docs/nia/cli/task.mdx
website/content/docs/nia/tasks.mdx
website/data/docs-navigation.js

Commits:
- Convert exiting CLI page into an 'overview' page and reorganize so that we can have a CLI directory with a page for different subcommands
- Reorganize 'overview' page into 'main process' vs. 'subcommand' sections. Feedback welcome on 'main process' naming.
- Add a 'task' subcommand page with details on enable and disable subcommand
Preview
- [Update cli page => overview](https://consul-pszpn6z7r-hashicorp.vercel.app/docs/nia/cli/cli-overview)
- [New task subcommand page](https://consul-pszpn6z7r-hashicorp.vercel.app/docs/nia/cli/task)

docs/nia: enable and disable subcommand

---

.changelog/9752.txt
agent/structs/config_entry_gateways.go
agent/structs/config_entry_gateways_test.go
agent/ui_endpoint_test.go

Previous to this commit, the API response for getting information about the upstreams for a gateway (`/v1/internal/ui/gateway-services-nodes/:gateway`) would include Gateway Addresses in the form `domain.name.:8080`, which due to the addition of the port is probably not the expected format (the trailing `.` is DNS not Address:Port URLs).
This commit rightTrims any `.` characters from the end of the domain before formatting the address to include the port resulting in `domain.name:8080`
One thing I'm unsure of, whilst this 'fixes' things for displaying this in the UI, does this effect anything else backend related? I had a quick search to see is the `.Addresses()` method was being used elsewhere, and I couldn't see anything, but would be good to double check.

ui: Remove any trailing fullstop/period DNS characters from Gateways UI API

---

website/content/docs/nia/api/api-overview.mdx
website/content/docs/nia/api/status.mdx

Below are some updates to the apis that resulted out of work on the disable/enable cli
Commits: (more details in message)
- Returning an error object instead of error string across all apis ([here](https://consul-emmjc97nd-hashicorp.vercel.app/docs/nia/api/api-overview#error))
- Support new "unknown" status value and new "enabled" field in the status api
docs and examples ([here](https://consul-emmjc97nd-hashicorp.vercel.app/docs/nia/api/status#status))

docs/nia: api updates

---

.changelog/9703.txt
agent/cache-types/streaming_health_services.go
agent/cache-types/streaming_health_services_test.go
agent/consul/state/catalog_events.go
agent/dns.go
agent/dns_test.go
agent/health_endpoint_test.go
agent/rpcclient/health/health.go
agent/structs/structs.go

Fixes #9695
Fixes #9702
This is also testing the 2 cases at once since I modified the DNS test:
* Will test both case insensitive and tags lookups

Streaming filter tags + case insensitive lookups for Service Names

---

agent/config/builder.go
agent/config/runtime_test.go
website/content/docs/agent/options.mdx

So that all servers will start the grpc server used by streaming.
Not backporting this, it should only be included in the next release.

streaming: default rpc.enable_streaming to true

---

.github/workflows/changelog-checker.yml
.github/workflows/pr-file-checker.yml
.github/workflows/website-checker.yml

This PR splits out the `website/` check to only run on PR `opened` while the changelog check runs on `opened`, `synchronize` (new commits) and `labeled` and also changes it to a status check that fails when there is no `pr/no-changelog` label applied nor is there a `.changelog/$pr_number.txt` file. 
I also changed the `on` trigger to be `pull_request` for the changelog check because it no longer needs a token secret to post to the PR so it doesn't need to only run on `pull_request_target`

update changelog and website checks

---

agent/health_endpoint_test.go
agent/testagent.go

I think the backport cherry-pick introduced this duplicate import. 
Fixes #9839

[1.9.x ]Fix merge conflict

---

website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

The Consul Federation requires the Server nodes to have an additional SAN entry of the form `<node_name>.server.<dc>.<domain>`. This was missing from the instructions for K8S to VM federation.
* Updated the instructions and CLI example
* Fixed numbering

Fix TLS cert creation instruction for Consul federation

---

.changelog/9768.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go
command/connect/envoy/bootstrap_tpl.go
command/connect/envoy/envoy.go
command/connect/envoy/envoy_test.go
command/connect/envoy/testdata/prometheus-metrics.golden
website/content/commands/connect/envoy.mdx

**Changes Proposed:**
Allows setting -prometheus-backend-port to configure the cluster
envoy_prometheus_bind_addr points to.
Allows setting -prometheus-scrape-path to configure which path
envoy_prometheus_bind_addr exposes metrics on.
-prometheus-backend-port is used by the consul-k8s metrics merging feature, to
configure envoy_prometheus_bind_addr to point to the merged metrics
endpoint that combines Envoy and service metrics so that one set of
annotations on a Pod can scrape metrics from the service and it's Envoy
sidecar.
-prometheus-scrape-path is used to allow configurability of the path
where prometheus metrics are exposed on envoy_prometheus_bind_addr. This value is also configurable via consul-k8s/consul-helm so for that it needs to be configurable here.

Add flags to consul connect envoy for metrics merging.

---

agent/cache-types/streaming_health_services.go
agent/cache-types/streaming_health_services_test.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/rpc/subscribe/subscribe.go
agent/structs/structs_oss.go

I added this recently without realizing that the method already existed and was named NamespaceOrEmpty. Replace all calls to GetNamespace with NamespaceOrEmpty or NamespaceOrDefault as appropriate.

structs: remove EnterpriseMeta.GetNamespace

---

website/content/docs/k8s/helm.mdx

These were autogenerated by `make gen-docs` on `consul-helm`

Docs for helm values introduced by metrics

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/coordinate.go
agent/consul/state/schema_test.go
agent/consul/state/session.go
agent/consul/state/state_store_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

state: convert nodes.ID to the new pattern of functional indexers

---

website/content/docs/agent/telemetry.mdx

This commits adds units and types to key metrics tables to have
consistent table views of all metrics in telemetry.mdx.
Fixes: https://github.com/hashicorp/consul/issues/9069

Add units and types to metrics tables

---

.changelog/9792.txt
command/kv/imp/kv_import.go
command/kv/imp/kv_import_test.go
website/content/commands/kv/import.mdx

Currently when data is imported via `consul kv import` it overwrites
keys under the root key. Since `consul kv export` can retrieve data for
the given prefix, i.e. part of the KV tree, importing it under root may
be not what users want.
To mirror prefix behavior from export this PR adds prefix feature to the
import command that adds prefix to all keys that are imported.

command/kv: Add prefix option to kv import command

---

website/content/docs/connect/config-entries/terminating-gateway.mdx

fix crds support reference and adding ACL clarification for linked services.

Docs: Update terminating-gateway-config-entry

---

.changelog/9672.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go
api/connect_ca.go
command/connect/ca/set/connect_ca_set.go
website/content/api-docs/connect/ca.mdx
website/content/commands/connect/ca.mdx

This allows setting ForceWithoutCrossSigning when reconfiguring the CA for any provider, in order to forcibly move to a new root in cases where the old provider isn't reachable or able to cross-sign for whatever reason. 
Previously this was ignored for the Consul/Vault providers, so it was possible to get stuck with an unusable CA.

connect/ca: Allow ForceWithoutCrossSigning for all providers

---

website/components/basic-hero/style.css
website/components/case-study-carousel/style.css
website/components/cloud-offerings-list/style.css
website/components/enterprise-comparison/style.css
website/components/footer/style.css
website/components/hcp-callout-section/HCPCalloutSection.module.css
website/components/learn-callout/style.css
website/components/mini-cta/style.css
website/package-lock.json
website/package.json

Removes references to deprecated gray CSS properties and maps all gray colors to new brand values.
[_Created by Sourcegraph campaign `kstraut/product-sites-migrate-v3-gray-colors`._](https://sourcegraph.hashi-mktg.com/users/kstraut/campaigns/product-sites-migrate-v3-gray-colors)
Due to old imports of `react-global-styles` within `react-components`, the proper gray values will not show until we update `react-components` later on because the old style sheets are taking precedent.
```
// v2 gray css properties to new v3 values
"--gray-3" --> "--gray-2" 
"--gray-4" --> "--gray-3" 
"--gray-5" --> "--gray-4" 
"--gray-6" --> "--gray-5" 
"--gray-7" --> "--gray-6" 
// Replace Deprecated Gray Value references
"DEPRECATED-gray-:[~1|2]" --> "gray-1" 
"DEPRECATED-gray-:[~3|4]" --> "gray-2" …
```

website(style): Update gray brand colors
