hashicorp/consul

.changelog/8599.txt
api/go.sum
api/mock_api_test.go
api/operator_autopilot.go
api/operator_autopilot_test.go

Previously we would error out and not parse the response. Now either a 200 or 429 status code are considered expected statuses and will result in the method returning the reply allowing API consumers to not only see if the system is healthy or not but which server is unhealthy.
This also introduces a mock http server that can be used to inject specific responses for testing out how the API client methods would handle that reply. While its not a replacement for integration tests, some tests like the one I needed to write here would be harder to reproduce if actually running consul servers.

AutopilotServerHealth now handles the 429 status code

---

agent/agent.go
agent/consul/state/catalog_events.go
agent/consul/state/memdb.go
agent/proxycfg/manager.go
agent/proxycfg/manager_test.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/rpcclient/health/health.go

Should be merged after #9671
Enables the connect streaming topic.
Enables the use of the streaming cache in connect.
Also fixes a bug in the snapshot for the connect topic.

use streaming backend for connect service health

---

website/content/api-docs/query.mdx

Add missing section on creating prepared query for namespaced services

Add namespaces to prepared query API docs

---

website/content/docs/connect/config-entries/service-resolver.mdx

SourceAddress was probably renamed to SourceIP but the docs weren't
updated.

docs: rename SourceAddress to SourceIP

---

lib/eof.go
lib/eof_test.go

IsErrEOF returns false when it should return true in a couple of cases:
1. if the error has been wrapped in another error (for example, if EOF
is wrapped in an RPC error)
2. if the error has been created from an Error field in an RPC response
(as it is the case in CallWithCodec in the net-rpc-msgpackrpc package
for example)

Use errors.Is() in IsErrEOF()

---

sdk/testutil/assertions.go
sdk/testutil/io.go
sdk/testutil/server.go
sdk/testutil/server_methods.go
sdk/testutil/server_wrapper.go

Using the interface opens up the use of all methods to benchmarks as well as tests.
Should be complete a drop in replacement.
Tested changes manually against both consul-terraform-sync's and consul-template's use of the sdk/testutil's TestServer to validate real-world use cases.

[SDK] change all cases of *testing.T to testing.TB

---

.changelog/9864.txt
ui/packages/consul-ui/app/abilities/acl.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
ui/packages/consul-ui/app/components/main-nav-vertical/index.scss
ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
ui/packages/consul-ui/app/modifiers/disabled.js
ui/packages/consul-ui/app/styles/base/icons/base-placeholders.scss

Shows a warning icon next to the Access Controls title of the side nav when ACLs are disabled to give an always on reminder that they are not enabled. We also show related unlinked navigation items which are visible but not clickable (Roles, Policies, Auth Methods). Tokens is still linked to give an area for us to provide further info.
When ACLs are enabled there is no change to how it was previously.
Worthwhile noting that we added a `(can "use acls")` which should be used within templates moving forwards rather then `(env "CONSUL_ACLS_ENABLED")` - we should try to gradually phase out using the `env` helper from within templates, instead favouring `can` for permission/abilities and `t` for text/copy/URLs.
Both `can` and `t` helpers are used widely in other product UIs whereas `env` is …

ui: Adds warning icon to side menu when ACLs are disabled

---

agent/consul/leader_intentions_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry.go

Previously this type was defined in structs, but unlike the other types in structs this type
is not used by RPC requests. By moving it to state we can better indicate that this is not
an API type, but part of the state implementation.

state: move ConfigEntryKindName

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/schema_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden
agent/structs/identity.go
agent/structs/structs.go

Using NodeIdentity to share the indexes with both.

state: convert services.node and checks.node indexes

---

agent/consul/state/config_entry.go
agent/consul/state/config_entry_intention.go
agent/consul/state/config_entry_oss.go
agent/consul/state/config_entry_oss_test.go
agent/consul/state/config_entry_schema.go
agent/consul/state/indexer.go
agent/consul/state/intention.go
agent/consul/state/schema_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

Branched from #9863
This PR converts the id and kind indexes to the new pattern.

state: convert config-entries table to the new pattern of functional indexers

---

agent/consul/state/intention.go
agent/structs/structs_oss.go
agent/structs/structs_oss_test.go

This is needed for an oss/ent split, where the enterprise side checks for wildcard name AND namespace.

Add methods to check intention has wildcard src or dst

---

agent/consul/config_endpoint_test.go
agent/proxycfg/state_test.go
agent/service_manager_test.go
agent/structs/config_entry_test.go

Some enterprise test fixes were needed from the tproxy changes. These are the OSS side of those.

Fixup enterprise tests from tproxy changes

---

ui/packages/consul-ui/app/modifiers/tooltip.js
ui/packages/consul-ui/app/modifiers/tooltip.mdx

This amends our tooltip modifier to automatically add a `tabindex="0"` to
all of our tooltips (if they don't have a tabindex already).
This means that all tooltips will automatically be
added to the natural tab order of the page. I'm pretty sure we don't
currently require the ability to disable this automatic functionality
but if we do at some point in the future we can add an option to disable
it, meaning all tooltips will be tabbable by default.

ui: Add all tooltips to the default tabbing order in the page

---

ui/packages/consul-ui/app/components/certificate/index.hbs
ui/packages/consul-ui/app/components/certificate/index.scss
ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
ui/packages/consul-ui/app/styles/components/empty-state/layout.scss
ui/packages/consul-ui/app/styles/components/empty-state/skin.scss
ui/packages/consul-ui/mock-api/v1/acl/auth-method/_

- Update Certificate to be monospaced
- Add empty states for claim and list claim mappings
- Update the styling of empty state actions block
[Demo Link](https://consul-ui-staging-ndzws32au-hashicorp.vercel.app/ui/dc1/acls/auth-methods/capacitor-0/auth-method#CONSUL_ACLS_ENABLE=1)

ui: Updates to auth-method show page

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/config_entry.go
agent/consul/state/schema_test.go
agent/structs/structs.go

The mesh-topology and gateway-services tables already use indexers that are pretty close to the new functional index pattern.
This PR doesn't change the indexers, but makes the following changes:
* adds tests for the indexers
* uses the index name constants for all operations
* moves the `UpstreamDownstream` type from `structs` to `state`, and un-exports it. This type is only used to store things, it's not part of any API.
* removes `gatewayServices` and `serviceGateways` functions, and calls the `tx.Get` operations directly. This makes it easier to see what the function is doing from the caller.

state: use constants and add indexer tests for gateway tables

---

website/content/api-docs/agent/connect.mdx

Removing unnecessary comment around CRL to avoid confusion, as discussed with @banks

Removing unnecessary comment

---

.changelog/9901.txt
ui/packages/consul-ui/app/components/consul/intention/form/index.js

By adding `@action` decorators to the actions called form within the
template.
Fixes https://github.com/hashicorp/consul/issues/9764

ui: Ensure intention form cancel button works

---

.changelog/9903.txt
api/agent.go
api/agent_test.go

This PR adds support for setting `QueryOptions` on a few `Agent` API
endpoints. Nomad needs to be able to set the `Namespace` field on
these endpoints to:
- query for services / checks in a namespace
- deregister services / checks in a namespace
- update TTL status on checks in a namespace

api: enable query options on agent endpoints

---

agent/consul/state/acl.go
agent/consul/state/acl_events.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/consul/state/catalog_oss.go
agent/consul/state/query_oss.go
agent/consul/state/schema_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

Also adds tests for indexers and uses index and table name constants.

state: convert acl-policies table to new functional indexer pattern

---

website/content/docs/nia/configuration.mdx

Changes from vault provider examples to the AWS provider. This is to further distinguish between the [optional vault configuration block (used for querying the Vault secrets)](https://www.consul.io/docs/nia/configuration#vault) for CTS with Terraform provider configurations themselves.
Preview link for the sections:
* https://consul-i8xlusrtr-hashicorp.vercel.app/docs/nia/configuration#terraform-provider
* https://consul-i8xlusrtr-hashicorp.vercel.app/docs/nia/configuration#multiple-provider-configurations

docs/nia: Update CTS configuration example for terraform providers

---

agent/consul/server_test.go
agent/pool/peek_test.go
agent/routine-leak-checker/leak_test.go
agent/testagent.go
command/tls/cert/create/tls_cert_create.go
tlsutil/generate.go
tlsutil/generate_test.go

I liked `CAOpts` from https://github.com/hashicorp/consul/pull/9585 so much that I added `CertOpts` as well.

introduce certopts

---

.github/workflows/changelog-checker.yml

The `.` immediately following the PR link was being included in the link, causing it to not go to its expected destination.

fix(changelog-checker): remove period to fix broken link

---

CHANGELOG.md

This was fixed as part of a refactor in 1.9.0 but no changelog entry was added. It affected some users who used automated security scanning tools which detected violations on Consul's error pages because appropriate security-related headers were not being added.
@mikemorris @alvin-huang do you think it makes sense to backport this to the changelog in release/1.9.x too? It seems to to me so I added the label but let me know if there's a good reason not to.

Retroactive Chagelog update for header fix

---

website/content/docs/nia/compatibility.mdx
website/content/docs/nia/installation/requirements.mdx
website/data/docs-navigation.js

Added a 'compatibility' page with a Consul compatibility matrix
Changes:
- [New compatibility page](https://consul-lnpwex284-hashicorp.vercel.app/docs/nia/compatibility)
- Link to compatibility page from the ['getting started: install consul' page](https://consul-lnpwex284-hashicorp.vercel.app/docs/nia/installation/requirements#install-consul)

docs/nia: consul compatibilty

---

website/content/docs/nia/architecture.mdx
website/content/docs/nia/configuration.mdx
website/content/docs/nia/index.mdx
website/content/docs/nia/installation/install.mdx
website/content/docs/nia/installation/run.mdx
website/content/docs/security/security-models/nia.mdx

Here the first changes to the documentation to cross link the Learn tutorials.
I am not sure if we want to add links in other pages but, once https://github.com/hashicorp/learn/pull/3096 is merged we might want to change the first link in https://www.consul.io/docs/nia/terraform-modules#how-to-create-a-compatible-terraform-module to the new specific CTS tutorial or add an extra one.
Comments or changes are welcome.

Cross linking Learn tutorials

---

agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go
agent/consul/state/operations_oss.go
agent/consul/state/session_oss.go
agent/consul/state/state_store_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

Also adds tests for the indexer, and removes some functions that are no longer used.

state: convert checks.ID index to the functional indexer pattern

---

agent/consul/state/acl.go
agent/consul/state/acl_events.go
agent/consul/state/acl_oss.go
agent/consul/state/acl_oss_test.go
agent/consul/state/acl_schema.go
agent/consul/state/acl_test.go
agent/consul/state/catalog.go
agent/consul/state/indexer.go
agent/consul/state/query.go
agent/consul/state/query_oss.go
agent/consul/state/schema_test.go
agent/consul/state/testdata/TestStateStoreSchema.golden

Just like all the others.
This also changes the `acl-roles.polcies` index to use an encoded UUID, where as previously it used a string. This should save a bit of memory for each linked policy.

state: convert ACLRoles policies index to new functional indexer pattern

---

.changelog/9923.txt
agent/http.go
agent/http_oss.go
agent/uiserver/uiserver.go
agent/uiserver/uiserver_test.go

This bug would result in the UI not having the correct settings in Consul enterprise, which could produce many warnings in the logs.
This bug occurred because the index page, which includes a map of configuration was rendered when the HTTPHandler is first created. This PR changes the UIServer to instead render the index page when the page is requested.
The rendering does not appear to be all that expensive, so rendering it when requested should not cause much extra latency.
Also includes a bit of cleanup to remove some unnecessary args, and unnecessary function wrapping.
This bug only exists in 1.9.x, so I think we only need one backport.

http: fix a bug that would cause runtimeConfig to be cached

---

agent/agent_endpoint_test.go

This removes three unused test helper functions from the `agent` package.
`externalIP()`
`testAgent_RegisterService_TranslateKeys()`
`makeTelemetryDefaults()`

agent: Prune Unused Test Helper Functions

---

website/content/commands/exec.mdx

The Agent token policy when using rexec should have `write` on "_rexec" key prefix. Updated the exec command documentation to explicitly state this requirement.

Document agent token policy requirement for rexec

---

.changelog/9920.txt
connect/proxy/config.go
connect/proxy/proxy_test.go
connect/service.go

@banks This should cover the technical aspects of the PR. I am not to happy with the pointer to the nextProto array, but I am not sure how we could pass the default nicely otherwise…

Allow passing ALPN next protocols down to connect services. Fixes #4466.

---

agent/agent_endpoint_test.go

I merged #7324, and apparently thet test that had been lying dormant and not running needed an update for enterprise.

Set default enterprise meta in test case

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go

Branched from #9948
Same pattern as the rest. The only significant change here is that `checks.status` will now use lowercase out of convenience. Previously all the values were already lowercase so it should be a no-op.

state: convert remaining checks table indexers to functional pattern

---

.changelog/9683.txt
.changelog/9923.txt

So these changelog entries will be parsed successfully.
TODO from chatting with @i0rek - could we catch formatting issues like this in the CI changelog check instead of omitting entries silently when running `changelog-build` at release time?

changelog: fixup release-note formatting

---

.changelog/9967.txt
agent/agent.go
agent/health_endpoint.go
agent/health_endpoint_test.go
agent/rpcclient/health/health.go

The streaming cache type for service health has no way to handle `v1/health/ingress/:service` queries as there is no equivalent topic that would return the appropriate data.
This PR ensures that attempts to use this endpoint will use the old cache-type for now so that they return appropriate data when streaming is enabled.
Manual backport to 1.9.x https://github.com/hashicorp/consul/pull/9968

api: ensure v1/health/ingress/:service endpoint works properly when streaming is enabled

---

.changelog/9967.txt
agent/agent.go
agent/health_endpoint.go
agent/health_endpoint_test.go
agent/rpcclient/health/health.go

[1.9.x] api: ensure v1/health/ingress/:service endpoint works properly when streaming is enabled

---

.changelog/9973.txt
agent/config/runtime_test.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/config_entry.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/structs/config_entry.go
agent/structs/config_entry_cluster.go
agent/structs/config_entry_cluster_oss.go
agent/structs/config_entry_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-17-x.golden
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-17-x.golden
api/config_entry.go
api/config_entry_cluster.go
api/config_entry_test.go
command/config/write/config_write_test.go

This adds a new config entry kind "cluster" with a single special name "cluster" where this can be controlled.
TODO

connect: add toggle to globally disable wildcard outbound network access when transparent proxy is enabled

---

website/package-lock.json
website/package.json

Remove the badges from the HCP products on the HashiStackMenu, as they are no longer needed.
[🔍 Preview](https://consul-git-brstackmenu-hashicorp.vercel.app/)

Upgrades the Stackmenu to latest

---

ui/packages/consul-ui/app/components/consul/auth-method/search-bar/index.hbs
ui/packages/consul-ui/app/models/auth-method.js
ui/packages/consul-ui/app/sort/comparators/auth-method.js
ui/packages/consul-ui/package.json
ui/yarn.lock

🐛 MaxTokenTTL comes in as a string from endpoint. We installed Duration.js package to reformat MaxTokenTTL as an integer and use the integer format to sortBy.
* No changelog since this feature has not been released.

ui:  Reformat MaxTokenTTL to sortBy as an integer

---

agent/cache-types/streaming_health_services.go
agent/grpc/client.go
agent/grpc/handler.go

These tuning parameters match the gRPC transport used by streaming to have the same keepalive behaviour our Yamux-based RPCs do.
While doing scaling experiments we saw issues with TCP connections dropping and not being detected until an event delivery is attempted since the default keepalive is only sent every 2 hours in gRPC.
This also tunes the retry backoff during streaming materializer failures. These parameters may have improved recovery times after TCP drops some, but in fact gRPC itself has it's own backoff policy that comes into play here too which was not investigated further. These settings seem reasonable though, especially given that gRPC is already doing backoff on reconnections lower down in the stack for the vast majority of cases where streaming clients would error.

streaming: Grpc tuning

---

.changelog/9978.txt
agent/cache/cache.go
agent/cache/cache_test.go

While testing Consul at scale we found this issue where agent caches might never expire.
It occurs for cache types that cancel requests and so return from `Fetch` when `Close` is called.
Currently, only streaming cache types have this behaviour but it is a supported behaviour for other future cache types too. The race here occurs very frequently (i.e. virtually all the time):
1. Value expires in cache, the entry is removes and then `Close` is called on the cache type. 
2. This immediately cancels a context which causes the goroutine running the current backround `Fetch` call to return. 
3. The cache handles Fetch return in `fetch` method and immediately re-inserts the resulting error into the cache entry that was just removed, touches the TTL and lets it live again!
Never removing the …

cache: fix bug where TTLs were ignored leading to leaked memory in client agents

---

.changelog/9978.txt
.changelog/9979.txt
agent/cache/cache.go
agent/cache/cache_test.go

Based on #9978.
This fixes a bug in the agent cache where TTL expiry times are only updated when successful updates are received.
There are two different ways this can cause items to be prematurely evicted from the cache:
1. If the agent is disconnected from servers for at least one TTL period, the waiting client `Get` requests will go round their loop seeing only errors and not updating the expiry time even though they are still interested (i.e. the value is still "alive").
2. If no updates are sent for one entire TTL then the waiting Get's will never see a valid update response and so never touch the expiry time meaning the value will be evicted.
Currently we don't run into this because until streaming, all cache-types had long TTLs of 72 hours.
It's also self-recovering in that the …

cache: Fix bug where connection errors can cause early cache expiry

---

agent/consul/state/catalog_events_oss_test.go
agent/consul/state/catalog_events_test.go

Best viewed with whitespace off. This same pattern was used in #9452 for a large `agent/config` test.
This pattern is temporarily broken (see https://github.com/golang/go/issues/44887), but should be fixed in 1.16.x.
----
The TestServiceHealthEventsFromChanges function was over 1400 lines.
Attempting to debug test failures in test functions this large is
difficult. It requires scrolling to the line which defines the testcase
because the failure message only includes the line number of the
assertion, not the line number of the test case.
This is an excellent example of where test tables stop working well, and
start being a problem. To mitigate this problem, the runCase pattern can
be used. When one of these tests fails, a failure message will print the
line number of both the test case and …

state: use runCase pattern for large test

---

lib/retry/retry.go
lib/retry/retry_test.go

I changed this in https://github.com/hashicorp/consul/pull/8802#pullrequestreview-500779357 because exceeding the MaxWait seemed wrong, but as other have pointed out, that behaviour is probably correct.
When multiple waiters hit the max value, we don't want them to converge, so restore the behaviour of allowing jitter to exceed max, and document it.

lib/retry: allow jitter to exceed max wait

---

agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/service_manager.go
agent/service_manager_test.go
agent/structs/config_entry.go
agent/structs/connect_proxy_config.go
agent/structs/structs.go
agent/structs/structs_test.go
api/config_entry.go
api/config_entry_test.go
command/config/write/config_write_test.go

This is a bit of an omnibus PR fixing primarily these issues:
- Centrally configured upstreams should not have ports validated, since the port will be empty.
- Update how we know whether the request was from an old client, since checking for explicit upstreamIDs won't be correct in transparent proxy mode when no explicit upstreams are configured.
- Ensure that upstream defaults can be applied to all upstreams from intentions, rather than only merging them against explicit upstreams.
- Ensure that overriding mesh gateway mode for disco chain watches works in transparent proxy mode.
- Ensure synthetic upstreams get cleaned up in local registrations

Fixup centralized upstream config resolution

---

ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs

Protocol is not a required field to make the metrics request for upstream/downstream. Quick fix with empty string.

ui: Return empty string  protocol for upstream/downstream metrics request

---

website/pages/style.css

Patches the docs pages link color until the [branding changes](https://github.com/hashicorp/consul/pull/9884) roll out. 
[See the preview](https://consul-d5f33w88c-hashicorp.vercel.app/docs) to test.

fix(website): docs link text color

---

agent/proxycfg/state_test.go

This key in the UpstreamConfig map will encode the namespace if it exists, so we should use `ServiceName.String()` to handle that.

Fixup wildcard ent assertion

---

agent/structs/config_entry.go
agent/structs/config_entry_test.go

The zero value of these flags was already being excluded in the xDS
generation of circuit breaker/outlier detection config.
See: `makeThresholdsIfNeeded` and `ToOutlierDetection`.
This validation actually leads to users having to specify every field 
in the structs if any one of them is defined.

Remove zero-value validation of upstream cfg structs

---

agent/xds/clusters.go
agent/xds/listeners.go

Avoid nil panic when cluster config doesn't exist

---

website/content/api-docs/libraries-and-sdks.mdx

See also https://github.com/alphaHeavy/consul-haskell/issues/40.

add consul-haskell to libraries-and-sdks documentation

---

agent/xds/listeners.go

Upcoming changes to consul-k8s will sync the ClusterIP as a tagged address.
This PR adds every tagged address as a possible address to match on for transparent proxies.

Remove kube-dns resolution since clusterip will be a tagged addr

---

agent/agent_endpoint_test.go
agent/structs/connect_proxy_config.go
agent/structs/connect_proxy_config_test.go
api/agent.go
api/catalog_test.go
api/config_entry.go
api/config_entry_test.go
command/config/write/config_write_test.go
command/services/config_test.go

This way we avoid serializing these when empty. Otherwise users of the
latest version of the api submodule cannot interact with older versions
of Consul, because the api client would send keys that Consul doesn't
recognize yet.
Related: https://github.com/golang/go/issues/11939

Convert new tproxy structs in api module into ptrs

---

.changelog/10013.txt
agent/acl.go
agent/acl_endpoint.go
agent/acl_test.go
agent/agent.go
agent/agent_endpoint.go
agent/connect_auth.go
agent/consul/acl.go
agent/consul/acl_oss.go
agent/consul/acl_server.go
agent/consul/acl_server_oss.go
agent/consul/acl_test.go
agent/consul/client.go
agent/consul/server.go
agent/event_endpoint.go
agent/http.go
agent/structs/acl.go
agent/ui_endpoint.go

This moves static token into the ACLResolver. Previously it was being handled at the Agent level for resolving the agent master token.
This will ensure that these tokens can be resolved properly for audit logging purposes in enterprise.

Move static token resolution into the ACLResolver

---

.changelog/10013.txt
agent/acl.go
agent/acl_endpoint.go
agent/acl_test.go
agent/agent.go
agent/agent_endpoint.go
agent/connect_auth.go
agent/consul/acl.go
agent/consul/acl_oss.go
agent/consul/acl_server.go
agent/consul/acl_server_oss.go
agent/consul/acl_test.go
agent/consul/client.go
agent/consul/server.go
agent/event_endpoint.go
agent/http.go
agent/structs/acl.go

Backports #10013 
Conflicts:
* agent/acl.go
* agent/acl_test.go
* agent/agent.go
* agent/ui_endpoint.go
Just superficial conflicts, nothing is functionally different from the original PR

Backport 1.8.x 10013: Move static token resolution into the ACLResolver

---

.changelog/10025.txt
agent/consul/fsm/snapshot_oss.go
agent/consul/fsm/snapshot_oss_test.go

Fixes #9784
Previously only a single auth method would be saved to the snapshot. This commit fixes the typo and adds to the test, to show that all auth methods are now saved.

snapshot: fix saving of auth methods

---

.changelog/9851.txt
agent/config/config.go

[1.8.x] Fix advertise_addr_wan_ipv6 configuration key

---

.changelog/9851.txt
agent/config/config.go

[1.7.x] Fix advertise_addr_wan_ipv6 configuration key

---

.changelog/10023.txt
agent/kvs_endpoint.go
agent/kvs_endpoint_test.go
website/content/api-docs/kv.mdx

CVE-2020-25864
A vulnerability was identified in Consul and Consul Enterprise ("Consul") such that a specially crafted KV entry could be used to perform a XSS attack when viewed in the raw mode.
This PR adds content-type headers to raw KV responses to prevent that attack.

Add content type headers to raw KV responses

---

.changelog/10023.txt
agent/kvs_endpoint.go
agent/kvs_endpoint_test.go

Backport of #10023, refs CVE-2020-25864. Dropped the conflicting docs change in `website/content/api-docs/kv.mdx` because we only publish the website from the most recent release branch.

backport(1.7.x): fix raw kv xss

---

.changelog/10023.txt
agent/kvs_endpoint.go
agent/kvs_endpoint_test.go

Backport of #10023, refs CVE-2020-25864. Dropped the conflicting docs change in `website/content/api-docs/kv.mdx` because we only publish the website from the most recent release branch.

backport(1.8.x): fix raw kv xss

---

.changelog/10039.txt
ui/packages/consul-ui/app/services/repository/proxy.js

The extra argument meant that the blocking query configuration wasn't
being read properly, and therefore the correct ?index wasn't being sent
with the request.
The error was introduced after our last 1.9.x release (but it is in the 1.10-0-alpha), hence no backport.
@mikemorris are we adding changelog entries for things which were broken in 1.10.0-alpha and fixed here?

ui: remove old nspace argument from the proxy instance repository

---

ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_

We noticed that our mock API would sometimes respond with an empty array
of addresses - which resulted in an empty space in the gateway upstream
listing which looked as though it could be broken.
I checked with backend, and as this will never happen, I made the change
here also so the gateway upstream list is always fully populated with
addresses.

ui: Never respond with empty gateway addresses (mock-api)

---

agent/proxycfg/manager_test.go
agent/proxycfg/state_test.go
agent/structs/connect_proxy_config.go
agent/structs/connect_proxy_config_oss.go
agent/xds/clusters.go

Previously the Upstream.Identifier() key would not prepend the namespace
if it was the default namespace. On the other hand, elements in the
DiscoveryChain map always have the namespace prepended in enterprise.
This mismatch leads to not being able to fetch UpstreamConfig for a
given upstream's DiscoveryChain.
This PR preserves the original behavior in OSS, and adapts some
tests to account for the oss/ent split.

Split Upstream.Identifier() so non-empty namespace is always prepended in ent

---

.changelog/10016.txt
agent/consul/helper_test.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/consul/state/intention.go
agent/consul/state/intention_test.go
agent/structs/connect_proxy_config.go
agent/structs/intention.go
agent/structs/structs.go
agent/ui_endpoint.go
agent/ui_endpoint_test.go

This PR ensures that we return:
- Upstreams and downstreams from intentions
- Whether all instances of a service's proxies are in transparent mode
- The default allow policy
TODO after beta:
- Refactor/break up the catalog function

Update topology endpoint to account for transparent proxy

---

website/content/docs/upgrading/instructions/index.mdx
website/content/docs/upgrading/instructions/upgrade-to-1-8-x.mdx
website/data/docs-nav-data.json

At the time the guide was created, 1.8.4 was the most recent release. This updates that to reflect the new most recent release in the 1.8.x series.

docs: update upgrade guide to use 1.8.10

---

agent/structs/config_entry.go

Previously would panic when attempting to read `c.Overrides` just below.

Don't panic on nil UpstreamConfiguration.Clone()

---

ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_

Fixes UI test failures introduced in #10035 which didn't run (and so didn't show up as failing) due to a CircleCI authorization issue.

ui: fix mismatched curly brace in mock-api

---

test/integration/connect/envoy/case-basic/verify.bats
test/integration/connect/envoy/case-http/verify.bats

Previously the Upstream identifier in enterprise avoided prepending the namespace if the upstream was in the default namespace. 
This changed in #10031, so this PR updates integration test assertions to account for a potential `default/` prefix.

Check for optionally prepended namespace in upstream assertion

---

ui/packages/consul-ui/app/components/app/index.scss
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
ui/packages/consul-ui/app/components/main-nav-vertical/README.mdx
ui/packages/consul-ui/app/components/main-nav-vertical/debug.scss
ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
ui/packages/consul-ui/app/styles/debug.scss
ui/packages/consul-ui/lib/startup/templates/head.html.js

This PR hoists our Datacenter menu into the top navigation bar.
Before:
After:
Notes:
1. We want to maintain the correct tabbing order of the navigation menus, so this is achieved mainly via CSS.
2. Showing visual labels for menus are now controlled via CSS
3. We added a story for the entire `%main-nav-vertical` CSS component

ui: Hoist DC menu into the top navigation bar

---

website/content/docs/k8s/connect/health.mdx
website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/connect/ingress-gateways.mdx
website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/helm.mdx

All k8s connect-related docs now need to mention that we require a Kubernetes service
for all Connect services

docs: update helm ref docs and connect docs

---

go.sum

I guess a couple PRs crossed streams and somehow that resulted in this line not being needed anymore in go.sum

vendor: commit changes from update-vendor

---

.changelog/10069.txt
agent/structs/config_entry.go
agent/structs/config_entry_test.go

This PR disallows wildcards as the name for a `service-defaults` config entry. Using wildcards as service names clashes with how they're used by intentions.
Note that the wildcard specifier is already disallowed as the destination name of connect proxies.

Disallow * as service-defaults name

---

agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/acl_replication_types.go
agent/consul/acl_token_exp.go
agent/consul/catalog_endpoint.go
agent/consul/config_endpoint.go
agent/consul/config_replication.go
agent/consul/consul_ca_delegate.go
agent/consul/coordinate_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/federation_state_replication.go
agent/consul/intention_endpoint.go
agent/consul/kvs_endpoint.go
agent/consul/leader.go
agent/consul/leader_connect.go
agent/consul/leader_connect_test.go
agent/consul/leader_federation_state_ae.go
agent/consul/leader_intentions.go
agent/consul/leader_intentions_test.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/rpc.go
agent/consul/session_endpoint.go
agent/consul/system_metadata.go
agent/consul/txn_endpoint.go

Fixes #9970
Previously we were inconsistently checking the response for errors. This
PR moves the response-is-error check into `raftApply`, so that all callers
can look at only the error response, instead of having to know that
errors could come from two places.
This should expose a few more errors that were previously hidden because
some calls to `raftApply` were ignoring the response return value.
Also handle errors more consistently. In some cases we would log the
error before returning it. This can be very confusing because it can
result in the same error being logged multiple times. Instead return
a wrapped error.
Also fixes a bug with `canRetry` and chunking errors. Previously it never would
have retried on those errors because it was looking at the wrong arg.

Handle FSM.Apply errors in raftApply

---

website/data/docs-nav-data.json

This page wasn't present in navigation and therefore not rendering due to recent nav infrastructure changes - this gets the page back in the nav and rendering again. We will be running a wider scan for other pages that have this same issue shortly!

Fix missing agent/sentinel page

---

.changelog/9672.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go
api/connect_ca.go
command/connect/ca/set/connect_ca_set.go
website/content/api-docs/connect/ca.mdx
website/content/commands/connect/ca.mdx

Backport #9672 to 1.9.x
This seemed important to backport for corrective recovery situations.

[1.9.x] connect/ca: Allow ForceWithoutCrossSigning for all providers

---

.changelog/9672.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go
api/connect_ca.go
command/connect/ca/set/connect_ca_set.go
website/pages/api-docs/connect/ca.mdx
website/pages/commands/connect/ca.mdx

Backport #9672 to 1.8.x
This seemed important to backport for corrective recovery situations.

[1.8.x] connect/ca: Allow ForceWithoutCrossSigning for all providers

---

ui/packages/consul-ui/app/components/inline-code/README.mdx
ui/packages/consul-ui/app/components/inline-code/index.scss
ui/packages/consul-ui/app/components/inline-code/layout.scss
ui/packages/consul-ui/app/components/inline-code/skin.scss
ui/packages/consul-ui/app/instance-initializers/i18n.js
ui/packages/consul-ui/app/styles/base/components/form-elements/index.scss
ui/packages/consul-ui/app/styles/base/components/form-elements/layout.scss
ui/packages/consul-ui/app/styles/base/components/form-elements/skin.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/typography.scss
ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
ui/packages/consul-ui/app/templates/debug.hbs
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/translations/en-us.yaml

Adds intro copy to the ingress gateways upstreams tab explaining the `Host` header for non-Consul usage.
Notes:
1. Added an `%inline-code` CSS component in order to do this, plus a story for it, then used this component for the other place where we have inline code (KVs) for consistency.
2. Added the ability to reference certain environment variables from within our translations file to make it easier to insert root domain configurable URLs into translations.
3. We are currently inserting HTML into the translations file to allow us to sprinkle _minimal_ formatting and links into the translations. This is a small stop gap until we can add a minimal markdown formatter in-between the translation file and the hbs template (could be done in the same injected custom I18nService we've added …

ui: Add information regarding Host header for ingress gateways

---

ui/packages/consul-ui/README.md
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/docs/bookmarklets.mdx
ui/packages/consul-ui/node-tests/config/environment.js

This adds a `PartitionEnabled`/`CONSUL_PARTITIONS_ENABLED` feature flag
that can be set during production form the consul binary, or
additionally during development/testing via cookies.
If this property is not set in the binary at all, then we default to `false`.
Also added this setting to our engineering docs (theres a little more change here just due to me moving that around a little, see commit messages for details)

ui: Add Admin Partition feature flag

---

ui/packages/consul-ui/app/components/consul/intention/permission/form/layout.scss

ui: Vertically stack methods listing in the L7 intentions form

---

agent/consul/leader.go
agent/consul/replication.go
agent/consul/replication_test.go
agent/consul/server.go

This adds metrics around replication status and latest replicated index to be emitted for:
* ACL Tokens
* ACL Policies
* ACL Roles
* Legacy ACLs
* Federation States
* Config Entries
* Namespaces
The metrics will be emitted with the name: `consul.leader.replication.<type>.status` and `consul.leader.replication.<type>.index`
The `status` one is 0 if the last round of replication errored and 1 if it didn't. The `index` one is updated with the last replicated index.
As we don't have unit tests to ensure metrics were emitted correctly I tested this manually like so:
1. `make dev-docker` for this branch
2. `git clone github.com/mkeeler/consul-docker-test`
3. `cd acls` within the `consul-docker-test` source
4. `terraform init`
5. `terraform apply -var consul_image=consul-dev`
* This will bring …

Add replication metrics

---

sdk/testutil/retry/retry.go
sdk/testutil/retry/retry_test.go

On a few occasions I've had to dig through stack traces for tests that timeout
and noticed that `retry.Run` runs the function in a goroutine. This makes
debuging a timeout more difficult because the gourinte of the retryable
function is disconnected from the stack of the actual test. It requires
searching through the entire stack dump to find the other goroutine.
By using panic instead of runtime.Goexit() we remove the need for a
separate goroutine.
Also a few other small improvements:
* add `R.Helper` so that an assertion function can be used with both
testing.T and retry.R.
* Pass t to `Retryer.NextOr`, and call `t.Helper` in a number of places
so that the line number reported by `t.Log` is the line in the test
where `retry.Run` was called, instead of some line in `retry.go` that
is not …

sdk/retry: a few small debug improvements

---

lib/ttlcache/eviction.go
lib/ttlcache/eviction_test.go

I ran into this while working on a larger change.  This was not actually causing a bug, but it seems like it would have the potential to cause a bug if we ever had different sources use a different TTL value for the same entry.
Previously we allowed `Update` to decrease the expiry value. With this change the expiry must always increase.

lib/ttlcache: never decrease the expiry on update

---

.github/workflows/check-unlinked-content.js
.github/workflows/check-unlinked-content.yml
website/components/_temp-enable-hidden-pages/index.js
website/data/api-docs-nav-data-hidden.json
website/data/commands-nav-data-hidden.json
website/data/docs-nav-data-hidden.json
website/pages/api-docs/[[...page]].jsx
website/pages/commands/[[...page]].jsx
website/pages/docs/[[...page]].jsx

🔍 [Preview](https://consul-git-fork-zchsh-zshandle-unlinked-content-hashicorp.vercel.app)
This PR fixes an issue where pages that were previously not included in `*-nav-data.json` files were not rendered.
This PR introduces a temporary fix to ensure these pages are rendered, but are not shown in the sidebar navigation, to match previous behaviour. [We plan to revisit this issue more intentionally in the near future](https://app.asana.com/0/1100423001970639/1200197752405255/f).
`docs`
- [/docs/agent/rpc](https://consul-git-fork-zchsh-zshandle-unlinked-content-hashicorp.vercel.app/docs/agent/rpc) (compare to [live](https://www.consulproject.io/docs/agent/rpc))
- [/docs/agent/sentinel](https://consul-git-fork-zchsh-zshandle-unlinked-content-hashicorp.vercel.app/docs/agent/sentinel) (compare …

website: resolve unlinked content

---

test/integration/connect/envoy/helpers.bash

It's less DIY now, and also for some reason the old way started breaking during #9855 tests.

test: switch envoy integration tests to use pgrep+kill instead of ps+grep+awk+kill

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh
agent/consul/leader.go
agent/consul/replication.go
agent/consul/replication_test.go
agent/consul/server.go

In addition to the cherry pick of the #10073 commit this also pulls in a CI fix to use the right SSH key during the CI runs.

[Backport/1.9.x] Backport #10073

---

.changelog/10091.txt
command/snapshot/inspect/snapshot_inspect.go
command/snapshot/inspect/snapshot_inspect_test.go

Back port of #10091 as it didn't cherry-pick cleanly.

Fix panic bug in snapshot inspect (#10091)

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh
agent/consul/leader.go
agent/consul/replication.go
agent/consul/replication_test.go
agent/consul/server.go

In addition to cherry-picking the single commit from #10073 this also picks a recent commit from master to fixup the SSH key used for CI.

[Backport/1.8.x] Backport #10073

---

agent/consul/replication.go
agent/setup.go

This fixes up not adding these definitions in #10073

Add prometheus guage definitions for replication metrics.

---

.changelog/10062.txt
.circleci/config.yml
ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
ui/packages/consul-ui/app/helpers/duration-from.js
ui/packages/consul-ui/app/helpers/duration-from.mdx
ui/packages/consul-ui/app/services/temporal.js
ui/packages/consul-ui/package.json
ui/packages/consul-ui/tests/acceptance/dc/nodes/sessions/list.feature
ui/packages/consul-ui/tests/integration/helpers/duration-from-test.js
ui/packages/consul-ui/tests/unit/services/temporal-test.js
ui/yarn.lock

This PR adds human formatting to our nanosecond based session duration values.
The functionality makes use of the `pretty-ms` JS package, which also includes an option for formatting 'subMilliseconds' which in our case is useful for formatting to nanosecond precision (used by the session duration values).
We've used a new `temporal` service to do this, which uses the above package to format _numbers only_ for the moment (we can add further types in a central place when needed, and there's a dev warning if you pass anything but a number to the method). The is a tiny bit of extra functionality on top for the above package:
1. `pretty-ms` separates units with a space, so I split-joined the spaces out.
2. I realized that we probably don't want to show a unit if the value is zero, therefore if …

ui: Adds human formatting to nanosecond based session durations

---

.changelog/10122.txt
ui/packages/consul-ui/app/components/topology-metrics/index.js

Adding a conditional that prevents the Topology view from breaking when there are no upstreams in the upstream column.
Before
After

ui: Fix empty SVG height

---

.changelog/10124.txt
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

If there are no upstreams or downstreams but the user has permissive intentions, like wildcard or default allow, then we still need to show banner and *(All Services) card, not empty state.
Before
After

ui: Update conditional for topology empty state

---

.changelog/10133.txt
ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
ui/packages/consul-ui/translations/components/consul/en-us.yaml

Update the wording for the banner and the popover for a service with an upstream that is not explicitly defined. 
Before
After

ui: Update not-defined intention popover and banner

---

.changelog/10136.txt
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/translations/routes/en-us.yaml

Adding a "warning" notice at the top of the service instance upstream tab. This gives the user more information about the upstreams list rendered.

ui: Add TProxy Mode notice banner to service instance Upstreams tab

---

connect/proxy/config_test.go
connect/proxy/conn_test.go
connect/proxy/listener.go
connect/proxy/listener_test.go

We noticed that `TestUpstreamListener` would deadlock sometimes when run
with the race detector ([example](https://app.circleci.com/pipelines/github/hashicorp/consul/18113/workflows/d9d32c2f-9adb-4171-8957-734f50786d70/jobs/358395/tests)). While debugging this issue I found and fixed the
following problems.
1. the net.Listener was not being closed properly when Listener.Stop was
called. This caused the Listener.Serve goroutine to run forever.
Fixed by storing a reference to net.Listener and closing it properly
when Listener.Stop is called.
2. call connWG.Add in the correct place. WaitGroup.Add must be called
before starting a goroutine, not from inside the goroutine.
3. Set metrics config EnableRuntimeMetrics to `false` so that we don't
start a background goroutine in each test for no …

connect/proxy: fix a few problems with tests

---

.changelog/10127.txt
agent/config/runtime_test.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/config_entry.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/structs/config_entry.go
agent/structs/config_entry_cluster.go
agent/structs/config_entry_cluster_oss.go
agent/structs/config_entry_test.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
api/config_entry.go
api/config_entry_cluster.go
api/config_entry_test.go
command/config/write/config_write_test.go
website/content/docs/connect/config-entries/mesh.mdx
website/data/docs-nav-data.json

This config entry is being renamed primarily because in k8s the name
cluster could be confusing given that the config entry applies across
federated datacenters.
Additionally, this config entry will only apply to Consul as a service
mesh, so the more generic "cluster" name is not needed.

Rename "cluster" config entry to "mesh"

---

ui/packages/consul-ui/app/components/consul/intention/permission/header/list/layout.scss

ui: Add a max height and scroll to the intention perm header lists

---

.changelog/8431.txt

I noticed that the H2 ping checks were released as part of the most recent beta but didn't see a changelog entry. After doing some investigating, I noticed that the changelog file I wrote used `enhancements` as its type, which is not supported by the template. I fixed the entry to use `feature` instead. I am sorry for the mistake and hope it does not cause too much trouble.

make h2ping changelog entry conform with changelog template

---

.changelog/10106.txt
.circleci/config.yml
agent/xds/proxysupport/proxysupport.go
command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
command/connect/envoy/testdata/access-log-path.golden
command/connect/envoy/testdata/defaults.golden
command/connect/envoy/testdata/existing-ca-file.golden
command/connect/envoy/testdata/existing-ca-path.golden
command/connect/envoy/testdata/extra_-multiple.golden
command/connect/envoy/testdata/extra_-single.golden
command/connect/envoy/testdata/grpc-addr-config.golden
command/connect/envoy/testdata/grpc-addr-env.golden
command/connect/envoy/testdata/grpc-addr-flag.golden
command/connect/envoy/testdata/grpc-addr-unix.golden
command/connect/envoy/testdata/ingress-gateway-address-specified.golden
command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
command/connect/envoy/testdata/ingress-gateway.golden
command/connect/envoy/testdata/stats-config-override.golden
command/connect/envoy/testdata/token-arg.golden
command/connect/envoy/testdata/token-env.golden
command/connect/envoy/testdata/token-file-arg.golden
command/connect/envoy/testdata/token-file-env.golden
command/connect/envoy/testdata/zipkin-tracing-config.golden
test/integration/connect/envoy/run-tests.sh

Manual, modified backport of #10101 to 1.8.x

[1.8.x] connect: update supported envoy versions to 1.14.7, 1.13.7, 1.12.7, 1.11.2

---

.circleci/config.yml

manual backport of https://github.com/hashicorp/consul/pull/10145 to 1.8.x

[1.8.x] remove Codecov from CI runs (#10145)

---

.changelog/10149.txt
agent/config/builder.go
website/content/docs/agent/options.mdx

Enable `use_streaming_backend` by default.
I'll make the rest of the docs changes in a separate PR.

config: default UseStreamingBackend to true

---

website/content/docs/discovery/services.mdx

Be more explicit that the definition of multiple services only works in config files,
not using the HTTP API.
Ref: https://discuss.hashicorp.com/t/register-multiple-services-via-put-request/

docs(discovery/service): Clarify multiple service definitions

---

.changelog/10162.txt
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-18-x.golden
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/transparent-proxy.envoy-1-18-x.golden
agent/xds/testdata/listeners/transparent-proxy.v2compat.envoy-1-16-x.golden
website/content/docs/connect/transparent-proxy.mdx

Initially we were loading every potential upstream address into Envoy
and then routing traffic to the logical upstream service. The downside
of this behavior is that traffic meant to go to a specific instance
would be load balanced across ALL instances.
Traffic to specific instance IPs should be forwarded to the original
destination and if it's a destination in the mesh then we should ensure
the appropriate certificates are used.
This PR makes transparent proxying a Kubernetes-only feature for now 
since support for other environments requires generating virtual IPs, 
and Consul does not do that at the moment.

Only consider virtual IPs for transparent proxies

---

.changelog/10163.txt
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_test.go
command/login/login_test.go

Previously during a `consul login -method=blah`, if the auth method was not found, the
error returned would be "ACL not found". This is potentially confusing
because there may be many different ACLs involved in a login: the ACL of
the Consul client, perhaps the binding rule or the auth method.
Now the error will be "auth method blah not found", which is much easier
to debug.

Give descriptive error if auth method not found

---

agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/structs/discovery_chain.go
agent/xds/listeners.go
agent/xds/listeners_test.go

Previously we would associate the address of a discovery chain target
with the discovery chain's filter chain. This was broken for a few reasons:
- If the upstream is a virtual service, the client proxy has no way of
dialing it because virtual services are not targets of their discovery
chains. The targets are distinct services. This is addressed by watching
the endpoints of all upstream services, not just their discovery chain
targets.
- If multiple discovery chains resolve to the same target, that would
lead to multiple filter chains attempting to match on the target's
virtual IP. This is addressed by only matching on the upstream's virtual
IP.
**NOTE:** this implementation requires an intention to the redirecting 
virtual service and not just to the final destination. This is how 
we …

Fixup discovery chain handling in transparent mode

---

.changelog/10100.txt
ui/packages/consul-ui/app/components/aria-menu/index.js
ui/packages/consul-ui/app/components/consul/intention/list/layout.scss
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/components/informed-action/skin.scss
ui/packages/consul-ui/app/components/menu-panel/index.hbs
ui/packages/consul-ui/app/components/menu-panel/index.js
ui/packages/consul-ui/app/components/menu-panel/layout.scss
ui/packages/consul-ui/app/styles/base/icons/icon-placeholders.scss

This PR adds a new CRD popover menu when an intention is being managed by CRDs.

ui: Adds CRD popover 'informed action' for intentions managed by CRDs

---

.changelog/10151.txt
ui/packages/consul-ui/app/components/data-collection/README.mdx
ui/packages/consul-ui/app/search/predicates/health-check.js
ui/packages/consul-ui/app/search/predicates/nspace.js
ui/packages/consul-ui/app/search/predicates/role.js
ui/packages/consul-ui/app/search/predicates/service-instance.js
ui/packages/consul-ui/app/search/predicates/token.js
ui/packages/consul-ui/app/search/predicates/upstream-instance.js
ui/packages/consul-ui/app/styles/debug.scss
ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/lib/startup/index.js
ui/packages/consul-ui/lib/startup/templates/head.html.js

This PR fixes the text search functionality for the upstream instance list in the Service Instance > [Upstream] tab.
The bugfix is in the [first commit](https://github.com/hashicorp/consul/pull/10151/commits/6b9abb7ad3a299b1c41f54adaf09094ea85d2f80)
I also added just enough [documentation for the DataCollection component](https://consul-ui-staging-i4xumeuom-hashicorp.vercel.app/ui/docs/components/data-collection) to jog my memory for when I come back here again, or for someone else if they need to dig in here.
I also took the opportunity here to enable our UI Engineering Docs for our preview builds.

ui: Fix text search for upstream instances

---

.changelog/10152.txt
ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs

Previous to this the namespace was being prefixed to the gateways name (bug introduced in https://github.com/hashicorp/consul/pull/9282).
Before:
After:

ui: Remove extra nspace value from service upstreams

---

.circleci/config.yml
.circleci/scripts/cherry-picker.sh

If an automatic backport fails to more than one release branch we need to crate a PR to backport it. So far we've had to create a backport PR for each target release branch.
With this change, we may be able to create only a single PR, and then run the backport automation to cherry-pick it into other release branches.
The idea is that if a change introduced in version n-1 caused a conflict, and there are no other changes, then the backport automation should be able to use the new commit for version n-2 and n-3.

ci: allow cherry-picking a manual backport to other release branches

---

agent/config/runtime_test.go
agent/config_endpoint_test.go
agent/consul/config_endpoint.go
agent/consul/fsm/snapshot_oss_test.go
agent/proxycfg/state_test.go
agent/structs/config_entry.go
agent/structs/config_entry_mesh.go
agent/structs/config_entry_oss.go
agent/structs/config_entry_test.go
agent/xds/listeners_test.go
api/config_entry.go
api/config_entry_cluster.go
api/config_entry_test.go
command/config/write/config_write.go
command/config/write/config_write_test.go

Related to #10067, making this change to the new config entry before it is released makes it much easier to remove these fields.
No config entry needs a Kind field. It is only used to determine the Go type to target. As we introduce new config entries (like this one) we can remove the kind field and have the `GetKind` method return the single supported value.
In this case (similar to proxy-defaults) the Name field is also unnecessary. We always use the same value. So we can omit the name field entirely. In the future if we want to support separate names, we can introduce the field in a backwards compatible way, where empty string means the old default name.
TODO:

config-entry: remove Kind and Name field from Mesh config entry

---

connect/tls_test.go

Follow up #10004 based on a suggestion in https://github.com/golang/go/issues/45891#issuecomment-830444530
Use the exported function to compare the `x509.CertPool` instead of comparing unexported fields and excluding one. This should be functionally the same (both implementations cared the Subjects, but this one is more future proof.

testing: slightly better comparison for x509.CertPool

---

.changelog/10189.txt
agent/health_endpoint.go

A recent change in 1.9.x inverted the order of these two lines, which caused the `X-Consul-Effective-Consistency` header to be missing for the service health endpoints.

http: set consistency header properly for health endpoint

---

.changelog/9683.txt
agent/local/state.go

Manual backport of #9683 because automation no longer works for PRs opened before the SSH key changed.

[1.8.x] local: use agent token to deregister services

---

website/content/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes.mdx

Per Consul PM team, kubeconfig is not required for manual join. I believe this should be clarified in the docs as the current wording refers to the auto join steps above which state kubeconfig is required.

K8s docs: Manual join: add note that kubeconfig not required

---

website/content/api-docs/namespaces.mdx

Looks like some copy/paste from ACL docs.

docs: fix api-docs namespace descriptions

---

agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/auto_config_endpoint.go
agent/consul/auto_config_endpoint_test.go
agent/consul/auto_encrypt_endpoint.go
agent/consul/catalog_endpoint.go
agent/consul/client.go
agent/consul/config_endpoint.go
agent/consul/connect_ca_endpoint.go
agent/consul/coordinate_endpoint.go
agent/consul/discovery_chain_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/health_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/kvs_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint.go
test/integration/connect/envoy/case-basic/verify.bats
test/integration/connect/envoy/case-http/verify.bats

Follow up to #9991
* Remove an unnecessary arg from ForwardRPC
* more cleanup of `canRetry`
* add tests for `canRetry`
* backport some ent changes to integration tests.

rpc: some cleanup of canRetry and ForwardRPC

---

CHANGELOG.md

and add two entries to 1.10.0-beta1 missed due to changelog entry formatting issues fixed in #10111 and #10130

changelog: add 1.10.0-beta2

---

.changelog/10186.txt
ui/packages/consul-ui/app/components/tag-list/README.mdx
ui/packages/consul-ui/app/components/tag-list/index.hbs
ui/packages/consul-ui/app/components/tag-list/index.js
ui/packages/consul-ui/tests/acceptance/dc/services/show/tags.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/tags-steps.js
ui/packages/consul-ui/tests/pages/dc/services/show.js

Fixes https://github.com/hashicorp/consul/issues/10135
Notes:
1. First commit includes failing acceptance tests
2. Moved TagList component to a glimmer template only component and de-duped the tags (also added the ability to just specify `@tags`)
3. Added docs
~Tests are failing at the min 👀~

ui: [BUGFIX] De-duplicate Tag rendering

---

.changelog/10174.txt
ui/packages/consul-ui/app/components/consul/intention/permission/list/index.hbs
ui/packages/consul-ui/app/components/list-collection/index.hbs
ui/packages/consul-ui/app/components/list-collection/index.scss
ui/packages/consul-ui/app/components/list-collection/layout.scss
ui/packages/consul-ui/app/components/list-collection/skin.scss
ui/packages/consul-ui/app/styles/components.scss

We have a component that we use quite a lot called `<ListCollection />`, we use it for our 'virtual/DOM-recycling scrolling' and just for normal 'native scrolling' lists.
This PR adds a `@partial` attribute to this component, letting you specify that you only want a certain number of rows to show initially. When this attribute is set, we also render a 'View more' button to let the user expand the list to show all the rows instead of just a 'partial' amount.
We also took the opportunity here to move the `list-collection` styles into the `app/components/list-collection` folder, so everything is co-located in the one folder.

ui: Adds ability to show a 'partial' list in list-collections

---

.changelog/10157.txt
ui/packages/consul-ui/app/components/consul/nspace/list/index.hbs
ui/packages/consul-ui/app/styles/components/composite-row.scss

PRed as a potential alternative approach to https://github.com/hashicorp/consul/pull/9930. ~, therefore in draft for the moment.~
This fixes the spacing bug in nspaces only by only showing `Description` if the namespace has one, and removing the extra 2 pixel margin of `dd`s for when `dt`s aren't rendered/don't exist.
If this is approved, there is still the outstanding design question of what to do for the various mixtures of lists containing icons/no-icons/mixture of icons/no-icons. But once we've decided what we want to do there, we can PR whatever the decision is separately.
Before:
After:

ui: Fix nspace spacing issue

---

website/content/docs/upgrading/upgrade-specific.mdx

This makes it clear that most Consul installations will already be using Raft protocol 3 and also explains the condition where one might not be (i.e., when `raft_protocol = 2` is set in the config).

Flesh out Raft Protocol Support note

---

.changelog/10121.txt
ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
ui/packages/consul-ui/app/styles/components/composite-row.scss

Adds conditionals to show ID if no Name is provided. Adds conditional to hide TTL icon if no TTL is provided. 
Before
After

ui: Add conditionals to Lock Session list items

---

agent/checks/check.go

In https://github.com/hashicorp/consul/pull/8431 H2 ping checks were added, but the functionality currently terminates the TCP connection without gracefully shutting down the HTTP2 client connection first (sending a GOAWAY frame). This pull request adds the graceful shutdown and also WaitGroups (as was suggested in the original pull request).

Add graceful shutdown of client connection and WaitGroup to H2PING

---

.circleci/config.yml
agent/consul/acl_endpoint_test.go
agent/testagent.go
go.mod
sdk/testutil/retry/retry.go

I've noticed a few more test flakes lately ([ex](https://app.circleci.com/pipelines/github/hashicorp/consul/18450/workflows/29b09269-d2f6-4564-a73c-ac4a2bcb5bad/jobs/366684/tests#failed-test-2)).
One common one is "TestAgent already started" which is fixed by this PR, by properly setting `a.Agent = nil` in the error case.
The rest of these changes are to try and make the failures easier to debug by reporting the right line number.
Also updates `gotestsum` to pickup some bug fixes.
Also fixed a long standing issue with `TestACLEndpoint_Login_with_TokenLocality` where it was being reported as failing, even thought it had not failed (see the last commit).

testing: attempt to fix some test flakes

---

.changelog/10239.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/structs/config_entry.go

The prior solution to call reply.Reset() aged poorly since newer fields
were added to the reply, but not added to Reset() leading serial
blocking query loops on the server to blend replies.
This could manifest as a service-defaults protocol change from
default=>http not reverting back to default after the config entry
reponsible was deleted.

server: ensure that central service config flattening properly resets the state each time

---

.changelog/10240.txt
agent/structs/config_entry.go
agent/structs/config_entry_test.go

[1.9.x] agent: ensure we hash the non-deprecated upstream fields on ServiceConfigRequest

---

.changelog/10239.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/structs/config_entry.go

The prior solution to call reply.Reset() aged poorly since newer fields
were added to the reply, but not added to Reset() leading serial
blocking query loops on the server to blend replies.
This could manifest as a service-defaults protocol change from
default=>http not reverting back to default after the config entry
reponsible was deleted.
Backport of #10239 to 1.9.x

[1.9.x] server: ensure that central service config flattening properly resets the state each time

---

ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/package.json
ui/yarn.lock

A while ago we discovered `runInDebug` imported from `@ember/debug` and started using it to be able to add engineering utilities to the UI to help other engineers without compiling the required debug code into the final production build.
For example:
https://github.com/hashicorp/consul/pull/8658
https://github.com/hashicorp/consul/pull/9675
https://github.com/hashicorp/consul/pull/9666
https://github.com/hashicorp/consul/pull/9831
https://github.com/hashicorp/consul/pull/9771
During https://github.com/hashicorp/consul/pull/9831 we found out there was a change at some point in the ember docs that changed the documented behaviour of `runInDebug` from being 'stripped' to being a 'noop' instead.
> We also noticed whilst we were doing this that although the older ember documentation for …

ui: Use babel plugin to strip calls to runInDebug

---

website/data/subnav.js

This PR sets the 'overview' tab link to the home page instead of the learn platform.

chore(website): 'overview' nav item links to home page

---

.changelog/10225.txt
ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
ui/packages/consul-ui/app/models/session.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/components/composite-row.scss
ui/packages/consul-ui/mock-api/v1/session/info/_
ui/packages/consul-ui/mock-api/v1/session/node/_

Whilst reviewing https://github.com/hashicorp/consul/pull/9930 and https://github.com/hashicorp/consul/pull/10121 we noticed a few bugs that required fixing up within Lock Sessions in the UI.
The first and most important was that the Lock Session APIs changed shape back in 1.7 but the documentation doesn't reflect this change (https://www.consul.io/api-docs/session#sample-response-3) so I've already added an issue for this here https://github.com/hashicorp/consul/issues/10095
The UI still expected the JSON response to be in the pre-1.7 shape so primarily this PR alters our mock API and the UI to the shape of the response as it is post-1.7.
Also:
Viewing a Session for a KV:
1. We noticed that the `Name` property is optional, so we only show this row if a Name is set for a session.
2. We …

ui: Miscellaneous Lock Session fixes

---

ui/packages/consul-ui/docs/bookmarklets.mdx

Adds a bookmarklet to our docs for folks to toggle the QUnit preview during testing so you can see the things behind it easily:
I think this is only temporarily needed as I vaguely remember trying an upgrade of something and this seemed to have been fixed before I backed out of the upgrade I was doing. I might be misremembering though.

ui: Adds QUnit toggle bookmarklet to our docs

---

.changelog/10210.txt
agent/config/builder_oss.go
agent/config/builder_oss_test.go
agent/config/config.go
agent/config/runtime_oss_test.go
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json

Consul Enterprise is getting the ability to load licenses via configuration. This PR includes the necessary bits to allow that to happen.

Add OSS bits for supporting specifying the enterprise license via config

---

website/content/docs/nia/installation/requirements.mdx

Add a link for a new TF module that Cisco created that dynamically creates and updates Endpoint Security Groups.

Add link for new Cisco TF module

---

.changelog/10211.txt
api/operator_license.go

The two methods in the API client to Put or Reset a license will now always return an error. These APIs will no longer exist in Consul Enterprise so instead of just getting 405s or removing the methods which would require a v2 of the API for Go module semantic version compatibility, I have chosen to have these return a predefined error noting that the functionality was removed in v1.10.0

Deprecate API driven licensing

---

.circleci/config.yml
.circleci/terraform/load-test/main.tf
.circleci/terraform/load-test/variables.tf

This PR allows `BASH_ENV` to be used within the `hashicorp/terraform` image which is alpine based. 
I also fixed the cluster_name uniqueness. The variable was set in the CI run but the variable was never declared in TF config and passed to the module so it was never used 🤦 . Now each cluster should be uniquely named with the shortref

ci: allow bash_env in load-test

---

ui/packages/consul-ui/app/components/tab-nav/README.mdx
ui/packages/consul-ui/app/components/tab-nav/index.scss
ui/packages/consul-ui/app/components/tab-nav/skin.scss

Following our branding update, we noticed that the new `rose` color we use as a highlight on our secondary nav/tabs looked a little weird next to our `red-500` which we use quite a lot. Considering current `structure` uses a `blue-500` for the highlight for the tabs, we took the opportunity to bring our tab coloring into line with that. This was a one line change here https://github.com/hashicorp/consul/pull/10259/files#diff-e0f0d30e1061b08e14e2c0c0ad168b4ce7fc4c638576abbb7893df5777433590L16, but we also:
1. Added a gray bottom border to the tabs whilst hovering (something else I noticed we we differed slightly from current `structure`)
2. Moved all the grays to use CSS properties rather than SASS variables now we have those (confusing _only all our grays_ are currently back to CSS …

ui: change coloring of secondary navigation elements

---

.changelog/10248.txt
agent/agent.go
agent/auto-config/auto_config.go
agent/auto-config/auto_config_oss.go
agent/auto-config/auto_config_oss_test.go
agent/auto-config/auto_config_test.go
agent/auto-config/auto_encrypt.go
agent/auto-config/auto_encrypt_test.go
agent/auto-config/config.go
agent/auto-config/config_oss.go
agent/auto-config/mock_oss_test.go
agent/auto-config/mock_test.go
agent/consul/client.go
agent/consul/config.go
agent/setup.go
agent/setup_oss.go
sdk/testutil/testlog.go
test/integration/connect/envoy/run-tests.sh

Consul Enterprise will be changing the code to automatically retrieve a license from the servers in the dc. This code is moving into the auto-config package.
This PR contains the necessary OSS modifications and integration points to allow that to work.

Prepare for adding license auto-retrieval to auto-config in enterprise

---

.changelog/10267.txt
agent/agent.go
agent/config/config.go
agent/consul/acl_token_exp.go
agent/consul/enterprise_server_oss.go
agent/consul/leader.go
agent/consul/leader_connect.go
agent/consul/leader_connect_ca.go
agent/consul/leader_federation_state_ae.go
agent/consul/leader_intentions.go
agent/consul/replication_test.go
agent/consul/server.go
agent/setup.go
agent/setup_oss.go
agent/testagent.go
lib/routine/routine.go
lib/routine/routine_test.go

The bulk of this commit is moving the LeaderRoutineManager from the agent/consul package into its own package: lib/gort. It also got a renaming and its Start method now requires a context. Requiring that context required updating a whole bunch of other places in the code.

Move some things around to allow for license updating via config reload

---

website/content/docs/enterprise/index.mdx
website/data/docs-nav-data.json

This PR renames the documentation sidebar collection name `Enterprise Features` to `Consul Enterprise`. This is to follow the same pattern as the other products (Nomad, and Vault).

docs: rename enterprise to Consul enterprise

---

website/content/docs/k8s/installation/install.mdx

Adds more clear indicators that the collections on the learn.hashicorp.com sites have specific instructions for single node deployments.
Closes  #8260 as the docs pages have since been moved.
Co-Authored by: soonoo <qpseh2m7@gmail.com>

Update Kubernetes docs to point to install pages.

---

ui/packages/consul-ui/app/components/app-view/layout.scss
ui/packages/consul-ui/app/styles/routes/dc/services/index.scss

This PR includes two minor CSS layout bugfixes:
1. z-Index dancing (+1) for our `<ConsulKind @withInfo=true />`
I quite often work on a very small screen and I noticed we had some z-index clashes between our info popover things and our 'mid-size' search bar, which could happen more often now we have the sidebar navigation. It would be nice to change all over our popover menu type things to use our [`with-overlay` modifier](https://consul-ui-staging-hashicorp.vercel.app/ui/docs/modifiers/with-overlay) so we can pretty much forget about z-index dancing and avoid these types of problems moving forwards.
Before:
After:
2. Fix up TabNav top border
During https://github.com/hashicorp/consul/pull/10259 we re-styled our secondary navigation to more closely follow Structures TabNavigation, which …

ui: Minor CSS tweaks/layout fixes

---

ui/packages/consul-ui/app/components/route/README.mdx
ui/packages/consul-ui/app/components/route/index.hbs
ui/packages/consul-ui/app/components/route/index.js
ui/packages/consul-ui/app/services/routlet.js
ui/packages/consul-ui/app/utils/routing/transitionable.js

In https://github.com/hashicorp/consul/pull/10212 we found that:
> Ideally we would have liked to have used paramsFor and the various params arguments in model hooks to access these 'optional' parameters. They are just 'params' just like all our other parameters in URLs, they just happen to be optional. Unfortunately this proved to be a little difficult to integrate into ember, so we (hopefully temporarily) went with a new optionalParams method that is available on all routes. optionalParams returns a hash/object of the configured optionalParams, defaulting each of them to an empty string (this decision was based on the experience of what we needed for our namespace support and felt like it made sense)
This PR adds a new exported `params` property to our Route components (the base branch …

ui: Routlet Params

---

.changelog/10287.txt
ui/packages/consul-ui/app/components/consul/service-instance/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/styles/components/icon-definition.scss
ui/packages/consul-ui/mock-api/v1/catalog/connect/_
ui/packages/consul-ui/mock-api/v1/health/service/_

This PR adds UI support for Unix Domain Sockets for upstream and downstreams (see https://github.com/hashicorp/consul/pull/9981 and https://github.com/hashicorp/consul/pull/10252)
We currently are using a temporary icon for 'socket' (temporarily we are using the port icon) until we have finished up an icon that means 'socket'.
I also noticed some more API properties that have been added over recent releases that we hadn't added to our mock-api (we mostly don't use any of these but handy to see at a glance whats available)

ui: Unix Domain Socket support

---

.changelog/10302.txt
agent/xds/listeners.go
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-18-x.golden
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-16-x.golden

Including it shouldn't hurt functionally, since no filter chain would
reference it, but it likely adds overhead.

Avoid adding original_dst filter when not needed

---

.changelog/10301.txt
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/testdata/clusters/transparent-proxy catalog destinations only.envoy-1-18-x.golden
agent/xds/testdata/clusters/transparent-proxy catalog destinations only.v2compat.envoy-1-16-x.golden

Previously their creation was gated on the existence of the global mesh
config. The associated listener filter chain was being created
correctly.

Ensure passthrough clusters can be created

---

.changelog/_923.txt

Was already manually added to the `release/1.8.x` branch during the 1.8.11-beta2 release

changelog: add entry for network areas WAN config fix

---

.changelog/10273.txt
agent/http.go
api/debug.go
command/debug/debug.go
command/debug/debug_test.go

Fixes #10208
The API allows collecting profiles even when debug_enabled=false, as long as ACLs are enabled. This PR remove the check for `debug_enabled` from the CLI so that users do not need to set debug_enabled=true for no reason.
Also fixes the API client to return errors on non-200 status codes for debug endpoints and improves the failure messages when pprof data can not be collected.
The fix to the API client exposed the fact that most of these tests were actually failing silently. They were never checking the actual output, and all of these tests were hitting 500 errors on the server (see comment below for why). So this PR also fixes the tests.

debug: remove the CLI check for debug_enabled

---

ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs

We decided that the description field for intentions should be above the 'Allow/deny/app-aware' widget rather than below it.
Before:
After:

ui: Move intention form description field

---

.changelog/10306.txt
go.mod
go.sum
vendor/github.com/hashicorp/raft-autopilot/autopilot.go
vendor/github.com/hashicorp/raft-autopilot/run.go
vendor/github.com/hashicorp/raft-autopilot/state.go
vendor/github.com/hashicorp/raft-autopilot/types.go
vendor/modules.txt

This is a pretty simple dependency bump. Mainly we are wanting to pull in this fix: https://github.com/hashicorp/raft-autopilot/pull/9

Bump raft-autopilot version to the latest.

---

.changelog/10306.txt
go.mod
go.sum
vendor/github.com/hashicorp/raft-autopilot/autopilot.go
vendor/github.com/hashicorp/raft-autopilot/run.go
vendor/github.com/hashicorp/raft-autopilot/state.go
vendor/github.com/hashicorp/raft-autopilot/types.go
vendor/modules.txt

This backports PR #10306 to pull in the latest raft-autopilot version for v1.9.x.
There were conflicts in the go.mod files between versions which wasn't very unexpected. To create this PR I:
1. New branch from release/1.9.x
2. Copied over the changelog file from the PR being backported.
3. `go get github.com/hashicorp/raft-autopilot@v0.1.5`
4. `make update-vendor`
I don't know why it modified the go.sum of the api module but figure I would just let the `make update-vendor` do its thing and commit it anyways.

[1.9.x] Backport #10306

---

website/Dockerfile

Update the node version in the website's `Dockerfile` to the latest LTS version, which is 14.17.0.

fix(website): update node version to latest LTS for website

---

website/content/docs/ecs/get-started/install.mdx

Fixes markdown syntax of ECS ARN link. Currently, line break between link text & url is causing a display issue [here](https://www.consul.io/docs/ecs/get-started/install#task-iam-role) :
Change appears fixed in [preview](https://consul-e6luoni7g-hashicorp.vercel.app/docs/ecs/get-started/install#task-iam-role)

ui: Fix broken link format in ECS install page

---

website/content/docs/security/acl/acl-system.mdx

Reference the correct name of the agent token in the ACL Agent Token section for the ACL System docs.
The agent token was previously configured in the legacy ACL system by setting the `acl_agent_token` top-level config option, but was renamed to `acl.tokens.agent` with the new ACL system.

docs: Fix agent token name under ACL Agent Token

---

.changelog/10273.txt
agent/http.go
api/debug.go
command/debug/debug.go
command/debug/debug_test.go

Backport of #10273
Conflict was in `http.go`

[1.7.x] debug: remove the CLI check for debug_enabled

---

agent/structs/config_entry.go
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_test.go
agent/structs/intention.go
agent/structs/intention_test.go
agent/structs/prepared_query_test.go
agent/structs/structs.go
agent/structs/structs_test.go

related issue: #9437, this PR builds on #9480
This PR adds cache key completeness tests for the remaining types in `structs`. See the comment on `assertCacheInfoKeyIsComplete`, or the description in the linked issue, for how this works.
There are 2 or 3 structs outside of the `structs` package that also implement the `cache.Request` interface, but to test those we'll need to extract this assertion function to an `internal/testing/` helper package so we can export it.

structs: Add more cache key completeness tests

---

.changelog/10324.txt
command/connect/envoy/exec_test.go
command/connect/envoy/exec_unix.go
command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go
command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap_test.go

Fixes #10246
Normally the named pipe would buffer up to 64k, but in some cases when a
soft limit is reached, they will start only buffering up to 4k.
In either case, we should not deadlock.
This commit changes the pipe-bootstrap command to first buffer all of
stdin into the process, before trying to write it to the named pipe.
This allows the process memory to act as the buffer, instead of the
named pipe.
Also changed the order of operations in `makeBootstrapPipe`. The new
test added in this PR showed that simply buffering in the process memory
was not enough to fix the issue. We also need to ensure that the
`pipe-bootstrap` process is started before we try to write to its
stdin. Otherwise the write will still block.
Also set stdout/stderr on the subprocess, so that any errors are visible …

envoy: fix deadlock when input is larger than named pipe buffer size

---

version/version.go

Replaces and closes #10228 
This is a clone of the above community contribution. Tests were not running in their PR, and it needed a rebase anyways.

Fix strings.Replace->strings.ReplaceAll

---

website/content/commands/acl/set-agent-token.mdx

Clarify that tokens configured via `set-agent-token` will not be persisted if `acl.enable_token_persistence` is `false`.

docs: Clarify set-agent-token token persistence behavior

---

agent/consul/subscribe_backend_test.go
agent/grpc/client.go
agent/grpc/client_test.go
agent/grpc/resolver/registry.go
agent/grpc/resolver/resolver.go
agent/grpc/server_test.go
agent/setup.go
agent/submatview/store.go

We have seen test flakes caused by 'concurrent map read and map write', and the race detector reports the problem as well (prevent us from running some tests with -race).
The root of the problem is the grpc expects resolvers to be registered at init time before any requests are made, but we were using a separate resolver for each test.
This commit introduces a resolver registry. The registry is registered as the single grpc resolver for the `consul` scheme. Each test uses the Authority section of the target (instead of the scheme) to identify the resolver that should be used for the test. The scheme is used for lookup, which is why it can no longer be used as the unique key.
This allows us to use a lock around the map of resolvers, preventing the data race.
<details>
<summary>data race …

grpc: fix resolver data race

---

.changelog/10324.txt
command/connect/envoy/exec_test.go
command/connect/envoy/exec_unix.go
command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go
command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap_test.go

[1.8.x] envoy: fix deadlock when input is larger than named pipe buffer size

---

.changelog/10340.txt
agent/consul/server.go
agent/consul/usagemetrics/usagemetrics.go
agent/consul/usagemetrics/usagemetrics_oss_test.go
agent/consul/usagemetrics/usagemetrics_test.go
website/content/docs/agent/telemetry.mdx

This PR adds cluster members to the metrics API. The number of members per
segment are reported as well as the total number of members.
Tested by running a multi-node cluster locally and ensuring the numbers were
correct. Also added unit test coverage to add the new expected gauges to
existing test cases.

usagemetrics: add cluster members to metrics API (#10340)

---

.changelog/_917.txt
agent/consul/client_serf.go
agent/consul/enterprise_client_oss.go
agent/consul/enterprise_server_oss.go
agent/consul/replication.go
agent/consul/server_serf.go
agent/metadata/server.go
agent/metadata/server_test.go

Restores the backport of https://github.com/hashicorp/consul/pull/10277 to `release/1.8.x`
This reverts commit 442a8efc7fc7eb0121e27339e5322efef5ea6418.

restore(1.8.x): Serf tag refactor

---

agent/submatview/store.go
agent/submatview/store_test.go

When info.Timeout is 0, it should have no timeout. Previously it was using a 0 duration timeout which caused it to return without waiting.
This bug was masked by using a timeout in the tests. Removing the timeout caused the tests to fail.
This bug only exists in the latest 1.10 beta release, so I guess no need for a changelog entry.

submatview: fix a bug with Store.Get

---

website/content/docs/connect/registration/service-registration.mdx
website/content/docs/discovery/services.mdx

This is a starting point for docs for the Unix Domain Sockets work
Most of the below writeup has been incorporated in the docs text, but a few issues remain:
1) It might be nice to incorporate the example at the end into the docs somehow, but wasn't sure how.
2) I didn't update the sample fields in the API docs; wasn't sure how to do that without confusion.
There are a number of cases where a user might wish to either 1)
expose a service through a Unix Domain Socket in the filesystem
('downstream') or 2) connect to an upstream service by a local unix
domain socket (upstream). 
As of Consul (1.10-beta2) we've added new syntax and support to configure
the Envoy proxy to support this
To connect to a service via local Unix Domain Socket instead of a
port, add local_bind_socket_path and …

Docs for Unix Domain Sockets

---

.changelog/10358.txt
command/monitor/monitor.go
command/monitor/monitor_test.go

when starting a new monitor we were starting (in case of json monitor) a json monitor and then overwrite it with a line monitor.
This will start one or the other.
Fix #10357

fix monitor to only start the monitor in json format when requested

---

website/content/docs/ecs/get-started/install.mdx

The [routing section](https://www.consul.io/docs/ecs/get-started/install#routing) of the ECS "Install" docs is really helpful, but the example terraform shows the `upstreams` and `environment` fields on the same level when the latter is actually [specified within the container definition](https://github.com/hashicorp/terraform-aws-consul-ecs/blob/main/examples/dev-server-fargate/main.tf#L58-L78). This change updates the example to reflect this.
Structured as shown, `terraform plan` throws an error

docs: Improve object nesting of ECS routing example

---

agent/consul/stream/event_buffer.go
agent/consul/stream/event_buffer_test.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_snapshot.go
agent/consul/stream/event_snapshot_test.go

While working on an end-to-end test for streaming I encountered this bug. The e2e test isn't quite ready yet, but I thought I would surface this bug fix separately.
This PR is best viewed by individual commit.
The head of the topic buffer was being ignored when creating a snapshot. This commit fixes the bug by ensuring that the head of the topic buffer is included in the snapshot before handing it off to the subscription.

stream: fix a bug with subscriptions and the latest item in the topic buffers.

---

website/data/alert-banner.js

---
Updates the alert banner data for HashiConf europe going live.

chore: updates alert banner

---

CHANGELOG.md
website/data/version.js

Also updates the main changelog with entries from recent releases.

website: bump latest binary to 1.9.6

---

.changelog/10302.txt
.changelog/10365.txt
agent/xds/listeners.go
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-18-x.golden
agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-16-x.golden

This reverts commit 19334e8abf7f3c9507bb400b9cc9045bb86845c0.
The addition of the "original_dst" filter does not depend on the mesh config, only on whether the proxy is in transparent mode. 
The PR to revert made it so that transparent proxying didn't work when `Mesh.TransparentProxy.CatalogDestinationsOnly` was set to `true` because Envoy couldn't recover the original IP address before iptables redirection.

Revert "Avoid adding original_dst filter when not needed"

---

agent/submatview/store_integration_test.go

This PR adds a test which integrations `rpc/health.Client`, and `submatview.Store`, with a real `rpc/subscribe` backend, and `stream.EventPublisher`. It runs with the race detector enabled to catch any concurrency bugs in the `submatview.Store`.

submatview: and Store integration test with stream backend

---

sdk/testutil/server.go

We have 2 threads calling `exec.Cmd.Wait` which is not reentrant. It causes some test case failure at our side when running the test suite with the `-race` flag.
I've just removed the `cmd.Wait` which looks useless.
Related to #8329

remove a race condition in sdk testutil server stop

---

agent/rpcclient/health/health.go
agent/submatview/store_test.go

Also set a more unique name for the serviceRequest.Type to prevent potential name conflicts in the future.

submatview: add test cases for store.Get with timeout and no index

---

agent/agent_endpoint.go

The `PrimaryDatacenter` value is available in the `DebugConfig` field, but that field is not stable and could change at any time.
The consul-k8s needs to be able to detect the primary DC for tests, so adding this value to the stable part of the API response.

http: add PrimaryDatacenter to the /v1/agent/self  response

---

website/content/docs/k8s/connect/terminating-gateways.mdx

Previously if you were to follow these docs and register two external
services, you would set the Address field on the node. The second
registered service would change the address of the node for the first
service.
Now the docs explain the address key and how to register more than one
external service.

Update k8s term gateway docs to make address clear

---

.changelog/10394.txt
agent/structs/structs.go
agent/structs/structs_test.go

Previously we would return an error if duplicate paths were specified.
This could lead to problems in cases where a user has the same path, 
say /healthz, on two different ports.
This validation was added to signal a potential misconfiguration.
Instead we will only check for duplicate listener ports, since that is
what would lead to ambiguity issues when generating xDS config.
In the future we could look into using a single listener and creating
distinct filter chains for each path/port.

Relax validation for expose.paths config

---

.changelog/10395.txt
logging/grpc.go
logging/grpc_test.go

grpc: move gRPC INFO logs to be emitted as TRACE logs from Consul

---

.changelog/10381.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/listeners.go
agent/xds/xds_protocol_helpers_test.go

Updates to a cluster will clear the associated endpoints, and updates to
a listener will clear the associated routes. Update the incremental xDS
logic to account for this implicit cleanup so that we can finish warming
the clusters and listeners.
Fixes #10379

xds: ensure that dependent xDS resources are reconfigured during primary type warming

---

api/acl.go
api/agent.go
api/api.go
api/catalog.go
api/config_entry.go
api/connect_ca.go
api/connect_intention.go
api/coordinate.go
api/debug.go
api/discovery_chain.go
api/event.go
api/health.go
api/kv.go
api/namespace.go
api/operator_area.go
api/operator_autopilot.go
api/operator_keyring.go
api/operator_license.go
api/operator_raft.go
api/prepared_query.go
api/session.go
api/status.go
api/txn.go

https://golang.org/pkg/net/http/#Client.Do says this:
> If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.
In some places we use `json.Decoder.Decode` to read the response body, but the decoder does not necessarily read all bytes. If there is any trailing whitespace (or other characters) the response body may not be fully read, preventing the client from re-using the TCP connection.
By reading and discarding all the bytes we ensure that the connection can be re-used.
I've seen a similar patch applied in a few other code bases to ensure that tcp connections can be re-used.

api: properly close the response body

---

.changelog/10368.txt
agent/agent_endpoint.go
logging/monitor/monitor.go
logging/monitor/monitor_test.go

Fixes #10347
improve monitor performance to avoid filling the log channel and loose logs when running monitor or debug.
An issue was reported that we loose some logs when are running `consul monitor` or `consul debug` commands. 
the current underlying monitor implementation avoid blocking when writing logs to not impact performance and allow losing some logs when we overflow the log channel (size 512 lines of code). This PR is to enhance the performance of the log channel read so we can avoid loosing logs.

improve monitor performance

---

agent/agent_endpoint_test.go
agent/structs/connect_proxy_config.go
agent/structs/connect_proxy_config_test.go

Updated JSON marshaling to avoid returning the proxy.transparent_proxy field when empty.
Opted to avoid turning it into a pointer so that it doesn't have to be nil-checked on every access.
Is there anything I'm missing about this approach?

Omit empty tproxy config in JSON responses

---

.changelog/10404.txt
agent/xds/listeners.go
agent/xds/testdata/listeners/ingress-http-multiple-services.envoy-1-18-x.golden
agent/xds/testdata/listeners/ingress-http-multiple-services.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/ingress-splitter-with-resolver-redirect.envoy-1-18-x.golden
agent/xds/testdata/listeners/ingress-splitter-with-resolver-redirect.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/terminating-gateway-custom-and-tagged-addresses.envoy-1-18-x.golden
agent/xds/testdata/listeners/terminating-gateway-custom-and-tagged-addresses.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/terminating-gateway-no-api-cert.envoy-1-18-x.golden
agent/xds/testdata/listeners/terminating-gateway-no-api-cert.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/terminating-gateway-service-subsets.envoy-1-18-x.golden
agent/xds/testdata/listeners/terminating-gateway-service-subsets.v2compat.envoy-1-16-x.golden
agent/xds/testdata/listeners/terminating-gateway.envoy-1-18-x.golden
agent/xds/testdata/listeners/terminating-gateway.v2compat.envoy-1-16-x.golden

Fixes: #9887
This PR updates the stats_prefix for ingress and terminating gateways.
1. For ingress gateways the change makes it so that the listener _port_ (`listenerKey.RouteName()`) does not get encoded in the metric name. (Brought up in the issue)
2. For terminating gateways we also make it so that the listener _name_ does not get encoded in the metric name. There was also a change to the filter name so that the rules defined [here](https://github.com/hashicorp/consul/blob/64d122b0a2447a6e0597bdaa3912e83cd15ef3ed/command/connect/envoy/bootstrap_config.go#L392:L410) apply. This will enable per-destination listener metrics.
These changes are **NOT** backwards compatible.
In 1.9.x:
```
envoy_http_14146_no_route{
local_cluster="ingress-service",
consul_source_service="ingress-service", …
```

Update ingress/terminating gateway stats labeling

---

agent/proxycfg/manager.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go

This PR makes a couple small changes to `proxycfg.state` to re-organize the package by vertical (feature). More details in the commit messages. Probably best viewed by individual commit.
Currently `state` has 3 switch/case statements to branch the logic for each kind of proxy. This PR starts us on a path to being able to use an interface, and a separate implementation of the interface for each kind. The generic parts of `state` (for handling watches and requests for snapshots) will remain in `state`, but the logic for initializing, and handling updates (which is 100% different for each kind) will be moved into a new type that `state` can use.  Much of this work is done in the follow up PRs #9489, #9490
I believe the proposed design will both make it easier to add new kinds, and also make …

proxycfg: prepare state for split by kind

---

.changelog/_releases-111.txt
.changelog/changelog.tmpl

Adding as a changelog entry to clarify this is Enterprise-only instead of adding to the OSS README in https://github.com/hashicorp/consul/pull/10412
Will show up as a changelog entry for 1.10 as:
```
NOTES:
* legal: **(Enterprise only)** Enterprise binary downloads will now include a copy of the EULA and Terms of Evaluation in the zip archive
```

changelog: add note on EULA/ToE packaging with Enterprise binaries

---

agent/config/builder.go
tlsutil/config.go
tlsutil/config_test.go

As I have been reading through the `tlsutil` package I noticed a panic and a few other things that were potentially unsafe or made it more difficult to read. This PR fixes the issues.

tlsutil: fix a possible panic, and make the package safer

---

agent/proxycfg/manager.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go

Instead of multiple switch/case statements, use a separate type for each kind of proxy. This makes adding new kinds easier because the new implementation can be added by implementing the interface.
Next steps will be to move each of the handlers into their own files so that the watch and update operations are next to each other.  (#9490)

proxycfg: split state into a handler for each kind

---

.changelog/10432.txt
agent/consul/client.go

This is needed in order to access the agent token in some enterprise code.

Hold onto the token store from the base deps in the Client

---

.changelog/10432.txt
agent/consul/client.go

This backports #10432. There was a conflict with because the `Client` in 1.8.x doesn't have the agent `BaseDeps` passed into it but rather has the token store provided in its options.

[1.8.x] Backport #10432

---

website/content/docs/k8s/connect/health.mdx

Update the health checks docs to include the changes for tproxy such as:
- mutating the k8s startup/liveness/readiness probes 
- addition of expose paths for these probes

Update health checks docs for tproxy

---

.changelog/10441.txt
agent/config/builder_oss.go
agent/config/builder_oss_test.go
agent/config/config.go
agent/config/runtime_oss_test.go
agent/config/runtime_test.go

This is mainly for forward compatibility with 1.10 where licensing requirements are changing.
For older releases we are adding the ability to load the license from a configuration/environment to facilitate a smoother upgrade process. For servers, we will allow the configuration to be set but it will not be used (a warning log is emitted saying as much). For client agents it will actually cause the license to be used in place of the auto-retrieval process.
Unlike with 1.10, client agents will not be able to update the license loaded via config with a reload. It is expected that this configuration is only used while on the path to upgrading to 1.10 and therefore the ability to reload the license should not be necessary.

Add ability to load a license from the configuration/environment

---

.changelog/10442.txt
agent/config/builder_oss.go
agent/config/builder_oss_test.go
agent/config/config.go
agent/config/runtime_oss_test.go
agent/config/runtime_test.go
agent/consul/client_test.go

This is mainly for forwards compatibility with 1.10 and should not be relied on for a cluster staying on a 1.8.x/1.9.x version. This was also just a backport of #10441 to the release/1.8.x branch.
For older releases we are adding the ability to load the license from a configuration/environment to facilitate a smoother upgrade process. For servers, we will allow the configuration to be set but it will not be used (a warning log is emitted saying as much). For client agents it will actually cause the license to be used in place of the auto-retrieval process.
Unlike with 1.10, client agents will not be able to update the license loaded via config with a reload. It is expected that this configuration is only used while on the path to upgrading to 1.10 and therefore the ability to reload the …

[1.8.x] Backport #10441 - Add ability to load a license from the configuration/environment

---

ui/packages/consul-ui/app/components/main-header-horizontal/layout.scss

In https://github.com/hashicorp/consul/pull/10295 we made a minor CSS layout bugfix that involved some z-index dancing. As is often the case with z-index dancing, once you change step everyone else has to change step also otherwise things like this happen:
This PR increases the z-index of the main menus in order to fix this layering bug.
Ideally we really need to get around to using our `tippy.js` based `{{with-overlay}}` modifier for all our menus, but for the moment this kicks the can a little further down the road, ten times 😄 .

ui: Increase z-index of main menus to avoid layering issues

---

tlsutil/config.go
tlsutil/config_test.go

Adds some godoc to explain what the types/fields are used for.
Removes some unused things, and un-exports internal things.
Change a couple pointer fields to non-pointers to remove the need to point at different places in memory.

tlsutil: additional godoc and small cleanup

---

agent/auto-config/auto_config_test.go
agent/auto-config/auto_encrypt_test.go
agent/auto-config/config.go
agent/auto-config/mock_test.go
agent/auto-config/run.go
tlsutil/config.go
tlsutil/config_test.go

Branched from #10439
Replace two methods with a single one that returns the cert. This moves more of the logic into the single caller (auto-config).
tlsutil.Configurator is widely used. By keeping it smaller and focused only on storing and returning TLS config, we make the code easier to follow.
These two methods were more related to auto-config than to tlsutil, so reducing the interface moves the logic closer to the feature that requires it.

tlsutil: reduce interface provided to auto-config

---

website/content/docs/enterprise/license/faq.mdx

This PR was to update the FAQ to include information about the upgrade requirements for 1.10.0: customers on Consul Enterprise 1.8+ or 1.9+ must upgrade Consul agents to the latest patch available (1.8.13 or 1.9.7) prior to upgrading the Consul server instances to 1.10.0.

docs: updated FAQ to accommodate new requirements prior to upgrading

---

website/content/docs/connect/config-entries/index.mdx
website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/registration/service-registration.mdx
website/content/docs/k8s/connect/index.mdx
website/pages/downloads/index.jsx

Remove beta tag for 1.10 features which are now GA.
Also remove beta callout on downloads page.

docs: Remove beta tag for 1.10 features

---

website/content/docs/connect/transparent-proxy.mdx
website/data/docs-nav-data.json

Should be merged after #10408 for the annotation links to work. Should be merged after Consul 1.10 GA, Consul-k8s 0.26.0, and Consul-helm 0.32.0 .

docs: update tproxy docs (/docs/connect/transparent-proxy)

---

website/content/docs/k8s/connect/index.mdx
website/content/docs/k8s/connect/ingress-gateways.mdx
website/content/docs/k8s/connect/terminating-gateways.mdx

* Assume tproxy is enabled by default and connect to upstreams
with kube DNS.
* Update docs for missing annotations.
This PR should be merged after Consul 1.10 GA, consul-k8s 0.26.0 GA and consul-helm 0.32.0 GA.

docs: update docs/k8s/connect for tproxy GA

---

website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/k8s/crds/index.mdx

Mesh is now a Config Entry as well as CRD as of Consul 1.10 GA. Also removing extra brace on ServiceDefaults that was causing Vercel deployments to fail.

docs - Adding Mesh as CRD in Consul K8s

---

.changelog/10478.txt
agent/structs/config_entry.go
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_gateways.go
agent/structs/config_entry_intentions.go
agent/structs/config_entry_intentions_oss.go
agent/structs/config_entry_intentions_test.go
agent/structs/config_entry_oss.go

affected kinds: service-defaults, ingress-gateway, terminating-gateway, service-intentions

structs: prohibit config entries from referencing more than one partition at a time

---

website/content/docs/nia/compatibility.mdx

Did a quick verification running CTS v0.2.0 with Consul 1.9.7 and 1.10.0 (the CI tests run with 1.8.0 so I didn't manually test that). Also tested CTS v0.1.2 with Consul 1.10.0
Added Terraform versions too because it's probably helpful 🙂 
[Preview link](https://consul-prf0b3obb-hashicorp.vercel.app/docs/nia/compatibility)

docs/nia: Update CTS compatible versions

---

website/content/docs/k8s/helm.mdx

Removing references from the 1.10 beta that were included in Helm Configuration Reference

docs: Remove beta version references from Helm reference

---

.circleci/config.yml

So that we catch any incompatibilities with the preivous Go version.
Related to #10470

ci: test api/sdk against last 2 Go versions

---

agent/connect/ca/provider.go
agent/connect/ca/provider_vault.go
agent/consul/leader_connect_ca.go

With an optional interface that providers can use to indicate if they
use an intermediate cert in the primary DC.
This removes the need to look up the provider config when renewing the
intermediate.

ca: replace ca.PrimaryIntermediateProviders

---

.changelog/10490.txt
tlsutil/config.go
tlsutil/config_test.go

Fixes #10481 
Related to https://github.com/hashicorp/consul/pull/9475#discussion_r566328324
When `EnableAgentTLSForChecks` is disabled we should not default to the agent server or node name.
The specific fix and test case can be seen in the second commit.

tlsutil: fix ServerName used for health checks that use TLS

---

sdk/testutil/io.go

This may have had some origin story as a workaround for something, but we don't even reliably use this throughout consul as it is so I suspect it was either unnecessary or no longer necessary.

sdk: Stop making a special /tmp/consul-test directory for testutil.TempFile and testutil.TempDir

---

.changelog/10490.txt
tlsutil/config.go
tlsutil/config_test.go

[1.10.x] tlsutil: fix ServerName used for health checks that use TLS

---

.changelog/10401.txt
agent/dns.go
agent/dns_test.go

This fix #10393
this is a bug for sure because we return a different record type then the one requested. That said we need to verify what is the intended behaviour:

return an empty record when asked for an addr dns with type other then A, AAAA and ANY

---

ui/packages/consul-ui/.docfy-config.js
ui/packages/consul-ui/README.md
ui/packages/consul-ui/app/styles/debug.scss
ui/packages/consul-ui/docs/index.mdx

This PR allows an engineer to colocate additional documentation within the Consul UIs Engineering Documentation, if need be, by specifying a local environment variable. This additional documentation will then be available only to the engineer on their machine, it does not get bundled in with any of our automated builds or UI preview sites.
It began as a single line change but I added a little more error checking for if someone tries this and for whatever reason they haven't quite done it correctly. Errors will warn in terminal but not block compilation/application serving.
We also specifically take extra care to avoid using `require` (a cousin of `eval`) to pull in the extra config, and only use a JSON file for anything specified in the environment file, so nothing specified in this file …

ui: Enable specifying additional docfy config as json

---

tlsutil/config.go
tlsutil/config_test.go

This PR makes a number of changes to try and reduce the size of tlsutil, and also make the logic a bit easier to trace by removing some functions.
* unexports a method that was only used internally
* removes methods whose sole purpose is to read a single field ("getter methods") and read the field directly
* removes some duplicate methods
* adds some slightly more descriptive docstrings
* inverts the logic in `outgoingRPCTLSDisabled` to remove double negatives.

tlsutil: unexport and remove methods

---

.changelog/10514.txt
agent/agent.go
agent/agent_test.go
agent/health_endpoint_test.go
agent/http.go
agent/rpcclient/health/health.go
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
agent/streaming_test.go
agent/structs/protobuf_compat.go
agent/structs/structs.go
agent/submatview/materializer.go
agent/submatview/store.go
proto/pbcommon/common.go
website/content/api-docs/features/blocking.mdx

This PR adds a new `X-Consul-Query-Backend` response header to make it easier to determine when streaming was used for a query. Adds a check for this header to a few tests that are meant to check that streaming is being used.
And finally fix the bug that was preventing streaming from being enabled on the client.
One commit is cherry-picked from #10396. It removes a test that is both very racy and also no longer valid because the requests are made via streaming, not the cache. Since the cache rate limit functionality is already tested in the appropriate package (agent/cache) it seems like we can remove this failing/flaky test.

streaming: fix not being able to enable streaming

---

website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/operations/uninstall.mdx

Helm 2 is no longer supported via Consul K8s. Helm 3 is now the supported version for Consul K8s.

docs: Remove Helm 2 mention in Consul K8s install and uninstall

---

website/content/docs/agent/options.mdx
website/content/docs/install/cloud-auto-join.mdx

Specifically call out that agents can be configured to join a network segment by either specifying the Serf LAN port in the join address, changing the agent's default Serf LAN port by configuring `ports.serf_lan`, or specifying the port in the `-serf-lan-port` command line flag.
Resolves #9972, resolves hashicorp/go-discover#57

docs: Clarify serf_lan/retry_join behavior with network segments

---

website/content/docs/connect/config-entries/service-splitter.mdx

Weight sum must be equal to 100.

docs: fix service splitter example weight sum

---

website/content/api-docs/libraries-and-sdks.mdx

We (Roblox) just published https://github.com/Roblox/rs-consul -- adding it to the list here for discovery by others.

Add rs-consul client to community-provided SDKs list

---

website/content/docs/connect/observability/ui-visualization.mdx

It's tricky because the `{{` needs to be escaped with Helm.
Fixes https://github.com/hashicorp/consul-helm/issues/1006

docs: Document setting dashboard_url on k8s

---

website/content/docs/k8s/connect/observability/metrics.mdx

The docs note an alpha pre-release version on K8s observability. Updating to only reference the GA 1.10.0 version of Consul for observability on k8s and metrics merging.

docs: remove alpha from 1.10.0 reference for observability on k8s metrics merging

---

.changelog/10515.txt
.circleci/config.yml
agent/config/runtime_test.go
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/grpc/stats.go
command/connect/redirecttraffic/redirect_traffic_test.go
tlsutil/config.go

Fixes #10509
Fixes 3 places where a `uint64` struct field was used with `sync/atomic`. The fields were not the first field in the struct, and would cause a panic on 32-bit platforms because the other fields caused the `uint64` fields to be not 64-bit aligned (https://golang.org/pkg/sync/atomic/#pkg-note-BUG). Also updates the comments to be more explicit about the problem.
Adds a new `go-test-32bit` CI job to catch the problem. It only runs `-short` tests so that we don't have to run a bunch of parallel jobs, but this seems to catch our existing problems even without running all tests. Hopefully all use of `sync/atomic` is covered by at least one test that runs in under 100ms.
TODO:

Fix panic on 32-bit platforms

---

.changelog/10514.txt
agent/agent.go
agent/agent_test.go
agent/health_endpoint_test.go
agent/http.go
agent/rpcclient/health/health.go
agent/rpcclient/health/view.go
agent/rpcclient/health/view_test.go
agent/streaming_test.go
agent/structs/protobuf_compat.go
agent/structs/structs.go
agent/submatview/materializer.go
agent/submatview/store.go
proto/pbcommon/common.go
website/content/api-docs/features/blocking.mdx

[1.10.x] streaming: fix not being able to enable streaming

---

CHANGELOG.md

Replaces `1.10.0-beta` prerelease changelog entries.

changelog: add 1.10.0, 1.9.7 and 1.8.13

---

CHANGELOG.md
agent/connect/uri.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_replication.go
agent/consul/authmethod/authmethods.go
agent/consul/authmethod/testauth/testing.go
agent/consul/discoverychain/compile.go
agent/consul/server.go
agent/service_manager_test.go
agent/sidecar_service.go
agent/structs/config_entry_discoverychain.go
agent/xds/routes.go
build-support/scripts/test-flake.sh
command/exec/exec.go
connect/proxy/config.go
ui/packages/consul-ui/app/mixins/with-blocking-actions.js
website/content/docs/agent/index.mdx
website/content/docs/connect/proxies/built-in.mdx
website/content/docs/connect/proxies/managed-deprecated.mdx
website/content/docs/connect/registration/service-registration.mdx
website/content/docs/dynamic-app-config/kv.mdx
website/content/docs/k8s/helm.mdx
website/content/docs/k8s/installation/install.mdx

HashiCorp voice, style, and language guidelines recommend avoiding ableist
language unless its reference to ability is accurate in a particular use.
Changes were not made to:
- Any file in `/vendor`
- Any package manager dependency file (e.g., funnily enough, there's a `sane` package used in the repo)
Changes were only needed to comments, not code (e.g., variable names).

Replace use of 'sane' where appropriate

---

ui/packages/consul-ui/.docfy-config.js
ui/packages/consul-ui/app/components/buttons/index.scss
ui/packages/consul-ui/app/components/buttons/layout.scss
ui/packages/consul-ui/app/components/buttons/skin.scss
ui/packages/consul-ui/app/components/copy-button/README.mdx
ui/packages/consul-ui/app/components/copy-button/index.hbs
ui/packages/consul-ui/app/components/copy-button/index.js
ui/packages/consul-ui/app/components/copy-button/index.scss
ui/packages/consul-ui/app/components/copy-button/layout.scss
ui/packages/consul-ui/app/components/copy-button/skin.scss
ui/packages/consul-ui/app/modifiers/with-copyable.js
ui/packages/consul-ui/app/modifiers/with-copyable.mdx
ui/packages/consul-ui/app/services/clipboard/local-storage.js
ui/packages/consul-ui/app/services/clipboard/os.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/tests/acceptance/components/copy-button.feature
ui/packages/consul-ui/translations/components/copy-button/en-us.yaml

During https://github.com/hashicorp/consul/pull/10285 we noticed that our CopyButton needed a few tweaks, luckily we have also decided to update how this works slightly.
This PR refactors the copy-to-clipboard functionality out of our CopyButton component and into a 'non-visual' modifier where it probably belongs.
- [with-copyable](https://consul-ui-staging-defwazcw9-hashicorp.vercel.app/ui/docs/modifiers/with-copyable)
- [CopyButton](https://consul-ui-staging-defwazcw9-hashicorp.vercel.app/ui/docs/components/copy-button)
Benefits:
- We don't have to reuse our CopyButton component if we want a method of copying text that doesn't look the same as our CopyButton (design vs behaviour)
- Our CopyButton component (as it already uses our StateChart component to deal with behaviour/state) is now …

ui: CopyButton amends

---

ui/packages/consul-ui/app/components/definition-table/README.mdx
ui/packages/consul-ui/app/components/definition-table/debug.scss
ui/packages/consul-ui/app/components/definition-table/layout.scss
ui/packages/consul-ui/app/styles/debug.scss

Whilst working on https://github.com/hashicorp/consul/pull/10511 I noticed this:
(note the margin between the copy button and the texts)
This was introduced during https://github.com/hashicorp/consul/pull/10285, which we delayed from merging to 1.10.0 for this kind of reason.
This PR fixes this up in the same way as our `horizontal-kv-list`s work (there's potentially some sort of reusability here but its getting to that 'is it even worth DRYing this out' stage)
I took the opportunity here to add some documentation around this CSS component also.

ui: Fixup definition-table + copy-button margin

---

ui/packages/consul-ui/config/environment.js
ui/packages/consul-ui/config/utils.js
ui/packages/consul-ui/ember-cli-build.js

The rebuild of the Consul UI used very minimal ES6 features for 2 reasons:
1. Ember at the time felt very ES5-like (we started on Ember 2.18), to a certain extent there are still things in Ember that feel ES5-like (no real support for non-syntax related ES6 features like `Sets` and `Maps` in handlebars templates for example)
2. Using less layers makes things simpler in lots of subtle ways, for example we didn't even realize that we had sourcemaps disabled for such a long time before https://github.com/hashicorp/consul/pull/7651
We had a period of time that we were we started moving to use more ES6 style syntax, but pretty soon after that we reduced our browser support (https://github.com/hashicorp/consul/pull/9729) by not supporting anything older than ~2016. This brought us back to being …

ui: Allow disabling of sourcemaps via env var

---

ui/packages/consul-ui/app/instance-initializers/debug.js
ui/packages/consul-ui/app/instance-initializers/i18n.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/docs/bookmarklets.mdx
ui/packages/consul-ui/package.json
ui/yarn.lock

We made a few PRs lately just trying to make our UI documentation and overall UI DX better. Having good documentation and developer experience make it much for myself and others to add new features to the UI.
Back in https://github.com/hashicorp/consul/pull/9399 we added `ember-intl` we've started slowly adding i18n support throughout the app. We don't translate anything just now at least, but its general good practice to externalize all of this copy so its easy for others to find and edit.
This PR adds a couple of debug utilities to help us to continue doing this:
1. We've added a `CONSUL_INTL_DEBUG` env/cookie variable to turn off variable interpolation within the `t` helper so you can see which variables are being interpolated.
2. We've added a `CONSUL_INTL_LOCALE` env/cookie which …

ui: Add intl debug helpers

---

.changelog/10411.txt
agent/connect/ca/common.go
agent/connect/ca/provider_aws_test.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/connect/ca/testing.go
agent/connect_ca_endpoint.go
agent/connect_ca_endpoint_test.go
agent/consul/leader_connect_ca_test.go
agent/consul/server_connect.go
agent/consul/state/connect_ca_test.go
agent/xds/listeners.go

This is a manual cherry-pick of #10411

Format certificates properly (rfc7468) with a trailing new line (#10411)

---

website/content/docs/nia/configuration.mdx

Closes https://github.com/hashicorp/consul-terraform-sync/issues/314

nia/docs: deprecate driver.working_dir in preference for global working_dir

---

.changelog/10552.txt
agent/agent_test.go
agent/config/builder.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/connect/ca/provider_test.go
agent/connect/testing_ca.go
agent/connect_ca_endpoint_test.go
agent/consul/config.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/fsm/commands_oss_test.go
agent/consul/leader_connect_test.go
agent/consul/server_test.go
agent/consul/state/connect_ca_test.go
agent/structs/connect_ca.go
agent/structs/connect_ca_test.go
api/connect_ca.go
api/connect_ca_test.go
command/connect/ca/set/connect_ca_set_test.go
command/connect/ca/set/test-fixtures/ca_config.json
ui/packages/consul-ui/mock-api/v1/connect/ca/configuration
website/content/api-docs/connect/ca.mdx
website/content/docs/connect/ca/consul.mdx
website/content/docs/connect/ca/index.mdx
website/content/docs/k8s/connect/connect-ca-provider.mdx

This field was never used. Since it is persisted as part of a `map[string]interface{}` it is pretty easy to remove it. We use mapstructure to decode this map into a struct, and we don't set `ErrorUnused=true`, so any unexpected keys in the map will be ignored.

ca: remove unused RotationPeriod field

---

.changelog/10559.txt
agent/operator_endpoint.go
agent/operator_endpoint_test.go
api/operator_autopilot.go

Closes #10558
Previously, for a POST request to the /v1/operator/autopilot/configuration
endpoint, any fields not included in the payload were set to a zero-initialized
value rather than the documented default value.
Now, if an optional field is not included in the payload, it will be set to its
documented default value:
```
- CleanupDeadServers:      true
- LastContactThreshold:    "200ms"
- MaxTrailingLogs:         250
- MinQuorum:               0
- ServerStabilizationTime: "10s"
- RedundancyZoneTag:       ""
- DisableUpgradeMigration: false
- UpgradeVersionTag:       ""
```

Fix defaults for autopilot config update

---

ui/packages/consul-ui/app/instance-initializers/debug.js
ui/packages/consul-ui/app/instance-initializers/i18n.js
ui/packages/consul-ui/app/utils/get-environment.js
ui/packages/consul-ui/docs/bookmarklets.mdx
ui/packages/consul-ui/package.json
ui/yarn.lock

This commit adds a couple of debug utilities to help us to continue slowly adding i18n support:
- We've added a CONSUL_INTL_DEBUG env/cookie variable to turn off variable interpolation within the t helper so you can see which variables are being interpolated.
- We've added a CONSUL_INTL_LOCALE env/cookie which currently supports two 'pseudo-locales' - la-fk (fake latin) and - (just dashes) either of which will make it easier to see what has not been localized until we can add prettier rules to prevent adding any copy into templates at all. I would guess if we ever translated the app we would use this for looking at things whilst developing also - but as yet I've not adding anything for that here seeing as we don't translate anything.
Both variables are dev-time only and all code for this …

ui: [Backport 1.10.x] Add intl debug helpers #10513

---

website/content/docs/connect/transparent-proxy.mdx
website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

When Transparent Proxy is turned on, a service in one Kubernetes cluster must dial a service in a different Kubernetes cluster using explicit upstreams. KubeDNS is not supported, so the explicit upstream annotation must be utilized.

docs: Update docs to reflect limitation in TProxy when using single Consul DC deployment with multiple k8s clusters

---

website/content/docs/enterprise/license/faq.mdx

This PR changes the faq license page title to align with the same title used for Nomad and Vault

docs: changing license faq title to align with Nomad and Vault faq pages

---

api/api_test.go
api/watch/funcs_test.go
command/connect/redirecttraffic/redirect_traffic_test.go

For cases where `go test -short` is used to invoke tests, we want to skip those that involve invoking the `consul` binary. 
Fixes #10575.

tests: skip cases that depend on test server when -short flag set

---

agent/agent.go
agent/consul/auto_config_endpoint_test.go
agent/consul/auto_encrypt_endpoint_test.go
agent/consul/client_test.go
agent/consul/config.go
agent/consul/rpc_test.go
agent/consul/server.go
agent/consul/server_serf.go
agent/consul/server_test.go
agent/consul/subscribe_backend_test.go

`tlsutil.Config` already presents an excellent structure for this configuration. Copying the `RuntimeConfig` fields to `agent/consul.Config` makes code harder to trace, and provides no advantage.
Instead of copying the fields around, use the `tlsutil.Config` struct directly.
This is one small step in removing the many layers of duplicate configuration.

config: remove duplicate tlsutil.Config fields from agent/consul.Config

---

website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx

The service account was typo'd and needs to be fixed
The documentation will not work to actually demo the mesh working unless this is changed.

Fixed a typo that broke the example static-server deployment

---

website/content/docs/agent/options.mdx

This PR makes two changes to the public user documentation for Agent TLS.
1. fixes our example of "TLS configuration" to actually enable TLS.
2. moves all of the related TLS configuration together into a section, and adds a paragraph to explain how these settings are applied.

docs: Improve TLS user documentation

---

.changelog/10564.txt
command/connect/redirecttraffic/redirect_traffic.go
sdk/iptables/iptables.go
sdk/iptables/iptables_executor_linux.go
sdk/iptables/iptables_executor_unsupported.go
website/content/commands/connect/redirect-traffic.mdx

This PR proposes to apply traffic redirection rules in a given Linux network namespace:
- The `iptables` SDK package now accepts `NetNS` configuration which should point to the path of the network namespace.
- The `redirect-traffic` command accepts `netns` flag with the same.
**Note:** I did not find a meaningful enough way to unit test this change since it's just wrapping every `iptables` command with a call to `nsenter`, and that's why there aren't tests added. I did test it manually on a VM:
```
root@test2:/home/irynashustava# ip netns add foo
root@test2:/home/irynashustava# ip netns
foo
root@test2:/home/irynashustava# ./consul connect redirect-traffic -netns=/var/run/netns/foo -proxy-uid=1234 -proxy-inbound-port=15001
Successfully applied traffic redirection rules …
```

cli/sdk: Allow applying redirect-traffic rules in a provided Linux namespace

---

.changelog/10331.txt
GNUmakefile
agent/connect/ca/provider_vault.go
agent/consul/connect_ca_endpoint_test.go

connect/ca: require new vault mount points when updating the key type/bits for the vault connect CA provider

---

website/content/docs/security/acl/acl-legacy.mdx

Add link in deprecation notice to Learn guide on migrating ACL tokens.

docs: Add link to learn guide on migrating ACL tokens

---

.changelog/10569.txt
ui/packages/consul-ui/app/components/app-view/index.hbs
ui/packages/consul-ui/app/locations/fsm-with-optional.js
ui/packages/consul-ui/tests/acceptance/dc/kvs/create.feature

In https://github.com/hashicorp/consul/pull/10212 we made a fairly significant change to how our routing for namespaces works, with an eye to supporting a future feature of the UI (more details on that PR)
We based the majority of that work on code already existing in the ember framework but noticed that our app would slightly inconsistently use the some of the code in here, which meant it was possible to set empty URL segments in URLs for example `/kv/folder-name//create` (the URL for creating a new KV within the `folder-name` folder).
Ember seems to generally strips these, and whilst I've not looked too far into it as yet, this wasn't happening previous to the above PR.
https://github.com/emberjs/ember.js/blob/297ab0e771409d61dcb014a9a40144cd7fdd5ee8/packages/%40ember/-internals/routing/ …

ui: [BUGFIX] Ensure in-folder KVs are created in the correct folder

---

.changelog/10604.txt
ui/packages/consul-ui/app/abilities/acl.js
ui/packages/consul-ui/app/components/app-view/index.hbs
ui/packages/consul-ui/app/router.js
ui/packages/consul-ui/tests/acceptance/dc/acls/access.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/acls/access-steps.js
ui/packages/consul-ui/tests/helpers/set-cookies.js
ui/packages/consul-ui/tests/steps/doubles/model.js

With ACLs disabled:
Before:
After:
Fixes #10591 
Extra note here. Out testing mostly runs everything with ACLs enabled, so we had to do a little bit of gymnastics to disable ACLs just for this test, which is also related to work going on elsewhere, got me thinking we might want to shuffle this around a little at some point. Not an urgent thing in the slightest, it's been fine for a number of years and has held up pretty well, but seeing as its a good few years old now and we have a better picture it could be an area we might want to tweak at some point.

ui: Show the correct 'ACLs Disabled' page when ACLs are disabled

---

.changelog/10605.txt
ui/packages/consul-ui/app/instance-initializers/ivy-codemirror.js
ui/packages/consul-ui/lib/startup/templates/body.html.js
ui/packages/consul-ui/vendor/init.js

Only whilst testing in/using the Consul binary itself, we unfortunately broke our runtime optional javascript loading. As a consequence of this, the KV editor would not load in the different user configurable syntax highlighting files on demand. 
Additionally, we use browser polyfills, but we only load these dynamically if the user is using a browser that requires them, saving on the downloaded payload (more on this to come)
Our JS framework includes URL fingerprinting features to enable 'cache busting' for downloaded assets for when the contents of a file changes. The idea here is, across different versions of Consul, if a file doesn't change, then the user won't have to re-download the file as it will have been cached. If we change the contents of a file then the fingerprint changes and …

ui: [BUGFIX] Fix KV Code Editor syntax loading

---

contributing/config/README.md

Building on #10281
[Preview](https://github.com/hashicorp/consul/tree/dnephin/contrib-docs-config/contributing/config).
Adds some developer docs for agent configuration. There aren't many details about auto-config, but hopefully the links to the source are a reasonable start.

contrib: add first draft of agent configuration docs

---

.changelog/10608.txt
ui/packages/consul-ui/app/adapters/permission.js
ui/packages/consul-ui/app/routes/dc.js
ui/packages/consul-ui/app/routes/settings.js
ui/packages/consul-ui/app/services/repository/permission.js

Previously when namespaces were enabled, we weren't requesting permission for the actively selected namespace, and instead always checking the permissions for the default namespace.
This PR ensures we request permissions for the actively selected namespace.
Notes:
All of the UI/API reading interaction uses a GET request with`?ns=` to specify the namespace, we have one API request which requires a POST with the request body containing the `Namespace`. This is so we can request various pieces of information required for the UI using a method we can customise for exactly what we need (there are more details in the comments in the changeset here). Unfortunately we were passing through a `nspace` parameter instead of a `ns` parameter which is the param name we are expecting deeper down, pretty …

ui: [BUGFIX] Ensure we use the ns query param name when requesting permissions

---

website/content/docs/agent/options.mdx

Follow up to #10588
Adds the version when these settings will be deprecated.

docs: add deprecation version for ports.grpc settings

---

website/content/docs/agent/options.mdx

While looking at the code with @Kedevlin we noticed these two config fields were missing from our configuration reference doc. Both of these seem like they would be useful, so this PR adds them to the docs.
https://github.com/hashicorp/consul/pull/128 added pid_file
https://github.com/hashicorp/consul/pull/1331 added disable_coordinates

docs: add config options that were missing

---

agent/config/builder.go
agent/config/builder_test.go
agent/config/runtime_test.go

This PR finishes the work started in #9448, #9451, and #9452
Remove `Builder.BuildAndValidate` and unexport `Build` and `Validate` to reduce the config interface a single `Load` function.
The last remaining test was converted to use `Load` instead of `BuildAndValidate` by adding another `shim` to the options struct.

config: unexport the remaining builder methods

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/index.mdx

New `task.terraform_version` option [link](https://consul-cw4924rvj-hashicorp.vercel.app/docs/nia/configuration#terraform_version)
Network Drivers config section [link](https://consul-cw4924rvj-hashicorp.vercel.app/docs/nia/configuration#network-drivers)
Terraform Cloud driver config section [link](https://consul-cw4924rvj-hashicorp.vercel.app/docs/nia/configuration#terraform-cloud-driver)
Enterprise callout SS

docs/nia: Add Terraform Cloud driver config with callout to TFE only

---

.changelog/10009.txt
agent/dns.go
agent/dns_test.go

Fixes #9945
This PR refactors parts of the `DNSServer` to allow us to set the response code and trim the response in a single place. This fixes the problem of the DNS response exceeding the max size.
I notice we never called trim in `handlePtr` or `handleRecurse`. I wonder if we should be.
TODO:

dns: properly trim response when EDNS is used

---

agent/agent_test.go
agent/consul/acl_test.go
agent/consul/leader_connect_test.go
agent/http_test.go
agent/service_manager_test.go
agent/testagent.go
go.mod
go.sum
lib/routine/routine.go
vendor/github.com/hashicorp/serf/serf/serf.go
vendor/modules.txt

Related to #8329
Fixes #9458
These commits are extracted from #10341. There's still a lot more work required to properly solve #9457 (ex: https://github.com/hashicorp/memberlist/pull/238), so I'd like to get some of the data race fixes merged to prevent them from rotting, and so that contributors can run the race detector locally with much less noise.

Fix some data races

---

.changelog/10009.txt
agent/dns.go
agent/dns_test.go

Backport of  #10009 to 1.8.x. I had to also backport #9004 to prevent merge conflicts.

[1.8.x] dns: properly trim response when EDNS is used

---

website/content/docs/security/acl/acl-rules.mdx
website/content/docs/security/acl/acl-system.mdx

Adds mention of `intentions` rules to ACL System and ACL Rules pages.
Resolves #9790

docs: Add intentions to ACL System docs

---

website/redirects.next.js

Fix an issue where [/docs/k8s/operations/tls-on-existing-cluster](https://www.consul.io/docs/k8s/operations/tls-on-existing-cluster) would never load when navigating directly to the URL because of a circular redirect.

website: Fix circular redirect with TLS on existing cluster

---

.changelog/10647.txt
agent/service_manager.go
agent/service_manager_test.go

If multiple instances of a service are co-located on the same node then
their proxies will all share a cache entry for their resolved service
configuration. This is because the cache key contains the name of the
watched service but does not take into account the ID of the watching
proxies.
This means that there will be multiple agent service manager watches
that can wake up on the same cache update. These watchers then
concurrently modify the value in the cache when merging the resolved
config into the local proxy definitions.
To avoid this concurrent map write we will only delete the key from
opaque config in the local proxy definition after the merge, rather
than from the cached value before the merge.
Fixes #10636

Avoid panic on concurrent writes to cached service config map

---

README.md

I checked a couple more of our repos before doing this.
- Vault: Don't seem to refer to either in the README
- Boundary: Don't seem to refer to either in the README
- Nomad: Uses `macOS`
- Vagrant: Uses `Mac OS X`
All in all, feels like its time to make this change for us?

docs: Refer to macOS vs Mac OS X in the main README

---

website/content/api-docs/session.mdx

Update output for /v1/session/ endpoints to match output post Consul 1.7.0.
Documents new `NodeChecks` and `ServiceChecks` parameters which were added in that release.
Resolves #7341, resolves #10095

docs: Update responses for /v1/session/ endpoints post 1.7

---

command/connect/envoy/envoy.go

Update help text of `consul connect envoy` command to mention the ability to provide pass-through options.

cli: Document pass-through option for `consul connect envoy`

---

website/content/api-docs/agent/service.mdx

Document supported namespace parameters for /agent/service* API endpoints.
Resolves #9710

docs: Add namespace parameters to /agent/service* endpoints

---

.changelog/10657.txt
agent/consul/state/connect_ca.go
agent/consul/state/connect_ca_test.go

This is a manual cherry-pick of #10657  to 1.9.x
- CONFLICT (content): Merge conflict in agent/consul/state/connect_ca_test.go
- CONFLICT (content): Merge conflict in agent/consul/state/connect_ca.go
* return an error when the index is not valid
* check response as bool when applying `CAOpSetConfig`
* remove check for bool response
* fix error message and add check to test
* fix comment
* add changelog

config raft apply silent error (#10657)

---

.changelog/10689.txt
agent/proxycfg/state.go

Knowing that blocking queries are firing does not provide much
information on its own. If we know the correlation IDs we can
piece together which parts of the snapshot have been populated.
Some of these responses might be empty from the blocking
query timing out. But if they're returning quickly I think we
can reasonably assume they contain data.

Log the correlation ID when blocking queries fire

---

website/content/docs/connect/ca/vault.mdx

Folks using Vault as a Connected CA with Consul, and using these instructions https://www.consul.io/docs/connect/ca/vault#vault-acl-policies found that besides the Vault Managed PKI Paths mentioned in there they had to add the following
```
path "auth/token/renew-self" {
capabilities = ["update"]
}
path "auth/token/lookup-self" {
capabilities = ["read"]
}
```
Suggestion is to add those in the page or mention this somewhere in the docs

docs: Vault as a Connected CA with Consul missing Managed PKI Paths

---

website/content/commands/kv/import.mdx

Add a sentence stating the version of Consul that introduced the `-prefix` option for `consul kv import`.
Resolves #10172

docs: Add version callout for `kv import -prefix`

---

agent/consul/leader_connect_test.go

Aims to address this failure:
https://app.circleci.com/pipelines/github/hashicorp/consul/20339/workflows/dcdee545-794f-4a80-8d42-f359b79fdd4f/jobs/412315/tests#failed-test-0
Failing assertion:
https://github.com/hashicorp/consul/blob/766d62e4918050d7576f530daa2eb50c32cab251/agent/consul/leader_connect_test.go#L494
Relevant log:
> TestLeader_SecondaryCA_IntermediateRefresh-node-377.server.connect: pruning old unused root CA: <id>
This test ran after TestLeader_CARootPruning, which sets the pruning interval to 200ms. Since it is set to run in parallel, there could have been a long enough delay between setting and reading the CA config to trigger a prune.

Reset root prune interval after TestLeader_CARootPruning completes

---

.changelog/10399.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/http.go
agent/http_register.go
agent/setup.go
api/agent.go
command/debug/debug.go
command/debug/debug_test.go
go.mod
go.sum

Related to #10320
Tested by running a dev agent and collecting a `consul debug` archive. All the metrics are indent formatted in the `metrics.json`.
TODO:

debug: use the new metrics stream in debug command

---

.github/CONTRIBUTING.md

Useful for contributors to check their work-in-progress by running only the tests which they expect to be affected by their changes, as the full test suite can take several minutes to execute.

Describe how to run a subset of all unit tests

---

.changelog/10706.txt
ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs

**🐛 Issue**: New intentions form - `Source Namespace` and `Destination Namespace` drop-downs have options duplicated with onChange action. Issue reported in #10686.
**🩹  Solution**: Update `onChange` action to mutate to the selected option. This is following the [usage documentation](https://github.com/cibernox/ember-power-select-with-create#usage) for `ember-power-select-with-create` package. 
**Screenshots:**
- Before
- After
Tests: ❌

ui: Fix dropdown option duplications

---

website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/installation/deployment-configurations/consul-enterprise.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx
website/content/docs/security/acl/auth-methods/oidc.mdx

The base64 CLI utility has two different short flag arguments for decode depending on the platform: [-D](https://www.unix.com/man-page/osx/1/base64/) and [-d](https://linux.die.net/man/1/base64).
Previously, the docs used the -D flag exclusively with the base64 utility. Luckily, the long form of the flag is the same across platforms: --decode.
All uses of the base64 -D flag have been replaced with --decode. Said uses were identified with grep:

Generalize base64 command usage in docs

---

.changelog/10707.txt
agent/agent.go
agent/config/runtime.go
agent/http.go
agent/rpcclient/health/health.go
agent/rpcclient/health/health_test.go

This PR fixes two problems:
1. the HTTP API would log cancelled requests as an error
2. the health endpoint, with the streaming backend, did not set the default timeout that was used with the blocking query backend

streaming: set default query timeout

---

website/content/docs/agent/options.mdx

This language is loosely based on some language from [Consul's Learn guide about enablingTLS](https://learn.hashicorp.com/tutorials/consul/tls-encryption-secure#initialize-the-built-in-ca). 
The goal is to provide some more information about the security implications of these configuration settings.

docs: give better guidance about how to configure the agent TLS CA

---

.circleci/scripts/cherry-picker.sh

To fix a failure in our docs-cherrypick automation. This started to fail today, I suspect because
github silently changed the order the labels were being returned, and by default it only
returns 30 labels.
We currently have 68 labels, so using per_page=100 (the maximum allowed) we should be able to fix
this failure.
Relevant API docs: https://docs.github.com/en/rest/reference/issues#list-labels-for-a-repository
I tested the commands from this script locally, and this change appears to fix the problem

ci: query for max number of possible labels

---

.changelog/10732.txt
agent/config/config.go
website/content/docs/agent/options.mdx

Consul Enterprise is adding the ability to configure the permission mode for audit logs. This PR contains the necessary OSS modifications to allow that to work, and associated documentation updates.

Add OSS bits for specifying audit log permission mode

---

.changelog/10691.txt
api/agent.go
api/agent_test.go

This PR adds support for setting QueryOptions on the following agent API endpoints:
- /agent/service/maintenance
- /agent/health/service/name/:name
- /agent/health/service/id/:id
This follows the same pattern used in #9903 to support query options for other agent API endpoints.
Resolves #9710

api: enable query opts on agent health and maintenance endpoints

---

agent/acl.go
agent/acl_endpoint.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/connect_ca_endpoint.go
agent/consul/discovery_chain_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/snapshot_endpoint.go
agent/http.go
agent/structs/intention.go
agent/xds/server.go
api/agent_test.go
command/maint/maint_test.go

As part of the discussion in [#10399](https://github.com/hashicorp/consul/pull/10399#discussion_r670020574), we thought that we could clean up the main token resolution API to return a non-nil value for the case where ACLs are disabled so that users don't need to do counter-intuitive nil checks on the result.
By changing this API, we had to update a few cases that were making assumptions out of the `nil` return. I think this makes more sense and cleans up the code ever so slightly. Curious if others agree. 
Note: the primary change is the one in `agent/consul/acl.go` -- everything else is fallout.

acls: Update ACL authorizer to return meaningful permission when ACLs are disabled

---

.changelog/10735.txt
ui/packages/consul-ui/app/components/composite-row/layout.scss
ui/packages/consul-ui/app/components/consul/token/list/index.hbs
ui/packages/consul-ui/app/models/token.js
ui/packages/consul-ui/mock-api/v1/acl/tokens
ui/packages/consul-ui/translations/common/en-us.yaml
ui/packages/consul-ui/translations/components/consul/en-us.yaml

Adds a copy button to each composite row in tokens list page, if Secret ID returns an actual ID. 
Reuses the [CopyButton](https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/app/components/copy-button/README.mdx) component and some conditional logic to flag Secret ID returning an empty string or `'<hidden>'`.
Adds secretID as a common consul translation.
Note: The styling changes did not impact the other composite rows with actions.
[Demo Link](https://consul-ui-staging-jbjn83adm-hashicorp.vercel.app/ui/dc1/acls/tokens#CONSUL_ACLS_ENABLE=1
)
Implemented in #10546.
In the backend, user permission are checked. 
If the user has the correct permission then the SecretID attribute returns an actual ID. 
If the user does not have the correct permissions `'<hiddlen>'` is returned. …

ui: Add copy button for Secret ID in Tokens list page

---

website/content/api-docs/agent/index.mdx

Document /v1/agent/host endpoint which is used by `consul debug`. Originally added in #4754.

docs: Add /v1/agent/host endpoint

---

website/content/api-docs/agent/check.mdx
website/content/api-docs/agent/connect.mdx
website/content/api-docs/discovery-chain.mdx

Document the namespace parameter can be specified on HTTP Check, Connect CA leaf, and Discovery Chain API endpoints.

docs: Add namespace parameter to additional HTTP endpoints

---

website/redirects.next.js

Add redirect [/docs/connect/ingress-gateways](https://www.consul.io/docs/connect/ingress-gateways), which currently returns
404, to [/docs/connect/gateways/ingress-gateway](https://www.consul.io/docs/connect/gateways/ingress-gateway).
Fixes #10748

website: Add redirect for /connect/ingress-gateways

---

website/content/commands/connect/envoy.mdx
website/content/commands/connect/proxy.mdx

Document the ability to specify `-sidecar-for` and `-proxy-id` flags via environment variables.
These environment variables have been supported for `consul connect proxy` since Connect was introduced in 1.2.0.
Support was added for using these variables with `consul connect envoy` in Consul 1.8.0 with PR #7498.

docs: Document supported `consul connect` env vars

---

website/content/docs/connect/config-entries/service-defaults.mdx

Add a note to the docs for the service defaults config entry which informs users that the service protocol can be configured for all services using the proxy defaults config entry.
Resolves #8279

docs: Note proxy-defaults can globally set service protocol

---

website/content/api-docs/libraries-and-sdks.mdx

The Verizon repository for the Helm Scala client for Consul is no longer actively maintained, but the people from the team that created the library at Verizon have forked it to their `getnelson` repo. This PR updates the link.
The library has not been super well maintained so hopefully with a corrected link it'll gain more adoption.

Update Helm SDK link

---

website/content/api-docs/session.mdx

The ServiceChecks parameter was incorrectly documented in e515c9d44 to state that it accepted a list of string values, when actually the API requires an array of ServiceCheck objects.
This commit updates the docs for the parameter to correctly reflect the fields required by the API.
Resolves #10752

docs: Fix service checks docs on session endpoint

---

website/content/docs/agent/options.mdx

add service config link to description of enable_central_service_config.

docs: link to config entries from enable_central_service_config

---

.changelog/10767.txt
ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
ui/packages/consul-ui/app/models/session.js
ui/packages/consul-ui/mock-api/v1/session/info/_

Resolves #10754. The `ServiceChecks` attribute formatting was outdated in the Lock Session endpoint API docs and in the UI mock data.
[Demo Link](https://consul-ui-staging-ioqavlpji-hashicorp.vercel.app/ui/dc1/kv/0-key-value/edit)
- API Docs were updated in #10759 . 
- UI mock data is update in this PR to match the [update docs](https://www.consul.io/api-docs/session#servicechecks).
- We grab all "ID" values from ServiceChecks objects and merged them with the [NodeChecks array](https://www.consul.io/api-docs/session#nodechecks). NodeChecks and ServiceChecks will unlikely have the same name, but if they do we will display them all.
Before:
After:
No additional testing. This change was not about integration, but on reading the response properly.

ui: Fix Health Checks in K/V form Lock Sessions Info section

---

.changelog/10675.txt
agent/consul/fsm/commands_oss.go

This fix the index passed to the state when performing op `CAOpSetRootsAndConfig`

fix state index for `CAOpSetRootsAndConfig` op

---

website/content/docs/connect/proxies/integrate.mdx

This PR improves the organization and readability of the Custom Proxy Integration documentation.  It also addresses usage that is not compliant with HashiCorp writing style guides.

general language and readability improvements to proxy integration docs

---

agent/acl.go
agent/acl_endpoint.go
agent/acl_test.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/connect_auth.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/internal_endpoint.go
agent/consul/kvs_endpoint.go
agent/rpc/subscribe/subscribe.go
agent/structs/intention.go
command/acl/bindingrule/read/bindingrule_read.go

Follow up to #10632
Remove more of the `authz == nil` checks now that resolving a token should never return a `nil`. There are a few more `auth != nil` checks to handle, but I'll do that in another PR to keep the diff small.
Also cleans up some agent methods that were only used by tests.

acl: remove authz == nil checks

---

agent/agent_endpoint.go
agent/connect_auth.go
agent/consul/catalog_endpoint.go
agent/consul/config_endpoint.go
agent/consul/coordinate_endpoint.go
agent/consul/health_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/kvs_endpoint.go
agent/consul/session_endpoint.go
agent/consul/txn_endpoint.go
agent/event_endpoint.go
agent/ui_endpoint.go

Branched from #10737, this PR continues the work from #10632
This diff is larger because it removes some checks that were around larger blocks of code. You can use [hide whitespace changes](https://github.com/hashicorp/consul/pull/10738/files?diff=split&w=1) to reduce the diff significantly.
There is one last remaining `authz != nil` check here: https://github.com/hashicorp/consul/blob/v1.10.1/agent/consul/acl.go#L1239-L1241
That one has to remain because it can be `nil` in OSS. Since this is internal to the "ACL system" it seems like a reasonable exception. We could probably change it to use a new `acl.DefaultAll` authorizer, but I'm not sure its worth it for this one small case.

acl: remove the last of the authz == nil checks

---

.changelog/10630.txt
agent/consul/leader_connect_ca.go

defer setting the state before returning to avoid  stuck in `INITIALIZING` state

---

agent/consul/leader_metrics.go

Branched from #10768
Closes #9891
Adds a warning log when any of the monitored certificates are within 1 day of expiration. Ideally the metrics should be used to monitor the expiration, but these logs will help in case the metrics are not being monitored correctly.

telemetry: add log message when certs are about to expire

---

agent/consul/acl.go
agent/consul/acl_client.go
agent/consul/acl_endpoint.go
agent/consul/acl_server.go
agent/consul/acl_test.go
agent/consul/catalog_endpoint.go
agent/consul/intention_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/session_endpoint.go

Branched from #10742
Best viewed by individual commit. There is more context in the commit messages.
This PR is another small incremental step toward two goals: making the ACL system easier to understand (by making it easier to trace the code), and making the code easier to change (by improving the structure). No structural changes yet, but these small changes will make it easier to move `ACLResolver` out of the `agent/consul` package.

acl: decouple filtering from ACLResolver and remove a couple methods

---

.changelog/10798.txt
agent/consul/acl.go
agent/consul/catalog_endpoint.go
agent/consul/txn_endpoint.go

Backport of the bugfix commit from #10793

[1.10.x] acl: fix txn_endpoint to properly authorize service registrations

---

CHANGELOG.md

Open to suggestions on improving this language, but hope this captures the issue well enough.
_meta note:_ should we add a `known-issue` type to https://github.com/hashicorp/consul/blob/main/.changelog/changelog.tmpl? thinking that would mostly make sense if we intend to sometimes ship releases with known issues (such as incomplete/preview features) but not if we're just adding notes like this post-release

changelog: add KNOWN ISSUES note for streaming with mesh gateways

---

.changelog/10612.txt
agent/consul/acl_replication.go
agent/consul/acl_replication_test.go
agent/consul/leader.go
agent/structs/acl.go
api/acl.go

This PR adds the new field `LastErrorMessage` to the `ACLReplicationStatus` endpoint. Whenever the Goroutine executing the `runACLReplicator` encounters an error, both `LastError` and `LastErrorMessage` field in the endpoint are updated. 
Test `TestACLReplication_TokensRedacted` is updated to check also the `LastErrorMessage` field.
Fixes #10521.

acl: acl replication routine to report the last error message

---

.changelog/10795.txt
command/watch/watch.go

Replace call to /agent/self with /status/leader to verify agent reachability before initializing a watch. This endpoint is not guarded by ACLs, and as such can be queried by any unauthenticated API client.
Fixes #9353

cli: Test API access using /status/leader in consul watch

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/enterprise/index.mdx
website/content/docs/nia/enterprise/license.mdx
website/content/docs/nia/license.mdx
website/data/docs-nav-data.json

Update links:
- [preview license_path config](https://consul-o9m20q4gc-hashicorp.vercel.app/docs/nia/configuration#license_path)
- [preview licensing page](https://consul-o9m20q4gc-hashicorp.vercel.app/docs/nia/enterprise/license)
- [preview enterprise overview page](https://consul-o9m20q4gc-hashicorp.vercel.app/docs/nia/enterprise)

docs/nia: add CTS enterprise license information

---

.changelog/10757.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go

Configure the self_admin cluster to use the admin bind address provided when starting Envoy.
Fixes #10747

cli: Use admin bind address in self_admin cluster

---

.changelog/10757.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go

Backport of #10757 to 1.9.x.
Configure the self_admin cluster to use the admin bind address provided when starting Envoy.
Fixes #10747

[1.9.x] cli: Use admin bind address in self_admin cluster (#10757)

---

.changelog/10820.txt
command/kv/imp/kv_import.go

Consul 1.10 (PR #9792) introduced the ability to specify a prefix when importing KV's. This however introduced a regression on Windows systems which breaks `kv import`. The key name is joined with specified`-prefix` using `filepath.Join()` which uses a forward slash (/) to delimit values on Unix-based systems, and a backslash (\) to delimit values on Windows – the latter of which is incompatible with Consul KV paths.
This commit replaces filepath.Join() with path.Join() which uses a forward slash as the delimiter, providing consistent key join behavior across supported operating systems.
Fixes #10583
**Note**: No additional tests were added in this commit because the existing tests would have caught this error if they had been run on Windows.

cli: Fix broken KV import on Windows

---

website/content/api-docs/config.mdx
website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/config-entries/mesh.mdx
website/content/docs/connect/config-entries/proxy-defaults.mdx
website/content/docs/connect/config-entries/service-defaults.mdx
website/content/docs/connect/config-entries/service-intentions.mdx
website/content/docs/connect/config-entries/service-resolver.mdx
website/content/docs/connect/config-entries/service-router.mdx
website/content/docs/connect/config-entries/service-splitter.mdx
website/content/docs/connect/config-entries/terminating-gateway.mdx

This commit adds example JSON configs for several config entry resources were missing examples in this language.
The examples have also been updated to use the new CodeTabs resource instead of the Tab component.
The changes can be previewed here https://consul-fb7xuafv0-hashicorp.vercel.app/docs/connect/config-entries.

docs: Add JSON examples to all config entries

---

.changelog/10757.txt
command/connect/envoy/bootstrap_config.go
command/connect/envoy/bootstrap_config_test.go

Backport of #10757 to 1.8.x.
Configure the self_admin cluster to use the admin bind address provided when starting Envoy.
Fixes #10747

[1.8.x] cli: Use admin bind address in self_admin cluster (#10757)

---

website/content/docs/connect/config-entries/ingress-gateway.mdx

This was necessary in older versions of Consul, but was obsoleted by
making Consul add the port number itself when constructing the Envoy
configuration.
https://github.com/hashicorp/consul/pull/8190 is the PR that fixed this issue.

docs: remove note on ingress gateway hosts field needing a port number

---

contributing/service-discovery/README.md
contributing/service-discovery/health-checks.md

Add the list of 6 entrypoints for registering a check. The hope is that this list acts as kind of a checklist for reviewing or modifying health checks, to prevent bugs like #7566.
[Preview](https://github.com/hashicorp/consul/blob/dnephin/contrib-check-register-flows/contributing/service-discovery/health-checks.md)

contrib: add list of check register flows

---

.changelog/10758.txt
agent/agent_endpoint.go
api/agent.go
api/agent_test.go
api/catalog_test.go
command/services/register/register.go
website/content/commands/services/register.mdx

Fix missed code to support unix domain sockets over command line. Also fixed error in rendering in services API.

Fixup to support unix domain socket via command line

---

.changelog/10813.txt
agent/grpc/internal/testservice/simple.pb.go
go.mod
go.sum
proto/pbacl/acl.pb.go
proto/pbautoconf/auto_config.pb.go
proto/pbcommon/common.pb.go
proto/pbconfig/config.pb.go
proto/pbconnect/connect.pb.go
proto/pbservice/healthcheck.pb.go
proto/pbservice/node.pb.go
proto/pbservice/service.pb.go
proto/pbsubscribe/subscribe.pb.go

Bump to the latest release of gogo/protobuf.
Longer term plan is still removing this dep and switching back to mainline google/protobuf as described in https://github.com/hashicorp/consul/issues/10471, but we should at least move to the latest release before doing that.

deps: upgrade gogo-protobuf to v1.3.2

---

.changelog/10824.txt
agent/agent.go
agent/proxycfg/manager.go
agent/proxycfg/manager_test.go

Fixes #10714
May also fix #10821, but maybe there are other improvements to make there, waiting on confirmation.
Use the agent token in `proxycfg.Manager` as a default when no token is provided by the registration.  This was broken in #10188.
TODO:

proxycfg: Use acl.tokens.default token as a default when there is no token in the registration

---

website/content/commands/connect/envoy.mdx
website/content/docs/connect/config-entries/ingress-gateway.mdx

Clarify the function of `-address` flag when instantiating an ingress gateway.
Resolves #9849

docs: Clarify ingress gateway's -address flag

---

.changelog/10824.txt
agent/agent.go
agent/proxycfg/manager.go
agent/proxycfg/manager_test.go

[1.8.x] Backport proxycfg: Use acl.tokens.default token as a default

---

agent/proxycfg/manager.go
agent/proxycfg/manager_test.go

#10824 was cherry-picked automatically into 1.9.x, but the code was incompatible, so the build failed.

[1.9.x] Fix the build

---

agent/proxycfg/manager_test.go

#10824 was cherry-picked automatically into 1.10.x, but the code was incompatible, so the build failed.

[1.10.x] Fix the build

---

website/content/docs/connect/security.mdx

Add a section to the Connect Security page which highlights the risks of exposing Envoy's administration interface outside of localhost.
Resolves #5692

Document possible risk w.r.t exposing the admin API in Envoy

---

.changelog/10835.txt
ui/packages/consul-ui/app/components/consul/source/README.mdx
ui/packages/consul-ui/app/components/consul/source/index.hbs
ui/packages/consul-ui/app/components/consul/source/index.scss
ui/packages/consul-ui/app/router.js
ui/packages/consul-ui/app/routes/dc/routing-config.js
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/templates/dc/routing-config.hbs
ui/packages/consul-ui/tests/acceptance/dc/routing-config.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/routing-config-steps.js
ui/packages/consul-ui/tests/pages.js
ui/packages/consul-ui/tests/pages/dc/routing-config.js
ui/packages/consul-ui/tests/unit/routes/dc/routing-config-test.js
ui/packages/consul-ui/translations/components/consul/en-us.yaml
ui/packages/consul-ui/translations/routes/en-us.yaml

This PR creates the Routing Configurations route and page.
Why: A routing configuration is not a real service. They are a routing configuration that route traffic to real services in Consul. For this reason we created a new route for routing-configs that does not follow the services `/dc/service/:name-of-service` pattern.
Changes:
- Created the new route `dc/routing-config/:name` and template for Routing Configurations. The Routing Config page will only show Discovery Chain. No other tabs/pages are expected to be added in the future.
- Create `Consul::Source` component. This is a component very similar to `Consul::Kind` . Consul uses the attribute Kind to describe Services, e.g. Terminating Gateway, Mesh Gateway, etc. Routing Configuration are not Services and so I create a new pill …

ui: Create Routing Configurations route and page

---

ui/packages/consul-ui/app/components/consul/intention/notice/permissions/index.hbs
ui/packages/consul-ui/translations/components/consul/en-us.yaml

This PR updates the wording in the L7 Permissions notice in the Intentions edit/create form. 
[Demo Link](https://consul-ui-staging-pru8uijja-hashicorp.vercel.app/ui/dc1/intentions/default:array-1:default:driver#CONSUL_ACLS_ENABLE=1)
Before:
After:
No backend changes required.
No updates to mock data.
No tests were updated.

ui: Update intention permissions notice wording

---

website/content/docs/agent/options.mdx

The current suggests the option expects a string of either "enabled" or "disabled" but this results in an error `'acl.enable_key_list_policy' expected type 'bool', got unconvertible type 'string', value: 'enabled'`. Setting to a boolean value resolves this, also had a quick look at the code (https://github.com/hashicorp/consul/blob/d2b58cd0d6e84f04eed08d233b8e8b396f6d7663/agent/config/runtime.go#L109) and it suggests this too

Update documentation for enable_key_list_policy

---

agent/acl.go
agent/acl_endpoint.go
agent/agent_endpoint.go
agent/consul/acl_endpoint_legacy.go
agent/consul/connect_ca_endpoint.go
agent/consul/discovery_chain_endpoint.go
agent/consul/federation_state_endpoint.go
agent/consul/internal_endpoint.go
agent/consul/operator_autopilot_endpoint.go
agent/consul/operator_raft_endpoint.go
agent/consul/prepared_query_endpoint.go
agent/consul/snapshot_endpoint.go
agent/consul/txn_endpoint.go
agent/http.go
agent/structs/config_entry_discoverychain.go
agent/xds/server.go

Follow up to https://github.com/hashicorp/consul/pull/10737#discussion_r682147950
Renames all variables for `acl.Authorizer` to use `authz`. Previously some places used `rule` which I believe was an old name carried over from the legacy ACL system.
A couple places also used `authorizer`.
This commit also removes another couple of authorizer nil checks that are no longer necessary.

acl: use authz consistently as the variable name for an acl.Authorizer

---

agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/consul/acl_endpoint_legacy.go
agent/consul/acl_endpoint_test.go
agent/http_register.go

acl: Remove legacy bootstrap and legacy translate rules API endpoints

---

agent/consul/fsm/commands_oss_test.go
agent/consul/fsm/snapshot_oss.go
agent/consul/internal_endpoint_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go
agent/consul/state/coordinate.go
agent/consul/state/coordinate_oss.go
agent/consul/state/coordinate_oss_test.go
agent/consul/state/coordinate_test.go
agent/consul/state/indexer.go
agent/consul/state/query.go
agent/consul/state/query_oss.go
agent/consul/state/schema_test.go
agent/consul/state/state_store_test.go
agent/consul/state/txn.go
agent/consul/state/txn_test.go
agent/rpc/subscribe/subscribe_test.go
agent/structs/structs.go
api/catalog_test.go
api/txn_test.go

Additionally:
- partitioned the catalog indexes appropriately for partitioning
- removed a stray reference to a non-existent index named "node.checks"

state: partition nodes and coordinates in the state store

---

agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_oss.go
agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_test.go
agent/consul/state/state_store_test.go
agent/consul/state/store_integration_test.go
agent/consul/stream/event.go
agent/consul/stream/event_publisher.go
agent/consul/stream/event_publisher_test.go
agent/consul/stream/event_test.go
agent/consul/stream/subscription.go

Chained off of https://github.com/hashicorp/consul/pull/10859
Also re-enabled some tests that had to be disabled in the prior PR.

state: adjust streaming event generation to account for partitioned nodes

---

.changelog/10804.txt
api/debug.go
command/commands_oss.go
command/debug/debug.go
command/debug/debug_test.go
command/registry.go
go.mod
go.sum
website/content/commands/debug.mdx

Related to #10320
Renames `cluster.json` to `members.json` to be more consistent with the API and internal method names we use for this data.
While working on this I noticed that handling of SIGINT was broken due to other changes we made for #10320. I fixed that problem by using a context, and changing the signal handler to cancel the context instead of only closing a channel.

debug: rename cluster.json -> members.json  and fix handling of Interrupt Signal

---

agent/xds/delta.go
agent/xds/server.go
contributing/service-mesh/README.md
contributing/service-mesh/xds.md

I learned recently how authorization works for xDS requests. Since I found it a bit surprising, I thought it would be good to document it in a couple places.

xds: document how authorization works

---

command/debug/debug.go
command/debug/debug_test.go

Branched from #10804
The unix timestamps that were used previously make the debug data a little bit more difficult to consume. By using human readable dates we can easily see when the profile data was collected.
Also moves `profile.prof`, `trace.out`, `consul.log`, and `metrics.json` out of the sub-directories. There is only one of each of these, so we can put them in the top-level directory.
Also improves the test coverage. Two test cases are removed and the assertions from those cases are moved to `TestDebugCommand`.
Now `TestDebugCommand` is able to validate the contents of all files. This change reduces the test runtime of the command/debug package by almost 50%, while also improving the test coverage by making much more strict assertions about the files and their contents.

debug: use human readable dates for filenames and improve the tests

---

website/content/docs/connect/transparent-proxy.mdx

It can only work if there is a running service instance in the local DC,
so this is quite misleading, since failover and redirects are typically
used when there is not an instance in the local DC.

doc: remove sentence that tproxy works cross-DC with config entries.

---

.changelog/10901.txt
ui/packages/consul-ui/app/components/token-source/index.hbs
ui/packages/consul-ui/app/services/repository/oidc-provider.js
ui/packages/consul-ui/tests/unit/services/repository/oidc-provider-test.js

This PR fixes 2 problems with our OIDC flow in the UI, the first is straightforwards, the second is relatively more in depth:
1: A typo (1.10.1 only)
During https://github.com/hashicorp/consul/pull/10503 we injected our settings service into the our oidc-provider service, there are some comments in the PR as to the whys and wherefores for this change (https://github.com/hashicorp/consul/pull/10503/files#diff-aa2ffda6d0a966ba631c079fa3a5f60a2a1bdc7eed5b3a98ee7b5b682f1cb4c3R28)
During development, this manifests itself as a javascript error:
Whereas during production, it simply breaks with no clear reason as to what the problem is.
Fixing the typo so it was no longer looking for an unknown service (`repository/settings` > `settings`)
fixed this part of the issue which was added as part of …

ui: [BUGFIX] Properly encode non-URL safe characters in OIDC responses

---

.changelog/10838.txt
agent/agent_test.go
agent/consul/client_test.go
agent/consul/options.go
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/server.go
agent/consul/subscribe_backend_test.go
agent/consul/wanfed/wanfed.go
agent/grpc/client.go
agent/grpc/client_test.go
agent/grpc/resolver/resolver.go
agent/grpc/server_test.go
agent/pool/conn.go
agent/pool/peek_test.go
agent/pool/pool.go
agent/setup.go

grpc: ensure that streaming gRPC requests work over mesh gateway based wan federation

---

.changelog/10901.txt
ui/packages/consul-ui/app/components/token-source/index.hbs
ui/packages/consul-ui/tests/unit/services/repository/oidc-provider-test.js

ui: [Backport] Backport of #10901 to 1.9.x

---

ui/packages/consul-ui/tests/integration/serializers/auth-method-test.js

During https://github.com/hashicorp/consul/pull/9617 we added a list view only for AuthMethods, but not a detail view. We did add the Adapter/Serializer that collected/reshaped data for a detail view.
The test for this serializer was skipped here, but I'm not sure why.
We then added https://github.com/hashicorp/consul/pull/9845 which began to use this AuthMethod Serializer, but we didn't go back to finish up the skipped test here either.
This PR unskips this test and finishes off the test correctly.

ui: Unskip auth-method serializer test

---

.changelog/10902.txt
ui/packages/consul-ui/app/abilities/policy.js

User with `read` permission can `edit` policies. An error message denying their request appears. The change temporarily appears in policy list page. The changes do not persist. Refreshing the page resets the changes.
Using a new Consul cluster with ACLs enabled with default deny.
- Create the a new policy with the following rules:
acl = "read" 
operator = "read" 
service_prefix "" { policy = "write" }
node_prefix "" { policy = "write" }
agent_prefix "" { policy = "write" }
- Create a new Role
- Update the Anonymous Token to use the new Role and Policy
- Log off and log back in with Anonymous Token
- Try to update a Policy name
Fix up a typo in the `canWrite()` permission for policy.
Now, the user can't edit any policies because form fields are disabled. 
Test coverage can be found …

ui: Disabling policy form fields from users with 'read' permissions

---

CHANGELOG.md

We just released 1.10.2, 1.9.9 and 1.8.15 so this adds their changelog entries.

changelog: add entries for 1.10.2, 1.9.9 and 1.8.15

---

.changelog/10952.txt
api/operator_license.go

Licensing recently changed in Consul v1.10 and along with those changes
the client API was updated such that PutLicense and ResetLicense both
immediately return an error to avoid an unecessary round trip that will
inevitably fail.
For reference, see: https://github.com/hashicorp/consul/commit/08eb600ee5e4eacfeef8223fc217973eeecdc692
Unfortunately, this change broke forward compatibility such that a v1.10
client can no longer make these requests to a v1.9 server which is a
valid use case.
This commit reintroduces these requests to fix this compatibility
breakage but leaves the deprecation notices in tact.

Revert early out errors in license API

---

website/content/docs/enterprise/audit-logging.mdx

When file rotation is enabled a timestamp will always be added as a suffix to the filename, even if the logs have not been rotated yet.
See the filename in this tutorial:
https://learn.hashicorp.com/tutorials/consul/audit-logging#explore-audit-logs

Update audit logging example

---

website/content/docs/nia/enterprise/license.mdx

This PR adds a link to the Enterprise License tutorial in the NIA documentation section.

docs: link to the enterprise license tutorial

---

website/content/docs/nia/enterprise/license.mdx

This PR fixes the license list numbering behaving incorrectly

docs: fixed numbering of license bullets and corrected indent

---

CHANGELOG.md

This is to advertise the issue with TLS verification and a temporary workaround.

Add changelog known issues for latest patch releases

---

website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

Per @lanceplarsen:
This policy is wrong because it misses ACL write in the namespace.  When using enterprise the policy is this:
namespace_prefix "" {
acl = "write"
service_prefix "" {
policy = "read"
intentions = "read"
}
}
This PR fixes this.

fixing the policy for configuring k8 clusters as secondary in federated arch

---

.changelog/10566.txt
sdk/testutil/server.go

Before this PR it wasn't possible to configure graceful consul shutdown in testutil. [this](https://github.com/hashicorp/consul/blob/21e855d860865f1472b3fdcb64a916e92bc83a9f/command/agent/agent.go#L313-L316) code was always triggered.
Now the default behavior is exactly the same as it used to be, but the users are able to set SkipLeaveOnInt flag, which causes consul to actually do the graceful shutdown on receiving SIGINT, and StopTimeout flag, which allows configuring for how long we are going to wait before sending `syscall.SIGABRT` to consul

Allow configuring graceful stop in testutil

---

.changelog/10964.txt
agent/consul/rpc_test.go
tlsutil/config.go
tlsutil/generate.go

Until now Consul never used the intermediate certificates to verify TLS certs, but it should! Like the [stdlib](https://pkg.go.dev/crypto/tls#example-Config-VerifyConnection).

use intermediates when verifying

---

agent/consul/state/acl.go
agent/consul/state/acl_schema.go

- convert indexAccessor to the new index.
- This index is for legacy ACL and should not impact the partitioning work.
- Converting this is just to normalize how we do indexes

convert indexAccessor to the new index

---

.changelog/10964.txt
agent/consul/rpc_test.go
tlsutil/config.go
tlsutil/generate.go

[1.8.x] use intermediates when verifying

---

.changelog/10964.txt
agent/consul/rpc_test.go
tlsutil/config.go
tlsutil/generate.go

[1.9.x] use intermediates when verifying

---

.changelog/10964.txt
agent/consul/rpc_test.go
tlsutil/config.go
tlsutil/generate.go

[1.10.x] use intermediates when verifying

---

website/content/docs/connect/intentions.mdx

Trying to work something out for a user I realise that while we do document the ability to wildcard namespaces in the [Config Entry reference](https://www.consul.io/docs/connect/config-entries/service-intentions#namespace), we just didn't mention it at all in this overview which made it hard to discover this is possible even when I already suspected it was!
There is an additional issue I found that wasn't super clearly documented: that L7 Permissions and wildcard destinations are mutually exclusive. I'll address that in a separate PR as we don't seem to call that out anywhere clearly.

Document how to make namespace wildcard intentions.

---

website/content/docs/connect/transparent-proxy.mdx

the bracket/parenthesis link syntax was flipped here

website: fixup incorrect markdown syntax

---

api/config_entry.go
api/config_entry_cluster.go
api/config_entry_discoverychain.go
api/config_entry_discoverychain_test.go
api/config_entry_gateways.go
api/config_entry_intentions.go
api/config_entry_test.go

ent->oss merge
Add the partition field to api.ConfigEntry structs and related tests.
Admin partitions are a Consul Enterprise feature.

Sync partition fields from enterprise

---

agent/config/builder.go
agent/structs/config_entry_gateways.go
sdk/testutil/assertions.go

Synced from enterprise:
> Also made a few improvements to the error messages that used "current" to make the error easier to understand.
> 
> Also improved the failure message for `RequireErrorContains`, because the previous error message did not provide enough information for me to debug some of these test failures.

Update error texts

---

agent/xds/rbac.go
agent/xds/rbac_test.go

The code changes are fairly narrow:
- ixnSourceMatches was updated to account for partitions
- SpiffeID pattern generation was updated to account for partitions
- Validation panics if a wildcard partition source is being used

Account for partition when matching src intentions

---

website/content/docs/k8s/operations/uninstall.mdx

As of Consul Helm 0.26.0, for Consul 1.8.x, we no longer need to manually remove the `consul-controller-webhook-cert` secret. This is a result of https://github.com/hashicorp/consul-k8s/pull/530.

docs: Remove step for deleting webhook-cert-manager secret on Consul K8s uninstall

---

website/content/docs/k8s/operations/uninstall.mdx

Reformatting uninstall as steps to make uninstall instructions more clear.

docs: Reformat Uninstall steps

---

agent/consul/acl.go
agent/consul/acl_oss_test.go
agent/consul/acl_test.go
agent/structs/acl.go
agent/structs/acl_oss.go

Also refactoring the enterprise side of a test to make it easier to reason about.
The main change here is to change the Service Identity and Node Identity templates.

acl: small resolver changes to account for partitions

---

website/content/docs/ecs/get-started/install.mdx
website/content/docs/ecs/get-started/migrate-existing-tasks.mdx
website/data/docs-nav-data.json

* Add "Migrate Existing Tasks" doc/guide
* Trim and update the Install guide (renamed to "Installation") for beta
* Update sidebar with links to Fargate and EC2 examples

docs: Migrate Existing Tasks page for ECS

---

api/api.go
api/operator_autopilot.go
api/operator_autopilot_test.go

This PR adds a `StatusError` struct to the `api` package. Now devs can unwrap the errors returned thru `query()` or `write()` funcs and inspect the error code programatically. 
https://github.com/hashicorp/consul/issues/10865
* added a `requireHttpCodes` method to mark acceptable codes (200, 429, etc)
* adoption of that func to all/ most `doRequest()` calls can be added in a subsequent PR
* this PR mostly builds on feedback from https://github.com/hashicorp/consul/pull/8816
[x] `go fmt`
[x] `go mod`
[x] n/a pr/changelog -- no "public" api changes

add StatusError to api package

---

.changelog/10987.txt
agent/xds/delta.go
agent/xds/delta_test.go
agent/xds/server.go
agent/xds/xds_protocol_helpers_test.go

Fixes #10563
The `resourceVersion` map was doing two jobs prior to this PR. The first job was to track what version of every resource we know envoy currently has. The second was to track subscriptions to those resources (by way of the empty string for a version). This mostly works out fine, but occasionally leads to consul removing a resource and accidentally (effectively) unsubscribing at the same time.
The fix separates these two jobs. When all of the resources for a subscription are removed we continue to track the subscription until envoy explicitly unsubscribes.
When building up the list of expected xDS resources all of LDS/RDS/CDS/EDS is generated from the same in-memory representation built by the `agent/proxycfg` package. For clusters there's a loop that will walk that …

xds: fix representation of incremental xDS subscriptions

---

.changelog/11095.txt
ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
ui/packages/consul-ui/app/components/consul/intention/form/index.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/create.feature
ui/packages/consul-ui/tests/acceptance/dc/intentions/filtered-select.feature
ui/packages/consul-ui/tests/steps/assertions/dom.js

This PR supersedes https://github.com/hashicorp/consul/pull/10706 and fixes https://github.com/hashicorp/consul/issues/10686 whilst making sure that saving intentions continues to work.
The original fix in https://github.com/hashicorp/consul/pull/10706 ignored the `change` action configured for the change event on the menus, meaning that the selected source/destination namespace could not be set by the user when editing/creating intentions. This, coupled with the fact that using the later intention `exact` endpoint for API requests endpoint means that you cannot use wildcard namespaces for saving intentions.
All in all this meant that intentions could no longer be saved using the UI (whilst using ENT):
This PR reverts https://github.com/hashicorp/consul/pull/10706 to fix the intention …

ui: [BUGFIX] Re-enable namespace menus whilst editing intentions

---

.changelog/11102.txt
ui-v2/app/components/consul-intention-form/index.js
ui-v2/tests/acceptance/dc/intentions/create.feature
ui-v2/tests/acceptance/dc/intentions/filtered-select.feature
ui-v2/tests/steps/assertions/dom.js

See #11095. Whilst this is a backport it only fixes the visual issue with the namespace menus (doubling up of selectable elements in the menu). The main issue that #11095 fixes is not an issue in 1.8.x as the original fix for this issue was never backported to 1.8.x.
I've included the tests I copy/pasted for 1.9.x, 1.10.x and 1.11.x here also, even though the bug introduced in those versions is not an issue in 1.8.x, it's still maybe useful to have those here also.

ui: [Backport] Backport of #11095 to 1.8.x

---

.changelog/10916.txt
ui/packages/consul-ui/app/abilities/kv.js
ui/packages/consul-ui/tests/acceptance/dc/acls/tokens/index.feature
ui/packages/consul-ui/tests/acceptance/dc/kvs/index.feature
ui/packages/consul-ui/tests/acceptance/navigation-links.feature

Currently there is no way for us to use our HTTP authorization API
endpoint to tell us whether a user has access to any KVs (including the
case where a user may not have access to the root KV store, but do have
access to a sub item)
This is a little weird still as in the above case the user would click
on this link and still get a 403 for the root, and then have to manually
type in the URL for the KV they do have access to.
Despite this we think this change makes sense as at least something about KV is
visible in the main navigation.
Once we have the ability to know if any KVs are accessible, we can add
this guard back in.
We'd initially just removed the logic around the button, but then
noticed there may be further related KV issues due to the nested nature
of KVs so we finally decided …

ui: Always show main navigation Key/Value link

---

.changelog/11077.txt
ui/packages/consul-ui/app/helpers/cached-model.js
ui/packages/consul-ui/app/services/repository.js
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/mock-api/v1/catalog/datacenters
ui/packages/consul-ui/tests/acceptance/dc/error.feature
ui/packages/consul-ui/tests/acceptance/dc/services/error.feature
ui/packages/consul-ui/tests/steps/doubles/model.js

Continuation of https://github.com/hashicorp/consul/pull/11017
During the above PR we left over a few less important FIXMEs to be fixed up in smaller iterative PRs.
This PR fixes what happens in the UI if you try to navigate to a non-existing DC.
When we received a 500 error from an API response due to a non-existent DC, previously we would show a 404 error, which is what we were trying to convey. But in the spirit of the UI being a 'thin client', its probably best to just show the 500 error from the API response, which may help folks to debug any issues better.
There is also ongoing work on improving our error messaging, and this is an opportunity to improve further by moving away from, or adding to, our generic error pages by including the actual error reported by the API as well as our …

ui: Gracefully recover from non-existent DC errors

---

ui/packages/consul-ui/app/components/menu-panel/index.js

This PR solves an occasionally flakey test I see every so often.

ui: Add an isDestroyed check for the MenuPanel component

---

ui/packages/consul-ui/docs/i18n.mdx

Adds some super high level/info info on how we localize the app, plus information on casing patterns for text.

ui: Add initial i18n docs page

---

.changelog/11099.txt
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/subscribe_backend.go
agent/consul/subscribe_backend_test.go
agent/rpc/subscribe/subscribe.go
agent/rpc/subscribe/subscribe_test.go
agent/submatview/store_integration_test.go
proto/pbcommon/common.go
proto/pbsubscribe/subscribe.go

grpc: strip local ACL tokens from RPCs during forwarding if crossing datacenters

---

agent/delegate_mock_test.go

Rebase+Merge didn't work well with the backporting process. The auto-backport only grabbed the latest commit and left this cherry-picked one behind.

Finish Backporting #11107

---

.changelog/11109.txt
agent/structs/testing_connect_proxy_config.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/custom-upstream.envoy-1-18-x.golden
agent/xds/testdata/listeners/custom-upstream.v2compat.envoy-1-16-x.golden

Fixes https://github.com/hashicorp/consul/issues/10897
We were missing a codepath for envoy listener escape hatches defined on Prepared Query upstream configs. The envoy tests were updated to cover this case.

connect: Allow upstream listener escape hatch for prepared queries

---

agent/delegate_mock_test.go

Fixes backport of #11107
Not sure why the backporting process didn't catch that the type didn't exist in the old version. Regardless its fixed

Fix broken backport of #11107 1.9.x

---

.changelog/11099.txt
agent/consul/rpc.go
agent/consul/rpc_test.go
agent/consul/subscribe_backend.go
agent/consul/subscribe_backend_test.go
agent/rpc/subscribe/subscribe.go
agent/rpc/subscribe/subscribe_test.go
agent/submatview/store_integration_test.go
proto/pbcommon/common.go
proto/pbsubscribe/subscribe.go

backport of #11099 to `release/1.10.x`
Conflicts:
- `agent/consul/rpc.go`: this needed a lot of work just because there is no concept of leader forwarding for gRPC in 1.10.x
- `agent/consul/subscribe_backend.go`
- `proto/pbcommon/common.go`

[1.10.x] grpc: strip local ACL tokens from RPCs during forwarding if crossing datacenters

---

ui/packages/consul-ui/tests/acceptance/dc/intentions/create.feature

This one has a long and complicated story, so I'll keep it as brief as I can.
- https://github.com/hashicorp/consul/pull/10706 fixed a visual bug reported in https://github.com/hashicorp/consul/issues/10686 but in doing so created a blocking bug that was only backported to 1.10 and 1.9 (I'm not entirely sure why, there seems to be some backporting confusion on that PR judging by the GH history)
- The blocking bug was fixed in https://github.com/hashicorp/consul/pull/11095 by reverting to the previous functionality and fixing the original visual bug with some ~copypasta so that our namespace menus consistently worked the same as the service menus. This fixed the blocking bug across 1.9 and 1.10 but the blocking bug was never backported to 1.8 so only the visual bug needed to be fixed …

ui: Use last-child for selecting the desired nspace instead of nth-child

---

website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/installation/deployment-configurations/consul-enterprise.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

Use kubectl's base64decode template function ([added in K8s 1.11](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.11.md#sig-cli-1)) to decode values in Secrets. Removes external call to `base64` utility on the host system.

docs: Decode K8s secrets with base64decode function

---

.changelog/11129.txt
ui/packages/consul-ui/app/adapters/intention.js
ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/form/index.js
ui/packages/consul-ui/app/components/consul/intention/list/skin.scss
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
ui/packages/consul-ui/app/models/intention.js
ui/packages/consul-ui/app/serializers/intention.js
ui/packages/consul-ui/app/services/repository/intention.js
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/mock-api/v1/connect/_
ui/packages/consul-ui/mock-api/v1/connect/intentions/_
ui/packages/consul-ui/mock-api/v1/connect/intentions/exact
ui/packages/consul-ui/tests/acceptance/dc/intentions/create.feature
ui/packages/consul-ui/tests/acceptance/dc/intentions/delete.feature
ui/packages/consul-ui/tests/acceptance/dc/intentions/permissions/warn.feature
ui/packages/consul-ui/tests/acceptance/dc/intentions/update.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions.feature
ui/packages/consul-ui/tests/integration/adapters/intention-test.js
ui/packages/consul-ui/tests/integration/serializers/intention-test.js

This PR is an iterative PR ontop of https://github.com/hashicorp/consul/pull/11017 to add further `partition` support for intentions.
Most of this is the same as our namespace support so it's pretty much adding `partition` everywhere with some copypasta.
Just to note, there are some little differences between namespaces and partitions surrounding differences between primaries and secondaries. I need to reach out to the team to refresh my memory on that, so there is nothing here that addresses any of those differences and they'll be added in a further iterative PR along with any other minor details.

ui: Add partition support to intentions

---

.changelog/11130.txt
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/styles/themes.scss

A while back we decided we would get rid of this informational panel at the top of the Namespace menu when editing namespaces. It kinda felt like a good time to remove of it.
This light-themed panel is the panel that has been removed:

ui: Remove info panel from the nspace menu when editing nspaces

---

website/content/docs/k8s/connect/terminating-gateways.mdx
website/content/docs/k8s/installation/deployment-configurations/consul-enterprise.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

Manually backport #11137 which failed to cherry pick to the 1.10.x branch when the original PR was merged.

[1.10.x] docs: Backport #11137 to release/1.10.x

---

website/content/docs/k8s/index.mdx
website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/k8s-cli.mdx
website/content/docs/k8s/operations/uninstall.mdx
website/data/docs-nav-data.json

Manually backport #11028 which failed to cherry pick to the stable-website branch when the original PR was merged.

docs: Backport #11028 k8s CLI docs to stable-website

---

ui-v2/app/templates/dc/nodes/show/sessions.hbs

* ui: Move action to the correct button for session invalidation
* Remove refresh-route completely, its not needed
(Also see #11105)

ui: [Backport 1.8.x] Remove refresh-route action for session invalidation (#11105)

---

ui/packages/consul-ui/tests/unit/abilities/-test.js

This PR adds a very small unit test to unit test all of our current and _future_ abilities and stems from an idea here:
https://github.com/hashicorp/consul/pull/10902#issuecomment-905331481
> If we wanted to go lower we could just test the abilities themselves, which would make it easier to just loop through them all and check that read, write, 'create', 'update' permissions report correctly for each model type we have (plus easily test any future models to prevent any typos like we have here). We could almost test the unit itself if it wasn't for the inheritance chain, so we'd be ever so slightly be blurring into integration, but in this case I think doing some sort of unit testing of the abilities themselves (in a future looking way) might be a good idea 🤔 . What do you think?
The PR …

ui: Adds a set of basic unit tests for abilities

---

.changelog/10915.txt
ui/packages/consul-ui/app/routes/dc/routing-config.js
ui/packages/consul-ui/app/styles/layout.scss
ui/packages/consul-ui/app/templates/dc/routing-config.hbs

Continuation of https://github.com/hashicorp/consul/pull/10835
DataSources added via javascript require cleaning up by assigning it to
an EventSource component in the template, otherwise the blocking query
can stick around when its no longer needed.
We also took the opportunity here to make this consistent with the rest
of the application.
1. Don't use `@model`.
2. Use our `<Route />` component.
3. Only use extra divs/spans specifically for styling only as a last resort.

ui: Ensure we clean up javascript based DataSources

---

.changelog/11149.txt
ui/packages/consul-ui/app/abilities/intention.js
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/models/intention.js
ui/packages/consul-ui/app/templates/dc/intentions/edit.hbs

Thanks to the amazing folks in https://github.com/hashicorp/consul/issues/11012 I realised that we had a small UI bug here that was further complicated by a problem with our `/v1/internal/acl/authorize` endpoint which was recently fixed here https://github.com/hashicorp/consul/pull/11061 . I initially thought this authorize endpoint error was in a 1.10.x release but looking a little harder, it seems like it isn't, it's only in our recent 1.11 alpha.
The UI bug here manifests itself only when a user/token is configured to have read-only access to intentions. Instead of only letting folks click to see a read only page of the intention, we would show an additional message saying that the intention was read-only due to it being 'Managed by [a kubernetes] CRD'. Whilst the intention was still …

ui: Don't show the CRD menu for read-only intentions

---

.changelog/10914.txt
ui/packages/consul-ui/app/templates/dc/acls/policies/index.hbs
ui/packages/consul-ui/app/templates/dc/acls/roles/index.hbs
ui/packages/consul-ui/app/templates/dc/nspaces/index.hbs

This PR adds a check to policy, role and namespace list pages to make sure the user has can write those things before offering to create them via a button. (The create page/form would then be a read-only form)
Before (when read only):
After (when read only):

ui: Hide create buttons for policies/roles/namespaces with readonly access

---

ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
ui/packages/consul-ui/app/styles/base/icons/icon-placeholders.scss

This PR adds @hashicorp/flight-icons to our icon set so we can use them when we want to/need to.
Please note: This PR does not use the new icons at all, it just installs them ready for use. All unused icons are tree-shaken out of the final build so it has absolutely no impact on the current UI as it stands.

ui: Adds Flight icons to our icon set

---

website/content/docs/connect/config-entries/service-intentions.mdx

There is a limitation on L7 intentions that I couldn't find documented anywhere. This fixes that at least in the reference docs for the affected fields.

Call out the incompatibility of wildcards and L7 permissions

---

agent/config/builder.go
agent/config/config.go
agent/config/deprecated.go
agent/config/merge_test.go
agent/config/runtime_test.go
lib/decode/decode.go
lib/decode/decode_test.go

We have deprecated config fields in the past, but I believe this approach has a number of advantages.
1. All of the deprecation logic (copying the value to the new location, and creating a warning) is together in the same place. Previously it was scattered in 3 or more places, which resulting in a lot of inconsistency.
2. Deprecated fields no longer need to be part of the `Config`. The `Config` struct can be used exclusively as an intermediate for merging. The new `DeprecatedConfig` and `decodeTarget` structs allow us to decode into `DeprecatedConfig` and immediately copy to the new config location.
3. Building a `RuntimeConfig` from a `Config` is more straightforward because deprecated config is handled before that step.

config: Use DeprecatedConfig struct for deprecated config fields

---

agent/config/builder.go
agent/config/config.go
agent/config/default.go
agent/config/deprecated.go
agent/config/deprecated_test.go
agent/config/runtime_test.go
website/content/docs/agent/options.mdx

Branched from #9456
This PR moves deprecated ACL config fields to the `DeprecatedConfig` struct, and adds a warning when they are set. Since we have equivalent fields in the new ACL system, it did not seem necessary to error when one of these fields are set.

acl: isolate deprecated config and warn when they are used

---

.changelog/11136.txt
acl/static_authorizer.go
agent/consul/acl.go
agent/consul/acl_test.go
website/pages/docs/agent/options.mdx

Backport of https://github.com/hashicorp/consul/pull/11136
Surprisingly, when I ran `git cherry-pick -m 1 19040586ce9102b083c82ea9bb3c5efd141b4712` localy it did not fail to merge. I'm guessing the automation failed ([link](https://app.circleci.com/pipelines/github/hashicorp/consul/22222/workflows/4c8c9b02-16f1-4024-89f0-42365b3b6448/jobs/460799)) because of this warning:
```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 5920 and retry the command.
```
In the release/1.8.x branch the website content is at a different path, so I guess it has to check too many files for renames. Maybe that's non-deterministic, which results in this problem?

[1.8.x]  acl: fix default Authorizer for down_policy extend-cache/async-cache

---

api/agent.go
api/debug.go
api/kv.go

This PR builds on https://github.com/hashicorp/consul/pull/11054 to wrap all remaining `doRequest()` calls around a `require*()` call.
https://github.com/hashicorp/consul/issues/10865
* mostly refactoring, no logic changes

wrap doRequest calls for error handling

---

.changelog/11117.txt
ui/packages/consul-ui/app/components/auth-dialog/index.hbs
ui/packages/consul-ui/app/components/data-source/README.mdx
ui/packages/consul-ui/app/components/empty-state/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/policy-selector/index.hbs
ui/packages/consul-ui/app/components/token-source/index.hbs
ui/packages/consul-ui/app/helpers/uri.js
ui/packages/consul-ui/app/services/data-sink/service.js
ui/packages/consul-ui/app/services/data-source/service.js
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/app/templates/dc/nodes/show/sessions.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs

Our DataSource came in very iteratively, when we first started using it we specifically tried not to use it for things that would require portions of the `@src=""` attribute to be URL encoded (so things like service names couldn't be used, but dc etc would be fine). We then gradually added an easy way to url encode the `@src=""` attributes with a `uri` helper and began to use the DataSource component more and more. This meant that some DataSource usage continued to be used without our uri helper.
Recently we hit https://github.com/hashicorp/consul/pull/10901 which was a direct result of us not encoding `@src` values/URIs (I didn't realise this was one of the places that required URL encoding) and not going back over things to finish things off once we had implemented our `uri` helper, …

ui: Make it hard to not URLEncode DataSource srcs/URIs

---

ui/packages/consul-ui/app/models/dc.js
ui/packages/consul-ui/app/serializers/dc.js
ui/packages/consul-ui/mock-api/v1/catalog/.config
ui/packages/consul-ui/tests/integration/serializers/dc-test.js

Adding [Default ACL Policy](https://www.consul.io/api-docs#default-acl-policy) header to the UI.
No screenshots.
No BE Changes.
Updating the headers for `X-Consul-Default-Acl-Policy` to return from the dc endpoint.
Update DC serializer test.
Adding integration tests with future implementation.

ui: Use of header default ACL policy

---

ui/packages/consul-ui/app/adapters/partition.js
ui/packages/consul-ui/app/components/auth-form/index.hbs
ui/packages/consul-ui/app/components/data-source/index.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/components/token-source/index.js
ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/routing/route.js
ui/packages/consul-ui/app/services/data-sink/protocols/http.js
ui/packages/consul-ui/app/services/repository/dc.js
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs

This commit addresses some left over admin partition FIXMEs (see https://github.com/hashicorp/consul/pull/11017)
1. Adds Partition correctly to Service Instances
2. Converts non-important 'we can do this later' FIXMEs to TODOs and leaves plenty of explanation
3. Removes some FIXMEs that I've double checked and addressed.
Most of the remaining FIXMEs I'm waiting on responses to questions from
the consul core folks for. I'll address those in a separate PR.
~Pretty sure none of this is needed for any imminent release.~

ui: Address some Admin Partition FIXMEs

---

agent/intentions_endpoint.go
agent/intentions_endpoint_test.go

Legacy Create and SpecificUpdate endpoints should not handle Source- or Destination- partitions (in either OSS or ENT).

agent: Reject partitions in legacy intention endpoints

---

tlsutil/config.go
tlsutil/config_test.go

I noticed this while looking over #11207
The errs were not being captured because the value of append was not being assigned.

rpc: include error for AuthorizeServerConn failures

---

tlsutil/config_test.go

Backport of #11210 was "successful" , but the imports were wrong.

[1.10.x] Fixing the build after auto-backport

---

tlsutil/config_test.go

Backport of #11210 was "successful" , but the imports were wrong.

[1.9.x] Fixing the build after auto-backport

---

agent/consul/acl.go
agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_test.go
agent/consul/acl_replication_test.go
agent/consul/acl_server.go
agent/consul/acl_token_exp.go
agent/consul/enterprise_server_oss.go
agent/consul/helper_test.go
agent/consul/intention_endpoint_test.go
agent/consul/leader.go
agent/consul/leader_connect_test.go
agent/consul/leader_federation_state_ae_test.go
agent/consul/leader_test.go
agent/consul/rpc_test.go
agent/consul/server.go
agent/consul/server_serf.go
agent/consul/state/acl.go
agent/consul/state/acl_schema.go
agent/consul/util.go
agent/consul/util_test.go
agent/metadata/server.go
agent/routine-leak-checker/leak_test.go
agent/structs/acl.go

Branched from #11126
This PR removes the rest of the "start in legacy" logic from `Server`. The upgrade token goroutine is kept around for cases where a user may restore from a snapshot with legacy tokens, or when a legacy token is created immediately before the server is shutdown for an upgrade.

acl: remove upgrade from legacy, start in non-legacy mode

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/network-drivers/index.mdx
website/content/docs/nia/network-drivers/terraform-cloud.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

Removes beta callouts in preparation for GA release. Essentially reverts https://github.com/hashicorp/consul/pull/11151

nia/docs: Remove references to v0.4.0-beta

---

CHANGELOG.md
agent/dns.go
agent/dns_test.go

So this PR fixes a bug in how SOA record is generated on a DNS query when using an alt domain. Essentially whenever the alt domain is in use and the SOA record is generated it always assumes the primary domain and never takes into account an alt domain. I'm not sure how critical this is, but it seems like this could be fairly problematic. Maybe people are not using alt domains? Right now I'm merging this to master, but my company really needs the fix on version v1.9.6, not sure what the process is for back porting. My company is using a custom build for now.

Fixing SOA record to use alt domain when alt domain in use

---

website/content/api-docs/libraries-and-sdks.mdx

This PR proposes adding [consulrs](https://github.com/jmgilman/consulrs) to the list of SDKs. It's currently the most feature-rich crate in the Rust ecosystem and offers significantly more than the one currently listed.

Adds consulrs Rust client library to SDK list

---

.changelog/11348.txt
agent/dns.go
agent/dns_test.go
website/content/docs/agent/options.mdx
website/content/docs/discovery/dns.mdx

This pull request is a rewrite of https://github.com/hashicorp/consul/pull/11274. 
It fixes responses for requests made with altDomain. 
Closes https://github.com/hashicorp/consul/issues/10224

Fix answers for alt domain

---

website/content/docs/security/acl/acl-rules.mdx

This PR addresses feedback on admin partitions ACL rules for beta 1. I've also rewritten, reorganized, and added to the content around ACL rule features and creation. Notably, the Rule Specification section has been rewritten and the specifics about resource rules have been addd to a Reference section, which also includes a table that is intended to serve as an overview/toc. 
Preview: https://consul-jjbjbbubp-hashicorp.vercel.app/docs/security/acl/acl-rules

admin partitions feedback related to ACLs; additional improvements to ACL rule docs

---

.changelog/11419.txt
agent/config_endpoint.go
agent/config_endpoint_test.go
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/config_replication_test.go
agent/consul/fsm/commands_oss.go
agent/consul/fsm/commands_oss_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry.go
api/config_entry.go
api/config_entry_test.go
command/config/delete/config_delete.go
command/config/delete/config_delete_test.go
testrpc/wait.go
website/content/api-docs/config.mdx
website/content/commands/config/delete.mdx

Adds support for Check-And-Set (CAS) deletion of config entries, similar to that [of KVs](https://www.consul.io/api-docs/kv#cas-1).
This is useful for cases where it is desirable to delete a config entry, but only if it has not been modified by another process since reading it (such as the scenario described in #11372).
Sidenote: this is my first PR to Consul 🎉 so any meta/style feedback is greatly appreciated!

Support Check-And-Set deletion of config entries

---

agent/consul/leader_connect_ca.go

The `CAMananger` has two distinct "modes". It can operator as a primary (in the primary DC), or a secondary (in a secondary DC). Some of the methods on `CAManager` are clearly identified as such, but not all.
This PR renames all methods that are primary-only or secondary-only to start with a `primary` or `secondary` prefix. This is one small step to help make these two "modes" more obvious, which will help prevent issues like the one described in #11159. In the future we may be able to make these two modes more concrete in code by having separate types for each.

ca: clearly identify methods that are primary-only or secondary-only

---

agent/connect/ca/provider.go

Branched from #11338
To make it more clear which methods are necessary for each "mode".  This will help prevent issues like the one described in #11159. In the future we should be able to pass to use only the `PrimaryProvider` when in primary mode, and only `SecondaryProvider` when in secondary mode, so that we can't accidentally call the wrong method.

ca: split the Provider interface into Primary/Secondary

---

agent/proxycfg/manager_test.go
agent/proxycfg/mesh_gateway.go
agent/proxycfg/snapshot.go
agent/proxycfg/state.go
agent/proxycfg/state_test.go
agent/proxycfg/terminating_gateway.go
agent/proxycfg/testing.go
agent/proxycfg/upstreams.go
agent/xds/clusters.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go

When checking which endpoint to use for an upstream we call BestAddress on the service instance. This function will optionally look for the tagged WAN address if it's a WAN request.
Originally we would only check whether the datacenters match, but now are also checking whether partitions match.
The last commit also fixes an issue with how the `GatewayKeys()` method wasn't deduplicating data.

Ensure calls to BestAddress consider partition

---

agent/agent.go
agent/consul/leader_metrics.go
agent/consul/server.go
agent/metrics.go
agent/metrics_test.go
agent/setup.go

Related to some improvements suggested here: https://github.com/hashicorp/consul/pull/10768#discussion_r682871038
Emit the metric immediately so that after restarting an agent, the new expiry time will be
emitted. This is particularly important when this metric is being monitored, because we want
the alert to resovle itself immediately.
Fixed a bug that was exposed in one of these metrics. The CARoot can be nil, so we have
to handle that case.
Removed the labels. With the labels these metrics would not match the predefined metric, and the prometheus sink would expire them long before they were emitted again. It should be the responsibility of agent or tool that pulls these metrics to add node and dc tags.
Only declare these metrics on servers, and emit a NaN when a server starts so that …

telemetry: improve cert expiry metrics

---

.github/workflows/build.yml

At the moment release builds are created for every PR. This change temporarily sets the target branch to an arbitrary name. 
It will be updated later to release branches. Currently there is no long-lived release branch for 1.11.

Prevent running build workflows on all PRs

---

.changelog/11428.txt
agent/config/builder.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_config.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/connect/generate_test.go
agent/connect_ca_endpoint.go
agent/consul/config.go
agent/structs/connect_ca.go
agent/structs/connect_ca_test.go
api/connect_ca.go
api/connect_ca_test.go
sdk/testutil/server.go
website/content/docs/agent/options.mdx
website/content/partials/http_api_connect_ca_common_options.mdx

This change adds an option to the `CommonCA` config to allow a `root_cert_ttl` value which will control the TTL (time to live) for root certs issued by supported CA providers. It's mostly plumbing.
* At present the only providers supported are `consul connect `and `vault`. 
* Let's focus on the functionality (going QSF -- quality, security, feature), before delving into all the refactoring opportunities
* No corresponding "cli flag" option added as it's not a pattern for our current ca config
I used the config file checklist [here](https://github.com/hashicorp/consul/blob/main/docs/config/checklist-adding-config-fields.md). Click below to expand on a "filled in" version of it.
<details>
<summary>Click to expand!</summary>
* `n/a` -- not applicable
* `?` -- I believe I may have fully …

add root_cert_ttl option for consul connect, vault ca providers

---

website/content/docs/connect/config-entries/service-defaults.mdx

The UpstreamConfig.Defaults field does not support setting Name or
Namespace because the purpose is to apply defaults to all upstreams.
I think this was just missed in the docs since those fields would
error if set under Defaults.
i.e. this is not supported:
```
UpstreamConfig {
Defaults {
Name = "foo"
Namespace = "bar"
}
}
```

Remove Name/Namespace fields from upstream default

---

ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs

Previously we had "Open metrics Dashboard" and "Configure metrics
dashboard" in the topology cards and then we had "Open Dashboard" in the
top nav when the dashboard was configured.
Now we use "Open dashboard" and "Configure dashboard".
This change was made for consistency in wording and casing. In addition,
the dashboard could be used for metrics but also other dashboards so
there's no need to scope it only to metrics. Also the config is:
```hcl
ui_config {
dashboard_url_templates
}
```
Which does not mention metrics
Before:

Use "Open dashboard" everywhere

---

website/content/docs/connect/observability/ui-visualization.mdx

The Consul UI topology view has an icon with the text
"Configure metrics dashboard" that links to this page. Add a notice at
the top of the page that links them directly to the relevant section.

Add quick-link for users coming from UI

---

ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs

Previously we had "Open metrics Dashboard" and "Configure metrics
dashboard" in the topology cards and then we had "Open Dashboard" in the
top nav when the dashboard was configured.
Now we use "Open dashboard" and "Configure dashboard".
This change was made for consistency in wording and casing. In addition,
the dashboard could be used for metrics but also other dashboards so
there's no need to scope it only to metrics. Also the config is:
```hcl
ui_config {
dashboard_url_templates
}
```
Which does not mention metrics

Use "Open dashboard" everywhere (#11406)

---

agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go

These changes just build on https://github.com/hashicorp/consul/commit/9b45107c1e907a8209ad4d38af230f2fa863fd22. ( https://github.com/hashicorp/consul/pull/10411 )
* testing is done thru existing units; this PR essentially "fixes" the tests too.
* this PR is blocking https://github.com/hashicorp/consul/pull/11449
```shell
$ export ENABLE_AWS_PCA_TESTS=true
$ go test -run TestAWS ./agent/connect/ca -v
...
ok      github.com/hashicorp/consul/agent/connect/ca    35.387s
```

fix aws pca certs

---

website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx

This documentation patch updates the sample replication token policy provided for multi-cluster federation using namespaces.
As ACLs are namespace-scoped resources, the `acl = "write"` permission must be applicable to all namespaces. Otherwise secondary datacenters will fail to replicate ACL tokens and policies outside the `default` namespace.

Update namespaced replication token example

---

website/content/docs/k8s/installation/install.mdx
website/content/docs/k8s/operations/uninstall.mdx

Since our docs now point folks to deploy Consul K8s in a dedicated `consul` namespace, this is a follow-on docs PR to allow folks to uninstall with that namespace now accounted for.

docs:  consul-k8s uninstall with namespace

---

.changelog/11409.txt
ui/packages/consul-ui/app/abilities/service-instance.js
ui/packages/consul-ui/app/abilities/service.js
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
ui/packages/consul-ui/app/services/repository.js
ui/packages/consul-ui/app/services/repository/service-instance.js
ui/packages/consul-ui/app/templates/dc/intentions/edit.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/edit.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs

ui: Ensure we check intention service prefix permissions for per service

---

ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs

I missed that partitions should never display if you can't use them, not just if you can't choose them.
This PR just adds a wrapping conditional for that, hoping the `Hide whitespace` thing in GH helps with review (yup it does, make sure you enable that for review)

ui: Only show partition / partition selector if partitions enabled

---

.changelog/11472.txt
ui/packages/consul-ui/app/adapters/permission.js
ui/packages/consul-ui/tests/unit/adapters/permission-test.js

Most HTTP API calls will use the default namespace of the calling token to additionally filter/select the data used for the response if one is not specified by the frontend.
The internal permissions/authorize endpoint does not do this (you can ask for permissions from different namespaces in on request).
Therefore this PR adds the tokens default namespace in the frontend only to our calls to the authorize endpoint. I tried to do it in a place that made it feel like it's getting added in the backend, i.e. in a place which was least likely to ever require changing or thinking about.
Note: 1.10.x base branch, a 1.11 PR to come that will add the same fix but for partitions also, I'm guessing it works better to fix on 1.10 and then add the 1.11 functionality, rather than fix on 1.11 and then …

ui: Ensure the tokens default nspace is passed thru to the auth endpoint

---

.changelog/11449.txt
agent/connect/ca/provider_aws.go
agent/connect/ca/provider_aws_test.go
website/content/docs/agent/options.mdx
website/content/partials/http_api_connect_ca_common_options.mdx

Branching off from https://github.com/hashicorp/consul/pull/11428
PR adds root cert ttl config to AWS CA provider.
* added new units around root cert ttl testing, also:
```
go test -run TestAWS ./agent/connect/ca
ok      github.com/hashicorp/consul/agent/connect/ca    53.035s
```

plumb thru root cert tll to the aws ca provider

---

.changelog/_1253.txt
agent/agent.go
agent/agent_test.go
agent/service_manager_test.go
agent/structs/structs.go
agent/util.go
agent/util_test.go

OSS side of https://github.com/hashicorp/consul-enterprise/pull/1253
This is a potential security issue because an attacker could conceivably manipulate inputs to cause persistence files to collide, effectively deleting the persistence file for one of the colliding elements.

Remove some usage of md5 from the system

---

website/content/docs/connect/ca/vault.mdx

Forgot to mention the RootCertTTL behavior change as part of the docs in https://github.com/hashicorp/consul/pull/11428.
Adding those here.

change vault ca docs to mention root cert ttl config

---

.changelog/11477.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/structs/connect_ca.go
go.mod
website/content/docs/connect/ca/vault.mdx

If there is a Namespace entry included in the Vault CA configuration,
set it as the Vault Namespace on the Vault client
Currently the only way to support Vault namespaces in the Consul CA
config is by doing one of the following:
1) Set the VAULT_NAMESPACE environment variable which will be picked up
by the Vault API client
2) Prefix all Vault paths with the namespace
Neither of these are super pleasant. The first requires direct access
and modification to the Consul runtime environment. It's possible and
expected that the consul owner has that access but it's not super pleasant.
The second requires more indepth knowledge of Vault and how it uses
Namespaces and could be confusing for anyone without that context. It
also infers that it is not supported

Support Vault Namespaces explicitly in CA config

---

.changelog/_1284.txt
agent/consul/acl_endpoint.go
agent/consul/acl_server.go
agent/consul/acl_token_exp.go
agent/consul/leader.go
agent/consul/state/state_store.go

also add a state store helper function for unit tests

rename helper method to reflect the non-deprecated terminology

---

acl/acl_test.go
acl/authorizer.go
acl/policy.go
acl/policy_merger.go
acl/policy_test.go
agent/acl_test.go
agent/consul/acl_endpoint.go
agent/consul/acl_test.go
agent/consul/catalog_endpoint_test.go
agent/consul/filter_test.go
agent/rpc/subscribe/subscribe_test.go
agent/structs/acl.go
agent/structs/acl_test.go
agent/structs/config_entry_discoverychain_test.go
agent/structs/config_entry_test.go
agent/structs/intention_test.go
agent/xds/delta_test.go

From what I can tell these fields are not used. They are never accessed directly, and I can't see anywhere that they would be used as a map key or serialized/deserialized. This PR removes these 2 unused fields.
We do use the `structs.ACLPolicy.ID` field for the `ACLResolver` cache, but not the `acl.Policy.ID`.

acl: remove Policy.ID and Policy.Revision

---

.circleci/config.yml

We ran into this again earlier in our builds wherever we were doing `apt-get update`:
```
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.9' to '10.11'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its …
```

ci: Loosen apt source verification

---

website/content/docs/connect/l7-traffic/index.mdx

Service resolvers can specify L4 rules such as redirects, or L7 rules such as
hash-based load balancing policies.

Fix caveat about resolvers operating at L4

---

.changelog/11514.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server_connect.go
agent/consul/state/connect_ca.go

Fixes #11367
Previously `secondaryInitialize` would return nil in this case, which prevented the
deferred initialize from happening, and left the CA in an uninitialized state until a config
update or root rotation.
To fix this I extracted the common parts into the delegate implementation. However looking at this
again, it seems like the handling in secondaryUpdateRoots is impossible, because that function
should never be called before the secondary is initialzied. I beleive we can remove some of that
logic in a follow up.
TODO:

ca: properly handle the case where the secondary initializes after the primary

---

.changelog/11522.txt
agent/proxycfg/testing.go
agent/structs/testing_catalog.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/testdata/endpoints/mesh-gateway-newer-information-in-federation-states.envoy-1-20-x.golden
agent/xds/testdata/endpoints/mesh-gateway-older-information-in-federation-states.envoy-1-20-x.golden

Fixes an issue (described in #10132) where if two DCs are WAN federated over mesh gateways, and the gateway in the non-primary DC is terminated and receives a new IP address (as is commonly the case when running them
on ephemeral compute instances) the primary DC is unable to re-establish its connection until the agent running on its own gateway is restarted.
This was happening because we always preferred gateways discovered by the `Internal.ServiceDump` RPC (which would fail because there's no way to dial the remote DC) over those discovered in the federation state, which is replicated as long as the primary DC's gateway is reachable - see the comment in `endpointsFromSnapshotMeshGateway`.

xds: prefer fed state gateway definitions if they're fresher

---

.changelog/11461.txt
agent/config/builder.go
agent/config/builder_test.go

if the provided value is an empty string then the client services
(DNS, HTTP, HTTPS, GRPC) are not listening and the user is not notified
in any way about what's happening.
Also, since a not provided client_addr defaults to 127.0.0.1, we make sure
we are not getting unwanted warnings
Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

config: warn the user if client_addr is empty

---

.changelog/11475.txt
ui/packages/consul-ui/app/adapters/intention.js
ui/packages/consul-ui/tests/integration/adapters/intention-test.js

Filters global intention listing by the current partition rather than trying to use a wildcard.
P.S. @karl-cardenas-coding I think this find came from you so FYI (thankyou!)

ui: Filter global intentions list by selected partition

---

.changelog/11522.txt
agent/proxycfg/testing.go
agent/structs/testing_catalog.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/testdata/endpoints/mesh-gateway-newer-information-in-federation-states.envoy-1-16-x.golden
agent/xds/testdata/endpoints/mesh-gateway-older-information-in-federation-states.envoy-1-16-x.golden

Backport of https://github.com/hashicorp/consul/pull/11522.

Backport 1.9.x: xds: prefer fed state gateway definitions if they're fresher

---

website/data/docs-nav-data.json

This PR removes a broken link to previous Ambassador content that was hosted.

docs: removed broken link to Ambassador

---

.changelog/11514.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server_connect.go
agent/consul/state/connect_ca.go

Backport of #11514
---------
Fixes #11367
Previously `secondaryInitialize` would return nil in this case, which prevented the
deferred initialize from happening, and left the CA in an uninitialized state until a config
update or root rotation.
To fix this I extracted the common parts into the delegate implementation. However looking at this
again, it seems like the handling in secondaryUpdateRoots is impossible, because that function
should never be called before the secondary is initialzied. I beleive we can remove some of that
logic in a follow up.

1.10.x: properly handle the case where the secondary initializes after the primary

---

.changelog/11245.txt
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/connect-proxy-upstream-defaults.envoy-1-18-x.golden
agent/xds/testdata/listeners/connect-proxy-upstream-defaults.v2compat.envoy-1-16-x.golden

Backport of #11245
------------------------
The duo of `makeUpstreamFilterChainForDiscoveryChain` and `makeListenerForDiscoveryChain` were really hard to reason about, and led to concealing a bug in their branching logic. There were several issues here:
* They tried to accomplish too much: determining filter name, cluster name, and whether RDS should be used. 
* They embedded logic to handle significantly different kinds of upstream listeners (passthrough, prepared query, typical services, and catch-all)
* They needed to coalesce different data sources (Upstream and CompiledDiscoveryChain)
Rather than handling all of those tasks inside of these functions, this PR pulls out the RDS/clusterName/filterName logic.
This refactor also fixed a bug with the handling of …

Update filter chain creation for listeners

---

.changelog/11480.txt
command/connect/redirecttraffic/redirect_traffic.go
command/connect/redirecttraffic/redirect_traffic_test.go
sdk/iptables/iptables.go
sdk/iptables/iptables_test.go

Redirect DNS requests to Consul if `-consul-dns-ip` is passed in.

command/redirect_traffic: Redirect DNS requests to Consul if -consul-dns-ip is passed in

---

website/content/docs/agent/options.mdx
website/content/docs/security/acl/acl-rules.mdx

Changed 'segments' in this page to 'resource labels' to disambiguate from 'network segments.
Applied additional feedback.

changed 'segments' in this page to 'resource labels' to disambiguate from 'network segments

---

.changelog/11541.txt
agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go
agent/consul/config_replication.go
agent/consul/config_replication_test.go

Best viewed by commit.
The first two commits add errors when a user attempts to target a secondary DC when writing a partition-exports config entry. The write would have typically been forwarded to the primary, regardless of the source DC and DC of the request. Since this config entry has a narrow scope we will reject certain writes to avoid silent failures.
The third commit prevents writing the config entry to a secondary DC via replication.

OSS Backport: Prevent writing partition-exports entries to secondary DCs

---

agent/consul/server_connect.go
test/integration/connect/envoy/case-wanfed-gw/primary/verify.bats

Surfaced [here](https://github.com/hashicorp/consul/pull/11514/files/d9110136f239b6d89471df028d0ce1093f398ab9..cc5a7ed36c893622f3735977bdc3feb56335d70a#r746828464).
The TrustDomain is populated from the Host() method which includes the
hard-coded "consul" domain. This means that despite having an empty
cluster ID, the TrustDomain won't be empty.

Use ClusterID to check for readiness

---

website/content/docs/k8s/operations/gossip-encryption-key-rotation.mdx

Reformat guide and add more commands to incorporate dedicated Consul namespace for installs and also provide example commands for execing into pods and defining ACL tokens.

docs: provide more example CLI commands and reference Vault

---

website/content/docs/connect/ca/vault.mdx

This PR adds a link to the Learn tutorial that is available for the Vault CA integration.

docs: added link to the Learn tutorial in Vault CA integration page

---

.changelog/11371.txt
ui/packages/consul-ui/app/components/consul/external-source/index.hbs
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/components/pill/index.scss
ui/packages/consul-ui/app/components/popover-menu/layout.scss
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/components/topology-metrics/index.hbs
ui/packages/consul-ui/app/helpers/service/external-source.js
ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/mock-api/v1/connect/_
ui/packages/consul-ui/mock-api/v1/connect/intentions/_
ui/packages/consul-ui/mock-api/v1/connect/intentions/exact
ui/packages/consul-ui/mock-api/v1/health/service/_
ui/packages/consul-ui/mock-api/v1/internal/ui/node/_
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
ui/packages/consul-ui/translations/common/en-us.yaml
ui/packages/consul-ui/translations/components/consul/en-us.yaml

This PR adds support of Consul API Gateway as an external source.
Support appears in the following areas:
- Service List row items
- Top of Service show page
- Service Topology tab - metrics and `Configure metrics dashboard` messaging hidden
- Service Instances tab - list row items
- Service Intentions tab - actions button hidden
- Top of Service Instance show page
BE Support in an internal repo. The BE support has been merged.
Updated every endpoint that had `"external-source": "${fake.helpers.randomize(['kubernetes'])}"`.
Added an acceptance test for hiding the metrics for a Consul API Gateway.

ui: Add Consul API Gateway as an external source

---

.changelog/11472.txt
ui/packages/consul-ui/app/adapters/permission.js
ui/packages/consul-ui/tests/unit/adapters/permission-test.js

See https://github.com/hashicorp/consul/pull/11472
This port additionally adds support for the tokens default partition.
Note: Similar to https://github.com/hashicorp/consul/pull/11472 we are probably going to change this internal endpoint to also inspect the tokens default namespace on the backend. At which point we can revert this commit/PR. Revert will need to happen on 1.10 and 1.11

ui: [Port] Ensure the tokens default nspace (and partition) is passed thru to the auth endpoint

---

.changelog/11505.txt
ui/packages/consul-ui/config/targets.js
ui/packages/consul-ui/docs/testing.mdx

Bumps our browser support to a "rough ~2 years back" approach.
Best way to understand this PR is to read the copy included in the PR.
Suggestions welcome!
cc @david-yu as I know you were interested in this last time we did it.
P.S. Whilst this doesn't touch any code we should probably changelog this, thoughts? edit: changelog added

ui: Bump our browser support

---

website/content/docs/connect/proxies/integrate.mdx

This PR adds a bit more context about how the Consul ACL token can be provided to Envoy or other proxies.

docs: added more information to help endusers with proxies and ACL

---

CHANGELOG.md

I copied these from their respective `release/1.n.x` branches, and added the missing "namespaces" entry under the security section.

add changelog for 1.10.4, 1.9.11, 1.8.17

---

ui/packages/consul-ui/app/services/repository.js

This PR fixes up a tiny typo with `partition` which was causing reconciliation clean up to be performed when it shouldn't be.

ui: Fixup partiton > partition typo

---

ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.scss
ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
ui/packages/consul-ui/app/components/copy-button/index.scss
ui/packages/consul-ui/app/components/definition-table/layout.scss
ui/packages/consul-ui/app/components/form-elements/index.scss
ui/packages/consul-ui/app/components/horizontal-kv-list/index.scss
ui/packages/consul-ui/app/components/horizontal-kv-list/layout.scss
ui/packages/consul-ui/app/components/horizontal-kv-list/skin.scss
ui/packages/consul-ui/mock-api/v1/catalog/connect/_
ui/packages/consul-ui/mock-api/v1/health/service/_

Various CSS tweaks/HTML cleanup around upstreams (but impacts other 'rows') found whilst adding partition support to rows but split off in order to backport down to 1.10 (partition stuff coming in a separate PR)
1. Prefer `{{tooltip}}` to `<Tooltip>`
2. Removed some now unnecessary spans
3. Stop using an empty `class=""` for styling purposes.
4. Renamed any classes used to identify response properties to follow the exact property name but kebab-cased.
5. Fixed up the alignment of things in the rows when used with a 'tiny copy button' (see screengrab) which was minus positioning and knocking things out (pending a proper refactor of our copy button CSS which is from the very very start of things)
6. Theres a bit of whitespacing, which hopefully the GH ignore whitespace thing will help with …

ui: Upstream CSS Tweaks

---

.circleci/config.yml
GNUmakefile

Also add lint-consul-retry to the 'make tools' set.
`go get` to install binaries is deprecated. Also `go install` is faster and doesn't require the weird interim directory and go.mod file.

build: switch to 'go install' over 'go get'

---

agent/local/state.go

Followup to #7189, rewrite outdated comment to reflect current logic in `State.SyncChanges()`.

Update node info sync comment

---

website/content/docs/agent/options.mdx

We mention in the config option that:
>  Should be enabled on all clients and servers in the cluster in order for Connect to function properly
But in https://www.consul.io/docs/connect/configuration we state:
> Enabling Connect requires changing the configuration of only your Consul servers (not client agents).
Also testing it locally seems to confirm the latter.

Connect.enabled config option

---

.changelog/11479.txt
ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/locations/fsm-with-optional.js
ui/packages/consul-ui/app/templates/application.hbs
ui/packages/consul-ui/lib/startup/templates/body.html.js

For our dc, nspace and partition 'bucket' menus, sometimes when selecting one 'bucket' we need to reset a different 'bucket' back to the one that your token has by default (or the default if not). For example when switching to a different partition whilst you are in a non-default namespace of another partition, we need to switch you to the token default namespace of the partition you are switching to.

ui: When certain menus are selected reset either nspace/partition

---

agent/connect/ca/provider_aws.go
agent/connect/ca/provider_consul.go
agent/connect/ca/provider_vault.go
agent/connect/uri_signing.go
agent/connect/uri_signing_test.go
agent/consul/leader_connect_ca.go
agent/consul/server_connect.go
agent/consul/state/config_entry.go

Slightly related to #11347
This was some cleanup I found sitting on a branch. I did this while working on #11514, and I'm opening a PR now so I don't lose the changes.
The idea here is that we only use one field from this struct, and it seems very likely that we'll want to store this ClusterID somewhere else (not on this struct), so by changing this functional signature now it'll be easier to make the larger change later.
This also helps simplify the `ConsulProvider`, because the provider no longer needs to get all `State`, it only needs the provider specific state. I had another commit which changed the interface to make that explicit, but I dropped it for now as it wasn't necessary.

ca: small cleanup of SpiffeIDSigningForCluster args

---

.changelog/11556.txt
ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/README.mdx
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.scss
ui/packages/consul-ui/app/components/consul/upstream/list/README.mdx
ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream/list/index.scss
ui/packages/consul-ui/app/styles/components.scss
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs

Adds a partition badge/label/visual to upstreams and upstream instances.
I also took the opportunity to fill out some documentation for both types of listing that I changed here

ui: Adding partitions + icons to upstreams/upstream instances

---

.changelog/11591.txt
ui/packages/consul-ui/app/components/token-source/index.js

Make sure we store the default `Partition` for a users token.

ui: Store the default partition when logging in

---

ui/packages/consul-ui/app/helpers/render-template.mdx

Adds Engineer documentation for our recently improved `render-template` helper, plus some ideas for further work/improvement here should anyone ever want to pick that up.
Builds on https://github.com/hashicorp/consul/pull/11328 ~and requires that to be merged before this one does.~ This is now merged
@radiantly would be great if you could give this the once over also 🙏 seeing as you worked on this recently.

ui: Add eng docs for our render-template helper

---

.changelog/11573.txt
agent/connect/ca/provider_vault.go
agent/connect/ca/provider_vault_test.go
agent/structs/connect_ca.go
website/content/docs/connect/ca/vault.mdx

- Support vault auth methods for the Vault connect CA provider
- Rotate the token (re-authenticate to vault using auth method) when the token can no longer be renewed
- The unit tests only test auth methods that don't require an external system (like aws or kubernetes)
- I've tested it manually on Kubernetes using the helm chart

Support auth methods for the vault connect CA provider

---

website/content/docs/connect/proxies/integrate.mdx

This PR serves two purposes:
- To deploy the previous changes to the proxy integration page that did not get deployed due to cherry-pick issues
-  Update all code blocks of the proxy integration to use the new code blocks component.

docs: updated proxy page to use new codeblock

---

website/content/docs/security/acl/acl-rules.mdx

Hide whitespace changes!
The docs refer to `admin_partition` and `admin_partition_prefix` whereas our code makes references to `partition` and `partition_prefix`, respectively.

docs: fix name for partition resource labels

---

agent/http_register.go
agent/intentions_endpoint.go

These endpoints are already marked as deprecated in the [docs](https://www.consul.io/api-docs/connect/intentions). This PR adds deprecation notices and moves the `IntentionSpecific-` set of methods to the bottom of the file.

cleanup: Clarify deprecated legacy intention endpoints

---

.changelog/11640.txt
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

See https://www.consul.io/docs/connect/observability/ui-visualization#configuring-dashboard-urls
Allows only `Datacenter`, `Service.Name` (as before) this PR adds `Service.Namespace`.
I've added backport labels here but pretty sure 1.9 and 1.8 will have to be manual.
P.S. There needs to be a follow up after the backports are done to add `Partition` here for 1.11 also.

ui: Add `Service.Namespace` variable to dashboard URL templates

---

website/content/api-docs/namespaces.mdx
website/content/commands/namespace/create.mdx
website/content/commands/namespace/update.mdx
website/content/docs/enterprise/namespaces.mdx

I updated all the (many) places I found that mention these fields to include details about the permissions the ACL token must have to perform the request.
I think probably having these fields on `website/content/docs/enterprise/namespaces.mdx` is a bit redundant, since we document it well in both the API and CLI reference. We should probably link to those instead of duplicating the docs, but I left that clean up for some other time.
Preview the docs here: https://consul-bpyodmi9x-hashicorp.vercel.app/api-docs/namespaces

docs: update docs about namespace default policy/role

---

agent/connect/ca/provider_consul.go
agent/connect/ca/provider_consul_test.go
agent/connect/ca/provider_vault.go
agent/connect/ca/testing.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/server.go

This is a small change I made while working on other bug fixes. I did this as a way of using the ConsulProvider as an "external PKI", but I decided to take a different approach. While the original reason for this change no longer exists, I thought this was still a nice cleanup because it limits the access the Consul Provider has to the state store. This should prevent accidentally using something from the state store that other providers would not have access to.

ca: reduce consul provider backend interface a bit

---

.changelog/11520.txt
ui/packages/consul-ui/app/routes/dc/kv/edit.js
ui/packages/consul-ui/app/services/repository/permission.js

Temporarily revert to pre-1.10 UI functionality by overwriting frontend
permissions. These are used to hide certain UI elements, but they are
still enforced on the backend.
This temporary measure should be removed again once https://github.com/hashicorp/consul/issues/11098
has been resolved
p.s. no-changelog label due to base branch not being main

ui: [Backport] Temporarily force all UI capabilities (#11520)

---

.changelog/11640.txt
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

See #11640
We currently allow only Datacenter, Service.Name, this PR adds Service.Namespace.

ui: [Backport/1.10.x] Add `Service.Namespace` variable to dashboard URL templates (#11640)

---

.changelog/11640.txt
ui/packages/consul-ui/app/templates/dc/services/show.hbs
ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs

See #11640
We currently allow only Datacenter, Service.Name, this PR adds Service.Namespace.

ui: [Backport/1.9.x] Add `Service.Namespace` variable to dashboard URL templates (#11640)

---

.changelog/11640.txt
ui-v2/app/templates/dc/services/show.hbs

See #11640 Note: 1.8.x doesn't have a topology view, therefore we only need to do this in once place.
We currently allow only Datacenter, Service.Name, this PR adds Service.Namespace.

ui: [Backport/1.8.x] Add `Service.Namespace` variable to dashboard URL templates (#11640)

---

agent/consul/coordinate_endpoint.go

No-op change for consistency across endpoints

acl: Fill authzContext from token in Coordinate endpoints

---

agent/consul/catalog_endpoint_test.go
agent/consul/prepared_query_endpoint_test.go

Allow custom ACL root tokens to be passed

cleanup: Refactor test helper

---

.changelog/11681.txt
ui/packages/consul-ui/app/services/data-source/service.js
ui/packages/consul-ui/app/utils/dom/event-source/callable.js

In Consul we have some endpoints that return an empty array/response when you don't have permissions to view anything. This means that a blocking query will start up for that empty request instead of not doing anything (as is the case with a 403)
Additionally when we 'close' a blocking query we cache/save the last received response plus the 'cursor' of where we were. This means when we need to pick the blocking query back up again, we have the previously received data plus the place where we last stopped listening for changes.
If time has passed when we pick up the blocking query and changes have taken place, the "pick this back up again" blocking query will immediately respond with the new changes. If nothing has changed we just resume waiting for updates from exactly the same place …

ui: Don't cache event sources following a 401

---

.changelog/11700.txt
agent/local/state.go
agent/structs/catalog.go
agent/structs/catalog_oss.go

Sync from enterprise
(Enterprise only) For 1.10.x client compatibility with 1.11.x servers

agent: Backport partitioned IDs for updateSyncState 

---

.changelog/11693.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/cache-types/connect_ca_leaf.go

PR addresses https://github.com/hashicorp/consul/issues/10871 / https://github.com/hashicorp/consul/issues/9862 . 
Today, once we HIT/ load up a leaf cert in the agent cache, we can return expired certs or certs signed by a previously rotated CA.
These changes introduces a `MustRevalidate` flag to the `connect_ca_leaf` cache type that we always use on non-blocking queries.
Always setting `MustRevalidate` on non blocking queries means we always "MISS" the cache on non blocking queries. In effect, the headers are now redundant. 
* ~[ ] docs update~ --> I want to pull this into a separate PR bc I want to change some of the docs wording

add MustRevalidate flag to connect_ca_leaf cache type; always use on non-blocking queries

---

.changelog/11693.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/cache-types/connect_ca_leaf.go

Cherry picks https://github.com/hashicorp/consul/pull/11693 into 1.9.x

add MustRevalidate flag to connect_ca_leaf cache type; always use on non-blocking queries (#11693)

---

.changelog/11671.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_test.go
agent/structs/connect_ca.go

Fixes #10826 
Fixes #10532
We were not saving the leaf signing cert on the `CARoot` when the Vault provider was initialized. This was only a problem for API users (not envoy and xDS) because [this extra code](https://github.com/hashicorp/consul/pull/11661#discussion_r757059682) was masking the bug.
In #11661 I'd like to remove that masking code (because it is unnecessary, and because we need to change the Provider interface, so fewer callers makes that easier).
This PR updates an existing test to catch the bug, then fixes the bug. I added a few more assertions to both the primary and secondary test cases to make sure we did not have a similar bug in other places.

ca: fix storing the leaf signing cert with Vault provider

---

agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server_test.go

While working on the CA system it is important to be able to run all the tests related to the system, without having to wait for unrelated tests. There are many slow and unrelated tests in agent/consul, so we need some way to filter to only the relevant tests.
This PR renames all the CA system related tests to start with either:
*  `TestCAMananger` for tests of internal operations that don't have RPC endpoint, or
* `TestConnectCA` for tests of RPC endpoints. 
This allows us to run all the test with:
go test -run 'TestCAMananger|TestConnectCA' ./agent/consul
The test naming follows an undocumented convention of naming tests as follows:
Test[<struct name>_]<function name>[_<test case description>]
I tried to always keep Primary/Secondary at the end of the description, and `_Vault_` has to …

ca: make test naming consistent

---

.changelog/11672.txt
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go

Fixes #11662
Branched from #11671 
Two other instance of this same bug were fixed a year+ ago in #6513 and  #7012, but this last one remained.
The test failed before the fix, and I extracted a new function for this since the logic is the same in all places, and the method name helps indicate the significance of this intermediate certificate.
We already have logic to fix the `SigningKeyID` on stored `CARoot` when the `CAMananger` is initialized, so we don't need to add more logic for it.

ca: set the correct SigningKeyID after config update with Vault provider

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/catalog_endpoint_test.go
agent/consul/health_endpoint.go
agent/consul/health_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the health endpoints.

health: support `ResultsFilteredByACLs` flag/header

---

agent/consul/kvs_endpoint.go
agent/consul/kvs_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the KV `List` and `ListKeys` endpoints.

kv: support `ResultsFilteredByACLs` flag/header

---

agent/event_endpoint.go
agent/event_endpoint_test.go

Adds support for the `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the event list endpoint.

event: support `X-Consul-Results-Filtered-By-ACLs` header in list endpoint

---

agent/consul/config_endpoint.go
agent/consul/config_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the config list endpoints.

config: support `ResultsFilteredByACLs` in list/list all endpoints

---

agent/consul/acl_endpoint.go
agent/consul/acl_endpoint_oss.go
agent/structs/acl_oss.go

Cross port of ent #1383 "Reject non-default datacenter when making partitioned ACLs"
On the OSS side this is a minor refactor to add some more checks that are no-ops on oss, but add function to the enterprise code.

Cross port of ent #1383

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/intention_endpoint.go
agent/consul/intention_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the intention endpoints.

intention: support `ResultsFilteredByACLs` flag/header

---

agent/acl.go
agent/acl_oss.go
agent/acl_test.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go

Adds support for the `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the agent-local endpoints.

agent: support `X-Consul-Results-Filtered-By-ACLs` header in agent-local endpoints

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/session_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the session endpoints.

sessions: support `ResultsFilteredByACLs` flag/header

---

website/content/docs/discovery/dns.mdx

Hello @jkirschner-hashicorp , 
As promised here is a doc change PR adding alternative domain section to  dns.mdx. 
Please let me know if  there are any change you would like me to make. 
Thanks.

added Alternative Domain section to dns page in docs

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/coordinate_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the node coordinates endpoint.

coordinate: support `ResultsFilteredByACLs` flag/header

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/catalog_endpoint.go
agent/consul/catalog_endpoint_test.go
agent/consul/internal_endpoint.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the catalog endpoints.

catalog: support `ResultsFilteredByACLs` flag/header

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/federation_state_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the federation state endpoints.

fedstate: support `ResultsFilteredByACLs` flag/header

---

.changelog/11720.txt
agent/agent.go
agent/config/builder.go
agent/config/config.go
agent/config/runtime.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/config/testdata/full-config.hcl
agent/config/testdata/full-config.json
agent/consul/config.go
agent/consul/server.go
go.mod
go.sum

In addition to just swapping out bbolt for bolt this also exposes a configuration to allow for disabling boltdb freelist syncing.
Finally it also enables metrics emission for the raft boltdb store to give us insights into boltdb performance.

Use bbolt instead of the legacy bolt implementation

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/prepared_query_endpoint.go
agent/consul/prepared_query_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the prepared queries list and execute endpoints.
Note: we only set the `ResultsFilteredByACLs` flag if **named** queries were removed from the result set. This is because un-named queries are treated as ephemeral and can only be listed by a management token.

query: support `ResultsFilteredByACLs` in query list endpoint

---

agent/consul/acl.go
agent/consul/acl_test.go
agent/consul/internal_endpoint.go
agent/consul/internal_endpoint_test.go

Adds support for the `ResultsFilteredByACLs` flag, and corresponding `X-Consul-Results-Filtered-By-ACLs` HTTP header (introduced in #11569) to the internal endpoints.
Note: I didn't update `GatewayIntentions` in this PR as this is handled by https://github.com/hashicorp/consul/pull/11612.

internal: support `ResultsFilteredByACLs` flag/header

---

.changelog/11737.txt
api/partition.go
test/integration/connect/envoy/run-tests.sh

Renamed for consistency with the HTTP API and CLI flags.

Rename internal references for admin partitions to be "partition"

---

.changelog/11738.txt
agent/consul/catalog_endpoint.go
agent/consul/fsm/snapshot_oss_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_oss.go
agent/consul/state/catalog_oss_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go
agent/consul/state/intention.go
agent/consul/state/schema.go
agent/consul/state/schema_test.go
agent/structs/structs.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy.envoy-1-20-x.golden

There are a few changes here:
- Transparent proxy listener configuration needs to account for the new tagged address with virtual IPs generated by Consul. These should be considered both for cross-partition and partition-local traffic. The plain "virtual" tagged address should only be used for partition-local traffic, since the address is not guaranteed to be unique across partitions.
- The existing way of computing upstreams/downstreams from intentions was based on watching the "services" table and then evaluating a service's intentions against the unique service names. This won't work in 1.11 because the services table does not have a wildcard partition index, and cross-partition upstreams from intentions are supported. This watch was replaced with a watch of a table that stores service …

Transparent proxy support for cross-partition

---

.changelog/11668.txt
ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs

This is definitely the last application facing FIXME for admin partitions.
This PR adds the correct link to the Admin Partition empty state.
I also took the opportunity to upgrade to use `<Action />`

ui: Add documentation link for partitions

---

.changelog/11679.txt
ui/packages/consul-ui/app/components/consul/discovery-chain/README.mdx
ui/packages/consul-ui/app/components/consul/discovery-chain/index.js
ui/packages/consul-ui/app/components/consul/discovery-chain/utils.js
ui/packages/consul-ui/mock-api/v1/discovery-chain/_
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-alternate-services-test.js
ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-resolvers-test.js

Partitions means that all of the discovery chain identifiers have an additional segment in them to convey the partition.
This PR adds the necessary code to pick that up so the viz works with a Consul 1.11 build.
Please note this PR does not add any extra user facing functionality, only support for new partition values in the HTTP response.
I also added a very bare docs file for the DiscoChain component while I was there.

ui: Adds basic support for the Routing tab viz with partitions

---

ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/filter/predicates/service.js
ui/packages/consul-ui/app/models/service.js
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/translations/common/en-us.yaml

Adds an extra source filter if you have an Services exported from a different partition:
Note the base branch here is previous related work, not main.

ui: Add exported service partition to the source filter menu

---

ui/packages/consul-ui/app/components/consul/bucket/list/index.hbs
ui/packages/consul-ui/app/components/consul/service/list/index.hbs
ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
ui/packages/consul-ui/app/components/popover-select/index.scss
ui/packages/consul-ui/app/filter/predicates/service.js
ui/packages/consul-ui/app/models/service.js
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/app/templates/dc/services/show/services.hbs
ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
ui/packages/consul-ui/mock-api/v1/health/service/_
ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
ui/packages/consul-ui/mock-api/v1/internal/ui/services
ui/packages/consul-ui/translations/common/en-us.yaml

Follow on from https://github.com/hashicorp/consul/pull/11702 (which is also the base branch here).
This PR adds cross partition linking between the Service list and other places where we use a `partition / namespace` 'bucket list'. Additionally we took the opportunity to roll out of new BucketList component to other areas where we use the same `partition / namespace` form.
Small note: Whilst doing this I had a little internal fight (😆 ) as to where to do the "use the route param, if not use the users token, if not default to `default`" thing. After quibbling about whether to put the "default to `default` if `@partition` wasn't set" in the component, I decided to put everything at the very top level in the route template. If this quibble turns out to be the correct way to go (we probably …

ui: Add cross partition linking and rollout BucketList

---

.changelog/11748.txt
agent/grpc/client_test.go
agent/grpc/resolver/resolver.go
agent/router/grpc.go
agent/router/router.go

Fixes a bug whereby servers present in multiple network areas would be
properly segmented in the Router, but not in the gRPC mirror. This would
lead servers in the current datacenter leaving from a network area
(possibly during the network area's removal) from deleting their own
records that still exist in the standard WAN area.
The gRPC client stack uses the gRPC server tracker to execute all RPCs,
even those targeting members of the current datacenter (which is unlike
the net/rpc stack which has a bypass mechanism).
This would manifest as a gRPC method call never opening a socket because
it would block forever waiting for the current datacenter's pool of
servers to be non-empty.
NOTE: this should probably be backported to 1.10 but it'll have to be manual.

areas: make the gRPC server tracker network area aware

---

.changelog/11670.txt
ui/packages/consul-ui/app/components/consul/intention/list/README.mdx
ui/packages/consul-ui/app/components/tabular-collection/index.scss

I also added a very basic Consul::Intention::List documentation page here, mostly for isolation whilst I was looking at this, but at some point in the future (probably when working on it next instead of just tweaking a value) we should probably fill that out in more detail.
On to the fix:
Before:
After:
Actually, need to take a look at how far back we can/need to backport this 👀 , at least 1.10.x, but need to check 1.9 and 1.8.

ui: Stop tables overlapping with their headers when scrolling

---

ui/packages/consul-ui/app/templates/head.hbs

This file was used quite a way back for `ember-page-title`. All in all we no longer use this file anywhere.

ui: remove old head.hbs file we don't need

---

ui/packages/consul-ui/app/utils/create-fingerprinter.js

Ember Data requires the usage of unique ID to identify its records in the frontend, and we use a centralized function to do that for all records. There are occasions where it can't make an ID, usually this is a bug our side, but there are occasions where Consul might not be giving us the data needed to make an ID, for example if a Service comes down to us with a blank Name. Whilst this isn't a problem to be fixed in the UI, I thought we could make an improvement here by giving a little more info as to why the UI cannot make a unique ID.
This is currently semi-hidden away in the javascript console, but we could potentially surface this in the UI itself as a larger task. I figured this smaller task could help folks in the meantime if they hit upon this as they might open up the javascript …

ui: Improve error messaging for when we can't make a slug

---

.changelog/11671.txt
.changelog/11672.txt
agent/connect/ca/provider.go
agent/connect/ca/provider_vault.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server_test.go
agent/structs/connect_ca.go

Backport #10476 (to fix conflicts), #11671, #11713, #11672
Conflicts were all over, but they were trivial to resolve (ex: tests on `main` that did not exist were pruned from the conflict).

[1.10.x] Backport of CA system bug fixes

---

.changelog/11671.txt
agent/connect/ca/provider.go
agent/connect/ca/provider_vault.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/server_test.go
agent/structs/connect_ca.go

Backport #10476 (to fix conflicts), #11671, #11713, #11672
Conflicts were all over, but they were trivial to resolve (ex: tests on main that did not exist were pruned from the conflict).

[1.9.x] Backport of CA system bug fixes

---

.changelog/11757.txt
agent/config/runtime_test.go
agent/consul/discoverychain/compile.go
agent/consul/discoverychain/compile_test.go
agent/consul/state/config_entry.go
agent/consul/state/config_entry_test.go
agent/structs/config_entry_discoverychain.go
agent/structs/config_entry_discoverychain_test.go
api/config_entry_discoverychain.go
api/config_entry_discoverychain_test.go
command/config/write/config_write_test.go
test/integration/connect/envoy/run-tests.sh

This PR updates the discovery chain so that routes, splits, and redirects can route to services in other partitions.

Allow cross-partition references in disco chain

---

.changelog/11744.txt
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/agent_test.go
agent/config/builder.go
agent/config/deprecated_test.go
agent/config/runtime_test.go
agent/config/testdata/TestRuntimeConfig_Sanitize.golden
agent/consul/acl.go
agent/consul/acl_test.go
agent/token/persistence.go
agent/token/persistence_test.go
agent/token/store.go
agent/token/store_test.go

Following the external-facing renaming of the `agent_master` ACL token to `agent_recovery` (in #11665 and #11669) this PR is the first of a series to fix internal references to the old name, starting with the `agent/token` package.
It's worth noting that this changes the name of the field in the on-disk token persistence file (see: a876f5263aadde1015fecb5370b934d00d41f2de) but maintains support for reading files created by earlier versions of Consul, with the previous name.

agent/token: rename `agent_master` to `agent_recovery` (internally)

---

agent/agent_endpoint.go
agent/agent_endpoint_test.go

Continues issue #11396 
**Overview:**
The goal of this PR is to transition the rest of the endpoint tests in ``agent_endpoint_test.go`` to use ServeHTTP. This is going to be a large change so I’m hoping to get some progressive feedback.

Transition all endpoint tests in agent_endpoint_test.go to go through ServeHTTP

---

website/content/docs/discovery/dns.mdx

We overlooked the location of the placement of the alt domain docs in #11458, as discussed [here](https://github.com/hashicorp/consul/pull/11458#issuecomment-985908493). This PR improves (fixes) the location.

improve location of DNS alt domain docs section

---

.changelog/11681.txt
ui/packages/consul-ui/app/services/data-source/service.js
ui/packages/consul-ui/app/utils/dom/event-source/callable.js

ui: [Backport 1.9.x] Don't cache event sources following a 401

---

.changelog/11681.txt
ui-v2/app/services/data-source/service.js
ui-v2/app/utils/dom/event-source/callable.js

ui: [Backport 1.8.x] Don't cache event sources following a 401

---

.changelog/11758.txt
agent/consul/rpc.go
agent/structs/structs_oss.go

There are cases where we cannot safely forward along a `Partition` value to remote servers. Specifically in the case where the server is "partition-aware" but not "partition-capable" -- these are typically servers on 1.10.x that can parse/handle EnterpriseMeta with a `Partition` value. Having a value, but not applying it correctly can lead to inadvertent filtering of `memdb` requests since these values are blindly forwarded through to the `memdb` query.
This adds the plumbing to unset the value specifically in the case of RPC prior to forwarding requests to a remote DC which is effectively a no-op for Consul OSS.

rpc: Unset partition before forwarding to remote datacenter

---

agent/connect/ca/provider_consul_test.go
agent/connect/ca/testing.go
agent/consul/fsm/commands_oss.go
agent/consul/leader_connect_ca_test.go

Previously we had a couple copies that reproduced the FSM operation.
These copies introduce risk that the test does not accurately match
production.
This PR removes the test versions of the FSM operation, and exports the
real production FSM operation so that it can be used in tests.
The consul provider tests did need to change because of this. Previously
we would return a hardcoded value of 2, but in production this value is
always incremented.

ca: use the real FSM operation in tests

---

ui/packages/consul-ui/app/styles/themes.scss

We recently added our 'auto theming' `--tone` colors, which are just reversed when using a dark theme. We also built in an escape hatch to be able to use colors that we didn't want ever to be themed i.e. we can then inject from The Outside using specific CSS selecting using a non `--tone`ed, non-reversing color just for those cases.
The TLDR:
Before:
After:
This one specifically was a good one to "go wrong" as it gave me a chance to have a little bit of a think how this approach would work with our ['composite color set' `%frame` idea from a while back](https://github.com/hashicorp/consul/pull/4623), as our 'dangerous button' styling here uses a `%frame`. First impressions of that are that we probably need a similar set of `%frame-tones` here as well as similar escape hatches. Another …

ui: Make 'dangerous' buttons have white text even in dark theme

---

ui/packages/consul-ui/app/components/consul/intention/notifications/index.hbs
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/app/routes/dc/services/show/topology.js
ui/packages/consul-ui/app/services/feedback.js

I noticed that some of our notifications had lost their text content following our reshuffle of notifications in https://github.com/hashicorp/consul/pull/11577 (towards getting rid of the old style notifications). The changes here all kind of make sense:
- The intention notifications here are for the topology view which still have a small bit of old code that we are yet to move over - all other intention areas use the new approach still.
- "Using" a token is part of our completely untouched for ages (but soon to be) ACLs area and is still therefore using the old style
Please note when I say 'style' above I mean 'style of code' not 'visual style'
If we were keeping this code longer term, there would be questions about making this less copypasta i.e. there are better ways to do it - but as …

ui: Fixup notifications for token using and topology intention saving

---

agent/connect/ca/testing.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/state/connect_ca.go
agent/structs/connect_ca.go
testrpc/wait.go

There's a bunch of stuff here, so probably best viewed by individual commit. I'll try to comment on any interesting lines. I've been running the tests with `-count=100` in a loop and the flakes appear to be fixed now.
Primarily this PR:
1. adds a test for using the Vault provider in a secondary PR (previously we mostly only tested with Vault provider in the primary)
2. improves some existing RenewIntermediate tests to be less flaky (hopefully not flaky at all!) and to be less verbose, so easier to read.
Other changes made:
* adds an `Active()` method to both the `IndexedCARoots` (the RPC response) and `CARoots` (the state store result) so that we can stop repeating the "lookup active root" loop in dozens of places.
I'm planning on back porting to reduce conflicts when I back port other …

ca: improve test coverage for RenewIntermediate

---

.changelog/11507.txt
version/version.go
version/version_test.go

Improved performance and added benchmark for func version.GetHumanVersion.
Instructions:
```
$ go install golang.org/x/perf/cmd/benchstat@latest
$ go test -bench=GetHumanVersion -count 5 -benchmem ./version > old.txt
$ go test -bench=GetHumanVersion -count 5 -benchmem ./version > new.txt
$ benchstat old.txt new.txt
```
Results
```
name               old time/op    new time/op    delta
GetHumanVersion-8     177ns ± 2%      80ns ± 3%  -54.53%  (p=0.008 n=5+5)
name               old alloc/op   new alloc/op   delta
GetHumanVersion-8     32.0B ± 0%     16.0B ± 0%  -50.00%  (p=0.008 n=5+5)
name               old allocs/op  new allocs/op  delta
GetHumanVersion-8      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.008 n=5+5)
```

Improved performance of the version.GetHumanVersion function by 50% on memory allocation.

---

.changelog/11791.txt
ui/packages/consul-ui/app/serializers/partition.js
ui/packages/consul-ui/mock-api/v1/partitions
ui/packages/consul-ui/tests/integration/serializers/partition-test.js

Pre-1.11.RC the partition listing API returned a `Partition: []` property. This has now been changed to `[]`.
This PR reflects that change.

ui: Change partitions to expect `[]` from the API

---

agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_schema.go
agent/consul/state/catalog_test.go

This PR fixes a bug that could happen when the most recently assigned virtual IP was freed and reassigned.

state: fix freed VIP table id index

---

agent/consul/leader.go
agent/consul/leader_connect.go
agent/consul/leader_test.go
agent/consul/server.go

This PR moves the server version check for enabling virtual IPs into a leader goroutine to make it more consistent with other logic of this type and limit the log warning rate a bit.

leader: move the virtual IP version check into a goroutine

---

ui/packages/consul-ui/app/components/consul/bucket/list/README.mdx
ui/packages/consul-ui/app/components/consul/bucket/list/index.hbs
ui/packages/consul-ui/app/components/consul/bucket/list/index.scss
ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
ui/packages/consul-ui/app/components/definition-table/layout.scss

I noticed that our Intention view/readonly pages had an old design for showing our `partition / namespace` 'BucketList'. Additionally in this page we need to additionally show the service name, so I added the ability to include that in the 'BucketList' - for which I told myself that a `Service` is still a bucket as it contains `Service Instances` 😬 
Before:
After:

ui: reuse BucketList for intention view pages

---

.changelog/11767.txt
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
ui/packages/consul-ui/mock-api/v1/connect/intentions/exact
ui/packages/consul-ui/tests/acceptance/dc/intentions/read-only.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/intentions/read-only-steps.js

I noticed we were no longer showing our specially designed read only page for intentions due to an undefined handlebars variable, so I fixed that up and added an acceptance test to prevent this happening here again.
It seems like this bug is only/specifically in 1.10.4 (and currently unreleased 1.11 branch)

ui: Ensure we show a special readonly page for intentions

---

.changelog/11801.txt
ui/packages/consul-ui/app/locations/fsm-with-optional.js
ui/packages/consul-ui/app/services/ui-config.js

We currently use special non-DNS permitted prefixes to detect the URL segments for partitions and namespace in order to keep our URLs as backwards compatible as possible whilst avoiding the use of query parameters `?` for identifying completely different sets of data (as opposed to different views of the same data, which is what we mostly use query params for). For example our URLs can look like any of the following:
- `/ui/datacenter-name/services/service-name`
- `/ui/~namespace-name/datacenter-name/services/service-name`
- `/ui/-partition-name/~namespace-name/datacenter-name/services/service-name`
We decided to change the nicer looking `-` to a `_` for the less common partition segment in order to keep the nicer `-` for other potentially more common purposes.
TLDR; This PR changes the …

ui: Change the URL prefix of partitions from `-` to `_`

---

.changelog/11804.txt
ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
ui/packages/consul-ui/app/components/consul/intention/form/index.js
ui/packages/consul-ui/app/services/repository/intention.js

Previously it was possible to select a wildcard partition when trying to make an intention, but as this is not possible, when doing so you would see one of our UI backend errors, which is a little confusing.
[Preview link for this PR](https://consul-ui-staging-2yg4bxp50-hashicorp.vercel.app/ui/dc1/intentions/create) notice the 2 partition menus have 'default' in them, not `* (All Partitions)`.
[Borken Preview Link](https://consul-ui-staging-gihql7391-hashicorp.vercel.app/ui/dc1/intentions/create) is very borken as it lets you specify `* (All Partitions)` which leads to the response when you try to save an intention into a non-mock Consul being very borked 😅 
This PR removes being able to select a wildcard partition from the intention menus.

ui: Disable setting wildcard partitions for intentions

---

.changelog/11803.txt
ui/packages/consul-ui/app/components/app/index.scss
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs

This PR adds the Consul version info back into the more visible footer of the UI (bottom left corner)

ui: Add version information back into the footer

---

agent/consul/leader.go
agent/consul/leader_test.go

This query has been incorrectly querying by accessor ID since New ACLs
were added. However, the legacy token compat allowed this to continue to
work, since it made a fallback query for the anonymousToken ID.
PR #11184 removed this legacy token query, which means that the query by
accessor ID is now the only check for the anonymous token's existence.
This PR updates the GetBySecret call to use the secret ID of the token.
--------------
We observed the impact of this issue in a k8s acceptance test. Existing 
anonymous token policies were being wiped on leadership establishment.

Use anonymousToken when querying by secret ID

---

.changelog/11818.txt
agent/http.go

When a URL path is not found, return a non-empty message with the 404 status code to help the user understand what went wrong. If the URL path was not prefixed with '/v1/', suggest that may be the cause of the problem (which is a common mistake).
```
curl --request GET --verbose localhost:8500/agent/services
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /agent/services HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Mon, 13 Dec 2021 16:32:45 GMT
< Content-Length: 87
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
Invalid URL …
```

http: improve 404 Not Found response message

---

.changelog/11826.txt
agent/proxycfg/connect_proxy.go
agent/proxycfg/ingress_gateway.go
agent/proxycfg/snapshot.go
agent/proxycfg/state_test.go
agent/proxycfg/upstreams.go
agent/structs/connect_proxy_config.go
agent/xds/clusters.go
agent/xds/clusters_test.go
agent/xds/endpoints.go
agent/xds/endpoints_test.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/routes.go

In a k8s acceptance test we observed a situation where a discovery watch was cancelled, then a cache update event was received for it. This created a stray entry in the DiscoveryChain map which was no longer associated with an upstream.
This PR adds several layers of mitigation for this:
1. Prevent storing chains when they do not have known upstreams
2. Validate that chains are associated with upstreams when generating xDS resources
3. Clean up the DiscoveryChain map separately from WatchedDIscoveryChains

[OSS] Handle discovery chain race

---

website/content/docs/connect/config-entries/ingress-gateway.mdx
website/content/docs/connect/gateways/ingress-gateway.mdx

This PR adds documentation for features added in #10903 and #11163.
These are "low-level" features designed to be used by systems integration builders rather than typical-end users but are included to provide a complete example so this functionality can be used. I don't anticipate a Learn guide for this feature as it's more of an integration interface so included a somewhat guide-like complete example of getting the whole feature to work.
If anyone can think of a better place to put the more detailed guide than the ingress gateway overview page I'd be open to suggestions.
Preview: https://consul-o89qrzjyl-hashicorp.vercel.app/docs/connect/config-entries/ingress-gateway#sds

Document SDS for ingress gateways

---

website/content/docs/connect/config-entries/exported-services.mdx

This adds documentation about the required `Name` field to the exported-services config entry kind (which must match the partition of the config entry).

docs: Update exported-services page to include required Name field

---

.github/workflows/build.yml

This was causing a rogue `-` to appear in artifacts. This was fixed for the `release/1.10.x` series but never made its way back into `main` or `release/1.11.x` so this is going to fix it for future releases.

Update product version extraction for CRT

---

.changelog/11830.txt
ui/packages/consul-ui/app/routes/dc.js

When the application initially loads we request a list of namespaces from the backend within the application model hook in order to immediately populate the namespace menu in the top left of the UI.
We also use this application model namespace list to find 'valid' namespaces to mark as 'selected' in order to show the currently selected menu item. If we can't find the specified namespace (taken from the URL segment) then we default to just show the 'default' namespace instead.
The namespace menu is refreshed everytime it is opened (we fire off a request to get a refreshed response) - importantly this request doesn't refresh the model on the application model hook, which is the one we sometimes use to check for a 'valid' selection 😬 .
The application model hook is also not refreshed when …

ui: Fix sticky namespace selector

---

.github/workflows/build.yml
.release/ci.hcl

Following up on a request from Jared Kirschner, this PR builds a new darwin arm64 binary. When this PR is merged to main or a release branch, the binary will be signed and notarized just like the other darwin binary.
An example binary built from this branch can be downloaded from github artifacts and smoke tested here: https://github.com/hashicorp/consul/actions/runs/1580741218
A note can be added to the changelog when the next release goes out saying that we will support darwin arm64 binaries from this release onwards.

Add darwin arm64 support

---

.changelog/11854.txt
go.mod
go.sum

We had mistakenly thought upgrading go version was enough; Consul configures http2 manually and needs to update `golang.org/x/net` as well

Update golang.org/x/net to address CVE-2021-44716

---

website/content/docs/connect/config-entries/exported-services.mdx

https://github.com/hashicorp/consul-k8s/pull/902 - reflects PR for ExportedServices. Also found it a little odd that Services was set to h4.

docs: ExportedServices CRD typo and change heading for services

---

website/content/api-docs/kv.mdx

This PR fixes a typo in the Consul KV Store API documentation.

docs: fix typo in KV store API

---

.changelog/11803.txt
ui/packages/consul-ui/app/components/app/index.scss
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs

See https://github.com/hashicorp/consul/pull/11803 and #11850 (which was also added post initial PR)

ui: [Backport 1.10.x] Add version information back into the footer (#11803)

---

website/content/docs/connect/config-entries/exported-services.mdx
website/content/docs/connect/config-entries/index.mdx

Adds Enterprise tag to Exported Services Config entry and adds to Overview

docs: add Exported Services to overview

---

.github/scripts/metrics_checker.sh
.github/workflows/pr-metrics-test-checker.yml

This PR wraps a small bash checker in a GH action. The checks are actually done on "diffs" and not necessarily the actual content. That said, I think this get us 80% there!
* quick eye check for reviewers on whether or not this PR has metric behavior changes in it 
* reminder to contributors to add testing for the metric behavior
* helps us build metric behavior testing in the long run
This is not meant to be a replacement for a good old fashioned, through review. It's meant to have the same call to action as a change log PR checker.
* I did a fair amount of testing in the enterprise repo (mostly manual); happy to reproduce some of it here on request.
At present, there are some metric behavior checks like [here](https://github.com/hashicorp/consul/pull/11231/files#diff-472e516d540a393b4317 …

add a metrics test check GH action

---

website/content/api-docs/agent/index.mdx
website/content/commands/force-leave.mdx

Document `prune` parameter added in #6571 and `wan` parameter added in
#11722.

Document /v1/agent/force-leave prune and wan params

---

.changelog/11868.txt
ui/packages/consul-ui/app/components/buttons/index.scss
ui/packages/consul-ui/app/components/modal-dialog/README.mdx
ui/packages/consul-ui/app/components/modal-dialog/index.js
ui/packages/consul-ui/app/templates/dc/acls/policies/-form.hbs
ui/packages/consul-ui/tests/pages/dc/acls/policies/edit.js

Fixes https://github.com/hashicorp/consul/issues/11269
https://github.com/hashicorp/consul/issues/11269#issuecomment-956110990 is pretty good explanation of whats happening here.
In order to see this failing on a preview site/during dev:
1. Enable ACLs for the dev UI using our bookmarklets/cookie values.
2. Click the login button in the top right of the UI and use any value as a token to login.
3. Go to the policy page using the [Policies] link in the left hand main navigation, then click on any policy (apart from Global Management).
4. Depending on randomness you will should see a list of tokens under "Applied to the following tokens" towards the bottom of the form (you must have 'attached tokens' for this to be a problem)
5. Click the delete button and witness the magical "Delete Button …

ui: Fix up missing policy delete warning modal

---

ui/packages/consul-ui/app/services/repository/permission.js
ui/packages/consul-ui/tests/acceptance/dc/intentions/index.feature

TLDR Remove an additional `s`.
---
ACL intention rules are called `intention` not `intentions`. 
The code involved here temporarily ignores the result of our HTTP API result as it does not function exactly how we need (more info in this issue but _not_ essential reading for PR purposes: https://github.com/hashicorp/consul/pull/11520), the original PR to do this ignore is https://github.com/hashicorp/consul/pull/11520.
The ignore essentially loops through the response of the HTTP request we make to the auth HTTP API and overwrites the ones which could be wrong (only a subset hence the `includes`) with a hardcoded `Allow: true`, which means we still show UI links for places that, once navigated or submitted to, may result in a 403 response from the backend.
The original desired UX …

ui: Check for `intention` ACL resources, not `intentions` ACL resources

---

.changelog/11892.txt
ui/packages/consul-ui/app/components/error-state/README.mdx
ui/packages/consul-ui/app/components/error-state/index.hbs
ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
ui/packages/consul-ui/app/templates/dc/services/index.hbs
ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs

1. Add an empty state header to the node listing page to make it consistent with other pages (use `CONSUL_NODE_COUNT=0` cookie value to see this on the node listing page)
2. Add additional [Login] button to both Node listing empty state and "Per Service Intentions" empty state, again our dev cookies will help here for viewing.
3. Noticed that `services` is now undefined in our Service List template, we should be using `items` instead. Consequently our slightly better tailored message wasn't showing at all, with this fix it will. You can see the difference pre and post PR for this one by using the search bar to search for a service that doesn't exist.
4. I noticed that we were missing a `@` in our ErrorState component, the small consequence of this is when we have an error that specified a …

ui: Various empty state improvements/fixups

---

.changelog/11774.txt
ui/packages/consul-ui/app/routes/dc/services/show/instances.js
ui/packages/consul-ui/app/search/predicates/service-instance.js
ui/packages/consul-ui/translations/common/en-us.yaml

When searching through our Service Instance list, you can choose to limit the search to Meta data, but in Service Instance listing we have Service Meta _and_ Node Meta available to us. Previous to this PR both these options would read 'Meta'.
This PR changes these texts to read Service Meta and Node Meta.
We also took the opportunity to add Node Name here to the list of options you can limit the search to.

ui: Fixup names of Meta for instance search, also add Node

---

.changelog/11891.txt
ui/packages/consul-ui/app/routing/route.js

Semi-related to https://github.com/hashicorp/consul/issues/11098 but not entirely, there is also an extra bit of gymnastics involved here for backporting/version complications, so the description is that extra bit complicated.
As of Consul UI 1.10 we started inspecting permissions ahead of time in order to decide which links/page/capabilities to show the user. The purpose was to prevent unnecessary HTTP requests from being performed and/or wasted time for users (for example filling out forms that are impossible to save on the backend dues to ACL permissions).
We added a `beforeModel` hook to all of our Routes (via our custom `route:basic` that all app Routes also inherit from). This hook would use the ahead of time permissions to make a decision on whether to proceed to the `model` hook, …

ui: Remove any route level auth checks

---

website/content/docs/enterprise/admin-partitions.mdx
website/content/docs/k8s/connect/connect-ca-provider.mdx

K8s Vault CA config docs:
* Re-add filename label on K8s Connect CA config.
* Remove call to `jq` when retrieving CA configuration.
* Clarify `connect.ca_config` and `connect.ca_provider` agent configs
are only used at cluster initialization.
Admin Partitions tutorial:
* Fix Helm client values filename.
* Use kubectl's template output to base64 decode Consul bootstrap token.

Minor doc fixes to K8s CA and Admin Partitions guides

---

agent/consul/autopilot_test.go
agent/consul/intention_endpoint_test.go
agent/consul/internal_endpoint_test.go
agent/consul/server_test.go
agent/consul/system_metadata_test.go

Our tests should run with the current version by default.
Also deprecate some functions, see commit message for the rationale.

testing: stop using an old version in testServer

---

.changelog/11774.txt
ui/packages/consul-ui/app/routes/dc/services/show/instances.js
ui/packages/consul-ui/app/search/predicates/service-instance.js
ui/packages/consul-ui/translations/en-us.yaml

Manual backport of https://github.com/hashicorp/consul/pull/11774
In 1.10.x we moved our translations file to use a split up files instead of one big one, hence the need for a manual intervention. This manual backport adds the necessary translation strings to the "one big file" instead of the split up ones.
No changelog label here as the changelog checker doesn't work if the base branch isn't main.

ui: [Backport 1.9.x] Fixup names of Meta for instance search, also add Node

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx
website/content/docs/nia/terraform-modules.mdx

Changes:
- Add `names` to `condition "services"` and `source_input "services"`
- Update any language that suggests `condition "services"` and `source_input "services"` only supports `regexp`
- Remove language around "default condition" and relationship to default relationship with `task.services` (see commit for details)
Links to previews:
- [configs](https://consul-8ducgp3y4-hashicorp.vercel.app/docs/nia/configuration#services-condition)
- [task page](https://consul-8ducgp3y4-hashicorp.vercel.app/docs/nia/tasks#services-condition)
- [tf module page](https://consul-8ducgp3y4-hashicorp.vercel.app/docs/nia/terraform-modules#services-source-input)

docs/nia: new config field names for services condition/source_input

---

test/integration/connect/envoy/case-wanfed-gw/global-setup.sh

We recently merged https://github.com/hashicorp/consul/pull/11781 which fixed permissions for generated private keys.
Our integration test needs to be updated to `docker cp` these keys with the correct permissions now.

Fix integration test with updated file perms

---

website/content/docs/k8s/installation/install.mdx

add the  missing namespace flag to kubectl port-forwad

Update install.mdx; add port-forward missing namespace flag

---

website/content/docs/nia/api/tasks.mdx
website/content/docs/nia/cli/task.mdx

Adds docs for the delete task API and CLI. Also makes some general changes to the existing docs:
- Updates the API and CLI format of existing task commands to use a table format for the request and response. 
- Adds possible response status codes (other than 5XX status codes)
If we're good with these two format changes, I'll update the status API as well in a follow up PR.
Change Preview:
https://consul-6041d885k-hashicorp.vercel.app/docs/nia/api/tasks
https://consul-6041d885k-hashicorp.vercel.app/docs/nia/cli/task

docs/nia: CTS delete task API and CLI

---

.changelog/11905.txt
ui/packages/consul-ui/app/components/data-loader/index.hbs

We recently updated a bug were in certain configurations you could log in but the view of data would not be refreshed/re-requested using the new token that you logged in with. Details in https://github.com/hashicorp/consul/pull/11681.
The approach in the mentioned PR was to use a client generated 401 error to cancel out all running blocking queries and immediately start them up again using the new token.
Unfortunately, on some pages where things can disappear whilst blocking on them (for instance a service might be deregistered whilst viewing the service detail page), we catch any errors and show a message saying the connection was lost for some reason. In some circumstances we get an error that we can safely ignore, and these are usually our client generated errors (such as our 429 …

ui: Ensure disconnect error doesn't appear w/auth change on some pages

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx

Changes:
- Update Catalog Services Condition configuration docs to new table format
- Rewrite `regexp` field docs to be required, no longer optional
- Remove details about `regexp` field's original default behavior when the
field was optional
Preview links: [configs](https://consul-o416vyf4s-hashicorp.vercel.app/docs/nia/configuration#catalog-services-condition), [removed tasks content](https://consul-o416vyf4s-hashicorp.vercel.app/docs/nia/tasks#catalog-services-condition)

docs/nia: require condition "catalog-services" block's regexp to be configured

---

.changelog/11931.txt
ui/packages/consul-ui/app/routing/route.js
ui/packages/consul-ui/app/services/routlet.js
ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
ui/packages/consul-ui/tests/acceptance/dc/kvs/edit.feature
ui/packages/consul-ui/tests/pages/dc/kv/edit.js

In 1.11.0/1 we moved our routing to use our Routlets almost entirely, but we missed moving the extra URL decoding for Ember Wildcard routes over to our routlet code that deals with URL params 😿 (Ember does not urlencode/urldecode wildcard routes by default)
This PR moves the code from our base Route (which all of our routes inherit from) over to our Routlet Service via a `normalizeParamsFor` method, which we then call from both our base Route and the Routlet Service. Whilst we barely use Ember Routes anymore, I left the required decoding in our base Route just incase it's required in future.
I'm a little surprised we had no acceptance test for this, so this fixes an unfortunate regression in 1.11.0/1 plus adds an acceptance test which would have caught this (and will catch it if it ever …

ui: Fix URL params decoding

---

ui/packages/consul-ui/app/components/code-editor/index.js
ui/packages/consul-ui/app/components/code-editor/skin.scss
ui/packages/consul-ui/app/instance-initializers/ivy-codemirror.js
ui/packages/consul-ui/app/services/code-mirror/linter.js
ui/packages/consul-ui/ember-cli-build.js
ui/packages/consul-ui/lib/startup/templates/body.html.js

Closes #6658
Add syntax highlighting for XML in Key/Value editor.
Screenshot for valid XML:
Screenshot for invalid XML:

ui: Add XML syntax highlighting to key/value editor

---

agent/consul/system_metadata_test.go

I think https://github.com/hashicorp/consul/pull/11796 was tested and merged without the changes from https://github.com/hashicorp/consul/pull/11798 as part of its base.
`TestLeader_SystemMetadata_CRUD` is run with with a server configured with `c.ConnectEnabled = false` but https://github.com/hashicorp/consul/pull/11798 moved the Virtual IP check to Leader goroutines which returns early if Connect is not enabled: https://github.com/hashicorp/consul/blob/ecbd3eb2a6c6ef09e4d19026f5e69efec568d7b4/agent/consul/leader_connect.go#L40-L52
This means the routine to check VirtualIPs is never run and we never set the VirtualIP metadata.
Could someone confirm that reverting this assertion makes sense? AFAIK Virtual IPs are only relevant for [Connect-capable …

testing: Revert assertion for virtual IP flag

---

.changelog/11335.txt
agent/agent_endpoint.go
agent/http.go
agent/http_test.go
api/agent.go

Relates to: #11258
To encode/decode the path params in HTTP API, we can use golang's `url.PathEscape` and `url.PathUnescape` methods.
url.PathEscape - PathEscape escapes the string so it can be safely placed inside a URL path segment, replacing special characters (including /) with %XX sequences as needed.

URL-encode/decode resource names for HTTP API

---

command/tls/cert/tls_cert.go

the usage example shows incorrect arguments for ca cert and key. the correct arguments are now -ca and -key

consul pls cert create usage example provided in CLI help shows outdated arguments

---

.changelog/11926.txt
command/acl/token/formatter.go
command/acl/token/testdata/FormatTokenList/complex.pretty-meta.golden
command/acl/token/testdata/FormatTokenList/complex.pretty.golden
website/content/commands/acl/token/list.mdx

Fix pretty CLI output of `consul acl token list` so that it properly displays node identities that are associated with a token.

cli: Show node identities in acl token list output

---

.changelog/10894.txt
agent/acl.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/consul/catalog_endpoint.go
agent/local/state.go
agent/local/state_test.go

Related to #10861.
Closes #9415.
Partial solution to #3122 (which also warrants a separate docs improvement).
Several practitioners had been confused by the `/agent/service/deregister/:service_id` endpoint (thinking it accepts name when it only accepts ID), and the resulting error message did not help them understand/fix the problem. This PR improves that error message. It also improves a related error message for health check endpoints.
Some examples of new error messages (as generated by the compiled `consul` dev binary):
```
$ curl --request GET http://127.0.0.1:8500/v1/agent/service/counting
Unknown service with ID "counting". Ensure that the service ID is passed, not the service name.
```
```
$ curl --request PUT http://127.0.0.1:8500/v1/agent/service/deregister/counting
Unknown …
```

Clarify service and health check not found error messages

---

.changelog/11905.txt
ui/packages/consul-ui/app/components/data-loader/index.hbs

Backport of https://github.com/hashicorp/consul/pull/11905
@amyrlam I just added you here as you did the original one, unfortunately the 1.9 backport didn't go cleanly due to some sort of template code change, but the changeset is simple enough so should just be a rubber stamp. Ty!

ui: [Backport/1.9.x] Ensure disconnect error doesn't appear w/auth change on some pages

---

ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs
ui/packages/consul-ui/app/abilities/partition.js

We have disabled partition creation on the backend if a user has more than one datacenter.
This PR reflects that in the UI by only showing the partition [Create] button if there is only one datacenter.
To share some thoughts/rationale here:
- The first API request we make is for a list of datacenters, before we even show you the UI.
- The list of datacenters is very unlikely to change without refreshing the UI, so I decided to use the EmberData cache seeing as we know we always have this list at the start (we have a thin 'repository' layer over Ember Data so we get this using EmberData's `peekAll`)
- There was a choice to pass the data into the ability via `can 'create partitions' dcs=(arrayOfDcs)` but I decided it would be better to inject the Datacenter Repository Service directly and …

ui: Only allow partition creation with a single datacenter setup

---

ui/packages/consul-ui/.dev.eslintrc.js
ui/packages/consul-ui/.eslintrc.js
ui/packages/consul-ui/app/locations/fsm-with-optional.js
ui/packages/consul-ui/app/services/auth-providers/oauth2-code-with-url-provider.js
ui/packages/consul-ui/package.json

Thankfully @amyrlam spotted this in a recent PR https://github.com/hashicorp/consul/pull/11900#discussion_r774261990 and this PR is off the back of that.
Back when we started in Ember 2.18 eslint tests would be run in the QUnit test runner along with the rest of our tests, initially this proved to be a little frustrating when trying to debug, create and fixup tests, as everytime you'd use a `console.log` statement somewhere a bunch more tests would fail confusing matters. Due to this we didn't add a no console rule to our eslint config, but instead kept a 'dev' eslint config that we could run separately containing a no-console rule. Nowadays we barely run this at all (and infact we commented it out quite a while back), but by chance we've been fairly good at keeping `console.log`s out of …

ui: Add selective no-console eslint rule

---

agent/acl_endpoint.go
agent/acl_endpoint_test.go
agent/agent_endpoint.go
agent/agent_endpoint_test.go
agent/http.go

issue #11393 
**Problem:**
There are several instances where handlers will write directly to ``resp`` instead of returning the appropriate error and letting the handler’s wrapper write the status code and body. As discussed, this is not optimal since there isn’t consistency which also affects how each function can be tested.
**Solution:** 
As discussed, I have begun changing some of these cases to use the created custom errors instead of writing directly to ``resp``. 
I was made aware that several unit tests check the response code, however we are transitioning to returning an error so the response code or body is never written. From my understanding there will be 2 approaches to testing with this new system.
1) Check the returned error type directly and ignore the response body or code. …

Ensure consistency with error-handling across all handlers.

---

.changelog/11924.txt
agent/proxycfg/manager.go
agent/proxycfg/manager_test.go
agent/proxycfg/state.go

reset `coalesceTimer` to nil as soon as the event is consumed

---

agent/local/state_test.go

Service ID representation in enterprise is different from OSS

Fix test for ENT

---

website/content/docs/k8s/installation/vault/gossip.mdx

The example Helm values file had the incorrect indent which was not properly setting the gossipEncyprtion key when using Vault as a secrets backend for Consul K8s.

docs: Fix indentation for gossipEncryption when using Vault secrets backend 

---

.changelog/11958.txt
go.mod
go.sum

This PR is to upgrade raft to v1.3.3 which will include https://github.com/hashicorp/raft/pull/483

upgrade raft to v1.3.3

---

.changelog/11940.txt
agent/agent_endpoint.go
agent/local/state.go
agent/local/state_test.go

This is a fix to the data race discovered in [here](https://app.circleci.com/pipelines/github/hashicorp/consul/25488/workflows/43e31311-9cf6-43d3-9eef-0eaef96be7ad/jobs/540392/tests)

clone the service under lock to avoid a data race

---

.changelog/11950.txt
agent/acl.go
agent/agent_endpoint_test.go

Update the `/agent/check/deregister/` API endpoint to return a 404 HTTP response code when an attempt is made to de-register a check ID that does not exist on the agent.
This brings the behavior of /agent/check/deregister/ inline with the behavior of /agent/service/deregister/ which was changed in #10632 to similarly return a 404 when de-registering non-existent services.
Fixes #5821

api: Return 404 when deregistering a non-existent check

---

.changelog/11960.txt
command/agent/agent.go
logging/logger.go

closes https://github.com/hashicorp/consul/issues/11773
Our logger uses [`io.MultiWriter`](https://pkg.go.dev/io#MultiWriter) which at minimum writes to `os.Stdout` and optionally to syslog or log file targets.
When Consul is run as a Windows Service, `os.Stdout` is not available and any writes by the logger fails silently, which inadvertently stopped writes to other targets because of `io.MultiWriter`'s behaviour:
```
If a listed writer returns an error, that overall write operation stops 
and returns the error; it does not continue down the list.
```
This PR uses a `noErrorWriter` wrapper which never returns an error so that even if writes to Stdout fail, writes to syslog and log file are unaffected.

Fix Windows logging to files

---

website/redirects.next.js

The mesh gateway docs at /docs/connect/gateways/mesh-gateway were moved in #11859 to a new location in order to accommodate the addition of separate instructions for using gateways with admin partitions.
This commit redirects the old mesh gateway page to its new location at /connect/gateways/mesh-gateway/service-to-service-traffic-datacenters.

docs: Redirect mesh-gateway page to new location

---

website/content/docs/nia/configuration.mdx
website/content/docs/nia/tasks.mdx

Doc updates:
- add new `source_includes_var` field to `condition "services"`
- change default value of `source_includes_var` from false to true
See commit messages for details on considerations for changes
links: [config changes](https://consul-51lz4jmt7-hashicorp.vercel.app/docs/nia/configuration#services-condition), [task execution changes](https://consul-51lz4jmt7-hashicorp.vercel.app/docs/nia/tasks#task-execution)

docs/nia - 'source_includes_var' changes

---

.changelog/11959.txt
ui/packages/consul-ui/app/components/consul/discovery-chain/skin.scss
ui/packages/consul-ui/app/components/topology-metrics/card/index.scss
ui/packages/consul-ui/app/components/topology-metrics/skin.scss

We recently noticed that our CSS compression seems to remove the odd border color when we compile up the UI for embedding in the binary. This results in some borders being a lot darker than they should be, but only once embedded in the binary/production (so not within our Ember development environment).
**Before:**
I noticed that just separating the `border-color` off from the shorthand `border` (which we do a lot anyway) seems to solve the issue without getting into too many ember-cli weeds. So this PR does that in the places I've noticed that are affected (topology and discovery chain visualizations), therefore fixing the issue and giving us time to figure out why this is happening if we want to do that (there's something to be said for just having a lint rule or something to make sure …

ui: Fix dark borders on certain visualizations

---

.changelog/11937.txt
ui/packages/consul-ui/app/templates/dc/services/show/intentions/edit.hbs
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions/create.feature
ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions/index.feature
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/intentions/create-steps.js
ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/intentions/index-steps.js
ui/packages/consul-ui/tests/helpers/type-to-url.js
ui/packages/consul-ui/tests/pages/dc/intentions/edit.js

We recently changed the intentions form to take a full model of a `dc` rather than just the string identifier (so `{Name: 'dc', Primary: true}` vs just `'dc'` in order to know whether the DC is the primary or not.
Unfortunately, we only did this on the global intentions page not the per service intentions page. This makes it impossible to save an intention from the per service intention page (whilst you can still save intentions from the global intention page as normal).
The fix here pretty much copy/pastes the approach taken in the global intention edit template over to the per service intention edit template.
Tests have been added for creation in the per service intention section, which again are pretty much just copied from the global one, unfortunately this didn't exist previously …

ui: [BUGFIX] Fixes an issue when editing intentions from the service > intentions sub tab

---

.changelog/11903.txt
ui/packages/consul-ui/app/components/outlet/index.js
ui/packages/consul-ui/app/components/route/index.hbs
ui/packages/consul-ui/app/components/route/index.js
ui/packages/consul-ui/app/filter/predicates/service-instance.js
ui/packages/consul-ui/app/helpers/merge-checks.js
ui/packages/consul-ui/app/models/proxy.js
ui/packages/consul-ui/app/models/service-instance.js
ui/packages/consul-ui/app/services/repository/proxy.js
ui/packages/consul-ui/app/services/repository/service-instance.js
ui/packages/consul-ui/app/services/routlet.js
ui/packages/consul-ui/app/templates/dc/services/instance.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/addresses.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/exposedpaths.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
ui/packages/consul-ui/docs/bookmarklets.mdx
ui/packages/consul-ui/mock-api/v1/catalog/connect/_
ui/packages/consul-ui/mock-api/v1/catalog/connect/backend
ui/packages/consul-ui/mock-api/v1/health/service/backend
ui/packages/consul-ui/mock-api/v1/health/service/backend-sidecar-proxy
ui/packages/consul-ui/tests/integration/services/routlet-test.js

Fixes https://github.com/hashicorp/consul/issues/11873
This PR is quite in-depth and there are a couple of things to understand here.
1. Routlet/Outlets/Routes - There is an RFC detailing this, ~I'll see if I can find the title here so folks can take a look if needed~ _CSL-164: Sharing data across Routes and Components in the Consul UI_. (Also _CSL-092 A componentized approach to data_, whilst not entirely necessary may also help here)
2. (Previous to this PR) Our approach to creating special munged together ProxyServiceInstances, which where a combination of the response from 2 endpoints - How we did this was the root of the issue here.
I've added quite a few inline comments and the link to the issue explains what the user facing problem/consequence was. But let me know if I can add any …

ui: Ensure service instance data does not get re-written on blocking refresh

---

.changelog/11968.txt
ui/packages/consul-ui/app/abilities/kv.js
ui/packages/consul-ui/app/services/repository/kv.js

Related to https://github.com/hashicorp/consul/issues/11098
This PR removes the KV pre-flight check to the internal authorization endpoint and instead relies on the response from the normal KV endpoint, thin client style.

ui: Remove KV pre-flight auth check

---

CHANGELOG.md

For the last two releases, we missed a step that would add the release's changelog notes back to the CHANGELOG.md on `main`. This adds them in a single PR (for simplicity). Each release is a separate commit if you want to review them separately.

Add missing entries to CHANGELOG.md

---

website/content/docs/connect/intentions.mdx

Noted that wildcards cannot be used as admin partition values when configuring intentions and made a few small improvements.

added line about wildcard intentions not supported for admin partitions

---

website/content/api-docs/kv.mdx
website/content/commands/kv/get.mdx
website/content/commands/kv/put.mdx

A handful of improvements to the KV API and CLI docs:
- Examples are now split into sections for easier scanability.
- `kv get` and `kv put` pages now call out their bulk equivalents.
- Clipboard has been hidden on example code snippets as the copied text isn't useful.

docs: kv doc improvements

---

website/content/api-docs/acl/index.mdx

hashicorp/consul#10612 added a `LastErrorMessage` field to the API response payload for the /acl/replication endpoint. Add this field to the API documentation.

Add LastErrorMessage to /acl/replication docs

---

website/content/docs/upgrading/instructions/upgrade-to-1-10-x.mdx
website/content/docs/upgrading/upgrade-specific.mdx

Also fixed a broken link in the 1.10.x upgrade instructions.
Live Docs Link to the new section: https://consul-oqyiiecv4-hashicorp.vercel.app/docs/upgrading/upgrade-specific#1-10-compatibility

Document Consul enterprise 1.10.0-1.10.4 forwards incompatibility with 1.11

---

website/content/docs/agent/options.mdx

Adding a small little note to the top of the 'command line options' section of this page following community feedback in https://github.com/hashicorp/consul/issues/10628

docs: clarify hcl/cli differences

---

.changelog/11979.txt
ui/packages/consul-ui/app/components/auth-form/index.hbs
ui/packages/consul-ui/app/components/token-source/README.mdx
ui/packages/consul-ui/app/components/token-source/index.hbs
ui/packages/consul-ui/app/serializers/oidc-provider.js
ui/packages/consul-ui/app/services/repository/oidc-provider.js
ui/packages/consul-ui/mock-api/v1/acl/oidc/callback
ui/packages/consul-ui/mock-api/v1/internal/ui/oidc-auth-methods
ui/packages/consul-ui/tests/acceptance/login.feature
ui/packages/consul-ui/tests/helpers/set-cookies.js
ui/packages/consul-ui/tests/helpers/type-to-url.js
ui/packages/consul-ui/tests/steps.js
ui/packages/consul-ui/tests/steps/doubles/http.js
ui/packages/consul-ui/tests/steps/doubles/model.js

There were a couple of places we'd missed adding the `partition` word to make sure that the partition is passed through to certain HTTP requests. This PR fixes those up.
Most of the code here is centered around testing this out in as close to e2e as possible, but I also took it for a spin with a Google OIDC provider and manually tested during our development environment with our fake OIDC provider. In all tests the correct partition is being appended to the HTTP API query params as expected.

ui: Ensure the partition is passed through to the request for the SSO auth URL

---

agent/acl_endpoint.go
agent/catalog_endpoint.go
agent/config_endpoint.go
agent/coordinate_endpoint.go
agent/discovery_chain_endpoint.go

This MR solves some parts of the issues in #11258. I intend to break it down into several smaller MRs to review those easily
Thanks @littlestar642 for his work . With #11335, we have with a generic function `getPathSuffixUnescaped` so I just apply it where necessary

URL-encode/decode resource names for HTTP API part 2

---

ui/packages/consul-ui/app/components/topology-metrics/card/index.hbs
ui/packages/consul-ui/app/components/topology-metrics/card/index.scss
ui/packages/consul-ui/app/components/topology-metrics/layout.scss
ui/packages/consul-ui/app/components/topology-metrics/skin.scss
ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
ui/packages/consul-ui/app/styles/base/icons/icon-placeholders.scss
ui/packages/consul-ui/mock-api/v1/internal/ui/service-topology/_

This PR adds Admin Partition to the Topology Metrics Card component. 
Conditionals cover the following scenarios:
- if any service on the page is in a different partition, all the cards show both partition and namespace.
- if all services on the page are in the same partition but have different namespaces, show the namespace label on the ones outside of the current namespace
[DEMO](https://consul-ui-staging-4llmogh9c-hashicorp.vercel.app/ui/dc1/services/service-5/topology)
No backend changes required.
Added `Partition` to the Upstream and Downstream services in the `service-topology` mock-api.
No testing added.

ui: Adding Partition to topology card

---

website/content/docs/connect/config-entries/service-resolver.mdx

This PR adds an example for a datacenter failover while using namespaces

docs: added another resolver example for DC and namespace failover

---

.changelog/11950.txt
agent/acl.go
agent/agent_endpoint_test.go

Manual backport of #11950 to release/1.11.x which failed to automatically cherry pick.

Backport #11950 to release/1.11.x

---

agent/local/state.go
agent/local/state_test.go

Dug into this test and found two races:
If a state sync is writing to `TaggedAddresses`
https://github.com/hashicorp/consul/blob/1eac39ae9c290431faf71e396559dc896d453436/agent/local/state.go#L1105
there is a chance that we are reading from the same map in a different goroutine:
https://github.com/hashicorp/consul/blob/1eac39ae9c290431faf71e396559dc896d453436/agent/agent_endpoint.go#L262-L264
Failed go-test-race [here](https://app.circleci.com/pipelines/github/hashicorp/consul/25488/workflows/43e31311-9cf6-43d3-9eef-0eaef96be7ad/jobs/540392/tests)
https://github.com/hashicorp/consul/pull/11940 was raised to fix this issue but I am reverting the changes because 1) it doesn't solve the concurrent map read+write; 2) it could potentially give a false sense of security; and 3) it seems to …

Fix races in anti-entropy tests

---

website/content/docs/k8s/operations/uninstall.mdx

Sometimes CRDs are not deleted since the finalizers don't fully complete execution. The added commands ensure that CRDs are deleted during the uninstall process. 
Sequence of operations
```
❯ export HELM_RELEASE=dyu
helm install ${HELM_RELEASE} hashicorp/consul --version "0.39.0" --create-namespace -n consul -f ./server-config.yaml
NAME: dyu
LAST DEPLOYED: Tue Jan 11 12:12:48 2022
NAMESPACE: consul
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing HashiCorp Consul!
Now that you have deployed Consul, you should look over the docs on using
Consul with Kubernetes available here:
https://www.consul.io/docs/platform/k8s/index.html
Your release is named dyu.
To learn more about the release, run:
$ helm status dyu
$ helm get all dyu
~/projects/consul1.11 1m 2s
❯ kubectl create ns …
```

docs: Update uninstall to ensure CRDs are deleted

---

website/content/docs/k8s/connect/connect-ca-provider.mdx

It is not clear that this page is to configure an external CA for Connect CA. Added line to clarify that this page is for configuring external CA's for the Connect CA. For the built-in CA, no config is needed.

Clarifies external CA config

---

ui/packages/consul-ui/docs/data-layer.mdx

First pass at adding some more generic Eng UI documentation for other folks working on the project. Specifically looking for feedback/questions from both folks who are familiar with this layer and folks who aren't.
[Preview link](https://consul-ui-staging-ljzxtsa8w-hashicorp.vercel.app/ui/docs/data-layer)
I added consul-ui as reviewer here, I think that covers everyone who would find this useful?

ui: First pass at writing some data layer related Eng docs

---

ui/packages/consul-acls/app/components/consul/acl/selector/README.mdx
ui/packages/consul-acls/app/components/consul/token/selector/README.mdx
ui/packages/consul-acls/app/components/consul/token/selector/index.hbs
ui/packages/consul-ui/.docfy-config.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs

Whilst working on https://github.com/hashicorp/consul/pull/11981 I added docs for the new TokenSelector and ACLSelector (which are mainly just wrapper components), I wasn't sure whether folks would prefer a separate PR so I decided to do this one separate.
There is one meaningful change here (which came to light due to writing the docs) in that previous we expected the user of the component to pass through a `@token` argument to AuthDialog (which then gets passed through to AuthProfile to show a truncated token.AccessorID.
As the AuthDialog component orchestrates the entire authorization dance (both for non-sso and sso flows) it reads and saves any user token changes and therefore knows about the token and 'exports'/yields it. Therefore I switched to use that reference to the `token` …

ui: Some ACL component documentation

---

ui/packages/consul-ui/app/components/app-view/layout.scss
ui/packages/consul-ui/app/styles/routes/dc/services/index.scss
ui/packages/consul-ui/app/templates/dc/services/show.hbs

Before:
After:
Please note: there is a purposeful very exact CSS selector being used here.
Please note, as we have undergone quite a lot of design change over the lifetime of the UI, we are building up to a more general "CSS trace" to bring a lot of things in line. That should be coming pretty soon and there will be updates to this area to go back to the large style buttons here plus some repositioning. That will be part of a larger PR though.
Oh, we also have a long term task to move all our `<a>` and `<button>`s to use `<Action>` which internally uses either `a` or `button` depending on whether you pass it a `@href` or not. So I took the opportunity to do that here also.
Backport-wise I'm guessing this should only go back to 1.10 at the earliest (as that was where we moved to the …

ui: Alter position of dashboard button in the service instance header

---

ui/packages/consul-acls/app/components/consul/acl/selector/README.mdx
ui/packages/consul-acls/app/components/consul/token/selector/README.mdx
ui/packages/consul-acls/app/components/consul/token/selector/index.hbs
ui/packages/consul-ui/.docfy-config.js
ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
ui/packages/consul-ui/tests/acceptance/navigation-links.feature

During https://github.com/hashicorp/consul/pull/11913 I noticed that I'd re-wired thing up slightly wrong (we added a wrapper component in that PR and it was rewired slightly wrong). I also used a `did-insert` helper which would not fire on `did-update` so I changed this to use our older `Ref` component which fires on insert and update.
The consequence of this bug was that our login button that appears in our empty state (which also opens the login modal) would be missing as in the EmptyState component (where this button is added) the button will only be added if the `open` property is defined. As I rewired it wrong open would be undefined and therefore the button would not show.
This bug is not currently in a release, and the original PR where it was introduced was only merged to `main` …

ui: Fix up wiring or empty state login button

---

.changelog/11985.txt
ui/packages/consul-ui/app/components/consul/intention/form/index.hbs

You cannot specify partitions whilst creating intentions if you are not in the primary datacenter.
Here we check to see if we have partitions enabled, then see if we are prohibited from 'choosing' them using our ability for partitions, in which case we show the notice which is just a simple-ish presentational component.
We only do this for the create screen, and as the `isManagedByCRDs` notice was intertwined with this conditional previously, we split that up here.

ui: Adds a notice for non-primary intention creation

---

website/content/docs/agent/options.mdx

Added in clarification on how autopilot uses min_quorum

docs: updated the description of min_quorum

---

agent/connect/ca/provider_consul_test.go
agent/connect/ca/testing.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/fsm/commands_oss.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/state/connect_ca.go
agent/structs/connect_ca.go
lib/routine/routine.go
testrpc/wait.go

Backport #11780, includes #11721 and baa2b8628e41ba577fb893ef490f16480b3f1dc4 to prevent most of the conflicts. Those 2 PRs are test-only changes, so should be safe.

[1.10.x] Backport CA and test fixes

---

agent/connect/ca/provider_consul_test.go
agent/connect/ca/testing.go
agent/consul/connect_ca_endpoint_test.go
agent/consul/fsm/commands_oss.go
agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_connect_test.go
agent/consul/state/connect_ca.go
agent/proxycfg/manager_test.go
agent/structs/connect_ca.go
testrpc/wait.go

Backport #11780, includes #11721 to prevent most of the conflicts. I couldn't take the extra commit #12037 because there were too many differences. So instead I l had to leave out the `leaderRoutine.Wait()` fix.

[1.9.x] Backport CA and test fixes

---

.changelog/12049.txt
agent/consul/leader_connect.go
agent/consul/leader_test.go
agent/consul/state/catalog.go
agent/consul/state/catalog_events.go
agent/consul/state/catalog_events_test.go
agent/consul/state/catalog_test.go
agent/structs/structs.go
agent/structs/system_metadata.go
agent/xds/listeners.go
agent/xds/listeners_test.go
agent/xds/testdata/listeners/transparent-proxy-terminating-gateway.envoy-1-20-x.golden

This PR adds support for connecting to services behind a terminating gateway when using a transparent proxy.

OSS: Add virtual IP generation for terminating gateway backed services

---

agent/consul/leader_connect_ca.go
agent/consul/leader_connect_ca_test.go
agent/consul/leader_metrics.go

This change is related to #11598, and #11159.  More detail in the commit messages, and I'll call out a few things below with inline comments.
The PR is not large, but it is still best viewed by individual commit, as there are a few independent changes, and the commit message has more context.
ActiveRoot should not be called from the secondary DC, because there should not be a requirement to run the same Vault instance in a secondary DC (#11159). `SignCertificate` is called in a secondary DC, so it should not call `Provider.ActiveRoot`. This PR removes that call.
We would also like to change the interface of `Provider.ActiveRoot` so that we can support using an intermediate cert as the primary CA in Consul (#11598). In preparation for making that change I am reducing the number of calls to …

ca: remove one call to Provider.ActiveRoot

---

website/content/docs/agent/config-entries.mdx
website/content/docs/agent/index.mdx
website/content/docs/agent/options.mdx
website/content/docs/agent/sentinel.mdx
website/content/docs/agent/telemetry.mdx

This PR is specifically for the [`agent` pages](https://www.consul.io/docs/agent) of the docs.
- Added `<CodeBlockConfig>` tags for code snippets with headings where applicable
- Added missing `$` to applicable shell-session examples

Update Web Components for Agent pages

---

website/data/commands-nav-data.json

Ensure `consul intention list` command is displayed in the navigation sidebar.
Fixes #12036

docs: Show `consul intention list` in nav sidebar

---

website/content/docs/upgrading/upgrade-specific.mdx

This just ensures we note that the right compatible 1.10 version for upgrades is 1.10.7 and not 1.10.6 as we found another issue in 1.10.6.

Updating the docs to point out that 1.10.7 should be used instead of 1.10.6

---

website/data/commands-nav-data.json

Manual backport of #12076 to 1.9.x.

[1.9.x] Backport docs change to show `consul intention list` in nav menu

---

CHANGELOG.md

Includes entries from [1.11.2](https://github.com/hashicorp/consul/releases/tag/v1.11.2), [1.10.7](https://github.com/hashicorp/consul/releases/tag/v1.10.7), and [1.9.14](https://github.com/hashicorp/consul/releases/tag/v1.9.14).

Add changelog from latest releases

---

CHANGELOG.md

I'm removing the `UNRELEASED` section here as it's misleading given we don't update it between releases.

Merg in changelog from 1.9.14

---

website/content/docs/connect/config-entries/ingress-gateway.mdx

Use plural form of "listeners", not possessive form of "listener's"

Minor grammar change to ingress-gateway.mdx

---

CHANGELOG.md
website/content/api-docs/acl/auth-methods.mdx
website/content/api-docs/acl/binding-rules.mdx
website/content/api-docs/acl/index.mdx
website/content/api-docs/acl/policies.mdx
website/content/api-docs/acl/roles.mdx
website/content/api-docs/acl/tokens.mdx
website/content/api-docs/admin-partitions.mdx
website/content/api-docs/agent/index.mdx
website/content/api-docs/agent/service.mdx
website/content/api-docs/catalog.mdx
website/content/api-docs/config.mdx
website/content/api-docs/connect/ca.mdx
website/content/api-docs/connect/intentions.mdx
website/content/api-docs/coordinate.mdx
website/content/api-docs/event.mdx
website/content/api-docs/kv.mdx
website/content/api-docs/namespaces.mdx
website/content/api-docs/operator/area.mdx
website/content/api-docs/operator/autopilot.mdx
website/content/api-docs/operator/keyring.mdx
website/content/api-docs/operator/license.mdx
website/content/api-docs/operator/raft.mdx
website/content/api-docs/snapshot.mdx
website/content/api-docs/status.mdx

As the title suggests, this docs changes is to include a link to the CLI command from the equivalent HTTP API page

Docs: Updating HTTP API endpoints with CLI equivalent links

---

.changelog/11335.txt
agent/agent_endpoint.go
agent/http.go
agent/http_test.go
api/agent.go

Backport https://github.com/hashicorp/consul/pull/11335 to 1.10.x.

[Backport 1.10.x] URL-encode/decode resource names for HTTP API

---

.changelog/11335.txt
agent/agent_endpoint.go
agent/http.go
agent/http_test.go
api/agent.go

[Backport 1.9.x] URL-encode/decode resource names for HTTP API

---

.changelog/12081.txt
ui/packages/consul-ui/app/components/consul/kv/form/index.hbs
ui/packages/consul-ui/app/services/repository/kv.js
ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
ui/packages/consul-ui/tests/acceptance/dc/kvs/create.feature

Fixes https://github.com/hashicorp/consul/issues/12073
See ^ for details.
The KV edit/form flow is one of our oldest form flows and it is currently a little bit of a mash up of mostly one of our old ways of doing forms with a tiny bit of cross over into our newer way of doing forms (the idea is soon to most entirely to new style forms the same as our namespace and partitions forms).
The fix here is two fold:
1. We shouldn't be providing the DataSource (which loads the data) with an id when we are creating from within a folder (in the buggy code we are providing the parentKey of the new KV you are creating)
2. Being able to provide an empty id to the DataSource/KV repository and that repository responding with a newly created object is more towards the "new way of doing forms", therefore …

ui: Fixup KV folder creation then further creation within that folder
